import {
  HeartPulse,
  Home,
  Building2,
  Flower2,
  FileText,
  ScrollText,
  FileCheck,
  Users,
  HandHelping,
  ClipboardList,
  Flag,
  Scale,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

export interface EolSubcategory {
  name: string;
  slug: string;
  icon: LucideIcon;
  description: string;
  keywords: string[];
}

export const EOL_SUBCATEGORIES: EolSubcategory[] = [
  {
    name: "Hospice & Palliative Care",
    slug: "hospice-palliative-care",
    icon: HeartPulse,
    description: "Comfort-focused care for serious illness and end of life",
    keywords: ["hospice", "palliative", "comfort care", "end of life care", "terminal"],
  },
  {
    name: "In-Home Care & Skilled Nursing",
    slug: "inhome-care-skilled-nursing",
    icon: Home,
    description: "Professional medical and personal care at home",
    keywords: ["home care", "home health", "skilled nursing", "in-home", "visiting nurse", "caregiver"],
  },
  {
    name: "Assisted Living & Nursing Homes",
    slug: "assisted-living-nursing-homes",
    icon: Building2,
    description: "Residential facilities for seniors and veterans",
    keywords: ["assisted living", "nursing home", "long-term care", "residential care", "veteran home", "senior living"],
  },
  {
    name: "Funeral & Burial Services",
    slug: "funeral-burial-services",
    icon: Flower2,
    description: "Funeral planning, burial, and cremation services",
    keywords: ["funeral", "burial", "cremation", "mortuary", "memorial"],
  },
  {
    name: "VA Death Benefits & Survivor Benefits",
    slug: "va-death-benefits-survivor-benefits",
    icon: FileText,
    description: "Federal benefits for surviving spouses, children, and dependents",
    keywords: ["death benefit", "survivor benefit", "DIC", "dependency indemnity", "burial allowance", "VA death"],
  },
  {
    name: "Wills, Estate Planning & Probate",
    slug: "wills-estate-planning-probate",
    icon: ScrollText,
    description: "Legal help for wills, trusts, and estate administration",
    keywords: ["will", "estate planning", "probate", "trust", "inheritance", "estate"],
  },
  {
    name: "Power of Attorney & Advance Directives",
    slug: "power-of-attorney-advance-directives",
    icon: FileCheck,
    description: "Legal documents for healthcare decisions and representation",
    keywords: ["power of attorney", "advance directive", "living will", "healthcare proxy", "POA", "DNR"],
  },
  {
    name: "Grief Counseling & Family Support",
    slug: "grief-counseling-family-support",
    icon: Users,
    description: "Emotional support for families and loved ones",
    keywords: ["grief", "bereavement", "counseling", "loss", "support group", "widow"],
  },
  {
    name: "Homebound Support & Daily Living",
    slug: "homebound-support-daily-living",
    icon: HandHelping,
    description: "Meals, transportation, and help with daily tasks",
    keywords: ["homebound", "meals on wheels", "daily living", "ADL", "home delivered meals", "companion"],
  },
  {
    name: "End-of-Life Care Planning",
    slug: "endoflife-care-planning",
    icon: ClipboardList,
    description: "Help creating a plan for care, finances, and family needs",
    keywords: ["care plan", "care planning", "end of life plan", "final arrangements", "advanced care"],
  },
  {
    name: "Veteran Funeral Honors & Cemetery Assistance",
    slug: "veteran-funeral-honors-cemetery-assistance",
    icon: Flag,
    description: "Military honors, national cemeteries, and headstones",
    keywords: ["funeral honors", "military honors", "national cemetery", "headstone", "flag", "burial flag", "veteran cemetery"],
  },
  {
    name: "Legal Help for Family & Final Affairs",
    slug: "legal-help-for-family-final-affairs",
    icon: Scale,
    description: "Attorneys and legal aid for end-of-life and survivor matters",
    keywords: ["legal help", "attorney", "legal aid", "final affairs", "survivor legal", "death certificate"],
  },
  {
    name: "Insurance & Financial Planning",
    slug: "insurance-financial-planning",
    icon: ShieldCheck,
    description: "Life insurance, burial insurance, and financial support for families",
    keywords: ["life insurance", "burial insurance", "final expense", "financial planning", "financial counseling", "estate financial", "SGLI", "VGLI"],
  },

  {
    name: "Caregiver Support",
    slug: "caregiver-support",
    icon: Users,
    description: "Programs that support family caregivers of aging or terminally ill veterans.",
    keywords: [],
  },
  {
    name: "Family Counseling",
    slug: "family-counseling",
    icon: Users,
    description: "Counseling for families navigating end-of-life decisions and grief together.",
    keywords: [],
  },
  {
    name: "Gold Star Family Support",
    slug: "gold-star-family-support",
    icon: Users,
    description: "Programs and benefits for surviving family of fallen service members.",
    keywords: [],
  },
  {
    name: "Survivor Benefits",
    slug: "survivor-benefits",
    icon: Users,
    description: "DIC, survivor pension, and other benefits available to surviving spouses and dependents.",
    keywords: [],
  },
  {
    name: "Survivor Benefits Support",
    slug: "survivor-benefits-support",
    icon: Users,
    description: "Help applying for and understanding survivor benefits.",
    keywords: [],
  },
  {
    name: "County Veterans Service Offices",
    slug: "county-veterans-service-offices",
    icon: Users,
    description: "Local county VSOs that assist with end-of-life claims, records, and survivor benefits.",
    keywords: [],
  },
  {
    name: "Disability Claims Assistance",
    slug: "disability-claims-assistance",
    icon: Users,
    description: "Help with disability claims connected to a veteran's final illness or service-connected condition.",
    keywords: [],
  },
  {
    name: "Pension Assistance",
    slug: "pension-assistance",
    icon: Users,
    description: "Pension and Aid & Attendance help during late-life care.",
    keywords: [],
  },
  {
    name: "Legal Aid Services",
    slug: "legal-aid-services",
    icon: Users,
    description: "Free or low-cost legal aid for end-of-life matters and family final affairs.",
    keywords: [],
  },
  {
    name: "Pro Bono Legal Services",
    slug: "pro-bono-legal-services",
    icon: Users,
    description: "Volunteer attorneys handling estate, probate, and survivor matters at no cost.",
    keywords: [],
  },
  {
    name: "Senior & Disabled Meal Programs",
    slug: "senior-disabled-meal-programs",
    icon: Users,
    description: "Meal delivery and nutrition programs for homebound elderly veterans.",
    keywords: [],
  },
  {
    name: "Veteran Outreach Programs",
    slug: "veteran-outreach-programs",
    icon: Users,
    description: "Outreach programs that connect aging and terminally ill veterans with services.",
    keywords: [],
  },
];
