/**
 * OHIO REBUILD — PHASE 1: STATE FOUNDATION
 * Florida SOP. Heavy statewide anchors. Hospital systems, university systems,
 * state agencies, statewide nonprofits. Builds ON TOP of existing 311 OH rows.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== HOSPITAL SYSTEMS — STATEWIDE (15) ==============
  { section: "HOSP", title: "OhioHealth — Statewide System", cat: "healthcare", sub: "Specialty Care", city: "Columbus", website_url: "https://www.ohiohealth.com/", source_name: "OhioHealth", source_type: "nonprofit", phone: "614-544-4636", address: "180 E Broad St, Columbus, OH 43215", zip: "43215", desc: "OhioHealth — faith-based nonprofit health system; 14 hospitals across central/SE Ohio (Riverside Methodist, Grant, Doctors, Dublin Methodist, Marion General, Mansfield, Shelby, MedCentral, O'Bleness Athens, Berger Lancaster, Hardin, Pickerington, Westerville, Marion). VA Choice/Community Care network." },
  { section: "HOSP", title: "ProMedica Health System", cat: "healthcare", sub: "Specialty Care", city: "Toledo", website_url: "https://www.promedica.org/", source_name: "ProMedica", source_type: "nonprofit", phone: "419-291-4000", address: "100 Madison Ave, Toledo, OH 43604", zip: "43604", desc: "ProMedica — integrated nonprofit health system in NW Ohio; Toledo Hospital, Toledo Children's, Bay Park, Flower, Defiance, Fostoria, Bixby, Herrick. VA Toledo CBOC partner; serves NW Ohio veterans." },
  { section: "HOSP", title: "Premier Health (Dayton)", cat: "healthcare", sub: "Specialty Care", city: "Dayton", website_url: "https://www.premierhealth.com/", source_name: "Premier Health", source_type: "nonprofit", phone: "937-208-2273", address: "110 N Main St Suite 1700, Dayton, OH 45402", zip: "45402", desc: "Premier Health — SW Ohio's largest health system; Miami Valley Hospital (Level I trauma), Atrium, Upper Valley, Miami Valley South. Wright-Patt AFB partner; Dayton VAMC Community Care network." },
  { section: "HOSP", title: "Mercy Health — Cincinnati", cat: "healthcare", sub: "Specialty Care", city: "Cincinnati", website_url: "https://www.mercy.com/", source_name: "Mercy Health (Bon Secours)", source_type: "nonprofit", phone: "513-952-5000", address: "1701 Mercy Health Pl, Cincinnati, OH 45237", zip: "45237", desc: "Mercy Health (Bon Secours Mercy Health) — Catholic health system; Anderson, Clermont, Fairfield, West, Kings Mills, Mercy Health-Lourdes; serves Cincinnati VAMC region veterans." },
  { section: "HOSP", title: "Kettering Health Network", cat: "healthcare", sub: "Specialty Care", city: "Kettering", website_url: "https://ketteringhealth.org/", source_name: "Kettering Health", source_type: "nonprofit", phone: "844-211-5482", address: "3535 Southern Blvd, Kettering, OH 45429", zip: "45429", desc: "Kettering Health — 14-hospital nonprofit network in SW Ohio; Kettering Main, Sycamore, Soin, Greene, Grandview, Hamilton, Troy, Piqua, Defiance, Dayton Heart. Wright-Patt AFB & Dayton VAMC referral partner." },
  { section: "HOSP", title: "Mount Carmel Health System", cat: "healthcare", sub: "Specialty Care", city: "Columbus", website_url: "https://www.mountcarmelhealth.com/", source_name: "Mount Carmel Health (Trinity Health)", source_type: "nonprofit", phone: "614-234-5000", address: "6001 E Broad St, Columbus, OH 43213", zip: "43213", desc: "Mount Carmel Health System — Catholic Trinity Health affiliate in central Ohio; Mount Carmel East, West, St. Ann's, Grove City, Lewis Center. Wylie OPC referral partner; serves central OH veterans." },
  { section: "HOSP", title: "TriHealth (Cincinnati)", cat: "healthcare", sub: "Specialty Care", city: "Cincinnati", website_url: "https://www.trihealth.com/", source_name: "TriHealth", source_type: "nonprofit", phone: "513-569-1900", address: "619 Oak St, Cincinnati, OH 45206", zip: "45206", desc: "TriHealth — joint venture of Catholic Health Initiatives & Bethesda Inc.; Bethesda North, Good Samaritan, Bethesda Butler, McCullough-Hyde Memorial. Cincinnati VAMC Community Care network." },
  { section: "HOSP", title: "The Christ Hospital Health Network", cat: "healthcare", sub: "Specialty Care", city: "Cincinnati", website_url: "https://www.thechristhospital.com/", source_name: "The Christ Hospital", source_type: "nonprofit", phone: "513-585-2000", address: "2139 Auburn Ave, Cincinnati, OH 45219", zip: "45219", desc: "The Christ Hospital — independent Cincinnati nonprofit; cardiovascular & cancer center of excellence; serves Cincinnati VAMC referral veterans for specialty care via VA Community Care." },
  { section: "HOSP", title: "Aultman Health Foundation (Canton)", cat: "healthcare", sub: "Specialty Care", city: "Canton", website_url: "https://www.aultman.org/", source_name: "Aultman Hospital", source_type: "nonprofit", phone: "330-452-9911", address: "2600 6th St SW, Canton, OH 44710", zip: "44710", desc: "Aultman Hospital — Stark County's largest hospital; Aultman Main, Aultman Orrville, Aultman North, Aultman Tuslaw. Canton VA OPC Community Care partner." },
  { section: "HOSP", title: "Genesis HealthCare System (Zanesville)", cat: "healthcare", sub: "Specialty Care", city: "Zanesville", website_url: "https://www.genesishcs.org/", source_name: "Genesis HealthCare System", source_type: "nonprofit", phone: "740-454-4000", address: "2951 Maple Ave, Zanesville, OH 43701", zip: "43701", desc: "Genesis HealthCare System — Muskingum/SE Ohio anchor hospital; Zanesville VA OPC Community Care partner serving SE OH veterans." },
  { section: "HOSP", title: "Adena Health System (Chillicothe)", cat: "healthcare", sub: "Specialty Care", city: "Chillicothe", website_url: "https://www.adena.org/", source_name: "Adena Health", source_type: "nonprofit", phone: "740-779-7500", address: "272 Hospital Rd, Chillicothe, OH 45601", zip: "45601", desc: "Adena Health System — south-central Ohio hospital network; Adena Regional Medical Center co-located with Chillicothe VAMC; major Community Care provider for Appalachian OH veterans." },
  { section: "HOSP", title: "MetroHealth System (Cleveland)", cat: "healthcare", sub: "Specialty Care", city: "Cleveland", website_url: "https://www.metrohealth.org/", source_name: "MetroHealth System", source_type: "public_university", phone: "216-778-7800", address: "2500 MetroHealth Dr, Cleveland, OH 44109", zip: "44109", desc: "MetroHealth System — Cuyahoga County public hospital; Level I trauma center, polytrauma rehab; Cleveland VAMC Community Care partner; serves uninsured/underinsured veterans." },
  { section: "HOSP", title: "Akron Children's Hospital", cat: "healthcare", sub: "Specialty Care", city: "Akron", website_url: "https://www.akronchildrens.org/", source_name: "Akron Children's", source_type: "nonprofit", phone: "330-543-1000", address: "1 Perkins Sq, Akron, OH 44308", zip: "44308", desc: "Akron Children's Hospital — pediatric anchor for NE Ohio; serves children of veteran families; TRICARE & VA Community Care pediatric specialty referrals." },
  { section: "HOSP", title: "Nationwide Children's Hospital (Columbus)", cat: "healthcare", sub: "Specialty Care", city: "Columbus", website_url: "https://www.nationwidechildrens.org/", source_name: "Nationwide Children's", source_type: "nonprofit", phone: "614-722-2000", address: "700 Children's Dr, Columbus, OH 43205", zip: "43205", desc: "Nationwide Children's Hospital — top-10 US pediatric hospital; serves children of central Ohio veterans/military; TRICARE & VA Community Care pediatric specialty network." },
  { section: "HOSP", title: "Cleveland Clinic Akron General", cat: "healthcare", sub: "Specialty Care", city: "Akron", website_url: "https://www.akrongeneral.org/", source_name: "Cleveland Clinic Akron General", source_type: "nonprofit", phone: "330-344-6000", address: "1 Akron General Ave, Akron, OH 44307", zip: "44307", desc: "Cleveland Clinic Akron General — Summit County anchor; Akron VA OPC Community Care partner; Level I trauma; serves Akron-Canton veterans for specialty care." },

  // ============== PUBLIC UNIVERSITIES — VETERAN SERVICES (12) ==============
  { section: "EDU", title: "Ohio State University Office of Military and Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Columbus", website_url: "https://veterans.osu.edu/", source_name: "Ohio State University", source_type: "public_university", phone: "614-247-8387", address: "Student Academic Services Bldg, 281 W Lane Ave, Columbus, OH 43210", zip: "43210", desc: "Ohio State Office of Military & Veterans Services — Ohio's flagship; serves 1,500+ student veterans/dependents; GI Bill/VR&E SCOs, Yellow Ribbon Program, Veterans Resource Center, dedicated military-credit policy, and veteran success coaches." },
  { section: "EDU", title: "Ohio University Veterans & Military Student Services Center", cat: "education", sub: "Veteran Student Services", city: "Athens", website_url: "https://www.ohio.edu/", source_name: "Ohio University", source_type: "public_university", phone: "740-593-1819", address: "Baker University Center 350, Athens, OH 45701", zip: "45701", desc: "Ohio University Veterans & Military Student Services Center — Athens campus serving Appalachian OH veterans; SCOs, Yellow Ribbon, Veterans Lounge in Baker Center, VA work-study, and partnership with Athens VA OPC." },
  { section: "EDU", title: "Kent State University Center for Adult and Veteran Services", cat: "education", sub: "Veteran Student Services", city: "Kent", website_url: "https://www.kent.edu/cavs", source_name: "Kent State University", source_type: "public_university", phone: "330-672-7933", address: "181 Schwartz Center, Kent, OH 44242", zip: "44242", desc: "Kent State Center for Adult & Veteran Services — Portage County anchor university; SCOs, Yellow Ribbon, Veterans Resource Center, Student Veteran Association chapter, and military credit articulation." },
  { section: "EDU", title: "Miami University Office of the Veterans Resource Coordinator", cat: "education", sub: "Veteran Student Services", city: "Oxford", website_url: "https://miamioh.edu/", source_name: "Miami University", source_type: "public_university", phone: "513-529-1809", address: "501 E High St, Oxford, OH 45056", zip: "45056", desc: "Miami University Veterans Resource Coordinator — Butler County public university; SCOs, Yellow Ribbon, Veteran Bridge Mentoring, Student Veteran Organization, and military credit evaluation for SW OH veterans." },
  { section: "EDU", title: "University of Toledo Office of Military & Veteran Affairs", cat: "education", sub: "Veteran Student Services", city: "Toledo", website_url: "https://www.utoledo.edu/", source_name: "University of Toledo", source_type: "public_university", phone: "419-530-1392", address: "2801 W Bancroft St, Toledo, OH 43606", zip: "43606", desc: "University of Toledo Office of Military & Veteran Affairs — NW Ohio; SCOs, Yellow Ribbon, Veterans Lounge, military-credit transcript review, and VR&E onsite counseling for Toledo VA CBOC referrals." },
  { section: "EDU", title: "Youngstown State University Office of Veterans Affairs", cat: "education", sub: "Veteran Student Services", city: "Youngstown", website_url: "https://ysu.edu/veterans-affairs", source_name: "Youngstown State University", source_type: "public_university", phone: "330-941-2503", address: "1 University Plaza, Youngstown, OH 44555", zip: "44555", desc: "YSU Office of Veterans Affairs — Mahoning Valley anchor; SCOs, Yellow Ribbon, Veterans Resource Center, military-credit articulation, and Youngstown VA OPC partner for tuition assistance & GI Bill processing." },
  { section: "EDU", title: "Shawnee State University Veteran & Military Services", cat: "education", sub: "Veteran Student Services", city: "Portsmouth", website_url: "https://www.shawnee.edu/", source_name: "Shawnee State University", source_type: "public_university", phone: "740-351-3251", address: "940 2nd St, Portsmouth, OH 45662", zip: "45662", desc: "Shawnee State University — Scioto County public university serving south-central OH veterans; SCOs, Yellow Ribbon Program, Veterans Lounge, and Portsmouth VA OPC partner." },
  { section: "EDU", title: "Central State University Office of Veteran Services", cat: "education", sub: "Veteran Student Services", city: "Wilberforce", website_url: "https://www.centralstate.edu/", source_name: "Central State University", source_type: "public_university", phone: "937-376-6011", address: "1400 Brush Row Rd, Wilberforce, OH 45384", zip: "45384", desc: "Central State University — Ohio's only public HBCU (Greene County); SCOs, Yellow Ribbon, dedicated student veteran advisor, and Wright-Patt/Dayton VAMC referral partner." },
  { section: "EDU", title: "Cleveland State University Veterans Resource Center", cat: "education", sub: "Veteran Student Services", city: "Cleveland", website_url: "https://www.csuohio.edu/", source_name: "Cleveland State University", source_type: "public_university", phone: "216-687-2127", address: "2121 Euclid Ave, Cleveland, OH 44115", zip: "44115", desc: "Cleveland State University Veterans Resource Center — Cuyahoga County public university serving 600+ student veterans; SCOs, Yellow Ribbon, Vet Lounge, and Cleveland VAMC GI Bill partner." },
  { section: "EDU", title: "OSU Newark Campus — Adult & Military Services", cat: "education", sub: "Veteran Student Services", city: "Newark", website_url: "https://newark.osu.edu/", source_name: "Ohio State University Newark", source_type: "public_university", phone: "740-366-9333", address: "1179 University Dr, Newark, OH 43055", zip: "43055", desc: "Ohio State Newark — regional OSU campus serving Licking County student veterans; SCOs, GI Bill processing, Yellow Ribbon, and military credit articulation." },
  { section: "EDU", title: "OSU Mansfield Campus — Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Mansfield", website_url: "https://mansfield.osu.edu/", source_name: "Ohio State University Mansfield", source_type: "public_university", phone: "419-755-4011", address: "1760 University Dr, Mansfield, OH 44906", zip: "44906", desc: "Ohio State Mansfield — regional OSU campus serving Richland/Crawford/Ashland student veterans; SCOs, GI Bill processing, Yellow Ribbon Program." },
  { section: "EDU", title: "OSU Lima Campus — Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Lima", website_url: "https://lima.osu.edu/", source_name: "Ohio State University Lima", source_type: "public_university", phone: "419-995-8600", address: "4240 Campus Dr, Lima, OH 45804", zip: "45804", desc: "Ohio State Lima — regional OSU campus serving Allen/Auglaize/Putnam/Hardin/Van Wert student veterans; SCOs, GI Bill processing, Yellow Ribbon." },

  // ============== COMMUNITY COLLEGES — VETERAN SERVICES (10) ==============
  { section: "EDU", title: "Lakeland Community College Veteran Services (Kirtland)", cat: "education", sub: "Veteran Student Services", city: "Kirtland", website_url: "https://www.lakelandcc.edu/", source_name: "Lakeland Community College", source_type: "community_college", phone: "440-525-7000", address: "7700 Clocktower Dr, Kirtland, OH 44094", zip: "44094", desc: "Lakeland Community College Veteran Services — Lake County CC; SCOs, GI Bill/VR&E processing, Yellow Ribbon, and Cleveland VAMC referral partner for veterans pursuing trades & academic transfer." },
  { section: "EDU", title: "Stark State College Veterans Resource Center (North Canton)", cat: "education", sub: "Veteran Student Services", city: "North Canton", website_url: "https://www.starkstate.edu/", source_name: "Stark State College", source_type: "community_college", phone: "330-494-6170", address: "6200 Frank Ave NW, North Canton, OH 44720", zip: "44720", desc: "Stark State College Veterans Resource Center — Stark County CC; SCOs, Yellow Ribbon, VRC lounge, military-credit evaluation, and Canton VA OPC partner for trades certifications." },
  { section: "EDU", title: "Cincinnati State Technical and Community College Veteran Services", cat: "education", sub: "Veteran Student Services", city: "Cincinnati", website_url: "https://www.cincinnatistate.edu/", source_name: "Cincinnati State", source_type: "community_college", phone: "513-569-1500", address: "3520 Central Pkwy, Cincinnati, OH 45223", zip: "45223", desc: "Cincinnati State Veteran Services — SW Ohio CC; SCOs, Yellow Ribbon, Veterans Lounge, accelerated technical programs, and Cincinnati VAMC VR&E partner." },
  { section: "EDU", title: "Hocking College Veterans Resource Center (Nelsonville)", cat: "education", sub: "Veteran Student Services", city: "Nelsonville", website_url: "https://www.hocking.edu/", source_name: "Hocking College", source_type: "community_college", phone: "740-753-3591", address: "3301 Hocking Pkwy, Nelsonville, OH 45764", zip: "45764", desc: "Hocking College Veterans Resource Center — Athens-area CC; SCOs, GI Bill, Yellow Ribbon, residential campus, vocational/trades focus, and Athens VA OPC partner." },
  { section: "EDU", title: "Edison State Community College Veterans Services (Piqua)", cat: "education", sub: "Veteran Student Services", city: "Piqua", website_url: "https://www.edisonohio.edu/", source_name: "Edison State Community College", source_type: "community_college", phone: "937-778-8600", address: "1973 Edison Dr, Piqua, OH 45356", zip: "45356", desc: "Edison State Community College — Miami County CC; SCOs, Yellow Ribbon, GI Bill processing, and Wright-Patt AFB military credit articulation for SW OH veterans." },
  { section: "EDU", title: "Eastern Gateway Community College Veteran Services (Steubenville)", cat: "education", sub: "Veteran Student Services", city: "Steubenville", website_url: "https://egcc.edu/", source_name: "Eastern Gateway Community College", source_type: "community_college", phone: "740-264-5591", address: "4000 Sunset Blvd, Steubenville, OH 43952", zip: "43952", desc: "Eastern Gateway Community College — Jefferson County CC serving E OH/Ohio Valley; SCOs, Yellow Ribbon, Veterans Lounge, and Pittsburgh VAMC partner for cross-state veterans." },
  { section: "EDU", title: "Marion Technical College Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Marion", website_url: "https://www.mtc.edu/", source_name: "Marion Technical College", source_type: "community_college", phone: "740-389-4636", address: "1467 Mt Vernon Ave, Marion, OH 43302", zip: "43302", desc: "Marion Technical College — Marion County CC co-located with OSU Marion; SCOs, Yellow Ribbon, technical degrees & nursing, and Marion-area veteran outreach." },
  { section: "EDU", title: "Clark State College Veterans Affairs (Springfield)", cat: "education", sub: "Veteran Student Services", city: "Springfield", website_url: "https://www.clarkstate.edu/", source_name: "Clark State College", source_type: "community_college", phone: "937-325-0691", address: "570 E Leffel Ln, Springfield, OH 45505", zip: "45505", desc: "Clark State College Veterans Affairs — Clark County CC; SCOs, Yellow Ribbon, GI Bill/VR&E, and Wright-Patt/Dayton VAMC referral partner." },

  // ============== STATE AGENCIES (8) ==============
  { section: "STATE", title: "Ohio Attorney General — Consumer Protection & Crime Victim Services", cat: "legal", sub: "Legal Aid Services", city: "Columbus", website_url: "https://www.ohioattorneygeneral.gov/", source_name: "Ohio Attorney General", source_type: "state_agency", phone: "800-282-0515", address: "30 E Broad St 14th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Attorney General — Consumer Protection Section (scams targeting veterans), Crime Victim Services (compensation up to $50K for OH veterans victimized by crime), and Veterans Initiative (predatory-claims advisor watchdog). Statewide hotline." },

  // ============== STATEWIDE NONPROFITS / FAITH NETWORKS (12) ==============
  { section: "NPO", title: "Salvation Army Ohio Division Headquarters", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://centralusa.salvationarmy.org/", source_name: "Salvation Army Ohio Division", source_type: "nonprofit", phone: "614-358-0386", address: "P.O. Box 1325, Columbus, OH 43216", zip: "43216", desc: "Salvation Army Ohio Division HQ — Eastern Territorial division covering all 88 OH counties through 50+ corps community centers; emergency assistance, transitional housing, addiction recovery (Adult Rehabilitation Centers in Cleveland & Cincinnati), disaster response, and veteran outreach." },
  { section: "NPO", title: "Catholic Charities Diocese of Toledo", cat: "community-support", sub: "Veteran Outreach Programs", city: "Toledo", website_url: "https://www.catholiccharitiesnwo.org/", source_name: "Catholic Charities Diocese of Toledo", source_type: "nonprofit", phone: "419-244-6711", address: "1933 Spielbusch Ave, Toledo, OH 43604", zip: "43604", desc: "Catholic Charities Diocese of Toledo — covers 19 NW OH counties; refugee resettlement, adoption services, disability services, food pantries, family counseling, and emergency assistance for veteran households." },
  { section: "NPO", title: "Catholic Charities Diocese of Youngstown", cat: "community-support", sub: "Veteran Outreach Programs", city: "Youngstown", website_url: "https://www.ccdoy.org/", source_name: "Catholic Charities Diocese of Youngstown", source_type: "nonprofit", phone: "330-744-8451", address: "319 W Rayen Ave, Youngstown, OH 44502", zip: "44502", desc: "Catholic Charities Diocese of Youngstown — covers 6 NE OH counties (Mahoning, Trumbull, Columbiana, Stark, Portage, Ashtabula); food pantries, behavioral health, refugee services, emergency assistance for veterans." },
  { section: "NPO", title: "Catholic Charities Southwestern Ohio", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cincinnati", website_url: "https://www.ccswoh.org/", source_name: "Catholic Charities SW Ohio", source_type: "nonprofit", phone: "513-241-7745", address: "100 E Eighth St, Cincinnati, OH 45202", zip: "45202", desc: "Catholic Charities SW Ohio — Cincinnati Archdiocese coverage; refugee resettlement, mental health counseling, family stabilization, su Casa Hispanic Center, and emergency rent/utility for veteran households." },
  { section: "NPO", title: "Lutheran Social Services of Central Ohio", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "http://www.lssco.org/", source_name: "Lutheran Social Services of Central Ohio", source_type: "nonprofit", phone: "614-228-5200", address: "750 E Long St Suite 2300, Columbus, OH 43203", zip: "43203", desc: "Lutheran Social Services of Central Ohio — central OH human services; food pantries (Faith Mission), housing, behavioral health, CHOICES DV shelter for women, and refugee services. Cross-faith partner for veteran families." },
  { section: "NPO", title: "Jewish Family Services of Columbus", cat: "family-support", sub: "Family Counseling", city: "Columbus", website_url: "https://www.jfscolumbus.org/", source_name: "Jewish Family Services of Columbus", source_type: "nonprofit", phone: "614-231-1890", address: "1070 College Ave, Columbus, OH 43209", zip: "43209", desc: "Jewish Family Services of Columbus — interfaith human services; counseling, career services, refugee resettlement, food pantry, older adult services. Serves all faiths; partners with central OH veteran families." },
  { section: "NPO", title: "Jewish Family Service of Cincinnati", cat: "family-support", sub: "Family Counseling", city: "Cincinnati", website_url: "https://www.jfscinti.org/", source_name: "Jewish Family Service of Cincinnati", source_type: "nonprofit", phone: "513-469-1188", address: "8487 Ridge Rd, Cincinnati, OH 45236", zip: "45236", desc: "Jewish Family Service of Cincinnati — interfaith human services in SW OH; counseling, career resource center, kosher food pantry, senior services, and Heart-to-Heart in-home senior care. Serves all faiths." },
  { section: "NPO", title: "Jewish Family Service Association of Cleveland", cat: "family-support", sub: "Family Counseling", city: "Cleveland", website_url: "https://www.jfsa-cleveland.org/", source_name: "Jewish Family Service Association of Cleveland", source_type: "nonprofit", phone: "216-378-3000", address: "29125 Chagrin Blvd, Pepper Pike, OH 44122", zip: "44122", desc: "Jewish Family Service Association of Cleveland — Cuyahoga County interfaith human services; counseling, vocational services, kosher meals on wheels, refugee resettlement, and Holocaust Survivor Services. Serves all faiths." },
  { section: "NPO", title: "Goodwill Industries of Central & Southern Ohio", cat: "employment", sub: "Job Placement Programs", city: "Columbus", website_url: "https://www.goodwillcolumbus.org/", source_name: "Goodwill Columbus", source_type: "nonprofit", phone: "614-294-5181", address: "1331 Edgehill Rd, Columbus, OH 43212", zip: "43212", desc: "Goodwill Industries of Central & Southern Ohio — covers 21 central/southern OH counties; vocational rehab, job placement, retail training, ARC industries (developmental disabilities), and dedicated veteran career navigators." },
  { section: "NPO", title: "Goodwill Industries of Greater Cleveland & East Central Ohio", cat: "employment", sub: "Job Placement Programs", city: "Canton", website_url: "https://www.goodwillgoodskills.org/", source_name: "Goodwill Industries of GCEC", source_type: "nonprofit", phone: "330-445-9000", address: "408 9th St SW, Canton, OH 44707", zip: "44707", desc: "Goodwill Industries of Greater Cleveland & East Central Ohio — covers Stark, Carroll, Wayne, Tuscarawas, Holmes, Coshocton, Harrison, Jefferson, Belmont counties; job training, disability employment, retail stores, and veteran job placement." },

  // ============== STATEWIDE LEGAL / CIVIL ANCHORS (5) ==============
  { section: "LEG", title: "Ohio Legal Help (Statewide Self-Help Portal)", cat: "legal", sub: "Legal Aid Services", city: "Columbus", website_url: "https://www.ohiolegalhelp.org/", source_name: "Ohio Legal Help", source_type: "nonprofit", phone: "614-389-9774", address: "Statewide online — admin Columbus, OH", zip: "43215", desc: "Ohio Legal Help — statewide free legal self-help portal launched 2019 by OH Access to Justice Foundation; do-it-yourself forms, plain-language guides on housing/family/consumer/veteran issues, and direct referrals to all 6 OH legal aid orgs." },
  { section: "LEG", title: "Legal Aid Society of Cleveland", cat: "legal", sub: "Civil Legal Aid", city: "Cleveland", website_url: "https://lasclev.org/", source_name: "Legal Aid Society of Cleveland", source_type: "nonprofit", phone: "888-817-3777", address: "1223 W 6th St, Cleveland, OH 44113", zip: "44113", desc: "Legal Aid Society of Cleveland — civil legal aid for low-income residents of Ashtabula, Cuyahoga, Geauga, Lake, and Lorain counties; housing, family, consumer, public benefits, and Medical-Legal Partnership with Cleveland VAMC." },
  { section: "LEG", title: "Southeastern Ohio Legal Services (SEOLS)", cat: "legal", sub: "Civil Legal Aid", city: "Athens", website_url: "http://www.seols.org/", source_name: "Southeastern Ohio Legal Services", source_type: "nonprofit", phone: "740-594-3558", address: "1 N Court St Suite 530, Athens, OH 45701", zip: "45701", desc: "Southeastern Ohio Legal Services — covers 30 Appalachian OH counties from 9 branch offices (Athens, Marietta, Newark, Steubenville, New Philadelphia, Zanesville, Portsmouth, Jackson, Cambridge); civil legal aid including veteran advocacy and Athens VA OPC partner." },

  // ============== HUNGER / FOODBANK NETWORK (5) ==============
  { section: "FOOD", title: "Greater Cleveland Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Cleveland", website_url: "https://www.greaterclevelandfoodbank.org/", source_name: "Greater Cleveland Food Bank", source_type: "nonprofit", phone: "216-738-2265", address: "13815 Coit Rd, Cleveland, OH 44110", zip: "44110", desc: "Greater Cleveland Food Bank — Feeding America hub for Cuyahoga, Ashtabula, Geauga, Lake, Richland, Ashland counties; 1,000+ partner agencies, mobile pantries, SNAP outreach, and Cleveland VAMC produce-prescription partner." },
  { section: "FOOD", title: "Shared Harvest Foodbank (Fairfield)", cat: "food-assistance", sub: "Food Banks", city: "Fairfield", website_url: "https://sharedharvest.org/", source_name: "Shared Harvest Foodbank", source_type: "nonprofit", phone: "513-874-0114", address: "5901 Dixie Hwy, Fairfield, OH 45014", zip: "45014", desc: "Shared Harvest Foodbank — Feeding America hub for Butler, Hamilton, Preble, Warren, Darke counties; 200+ partner pantries, mobile food pantries, BackPack Buddies, and Operation Veteran Care monthly veteran food box distribution." },
  { section: "FOOD", title: "Southeast Ohio Foodbank (Logan)", cat: "food-assistance", sub: "Food Banks", city: "Logan", website_url: "https://www.hapcap.org/southeast-ohio-foodbank/", source_name: "Southeast Ohio Foodbank (HAPCAP)", source_type: "nonprofit", phone: "740-385-6813", address: "30 W Sugar Run Rd, Logan, OH 43138", zip: "43138", desc: "Southeast Ohio Foodbank — operated by Hocking Athens Perry CAP; serves 10 Appalachian counties (Athens, Hocking, Perry, Vinton, Meigs, Morgan, Washington, Noble, Monroe, Belmont) including high-need veteran rural population." },

  // ============== SENIOR / AGING NETWORK (4) ==============
  { section: "AGE", title: "Central Ohio Area Agency on Aging (COAAA)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Columbus", website_url: "https://www.coaaa.org/", source_name: "COAAA", source_type: "nonprofit", phone: "614-645-7250", address: "3776 S High St, Columbus, OH 43207", zip: "43207", desc: "Central Ohio Area Agency on Aging (COAAA) — PSA 6 covering Franklin, Delaware, Fairfield, Fayette, Licking, Madison, Pickaway, Union; PASSPORT Medicaid waiver, Senior Options, Caregiver Support, Long-Term Care Ombudsman for elderly veterans." },
  { section: "AGE", title: "Area Agency on Aging Region 9 (Cambridge)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Cambridge", website_url: "https://www.aaa9.org/", source_name: "Area Agency on Aging Region 9", source_type: "nonprofit", phone: "740-439-4478", address: "60788 Southgate Rd, Byesville, OH 43723", zip: "43723", desc: "Area Agency on Aging Region 9 — covers 9 SE OH Appalachian counties (Belmont, Carroll, Coshocton, Guernsey, Harrison, Holmes, Jefferson, Muskingum, Tuscarawas); PASSPORT Medicaid waiver, in-home services, congregate meals for elderly veterans." },
  { section: "AGE", title: "AARP Ohio State Office", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Columbus", website_url: "https://states.aarp.org/ohio/", source_name: "AARP Ohio", source_type: "nonprofit", phone: "866-389-5653", address: "17 S High St Suite 800, Columbus, OH 43215", zip: "43215", desc: "AARP Ohio — state office advocating for Ohioans 50+; AARP Tax-Aide free tax prep at 200+ OH sites, AARP Driver Safety Course, fraud watch (predatory veteran-claims advisor scams), and statewide caregiver supports." },
];

runSeed(ROWS, { state: "OH", commit: COMMIT, scriptName: "seed-oh-rebuild-p1.ts" });
