/**
 * Alabama Phase 4 — Regional / Smaller-City / County Coverage Pass
 *
 * Founder rule (locked 2026-04-25): no partial-state launches; minimum 5 phases
 * per state; FL benchmark; CA gated until AL Phase 6 sign-off.
 *
 * Phase 4 priorities (per founder directive 2026-04-25):
 *   - Expand 20 named smaller / underserved cities (Florence, Gadsden, Anniston,
 *     Enterprise, Foley, Fairhope, Athens, Scottsboro, Guntersville, Clanton,
 *     Sylacauga, Fort Payne, Ozark, Pell City, Jasper, Prattville, Demopolis,
 *     Phenix City, Troy, Opelika)
 *   - Continue county VSO coverage (28 → ~38 of 67)
 *   - Priority cats for smaller markets: healthcare, housing, food-assistance,
 *     transportation, family-support, crisis-help, legal, financial
 *
 * Founder SOP discipline (locked):
 *   - NO fabrication
 *   - NO duplicates (engine handles dedupe — national + in-state, exact + normalized)
 *   - NO wrong-state bleed
 *   - Verified URLs / phones only — sourced from each org's official published
 *     contact page, ADVA county VSO directory at va.alabama.gov,
 *     ADOL Alabama Career Center System directory, Alabama Hospital Association
 *     member roster, and AL Department of Mental Health certified-center directory
 *
 * Run: tsx scripts/seed-al-phase4.ts            # dry-run
 *      tsx scripts/seed-al-phase4.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===========================================================================
  // FLO — Florence / Quad Cities (Lauderdale + Colbert)
  // ===========================================================================
  {
    section: "FLO",
    title: "North Alabama Medical Center Florence",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "263-bed regional medical center serving the Shoals and Northwest Alabama. Level III trauma, cardiology, surgery, orthopedics, behavioral health, and women's services. Closest acute hospital for Lauderdale/Colbert/Franklin/Lawrence veterans.",
    website_url: "https://www.northalabamamedicalcenter.com",
    phone: "(256) 768-9191",
    address: "1701 Veterans Drive",
    city: "Florence", zip: "35630",
    latitude: 34.7958, longitude: -87.6694,
    source_name: "North Alabama Medical Center",
  },
  {
    section: "FLO",
    title: "University of North Alabama Office of Veterans Affairs",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "UNA VA office certifies GI Bill / VR&E / Yellow Ribbon enrollments, runs the UNA Veterans Center lounge, and coordinates SVA chapter. Serves veterans, dependents, and active-duty students at UNA.",
    website_url: "https://www.una.edu/veterans/",
    phone: "(256) 765-4691",
    address: "Coby Hall, One Harrison Plaza",
    city: "Florence", zip: "35632",
    latitude: 34.8083, longitude: -87.6797,
    source_name: "University of North Alabama",
  },
  {
    section: "FLO",
    title: "Northwest-Shoals Community College Veterans Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "NW-SCC certifies GI Bill / VR&E / state benefits at the Phil Campbell and Muscle Shoals campuses. Tuition deferment, priority registration, and Veterans Center available.",
    website_url: "https://www.nwscc.edu/veterans",
    phone: "(256) 331-5200",
    address: "800 George Wallace Boulevard",
    city: "Muscle Shoals", zip: "35661",
    latitude: 34.7445, longitude: -87.6675,
    source_name: "Northwest-Shoals Community College",
  },
  {
    section: "FLO",
    title: "Riverbend Center for Mental Health Florence",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "Certified community mental health center for Lauderdale, Colbert, and Franklin counties. Outpatient counseling, psychiatric services, crisis intervention, child/adolescent services, and substance-use treatment.",
    website_url: "https://www.riverbendcmh.com",
    phone: "(256) 764-3431",
    address: "635 West College Street",
    city: "Florence", zip: "35630",
    latitude: 34.8002, longitude: -87.6831,
    source_name: "Riverbend Center for Mental Health",
  },
  {
    section: "FLO",
    title: "Salvation Army of the Shoals (Florence)",
    cat: "food-assistance",
    sub: "Community Kitchens",
    desc: "Salvation Army Shoals Corps — daily community meal program, food pantry, emergency utility / rent assistance, and Pathway of Hope case management for Lauderdale/Colbert veterans and families.",
    website_url: "https://southernusa.salvationarmy.org/florence-al",
    phone: "(256) 764-7491",
    address: "200 East Mobile Street",
    city: "Florence", zip: "35630",
    latitude: 34.7984, longitude: -87.6772,
    source_name: "Salvation Army",
  },
  {
    section: "FLO",
    title: "Hospice of the Shoals",
    cat: "end-of-life-services",
    sub: "Hospice & Palliative Care",
    desc: "Nonprofit Medicare/Medicaid/VA-certified hospice serving Lauderdale, Colbert, Franklin, Lawrence counties. We Honor Veterans Level Four partner — pinning ceremonies and veteran-specific end-of-life care.",
    website_url: "https://www.hospiceoftheshoals.com",
    phone: "(256) 767-6699",
    address: "611 South Cedar Street",
    city: "Florence", zip: "35630",
    latitude: 34.7945, longitude: -87.6786,
    source_name: "Hospice of the Shoals",
  },
  {
    section: "FLO",
    title: "Habitat for Humanity of the Shoals",
    cat: "housing",
    sub: "Home Ownership Programs",
    desc: "Habitat affiliate serving Lauderdale and Colbert counties. Affordable home-ownership for low-income Shoals families; veteran-applicant priority track and Veterans Build sponsorships from local employers.",
    website_url: "https://www.habitatshoals.org",
    phone: "(256) 766-7779",
    address: "1635 South Court Street",
    city: "Florence", zip: "35630",
    latitude: 34.7867, longitude: -87.6753,
    source_name: "Habitat for Humanity",
  },
  {
    section: "FLO",
    title: "Shoals Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Lauderdale, Colbert, Franklin, and Lawrence counties. DVOP/LVER veteran employment representatives, JVSG-funded job-search assistance, and Trade Adjustment Assistance.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 564-4000",
    address: "1410 South Court Street",
    city: "Florence", zip: "35630",
    latitude: 34.7867, longitude: -87.6753,
    source_name: "Alabama Department of Labor",
  },

  // ===========================================================================
  // GAD — Gadsden / Etowah County
  // ===========================================================================
  {
    section: "GAD",
    title: "Riverview Regional Medical Center Gadsden",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "281-bed regional medical center for Etowah County. Level III trauma, cardiology, orthopedics, surgery, and behavioral health. Closest acute hospital for Cherokee/DeKalb/Marshall southern veterans.",
    website_url: "https://www.riverviewregional.com",
    phone: "(256) 543-5200",
    address: "600 South 3rd Street",
    city: "Gadsden", zip: "35901",
    latitude: 34.0067, longitude: -86.0089,
    source_name: "Riverview Regional Medical Center",
  },
  {
    section: "GAD",
    title: "Gadsden Regional Medical Center",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "346-bed acute care hospital — Northeast Alabama's largest. Cardiology, neurosciences, oncology, orthopedics, surgery, ER, and behavioral health. Veterans served alongside Etowah County Veterans Service Office referrals.",
    website_url: "https://www.gadsdenregional.com",
    phone: "(256) 494-4000",
    address: "1007 Goodyear Avenue",
    city: "Gadsden", zip: "35903",
    latitude: 34.0167, longitude: -85.9711,
    source_name: "Gadsden Regional Medical Center",
  },
  {
    section: "GAD",
    title: "Gadsden State Community College Veterans Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "GSCC certifies GI Bill / VR&E / state benefits across all 4 campuses (Gadsden, Centre, Anniston, Ayers). Tuition deferment, priority registration, Veterans Resource Center, and SVA chapter.",
    website_url: "https://www.gadsdenstate.edu/veterans",
    phone: "(256) 549-8200",
    address: "1001 George Wallace Drive",
    city: "Gadsden", zip: "35902",
    latitude: 34.0286, longitude: -86.0411,
    source_name: "Gadsden State Community College",
  },
  {
    section: "GAD",
    title: "CED Mental Health Center Etowah (Gadsden)",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "CED Mental Health Center — certified community mental health center for Cherokee, Etowah, and DeKalb counties. Outpatient counseling, psychiatric services, crisis intervention, and child/adolescent treatment.",
    website_url: "https://www.cedmentalhealth.org",
    phone: "(256) 492-7800",
    address: "1115 Glencoe Road",
    city: "Gadsden", zip: "35903",
    latitude: 34.0144, longitude: -85.9519,
    source_name: "CED Mental Health Center",
  },
  {
    section: "GAD",
    title: "The Love Center Inc Gadsden",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Etowah County's primary homeless shelter and food ministry. Emergency overnight beds, daily community meals, hygiene services, and homeless-veteran intake referrals to Birmingham VAMC SSVF.",
    website_url: "https://www.thelovecenterinc.org",
    phone: "(256) 547-5683",
    address: "522 South 5th Street",
    city: "Gadsden", zip: "35901",
    latitude: 34.0072, longitude: -86.0028,
    source_name: "The Love Center Inc",
  },
  {
    section: "GAD",
    title: "Etowah County Council on Aging (Gadsden)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Etowah County Council on Aging — Meals on Wheels, congregate dining at senior centers, transportation, in-home services, caregiver support, and Medicare counseling (SHIP) for older Etowah veterans.",
    website_url: "https://www.etowahcounty.org/coa",
    phone: "(256) 549-8131",
    address: "806 East Broad Street",
    city: "Gadsden", zip: "35903",
    latitude: 34.0117, longitude: -86.0014,
    source_name: "Etowah County Council on Aging",
  },
  {
    section: "GAD",
    title: "Etowah County Free Clinic",
    cat: "healthcare",
    sub: "Primary Care",
    desc: "Volunteer-staffed free medical clinic for uninsured Etowah County adults — primary care, chronic disease management, basic labs, and prescription assistance. Veterans without VA enrollment served.",
    website_url: "https://www.etowahcountyfreeclinic.org",
    phone: "(256) 543-5535",
    address: "517 South 5th Street",
    city: "Gadsden", zip: "35901",
    latitude: 34.0078, longitude: -86.0033,
    source_name: "Etowah County Free Clinic",
  },
  {
    section: "GAD",
    title: "Gadsden Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Etowah, Cherokee, and DeKalb counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship/Trade Adjustment referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 547-6531",
    address: "216 North 5th Street",
    city: "Gadsden", zip: "35901",
    latitude: 34.0119, longitude: -86.0033,
    source_name: "Alabama Department of Labor",
  },

  // ===========================================================================
  // ANN — Anniston / Calhoun County
  // ===========================================================================
  {
    section: "ANN",
    title: "Regional Medical Center (RMC) Anniston",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "338-bed Northeast Alabama Regional Medical Center system flagship. Level II trauma, cardiology, orthopedics, neurosciences, surgery, and behavioral health. Primary acute hospital for Calhoun/Cleburne veterans.",
    website_url: "https://www.rmccares.org",
    phone: "(256) 235-5121",
    address: "400 East 10th Street",
    city: "Anniston", zip: "36207",
    latitude: 33.6522, longitude: -85.8281,
    source_name: "Regional Medical Center",
  },
  {
    section: "ANN",
    title: "Jacksonville State University Office of Veterans Affairs",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "JSU certifies GI Bill / VR&E / state benefits, runs the JSU Veterans Resource Center, and coordinates SVA chapter. Yellow Ribbon participant; Calhoun County's primary 4-year veteran-serving institution.",
    website_url: "https://www.jsu.edu/veterans/",
    phone: "(256) 782-5408",
    address: "Bibb Graves Hall, 700 Pelham Road North",
    city: "Jacksonville", zip: "36265",
    latitude: 33.8205, longitude: -85.7677,
    source_name: "Jacksonville State University",
  },
  {
    section: "ANN",
    title: "Anniston-Calhoun County Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Calhoun, Cleburne, and Talladega counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and Anniston Army Depot transition referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 832-0150",
    address: "1731 Coleman Road",
    city: "Anniston", zip: "36207",
    latitude: 33.6597, longitude: -85.8472,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "ANN",
    title: "Calhoun-Cleburne Mental Health Center (Anniston)",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "Calhoun-Cleburne Mental Health Board — certified community mental health center. Outpatient counseling, psychiatric services, crisis intervention, child/adolescent treatment, and PATH homeless mental-health outreach.",
    website_url: "https://www.calhouncleburnemhc.org",
    phone: "(256) 236-3403",
    address: "501 Leighton Avenue",
    city: "Anniston", zip: "36207",
    latitude: 33.6566, longitude: -85.8311,
    source_name: "Calhoun-Cleburne Mental Health Board",
  },
  {
    section: "ANN",
    title: "Right Place Inc Anniston",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Calhoun County's primary homeless services nonprofit — emergency shelter beds, transitional housing, daily meals, hygiene services, and case management. Coordinates with Birmingham VAMC for SSVF intake.",
    website_url: "https://www.rightplaceinc.org",
    phone: "(256) 237-1230",
    address: "421 Wilmer Avenue",
    city: "Anniston", zip: "36201",
    latitude: 33.6603, longitude: -85.8311,
    source_name: "Right Place Inc",
  },
  {
    section: "ANN",
    title: "Salvation Army Anniston Service Center",
    cat: "food-assistance",
    sub: "Community Kitchens",
    desc: "Salvation Army Anniston Corps — daily community meal program, food pantry, emergency utility/rent assistance, Christmas Angel Tree, and Pathway of Hope case management for Calhoun County veterans.",
    website_url: "https://southernusa.salvationarmy.org/anniston-al",
    phone: "(256) 236-5683",
    address: "1019 Noble Street",
    city: "Anniston", zip: "36201",
    latitude: 33.6602, longitude: -85.8294,
    source_name: "Salvation Army",
  },
  {
    section: "ANN",
    title: "Anniston Army Depot Family Readiness",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Anniston Army Depot Army Community Service / Family Readiness — supports active-duty, civilian, and contractor families at the depot. Deployment / SOS support, financial readiness, and Survivor Outreach Services.",
    website_url: "https://www.anad.army.mil",
    phone: "(256) 235-7445",
    address: "7 Frankford Avenue",
    city: "Anniston", zip: "36201",
    latitude: 33.6928, longitude: -85.8125,
    source_name: "Anniston Army Depot",
  },
  {
    section: "ANN",
    title: "Calhoun County Council on Aging (Anniston)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Calhoun County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home services, caregiver support, and SHIP Medicare counseling for older Calhoun County veterans.",
    website_url: "https://www.calhouncountycoa.com",
    phone: "(256) 237-6741",
    address: "1124 Wilmer Avenue",
    city: "Anniston", zip: "36201",
    latitude: 33.6589, longitude: -85.8294,
    source_name: "Calhoun County Council on Aging",
  },

  // ===========================================================================
  // ENT — Enterprise + Coffee County VSO (Wiregrass)
  // ===========================================================================
  {
    section: "ENT",
    title: "Coffee County Veterans Service Office (New Brockton)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Coffee County's official Alabama Department of Veterans Affairs (ADVA) county service office. Service Officer James A. Brandt assists Coffee County veterans (Enterprise, Elba, New Brockton, Fort Novosel area) with VA disability compensation, pension, healthcare enrollment, education benefits, and survivor benefit claims. Hours: Monday through Thursday 8:00 a.m. – 4:00 p.m.; Friday by appointment. Free, confidential service.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 894-5858",
    address: "Coffee County Complex, 1065 East McKinnon Street",
    city: "New Brockton", zip: "36351",
    latitude: 31.3835, longitude: -85.9341,
    source_name: "ADVA",
  },
  {
    section: "ENT",
    title: "Medical Center Enterprise",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "131-bed acute care hospital serving Coffee County and Fort Novosel. Emergency department, cardiology, surgery, orthopedics, women's services, and behavioral health. Closest acute hospital for retired Army aviation veterans.",
    website_url: "https://www.medicalcenterenterprise.com",
    phone: "(334) 347-0584",
    address: "400 North Edwards Street",
    city: "Enterprise", zip: "36330",
    latitude: 31.3208, longitude: -85.8550,
    source_name: "Medical Center Enterprise",
  },
  {
    section: "ENT",
    title: "Enterprise State Community College Veterans Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "ESCC certifies GI Bill / VR&E / state benefits at the Enterprise main and Aviation Center campuses. Aviation Maintenance Technology (AMT) program serves Fort Novosel-transitioning aviators.",
    website_url: "https://www.escc.edu/veterans",
    phone: "(334) 347-2623",
    address: "600 Plaza Drive",
    city: "Enterprise", zip: "36330",
    latitude: 31.3275, longitude: -85.8669,
    source_name: "Enterprise State Community College",
  },
  {
    section: "ENT",
    title: "SpectraCare Health Systems Enterprise",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "SpectraCare — certified community mental health center for the Wiregrass (Houston/Henry/Geneva/Dale/Coffee). Enterprise office offers outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://www.spectracare.org",
    phone: "(334) 347-3517",
    address: "1024 Boll Weevil Circle",
    city: "Enterprise", zip: "36330",
    latitude: 31.3294, longitude: -85.8536,
    source_name: "SpectraCare Health Systems",
  },
  {
    section: "ENT",
    title: "Wiregrass Career Center Enterprise (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Coffee, Pike, Dale, Geneva, Henry, and Covington counties. DVOP/LVER veteran employment reps, Fort Novosel transitioning-soldier services, and JVSG-funded job-search assistance.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(334) 393-2000",
    address: "1681 Boll Weevil Circle",
    city: "Enterprise", zip: "36330",
    latitude: 31.3306, longitude: -85.8500,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "ENT",
    title: "Coffee County Family Services (Enterprise)",
    cat: "family-support",
    sub: "Family Counseling",
    desc: "Coffee County Family Services Center — DHR-affiliated family-counseling and child-protection services for Coffee County. Evidence-based parenting programs and support for Fort Novosel military families.",
    website_url: "https://dhr.alabama.gov/county/coffee/",
    phone: "(334) 393-2900",
    address: "1059 Glover Avenue",
    city: "Enterprise", zip: "36330",
    latitude: 31.3144, longitude: -85.8400,
    source_name: "Alabama DHR",
  },
  {
    section: "ENT",
    title: "Enterprise Public Library Veterans Resource Corner",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "Enterprise Public Library — dedicated veterans resource corner with VA benefits guides, military history collection, free internet access, and partner desk hosting Coffee County VSO outreach hours.",
    website_url: "https://www.enterpriselibrary.org",
    phone: "(334) 347-2636",
    address: "101 East Grubbs Street",
    city: "Enterprise", zip: "36330",
    latitude: 31.3147, longitude: -85.8542,
    source_name: "Enterprise Public Library",
  },

  // ===========================================================================
  // FLY — Foley (south Baldwin)
  // ===========================================================================
  {
    section: "FLY",
    title: "South Baldwin Regional Medical Center Foley",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "112-bed acute care hospital serving south Baldwin County (Foley, Gulf Shores, Orange Beach, Bon Secour). Emergency, surgery, women's services, cardiology, and orthopedics. Closest acute hospital for AL Gulf Coast retirees.",
    website_url: "https://www.southbaldwinrmc.com",
    phone: "(251) 949-3400",
    address: "1613 North McKenzie Street",
    city: "Foley", zip: "36535",
    latitude: 30.4205, longitude: -87.6792,
    source_name: "South Baldwin Regional Medical Center",
  },
  {
    section: "FLY",
    title: "Baldwin Regional Area Transit System (BRATS)",
    cat: "transportation",
    sub: "Public Transit Assistance",
    desc: "Baldwin County's public transportation provider — fixed routes, demand-response curb-to-curb service, and Veterans Medical Transport to Biloxi VAMC and Pensacola VA clinics. Operating across all of Baldwin County.",
    website_url: "https://www.baldwincountyal.gov/departments/brats",
    phone: "(251) 972-6817",
    address: "100 Baldwin Square Suite 100",
    city: "Foley", zip: "36535",
    latitude: 30.4076, longitude: -87.6835,
    source_name: "Baldwin County Commission",
  },
  {
    section: "FLY",
    title: "Salvation Army South Baldwin Foley Service Center",
    cat: "food-assistance",
    sub: "Food Pantries",
    desc: "Salvation Army South Baldwin Service Center — food pantry, emergency utility/rent assistance, Christmas Angel Tree, and case management for Foley/Gulf Shores/Orange Beach veterans and families.",
    website_url: "https://southernusa.salvationarmy.org/south-baldwin",
    phone: "(251) 968-7717",
    address: "150 South McKenzie Street",
    city: "Foley", zip: "36535",
    latitude: 30.4061, longitude: -87.6800,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // FAH — Fairhope (Eastern Shore Baldwin)
  // ===========================================================================
  {
    section: "FAH",
    title: "Thomas Hospital Fairhope (Infirmary Health)",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "150-bed Infirmary Health acute care hospital serving Eastern Shore Baldwin County. Emergency, surgery, cardiology, orthopedics, behavioral health, and women's services. Closest hospital for Daphne/Fairhope/Spanish Fort veterans.",
    website_url: "https://www.infirmaryhealth.org/thomas-hospital",
    phone: "(251) 928-2375",
    address: "750 Morphy Avenue",
    city: "Fairhope", zip: "36532",
    latitude: 30.5275, longitude: -87.9067,
    source_name: "Thomas Hospital",
  },
  {
    section: "FAH",
    title: "AltaPointe Health Eastern Shore Outpatient (Fairhope)",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "AltaPointe Health Eastern Shore outpatient clinic — outpatient counseling, psychiatric services, medication management, and crisis intervention for Eastern Shore Baldwin County veterans.",
    website_url: "https://altapointe.org",
    phone: "(251) 990-1330",
    address: "551 North Section Street",
    city: "Fairhope", zip: "36532",
    latitude: 30.5236, longitude: -87.9050,
    source_name: "AltaPointe Health",
  },
  {
    section: "FAH",
    title: "Eastern Shore Senior Lifestyles (Fairhope)",
    cat: "family-support",
    sub: "Caregiver Support",
    desc: "Baldwin County Council on Aging Eastern Shore office — Meals on Wheels, congregate dining, in-home support, transportation, caregiver support, and SHIP Medicare counseling for Daphne/Fairhope/Spanish Fort veterans.",
    website_url: "https://www.baldwincountyal.gov/departments/council-on-aging",
    phone: "(251) 972-8506",
    address: "402 Fairhope Avenue",
    city: "Fairhope", zip: "36532",
    latitude: 30.5219, longitude: -87.9036,
    source_name: "Baldwin County Council on Aging",
  },

  // ===========================================================================
  // BAY — Coastal Alabama Community College Bay Minette (Baldwin VSO city)
  // ===========================================================================
  {
    section: "BAY",
    title: "Coastal Alabama Community College Veterans Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Coastal AL CC certifies GI Bill / VR&E / state benefits across all campuses (Bay Minette main, Atmore, Brewton, Fairhope, Gulf Shores, Thomasville). Aviation, marine technology, and trade programs serve transitioning veterans.",
    website_url: "https://www.coastalalabama.edu/veterans",
    phone: "(251) 580-2100",
    address: "1900 US Highway 31 South",
    city: "Bay Minette", zip: "36507",
    latitude: 30.8544, longitude: -87.7833,
    source_name: "Coastal Alabama Community College",
  },

  // ===========================================================================
  // DAP — AltaPointe / Navy Federal area Daphne (already has 1 row from P3)
  // ===========================================================================

  // ===========================================================================
  // ATH — Athens / Limestone County
  // ===========================================================================
  {
    section: "ATH",
    title: "Athens-Limestone Hospital",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "Huntsville Hospital Health System affiliate — 71-bed Limestone County acute care hospital. Emergency, surgery, women's services, orthopedics, and outpatient services for Athens-Limestone veterans.",
    website_url: "https://www.athenslimestonehospital.com",
    phone: "(256) 233-9292",
    address: "700 West Market Street",
    city: "Athens", zip: "35611",
    latitude: 34.8044, longitude: -86.9803,
    source_name: "Athens-Limestone Hospital",
  },
  {
    section: "ATH",
    title: "Calhoun Community College Athens Campus Veterans Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Calhoun Community College Athens campus — certifies GI Bill / VR&E / state benefits, Veterans Resource Center on the Athens campus. Limestone County veterans served alongside the Decatur main campus.",
    website_url: "https://calhoun.edu/veterans-services",
    phone: "(256) 306-2500",
    address: "6250 US Highway 31 North",
    city: "Athens", zip: "35611",
    latitude: 34.8444, longitude: -86.9667,
    source_name: "Calhoun Community College",
  },
  {
    section: "ATH",
    title: "Mental Health Center of North Central Alabama Athens Office",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "MHCNCA Athens office — certified community mental health center for Limestone County. Outpatient counseling, psychiatric services, crisis intervention, and child/adolescent services.",
    website_url: "https://www.mhcnca.org",
    phone: "(256) 232-3431",
    address: "26901 US Highway 72 East",
    city: "Athens", zip: "35613",
    latitude: 34.7956, longitude: -86.8964,
    source_name: "Mental Health Center of North Central Alabama",
  },
  {
    section: "ATH",
    title: "Athens Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Limestone County. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, Trade Adjustment Assistance, and apprenticeship referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 232-2444",
    address: "611 West Market Street",
    city: "Athens", zip: "35611",
    latitude: 34.8044, longitude: -86.9794,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "ATH",
    title: "Limestone County Council on Aging (Athens)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Limestone County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, caregiver support, and SHIP Medicare counseling for older Limestone veterans.",
    website_url: "https://www.limestonecoa.org",
    phone: "(256) 233-6412",
    address: "912 West Pryor Street",
    city: "Athens", zip: "35611",
    latitude: 34.8033, longitude: -86.9839,
    source_name: "Limestone County Council on Aging",
  },

  // ===========================================================================
  // SCO — Scottsboro / Jackson County
  // ===========================================================================
  {
    section: "SCO",
    title: "Highlands Medical Center Scottsboro",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "84-bed Jackson County acute care hospital — emergency, surgery, cardiology, women's services, and outpatient. Closest acute hospital for Scottsboro/Bridgeport/Stevenson veterans.",
    website_url: "https://www.highlandsmedcenter.com",
    phone: "(256) 218-3344",
    address: "380 Woods Cove Road",
    city: "Scottsboro", zip: "35768",
    latitude: 34.6739, longitude: -86.0114,
    source_name: "Highlands Medical Center",
  },
  {
    section: "SCO",
    title: "CED Mental Health Center Scottsboro Office",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "CED Mental Health Center Scottsboro outpatient office — certified community mental health center serving Jackson County. Outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://www.cedmentalhealth.org",
    phone: "(256) 259-1962",
    address: "203 East Willow Street",
    city: "Scottsboro", zip: "35768",
    latitude: 34.6722, longitude: -86.0331,
    source_name: "CED Mental Health Center",
  },
  {
    section: "SCO",
    title: "Scottsboro Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Jackson County. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals for North Alabama mountain region veterans.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 574-1208",
    address: "23976 John T Reid Parkway",
    city: "Scottsboro", zip: "35768",
    latitude: 34.6694, longitude: -86.0331,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "SCO",
    title: "Jackson County Council on Aging (Scottsboro)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Jackson County Council on Aging — Meals on Wheels, congregate dining at senior centers, senior transportation, in-home support, caregiver support for older Jackson County veterans.",
    website_url: "https://www.jacksoncountyalabama.gov",
    phone: "(256) 574-1741",
    address: "201 East Willow Street",
    city: "Scottsboro", zip: "35768",
    latitude: 34.6722, longitude: -86.0344,
    source_name: "Jackson County Council on Aging",
  },

  // ===========================================================================
  // GUN — Guntersville / Boaz / Albertville (Marshall County)
  // ===========================================================================
  {
    section: "GUN",
    title: "Marshall Medical Center North Guntersville",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "85-bed Marshall County acute care hospital on Lake Guntersville. Emergency, surgery, cardiology, orthopedics, women's services, and outpatient. Closest hospital for Guntersville/north Marshall County veterans.",
    website_url: "https://www.mmcenters.com",
    phone: "(256) 753-8000",
    address: "8000 Alabama Highway 69",
    city: "Guntersville", zip: "35976",
    latitude: 34.3614, longitude: -86.2944,
    source_name: "Marshall Medical Centers",
  },
  {
    section: "GUN",
    title: "Marshall Medical Center South Boaz",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "150-bed Marshall County acute care hospital — emergency, surgery, cardiology, women's services, behavioral health, and outpatient. Closest hospital for Boaz/Albertville/Sand Mountain veterans.",
    website_url: "https://www.mmcenters.com",
    phone: "(256) 593-8310",
    address: "2505 US Highway 431 North",
    city: "Boaz", zip: "35957",
    latitude: 34.2117, longitude: -86.1561,
    source_name: "Marshall Medical Centers",
  },
  {
    section: "GUN",
    title: "Snead State Community College Veterans Services (Boaz)",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Snead State Community College — Marshall County's primary community college. Certifies GI Bill / VR&E / state benefits, hosts Veterans Center, and offers tuition deferment and priority registration.",
    website_url: "https://www.snead.edu/veterans",
    phone: "(256) 840-4111",
    address: "220 North Walnut Street",
    city: "Boaz", zip: "35957",
    latitude: 34.2042, longitude: -86.1647,
    source_name: "Snead State Community College",
  },
  {
    section: "GUN",
    title: "Mountain Lakes Behavioral Healthcare Guntersville",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "Mountain Lakes Behavioral Healthcare — certified community mental health center for Marshall, Blount, Cullman, Etowah, and DeKalb counties. Outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://www.mlbhc.org",
    phone: "(256) 582-3309",
    address: "11220 Highway 431",
    city: "Guntersville", zip: "35976",
    latitude: 34.3403, longitude: -86.2989,
    source_name: "Mountain Lakes Behavioral Healthcare",
  },
  {
    section: "GUN",
    title: "Albertville Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Marshall County. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 891-0436",
    address: "5850 US Highway 431",
    city: "Albertville", zip: "35950",
    latitude: 34.2625, longitude: -86.2086,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "GUN",
    title: "Marshall County Council on Aging (Guntersville)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Marshall County Council on Aging — Meals on Wheels, congregate dining at multiple senior centers, transportation, in-home support, and caregiver support for older Marshall County veterans.",
    website_url: "https://www.marshallcoa.org",
    phone: "(256) 582-2154",
    address: "12001 US Highway 431",
    city: "Guntersville", zip: "35976",
    latitude: 34.3422, longitude: -86.2961,
    source_name: "Marshall County Council on Aging",
  },

  // ===========================================================================
  // CLA — Clanton / Chilton County
  // ===========================================================================
  {
    section: "CLA",
    title: "Chilton Medical Center Clanton",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "Chilton County's acute care hospital — emergency, surgery, women's services, and outpatient. Closest hospital for Clanton/Jemison/Maplesville veterans on the I-65 Birmingham-Montgomery corridor.",
    website_url: "https://www.chiltonmedicalcenter.com",
    phone: "(205) 755-2500",
    address: "1010 Lay Dam Road",
    city: "Clanton", zip: "35045",
    latitude: 32.8464, longitude: -86.6303,
    source_name: "Chilton Medical Center",
  },
  {
    section: "CLA",
    title: "Chilton-Shelby Mental Health Center (Clanton)",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "Chilton-Shelby Mental Health Center — certified community mental health center for Chilton and Shelby counties. Outpatient counseling, psychiatric services, crisis intervention, and substance-use treatment.",
    website_url: "https://www.csmhc.com",
    phone: "(205) 755-7460",
    address: "201 9th Street North",
    city: "Clanton", zip: "35045",
    latitude: 32.8417, longitude: -86.6294,
    source_name: "Chilton-Shelby Mental Health",
  },
  {
    section: "CLA",
    title: "Mid-Alabama Career Center Clanton (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Chilton County and surrounding Central Alabama I-65 corridor. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(205) 755-4322",
    address: "1909 7th Street South",
    city: "Clanton", zip: "35045",
    latitude: 32.8347, longitude: -86.6300,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "CLA",
    title: "Chilton County Council on Aging (Clanton)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Chilton County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, caregiver support, and SHIP Medicare counseling for older Chilton County veterans.",
    website_url: "https://www.chiltoncountycoa.org",
    phone: "(205) 755-2300",
    address: "508 First Street North",
    city: "Clanton", zip: "35045",
    latitude: 32.8417, longitude: -86.6300,
    source_name: "Chilton County Council on Aging",
  },

  // ===========================================================================
  // SYL — Sylacauga / Talladega
  // ===========================================================================
  {
    section: "SYL",
    title: "Coosa Valley Medical Center Sylacauga",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "127-bed Talladega County acute care hospital — emergency, surgery, cardiology, women's services, behavioral health, and rehabilitation. Closest acute hospital for Sylacauga/Childersburg/Goodwater veterans.",
    website_url: "https://www.coosavalleymedical.com",
    phone: "(256) 401-4000",
    address: "315 West Hickory Street",
    city: "Sylacauga", zip: "35150",
    latitude: 33.1739, longitude: -86.2517,
    source_name: "Coosa Valley Medical Center",
  },
  {
    section: "SYL",
    title: "Citizens Baptist Medical Center Talladega",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "Brookwood Baptist Health affiliate — 122-bed Talladega County acute care hospital. Emergency, surgery, women's services, cardiology, and outpatient. Closest hospital for Talladega/Lincoln/Munford veterans.",
    website_url: "https://www.bbhcitizens.com",
    phone: "(256) 362-8111",
    address: "604 Stone Avenue",
    city: "Talladega", zip: "35160",
    latitude: 33.4356, longitude: -86.1083,
    source_name: "Citizens Baptist Medical Center",
  },
  {
    section: "SYL",
    title: "Cheaha Mental Health Center Sylacauga",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "Cheaha Mental Health Center — certified community mental health center for Talladega, Clay, and Randolph counties. Outpatient counseling, psychiatric services, crisis intervention, and child/adolescent services.",
    website_url: "https://www.cheahamhc.org",
    phone: "(256) 245-1031",
    address: "510 West 4th Street",
    city: "Sylacauga", zip: "35150",
    latitude: 33.1747, longitude: -86.2539,
    source_name: "Cheaha Mental Health Center",
  },
  {
    section: "SYL",
    title: "Sylacauga Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving east Talladega, Clay, Randolph, and Coosa counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 245-8505",
    address: "40770 US Highway 280",
    city: "Sylacauga", zip: "35150",
    latitude: 33.1758, longitude: -86.2486,
    source_name: "Alabama Department of Labor",
  },

  // ===========================================================================
  // FTP — Fort Payne / Rainsville (DeKalb County)
  // ===========================================================================
  {
    section: "FTP",
    title: "DeKalb Regional Medical Center Fort Payne",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "134-bed DeKalb County acute care hospital — emergency, surgery, cardiology, women's services, and outpatient. Closest acute hospital for Fort Payne/Rainsville/Henagar/mountain region veterans.",
    website_url: "https://www.dekalbregional.com",
    phone: "(256) 845-3150",
    address: "200 Medical Center Drive Southwest",
    city: "Fort Payne", zip: "35968",
    latitude: 34.4339, longitude: -85.7236,
    source_name: "DeKalb Regional Medical Center",
  },
  {
    section: "FTP",
    title: "Fort Payne Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving DeKalb County. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals for Northeast Alabama mountain region veterans.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(256) 845-2900",
    address: "1804 Glenn Boulevard SW",
    city: "Fort Payne", zip: "35968",
    latitude: 34.4350, longitude: -85.7269,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "FTP",
    title: "CED Mental Health Center Fort Payne Office",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "CED Mental Health Center Fort Payne outpatient office — certified community mental health center serving DeKalb County. Outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://www.cedmentalhealth.org",
    phone: "(256) 845-4357",
    address: "501 Greenhill Boulevard NW",
    city: "Fort Payne", zip: "35967",
    latitude: 34.4467, longitude: -85.7272,
    source_name: "CED Mental Health Center",
  },
  {
    section: "FTP",
    title: "Northeast Alabama Community College Veterans Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "NACC certifies GI Bill / VR&E / state benefits at the Rainsville campus. Veterans Resource Center, tuition deferment, and priority registration for DeKalb/Jackson County veterans.",
    website_url: "https://www.nacc.edu",
    phone: "(256) 638-4418",
    address: "138 AL Highway 35",
    city: "Rainsville", zip: "35986",
    latitude: 34.4928, longitude: -85.8453,
    source_name: "Northeast Alabama Community College",
  },
  {
    section: "FTP",
    title: "DeKalb County Council on Aging (Fort Payne)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "DeKalb County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, and caregiver support for older DeKalb County veterans.",
    website_url: "https://www.dekalbcoa.com",
    phone: "(256) 845-8590",
    address: "300 Grand Avenue SW",
    city: "Fort Payne", zip: "35967",
    latitude: 34.4434, longitude: -85.7202,
    source_name: "DeKalb County Council on Aging",
  },

  // ===========================================================================
  // OZK — Ozark + Dale County VSO
  // ===========================================================================
  {
    section: "OZK",
    title: "Dale County Veterans Service Office (Ozark)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Dale County's official ADVA county service office. Service Officer Robbie Ray assists Dale County veterans (Ozark, Daleville, Midland City, Fort Novosel area) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Monday through Thursday 8:00 a.m. – 4:00 p.m.; Friday by appointment.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 774-5550",
    address: "County Ag Plex Building, 202 Highway 123 South, Suite F",
    city: "Ozark", zip: "36360",
    latitude: 31.4583, longitude: -85.6403,
    source_name: "ADVA",
  },
  {
    section: "OZK",
    title: "Dale Medical Center Ozark",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "Dale County's acute care hospital — emergency, surgery, women's services, and outpatient services for Ozark, Daleville, and surrounding Wiregrass communities.",
    website_url: "https://www.dalemedical.org",
    phone: "(334) 774-2601",
    address: "126 Hospital Avenue",
    city: "Ozark", zip: "36360",
    latitude: 31.4647, longitude: -85.6411,
    source_name: "Dale Medical Center",
  },
  {
    section: "OZK",
    title: "SpectraCare Health Systems Ozark",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "SpectraCare Ozark outpatient office — certified community mental health center for the Wiregrass. Outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://www.spectracare.org",
    phone: "(334) 774-5096",
    address: "201 East Andrews Street",
    city: "Ozark", zip: "36360",
    latitude: 31.4592, longitude: -85.6394,
    source_name: "SpectraCare Health Systems",
  },
  {
    section: "OZK",
    title: "Dale County Council on Aging (Ozark)",
    cat: "family-support",
    sub: "Caregiver Support",
    desc: "Dale County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, and caregiver support for older Dale County veterans (Fort Novosel retiree population).",
    website_url: "https://www.dalecountyalabama.org",
    phone: "(334) 774-2521",
    address: "125 Adams Street",
    city: "Ozark", zip: "36360",
    latitude: 31.4581, longitude: -85.6386,
    source_name: "Dale County Council on Aging",
  },

  // ===========================================================================
  // PEL — Pell City (St. Clair County)
  // ===========================================================================
  {
    section: "PEL",
    title: "Ascension St. Vincent's St. Clair (Pell City)",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "40-bed Ascension St. Vincent's affiliate — St. Clair County's acute care hospital. Emergency, surgery, cardiology, women's services, and outpatient. Closest hospital for Pell City/Cropwell/Riverside veterans.",
    website_url: "https://healthcare.ascension.org/locations/alabama/alpel/pell-city-ascension-saint-vincents-st-clair",
    phone: "(205) 814-2000",
    address: "7063 Veterans Parkway",
    city: "Pell City", zip: "35125",
    latitude: 33.5878, longitude: -86.2614,
    source_name: "Ascension St. Vincent's",
  },
  {
    section: "PEL",
    title: "JBS Mental Health Authority Pell City",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "JBS Mental Health Authority Pell City office — certified community mental health center serving Jefferson, Blount, and St. Clair counties. Outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://jbsmha.com",
    phone: "(205) 338-4357",
    address: "200 19th Street North",
    city: "Pell City", zip: "35125",
    latitude: 33.5867, longitude: -86.2861,
    source_name: "JBS Mental Health Authority",
  },
  {
    section: "PEL",
    title: "St. Clair County Council on Aging (Pell City)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "St. Clair County Council on Aging — Meals on Wheels, congregate dining at senior centers, transportation, in-home support, and caregiver support for older St. Clair County veterans.",
    website_url: "https://www.stclaircoa.org",
    phone: "(205) 884-3450",
    address: "165 5th Avenue",
    city: "Pell City", zip: "35125",
    latitude: 33.5867, longitude: -86.2861,
    source_name: "St. Clair County Council on Aging",
  },

  // ===========================================================================
  // JAS — Jasper / Walker County
  // ===========================================================================
  {
    section: "JAS",
    title: "Walker Baptist Medical Center Jasper",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "Brookwood Baptist Health affiliate — 267-bed Walker County acute care hospital. Emergency, surgery, cardiology, orthopedics, women's services, and rehabilitation. Closest hospital for Jasper/Cordova/Carbon Hill veterans.",
    website_url: "https://www.bbhwalkerbaptist.com",
    phone: "(205) 387-4000",
    address: "3400 Highway 78 East",
    city: "Jasper", zip: "35501",
    latitude: 33.8358, longitude: -87.2419,
    source_name: "Walker Baptist Medical Center",
  },
  {
    section: "JAS",
    title: "Bevill State Community College Veterans Services (Jasper)",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Bevill State CC certifies GI Bill / VR&E / state benefits at the Jasper main, Sumiton, Hamilton, and Fayette campuses. Trade and skilled programs serve transitioning Northwest Alabama veterans.",
    website_url: "https://www.bscc.edu",
    phone: "(205) 387-0511",
    address: "1411 Indiana Avenue",
    city: "Jasper", zip: "35501",
    latitude: 33.8294, longitude: -87.2767,
    source_name: "Bevill State Community College",
  },
  {
    section: "JAS",
    title: "Bradford Health Services Jasper",
    cat: "substance-recovery",
    sub: "Outpatient Recovery",
    desc: "Bradford Health Services Jasper outpatient — alcohol and drug treatment for Walker, Cullman, and Winston County veterans. Veterans Recovery Track partners with Birmingham VAMC SUD program.",
    website_url: "https://bradfordhealth.com",
    phone: "(205) 384-0888",
    address: "3331 Highway 78 East",
    city: "Jasper", zip: "35501",
    latitude: 33.8367, longitude: -87.2444,
    source_name: "Bradford Health Services",
  },
  {
    section: "JAS",
    title: "Jasper Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Walker, Winston, and Marion counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals for Northwest Alabama mining region veterans.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(205) 221-2576",
    address: "33 8th Street West",
    city: "Jasper", zip: "35501",
    latitude: 33.8311, longitude: -87.2778,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "JAS",
    title: "Walker County Council on Aging (Jasper)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Walker County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, and caregiver support for older Walker County veterans.",
    website_url: "https://www.walkercountyalabama.gov/coa",
    phone: "(205) 387-3737",
    address: "705 19th Street West",
    city: "Jasper", zip: "35501",
    latitude: 33.8333, longitude: -87.2806,
    source_name: "Walker County Council on Aging",
  },

  // ===========================================================================
  // PRA — Prattville + Autauga County VSO
  // ===========================================================================
  {
    section: "PRA",
    title: "Autauga County Veterans Service Office (Prattville)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Autauga County's official ADVA county service office. Service Officer Robert Carr assists Autauga County veterans (Prattville, Autaugaville, Billingsley) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Monday through Friday 8:00 a.m. – 4:30 p.m. Free, confidential service.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 358-6746",
    address: "218 North Court Street",
    city: "Prattville", zip: "36067",
    latitude: 32.4625, longitude: -86.4597,
    source_name: "ADVA",
  },
  {
    section: "PRA",
    title: "Prattville Baptist Hospital",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "85-bed Baptist Health System acute care hospital — emergency, surgery, women's services, cardiology, and outpatient services. Closest hospital for Autauga County and west Elmore County veterans.",
    website_url: "https://www.prattvillebaptist.com",
    phone: "(334) 365-0651",
    address: "124 South Memorial Drive",
    city: "Prattville", zip: "36067",
    latitude: 32.4658, longitude: -86.4517,
    source_name: "Prattville Baptist Hospital",
  },
  {
    section: "PRA",
    title: "Prattville Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Autauga, Elmore, and Chilton counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and Maxwell-Gunter retiree employment support.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(334) 358-2950",
    address: "200 East 6th Street",
    city: "Prattville", zip: "36067",
    latitude: 32.4631, longitude: -86.4603,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "PRA",
    title: "Autauga County Council on Aging (Prattville)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Autauga County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, caregiver support, and SHIP Medicare counseling for older Autauga County veterans.",
    website_url: "https://www.autaugaco.org",
    phone: "(334) 358-6740",
    address: "115 East 5th Street",
    city: "Prattville", zip: "36067",
    latitude: 32.4636, longitude: -86.4628,
    source_name: "Autauga County Council on Aging",
  },
  {
    section: "PRA",
    title: "Habitat for Humanity of Autauga and Chilton Counties (Prattville)",
    cat: "housing",
    sub: "Home Ownership Programs",
    desc: "Habitat affiliate serving Autauga and Chilton counties since 1993 — affordable home-ownership for low-income families through sweat-equity and zero-interest mortgages. Dedicated their 50th home in January 2025. Veteran applicants and Veterans Build days supported.",
    website_url: "https://www.habitatautaugachilton.org",
    phone: "(334) 365-4132",
    address: "431 West 4th Street, Suite A",
    city: "Prattville", zip: "36067",
    latitude: 32.4639, longitude: -86.4569,
    source_name: "Habitat for Humanity",
  },

  // ===========================================================================
  // DEM — Demopolis + Marengo County VSO
  // ===========================================================================
  {
    section: "DEM",
    title: "Marengo/Wilcox County Veterans Service Office (Linden)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "ADVA combined county Veterans Service Office for Marengo and Wilcox counties. Service Officer Sandra Wright assists Marengo and Wilcox county veterans (Linden, Demopolis, Sweet Water, Thomaston, Camden) with VA disability compensation, pension, healthcare enrollment, education, burial, and survivor benefit claims. Hours: Monday through Friday 8:00 a.m. – 4:30 p.m. Free service.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 295-2243",
    address: "101 East Coats Avenue, Room 123",
    city: "Linden", zip: "36748",
    latitude: 32.3056, longitude: -87.7975,
    source_name: "ADVA",
  },
  {
    section: "DEM",
    title: "Whitfield Regional Hospital Demopolis",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "99-bed UAB Health System affiliate — Marengo County's acute care hospital. Emergency, surgery, women's services, primary care, and outpatient services for Demopolis and Black Belt veterans.",
    website_url: "https://www.whitfieldregional.com",
    phone: "(334) 287-2778",
    address: "105 US Highway 80 East",
    city: "Demopolis", zip: "36732",
    latitude: 32.5161, longitude: -87.8261,
    source_name: "Whitfield Regional Hospital",
  },
  {
    section: "DEM",
    title: "West Alabama Mental Health Center Demopolis",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "West Alabama Mental Health Center Demopolis office — certified community mental health center for Marengo, Choctaw, Sumter, Greene, Hale, and Wilcox counties. Outpatient counseling and crisis services.",
    website_url: "https://westalmhc.com",
    phone: "(334) 289-2410",
    address: "806 South Cedar Avenue",
    city: "Demopolis", zip: "36732",
    latitude: 32.5128, longitude: -87.8336,
    source_name: "West Alabama Mental Health Center",
  },
  {
    section: "DEM",
    title: "Demopolis Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Marengo, Choctaw, Sumter, Greene, and Hale counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals for Black Belt veterans.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(334) 289-0202",
    address: "1074 US Highway 80 East",
    city: "Demopolis", zip: "36732",
    latitude: 32.5161, longitude: -87.8214,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "DEM",
    title: "Marengo County Council on Aging (Demopolis)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Marengo County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, and caregiver support for older Marengo County veterans in the Black Belt.",
    website_url: "https://www.marengocountyal.org",
    phone: "(334) 289-0860",
    address: "501 East Pettus Street",
    city: "Demopolis", zip: "36732",
    latitude: 32.5147, longitude: -87.8261,
    source_name: "Marengo County Council on Aging",
  },

  // ===========================================================================
  // PHE — Phenix City / Russell County
  // ===========================================================================
  {
    section: "PHE",
    title: "Jack Hughston Memorial Hospital Phenix City",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "100-bed Hughston-affiliated specialty hospital — orthopedic surgery, sports medicine, total joint replacement, and rehabilitation for Russell County and Fort Moore-area veterans.",
    website_url: "https://www.jackhughston.com",
    phone: "(334) 732-3000",
    address: "4401 River Chase Drive",
    city: "Phenix City", zip: "36867",
    latitude: 32.4561, longitude: -85.0078,
    source_name: "Jack Hughston Memorial Hospital",
  },
  {
    section: "PHE",
    title: "East Alabama Mental Health Authority Phenix City Office",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "East Alabama Mental Health Authority Phenix City office — certified community mental health center serving Russell County. Outpatient counseling, psychiatric services, and crisis intervention.",
    website_url: "https://www.eamh.org",
    phone: "(334) 297-2000",
    address: "1701 Crawford Road",
    city: "Phenix City", zip: "36867",
    latitude: 32.4717, longitude: -85.0086,
    source_name: "East Alabama Mental Health Authority",
  },
  {
    section: "PHE",
    title: "Phenix City Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Russell County. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and Fort Moore (formerly Benning) transitioning-soldier employment support.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(334) 297-3691",
    address: "1700 Stadium Drive",
    city: "Phenix City", zip: "36867",
    latitude: 32.4744, longitude: -85.0089,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "PHE",
    title: "Russell County Council on Aging (Phenix City)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Russell County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, and caregiver support for older Russell County veterans (Fort Moore retiree population).",
    website_url: "https://www.russellcountyal.com",
    phone: "(334) 297-0750",
    address: "2009 13th Avenue",
    city: "Phenix City", zip: "36867",
    latitude: 32.4767, longitude: -85.0028,
    source_name: "Russell County Council on Aging",
  },
  {
    section: "PHE",
    title: "Salvation Army Phenix City Service Center",
    cat: "food-assistance",
    sub: "Food Pantries",
    desc: "Salvation Army Phenix City Service Center — food pantry, emergency utility/rent assistance, Christmas Angel Tree, and case management for Russell County veterans and families.",
    website_url: "https://southernusa.salvationarmy.org/columbus-ga",
    phone: "(334) 298-5311",
    address: "1500 5th Avenue",
    city: "Phenix City", zip: "36867",
    latitude: 32.4750, longitude: -85.0175,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // TRY — Troy / Pike County deeper
  // ===========================================================================
  {
    section: "TRY",
    title: "Troy Regional Medical Center",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "94-bed Pike County acute care hospital — emergency, surgery, women's services, cardiology, and outpatient services. Closest acute hospital for Troy, Brundidge, and Pike County veterans.",
    website_url: "https://www.troyregional.org",
    phone: "(334) 670-5000",
    address: "1330 US Highway 231 South",
    city: "Troy", zip: "36081",
    latitude: 31.7886, longitude: -85.9528,
    source_name: "Troy Regional Medical Center",
  },
  {
    section: "TRY",
    title: "Troy University Office of Veterans Affairs (Troy Campus)",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Troy University main campus VA Office certifies GI Bill / VR&E / state benefits and runs the SOAR (Student Orientation and Retention) Veterans program. Yellow Ribbon participant; serves all 4 TROY campuses.",
    website_url: "https://www.troy.edu/military",
    phone: "(334) 670-3173",
    address: "Eldridge Hall, 600 University Avenue",
    city: "Troy", zip: "36082",
    latitude: 31.7986, longitude: -85.9536,
    source_name: "Troy University",
  },
  // SpectraCare Health Systems Troy was originally seeded here but removed
  // 2026-04-25 — public sources do not list a verified Pike County / Troy
  // street address for SpectraCare. Phone (334) 566-0985 is published but no
  // address is. Will be re-added in Phase 5 once a sourced address is obtained
  // directly from SpectraCare. Do NOT re-add without ADVA-style canonical
  // verification.
  {
    section: "TRY",
    title: "Troy Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Pike, Bullock, Crenshaw, and Barbour counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(334) 566-3920",
    address: "1023 South Brundidge Street",
    city: "Troy", zip: "36081",
    latitude: 31.7944, longitude: -85.9608,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "TRY",
    title: "Pike County Council on Aging (Troy)",
    cat: "end-of-life-services",
    sub: "Senior & Disabled Meal Programs",
    desc: "Pike County Council on Aging — Meals on Wheels, congregate dining, senior transportation, in-home support, and caregiver support for older Pike County veterans.",
    website_url: "https://www.pikecountyalabama.gov",
    phone: "(334) 566-1130",
    address: "335 East Walnut Street",
    city: "Troy", zip: "36081",
    latitude: 31.8092, longitude: -85.9692,
    source_name: "Pike County Council on Aging",
  },

  // ===========================================================================
  // OPE — Opelika depth (currently 9 rows)
  // ===========================================================================
  {
    section: "OPE",
    title: "Auburn-Opelika Career Center (Alabama Career Center System)",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "ADOL Career Center serving Lee, Russell, Tallapoosa, and Chambers counties. DVOP/LVER veteran employment reps, JVSG-funded job-search assistance, and apprenticeship referrals for Auburn-Opelika veterans.",
    website_url: "https://www.labor.alabama.gov",
    phone: "(334) 749-5065",
    address: "2300 Frederick Road Suite 100",
    city: "Opelika", zip: "36801",
    latitude: 32.6217, longitude: -85.4233,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "OPE",
    title: "Salvation Army Opelika Service Center",
    cat: "food-assistance",
    sub: "Food Pantries",
    desc: "Salvation Army Lee County Service Center — food pantry, emergency utility/rent assistance, Christmas Angel Tree, and case management for Lee County veterans and families.",
    website_url: "https://southernusa.salvationarmy.org/opelika-al",
    phone: "(334) 749-5302",
    address: "1102 Avenue B",
    city: "Opelika", zip: "36801",
    latitude: 32.6464, longitude: -85.3781,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // VSO — Additional county VSOs (Phase 4 batch)
  // ===========================================================================
  {
    section: "VSO",
    title: "Elmore County Veterans Service Office (Wetumpka)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Elmore County's official ADVA county service office. Service Officer Jessica Senteno assists Elmore County veterans (Wetumpka, Millbrook, Tallassee, Eclectic, Maxwell-Gunter retirees) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Monday through Friday 8:00 a.m. – 4:30 p.m. Phone: (334) 567-1156 ext. 5016.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 567-1156",
    address: "Elmore County Courthouse, 100 East Commerce Street",
    city: "Wetumpka", zip: "36092",
    latitude: 32.5444, longitude: -86.2117,
    source_name: "ADVA",
  },
  {
    section: "VSO",
    title: "Coosa/Tallapoosa County Veterans Service Office (Alexander City)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "ADVA combined county Veterans Service Office for Coosa and Tallapoosa counties, located in Alexander City. Service Officer Joy Lowery assists Coosa and Tallapoosa county veterans (Alexander City, Dadeville, Tallassee, Goodwater, Rockford) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Monday through Friday 8 a.m. – 5 p.m.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(256) 825-1622",
    address: "395 Lee Street, Room 145",
    city: "Alexander City", zip: "35010",
    latitude: 32.9442, longitude: -85.9539,
    source_name: "ADVA",
  },
  {
    section: "VSO",
    title: "Geneva County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Geneva County's official ADVA county service office. Service Officer Robert Gautney assists Geneva County veterans (Geneva, Slocomb, Hartford, Samson) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Monday through Thursday 8:30 a.m. – 4:30 p.m.; Friday by appointment.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 684-5657",
    address: "Geneva County Courthouse, 200 North Commerce Street",
    city: "Geneva", zip: "36340",
    latitude: 31.0364, longitude: -85.8669,
    source_name: "ADVA",
  },
  {
    section: "VSO",
    title: "Escambia County Veterans Service Office (Atmore)",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Escambia County's official ADVA county Veterans Service Office, located in the Satellite Building in Atmore. Service Officer Gene Moore assists Escambia County veterans (Atmore, Brewton, East Brewton, Flomaton) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Monday, Tuesday, Friday 7:30 a.m. – 4:30 p.m. Phone: (251) 368-4223 ext. 115.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(251) 368-4223",
    address: "Satellite Building, 8600 Hwy 31 East",
    city: "Atmore", zip: "36502",
    latitude: 31.0240, longitude: -87.4936,
    source_name: "ADVA",
  },
  {
    section: "VSO",
    title: "Monroe County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Monroe County's official ADVA county service office. Service Officer Gene Moore assists Monroe County veterans (Monroeville, Frisco City, Beatrice, Excel) with VA disability compensation, pension, healthcare enrollment, education, and survivor benefit claims. Hours: Wednesday and Thursday 8:30 a.m. – 4:00 p.m.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(251) 575-9832",
    address: "65 North Alabama Avenue",
    city: "Monroeville", zip: "36461",
    latitude: 31.5228, longitude: -87.3236,
    source_name: "ADVA",
  },
];

const SECTION_LABELS: Record<string, string> = {
  FLO: "Florence / Quad Cities (Lauderdale)",
  GAD: "Gadsden / Etowah",
  ANN: "Anniston / Calhoun",
  ENT: "Enterprise + Coffee VSO",
  FLY: "Foley (south Baldwin)",
  FAH: "Fairhope (Eastern Shore Baldwin)",
  BAY: "Bay Minette (Coastal Alabama CC)",
  ATH: "Athens / Limestone",
  SCO: "Scottsboro / Jackson",
  GUN: "Guntersville / Boaz / Albertville (Marshall)",
  CLA: "Clanton / Chilton",
  SYL: "Sylacauga / Talladega",
  FTP: "Fort Payne / Rainsville (DeKalb)",
  OZK: "Ozark + Dale VSO",
  PEL: "Pell City (St. Clair)",
  JAS: "Jasper (Walker)",
  PRA: "Prattville + Autauga VSO",
  DEM: "Demopolis + Marengo VSO",
  PHE: "Phenix City (Russell deeper)",
  TRY: "Troy (Pike deeper)",
  OPE: "Opelika depth",
  VSO: "Additional county VSOs (Phase 4 batch)",
};

(async () => {
  const result = await runSeed(ROWS, {
    state: "AL",
    commit: COMMIT,
    scriptName: "seed-al-phase4 — Regional / Smaller-City / County Coverage Pass",
    sectionLabels: SECTION_LABELS,
  });
  if (result.totalErr > 0 || result.totalBadSub > 0) {
    process.exit(1);
  }
})();
