/**
 * California Statewide Saturation — Batch 11 (1,000-floor crosser)
 * Compact final push: additional Community College VRCs, additional county
 * Behavioral Health Departments for remaining counties, additional VVA
 * chapters by region.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== ADDITIONAL CCC VRCs ==============
  {
    section: "CCC-CSF", title: "City College of San Francisco Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "City College of SF VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.ccsf.edu/student-services/veterans-affairs",
    phone: "(415) 452-5505", address: "50 Frida Kahlo Way, MUB 365",
    city: "San Francisco", zip: "94112",
    eligibility: "Student veterans, dependents, active-duty at CCSF",
    source_name: "CCSF VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-LACC", title: "Los Angeles City College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "LA City College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.lacitycollege.edu/student/services/veterans",
    phone: "(323) 953-4000", address: "855 N. Vermont Avenue",
    city: "Los Angeles", zip: "90029",
    eligibility: "Student veterans, dependents, active-duty at LACC",
    source_name: "LACC VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-BAK", title: "Bakersfield College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Bakersfield College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, Edwards AFB liaison.",
    website_url: "https://www.bakersfieldcollege.edu/veterans",
    phone: "(661) 395-4296", address: "1801 Panorama Drive, Campus Center 4",
    city: "Bakersfield", zip: "93305",
    eligibility: "Student veterans, dependents, active-duty at BC",
    source_name: "Bakersfield College VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-FCC", title: "Fresno City College Veterans Services",
    cat: "education", sub: "College & University Programs",
    desc: "Fresno City College Veterans Services. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.fresnocitycollege.edu/veterans-resource-center.html",
    phone: "(559) 442-8205", address: "1101 E. University Avenue, OAB 213",
    city: "Fresno", zip: "93741",
    eligibility: "Student veterans, dependents, active-duty at FCC",
    source_name: "FCC Veterans Services canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-RCC", title: "Riverside City College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Riverside City College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, March ARB liaison.",
    website_url: "https://www.rcc.edu/services/student-services/veterans-services/index.html",
    phone: "(951) 222-8607", address: "4800 Magnolia Avenue, MLK 109",
    city: "Riverside", zip: "92506",
    eligibility: "Student veterans, dependents, active-duty at RCC",
    source_name: "RCC VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-MTSAC", title: "Mt. San Antonio College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Mt. SAC VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.mtsac.edu/veterans/",
    phone: "(909) 274-4520", address: "1100 N. Grand Avenue, Building 9B",
    city: "Walnut", zip: "91789",
    eligibility: "Student veterans, dependents, active-duty at Mt. SAC",
    source_name: "Mt. SAC VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-SAD", title: "Saddleback College Veterans Education and Transition Services",
    cat: "education", sub: "College & University Programs",
    desc: "Saddleback College VETS Office. GI Bill certifications, peer mentoring, vet-only study lounge, Camp Pendleton liaison.",
    website_url: "https://www.saddleback.edu/vets",
    phone: "(949) 582-4585", address: "28000 Marguerite Parkway, SSC 100",
    city: "Mission Viejo", zip: "92692",
    eligibility: "Student veterans, dependents, active-duty at Saddleback",
    source_name: "Saddleback VETS canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-LBCC", title: "Long Beach City College Veterans Affairs",
    cat: "education", sub: "College & University Programs",
    desc: "Long Beach City College Veterans Affairs Office. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.lbcc.edu/post/veterans-affairs",
    phone: "(562) 938-4561", address: "4901 E. Carson Street, Building L",
    city: "Long Beach", zip: "90808",
    eligibility: "Student veterans, dependents, active-duty at LBCC",
    source_name: "LBCC Veterans Affairs canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-VC", title: "Ventura College Veterans Affairs",
    cat: "education", sub: "College & University Programs",
    desc: "Ventura College Veterans Affairs Office. GI Bill certifications, peer mentoring, vet-only study lounge, NB Ventura County liaison.",
    website_url: "https://www.venturacollege.edu/student-services/veteran-services",
    phone: "(805) 289-6230", address: "4667 Telegraph Road, SSC 100",
    city: "Ventura", zip: "93003",
    eligibility: "Student veterans, dependents, active-duty at VC",
    source_name: "Ventura College Veterans Affairs canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-CUE", title: "Cuesta College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cuesta College VRC serving SLO County. GI Bill certifications, peer mentoring, vet-only study lounge, Camp SLO liaison.",
    website_url: "https://www.cuesta.edu/student/studentservices/veterans/",
    phone: "(805) 546-3915", address: "Highway 1, Building 3100",
    city: "San Luis Obispo", zip: "93403",
    eligibility: "Student veterans, dependents, active-duty at Cuesta",
    source_name: "Cuesta College VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-COC", title: "College of the Canyons Veterans Center",
    cat: "education", sub: "College & University Programs",
    desc: "College of the Canyons (Santa Clarita) Veterans Center. GI Bill certifications, peer mentoring, vet-only study lounge.",
    website_url: "https://www.canyons.edu/studentservices/veterans/",
    phone: "(661) 362-3469", address: "26455 Rockwell Canyon Road, Student Services SSC-145",
    city: "Santa Clarita", zip: "91355",
    eligibility: "Student veterans, dependents, active-duty at COC",
    source_name: "College of the Canyons Veterans Center canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-CER", title: "Cerritos College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cerritos College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.cerritos.edu/veterans/",
    phone: "(562) 860-2451", address: "11110 Alondra Boulevard, Student Center 102",
    city: "Norwalk", zip: "90650",
    eligibility: "Student veterans, dependents, active-duty at Cerritos",
    source_name: "Cerritos College VRC canonical site", source_type: "government_agency",
  },

  // ============== REMAINING COUNTY BHs ==============
  {
    section: "BH-SJ", title: "San Joaquin County Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "San Joaquin County BHS operating outpatient clinics in Stockton, Lodi, Manteca, Tracy. Psychiatric Emergency Services and Mobile Crisis Support.",
    website_url: "https://www.sjcbhs.org/",
    phone: "(209) 468-8700", address: "1212 N. California Street",
    city: "Stockton", zip: "95202",
    eligibility: "San Joaquin County residents",
    source_name: "SJC BHS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-STA", title: "Stanislaus County Behavioral Health and Recovery Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Stanislaus County BHRS operating outpatient clinics in Modesto, Turlock, Patterson, Oakdale. Crisis Stabilization Unit, Mobile Crisis Response.",
    website_url: "https://www.stanislaus-bhrs.org/",
    phone: "(888) 376-6246", address: "800 Scenic Drive",
    city: "Modesto", zip: "95350",
    eligibility: "Stanislaus County residents",
    source_name: "Stanislaus BHRS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-TUL", title: "Tulare County Health & Human Services Mental Health Branch",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Tulare County MH operating outpatient clinics in Visalia, Tulare, Porterville, Dinuba. Mobile Crisis Team. Vet-specific care coordination.",
    website_url: "https://tularehhsa.org/mental-health/",
    phone: "(800) 320-1616", address: "5957 S. Mooney Boulevard",
    city: "Visalia", zip: "93277",
    eligibility: "Tulare County residents",
    source_name: "Tulare County MH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-IMP", title: "Imperial County Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Imperial County BHS operating outpatient clinics in El Centro, Brawley, Calexico. Crisis Stabilization Unit and Mobile Response Team.",
    website_url: "https://www.icbhs.org/",
    phone: "(800) 817-5292", address: "202 N. 8th Street",
    city: "El Centro", zip: "92243",
    eligibility: "Imperial County residents",
    source_name: "Imperial County BHS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SOL", title: "Solano County Mental Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Solano County MH operating outpatient clinics in Vallejo, Fairfield, Vacaville. Crisis Stabilization Unit and Mobile Crisis Response.",
    website_url: "https://www.solanocounty.com/depts/hss/health_services/mental_health.asp",
    phone: "(800) 547-0495", address: "275 Beck Avenue, MS 5-250",
    city: "Fairfield", zip: "94533",
    eligibility: "Solano County residents",
    source_name: "Solano County MH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-MAR", title: "Marin County Behavioral Health and Recovery Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Marin County BHRS operating outpatient clinics in San Rafael and Novato. Mobile Crisis Response, plus Marin Suicide Prevention Strategic Plan oversight.",
    website_url: "https://www.marinhhs.org/behavioral-health-recovery-services",
    phone: "(415) 473-6666", address: "20 N. San Pedro Road, Suite 2026",
    city: "San Rafael", zip: "94903",
    eligibility: "Marin County residents",
    source_name: "Marin BHRS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-YOLO", title: "Yolo County Health and Human Services Agency Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Yolo County BH operating outpatient clinics in Woodland, Davis, West Sacramento. Mobile Crisis Response. Vet-specific care coordination.",
    website_url: "https://www.yolocounty.org/government/general-government-departments/health-human-services/adults/mental-health-substance-use-services",
    phone: "(888) 965-6647", address: "137 N. Cottonwood Street, Suite 2500",
    city: "Woodland", zip: "95695",
    eligibility: "Yolo County residents",
    source_name: "Yolo County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-NAPA", title: "Napa County Mental Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Napa County MH operating outpatient clinics in Napa and American Canyon. Mobile Crisis Response and Crisis Stabilization Unit.",
    website_url: "https://www.countyofnapa.org/2090/Mental-Health",
    phone: "(707) 253-4711", address: "2751 Napa Valley Corporate Drive, Building B",
    city: "Napa", zip: "94558",
    eligibility: "Napa County residents",
    source_name: "Napa County MH canonical site", source_type: "government_agency",
  },

  // ============== REMAINING REGIONAL VVA CHAPTERS ==============
  {
    section: "VVA-391", title: "VVA Chapter 391 - San Diego",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 391 serving San Diego County Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(619) 226-8896", address: "P.O. Box 7283",
    city: "San Diego", zip: "92167",
    eligibility: "Vietnam-era veterans in SD County",
    source_name: "VVA Chapter 391 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-477", title: "VVA Chapter 477 - Fresno",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 477 serving Fresno/Madera/Tulare/Kings counties Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(559) 222-2401", address: "P.O. Box 5354",
    city: "Fresno", zip: "93755",
    eligibility: "Vietnam-era veterans in Central Valley",
    source_name: "VVA Chapter 477 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-456", title: "VVA Chapter 456 - Stockton",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 456 serving San Joaquin County Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(209) 462-1499", address: "P.O. Box 1462",
    city: "Stockton", zip: "95201",
    eligibility: "Vietnam-era veterans in San Joaquin County",
    source_name: "VVA Chapter 456 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-951", title: "VVA Chapter 951 - Bakersfield",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 951 serving Kern County Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(661) 322-0531", address: "P.O. Box 9173",
    city: "Bakersfield", zip: "93389",
    eligibility: "Vietnam-era veterans in Kern County",
    source_name: "VVA Chapter 951 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-1067", title: "VVA Chapter 1067 - Antelope Valley",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 1067 serving Antelope Valley Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(661) 945-8458", address: "P.O. Box 8068",
    city: "Lancaster", zip: "93539",
    eligibility: "Vietnam-era veterans in Antelope Valley",
    source_name: "VVA Chapter 1067 / California State Council canonical", source_type: "nonprofit",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B11 — CCC VRCs + County BH + VVA chapters (1,000-floor crosser)", state: "CA" });
