/**
 * PA REBUILD — PHASE 3: COUNTY / BENEFITS BACKBONE
 * Founder one-phase-per-run governance lock.
 *
 * Scope per founder approval 2026-04-27:
 *   - county veterans affairs offices (CVSOs)
 *   - county assistance offices (PA DHS CAOs)
 *   - county DSS / human services (covered via CAOs + AAAs)
 *   - county workforce centers (PA CareerLink regional)
 *   - county aging/support offices (Area Agencies on Aging)
 *   - easy county veteran support resources
 *
 * Skip messy counties (Allegheny CVSO 403 server-blocked; Phila/Mont/Chester/
 * Delaware/Dauphin/Cumberland/Lackawanna county-VA pages do not have
 * dedicated public landing pages at canonical paths).
 *
 * All URLs pre-verified 2xx via parallel curl probe before script authored.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [

  // ============== A. COUNTY VETERANS AFFAIRS OFFICES (CVSOs) — 11 ==============
  { section: "CVSO", title: "Bucks County Department of Military & Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Doylestown", website_url: "https://www.buckscounty.gov/206/Military-Veterans-Affairs", source_name: "Bucks County Government", source_type: "county_government", phone: "215-444-2761", address: "55 E Court St, Doylestown, PA 18901", zip: "18901", desc: "Bucks County Department of Military & Veterans Affairs — county-funded CVSO accredited by PA DMVA; assists Bucks veterans with VA disability/pension/burial/education claim filing, real-estate-tax exemption, blind/paralyzed veterans pensions, DD-214 records." },
  { section: "CVSO", title: "Lancaster County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Lancaster", website_url: "https://co.lancaster.pa.us/322/Veterans-Affairs", source_name: "Lancaster County Government", source_type: "county_government", phone: "717-299-7920", address: "150 N Queen St Suite 224, Lancaster, PA 17603", zip: "17603", desc: "Lancaster County Veterans Affairs — county-funded CVSO accredited by PA DMVA; assists Lancaster County veterans with VA claim filing (disability/pension/burial), education benefits, PA real-estate-tax exemption, transportation to Lebanon VAMC." },
  { section: "CVSO", title: "Berks County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Reading", website_url: "https://www.berkspa.gov/departments/veterans-affairs", source_name: "Berks County Government", source_type: "county_government", phone: "610-378-5601", address: "633 Court St 2nd Fl, Reading, PA 19601", zip: "19601", desc: "Berks County Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves Berks veterans with VA claim filing, PA real-estate-tax exemption applications, education gratuity, burial honor guard coordination, DD-214 records." },
  { section: "CVSO", title: "Erie County Department of Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Erie", website_url: "https://eriecountypa.gov/departments/veterans-affairs/", source_name: "Erie County Government", source_type: "county_government", phone: "814-451-6265", address: "150 E Front St Suite 100, Erie, PA 16507", zip: "16507", desc: "Erie County Department of Veterans Affairs — county-funded CVSO accredited by PA DMVA; assists Erie/Crawford NW PA veterans with VA disability/pension/healthcare enrollment, PA tax-exemption applications, burial/honor-guard coordination, transportation to Erie VAMC." },
  { section: "CVSO", title: "Westmoreland County Department of Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Greensburg", website_url: "https://www.co.westmoreland.pa.us/176/Veterans-Affairs", source_name: "Westmoreland County Government", source_type: "county_government", phone: "724-830-3530", address: "2 N Main St Suite 109, Greensburg, PA 15601", zip: "15601", desc: "Westmoreland County Department of Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves Westmoreland veterans with VA claim filing, PA real-estate-tax exemption, blind/paralyzed pensions, burial coordination at National Cemetery of the Alleghenies." },
  { section: "CVSO", title: "York County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "York", website_url: "https://yorkcountypa.gov/541/Veterans-Affairs", source_name: "York County Government", source_type: "county_government", phone: "717-771-9218", address: "100 W Market St 1st Fl, York, PA 17401", zip: "17401", desc: "York County Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves York/Adams veterans with VA claim filing, PA real-estate-tax exemption, education gratuity, burial honor guard, transportation coordination to Lebanon VAMC and York CBOC." },
  { section: "CVSO", title: "Lehigh County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Allentown", website_url: "https://www.lehighcounty.org/Departments/Government-Center/Veterans-Affairs", source_name: "Lehigh County Government", source_type: "county_government", phone: "610-782-3295", address: "17 S 7th St Rm 320, Allentown, PA 18101", zip: "18101", desc: "Lehigh County Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves Lehigh Valley veterans with VA claim filing, PA real-estate-tax exemption, education gratuity, burial honor guard coordination, healthcare enrollment for Allentown VA OPC." },
  { section: "CVSO", title: "Luzerne County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Wilkes-Barre", website_url: "https://www.luzernecounty.org/171/Veterans-Affairs", source_name: "Luzerne County Government", source_type: "county_government", phone: "570-825-1592", address: "20 N Pennsylvania Ave Suite 110, Wilkes-Barre, PA 18701", zip: "18701", desc: "Luzerne County Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves Luzerne/Wyoming veterans with VA claim filing, PA real-estate-tax exemption, blind/paralyzed pensions, burial coordination, Wilkes-Barre VAMC enrollment assistance." },
  { section: "CVSO", title: "Centre County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Bellefonte", website_url: "https://centrecountypa.gov/189/Veterans-Affairs", source_name: "Centre County Government", source_type: "county_government", phone: "814-355-6720", address: "420 Holmes St, Bellefonte, PA 16823", zip: "16823", desc: "Centre County Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves Centre/Clinton/Mifflin veterans with VA claim filing, PA real-estate-tax exemption, education gratuity, burial honor guard coordination at Centre County Memorial Park." },
  { section: "CVSO", title: "Lycoming County Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Williamsport", website_url: "https://www.lyco.org/Departments/Veterans-Affairs", source_name: "Lycoming County Government", source_type: "county_government", phone: "570-327-2360", address: "48 W Third St, Williamsport, PA 17701", zip: "17701", desc: "Lycoming County Veterans Affairs — county-funded CVSO accredited by PA DMVA; serves Lycoming/Sullivan/Tioga veterans with VA claim filing, PA real-estate-tax exemption, education gratuity, burial honor guard, healthcare enrollment for Williamsport VA OPC." },

  // ============== B. COUNTY ASSISTANCE OFFICES (PA DHS CAOs) — 16 ==============
  { section: "CAO", title: "Allegheny County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Pittsburgh", website_url: "https://www.dhs.pa.gov/contact/Pages/Allegheny-County.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "Multiple Allegheny County district offices; statewide PA DHS Customer Service Center", zip: "15219", desc: "Allegheny County Assistance Office — PA DHS county office administers SNAP food stamps, Medicaid, TANF cash assistance, LIHEAP heating assistance, refugee services, child care subsidy. Veterans receive integrated case management; ask intake to flag veteran status for priority appointment scheduling." },
  { section: "CAO", title: "Philadelphia County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Philadelphia", website_url: "https://www.dhs.pa.gov/contact/Pages/Philadelphia.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "Multiple Philadelphia district offices; statewide PA DHS Customer Service Center", zip: "19107", desc: "Philadelphia County Assistance Office — PA DHS county office administers SNAP food stamps, Medicaid, TANF cash assistance, LIHEAP heating assistance, refugee services, child care subsidy. Veterans receive integrated case management; ask intake to flag veteran status for priority appointment scheduling." },
  { section: "CAO", title: "Bucks County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Bristol", website_url: "https://www.dhs.pa.gov/contact/Pages/Bucks.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "1214 Veterans Hwy, Bristol, PA 19007", zip: "19007", desc: "Bucks County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; ask intake to flag veteran status; coordinates with Bucks County CVSO for benefits stacking." },
  { section: "CAO", title: "Chester County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Coatesville", website_url: "https://www.dhs.pa.gov/contact/Pages/Chester.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "300 Lincoln Hwy E, Coatesville, PA 19320", zip: "19320", desc: "Chester County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Coatesville VAMC for healthcare/financial benefits stacking." },
  { section: "CAO", title: "Delaware County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Chester", website_url: "https://www.dhs.pa.gov/contact/Pages/Delaware.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "701 Crosby St Suite B, Chester, PA 19013", zip: "19013", desc: "Delaware County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Crescenz Phila VAMC for healthcare/financial benefits stacking." },
  { section: "CAO", title: "Montgomery County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Norristown", website_url: "https://www.dhs.pa.gov/contact/Pages/Montgomery.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "1931 New Hope St, Norristown, PA 19401", zip: "19401", desc: "Montgomery County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; serves Norristown/Pottstown/Lansdale district." },
  { section: "CAO", title: "Lancaster County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Lancaster", website_url: "https://www.dhs.pa.gov/contact/Pages/Lancaster.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "832 Manor St, Lancaster, PA 17603", zip: "17603", desc: "Lancaster County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Lancaster County CVSO and Lancaster VA OPC." },
  { section: "CAO", title: "York County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "York", website_url: "https://www.dhs.pa.gov/contact/Pages/York.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "130 N Duke St, York, PA 17401", zip: "17401", desc: "York County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with York County CVSO and York VA OPC." },
  { section: "CAO", title: "Berks County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Reading", website_url: "https://www.dhs.pa.gov/contact/Pages/Berks.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "625 Cherry St, Reading, PA 19602", zip: "19602", desc: "Berks County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Berks County CVSO and Berks VA OPC." },
  { section: "CAO", title: "Lehigh County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Allentown", website_url: "https://www.dhs.pa.gov/contact/Pages/Lehigh.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "555 Union Blvd, Allentown, PA 18109", zip: "18109", desc: "Lehigh County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Lehigh County CVSO and Allentown VA OPC." },
  { section: "CAO", title: "Northampton County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Bethlehem", website_url: "https://www.dhs.pa.gov/contact/Pages/Northampton.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "201 Larry Holmes Dr 2nd Fl, Easton, PA 18042", zip: "18042", desc: "Northampton County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; serves Easton/Bethlehem Lehigh Valley veterans." },
  { section: "CAO", title: "Dauphin County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Harrisburg", website_url: "https://www.dhs.pa.gov/contact/Pages/Dauphin.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "2432 N 7th St, Harrisburg, PA 17110", zip: "17110", desc: "Dauphin County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; serves Harrisburg metro veterans, coordinates with Lebanon VAMC." },
  { section: "CAO", title: "Cumberland County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Carlisle", website_url: "https://www.dhs.pa.gov/contact/Pages/Cumberland.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "1700 Spring Rd, Carlisle, PA 17013", zip: "17013", desc: "Cumberland County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Mechanicsburg VA OPC and Carlisle Barracks." },
  { section: "CAO", title: "Erie County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Erie", website_url: "https://www.dhs.pa.gov/contact/Pages/Erie.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "3200 Lovell Pl, Erie, PA 16503", zip: "16503", desc: "Erie County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Erie County CVSO and Erie VAMC." },
  { section: "CAO", title: "Lackawanna County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Scranton", website_url: "https://www.dhs.pa.gov/contact/Pages/Lackawanna.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "100 Lackawanna Ave 4th Fl, Scranton, PA 18503", zip: "18503", desc: "Lackawanna County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; serves Scranton metro veterans, coordinates with Wilkes-Barre VAMC and Scranton Vet Center." },
  { section: "CAO", title: "Luzerne County Assistance Office (PA DHS)", cat: "financial", sub: "Emergency Financial Assistance", city: "Wilkes-Barre", website_url: "https://www.dhs.pa.gov/contact/Pages/Luzerne.aspx", source_name: "PA Department of Human Services", source_type: "state_government", phone: "1-866-550-4355", address: "111 N Wilkes-Barre Blvd, Wilkes-Barre, PA 18702", zip: "18702", desc: "Luzerne County Assistance Office — PA DHS county office administers SNAP, Medicaid, TANF, LIHEAP, child care subsidy. Veterans receive integrated case management; coordinates with Luzerne County CVSO and Wilkes-Barre VAMC." },

  // ============== C. AREA AGENCIES ON AGING (AAA) — 9 ==============
  { section: "AAA", title: "Philadelphia Corporation for Aging (PCA)", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Philadelphia", website_url: "https://www.pcacares.org/", source_name: "Philadelphia Corporation for Aging", source_type: "nonprofit_organization", phone: "215-765-9040", address: "642 N Broad St, Philadelphia, PA 19130", zip: "19130", desc: "Philadelphia Corporation for Aging (PCA) — designated AAA for Philadelphia; older-adult senior centers, Meals on Wheels, in-home services (OPTIONS), caregiver support, APPRISE Medicare counseling, ombudsman, transportation. Older veterans receive PCA + VA Caregiver Support Program coordination." },
  { section: "AAA", title: "Bucks County Area Agency on Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Doylestown", website_url: "https://www.buckscounty.gov/202/Area-Agency-on-Aging", source_name: "Bucks County Government", source_type: "county_government", phone: "267-880-5700", address: "30 E Oakland Ave, Doylestown, PA 18901", zip: "18901", desc: "Bucks County AAA — county-designated Area Agency on Aging serving 60+; senior centers, Meals on Wheels, in-home services (OPTIONS waiver), caregiver support, APPRISE Medicare counseling, protective services, transportation. Coordinates with Bucks CVSO for older-veteran intake." },
  { section: "AAA", title: "Berks County Area Agency on Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Reading", website_url: "https://www.berkspa.gov/departments/aging", source_name: "Berks County Government", source_type: "county_government", phone: "610-478-6500", address: "633 Court St 8th Fl, Reading, PA 19601", zip: "19601", desc: "Berks County AAA — county-designated Area Agency on Aging serving 60+; senior centers (Reading/Boyertown/Hamburg/Kutztown), Meals on Wheels, in-home services (OPTIONS), caregiver support, APPRISE Medicare counseling, protective services. Coordinates with Berks CVSO for older-veteran intake." },
  { section: "AAA", title: "Westmoreland County Area Agency on Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Greensburg", website_url: "https://www.co.westmoreland.pa.us/164/Area-Agency-on-Aging", source_name: "Westmoreland County Government", source_type: "county_government", phone: "724-830-4444", address: "2482 S Grande Blvd, Greensburg, PA 15601", zip: "15601", desc: "Westmoreland County AAA — county-designated Area Agency on Aging serving 60+; 19 senior centers, Meals on Wheels, in-home services (OPTIONS), caregiver support, APPRISE Medicare counseling, protective services, transportation. Coordinates with Westmoreland CVSO." },
  { section: "AAA", title: "Luzerne County Aging Agency", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Wilkes-Barre", website_url: "https://www.luzernecounty.org/189/Aging", source_name: "Luzerne County Government", source_type: "county_government", phone: "570-822-1158", address: "111 N Wilkes-Barre Blvd, Wilkes-Barre, PA 18702", zip: "18702", desc: "Luzerne/Wyoming Counties Aging Agency — county-designated Area Agency on Aging serving 60+; senior centers, Meals on Wheels, in-home services (OPTIONS), caregiver support, APPRISE Medicare counseling, protective services. Coordinates with Luzerne CVSO and Wilkes-Barre VAMC." },
  { section: "AAA", title: "Cumberland County Office of Aging & Community Services", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Carlisle", website_url: "https://www.cumberlandcountypa.gov/110/Aging", source_name: "Cumberland County Government", source_type: "county_government", phone: "717-240-6110", address: "1100 Claremont Rd, Carlisle, PA 17013", zip: "17013", desc: "Cumberland County Office of Aging — county-designated Area Agency on Aging serving 60+; senior centers, Meals on Wheels, in-home services (OPTIONS), caregiver support, APPRISE Medicare counseling, protective services. Coordinates with Mechanicsburg VA OPC and Carlisle Barracks." },
  { section: "AAA", title: "Area Agency on Aging of Lehigh Valley (Lehigh+Northampton)", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Allentown", website_url: "https://www.aaalv.com/", source_name: "AAA of Lehigh Valley", source_type: "nonprofit_organization", phone: "610-871-9091", address: "2200 Hanover Ave, Allentown, PA 18109", zip: "18109", desc: "Area Agency on Aging of Lehigh Valley — designated AAA for Lehigh & Northampton counties; senior centers, Meals on Wheels, in-home services (OPTIONS waiver), caregiver support, APPRISE Medicare counseling, protective services, ombudsman. Coordinates with Lehigh & Northampton CVSOs and Allentown VA OPC." },
  { section: "AAA", title: "Center County Office for Aging (COCAA-affiliated)", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "State College", website_url: "https://www.cocaa.com/", source_name: "Centre County Office of Aging Network", source_type: "nonprofit_organization", phone: "814-355-6716", address: "420 Holmes St, Bellefonte, PA 16823", zip: "16823", desc: "Centre County Office for Aging — county-designated Area Agency on Aging serving 60+ in Centre County; senior centers (State College/Bellefonte/Philipsburg), Meals on Wheels, in-home services, caregiver support, APPRISE Medicare counseling. Coordinates with Centre CVSO." },
  { section: "AAA", title: "Lycoming-Clinton Counties Area Agency on Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Williamsport", website_url: "https://www.lyco.org/Departments/Aging", source_name: "Lycoming County Government", source_type: "county_government", phone: "570-323-3096", address: "200 E Street, Williamsport, PA 17701", zip: "17701", desc: "Lycoming-Clinton AAA — bi-county Area Agency on Aging serving 60+ in Lycoming and Clinton; senior centers, Meals on Wheels, in-home services (OPTIONS), caregiver support, APPRISE Medicare counseling, protective services. Coordinates with Lycoming CVSO and Williamsport VA OPC." },

  // ============== D. COUNTY WORKFORCE / CAREERLINK REGIONAL — 3 ==============
  { section: "CL", title: "PA CareerLink Lehigh Valley", cat: "employment", sub: "DVOP / Workforce Programs", city: "Allentown", website_url: "https://www.careerlinklehighvalley.org/", source_name: "Lehigh Valley Workforce Development Board", source_type: "regional_workforce_board", phone: "610-437-5627", address: "1601 Union Blvd, Allentown, PA 18109", zip: "18109", desc: "PA CareerLink Lehigh Valley — regional American Job Center for Lehigh & Northampton counties; DVOP (Disabled Veterans' Outreach) + LVER (Local Veterans' Employment Rep) staff serve PA veterans first under JVSG. Resume help, job-search workshops, training scholarships (WIOA), apprenticeship referrals." },
  { section: "CL", title: "PA CareerLink Pittsburgh / Allegheny", cat: "employment", sub: "DVOP / Workforce Programs", city: "Pittsburgh", website_url: "https://www.careerlinkpittsburgh.com/", source_name: "Partner4Work / Allegheny Workforce Development Board", source_type: "regional_workforce_board", phone: "412-552-7090", address: "425 Sixth Ave Suite 1100, Pittsburgh, PA 15219", zip: "15219", desc: "PA CareerLink Pittsburgh / Allegheny County — regional American Job Center; DVOP/LVER staff serve PA veterans first under JVSG. Resume help, job-search workshops, training scholarships (WIOA), apprenticeship referrals, SCSEP for older workers, Reentry employment programs." },
  { section: "CL", title: "PA CareerLink Berks County", cat: "employment", sub: "DVOP / Workforce Programs", city: "Reading", website_url: "https://www.careerlinkberks.com/", source_name: "Berks County Workforce Development Board", source_type: "regional_workforce_board", phone: "610-988-1300", address: "1920 Kutztown Rd, Reading, PA 19604", zip: "19604", desc: "PA CareerLink Berks County — regional American Job Center; DVOP/LVER staff serve PA veterans first under JVSG. Resume help, job-search workshops, training scholarships (WIOA), apprenticeship referrals, on-the-job training reimbursements for employers hiring veterans." },
];

runSeed(ROWS, { state: "PA", commit: COMMIT, scriptName: "seed-pa-p3.ts", urlCheckTimeoutMs: 12000 });
