/**
 * Texas ROUND 2 — Phase 3: County Network Strong (Florida SOP)
 * County VSOs in counties not yet loaded + county-level supporting orgs.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  // CVSO — County Veterans Service Offices (TVC-accredited, in counties not yet loaded)
  { section: "CVSO", title: "Galveston County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Galveston", website_url: "https://www.galvestoncountytx.gov/government/departments/veterans-services", source_name: "Galveston County", source_type: "cvso", phone: "409-770-5620", address: "722 Moody Ave, Galveston, TX 77550", zip: "77550", desc: "Galveston County's TVC-accredited County Veterans Service Office providing free claims-assistance representation for service-connected disability, pension, education, healthcare enrollment, and survivor benefits to Galveston County veterans, dependents, and survivors. Branch office in League City." },
  { section: "CVSO", title: "Brazoria County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Angleton", website_url: "https://www.brazoriacountytx.gov/departments/veterans-services", source_name: "Brazoria County", source_type: "cvso", phone: "979-864-1860", address: "451 N Velasco St, Angleton, TX 77515", zip: "77515", desc: "Brazoria County's TVC-accredited County Veterans Service Office providing free claims representation for service-connected disability, pension, education, healthcare, and survivor benefits to Brazoria County veterans (Angleton, Pearland, Lake Jackson, Alvin, Freeport)." },
  { section: "CVSO", title: "Fort Bend County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Richmond", website_url: "https://www.fortbendcountytx.gov/government/departments/social-services/veterans-services", source_name: "Fort Bend County", source_type: "cvso", phone: "281-238-3370", address: "4520 Reading Rd, Rosenberg, TX 77471", zip: "77471", desc: "Fort Bend County's TVC-accredited County Veterans Service Office providing free claims representation, benefits navigation, and burial assistance to Fort Bend County veterans (Richmond, Rosenberg, Sugar Land, Missouri City, Stafford, Katy)." },
  { section: "CVSO", title: "Montgomery County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Conroe", website_url: "https://www.mctx.org/departments/departments_d_-_f/department_of_veteran_services.php", source_name: "Montgomery County", source_type: "cvso", phone: "936-538-8163", address: "1400 S Loop 336 W, Conroe, TX 77304", zip: "77304", desc: "Montgomery County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Montgomery County veterans (Conroe, The Woodlands, Magnolia, Montgomery, Willis, Splendora, New Caney)." },
  { section: "CVSO", title: "Collin County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "McKinney", website_url: "https://www.collincountytx.gov/veteran_services/", source_name: "Collin County", source_type: "cvso", phone: "972-548-5570", address: "825 N McDonald St, McKinney, TX 75069", zip: "75069", desc: "Collin County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Collin County veterans (McKinney, Plano, Frisco, Allen, Wylie, Prosper, Celina). Texas Veterans Cup-of-Joe quarterly outreach events." },
  { section: "CVSO", title: "Denton County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Denton", website_url: "https://www.dentoncounty.gov/Departments/Veterans-Services", source_name: "Denton County", source_type: "cvso", phone: "940-349-2950", address: "401 W Hickory St, Denton, TX 76201", zip: "76201", desc: "Denton County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Denton County veterans (Denton, Lewisville, Flower Mound, Carrollton, Frisco-Denton portion, The Colony, Little Elm)." },
  { section: "CVSO", title: "Williamson County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Georgetown", website_url: "https://www.wilco.org/Departments/Veteran-Services", source_name: "Williamson County", source_type: "cvso", phone: "512-943-1900", address: "100 Wilco Way, Georgetown, TX 78626", zip: "78626", desc: "Williamson County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Williamson County veterans (Georgetown, Round Rock, Cedar Park, Leander, Pflugerville, Hutto, Liberty Hill, Taylor)." },
  { section: "CVSO", title: "Hays County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "San Marcos", website_url: "https://hayscountytx.gov/veteran-services/", source_name: "Hays County", source_type: "cvso", phone: "512-393-2261", address: "401-B Broadway St, San Marcos, TX 78666", zip: "78666", desc: "Hays County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Hays County veterans (San Marcos, Buda, Kyle, Dripping Springs, Wimberley)." },
  { section: "CVSO", title: "Comal County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "New Braunfels", website_url: "https://www.co.comal.tx.us/VS.htm", source_name: "Comal County", source_type: "cvso", phone: "830-221-1170", address: "178 E Mill St, New Braunfels, TX 78130", zip: "78130", desc: "Comal County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Comal County veterans (New Braunfels, Canyon Lake, Bulverde, Spring Branch, Garden Ridge)." },
  { section: "CVSO", title: "Guadalupe County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Seguin", website_url: "https://www.co.guadalupe.tx.us/veterans/", source_name: "Guadalupe County", source_type: "cvso", phone: "830-303-8856", address: "211 W Court St, Seguin, TX 78155", zip: "78155", desc: "Guadalupe County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Guadalupe County veterans (Seguin, Schertz, Cibolo, Marion, Selma)." },
  { section: "CVSO", title: "Smith County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Tyler", website_url: "https://www.smith-county.com/government/departments/veterans-services", source_name: "Smith County", source_type: "cvso", phone: "903-590-2950", address: "200 E Ferguson St, Tyler, TX 75702", zip: "75702", desc: "Smith County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Smith County veterans (Tyler, Lindale, Whitehouse, Bullard, Troup). Hosts the East Texas Veterans Resource Fair annually." },
  { section: "CVSO", title: "Gregg County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Longview", website_url: "https://www.co.gregg.tx.us/page/gregg.veteran.services", source_name: "Gregg County", source_type: "cvso", phone: "903-237-2664", address: "101 E Methvin St, Longview, TX 75601", zip: "75601", desc: "Gregg County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Gregg County veterans (Longview, Kilgore, White Oak, Gladewater)." },
  { section: "CVSO", title: "Bowie County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "New Boston", website_url: "https://www.co.bowie.tx.us/page/bowie.veteran.services", source_name: "Bowie County", source_type: "cvso", phone: "903-628-6730", address: "710 James Bowie Dr, New Boston, TX 75570", zip: "75570", desc: "Bowie County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Bowie County veterans (Texarkana, New Boston, Hooks, DeKalb, Wake Village)." },
  { section: "CVSO", title: "Wichita County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Wichita Falls", website_url: "https://www.co.wichita.tx.us/237/Veterans-Services", source_name: "Wichita County", source_type: "cvso", phone: "940-766-8131", address: "600 Scott Ave, Wichita Falls, TX 76301", zip: "76301", desc: "Wichita County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Wichita County veterans (Wichita Falls, Burkburnett, Iowa Park, Electra) including Sheppard AFB retirees." },
  { section: "CVSO", title: "Taylor County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Abilene", website_url: "https://www.taylorcountytexas.org/197/Veteran-Services", source_name: "Taylor County", source_type: "cvso", phone: "325-674-1295", address: "400 Oak St, Abilene, TX 79602", zip: "79602", desc: "Taylor County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Taylor County veterans (Abilene, Tye, Merkel, Buffalo Gap) including Dyess AFB retirees and active-duty members in transition." },
  { section: "CVSO", title: "Tom Green County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "San Angelo", website_url: "https://www.co.tom-green.tx.us/page/tomgreen.Veteran.Services", source_name: "Tom Green County", source_type: "cvso", phone: "325-655-7261", address: "122 W Henry St, San Angelo, TX 76903", zip: "76903", desc: "Tom Green County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Tom Green County veterans (San Angelo, Wall) including Goodfellow AFB retirees and active-duty members in transition." },
  { section: "CVSO", title: "Webb County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Laredo", website_url: "https://www.webbcountytx.gov/CountyClerk/VeteranServices.html", source_name: "Webb County", source_type: "cvso", phone: "956-523-4022", address: "1110 Washington St, Laredo, TX 78040", zip: "78040", desc: "Webb County's TVC-accredited County Veterans Service Office providing free bilingual claims representation and benefits navigation to Webb County veterans (Laredo region). Coordinates with VA Texas Valley Coastal Bend Laredo CBOC." },
  { section: "CVSO", title: "Cameron County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Brownsville", website_url: "https://www.cameroncountytx.gov/veterans-services/", source_name: "Cameron County", source_type: "cvso", phone: "956-983-5450", address: "964 E Harrison St, Brownsville, TX 78520", zip: "78520", desc: "Cameron County's TVC-accredited County Veterans Service Office providing free bilingual claims representation and benefits navigation to Cameron County veterans (Brownsville, Harlingen, San Benito, Los Fresnos, Port Isabel)." },
  { section: "CVSO", title: "Hidalgo County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Edinburg", website_url: "https://www.hidalgocounty.us/2068/Veterans-Service", source_name: "Hidalgo County", source_type: "cvso", phone: "956-318-2645", address: "2812 S Business Hwy 281, Edinburg, TX 78539", zip: "78539", desc: "Hidalgo County's TVC-accredited County Veterans Service Office providing free bilingual claims representation and benefits navigation to Hidalgo County veterans (McAllen, Edinburg, Mission, Pharr, Weslaco, Donna)." },
  { section: "CVSO", title: "Nueces County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Corpus Christi", website_url: "https://www.nuecesco.com/county-services/veterans-services", source_name: "Nueces County", source_type: "cvso", phone: "361-888-0292", address: "901 Leopard St, Corpus Christi, TX 78401", zip: "78401", desc: "Nueces County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Nueces County veterans (Corpus Christi, Robstown, Port Aransas, Bishop) including NAS Corpus Christi retirees." },
  { section: "CVSO", title: "Lubbock County Veterans Assistance", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Lubbock", website_url: "https://www.lubbockcounty.gov/county-departments/veterans-services", source_name: "Lubbock County", source_type: "cvso", phone: "806-775-1640", address: "916 Main St, Lubbock, TX 79401", zip: "79401", desc: "Lubbock County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Lubbock County veterans (Lubbock, Slaton, Wolfforth, Idalou)." },
  { section: "CVSO", title: "Potter County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Amarillo", website_url: "https://www.co.potter.tx.us/page/potter.Veteran.Services", source_name: "Potter County", source_type: "cvso", phone: "806-379-2348", address: "500 S Fillmore St, Amarillo, TX 79101", zip: "79101", desc: "Potter County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Potter County veterans (Amarillo) and surrounding Texas Panhandle counties. Coordinates with the VA Amarillo Health Care System." },
  { section: "CVSO", title: "Midland County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Midland", website_url: "https://www.midlandcountytx.com/272/Veterans-Services-Office", source_name: "Midland County", source_type: "cvso", phone: "432-688-1077", address: "200 W Wall St, Midland, TX 79701", zip: "79701", desc: "Midland County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Midland County veterans (Midland) and the surrounding Permian Basin." },
  { section: "CVSO", title: "Ector County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Odessa", website_url: "https://www.co.ector.tx.us/page/ector.Veteran.Services", source_name: "Ector County", source_type: "cvso", phone: "432-498-4080", address: "1010 E 8th St, Odessa, TX 79761", zip: "79761", desc: "Ector County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Ector County veterans (Odessa) and the surrounding Permian Basin." },
  { section: "CVSO", title: "Brazos County Veterans Service Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Bryan", website_url: "https://www.brazoscountytx.gov/162/Veterans-Service-Office", source_name: "Brazos County", source_type: "cvso", phone: "979-361-4321", address: "4001 E 29th St, Bryan, TX 77802", zip: "77802", desc: "Brazos County's TVC-accredited County Veterans Service Office providing free claims representation and benefits navigation to Brazos County veterans (Bryan, College Station) and Texas A&M-affiliated student veterans." },
];

console.log(`[seed-tx-r2-phase3] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "TX", commit: COMMIT, scriptName: "TX Round 2 — Phase 3: County Network",
  batchTag: "tx-r2-phase3", allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: { CVSO: "County Veterans Service Offices (TVC-accredited)" },
}).catch((e) => { console.error(e); process.exit(1); });
