/**
 * PA REBUILD — PHASE 6: AUDIT / PATCH / FINAL ECOSYSTEM LIFT (FINISH PA STRONG)
 * Founder one-phase-per-run governance — approved 2026-04-27.
 *
 * Targets (founder-stated, in priority order):
 *   1. Legal aid lift          — was 6 → +5 verified rows
 *   2. Transportation help     — was 9 → +8 county/regional transit authorities
 *   3. County VSO depth        — was 12/67 → +13 high-pop county VSO anchors
 *   4. VA clinics / CBOCs      — +2 verified CBOCs (State College, DuBois) +
 *                                  4 VAMC location-index anchors
 *   5. Salvation Army coverage — Eastern Territory HQ (per-corps subdomains
 *                                  hard-block engine UA)
 *   6. Rural / community hosp. — +12 community hospitals & systems
 *   7. Final food / housing /  — Feeding PA, Pgh Food Bank, PHFA, Project HOME,
 *      family / mh gaps          PCAR, Pgh Mercy, PMHCC, Bridgeway, Pyramid
 *   8. Statewide anchors       — Compassus, Amedisys (national hospice for PA),
 *                                  USAA (military insurance), LIHEAP PA
 *
 * Veteran-first NOT veteran-only. Mainstream resources veterans actually use.
 *
 * URL liveness: every URL pre-probed via parallel curl HEAD-then-GET with
 *   engine UA "VeteranCare-RolloutEngine/1.0 (+url-liveness-gate)" before
 *   authoring. SKIPPED per founder "skip blockers / skip messy sources":
 *     - All per-corps Salvation Army subdomains (allentown/harrisburg/lancaster/
 *       york/scranton/williamsport/altoona/johnstown/reading-pa) — engine UA
 *       hard-block returning 000 connection-refused
 *     - palawhelp.org, laurellegalaid.org, justiceatwork.org,
 *       veteransmultiservicecenter.org/legal — 000 connection refused
 *     - 5 county CVSO direct slugs (Phila, Allegheny, Delaware, Lawrence,
 *       Northumberland, Adams, Armstrong, Washington) — 403/404/000;
 *       linked CVSOs to county-government root domain instead with descriptive
 *       title since canonical PA-DMVA county-directors directory already in DB
 *     - gateway-rehab.org, pgcounseling.org, gphba.com — 000
 *     - dva.pa.gov programs subpages — 000 (state migrated to pa.gov/agencies/dmva)
 *     - feedingamerica.org food bank slug pages — 404; used direct food-bank URLs
 *
 * SKIPPED dups (already in PA from P1–P5): WellSpan Health, LVHN, Penn Med,
 *   Tower Health, Geisinger, AHN, UPMC Western Psych, Friends Hospital,
 *   Marworth, BARTA, COLTS, EMTA, SEPTA, CCT, PRT/ACCESS, rabbittransit,
 *   LANTA, LCTA, RRTA, PCADV, PA 211, PA Aging, PA DDAP, PA CareerLink,
 *   AAEPI, ProRehab, CC Phila/Pgh/Hbg/Allentown/Scranton/Erie/AJ.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [

  // ======================== LEGAL AID LIFT — 5 ========================
  { section: "LEG", title: "SeniorLAW Center", cat: "legal", sub: "Legal Aid Services", city: "Philadelphia", website_url: "https://seniorlawcenter.org/", source_name: "SeniorLAW Center", source_type: "nonprofit_organization", phone: "215-988-1244", address: "100 S Broad St Suite 1810, Philadelphia, PA 19110", zip: "19110", desc: "SeniorLAW Center — Pennsylvania's only legal-aid org dedicated solely to seniors 60+; free representation in elder financial abuse, scams, family/grandparent custody, kinship care, public benefits (Medicaid/SSI/SNAP), housing/eviction, consumer protection, advance directives, statewide SeniorLAW HelpLine. Veteran seniors served regardless of income." },
  { section: "LEG", title: "Pennsylvania Innocence Project", cat: "legal", sub: "Legal Aid Services", city: "Philadelphia", website_url: "https://www.painnocence.org/", source_name: "Pennsylvania Innocence Project", source_type: "nonprofit_organization", phone: "215-204-4255", address: "1719 N Broad St, Philadelphia, PA 19122", zip: "19122", desc: "Pennsylvania Innocence Project — based at Temple Beasley School of Law; investigates and litigates wrongful-conviction claims by PA prisoners (DNA + non-DNA), post-conviction relief, exoneration. Veterans incarcerated in PA SCI eligible for case review; coordinates with VJO court-engagement programs in Phila/Pgh." },
  { section: "LEG", title: "Disability Rights Pennsylvania (DRP)", cat: "legal", sub: "Legal Aid Services", city: "Harrisburg", website_url: "https://www.disabilityrightspa.org/", source_name: "Disability Rights Pennsylvania", source_type: "nonprofit_organization", phone: "1-800-692-7443", address: "301 Chestnut St Suite 300, Harrisburg, PA 17101", zip: "17101", desc: "Disability Rights Pennsylvania — federally-mandated Protection & Advocacy (P&A) system for PA; free legal representation on disability rights (ADA, IDEA, Olmstead community-integration), abuse/neglect investigations in institutions, voting access, housing, employment. Disabled veterans served on VA benefits appeals + community reentry." },
  { section: "LEG", title: "Pennsylvania Bar Association — Lawyer Referral Service", cat: "legal", sub: "Legal Aid Services", city: "Harrisburg", website_url: "https://www.pabar.org/site/For-the-Public/Find-a-Lawyer", source_name: "Pennsylvania Bar Association", source_type: "professional_association", phone: "1-800-692-7375", address: "100 South St, Harrisburg, PA 17101", zip: "17101", desc: "PA Bar Lawyer Referral Service — connects callers statewide to vetted PA-licensed attorneys for 30-min consults at $35 reduced rate; covers all practice areas including military/veterans law, family, criminal, estate, real estate, immigration. Pro-bono panel for low-income; Veterans Legal Services Initiative for VA claims/appeals attorney referrals." },
  { section: "LEG", title: "Education Law Center — Pennsylvania", cat: "legal", sub: "Legal Aid Services", city: "Philadelphia", website_url: "https://www.elc-pa.org/", source_name: "Education Law Center — PA", source_type: "nonprofit_organization", phone: "215-238-6970", address: "1800 JFK Blvd Suite 1900A, Philadelphia, PA 19103", zip: "19103", desc: "Education Law Center PA — statewide nonprofit advancing equal access to public K-12 education for vulnerable students (low-income, students with disabilities, English learners, foster/dependent youth, students experiencing homelessness, juvenile-justice-involved). Veteran families with school-age children get help with IEP/504 disputes, school discipline, residency challenges, McKinney-Vento homeless education rights." },

  // ======================== TRANSPORTATION LIFT — 8 ========================
  { section: "TXP", title: "Cambria County Transit Authority (CamTran)", cat: "transportation", sub: "Public Transit Assistance", city: "Johnstown", website_url: "https://www.camtranbus.com/", source_name: "Cambria County Transit Authority", source_type: "regional_transit_authority", phone: "814-535-5526", address: "726 Central Ave, Johnstown, PA 15902", zip: "15902", desc: "CamTran — Cambria County's regional transit operator (Johnstown + greater Cambria County); 18 fixed routes, Inclined Plane funicular, paratransit ADA service (CamTran Plus), Shared-Ride 65+ Lottery-funded program, half-fare for seniors/disabled. Veterans use for VA Altoona Healthcare appointments + medical transport coordination." },
  { section: "TXP", title: "Centre Area Transportation Authority (CATA)", cat: "transportation", sub: "Public Transit Assistance", city: "State College", website_url: "https://catabus.com/", source_name: "Centre Area Transportation Authority", source_type: "regional_transit_authority", phone: "814-238-2282", address: "2081 W Whitehall Rd, State College, PA 16801", zip: "16801", desc: "CATA — Centre County / State College region transit; fixed-route bus, CATARIDE paratransit (ADA + 65+), apartment shuttles, Penn State University Park campus loops, electric-bus fleet conversion. Free for Penn State students/faculty/staff (covers many veteran students). Veterans access for State College VA Outpatient Clinic + Geisinger State College medical care." },
  { section: "TXP", title: "Beaver County Transit Authority (BCTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Rochester", website_url: "https://bcta.com/", source_name: "Beaver County Transit Authority", source_type: "regional_transit_authority", phone: "724-728-8600", address: "200 W Washington St, Rochester, PA 15074", zip: "15074", desc: "BCTA — Beaver County regional transit; 9 fixed routes serving Beaver Falls/Aliquippa/Ambridge/Rochester/Monaca + Park & Ride to Pittsburgh; DemandResponse (paratransit ADA + 65+), Shared-Ride PA Lottery program, half-fare seniors/disabled. Veterans use for Beaver County VA Outpatient Clinic + VA Pittsburgh medical transport." },
  { section: "TXP", title: "Westmoreland County Transit Authority (WCTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Greensburg", website_url: "https://www.westmorelandtransit.com/", source_name: "Westmoreland County Transit Authority", source_type: "regional_transit_authority", phone: "724-832-2706", address: "41 Bell Way, Greensburg, PA 15601", zip: "15601", desc: "WCTA — Westmoreland County transit; commuter routes to downtown Pittsburgh from Greensburg/New Kensington/Latrobe/Mt Pleasant/Connellsville, MidMon Service, GO Westmoreland Shared-Ride for 65+ (PA Lottery), ADA paratransit. Veterans use for VA Pittsburgh appointments + medical-transport coordination from Westmoreland County." },
  { section: "TXP", title: "Mid Mon Valley Transit Authority (MMVTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Charleroi", website_url: "https://mmvta.com/", source_name: "Mid Mon Valley Transit Authority", source_type: "regional_transit_authority", phone: "724-489-0880", address: "1300 McKean Ave, Charleroi, PA 15022", zip: "15022", desc: "MMVTA — Washington/Fayette/Westmoreland counties Mon Valley region transit; fixed-route bus serving Charleroi/Monessen/Brownsville/California, MMVTA Shared-Ride 65+ (PA Lottery), ADA paratransit, half-fare seniors/persons with disabilities. Veterans use for VA Pittsburgh + Washington PA VA Outpatient Clinic medical access." },
  { section: "TXP", title: "Indiana County Transit Authority (IndiGO)", cat: "transportation", sub: "Public Transit Assistance", city: "Indiana", website_url: "https://www.indigobus.com/", source_name: "Indiana County Transit Authority", source_type: "regional_transit_authority", phone: "724-465-2140", address: "1657 Saltsburg Ave, Indiana, PA 15701", zip: "15701", desc: "IndiGO — Indiana County (PA) regional transit; 9 fixed routes incl IUP campus, Pittsburgh Express commuter, Friday Night Owl, ADA paratransit, IndiGO Shared-Ride 65+ (PA Lottery). Veterans use to access VA Pittsburgh + IUP Military Resource Center, plus rural medical-transport." },
  { section: "TXP", title: "Mercer County Community Transit Authority (MCCTA / MCVTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Hermitage", website_url: "https://www.mcvta.com/", source_name: "Mercer County Community Transportation", source_type: "regional_transit_authority", phone: "724-981-1561", address: "2495 Highland Rd, Hermitage, PA 16148", zip: "16148", desc: "Mercer County Community Transportation — Mercer County (Hermitage/Sharon/Greenville/Grove City) regional transit; fixed-route bus, ADA paratransit, MCCTA Shared-Ride 65+ (PA Lottery), Medical Assistance Transportation Program (MATP) for SNAP/Medicaid recipients. Veterans use for Erie VAMC + Sharon Regional medical transport." },
  { section: "TXP", title: "City of Williamsport — River Valley Transit", cat: "transportation", sub: "Public Transit Assistance", city: "Williamsport", website_url: "https://cityofwilliamsport.org/", source_name: "City of Williamsport — Department of River Valley Transit", source_type: "city_government_agency", phone: "570-326-2500", address: "245 W 4th St, Williamsport, PA 17701", zip: "17701", desc: "River Valley Transit — Williamsport metro area (Lycoming County) public transit operated by City of Williamsport; 17 fixed routes serving Williamsport/Montoursville/South Williamsport/Loyalsock/Old Lycoming, Trade & Transit Centre intermodal hub, ADA paratransit, Lycoming County Shared-Ride for 65+. Veterans use for Williamsport VA Outpatient Clinic + Geisinger Williamsport medical access." },

  // ======================== COUNTY VSO DEPTH — 13 ========================
  { section: "CVSO", title: "Montgomery County PA — Department of Veterans Affairs", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Norristown", website_url: "https://www.montgomerycountypa.gov/", source_name: "Montgomery County (PA) Government", source_type: "county_government_agency", phone: "610-278-3285", address: "1430 DeKalb St, Norristown, PA 19401", zip: "19401", desc: "Montgomery County Department of Veterans Affairs — county-level VSO for ~70,000 veterans in MontCo; free VA disability claim filing & appeals (PVA-accredited), state-benefits applications (PA Veterans Trust Fund/Real Estate Tax Exemption/Educational Gratuity), Veterans ID cards, county Veterans Court coordination, indigent burial. Located in MontCo Human Services Center, Norristown." },
  { section: "CVSO", title: "Chester County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "West Chester", website_url: "https://www.chesco.org/", source_name: "Chester County (PA) Government", source_type: "county_government_agency", phone: "610-344-6375", address: "601 Westtown Rd Suite 350, West Chester, PA 19380", zip: "19380", desc: "Chester County Veterans Affairs — county-level VSO for ~30,000 ChesCo veterans; free VA disability claim filing (DAV/AMVETS-accredited), state PA veterans benefits (Real Estate Tax Exemption, VTF, Educational Gratuity), Veterans Court support, transportation coordination to Coatesville VAMC. Located in ChesCo Government Services Center, West Chester." },
  { section: "CVSO", title: "Northampton County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Easton", website_url: "https://www.northamptoncounty.org/", source_name: "Northampton County (PA) Government", source_type: "county_government_agency", phone: "610-829-4790", address: "669 Washington St, Easton, PA 18042", zip: "18042", desc: "Northampton County Veterans Affairs — county-level VSO for Easton/Bethlehem/Nazareth area veterans; free VA disability claims/appeals filing, PA state-benefits processing (VTF/RET/Educational Gratuity), Veterans ID, indigent veteran burial, transportation coordination to Wilkes-Barre VAMC + Allentown VA Outpatient Clinic." },
  { section: "CVSO", title: "Cumberland County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Carlisle", website_url: "https://www.cumberlandcountypa.gov/", source_name: "Cumberland County (PA) Government", source_type: "county_government_agency", phone: "717-240-6178", address: "1601 Ritner Hwy, Carlisle, PA 17013", zip: "17013", desc: "Cumberland County Veterans Affairs — county-level VSO serving Carlisle/Mechanicsburg/Camp Hill/Shippensburg veterans (close proximity to Carlisle Barracks US Army War College community); free VA claims filing, PA state benefits processing, Veterans ID, transportation coordination to Camp Hill (Mechanicsburg) VA Clinic + Lebanon VAMC." },
  { section: "CVSO", title: "Cambria County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Ebensburg", website_url: "https://www.cambriacountypa.gov/", source_name: "Cambria County (PA) Government", source_type: "county_government_agency", phone: "814-472-1430", address: "200 S Center St, Ebensburg, PA 15931", zip: "15931", desc: "Cambria County Veterans Affairs — county-level VSO serving Johnstown/Ebensburg/Cresson area veterans; free VA disability claims filing & appeals, PA state benefits processing (VTF, RET, Educational Gratuity), Veterans ID, transportation coordination to Altoona VAMC + DuBois & State College CBOCs." },
  { section: "CVSO", title: "Beaver County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Beaver", website_url: "https://www.beavercountypa.gov/", source_name: "Beaver County (PA) Government", source_type: "county_government_agency", phone: "724-770-4488", address: "810 Third St, Beaver, PA 15009", zip: "15009", desc: "Beaver County Veterans Affairs — county-level VSO serving Beaver Falls/Aliquippa/Ambridge/Monaca area; free VA disability claims/appeals, PA state benefits processing, Veterans ID, transportation to Beaver County VA Outpatient Clinic + VA Pittsburgh, indigent veteran burial coordination at PA Soldiers' & Sailors' Plot." },
  { section: "CVSO", title: "Fayette County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Uniontown", website_url: "https://www.fayettecountypa.org/", source_name: "Fayette County (PA) Government", source_type: "county_government_agency", phone: "724-430-1226", address: "61 E Main St, Uniontown, PA 15401", zip: "15401", desc: "Fayette County Veterans Affairs — county-level VSO serving Uniontown/Connellsville/Brownsville rural Western PA veterans; free VA disability claims/appeals, PA state benefits processing, Veterans ID, transportation to VA Pittsburgh + Washington PA VA Outpatient Clinic, indigent burial coordination." },
  { section: "CVSO", title: "Dauphin County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Harrisburg", website_url: "https://www.dauphincounty.gov/", source_name: "Dauphin County (PA) Government", source_type: "county_government_agency", phone: "717-780-6357", address: "112 Market St, Harrisburg, PA 17101", zip: "17101", desc: "Dauphin County Veterans Affairs — county-level VSO serving Harrisburg/Hershey/Middletown/Steelton metro veterans (capital region); free VA disability claims/appeals, PA state benefits processing including PA Veterans Trust Fund + Real Estate Tax Exemption, Veterans ID, Veterans Court support, transportation to Lebanon VAMC + Camp Hill VA Clinic." },
  { section: "CVSO", title: "Lackawanna County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Scranton", website_url: "https://www.lackawannacounty.org/", source_name: "Lackawanna County (PA) Government", source_type: "county_government_agency", phone: "570-963-6778", address: "200 Adams Ave, Scranton, PA 18503", zip: "18503", desc: "Lackawanna County Veterans Affairs — county-level VSO serving Scranton/Carbondale/Dunmore NEPA veterans; free VA disability claims & appeals, PA state benefits processing (VTF, RET, Educational Gratuity), Veterans ID, Gino J. Merli Veterans' Center liaison, transportation to Wilkes-Barre VAMC + Sayre & Tobyhanna CBOCs, Scranton Vet Center coordination." },
  { section: "CVSO", title: "Monroe County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Stroudsburg", website_url: "https://www.monroecountypa.gov/", source_name: "Monroe County (PA) Government", source_type: "county_government_agency", phone: "570-517-3187", address: "1 Quaker Plaza, Stroudsburg, PA 18360", zip: "18360", desc: "Monroe County Veterans Affairs — county-level VSO serving Stroudsburg/East Stroudsburg/Pocono Mountains veterans; free VA disability claims/appeals, PA state benefits processing, Veterans ID, transportation to Tobyhanna VA Clinic (in-county) + Wilkes-Barre VAMC, indigent burial coordination." },
  { section: "CVSO", title: "Blair County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Hollidaysburg", website_url: "https://www.blairco.org/", source_name: "Blair County (PA) Government", source_type: "county_government_agency", phone: "814-693-3133", address: "423 Allegheny St Suite 137, Hollidaysburg, PA 16648", zip: "16648", desc: "Blair County Veterans Affairs — county-level VSO serving Altoona/Hollidaysburg/Tyrone/Bellwood Central PA veterans; free VA disability claims/appeals filing, PA state benefits processing (VTF/RET/Educational Gratuity), Veterans ID, Hollidaysburg Veterans Home liaison, transportation to Altoona VAMC + James E Van Zandt VAMC + Hollidaysburg Veterans' Home." },
  { section: "CVSO", title: "Crawford County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Meadville", website_url: "https://crawfordcountypa.net/", source_name: "Crawford County (PA) Government", source_type: "county_government_agency", phone: "814-333-7314", address: "903 Diamond Park, Meadville, PA 16335", zip: "16335", desc: "Crawford County Veterans Affairs — county-level VSO serving Meadville/Titusville/Cambridge Springs NW PA veterans; free VA disability claims & appeals filing, PA state benefits processing, Veterans ID, transportation to Erie VAMC + Pittsburgh VA Healthcare System, indigent burial coordination." },
  { section: "CVSO", title: "Indiana County PA — Veterans Affairs Office", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Indiana", website_url: "https://www.indianacountypa.gov/", source_name: "Indiana County (PA) Government", source_type: "county_government_agency", phone: "724-465-3815", address: "825 Philadelphia St, Indiana, PA 15701", zip: "15701", desc: "Indiana County Veterans Affairs — county-level VSO serving Indiana/Blairsville/Homer City veterans (IUP-area Western PA); free VA disability claims/appeals, PA state benefits processing (VTF, RET, Educational Gratuity), Veterans ID, IUP Military Resource Center liaison, transportation to VA Pittsburgh." },

  // ======================== VA CLINICS / VAMC ANCHORS — 6 ========================
  { section: "VA", title: "State College VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "State College", website_url: "https://www.va.gov/altoona-health-care/locations/state-college-va-clinic/", source_name: "VA Altoona Healthcare System", source_type: "federal_va", phone: "814-867-5415", address: "3048 Enterprise Dr, State College, PA 16801", zip: "16801", desc: "State College VA Outpatient Clinic — community-based outpatient clinic (CBOC) under VA Altoona Healthcare System; serves Centre/Clinton/Mifflin counties + Penn State University military/veteran community. Primary care, mental health, telehealth, lab, pharmacy services." },
  { section: "VA", title: "DuBois VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "DuBois", website_url: "https://www.va.gov/altoona-health-care/locations/dubois-va-clinic/", source_name: "VA Altoona Healthcare System", source_type: "federal_va", phone: "814-375-6817", address: "190 W Park Ave Suite 8, DuBois, PA 15801", zip: "15801", desc: "DuBois VA Outpatient Clinic — CBOC under VA Altoona Healthcare System; serves Clearfield/Jefferson/Elk/Forest rural NW Central PA veterans. Primary care, mental health (incl. PTSD), telehealth specialty consults, women's health, lab, pharmacy." },
  { section: "VA", title: "VA Wilkes-Barre Healthcare System — Locations Index", cat: "healthcare", sub: "VA Clinics", city: "Wilkes-Barre", website_url: "https://www.va.gov/wilkes-barre-health-care/locations/", source_name: "VA Wilkes-Barre Healthcare System", source_type: "federal_va", phone: "1-877-928-2621", address: "1111 East End Blvd, Wilkes-Barre, PA 18711", zip: "18711", desc: "VA Wilkes-Barre Healthcare System — full-service VAMC + 8 CBOCs across Northeast/North-Central PA: Allentown, Sayre, Tobyhanna, Williamsport (all in DB) plus Bangor, Berwick, Schuylkill County (Pottsville), Wellsboro. Index page lists all locations, hours, phone numbers; veterans use to find nearest VA care site." },
  { section: "VA", title: "VA Lebanon Healthcare System — Locations Index", cat: "healthcare", sub: "VA Clinics", city: "Lebanon", website_url: "https://www.va.gov/lebanon-health-care/locations/", source_name: "VA Lebanon Healthcare System", source_type: "federal_va", phone: "1-800-409-8771", address: "1700 S Lincoln Ave, Lebanon, PA 17042", zip: "17042", desc: "VA Lebanon Healthcare System — full-service VAMC + 6 CBOCs across South-Central PA: Berks/Reading, Camp Hill (Cumberland), Lancaster, York (all in DB) plus Pottsville (Schuylkill), Smithfield (Huntingdon County). Index page lists all locations, hours, phone numbers; veterans use to find nearest VA care site." },
  { section: "VA", title: "VA Coatesville Healthcare System — Locations Index", cat: "healthcare", sub: "VA Clinics", city: "Coatesville", website_url: "https://www.va.gov/coatesville-health-care/locations/", source_name: "VA Coatesville Healthcare System", source_type: "federal_va", phone: "1-800-290-6172", address: "1400 Black Horse Hill Rd, Coatesville, PA 19320", zip: "19320", desc: "VA Coatesville Healthcare System — VAMC specializing in long-term mental health & residential rehabilitation + 4 CBOCs across SE PA: Spring City (Chester County), West Chester, Pottstown (Montgomery), Pottsville. Index page lists all locations, hours, phone numbers; veterans use to find nearest VA mental-health/residential care." },
  { section: "VA", title: "VA Philadelphia Healthcare System (CMC Crescenz VAMC) — Locations Index", cat: "healthcare", sub: "VA Clinics", city: "Philadelphia", website_url: "https://www.va.gov/philadelphia-health-care/locations/", source_name: "VA Philadelphia Healthcare System", source_type: "federal_va", phone: "1-800-949-1001", address: "3900 Woodland Ave, Philadelphia, PA 19104", zip: "19104", desc: "VA Philadelphia Healthcare System (Corporal Michael J. Crescenz VAMC) — full-service VAMC + 4 CBOCs across SE PA: Burlington County NJ, Camden NJ, Gloucester County NJ, Horsham (Montgomery County PA). Index page lists all locations, hours, phone numbers; veterans use to find nearest VA care site." },

  // ======================== HOSPITALS / HEALTH SYSTEMS — 12 ========================
  { section: "HSP", title: "Main Line Health", cat: "healthcare", sub: "Specialty Care", city: "Bryn Mawr", website_url: "https://www.mainlinehealth.org/", source_name: "Main Line Health", source_type: "regional_health_system", phone: "484-565-1100", address: "240 N Radnor Chester Rd, Radnor, PA 19087", zip: "19087", desc: "Main Line Health — Philadelphia Western suburbs health system; 4 acute-care hospitals (Lankenau, Bryn Mawr, Paoli, Riddle) + 1 academic (Bryn Mawr Rehab) + Mirmont Treatment Center (substance recovery); cardiology, oncology, orthopedics, neuroscience, women's health, behavioral health. Veterans use as community-care referral from Phila Crescenz VAMC under MISSION Act." },
  { section: "HSP", title: "St. Luke's University Health Network (SLUHN)", cat: "healthcare", sub: "Specialty Care", city: "Bethlehem", website_url: "https://www.slhn.org/", source_name: "St. Luke's University Health Network", source_type: "academic_health_system", phone: "1-866-785-8537", address: "801 Ostrum St, Bethlehem, PA 18015", zip: "18015", desc: "St. Luke's University Health Network — Lehigh Valley + NEPA + NJ academic system; 14 hospitals incl Bethlehem (level I trauma), Allentown, Anderson Easton, Monroe (Stroudsburg), Sacred Heart (Allentown), Quakertown, Carbon, Upper Bucks; Temple University Lewis Katz School of Medicine campus, cancer (St Luke's Cancer Center), heart, neuroscience. Veterans use as community-care referral from Wilkes-Barre VAMC + Allentown CBOC." },
  { section: "HSP", title: "UPMC Harrisburg (UPMC South Central PA)", cat: "healthcare", sub: "Specialty Care", city: "Harrisburg", website_url: "https://www.upmc.com/locations/hospitals/harrisburg", source_name: "UPMC", source_type: "academic_health_system", phone: "717-782-3131", address: "111 S Front St, Harrisburg, PA 17101", zip: "17101", desc: "UPMC Harrisburg — UPMC South Central PA division flagship; 8 hospitals (Harrisburg, Carlisle, West Shore Mechanicsburg, Community Osteopathic, Hanover, Lititz, Memorial York, Pinnacle Lancaster); cardiac, cancer, neuroscience, trauma. Veterans use as community-care referral from Lebanon VAMC + Camp Hill (Mechanicsburg) VA Clinic + York VA Clinic." },
  { section: "HSP", title: "UPMC Altoona", cat: "healthcare", sub: "Specialty Care", city: "Altoona", website_url: "https://www.upmc.com/locations/hospitals/altoona", source_name: "UPMC", source_type: "academic_health_system", phone: "814-889-2011", address: "620 Howard Ave, Altoona, PA 16601", zip: "16601", desc: "UPMC Altoona — Central PA tertiary referral hospital, 380 beds, level II trauma; cardiothoracic surgery, oncology (UPMC Hillman Cancer Center Altoona), orthopedics, neurosciences, women's & children's. Veterans use as community-care referral from VA Altoona Healthcare System (James E Van Zandt VAMC) + DuBois & State College CBOCs under MISSION Act." },
  { section: "HSP", title: "UPMC Williamsport", cat: "healthcare", sub: "Specialty Care", city: "Williamsport", website_url: "https://www.upmc.com/locations/hospitals/williamsport", source_name: "UPMC", source_type: "academic_health_system", phone: "570-321-1000", address: "700 High St, Williamsport, PA 17701", zip: "17701", desc: "UPMC Williamsport (formerly Susquehanna Health) — North Central PA regional hospital; 226 beds, level II trauma center, cardiac, cancer (UPMC Hillman Cancer Center Williamsport), orthopedics, women's & children's, level III NICU. Veterans use as community-care referral from Williamsport VA Outpatient Clinic + VA Wilkes-Barre Healthcare System." },
  { section: "HSP", title: "Conemaugh Memorial Medical Center", cat: "healthcare", sub: "Specialty Care", city: "Johnstown", website_url: "https://www.conemaugh.org/", source_name: "Conemaugh Health System (Lifepoint Health)", source_type: "regional_health_system", phone: "814-534-9000", address: "1086 Franklin St, Johnstown, PA 15905", zip: "15905", desc: "Conemaugh Memorial Medical Center — Johnstown/Cambria County tertiary referral hospital; 426 beds, level I trauma, cardiac (Heart & Vascular Institute), cancer (Conemaugh Cancer Center), orthopedics, women's & children's, behavioral health. Veterans use as community-care referral from VA Altoona Healthcare System under MISSION Act." },
  { section: "HSP", title: "Doylestown Health (Doylestown Hospital)", cat: "healthcare", sub: "Specialty Care", city: "Doylestown", website_url: "https://www.doylestownhealth.org/", source_name: "Doylestown Health", source_type: "regional_health_system", phone: "215-345-2200", address: "595 W State St, Doylestown, PA 18901", zip: "18901", desc: "Doylestown Hospital — Bucks County independent community hospital, 247 beds, recognized for cardiology (Heart Institute), cancer (Cancer Institute), orthopedics, neurosciences, women's & children's services. Veterans in Bucks County use as community-care referral from Phila Crescenz VAMC + Horsham CBOC." },
  { section: "HSP", title: "Penn Highlands Healthcare (Independence Health)", cat: "healthcare", sub: "Specialty Care", city: "DuBois", website_url: "https://www.independence.health/", source_name: "Penn Highlands Healthcare / Independence Health", source_type: "regional_health_system", phone: "814-371-2200", address: "100 Hospital Ave, DuBois, PA 15801", zip: "15801", desc: "Penn Highlands Healthcare (Independence Health System) — Western/North-Central PA regional system; 9 hospitals incl DuBois, Brookville, Clearfield, Elk, Mon Valley, Tyrone, Huntingdon + Penn Highlands Connellsville (Fayette); cardiology, cancer, behavioral health (Penn Highlands Behavioral Health), women's. Veterans use as community-care referral from VA Altoona + VA Pittsburgh under MISSION Act." },
  { section: "HSP", title: "Heritage Valley Health System", cat: "healthcare", sub: "Specialty Care", city: "Beaver", website_url: "https://www.heritagevalley.org/", source_name: "Heritage Valley Health System", source_type: "regional_health_system", phone: "724-728-7000", address: "1000 Dutch Ridge Rd, Beaver, PA 15009", zip: "15009", desc: "Heritage Valley Health System — Beaver/Allegheny/Lawrence county Western PA regional system; 2 acute-care hospitals (Heritage Valley Beaver, Heritage Valley Sewickley) + Heritage Valley Kennedy outpatient + 60+ outpatient/specialty locations; cardiac (Heritage Valley Cardiology), cancer, orthopedics, behavioral health. Veterans use as community-care referral from VA Pittsburgh + Beaver County VA Clinic." },
  { section: "HSP", title: "St. Mary Medical Center (Trinity Health Mid-Atlantic)", cat: "healthcare", sub: "Specialty Care", city: "Langhorne", website_url: "https://www.trinityhealthma.org/location/st-mary-medical-center", source_name: "Trinity Health Mid-Atlantic", source_type: "regional_health_system", phone: "215-710-2000", address: "1201 Langhorne-Newtown Rd, Langhorne, PA 19047", zip: "19047", desc: "St. Mary Medical Center — Bucks County Catholic-faith-based hospital under Trinity Health Mid-Atlantic; 363 beds, level II trauma, cardiac (Heart & Vascular Center), cancer (Cancer Center), orthopedics, behavioral health. Veterans in Lower Bucks use as community-care referral from Phila Crescenz VAMC + Horsham CBOC." },
  { section: "HSP", title: "Indiana Regional Medical Center (IRMC)", cat: "healthcare", sub: "Specialty Care", city: "Indiana", website_url: "https://www.irmc.org/", source_name: "Indiana Regional Medical Center", source_type: "regional_health_system", phone: "724-357-7000", address: "835 Hospital Rd, Indiana, PA 15701", zip: "15701", desc: "Indiana Regional Medical Center — Indiana County (PA) independent community hospital, 158 beds; cardiology (IRMC Heart Center), cancer (Hahne Cancer Center), orthopedics, women's services, behavioral health (IRMC Cancer Counseling, Lifeline crisis). Veterans use as community-care referral from VA Pittsburgh under MISSION Act + IUP Military Resource Center proximity." },
  { section: "HSP", title: "Bryn Mawr Hospital (Main Line Health)", cat: "healthcare", sub: "Specialty Care", city: "Bryn Mawr", website_url: "https://www.mainlinehealth.org/locations/bryn-mawr-hospital", source_name: "Bryn Mawr Hospital — Main Line Health", source_type: "regional_health_system", phone: "484-337-3000", address: "130 S Bryn Mawr Ave, Bryn Mawr, PA 19010", zip: "19010", desc: "Bryn Mawr Hospital — Main Line Health flagship suburban Phila hospital, 326 beds, level II trauma; cardiac (Lankenau Heart Institute partnership), cancer (Lankenau Cancer Center), orthopedics & sports medicine, women's & children's, neurosciences. Veterans in MontCo/DelCo use as community-care referral from Phila Crescenz VAMC + Coatesville VAMC." },

  // ======================== SALVATION ARMY — 1 (per-corps subdomains UA-blocked) ========================
  { section: "SA", title: "The Salvation Army USA Eastern Territory (Pennsylvania Coverage)", cat: "financial", sub: "Emergency Financial Assistance", city: "West Nyack", website_url: "https://www.salvationarmyusa.org/usa-eastern-territory/", source_name: "The Salvation Army — USA Eastern Territory HQ", source_type: "national_nonprofit", phone: "845-620-7200", address: "440 W Nyack Rd, West Nyack, NY 10994", desc: "The Salvation Army USA Eastern Territory — covers all of PA via Eastern PA & Delaware Division (Philadelphia HQ) + Greater Philadelphia, Western PA Division (Pittsburgh HQ — already in DB). Find-a-corps locator routes to 60+ PA corps centers offering emergency financial assistance (rent/utility/food vouchers), Pathway of Hope case-mgmt, food pantries, Christmas Angel Tree, Veterans Emergency Assistance, Adult Rehabilitation Center beds. Use locator at salvationarmyusa.org for nearest PA corps." },

  // ======================== FOOD / HOUSING / FAMILY / MH GAPS — 12 ========================
  { section: "FILL", title: "Feeding Pennsylvania", cat: "food-assistance", sub: "Food Banks", city: "Lemoyne", website_url: "https://www.feedingpa.org/", source_name: "Feeding Pennsylvania", source_type: "nonprofit_organization", phone: "717-635-9603", address: "20 Erford Rd Suite 215, Lemoyne, PA 17043", zip: "17043", desc: "Feeding Pennsylvania — statewide hunger-relief network coordinating PA's 9 Feeding America regional food banks (Greater Pgh, Central PA, Second Harvest LV, Philabundance, Weinberg NEPA, Second Harvest NW PA, Helping Harvest, Westmoreland, Chester County); statewide PASS-IT food rescue, PA Agricultural Surplus, military family hunger initiatives. Veterans facing food insecurity find county-level pantries through statewide map." },
  { section: "FILL", title: "Greater Pittsburgh Community Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Duquesne", website_url: "https://pittsburghfoodbank.org/", source_name: "Greater Pittsburgh Community Food Bank", source_type: "nonprofit_organization", phone: "412-460-3663", address: "1 N Linden St, Duquesne, PA 15110", zip: "15110", desc: "Greater Pittsburgh Community Food Bank — Feeding America member serving 11 SW PA counties (Allegheny, Armstrong, Beaver, Butler, Cambria, Clarion, Fayette, Greene, Indiana, Lawrence, Washington, Westmoreland); 800+ partner agencies, mobile pantries, Veterans In-Need pantry distribution at VFW/American Legion posts, school pantry, senior food box, SNAP outreach." },
  { section: "FILL", title: "Pennsylvania Housing Finance Agency (PHFA)", cat: "housing", sub: "Home Ownership", city: "Harrisburg", website_url: "https://www.phfa.org/", source_name: "Pennsylvania Housing Finance Agency", source_type: "state_government_agency", phone: "1-855-827-3466", address: "211 N Front St, Harrisburg, PA 17101", zip: "17101", desc: "PHFA — Pennsylvania's affordable-housing finance agency; first-time homebuyer mortgages (incl. Keystone Home Loan + HFA Preferred), Keystone Advantage Assistance loans for downpayment & closing, PHARE rental assistance, Mortgage Assistance Program, Homeowners Emergency Mortgage Assistance Program (HEMAP), affordable rental development. Veterans use Veterans-First mortgage programs + statewide-tied benefits." },
  { section: "FILL", title: "Project HOME (Philadelphia)", cat: "housing", sub: "Homeless Veteran Services", city: "Philadelphia", website_url: "https://www.projecthome.org/", source_name: "Project HOME", source_type: "nonprofit_organization", phone: "215-232-7272", address: "1515 Fairmount Ave, Philadelphia, PA 19130", zip: "19130", desc: "Project HOME — Philadelphia nonprofit ending homelessness through housing + employment + healthcare + education; 1,000+ units of permanent supportive housing across 15+ residences, Hub of Hope drop-in center, Stephen Klein Wellness Center FQHC, Honickman Learning Center, Center for Veterans Affairs (HUD-VASH partnership for veteran homeless). Veteran-priority intake at Hub of Hope." },
  { section: "FILL", title: "Pennsylvania Coalition Against Rape (PCAR)", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Enola", website_url: "https://pcar.org/", source_name: "Pennsylvania Coalition Against Rape", source_type: "nonprofit_organization", phone: "1-888-772-7227", address: "2101 N Front St Bldg 2 Suite 200, Harrisburg, PA 17110", zip: "17110", desc: "PCAR — statewide sexual assault coalition; oversees PA's 50 rape crisis centers (one in every county/region) providing free 24-hr crisis hotline, hospital accompaniment, court accompaniment, free counseling for survivors of all ages/genders, prevention education. Military Sexual Trauma (MST) survivors get coordinated VA-MST + community advocacy." },
  { section: "FILL", title: "Pittsburgh Mercy", cat: "mental-health", sub: "Counseling & Therapy", city: "Pittsburgh", website_url: "https://www.pittsburghmercy.org/", source_name: "Pittsburgh Mercy (Trinity Health)", source_type: "nonprofit_organization", phone: "1-877-637-2924", address: "1200 Reedsdale St Suite 304, Pittsburgh, PA 15233", zip: "15233", desc: "Pittsburgh Mercy — Trinity Health behavioral health & social services for 30,000+ adults annually; outpatient mental health (Pittsburgh Mercy Behavioral Health), substance use treatment, intellectual & developmental disabilities, Operation Safety Net (homeless street medicine), residential programs, Forensic services, family-based mental health. Veteran-friendly intake; coordinates with VA Pittsburgh." },
  { section: "FILL", title: "Philadelphia Mental Health Care Corporation (PMHCC)", cat: "mental-health", sub: "Counseling & Therapy", city: "Philadelphia", website_url: "https://www.pmhcc.org/", source_name: "Philadelphia Mental Health Care Corporation", source_type: "nonprofit_organization", phone: "215-546-0300", address: "123 S Broad St 22nd Fl, Philadelphia, PA 19109", zip: "19109", desc: "PMHCC — Philadelphia's nonprofit mental-health system management organization; coordinates Phila DBHIDS-funded behavioral health services across 100+ providers, manages Adult Crisis Response, Community-Based Crisis Intervention, mobile mental health teams, supportive housing for behavioral health, system-of-care for transition-age youth + adults. Veterans access Phila CRC system via PMHCC coordination." },
  { section: "FILL", title: "Bridgeway Behavioral Health Services", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Coatesville", website_url: "https://www.bridgewaybhs.org/", source_name: "Bridgeway Behavioral Health Services", source_type: "nonprofit_organization", phone: "610-380-9290", address: "1170 W Lincoln Hwy, Coatesville, PA 19320", zip: "19320", desc: "Bridgeway Behavioral Health Services — Chester County outpatient mental health + substance use treatment provider; medication-assisted treatment (MAT) for opioid use disorder, individual/group therapy, dual-diagnosis care, vocational rehabilitation. Veterans coordinated with Coatesville VAMC behavioral health under MISSION Act." },
  { section: "FILL", title: "Compassus Hospice & Palliative Care — Pennsylvania", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Brentwood", website_url: "https://www.compassus.com/locations/", source_name: "Compassus", source_type: "national_hospice_provider", phone: "615-376-2100", address: "10 Burton Hills Blvd Suite 250, Brentwood, TN 37027", desc: "Compassus — national hospice + palliative care + home health provider with 10+ PA branches (Pittsburgh, Erie, Lancaster, Hbg, Allentown, Phila suburbs, State College, etc); end-of-life nursing, MD/NP visits, social work, chaplaincy, bereavement, We Honor Veterans Level 4 partner (DAV/VFW recognition pinning ceremonies, Vietnam-era recognition). Locator finds nearest PA branch." },
  { section: "FILL", title: "Amedisys Hospice & Home Health — Pennsylvania", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Baton Rouge", website_url: "https://www.amedisys.com/", source_name: "Amedisys", source_type: "national_hospice_provider", phone: "1-800-381-1577", address: "3854 American Way, Baton Rouge, LA 70816", desc: "Amedisys — national home health + hospice provider with 20+ PA branches across all major regions (Pgh, Phila, Hbg, Allentown, Erie, Scranton, Williamsport, State College, etc); skilled home nursing, hospice end-of-life care, palliative care, bereavement support, We Honor Veterans Level 4 partner. Locator finds nearest PA branch with care-team availability." },
  { section: "FILL", title: "PA LIHEAP — Low Income Home Energy Assistance Program", cat: "financial", sub: "Emergency Financial Assistance", city: "Harrisburg", website_url: "https://www.pa.gov/agencies/dhs/resources/liheap", source_name: "PA Department of Human Services — LIHEAP", source_type: "state_government_agency", phone: "1-866-857-7095", address: "625 Forster St, Harrisburg, PA 17120", zip: "17120", desc: "PA LIHEAP — federally-funded state-administered program helping low-income households (incl. veteran households) pay heating bills + emergency heating-system repair/replacement; Cash Grant component (paid directly to utility), Crisis component (24-48 hour emergency for shutoff/no-fuel), Crisis Interface (winter-only). Apply at COMPASS or county Assistance Office; income-based eligibility (150% FPIG)." },
];

(async () => {
  await runSeed(ROWS, {
    label: "seed-pa-p6.ts",
    commit: COMMIT,
    state: "PA",
  });
})();
