/**
 * OHIO — PHASE 2: HEALTHCARE FOUNDATION
 * Per locked national 6-phase SOP. ~55 rows:
 *   - VA CBOCs across OH (Cleveland, Columbus/Wylie, Cincinnati, Dayton, Chillicothe systems)
 *   - Vet Centers (OH)
 *   - Major OH hospital systems (anchors)
 *   - OH FQHCs (anchors per region)
 *   - County ADAMH boards (top metros)
 *   - Mobile crisis providers + recovery providers (boost mental-health, substance-recovery, crisis-help)
 *   - Healthcare nonprofits
 * Veteran-first / not veteran-only: includes both VA-system facilities and mainstream community healthcare.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ---- A. VA CBOCs — Cleveland system (6) ----
  { section: "CBOC", title: "Akron VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Akron", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/akron-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "330-344-7700", address: "55 W Waterloo Rd, Akron, OH 44319", zip: "44319", desc: "Akron VA Outpatient Clinic — VA Northeast Ohio HCS community-based outpatient clinic serving Summit & Portage county veterans. Primary care, mental health, lab, pharmacy, telehealth, and women's health." },
  { section: "CBOC", title: "Canton VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Canton", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/canton-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "330-489-4600", address: "733 Market Ave S, Canton, OH 44702", zip: "44702", desc: "Canton VA Outpatient Clinic — VA Northeast Ohio HCS community-based outpatient clinic serving Stark county veterans. Primary care, mental health, lab, pharmacy, telehealth, audiology, and social work." },
  { section: "CBOC", title: "Youngstown VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Youngstown", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "330-740-9200", address: "2031 Belmont Ave, Youngstown, OH 44505", zip: "44505", desc: "Youngstown VA Outpatient Clinic — VA Northeast Ohio HCS community-based outpatient clinic serving Mahoning, Trumbull, and Columbiana county veterans. Primary care, mental health, telehealth, women's health, lab, pharmacy." },
  { section: "CBOC", title: "Mansfield VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Mansfield", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "419-526-7155", address: "1456 Park Avenue West, Mansfield, OH 44906", zip: "44906", desc: "Mansfield VA Outpatient Clinic — VA Northeast Ohio HCS community-based outpatient clinic serving Richland and surrounding county veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Lorain VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Lorain", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/lorain-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "440-934-2000", address: "5275 N Abbe Rd, Elyria, OH 44035", zip: "44035", desc: "Lorain VA Outpatient Clinic — VA Northeast Ohio HCS community-based outpatient clinic serving Lorain county veterans. Primary care, mental health, women's health, telehealth, lab, pharmacy, social work." },
  { section: "CBOC", title: "Lake County (Painesville) VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Painesville", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/lake-county-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "440-358-2900", address: "7 W Jackson St, Painesville, OH 44077", zip: "44077", desc: "Lake County VA Outpatient Clinic — VA Northeast Ohio HCS community-based outpatient clinic in Painesville serving Lake and Geauga county veterans. Primary care, mental health, women's health, telehealth, lab, pharmacy." },

  // ---- A. VA CBOCs — Wylie/Columbus system (3) ----
  { section: "CBOC", title: "Marion VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Marion", website_url: "https://www.va.gov/central-ohio-health-care/locations/marion-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-223-8809", address: "1203 Delaware Ave, Marion, OH 43302", zip: "43302", desc: "Marion VA Outpatient Clinic — VA Central Ohio HCS community-based outpatient clinic serving Marion-area veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Newark VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Newark", website_url: "https://www.va.gov/central-ohio-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-788-8329", address: "1855 W Main St, Newark, OH 43055", zip: "43055", desc: "Newark VA Outpatient Clinic — VA Central Ohio HCS community-based outpatient clinic serving Licking county veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Zanesville VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Zanesville", website_url: "https://www.va.gov/central-ohio-health-care/locations/zanesville-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-453-7725", address: "2800 Maple Ave, Zanesville, OH 43701", zip: "43701", desc: "Zanesville VA Outpatient Clinic — VA Central Ohio HCS community-based outpatient clinic serving Muskingum-area veterans. Primary care, mental health, telehealth, lab, pharmacy." },

  // ---- A. VA CBOCs — Cincinnati system (2) ----
  { section: "CBOC", title: "Hamilton VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Hamilton", website_url: "https://www.va.gov/cincinnati-health-care/locations/hamilton-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "513-870-9444", address: "1755 S Erie Hwy, Hamilton, OH 45011", zip: "45011", desc: "Hamilton VA Outpatient Clinic — Cincinnati VA HCS community-based outpatient clinic serving Butler county veterans. Primary care, mental health, women's health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Clermont County VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Cincinnati", website_url: "https://www.va.gov/cincinnati-health-care/locations/clermont-county-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "513-943-3680", address: "4355 Ferguson Dr Suite 270, Cincinnati, OH 45245", zip: "45245", desc: "Clermont County VA Outpatient Clinic — Cincinnati VA HCS community-based outpatient clinic in Cincinnati's Eastgate area serving Clermont county and east-Cincinnati veterans. Primary care, mental health, telehealth, lab, pharmacy." },

  // ---- A. VA CBOCs — Dayton system (3) ----
  { section: "CBOC", title: "Lima VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Lima", website_url: "https://www.va.gov/dayton-health-care/locations/lima-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "419-227-1080", address: "1303 Bellefontaine Ave, Lima, OH 45804", zip: "45804", desc: "Lima VA Outpatient Clinic — Dayton VA HCS community-based outpatient clinic serving Allen and surrounding NW Ohio county veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Middletown VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Middletown", website_url: "https://www.va.gov/dayton-health-care/locations/middletown-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "513-423-8387", address: "4337 N Union Rd, Middletown, OH 45044", zip: "45044", desc: "Middletown VA Outpatient Clinic — Dayton VA HCS community-based outpatient clinic serving Butler/Warren-area veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Springfield VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Springfield", website_url: "https://www.va.gov/dayton-health-care/locations/springfield-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "937-328-3385", address: "512 S Burnett Rd, Springfield, OH 45505", zip: "45505", desc: "Springfield VA Outpatient Clinic — Dayton VA HCS community-based outpatient clinic serving Clark county veterans. Primary care, mental health, telehealth, lab, pharmacy." },

  // ---- A. VA CBOCs — Chillicothe system (3) ----
  { section: "CBOC", title: "Athens VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Athens", website_url: "https://www.va.gov/chillicothe-health-care/locations/athens-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-593-7314", address: "510 W Union St, Athens, OH 45701", zip: "45701", desc: "Athens VA Outpatient Clinic — Chillicothe VA HCS community-based outpatient clinic serving Athens and SE Ohio county veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Cambridge VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Cambridge", website_url: "https://www.va.gov/chillicothe-health-care/locations/cambridge-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-432-1963", address: "2146 Southgate Pkwy, Cambridge, OH 43725", zip: "43725", desc: "Cambridge VA Outpatient Clinic — Chillicothe VA HCS community-based outpatient clinic serving Guernsey and SE Ohio county veterans. Primary care, mental health, telehealth, lab, pharmacy." },
  { section: "CBOC", title: "Portsmouth VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Portsmouth", website_url: "https://www.va.gov/chillicothe-health-care/locations/portsmouth-va-clinic/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-353-3236", address: "840 Gallia St, Portsmouth, OH 45662", zip: "45662", desc: "Portsmouth VA Outpatient Clinic — Chillicothe VA HCS community-based outpatient clinic serving Scioto and S Ohio county veterans. Primary care, mental health, telehealth, lab, pharmacy." },

  // ---- B. VET CENTERS (6) ----
  { section: "VC", title: "Cleveland Heights Vet Center", cat: "mental-health", sub: "Vet Centers", city: "Cleveland Heights", website_url: "https://www.va.gov/find-locations/facility/vc_0306V", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "216-707-7901", address: "2210 Lee Rd Suite 300, Cleveland Heights, OH 44118", zip: "44118", desc: "Cleveland Heights Vet Center — VA Readjustment Counseling Service center serving combat-era veterans, MST survivors, and bereaved families across NE Ohio. Free individual + group counseling, family counseling, military sexual trauma counseling; confidential, no claim required." },
  { section: "VC", title: "McCafferty Outstation Vet Center (Cleveland)", cat: "mental-health", sub: "Vet Centers", city: "Cleveland", website_url: "https://www.va.gov/find-locations/facility/vc_0917V", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "216-939-0784", address: "4242 Lorain Ave, Cleveland, OH 44113", zip: "44113", desc: "McCafferty Outstation Vet Center — VA Readjustment Counseling Service outstation on Cleveland's west side. Free individual + group counseling, family counseling, MST counseling; confidential, no claim required." },
  { section: "VC", title: "Columbus Vet Center", cat: "mental-health", sub: "Vet Centers", city: "Columbus", website_url: "https://www.va.gov/find-locations/facility/vc_0312V", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "614-257-5550", address: "30 Spruce St, Columbus, OH 43215", zip: "43215", desc: "Columbus Vet Center — VA Readjustment Counseling Service center serving combat-era veterans, MST survivors, and bereaved families across central Ohio. Free individual + group counseling, family counseling, MST counseling; confidential, no claim required." },
  { section: "VC", title: "Cincinnati Vet Center", cat: "mental-health", sub: "Vet Centers", city: "Cincinnati", website_url: "https://www.va.gov/find-locations/facility/vc_0307V", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "513-763-3500", address: "7570 Beechmont Ave, Cincinnati, OH 45255", zip: "45255", desc: "Cincinnati Vet Center — VA Readjustment Counseling Service center serving combat-era veterans, MST survivors, and bereaved families across SW Ohio. Free individual + group counseling, family counseling, MST counseling; confidential, no claim required." },
  { section: "VC", title: "Dayton Vet Center", cat: "mental-health", sub: "Vet Centers", city: "Dayton", website_url: "https://www.va.gov/find-locations/facility/vc_0308V", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "937-461-9150", address: "627 Edwin C Moses Blvd Suite 3, Dayton, OH 45417", zip: "45417", desc: "Dayton Vet Center — VA Readjustment Counseling Service center serving combat-era veterans, MST survivors, and bereaved families across SW Ohio. Free individual + group counseling, family counseling, MST counseling; confidential, no claim required." },
  { section: "VC", title: "Toledo Vet Center", cat: "mental-health", sub: "Vet Centers", city: "Toledo", website_url: "https://www.va.gov/find-locations/facility/vc_0311V", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "419-213-7533", address: "1565 S Byrne Rd Suite 104, Toledo, OH 43614", zip: "43614", desc: "Toledo Vet Center — VA Readjustment Counseling Service center serving combat-era veterans, MST survivors, and bereaved families across NW Ohio. Free individual + group counseling, family counseling, MST counseling; confidential, no claim required." },

  // ---- C. MAJOR OH HOSPITALS (10) ----
  { section: "HOSP", title: "Cleveland Clinic Main Campus", cat: "healthcare", sub: "Specialty Care", city: "Cleveland", website_url: "https://my.clevelandclinic.org/", source_name: "Cleveland Clinic", source_type: "hospital_system", phone: "216-444-2200", address: "9500 Euclid Ave, Cleveland, OH 44195", zip: "44195", desc: "Cleveland Clinic Main Campus — flagship 1,400-bed academic medical center; Top-2 US News national-ranked hospital; #1 cardiology in US for 30+ consecutive years. Tertiary specialty care across all major service lines; veterans accepted via VA Community Care referral and TRICARE." },
  { section: "HOSP", title: "University Hospitals Cleveland Medical Center", cat: "healthcare", sub: "Specialty Care", city: "Cleveland", website_url: "https://www.uhhospitals.org/locations/uh-cleveland-medical-center", source_name: "University Hospitals", source_type: "hospital_system", phone: "216-844-1000", address: "11100 Euclid Ave, Cleveland, OH 44106", zip: "44106", desc: "University Hospitals Cleveland Medical Center — 1,032-bed academic medical center affiliated with Case Western Reserve University SOM. Seidman Cancer Center, Harrington Heart & Vascular, MacDonald Women's, Rainbow Babies & Children's. Veterans accepted via VA Community Care referral and TRICARE." },
  { section: "HOSP", title: "MetroHealth Medical Center", cat: "healthcare", sub: "Specialty Care", city: "Cleveland", website_url: "https://www.metrohealth.org/", source_name: "MetroHealth System", source_type: "hospital_system", phone: "216-778-7800", address: "2500 MetroHealth Dr, Cleveland, OH 44109", zip: "44109", desc: "MetroHealth Medical Center — 731-bed Cuyahoga County safety-net public hospital and Level I Adult & Pediatric Trauma Center. Burn center, comprehensive stroke center, sliding-scale primary care; the largest Medicaid provider in NE Ohio. Veterans accepted via VA Community Care and Medicaid." },
  { section: "HOSP", title: "OSU Wexner Medical Center", cat: "healthcare", sub: "Specialty Care", city: "Columbus", website_url: "https://wexnermedical.osu.edu/", source_name: "Ohio State University Wexner Medical Center", source_type: "hospital_system", phone: "614-293-5123", address: "410 W 10th Ave, Columbus, OH 43210", zip: "43210", desc: "Ohio State University Wexner Medical Center — 1,400-bed academic medical center; James Cancer Hospital (NCI-designated comprehensive cancer center), Ross Heart Hospital, Brain & Spine Hospital, University Hospital. Veterans accepted via VA Community Care and TRICARE." },
  { section: "HOSP", title: "OhioHealth Riverside Methodist Hospital", cat: "healthcare", sub: "Specialty Care", city: "Columbus", website_url: "https://www.ohiohealth.com/", source_name: "OhioHealth", source_type: "hospital_system", phone: "614-566-5000", address: "3535 Olentangy River Rd, Columbus, OH 43214", zip: "43214", desc: "OhioHealth Riverside Methodist Hospital — 1,059-bed flagship of OhioHealth system. McConnell Heart Hospital, Neuroscience Center, Bing Cancer Center, Level III trauma. Veterans accepted via VA Community Care and TRICARE." },
  { section: "HOSP", title: "UC Medical Center (UC Health)", cat: "healthcare", sub: "Specialty Care", city: "Cincinnati", website_url: "https://www.uchealth.com/locations/uc-medical-center/", source_name: "UC Health", source_type: "hospital_system", phone: "513-584-1000", address: "234 Goodman St, Cincinnati, OH 45219", zip: "45219", desc: "University of Cincinnati Medical Center — 695-bed academic medical center, Level I trauma, Comprehensive Stroke Center, UC Cancer Center (NCI-designated). Veterans accepted via VA Community Care and TRICARE." },
  { section: "HOSP", title: "TriHealth Bethesda North Hospital", cat: "healthcare", sub: "Specialty Care", city: "Cincinnati", website_url: "https://www.trihealth.com/hospitals-and-practices/bethesda-north-hospital", source_name: "TriHealth", source_type: "hospital_system", phone: "513-865-1111", address: "10500 Montgomery Rd, Cincinnati, OH 45242", zip: "45242", desc: "TriHealth Bethesda North Hospital — 374-bed acute-care hospital serving NE Cincinnati metro. Cardiology, women's, surgical specialty, Heart Institute. Veterans accepted via VA Community Care and TRICARE." },
  { section: "HOSP", title: "Premier Health Miami Valley Hospital", cat: "healthcare", sub: "Specialty Care", city: "Dayton", website_url: "https://www.premierhealth.com/locations/miami-valley-hospital", source_name: "Premier Health", source_type: "hospital_system", phone: "937-208-8000", address: "1 Wyoming St, Dayton, OH 45409", zip: "45409", desc: "Premier Health Miami Valley Hospital — 970-bed Level I Adult & Pediatric Trauma Center serving SW Ohio; CareFlight air-medical, Heart & Vascular Center, Stroke Center. Veterans accepted via VA Community Care and TRICARE." },
  { section: "HOSP", title: "ProMedica Toledo Hospital", cat: "healthcare", sub: "Specialty Care", city: "Toledo", website_url: "https://www.promedica.org/", source_name: "ProMedica", source_type: "hospital_system", phone: "419-291-4000", address: "2142 N Cove Blvd, Toledo, OH 43606", zip: "43606", desc: "ProMedica Toledo Hospital — 794-bed Level I Adult Trauma Center, ProMedica Toledo Children's Hospital co-campus, comprehensive stroke center, full cardiac/neuro/cancer care. Veterans accepted via VA Community Care and TRICARE." },
  { section: "HOSP", title: "Summa Health Akron Campus", cat: "healthcare", sub: "Specialty Care", city: "Akron", website_url: "https://www.summahealth.org/locations/hospitals/akron-campus", source_name: "Summa Health", source_type: "hospital_system", phone: "330-375-3000", address: "141 N Forge St, Akron, OH 44304", zip: "44304", desc: "Summa Health Akron Campus — 750-bed teaching hospital, Level I Adult Trauma Center, comprehensive stroke center, Heart & Vascular Institute, Cancer Institute. Veterans accepted via VA Community Care and TRICARE." },

  // ---- D. FQHCs (8) ----
  { section: "FQHC", title: "PrimaryOne Health (Columbus)", cat: "healthcare", sub: "Primary Care", city: "Columbus", website_url: "https://primaryonehealth.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "614-645-5500", address: "1180 E Main St, Columbus, OH 43205", zip: "43205", desc: "PrimaryOne Health — HRSA-funded FQHC operating 11 health centers across Franklin County. Sliding-fee primary care, dental, behavioral health, women's health, pediatrics, vision, pharmacy. Sees uninsured, Medicaid, Medicare, VA Choice/Community Care patients; veteran outreach with Wylie OPC." },
  { section: "FQHC", title: "Lower Lights Christian Health Center", cat: "healthcare", sub: "Primary Care", city: "Columbus", website_url: "https://lowerlights.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "614-274-1455", address: "1160 W Broad St, Columbus, OH 43222", zip: "43222", desc: "Lower Lights Christian Health Center — HRSA-funded FQHC on Columbus near-west side. Sliding-fee primary care, dental, behavioral health, OB/GYN, pediatrics, pharmacy. Sees uninsured, Medicaid, Medicare; partners with veterans' services." },
  { section: "FQHC", title: "Heart of Ohio Family Health Centers", cat: "healthcare", sub: "Primary Care", city: "Columbus", website_url: "https://www.heartofohiofamilyhealth.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "614-235-5555", address: "2365 Innis Rd, Columbus, OH 43224", zip: "43224", desc: "Heart of Ohio Family Health Centers — HRSA-funded FQHC operating 5 health centers across Franklin County. Sliding-fee primary care, dental, behavioral health, women's health, pediatrics, pharmacy." },
  { section: "FQHC", title: "Care Alliance Health Center (Cleveland)", cat: "healthcare", sub: "Primary Care", city: "Cleveland", website_url: "https://www.carealliance.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "216-781-6724", address: "2916 Central Ave, Cleveland, OH 44115", zip: "44115", desc: "Care Alliance Health Center — HRSA-funded FQHC and HCH (health care for the homeless) program operating 4 sites across Cleveland. Sliding-fee primary care, dental, behavioral health, women's health, pharmacy; HUD-VASH partnership with Louis Stokes Cleveland VAMC." },
  { section: "FQHC", title: "Neighborhood Family Practice (Cleveland)", cat: "healthcare", sub: "Primary Care", city: "Cleveland", website_url: "https://www.nfpmedcenter.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "216-281-0872", address: "3569 Ridge Rd, Cleveland, OH 44102", zip: "44102", desc: "Neighborhood Family Practice — HRSA-funded FQHC operating 5 health centers across Cleveland's near-west side. Sliding-fee primary care, dental, behavioral health, OB/GYN, pediatrics, refugee health." },
  { section: "FQHC", title: "Cincinnati Health Network — Crossroad Health Center", cat: "healthcare", sub: "Primary Care", city: "Cincinnati", website_url: "https://www.crossroadhc.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "513-381-2247", address: "5 E Liberty St, Cincinnati, OH 45202", zip: "45202", desc: "Crossroad Health Center — HRSA-funded FQHC operating 3 sites in downtown Cincinnati and Over-the-Rhine. Sliding-fee primary care, dental, behavioral health, women's health, pharmacy; HCH program for homeless and unstably-housed adults." },
  { section: "FQHC", title: "Five Rivers Health Centers (Dayton)", cat: "healthcare", sub: "Primary Care", city: "Dayton", website_url: "https://www.fiverivershealthcenters.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "937-208-8001", address: "2261 Philadelphia Dr, Dayton, OH 45406", zip: "45406", desc: "Five Rivers Health Centers — HRSA-funded FQHC operated by Premier Health, with 6 sites across Montgomery County. Sliding-fee primary care, dental, behavioral health, OB/GYN, pediatrics, pharmacy, school-based health." },
  { section: "FQHC", title: "Neighborhood Health Association (Toledo)", cat: "healthcare", sub: "Primary Care", city: "Toledo", website_url: "https://www.nhainc.org/", source_name: "HRSA Health Center Program", source_type: "fqhc", phone: "419-720-7458", address: "1415 Jefferson Ave, Toledo, OH 43604", zip: "43604", desc: "Neighborhood Health Association — HRSA-funded FQHC operating 13 health centers across Lucas County. Sliding-fee primary care, dental, behavioral health, OB/GYN, pediatrics, pharmacy, HCH program; serves uninsured, Medicaid, Medicare, refugee populations." },

  // ---- E. ADAMH BOARDS (5) ----
  { section: "ADAMH", title: "Franklin County ADAMH Board", cat: "mental-health", sub: "Counseling & Therapy", city: "Columbus", website_url: "https://adamhfranklin.org/", source_name: "Franklin County Alcohol Drug & Mental Health Board", source_type: "county_agency", phone: "614-224-1057", address: "447 E Broad St, Columbus, OH 43215", zip: "43215", desc: "Franklin County Alcohol Drug & Mental Health (ADAMH) Board — county behavioral-health authority funding 30+ contracted providers serving 40,000+ Franklin County residents annually. Crisis line, mobile crisis (Netcare Access), SUD treatment, recovery housing, veteran specialty care coordination with Wylie OPC." },
  { section: "ADAMH", title: "ADAMHS Board of Cuyahoga County", cat: "mental-health", sub: "Counseling & Therapy", city: "Cleveland", website_url: "https://www.cuyahogacounty.us/health-and-human-services/agencies/adamhs-board", source_name: "Cuyahoga County (ADAMHS Board)", source_type: "county_agency", phone: "216-241-3400", address: "2012 W 25th St 6th Floor, Cleveland, OH 44113", zip: "44113", desc: "ADAMHS Board of Cuyahoga County — county behavioral-health authority funding 60+ contracted providers serving 70,000+ Cuyahoga County residents annually. 24/7 crisis line, mobile crisis (FrontLine Service), SUD treatment, recovery housing; veteran specialty coordination with Cleveland VAMC." },
  { section: "ADAMH", title: "Hamilton County Mental Health & Recovery Services Board", cat: "mental-health", sub: "Counseling & Therapy", city: "Cincinnati", website_url: "https://www.hcmhrsb.org/", source_name: "Hamilton County Mental Health & Recovery Services Board", source_type: "county_agency", phone: "513-946-8600", address: "2350 Auburn Ave, Cincinnati, OH 45219", zip: "45219", desc: "Hamilton County Mental Health & Recovery Services Board — county behavioral-health authority funding 40+ contracted providers serving 35,000+ Hamilton County residents annually. 24/7 crisis line, mobile crisis, SUD treatment, recovery housing; veteran coordination with Cincinnati VAMC." },
  { section: "ADAMH", title: "Montgomery County ADAMHS Board", cat: "mental-health", sub: "Counseling & Therapy", city: "Dayton", website_url: "https://www.mcadamhs.org/", source_name: "Montgomery County ADAMHS Board", source_type: "county_agency", phone: "937-443-0416", address: "409 E Monument Ave 4th Floor, Dayton, OH 45402", zip: "45402", desc: "Montgomery County ADAMHS Board — county behavioral-health authority funding 30+ contracted providers serving 30,000+ Montgomery County residents annually. 24/7 crisis line, mobile crisis (Eastway Behavioral Healthcare), SUD treatment, recovery housing; veteran coordination with Dayton VAMC." },
  { section: "ADAMH", title: "Stark County Mental Health & Addiction Recovery (StarkMHAR)", cat: "mental-health", sub: "Counseling & Therapy", city: "Canton", website_url: "https://starkmhar.org/", source_name: "Stark County Mental Health & Addiction Recovery", source_type: "county_agency", phone: "330-455-6644", address: "121 Cleveland Ave SW, Canton, OH 44702", zip: "44702", desc: "Stark County Mental Health & Addiction Recovery (StarkMHAR) — county behavioral-health authority funding 20+ contracted providers serving 18,000+ Stark County residents annually. 24/7 crisis line via Coleman Crisis Services, SUD treatment, recovery housing; veteran coordination with Canton VA OPC." },

  // ---- F. CRISIS PROVIDERS (4) ----
  { section: "CRIS", title: "Netcare Access (Franklin County Mobile Crisis)", cat: "crisis-help", sub: "Mobile Crisis Teams", city: "Columbus", website_url: "https://www.netcareaccess.org/", source_name: "Netcare Access", source_type: "nonprofit", phone: "614-276-2273", address: "199 S Central Ave, Columbus, OH 43223", zip: "43223", desc: "Netcare Access — Franklin County's 24/7 behavioral-health crisis-stabilization center and mobile crisis response. Crisis hotline 614-276-CARE, walk-in psychiatric crisis assessment, mobile crisis dispatch, SUD assessment & withdrawal management; primary 988 partner in Franklin County." },
  { section: "CRIS", title: "FrontLine Service (Cuyahoga County Mobile Crisis)", cat: "crisis-help", sub: "Mobile Crisis Teams", city: "Cleveland", website_url: "https://frontlineservice.org/", source_name: "FrontLine Service", source_type: "nonprofit", phone: "216-623-6888", address: "1744 Payne Ave, Cleveland, OH 44114", zip: "44114", desc: "FrontLine Service — Cuyahoga County's 24/7 behavioral-health mobile crisis response, suicide prevention hotline, and homeless-services lead. Suicide prevention 216-623-6888, mobile crisis dispatch countywide; SAMHSA-designated 988 partner; Outreach Program for Cleveland's chronically-homeless veterans." },
  { section: "CRIS", title: "Eastway Behavioral Healthcare (Montgomery Mobile Crisis)", cat: "crisis-help", sub: "Mobile Crisis Teams", city: "Dayton", website_url: "https://www.eastway.org/", source_name: "Eastway Behavioral Healthcare", source_type: "nonprofit", phone: "937-223-4357", address: "600 Wayne Ave, Dayton, OH 45410", zip: "45410", desc: "Eastway Behavioral Healthcare — Montgomery County's 24/7 mobile crisis response, crisis-stabilization unit, and outpatient SUD/MH treatment. Crisis line 937-CRISIS-1; 988 partner; veteran coordination with Dayton VAMC and Vet Center." },
  { section: "CRIS", title: "Unison Health (Lucas County Mobile Crisis)", cat: "crisis-help", sub: "Mobile Crisis Teams", city: "Toledo", website_url: "https://www.unisonhealth.org/", source_name: "Unison Health", source_type: "nonprofit", phone: "419-693-0631", address: "1425 Starr Ave, Toledo, OH 43605", zip: "43605", desc: "Unison Health — Lucas County's 24/7 mobile crisis response and largest community behavioral-health provider. Outpatient + intensive outpatient + residential SUD/MH; SAMHSA Center of Excellence; primary 988 partner in NW Ohio; veteran coordination with Toledo Vet Center." },

  // ---- G. RECOVERY (SUD) PROVIDERS (8) ----
  { section: "REC", title: "Maryhaven", cat: "substance-recovery", sub: "Detox Programs", city: "Columbus", website_url: "https://maryhaven.com/", source_name: "Maryhaven Inc", source_type: "nonprofit", phone: "614-445-8131", address: "1791 Alum Creek Dr, Columbus, OH 43207", zip: "43207", desc: "Maryhaven — central Ohio's largest behavioral healthcare and addiction-recovery provider. Detoxification, residential treatment, MAT (Medication-Assisted Treatment), outpatient, women's specialty, and the Veterans Recovery Program partnered with Wylie OPC and Columbus Vet Center." },
  { section: "REC", title: "Stella Maris (Cleveland)", cat: "substance-recovery", sub: "Detox Programs", city: "Cleveland", website_url: "https://stellamariscleveland.com/", source_name: "Stella Maris Inc", source_type: "nonprofit", phone: "216-781-0550", address: "1320 Washington Ave, Cleveland, OH 44113", zip: "44113", desc: "Stella Maris — Cleveland's residential and outpatient SUD recovery provider on the Cuyahoga River flats. Medical detox, 30-day residential, partial hospitalization, MAT, sober-living transitional housing, and a Veterans Track partnered with Cleveland VAMC." },
  { section: "REC", title: "IBH Addiction Recovery Center (Akron)", cat: "substance-recovery", sub: "Detox Programs", city: "Akron", website_url: "https://www.ibh.org/", source_name: "IBH Addiction Recovery Center", source_type: "nonprofit", phone: "330-644-4095", address: "3445 S Main St, Akron, OH 44319", zip: "44319", desc: "IBH Addiction Recovery Center — Akron's primary nonprofit residential SUD treatment center. Medical detox, residential, partial hospitalization, MAT, sober living, and a Veterans Specialty Track partnered with Akron VA OPC and Cleveland VAMC." },
  { section: "REC", title: "Talbert House (Cincinnati)", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Cincinnati", website_url: "https://talberthouse.org/", source_name: "Talbert House", source_type: "nonprofit", phone: "513-751-7747", address: "2600 Victory Pkwy, Cincinnati, OH 45206", zip: "45206", desc: "Talbert House — SW Ohio's largest behavioral health, SUD, and reentry services provider. 30+ programs across detox, residential, MAT, outpatient SUD, mental health, recovery housing, and reentry; Veterans Specialty Programs partnered with Cincinnati VAMC." },
  { section: "REC", title: "Crossroads Center (Cincinnati)", cat: "substance-recovery", sub: "Detox Programs", city: "Cincinnati", website_url: "https://www.thecrossroadscenter.org/", source_name: "The Crossroads Center", source_type: "nonprofit", phone: "513-475-5300", address: "311 Martin Luther King Dr E, Cincinnati, OH 45219", zip: "45219", desc: "The Crossroads Center — Cincinnati nonprofit SUD treatment center providing medical detox, intensive outpatient, MAT, women's residential, and ambulatory withdrawal management. CARF-accredited; sliding-fee; serves Hamilton County via HCMHRSB contract." },
  { section: "REC", title: "Samaritan Behavioral Health (Dayton)", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Dayton", website_url: "https://www.premierhealth.com/services/behavioral-health", source_name: "Premier Health Samaritan Behavioral Health", source_type: "hospital_system", phone: "937-734-8333", address: "601 S Edwin C Moses Blvd, Dayton, OH 45417", zip: "45417", desc: "Samaritan Behavioral Health — Premier Health's outpatient mental-health and SUD treatment system across Montgomery and Greene counties. Outpatient SUD, MAT, intensive outpatient, partial hospitalization, dual-diagnosis; sliding-fee + Medicaid; veteran coordination with Dayton VAMC." },
  { section: "REC", title: "A Renewed Mind (Toledo)", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Toledo", website_url: "https://www.arenewedmindservices.org/", source_name: "A Renewed Mind", source_type: "nonprofit", phone: "419-720-9247", address: "3450 W Central Ave, Toledo, OH 43606", zip: "43606", desc: "A Renewed Mind — NW Ohio's largest community SUD and mental-health provider. Outpatient SUD, MAT, intensive outpatient, mental-health counseling, peer recovery support, and Care Coordination through Lucas County MHRSB. Veteran coordination with Toledo Vet Center." },
  { section: "REC", title: "Glenbeigh Hospital (Rock Creek)", cat: "substance-recovery", sub: "Detox Programs", city: "Rock Creek", website_url: "https://www.glenbeigh.com/", source_name: "Glenbeigh Hospital and Outpatient Centers", source_type: "hospital_system", phone: "800-234-1001", address: "PO Box 298, 2863 OH-45, Rock Creek, OH 44084", zip: "44084", desc: "Glenbeigh — NE Ohio specialty addiction hospital (Cleveland Clinic affiliated). Inpatient medical detox, 30-day residential, partial hospitalization, intensive outpatient, MAT; 9 outpatient locations across NE Ohio; serves veterans via VA Community Care." },

  // ---- H. HEALTHCARE NONPROFITS (3) ----
  { section: "NPO", title: "NAMI Ohio", cat: "mental-health", sub: "Family Support (Mental Health)", city: "Columbus", website_url: "https://namiohio.org/", source_name: "National Alliance on Mental Illness Ohio", source_type: "nonprofit", phone: "614-224-2700", address: "1225 Dublin Rd Suite 125, Columbus, OH 43215", zip: "43215", desc: "NAMI Ohio — statewide chapter of the National Alliance on Mental Illness. Free Family-to-Family classes, peer-led NAMI Connection support groups, NAMI Basics for parents/caregivers, NAMI Veterans support partnered with VA Ohio facilities, advocacy at the Ohio Statehouse; 28 local affiliates across Ohio." },
  { section: "NPO", title: "NAMI Greater Cleveland", cat: "mental-health", sub: "Peer Support", city: "Cleveland", website_url: "https://www.namigreatercleveland.org/", source_name: "NAMI Greater Cleveland", source_type: "nonprofit", phone: "216-875-0266", address: "2012 W 25th St Suite 705, Cleveland, OH 44113", zip: "44113", desc: "NAMI Greater Cleveland — Cuyahoga County NAMI affiliate offering free peer-led support groups, family-to-family education, NAMI Connection groups, crisis-intervention training, and provider/community education. Veteran-and-family programs coordinated with Cleveland VAMC." },
  { section: "NPO", title: "Alzheimer's Association — Greater Cincinnati Chapter (Ohio)", cat: "family-support", sub: "Caregiver Support", city: "Cincinnati", website_url: "https://www.alz.org/cincinnati", source_name: "Alzheimer's Association", source_type: "nonprofit", phone: "800-272-3900", address: "644 Linn St Suite 1026, Cincinnati, OH 45203", zip: "45203", desc: "Alzheimer's Association Greater Cincinnati Chapter — serves SW Ohio, NKY, and SE Indiana families affected by Alzheimer's & related dementias. 24/7 helpline, support groups, care consultations, education, and Veteran Caregiver Support partnered with Cincinnati VAMC Geriatrics." },
];

console.log(`[seed-oh-phase2] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "OH", commit: COMMIT, scriptName: "OH Phase 2 — Healthcare Foundation",
  batchTag: "oh-phase2",
  sectionLabels: { CBOC: "VA CBOCs", VC: "Vet Centers", HOSP: "Major Hospitals", FQHC: "FQHCs", ADAMH: "ADAMH Boards", CRIS: "Mobile Crisis", REC: "SUD Recovery", NPO: "Healthcare Nonprofits" },
}).catch((e) => { console.error(e); process.exit(1); });
