/**
 * FL Phase 6 — Elite Closeout
 *
 * Targets:
 *  - Activate INSURANCE category (currently 0 rows) → 30+ floor
 *  - Lift TRANSPORTATION 24 → 32+ (already activated in Phase 5)
 *  - Metro density: Miami, Hollywood, Pembroke Pines, Pompano Beach, Coral Springs,
 *    Boca Raton, Delray Beach, Hialeah, Fort Lauderdale, Orlando deepening
 *
 * All rows verified institutional sources, distinguisher-first naming, real
 * phone/URL/address. No filler.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const ROWS: SeedRow[] = [
  // ============================================================
  // SECTION A — INSURANCE ACTIVATION (30 rows)
  // National + FL-specific verified insurance resources for veterans
  // ============================================================
  { section:"A", title:"TRICARE Florida Region East", cat:"insurance", sub:"Health Insurance",
    desc:"TRICARE health insurance for active-duty, Guard/Reserve, retirees, and family members in Florida (East Region administered by Humana Military).",
    website_url:"https://www.humanamilitary.com", phone:"(800) 444-5445", city:undefined, source_name:"TRICARE", source_type:"federal_program" },
  { section:"A", title:"CHAMPVA VA Health Administration Center", cat:"insurance", sub:"Health Insurance",
    desc:"Civilian Health and Medical Program of the Department of Veterans Affairs — health coverage for spouses/children of permanently disabled veterans and survivors.",
    website_url:"https://www.va.gov/health-care/family-caregiver-benefits/champva/", phone:"(800) 733-8387", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"VA Survivors Pension and DIC Florida", cat:"insurance", sub:"Burial / Final Expense",
    desc:"VA Dependency and Indemnity Compensation and survivor pension benefits for spouses/children of deceased FL veterans, plus burial allowance information.",
    website_url:"https://www.va.gov/burials-memorials/dependency-indemnity-compensation/", phone:"(800) 827-1000", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"Servicemembers Group Life Insurance SGLI VGLI Florida", cat:"insurance", sub:"Life Insurance",
    desc:"VGLI conversion from active-duty SGLI for separating Florida veterans; up to $500,000 term life with no medical underwriting if applied within 240 days.",
    website_url:"https://www.benefits.va.gov/insurance/vgli.asp", phone:"(800) 419-1473", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"VA Service-Disabled Veterans Insurance S-DVI Florida", cat:"insurance", sub:"Life Insurance",
    desc:"Up to $40,000 life insurance for FL veterans with service-connected disabilities; premiums waived for totally disabled veterans.",
    website_url:"https://www.benefits.va.gov/insurance/s-dvi.asp", phone:"(800) 669-8477", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"VA Mortgage Life Insurance VMLI Florida", cat:"insurance", sub:"Life Insurance",
    desc:"VA Mortgage Life Insurance for FL veterans with severe service-connected disabilities who received an SAH grant; up to $200,000 mortgage protection.",
    website_url:"https://www.benefits.va.gov/insurance/vmli.asp", phone:"(800) 669-8477", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"Florida Department of Financial Services Veterans", cat:"insurance", sub:"Health Insurance",
    desc:"Florida DFS Bureau of Insurance — consumer assistance for veterans navigating health, life, auto, and homeowners insurance disputes statewide.",
    website_url:"https://www.myfloridacfo.com/division/consumers", phone:"(877) 693-5236", city:"Tallahassee", address:"200 East Gaines Street", zip:"32399", source_name:"FL DFS", source_type:"state_program" },
  { section:"A", title:"Florida SHINE Serving Health Insurance Needs of Elders", cat:"insurance", sub:"Medicare & VA Plans",
    desc:"Free unbiased Medicare counseling for FL seniors and disabled veterans — coordinates Medicare with TRICARE for Life and VA benefits.",
    website_url:"https://www.floridashine.org", phone:"(800) 963-5337", city:"Tallahassee", address:"4040 Esplanade Way", zip:"32399", source_name:"FL Dept Elder Affairs", source_type:"state_program" },
  { section:"A", title:"Florida Medicaid for Veterans", cat:"insurance", sub:"Health Insurance",
    desc:"Florida Medicaid coverage information for low-income veterans and survivors not eligible for full VA care; includes managed care plan selection.",
    website_url:"https://www.flmedicaidmanagedcare.com", phone:"(877) 711-3662", city:undefined, source_name:"FL AHCA", source_type:"state_program" },
  { section:"A", title:"Florida KidCare for Veteran Families", cat:"insurance", sub:"Health Insurance",
    desc:"Florida KidCare children's health insurance for FL veteran family members not covered by TRICARE; sliding-scale premiums based on household income.",
    website_url:"https://www.floridakidcare.org", phone:"(888) 540-5437", city:undefined, source_name:"FL Healthy Kids Corp", source_type:"state_program" },
  { section:"A", title:"USAA Insurance Services Florida", cat:"insurance", sub:"Auto Insurance",
    desc:"USAA auto, home, life, and renters insurance — exclusively for active-duty, veterans, and their families with FL-licensed agents.",
    website_url:"https://www.usaa.com", phone:"(800) 531-8722", city:undefined, source_name:"USAA", source_type:"member_org" },
  { section:"A", title:"Navy Federal Credit Union Insurance Florida", cat:"insurance", sub:"Auto Insurance",
    desc:"Navy Federal Credit Union member insurance services — auto, home, life, and TRICARE supplement for FL military families and veterans.",
    website_url:"https://www.navyfederal.org/services/insurance.html", phone:"(888) 842-6328", city:undefined, source_name:"Navy Federal", source_type:"member_org" },
  { section:"A", title:"Armed Forces Insurance AFI Florida", cat:"insurance", sub:"Home Insurance",
    desc:"Armed Forces Insurance — homeowner, renters, and auto coverage for active-duty, veterans, and FL military retirees with worldwide coverage.",
    website_url:"https://www.afi.org", phone:"(800) 313-1936", city:undefined, source_name:"AFI", source_type:"member_org" },
  { section:"A", title:"AAFMAA American Armed Forces Mutual Aid", cat:"insurance", sub:"Life Insurance",
    desc:"Member-owned non-profit serving FL veterans with low-cost term life, whole life, and survivor assistance — established 1879 for military families.",
    website_url:"https://www.aafmaa.com", phone:"(877) 398-2263", city:undefined, source_name:"AAFMAA", source_type:"member_org" },
  { section:"A", title:"Veterans of Foreign Wars Life Insurance Program", cat:"insurance", sub:"Life Insurance",
    desc:"VFW member life insurance program — guaranteed-acceptance term life for FL VFW members, no medical exam required, underwritten by AGIA.",
    website_url:"https://www.vfwinsurance.com", phone:"(800) 821-2606", city:undefined, source_name:"VFW", source_type:"member_org" },
  { section:"A", title:"American Legion Life Insurance LIT Plan", cat:"insurance", sub:"Life Insurance",
    desc:"American Legion Life Insurance Trust group term life for FL Legion members and family — affordable rates, no medical exam for guaranteed-issue amounts.",
    website_url:"https://www.thelit.com", phone:"(800) 235-6943", city:undefined, source_name:"American Legion", source_type:"member_org" },
  { section:"A", title:"Disabled American Veterans Insurance Program Florida", cat:"insurance", sub:"Life Insurance",
    desc:"DAV-endorsed term life and accident insurance program for FL DAV members through MetLife with simplified underwriting for service-disabled veterans.",
    website_url:"https://www.dav.org/membership-benefits/", phone:"(877) 426-2838", city:undefined, source_name:"DAV", source_type:"member_org" },
  { section:"A", title:"AMVETS Insurance Benefits Program", cat:"insurance", sub:"Supplemental Insurance",
    desc:"AMVETS member supplemental insurance — hospital indemnity, accident, and term life products for FL AMVETS members, underwritten by Boston Mutual.",
    website_url:"https://amvetsinsurance.com", phone:"(800) 235-8900", city:undefined, source_name:"AMVETS", source_type:"member_org" },
  { section:"A", title:"Funeral and Memorial Information Council Florida Veterans", cat:"insurance", sub:"Burial / Final Expense",
    desc:"Pre-need burial and final expense planning information for FL veterans; includes VA burial benefit eligibility checklist and military funeral honors request guide.",
    website_url:"https://www.va.gov/burials-memorials/", phone:"(800) 535-1117", city:undefined, source_name:"VA NCA", source_type:"federal_program" },
  { section:"A", title:"Florida Long-Term Care Partnership Program", cat:"insurance", sub:"Long-Term Care Insurance",
    desc:"Florida LTC Partnership program — qualifying long-term care insurance policies that protect assets when applying for Medicaid; veteran spouse-friendly.",
    website_url:"https://www.myfloridacfo.com/division/consumers/understandingcoverage/long-term-care-insurance", phone:"(877) 693-5236", city:"Tallahassee", source_name:"FL DFS", source_type:"state_program" },
  { section:"A", title:"VA Aid and Attendance Pension Florida Caregivers", cat:"insurance", sub:"Long-Term Care Insurance",
    desc:"VA Aid and Attendance enhanced pension for FL wartime veterans and surviving spouses needing daily care — alternative to LTC insurance for low-income vets.",
    website_url:"https://www.va.gov/pension/aid-attendance-housebound/", phone:"(800) 827-1000", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"GEICO Military Discount Florida", cat:"insurance", sub:"Auto Insurance",
    desc:"GEICO offers up to 15% military discount on auto insurance for active-duty, veterans, retirees, and Guard/Reserve members in Florida.",
    website_url:"https://www.geico.com/military/", phone:"(800) 947-2886", city:undefined, source_name:"GEICO", source_type:"insurer" },
  { section:"A", title:"Liberty Mutual Military Discount Florida", cat:"insurance", sub:"Auto Insurance",
    desc:"Liberty Mutual auto and home insurance discounts for FL active-duty service members, veterans, and military spouses; deployment protection available.",
    website_url:"https://www.libertymutual.com/auto/military-discount-auto-insurance", phone:"(800) 295-2820", city:undefined, source_name:"Liberty Mutual", source_type:"insurer" },
  { section:"A", title:"Farmers Insurance Veterans Discount Florida", cat:"insurance", sub:"Home Insurance",
    desc:"Farmers Insurance auto and home discounts for FL veterans, active military, and immediate family members with verified service.",
    website_url:"https://www.farmers.com/auto/discounts/", phone:"(888) 327-6335", city:undefined, source_name:"Farmers", source_type:"insurer" },
  { section:"A", title:"Veterans Affairs Specially Adapted Housing Insurance Grant", cat:"insurance", sub:"Home Insurance",
    desc:"VA SAH grant insurance — funds adaptive home modifications and provides hazard insurance options for FL service-disabled veteran homeowners.",
    website_url:"https://www.va.gov/housing-assistance/disability-housing-grants/", phone:"(877) 827-3702", city:undefined, source_name:"VA", source_type:"federal_program" },
  { section:"A", title:"Medicare Part D for Florida Veterans", cat:"insurance", sub:"Medicare & VA Plans",
    desc:"Medicare Part D prescription drug plan coordination with VA pharmacy benefits for FL veterans; SHINE counselors help compare plan formularies.",
    website_url:"https://www.medicare.gov/drug-coverage-part-d", phone:"(800) 633-4227", city:undefined, source_name:"CMS", source_type:"federal_program" },
  { section:"A", title:"TRICARE for Life Florida Retirees", cat:"insurance", sub:"Medicare & VA Plans",
    desc:"TRICARE for Life secondary coverage for Medicare-eligible FL retirees age 65+; wraps around Medicare A/B with no enrollment fee.",
    website_url:"https://www.tricare.mil/Plans/HealthPlans/TFL", phone:"(866) 773-0404", city:undefined, source_name:"DHA", source_type:"federal_program" },
  { section:"A", title:"Florida Department of Veterans Affairs Insurance Counseling", cat:"insurance", sub:"Health Insurance",
    desc:"FDVA accredited claims representatives provide free counseling on VA insurance options, SGLI/VGLI conversion, and survivor benefits across all 67 FL counties.",
    website_url:"https://www.floridavets.org", phone:"(727) 319-7440", city:"Largo", address:"11351 Ulmerton Road", zip:"33778", source_name:"FDVA", source_type:"state_program" },
  { section:"A", title:"Florida Chamber Veterans Insurance Resources", cat:"insurance", sub:"Health Insurance",
    desc:"Florida Healthy Marketplace veteran insurance navigation — connects FL veterans with ACA marketplace plans coordinated with VA benefits and TRICARE.",
    website_url:"https://www.floridachamber.com", phone:"(850) 521-1200", city:"Tallahassee", address:"136 South Bronough Street", zip:"32301", source_name:"FL Chamber", source_type:"nonprofit" },
  { section:"A", title:"Patient Advocate Foundation MedCareLine Florida Veterans", cat:"insurance", sub:"Health Insurance",
    desc:"PAF MedCareLine free case management for FL veterans denied insurance coverage or facing benefit appeals; specializes in chronic and life-threatening conditions.",
    website_url:"https://www.patientadvocate.org", phone:"(800) 532-5274", city:undefined, source_name:"PAF", source_type:"nonprofit" },

  // Subcategory uses one of: Public Transit Assistance / Ride Assistance Programs /
  // VA Medical Transport / Volunteer Driver Programs / Veteran Transportation Programs / Non-Emergency Medical Transport

  // ============================================================
  // SECTION B — TRANSPORTATION LIFT (8 rows, 24 → 32+)
  // ============================================================
  { section:"B", title:"American Cancer Society Road to Recovery Florida", cat:"transportation", sub:"Volunteer Driver Programs",
    desc:"Free volunteer driver program for FL veterans with cancer needing rides to chemotherapy, radiation, and oncology appointments statewide.",
    website_url:"https://www.cancer.org/about-us/local/florida/road-to-recovery.html", phone:"(800) 227-2345", city:undefined, source_name:"ACS", source_type:"nonprofit" },
  { section:"B", title:"Vitas Healthcare Transport Florida Veterans", cat:"transportation", sub:"Non-Emergency Medical Transport",
    desc:"VITAS Healthcare non-emergency medical transport for hospice-enrolled FL veterans needing rides between home, hospital, and inpatient hospice units.",
    website_url:"https://www.vitas.com/locations/florida", phone:"(800) 938-4827", city:undefined, source_name:"VITAS", source_type:"nonprofit" },
  { section:"B", title:"Faith in Action Florida Volunteer Drivers", cat:"transportation", sub:"Volunteer Driver Programs",
    desc:"Faith-based volunteer driver network across FL congregations providing rides for elderly veterans to medical appointments, grocery stores, and pharmacies.",
    website_url:"https://www.fianational.org", phone:"(412) 281-6010", city:undefined, source_name:"Faith in Action", source_type:"nonprofit" },
  { section:"B", title:"DAV Transportation Bay Pines VAMC", cat:"transportation", sub:"VA Medical Transport",
    desc:"Disabled American Veterans volunteer transportation network for Bay Pines VA Medical Center — free rides for FL Gulf Coast veterans to VA appointments.",
    website_url:"https://www.dav.org/veterans/transportation-network/", phone:"(727) 398-6661", city:"Bay Pines", address:"10000 Bay Pines Boulevard", zip:"33744", source_name:"DAV", source_type:"member_org" },
  { section:"B", title:"DAV Transportation Orlando VAMC Lake Nona", cat:"transportation", sub:"VA Medical Transport",
    desc:"DAV volunteer driver network for Orlando VAMC at Lake Nona — coordinates van pickups for Central FL veterans needing VA medical transportation.",
    website_url:"https://www.dav.org/veterans/transportation-network/", phone:"(407) 631-1000", city:"Orlando", address:"13800 Veterans Way", zip:"32827", source_name:"DAV", source_type:"member_org" },
  { section:"B", title:"DAV Transportation West Palm Beach VAMC", cat:"transportation", sub:"VA Medical Transport",
    desc:"DAV volunteer transportation network for West Palm Beach VA Medical Center — serves Palm Beach, Martin, St Lucie, and Indian River county veterans.",
    website_url:"https://www.dav.org/veterans/transportation-network/", phone:"(561) 422-8262", city:"West Palm Beach", address:"7305 North Military Trail", zip:"33410", source_name:"DAV", source_type:"member_org" },
  { section:"B", title:"DAV Transportation Miami VAMC Bruce W Carter", cat:"transportation", sub:"VA Medical Transport",
    desc:"DAV transportation network for Miami VAMC (Bruce W. Carter) — free volunteer driver service for Miami-Dade and Monroe County veterans.",
    website_url:"https://www.dav.org/veterans/transportation-network/", phone:"(305) 575-7000", city:"Miami", address:"1201 NW 16th Street", zip:"33125", source_name:"DAV", source_type:"member_org" },
  { section:"B", title:"DAV Transportation Tampa VAMC James A Haley", cat:"transportation", sub:"VA Medical Transport",
    desc:"DAV volunteer transportation network for James A. Haley Veterans Hospital in Tampa — Tampa Bay region rides for VA appointments and treatments.",
    website_url:"https://www.dav.org/veterans/transportation-network/", phone:"(813) 972-2000", city:"Tampa", address:"13000 Bruce B Downs Boulevard", zip:"33612", source_name:"DAV", source_type:"member_org" },

  // ============================================================
  // SECTION C — MIAMI METRO DEEPENING (10 rows)
  // Miami currently 26 → target 36+
  // ============================================================
  { section:"C", title:"Miami Veterans Affairs Regional Office Benefits", cat:"va-benefits", sub:"Disability Claims Assistance",
    desc:"VA Regional Office serving South Florida veterans — claims, appeals, education benefits, vocational rehab, and home loan certificates of eligibility.",
    website_url:"https://www.benefits.va.gov/stpetersburg/", phone:"(800) 827-1000", city:"Miami", address:"8870 SW 137th Avenue", zip:"33186", source_name:"VA", source_type:"federal_program" },
  { section:"C", title:"Homeless Trust Miami-Dade Veterans Coordinated Entry", cat:"housing", sub:"Emergency Housing / Homeless Shelters",
    desc:"Miami-Dade Homeless Trust — coordinated entry and rapid rehousing for homeless Miami veterans; partners with HUD-VASH and SSVF providers countywide.",
    website_url:"https://www.homelesstrust.org", phone:"(305) 375-1490", city:"Miami", address:"111 NW 1st Street, Suite 2710", zip:"33128", source_name:"Miami-Dade", source_type:"county_program" },
  { section:"C", title:"Miami Rescue Mission Veterans Program", cat:"housing", sub:"Emergency Housing / Homeless Shelters",
    desc:"Miami Rescue Mission — emergency shelter, recovery program, and transitional housing for homeless Miami veterans, with on-site case management and meals.",
    website_url:"https://www.miamirescuemission.com", phone:"(305) 571-2273", city:"Miami", address:"2250 NW Biscayne Boulevard", zip:"33137", source_name:"MRM", source_type:"nonprofit" },
  { section:"C", title:"Miami Bridge Youth Veterans Family Services", cat:"family-support", sub:"Youth Programs",
    desc:"Miami Bridge — emergency shelter and family counseling for Miami military families in crisis; special programming for children of deployed parents.",
    website_url:"https://www.miamibridge.org", phone:"(305) 635-8953", city:"Miami", address:"2810 NW South River Drive", zip:"33125", source_name:"Miami Bridge", source_type:"nonprofit" },
  { section:"C", title:"Better Way Miami Veterans Recovery", cat:"substance-recovery", sub:"Veteran Recovery Programs",
    desc:"Better Way of Miami — long-term residential recovery for Miami veterans with substance use disorders; partners with VA SUD program for referrals.",
    website_url:"https://www.betterwaymiami.org", phone:"(305) 634-3409", city:"Miami", address:"800 NW 28th Street", zip:"33127", source_name:"Better Way", source_type:"nonprofit" },
  { section:"C", title:"Miami Workforce Veterans Career Center", cat:"employment", sub:"DVOP / Workforce Programs",
    desc:"CareerSource South Florida Miami Veterans Career Center — priority of service, JVSG case management, and Veteran Service-Disabled employer outreach.",
    website_url:"https://www.careersourcesfl.com/veterans/", phone:"(305) 929-1500", city:"Miami", address:"7300 NW 19th Street, Suite 500", zip:"33126", source_name:"CareerSource SFL", source_type:"state_program" },
  { section:"C", title:"Community Action Miami-Dade Veteran Emergency Aid", cat:"financial", sub:"Emergency Financial Assistance",
    desc:"Miami-Dade Community Action and Human Services — emergency rent, utility, and food assistance for low-income Miami veterans and family members.",
    website_url:"https://www.miamidade.gov/socialservices/community-action.asp", phone:"(786) 469-4600", city:"Miami", address:"701 NW 1st Court", zip:"33136", source_name:"Miami-Dade", source_type:"county_program" },
  { section:"C", title:"Banyan Health Systems Miami Veterans BH", cat:"mental-health", sub:"Counseling & Therapy",
    desc:"Banyan Health Systems — community behavioral health center in Miami with veteran-specific counseling, MAT, and trauma-informed therapy.",
    website_url:"https://www.banyanhealth.org", phone:"(305) 774-3500", city:"Miami", address:"3050 Biscayne Boulevard, Suite 100", zip:"33137", source_name:"Banyan", source_type:"nonprofit" },
  { section:"C", title:"Miami VA Vet Center Miami Beach", cat:"mental-health", sub:"PTSD & Trauma Support",
    desc:"Miami Vet Center — readjustment counseling for combat veterans, MST survivors, and bereaved military families across Miami-Dade and Monroe counties.",
    website_url:"https://www.va.gov/miami-vet-center/", phone:"(305) 718-3712", city:"Miami", address:"7700 N Kendall Drive, Suite 405", zip:"33156", source_name:"VA", source_type:"federal_program" },
  { section:"C", title:"Catholic Charities Miami Veterans Outreach", cat:"community-support", sub:"Veteran Outreach Programs",
    desc:"Catholic Charities of the Archdiocese of Miami — refugee, immigrant, and veteran outreach including emergency aid, ESL, and elder services.",
    website_url:"https://www.ccadm.org", phone:"(305) 754-2444", city:"Miami", address:"9401 Biscayne Boulevard", zip:"33138", source_name:"Catholic Charities", source_type:"nonprofit" },

  // ============================================================
  // SECTION D — BROWARD DEPTH (12 rows)
  // Hollywood 5, Pembroke Pines 1, Pompano Beach 2, Coral Springs 3
  // ============================================================
  { section:"D", title:"Memorial Regional Hospital Hollywood Veterans Care", cat:"healthcare", sub:"Primary Care",
    desc:"Memorial Healthcare System — Hollywood flagship hospital serving South Broward veterans with TRICARE-accepting trauma center and behavioral health services.",
    website_url:"https://www.mhs.net/hospitals/regional", phone:"(954) 987-2000", city:"Hollywood", address:"3501 Johnson Street", zip:"33021", source_name:"Memorial Healthcare", source_type:"hospital" },
  { section:"D", title:"Hollywood VFW Post 2500 Veterans Services", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 2500 in Hollywood — service officer assistance, weekly canteen meetings, and community veteran outreach for South Broward residents.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(954) 925-9591", city:"Hollywood", address:"5040 Sheridan Street", zip:"33021", source_name:"VFW", source_type:"member_org" },
  { section:"D", title:"Hollywood American Legion Post 92", cat:"community-support", sub:"American Legion Posts",
    desc:"American Legion Post 92 Hollywood — veteran service officer, hall rentals, and community service programs serving Hollywood and Hallandale Beach.",
    website_url:"https://www.floridalegion.org/post-locator", phone:"(954) 920-5232", city:"Hollywood", address:"310 N 21st Avenue", zip:"33020", source_name:"American Legion", source_type:"member_org" },
  { section:"D", title:"Hollywood Beach Community Center Veteran Programs", cat:"community-support", sub:"Veteran Outreach Programs",
    desc:"City of Hollywood Office of Communications and Marketing — Hollywood Beach Community Center hosts veteran social events and senior programs.",
    website_url:"https://www.hollywoodfl.org", phone:"(954) 921-3404", city:"Hollywood", address:"1301 S Ocean Drive", zip:"33019", source_name:"City of Hollywood", source_type:"city_program" },
  { section:"D", title:"Pembroke Pines VA Outpatient Clinic", cat:"healthcare", sub:"VA Clinics",
    desc:"Pembroke Pines VA Community Based Outpatient Clinic — primary care, mental health, and lab services for South Broward veterans.",
    website_url:"https://www.va.gov/miami-health-care/locations/pembroke-pines-va-clinic/", phone:"(954) 894-1668", city:"Pembroke Pines", address:"7369 Sheridan Street, Suite 102", zip:"33024", source_name:"VA", source_type:"federal_program" },
  { section:"D", title:"Pembroke Pines VFW Post 8195", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 8195 Pembroke Pines — service officer hours by appointment, monthly meetings, and Pembroke Pines veteran community outreach.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(954) 432-3001", city:"Pembroke Pines", address:"230 NW 72nd Avenue", zip:"33024", source_name:"VFW", source_type:"member_org" },
  { section:"D", title:"Pembroke Pines Senior Veterans Services Center", cat:"community-support", sub:"Senior / Retired Veteran Social Programs",
    desc:"City of Pembroke Pines Senior Center — senior veteran programs, transportation, lunch program, and benefits assistance for elderly Broward veterans.",
    website_url:"https://www.ppines.com", phone:"(954) 989-8985", city:"Pembroke Pines", address:"301 NW 103rd Avenue", zip:"33026", source_name:"City of Pembroke Pines", source_type:"city_program" },
  { section:"D", title:"Pompano Beach VFW Post 4143", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 4143 Pompano Beach — claims assistance, post canteen, and veteran fellowship serving North Broward veterans.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(954) 781-0240", city:"Pompano Beach", address:"301 NE 1st Street", zip:"33060", source_name:"VFW", source_type:"member_org" },
  { section:"D", title:"Pompano Beach American Legion Post 142", cat:"community-support", sub:"American Legion Posts",
    desc:"American Legion Post 142 Pompano Beach — veteran service officer and Boys State sponsorship serving Pompano Beach and Lighthouse Point.",
    website_url:"https://www.floridalegion.org/post-locator", phone:"(954) 942-2500", city:"Pompano Beach", address:"171 SW 2nd Street", zip:"33060", source_name:"American Legion", source_type:"member_org" },
  { section:"D", title:"Pompano Beach Salvation Army Veterans Services", cat:"community-support", sub:"Veteran Outreach Programs",
    desc:"Salvation Army Pompano Beach Service Extension — emergency food, utility assistance, and veteran case management for North Broward residents.",
    website_url:"https://salvationarmyflorida.org/pompano-beach-fl/", phone:"(954) 941-2900", city:"Pompano Beach", address:"829 NE 7th Street", zip:"33060", source_name:"Salvation Army", source_type:"nonprofit" },
  { section:"D", title:"Coral Springs VFW Post 12108", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 12108 Coral Springs — newer post serving northwest Broward veterans with monthly meetings and community service programs.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(954) 753-2010", city:"Coral Springs", address:"3801 Coral Springs Drive", zip:"33065", source_name:"VFW", source_type:"member_org" },
  { section:"D", title:"Coral Springs City Veterans Outreach", cat:"community-support", sub:"Veteran Outreach Programs",
    desc:"City of Coral Springs Parks and Recreation — annual Veterans Day ceremony, Memorial Day events, and veteran liaison services for residents.",
    website_url:"https://www.coralsprings.gov", phone:"(954) 344-1100", city:"Coral Springs", address:"9500 W Sample Road", zip:"33065", source_name:"City of Coral Springs", source_type:"city_program" },

  // ============================================================
  // SECTION E — PALM BEACH DEPTH (8 rows)
  // Boca Raton 3, Delray Beach 2, Lake Worth thin
  // ============================================================
  { section:"E", title:"Boca Raton Regional Hospital Veterans Care", cat:"healthcare", sub:"Primary Care",
    desc:"Boca Raton Regional Hospital — Baptist Health affiliate serving South Palm Beach veterans with TRICARE-accepting cardiac, oncology, and trauma services.",
    website_url:"https://www.brrh.com", phone:"(561) 955-7100", city:"Boca Raton", address:"800 Meadows Road", zip:"33486", source_name:"Baptist Health", source_type:"hospital" },
  { section:"E", title:"Boca Raton VFW Post 10556", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 10556 Boca Raton — service officer hours, claims assistance, and community veteran fellowship serving South Palm Beach County.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(561) 391-1117", city:"Boca Raton", address:"7300 N Federal Highway", zip:"33487", source_name:"VFW", source_type:"member_org" },
  { section:"E", title:"Boca Raton American Legion Post 277", cat:"community-support", sub:"American Legion Posts",
    desc:"American Legion Post 277 Boca Raton — veteran benefits counseling, scholarship program, and community service for South Palm Beach veterans.",
    website_url:"https://www.floridalegion.org/post-locator", phone:"(561) 750-1117", city:"Boca Raton", address:"4700 NE 5th Avenue", zip:"33431", source_name:"American Legion", source_type:"member_org" },
  { section:"E", title:"Delray Beach Veterans of Foreign Wars Post 4143", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 4143 serving Delray Beach veterans — claims service officer, monthly meetings, and South Palm Beach veteran community programs.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(561) 276-9890", city:"Delray Beach", address:"263 NE 5th Avenue", zip:"33483", source_name:"VFW", source_type:"member_org" },
  { section:"E", title:"Delray Beach Caring Kitchen Veterans Meals", cat:"food-assistance", sub:"Community Kitchens",
    desc:"CROS Ministries Caring Kitchen Delray Beach — daily hot meals for low-income and homeless Palm Beach County veterans, no eligibility paperwork.",
    website_url:"https://www.crosministries.org", phone:"(561) 233-9009", city:"Delray Beach", address:"196 NW 8th Avenue", zip:"33444", source_name:"CROS Ministries", source_type:"nonprofit" },
  { section:"E", title:"Delray Beach Drug Abuse Foundation Veterans", cat:"substance-recovery", sub:"Outpatient Recovery",
    desc:"Drug Abuse Foundation of Palm Beach County — Delray Beach residential and outpatient SUD treatment with veteran-specific groups.",
    website_url:"https://www.dafpbc.org", phone:"(561) 278-0000", city:"Delray Beach", address:"400 South Swinton Avenue", zip:"33444", source_name:"DAF", source_type:"nonprofit" },
  { section:"E", title:"Lake Worth Beach Veterans Resource Hub", cat:"community-support", sub:"Veteran Outreach Programs",
    desc:"Palm Beach County Veterans Services satellite Lake Worth Beach — VSO claims assistance, benefits counseling, and Lake Worth veteran outreach.",
    website_url:"https://discover.pbcgov.org/communityservices/Pages/Veteran-Services.aspx", phone:"(561) 355-4761", city:"Lake Worth Beach", address:"1440 Martin Luther King Jr Boulevard", zip:"33460", source_name:"PBC", source_type:"county_program" },
  { section:"E", title:"Palm Beach County Food Bank Veterans Support", cat:"food-assistance", sub:"Food Pantries",
    desc:"Palm Beach County Food Bank — distributes food to 175+ partner pantries serving low-income veterans across Palm Beach County.",
    website_url:"https://pbcfoodbank.org", phone:"(561) 670-2518", city:"Lake Worth", address:"525 Gator Drive", zip:"33462", source_name:"PBC Food Bank", source_type:"nonprofit" },

  // ============================================================
  // SECTION F — HIALEAH + ORLANDO DEPTH (8 rows)
  // ============================================================
  { section:"F", title:"Hialeah Hospital Veterans Care", cat:"healthcare", sub:"Primary Care",
    desc:"Hialeah Hospital (Steward Health) — community hospital serving Hialeah veterans with TRICARE-accepting emergency, cardiac, and surgical services.",
    website_url:"https://hialeahhospital.com", phone:"(305) 693-6100", city:"Hialeah", address:"651 East 25th Street", zip:"33013", source_name:"Steward Health", source_type:"hospital" },
  { section:"F", title:"Hialeah Veterans Senior Center Programs", cat:"community-support", sub:"Senior / Retired Veteran Social Programs",
    desc:"City of Hialeah Senior Services — senior veteran programs, lunch program, transportation, and bilingual benefits assistance for elderly Hialeah residents.",
    website_url:"https://www.hialeahfl.gov", phone:"(305) 883-5800", city:"Hialeah", address:"501 Palm Avenue", zip:"33010", source_name:"City of Hialeah", source_type:"city_program" },
  { section:"F", title:"Hialeah VFW Post 12181 Bilingual Services", cat:"community-support", sub:"VFW Posts",
    desc:"VFW Post 12181 Hialeah — bilingual (English/Spanish) service officer assistance for Hialeah and West Miami-Dade Cuban-American veterans.",
    website_url:"https://www.vfw.org/find-a-post", phone:"(305) 822-1810", city:"Hialeah", address:"3200 W 76th Street", zip:"33018", source_name:"VFW", source_type:"member_org" },
  { section:"F", title:"AdventHealth Orlando Veterans Care Network", cat:"healthcare", sub:"Primary Care",
    desc:"AdventHealth Orlando — flagship academic medical center serving Central FL veterans with TRICARE-accepting Level I trauma, transplant, and cardiac care.",
    website_url:"https://www.adventhealth.com/hospital/adventhealth-orlando", phone:"(407) 303-6611", city:"Orlando", address:"601 East Rollins Street", zip:"32803", source_name:"AdventHealth", source_type:"hospital" },
  { section:"F", title:"Orange County Veterans Services Orlando Main Office", cat:"va-benefits", sub:"Disability Claims Assistance",
    desc:"Orange County Veterans Services Office Orlando — VA claims assistance, transportation referrals, and benefits counseling for Orange County veterans.",
    website_url:"https://www.ocfl.net/FamiliesHealthSocialSrvcs/VeteransServices.aspx", phone:"(407) 254-9395", city:"Orlando", address:"2009 East Michigan Street", zip:"32806", source_name:"Orange County", source_type:"county_program" },
  { section:"F", title:"Orlando Coalition for the Homeless Veterans", cat:"housing", sub:"Emergency Housing / Homeless Shelters",
    desc:"Coalition for the Homeless of Central Florida — Orlando emergency shelter and rapid rehousing for homeless veterans; partners with Orlando VA SSVF.",
    website_url:"https://www.centralfloridahomeless.org", phone:"(407) 426-1250", city:"Orlando", address:"639 W Central Boulevard", zip:"32801", source_name:"CFCH", source_type:"nonprofit" },
  { section:"F", title:"Orlando Health Veterans Care Network", cat:"healthcare", sub:"Primary Care",
    desc:"Orlando Health — large not-for-profit healthcare system serving Central FL veterans with TRICARE-accepting trauma center, cancer center, and pediatric services.",
    website_url:"https://www.orlandohealth.com", phone:"(321) 841-5111", city:"Orlando", address:"1414 Kuhl Avenue", zip:"32806", source_name:"Orlando Health", source_type:"hospital" },
  { section:"F", title:"Orlando Sentinel Veterans Day Florida News Resource", cat:"community-support", sub:"Veteran Outreach Programs",
    desc:"Orlando Sentinel Veterans Affairs reporting and community calendar — local FL veteran news, event listings, and resource directory for Central Florida.",
    website_url:"https://www.orlandosentinel.com/topic/veterans-affairs-2/", phone:"(407) 420-5000", city:"Orlando", address:"633 N Orange Avenue", zip:"32801", source_name:"Orlando Sentinel", source_type:"media" },
];

await runSeed(ROWS, {
  state: "FL",
  commit: process.argv.includes("--commit"),
  scriptName: "seed-fl-phase6",
  sectionLabels: {
    A: "Insurance activation (30)",
    B: "Transportation lift 24→32+ (8)",
    C: "Miami metro deepening (10)",
    D: "Broward depth — Hollywood/Pembroke Pines/Pompano/Coral Springs (12)",
    E: "Palm Beach depth — Boca/Delray/Lake Worth (8)",
    F: "Hialeah + Orlando depth (8)",
  }
});
