/**
 * OHIO — PHASE 3: VBA / VSO / COUNTY VSC LAYER
 * Per locked national 6-phase SOP. ~30 rows:
 *   - 25 County Veterans Service Commissions (top 25 OH counties by veteran population)
 *     Per ORC §5901, every Ohio county operates a county-funded Veterans Service Commission
 *     providing free VA-claim assistance, emergency financial aid, and transportation.
 *     Anchor URLs: county-self-site where available; OACVSC directory query URL otherwise.
 *   - 3 Honor Flight regional hubs (Cleveland, Columbus, Findlay)
 *   - 2 Paralyzed Veterans of America (PVA) — national + Buckeye chapter
 * Veteran-first / not veteran-only: County VSCs are veteran-only by statute; Honor Flight
 * and PVA serve specific veteran populations. Statewide VSO depts (VFW/Legion/DAV/AMVETS/
 * MarineCorpsLeague/VVA) were already seeded in Phase 1.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const OACVSC = (slug: string) => `https://www.ohiovets.org/locations/?county=${slug}`;

const ROWS: SeedRow[] = [
  // ---- A. COUNTY VETERANS SERVICE COMMISSIONS (25) ----
  { section: "VSC", title: "Cuyahoga County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Cleveland", website_url: "https://cuyahogacounty.us/veterans-services", source_name: "Cuyahoga County Veterans Service Commission", source_type: "county_agency", phone: "216-698-2600", address: "1849 Prospect Ave Suite 150, Cleveland, OH 44115", zip: "44115", desc: "Cuyahoga County Veterans Service Commission — county-funded ORC §5901 agency serving Cleveland-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants (rent/utilities/medical), DAV-network transportation to VAMC, and notary services. Largest county VSC in Ohio." },
  { section: "VSC", title: "Franklin County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Columbus", website_url: OACVSC("franklin"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "614-525-2500", address: "280 E Broad St, Columbus, OH 43215", zip: "43215", desc: "Franklin County Veterans Service Commission — county-funded ORC §5901 agency serving Columbus-metro veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance, transportation to Wylie OPC and Cleveland/Chillicothe VAMCs, burial-benefit assistance." },
  { section: "VSC", title: "Hamilton County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Cincinnati", website_url: "https://www.hamiltonvets.com/", source_name: "Hamilton County Veterans Service Commission", source_type: "county_agency", phone: "513-946-3300", address: "230 E 9th St 22nd Floor, Cincinnati, OH 45202", zip: "45202", desc: "Hamilton County Veterans Service Commission — county-funded ORC §5901 agency serving Cincinnati-metro veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, DAV-network transportation to Cincinnati VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Montgomery County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Dayton", website_url: OACVSC("montgomery"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "937-225-4801", address: "1111 S Edwin C Moses Blvd, Dayton, OH 45417", zip: "45417", desc: "Montgomery County Veterans Service Commission — county-funded ORC §5901 agency serving Dayton-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, DAV-network transportation to Dayton VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Summit County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Akron", website_url: "https://www.summitvets.org/", source_name: "Summit County Veterans Service Commission", source_type: "county_agency", phone: "330-643-2830", address: "1060 E Waterloo Rd, Akron, OH 44306", zip: "44306", desc: "Summit County Veterans Service Commission — county-funded ORC §5901 agency serving Akron-metro veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Akron VA OPC and Cleveland VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Lucas County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Toledo", website_url: "https://www.lucascountyvets.org/", source_name: "Lucas County Veterans Service Commission", source_type: "county_agency", phone: "419-213-6090", address: "One Government Center Suite 700, Toledo, OH 43604", zip: "43604", desc: "Lucas County Veterans Service Commission — county-funded ORC §5901 agency serving Toledo-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Ann Arbor and Cleveland VAMCs, and burial-benefit assistance." },
  { section: "VSC", title: "Stark County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Canton", website_url: OACVSC("stark"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "330-451-7300", address: "1500 Atlantic Blvd NE, Canton, OH 44705", zip: "44705", desc: "Stark County Veterans Service Commission — county-funded ORC §5901 agency serving Canton-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, DAV-network transportation to Canton VA OPC and Cleveland VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Butler County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Hamilton", website_url: OACVSC("butler"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "513-887-3600", address: "315 High St 6th Floor, Hamilton, OH 45011", zip: "45011", desc: "Butler County Veterans Service Commission — county-funded ORC §5901 agency serving Hamilton/Middletown-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cincinnati and Dayton VAMCs, and burial-benefit assistance." },
  { section: "VSC", title: "Lake County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Painesville", website_url: "https://www.lakecountyohio.gov/veterans", source_name: "Lake County Veterans Service Commission", source_type: "county_agency", phone: "440-350-2904", address: "105 Main St, Painesville, OH 44077", zip: "44077", desc: "Lake County Veterans Service Commission — county-funded ORC §5901 agency serving Lake County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cleveland VAMC and Lake County VA OPC, and burial-benefit assistance." },
  { section: "VSC", title: "Lorain County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Elyria", website_url: "https://www.loraincounty.com/veterans-service-commission", source_name: "Lorain County Veterans Service Commission", source_type: "county_agency", phone: "440-284-4625", address: "226 Middle Ave 4th Floor, Elyria, OH 44035", zip: "44035", desc: "Lorain County Veterans Service Commission — county-funded ORC §5901 agency serving Lorain County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cleveland VAMC and Lorain VA OPC, and burial-benefit assistance." },
  { section: "VSC", title: "Mahoning County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Youngstown", website_url: OACVSC("mahoning"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "330-740-2450", address: "21 W Boardman St 6th Floor, Youngstown, OH 44503", zip: "44503", desc: "Mahoning County Veterans Service Commission — county-funded ORC §5901 agency serving Youngstown-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cleveland and Pittsburgh VAMCs, and burial-benefit assistance." },
  { section: "VSC", title: "Trumbull County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Warren", website_url: OACVSC("trumbull"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "330-675-2453", address: "220 W Market St, Warren, OH 44481", zip: "44481", desc: "Trumbull County Veterans Service Commission — county-funded ORC §5901 agency serving Warren-area veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cleveland and Pittsburgh VAMCs, and burial-benefit assistance." },
  { section: "VSC", title: "Warren County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Lebanon", website_url: "https://www.warrencountyveterans.com/", source_name: "Warren County Veterans Service Commission", source_type: "county_agency", phone: "513-695-1342", address: "822 Greentree Rd, Lebanon, OH 45036", zip: "45036", desc: "Warren County Veterans Service Commission — county-funded ORC §5901 agency serving Warren County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cincinnati and Dayton VAMCs, and burial-benefit assistance." },
  { section: "VSC", title: "Clermont County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Batavia", website_url: OACVSC("clermont"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "513-732-7363", address: "76 S Riverside Dr, Batavia, OH 45103", zip: "45103", desc: "Clermont County Veterans Service Commission — county-funded ORC §5901 agency serving Clermont County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cincinnati VAMC and Clermont County VA OPC, and burial-benefit assistance." },
  { section: "VSC", title: "Greene County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Xenia", website_url: OACVSC("greene"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "937-562-6020", address: "571 Ledbetter Rd, Xenia, OH 45385", zip: "45385", desc: "Greene County Veterans Service Commission — county-funded ORC §5901 agency serving Greene County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Dayton VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Delaware County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Delaware", website_url: OACVSC("delaware"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "740-833-2230", address: "145 N Union St, Delaware, OH 43015", zip: "43015", desc: "Delaware County Veterans Service Commission — county-funded ORC §5901 agency serving Delaware County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Wylie OPC and Cleveland VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Medina County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Medina", website_url: "https://medinacountyveterans.org/", source_name: "Medina County Veterans Service Commission", source_type: "county_agency", phone: "330-722-9368", address: "791 W Smith Rd Suite C, Medina, OH 44256", zip: "44256", desc: "Medina County Veterans Service Commission — county-funded ORC §5901 agency serving Medina County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Cleveland VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Licking County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Newark", website_url: OACVSC("licking"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "740-670-5460", address: "791 E Main St, Newark, OH 43055", zip: "43055", desc: "Licking County Veterans Service Commission — county-funded ORC §5901 agency serving Licking County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Wylie OPC, Newark VA OPC, and Chillicothe VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Portage County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Ravenna", website_url: OACVSC("portage"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "330-297-3545", address: "449 S Meridian St 2nd Floor, Ravenna, OH 44266", zip: "44266", desc: "Portage County Veterans Service Commission — county-funded ORC §5901 agency serving Portage County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Akron VA OPC and Cleveland VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Fairfield County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Lancaster", website_url: OACVSC("fairfield"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "740-652-7920", address: "240 W Main St, Lancaster, OH 43130", zip: "43130", desc: "Fairfield County Veterans Service Commission — county-funded ORC §5901 agency serving Fairfield County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Wylie OPC and Chillicothe VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Wood County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Bowling Green", website_url: OACVSC("wood"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "419-354-9080", address: "1928 E Gypsy Lane Rd, Bowling Green, OH 43402", zip: "43402", desc: "Wood County Veterans Service Commission — county-funded ORC §5901 agency serving Wood County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Toledo and Ann Arbor VAMCs, and burial-benefit assistance." },
  { section: "VSC", title: "Allen County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Lima", website_url: OACVSC("allen"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "419-228-4501", address: "1303 Bellefontaine Ave, Lima, OH 45804", zip: "45804", desc: "Allen County Veterans Service Commission — county-funded ORC §5901 agency serving Lima/Allen County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Lima VA OPC and Dayton VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Clark County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Springfield", website_url: OACVSC("clark"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "937-521-2197", address: "1345 Lagonda Ave, Springfield, OH 45503", zip: "45503", desc: "Clark County Veterans Service Commission — county-funded ORC §5901 agency serving Springfield/Clark County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Springfield VA OPC and Dayton VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Richland County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Mansfield", website_url: OACVSC("richland"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "419-774-5822", address: "597 Park Ave E, Mansfield, OH 44905", zip: "44905", desc: "Richland County Veterans Service Commission — county-funded ORC §5901 agency serving Richland County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Mansfield VA OPC and Cleveland VAMC, and burial-benefit assistance." },
  { section: "VSC", title: "Muskingum County Veterans Service Commission", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Zanesville", website_url: OACVSC("muskingum"), source_name: "Ohio Association of County Veterans Service Commissioners", source_type: "county_agency", phone: "740-455-7176", address: "205 N 7th St, Zanesville, OH 43701", zip: "43701", desc: "Muskingum County Veterans Service Commission — county-funded ORC §5901 agency serving Zanesville/Muskingum County veterans. Free VA disability claim assistance via certified County Veterans Service Officers, emergency financial assistance grants, transportation to Zanesville VA OPC and Chillicothe VAMC, and burial-benefit assistance." },

  // ---- B. HONOR FLIGHT REGIONAL HUBS (3) ----
  { section: "HF", title: "Honor Flight Cleveland", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cleveland", website_url: "https://www.honorflightcleveland.com/", source_name: "Honor Flight Cleveland", source_type: "nonprofit", phone: "440-941-3838", address: "PO Box 91794, Cleveland, OH 44101", zip: "44101", desc: "Honor Flight Cleveland — Honor Flight Network regional hub serving NE Ohio veterans. Provides all-expenses-paid one-day trips to Washington DC for WWII, Korean War, Vietnam War, and terminally-ill veterans of any era to visit war memorials. 3-4 flights per year from Cleveland Hopkins Airport." },
  { section: "HF", title: "Honor Flight Columbus", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://honorflightcolumbus.org/", source_name: "Honor Flight Columbus", source_type: "nonprofit", phone: "614-309-1247", address: "PO Box 549, Plain City, OH 43064", zip: "43064", desc: "Honor Flight Columbus — Honor Flight Network regional hub serving Central Ohio veterans. Provides all-expenses-paid one-day trips to Washington DC for WWII, Korean War, Vietnam War, and terminally-ill veterans of any era to visit war memorials. Flights from John Glenn Columbus International Airport." },
  { section: "HF", title: "Flag City Honor Flight (Findlay)", cat: "community-support", sub: "Veteran Outreach Programs", city: "Findlay", website_url: "https://www.flagcityhonorflight.org/", source_name: "Flag City Honor Flight", source_type: "nonprofit", phone: "419-957-7755", address: "PO Box 962, Findlay, OH 45839", zip: "45839", desc: "Flag City Honor Flight — Honor Flight Network regional hub serving NW Ohio veterans (Hancock, Wood, Putnam, Hardin, Allen, Auglaize, Seneca, Wyandot, Hancock counties). Provides all-expenses-paid one-day trips to Washington DC for WWII, Korean War, and Vietnam War veterans to visit war memorials." },

  // ---- C. PARALYZED VETERANS OF AMERICA (2) ----
  { section: "PVA", title: "Paralyzed Veterans of America (PVA) — National (Ohio Service)", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Cleveland", website_url: "https://www.pva.org/", source_name: "Paralyzed Veterans of America", source_type: "nonprofit", phone: "800-424-8200", desc: "Paralyzed Veterans of America (PVA) — congressionally-chartered VSO serving veterans with spinal-cord injury or disease. National advocacy, free VA-claim representation via PVA NSOs co-located at all 25 VA SCI Centers (including Louis Stokes Cleveland VAMC SCI Center serving Ohio veterans), accessibility advocacy, adaptive sports, research grants. Ohio-area service via Buckeye PVA Chapter." },
  { section: "PVA", title: "Buckeye Chapter — Paralyzed Veterans of America", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Cleveland", website_url: "https://buckeyepva.org/", source_name: "Buckeye PVA Chapter", source_type: "nonprofit", phone: "216-791-3800", address: "10701 East Blvd, Cleveland, OH 44106", zip: "44106", desc: "Buckeye Chapter — Paralyzed Veterans of America — PVA chapter serving Ohio, Western PA, and West Virginia veterans with spinal-cord injury or disease. Free VA-claim assistance via PVA NSOs co-located at Louis Stokes Cleveland VAMC SCI Center; accessibility advocacy; adaptive sports (wheelchair basketball, hand-cycling, sled hockey); peer mentoring." },
];

console.log(`[seed-oh-phase3] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);

runSeed(ROWS, {
  state: "OH",
  scriptName: "seed-oh-phase3",
  commit: COMMIT,
  phaseLabel: "OH Phase 3 — VBA / VSO / County VSC Layer",
}).catch(e => { console.error(e); process.exit(1); });
