/**
 * OHIO — PHASE 4: COMMUNITY SERVICES LIFT
 * Per locked national 6-phase SOP. ~75 rows across weak community categories:
 *   - Housing (HUD-VASH, transitional, CoC, faith-based, statewide coalitions)
 *   - Food assistance (12 OH foodbank network + Salvation Army centers)
 *   - Financial (credit unions, VITA, financial coaching, Operation HOPE)
 *   - Legal (Legal Aid offices, Ohio Justice & Policy, OSBA Lawyer Referral, OH Vets Legal)
 *   - Employment (OhioMeansJobs, Goodwill, Easterseals, Helmets-to-Hardhats, Hire Heroes)
 *   - Family support, Education, Insurance, Disabled-veterans deepening
 * Veteran-first / not veteran-only: includes mainstream orgs serving vets among general public.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ==============================================================
  // A. HOUSING (18) — HUD-VASH, transitional, CoC leads, statewide
  // ==============================================================
  { section: "HOUS", title: "Volunteers of America Ohio & Indiana", cat: "housing", sub: "Transitional Housing", city: "Columbus", website_url: "https://www.voaohin.org/", source_name: "Volunteers of America Ohio & Indiana", source_type: "nonprofit", phone: "614-917-7100", address: "1295 Essex Ave, Columbus, OH 43201", zip: "43201", desc: "Volunteers of America Ohio & Indiana — major regional human-services nonprofit operating veteran transitional housing (Per Diem program), HUD-VASH support, Supportive Services for Veteran Families (SSVF), reentry housing, and addiction treatment across Ohio. SSVF covers 30+ Ohio counties." },
  { section: "HOUS", title: "Maryhaven — Veteran Recovery Housing (Columbus)", cat: "housing", sub: "Transitional Housing", city: "Columbus", website_url: "https://www.maryhaven.com/", source_name: "Maryhaven", source_type: "nonprofit", phone: "614-445-8131", address: "1791 Alum Creek Dr, Columbus, OH 43207", zip: "43207", desc: "Maryhaven — Central Ohio's oldest and largest behavioral healthcare provider with dedicated veteran services including the Maryhaven Veterans Recovery House (VA Per Diem transitional housing), SUD treatment, mental health, and gambling intervention; partners with Wylie OPC and Chalmers P. Wylie VA." },
  { section: "HOUS", title: "Lutheran Metropolitan Ministry — Veteran Services (Cleveland)", cat: "housing", sub: "Transitional Housing", city: "Cleveland", website_url: "https://www.lutheranmetro.org/", source_name: "Lutheran Metropolitan Ministry", source_type: "nonprofit", phone: "216-696-2715", address: "4515 Superior Ave, Cleveland, OH 44103", zip: "44103", desc: "Lutheran Metropolitan Ministry (LMM) — operates the Men's Shelter at 2100 Lakeside (largest in OH), the LMM Veterans Resource Center, transitional housing for homeless veterans, and SSVF rapid-rehousing across Cuyahoga County in partnership with Cleveland VAMC HUD-VASH team." },
  { section: "HOUS", title: "Family Promise of Greater Cleveland", cat: "housing", sub: "Emergency Housing", city: "Cleveland", website_url: "https://www.familypromisecle.org/", source_name: "Family Promise of Greater Cleveland", source_type: "nonprofit", phone: "216-767-4060", address: "3470 E 152nd St, Cleveland, OH 44120", zip: "44120", desc: "Family Promise of Greater Cleveland — emergency shelter and rapid rehousing for homeless families with children in Cuyahoga County; 90-day shelter stays with case management, employment support, and housing-search assistance. Serves veteran families among general population." },
  { section: "HOUS", title: "Coalition on Homelessness & Housing in Ohio (COHHIO)", cat: "housing", sub: "Rental Assistance", city: "Columbus", website_url: "https://cohhio.org/", source_name: "COHHIO", source_type: "nonprofit", phone: "614-280-1984", address: "175 S Third St Suite 250, Columbus, OH 43215", zip: "43215", desc: "Coalition on Homelessness and Housing in Ohio (COHHIO) — statewide coalition of 600+ housing-and-homelessness orgs. Operates Ohio Housing Locator, runs the Ohio Balance of State Continuum of Care (covers 80 of 88 counties), advocates for affordable-housing policy, and connects veterans to local SSVF and HUD-VASH resources." },
  { section: "HOUS", title: "Northeast Ohio Coalition for the Homeless (NEOCH)", cat: "housing", sub: "Rental Assistance", city: "Cleveland", website_url: "https://www.neoch.org/", source_name: "Northeast Ohio Coalition for the Homeless", source_type: "nonprofit", phone: "216-432-0540", address: "3631 Perkins Ave Suite 3A-3, Cleveland, OH 44114", zip: "44114", desc: "Northeast Ohio Coalition for the Homeless (NEOCH) — Cleveland-based homeless advocacy nonprofit; operates the Cleveland Street Card resource directory, voter ID assistance, civil-rights advocacy, and connects unsheltered veterans to LMM, VA HUD-VASH, and SSVF providers." },
  { section: "HOUS", title: "Ohio Housing Finance Agency (OHFA)", cat: "housing", sub: "Rental Assistance", city: "Columbus", website_url: "https://ohiohome.org/", source_name: "Ohio Housing Finance Agency", source_type: "state_agency", phone: "614-466-7970", address: "2600 Corporate Exchange Dr Suite 300, Columbus, OH 43231", zip: "43231", desc: "Ohio Housing Finance Agency (OHFA) — state agency; first-time homebuyer down-payment assistance (including Heroes program for veterans, active-duty, police, fire, EMTs, teachers), low-rate mortgage financing, and Housing Choice Voucher / Section 8 administration in non-PHA areas." },
  { section: "HOUS", title: "YWCA Greater Cleveland — Independence Place", cat: "housing", sub: "Transitional Housing", city: "Cleveland", website_url: "https://www.ywcaofcleveland.org/", source_name: "YWCA Greater Cleveland", source_type: "nonprofit", phone: "216-881-6878", address: "4019 Prospect Ave E, Cleveland, OH 44103", zip: "44103", desc: "YWCA Greater Cleveland — operates Independence Place permanent supportive housing for women aging out of foster care, NIA emergency shelter for women, and women's-only transitional housing programs; serves women veterans through SSVF and HUD-VASH coordination." },
  { section: "HOUS", title: "YWCA Columbus", cat: "housing", sub: "Emergency Housing", city: "Columbus", website_url: "https://www.ywcacolumbus.org/", source_name: "YWCA Columbus", source_type: "nonprofit", phone: "614-224-9121", address: "65 S 4th St, Columbus, OH 43215", zip: "43215", desc: "YWCA Columbus — operates the Family Center (largest family homeless shelter in Central Ohio), WINGS permanent supportive housing, and Griswold Building affordable women's housing. Serves veteran families among general population." },
  { section: "HOUS", title: "Catholic Charities Diocese of Cleveland — Housing Services", cat: "housing", sub: "Rental Assistance", city: "Cleveland", website_url: "https://www.ccdocle.org/", source_name: "Catholic Charities Diocese of Cleveland", source_type: "nonprofit", phone: "216-334-2900", address: "7911 Detroit Ave, Cleveland, OH 44102", zip: "44102", desc: "Catholic Charities Diocese of Cleveland — 8-county NE Ohio operations including Bishop Cosgrove Center (day shelter), Matt Talbot Inn recovery housing, Sancta Maria Hall transitional housing, Migration & Refugee Services housing placement, and emergency rent/utility assistance for veterans and families." },
  { section: "HOUS", title: "Catholic Social Services of the Miami Valley", cat: "housing", sub: "Rental Assistance", city: "Dayton", website_url: "https://www.cssmv.org/", source_name: "Catholic Social Services of the Miami Valley", source_type: "nonprofit", phone: "937-223-7217", address: "922 W Riverview Ave, Dayton, OH 45402", zip: "45402", desc: "Catholic Social Services of the Miami Valley — 9-county Dayton-region operations including Choices in Community Living, emergency rent/utility assistance, Adult Day Services for older veterans, and refugee resettlement housing placement." },
  { section: "HOUS", title: "Eden Inc — Permanent Supportive Housing (Columbus)", cat: "housing", sub: "Transitional Housing", city: "Columbus", website_url: "https://www.edeninc.org/", source_name: "Eden Inc", source_type: "nonprofit", phone: "614-255-4666", address: "3675 Olentangy River Rd, Columbus, OH 43214", zip: "43214", desc: "Eden Inc — Central Ohio's largest nonprofit affordable-housing developer; 50+ properties with 2,500+ units of permanent supportive housing for formerly-homeless individuals and families, including dedicated veteran units in partnership with Wylie VA HUD-VASH program." },
  { section: "HOUS", title: "EDEN (Emerald Development & Economic Network) — Cleveland", cat: "housing", sub: "Transitional Housing", city: "Cleveland", website_url: "https://www.edeninc.org/", source_name: "EDEN Inc Cleveland", source_type: "nonprofit", phone: "216-961-9690", address: "7812 Madison Ave, Cleveland, OH 44102", zip: "44102", desc: "EDEN Inc Cleveland — Cuyahoga County's largest provider of permanent supportive housing for chronically homeless adults with disabilities; 1,300+ housing units across 30+ properties, dedicated veteran units coordinated with Cleveland VAMC HUD-VASH and SSVF teams." },
  { section: "HOUS", title: "Community Shelter Board (Franklin County)", cat: "housing", sub: "Emergency Housing", city: "Columbus", website_url: "https://www.csb.org/", source_name: "Community Shelter Board", source_type: "nonprofit", phone: "614-221-9195", address: "355 E Campus View Blvd Suite 250, Columbus, OH 43235", zip: "43235", desc: "Community Shelter Board — lead agency for Franklin County Continuum of Care; coordinates the Coordinated Entry system, single-adult and family shelters, rapid-rehousing, and permanent supportive housing for 14,000+ people annually including veterans served via SSVF and HUD-VASH partnerships." },
  { section: "HOUS", title: "Strategies to End Homelessness (Hamilton County)", cat: "housing", sub: "Rental Assistance", city: "Cincinnati", website_url: "https://www.strategiestoendhomelessness.org/", source_name: "Strategies to End Homelessness", source_type: "nonprofit", phone: "513-263-2790", address: "2368 Victory Pkwy Suite 600, Cincinnati, OH 45206", zip: "45206", desc: "Strategies to End Homelessness — lead agency for Hamilton County Continuum of Care; coordinates Cincinnati Central Access Point (CAP), shelter diversion, rapid-rehousing, permanent supportive housing, and SSVF/HUD-VASH coordination with Cincinnati VAMC for homeless veterans." },
  { section: "HOUS", title: "Mercy House of the Akron-Canton Area", cat: "housing", sub: "Emergency Housing", city: "Akron", website_url: "https://mercyhouseministries.org/", source_name: "Mercy House Ministries", source_type: "nonprofit", phone: "330-535-5970", address: "150 Mercy Ln, Akron, OH 44307", zip: "44307", desc: "Mercy House Ministries — Akron-area emergency shelter for women and families experiencing homelessness; 90-day shelter stays with case management, food, clothing, and rehousing assistance. Serves women veterans among general population." },
  { section: "HOUS", title: "Toledo Lucas County Homelessness Board", cat: "housing", sub: "Rental Assistance", city: "Toledo", website_url: "https://tlchb.org/", source_name: "Toledo Lucas County Homelessness Board", source_type: "nonprofit", phone: "419-244-6711", address: "1946 N 13th St Suite 437, Toledo, OH 43604", zip: "43604", desc: "Toledo Lucas County Homelessness Board (TLCHB) — lead agency for the Toledo/Lucas County Continuum of Care; coordinates emergency shelter, rapid-rehousing, permanent supportive housing, the 1Matters annual Homeless Veterans Stand Down, and SSVF/HUD-VASH partnership with Toledo CBOC and Ann Arbor VAMC." },

  // ==============================================================
  // B. FOOD ASSISTANCE (14) — Ohio Association of Foodbanks (12) + Salvation Army (2)
  // ==============================================================
  { section: "FOOD", title: "Ohio Association of Foodbanks", cat: "food-assistance", sub: "Food Banks", city: "Columbus", website_url: "https://ohiofoodbanks.org/", source_name: "Ohio Association of Foodbanks", source_type: "nonprofit", phone: "614-221-4336", address: "51 N High St Suite 761, Columbus, OH 43215", zip: "43215", desc: "Ohio Association of Foodbanks — statewide coalition of Ohio's 12 Feeding America foodbanks serving all 88 counties through 3,600+ partner pantries, soup kitchens, and shelters. Operates SNAP outreach helpline, Ohio's CSFP commodity program, and benefits enrollment for veterans and low-income families." },
  { section: "FOOD", title: "Greater Cleveland Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Cleveland", website_url: "https://www.greaterclevelandfoodbank.org/", source_name: "Greater Cleveland Food Bank", source_type: "nonprofit", phone: "216-738-2265", address: "13815 Coit Rd, Cleveland, OH 44110", zip: "44110", desc: "Greater Cleveland Food Bank — largest hunger-relief organization in NE Ohio; serves Cuyahoga, Ashtabula, Geauga, Lake, Ashland, and Richland counties through 1,000+ partner pantries and meal programs. Veteran outreach via VA Cleveland VAMC, monthly drive-thru distributions, and SNAP application assistance." },
  { section: "FOOD", title: "Mid-Ohio Food Collective", cat: "food-assistance", sub: "Food Banks", city: "Grove City", website_url: "https://www.midohiofoodbank.org/", source_name: "Mid-Ohio Food Collective", source_type: "nonprofit", phone: "614-277-3663", address: "3960 Brookham Dr, Grove City, OH 43123", zip: "43123", desc: "Mid-Ohio Food Collective — Central Ohio's largest hunger-relief charity; serves 20 counties through 680+ partner pantries, mobile markets, and the Kroger Community Food Pantry. Distributes 75M+ pounds annually; partner Veterans Food Pantry events with Wylie VA OPC." },
  { section: "FOOD", title: "Freestore Foodbank (Cincinnati)", cat: "food-assistance", sub: "Food Banks", city: "Cincinnati", website_url: "https://freestorefoodbank.org/", source_name: "Freestore Foodbank", source_type: "nonprofit", phone: "513-482-4500", address: "1141 Central Pkwy, Cincinnati, OH 45202", zip: "45202", desc: "Freestore Foodbank — Greater Cincinnati's largest food bank; serves 20 counties across SW Ohio, NKY, and SE Indiana through 600+ partner agencies. Operates Liberty Street Center, Power Pack school program, SNAP outreach, and Veterans Pantry partnership with Cincinnati VAMC." },
  { section: "FOOD", title: "The Foodbank Inc (Dayton)", cat: "food-assistance", sub: "Food Banks", city: "Dayton", website_url: "https://thefoodbankdayton.org/", source_name: "The Foodbank Inc", source_type: "nonprofit", phone: "937-461-0265", address: "56 Armor Pl, Dayton, OH 45417", zip: "45417", desc: "The Foodbank Inc — Dayton-area regional food bank serving Montgomery, Greene, and Preble counties through 100+ partner pantries; distributes 24M+ pounds annually. Drive-thru distribution at Kettering, monthly mobile pantries, and Veterans Day distribution with Dayton VAMC." },
  { section: "FOOD", title: "Akron-Canton Regional Foodbank", cat: "food-assistance", sub: "Food Banks", city: "Akron", website_url: "https://www.akroncantonfoodbank.org/", source_name: "Akron-Canton Regional Foodbank", source_type: "nonprofit", phone: "330-535-6900", address: "350 Opportunity Pkwy, Akron, OH 44307", zip: "44307", desc: "Akron-Canton Regional Foodbank — serves 8 counties (Carroll, Holmes, Medina, Portage, Stark, Summit, Tuscarawas, Wayne) through 500+ partner agencies including pantries, soup kitchens, and shelters. Distributes 30M+ pounds annually; SNAP outreach and Senior Box program." },
  { section: "FOOD", title: "Toledo Northwestern Ohio Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Toledo", website_url: "https://toledofoodbank.org/", source_name: "Toledo Northwestern Ohio Food Bank", source_type: "nonprofit", phone: "419-242-5000", address: "24 E Woodruff Ave, Toledo, OH 43604", zip: "43604", desc: "Toledo Northwestern Ohio Food Bank — serves 8 NW Ohio counties (Defiance, Erie, Fulton, Henry, Lucas, Ottawa, Sandusky, Williams) through 200+ partner agencies. Mobile market routes, weekend BackPack program, SNAP outreach, and partnership with 1Matters Veterans Stand Down." },
  { section: "FOOD", title: "Second Harvest Food Bank of North Central Ohio", cat: "food-assistance", sub: "Food Banks", city: "Lorain", website_url: "https://www.secondharvestfoodbank.org/", source_name: "Second Harvest Food Bank of North Central Ohio", source_type: "nonprofit", phone: "440-960-2265", address: "5510 Baumhart Rd, Lorain, OH 44053", zip: "44053", desc: "Second Harvest Food Bank of North Central Ohio — serves Lorain, Erie, Crawford, and Huron counties through 100+ partner agencies. Mobile pantry routes, BackPack child-hunger program, Senior Box CSFP, and SNAP outreach." },
  { section: "FOOD", title: "Second Harvest Food Bank of the Mahoning Valley", cat: "food-assistance", sub: "Food Banks", city: "Youngstown", website_url: "http://www.mahoningvalleysecondharvest.org/", source_name: "Second Harvest Food Bank of the Mahoning Valley", source_type: "nonprofit", phone: "330-792-5522", address: "2805 Salt Springs Rd, Youngstown, OH 44509", zip: "44509", desc: "Second Harvest Food Bank of the Mahoning Valley — serves Mahoning, Trumbull, and Columbiana counties through 165+ partner pantries and soup kitchens; 12M+ pounds distributed annually. Mobile pantry, BackPack program, Senior Box CSFP, and SNAP outreach." },
  { section: "FOOD", title: "Shared Harvest Foodbank (Fairfield)", cat: "food-assistance", sub: "Food Banks", city: "Fairfield", website_url: "https://www.sharedharvest.org/", source_name: "Shared Harvest Foodbank", source_type: "nonprofit", phone: "513-874-0114", address: "5901 Dixie Hwy, Fairfield, OH 45014", zip: "45014", desc: "Shared Harvest Foodbank — serves Butler, Warren, Preble, Darke, and Miami counties through 130+ partner agencies; 14M+ pounds distributed annually. Mobile pantry, BackPack program, Senior Box CSFP, and SNAP application assistance." },
  { section: "FOOD", title: "West Ohio Food Bank (Lima)", cat: "food-assistance", sub: "Food Banks", city: "Lima", website_url: "https://westohiofoodbank.org/", source_name: "West Ohio Food Bank", source_type: "nonprofit", phone: "419-222-7946", address: "1380 E Kibby St, Lima, OH 45804", zip: "45804", desc: "West Ohio Food Bank — serves 11 NW Ohio counties (Allen, Auglaize, Hancock, Hardin, Logan, Mercer, Paulding, Putnam, Shelby, Van Wert, Wyandot) through 130+ partner agencies. Mobile pantry, BackPack program, Senior Box CSFP, and SNAP outreach." },
  { section: "FOOD", title: "Southeastern Ohio Foodbank (Logan)", cat: "food-assistance", sub: "Food Banks", city: "Logan", website_url: "https://www.hapcap.org/foodbank/", source_name: "Hocking Athens Perry Community Action (HAPCAP)", source_type: "nonprofit", phone: "740-385-6813", address: "1005 W Hunter St, Logan, OH 43138", zip: "43138", desc: "Southeastern Ohio Foodbank (HAPCAP) — serves 10 Appalachian SE Ohio counties (Athens, Hocking, Perry, Vinton, Morgan, Washington, Noble, Monroe, Meigs, Gallia) through 70+ partner pantries. Distributes 7M+ pounds annually in one of Ohio's most food-insecure regions; veteran outreach via Chillicothe VAMC partnership." },
  { section: "FOOD", title: "Salvation Army Northeast Ohio Division (Cleveland)", cat: "food-assistance", sub: "Food Banks", city: "Cleveland", website_url: "https://easternusa.salvationarmy.org/northeast-ohio/", source_name: "The Salvation Army", source_type: "nonprofit", phone: "216-781-3773", address: "2507 E 22nd St, Cleveland, OH 44115", zip: "44115", desc: "Salvation Army Northeast Ohio Division — operates 28 corps community centers across NE Ohio with food pantries, hot meal programs, emergency rent/utility assistance, holiday Angel Tree program, and Pathway of Hope intensive case management. Serves veteran families through SSVF coordination." },
  { section: "FOOD", title: "Salvation Army Central Ohio Area Services (Columbus)", cat: "food-assistance", sub: "Food Banks", city: "Columbus", website_url: "https://columbus.salvationarmy.us/", source_name: "The Salvation Army", source_type: "nonprofit", phone: "614-437-2100", address: "966 E Main St, Columbus, OH 43205", zip: "43205", desc: "Salvation Army Central Ohio Area Services — operates 6 corps community centers across Franklin & surrounding counties with food pantries, emergency shelter, hot meal programs, rent/utility assistance, and Pathway of Hope intensive family case management." },

  // ==============================================================
  // C. FINANCIAL (12) — credit unions, financial coaching, VITA, OH bonus
  // ==============================================================
  { section: "FIN", title: "Wright-Patt Credit Union", cat: "financial", sub: "Banking / Lending Support", city: "Beavercreek", website_url: "https://www.wpcu.coop/", source_name: "Wright-Patt Credit Union", source_type: "credit_union", phone: "937-912-7000", address: "3560 Pentagon Blvd, Beavercreek, OH 45431", zip: "45431", desc: "Wright-Patt Credit Union (WPCU) — Ohio's largest credit union by members (470,000+), founded 1932 to serve Wright-Patterson AFB. 35+ branches across Ohio and Indiana; military and veteran membership eligibility, free checking, low-rate auto/home loans, financial coaching, and Mil-Wallet active-duty banking." },
  { section: "FIN", title: "Kemba Financial Credit Union (Central Ohio)", cat: "financial", sub: "Banking / Lending Support", city: "Gahanna", website_url: "https://www.kemba.org/", source_name: "Kemba Financial Credit Union", source_type: "credit_union", phone: "614-235-2395", address: "555 Officenter Pl, Gahanna, OH 43230", zip: "43230", desc: "Kemba Financial Credit Union — Central Ohio member-owned credit union with 100,000+ members and 18 branches across Franklin and surrounding counties. Open SEG charter accepts veterans and active-duty; free checking, low-rate auto/home loans, free GreenPath financial counseling." },
  { section: "FIN", title: "Telhio Credit Union (Central Ohio)", cat: "financial", sub: "Banking / Lending Support", city: "Columbus", website_url: "https://www.telhio.org/", source_name: "Telhio Credit Union", source_type: "credit_union", phone: "614-221-3233", address: "96 N 4th St, Columbus, OH 43215", zip: "43215", desc: "Telhio Credit Union — Central Ohio member-owned credit union with 65,000+ members and branches across Franklin, Pickaway, and surrounding counties. Open membership accepts veterans; free checking, low-rate auto/home loans, BizLink small-business banking, and free financial education." },
  { section: "FIN", title: "Ohio Operation HOPE — Cincinnati", cat: "financial", sub: "Budgeting & Financial Coaching", city: "Cincinnati", website_url: "https://operationhope.org/", source_name: "Operation HOPE", source_type: "nonprofit", phone: "888-388-4673", address: "1331 Main St, Cincinnati, OH 45202", zip: "45202", desc: "Operation HOPE Inc — national nonprofit financial-empowerment platform with HOPE Inside locations in Cincinnati (US Bank Tower); free credit & money management coaching, small-business technical assistance, homebuyer counseling, and youth financial literacy. Veteran HOPE Corps for transitioning service members." },
  { section: "FIN", title: "ESOP — Empowering & Strengthening Ohio's People", cat: "financial", sub: "Budgeting & Financial Coaching", city: "Cleveland", website_url: "https://www.esop-cleveland.org/", source_name: "Empowering and Strengthening Ohio's People", source_type: "nonprofit", phone: "216-361-0718", address: "11890 Fairhill Rd, Cleveland, OH 44120", zip: "44120", desc: "ESOP — Empowering and Strengthening Ohio's People — HUD-certified housing counseling and financial coaching nonprofit serving 25 Ohio counties. Free foreclosure prevention, reverse-mortgage counseling, credit/budget coaching, identity-theft recovery, and tax preparation; veteran financial-stability programming." },
  { section: "FIN", title: "Apprisen — Consumer Credit Counseling", cat: "financial", sub: "Budgeting & Financial Coaching", city: "Columbus", website_url: "https://www.apprisen.com/", source_name: "Apprisen", source_type: "nonprofit", phone: "800-355-2227", address: "1500 W 3rd Ave Suite 225, Columbus, OH 43212", zip: "43212", desc: "Apprisen — nonprofit consumer credit counseling agency serving Ohio and 13 other states for 65+ years. Free debt-management plans, bankruptcy pre-filing & pre-discharge counseling, housing counseling, student-loan counseling, and Medicare planning; HUD- and NFCC-certified." },
  { section: "FIN", title: "Homeport — Housing & Financial Counseling (Columbus)", cat: "financial", sub: "Budgeting & Financial Coaching", city: "Columbus", website_url: "https://www.homeportohio.org/", source_name: "Homeport", source_type: "nonprofit", phone: "614-221-8889", address: "3443 Agler Rd, Columbus, OH 43219", zip: "43219", desc: "Homeport — Central Ohio's leading nonprofit affordable-housing developer and HUD-certified housing counseling agency; first-time homebuyer education, down-payment assistance, foreclosure prevention, and financial coaching. Operates 2,800+ affordable apartments and homeownership opportunities." },
  { section: "FIN", title: "Cincinnati Financial Empowerment Center", cat: "financial", sub: "Budgeting & Financial Coaching", city: "Cincinnati", website_url: "https://www.unitedwaygc.org/", source_name: "United Way of Greater Cincinnati", source_type: "nonprofit", phone: "513-762-7100", address: "2400 Reading Rd, Cincinnati, OH 45202", zip: "45202", desc: "United Way of Greater Cincinnati — operates the Free Tax Prep Coalition (VITA), Financial Stability collaborative, Born Learning early-childhood programs, and 211 community resource hotline serving Hamilton, Butler, Clermont, Warren, and surrounding counties." },
  { section: "FIN", title: "Goodwill Industries of Akron — Financial Coaching", cat: "financial", sub: "Budgeting & Financial Coaching", city: "Akron", website_url: "https://www.goodwillakron.org/", source_name: "Goodwill Industries of Akron", source_type: "nonprofit", phone: "330-724-6995", address: "570 E Waterloo Rd, Akron, OH 44319", zip: "44319", desc: "Goodwill Industries of Akron — workforce-development nonprofit serving 8 NE Ohio counties; integrated financial coaching paired with job training, GED prep, digital-literacy classes, and disability employment services. Veteran services include Operation Goodwill job placement." },

  // ==============================================================
  // D. LEGAL (12) — Legal Aid offices statewide + OSBA
  // ==============================================================
  { section: "LEGAL", title: "Legal Aid Society of Cleveland", cat: "legal", sub: "Legal Aid Services", city: "Cleveland", website_url: "https://lasclev.org/", source_name: "Legal Aid Society of Cleveland", source_type: "nonprofit", phone: "216-687-1900", address: "1223 W 6th St, Cleveland, OH 44113", zip: "44113", desc: "Legal Aid Society of Cleveland — 5-county NE Ohio civil legal aid (Cuyahoga, Ashtabula, Geauga, Lake, Lorain). Free legal representation for low-income residents in housing/eviction, family law, public benefits, consumer debt, immigration, and the Volunteer Lawyers for Veterans clinic at Cleveland VAMC." },
  { section: "LEGAL", title: "Legal Aid Society of Columbus", cat: "legal", sub: "Legal Aid Services", city: "Columbus", website_url: "http://www.columbuslegalaid.org/", source_name: "Legal Aid Society of Columbus", source_type: "nonprofit", phone: "614-241-2001", address: "1108 City Park Ave, Columbus, OH 43206", zip: "43206", desc: "Legal Aid Society of Columbus — 6-county Central Ohio civil legal aid (Franklin, Delaware, Madison, Marion, Morrow, Union). Free legal representation in housing/eviction, family law, public benefits, consumer protection, and the Veterans Civil Justice Initiative serving Wylie OPC and Chillicothe VAMC veterans." },
  { section: "LEGAL", title: "Legal Aid Society of Greater Cincinnati", cat: "legal", sub: "Legal Aid Services", city: "Cincinnati", website_url: "https://www.lascinti.org/", source_name: "Legal Aid Society of Greater Cincinnati", source_type: "nonprofit", phone: "513-241-9400", address: "215 E 9th St 5th Floor, Cincinnati, OH 45202", zip: "45202", desc: "Legal Aid Society of Greater Cincinnati — 7-county SW Ohio civil legal aid (Hamilton, Brown, Butler, Clermont, Clinton, Highland, Warren). Free representation in housing, family law, public benefits, consumer debt, and the Veterans Justice Project clinics at Cincinnati VAMC and Fort Thomas VA OPC." },
  { section: "LEGAL", title: "Advocates for Basic Legal Equality (ABLE) — Toledo", cat: "legal", sub: "Legal Aid Services", city: "Toledo", website_url: "https://www.ablelaw.org/", source_name: "Advocates for Basic Legal Equality", source_type: "nonprofit", phone: "419-255-0814", address: "525 Jefferson Ave Suite 300, Toledo, OH 43604", zip: "43604", desc: "Advocates for Basic Legal Equality (ABLE) — 32-county NW & W-Central Ohio civil legal aid. Free representation in housing/eviction, family law, public benefits, consumer protection, migrant farmworker law, and veteran-specific benefits & discharge-upgrade clinics." },
  { section: "LEGAL", title: "Community Legal Aid Services — Akron/Canton/Youngstown", cat: "legal", sub: "Legal Aid Services", city: "Akron", website_url: "https://www.communitylegalaid.org/", source_name: "Community Legal Aid Services", source_type: "nonprofit", phone: "330-983-2628", address: "50 S Main St Suite 800, Akron, OH 44308", zip: "44308", desc: "Community Legal Aid Services — 8-county NE Ohio civil legal aid (Summit, Stark, Mahoning, Trumbull, Columbiana, Medina, Portage, Wayne). Free representation in housing, family law, public benefits, consumer protection, and the Volunteer Lawyers Project veteran clinics with Stark, Summit, and Mahoning VSCs." },
  { section: "LEGAL", title: "Legal Aid of Western Ohio — Dayton", cat: "legal", sub: "Legal Aid Services", city: "Dayton", website_url: "https://lawolaw.org/", source_name: "Legal Aid of Western Ohio", source_type: "nonprofit", phone: "937-228-8088", address: "130 W 2nd St Suite 700, Dayton, OH 45402", zip: "45402", desc: "Legal Aid of Western Ohio (LAWO) — 32-county NW & W-Central Ohio civil legal aid sister to ABLE. Free representation in housing, family law, public benefits, consumer law, and veteran benefits with offices in Toledo, Defiance, Findlay, Lima, Springfield, and Dayton serving Dayton VAMC and Wright-Patterson personnel." },
  { section: "LEGAL", title: "Southeastern Ohio Legal Services (SEOLS)", cat: "legal", sub: "Legal Aid Services", city: "Athens", website_url: "https://www.ohiolegalhelp.org/", source_name: "Southeastern Ohio Legal Services", source_type: "nonprofit", phone: "740-594-3558", address: "10 W 2nd St, Athens, OH 45701", zip: "45701", desc: "Southeastern Ohio Legal Services (SEOLS) — 30-county SE Ohio Appalachian civil legal aid; free representation in housing/eviction, family law, public benefits, consumer protection, and veteran benefits. Offices in Athens, Cambridge, Chillicothe, Marietta, New Philadelphia, Portsmouth, Steubenville, Zanesville." },
  { section: "LEGAL", title: "Pro Seniors Inc — Legal Hotline (Cincinnati)", cat: "legal", sub: "Wills, Estate Planning & Probate", city: "Cincinnati", website_url: "https://www.proseniors.org/", source_name: "Pro Seniors Inc", source_type: "nonprofit", phone: "513-345-4160", address: "7162 Reading Rd Suite 1150, Cincinnati, OH 45237", zip: "45237", desc: "Pro Seniors Inc — Ohio's only statewide legal hotline dedicated to seniors (60+); free legal advice and brief services in elder law, Medicaid, Medicare, long-term care, guardianship, advance directives, consumer fraud, and elder abuse. Serves Ohio veterans 60+ statewide." },
  { section: "LEGAL", title: "Ohio State Bar Association — Lawyer Referral Service", cat: "legal", sub: "Pro Bono Legal Services", city: "Columbus", website_url: "https://www.ohiobar.org/public-resources/find-a-lawyer/", source_name: "Ohio State Bar Association", source_type: "professional_assoc", phone: "800-282-6556", address: "1700 Lake Shore Dr, Columbus, OH 43204", zip: "43204", desc: "Ohio State Bar Association Lawyer Referral & Information Service — connects Ohio residents to licensed attorneys in their county; reduced-fee initial consultation, military legal assistance referrals for active-duty and veterans, and modest-means panels for low-income clients." },
  { section: "LEGAL", title: "Cleveland Metropolitan Bar Association — Lawyer Referral", cat: "legal", sub: "Pro Bono Legal Services", city: "Cleveland", website_url: "https://www.clemetrobar.org/", source_name: "Cleveland Metropolitan Bar Association", source_type: "professional_assoc", phone: "216-696-3525", address: "1375 E 9th St Floor 2, Cleveland, OH 44114", zip: "44114", desc: "Cleveland Metropolitan Bar Association — Lawyer Referral Service connects NE Ohio residents to vetted attorneys with $50 reduced-fee consultations; Volunteer Lawyers for the Veterans clinic at Cleveland VAMC partners with Legal Aid Society of Cleveland." },
  { section: "LEGAL", title: "Ohio Disability Rights Law & Policy Center (Disability Rights Ohio)", cat: "legal", sub: "Disability Claims Assistance", city: "Columbus", website_url: "https://www.disabilityrightsohio.org/", source_name: "Disability Rights Ohio", source_type: "nonprofit", phone: "614-466-7264", address: "200 Civic Center Dr Suite 300, Columbus, OH 43215", zip: "43215", desc: "Disability Rights Ohio — federally-mandated Ohio Protection & Advocacy system; free legal advocacy for Ohioans with disabilities including disabled veterans. Special education, abuse/neglect investigation, voting rights, employment discrimination, ADA enforcement, and assistive-technology access." },
  { section: "LEGAL", title: "Ohio Justice & Policy Center", cat: "legal", sub: "Criminal Defense", city: "Cincinnati", website_url: "https://www.ohiojpc.org/", source_name: "Ohio Justice & Policy Center", source_type: "nonprofit", phone: "513-421-1108", address: "215 E 9th St Suite 601, Cincinnati, OH 45202", zip: "45202", desc: "Ohio Justice & Policy Center — statewide criminal-justice reform legal nonprofit; free reentry legal services (record sealing, CQE Certificates of Qualification for Employment), prison conditions advocacy, and the Veterans Reentry Project for justice-involved Ohio veterans." },

  // ==============================================================
  // E. EMPLOYMENT (10) — OhioMeansJobs, Goodwills, vet-specific
  // ==============================================================
  { section: "EMP", title: "OhioMeansJobs Cleveland-Cuyahoga County", cat: "employment", sub: "Job Placement Programs", city: "Cleveland", website_url: "https://omjcc.us/", source_name: "OhioMeansJobs Cleveland-Cuyahoga County", source_type: "county_agency", phone: "216-777-8200", address: "1910 Carnegie Ave, Cleveland, OH 44115", zip: "44115", desc: "OhioMeansJobs Cleveland-Cuyahoga County — local workforce board operating the Cuyahoga County OMJ Center with priority-of-service for veterans; LVER/DVOP staff, on-site job fairs, training-voucher access, and partnerships with Cleveland VAMC Compensated Work Therapy program." },
  { section: "EMP", title: "OhioMeansJobs Franklin County", cat: "employment", sub: "Job Placement Programs", city: "Columbus", website_url: "https://www.omjcfc.org/", source_name: "OhioMeansJobs Franklin County", source_type: "county_agency", phone: "614-559-5052", address: "1111 E Broad St, Columbus, OH 43205", zip: "43205", desc: "OhioMeansJobs Franklin County — local workforce board operating the Franklin County OMJ Center with priority-of-service for veterans; LVER/DVOP staff, sector-based training partnerships, and Wylie VA OPC Compensated Work Therapy and HVRP coordination." },
  { section: "EMP", title: "Goodwill Easter Seals Miami Valley (Dayton)", cat: "employment", sub: "Job Placement Programs", city: "Dayton", website_url: "https://www.gesmv.org/", source_name: "Goodwill Easter Seals Miami Valley", source_type: "nonprofit", phone: "937-461-4800", address: "1511 Kuntz Rd, Dayton, OH 45404", zip: "45404", desc: "Goodwill Easter Seals Miami Valley — Dayton-region workforce nonprofit; vocational evaluation, job training, supported employment for adults with disabilities, contract services for businesses, and Operation: Veteran Outreach providing dedicated job placement for area veterans." },
  { section: "EMP", title: "Goodwill Industries of Greater Cleveland & East Central Ohio", cat: "employment", sub: "Job Placement Programs", city: "Canton", website_url: "https://www.goodwillgoodskills.org/", source_name: "Goodwill Industries", source_type: "nonprofit", phone: "330-445-8350", address: "408 9th St SW, Canton, OH 44707", zip: "44707", desc: "Goodwill Industries of Greater Cleveland & East Central Ohio — 16-county NE/EC Ohio workforce nonprofit; job-readiness training, GED preparation, computer literacy, and Operation Goodwill veteran services with employment specialists at Cleveland and Canton VAs." },
  { section: "EMP", title: "Goodwill Columbus", cat: "employment", sub: "Job Placement Programs", city: "Columbus", website_url: "https://www.goodwillcolumbus.org/", source_name: "Goodwill Columbus", source_type: "nonprofit", phone: "614-294-5181", address: "1331 Edgehill Rd, Columbus, OH 43212", zip: "43212", desc: "Goodwill Columbus — Central Ohio workforce nonprofit; job-readiness training, vocational rehabilitation, supported employment for people with disabilities including disabled veterans, and Goodwill Manufacturing/Contract Services with priority hiring for Wylie VAMC referrals." },
  { section: "EMP", title: "Hire Heroes USA — Ohio", cat: "employment", sub: "Career Counseling", city: "Columbus", website_url: "https://www.hireheroesusa.org/", source_name: "Hire Heroes USA", source_type: "nonprofit", phone: "844-634-1520", address: "Statewide remote service", zip: "43215", desc: "Hire Heroes USA — national veteran-employment nonprofit serving Ohio veterans, transitioning service members, and military spouses; free 1-on-1 career coaching, federal-resume writing, mock interviews, LinkedIn coaching, and employer-introduction Job Board with 100,000+ veteran placements nationally." },
  { section: "EMP", title: "Helmets to Hardhats — Ohio", cat: "employment", sub: "Apprenticeships & Skilled Trades", city: "Columbus", website_url: "https://helmetstohardhats.org/", source_name: "Helmets to Hardhats", source_type: "nonprofit", phone: "866-741-6210", address: "Statewide service", zip: "43215", desc: "Helmets to Hardhats — joint labor-management nonprofit connecting veterans, transitioning service members, and Reservists/Guardsmen to skilled-trades apprenticeships and careers in Ohio's union construction industry. Free placement, GI-Bill apprenticeship benefits guidance, and signatory contractor referrals." },
  { section: "EMP", title: "Easterseals Northern Ohio", cat: "employment", sub: "Vocational Rehabilitation", city: "Cleveland", website_url: "https://www.easterseals.com/", source_name: "Easterseals Northern Ohio", source_type: "nonprofit", phone: "216-432-1414", address: "2173 W 25th St, Cleveland, OH 44113", zip: "44113", desc: "Easterseals Northern Ohio — disability-services nonprofit serving 26 NE Ohio counties; vocational evaluation, job-readiness training, supported employment, autism services, military & veteran services, Camp Cheerful adaptive recreation, and home-modification services for disabled veterans." },

  // ==============================================================
  // F. FAMILY-SUPPORT (8) — military family, Operation Homefront, Blue Star Mothers, USO
  // ==============================================================
  { section: "FAM", title: "Operation Homefront — Ohio", cat: "family-support", sub: "Military Family Support", city: "Columbus", website_url: "https://www.operationhomefront.org/", source_name: "Operation Homefront", source_type: "nonprofit", phone: "210-659-7756", address: "Statewide service", zip: "43215", desc: "Operation Homefront — national nonprofit serving Ohio military and veteran families with critical financial assistance (rent, utilities, auto repair), Holiday Meals for Military, Back-to-School Brigade backpack program, Star-Spangled Babies layette program, and Transitional Homes for Community Reintegration in Cincinnati." },
  { section: "FAM", title: "Blue Star Mothers of America — Ohio Chapters", cat: "family-support", sub: "Military Family Support", city: "Columbus", website_url: "https://www.bluestarmothers.org/", source_name: "Blue Star Mothers of America", source_type: "nonprofit", phone: "419-238-3550", address: "Statewide service - 35+ OH chapters", zip: "43215", desc: "Blue Star Mothers of America — Ohio is the founding state with 35+ active chapters statewide. Mothers of active-duty service members provide care packages to deployed troops, support military families during deployment, welcome-home events, and bereavement support for Gold Star families." },
  { section: "FAM", title: "USO of Northern Ohio", cat: "family-support", sub: "Military Family Support", city: "Cleveland", website_url: "https://www.uso.org/", source_name: "USO Northern Ohio", source_type: "nonprofit", phone: "216-265-2400", address: "5300 Riverside Dr, Cleveland, OH 44135", zip: "44135", desc: "USO of Northern Ohio — operates the Cleveland Hopkins International Airport USO Center providing free meals, snacks, Wi-Fi, and respite for traveling service members and military families across Northern Ohio. Mobile USO at military events, Holiday Meals, and Operation USO Care Package." },
  { section: "FAM", title: "TAPS — Tragedy Assistance Program for Survivors (Ohio)", cat: "family-support", sub: "Gold Star Family Support", city: "Columbus", website_url: "https://www.taps.org/", source_name: "Tragedy Assistance Program for Survivors", source_type: "nonprofit", phone: "800-959-8277", address: "Statewide service", zip: "43215", desc: "TAPS — Tragedy Assistance Program for Survivors — national nonprofit serving Ohio's Gold Star families and survivors of fallen service members with peer-based emotional support, casework assistance, grief counseling referrals, Good Grief Camps for children, and an annual National Military Survivor Seminar." },
  { section: "FAM", title: "Gold Star Wives of America — Ohio", cat: "family-support", sub: "Military Family Support", city: "Columbus", website_url: "https://www.goldstarwives.org/", source_name: "Gold Star Wives of America", source_type: "nonprofit", phone: "888-751-6350", address: "Statewide service", zip: "43215", desc: "Gold Star Wives of America — congressionally-chartered VSO of widows whose spouses died on active duty or from service-connected causes; Ohio chapters in Cleveland, Columbus, Cincinnati, and Dayton offer peer support, DIC/SBP benefits navigation, and advocacy for surviving spouses." },
  { section: "FAM", title: "Military Officers Association of America (MOAA) — Ohio Council", cat: "family-support", sub: "Military Family Support", city: "Columbus", website_url: "https://www.moaa.org/", source_name: "Military Officers Association of America", source_type: "nonprofit", phone: "800-234-6622", address: "Statewide service - 12+ OH chapters", zip: "43215", desc: "Military Officers Association of America (MOAA) — largest officer-association VSO; 12+ Ohio chapters (Cleveland, Columbus, Cincinnati, Dayton/Wright-Patt, Toledo, Springfield, Akron) for currently-serving and retired officers/warrants/spouses. Career-transition assistance, scholarship loans for military children, and benefits advocacy." },
  { section: "FAM", title: "Ohio National Guard Family Readiness Program", cat: "family-support", sub: "Military Family Support", city: "Columbus", website_url: "https://ong.ohio.gov/", source_name: "Ohio National Guard", source_type: "state_agency", phone: "614-336-7000", address: "2825 W Dublin Granville Rd, Columbus, OH 43235", zip: "43235", desc: "Ohio National Guard Family Readiness Program — full-time Family Readiness Support Assistants and volunteer Family Readiness Group leaders at every OHARNG armory and OANG wing. Pre/during/post-deployment family support, child & youth programs, Survivor Outreach Services, and Yellow Ribbon Reintegration." },
  { section: "FAM", title: "Snowball Express (Gary Sinise Foundation) — Ohio", cat: "family-support", sub: "Gold Star Family Support", city: "Columbus", website_url: "https://www.garysinisefoundation.org/snowball-express", source_name: "Gary Sinise Foundation Snowball Express", source_type: "nonprofit", phone: "888-885-9011", address: "Statewide service", zip: "43215", desc: "Snowball Express (Gary Sinise Foundation) — annual all-expenses-paid trip to Walt Disney World for children of fallen U.S. military heroes (under 18, lost a parent in active service post-9/11). Year-round bereavement support and regional Ohio meetups for Gold Star families." },

  // ==============================================================
  // G. EDUCATION (8) — GI Bill, OH state aid, university vet centers
  // ==============================================================
  { section: "EDU", title: "Ohio State University Office of Military and Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Columbus", website_url: "https://veterans.osu.edu/", source_name: "The Ohio State University", source_type: "university", phone: "614-247-VETS", address: "281 W Lane Ave, Columbus, OH 43210", zip: "43210", desc: "Ohio State University Office of Military and Veterans Services — supports 2,000+ veteran/military-affiliated OSU students; GI Bill certification, VetSuccess on Campus (VSOC) counselor, Buckeye Vet Network mentoring, dedicated student lounge in Postle Hall, and the Military and Veterans Studies minor." },
  { section: "EDU", title: "University of Cincinnati Veterans Programs & Services", cat: "education", sub: "Veteran Student Services", city: "Cincinnati", website_url: "https://www.uc.edu/", source_name: "University of Cincinnati", source_type: "university", phone: "513-556-6811", address: "2614 McMicken Cir, Cincinnati, OH 45221", zip: "45221", desc: "University of Cincinnati Veterans Programs & Services — supports 1,000+ veteran/military students; GI Bill certification, VetSuccess on Campus counselor, Veterans Center in Stratford Heights, UC Vet Net mentoring, and Yellow Ribbon Program participation." },
  { section: "EDU", title: "Wright State University Veteran & Military Center", cat: "education", sub: "Veteran Student Services", city: "Dayton", website_url: "https://www.wright.edu/veteran-and-military-center", source_name: "Wright State University", source_type: "university", phone: "937-775-5550", address: "3640 Colonel Glenn Hwy, Dayton, OH 45435", zip: "45435", desc: "Wright State University Veteran & Military Center — supports 1,500+ veteran/military students adjacent to Wright-Patterson AFB; GI Bill & TA certification, VetSuccess on Campus counselor, dedicated Veteran & Military Center in Allyn Hall, and Yellow Ribbon participation." },
  { section: "EDU", title: "Kent State University Center for Adult & Veteran Services", cat: "education", sub: "Veteran Student Services", city: "Kent", website_url: "https://www.kent.edu/cavs", source_name: "Kent State University", source_type: "university", phone: "330-672-7933", address: "164 Schwartz Center, Kent, OH 44242", zip: "44242", desc: "Kent State University Center for Adult and Veteran Services — supports 800+ veteran/military students across Kent's 8-campus system; GI Bill certification, Veterans Lounge in Schwartz Center, Student Veterans Association, and the Salute Veterans National Honor Society chapter." },
  { section: "EDU", title: "Ohio College Tuition Trust Authority — CollegeAdvantage 529", cat: "education", sub: "Tuition Assistance", city: "Columbus", website_url: "https://www.collegeadvantage.com/", source_name: "Ohio Tuition Trust Authority", source_type: "state_agency", phone: "800-233-6734", address: "35 E Chestnut St 8th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Tuition Trust Authority — administers CollegeAdvantage Ohio's 529 Plan (Direct & Advisor Plans) for K-12 and higher-education savings; tax-deductible contributions for Ohio families including military and veteran families saving for dependents' education on top of GI Bill transfers." },

  // ==============================================================
  // H. INSURANCE (6) — TRICARE, OSHIIP, USAA, VA insurance
  // ==============================================================
  { section: "INS", title: "Ohio Senior Health Insurance Information Program (OSHIIP)", cat: "insurance", sub: "Medicare & VA Plans", city: "Columbus", website_url: "https://www.shiphelp.org/about-medicare/regional-ship-location", source_name: "SHIP National Technical Assistance Center", source_type: "nonprofit", phone: "800-686-1578", address: "50 W Town St 3rd Floor Suite 300, Columbus, OH 43215", zip: "43215", desc: "Ohio Senior Health Insurance Information Program (OSHIIP) — Ohio's federally-funded SHIP under Ohio Department of Insurance; free unbiased Medicare counseling for Ohioans 65+ including older veterans coordinating Medicare with VA healthcare. 88-county volunteer counselor network, Medicare/Medigap/Part D plan comparison, and fraud prevention. Locator: shiphelp.org." },
  { section: "INS", title: "TRICARE East Region (Humana Military)", cat: "insurance", sub: "Health Insurance", city: "Columbus", website_url: "https://www.humanamilitary.com/", source_name: "Humana Military / TRICARE East", source_type: "federal_program", phone: "800-444-5445", address: "Serves Ohio statewide", zip: "43215", desc: "TRICARE East Region (Humana Military) — Department of Defense managed-care contractor for the 32-state Eastern region including Ohio; administers TRICARE Prime, Select, and US Family Health Plan benefits for active-duty, retired, Reserve/Guard, and family members. Ohio Wright-Patterson AFB enrollment center and statewide network providers." },
  { section: "INS", title: "USAA — Member Service (Veterans & Military Families)", cat: "insurance", sub: "Auto Insurance", city: "Columbus", website_url: "https://www.usaa.com/", source_name: "USAA", source_type: "for_profit", phone: "800-531-8722", address: "Serves Ohio statewide", zip: "43215", desc: "USAA — financial-services company exclusively serving current and former U.S. military members and their families; auto, home, renters, life, and health insurance, banking, investments, and retirement services for 13M+ members. Military-aware claims handling and SCRA compliance." },
  { section: "INS", title: "VA Insurance (SGLI/VGLI/Servicemembers' & Veterans' Group Life)", cat: "insurance", sub: "Life Insurance", city: "Cleveland", website_url: "https://www.va.gov/life-insurance/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "800-419-1473", address: "VA Insurance Center, Philadelphia, PA serves OH", zip: "44199", desc: "VA Life Insurance Programs — administered by VA Insurance Center for Ohio veterans; includes VGLI (Veterans' Group Life Insurance — convert SGLI within 1 year of separation), Service-Disabled Veterans Insurance (S-DVI), Veterans Mortgage Life Insurance (VMLI for SAH grant recipients), and beneficiary financial counseling." },

  // ==============================================================
  // I. DISABLED-VETERANS deepening (5)
  // ==============================================================
  { section: "DV", title: "Wounded Warrior Project — Northeast Region (Ohio)", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Cleveland", website_url: "https://www.woundedwarriorproject.org/", source_name: "Wounded Warrior Project", source_type: "nonprofit", phone: "888-997-2586", address: "Northeast Region serves Ohio", zip: "44199", desc: "Wounded Warrior Project (WWP) — national post-9/11 wounded-veteran nonprofit; Ohio members served by NE Region staff with mental-health Project Odyssey, Warriors to Work career counseling, Independence Program for severely-injured warriors, Combat Stress Recovery Program, and the WWP Talk peer-support phone line." },
  { section: "DV", title: "Blinded Veterans Association — Buckeye Regional Group", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Cleveland", website_url: "https://bva.org/", source_name: "Blinded Veterans Association", source_type: "nonprofit", phone: "800-669-7079", address: "Cleveland VAMC BROS, 10701 East Blvd, Cleveland, OH 44106", zip: "44106", desc: "Blinded Veterans Association (BVA) — congressionally-chartered VSO for legally-blind veterans; Buckeye Regional Group serves Ohio with peer support, free VA-claims assistance via BVA national service officers co-located at VA Blind Rehabilitation Service centers (Cleveland VAMC has BROS - Blind Rehab Outpatient Specialist)." },
  { section: "DV", title: "Disabled American Veterans (DAV) Department of Ohio", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Columbus", website_url: "https://dav.org/find-your-local-office/?_state=Ohio", source_name: "DAV Department of Ohio", source_type: "nonprofit", phone: "614-431-6990", address: "1655 Old Leonard Ave, Columbus, OH 43219", zip: "43219", desc: "DAV Department of Ohio — congressionally-chartered VSO with 35,000+ Ohio members across 100+ chapters and 9 districts. Free VA disability claims representation by DAV National Service Officers stationed at Cleveland VARO; DAV Transportation Network drives veterans to all 5 OH VAMCs and CBOCs." },
  { section: "DV", title: "VA Caregiver Support — Cleveland VAMC", cat: "disabled-veterans", sub: "Caregiver & Family Support", city: "Cleveland", website_url: "https://www.va.gov/family-and-caregiver-benefits/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "855-260-3274", address: "10701 East Blvd, Cleveland, OH 44106", zip: "44106", desc: "VA Caregiver Support Program — Cleveland VAMC Caregiver Support Coordinator administers the Program of Comprehensive Assistance for Family Caregivers (PCAFC) including monthly stipend, CHAMPVA health insurance, mental-health counseling, respite care, and Caregiver Support Line for caregivers of disabled OH veterans." },
];

console.log(`[seed-oh-phase4] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);

runSeed(ROWS, {
  state: "OH",
  state_full: "Ohio",
  commit: COMMIT,
  scriptName: "seed-oh-phase4",
}).catch((e) => { console.error(e); process.exit(1); });
