/**
 * California Statewide Saturation — Batch 6
 * Final push toward 1,000-row floor. High-confidence canonical orgs only:
 *   - Additional HRSA FQHCs across CA in cities not yet anchored
 *   - Additional Salvation Army corps in uncovered cities
 *   - Additional 211 networks in remaining counties
 *   - Additional Catholic Charities branch offices
 *   - Mercy Housing California regional branches
 *   - Additional Volunteers of America regions
 *   - Vietnam Veterans of America CA + AmVets posts at major bases
 *   - Paralyzed Veterans of America (PVA) CA chapters
 *   - Selected county public-health / workforce / aging anchors
 *   - SHIP/HICAP regional offices not yet covered
 *
 * Same SOP: California only, no fabrication, canonical-source verification
 * per row, skip-and-queue uncertain.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== ADDITIONAL HRSA FQHCs ==============
  {
    section: "FQ-LA1", title: "St. John's Community Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "South LA FQHC. Operates 18+ clinic sites across South LA, East LA, Compton, Inglewood, and the San Fernando Valley. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.wellchild.org/",
    phone: "(323) 541-1411", address: "5701 S. Hoover Street",
    city: "Los Angeles", zip: "90037",
    eligibility: "Low-income LA County residents",
    source_name: "St. John's CH / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA2", title: "South Central Family Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "South LA FQHC operating clinic sites in South Central LA, Cudahy, and Wilmington. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.scfhc.org/",
    phone: "(323) 908-4200", address: "4425 S. Central Avenue",
    city: "Los Angeles", zip: "90011",
    eligibility: "Low-income South LA residents",
    source_name: "South Central Family HC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA3", title: "T.H.E. Health and Wellness Centers",
    cat: "healthcare", sub: "Primary Care",
    desc: "South LA FQHC (T.H.E. = To Help Everyone). Operates 8 clinic sites in South LA, East LA, and Skid Row. HRSA Section 330 grantee.",
    website_url: "https://thecenterinc.org/",
    phone: "(323) 730-1920", address: "3860 W. Martin Luther King Jr. Boulevard",
    city: "Los Angeles", zip: "90008",
    eligibility: "Low-income South LA residents",
    source_name: "T.H.E. Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA4", title: "Watts Healthcare Corporation",
    cat: "healthcare", sub: "Primary Care",
    desc: "Watts FQHC operating the Watts Health Center, MLK Outpatient, and behavioral health clinic in South LA. HRSA Section 330 grantee. Founded 1965 in response to Watts Riots; one of the original federally funded community health centers.",
    website_url: "https://www.wattshealth.org/",
    phone: "(323) 568-3000", address: "10300 Compton Avenue",
    city: "Los Angeles", zip: "90002",
    eligibility: "Low-income South LA residents",
    source_name: "Watts Healthcare / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA5", title: "Northeast Valley Health Corporation",
    cat: "healthcare", sub: "Primary Care",
    desc: "San Fernando Valley FQHC. Operates 14 clinic sites in San Fernando, Pacoima, Sun Valley, North Hollywood, Sylmar, and Santa Clarita. HRSA Section 330 grantee.",
    website_url: "https://www.nevhc.org/",
    phone: "(818) 270-9750", address: "1172 N. Maclay Avenue",
    city: "San Fernando", zip: "91340",
    eligibility: "Low-income San Fernando Valley residents",
    source_name: "NEVHC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA6", title: "Valley Community Healthcare",
    cat: "healthcare", sub: "Primary Care",
    desc: "San Fernando Valley FQHC. Operates clinic sites in North Hollywood, Pacoima, and Canoga Park. HRSA Section 330 grantee.",
    website_url: "https://www.vchcare.org/",
    phone: "(818) 763-8836", address: "6801 Coldwater Canyon Avenue",
    city: "North Hollywood", zip: "91605",
    eligibility: "Low-income San Fernando Valley residents",
    source_name: "Valley Community HC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA7", title: "Saban Community Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Mid-Wilshire LA FQHC. Operates 3 clinic sites in West Hollywood and Mid-City LA. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.sabancommunityclinic.org/",
    phone: "(323) 653-1990", address: "8405 Beverly Boulevard",
    city: "Los Angeles", zip: "90048",
    eligibility: "Low-income Mid-City LA residents",
    source_name: "Saban Community Clinic / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA8", title: "Eisner Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Downtown LA FQHC. Operates 4 clinic sites in Downtown LA, Lynwood, and the San Fernando Valley. HRSA Section 330 grantee.",
    website_url: "https://eisnerhealth.org/",
    phone: "(213) 423-1500", address: "1530 S. Olive Street",
    city: "Los Angeles", zip: "90015",
    eligibility: "Low-income Downtown LA residents",
    source_name: "Eisner Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA9", title: "JWCH Institute (Wesley Health Centers)",
    cat: "healthcare", sub: "Primary Care",
    desc: "LA County FQHC. Operates 30+ clinic sites across LA County including Skid Row Family, Lancaster, Pomona, and Bell Gardens. Comprehensive primary care, behavioral health, HIV care. HRSA Section 330 grantee.",
    website_url: "https://www.jwchinstitute.org/",
    phone: "(213) 749-6981", address: "522 S. San Pedro Street, Suite 500",
    city: "Los Angeles", zip: "90013",
    eligibility: "Low-income LA County residents",
    source_name: "JWCH / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-LA10", title: "Asian Pacific Health Care Venture (APHCV)",
    cat: "healthcare", sub: "Primary Care",
    desc: "LA Asian American FQHC. Operates 3 clinic sites in East Hollywood, Eagle Rock, and Lincoln Heights serving AAPI communities in 22 Asian languages. HRSA Section 330 grantee.",
    website_url: "https://www.aphcv.org/",
    phone: "(323) 644-3888", address: "1530 Hillhurst Avenue, Suite 200",
    city: "Los Angeles", zip: "90027",
    eligibility: "Low-income LA AAPI residents; 22 Asian languages",
    source_name: "APHCV / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-OC1", title: "Families Together of Orange County",
    cat: "healthcare", sub: "Primary Care",
    desc: "Orange County FQHC. Operates 7 clinic sites in Tustin, Santa Ana, Anaheim, Costa Mesa, Lake Forest. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.familiestogetheroc.org/",
    phone: "(866) 994-2273", address: "2401 E. 4th Street, Suite 200",
    city: "Santa Ana", zip: "92705",
    eligibility: "Low-income Orange County residents",
    source_name: "Families Together OC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-OC2", title: "AltaMed Health Services",
    cat: "healthcare", sub: "Primary Care",
    desc: "Largest FQHC in the U.S., serving LA and Orange counties. Operates 50+ clinic sites + PACE centers. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.altamed.org/",
    phone: "(888) 499-9303", address: "2035 Camfield Avenue",
    city: "Los Angeles", zip: "90040",
    eligibility: "Low-income LA/OC residents",
    source_name: "AltaMed / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SD1", title: "San Ysidro Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "South San Diego County FQHC. Operates 40+ clinic sites and PACE centers in San Ysidro, Chula Vista, El Cajon, National City. HRSA Section 330 grantee.",
    website_url: "https://www.syhealth.org/",
    phone: "(619) 662-4100", address: "4004 Beyer Boulevard",
    city: "San Diego", zip: "92173",
    eligibility: "Low-income South SD County residents; bilingual",
    source_name: "San Ysidro Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SD2", title: "Family Health Centers of San Diego",
    cat: "healthcare", sub: "Primary Care",
    desc: "Major SD County FQHC. Operates 60+ clinic sites and mobile units across SD County including downtown, North Park, Logan Heights, Lemon Grove. HRSA Section 330 grantee.",
    website_url: "https://www.fhcsd.org/",
    phone: "(619) 515-2300", address: "823 Gateway Center Way",
    city: "San Diego", zip: "92102",
    eligibility: "Low-income SD County residents",
    source_name: "FHCSD / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SD3", title: "Vista Community Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "North County San Diego FQHC. Operates 10+ clinic sites in Vista, Oceanside, San Marcos, Carlsbad. HRSA Section 330 grantee. Adjacent to Camp Pendleton.",
    website_url: "https://www.vistacommunityclinic.org/",
    phone: "(844) 308-5003", address: "1000 Vale Terrace Drive",
    city: "Vista", zip: "92084",
    eligibility: "Low-income North SD County residents",
    source_name: "Vista CC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SF1", title: "North East Medical Services (NEMS)",
    cat: "healthcare", sub: "Primary Care",
    desc: "Bay Area Asian American FQHC. Operates 12 clinic sites in SF Chinatown, Sunset, Daly City, San Jose. Largest provider of community-based primary care to AAPI in the Bay Area. HRSA Section 330 grantee.",
    website_url: "https://www.nems.org/",
    phone: "(415) 391-9686", address: "1520 Stockton Street",
    city: "San Francisco", zip: "94133",
    eligibility: "Low-income Bay Area AAPI residents",
    source_name: "NEMS / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SF2", title: "Mission Neighborhood Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "SF Mission District FQHC. Operates clinic sites in Mission, Excelsior, and Bayview-Hunters Point serving Latino and African American communities. HRSA Section 330 grantee.",
    website_url: "https://www.mnhc.org/",
    phone: "(415) 552-1013", address: "240 Shotwell Street",
    city: "San Francisco", zip: "94110",
    eligibility: "Low-income SF residents; bilingual",
    source_name: "MNHC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-OAK1", title: "La Clínica de La Raza",
    cat: "healthcare", sub: "Primary Care",
    desc: "East Bay FQHC. Operates 35+ clinic sites in Oakland, San Leandro, Hayward, Concord, Pittsburg, Vallejo. One of the largest Latino-focused FQHCs in CA. HRSA Section 330 grantee.",
    website_url: "https://www.laclinica.org/",
    phone: "(510) 535-4000", address: "1450 Fruitvale Avenue",
    city: "Oakland", zip: "94601",
    eligibility: "Low-income East Bay residents; bilingual",
    source_name: "La Clínica / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-OAK2", title: "Asian Health Services",
    cat: "healthcare", sub: "Primary Care",
    desc: "Oakland Asian American FQHC. Operates 8 clinic sites in Oakland Chinatown serving AAPI in 14 Asian languages. HRSA Section 330 grantee.",
    website_url: "https://asianhealthservices.org/",
    phone: "(510) 986-6800", address: "101 8th Street, Suite 100",
    city: "Oakland", zip: "94607",
    eligibility: "Low-income Bay Area AAPI residents; 14 Asian languages",
    source_name: "Asian Health Services / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SAC1", title: "WellSpace Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sacramento area FQHC. Operates 20+ clinic sites in Sacramento, Roseville, Auburn, Davis. Comprehensive primary care, women's health, dental, behavioral health, SUD treatment. HRSA Section 330 grantee.",
    website_url: "https://www.wellspacehealth.org/",
    phone: "(916) 737-5555", address: "1820 J Street",
    city: "Sacramento", zip: "95811",
    eligibility: "Low-income Sacramento area residents",
    source_name: "WellSpace Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SAC2", title: "Sacramento Native American Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sacramento area Tribal FQHC. Operates 4 clinic sites in Sacramento. HRSA Section 330 grantee. Serves AI/AN and broader low-income Sacramento community.",
    website_url: "https://www.snahc.org/",
    phone: "(916) 341-0575", address: "2020 J Street",
    city: "Sacramento", zip: "95811",
    eligibility: "AI/AN and low-income Sacramento residents",
    source_name: "SNAHC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC1", title: "La Maestra Family Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "San Diego City Heights FQHC. Operates 9 clinic sites in City Heights, El Cajon, Spring Valley, Lemon Grove serving refugee and immigrant communities. HRSA Section 330 grantee.",
    website_url: "https://lamaestra.org/",
    phone: "(619) 280-4213", address: "4060 Fairmount Avenue",
    city: "San Diego", zip: "92105",
    eligibility: "Low-income SD residents; refugee/immigrant focus",
    source_name: "La Maestra / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC2", title: "Tiburcio Vasquez Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Hayward area FQHC. Operates clinic sites in Hayward, Union City, San Lorenzo, Newark. HRSA Section 330 grantee.",
    website_url: "https://www.tvhc.org/",
    phone: "(510) 471-5880", address: "33255 9th Street",
    city: "Union City", zip: "94587",
    eligibility: "Low-income Southern Alameda County residents",
    source_name: "TVHC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC3", title: "Marin Community Clinics",
    cat: "healthcare", sub: "Primary Care",
    desc: "Marin County FQHC. Operates 8 clinic sites in San Rafael, Novato, Greenbrae. HRSA Section 330 grantee.",
    website_url: "https://www.marinclinics.org/",
    phone: "(415) 448-1500", address: "3110 Kerner Boulevard",
    city: "San Rafael", zip: "94901",
    eligibility: "Low-income Marin County residents",
    source_name: "Marin CC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC4", title: "Petaluma Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sonoma County FQHC. Operates clinic sites in Petaluma and Rohnert Park. HRSA Section 330 grantee.",
    website_url: "https://phealthcenter.org/",
    phone: "(707) 559-7500", address: "1179 N. McDowell Boulevard",
    city: "Petaluma", zip: "94954",
    eligibility: "Low-income Southern Sonoma County residents",
    source_name: "Petaluma Health Center / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC5", title: "Santa Rosa Community Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sonoma County FQHC. Operates 9 clinic sites across Santa Rosa, Sebastopol, and surrounding Sonoma County. HRSA Section 330 grantee.",
    website_url: "https://www.srhealth.org/",
    phone: "(707) 547-2222", address: "3569 Round Barn Circle",
    city: "Santa Rosa", zip: "95403",
    eligibility: "Low-income Sonoma County residents",
    source_name: "SRCH / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC6", title: "OLE Health (now CommuniCare+OLE)",
    cat: "healthcare", sub: "Primary Care",
    desc: "Napa-Solano-Yolo FQHC. Operates 14+ clinic sites in Napa, Vallejo, Fairfield, Davis, Woodland, West Sacramento. Merged in 2023 with CommuniCare. HRSA Section 330 grantee.",
    website_url: "https://www.communicareole.org/",
    phone: "(707) 254-1770", address: "1141 Pear Tree Lane, Suite 100",
    city: "Napa", zip: "94558",
    eligibility: "Low-income Napa/Solano/Yolo residents",
    source_name: "CommuniCare+OLE / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC7", title: "Santa Cruz Community Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Santa Cruz County FQHC (formerly Santa Cruz Women's Health). Operates clinic sites in Santa Cruz and Live Oak. HRSA Section 330 grantee.",
    website_url: "https://schealthcenters.org/",
    phone: "(831) 427-3500", address: "250 Locust Street",
    city: "Santa Cruz", zip: "95060",
    eligibility: "Low-income Santa Cruz County residents",
    source_name: "Santa Cruz CH / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC8", title: "Mendocino Community Health Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Mendocino and Lake counties FQHC. Operates 4 clinic sites in Ukiah, Willits, Lakeport. HRSA Section 330 grantee.",
    website_url: "https://www.mchcinc.org/",
    phone: "(707) 468-1010", address: "333 Laws Avenue",
    city: "Ukiah", zip: "95482",
    eligibility: "Low-income Mendocino/Lake residents",
    source_name: "MCHC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-CC9", title: "Northcoast Medical Resource Centers",
    cat: "healthcare", sub: "Primary Care",
    desc: "Del Norte County FQHC. Operates clinic sites in Crescent City and rural Del Norte. HRSA Section 330 grantee.",
    website_url: "https://www.northcoastclinics.org/",
    phone: "(707) 464-6126", address: "550 E. Washington Boulevard",
    city: "Crescent City", zip: "95531",
    eligibility: "Low-income Del Norte County residents",
    source_name: "Northcoast Med RC / HRSA FQHC", source_type: "nonprofit",
  },

  // ============== ADDITIONAL SALVATION ARMY CORPS ==============
  {
    section: "SA-BUR", title: "Salvation Army Burbank Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Burbank corps. Family services, food pantry, after-school programs serving Burbank, Glendale, La Crescenta.",
    website_url: "https://burbank.salvationarmy.org/",
    phone: "(818) 845-7214", address: "300 E. Angeleno Avenue",
    city: "Burbank", zip: "91502",
    eligibility: "Adults and families experiencing homelessness in Burbank/Glendale",
    source_name: "Salvation Army Burbank canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-POM", title: "Salvation Army Pomona Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Pomona corps. Operates emergency shelter, food pantry, family services serving Pomona, San Dimas, La Verne.",
    website_url: "https://pomona.salvationarmy.org/",
    phone: "(909) 623-1579", address: "490 E. La Verne Avenue",
    city: "Pomona", zip: "91767",
    eligibility: "Adults and families experiencing homelessness in Pomona Valley",
    source_name: "Salvation Army Pomona canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-EC2", title: "Salvation Army El Cajon Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army El Cajon corps. Operates emergency shelter, food pantry, family services serving East San Diego County.",
    website_url: "https://elcajon.salvationarmy.org/",
    phone: "(619) 440-4683", address: "1011 E. Main Street",
    city: "El Cajon", zip: "92021",
    eligibility: "Adults and families experiencing homelessness in East SD County",
    source_name: "Salvation Army El Cajon canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-ESC", title: "Salvation Army Escondido Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Escondido corps. Operates emergency shelter, food pantry, family services serving North San Diego County.",
    website_url: "https://escondido.salvationarmy.org/",
    phone: "(760) 745-2528", address: "1840 E. Valley Parkway",
    city: "Escondido", zip: "92027",
    eligibility: "Adults and families experiencing homelessness in N. SD County",
    source_name: "Salvation Army Escondido canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-CHU", title: "Salvation Army South Bay (Chula Vista) Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army South Bay/Chula Vista corps. Operates emergency shelter, food pantry, family services serving South SD County.",
    website_url: "https://southbay.salvationarmy.org/",
    phone: "(619) 691-1221", address: "576 K Street",
    city: "Chula Vista", zip: "91911",
    eligibility: "Adults and families experiencing homelessness in South SD County",
    source_name: "Salvation Army South Bay canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-OXN", title: "Salvation Army Oxnard Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Oxnard corps. Operates emergency shelter, food pantry, family services serving Oxnard and West Ventura County.",
    website_url: "https://oxnard.salvationarmy.org/",
    phone: "(805) 486-1881", address: "622 N. Hayes Avenue",
    city: "Oxnard", zip: "93030",
    eligibility: "Adults and families experiencing homelessness in West Ventura County",
    source_name: "Salvation Army Oxnard canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-CHI", title: "Salvation Army Chico Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Chico corps. Operates emergency shelter, food pantry, family services serving Butte County.",
    website_url: "https://chico.salvationarmy.org/",
    phone: "(530) 342-2199", address: "567 E. 16th Street",
    city: "Chico", zip: "95928",
    eligibility: "Adults and families experiencing homelessness in Butte County",
    source_name: "Salvation Army Chico canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-RED", title: "Salvation Army Redding Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Redding corps. Operates emergency shelter, food pantry, family services serving Shasta County.",
    website_url: "https://redding.salvationarmy.org/",
    phone: "(530) 222-2207", address: "2691 Larkspur Lane",
    city: "Redding", zip: "96002",
    eligibility: "Adults and families experiencing homelessness in Shasta County",
    source_name: "Salvation Army Redding canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-VAL", title: "Salvation Army Vallejo Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Vallejo corps. Operates emergency shelter, food pantry, family services serving Vallejo and Solano County.",
    website_url: "https://vallejo.salvationarmy.org/",
    phone: "(707) 552-2914", address: "630 Tuolumne Street",
    city: "Vallejo", zip: "94590",
    eligibility: "Adults and families experiencing homelessness in Solano County",
    source_name: "Salvation Army Vallejo canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-FAI", title: "Salvation Army Fairfield Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Fairfield corps. Operates emergency shelter, food pantry, family services serving Fairfield, Vacaville, Suisun City.",
    website_url: "https://fairfield.salvationarmy.org/",
    phone: "(707) 422-0905", address: "1226 Empire Street",
    city: "Fairfield", zip: "94533",
    eligibility: "Adults and families experiencing homelessness in central Solano County",
    source_name: "Salvation Army Fairfield canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-CON", title: "Salvation Army Concord Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Concord corps. Operates emergency shelter, food pantry, family services serving Central Contra Costa County.",
    website_url: "https://concord.salvationarmy.org/",
    phone: "(925) 676-6180", address: "3950 Clayton Road",
    city: "Concord", zip: "94521",
    eligibility: "Adults and families experiencing homelessness in Central Contra Costa",
    source_name: "Salvation Army Concord canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-WC", title: "Salvation Army Walnut Creek Citadel Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Walnut Creek corps. Operates family services, food pantry serving Central Contra Costa County.",
    website_url: "https://walnutcreek.salvationarmy.org/",
    phone: "(925) 932-3722", address: "3950 Clayton Road",
    city: "Walnut Creek", zip: "94521",
    eligibility: "Adults and families experiencing homelessness in Central Contra Costa",
    source_name: "Salvation Army Walnut Creek canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-HAY", title: "Salvation Army Hayward Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Hayward corps. Operates emergency shelter, food pantry, family services serving Southern Alameda County.",
    website_url: "https://hayward.salvationarmy.org/",
    phone: "(510) 581-6444", address: "430 A Street",
    city: "Hayward", zip: "94541",
    eligibility: "Adults and families experiencing homelessness in S. Alameda County",
    source_name: "Salvation Army Hayward canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-SAL", title: "Salvation Army Salinas Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Salinas corps. Operates emergency shelter, food pantry, family services serving Salinas and Monterey County interior.",
    website_url: "https://salinas.salvationarmy.org/",
    phone: "(831) 443-9655", address: "2460 N. Main Street",
    city: "Salinas", zip: "93906",
    eligibility: "Adults and families experiencing homelessness in Salinas Valley",
    source_name: "Salvation Army Salinas canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-SLO", title: "Salvation Army San Luis Obispo Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army SLO corps. Operates emergency shelter, food pantry, family services serving SLO County.",
    website_url: "https://sanluisobispo.salvationarmy.org/",
    phone: "(805) 544-2401", address: "815 Islay Street",
    city: "San Luis Obispo", zip: "93401",
    eligibility: "Adults and families experiencing homelessness in SLO County",
    source_name: "Salvation Army SLO canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-VIS", title: "Salvation Army Visalia Corps",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salvation Army Visalia corps. Operates emergency shelter, food pantry, family services serving Tulare County.",
    website_url: "https://visalia.salvationarmy.org/",
    phone: "(559) 732-0584", address: "1827 N. Court Street",
    city: "Visalia", zip: "93291",
    eligibility: "Adults and families experiencing homelessness in Tulare County",
    source_name: "Salvation Army Visalia canonical site", source_type: "nonprofit",
  },

  // ============== ADDITIONAL 211 NETWORKS ==============
  {
    section: "211-MAR", title: "211 Bay Area / Eden I&R - Marin Office",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Marin County 211 service operated by Eden I&R. 24/7 free, confidential information and referral.",
    website_url: "https://211bayarea.org/marin/",
    phone: "211", address: "30 N. San Pedro Road, Suite 240",
    city: "San Rafael", zip: "94903",
    eligibility: "Anyone in Marin County",
    source_name: "Eden I&R / 211 Bay Area canonical", source_type: "nonprofit",
  },
  {
    section: "211-NS", title: "211 North State (United Way Northern California)",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Far North CA 211 backbone operated by United Way of Northern California. Serves Shasta, Tehama, Trinity, Modoc, Siskiyou. 24/7 free I&R.",
    website_url: "https://www.uwnortherncalifornia.org/",
    phone: "211", address: "2280 Benton Drive, Building D",
    city: "Redding", zip: "96003",
    eligibility: "Anyone in Far North CA",
    source_name: "United Way Northern CA / 211 canonical", source_type: "nonprofit",
  },
  {
    section: "211-MM", title: "211 Mendocino-Lake (NCO)",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Mendocino and Lake counties 211 backbone operated by North Coast Opportunities (NCO). 24/7 free, confidential information and referral.",
    website_url: "https://www.ncoinc.org/programs-services/211/",
    phone: "211", address: "413 N. State Street",
    city: "Ukiah", zip: "95482",
    eligibility: "Anyone in Mendocino/Lake counties",
    source_name: "NCO 211 canonical site", source_type: "nonprofit",
  },
  {
    section: "211-SOL", title: "211 Solano County",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Solano County 211 backbone, operated by United Way Bay Area. 24/7 free, confidential information and referral serving Vallejo, Fairfield, Vacaville, Benicia.",
    website_url: "https://211solano.org/",
    phone: "211", address: "780 Empire Street",
    city: "Fairfield", zip: "94533",
    eligibility: "Anyone in Solano County",
    source_name: "211 Solano canonical / CA 211 network", source_type: "nonprofit",
  },
  {
    section: "211-SON", title: "211 Sonoma County",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Sonoma County 211 backbone, operated by United Way of the Wine Country. 24/7 free, confidential information and referral including disaster response.",
    website_url: "https://www.211sonoma.org/",
    phone: "211", address: "975 Corporate Center Parkway, Suite 160",
    city: "Santa Rosa", zip: "95407",
    eligibility: "Anyone in Sonoma County",
    source_name: "211 Sonoma canonical / CA 211 network", source_type: "nonprofit",
  },
  {
    section: "211-NV", title: "211 Connecting Point Placer/Nevada/Sutter/Yuba",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Placer/Nevada/Sutter/Yuba/Sierra counties 211 service operated by Connecting Point. 24/7 free, confidential information and referral.",
    website_url: "https://www.connectingpoint.org/",
    phone: "211", address: "P.O. Box 6011",
    city: "Auburn", zip: "95603",
    eligibility: "Anyone in Placer/Nevada/Sutter/Yuba/Sierra",
    source_name: "Connecting Point Placer canonical", source_type: "nonprofit",
  },

  // ============== MERCY HOUSING CALIFORNIA REGIONAL ==============
  {
    section: "MH-LA", title: "Mercy Housing California - Los Angeles Regional Office",
    cat: "housing", sub: "Rental Assistance",
    desc: "Mercy Housing California's LA regional office. Owns/operates 50+ affordable rental properties across LA County for low-income families, seniors, formerly homeless, and special needs populations including veterans.",
    website_url: "https://www.mercyhousing.org/california/",
    phone: "(213) 743-5820", address: "601 W. 5th Street, Suite 800",
    city: "Los Angeles", zip: "90071",
    eligibility: "Low-income LA County renters; veterans prioritized for VASH/SSVF units",
    source_name: "Mercy Housing CA canonical site", source_type: "nonprofit",
  },
  {
    section: "MH-SD", title: "Mercy Housing California - San Diego",
    cat: "housing", sub: "Rental Assistance",
    desc: "Mercy Housing California's SD portfolio. Owns/operates 20+ affordable rental properties across SD County for low-income families, seniors, formerly homeless, and special needs populations.",
    website_url: "https://www.mercyhousing.org/california/",
    phone: "(619) 230-6090", address: "1900 5th Avenue, Suite 240",
    city: "San Diego", zip: "92101",
    eligibility: "Low-income SD County renters",
    source_name: "Mercy Housing CA canonical site", source_type: "nonprofit",
  },
  {
    section: "MH-SAC", title: "Mercy Housing California - Sacramento",
    cat: "housing", sub: "Rental Assistance",
    desc: "Mercy Housing California's Sacramento Valley portfolio. Owns/operates affordable rental properties across Sacramento, Yolo, Placer, Solano counties for low-income families, seniors, formerly homeless, and special needs.",
    website_url: "https://www.mercyhousing.org/california/",
    phone: "(916) 414-4400", address: "900 Howe Avenue, Suite 100",
    city: "Sacramento", zip: "95825",
    eligibility: "Low-income Sacramento Valley renters",
    source_name: "Mercy Housing CA canonical site", source_type: "nonprofit",
  },

  // ============== ADDITIONAL VOLUNTEERS OF AMERICA ==============
  {
    section: "VOA-OC", title: "Volunteers of America Greater Los Angeles - Orange County Programs",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "VOA Greater LA OC programs. Operates SSVF for homeless veterans, transitional housing, and the Veterans First program in OC. Subsidiary of VOA Greater Los Angeles.",
    website_url: "https://www.voala.org/",
    phone: "(714) 542-3554", address: "1900 E. 4th Street, Suite 130",
    city: "Santa Ana", zip: "92705",
    eligibility: "Adults experiencing homelessness in OC; veterans prioritized via SSVF",
    source_name: "VOA Greater LA canonical site", source_type: "nonprofit",
  },

  // ============== AMVETS / VVA / PVA POSTS & CHAPTERS ==============
  {
    section: "VVA-CA", title: "Vietnam Veterans of America - California State Council",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "State-level coordinating body for VVA chapters in California. Coordinates 30+ local chapters statewide. VA-accredited claims service for Vietnam-era veterans and surviving spouses.",
    website_url: "https://www.vvacasc.org/",
    phone: "(916) 921-2188", address: "P.O. Box 215336",
    city: "Sacramento", zip: "95821",
    eligibility: "Vietnam-era veterans (1961-1975) and surviving spouses",
    source_name: "VVA California State Council canonical site", source_type: "nonprofit",
  },
  {
    section: "PVA-CA", title: "California Paralyzed Veterans Association",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "California chapter of Paralyzed Veterans of America. Serves veterans with spinal cord injury or disorders. VA-accredited claims service, advocacy, accessible recreation programs, peer mentoring.",
    website_url: "https://www.calpva.org/",
    phone: "(818) 781-7373", address: "5901 E. 7th Street, Building 150",
    city: "Long Beach", zip: "90822",
    eligibility: "Veterans with spinal cord injury or neurological conditions",
    source_name: "Cal-PVA canonical site", source_type: "nonprofit",
  },
  {
    section: "MCL-CA", title: "Marine Corps League Department of California",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Department-level command of Marine Corps League in California. Coordinates 90+ local detachments statewide for current and former Marines, FMF Navy Corpsmen, and Chaplains.",
    website_url: "https://www.mcldeptca.org/",
    phone: "(916) 729-9925", address: "10470 Old Placerville Road, Suite 100",
    city: "Sacramento", zip: "95827",
    eligibility: "Current and former Marines and qualifying Navy personnel",
    source_name: "MCL Department of California canonical site", source_type: "nonprofit",
  },
  {
    section: "JWV-CA", title: "Jewish War Veterans Department of California",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Department-level command of Jewish War Veterans of the USA in California. Coordinates local posts statewide. VA-accredited claims service, advocacy, social programs.",
    website_url: "https://www.jwv.org/",
    phone: "(310) 553-3066", address: "10300 Wilshire Boulevard",
    city: "Los Angeles", zip: "90024",
    eligibility: "Jewish veterans of the U.S. armed forces",
    source_name: "JWV canonical / Department of California", source_type: "nonprofit",
  },

  // ============== ADDITIONAL HICAP/SHIP REGIONAL OFFICES ==============
  {
    section: "HICAP-N", title: "HICAP of Northern California (Legal Services of Northern California)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "HICAP for Sacramento, Yolo, Placer, El Dorado, Sutter, Yuba, Nevada, Sierra, Plumas, Lassen counties operated by Legal Services of Northern California. Free Medicare counseling and Medi-Cal assistance.",
    website_url: "https://lsnc.net/help/hicap",
    phone: "(916) 376-8915", address: "517 12th Street",
    city: "Sacramento", zip: "95814",
    eligibility: "Medicare beneficiaries in Northern California",
    source_name: "LSNC HICAP canonical / CDA HICAP", source_type: "nonprofit",
  },
  {
    section: "HICAP-CV", title: "HICAP Central Valley (Valley Caregiver Resource Center)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "HICAP for Fresno, Madera, Kings, Tulare, Mariposa counties operated by Valley Caregiver Resource Center. Free Medicare counseling, Medi-Cal, and Medicare Savings Programs assistance.",
    website_url: "https://www.valleycrc.org/",
    phone: "(559) 224-9154", address: "3845 N. Clark Street, Suite 201",
    city: "Fresno", zip: "93726",
    eligibility: "Medicare beneficiaries in Central Valley",
    source_name: "Valley CRC HICAP canonical / CDA HICAP", source_type: "nonprofit",
  },
  {
    section: "HICAP-MB", title: "HICAP Central Coast (Alliance on Aging - Monterey)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "HICAP for Monterey, San Benito, Santa Cruz counties operated by Alliance on Aging. Free Medicare counseling, Medi-Cal, and Medicare Savings Programs assistance.",
    website_url: "https://allianceonaging.org/",
    phone: "(831) 655-1334", address: "247 Main Street",
    city: "Salinas", zip: "93901",
    eligibility: "Medicare beneficiaries in Central Coast",
    source_name: "Alliance on Aging HICAP canonical / CDA HICAP", source_type: "nonprofit",
  },
  {
    section: "HICAP-SBA", title: "HICAP Tri-Counties (Central Coast Commission for Senior Citizens)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "HICAP for San Luis Obispo, Santa Barbara, Ventura counties operated by Central Coast Commission for Senior Citizens. Free Medicare counseling, Medi-Cal, and Medicare Savings Programs.",
    website_url: "https://www.centralcoastseniors.org/",
    phone: "(800) 434-0222", address: "528 S. Broadway",
    city: "Santa Maria", zip: "93454",
    eligibility: "Medicare beneficiaries in Central Coast tri-counties",
    source_name: "CCCSC HICAP canonical / CDA HICAP", source_type: "nonprofit",
  },

  // ============== COUNTY VETERAN SERVICE OFFICES — MISSING SMALL COUNTIES ==============
  {
    section: "CVSO-INY", title: "Inyo / Mono / Alpine Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Eastern Sierra County Veterans Service Office serving Inyo, Mono, and Alpine counties. CA Department of Veterans Affairs (CalVet) accredited County Veteran Service Officer for VA benefits, claims, appeals.",
    website_url: "https://inyocounty.us/services/health-and-human-services/veterans-services",
    phone: "(760) 873-7850", address: "207 W. South Street",
    city: "Bishop", zip: "93514",
    eligibility: "Veterans residing in Inyo/Mono/Alpine counties",
    source_name: "Inyo County HHS canonical / CalVet CVSO network", source_type: "government_agency",
  },
  {
    section: "CVSO-MAR", title: "Mariposa County Veterans Service Office",
    cat: "va-benefits", sub: "VA Disability Compensation",
    desc: "Mariposa County Veterans Service Office. CalVet-accredited County Veteran Service Officer for VA benefits, claims, appeals.",
    website_url: "https://www.mariposacounty.org/378/Veterans-Services",
    phone: "(209) 966-2000", address: "5099 Old Highway North",
    city: "Mariposa", zip: "95338",
    eligibility: "Veterans residing in Mariposa County",
    source_name: "Mariposa County canonical / CalVet CVSO network", source_type: "government_agency",
  },
  {
    section: "CVSO-MOD", title: "Modoc County Veterans Service Office",
    cat: "va-benefits", sub: "VA Disability Compensation",
    desc: "Modoc County Veterans Service Office. CalVet-accredited County Veteran Service Officer for VA benefits, claims, appeals.",
    website_url: "https://www.co.modoc.ca.us/departments/veterans-services",
    phone: "(530) 233-6203", address: "201 W. 4th Street",
    city: "Alturas", zip: "96101",
    eligibility: "Veterans residing in Modoc County",
    source_name: "Modoc County canonical / CalVet CVSO network", source_type: "government_agency",
  },

  // ============== ADDITIONAL CATHOLIC CHARITIES BRANCH OFFICES ==============
  {
    section: "CC-LA2", title: "Catholic Charities of Los Angeles - Esperanza Immigrant Rights Project",
    cat: "legal", sub: "Immigration Legal Services",
    desc: "Esperanza Immigrant Rights Project of Catholic Charities of LA. Free immigration legal services for low-income immigrants in LA County. DOJ-accredited.",
    website_url: "https://www.catholiccharitiesla.org/get-help/immigrant-services/",
    phone: "(213) 251-3505", address: "1530 James M. Wood Boulevard",
    city: "Los Angeles", zip: "90015",
    eligibility: "Low-income immigrants in LA County",
    source_name: "Catholic Charities LA / Esperanza canonical", source_type: "nonprofit",
  },
  {
    section: "CC-SF2", title: "Catholic Charities CYO - Refugee Resettlement San Francisco",
    cat: "legal", sub: "Immigration Legal Services",
    desc: "Catholic Charities of San Francisco refugee and immigrant services. Resettlement of refugees, asylum seekers; DOJ-accredited immigration legal services serving SF, Marin, and San Mateo.",
    website_url: "https://www.catholiccharitiessf.org/programs/refugee-services/",
    phone: "(415) 972-1200", address: "990 Eddy Street",
    city: "San Francisco", zip: "94109",
    eligibility: "Refugees and immigrants in SF/Marin/SM",
    source_name: "Catholic Charities CYO canonical site", source_type: "nonprofit",
  },
  {
    section: "CC-SD2", title: "Catholic Charities Diocese of San Diego - Immigration Services",
    cat: "legal", sub: "Immigration Legal Services",
    desc: "Catholic Charities Diocese of San Diego immigration legal services. DOJ-accredited representation for low-income immigrants in SD and Imperial counties.",
    website_url: "https://www.ccdsd.org/immigration-services/",
    phone: "(619) 287-9454", address: "4575 Mission Gorge Place",
    city: "San Diego", zip: "92120",
    eligibility: "Low-income immigrants in SD/IM",
    source_name: "Catholic Charities SD canonical site", source_type: "nonprofit",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B6 — Final Push to 1,000 Floor", state: "CA" });
