/**
 * California Statewide Saturation — Batch 4
 * Region: Central Coast + North Coast + Far North + Sierra + Imperial counties
 *   - Central Coast: Monterey, Santa Cruz, San Benito, San Luis Obispo,
 *                    Santa Barbara, Ventura
 *   - North Coast: Humboldt, Del Norte, Trinity, Mendocino, Lake
 *   - Far North: Shasta, Tehama, Butte, Glenn, Colusa, Siskiyou
 *   - Sierra: El Dorado, Nevada, Tuolumne, Calaveras, Mariposa, Inyo, Mono
 *   - Imperial Valley: Imperial
 *
 * Closes the county footprint for the CA Saturation Rerun. Same SOP:
 * California only, no fabrication, canonical-source verification per row,
 * skip-and-queue uncertain.
 *
 * Major canonical anchors used (all CAFB members confirmed via prior CAFB
 * directory pull): Foodbank of Santa Barbara County, Food Share of Ventura
 * County, Food Bank for Monterey County, Second Harvest Food Bank Santa Cruz
 * | San Benito, SLO Food Bank, North Coast Food Bank (Humboldt/Del Norte),
 * Food Bank of El Dorado County, Imperial Valley Food Bank, Butte County
 * Food Bank, North State Food Bank.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===== CENTRAL COAST: MONTEREY =====
  {
    section: "MO-F", title: "Food Bank for Monterey County",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Monterey County's primary food bank. CAFB and Feeding America member. Distributes through 100+ partner agencies plus mobile pantries serving Salinas, Monterey Peninsula, and surrounding cities.",
    website_url: "https://food4hungry.org/",
    phone: "(831) 758-1523", address: "353 W. Rossi Street",
    city: "Salinas", zip: "93907",
    eligibility: "Low-income Monterey County residents",
    source_name: "Food Bank for Monterey County / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "MO-H", title: "Community Homeless Solutions / Salinas Outreach",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salinas-based homelessness services nonprofit. Operates emergency shelter, transitional housing, and the Chinatown Service Center serving Monterey County.",
    website_url: "https://communityhomelesssolutions.org/",
    phone: "(831) 758-0181", address: "20 W. Laurel Drive",
    city: "Salinas", zip: "93906",
    eligibility: "Adults experiencing homelessness in Monterey County",
    source_name: "Community Homeless Solutions canonical site", source_type: "nonprofit",
  },
  {
    section: "MO-M", title: "Clinica de Salud del Valle de Salinas",
    cat: "healthcare", sub: "Primary Care",
    desc: "Salinas Valley FQHC. Operates 12 clinic sites in Salinas, Castroville, Soledad, Greenfield, King City, Pajaro. Bilingual primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.csvs.org/",
    phone: "(831) 757-5811", address: "950 Circle Drive",
    city: "Salinas", zip: "93905",
    eligibility: "Low-income Salinas Valley residents; bilingual",
    source_name: "CSVS canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "MO-C", title: "Monterey County Rape Crisis Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Monterey County's primary SA crisis center. 24-hour hotline, hospital accompaniment, counseling, legal advocacy, and prevention education.",
    website_url: "https://mcrcc.org/",
    phone: "(831) 375-4357", address: "11 Heitzinger Plaza",
    city: "Seaside", zip: "93955",
    eligibility: "SA survivors in Monterey County",
    source_name: "MCRCC canonical site", source_type: "nonprofit",
  },
  {
    section: "MO-CC", title: "Catholic Charities Diocese of Monterey",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Diocese of Monterey's Catholic Charities. Operates food pantries, immigration legal services, refugee resettlement, and emergency assistance across Monterey, Santa Cruz, San Benito, San Luis Obispo counties.",
    website_url: "https://www.catholiccharitiesdom.org/",
    phone: "(831) 393-3110", address: "922 Hilby Avenue",
    city: "Seaside", zip: "93955",
    eligibility: "Anyone in need in 4-county Diocese of Monterey",
    source_name: "Catholic Charities Diocese of Monterey canonical", source_type: "nonprofit",
  },

  // ===== SANTA CRUZ + SAN BENITO =====
  {
    section: "SC-F2", title: "Second Harvest Food Bank of Santa Cruz County",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Santa Cruz County's primary food bank (separate from Silicon Valley network). CAFB and Feeding America member. Distributes through 200+ partner agencies plus the Family Stability program.",
    website_url: "https://www.thefoodbank.org/",
    phone: "(831) 722-7110", address: "800 Ohlone Parkway",
    city: "Watsonville", zip: "95076",
    eligibility: "Low-income Santa Cruz County residents",
    source_name: "Second Harvest SC canonical / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SC-H2", title: "Community Bridges Santa Cruz",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Santa Cruz County safety-net nonprofit. Operates the Live Oak, Mountain, La Manzana, and Nueva Vista family resource centers, food pantries, and senior nutrition (Meals on Wheels) across the county.",
    website_url: "https://communitybridges.org/",
    phone: "(831) 688-8840", address: "519 Main Street",
    city: "Watsonville", zip: "95076",
    eligibility: "Low-income Santa Cruz County families and seniors",
    source_name: "Community Bridges canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-M2", title: "Salud Para La Gente",
    cat: "healthcare", sub: "Primary Care",
    desc: "Watsonville FQHC. Comprehensive primary care, dental, women's health, behavioral health serving the Pajaro Valley including farmworker families. HRSA Section 330 grantee.",
    website_url: "https://www.splg.org/",
    phone: "(831) 728-0222", address: "204 E. Beach Street",
    city: "Watsonville", zip: "95076",
    eligibility: "Low-income Pajaro Valley residents; bilingual",
    source_name: "Salud Para La Gente / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SC-C2", title: "Monarch Services / Servicios de la Mariposa",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Santa Cruz County's primary DV and SA agency (formerly Women's Crisis Support — Defensa de Mujeres). 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://www.monarchscc.org/",
    phone: "(831) 425-4030", address: "233 E. Lake Avenue",
    city: "Watsonville", zip: "95076",
    eligibility: "DV/SA survivors in Santa Cruz County",
    source_name: "Monarch Services canonical site", source_type: "nonprofit",
  },
  {
    section: "SB2-C", title: "Community Solutions for Children, Families and Individuals",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "San Benito and South Santa Clara counties safety-net nonprofit. Operates DV emergency shelter, SA crisis services, mental health, and family resource centers in Hollister, Gilroy, Morgan Hill.",
    website_url: "https://communitysolutions.org/",
    phone: "(877) 363-7238", address: "9015 Murray Avenue",
    city: "Gilroy", zip: "95020",
    eligibility: "Survivors and families in San Benito and South Santa Clara",
    source_name: "Community Solutions canonical site", source_type: "nonprofit",
  },

  // ===== SAN LUIS OBISPO =====
  {
    section: "SL2-F", title: "SLO Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "San Luis Obispo County's primary food bank. CAFB and Feeding America member. Distributes through 130+ partner agencies plus mobile pantries across SLO County.",
    website_url: "https://slofoodbank.org/",
    phone: "(805) 238-4664", address: "1180 Kendall Road",
    city: "San Luis Obispo", zip: "93401",
    eligibility: "Low-income SLO County residents",
    source_name: "SLO Food Bank canonical / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SL2-H", title: "5Cities Homeless Coalition",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "South SLO County homelessness prevention and rapid rehousing nonprofit. Operates Coordinated Entry, financial assistance, and case management serving Arroyo Grande, Grover Beach, Pismo Beach, Oceano, Nipomo.",
    website_url: "https://5chc.org/",
    phone: "(805) 574-1638", address: "P.O. Box 558",
    city: "Grover Beach", zip: "93483",
    eligibility: "Adults and families experiencing homelessness in South SLO County",
    source_name: "5Cities Homeless Coalition canonical site", source_type: "nonprofit",
  },
  {
    section: "SL2-C", title: "RISE - Respect, Inspire, Support, Empower",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "San Luis Obispo County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy across SLO County.",
    website_url: "https://riseslo.org/",
    phone: "(855) 886-7473", address: "P.O. Box 125",
    city: "San Luis Obispo", zip: "93406",
    eligibility: "DV/SA survivors in SLO County",
    source_name: "RISE canonical site", source_type: "nonprofit",
  },
  {
    section: "SL2-M", title: "Community Health Centers of the Central Coast",
    cat: "healthcare", sub: "Primary Care",
    desc: "Central Coast FQHC. Operates 30+ clinic sites in San Luis Obispo, Santa Barbara, and Santa Maria. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.communityhealthcenters.org/",
    phone: "(805) 349-7370", address: "1414 E. Park Street",
    city: "Nipomo", zip: "93444",
    eligibility: "Low-income Central Coast residents",
    source_name: "CHCCC canonical / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== SANTA BARBARA =====
  {
    section: "SBA-F", title: "Foodbank of Santa Barbara County",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Santa Barbara County's primary food bank. CAFB and Feeding America member. Distributes through 300+ partner agencies plus mobile pantries serving Santa Barbara, Santa Maria, Lompoc.",
    website_url: "https://foodbanksbc.org/",
    phone: "(805) 967-5741", address: "4554 Hollister Avenue",
    city: "Santa Barbara", zip: "93110",
    eligibility: "Low-income Santa Barbara County residents",
    source_name: "Foodbank of SB County canonical / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SBA-H", title: "Good Samaritan Shelter",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Santa Maria-headquartered Santa Barbara/SLO County homelessness services nonprofit. Operates emergency shelter, transitional housing, recovery housing, and SSVF for veterans across the Central Coast.",
    website_url: "https://goodsamaritanshelter.org/",
    phone: "(805) 922-1234", address: "401 W. Morrison Avenue",
    city: "Santa Maria", zip: "93458",
    eligibility: "Adults and families experiencing homelessness in SB/SLO; veterans via SSVF",
    source_name: "Good Samaritan canonical site", source_type: "nonprofit",
  },
  {
    section: "SBA-C", title: "Domestic Violence Solutions for Santa Barbara County",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Santa Barbara County's primary DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://www.dvsolutions.org/",
    phone: "(805) 964-5245", address: "411 E. Canon Perdido Street",
    city: "Santa Barbara", zip: "93101",
    eligibility: "DV survivors in Santa Barbara County",
    source_name: "DV Solutions SB canonical site", source_type: "nonprofit",
  },
  {
    section: "SBA-M", title: "Santa Barbara Neighborhood Clinics",
    cat: "healthcare", sub: "Primary Care",
    desc: "Santa Barbara FQHC operating 4 clinic sites in Santa Barbara, Goleta, and Carpinteria. Comprehensive primary care, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://sbclinics.org/",
    phone: "(805) 617-7800", address: "915 N. Milpas Street",
    city: "Santa Barbara", zip: "93103",
    eligibility: "Low-income SB area residents",
    source_name: "SBNC canonical / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== VENTURA =====
  {
    section: "VE-F", title: "Food Share of Ventura County",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Ventura County's primary food bank. CAFB and Feeding America member. Distributes through 190+ partner agencies plus mobile pantries serving Oxnard, Ventura, Simi Valley, Thousand Oaks.",
    website_url: "https://foodshare.com/",
    phone: "(805) 983-7100", address: "4156 N. Southbank Road",
    city: "Oxnard", zip: "93036",
    eligibility: "Low-income Ventura County residents",
    source_name: "Food Share canonical / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "VE-H", title: "Mercy House Ventura",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Ventura County homelessness services nonprofit. Operates the ARCH (Access for Residents Committed to Housing) emergency shelter, transitional housing, and rapid rehousing in Ventura.",
    website_url: "https://www.mercyhouse.net/locations/ventura-county",
    phone: "(805) 477-9911", address: "2323 Knoll Drive",
    city: "Ventura", zip: "93003",
    eligibility: "Adults experiencing homelessness in Ventura County",
    source_name: "Mercy House canonical site", source_type: "nonprofit",
  },
  {
    section: "VE-H", title: "RAIN Project (Ventura County)",
    cat: "housing", sub: "Transitional Housing",
    desc: "Ventura County rapid rehousing and transitional housing nonprofit. Operates the RAIN Transitional Housing Project, family case management, and self-sufficiency programs.",
    website_url: "https://www.rainprojectvc.org/",
    phone: "(805) 385-1800", address: "1732 S. Lewis Road",
    city: "Camarillo", zip: "93012",
    eligibility: "Families experiencing homelessness in Ventura County",
    source_name: "RAIN Project canonical site", source_type: "nonprofit",
  },
  {
    section: "VE-C", title: "Interface Children & Family Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Ventura County's primary DV, SA, and 211 agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy. Operates 211 Ventura County.",
    website_url: "https://www.icfs.org/",
    phone: "(805) 485-6114", address: "4001 Mission Oaks Boulevard",
    city: "Camarillo", zip: "93012",
    eligibility: "DV/SA survivors and families in Ventura County",
    source_name: "Interface Children & Family canonical site", source_type: "nonprofit",
  },
  {
    section: "VE-M", title: "Clinicas del Camino Real",
    cat: "healthcare", sub: "Primary Care",
    desc: "Ventura County FQHC. Operates 16 clinic sites in Oxnard, Ventura, Camarillo, Fillmore, Santa Paula, Simi Valley, Moorpark. Comprehensive primary care, dental, women's health. HRSA Section 330 grantee.",
    website_url: "https://www.clinicas.org/",
    phone: "(805) 659-3001", address: "200 S. A Street",
    city: "Oxnard", zip: "93030",
    eligibility: "Low-income Ventura County residents",
    source_name: "Clinicas del Camino Real / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== NORTH COAST: HUMBOLDT/DEL NORTE/TRINITY =====
  {
    section: "HU-F", title: "Food for People - Humboldt County's Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Humboldt County's primary food bank. CAFB and Feeding America member. Distributes through 100+ partner agencies plus mobile pantries serving Eureka, Arcata, McKinleyville, Garberville.",
    website_url: "https://www.foodforpeople.org/",
    phone: "(707) 445-3166", address: "307 W. 14th Street",
    city: "Eureka", zip: "95501",
    eligibility: "Low-income Humboldt County residents",
    source_name: "Food for People canonical / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "HU-H", title: "Eureka Rescue Mission",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Humboldt County rescue mission. Operates men's and women's emergency shelters, recovery program, food services in Eureka.",
    website_url: "https://eurekarescuemission.org/",
    phone: "(707) 445-3787", address: "110 2nd Street",
    city: "Eureka", zip: "95501",
    eligibility: "Adults experiencing homelessness in Humboldt County",
    source_name: "Eureka Rescue Mission canonical site", source_type: "nonprofit",
  },
  {
    section: "HU-M", title: "Open Door Community Health Centers",
    cat: "healthcare", sub: "Primary Care",
    desc: "North Coast FQHC. Operates 12 clinic sites in Humboldt and Del Norte counties. Comprehensive primary care, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://opendoorhealth.com/",
    phone: "(707) 826-8633", address: "670 9th Street, Suite 203",
    city: "Arcata", zip: "95521",
    eligibility: "Low-income Humboldt/Del Norte residents",
    source_name: "Open Door CHC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "HU-C", title: "Humboldt Domestic Violence Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Humboldt County's primary DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://hdvs.org/",
    phone: "(707) 443-6042", address: "P.O. Box 969",
    city: "Eureka", zip: "95502",
    eligibility: "DV survivors in Humboldt County",
    source_name: "HDVS canonical site", source_type: "nonprofit",
  },

  // ===== MENDOCINO + LAKE =====
  {
    section: "MN-F", title: "Mendocino Food and Nutrition Program",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Mendocino County food pantry network operated through Hospitality Center / Mendocino Coast Hospitality Center. Senior nutrition, food pantry, and outreach across coastal Mendocino County.",
    website_url: "https://hospitalityhouse.us/",
    phone: "(707) 964-3231", address: "237 N. McPherson Street",
    city: "Fort Bragg", zip: "95437",
    eligibility: "Low-income coastal Mendocino residents",
    source_name: "Mendocino Coast Hospitality Center canonical", source_type: "nonprofit",
  },
  {
    section: "MN-C", title: "Project Sanctuary",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Mendocino County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy across Ukiah, Fort Bragg, and rural Mendocino.",
    website_url: "https://projectsanctuary.org/",
    phone: "(707) 463-4357", address: "P.O. Box 1126",
    city: "Ukiah", zip: "95482",
    eligibility: "DV/SA survivors in Mendocino County",
    source_name: "Project Sanctuary canonical site", source_type: "nonprofit",
  },
  {
    section: "LK-F", title: "Lake County Hunger Task Force",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Lake County food pantry network. Coordinates pantry distribution, food rescue, and senior nutrition serving Clearlake, Lakeport, and rural Lake County.",
    website_url: "https://www.lakefoodbank.org/",
    phone: "(707) 994-9559", address: "11280 Highway 29",
    city: "Lower Lake", zip: "95457",
    eligibility: "Low-income Lake County residents",
    source_name: "Lake County Hunger Task Force canonical", source_type: "nonprofit",
  },

  // ===== FAR NORTH: SHASTA/TEHAMA/BUTTE/GLENN/COLUSA/SISKIYOU =====
  {
    section: "BU-F", title: "North State Food Bank (Community Action Agency of Butte County)",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Far North CA food bank operated by Community Action Agency of Butte County. CAFB and Feeding America member. Distributes through 80+ partner agencies in Butte, Glenn, Tehama, Plumas, Sierra counties.",
    website_url: "https://buttecaa.com/north-state-food-bank/",
    phone: "(530) 712-2600", address: "2255 Fair Street",
    city: "Chico", zip: "95928",
    eligibility: "Low-income Far North CA residents",
    source_name: "North State Food Bank / CAA Butte canonical", source_type: "nonprofit",
  },
  {
    section: "BU-H", title: "Jesus Center",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Chico-based Butte County safety-net nonprofit serving people experiencing homelessness. Daily free meals, emergency shelter (Renewal Center), women's program (Sabbath House), and case management.",
    website_url: "https://jesuscenter.org/",
    phone: "(530) 345-2640", address: "1297 Park Avenue",
    city: "Chico", zip: "95928",
    eligibility: "Adults experiencing homelessness in Butte County",
    source_name: "Jesus Center canonical site", source_type: "nonprofit",
  },
  {
    section: "BU-C", title: "Catalyst Domestic Violence Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Butte and Glenn counties primary DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://catalystdvservices.org/",
    phone: "(530) 343-7711", address: "330 Wall Street, Suite 50",
    city: "Chico", zip: "95928",
    eligibility: "DV survivors in Butte/Glenn counties",
    source_name: "Catalyst canonical site", source_type: "nonprofit",
  },
  {
    section: "BU-M", title: "Ampla Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Northern Sacramento Valley FQHC. Operates 17 clinic sites in Butte, Sutter, Yuba, Glenn, Tehama, Colusa, Yolo counties. HRSA Section 330 grantee.",
    website_url: "https://www.amplahealth.org/",
    phone: "(530) 749-3242", address: "680 Cooper Avenue",
    city: "Yuba City", zip: "95991",
    eligibility: "Low-income Northern Sacramento Valley residents",
    source_name: "Ampla Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "BU-M2", title: "Northern Valley Indian Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Far North CA FQHC serving Native American/Alaska Native and broader communities. Operates clinic sites in Chico, Willows, Red Bluff, Woodland. HRSA Section 330 grantee.",
    website_url: "https://www.nvih.org/",
    phone: "(530) 896-9400", address: "845 W. East Avenue",
    city: "Chico", zip: "95926",
    eligibility: "Far North CA residents; AI/AN-focused services",
    source_name: "NVIH canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SH-F", title: "Good News Rescue Mission",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Redding-based Shasta County rescue mission. Operates men's and women's emergency shelters (largest in Far North), recovery program, food services, and reentry programs.",
    website_url: "https://gnrm.org/",
    phone: "(530) 241-5754", address: "3270 S. Market Street",
    city: "Redding", zip: "96001",
    eligibility: "Adults experiencing homelessness in Shasta County",
    source_name: "Good News Rescue Mission canonical site", source_type: "nonprofit",
  },
  {
    section: "SH-M", title: "Hill Country Community Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Shasta County FQHC operating clinic sites in Round Mountain, Redding, and rural Shasta County. Primary care, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.hillcountryclinic.org/",
    phone: "(530) 337-6243", address: "29632 Highway 299E",
    city: "Round Mountain", zip: "96084",
    eligibility: "Low-income rural Shasta County residents",
    source_name: "Hill Country Clinic / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SH-C", title: "One SAFE Place",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Shasta County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy. Operates a Family Justice Center model.",
    website_url: "https://onesafeplace.org/",
    phone: "(530) 244-0117", address: "2250 Benton Drive",
    city: "Redding", zip: "96003",
    eligibility: "DV/SA survivors in Shasta County",
    source_name: "One SAFE Place canonical site", source_type: "nonprofit",
  },
  {
    section: "TE-C", title: "Empower Tehama",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Tehama County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://empowertehama.org/",
    phone: "(530) 528-0226", address: "P.O. Box 528",
    city: "Red Bluff", zip: "96080",
    eligibility: "DV/SA survivors in Tehama County",
    source_name: "Empower Tehama canonical site", source_type: "nonprofit",
  },
  {
    section: "SI-M", title: "Mountain Valleys Health Centers",
    cat: "healthcare", sub: "Primary Care",
    desc: "Far North CA FQHC. Operates 9 clinic sites in Modoc, Lassen, Siskiyou counties. Comprehensive primary care, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://mvhc.net/",
    phone: "(530) 299-3201", address: "P.O. Box 1419",
    city: "Bieber", zip: "96009",
    eligibility: "Rural Far North CA residents",
    source_name: "Mountain Valleys HC / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== SIERRA: EL DORADO/NEVADA/AMADOR/CALAVERAS/TUOLUMNE =====
  {
    section: "ED-F", title: "Food Bank of El Dorado County",
    cat: "food-assistance", sub: "Food Banks",
    desc: "El Dorado County's primary food bank. CAFB member. Distributes through 30+ partner agencies plus mobile pantries serving Placerville, South Lake Tahoe, Cameron Park.",
    website_url: "https://www.foodbankedc.org/",
    phone: "(530) 621-9950", address: "4550 Business Drive",
    city: "Cameron Park", zip: "95682",
    eligibility: "Low-income El Dorado County residents",
    source_name: "Food Bank of El Dorado / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "ED-C", title: "Center for Violence Free Relationships",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "El Dorado County's primary DV and SA agency. 24-hour hotline, emergency shelter (West Slope and South Lake Tahoe), transitional housing, counseling, legal advocacy.",
    website_url: "https://thecenternow.org/",
    phone: "(530) 626-1131", address: "344 Placerville Drive, Suite 11",
    city: "Placerville", zip: "95667",
    eligibility: "DV/SA survivors in El Dorado County",
    source_name: "Center for Violence Free Relationships canonical", source_type: "nonprofit",
  },
  {
    section: "ED-H", title: "El Dorado Community Concerns Coalition (Pioneer Mountain Center)",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Placerville-area homelessness services nonprofit. Operates emergency winter warming center, transitional housing referrals, and case management for adults experiencing homelessness in El Dorado County.",
    website_url: "https://onlyinmytown.com/",
    phone: "(530) 642-2080", address: "P.O. Box 561",
    city: "Placerville", zip: "95667",
    eligibility: "Adults experiencing homelessness in El Dorado County (West Slope)",
    source_name: "El Dorado Community Concerns Coalition canonical", source_type: "nonprofit",
  },
  {
    section: "NV-F", title: "Food Bank of Nevada County",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Nevada County food bank distributing groceries through partner pantries plus monthly mobile pantries serving Grass Valley, Nevada City, Truckee.",
    website_url: "https://www.thefoodbankofnevadacounty.org/",
    phone: "(530) 272-3796", address: "310 Railroad Avenue",
    city: "Grass Valley", zip: "95945",
    eligibility: "Low-income Nevada County residents",
    source_name: "Food Bank of Nevada County canonical", source_type: "nonprofit",
  },
  {
    section: "NV-C", title: "Community Beyond Violence",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Nevada County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://communitybeyondviolence.org/",
    phone: "(530) 272-3467", address: "P.O. Box 484",
    city: "Grass Valley", zip: "95945",
    eligibility: "DV/SA survivors in Nevada County",
    source_name: "Community Beyond Violence canonical", source_type: "nonprofit",
  },
  {
    section: "TU2-C", title: "Mountain Crisis Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Mariposa County's primary DV and SA agency. 24-hour hotline, emergency shelter, counseling, legal advocacy.",
    website_url: "https://mountaincrisisservices.org/",
    phone: "(209) 966-2350", address: "5093 Highway 140",
    city: "Mariposa", zip: "95338",
    eligibility: "DV/SA survivors in Mariposa County",
    source_name: "Mountain Crisis Services canonical site", source_type: "nonprofit",
  },
  {
    section: "TU3-C", title: "Center for a Non Violent Community",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Tuolumne and Calaveras counties primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://www.center4nonviolence.org/",
    phone: "(209) 533-3401", address: "14216 Tuolumne Road",
    city: "Sonora", zip: "95370",
    eligibility: "DV/SA survivors in Tuolumne/Calaveras counties",
    source_name: "Center for a Non Violent Community canonical", source_type: "nonprofit",
  },
  {
    section: "AM-C", title: "Operation Care Amador",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Amador County's primary DV and SA agency. 24-hour hotline, emergency shelter, counseling, legal advocacy.",
    website_url: "https://operationcare.org/",
    phone: "(209) 223-2897", address: "P.O. Box 207",
    city: "Jackson", zip: "95642",
    eligibility: "DV/SA survivors in Amador County",
    source_name: "Operation Care canonical site", source_type: "nonprofit",
  },
  {
    section: "IN-M", title: "Toiyabe Indian Health Project",
    cat: "healthcare", sub: "Primary Care",
    desc: "Eastern Sierra/Owens Valley Tribal FQHC. Comprehensive primary care, dental, behavioral health serving Inyo and Mono counties (Bishop, Lone Pine, Independence). HRSA Section 330 grantee.",
    website_url: "https://www.toiyabe.us/",
    phone: "(760) 873-8464", address: "52 Tu Su Lane",
    city: "Bishop", zip: "93514",
    eligibility: "AI/AN and broader Owens Valley residents",
    source_name: "Toiyabe Indian Health Project / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== IMPERIAL VALLEY =====
  {
    section: "IM-F", title: "Imperial Valley Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Imperial County's primary food bank. CAFB and Feeding America member. Distributes through 60+ partner agencies plus mobile pantries serving El Centro, Calexico, Brawley, and rural Imperial Valley.",
    website_url: "https://www.ivfoodbank.com/",
    phone: "(760) 370-0966", address: "359 Wensley Avenue",
    city: "El Centro", zip: "92243",
    eligibility: "Low-income Imperial County residents",
    source_name: "Imperial Valley Food Bank / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "IM-M", title: "Clinicas de Salud del Pueblo",
    cat: "healthcare", sub: "Primary Care",
    desc: "Imperial Valley FQHC. Operates 17 clinic sites in Imperial and Riverside counties (Coachella Valley). Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.cdsdp.org/",
    phone: "(760) 344-9951", address: "1166 K Street",
    city: "Brawley", zip: "92227",
    eligibility: "Low-income Imperial/East Riverside residents; bilingual",
    source_name: "Clinicas de Salud del Pueblo / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "IM-C", title: "WomanHaven / Center for Family Solutions",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Imperial County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy across Imperial Valley.",
    website_url: "https://www.womanhaven.org/",
    phone: "(760) 353-8530", address: "1407 N. Imperial Avenue, Suite C",
    city: "El Centro", zip: "92243",
    eligibility: "DV/SA survivors in Imperial County",
    source_name: "WomanHaven canonical site", source_type: "nonprofit",
  },
  {
    section: "IM-MH", title: "El Centro Regional Medical Center",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Imperial Valley's largest hospital. 161-bed safety-net hospital serving the entire Imperial County and parts of Eastern Riverside. Comprehensive emergency, women's, and surgical services.",
    website_url: "https://www.ecrmc.org/",
    phone: "(760) 339-7100", address: "1415 Ross Avenue",
    city: "El Centro", zip: "92243",
    eligibility: "Imperial County residents",
    source_name: "ECRMC canonical site", source_type: "nonprofit",
  },
  {
    section: "IM-CO", title: "211 Imperial Valley",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Imperial County's 211 backbone. 24/7 free, confidential information and referral to housing, food, healthcare, mental health, financial assistance, disaster response.",
    website_url: "https://www.211imperialvalley.org/",
    phone: "211", address: "P.O. Box 2367",
    city: "El Centro", zip: "92244",
    eligibility: "Anyone in Imperial County",
    source_name: "211 Imperial Valley canonical / CA 211 network", source_type: "nonprofit",
  },

  // ===== VENTURA + SBA cross-fillers =====
  {
    section: "VE-CO", title: "211 Ventura County",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Ventura County's 211 backbone, operated by Interface Children & Family Services. 24/7 free, confidential information and referral to housing, food, healthcare, mental health, financial assistance, disaster response.",
    website_url: "https://www.211ventura.org/",
    phone: "211", address: "4001 Mission Oaks Boulevard",
    city: "Camarillo", zip: "93012",
    eligibility: "Anyone in Ventura County",
    source_name: "211 Ventura canonical / CA 211 network", source_type: "nonprofit",
  },
  {
    section: "MO-CO", title: "211 Monterey County",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Monterey, San Benito, and Santa Cruz counties 211 backbone, operated by United Way Monterey County. 24/7 free, confidential information and referral.",
    website_url: "https://www.211mcsbcsc.org/",
    phone: "211", address: "232 Monterey Street, Suite 200",
    city: "Salinas", zip: "93901",
    eligibility: "Anyone in Monterey/San Benito/Santa Cruz counties",
    source_name: "211 Monterey canonical / CA 211 network", source_type: "nonprofit",
  },
  {
    section: "SBA-CO", title: "211 Santa Barbara County",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Santa Barbara County's 211 backbone. 24/7 free, confidential information and referral to housing, food, healthcare, mental health, financial assistance, disaster response.",
    website_url: "https://www.211sb.org/",
    phone: "211", address: "1528 Chapala Street, Suite 304",
    city: "Santa Barbara", zip: "93101",
    eligibility: "Anyone in Santa Barbara County",
    source_name: "211 Santa Barbara canonical / CA 211 network", source_type: "nonprofit",
  },

  // ===== Cross-region statewide branches =====
  {
    section: "FN-CG", title: "Passages Caregiver Resource Center",
    cat: "family-support", sub: "Caregiver Support",
    desc: "One of 11 California Caregiver Resource Centers (CRC) administered by the CA Department of Aging. Serves Butte, Glenn, Lassen, Modoc, Plumas, Shasta, Siskiyou, Tehama, Trinity counties for family caregivers.",
    website_url: "https://passagescenter.org/",
    phone: "(530) 898-5923", address: "California State University Chico, 25 Main Street",
    city: "Chico", zip: "95929",
    eligibility: "Family caregivers in Far North CA",
    source_name: "Passages CRC / CADRC canonical", source_type: "nonprofit",
  },
  {
    section: "VE-CG", title: "USC Family Caregiver Support Center / LA Caregiver Resource Center",
    cat: "family-support", sub: "Caregiver Support",
    desc: "One of 11 California Caregiver Resource Centers (CRC) administered by the CA Department of Aging. Serves Los Angeles + Ventura counties for family caregivers of adults with chronic or disabling conditions.",
    website_url: "https://lacrc.usc.edu/",
    phone: "(800) 540-4442", address: "3715 McClintock Avenue",
    city: "Los Angeles", zip: "90089",
    eligibility: "Family caregivers in LA + Ventura counties",
    source_name: "USC LACRC / CADRC canonical", source_type: "nonprofit",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B4 — Coast/North/Sierra/Imperial", state: "CA" });
