/**
 * SC Phase 6 — Micro-fill Closeout (target ~40 verified rows)
 *
 * Founder ask (2026-04-24): close SC under the new SOP before NC Phase 5.
 * Lift the 3 weak categories above the 30-row operational floor with REAL
 * verified resources only (no padding):
 *   INS — Insurance         15 → 30+   (+15 candidates)
 *   FIN — Financial/Credit  17 → 30+   (+13 candidates)
 *   CRI — Crisis Help       18 → 30+   (+12 candidates)
 *
 * Naming rule (codified Phase 5): unique geography/program identifier BEFORE
 * the first em-dash so normalizeTitle() does not collapse parent-org siblings.
 *
 * Run:
 *   tsx scripts/seed-sc-phase6-microfill.ts            # dry-run
 *   tsx scripts/seed-sc-phase6-microfill.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const STATE = "SC";
const COMMIT = process.argv.includes("--commit");

const SECTION_LABELS: Record<string, string> = {
  INS: "Insurance micro-fill",
  FIN: "Financial micro-fill",
  CRI: "Crisis micro-fill",
};

const ROWS: SeedRow[] = [
  // ===========================================================================
  // INS — Insurance micro-fill (15 candidates → target lift to 30+)
  // ===========================================================================
  { section: "INS", title: "SC Department of Insurance Consumer Services Office",
    cat: "insurance", sub: "Health Insurance",
    desc: "SC state insurance regulator. Free help for veterans on insurance complaints, denied claims, fraud, and policy disputes (auto, home, life, health). Consumer hotline.",
    website_url: "https://doi.sc.gov/", phone: "803-737-6160",
    address: "1201 Main Street, Suite 1000", city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "SC Department of Insurance", source_type: "government" },

  { section: "INS", title: "TRICARE East Region Beneficiary Services (Humana Military)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Humana Military operates TRICARE East Region covering SC. Beneficiary services, network referrals, claims, and authorizations for active-duty, retirees, and family members.",
    website_url: "https://www.humanamilitary.com", phone: "800-444-5445",
    address: "TRICARE East regional office (SC service)",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Humana Military / TRICARE East", source_type: "government" },

  { section: "INS", title: "Beaufort Naval Hospital TRICARE Service Center",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "TRICARE service for Beaufort/Parris Island military families. Enrollment, PCM changes, authorizations, and beneficiary services on Beaufort Naval Hospital campus.",
    website_url: "https://beaufort.tricare.mil", phone: "843-228-5301",
    address: "1 Pinckney Boulevard", city: "Beaufort", zip: "29902",
    latitude: 32.4368, longitude: -80.7144,
    source_name: "U.S. Navy / TRICARE", source_type: "government" },

  { section: "INS", title: "Shaw Air Force Base TRICARE Operations Office",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "TRICARE service for Shaw AFB community. Beneficiary services, PCM enrollment, referrals, claims for active-duty 20th Fighter Wing and retirees in Sumter region.",
    website_url: "https://shaw.tricare.mil", phone: "803-895-6850",
    address: "431 Meadowlark Lane", city: "Sumter", zip: "29152",
    latitude: 33.9740, longitude: -80.4710,
    source_name: "U.S. Air Force / TRICARE", source_type: "government" },

  { section: "INS", title: "CHAMPVA Health Administration Center (SC Service)",
    cat: "insurance", sub: "Health Insurance",
    desc: "VA Civilian Health and Medical Program (CHAMPVA) for SC veterans' eligible spouses, surviving spouses, and dependent children of permanently disabled or deceased veterans.",
    website_url: "https://www.va.gov/health-care/family-caregiver-benefits/champva/",
    phone: "800-733-8387",
    address: "VA HAC handles SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },

  { section: "INS", title: "Veterans Mortgage Life Insurance (VMLI) Program",
    cat: "insurance", sub: "Life Insurance",
    desc: "VA mortgage life insurance for severely disabled veterans with SAH grants. Up to $200K coverage paid directly to mortgage lender on death. SC veterans apply via VA insurance.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/vmli/",
    phone: "800-419-1473",
    address: "VA Insurance Center serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },

  { section: "INS", title: "Beneficiary Financial Counseling Service (BFCS) — Prudential",
    cat: "insurance", sub: "Life Insurance",
    desc: "Free Prudential financial counseling for SGLI/VGLI beneficiaries of SC veterans. Helps surviving spouses and families decide how to use life insurance proceeds.",
    website_url: "https://benefits.prudential.com/militaryfamilies",
    phone: "888-243-7351",
    address: "Prudential SGLI/VGLI service center",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Prudential / VA OSGLI", source_type: "government" },

  { section: "INS", title: "Service-Disabled Veterans Insurance (S-DVI) Program",
    cat: "insurance", sub: "Life Insurance",
    desc: "VA life insurance for SC veterans rated for a service-connected disability. Up to $40K base coverage, plus supplemental for totally-disabled. Apply within 2 years of rating.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/s-dvi/",
    phone: "800-419-1473",
    address: "VA Insurance Center serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },

  { section: "INS", title: "DFAS Survivor Benefit Plan (SBP) Administration",
    cat: "insurance", sub: "Life Insurance",
    desc: "Defense Finance and Accounting Service administers SBP annuity for surviving spouses of SC military retirees. Election counseling, claims, and monthly annuity payments.",
    website_url: "https://www.dfas.mil/RetiredMilitary/survivors/SBP-AC/",
    phone: "800-321-1080",
    address: "DFAS Cleveland serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "U.S. Department of Defense / DFAS", source_type: "government" },

  { section: "INS", title: "Federal Long Term Care Insurance Program (FLTCIP)",
    cat: "insurance", sub: "Long-Term Care Insurance",
    desc: "Federally-sponsored long-term care insurance for SC veterans, federal employees, and qualifying family members. Group rates, no medical underwriting in some windows.",
    website_url: "https://www.ltcfeds.com",
    phone: "800-582-3337",
    address: "FLTCIP serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "U.S. Office of Personnel Management", source_type: "government" },

  { section: "INS", title: "TRICARE Pharmacy Program (Express Scripts SC)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Express Scripts manages TRICARE pharmacy benefits for SC active-duty, retirees, and dependents. Home delivery, in-network retail, formulary, and military pharmacy options.",
    website_url: "https://militaryrx.express-scripts.com",
    phone: "877-363-1303",
    address: "Express Scripts serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Express Scripts / TRICARE", source_type: "government" },

  { section: "INS", title: "MOAA Insurance Plans — South Carolina Service",
    cat: "insurance", sub: "Life Insurance",
    desc: "Military Officers Association of America insurance plans for SC retired and active officers, surviving spouses. Term life, dental, vision, long-term care, Medicare supplement.",
    website_url: "https://www.moaainsurance.com",
    phone: "800-247-2192",
    address: "MOAA serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Military Officers Association of America", source_type: "nonprofit" },

  { section: "INS", title: "NCOA Insurance Trust — South Carolina Service",
    cat: "insurance", sub: "Life Insurance",
    desc: "Non-Commissioned Officers Association insurance trust for SC enlisted veterans and family. Term life, accident, hospital indemnity, group rates for member NCOs.",
    website_url: "https://www.ncoa-usa.org",
    phone: "800-662-2620",
    address: "NCOA serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Non-Commissioned Officers Association", source_type: "nonprofit" },

  { section: "INS", title: "SC Healthy Connections Medicaid Veterans Outreach",
    cat: "insurance", sub: "Health Insurance",
    desc: "SC Department of Health and Human Services Medicaid program. Low-income SC veterans may qualify for full Medicaid; works alongside VA Healthcare. Online application.",
    website_url: "https://www.scdhhs.gov",
    phone: "888-549-0820",
    address: "1801 Main Street", city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "SC Department of Health and Human Services", source_type: "government" },

  { section: "INS", title: "SC Healthy Connections Kids (CHIP)",
    cat: "insurance", sub: "Health Insurance",
    desc: "Children's Health Insurance Program for SC veteran families with children up to 19. Low or no-cost coverage for kids in families above Medicaid limits.",
    website_url: "https://www.scdhhs.gov/programs-services/healthy-connections-kids",
    phone: "888-549-0820",
    address: "1801 Main Street", city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "SC Department of Health and Human Services", source_type: "government" },

  // ===========================================================================
  // FIN — Financial / Credit micro-fill (13 candidates)
  // ===========================================================================
  { section: "FIN", title: "Navy Federal Credit Union Mt Pleasant Branch",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Navy Federal full-service branch serving Charleston tri-county military families. Auto loans, mortgages, savings, military checking. Open to all DoD/veteran members.",
    website_url: "https://www.navyfederal.org",
    phone: "888-842-6328",
    address: "880 Houston Northcutt Boulevard", city: "Mount Pleasant", zip: "29464",
    latitude: 32.7991, longitude: -79.8674,
    source_name: "Navy Federal Credit Union", source_type: "nonprofit" },

  { section: "FIN", title: "Navy Federal Credit Union Beaufort Branch",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Navy Federal full-service branch serving Beaufort/Parris Island and Hilton Head military community. Auto, mortgages, military checking, financial counseling.",
    website_url: "https://www.navyfederal.org",
    phone: "888-842-6328",
    address: "200 Robert Smalls Parkway", city: "Beaufort", zip: "29906",
    latitude: 32.4368, longitude: -80.7144,
    source_name: "Navy Federal Credit Union", source_type: "nonprofit" },

  { section: "FIN", title: "Navy Federal Credit Union Sumter Branch (Shaw AFB)",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Navy Federal branch serving Shaw AFB and Sumter military community. Auto loans, mortgages, military checking, savings. Open to all military, veterans, and family.",
    website_url: "https://www.navyfederal.org",
    phone: "888-842-6328",
    address: "1146 Broad Street", city: "Sumter", zip: "29150",
    latitude: 33.9210, longitude: -80.3434,
    source_name: "Navy Federal Credit Union", source_type: "nonprofit" },

  { section: "FIN", title: "SAFE Federal Credit Union Sumter Headquarters",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Sumter-based credit union founded by Shaw AFB personnel. 25+ branches across SC. Military-friendly auto loans, VA loans, savings, financial education for veterans.",
    website_url: "https://www.safefed.org",
    phone: "803-469-8600",
    address: "1730 Highway 15 South", city: "Sumter", zip: "29150",
    latitude: 33.9210, longitude: -80.3434,
    source_name: "SAFE Federal Credit Union", source_type: "nonprofit" },

  { section: "FIN", title: "Founders Federal Credit Union Lancaster Headquarters",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Lancaster-based credit union with 30+ SC branches. Auto loans, mortgages, savings, debt consolidation, free financial counseling. Open to SC residents and family.",
    website_url: "https://www.foundersfcu.com",
    phone: "800-845-1614",
    address: "737 Plantation Road", city: "Lancaster", zip: "29720",
    latitude: 34.7204, longitude: -80.7706,
    source_name: "Founders Federal Credit Union", source_type: "nonprofit" },

  { section: "FIN", title: "South Carolina Federal Credit Union Charleston HQ",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "SC Federal Credit Union serves DoD personnel statewide and Charleston tri-county. Military-friendly checking, auto loans, mortgages, financial counseling.",
    website_url: "https://www.scfederal.org",
    phone: "800-845-0432",
    address: "6265 Rivers Avenue", city: "North Charleston", zip: "29406",
    latitude: 32.9024, longitude: -80.0388,
    source_name: "South Carolina Federal Credit Union", source_type: "nonprofit" },

  { section: "FIN", title: "Family Credit Counseling Service of SC (Columbia)",
    cat: "financial", sub: "Debt Counseling",
    desc: "Nonprofit credit counseling for SC veterans. Free debt analysis, debt management plans, bankruptcy counseling, housing counseling. Sliding-scale fees, NFCC-affiliated.",
    website_url: "https://www.fccsmidlands.org",
    phone: "803-733-1858",
    address: "2711 Middleburg Drive, Suite 209", city: "Columbia", zip: "29204",
    latitude: 34.0397, longitude: -81.0237,
    source_name: "Family Credit Counseling Service", source_type: "nonprofit" },

  { section: "FIN", title: "SC Department of Revenue Veterans Property Tax Exemption",
    cat: "financial", sub: "Tax Preparation",
    desc: "SC DOR program: 100%-disabled veterans qualify for property tax exemption on home + vehicle. Survivor extension. Apply through county auditor with VA disability letter.",
    website_url: "https://dor.sc.gov/tax/veterans",
    phone: "844-898-8542",
    address: "300A Outlet Pointe Boulevard", city: "Columbia", zip: "29210",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "SC Department of Revenue", source_type: "government" },

  { section: "FIN", title: "Charleston County Auditor Veteran Property Tax Office",
    cat: "financial", sub: "Tax Preparation",
    desc: "Charleston County Auditor processes veteran disability property-tax exemptions for tri-county home and vehicle. Bring DD-214 + VA disability letter to apply.",
    website_url: "https://www.charlestoncounty.org/departments/auditor/",
    phone: "843-958-4200",
    address: "101 Meeting Street, Suite 105", city: "Charleston", zip: "29401",
    latitude: 32.7872, longitude: -79.9486,
    source_name: "Charleston County Government", source_type: "government" },

  { section: "FIN", title: "Greenville County Auditor Veteran Property Tax Office",
    cat: "financial", sub: "Tax Preparation",
    desc: "Greenville County Auditor processes veteran disability property-tax exemptions for home and vehicle. Bring DD-214 + VA disability letter to apply.",
    website_url: "https://www.greenvillecounty.org/auditor/",
    phone: "864-467-7240",
    address: "301 University Ridge, Suite 800", city: "Greenville", zip: "29601",
    latitude: 34.8431, longitude: -82.4002,
    source_name: "Greenville County Government", source_type: "government" },

  { section: "FIN", title: "United Way of the Midlands Columbia",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Columbia-area United Way coordinating financial-stability programs: emergency assistance, FAFSA help, VITA tax prep, housing counseling, financial coaching.",
    website_url: "https://www.uway.org",
    phone: "803-733-5400",
    address: "1818 Blanding Street", city: "Columbia", zip: "29201",
    latitude: 34.0119, longitude: -81.0381,
    source_name: "United Way of the Midlands", source_type: "nonprofit" },

  { section: "FIN", title: "United Way of Greater Greenville County",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Greenville County United Way. Financial stability initiatives, VITA free tax prep, FAFSA assistance, eviction prevention, financial literacy for veterans.",
    website_url: "https://www.unitedwaygc.org",
    phone: "864-467-3300",
    address: "105 Edinburgh Court", city: "Greenville", zip: "29607",
    latitude: 34.8389, longitude: -82.3779,
    source_name: "United Way of Greater Greenville County", source_type: "nonprofit" },

  { section: "FIN", title: "SC Thrive Statewide Benefits Enrollment",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Statewide benefits enrollment center. Free help applying for SNAP, Medicaid, Healthy Connections, LIHEAP, SC Voucher, free tax prep. Helps SC veterans stack benefits.",
    website_url: "https://scthrive.org",
    phone: "800-726-8774",
    address: "PO Box 5366", city: "Columbia", zip: "29250",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "SC Thrive", source_type: "nonprofit" },

  { section: "FIN", title: "Modest Needs Foundation SC Emergency Grants",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "National emergency grant nonprofit serving SC. Self-sufficiency grants of up to $1000 for low-income working veterans facing one-time hardship (medical bill, car repair, etc).",
    website_url: "https://www.modestneeds.org",
    phone: "844-667-3776",
    address: "Modest Needs serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Modest Needs Foundation", source_type: "nonprofit" },

  // ===========================================================================
  // CRI — Crisis Help micro-fill (12 candidates)
  // ===========================================================================
  { section: "CRI", title: "SC DMH Mobile Crisis Spartanburg Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis Response in Spartanburg/Cherokee/Union counties. 24/7 in-person + phone crisis stabilization. Veterans referred to Vet Center for follow-up.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Spartanburg Mental Health Center", city: "Spartanburg", zip: "29306",
    latitude: 34.9496, longitude: -81.9320,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "SC DMH Mobile Crisis Pee Dee Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis Response covering Florence/Darlington/Marion/Marlboro/Dillon. 24/7 in-person + phone crisis stabilization. Veterans referred to Vet Center.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Pee Dee Mental Health Center", city: "Florence", zip: "29501",
    latitude: 34.1971, longitude: -79.7626,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "SC DMH Mobile Crisis Lowcountry Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis covering Beaufort/Jasper/Hampton/Allendale/Colleton. 24/7 in-person + phone crisis stabilization. Strong military-spouse referral pathway.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Coastal Empire Mental Health Center", city: "Beaufort", zip: "29902",
    latitude: 32.4368, longitude: -80.7144,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "SC DMH Mobile Crisis Aiken-Barnwell Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis covering Aiken/Barnwell/Allendale CSRA region. 24/7 in-person + phone crisis stabilization. Coordinates with Augusta VA across border.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Aiken-Barnwell Mental Health Center", city: "Aiken", zip: "29801",
    latitude: 33.5604, longitude: -81.7196,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "SC DMH Mobile Crisis Anderson-Oconee-Pickens Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis covering Upstate AOP region. 24/7 in-person + phone crisis stabilization for Anderson/Oconee/Pickens veterans.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Anderson-Oconee-Pickens MHC", city: "Anderson", zip: "29621",
    latitude: 34.5034, longitude: -82.6501,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "SC DMH Mobile Crisis Lexington Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis covering Lexington County. 24/7 in-person + phone crisis stabilization for veterans in West Columbia / Lexington / Cayce / Batesburg-Leesville.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Lexington County CMHC", city: "Lexington", zip: "29072",
    latitude: 33.9759, longitude: -81.2371,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "SC DMH Mobile Crisis Catawba Region",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "SC DMH Mobile Crisis covering Rock Hill/York/Lancaster/Chester. 24/7 in-person + phone crisis stabilization. Coordinates with Charlotte VA across border.",
    website_url: "https://www.scdmh.org/mobile-crisis/",
    phone: "833-364-2274",
    address: "Catawba Mental Health Center", city: "Rock Hill", zip: "29732",
    latitude: 34.9249, longitude: -81.0251,
    source_name: "SC Department of Mental Health", source_type: "government" },

  { section: "CRI", title: "Phoenix Center Greenville Crisis Stabilization Unit",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "Greenville County Phoenix Center 16-bed crisis stabilization unit for substance use + co-occurring mental health crisis. 23-59 hour hold. Veteran intake.",
    website_url: "https://phoenixcenter.org/crisis-stabilization/",
    phone: "864-467-3790",
    address: "1400 Cleveland Street", city: "Greenville", zip: "29607",
    latitude: 34.8389, longitude: -82.3779,
    source_name: "Phoenix Center", source_type: "nonprofit" },

  { section: "CRI", title: "Crisis Text Line SC (text HOME to 741741)",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "24/7 anonymous text-based crisis counseling. Text HOME to 741741 from any SC mobile carrier. Crisis counselors trained for trauma, PTSD, suicide ideation; veteran-aware.",
    website_url: "https://www.crisistextline.org",
    phone: "741741",
    address: "Crisis Text Line serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Crisis Text Line", source_type: "nonprofit" },

  { section: "CRI", title: "RAINN National Sexual Assault Hotline (SC Service)",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "RAINN 24/7 hotline routing SC callers to nearest local rape crisis center. Free, confidential. Specifically resources for MST (Military Sexual Trauma) survivors.",
    website_url: "https://www.rainn.org",
    phone: "800-656-4673",
    address: "RAINN serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "RAINN", source_type: "nonprofit" },

  { section: "CRI", title: "National DV Hotline SC General Public Line",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "24/7 free confidential hotline for SC domestic violence victims, including military spouses. Safety planning, shelter referrals, legal advocacy. Spanish line available.",
    website_url: "https://www.thehotline.org",
    phone: "800-799-7233",
    address: "National DV Hotline serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "National Domestic Violence Hotline", source_type: "nonprofit" },

  { section: "CRI", title: "Trans Lifeline SC Peer Support",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "Peer-run hotline for transgender SC veterans in crisis. Operated by trans people for trans people. Confidential, no active rescue protocol unless requested.",
    website_url: "https://translifeline.org",
    phone: "877-565-8860",
    address: "Trans Lifeline serves SC remotely",
    city: "Columbia", zip: "29201",
    latitude: 34.0007, longitude: -81.0394,
    source_name: "Trans Lifeline", source_type: "nonprofit" },
];

runSeed(ROWS, {
  state: STATE,
  commit: COMMIT,
  scriptName: "seed-sc-phase6-microfill",
  sectionLabels: SECTION_LABELS,
});
