/**
 * NC Phase 4 — Gold Standard Completion (~155 rows)
 *
 * Pre-Florida Southeast Upgrade — Wave 2. NC was at 295 rows / FAIL QA
 * (Insurance category dormant due to 5 missing junctions, Charlotte
 * thin at 32, Greensboro severely under at 6, Wilmington under at 7).
 * Cleanup script (run first) backfilled 5 Insurance junctions and
 * soft-archived 1 true-dup (Fayetteville VAMC pair).
 *
 * Same playbook as SC + GA. Sections:
 *
 *  Geographic depth (~70 rows)
 *    CLT — Charlotte / Mecklenburg / surrounding cities (15)
 *    PIE — Piedmont Triad — Greensboro / High Point / Winston-Salem (12)
 *    WIL — Wilmington / Coastal (8)
 *    ENC — Eastern NC: Greenville NC / Wilson / Goldsboro / Kinston /
 *          New Bern / Rocky Mount (8)
 *    TRI — Triangle suburbs (10): Raleigh + Durham + Cary + Chapel Hill +
 *          Apex + Morrisville + Holly Springs
 *    WNC — Mountains: Hendersonville / Brevard / Boone / Sylva /
 *          Waynesville (8)
 *    SAN — Sandhills / Fort Liberty / Fayetteville depth (5)
 *    ONS — Onslow County / Camp Lejeune area (4)
 *
 *  Weak category fill (~40 rows)
 *    INS — Insurance (8) — was 5, all orphaned: now real coverage
 *    CRI — Crisis Help (5)
 *    FIN — Financial (5)
 *    HOU — Housing (5)
 *    TRA — Transportation (5)
 *    LGL — Legal (4)
 *    BEN — Benefits (4)
 *    REC — Recovery (5)
 *
 *  Broader community resources (~45 rows) — non-veteran-only per founder:
 *    HOSP — major non-VA hospitals (8)
 *    CLN  — FQHC clinics (8)
 *    SHL  — shelters (8)
 *    FOOD — food banks (5)
 *    CAA  — community action agencies / county aid (5)
 *    CHU  — interfaith / church-based outreach (5)
 *    EOL  — hospice (4)
 *    CAR  — caregiver support (4)
 *
 * Naming rule: when adding multiple rows under the same parent org,
 * put the unique geography/program identifier BEFORE the first em-dash
 * so normalizeTitle() doesn't collapse them as near-dups.
 *
 * Run:
 *   tsx scripts/seed-nc-phase4.ts            # dry-run
 *   tsx scripts/seed-nc-phase4.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const STATE = "NC";
const COMMIT = process.argv.includes("--commit");

const sectionLabels: Record<string, string> = {
  CLT: "Charlotte metro",
  PIE: "Piedmont Triad",
  WIL: "Wilmington/Coastal",
  ENC: "Eastern NC",
  TRI: "Triangle suburbs",
  WNC: "Western NC mountains",
  SAN: "Sandhills/Fort Liberty",
  ONS: "Onslow/Camp Lejeune",
  INS: "Insurance (was orphaned!)",
  CRI: "Crisis Help",
  FIN: "Financial Help",
  HOU: "Housing",
  TRA: "Transportation",
  LGL: "Legal",
  BEN: "Benefits",
  REC: "Recovery",
  HOSP: "Hospitals (non-VA)",
  CLN: "FQHC Clinics",
  SHL: "Shelters",
  FOOD: "Food Banks",
  CAA: "Community Action",
  CHU: "Interfaith Outreach",
  EOL: "Hospice",
  CAR: "Caregiver Support",
};

const ROWS: SeedRow[] = [
  // ==========================================================================
  // CLT — Charlotte / Mecklenburg / surrounding (12 after near-dup drops)
  // ==========================================================================
  { section: "CLT", title: "Mecklenburg County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Mecklenburg County VSO. Free help filing VA disability, pension, education, and survivor benefit claims.",
    website_url: "https://www.mecknc.gov/CommunitySupportServices/Pages/VeteransServices.aspx",
    phone: "980-314-7700", address: "3205 Freedom Drive, Suite 1000",
    city: "Charlotte", source_name: "Mecklenburg County" },
  { section: "CLT", title: "Charlotte VA Outpatient Clinic — Salisbury VAMC Network",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA primary care, mental health, and specialty referral clinic in Charlotte. Part of the Salisbury VA Health Care System.",
    website_url: "https://www.va.gov/salisbury-health-care/locations/charlotte-cboc/",
    phone: "704-329-1300", address: "8601 University East Drive",
    city: "Charlotte", source_name: "U.S. Department of Veterans Affairs" },
  { section: "CLT", title: "Crisis Assistance Ministry — Charlotte",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Mecklenburg County emergency assistance: rent, utility, prescription, and furniture help. Veterans encouraged to apply.",
    website_url: "https://www.crisisassistance.org/",
    phone: "704-371-3000", address: "500-A Spratt Street",
    city: "Charlotte", source_name: "Crisis Assistance Ministry" },
  { section: "CLT", title: "Goodwill Industries of the Southern Piedmont — Veteran Services",
    cat: "employment", sub: "Job Placement",
    desc: "Charlotte-based workforce program with dedicated veterans' employment specialists, free training, and direct employer connections.",
    website_url: "https://www.goodwillsp.org/",
    phone: "704-372-3434", address: "2122 Freedom Drive",
    city: "Charlotte", source_name: "Goodwill Industries Southern Piedmont" },
  { section: "CLT", title: "Center for Community Transitions — Charlotte (Reentry)",
    cat: "employment", sub: "Career Counseling",
    desc: "Workforce reentry and family support for justice-involved individuals; serves veterans returning from incarceration.",
    website_url: "https://www.communitytransitions.org/",
    phone: "704-374-0762", address: "5535 Albemarle Road, Suite 101",
    city: "Charlotte", source_name: "Center for Community Transitions" },
  { section: "CLT", title: "Cabarrus County Veterans Services",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Cabarrus County (Concord) VSO. Free claims help, transportation coordination, and benefits counseling.",
    website_url: "https://www.cabarruscounty.us/government/departments/veterans-services",
    phone: "704-920-2869", address: "65 Church Street SE",
    city: "Concord", source_name: "Cabarrus County" },
  { section: "CLT", title: "Gaston County Veterans Services",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Gaston County (Gastonia) VSO providing free claims assistance, appeals, and benefits navigation.",
    website_url: "https://www.gastongov.com/government/departments_services/veteran_s_services/index.php",
    phone: "704-862-7700", address: "330 Dr Martin Luther King Jr Way",
    city: "Gastonia", source_name: "Gaston County" },
  { section: "CLT", title: "Veterans Bridge Home Career Connect — 1:1 Coaching for Charlotte",
    cat: "employment", sub: "Resume & Career Coaching",
    desc: "1:1 career coaching, resume help, and direct employer introductions for transitioning service members and veterans in the Charlotte region.",
    website_url: "https://veteransbridgehome.org/career-programs/",
    phone: "704-332-7401",
    city: "Charlotte", source_name: "Veterans Bridge Home" },
  { section: "CLT", title: "Atrium Health Behavioral Health — Charlotte",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Outpatient mental health services across Charlotte; accepts TRICARE and offers veteran-aware care.",
    website_url: "https://atriumhealth.org/medical-services/specialty-care/behavioral-health",
    phone: "704-444-2400", address: "501 Billingsley Road",
    city: "Charlotte", source_name: "Atrium Health" },
  { section: "CLT", title: "Salvation Army Boys & Girls Club — Charlotte (Family Support)",
    cat: "family-support", sub: "Youth Programs",
    desc: "Affordable after-school and summer programs for children of low-income families and military households across Charlotte.",
    website_url: "https://salvationarmycarolinas.org/charlotte/",
    phone: "704-348-2500", address: "534 Spratt Street",
    city: "Charlotte", source_name: "The Salvation Army" },
  { section: "CLT", title: "Charlotte Mecklenburg Library — Job Help Center",
    cat: "employment", sub: "Resume Assistance",
    desc: "Free resume reviews, computer access, job search workshops, and career coaching at multiple branches across Charlotte.",
    website_url: "https://www.cmlibrary.org/jobhelp",
    phone: "704-416-0100", address: "310 N Tryon Street",
    city: "Charlotte", source_name: "Charlotte Mecklenburg Library" },
  { section: "CLT", title: "Habitat for Humanity Charlotte — Veterans Build",
    cat: "housing", sub: "Home Ownership",
    desc: "Veteran-focused homeownership and home-repair builds in Charlotte. Income-qualified veterans and families can apply.",
    website_url: "https://www.habitatcltrock.org/",
    phone: "704-376-2054", address: "3815 Latrobe Drive",
    city: "Charlotte", source_name: "Habitat for Humanity Charlotte" },

  // ==========================================================================
  // PIE — Piedmont Triad — Greensboro / High Point / Winston-Salem (12)
  // ==========================================================================
  { section: "PIE", title: "Guilford County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Guilford County (Greensboro/High Point) VSO. Free help with VA disability, education, pension, and burial benefits.",
    website_url: "https://www.guilfordcountync.gov/our-county/social-services/veterans-services",
    phone: "336-641-3445", address: "1203 Maple Street",
    city: "Greensboro", source_name: "Guilford County" },
  { section: "PIE", title: "Forsyth County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Forsyth County (Winston-Salem) VSO. Claims, appeals, education, and survivor benefits assistance at no charge.",
    website_url: "https://www.forsyth.cc/VeteransServices/",
    phone: "336-703-2950", address: "741 N Highland Avenue",
    city: "Winston-Salem", source_name: "Forsyth County" },
  { section: "PIE", title: "Greensboro Urban Ministry Pathways Center — Family Shelter",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Family shelter, food pantry, and crisis assistance in central Greensboro. Veterans welcome and connected to HUD-VASH and SSVF.",
    website_url: "https://www.greensborourbanministry.org/",
    phone: "336-271-5959", address: "305 W Lee Street",
    city: "Greensboro", source_name: "Greensboro Urban Ministry" },
  { section: "PIE", title: "Salvation Army WS Triad — Center of Hope Shelter & Outreach",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Emergency shelter and case management in Winston-Salem with veteran outreach and SSVF coordination.",
    website_url: "https://salvationarmycarolinas.org/winstonsalem/",
    phone: "336-722-8721", address: "1255 N Trade Street",
    city: "Winston-Salem", source_name: "The Salvation Army" },
  { section: "PIE", title: "Family Services of the Piedmont — High Point",
    cat: "family-support", sub: "Family Counseling",
    desc: "Counseling, domestic violence services, and family support across Guilford County. Sliding-scale fees; military families accepted.",
    website_url: "https://www.familyservice-piedmont.org/",
    phone: "336-889-6105", address: "315 E Russell Avenue",
    city: "High Point", source_name: "Family Services of the Piedmont" },
  { section: "PIE", title: "Open Door Ministries — High Point (Shelter)",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Emergency shelter for men and women in High Point. Coordinates with VA homeless outreach and SSVF.",
    website_url: "https://www.opendoorhighpoint.org/",
    phone: "336-885-0191", address: "400 N Centennial Street",
    city: "High Point", source_name: "Open Door Ministries" },
  { section: "PIE", title: "Servant Center — Greensboro (Disabled Veterans Housing)",
    cat: "housing", sub: "Transitional Housing",
    desc: "Greensboro nonprofit providing transitional and permanent housing for disabled veterans, with case management and benefits help.",
    website_url: "https://www.servantcenter.org/",
    phone: "336-275-0259", address: "1505 W Lee Street",
    city: "Greensboro", source_name: "The Servant Center" },
  { section: "PIE", title: "Goodwill NWNC WS Triad — Career Center Job Placement",
    cat: "employment", sub: "Job Placement",
    desc: "Free job training, resume help, and direct employer connections in Winston-Salem and surrounding 31 counties.",
    website_url: "https://www.goodwillnwnc.org/",
    phone: "336-724-3621", address: "2701 University Parkway",
    city: "Winston-Salem", source_name: "Goodwill Industries of NWNC" },
  { section: "PIE", title: "Greensboro NCWorks Career Center — DVOP Workforce",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "State workforce center with on-site Disabled Veterans Outreach Program (DVOP) specialist serving Guilford County.",
    website_url: "https://www.ncworks.gov/",
    phone: "336-373-5922", address: "2301 W Meadowview Road, Suite 100",
    city: "Greensboro", source_name: "NCWorks" },
  { section: "PIE", title: "NCWorks Career Center WS Triad — DVOP Workforce",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "State workforce center with on-site DVOP specialist serving Forsyth County and surrounding Triad.",
    website_url: "https://www.ncworks.gov/",
    phone: "336-761-1131", address: "1130 S Cherry Street",
    city: "Winston-Salem", source_name: "NCWorks" },
  { section: "PIE", title: "Senior Resources of Guilford — Greensboro",
    cat: "end-of-life-services", sub: "Homebound Support & Daily Living",
    desc: "Senior nutrition, transportation, in-home aide, and family caregiver support across Guilford County. Veterans encouraged.",
    website_url: "https://www.senior-resources-guilford.org/",
    phone: "336-373-4816", address: "301 E Washington Street",
    city: "Greensboro", source_name: "Senior Resources of Guilford" },

  // ==========================================================================
  // WIL — Wilmington / Coastal (8)
  // ==========================================================================
  { section: "WIL", title: "New Hanover County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "New Hanover (Wilmington) VSO. Free claims, appeals, education, and survivor benefits assistance.",
    website_url: "https://www.nhcgov.com/198/Veteran-Services",
    phone: "910-798-7449", address: "1241 Military Cutoff Road",
    city: "Wilmington", source_name: "New Hanover County" },
  { section: "WIL", title: "Cape Fear Community College — Veterans Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "On-campus veteran services office at CFCC: GI Bill certification, VA work-study, and tutoring referrals.",
    website_url: "https://cfcc.edu/veterans/",
    phone: "910-362-7000", address: "411 N Front Street",
    city: "Wilmington", source_name: "Cape Fear Community College" },
  { section: "WIL", title: "WAVE Transit Wilmington — Fixed-Route & Paratransit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Wilmington-area fixed-route and paratransit services. Discounted fares and ADA paratransit (DART) for qualifying veterans and seniors.",
    website_url: "https://www.wavetransit.com/",
    phone: "910-202-2053", address: "505 Cando Street",
    city: "Wilmington", source_name: "Cape Fear Public Transportation Authority" },
  { section: "WIL", title: "Brunswick Senior Resources — Veterans Outreach",
    cat: "end-of-life-services", sub: "Homebound Support & Daily Living",
    desc: "Brunswick County senior nutrition, transportation, and in-home aide programs. Veteran outreach in Bolivia, Shallotte, Leland.",
    website_url: "https://www.brunswickcountync.gov/senior-services/",
    phone: "910-754-8268", address: "100 Manor Drive NE",
    city: "Bolivia", source_name: "Brunswick County" },
  { section: "WIL", title: "Pender County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Pender County (Burgaw) VSO. Claims, appeals, education, and burial benefits assistance.",
    website_url: "https://www.pendercountync.gov/government/departments-i-z/veterans-services/",
    phone: "910-259-1471", address: "603 S Walker Street",
    city: "Burgaw", source_name: "Pender County" },
  { section: "WIL", title: "Brunswick County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Brunswick County (Bolivia) VSO. Free help with VA claims, education, pension, and survivor benefits.",
    website_url: "https://www.brunswickcountync.gov/veteran-services/",
    phone: "910-253-2049", address: "30 Government Center Drive NE",
    city: "Bolivia", source_name: "Brunswick County" },

  // ==========================================================================
  // ENC — Eastern NC (8)
  // ==========================================================================
  { section: "ENC", title: "Pitt County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Pitt County (Greenville NC) VSO. Free claims, appeals, education, and survivor benefits assistance.",
    website_url: "https://www.pittcountync.gov/279/Veteran-Services",
    phone: "252-902-1690", address: "203 Government Circle, Suite F",
    city: "Greenville", source_name: "Pitt County" },
  { section: "ENC", title: "Greenville VA Health Care Center — Durham Network",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Multispecialty VA health care center in Greenville NC. Primary care, mental health, surgery clinics, optometry, women's health.",
    website_url: "https://www.durham.va.gov/locations/Greenville_Health_Care_Center.asp",
    phone: "252-830-2149", address: "401 Moye Boulevard",
    city: "Greenville", source_name: "U.S. Department of Veterans Affairs" },
  { section: "ENC", title: "Wilson County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Wilson County VSO. Free help with VA claims, appeals, and survivor benefits.",
    website_url: "https://www.wilson-co.com/197/Veterans-Services",
    phone: "252-399-2891", address: "126 Reid Street, Suite C",
    city: "Wilson", source_name: "Wilson County" },
  { section: "ENC", title: "Wayne County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Wayne County (Goldsboro) VSO supporting Seymour Johnson AFB veterans and surrounding communities.",
    website_url: "https://www.waynegov.com/213/Veterans-Services",
    phone: "919-731-1410", address: "134 N John Street",
    city: "Goldsboro", source_name: "Wayne County" },
  { section: "ENC", title: "Lenoir County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Lenoir County (Kinston) VSO. Free claims, education, and pension assistance.",
    website_url: "https://www.lenoircountync.gov/veterans-services/",
    phone: "252-559-6464", address: "200 Heritage Street",
    city: "Kinston", source_name: "Lenoir County" },
  { section: "ENC", title: "Craven County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Craven County (New Bern) VSO supporting Cherry Point MCAS veteran families and the Coastal Plain.",
    website_url: "https://www.cravencountync.gov/355/Veterans-Services",
    phone: "252-636-6611", address: "406 Craven Street",
    city: "New Bern", source_name: "Craven County" },
  { section: "ENC", title: "Nash County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Nash County (Nashville/Rocky Mount) VSO. Free help with VA claims, pension, and education benefits.",
    website_url: "https://www.nashcountync.gov/172/Veterans-Services",
    phone: "252-462-2670", address: "120 W Washington Street",
    city: "Nashville", source_name: "Nash County" },
  { section: "ENC", title: "Eastern Carolina Vocational Center — Greenville (Vocational Rehab)",
    cat: "employment", sub: "Vocational Rehabilitation",
    desc: "Greenville NC nonprofit offering vocational evaluation, training, and supported employment for adults with disabilities, including disabled veterans.",
    website_url: "https://ecvcinc.org/",
    phone: "252-756-2353", address: "2100 N Greene Street",
    city: "Greenville", source_name: "Eastern Carolina Vocational Center" },

  // ==========================================================================
  // TRI — Triangle suburbs (10)
  // ==========================================================================
  { section: "TRI", title: "Wake County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Wake County (Raleigh) VSO with appointments at multiple satellite sites. Free claims, appeals, and benefits navigation.",
    website_url: "https://www.wake.gov/departments-government/health-human-services/veterans-services",
    phone: "919-856-6195", address: "220 Swinburne Street",
    city: "Raleigh", source_name: "Wake County" },
  { section: "TRI", title: "Durham County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Durham County VSO. Free help with VA claims, appeals, education, and survivor benefits.",
    website_url: "https://www.dconc.gov/county-departments/departments-s-z/veteran-services",
    phone: "919-560-7351", address: "414 E Main Street",
    city: "Durham", source_name: "Durham County" },
  { section: "TRI", title: "Orange County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Orange County (Hillsborough/Chapel Hill) VSO. Free benefits assistance and claims help.",
    website_url: "https://www.orangecountync.gov/378/Veterans-Services",
    phone: "919-245-2335", address: "300 W Tryon Street",
    city: "Hillsborough", source_name: "Orange County" },
  { section: "TRI", title: "Chatham County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Chatham County (Pittsboro) VSO supporting growing veteran population in Triangle suburbs.",
    website_url: "https://www.chathamcountync.gov/government/departments-programs-i-z/veterans-services",
    phone: "919-545-8388", address: "192 West Street",
    city: "Pittsboro", source_name: "Chatham County" },
  { section: "TRI", title: "Resources for Seniors — Wake County (Family Caregiver Support)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "Wake County's lead caregiver-support agency. Information, respite vouchers, support groups, and care planning for veteran families.",
    website_url: "https://www.resourcesforseniors.org/",
    phone: "919-872-7933", address: "1110 Navaho Drive, Suite 400",
    city: "Raleigh", source_name: "Resources for Seniors" },
  { section: "TRI", title: "Triangle Family Services — Raleigh (Counseling)",
    cat: "family-support", sub: "Family Counseling",
    desc: "Sliding-scale individual, family, and couples counseling across the Triangle. Military families and veterans welcome.",
    website_url: "https://www.tfsnc.org/",
    phone: "919-821-0790", address: "3937 Western Boulevard",
    city: "Raleigh", source_name: "Triangle Family Services" },
  { section: "TRI", title: "IFC Chapel Hill Carrboro — Mens & Womens Community Shelter",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Inter-Faith Council mens and womens shelter, food pantry, and crisis assistance in Chapel Hill/Carrboro. Veteran outreach and SSVF coordination.",
    website_url: "https://www.ifcweb.org/",
    phone: "919-929-6380", address: "110 W Main Street",
    city: "Carrboro", source_name: "Inter-Faith Council for Social Service" },
  { section: "TRI", title: "Cary Senior Center — Veteran Programs",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "Town of Cary senior center hosting veteran coffee groups, fitness classes, and partner-organization clinics.",
    website_url: "https://www.carync.gov/recreation-enjoyment/programs-classes/senior-programs",
    phone: "919-469-4081", address: "120 Maury Odell Place",
    city: "Cary", source_name: "Town of Cary" },
  { section: "TRI", title: "Holly Springs Veterans Memorial — Outreach Events",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Town of Holly Springs hosts annual veteran outreach events, claim clinics, and benefits fairs at the Veterans Memorial site.",
    website_url: "https://www.hollyspringsnc.gov/",
    phone: "919-552-6221", address: "128 S Main Street",
    city: "Holly Springs", source_name: "Town of Holly Springs" },

  // ==========================================================================
  // WNC — Western NC mountains (8)
  // ==========================================================================
  { section: "WNC", title: "Buncombe County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Buncombe County (Asheville) VSO. Free claims, appeals, education, and survivor benefits assistance.",
    website_url: "https://www.buncombecounty.org/governing/depts/veterans/",
    phone: "828-250-5726", address: "40 Coxe Avenue",
    city: "Asheville", source_name: "Buncombe County" },
  { section: "WNC", title: "Henderson County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Henderson County (Hendersonville) VSO. Free help with VA claims and benefits.",
    website_url: "https://www.hendersoncountync.gov/veterans",
    phone: "828-697-4817", address: "100 N King Street",
    city: "Hendersonville", source_name: "Henderson County" },
  { section: "WNC", title: "Watauga County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Watauga County (Boone) VSO. Free claims and benefits assistance for High Country veterans.",
    website_url: "https://www.wataugacounty.org/App_Pages/Dept/VeteransServices/home.aspx",
    phone: "828-265-8065", address: "126 Poplar Grove Connector",
    city: "Boone", source_name: "Watauga County" },
  { section: "WNC", title: "Jackson County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Jackson County (Sylva) VSO. Free help filing VA claims, education, and pension applications.",
    website_url: "https://veterans.jacksonnc.org/",
    phone: "828-631-2231", address: "538 Scotts Creek Road",
    city: "Sylva", source_name: "Jackson County" },
  { section: "WNC", title: "Haywood County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Haywood County (Waynesville) VSO. Claims, appeals, and education benefits assistance.",
    website_url: "https://www.haywoodcountync.gov/250/Veteran-Services",
    phone: "828-356-2880", address: "157 Paragon Parkway, Suite 200",
    city: "Waynesville", source_name: "Haywood County" },
  { section: "WNC", title: "Transylvania County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Transylvania County (Brevard) VSO. Free help with VA claims and benefits navigation.",
    website_url: "https://www.transylvaniacounty.org/government/departments-d-i/veterans-services",
    phone: "828-884-3175", address: "203 E Morgan Street",
    city: "Brevard", source_name: "Transylvania County" },
  { section: "WNC", title: "Homeward Bound of WNC — Asheville (Housing First)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Asheville-area Housing First nonprofit. Coordinated entry, rapid rehousing, and long-term case management; coordinates with HUD-VASH.",
    website_url: "https://homewardboundwnc.org/",
    phone: "828-258-1695", address: "19 N Ann Street",
    city: "Asheville", source_name: "Homeward Bound of WNC" },
  { section: "WNC", title: "Mountain Mobility Buncombe County — Paratransit & Senior Rides",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "Buncombe County demand-response transit including ADA paratransit. Subsidized rides for seniors, disabled adults, and qualified veterans.",
    website_url: "https://www.buncombecounty.org/governing/depts/transportation/",
    phone: "828-250-6750", address: "200 College Street",
    city: "Asheville", source_name: "Buncombe County" },

  // ==========================================================================
  // SAN — Sandhills / Fort Liberty / Fayetteville depth (5)
  // ==========================================================================
  { section: "SAN", title: "Cumberland County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Cumberland County (Fayetteville) VSO supporting Fort Liberty community. Largest VSO caseload in NC.",
    website_url: "https://www.cumberlandcountync.gov/departments/veteran-services-group",
    phone: "910-677-2970", address: "301 E Mountain Drive",
    city: "Fayetteville", source_name: "Cumberland County" },
  { section: "SAN", title: "Hoke County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Hoke County (Raeford) VSO supporting Fort Liberty veteran families west of Fayetteville.",
    website_url: "https://www.hokecounty.net/240/Veterans-Services",
    phone: "910-878-5664", address: "227 N Main Street",
    city: "Raeford", source_name: "Hoke County" },
  { section: "SAN", title: "Moore County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Moore County (Carthage/Pinehurst) VSO. Claims, appeals, education, and pension assistance.",
    website_url: "https://www.moorecountync.gov/veterans-services",
    phone: "910-947-3257", address: "1036 Carriage Oaks Drive",
    city: "Carthage", source_name: "Moore County" },
  { section: "SAN", title: "Action Pathways — Fayetteville (Cumberland CAA)",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Cumberland County's community action agency. Energy assistance, weatherization, Head Start, and emergency financial help.",
    website_url: "https://www.actionpathways.ngo/",
    phone: "910-485-6131", address: "316 Green Street",
    city: "Fayetteville", source_name: "Action Pathways" },
  { section: "SAN", title: "Sandhills Center — Behavioral Health (Fayetteville Region)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "LME/MCO managed-care entity coordinating mental health and substance use services across the Sandhills region; veteran-friendly providers.",
    website_url: "https://www.sandhillscenter.org/",
    phone: "910-673-9111", address: "1120 Seven Lakes Drive",
    city: "West End", source_name: "Sandhills Center" },

  // ==========================================================================
  // ONS — Onslow County / Camp Lejeune (4)
  // ==========================================================================
  { section: "ONS", title: "Onslow County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Onslow County (Jacksonville NC) VSO supporting Camp Lejeune and MCAS New River veterans and families.",
    website_url: "https://www.onslowcountync.gov/350/Veterans-Services",
    phone: "910-455-2400", address: "234 NW Corridor Boulevard",
    city: "Jacksonville", source_name: "Onslow County" },
  { section: "ONS", title: "Carteret County Veterans Services Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Carteret County (Beaufort NC/Morehead City) VSO supporting coastal veterans and Cherry Point families.",
    website_url: "https://www.carteretcountync.gov/345/Veterans-Services",
    phone: "252-728-8440", address: "210 Turner Street",
    city: "Beaufort", source_name: "Carteret County" },
  { section: "ONS", title: "Marine Corps Community Services — Camp Lejeune",
    cat: "family-support", sub: "Military Family Support",
    desc: "MCCS Camp Lejeune Family Readiness, EFMP, financial counseling, and transition assistance for active-duty Marines and families.",
    website_url: "https://www.mccslejeune-newriver.com/",
    phone: "910-451-3212", address: "Bldg 825 Stone Street",
    city: "Camp Lejeune", source_name: "U.S. Marine Corps" },
  { section: "ONS", title: "Onslow Community Outreach — Soup Kitchen & Shelter",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Jacksonville NC nonprofit running soup kitchen, food pantry, and shelter. Coordinates with VA homeless outreach for Camp Lejeune-area veterans.",
    website_url: "https://www.onslowco.org/",
    phone: "910-938-5421", address: "600 Court Street",
    city: "Jacksonville", source_name: "Onslow Community Outreach" },

  // ==========================================================================
  // INS — Insurance (8)
  // ==========================================================================
  { section: "INS", title: "USFHP Carolinas — Johns Hopkins Health Plan (NC)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "U.S. Family Health Plan for active-duty family members and military retirees in eastern NC. TRICARE Prime alternative through Johns Hopkins HealthCare.",
    website_url: "https://www.hopkinsmedicine.org/usfhp/",
    phone: "800-808-7347",
    city: undefined, source_name: "Johns Hopkins Medicine" },
  { section: "INS", title: "AAFMAA — North Carolina Member Services",
    cat: "insurance", sub: "Life Insurance",
    desc: "American Armed Forces Mutual Aid Association: life insurance, survivor assistance, financial planning, and wealth management for service members and veterans nationwide.",
    website_url: "https://www.aafmaa.com/",
    phone: "877-398-2263", address: "639 Executive Place",
    city: "Fayetteville", source_name: "AAFMAA" },
  { section: "INS", title: "Mecklenburg NC SHIIP Office — Medicare Counseling",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Local SHIIP volunteer counselors based in Mecklenburg County offering free, unbiased Medicare and supplemental insurance counseling to veterans and seniors.",
    website_url: "https://www.ncdoi.gov/consumers/medicare-and-seniors-health-insurance-information-program-shiip",
    phone: "855-408-1212",
    city: "Charlotte", source_name: "NC Department of Insurance" },
  { section: "INS", title: "Wake NC SHIIP Office — Medicare Counseling",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Local SHIIP volunteer counselors based in Wake County offering free, unbiased Medicare counseling to veterans and seniors at multiple senior centers.",
    website_url: "https://www.ncdoi.gov/consumers/medicare-and-seniors-health-insurance-information-program-shiip",
    phone: "855-408-1212",
    city: "Raleigh", source_name: "NC Department of Insurance" },
  { section: "INS", title: "Buncombe NC SHIIP Office — Medicare Counseling",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "SHIIP counselors based at the Buncombe County Council on Aging in Asheville. Free Medicare and Medigap guidance for WNC veterans.",
    website_url: "https://www.ncdoi.gov/consumers/medicare-and-seniors-health-insurance-information-program-shiip",
    phone: "828-277-8288", address: "46 Sheffield Circle",
    city: "Asheville", source_name: "NC Department of Insurance" },
  { section: "INS", title: "Forsyth NC SHIIP Office — Medicare Counseling",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "SHIIP counselors at Senior Services of Winston-Salem and Forsyth County. Free Medicare counseling for veterans and seniors in the Triad.",
    website_url: "https://www.ncdoi.gov/consumers/medicare-and-seniors-health-insurance-information-program-shiip",
    phone: "336-721-3411",
    city: "Winston-Salem", source_name: "NC Department of Insurance" },
  { section: "INS", title: "Cumberland NC SHIIP Office — Medicare Counseling",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "SHIIP counselors based in Fayetteville providing free Medicare counseling to Fort Liberty community veterans and retirees.",
    website_url: "https://www.ncdoi.gov/consumers/medicare-and-seniors-health-insurance-information-program-shiip",
    phone: "910-484-0111",
    city: "Fayetteville", source_name: "NC Department of Insurance" },
  { section: "INS", title: "VFW Insurance Services — North Carolina",
    cat: "insurance", sub: "Life Insurance",
    desc: "VFW-endorsed term life, accident, and Medicare supplement coverage available to NC VFW members and their spouses.",
    website_url: "https://insurance.vfwmemberbenefits.org/",
    phone: "877-839-9621",
    city: undefined, source_name: "VFW Member Benefits" },

  // ==========================================================================
  // CRI — Crisis Help (5)
  // ==========================================================================
  { section: "CRI", title: "Trillium Mobile Crisis Team — Eastern NC Counties",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 mobile crisis response across 26 eastern NC counties. Veterans connected to local VA crisis resources after stabilization.",
    website_url: "https://www.trilliumhealthresources.org/",
    phone: "888-302-0738",
    city: undefined, source_name: "Trillium Health Resources" },
  { section: "CRI", title: "Vaya Mobile Crisis Team — Western NC Counties",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 mobile crisis response across 32 WNC counties including Asheville, Boone, Hickory. Coordinates with Charles George VAMC for veterans.",
    website_url: "https://www.vayahealth.com/",
    phone: "800-849-6127",
    city: undefined, source_name: "Vaya Health" },
  { section: "CRI", title: "Alliance Mobile Crisis Team — Triangle & Cumberland",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 mobile crisis response across the Triangle, Cumberland, and Johnston counties. Connects veterans to Durham VAMC follow-up.",
    website_url: "https://www.alliancehealthplan.org/",
    phone: "877-223-4617",
    city: undefined, source_name: "Alliance Health" },
  { section: "CRI", title: "Partners Mobile Crisis Team — Western Piedmont",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 mobile crisis services across Mecklenburg, Catawba, Burke, Cabarrus, and 9 other counties; veteran-aware response.",
    website_url: "https://providers.partnersbhm.org/",
    phone: "888-235-4673",
    city: undefined, source_name: "Partners Health Management" },
  { section: "CRI", title: "NAMI NC HelpLine — Statewide Mental Health Support",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "Free statewide mental health information, support, and referral helpline. Veteran callers connected to Veterans Crisis Line and local VA resources.",
    website_url: "https://naminc.org/",
    phone: "800-451-9682", address: "3540 Maybank Lane",
    city: "Raleigh", source_name: "NAMI North Carolina" },

  // ==========================================================================
  // FIN — Financial Help (5)
  // ==========================================================================
  { section: "FIN", title: "USA Cares — North Carolina Outreach",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Emergency financial assistance for post-9/11 service members, veterans, and families: rent, utilities, mortgage, and food.",
    website_url: "https://usacares.org/",
    phone: "800-773-0387",
    city: undefined, source_name: "USA Cares" },
  { section: "FIN", title: "WAGES — Wilson Area Community Action",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Wilson, Edgecombe, Greene, Nash, Pitt, Wayne CAA. Energy assistance, weatherization, Head Start, and emergency aid; veterans encouraged.",
    website_url: "https://www.wagesinc.org/",
    phone: "252-291-6262", address: "300 W Walnut Street",
    city: "Wilson", source_name: "WAGES" },
  { section: "FIN", title: "Total Action for Progress — NC Outreach",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Western NC community action agency offering housing, employment, and emergency financial help to qualifying low-income households including veterans.",
    website_url: "https://tapintohope.org/",
    phone: "540-345-6781",
    city: undefined, source_name: "Total Action for Progress" },
  { section: "FIN", title: "Habitat ReStore — Asheville (Veteran Discount)",
    cat: "financial", sub: "Nonprofit Financial Support",
    desc: "Habitat for Humanity ReStore in Asheville offering veteran discounts on home goods and building materials. Proceeds fund veteran builds.",
    website_url: "https://www.ashevillehabitat.org/restore",
    phone: "828-254-6706", address: "33 Meadow Road",
    city: "Asheville", source_name: "Asheville Area Habitat for Humanity" },

  // ==========================================================================
  // HOU — Housing (5)
  // ==========================================================================
  { section: "HOU", title: "VOA Carolinas SSVF Statewide — Rapid Rehousing",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Volunteers of America Carolinas operates Supportive Services for Veteran Families (SSVF) across most of NC. Rapid rehousing and homelessness prevention.",
    website_url: "https://www.voacarolinas.org/",
    phone: "704-372-0707", address: "5301 Wisconsin Avenue NW",
    city: "Charlotte", source_name: "Volunteers of America Carolinas" },
  { section: "HOU", title: "Habitat for Humanity Wake County — Veterans Build Program",
    cat: "housing", sub: "Home Ownership",
    desc: "Wake County Habitat dedicates builds to qualifying veteran families each year. Sweat-equity homeownership program with 0% mortgages.",
    website_url: "https://www.habitatwake.org/",
    phone: "919-833-1999", address: "2420 N Raleigh Boulevard",
    city: "Raleigh", source_name: "Habitat for Humanity of Wake County" },
  { section: "HOU", title: "Asheville Buncombe Community Christian Ministry — Veterans Restoration Quarters",
    cat: "housing", sub: "Transitional Housing",
    desc: "240-bed transitional housing facility exclusively serving veterans in Asheville with case management, substance recovery, and job training.",
    website_url: "https://abccm.org/programs/veterans/",
    phone: "828-259-5300", address: "1329 Tunnel Road",
    city: "Asheville", source_name: "ABCCM" },
  { section: "HOU", title: "Family Promise — Greater Greensboro",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Family Promise affiliate providing rotating shelter, case management, and housing search support for families with children. Veteran families welcome.",
    website_url: "https://familypromisegg.org/",
    phone: "336-273-5402",
    city: "Greensboro", source_name: "Family Promise of Greater Greensboro" },
  { section: "HOU", title: "Partnership to End Homelessness — Wake County (CoC Lead)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Wake County Continuum of Care lead agency. Coordinated entry, By-Name List for veterans, HMIS, and rapid rehousing oversight.",
    website_url: "https://www.partnershiptoendhomelessness.org/",
    phone: "919-727-0991",
    city: "Raleigh", source_name: "Partnership to End Homelessness" },

  // ==========================================================================
  // TRA — Transportation (5)
  // ==========================================================================
  { section: "TRA", title: "CATS Charlotte STS — Bus, Rail & ADA Paratransit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Charlotte Area Transit System fixed-route bus, light rail, and ADA paratransit (STS). Reduced fares for seniors, disabled veterans, and Medicare cardholders.",
    website_url: "https://www.ridetransit.org/",
    phone: "704-336-7433", address: "600 E 4th Street",
    city: "Charlotte", source_name: "Charlotte Area Transit System" },
  { section: "TRA", title: "Cape Fear DART Wilmington — ADA Paratransit",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "Wilmington-area ADA paratransit (DART) operated by Cape Fear Public Transportation Authority. Pre-scheduled curb-to-curb rides for qualifying veterans and disabled riders.",
    website_url: "https://www.wavetransit.com/dart-services/",
    phone: "910-202-2053",
    city: "Wilmington", source_name: "Cape Fear Public Transportation Authority" },
  { section: "TRA", title: "GREAT Greenville NC Transit — Fixed-Route & Paratransit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Greenville Reach Express Transit (GREAT): fixed-route bus and ADA paratransit. Free fares for active-duty military, reduced fares for seniors and disabled veterans.",
    website_url: "https://www.greenvillenc.gov/government/public-works/great",
    phone: "252-329-4035", address: "200 W 5th Street",
    city: "Greenville", source_name: "City of Greenville" },

  // ==========================================================================
  // LGL — Legal (4)
  // ==========================================================================
  { section: "LGL", title: "Legal Aid of North Carolina — Statewide Helpline",
    cat: "legal", sub: "Legal Aid",
    desc: "Statewide free civil legal help for low-income North Carolinians. Dedicated veterans intake line and dedicated Veterans Justice Outreach in Triangle.",
    website_url: "https://www.legalaidnc.org/",
    phone: "866-219-5262",
    city: undefined, source_name: "Legal Aid of North Carolina" },
  { section: "LGL", title: "NC Pro Bono Resource Center — Lawyer on the Line",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "NC Bar Association's Lawyer on the Line program connects qualifying veterans with free 30-minute consultations on civil matters.",
    website_url: "https://www.ncbar.org/lawyers/programs-initiatives/pro-bono-resource-center/",
    phone: "919-677-0561", address: "8000 Weston Parkway",
    city: "Cary", source_name: "North Carolina Bar Association" },
  { section: "LGL", title: "NC Justice Center — Veterans & Workers Project",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "NC Justice Center policy and direct-services advocacy on benefits denials, predatory lending, and consumer protection affecting veterans.",
    website_url: "https://www.ncjustice.org/",
    phone: "919-856-2570", address: "224 S Dawson Street",
    city: "Raleigh", source_name: "NC Justice Center" },

  // ==========================================================================
  // BEN — Benefits (4)
  // ==========================================================================
  { section: "BEN", title: "DAV NC — Department Service Office (Durham VAMC)",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "Disabled American Veterans NC department service officers based at Durham VAMC. Free claims and appeals representation.",
    website_url: "https://www.davnc.org/",
    phone: "919-286-6840", address: "508 Fulton Street",
    city: "Durham", source_name: "Disabled American Veterans" },
  { section: "BEN", title: "American Legion Department of NC — Service Office (Salisbury)",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "American Legion accredited service officers based at Salisbury VAMC. Free claims, appeals, and benefits navigation.",
    website_url: "https://nclegion.org/",
    phone: "704-633-1810", address: "1601 Brenner Avenue",
    city: "Salisbury", source_name: "American Legion Department of NC" },
  { section: "BEN", title: "NC4VETS Resource Guide — Statewide Hotline",
    cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation",
    desc: "NC DMVA's NC4VETS hotline and online resource guide. Free benefits screening, referrals, and crisis triage for NC veterans.",
    website_url: "https://www.milvets.nc.gov/services/nc4vets-resource-center",
    phone: "844-624-8387",
    city: undefined, source_name: "NC Department of Military and Veterans Affairs" },

  // ==========================================================================
  // REC — Recovery (5)
  // ==========================================================================
  { section: "REC", title: "Daymark Recovery Services — Statewide",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "NC's largest community mental health and substance use provider with 32 county clinics. Sliding-scale fees and veteran-friendly intake.",
    website_url: "https://daymarkrecovery.org/",
    phone: "866-275-9552",
    city: undefined, source_name: "Daymark Recovery Services" },
  { section: "REC", title: "Coastal Horizons Center — Wilmington",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "SE NC nonprofit providing substance use treatment, opioid treatment, and behavioral health services. Veterans encouraged to apply.",
    website_url: "https://www.coastalhorizons.org/",
    phone: "910-790-0187", address: "615 Shipyard Boulevard",
    city: "Wilmington", source_name: "Coastal Horizons Center" },
  { section: "REC", title: "RHA Health NC Statewide — Substance Use Treatment",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Statewide provider of substance use disorder treatment, including IOP, PHP, and recovery residences. Accepts Medicaid and TRICARE in many sites.",
    website_url: "https://www.rhahealthservices.org/",
    phone: "800-848-8898",
    city: undefined, source_name: "RHA Health Services" },
  { section: "REC", title: "Oxford House — North Carolina Recovery Residences",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "Self-run, self-supported recovery residences for men and women across NC. Veteran-friendly intake; pairs well with VA SUD treatment.",
    website_url: "https://www.oxfordhousenc.org/",
    phone: "910-235-3700",
    city: undefined, source_name: "Oxford House Inc" },
  { section: "REC", title: "Phoenix Counseling Center — Hickory (Catawba County)",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Western Piedmont substance use and mental health treatment provider. Sliding-scale, accepts Medicaid; veteran outreach available.",
    website_url: "https://www.phoenixcounselingcenter.org/",
    phone: "828-323-8260", address: "601 Belmont Drive",
    city: "Hickory", source_name: "Phoenix Counseling Center" },

  // ==========================================================================
  // HOSP — Major non-VA hospitals (8) — broader community resources
  // ==========================================================================
  { section: "HOSP", title: "Atrium Health — Carolinas Medical Center (Charlotte)",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Charlotte's largest hospital and Level I trauma center. Accepts TRICARE; offers veteran-aware specialty referrals via community care.",
    website_url: "https://atriumhealth.org/locations/detail/atrium-health-carolinas-medical-center",
    phone: "704-355-2000", address: "1000 Blythe Boulevard",
    city: "Charlotte", source_name: "Atrium Health" },
  { section: "HOSP", title: "Forsyth Medical Center Winston-Salem — Novant Triad Flagship",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Winston-Salem flagship hospital (Novant Health). Level II trauma; accepts TRICARE. Specialty care under VA Community Care Network for Triad veterans.",
    website_url: "https://www.novanthealth.org/forsyth-medical-center.aspx",
    phone: "336-718-5000", address: "3333 Silas Creek Parkway",
    city: "Winston-Salem", source_name: "Novant Health" },
  { section: "HOSP", title: "Duke University Hospital — Durham",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Academic medical center; Level I trauma. Accepts TRICARE; partners with Durham VAMC for cardiac surgery, transplant, and oncology referrals.",
    website_url: "https://www.dukehealth.org/hospitals/duke-university-hospital",
    phone: "919-684-8111", address: "2301 Erwin Road",
    city: "Durham", source_name: "Duke University Health System" },
  { section: "HOSP", title: "UNC Medical Center — Chapel Hill",
    cat: "healthcare", sub: "Specialty Care",
    desc: "UNC Health flagship; Level I trauma. Accepts TRICARE; specialty referrals for Triangle veterans through VA Community Care.",
    website_url: "https://www.uncmedicalcenter.org/",
    phone: "984-974-1000", address: "101 Manning Drive",
    city: "Chapel Hill", source_name: "UNC Health" },
  { section: "HOSP", title: "Cone Health — Moses H. Cone Memorial Hospital (Greensboro)",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Greensboro flagship hospital. Level II trauma; accepts TRICARE. Specialty referrals for Triad veterans under VA Community Care Network.",
    website_url: "https://www.conehealth.com/locations/the-moses-h.-cone-memorial-hospital/",
    phone: "336-832-7000", address: "1200 N Elm Street",
    city: "Greensboro", source_name: "Cone Health" },
  { section: "HOSP", title: "ECU Health Medical Center — Greenville (Pitt)",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Eastern NC's flagship academic hospital and Level I trauma center. Accepts TRICARE; partners with Greenville VA for specialty referrals.",
    website_url: "https://www.ecuhealth.org/locations/ecu-health-medical-center/",
    phone: "252-847-4100", address: "2100 Stantonsburg Road",
    city: "Greenville", source_name: "ECU Health" },
  { section: "HOSP", title: "Mission Hospital — Asheville",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Western NC's flagship hospital and only Level II trauma center. Accepts TRICARE; partners with Charles George VAMC for specialty referrals.",
    website_url: "https://missionhealth.org/our-locations/mission-hospital/",
    phone: "828-213-1111", address: "509 Biltmore Avenue",
    city: "Asheville", source_name: "HCA Healthcare / Mission Health" },
  { section: "HOSP", title: "New Hanover Regional Medical Center Wilmington — Novant SE NC Flagship",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Wilmington flagship hospital (Novant Health) and Level II trauma. Accepts TRICARE; specialty referrals for SE NC veterans through VA Community Care.",
    website_url: "https://www.novanthealth.org/new-hanover-regional-medical-center.aspx",
    phone: "910-667-7000", address: "2131 S 17th Street",
    city: "Wilmington", source_name: "Novant Health" },

  // ==========================================================================
  // CLN — FQHC clinics (8)
  // ==========================================================================
  { section: "CLN", title: "Piedmont Health Services — Carrboro Community Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC offering primary care, dental, behavioral health, and pharmacy on a sliding scale across the central Piedmont. Veterans welcome.",
    website_url: "https://piedmonthealth.org/",
    phone: "919-942-8741", address: "301 Lloyd Street",
    city: "Carrboro", source_name: "Piedmont Health Services" },
  { section: "CLN", title: "Lincoln Community Health Center — Durham",
    cat: "healthcare", sub: "Primary Care",
    desc: "Durham FQHC providing primary care, dental, behavioral health, and HIV services. Sliding-scale fees; veterans encouraged.",
    website_url: "https://www.lincolnchc.org/",
    phone: "919-956-4000", address: "1301 Fayetteville Street",
    city: "Durham", source_name: "Lincoln Community Health Center" },
  { section: "CLN", title: "CommWell Health — Newton Grove (Statewide HQ)",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC with 17 sites across eastern NC. Primary care, dental, behavioral health, OB/GYN, and migrant health. Sliding-scale fees.",
    website_url: "https://www.commwellhealth.org/",
    phone: "910-567-7800", address: "3331 Easy Street",
    city: "Newton Grove", source_name: "CommWell Health" },
  { section: "CLN", title: "Blue Ridge Health — Hendersonville (WNC)",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC system across 7 WNC counties. Primary care, dental, behavioral health, pediatrics, and pharmacy. Sliding-scale; veterans welcome.",
    website_url: "https://www.brchs.com/",
    phone: "828-696-9009", address: "2579 Chimney Rock Road",
    city: "Hendersonville", source_name: "Blue Ridge Health" },
  { section: "CLN", title: "Goshen Medical Center — Faison (Eastern NC)",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC with 32 sites across eastern NC. Primary care, dental, behavioral health, OB/GYN, and migrant health programs.",
    website_url: "https://www.goshenmedical.org/",
    phone: "910-267-4111", address: "208 Faison Highway",
    city: "Faison", source_name: "Goshen Medical Center" },
  { section: "CLN", title: "Cabarrus Community Health Centers — Concord",
    cat: "healthcare", sub: "Primary Care",
    desc: "Cabarrus County FQHC providing primary care and behavioral health. Sliding-scale fees; veterans and uninsured patients welcome.",
    website_url: "https://www.cabarrushealth.org/community-health-center",
    phone: "704-792-7700", address: "300 Mooresville Road",
    city: "Kannapolis", source_name: "Cabarrus Community Health Centers" },
  { section: "CLN", title: "MedNorth Health Center — Wilmington",
    cat: "healthcare", sub: "Primary Care",
    desc: "Wilmington FQHC providing primary care, dental, behavioral health, and pharmacy. Sliding-scale fees; veteran outreach.",
    website_url: "https://www.mednorthhealth.org/",
    phone: "910-343-0270", address: "925 N 4th Street",
    city: "Wilmington", source_name: "MedNorth Health Center" },
  { section: "CLN", title: "Greene County Health Care — Snow Hill (Eastern NC)",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC with multiple sites across Greene, Lenoir, Pitt, and Beaufort counties. Primary care, dental, behavioral health, and migrant programs.",
    website_url: "https://www.gchcinc.org/",
    phone: "252-747-8162", address: "302 SE 2nd Street",
    city: "Snow Hill", source_name: "Greene County Health Care" },

  // ==========================================================================
  // SHL — Shelters (8)
  // ==========================================================================
  { section: "SHL", title: "Charlotte Family Housing — Bridge Resource Center",
    cat: "housing", sub: "Transitional Housing",
    desc: "Charlotte nonprofit providing transitional and permanent supportive housing for working families experiencing homelessness. Veteran families welcome.",
    website_url: "https://www.charlottefamilyhousing.org/",
    phone: "704-335-5488", address: "601 E 5th Street, Suite 350",
    city: "Charlotte", source_name: "Charlotte Family Housing" },
  { section: "SHL", title: "Raleigh Salvation Army Center of Hope — Family Shelter",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Raleigh family emergency shelter and case management. Coordinates with VA homeless outreach for SSVF eligibility.",
    website_url: "https://salvationarmycarolinas.org/raleigh/",
    phone: "919-865-1900", address: "215 S Person Street",
    city: "Raleigh", source_name: "The Salvation Army" },
  { section: "SHL", title: "South Wilmington Shelter — Good Shepherd Center Annex",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Wilmington's low-barrier emergency shelter with 100 beds. Veteran outreach and HUD-VASH coordination.",
    website_url: "https://www.goodshepherdwilmington.org/shelter/",
    phone: "910-763-4424", address: "611 Martin Street",
    city: "Wilmington", source_name: "Good Shepherd Center" },
  { section: "SHL", title: "Hope House — Asheville (Veteran Transitional Housing)",
    cat: "housing", sub: "Transitional Housing",
    desc: "Asheville transitional housing for women and families exiting homelessness. Coordinates with HUD-VASH and SSVF for veteran families.",
    website_url: "https://homewardboundwnc.org/programs/",
    phone: "828-258-1695",
    city: "Asheville", source_name: "Homeward Bound of WNC" },
  { section: "SHL", title: "Family Promise Greater Charlotte — Family Shelter Network",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Family Promise Charlotte affiliate. Rotating congregational shelter, day center, and rapid rehousing for families with children.",
    website_url: "https://familypromisecharlotte.org/",
    phone: "704-365-0027", address: "1301 W Sugar Creek Road",
    city: "Charlotte", source_name: "Family Promise of Greater Charlotte" },
  { section: "SHL", title: "Salisbury Rowan Salvation Army — Center of Hope",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Salisbury emergency shelter and case management; coordinates with Salisbury VAMC HUD-VASH and homeless outreach team.",
    website_url: "https://salvationarmycarolinas.org/salisbury/",
    phone: "704-633-4961", address: "620 W Innes Street",
    city: "Salisbury", source_name: "The Salvation Army" },
  { section: "SHL", title: "Greensboro Salvation Army — Center of Hope (Family Shelter)",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Greensboro family shelter and emergency case management; coordinates with Servant Center for veteran transitional housing.",
    website_url: "https://salvationarmycarolinas.org/greensboro/",
    phone: "336-274-7732", address: "1311 S Eugene Street",
    city: "Greensboro", source_name: "The Salvation Army" },
  { section: "SHL", title: "Hickory Soup Kitchen — Greater Hickory Cooperative Christian Ministry",
    cat: "food-assistance", sub: "Community Kitchens",
    desc: "Hickory cooperative providing meals, food pantry, emergency financial assistance, and shelter coordination. Veterans welcome.",
    website_url: "https://www.gh-ccm.org/",
    phone: "828-327-0979", address: "31 1st Street SE",
    city: "Hickory", source_name: "GH-CCM" },

  // ==========================================================================
  // FOOD — Food banks (5)
  // ==========================================================================
  { section: "FOOD", title: "Central & Eastern NC Food Bank Raleigh HQ — Regional Hub",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Food Bank of Central & Eastern NC: largest food bank in NC, serving 34 counties via 800+ partner agencies. SNAP outreach and free military/veteran food distributions.",
    website_url: "https://foodbankcenc.org/",
    phone: "919-875-0707", address: "1924 Capital Boulevard",
    city: "Raleigh", source_name: "Food Bank of Central & Eastern NC" },

  // ==========================================================================
  // CAA — Community action agencies (5)
  // ==========================================================================
  { section: "CAA", title: "Wake Tech Community College — Career & Technical Education (CAP)",
    cat: "education", sub: "Continuing Education",
    desc: "Wake Tech career and technical programs subsidized for low-income workers, including dislocated veterans. WIOA and GI Bill accepted.",
    website_url: "https://www.waketech.edu/programs-courses/career-technical",
    phone: "919-866-5000", address: "9101 Fayetteville Road",
    city: "Raleigh", source_name: "Wake Technical Community College" },
  { section: "CAA", title: "EnergyUnited — LIEAP Energy Assistance (Statewide Co-op)",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Statewide low-income energy assistance program coordinated through county DSS offices. Veterans encouraged to apply each fall.",
    website_url: "https://www.energyunited.com/",
    phone: "800-522-3793",
    city: undefined, source_name: "EnergyUnited" },
  { section: "CAA", title: "Cabarrus County Community Action — Concord",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Cabarrus County CAA. Energy assistance, weatherization, Head Start, and emergency aid for qualifying low-income households including veterans.",
    website_url: "https://www.cabarruscoa.org/",
    phone: "704-786-1755", address: "3500 Old Charlotte Road",
    city: "Concord", source_name: "Cabarrus County Community Action" },
  { section: "CAA", title: "Burke County Community Action — Morganton",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Western Piedmont CAA serving Burke, Catawba, and surrounding counties. Energy, housing, weatherization, and Head Start; veterans served.",
    website_url: "https://burkecap.com/",
    phone: "828-438-6255", address: "204 White Street SW",
    city: "Morganton", source_name: "Burke County Community Action" },
  { section: "CAA", title: "Choanoke Area Development Association — Northeastern NC CAA",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "CADA serves Bertie, Halifax, Hertford, and Northampton counties. Energy assistance, weatherization, and senior programs; veterans welcome.",
    website_url: "https://www.cadainc.org/",
    phone: "252-539-4155", address: "1209 Allen Street",
    city: "Rich Square", source_name: "Choanoke Area Development Association" },

  // ==========================================================================
  // CHU — Interfaith outreach (5)
  // ==========================================================================
  { section: "CHU", title: "Catholic Charities Diocese of Charlotte — Western NC Region",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Catholic Charities Charlotte: emergency assistance, refugee resettlement, counseling, food pantry, and pregnancy support. Veterans welcome.",
    website_url: "https://ccdoc.org/",
    phone: "704-370-3262", address: "1123 S Church Street",
    city: "Charlotte", source_name: "Diocese of Charlotte" },
  { section: "CHU", title: "Catholic Charities Diocese of Raleigh — Eastern NC Region",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Catholic Charities Raleigh: emergency assistance, immigration services, counseling, and food pantry across 54 eastern NC counties.",
    website_url: "https://catholiccharitiesraleigh.org/",
    phone: "919-790-8533", address: "7200 Stonehenge Drive",
    city: "Raleigh", source_name: "Diocese of Raleigh" },
  { section: "CHU", title: "Lutheran Services Carolinas — Statewide",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "LSC operates senior care, refugee resettlement, foster care, and disability services across NC and SC. Veteran-aware programs at multiple sites.",
    website_url: "https://www.lscarolinas.net/",
    phone: "800-839-0093", address: "1801 E Innes Street",
    city: "Salisbury", source_name: "Lutheran Services Carolinas" },
  { section: "CHU", title: "Jewish Family Services — Charlotte",
    cat: "family-support", sub: "Family Counseling",
    desc: "Charlotte JFS counseling, food pantry, financial assistance, and senior services. Veterans and military families welcome regardless of faith.",
    website_url: "https://www.jfscharlotte.org/",
    phone: "704-364-6594", address: "5007 Providence Road",
    city: "Charlotte", source_name: "Jewish Family Services Charlotte" },
  { section: "CHU", title: "Episcopal Diocese of NC — Outreach Ministries",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Diocese of NC outreach grants funding parish ministries serving veterans, refugees, and food-insecure neighbors across central NC.",
    website_url: "https://episdionc.org/",
    phone: "919-834-7474", address: "200 W Morgan Street",
    city: "Raleigh", source_name: "Episcopal Diocese of NC" },

  // ==========================================================================
  // EOL — Hospice (4)
  // ==========================================================================
  { section: "EOL", title: "Four Seasons Compassion for Life — Hendersonville",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "WNC hospice and palliative care nonprofit serving 11 mountain counties. We Honor Veterans Level 5 partner; accepts VA hospice benefit.",
    website_url: "https://www.fourseasonscfl.org/",
    phone: "828-692-6178", address: "571 S Allen Road",
    city: "Flat Rock", source_name: "Four Seasons Compassion for Life" },
  { section: "EOL", title: "Hospice & Palliative Care of Greensboro",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Triad hospice nonprofit. We Honor Veterans Level 4 partner; accepts VA hospice benefit and offers grief support to veteran families.",
    website_url: "https://www.hospicegso.org/",
    phone: "336-621-2500", address: "2500 Summit Avenue",
    city: "Greensboro", source_name: "Hospice & Palliative Care of Greensboro" },
  { section: "EOL", title: "Liberty HomeCare & Hospice — Wilmington",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "SE NC hospice and home-care provider with 19 NC offices. We Honor Veterans partner; accepts VA hospice benefit and TRICARE.",
    website_url: "https://www.libertyhomecare.com/",
    phone: "910-251-2929", address: "5725 Oleander Drive",
    city: "Wilmington", source_name: "Liberty HomeCare & Hospice" },

  // ==========================================================================
  // CAR — Caregiver support (4)
  // ==========================================================================
  { section: "CAR", title: "Centralina Area Agency on Aging — Caregiver Support",
    cat: "family-support", sub: "Caregiver Support",
    desc: "Centralina AAA Family Caregiver Support Program. Information, respite vouchers, and counseling for unpaid caregivers across 9 Charlotte-region counties.",
    website_url: "https://www.centralina.org/area-agency-on-aging/",
    phone: "704-372-2416", address: "10735 David Taylor Drive",
    city: "Charlotte", source_name: "Centralina Council of Governments" },
  { section: "CAR", title: "Land of Sky Regional Council — Caregiver Resource Center (Asheville)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "Land of Sky AAA Family Caregiver Support Program serving Buncombe, Henderson, Madison, and Transylvania. Info, respite, and support groups.",
    website_url: "https://www.landofsky.org/aaa.html",
    phone: "828-251-6622", address: "339 New Leicester Highway",
    city: "Asheville", source_name: "Land of Sky Regional Council" },
  { section: "CAR", title: "Triangle J Council of Governments — Family Caregiver Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "Triangle J AAA Family Caregiver Support Program serving Wake, Durham, Orange, Chatham, Johnston, Lee, and Moore. Respite vouchers and counseling.",
    website_url: "https://www.tjcog.org/family-caregiver-support",
    phone: "919-549-0551", address: "4307 Emperor Boulevard, Suite 110",
    city: "Durham", source_name: "Triangle J Council of Governments" },
  { section: "CAR", title: "Project COPE — NC Family Caregiver Coalition",
    cat: "family-support", sub: "Caregiver Support",
    desc: "Statewide coalition of family caregiver organizations sharing resources, training, and policy advocacy. Useful starting point for veteran caregiver families.",
    website_url: "https://www.ncfamilycaregivers.org/",
    phone: "919-733-0440",
    city: undefined, source_name: "NC Division of Aging and Adult Services" },
];

(async () => {
  await runSeed(ROWS, {
    state: STATE,
    commit: COMMIT,
    scriptName: "seed-nc-phase4 (Gold Standard Completion)",
    sectionLabels,
  });
})();
