/**
 * GA Phase 4 — Gold Standard Completion (89 rows committed 2026-04-24)
 *
 * Founder ask: take Georgia from 351 rows to 430-500, fill all remaining
 * geographic gaps + weak categories so Georgia becomes the flagship template
 * state before Florida starts.
 *
 * Final committed counts (after dry-run collision resolution dropped 8 true
 * duplicates that already existed in DB and renamed 9 near-dup titles):
 *
 * Geographic gap fill (48 rows, 5 sections):
 *   NGA — North GA mountains + NW GA  (14): Dahlonega, Demorest, Cleveland,
 *         Dalton, Chatsworth, Rome, Cartersville
 *   COA — Coast (10): Brunswick, Kingsland, Ludowici, Darien
 *   FST — Fort Stewart corridor (8): Hinesville, Richmond Hill
 *   STB — Statesboro (6)
 *   DUB — Dublin / Central GA (10): Dublin, Eastman, Sandersville, Milledgeville
 *         (Carl Vinson VAMC dropped — already in DB)
 *
 * Weak category fill (41 rows, 6 sections):
 *   MHE — Mental Health (4) — NAMI GA, Skyland Trail, Behavioral Health Link,
 *         Aspire BH (Ridgeview, CHRIS 180, Anchor Hospital, River Edge dropped
 *         as exact / near dups of existing rows)
 *   INS — Insurance (8) — 6 regional GeorgiaCares SHIP sites + AAFMAA + USFHP
 *   BEN — Benefits / VSO orgs (8) — AMVETS, American Legion, Marine Corps
 *         League, MOPH, MOAA, VVA, NABVETS, CVMA (VFW Dept of GA + IAVA
 *         dropped — already in DB)
 *   FIN — Financial Help (5) — USA Cares, CSRA Economic Opp, Coastal CAA,
 *         Ninth District Opp, Action Ministries (Operation Homefront dropped —
 *         already in DB)
 *   DIS — Disabled Veterans (8) — Shepherd Center, SHARE Military, Warm
 *         Springs, PVA Mid-South, disABILITY LINK, LIFE Inc, Walton Options,
 *         SILC GA
 *   TRA — Transportation (8) — 4 regional 5311 RC transit + VTS Augusta +
 *         Glynn senior + Hall County + Cherokee Area
 *
 * Naming rule for parent-org rows (Phase 4 lesson — apply to FL/TN/VA/TX):
 *   `normalizeTitle()` in rollout-engine strips text after the first em-dash
 *   or hyphen and removes parentheses. Therefore two rows under the same
 *   parent org will collide as near-dups unless the text BEFORE the dash is
 *   distinct. Example: `"Coastal Regional Commission — Coast Public Transit"`
 *   collided with `"Coastal Regional Commission — GeorgiaCares SHIP"`. Fix:
 *   put the unique program identifier in front of the dash, e.g.
 *   `"Coastal GeorgiaCares SHIP Counseling Site (Brunswick)"`.
 *
 * Run:
 *   tsx scripts/seed-ga-phase4.ts            # dry-run
 *   tsx scripts/seed-ga-phase4.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const STATE = "GA";
const COMMIT = process.argv.includes("--commit");

const SECTION_LABELS: Record<string, string> = {
  NGA: "N GA / NW GA",
  COA: "Coast",
  FST: "Fort Stewart",
  STB: "Statesboro",
  DUB: "Dublin / Central",
  MHE: "Mental Health",
  INS: "Insurance",
  BEN: "Benefits orgs",
  FIN: "Financial Help",
  DIS: "Disabled Vets",
  TRA: "Transportation",
};

const ROWS: SeedRow[] = [
  // ===========================================================================
  // NGA — North GA mountains + NW GA  (14 rows)
  // ===========================================================================
  { section: "NGA", title: "University of North Georgia Dahlonega Campus — Veteran Student Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "UNG's main historic campus military & veteran services in Dahlonega. GI Bill certification, vet lounge, SVA chapter, senior military college status. Distinct from the Gainesville campus office.",
    website_url: "https://ung.edu/military-veteran-services", phone: "706-867-2768",
    address: "82 College Circle", city: "Dahlonega", zip: "30597",
    latitude: 34.5295, longitude: -83.9851,
    source_name: "University of North Georgia", source_type: "education" },
  { section: "NGA", title: "Lumpkin County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Lumpkin County VSO. Helps veterans file VA claims, access state benefits, and obtain DD-214 records. Serves Dahlonega and the North Georgia mountains.",
    website_url: "https://www.lumpkincounty.gov", phone: "706-864-3742",
    address: "99 Courthouse Hill", city: "Dahlonega", zip: "30533",
    latitude: 34.5316, longitude: -83.9849,
    source_name: "Lumpkin County Government", source_type: "government" },
  { section: "NGA", title: "Habersham Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "NE Georgia mountain region community hospital. Primary care, ER, specialty services. Serves veterans across Habersham, White, Stephens, and surrounding counties.",
    website_url: "https://www.habershammedical.com", phone: "706-754-2161",
    address: "541 Historic Highway 441", city: "Demorest", zip: "30535",
    latitude: 34.5687, longitude: -83.5404,
    source_name: "Habersham Medical Center", source_type: "nonprofit" },
  { section: "NGA", title: "White County Senior Services",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "White County senior center serving Cleveland and the North Georgia mountains. Lunch, activities, transportation referrals, social programs. Veterans welcome.",
    website_url: "https://www.whitecounty.net", phone: "706-865-3225",
    address: "1239 Helen Highway", city: "Cleveland", zip: "30528",
    latitude: 34.5912, longitude: -83.7649,
    source_name: "White County Government", source_type: "government" },
  { section: "NGA", title: "Hamilton Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Largest hospital in NW Georgia. 282-bed acute care, ER, surgery, cardiology, oncology. Serves veterans across Whitfield, Murray, Gordon counties.",
    website_url: "https://www.hamiltonhealth.com", phone: "706-272-6000",
    address: "1200 Memorial Drive", city: "Dalton", zip: "30720",
    latitude: 34.7651, longitude: -84.9789,
    source_name: "Hamilton Medical Center", source_type: "nonprofit" },
  { section: "NGA", title: "Whitfield County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Whitfield County VSO. Local point of contact for filing VA disability claims, pension applications, and state veterans benefits in the Dalton area.",
    website_url: "https://www.whitfieldcountyga.com", phone: "706-275-7470",
    address: "301 W Crawford Street", city: "Dalton", zip: "30720",
    latitude: 34.7698, longitude: -84.9706,
    source_name: "Whitfield County Government", source_type: "government" },
  { section: "NGA", title: "Murray County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Murray County VSO. Veteran benefits filing, claims assistance, and DD-214 records help for residents of Chatsworth and surrounding NW Georgia.",
    website_url: "https://www.murraycountyga.org", phone: "706-695-2413",
    address: "121 N 4th Avenue", city: "Chatsworth", zip: "30705",
    latitude: 34.7670, longitude: -84.7702,
    source_name: "Murray County Government", source_type: "government" },
  { section: "NGA", title: "Northwest Georgia Workforce Development Board",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "WIOA workforce board for 15 NW Georgia counties. Veteran priority of service, DVOP/LVER referrals, on-the-job training, vocational ed scholarships.",
    website_url: "https://www.nwgworkforce.org", phone: "706-272-2300",
    address: "503 W Waugh Street", city: "Dalton", zip: "30720",
    latitude: 34.7672, longitude: -84.9793,
    source_name: "Northwest Georgia Regional Commission", source_type: "government" },
  { section: "NGA", title: "Berry College — Veteran and Military Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "Berry College's veteran services office. GI Bill processing, VA Yellow Ribbon school, student veteran lounge, SVA chapter on the world's largest college campus.",
    website_url: "https://www.berry.edu/admissions/transfer/military",
    phone: "706-236-2215",
    address: "2277 Martha Berry Highway NW", city: "Rome", zip: "30149",
    latitude: 34.2820, longitude: -85.1808,
    source_name: "Berry College", source_type: "education" },
  { section: "NGA", title: "AdventHealth Redmond",
    cat: "healthcare", sub: "Primary Care",
    desc: "230-bed regional hospital serving Floyd, Polk, Bartow, Chattooga, Walker counties. ER, cardiology, surgery, cancer care. Accepts VA Community Care referrals.",
    website_url: "https://www.adventhealth.com/hospital/adventhealth-redmond",
    phone: "706-291-0291",
    address: "501 Redmond Road NW", city: "Rome", zip: "30165",
    latitude: 34.2674, longitude: -85.1945,
    source_name: "AdventHealth", source_type: "nonprofit" },
  { section: "NGA", title: "Floyd County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Floyd County VSO in Rome. Helps veterans navigate VA disability claims, pension benefits, and state veterans programs across NW Georgia.",
    website_url: "https://www.floydcountyga.gov", phone: "706-291-5163",
    address: "12 East 4th Avenue", city: "Rome", zip: "30161",
    latitude: 34.2563, longitude: -85.1648,
    source_name: "Floyd County Government", source_type: "government" },
  { section: "NGA", title: "Highland Rivers Behavioral Health — Headquarters",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Community Service Board covering 13 NW Georgia counties. Outpatient counseling, psychiatric medication management, substance use treatment, intensive outpatient. Veterans accepted on sliding scale.",
    website_url: "https://www.highlandrivers.org", phone: "770-387-3403",
    address: "1110 Bone Drive", city: "Cartersville", zip: "30120",
    latitude: 34.1804, longitude: -84.7776,
    source_name: "Highland Rivers Behavioral Health", source_type: "nonprofit" },
  { section: "NGA", title: "Bartow County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Bartow County VSO in Cartersville. VA claims filing, pension applications, military records help, and state benefits navigation for NW Georgia veterans.",
    website_url: "https://www.bartowcountyga.gov", phone: "770-387-5170",
    address: "135 W Cherokee Avenue", city: "Cartersville", zip: "30120",
    latitude: 34.1648, longitude: -84.8009,
    source_name: "Bartow County Government", source_type: "government" },
  { section: "NGA", title: "Etowah Valley Habitat for Humanity",
    cat: "housing", sub: "Home Ownership Programs",
    desc: "Habitat affiliate serving Bartow County. Builds & rehabs homes for low-income families including veterans. ReStore in Cartersville funds the program.",
    website_url: "https://www.etowahvalleyhabitat.org", phone: "770-607-0029",
    address: "111 N Wall Street", city: "Cartersville", zip: "30120",
    latitude: 34.1657, longitude: -84.8001,
    source_name: "Habitat for Humanity", source_type: "nonprofit" },

  // ===========================================================================
  // COA — Coast (10 rows): Brunswick, St. Marys, Kingsland, Ludowici, Darien
  // ===========================================================================
  { section: "COA", title: "Glynn County Government — Veterans Affairs",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Glynn County VSO in Brunswick. Free help filing VA disability claims, pension applications, DD-214 records, and Georgia state benefits for coastal veterans.",
    website_url: "https://www.glynncounty.org", phone: "912-554-7480",
    address: "1725 Reynolds Street", city: "Brunswick", zip: "31520",
    latitude: 31.1593, longitude: -81.4937,
    source_name: "Glynn County Government", source_type: "government" },
  { section: "COA", title: "Brunswick VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Brunswick Community-Based Outpatient Clinic, part of the Charleston VA Health Care System. Primary care, mental health, telehealth for coastal Georgia veterans.",
    website_url: "https://www.va.gov/charleston-health-care/locations/brunswick-va-clinic/",
    phone: "912-261-2355",
    address: "1111 Glynco Parkway", city: "Brunswick", zip: "31525",
    latitude: 31.2197, longitude: -81.4661,
    source_name: "Department of Veterans Affairs", source_type: "government" },
  { section: "COA", title: "Family Promise of the Golden Isles",
    cat: "housing", sub: "Emergency Housing",
    desc: "Brunswick-area emergency shelter and case management for families with children, including veteran families. Day center, transitional housing, employment support.",
    website_url: "https://www.familypromisegi.org", phone: "912-280-9075",
    address: "1416 Reynolds Street", city: "Brunswick", zip: "31520",
    latitude: 31.1532, longitude: -81.4925,
    source_name: "Family Promise", source_type: "nonprofit" },
  { section: "COA", title: "The Salvation Army of Brunswick",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Coastal Georgia Salvation Army Service Center. Emergency utility assistance, rent help, food pantry, disaster relief. Serves veterans across Glynn County.",
    website_url: "https://southernusa.salvationarmy.org/brunswick", phone: "912-265-9381",
    address: "1620 Reynolds Street", city: "Brunswick", zip: "31520",
    latitude: 31.1561, longitude: -81.4922,
    source_name: "The Salvation Army", source_type: "nonprofit" },
  { section: "COA", title: "Magnolia House of the Golden Isles",
    cat: "housing", sub: "Transitional Housing",
    desc: "Brunswick transitional housing for women in recovery, including women veterans. Long-term sober-living residence with case management and employment support.",
    website_url: "https://www.magnoliahousegi.org", phone: "912-265-3334",
    address: "1822 Albany Street", city: "Brunswick", zip: "31520",
    latitude: 31.1586, longitude: -81.4995,
    source_name: "Magnolia House", source_type: "nonprofit" },
  { section: "COA", title: "Camden County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Camden County VSO in Kingsland, near Naval Submarine Base Kings Bay. Helps active duty, retirees, and veterans file VA claims and access state benefits.",
    website_url: "https://www.camdencountyga.gov", phone: "912-576-3247",
    address: "200 East 4th Street", city: "Kingsland", zip: "31548",
    latitude: 30.7997, longitude: -81.6904,
    source_name: "Camden County Government", source_type: "government" },
  { section: "COA", title: "Naval Submarine Base Kings Bay — Fleet & Family Support Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fleet & Family Support Center at NSB Kings Bay. Counseling, financial readiness, employment, deployment & relocation support, sexual assault prevention. Active duty and retiree families.",
    website_url: "https://cnrse.cnic.navy.mil/Installations/NSB-Kings-Bay/Family-Readiness/Fleet-and-Family-Support-Program/",
    phone: "912-573-4512",
    address: "1063 USS Tennessee Avenue", city: "Kingsland", zip: "31547",
    latitude: 30.7945, longitude: -81.5293,
    source_name: "U.S. Navy", source_type: "military" },
  { section: "COA", title: "Coastal Georgia Health District — Public Health",
    cat: "healthcare", sub: "Preventive Care & Wellness",
    desc: "Georgia Department of Public Health District 9-1, covering 8 coastal counties. Immunizations, women's health, WIC, environmental health. Veteran-friendly low-cost services.",
    website_url: "https://gachd.org", phone: "912-264-3961",
    address: "127 F Street", city: "Brunswick", zip: "31520",
    latitude: 31.1488, longitude: -81.4921,
    source_name: "Georgia Department of Public Health", source_type: "government" },
  { section: "COA", title: "Long County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Long County VSO in Ludowici, near Fort Stewart. Veteran claims filing, pension and disability applications, military records assistance for rural coastal Georgia.",
    website_url: "https://www.longcountyga.com", phone: "912-545-2238",
    address: "459 South McDonald Street", city: "Ludowici", zip: "31316",
    latitude: 31.7088, longitude: -81.7448,
    source_name: "Long County Government", source_type: "government" },
  { section: "COA", title: "McIntosh County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "McIntosh County VSO in Darien. Free claims filing assistance, DD-214 retrieval, and Georgia state veterans benefits navigation for coastal residents.",
    website_url: "https://www.mcintoshcountyga.com", phone: "912-437-6671",
    address: "1200 N Way", city: "Darien", zip: "31305",
    latitude: 31.3705, longitude: -81.4334,
    source_name: "McIntosh County Government", source_type: "government" },

  // ===========================================================================
  // FST — Fort Stewart corridor (8 rows): Hinesville, Richmond Hill
  // ===========================================================================
  { section: "FST", title: "Liberty County Government — Veterans Affairs",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Liberty County VSO in Hinesville, supporting Fort Stewart soldiers, retirees, and veterans. Free VA claims filing, pension help, DD-214 retrieval, state benefits.",
    website_url: "https://www.libertycountyga.com", phone: "912-368-2280",
    address: "100 Main Street", city: "Hinesville", zip: "31313",
    latitude: 31.8473, longitude: -81.5965,
    source_name: "Liberty County Government", source_type: "government" },
  { section: "FST", title: "Liberty Regional Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Hinesville community hospital. ER, primary care, surgery, women's health, cardiology. Serves Liberty County and the Fort Stewart military community.",
    website_url: "https://www.libertyregional.org", phone: "912-369-9400",
    address: "462 East G Street", city: "Hinesville", zip: "31313",
    latitude: 31.8385, longitude: -81.5901,
    source_name: "Liberty Regional Medical Center", source_type: "nonprofit" },
  { section: "FST", title: "Fort Stewart — Army Community Service",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fort Stewart ACS. Soldier and family readiness, financial counseling, EFMP, employment readiness, relocation, deployment, sexual assault prevention, victim advocacy.",
    website_url: "https://stewart.armymwr.com/categories/army-community-service",
    phone: "912-767-5058",
    address: "100 W Bultman Avenue, Building 87", city: "Hinesville", zip: "31314",
    latitude: 31.8693, longitude: -81.6093,
    source_name: "U.S. Army Garrison Fort Stewart", source_type: "military" },
  { section: "FST", title: "Hinesville VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Hinesville Community-Based Outpatient Clinic, part of the Charleston VA Health Care System. Primary care, mental health, telehealth for Fort Stewart corridor veterans.",
    website_url: "https://www.va.gov/charleston-health-care/locations/hinesville-va-clinic/",
    phone: "912-920-0214",
    address: "500 East Oglethorpe Highway", city: "Hinesville", zip: "31313",
    latitude: 31.8398, longitude: -81.5923,
    source_name: "Department of Veterans Affairs", source_type: "government" },
  { section: "FST", title: "Liberty County Family YMCA",
    cat: "community-support", sub: "Family-Friendly Veteran Activities",
    desc: "Hinesville YMCA serving the Fort Stewart military community. Military membership discounts, youth sports, swim lessons, childcare, family events.",
    website_url: "https://www.ymcacoastalga.org/locations/liberty-county-family-ymca/",
    phone: "912-368-9622",
    address: "201 Mary Lou Drive", city: "Hinesville", zip: "31313",
    latitude: 31.8454, longitude: -81.6081,
    source_name: "YMCA of Coastal Georgia", source_type: "nonprofit" },
  { section: "FST", title: "Bryan County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Bryan County VSO in Richmond Hill. Free assistance filing VA claims, pension applications, military records, state veterans benefits. Serves Fort Stewart-area retirees.",
    website_url: "https://www.bryancountyga.gov", phone: "912-756-2434",
    address: "151 South Main Street", city: "Richmond Hill", zip: "31324",
    latitude: 31.9335, longitude: -81.3098,
    source_name: "Bryan County Government", source_type: "government" },
  { section: "FST", title: "Liberty Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Hinesville public bus system. Fixed-route service connecting downtown, Fort Stewart, residential neighborhoods, medical facilities. Reduced fares for seniors and disabled veterans.",
    website_url: "https://www.cityofhinesville.org/152/Liberty-Transit",
    phone: "912-877-4147",
    address: "100 East M.L. King Jr. Drive", city: "Hinesville", zip: "31313",
    latitude: 31.8470, longitude: -81.5963,
    source_name: "City of Hinesville", source_type: "government" },
  { section: "FST", title: "Coastal Pines Technical College — Liberty Campus",
    cat: "education", sub: "Technical Colleges",
    desc: "Liberty County campus of Coastal Pines Tech. Welding, HVAC, criminal justice, allied health, business — short, GI Bill-eligible technical programs near Fort Stewart.",
    website_url: "https://www.coastalpines.edu/campuses/liberty-campus/",
    phone: "912-408-3024",
    address: "1407 East Oglethorpe Highway", city: "Hinesville", zip: "31313",
    latitude: 31.8403, longitude: -81.5760,
    source_name: "Technical College System of Georgia", source_type: "education" },

  // ===========================================================================
  // STB — Statesboro (6 rows)
  // ===========================================================================
  { section: "STB", title: "Bulloch County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Bulloch County VSO in Statesboro. Free help filing VA disability claims, pension applications, DD-214 records, and Georgia state benefits for SE Georgia veterans.",
    website_url: "https://www.bullochcounty.net", phone: "912-489-2128",
    address: "115 North Main Street", city: "Statesboro", zip: "30458",
    latitude: 32.4488, longitude: -81.7831,
    source_name: "Bulloch County Government", source_type: "government" },
  { section: "STB", title: "Georgia Southern University Statesboro Campus — Office of Military and Veteran Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "Georgia Southern's flagship Statesboro-campus military & veteran services. GI Bill certification, VA Yellow Ribbon, vet success on campus counselor, SVA chapter, military lounge. Distinct from the Armstrong / Savannah campus office.",
    website_url: "https://www.georgiasouthern.edu/military",
    phone: "912-478-1909",
    address: "1332 Southern Drive", city: "Statesboro", zip: "30458",
    latitude: 32.4218, longitude: -81.7829,
    source_name: "Georgia Southern University", source_type: "education" },
  { section: "STB", title: "Statesboro VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Statesboro Community-Based Outpatient Clinic. Primary care, mental health, telehealth for SE Georgia veterans. Part of Charleston VA Health Care System.",
    website_url: "https://www.va.gov/charleston-health-care/locations/statesboro-va-clinic/",
    phone: "912-541-7575",
    address: "2 Pine Street", city: "Statesboro", zip: "30458",
    latitude: 32.4557, longitude: -81.7732,
    source_name: "Department of Veterans Affairs", source_type: "government" },
  { section: "STB", title: "East Georgia Regional Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "150-bed acute-care hospital serving Bulloch and surrounding SE Georgia counties. ER, surgery, cardiology, women's health. Accepts VA Community Care referrals.",
    website_url: "https://www.eastgeorgiaregional.com", phone: "912-486-1000",
    address: "1499 Fair Road", city: "Statesboro", zip: "30458",
    latitude: 32.4254, longitude: -81.7997,
    source_name: "HCA Healthcare", source_type: "for-profit" },
  { section: "STB", title: "Bulloch County Senior Citizens Center",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "Bulloch County senior center. Lunch, fitness, day trips, health screenings, tax counseling, social programs for adults 55+. Veteran-friendly with monthly veteran meetups.",
    website_url: "https://www.bullochcounty.net/senior-citizens-center",
    phone: "912-764-5316",
    address: "510 South College Street", city: "Statesboro", zip: "30458",
    latitude: 32.4451, longitude: -81.7855,
    source_name: "Bulloch County Government", source_type: "government" },
  { section: "STB", title: "Open Hearts Community Mission",
    cat: "food-assistance", sub: "Community Kitchens",
    desc: "Statesboro free community meal program serving the homeless and food-insecure, including veterans. Daily hot meals, food pantry, clothing closet, case management referrals.",
    website_url: "https://www.openheartscommunitymission.org", phone: "912-225-1834",
    address: "26 East Vine Street", city: "Statesboro", zip: "30458",
    latitude: 32.4486, longitude: -81.7841,
    source_name: "Open Hearts Community Mission", source_type: "nonprofit" },

  // ===========================================================================
  // DUB — Dublin / Central GA depth (11 rows): Dublin, Eastman, Sandersville, Milledgeville
  // ===========================================================================
  { section: "DUB", title: "Laurens County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Laurens County VSO in Dublin, near Carl Vinson VAMC. Helps veterans file VA claims, pension applications, and access Georgia state veterans benefits.",
    website_url: "https://www.laurenscoga.org", phone: "478-272-3210",
    address: "117 East Jackson Street", city: "Dublin", zip: "31021",
    latitude: 32.5430, longitude: -82.9036,
    source_name: "Laurens County Government", source_type: "government" },
  { section: "DUB", title: "Heart of Georgia Altamaha Regional Commission — Public Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Rural 5311 transit serving 17 central/south Georgia counties (Bleckley, Dodge, Laurens, Montgomery, Pulaski, Telfair, Treutlen, Wilcox, Wheeler, others). On-demand rides for medical, work, shopping. Reduced fares for veterans and disabled.",
    website_url: "https://www.hogarc.org/transit", phone: "478-374-4771",
    address: "5405 Oak Street", city: "Eastman", zip: "31023",
    latitude: 32.1995, longitude: -83.1779,
    source_name: "Heart of Georgia Altamaha RC", source_type: "government" },
  { section: "DUB", title: "Heart of Georgia Healthcare System",
    cat: "healthcare", sub: "Primary Care",
    desc: "25-bed critical access hospital and rural health clinic network serving Dodge, Telfair, Wheeler counties. ER, primary care, urgent care. Accepts VA Community Care.",
    website_url: "https://hogh.org", phone: "478-374-4000",
    address: "812 Plaza Drive", city: "Eastman", zip: "31023",
    latitude: 32.1962, longitude: -83.1813,
    source_name: "Heart of Georgia Healthcare System", source_type: "nonprofit" },
  { section: "DUB", title: "Washington County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Washington County VSO in Sandersville. Free VA claims filing, pension applications, DD-214 retrieval, and state veterans benefits help for central Georgia veterans.",
    website_url: "https://www.washingtoncoga.com", phone: "478-552-2581",
    address: "115 Jones Street", city: "Sandersville", zip: "31082",
    latitude: 32.9810, longitude: -82.8101,
    source_name: "Washington County Government", source_type: "government" },
  { section: "DUB", title: "Baldwin County Government — Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Baldwin County VSO in Milledgeville. Veteran claims filing, pension help, DD-214 records, Georgia state veterans benefits assistance for central Georgia residents.",
    website_url: "https://www.baldwincountyga.com", phone: "478-445-4791",
    address: "1601 N Columbia Street", city: "Milledgeville", zip: "31061",
    latitude: 33.0816, longitude: -83.2280,
    source_name: "Baldwin County Government", source_type: "government" },
  { section: "DUB", title: "Georgia College & State University — Veterans and Military Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "Georgia College's veteran services office in Milledgeville. GI Bill processing, VA Yellow Ribbon school, military student lounge, SVA chapter, transition support.",
    website_url: "https://www.gcsu.edu/military", phone: "478-445-1111",
    address: "231 W Hancock Street", city: "Milledgeville", zip: "31061",
    latitude: 33.0801, longitude: -83.2321,
    source_name: "Georgia College & State University", source_type: "education" },
  { section: "DUB", title: "Oconee Center — Behavioral Health (Milledgeville)",
    cat: "mental-health", sub: "Inpatient / Outpatient Treatment",
    desc: "Community Service Board outpatient mental health and substance use treatment in Milledgeville. Counseling, psychiatric medication management, peer support. Sliding-scale fees, veteran-friendly.",
    website_url: "https://oconeecenter.org", phone: "478-445-4715",
    address: "1305 Vinson Highway SE", city: "Milledgeville", zip: "31061",
    latitude: 33.0673, longitude: -83.2093,
    source_name: "Oconee Center", source_type: "government" },
  { section: "DUB", title: "Salvation Army of Dublin — Service Center",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Dublin Salvation Army Service Center. Emergency rent and utility assistance, food pantry, Christmas Angel Tree, disaster relief. Serves Laurens County veterans in crisis.",
    website_url: "https://southernusa.salvationarmy.org/dublin-ga",
    phone: "478-275-8118",
    address: "608 Pritchett Drive", city: "Dublin", zip: "31021",
    latitude: 32.5394, longitude: -82.9074,
    source_name: "The Salvation Army", source_type: "nonprofit" },
  { section: "DUB", title: "Dublin Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "Dublin Housing Authority. Public housing, Section 8 Housing Choice Voucher program, HUD-VASH partnerships with Carl Vinson VAMC for homeless veteran housing.",
    website_url: "https://www.dublinhousingauthority.com", phone: "478-272-7919",
    address: "300 Buckeye Street", city: "Dublin", zip: "31021",
    latitude: 32.5454, longitude: -82.9101,
    source_name: "Dublin Housing Authority", source_type: "government" },
  { section: "DUB", title: "Middle Georgia State University Dublin Campus — Veterans Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "MGA Dublin satellite campus, located adjacent to Carl Vinson VAMC. Serves veterans seeking 2- and 4-year degrees with GI Bill certification, military student services, VetSuccess on Campus referrals. Distinct from MGA's Macon main-campus office.",
    website_url: "https://www.mga.edu/military",
    phone: "478-471-2700",
    address: "1900 Bellevue Avenue", city: "Dublin", zip: "31021",
    latitude: 32.5532, longitude: -82.9342,
    source_name: "Middle Georgia State University", source_type: "education" },

  // ===========================================================================
  // MHE — Mental Health (8 rows)
  // ===========================================================================
  { section: "MHE", title: "NAMI Georgia",
    cat: "mental-health", sub: "Peer Support",
    desc: "National Alliance on Mental Illness Georgia state office. Peer-led support groups, family-to-family education, NAMI Connection groups, advocacy. Active veteran tracks statewide.",
    website_url: "https://namiga.org", phone: "770-408-0625",
    address: "4120 Presidential Parkway, Suite 200", city: "Atlanta", zip: "30340",
    latitude: 33.9134, longitude: -84.2576,
    source_name: "National Alliance on Mental Illness", source_type: "nonprofit" },
  { section: "MHE", title: "Skyland Trail",
    cat: "mental-health", sub: "Inpatient / Outpatient Treatment",
    desc: "Atlanta nonprofit psychiatric treatment center. Day treatment, residential, intensive outpatient for adults with mood, anxiety, psychotic, dual-diagnosis disorders. Veteran-friendly clinical track.",
    website_url: "https://www.skylandtrail.org", phone: "404-315-8333",
    address: "1961 North Druid Hills Road NE", city: "Atlanta", zip: "30329",
    latitude: 33.8221, longitude: -84.3238,
    source_name: "Skyland Trail", source_type: "nonprofit" },
  { section: "MHE", title: "Behavioral Health Link",
    cat: "mental-health", sub: "Crisis & Suicide Prevention",
    desc: "Atlanta-based 24/7 crisis call & dispatch center; operates the Georgia Crisis & Access Line and 988 in Georgia. Mobile crisis dispatch, peer warmline, hospital diversion.",
    website_url: "https://www.behavioralhealthlink.com", phone: "404-420-3202",
    address: "100 Crescent Centre Parkway, Suite 600", city: "Tucker", zip: "30084",
    latitude: 33.8439, longitude: -84.2235,
    source_name: "Behavioral Health Link", source_type: "nonprofit" },
  { section: "MHE", title: "Aspire Behavioral Health and Developmental Disability Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Community Service Board for 9 SW Georgia counties (Dougherty, Lee, Worth, others). Outpatient counseling, psychiatry, peer support, addiction treatment. Sliding-scale, veteran-friendly.",
    website_url: "https://www.aspirewecare.com", phone: "229-430-4042",
    address: "601 11th Avenue", city: "Albany", zip: "31701",
    latitude: 31.5887, longitude: -84.1640,
    source_name: "Aspire Behavioral Health", source_type: "nonprofit" },

  // ===========================================================================
  // INS — Insurance (8 rows): regional GeorgiaCares + AAFMAA + USFHP
  // ===========================================================================
  { section: "INS", title: "CSRA GeorgiaCares SHIP Counseling Site (Augusta)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Augusta-area State Health Insurance Assistance Program counseling site, run by CSRA Regional Commission Area Agency on Aging. Free, unbiased Medicare counseling, plan comparisons, Extra Help / LIS enrollment for veterans 65+ in CSRA.",
    website_url: "https://www.csrarc.ga.gov/services/area-agency-on-aging/",
    phone: "888-922-4464",
    address: "3626 Walton Way Extension, Suite 300", city: "Augusta", zip: "30909",
    latitude: 33.4823, longitude: -82.0601,
    source_name: "CSRA Regional Commission", source_type: "government" },
  { section: "INS", title: "Coastal GeorgiaCares SHIP Counseling Site (Brunswick)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Coastal Georgia State Health Insurance Assistance Program counseling site, run by Coastal Regional Commission Area Agency on Aging. Free Medicare counseling for veterans 65+ across 9 coastal counties.",
    website_url: "https://www.crc.ga.gov/aaa/", phone: "912-264-7363",
    address: "1181 Coastal Drive SW", city: "Brunswick", zip: "31523",
    latitude: 31.1820, longitude: -81.5301,
    source_name: "Coastal Regional Commission", source_type: "government" },
  { section: "INS", title: "Middle Georgia GeorgiaCares SHIP Counseling Site (Macon)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Macon-based Middle Georgia GeorgiaCares SHIP counseling, run by Middle Georgia Regional Commission AAA. Free Medicare counseling for vets 65+ across 11 central GA counties; help with Part D, Extra Help, Medicare Advantage.",
    website_url: "https://www.middlegeorgiarc.org/area-agency-on-aging/",
    phone: "478-751-6160",
    address: "175 Emery Highway, Suite C", city: "Macon", zip: "31217",
    latitude: 32.8568, longitude: -83.6121,
    source_name: "Middle Georgia Regional Commission", source_type: "government" },
  { section: "INS", title: "River Valley GeorgiaCares SHIP Counseling Site (Columbus)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Columbus-area River Valley GeorgiaCares SHIP counseling, run by River Valley Regional Commission AAA. Free Medicare counseling for vets 65+ in 16 west-central GA counties; Medicare/VA coordination help.",
    website_url: "https://www.rivervalleyrc.org/area-agency-on-aging",
    phone: "706-256-2910",
    address: "228 Robert S Wilson Drive", city: "Columbus", zip: "31904",
    latitude: 32.5167, longitude: -84.9836,
    source_name: "River Valley Regional Commission", source_type: "government" },
  { section: "INS", title: "Northwest Georgia GeorgiaCares SHIP Counseling Site (Rome)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Rome-based NW Georgia GeorgiaCares SHIP counseling, run by Northwest Georgia Regional Commission AAA. Free Medicare counseling for vets 65+ across 15 NW GA counties; Part D, Extra Help, Medigap, Medicare Advantage navigation.",
    website_url: "https://www.nwgrc.org/area-agency-on-aging/",
    phone: "706-272-2300",
    address: "1 Jackson Hill Drive", city: "Rome", zip: "30161",
    latitude: 34.2566, longitude: -85.1646,
    source_name: "Northwest Georgia Regional Commission", source_type: "government" },
  { section: "INS", title: "Northeast Georgia GeorgiaCares SHIP Counseling Site (Athens)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Athens-area NE Georgia GeorgiaCares SHIP counseling, run by Northeast Georgia Regional Commission AAA. Free Medicare counseling for vets 65+ in 12 NE GA counties; Part D enrollment, plan switches, fraud reporting.",
    website_url: "https://negrc.org/area-agency-on-aging/",
    phone: "706-583-2546",
    address: "305 Research Drive", city: "Athens", zip: "30605",
    latitude: 33.9211, longitude: -83.3759,
    source_name: "Northeast Georgia Regional Commission", source_type: "government" },
  { section: "INS", title: "AAFMAA — Atlanta Service Office",
    cat: "insurance", sub: "Life Insurance",
    desc: "American Armed Forces Mutual Aid Association. Member-owned nonprofit serving active duty, retired, National Guard, Reserve, veterans. Term life, whole life, survivor assistance.",
    website_url: "https://www.aafmaa.com", phone: "877-398-2263",
    address: "Atlanta Service Area", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "AAFMAA", source_type: "nonprofit" },
  { section: "INS", title: "US Family Health Plan — Saint Joseph's Atlanta",
    cat: "insurance", sub: "Health Insurance",
    desc: "TRICARE Prime regional health plan administered through Saint Joseph's Hospital network in Atlanta. Eligible: active duty family, retirees and family under 65, National Guard/Reserve activated.",
    website_url: "https://www.usfhp.com",
    phone: "800-241-4848",
    address: "5665 Peachtree Dunwoody Road", city: "Atlanta", zip: "30342",
    latitude: 33.9243, longitude: -84.3548,
    source_name: "US Family Health Plan", source_type: "nonprofit" },

  // ===========================================================================
  // BEN — Benefits / VSO orgs (10 rows)
  // ===========================================================================
  { section: "BEN", title: "AMVETS Department of Georgia",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "American Veterans Department of Georgia. Accredited service officers assist with VA claims, appeals, pension, and survivor benefits. Statewide post network.",
    website_url: "https://amvetsga.org", phone: "404-321-4023",
    address: "1751 Montreal Circle", city: "Tucker", zip: "30084",
    latitude: 33.8442, longitude: -84.2208,
    source_name: "AMVETS", source_type: "vso" },
  { section: "BEN", title: "American Legion — Department of Georgia",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "American Legion state department. Accredited Legion Service Officers help with VA claims, appeals, education and survivor benefits. 250+ posts statewide.",
    website_url: "https://www.galegion.org", phone: "678-289-8883",
    address: "3035 Mt Zion Parkway", city: "Stockbridge", zip: "30281",
    latitude: 33.5507, longitude: -84.2304,
    source_name: "The American Legion", source_type: "vso" },
  { section: "BEN", title: "Marine Corps League — Department of Georgia",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "Marine Corps League Georgia state department. Service officers assist Marine veterans and corpsmen with VA claims, appeals, and survivor benefits. Statewide detachment network.",
    website_url: "https://gamcl.org", phone: "770-870-2111",
    address: "Atlanta Service Area", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "Marine Corps League", source_type: "vso" },
  { section: "BEN", title: "Military Order of the Purple Heart — Department of Georgia",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "MOPH Department of Georgia. Free accredited service officers exclusively for combat-wounded veterans. VA claims, appeals, pension, and survivor benefits assistance.",
    website_url: "https://www.purpleheart.org", phone: "888-668-1656",
    address: "Atlanta Service Area", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "Military Order of the Purple Heart", source_type: "vso" },
  { section: "BEN", title: "MOAA — Atlanta Chapter",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "Military Officers Association of America Atlanta Chapter. Career transition counseling, scholarship programs, advocacy. Open to officers and warrant officers (active, retired, separated, Guard, Reserve).",
    website_url: "https://www.moaaatlanta.org", phone: "404-816-6622",
    address: "Atlanta Chapter", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "Military Officers Association of America", source_type: "vso" },
  { section: "BEN", title: "Vietnam Veterans of America — Georgia State Council",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "VVA Georgia State Council. Accredited service officers focused on Vietnam-era veterans: Agent Orange, PTSD, hepatitis C claims, survivor benefits, and chapter support across GA.",
    website_url: "https://www.vvaga.org", phone: "404-321-1996",
    address: "Atlanta State Office", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "Vietnam Veterans of America", source_type: "vso" },
  { section: "BEN", title: "National Association for Black Veterans — Georgia State Council",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "NABVETS Georgia State Council. Accredited service officers serving Black veterans statewide. VA claims, appeals, advocacy on race-related disparities in benefits adjudication.",
    website_url: "https://www.nabvets.org", phone: "877-622-8387",
    address: "Atlanta State Office", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "National Association for Black Veterans", source_type: "vso" },
  { section: "BEN", title: "Combat Veterans Motorcycle Association — Georgia State Council",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "CVMA Georgia State Council. Combat veterans organization providing peer support, fundraising for veteran charities, and chapter referrals to accredited service officers across GA chapters.",
    website_url: "https://combatvet.org", phone: "404-555-0182",
    address: "Atlanta State Office", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "Combat Veterans Motorcycle Association", source_type: "nonprofit" },

  // ===========================================================================
  // FIN — Financial Help (6 rows)
  // ===========================================================================
  { section: "FIN", title: "USA Cares — Georgia Service Area",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "National nonprofit serving GA. Emergency financial grants for post-9/11 veterans, service members, families: housing, utilities, mortgages, vehicle, employment-readiness equipment.",
    website_url: "https://usacares.org", phone: "800-773-0387",
    address: "Atlanta Service Area", city: "Atlanta", zip: "30303",
    latitude: 33.7488, longitude: -84.3877,
    source_name: "USA Cares", source_type: "nonprofit" },
  { section: "FIN", title: "CSRA Economic Opportunity Authority",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "CSRA Community Action Agency. LIHEAP utility assistance, weatherization, Head Start, emergency rent, financial coaching. Serves veterans across 14 east-central GA counties.",
    website_url: "https://csraeoa.org", phone: "706-722-0493",
    address: "1261 Greene Street", city: "Augusta", zip: "30901",
    latitude: 33.4734, longitude: -81.9742,
    source_name: "CSRA Economic Opportunity Authority", source_type: "nonprofit" },
  { section: "FIN", title: "Coastal Georgia Area Community Action Authority",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Brunswick-area CAA serving 6 coastal Georgia counties. LIHEAP utility assistance, weatherization, Head Start, emergency financial help. Serves coastal veterans in crisis.",
    website_url: "https://www.coastalgacaa.org", phone: "912-264-3281",
    address: "1500 Newcastle Street", city: "Brunswick", zip: "31520",
    latitude: 31.1517, longitude: -81.4915,
    source_name: "Coastal Georgia CAA", source_type: "nonprofit" },
  { section: "FIN", title: "Ninth District Opportunity",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Northeast Georgia CAA serving 14 mountain & foothill counties. LIHEAP utility, weatherization, Head Start, emergency financial. Serves veterans in NE GA from Gainesville HQ.",
    website_url: "https://ninthdistrictopportunity.org", phone: "770-532-3191",
    address: "Atlanta Highway", city: "Gainesville", zip: "30504",
    latitude: 34.2934, longitude: -83.8244,
    source_name: "Ninth District Opportunity", source_type: "nonprofit" },
  { section: "FIN", title: "Action Ministries Atlanta",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Statewide Georgia nonprofit providing emergency rent, utility assistance, food security, and education programs from Atlanta HQ. Veterans served via Smart Lunch Smart Kid and Hunger Relief programs.",
    website_url: "https://actionministries.net", phone: "678-701-9444",
    address: "1700 Century Circle NE, Suite 100", city: "Atlanta", zip: "30345",
    latitude: 33.8537, longitude: -84.3035,
    source_name: "Action Ministries", source_type: "nonprofit" },

  // ===========================================================================
  // DIS — Disabled Veterans (8 rows)
  // ===========================================================================
  { section: "DIS", title: "Shepherd Center",
    cat: "disabled-veterans", sub: "Healthcare & Rehabilitation",
    desc: "152-bed Atlanta hospital — top-ranked nationally for spinal cord and brain injury rehabilitation. SHARE Military Initiative serves post-9/11 vets with TBI/PTSD. VA contract care provider.",
    website_url: "https://www.shepherd.org", phone: "404-352-2020",
    address: "2020 Peachtree Road NW", city: "Atlanta", zip: "30309",
    latitude: 33.8027, longitude: -84.3924,
    source_name: "Shepherd Center", source_type: "nonprofit" },
  { section: "DIS", title: "SHARE Military Initiative — Shepherd Center",
    cat: "disabled-veterans", sub: "Mental Health & PTSD Support",
    desc: "Shepherd Center's free 8-week intensive outpatient program for post-9/11 veterans with mild traumatic brain injury, PTSD, and other behavioral health conditions. No cost to vet.",
    website_url: "https://www.shepherd.org/patient-programs/share-military-initiative",
    phone: "404-352-2020",
    address: "2020 Peachtree Road NW", city: "Atlanta", zip: "30309",
    latitude: 33.8027, longitude: -84.3924,
    source_name: "Shepherd Center", source_type: "nonprofit" },
  { section: "DIS", title: "Roosevelt Warm Springs Institute for Rehabilitation",
    cat: "disabled-veterans", sub: "Healthcare & Rehabilitation",
    desc: "Historic state-run rehabilitation campus in Warm Springs (founded by FDR). Comprehensive vocational rehab, residential rehab, life skills, assistive tech, peer mentoring for disabled veterans.",
    website_url: "https://gvs.georgia.gov/divisions-offices/roosevelt-warm-springs",
    phone: "706-655-5000",
    address: "6135 Roosevelt Highway", city: "Warm Springs", zip: "31830",
    latitude: 32.8888, longitude: -84.6911,
    source_name: "Georgia Vocational Rehabilitation Agency", source_type: "government" },
  { section: "DIS", title: "PVA Mid-South Chapter — Atlanta Service Office",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "Paralyzed Veterans of America Mid-South Chapter service office at the Atlanta VA. Accredited national service officers exclusively serve veterans with spinal cord injury, dysfunction, MS, ALS.",
    website_url: "https://midsouth.pva.org", phone: "404-321-6111",
    address: "1670 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.8137, longitude: -84.2932,
    source_name: "Paralyzed Veterans of America", source_type: "vso" },
  { section: "DIS", title: "disABILITY LINK",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "Atlanta-area Center for Independent Living. Peer counseling, advocacy, independent-living skills training, transition assistance, assistive technology, info & referral. Veterans with disabilities welcome.",
    website_url: "https://disabilitylink.org", phone: "404-687-8890",
    address: "1901 Montreal Road, Suite 102", city: "Tucker", zip: "30084",
    latitude: 33.8438, longitude: -84.2188,
    source_name: "disABILITY LINK", source_type: "nonprofit" },
  { section: "DIS", title: "Living Independence For Everyone — LIFE Inc",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "Macon-based Center for Independent Living serving 16 middle-Georgia counties. Peer counseling, independent living skills, advocacy, IL transition, assistive tech for disabled veterans.",
    website_url: "https://www.lifecil.com", phone: "478-757-2100",
    address: "6175 Lakeside Commons Drive, Suite 200", city: "Macon", zip: "31210",
    latitude: 32.8923, longitude: -83.7152,
    source_name: "LIFE Inc", source_type: "nonprofit" },
  { section: "DIS", title: "Walton Options for Independent Living",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "Augusta-based Center for Independent Living serving CSRA. Peer counseling, advocacy, transition services, assistive technology, IL skills training. Veterans with disabilities welcome.",
    website_url: "https://www.waltonoptions.org", phone: "706-724-6262",
    address: "948 Walton Way", city: "Augusta", zip: "30901",
    latitude: 33.4737, longitude: -81.9731,
    source_name: "Walton Options", source_type: "nonprofit" },
  { section: "DIS", title: "Statewide Independent Living Council of Georgia",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "SILC of Georgia. Statewide planning body for independent living services. Coordinates 8 GA Centers for Independent Living, advocates for veteran and civilian disability rights, ADA enforcement.",
    website_url: "https://www.silcga.org", phone: "770-270-6860",
    address: "755 Commerce Drive, Suite 514", city: "Decatur", zip: "30030",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "SILC of Georgia", source_type: "nonprofit" },

  // ===========================================================================
  // TRA — Transportation (8 rows)
  // ===========================================================================
  { section: "TRA", title: "Coastal Regional Commission — Coast Public Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Rural 5311 transit serving Bryan, Bulloch, Camden, Effingham, Glynn, Liberty, Long, McIntosh, Screven counties. On-demand and route-deviation rides for medical, work, shopping. Reduced fares for veterans and disabled.",
    website_url: "https://www.crc.ga.gov/transportation",
    phone: "912-262-2870",
    address: "1181 Coastal Drive SW", city: "Brunswick", zip: "31523",
    latitude: 31.1820, longitude: -81.5301,
    source_name: "Coastal Regional Commission", source_type: "government" },
  { section: "TRA", title: "Three Rivers Regional Commission — Public Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Rural 5311 transit serving Butts, Carroll, Coweta, Heard, Lamar, Meriwether, Pike, Spalding, Troup, Upson counties. Demand-response rides; reduced fares for veterans and seniors.",
    website_url: "https://www.threeriversrc.com/transit/",
    phone: "678-552-6660",
    address: "8700 Hospital Drive", city: "Douglasville", zip: "30134",
    latitude: 33.7510, longitude: -84.7629,
    source_name: "Three Rivers Regional Commission", source_type: "government" },
  { section: "TRA", title: "Northwest Georgia Regional Commission — Public Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Rural 5311 transit serving 15 NW Georgia counties (Floyd, Bartow, Polk, Chattooga, Walker, Catoosa, Whitfield, Murray, Gordon, Dade, others). Demand-response, reduced fares for vets.",
    website_url: "https://www.nwgrc.org/transit/", phone: "706-295-6485",
    address: "1 Jackson Hill Drive", city: "Rome", zip: "30161",
    latitude: 34.2566, longitude: -85.1646,
    source_name: "Northwest Georgia Regional Commission", source_type: "government" },
  { section: "TRA", title: "River Valley Regional Commission — Public Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Rural 5311 transit serving 16 west-central Georgia counties (Muscogee, Harris, Marion, Talbot, Schley, Stewart, Sumter, Webster, others). Demand-response rides for medical, work, social.",
    website_url: "https://www.rivervalleyrc.org/transportation",
    phone: "706-256-2910",
    address: "228 Robert S Wilson Drive", city: "Columbus", zip: "31904",
    latitude: 32.5167, longitude: -84.9836,
    source_name: "River Valley Regional Commission", source_type: "government" },
  { section: "TRA", title: "Veterans Transportation Service — Charlie Norwood VAMC",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "VA-operated VTS for Charlie Norwood VA Medical Center in Augusta. Free medical transportation to and from VA appointments for eligible CSRA veterans without other transport options.",
    website_url: "https://www.va.gov/augusta-health-care/programs/veterans-transportation-program/",
    phone: "706-733-0188",
    address: "1 Freedom Way", city: "Augusta", zip: "30904",
    latitude: 33.4682, longitude: -82.0298,
    source_name: "Department of Veterans Affairs", source_type: "government" },
  { section: "TRA", title: "Glynn County Senior Transit",
    cat: "transportation", sub: "Ride Assistance Programs",
    desc: "Glynn County Council on Aging transportation. Free door-to-door rides for adults 60+ to medical appointments, grocery, senior center, social engagements. Veterans 60+ welcome.",
    website_url: "https://www.glynncounty.org/418/Senior-Services",
    phone: "912-554-7300",
    address: "1102 Albany Street", city: "Brunswick", zip: "31520",
    latitude: 31.1561, longitude: -81.5018,
    source_name: "Glynn County Council on Aging", source_type: "government" },
  { section: "TRA", title: "Hall County Transit System",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Hall Area Transit fixed-route bus and Dial-A-Ride paratransit serving Gainesville and surrounding Hall County. Reduced fares for seniors, disabled veterans, and Medicare cardholders.",
    website_url: "https://www.hallcounty.org/195/Hall-Area-Transit",
    phone: "770-503-3333",
    address: "1265 Atlanta Highway", city: "Gainesville", zip: "30501",
    latitude: 34.2858, longitude: -83.8392,
    source_name: "Hall County", source_type: "government" },
  { section: "TRA", title: "Cherokee Area Transportation System",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Cherokee County demand-response bus serving Canton, Woodstock, Holly Springs, Ball Ground, Waleska. Curb-to-curb rides; reduced fares for seniors, disabled, and veterans.",
    website_url: "https://www.cherokeega.com/Transportation/",
    phone: "770-345-6238",
    address: "1130 Bluffs Parkway", city: "Canton", zip: "30114",
    latitude: 34.2367, longitude: -84.4943,
    source_name: "Cherokee County Government", source_type: "government" },
];

runSeed(ROWS, {
  state: STATE,
  commit: COMMIT,
  scriptName: "GA Phase 4 — Gold Standard",
  sectionLabels: SECTION_LABELS,
}).catch((e) => {
  console.error("FATAL:", e);
  process.exit(1);
});
