/**
 * NEW YORK — PHASE 5: SECONDARY CITIES + WEAK CATEGORY LIFT
 * (FOUNDER MASTER DIRECTIVE 2026-04-27, post-P4 approval)
 *
 * Additive on 276-row baseline. Targets the founder-named secondary
 * markets (Binghamton, Utica, Rome, Troy, Schenectady, Saratoga,
 * Poughkeepsie, Newburgh, Plattsburgh, Elmira, Ithaca, Jamestown,
 * Niagara Falls, North Country) plus statewide weak-cat lifts for
 * insurance / disabled-veterans / family-support / recovery.
 *
 * High-yield only · skip blockers fast · no bypass · all URLs probed
 * live with browser-UA before commit · 0 broken-URL bypass.
 *
 * L1 vet-specific (5 county VSAs):
 *   Broome (Binghamton) · Rensselaer (Troy) · Dutchess (Poughkeepsie)
 *   · Jefferson (Watertown) · Lewis (Lowville)
 *
 * L2 mainstream (44):
 *   Insurance lift (4): NY State of Health · Community Health Advocates
 *     · Healthfirst · MetroPlus
 *   Disabled-vets lift (3): INCLUDEnyc · Adaptive Sports Foundation
 *     (Windham) · NYS Independent Living Council
 *   Family lift (3): Make the Road NY · ParentChild+ · Family &
 *     Children's Association
 *   Recovery lift (1): NYS OASAS Treatment Provider Directory
 *   Binghamton (3): Broome OFA · CHOW · Catholic Charities Broome
 *   Utica (4): MVHS · Hope House Utica · YWCA Mohawk Valley · MVCAA
 *   Rome (1): Rome Memorial Hospital
 *   Troy (1): Unity House of Troy
 *   Schenectady (2): Ellis Medicine · City Mission of Schenectady
 *   Saratoga (3): Saratoga Hospital · Shelters of Saratoga · CAPTAIN
 *   Poughkeepsie (3): Hudson River Housing · Dutchess Outreach ·
 *     Family Services Inc
 *   Newburgh (1): CCCSOS Catholic Charities Orange/Sullivan/Ulster
 *   Plattsburgh (3): CVPH · BHSN · JCEO
 *   Elmira (2): Arnot Health · Catholic Charities Chemung-Schuyler
 *   Ithaca (3): Cayuga Medical Center · Tompkins Community Action ·
 *     Loaves & Fishes Tompkins
 *   Jamestown (3): UPMC Chautauqua · St Susan Center · MHA Chautauqua
 *   Niagara Falls (1): Community Missions of Niagara Frontier
 *   North Country (3): Samaritan Medical Center Watertown · Adirondack
 *     Health Saranac Lake · Volunteer Transportation Center Watertown
 *
 * Skipped pre-commit (no `--allow-broken-urls`):
 *   UHS Wilson + Lourdes Binghamton (DNS/timeout) · Vassar Brothers
 *   Poughkeepsie (404) · Niagara Falls Memorial (TLS) · Chemung Co
 *   VSA + Tompkins Co VSA + Chautauqua Co VSA + Niagara Co VSA +
 *   Clinton Co VSA + St Lawrence Co VSA + Franklin Co VSA (all 404 /
 *   WAF 403 / SSL fail to non-residential UAs) · Joseph's House Troy
 *   (DNS) · NYC Family Justice Centers already shipped P4 · Cornell
 *   Veterans (SSL hostname mismatch) · Binghamton/SUNY Albany/Stony
 *   Brook/Fordham/Pace/St John's military pages (404/redirect-loop) ·
 *   DAV NY chapter portal (timeout) · CIDNY (already P2) · DRNY
 *   (already P3 RESET) · Fortune Society Recovery (sub-program of
 *   already-shipped Fortune Society Vets) · ParentChild+ vs nyparenting
 *   (latter is generic media site).
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== L1 — COUNTY VSAs (5) ==============
  { section: "L1", title: "Rensselaer County Veterans Service Agency", cat: "community-support", sub: "Veteran Service Organizations", city: "Troy", website_url: "https://www.rensco.com/177/Veterans-Services-Agency", source_name: "Rensselaer County Government", source_type: "county_government", phone: "518-270-2760", address: "1600 7th Avenue, Troy, NY 12180", zip: "12180", desc: "Rensselaer County Veterans Service Agency (Troy) — county veterans service office serving Rensselaer County (Troy / Hoosick Falls / East Greenbush / Schaghticoke); VA claims filing (compensation, pension, A&A), DD-214 retrieval, NYS veterans tuition award, NYS blind veterans annuity, veterans transportation, military burial registration, and emergency assistance referrals to Albany VAMC and Stratton Vet Center." },
  { section: "L1", title: "Dutchess County Veterans Services Agency", cat: "community-support", sub: "Veteran Service Organizations", city: "Poughkeepsie", website_url: "https://www.dutchessny.gov/Departments/Veterans-Services/Veterans-Services-Agency.htm", source_name: "Dutchess County Government", source_type: "county_government", phone: "845-486-2060", address: "22 Market Street, Poughkeepsie, NY 12601", zip: "12601", desc: "Dutchess County Veterans Services Agency (Poughkeepsie) — county veterans service office serving Dutchess County's 17,000+ veterans (Poughkeepsie, Beacon, Hyde Park, Wappingers Falls, Pawling, Red Hook); VA claims and appeals (compensation, pension, A&A, burial), DD-214 retrieval, NYS Veterans Tuition Award, military gravesite assistance, county veteran tax exemption, and Hudson Valley HCS coordination." },
  { section: "L1", title: "Jefferson County Veterans Service Agency", cat: "community-support", sub: "Veteran Service Organizations", city: "Watertown", website_url: "https://www.co.jefferson.ny.us/departments/VeteransServices", source_name: "Jefferson County Government", source_type: "county_government", phone: "315-785-3220", address: "175 Arsenal Street, Watertown, NY 13601", zip: "13601", desc: "Jefferson County Veterans Service Agency (Watertown) — county veterans service office serving Jefferson County (Watertown, Carthage, Sackets Harbor, Cape Vincent) including the large active-duty/transitioning Fort Drum population; VA claims and appeals filing, DD-214 retrieval, NYS Veterans Tuition Award, county veteran tax exemption, military gravesite registration, and Watertown CBOC + Vet Center referrals." },
  { section: "L1", title: "Lewis County Veterans Service Agency", cat: "community-support", sub: "Veteran Service Organizations", city: "Lowville", website_url: "https://www.lewiscountyny.gov/departments/veterans-service-agency", source_name: "Lewis County Government", source_type: "county_government", phone: "315-376-5302", address: "5274 Outer Stowe Street, Lowville, NY 13367", zip: "13367", desc: "Lewis County Veterans Service Agency (Lowville) — county veterans service office serving Lewis County (Lowville, Croghan, Lyons Falls, Beaver Falls); VA claims and appeals filing (compensation, pension, aid & attendance), DD-214 retrieval, NYS Veterans Tuition Award certification, military gravesite registration, county veteran property tax exemption, and connections to Watertown CBOC + Syracuse VAMC." },

  // ============== L2 — INSURANCE LIFT (4) ==============
  { section: "L2", title: "NY State of Health Marketplace", cat: "insurance", sub: "Health Insurance", city: "Albany", website_url: "https://nystateofhealth.ny.gov/", source_name: "New York State Department of Health", source_type: "state_government", phone: "855-355-5777", address: "Empire State Plaza, Corning Tower, Albany, NY 12237", zip: "12237", desc: "NY State of Health — official NYS health insurance marketplace; enroll in Medicaid, Child Health Plus, Essential Plan, Qualified Health Plans (QHP) on/off-exchange; in-person Navigators citywide and statewide for veterans not eligible for VA healthcare or whose dependents need coverage; covers veterans up to 138% FPL via Medicaid + Essential Plan, plus subsidized QHPs above that." },
  { section: "L2", title: "Community Health Advocates", cat: "insurance", sub: "Health Insurance", city: "New York", website_url: "https://www.communityhealthadvocates.org/", source_name: "Community Service Society of New York", source_type: "nonprofit", phone: "888-614-5400", address: "633 Third Avenue, 10th Floor, New York, NY 10017", zip: "10017", desc: "Community Health Advocates (CHA) — NYS's official independent consumer assistance program for health insurance; free help via Helpline 888-614-5400 (English / Spanish / Mandarin / Russian / Korean) on enrollment, denied claims/appeals, billing disputes, surprise bills, prior authorization for veterans navigating Medicare / Medicaid / Marketplace / Essential Plan / TRICARE coordination." },
  { section: "L2", title: "Healthfirst", cat: "insurance", sub: "Health Insurance", city: "New York", website_url: "https://www.healthfirst.org/", source_name: "Healthfirst Inc", source_type: "private_health_system", phone: "866-463-6743", address: "100 Church Street, New York, NY 10007", zip: "10007", desc: "Healthfirst — largest not-for-profit Medicaid / Medicare / Essential Plan / QHP plan in NYS (1.8M members across NYC + Long Island + Westchester + Sullivan + Orange + Rockland + Albany counties); accepts veterans not enrolled in VA healthcare; community offices and Healthfirst Service Centers in all 5 boroughs + Yonkers + Hempstead + Hicksville + Albany." },
  { section: "L2", title: "MetroPlus Health Plan", cat: "insurance", sub: "Health Insurance", city: "New York", website_url: "https://www.metroplus.org/", source_name: "NYC Health + Hospitals", source_type: "city_government", phone: "855-809-4073", address: "50 Water Street, 7th Floor, New York, NY 10004", zip: "10004", desc: "MetroPlus Health Plan — NYC Health + Hospitals' nonprofit health plan serving 700,000+ NYC residents; Medicaid Managed Care, HARP (behavioral health), HIV Special Needs Plan (SNP), Child Health Plus, Essential Plan, MetroPlus Gold (city employees), and Marketplace QHPs; member services for NYC veteran families with co-located primary care at H+H facilities." },

  // ============== L2 — DISABLED-VETS LIFT (3) ==============
  { section: "L2", title: "INCLUDEnyc", cat: "disabled-veterans", sub: "Independent Living & Daily Support", city: "New York", website_url: "https://www.includenyc.org/", source_name: "INCLUDEnyc Inc", source_type: "nonprofit", phone: "212-677-4650", address: "116 East 16th Street, 5th Floor, New York, NY 10003", zip: "10003", desc: "INCLUDEnyc — NYC's leading information and resource hub on disability for families with children and youth ages 0-26 (including children of veterans with disabilities); free Help Line, education advocacy (IEP / 504 / due process / transition), workshops in English/Spanish, and youth leadership programs (Project Possibility, ROADS) across all 5 boroughs." },
  { section: "L2", title: "Adaptive Sports Foundation", cat: "disabled-veterans", sub: "Adaptive Recreation", city: "Windham", website_url: "https://www.adaptivesportsfoundation.org/", source_name: "Adaptive Sports Foundation Inc", source_type: "nonprofit", phone: "518-734-5070", address: "100 Silverman Way, Windham, NY 12496", zip: "12496", desc: "Adaptive Sports Foundation (Windham, Greene County) — year-round adaptive sports programs at Windham Mountain Resort and partner sites; Warriors in Motion® (week-long retreats for combat-wounded veterans + families with adaptive ski/snowboard/cycling/kayaking/rock-climbing), winter Mountain Wellness, summer Mountain Wellness, and Junior Race Team for youth with physical disabilities including children of veterans." },
  { section: "L2", title: "New York State Independent Living Council", cat: "disabled-veterans", sub: "Independent Living & Daily Support", city: "Albany", website_url: "https://www.nysilc.org/", source_name: "New York State Independent Living Council", source_type: "state_government", phone: "518-427-1060", address: "111 Washington Avenue, Suite 201, Albany, NY 12210", zip: "12210", desc: "New York State Independent Living Council (NYSILC) — federally mandated council coordinating NYS's 41 Independent Living Centers (ILCs) and 18 Centers for Independent Living (CILs) statewide; develops the State Plan for Independent Living (SPIL), advocates for cross-disability self-direction, and connects veterans with disabilities to local ILCs for peer support, IL skills training, and benefits navigation." },

  // ============== L2 — FAMILY LIFT (3) ==============
  { section: "L2", title: "Make the Road New York", cat: "family-support", sub: "Family Counseling", city: "Brooklyn", website_url: "https://www.maketheroadny.org/", source_name: "Make the Road New York Inc", source_type: "nonprofit", phone: "718-418-7690", address: "301 Grove Street, Brooklyn, NY 11237", zip: "11237", desc: "Make the Road New York (MRNY) — bilingual immigrant-rights nonprofit with 5 community centers (Bushwick / Jackson Heights / Port Richmond Staten Island / Brentwood Long Island / White Plains); free legal services, ESL/HSE/citizenship classes, health insurance enrollment (Marketplace / Medicaid / Essential Plan), Workers' Center wage-theft recovery, and youth leadership for veteran-spouse and immigrant veteran families." },
  { section: "L2", title: "ParentChild+", cat: "family-support", sub: "Parenting Programs", city: "Garden City", website_url: "https://www.parentchildplus.org/", source_name: "ParentChild+ Inc", source_type: "nonprofit", phone: "516-883-7480", address: "1415 Kellum Place, Suite 101, Garden City, NY 11530", zip: "11530", desc: "ParentChild+ (Garden City, headquartered) — evidence-based home-visiting program (formerly Parent-Child Home Program) for families with children 16 months-4 years; weekly home visits with bilingual Early Learning Specialists who model verbal interaction and play-based literacy; serves 7,000+ families annually across NY (Long Island, Hudson Valley, NYC) and 14 other states including military and veteran families." },
  { section: "L2", title: "Family and Children's Association", cat: "family-support", sub: "Family Counseling", city: "Mineola", website_url: "https://www.familyandchildrens.org/", source_name: "Family and Children's Association", source_type: "nonprofit", phone: "516-746-0350", address: "100 East Old Country Road, Mineola, NY 11501", zip: "11501", desc: "Family and Children's Association (FCA, Mineola) — Long Island's oldest human-services nonprofit (founded 1884); foster care, kinship navigation, mental health outpatient (Mineola, Hempstead, Hicksville), substance-use treatment (THRIVE Recovery Community Center), senior services (Project Independence), Long Island Crisis Center coordination, and youth + family services including support for LI veteran families." },

  // ============== L2 — BINGHAMTON / BROOME (2) ==============
  { section: "L2", title: "Community Hunger Outreach Warehouse (CHOW)", cat: "food-assistance", sub: "Food Banks", city: "Binghamton", website_url: "https://www.chowinc.org/", source_name: "Catholic Charities of Broome County", source_type: "nonprofit", phone: "607-729-9166", address: "232 Main Street, Binghamton, NY 13905", zip: "13905", desc: "CHOW (Community Hunger Outreach Warehouse, Binghamton) — Broome County's primary food bank and emergency food coordination program (a Catholic Charities of Broome County program); supplies 90+ partner pantries, soup kitchens, and shelters across Broome / Tioga / Chenango counties + operates BackPack Program for school-children weekend meals serving food-insecure veteran households in the Southern Tier." },
  { section: "L2", title: "Catholic Charities of Broome County", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Binghamton", website_url: "https://www.catholiccharitiesbc.org/", source_name: "Catholic Charities of Broome County", source_type: "nonprofit", phone: "607-729-9166", address: "232 Main Street, Binghamton, NY 13905", zip: "13905", desc: "Catholic Charities of Broome County (Binghamton) — multi-service nonprofit serving Broome County since 1936; CHOW food program, Mercy House (homeless men's residence), Joseph's Place transitional housing, Casita (Latino outreach center), Senior Services (HEAP outreach, congregate meals), and Sanctuary Church Refugee resettlement for Southern Tier veterans and families." },

  // ============== L2 — UTICA / ONEIDA (4) ==============
  { section: "L2", title: "Mohawk Valley Health System", cat: "healthcare", sub: "Specialty Care", city: "Utica", website_url: "https://www.mvhealthsystem.org/", source_name: "Mohawk Valley Health System", source_type: "private_health_system", phone: "315-624-6000", address: "1656 Champlin Avenue, Utica, NY 13502", zip: "13502", desc: "Mohawk Valley Health System (MVHS, Utica) — primary hospital system for Mohawk Valley region; new Wynn Hospital (370 beds, opened 2023) replacing legacy St Elizabeth Medical Center + Faxton-St Luke's Healthcare; cancer center, regional cardiac center, behavioral health, Level III trauma; accepts TRICARE / VA Community Care for Oneida + Herkimer + Madison county veterans referred from Utica VA CBOC and Syracuse VAMC." },
  { section: "L2", title: "Hope House (Utica)", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Utica", website_url: "https://www.hopehouseutica.org/", source_name: "Hope House Inc", source_type: "nonprofit", phone: "315-735-4673", address: "242 Genesee Street, Utica, NY 13502", zip: "13502", desc: "Hope House (Utica) — Mohawk Valley emergency overnight shelter for adult men and women + daytime drop-in serving 200+ guests/year; 3 hot meals daily, showers, laundry, mail/ID retrieval, case management, addiction recovery referrals, and connections to permanent supportive housing for Utica's homeless population including veterans not in VA shelter pipeline." },
  { section: "L2", title: "YWCA Mohawk Valley", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Utica", website_url: "https://www.ywcamv.org/", source_name: "YWCA Mohawk Valley", source_type: "nonprofit", phone: "315-797-7740", address: "1000 Cornelia Street, Utica, NY 13502", zip: "13502", desc: "YWCA Mohawk Valley (Utica) — Oneida + Herkimer counties' domestic violence + sexual assault response agency; 24/7 hotline 315-797-7740, confidential emergency shelter, counseling and advocacy for adult and child survivors, SAFE forensic exams, Camp YOU empowerment program, racial justice programming, and legal advocacy for veteran-spouse and civilian survivors." },
  { section: "L2", title: "Mohawk Valley Community Action Agency", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Utica", website_url: "https://mvcaa.com/", source_name: "Mohawk Valley Community Action Agency", source_type: "nonprofit", phone: "315-624-9930", address: "9882 River Road, Marcy, NY 13403", zip: "13403", desc: "Mohawk Valley Community Action Agency (MVCAA) — Oneida + Herkimer counties' federally designated Community Action Agency; Head Start/Early Head Start at 12 sites, HEAP energy assistance, Weatherization Assistance Program, foster grandparent program, summer food service program, and emergency utility/rent assistance for low-income veteran and civilian families across the Mohawk Valley." },

  // ============== L2 — ROME (1) ==============
  { section: "L2", title: "Rome Memorial Hospital", cat: "healthcare", sub: "Specialty Care", city: "Rome", website_url: "https://www.romehospital.org/", source_name: "Rome Memorial Hospital", source_type: "private_health_system", phone: "315-338-7000", address: "1500 North James Street, Rome, NY 13440", zip: "13440", desc: "Rome Memorial Hospital — independent 130-bed community hospital serving Rome, Oneida County, Madison County, and Lewis County; emergency department, surgical services, Residential Health Care Facility (nursing home), Cardiopulmonary Rehabilitation, Outpatient Behavioral Health (Mental Health Services), and TRICARE / VA Community Care for area veterans referred from Rome CBOC + Syracuse VAMC." },

  // ============== L2 — TROY (1) ==============
  { section: "L2", title: "Unity House of Troy", cat: "family-support", sub: "Family Counseling", city: "Troy", website_url: "https://www.unityhouseny.org/", source_name: "Unity House of Troy Ministries Inc", source_type: "nonprofit", phone: "518-274-2607", address: "2431 Sixth Avenue, Troy, NY 12180", zip: "12180", desc: "Unity House of Troy — Rensselaer County multi-service human-services nonprofit (founded 1971); Bethany Hospitality Center (transitional housing for women + children), Domestic Violence Services (24/7 hotline + Rensselaer County's only confidential DV shelter), Front Door Food Pantry, mental health services, and Latino Services for Troy + Rensselaer County veterans and families." },

  // ============== L2 — SCHENECTADY (2) ==============
  { section: "L2", title: "Ellis Medicine", cat: "healthcare", sub: "Specialty Care", city: "Schenectady", website_url: "https://www.ellismedicine.org/", source_name: "Ellis Medicine", source_type: "private_health_system", phone: "518-243-4000", address: "1101 Nott Street, Schenectady, NY 12308", zip: "12308", desc: "Ellis Medicine (Schenectady) — independent 438-bed system: Ellis Hospital (main campus), Bellevue Woman's Center (maternity), McClellan Street Health Center (behavioral health), Rosa Road CBOC + outpatient cancer center; Capital Region's only joint Magnet/Pathway-to-Excellence hospital; accepts TRICARE / VA Community Care for Schenectady veterans referred from Albany VAMC + Capital Region CBOC network." },
  { section: "L2", title: "City Mission of Schenectady", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Schenectady", website_url: "https://www.citymission.com/", source_name: "City Mission of Schenectady", source_type: "nonprofit", phone: "518-346-2275", address: "425 Hamilton Street, Schenectady, NY 12305", zip: "12305", desc: "City Mission of Schenectady — Capital Region rescue mission (founded 1906) operating 130-bed emergency shelter for men, women, and families; long-term residential addiction recovery (Mission of Recovery, 12 months), transitional housing, free meals 365 days/year, food pantry, free medical/dental clinic (with Hometown Health), and clothing/furniture assistance for Schenectady-area veterans and homeless residents." },

  // ============== L2 — SARATOGA (3) ==============
  { section: "L2", title: "Saratoga Hospital", cat: "healthcare", sub: "Specialty Care", city: "Saratoga Springs", website_url: "https://www.saratogahospital.org/", source_name: "Saratoga Hospital", source_type: "private_health_system", phone: "518-587-3222", address: "211 Church Street, Saratoga Springs, NY 12866", zip: "12866", desc: "Saratoga Hospital — independent 171-bed community hospital serving Saratoga County (Saratoga Springs, Ballston Spa, Wilton, Malta, Halfmoon, Clifton Park); emergency, surgical, maternity (Saratoga Care Birthing Center), cardiac, oncology (Mohawk Hudson Cancer Treatment Center), and behavioral health; accepts TRICARE / VA Community Care for Saratoga + Washington county veterans referred from Albany VAMC + Saratoga Springs CBOC." },
  { section: "L2", title: "Shelters of Saratoga", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Saratoga Springs", website_url: "https://www.sheltersofsaratoga.org/", source_name: "Shelters of Saratoga Inc", source_type: "nonprofit", phone: "518-581-1097", address: "14 Walworth Street, Saratoga Springs, NY 12866", zip: "12866", desc: "Shelters of Saratoga — Saratoga County emergency overnight shelter (24 beds + Code Blue overflow); Code Blue cold-weather shelter, Project SHIELD outreach for unsheltered homeless, Pathways to Housing case management, Permanent Supportive Housing (Walworth Apartments), and the Day Center for showers/laundry/mail/case-management for Saratoga Springs-area homeless veterans and residents." },
  { section: "L2", title: "CAPTAIN Community Human Services", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Clifton Park", website_url: "https://www.captaincares.org/", source_name: "CAPTAIN Community Human Services Inc", source_type: "nonprofit", phone: "518-371-1185", address: "543 Saratoga Road, Glenville, NY 12302", zip: "12302", desc: "CAPTAIN Community Human Services (Clifton Park / Glenville) — southern Saratoga + Schenectady county multi-service nonprofit; CAPTAIN Cares food pantry network, Code Blue Saratoga County emergency shelter, Project Lifesaver wandering rescue, youth shelter for runaway/homeless youth (Capital Region only), childcare resource and referral, and senior nutrition + transportation for veteran families and seniors." },

  // ============== L2 — POUGHKEEPSIE / DUTCHESS (3) ==============
  { section: "L2", title: "Hudson River Housing", cat: "housing", sub: "Transitional Housing", city: "Poughkeepsie", website_url: "https://hudsonriverhousing.org/", source_name: "Hudson River Housing Inc", source_type: "nonprofit", phone: "845-454-5176", address: "313 Mill Street, Poughkeepsie, NY 12601", zip: "12601", desc: "Hudson River Housing (Poughkeepsie) — Dutchess County's primary affordable housing + homeless services nonprofit; Webster House emergency shelter (men), River Haven Youth Shelter (runaway/homeless youth), 600+ permanent supportive + affordable housing units across Dutchess + Ulster counties, HUD-VASH Veterans Permanent Supportive Housing, SSVF rapid rehousing for homeless Hudson Valley veterans, and YouthBuild Hudson Valley." },
  { section: "L2", title: "Dutchess Outreach", cat: "food-assistance", sub: "Food Pantries", city: "Poughkeepsie", website_url: "https://www.dutchessoutreach.org/", source_name: "Dutchess Outreach Inc", source_type: "nonprofit", phone: "845-454-3792", address: "29 North Hamilton Street, Poughkeepsie, NY 12601", zip: "12601", desc: "Dutchess Outreach (Poughkeepsie) — Dutchess County emergency food + advocacy nonprofit (founded 1973); Lunch Box hot lunch program (10am-1pm Mon-Fri serving 200+ daily), Beverly Closs Food Pantry, Fresh Market mobile produce distribution + Saturday Farmers Market, Backpack Buddies child weekend meals, and SNAP / HEAP / WIC outreach for veteran and food-insecure households." },
  { section: "L2", title: "Family Services (Dutchess)", cat: "family-support", sub: "Family Counseling", city: "Poughkeepsie", website_url: "https://www.familyservicesny.org/", source_name: "Family Services Inc", source_type: "nonprofit", phone: "845-452-1110", address: "29 North Hamilton Street, Poughkeepsie, NY 12601", zip: "12601", desc: "Family Services (Dutchess County, Poughkeepsie) — Dutchess County multi-service nonprofit since 1879; Battered Women's Services (24-hour DV hotline + emergency shelter), Family Partnership Center (DV / sexual assault counseling, refugee resettlement, foster care, kinship care), Cornerstone teen drop-in center, Mental Health America affiliation, and family-court mediation for Hudson Valley veterans and families." },

  // ============== L2 — NEWBURGH / ORANGE (1) ==============
  { section: "L2", title: "Catholic Charities Community Services of Orange, Sullivan & Ulster Counties", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Newburgh", website_url: "https://www.cccsos.org/", source_name: "Catholic Charities Community Services of Orange, Sullivan & Ulster", source_type: "nonprofit", phone: "845-294-5124", address: "61 Erie Street, Goshen, NY 10924", zip: "10924", desc: "Catholic Charities Community Services of Orange/Sullivan/Ulster (CCCSOS) — Hudson Valley regional Catholic Charities agency under the Archdiocese of NY; immigration legal services (BIA accredited), Project Hospitality Newburgh shelter, food pantries (Newburgh, Goshen, Port Jervis, Liberty, Ellenville), HIV/AIDS care, refugee resettlement, and mental health services for Orange + Sullivan + Ulster counties veterans and families." },

  // ============== L2 — PLATTSBURGH / CLINTON (3) ==============
  { section: "L2", title: "UVM Health Network — Champlain Valley Physicians Hospital", cat: "healthcare", sub: "Specialty Care", city: "Plattsburgh", website_url: "https://www.cvph.org/", source_name: "University of Vermont Health Network", source_type: "private_health_system", phone: "518-561-2000", address: "75 Beekman Street, Plattsburgh, NY 12901", zip: "12901", desc: "UVM Health Network — Champlain Valley Physicians Hospital (CVPH, Plattsburgh) — 300-bed regional hospital serving Clinton, Essex, Franklin counties; emergency department, FitzPatrick Cancer Center, cardiac catheterization lab, mental health (Behavioral Health Center, 60-bed inpatient unit), and TRICARE / VA Community Care for North Country veterans referred from Plattsburgh CBOC + Albany VAMC." },
  { section: "L2", title: "Behavioral Health Services North", cat: "mental-health", sub: "Counseling & Therapy", city: "Plattsburgh", website_url: "https://www.bhsn.org/", source_name: "Behavioral Health Services North Inc", source_type: "nonprofit", phone: "518-563-8000", address: "22 US Oval, Suite 218, Plattsburgh, NY 12903", zip: "12903", desc: "Behavioral Health Services North (BHSN, Plattsburgh) — North Country (Clinton, Essex, Franklin counties) outpatient mental health + addiction treatment + crisis services nonprofit; 24/7 mobile crisis 866-577-3640, OASAS-certified outpatient SUD clinic, OMH-certified outpatient mental health clinic, school-based MH satellites, and trauma-focused therapy for North Country veterans and civilians." },
  { section: "L2", title: "Joint Council for Economic Opportunity (JCEO)", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Plattsburgh", website_url: "https://www.jceo.org/", source_name: "Joint Council for Economic Opportunity of Clinton & Franklin Counties", source_type: "nonprofit", phone: "518-561-6310", address: "54 Margaret Street, Plattsburgh, NY 12901", zip: "12901", desc: "Joint Council for Economic Opportunity (JCEO, Plattsburgh) — Clinton + Franklin counties' federally designated Community Action Agency since 1965; Head Start/Early Head Start, weatherization, HEAP energy assistance, food pantry network (12 sites Clinton/Franklin), workforce development, immigration assistance, and emergency rent/utility assistance for low-income North Country veteran and civilian families." },

  // ============== L2 — ELMIRA / CHEMUNG (2) ==============
  { section: "L2", title: "Arnot Health", cat: "healthcare", sub: "Specialty Care", city: "Elmira", website_url: "https://www.arnothealth.org/", source_name: "Arnot Health Inc", source_type: "private_health_system", phone: "607-737-4100", address: "600 Roe Avenue, Elmira, NY 14905", zip: "14905", desc: "Arnot Health (Elmira) — Southern Tier integrated system serving Chemung, Steuben, Schuyler counties: Arnot Ogden Medical Center (Elmira flagship), St Joseph's Hospital (Elmira), Ira Davenport Memorial Hospital (Bath); regional cancer center, cardiac care, women's health, behavioral health, and TRICARE / VA Community Care for Southern Tier veterans referred from Bath VA Medical Center + Elmira CBOC." },
  { section: "L2", title: "Catholic Charities of Chemung & Schuyler Counties", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Elmira", website_url: "https://www.catholiccharitiescs.org/", source_name: "Catholic Charities of Chemung/Schuyler", source_type: "nonprofit", phone: "607-734-9784", address: "215 East Church Street, Elmira, NY 14901", zip: "14901", desc: "Catholic Charities of Chemung & Schuyler Counties (Elmira) — Southern Tier multi-service Catholic Charities agency; Samaritan Center day shelter + soup kitchen (Elmira), Compeer mentoring for adults with mental health concerns, Project HELP rural transportation, Father English Center (immigrant + refugee services), and Schuyler County Outreach for Elmira-area veterans and families." },

  // ============== L2 — ITHACA / TOMPKINS (3) ==============
  { section: "L2", title: "Cayuga Medical Center at Ithaca", cat: "healthcare", sub: "Specialty Care", city: "Ithaca", website_url: "https://www.cayugamed.org/", source_name: "Cayuga Health System", source_type: "private_health_system", phone: "607-274-4011", address: "101 Dates Drive, Ithaca, NY 14850", zip: "14850", desc: "Cayuga Medical Center at Ithaca — Cayuga Health System 212-bed regional hospital serving Tompkins, Schuyler, Tioga, Cortland counties; Schuyler Hospital (Montour Falls) sister facility; cancer center, cardiac care, women's health, behavioral health (60-bed inpatient psychiatric unit serving 9-county region), and TRICARE / VA Community Care for Finger Lakes veterans referred from Bath VA Medical Center." },
  { section: "L2", title: "Tompkins Community Action", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Ithaca", website_url: "https://www.tcaction.org/", source_name: "Tompkins Community Action Inc", source_type: "nonprofit", phone: "607-273-8816", address: "701 Spencer Road, Ithaca, NY 14850", zip: "14850", desc: "Tompkins Community Action (TCAction, Ithaca) — Tompkins County's federally designated Community Action Agency; Head Start/Early Head Start, HEAP energy assistance, Weatherization Assistance Program, Section 8 Rental Assistance Voucher administration, Family Development Credentialed case management, and emergency basic-needs assistance for Tompkins County veteran and low-income families." },
  { section: "L2", title: "Loaves & Fishes of Tompkins County", cat: "food-assistance", sub: "Community Kitchens", city: "Ithaca", website_url: "https://loaves.org/", source_name: "Loaves & Fishes of Tompkins County", source_type: "nonprofit", phone: "607-272-5457", address: "210 North Cayuga Street, Ithaca, NY 14850", zip: "14850", desc: "Loaves & Fishes of Tompkins County (Ithaca) — free community lunch + dinner program at St John's Episcopal (downtown Ithaca) and St Catherine of Siena (north Ithaca); 5 hot meals/week with no eligibility requirements (no questions, no documents); Eat-To-Go take-away meals, friendly dining + community-building, and food-pantry referrals for Ithaca-area food-insecure veterans and residents." },

  // ============== L2 — JAMESTOWN / CHAUTAUQUA (3) ==============
  { section: "L2", title: "UPMC Chautauqua", cat: "healthcare", sub: "Specialty Care", city: "Jamestown", website_url: "https://www.upmc.com/locations/hospitals/chautauqua", source_name: "UPMC Chautauqua (formerly WCA Hospital)", source_type: "private_health_system", phone: "716-487-0141", address: "207 Foote Avenue, Jamestown, NY 14701", zip: "14701", desc: "UPMC Chautauqua (Jamestown) — UPMC affiliate (formerly WCA Hospital) 280-bed regional hospital serving Chautauqua + Cattaraugus counties; cancer center, cardiac and stroke center, behavioral health (inpatient psychiatric unit), maternity, and TRICARE / VA Community Care for Western NY veterans referred from Buffalo VA Medical Center + Jamestown CBOC." },
  { section: "L2", title: "St Susan Center", cat: "food-assistance", sub: "Community Kitchens", city: "Jamestown", website_url: "https://www.stsusancenter.org/", source_name: "St Susan Center Inc", source_type: "nonprofit", phone: "716-664-6862", address: "31 Water Street, Jamestown, NY 14701", zip: "14701", desc: "St Susan Center (Jamestown) — Chautauqua County free community soup kitchen serving 100,000+ meals/year; daily hot lunch (Mon-Fri) and dinner (Mon-Thu) with no eligibility requirements, Backpack Program weekend child meals, holiday meal distribution, and emergency food bag take-out for Jamestown-area food-insecure veterans and residents." },
  { section: "L2", title: "Mental Health Association in Chautauqua County", cat: "mental-health", sub: "Counseling & Therapy", city: "Jamestown", website_url: "https://www.mhachautauqua.org/", source_name: "Mental Health Association in Chautauqua County NY Inc", source_type: "nonprofit", phone: "716-661-9044", address: "31 Water Street, Suite 7, Jamestown, NY 14701", zip: "14701", desc: "Mental Health Association in Chautauqua County (Jamestown) — Chautauqua County peer-run mental health advocacy and recovery nonprofit; Recovery Connection peer-support center, Open Door Crisis Respite (alternative to psychiatric hospitalization), Peer Workforce Development, Suicide Prevention Coalition, and Compeer 1-to-1 mentoring for adults with mental illness including Chautauqua County veterans." },

  // ============== L2 — NIAGARA FALLS (1) ==============
  { section: "L2", title: "Community Missions of Niagara Frontier", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Niagara Falls", website_url: "https://www.communitymissions.org/", source_name: "Community Missions Inc", source_type: "nonprofit", phone: "716-285-3403", address: "1570 Buffalo Avenue, Niagara Falls, NY 14303", zip: "14303", desc: "Community Missions of Niagara Frontier (Niagara Falls) — Niagara County's primary homeless services + behavioral health nonprofit since 1925; 84-bed emergency shelter for adults and families, Niagara Gospel Rescue Mission integration, OASAS-certified residential addiction treatment (Crisis Stabilization), OMH-certified outpatient mental health clinic, Youth Services, Veterans Initiative case management, and 365-day soup kitchen for Niagara Falls homeless veterans and residents." },

  // ============== L2 — NORTH COUNTRY (3) ==============
  { section: "L2", title: "Samaritan Medical Center (Watertown)", cat: "healthcare", sub: "Specialty Care", city: "Watertown", website_url: "https://www.samaritanhealth.com/", source_name: "Samaritan Health", source_type: "private_health_system", phone: "315-785-4000", address: "830 Washington Street, Watertown, NY 13601", zip: "13601", desc: "Samaritan Medical Center (Watertown) — independent Samaritan Health system 294-bed regional hospital serving Jefferson + Lewis + St Lawrence counties + Fort Drum military community; emergency department, family birthing center, cancer center, cardiac care, behavioral health (Mental Health Clinic + outpatient SUD), and TRICARE / VA Community Care for active-duty Fort Drum families and North Country veterans referred from Watertown CBOC." },
  { section: "L2", title: "Adirondack Health", cat: "healthcare", sub: "Specialty Care", city: "Saranac Lake", website_url: "https://www.adirondackhealth.org/", source_name: "Adirondack Health", source_type: "private_health_system", phone: "518-891-4141", address: "2233 State Route 86, Saranac Lake, NY 12983", zip: "12983", desc: "Adirondack Health (Saranac Lake) — Tri-Lakes (Saranac Lake / Lake Placid / Tupper Lake) + Adirondack Park hospital system; Adirondack Medical Center (97-bed flagship Saranac Lake), Mercy Living Center long-term care, Lake Placid Health and Medical Fitness Center, primary care + specialty clinics across the High Peaks region, and TRICARE / VA Community Care for Essex + Franklin county veterans referred from Plattsburgh CBOC + Albany VAMC." },
  { section: "L2", title: "Volunteer Transportation Center (Watertown)", cat: "transportation", sub: "Volunteer Driver Programs", city: "Watertown", website_url: "https://www.volunteertransportationcenter.org/contact/", source_name: "Volunteer Transportation Center Inc", source_type: "nonprofit", phone: "315-788-0422", address: "131 Court Street, Watertown, NY 13601", zip: "13601", desc: "Volunteer Transportation Center (VTC, Watertown) — North Country (Jefferson, Lewis, St Lawrence, Oswego, Hamilton, Herkimer, Otsego counties) volunteer-driver nonprofit; matches volunteer drivers with seniors, people with disabilities, veterans, and low-income residents needing rides to medical appointments (including VA Syracuse / Albany / Watertown CBOC), grocery, dialysis, and chemo; subsidized by NYS DOT 5310 + county aging funding." },
];

(async () => {
  await runSeed(ROWS, {
    state: "NY",
    commit: COMMIT,
    allowBrokenUrls: false,
    scriptName: "seed-ny-p5",
    batchTag: "ny-p5-2026-04-27",
    urlCheckTimeoutMs: 12000,
  });
})().catch((e) => { console.error(e); process.exit(1); });
