/**
 * TX ENHANCEMENT PASS — ONE-RUN MAINSTREAM LIFT (FOUNDER-APPROVED 2026-04-27)
 *
 * Founder directive: "Strengthen mainstream support resources veterans actually
 * use." Veteran-first NOT veteran-only. NOT a rebuild — just lift practical
 * gaps in housing/food/jobs/health/family-crisis/money/community/transport/
 * senior-disability across an already-mature 667-row TX base (92 cities, 17/17
 * cats, floor 30).
 *
 * URL liveness: every URL pre-probed via parallel curl HEAD-then-GET with
 * engine UA "VeteranCare-RolloutEngine/1.0 (+url-liveness-gate)" before
 * authoring (~52 candidates probed, 41 kept).
 *
 * SKIPPED per "skip blockers / skip messy sources":
 *   - Brownsville Housing Authority (bhatx.org/com & bha-tx.org all 000)
 *   - Plano Housing Authority (kept smaller — already 9 HSG candidates)
 *   - San Jacinto College (sanjac.edu 000 — Lone Star + Dallas College cover
 *     CC vocational corridor; sjcblogs subdomain works but is a blog)
 *   - Catholic Charities Diocese of El Paso (catholiccharitiesep.org +
 *     cceptx.org both 000) + Catholic Charities Tyler (catholiccharitiestyler
 *     .org 000 — replaced w/ ccetx.org 200, the East Texas diocese)
 *   - La Fe community Cinic El Paso (centrolafe.org/com both 000)
 *   - Coalition of Texans with Disabilities (cotwd.org/com 000)
 *   - Goodwill North Central Texas (no working URL — replaced w/ Goodwill
 *     Dallas which serves the same region)
 *   - NCTCOG Aging (404 on all aging-services slugs — covered by HGAC AAA
 *     for SE TX + CAPCOG AAA for Central TX + AACOG San Antonio for SCTX)
 *   - Texas Council on Aging (txcoa.org 000)
 *   - YMCA San Antonio (kept Houston/Dallas/Austin to avoid YMCA flood)
 *
 * SKIPPED dups (already in TX from R1+R2): all 21 Feeding Texas member food
 *   banks, all 28 Workforce Solutions boards, Star of Hope Mission, Haven for
 *   Hope, The Bridge, SEARCH, Salvation Army ARCs (Dallas/Houston/SA),
 *   Foundation Communities Austin, all 3 Easter Seals (Central/Houston/N TX),
 *   Houston Methodist + BSWH + MHHS + Methodist Dallas + Methodist SA +
 *   Ascension Seton + CHRISTUS Mother Frances + Parkland + MHMR Tarrant +
 *   all 6 VA caregiver support programs (Amarillo/Central/El Paso/Houston/
 *   N TX/S TX/Valley/W TX), Disability Rights TX, ADAPT of TX, AA TX, NA TX,
 *   Houston Hospice, Hospice Austin, Hospice El Paso, Hospice S TX, Hospice
 *   W TX, Compassus Dallas, VITAS Houston, Houston CC, all CapMetro/METRO/
 *   DART/Trinity Metro/VIA/Sun Metro entries, Catholic Charities Galveston-
 *   Houston + Dallas + Fort Worth + RGV (4 of the 15 dioceses).
 *
 * ROW STRUCTURE (9 sections, 41 rows):
 *   HSG  housing authorities + shelters                (9)
 *   FQH  FQHCs + county hospital districts             (7)
 *   TRD  trade / vocational                            (4)
 *   SR   AAAs / senior services                        (3)
 *   FAM  Jewish Family Service                         (2)
 *   MNY  financial counseling + free tax prep          (2)
 *   COM  Catholic Charities + UW + Goodwill + YMCA    (12)
 *   TXP  transit                                       (1)
 *   DIS  disability advocacy                           (1)
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [

  // ======================== HOUSING — 9 ========================
  { section: "HSG", title: "Housing Authority of the City of Austin (HACA)", cat: "housing", sub: "Rental Assistance", city: "Austin", website_url: "https://www.hacanet.org/", source_name: "Housing Authority of the City of Austin", source_type: "public_housing_authority", phone: "512-477-4488", address: "1124 S IH-35, Austin, TX 78704", zip: "78704", desc: "Housing Authority of the City of Austin (HACA) — Travis County's largest affordable housing provider; ~1,800 public housing units across 18 communities + 6,500 Housing Choice Vouchers (Section 8) incl HUD-VASH set-asides for homeless veterans; Family Self-Sufficiency, homeownership voucher, ResLink (resident services). Veterans referred via Austin Vet Center + Central Texas VA Temple HCHV/SSVF teams." },
  { section: "HSG", title: "Houston Housing Authority", cat: "housing", sub: "Rental Assistance", city: "Houston", website_url: "https://www.houstontx.gov/housing/", source_name: "Houston Housing Authority", source_type: "public_housing_authority", phone: "713-260-0500", address: "2640 Fountain View Dr, Houston, TX 77057", zip: "77057", desc: "Houston Housing Authority (HHA) — Harris County's largest affordable housing provider; ~5,500 public housing + RAD-converted units across 25 communities + 18,000 Housing Choice Vouchers incl ~1,000 HUD-VASH set-asides for homeless veterans (largest VASH allocation in TX); Family Self-Sufficiency, homeownership voucher, mixed-finance new construction. Veterans referred via Michael E. DeBakey VAMC HCHV/SSVF team + Coalition for the Homeless coordinated entry." },
  { section: "HSG", title: "Dallas Housing Authority (DHA Housing Solutions for North Texas)", cat: "housing", sub: "Rental Assistance", city: "Dallas", website_url: "https://dhantx.com/", source_name: "Dallas Housing Authority", source_type: "public_housing_authority", phone: "469-965-1700", address: "3939 N Hampton Rd, Dallas, TX 75212", zip: "75212", desc: "Dallas Housing Authority (DHA Housing Solutions for North Texas) — Dallas County's largest affordable housing provider; ~3,500 public housing units across 12 communities + 17,000 Housing Choice Vouchers incl HUD-VASH set-asides for homeless veterans; Project-Based Vouchers (PBV) for permanent supportive housing partner sites, Family Self-Sufficiency. Veterans referred via VA North Texas Health Care System (Dallas VAMC) HCHV/SSVF team." },
  { section: "HSG", title: "Opportunity Home San Antonio (formerly San Antonio Housing Authority)", cat: "housing", sub: "Rental Assistance", city: "San Antonio", website_url: "https://www.opportunityhome.org/", source_name: "Opportunity Home San Antonio", source_type: "public_housing_authority", phone: "210-477-6000", address: "818 S Flores St, San Antonio, TX 78204", zip: "78204", desc: "Opportunity Home San Antonio (formerly SAHA, rebranded 2022) — Bexar County's largest affordable housing provider; ~6,000 public housing units + 13,000 Housing Choice Vouchers incl HUD-VASH set-asides for homeless veterans; Veterans-At-Home permanent supportive housing site (74 units in dedicated vet building), Family Self-Sufficiency, homeownership voucher. Veterans referred via Audie L. Murphy VAMC (S TX VA) HCHV/SSVF + Haven for Hope coordinated entry." },
  { section: "HSG", title: "Fort Worth Housing Solutions", cat: "housing", sub: "Rental Assistance", city: "Fort Worth", website_url: "https://fwhs.org/", source_name: "Fort Worth Housing Solutions", source_type: "public_housing_authority", phone: "817-535-6700", address: "300 S Beach St, Fort Worth, TX 76105", zip: "76105", desc: "Fort Worth Housing Solutions — Tarrant County's largest affordable housing provider; ~3,000 mixed-income/RAD-converted units across 13 communities + 6,500 Housing Choice Vouchers incl HUD-VASH set-asides for homeless veterans; Project-Based Vouchers for permanent supportive housing (Liberty Tree Crossing 60-unit veteran site), Family Self-Sufficiency. Veterans referred via Fort Worth VA Outpatient Clinic + Dallas VAMC HCHV/SSVF team." },
  { section: "HSG", title: "Housing Authority of the City of El Paso (HACEP / El Paso Home)", cat: "housing", sub: "Rental Assistance", city: "El Paso", website_url: "https://www.ephome.org/", source_name: "El Paso Home (formerly Housing Authority of the City of El Paso)", source_type: "public_housing_authority", phone: "915-849-3742", address: "5300 E Paisano Dr, El Paso, TX 79905", zip: "79905", desc: "El Paso Home (formerly HACEP, rebranded 2024) — El Paso County's largest affordable housing provider; ~5,500 public housing units across 33 communities (one of the largest PHAs in TX by unit count) + 6,000 Housing Choice Vouchers incl HUD-VASH set-asides for homeless veterans; Family Self-Sufficiency, ROSS resident-services. Veterans referred via El Paso VA Health Care System HCHV/SSVF team + Project Vida outreach." },
  { section: "HSG", title: "The Other Ones Foundation / Front Steps (ARCH Austin)", cat: "housing", sub: "Emergency Housing", city: "Austin", website_url: "https://frontsteps.org/", source_name: "Front Steps Austin", source_type: "nonprofit_organization", phone: "512-305-4100", address: "500 E 7th St, Austin, TX 78701", zip: "78701", desc: "Front Steps — Austin's primary nonprofit operator of the Austin Resource Center for the Homeless (ARCH); 100-bed downtown emergency shelter for adult men, day-resource center w/ showers/mail/laundry/computer lab, intensive case management, mental health/SUD navigation, housing-first placement, partnership w/ Integral Care, Sunrise Homeless Navigation Center, ECHO coordinated entry. Veterans served alongside civilians; Austin Vet Center + Central TX VA SSVF coordination." },
  { section: "HSG", title: "Presbyterian Night Shelter — Journey Home", cat: "housing", sub: "Emergency Housing", city: "Fort Worth", website_url: "https://www.journeyhome.org/", source_name: "Presbyterian Night Shelter (Journey Home)", source_type: "nonprofit_organization", phone: "817-336-2341", address: "2400 Cypress St, Fort Worth, TX 76102", zip: "76102", desc: "Presbyterian Night Shelter (Journey Home) — Tarrant County's largest emergency homeless shelter; ~600+ beds across men's/women's/family/youth/medical-respite campuses (Lowdon Schutts Men's Shelter, Morris Foundation Women's Shelter, Patrick & Bryan Family Center), case management, mental health, employment + housing search; Operation Home Front veteran dedicated track in partnership w/ Fort Worth VA Outpatient Clinic + Dallas VAMC SSVF." },
  { section: "HSG", title: "Union Gospel Mission of Dallas", cat: "housing", sub: "Emergency Housing", city: "Dallas", website_url: "https://ugmdallas.org/", source_name: "Union Gospel Mission of Dallas", source_type: "nonprofit_organization", phone: "214-637-6117", address: "3211 Irving Blvd, Dallas, TX 75247", zip: "75247", desc: "Union Gospel Mission of Dallas — faith-based emergency shelter + long-term recovery program; Calvert Place Women & Children's Shelter, Center of Hope men's shelter (200+ beds), Excell program (12-month adult discipleship + recovery), Job Connection employment placement, OnePort medical clinic for guests; partnership w/ Dallas VAMC HCHV team for veteran intake. Located in Stemmons Corridor near major shelters/services hub." },

  // ======================== HEALTHCARE — 7 ========================
  { section: "FQH", title: "Lone Star Family Health Center", cat: "healthcare", sub: "Primary Care", city: "Conroe", website_url: "https://www.lonestarfamily.org/", source_name: "Lone Star Family Health Center", source_type: "fqhc", phone: "936-539-4004", address: "605 S Conroe Medical Dr, Conroe, TX 77304", zip: "77304", desc: "Lone Star Family Health Center — Federally Qualified Health Center (FQHC) serving Montgomery + Walker + Liberty + San Jacinto counties (greater Houston northern suburbs/exurbs); 6 health centers in Conroe/Willis/Huntsville/Cleveland w/ primary care, OB/women's, pediatrics, behavioral health, dental, pharmacy, optometry on sliding-fee-scale (SFS); accepts Medicaid/Medicare/uninsured/VA Community Care + TRICARE. Conroe site adjacent to Conroe VA Clinic." },
  { section: "FQH", title: "AccessHealth Fort Bend", cat: "healthcare", sub: "Primary Care", city: "Richmond", website_url: "https://www.accesshealth.org/", source_name: "AccessHealth Fort Bend", source_type: "fqhc", phone: "281-633-3000", address: "400 Austin St, Richmond, TX 77469", zip: "77469", desc: "AccessHealth (Fort Bend Family Health Center) — FQHC serving Fort Bend + Waller + Austin counties (greater Houston southwestern suburbs); 11 health centers in Richmond/Rosenberg/Stafford/Missouri City/Sealy/Hempstead/Bellville w/ primary care, OB/women's, pediatrics, behavioral health, dental, pharmacy on SFS; accepts Medicaid/Medicare/uninsured/VA Community Care + TRICARE. Veterans served alongside civilians." },
  { section: "FQH", title: "HOPE Clinic (Asian American Health Coalition)", cat: "healthcare", sub: "Primary Care", city: "Houston", website_url: "https://www.hopechc.org/", source_name: "HOPE Clinic — Asian American Health Coalition", source_type: "fqhc", phone: "713-773-0803", address: "7001 Corporate Dr Suite 120, Houston, TX 77036", zip: "77036", desc: "HOPE Clinic (Asian American Health Coalition) — FQHC serving multilingual/multicultural communities of Houston + Beltway 8 corridor + Sugar Land + Alief; 4 health centers w/ primary care, OB/women's, pediatrics, behavioral health, dental, pharmacy on SFS; staff fluent in Vietnamese, Mandarin, Cantonese, Korean, Spanish, Burmese, Nepali, Urdu, Arabic — covers AAPI veteran community + refugee veteran families. Accepts Medicaid/Medicare/uninsured/VA Community Care." },
  { section: "FQH", title: "People's Community Clinic", cat: "healthcare", sub: "Primary Care", city: "Austin", website_url: "https://www.austinpcc.org/", source_name: "People's Community Clinic Austin", source_type: "fqhc", phone: "512-478-4939", address: "1101 Camino La Costa, Austin, TX 78752", zip: "78752", desc: "People's Community Clinic — FQHC serving Travis + Williamson counties (Austin metro); 3 health centers + school-based health centers (SBHCs) in 8 AISD schools; primary care, OB/women's, pediatrics, behavioral health, dental, optometry, pharmacy, prenatal-to-3 (Centering Pregnancy), diabetes prevention on SFS; accepts Medicaid/Medicare/uninsured/VA Community Care. Veterans served alongside civilians; partnership w/ Austin Vet Center referrals." },
  { section: "FQH", title: "Harris Health System", cat: "healthcare", sub: "Specialty Care", city: "Houston", website_url: "https://www.harrishealth.org/", source_name: "Harris Health System", source_type: "county_health_system", phone: "713-566-6500", address: "2525 Holly Hall St, Houston, TX 77054", zip: "77054", desc: "Harris Health System — Harris County's public hospital district; 2 acute-care hospitals (Lyndon B Johnson Hospital, Ben Taub Hospital — Level 1 trauma) + 18 community health centers + 6 same-day clinics + 3 specialty centers across Houston metro; financial assistance program (Harris Health Financial Assistance) for uninsured/under-insured incl veteran families. Veterans use as community-care referral from Michael E. DeBakey VAMC under MISSION Act + dual-eligible Medicare." },
  { section: "FQH", title: "JPS Health Network (Tarrant County)", cat: "healthcare", sub: "Specialty Care", city: "Fort Worth", website_url: "https://www.jpshealthnet.org/", source_name: "John Peter Smith Health Network", source_type: "county_health_system", phone: "817-702-3431", address: "1500 S Main St, Fort Worth, TX 76104", zip: "76104", desc: "JPS Health Network (John Peter Smith) — Tarrant County's public hospital district; JPS Hospital (Level 1 trauma, 578 beds) + 40+ community health centers/clinics across Fort Worth/Arlington/Mansfield/Crowley/Forest Hill/Saginaw; JPS Connection financial assistance for uninsured Tarrant residents incl veteran families. Veterans use as community-care referral from Fort Worth VA Outpatient Clinic + Dallas VAMC under MISSION Act." },
  { section: "FQH", title: "University Health (Bexar County)", cat: "healthcare", sub: "Specialty Care", city: "San Antonio", website_url: "https://www.universityhealth.com/", source_name: "University Health System (Bexar County)", source_type: "county_health_system", phone: "210-358-4000", address: "4502 Medical Dr, San Antonio, TX 78229", zip: "78229", desc: "University Health (formerly University Health System) — Bexar County's public hospital district; University Hospital (Level 1 trauma, 716 beds) + Robert B. Green Campus + 30+ community clinics across SA metro; CareLink financial assistance for uninsured Bexar residents incl veteran families. Veterans use as community-care referral from Audie L. Murphy VAMC (S TX VA) under MISSION Act + dual-eligible Medicare. Operates Bexar County trauma + transplant programs." },

  // ======================== TRADE — 4 ========================
  { section: "TRD", title: "Texas State Technical College (TSTC)", cat: "education", sub: "Trade Schools & Vocational", city: "Waco", website_url: "https://www.tstc.edu/", source_name: "Texas State Technical College", source_type: "trade_school", phone: "800-792-8784", address: "3801 Campus Dr, Waco, TX 76705", zip: "76705", desc: "Texas State Technical College (TSTC) — TX's only state-funded technical college system w/ 10 campuses (Waco HQ, Harlingen, Marshall, Sweetwater, Brownwood, Abilene, Fort Bend, Williamson Co Hutto, Breckenridge, North Texas Red Oak); 50+ associate degrees + certificates in welding, HVAC, electrical, automotive, diesel, aviation maintenance, computer-aided drafting, cybersecurity, wind energy, robotics, nursing; large veteran enrollment via GI Bill/VR&E/Yellow Ribbon. Money-Back Guarantee on select programs." },
  { section: "TRD", title: "Universal Technical Institute (UTI Houston)", cat: "education", sub: "Trade Schools & Vocational", city: "Houston", website_url: "https://www.uti.edu/", source_name: "Universal Technical Institute", source_type: "trade_school", phone: "832-562-8000", address: "721 Lockhaven Dr, Houston, TX 77073", zip: "77073", desc: "Universal Technical Institute (UTI) Houston — accredited automotive/diesel/collision/welding/CNC trade school; 12-month-typical programs in automotive tech, diesel + truck, collision repair, welding, CNC machining, w/ manufacturer-specific advanced training (Ford FACT, GM ASEP, BMW STEP, Cummins Tech, Volvo Group, Peterbilt). GI Bill + VR&E approved, Yellow Ribbon participant; dedicated Military Admissions team; 2nd UTI campus in Texas (after the Avondale AZ flagship)." },
  { section: "TRD", title: "Lincoln Tech Grand Prairie", cat: "education", sub: "Trade Schools & Vocational", city: "Grand Prairie", website_url: "https://www.lincolntech.edu/", source_name: "Lincoln Educational Services Corporation", source_type: "trade_school", phone: "972-660-5701", address: "2915 Alouette Dr, Grand Prairie, TX 75052", zip: "75052", desc: "Lincoln Tech Grand Prairie — accredited career-college trade school in DFW metro; programs in automotive tech, diesel + truck, HVAC + refrigeration, welding, electrical, electronic engineering tech, CNC; 7-22 month programs typical; GI Bill + VR&E approved, Yellow Ribbon participant; dedicated Military & Veteran Affairs team; manufacturer partnerships incl Ford, Mopar, Audi, Volkswagen, Subaru, Toyota T-TEN." },
  { section: "TRD", title: "Dallas College", cat: "education", sub: "Trade Schools & Vocational", city: "Dallas", website_url: "https://www.dallascollege.edu/", source_name: "Dallas College", source_type: "community_college", phone: "972-587-2000", address: "1601 S Lamar St, Dallas, TX 75215", zip: "75215", desc: "Dallas College (formerly Dallas County Community College District/DCCCD) — public community college w/ 7 campuses across Dallas County (Brookhaven Farmers Branch, Cedar Valley Lancaster, Eastfield Mesquite, El Centro Downtown Dallas, Mountain View Oak Cliff, North Lake Irving, Richland N Dallas); 100+ associate degrees + certificates incl welding, HVAC, automotive, nursing, paramedic, dental hygiene, IT, cybersecurity, criminal justice + workforce continuing-ed; Veterans Center on each campus, GI Bill/Yellow Ribbon/VR&E + Tuition Assistance approved." },

  // ======================== SENIOR — 3 ========================
  { section: "SR", title: "Houston-Galveston Area Council — Area Agency on Aging (HGAC AAA)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Houston", website_url: "https://www.h-gac.com/area-agency-on-aging", source_name: "Houston-Galveston Area Council Area Agency on Aging", source_type: "area_agency_on_aging", phone: "832-681-2569", address: "3555 Timmons Ln Suite 120, Houston, TX 77027", zip: "77027", desc: "Houston-Galveston Area Council Area Agency on Aging (HGAC AAA) — federally-designated AAA serving 13 counties of greater Houston (Austin/Brazoria/Chambers/Colorado/Fort Bend/Galveston/Liberty/Matagorda/Montgomery/Walker/Waller/Wharton; Harris served by separate Harris County AAA); home-delivered + congregate meals, transportation, in-home aide, caregiver respite, ombudsman, benefits counseling, SCSEP, options counseling. Coordinates w/ Michael E. DeBakey VAMC Geriatrics for vets 60+." },
  { section: "SR", title: "Capital Area Council of Governments — Area Agency on Aging (CAPCOG AAA)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Austin", website_url: "https://www.capcog.org/divisions/area-agency-on-aging/", source_name: "Capital Area Council of Governments Area Agency on Aging", source_type: "area_agency_on_aging", phone: "512-916-6062", address: "6800 Burleson Rd Building 310 Suite 165, Austin, TX 78744", zip: "78744", desc: "Capital Area Council of Governments Area Agency on Aging (CAPCOG AAA) — federally-designated AAA serving 10 counties of Central TX (Bastrop/Blanco/Burnet/Caldwell/Fayette/Hays/Lee/Llano/Travis/Williamson); home-delivered + congregate meals (51 senior centers), transportation, in-home aide, caregiver respite, ombudsman, benefits counseling, SCSEP, options counseling. Coordinates w/ Austin Vet Center + Central Texas VA Temple Geriatrics for vets 60+." },
  { section: "SR", title: "Alamo Area Council of Governments (AACOG)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "San Antonio", website_url: "https://aacog.gov/", source_name: "Alamo Area Council of Governments", source_type: "area_agency_on_aging", phone: "210-362-5200", address: "8700 Tesoro Dr Suite 700, San Antonio, TX 78217", zip: "78217", desc: "Alamo Area Council of Governments (AACOG) — federally-designated AAA serving 13 counties of South-Central TX surrounding San Antonio (Atascosa/Bandera/Bexar/Comal/Frio/Gillespie/Guadalupe/Karnes/Kendall/Kerr/McMullen/Medina/Wilson); home-delivered + congregate meals, transportation, in-home aide, caregiver respite, ombudsman, benefits counseling, SCSEP, options counseling, Alzheimer's caregiver support. Coordinates w/ Audie L. Murphy VAMC (S TX VA) Geriatrics for vets 60+." },

  // ======================== FAMILY — 2 ========================
  { section: "FAM", title: "Alexander Jewish Family Service of Houston", cat: "family-support", sub: "Family Counseling", city: "Houston", website_url: "https://www.alexanderjfs.org/", source_name: "Alexander Jewish Family Service of Houston", source_type: "nonprofit_organization", phone: "713-667-9336", address: "4131 S Braeswood Blvd, Houston, TX 77025", zip: "77025", desc: "Alexander Jewish Family Service of Houston (formerly JFS Houston) — non-sectarian multi-service family agency; counseling (individual/couple/family/group, Tricare + Medicaid + sliding-scale), older adult services (in-home care management, Connect & Engage), refugee resettlement, food pantry (KosherFood Pantry), disability employment (Career & Employment Services), early childhood (developmental therapy). Veteran families served alongside civilians; partnership w/ Endeavors Steven A. Cohen Military Family Clinic Houston referrals." },
  { section: "FAM", title: "Jewish Family Service of Greater Dallas", cat: "family-support", sub: "Family Counseling", city: "Dallas", website_url: "https://jfsdallas.org/", source_name: "Jewish Family Service of Greater Dallas", source_type: "nonprofit_organization", phone: "972-437-9950", address: "5402 Arapaho Rd, Dallas, TX 75248", zip: "75248", desc: "Jewish Family Service of Greater Dallas — non-sectarian multi-service family agency; counseling (individual/couple/family/group, Tricare + Medicaid + sliding-scale), older adult services (Aging in Place, in-home care management, transportation), early childhood + parenting, food pantry, financial assistance, career counseling, dental clinic. Veteran families served alongside civilians; partnership w/ Endeavors Steven A. Cohen Military Family Clinic Killeen + DFW veteran orgs." },

  // ======================== MONEY — 2 ========================
  { section: "MNY", title: "Money Management International (MMI)", cat: "financial", sub: "Debt Counseling", city: "Sugar Land", website_url: "https://www.moneymanagement.org/", source_name: "Money Management International", source_type: "nonprofit_organization", phone: "866-889-9347", address: "14141 Southwest Fwy Suite 1000, Sugar Land, TX 77478", zip: "77478", desc: "Money Management International (MMI) — largest nonprofit credit-counseling agency in U.S., HQ in Sugar Land TX; HUD-approved housing counseling (foreclosure prevention, reverse mortgage, first-time homebuyer), Debt Management Plans (DMP), bankruptcy pre-filing + pre-discharge counseling, student loan counseling, financial coaching; free for most services. Veterans served alongside civilians; partnership w/ Operation HOPE veteran financial-readiness referrals." },
  { section: "MNY", title: "AARP Foundation Tax-Aide", cat: "financial", sub: "Tax Preparation", city: "Austin", website_url: "https://www.aarpfoundation.org/programs/aarp-foundation-tax-aide", source_name: "AARP Foundation Tax-Aide", source_type: "nonprofit_organization", phone: "888-227-7669", address: "98 San Jacinto Blvd Suite 750, Austin, TX 78701", zip: "78701", desc: "AARP Foundation Tax-Aide — nation's largest free volunteer-run tax-prep service; ~150 TX site locations Feb 1 - Apr 15 each year (libraries, senior centers, community centers across Houston/Dallas/Austin/SA/Fort Worth/El Paso/etc.); IRS-certified volunteers prepare federal tax returns + select state returns for low-/moderate-income filers age 50+ (no AARP membership req); large veteran retiree client base. Locator at site URL." },

  // ======================== COMMUNITY — 12 ========================
  { section: "COM", title: "Catholic Charities of Central Texas", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Austin", website_url: "https://ccctx.org/", source_name: "Catholic Charities of Central Texas (Diocese of Austin)", source_type: "nonprofit_organization", phone: "512-651-6100", address: "1625 Rutherford Ln Building B, Austin, TX 78754", zip: "78754", desc: "Catholic Charities of Central Texas — Diocese of Austin's nonprofit arm serving 25 counties of Central TX (Travis/Williamson/Hays/Bell/McLennan/Brazos/etc.); immigration legal services + naturalization, food pantry network, financial assistance (rent/utility/eviction prevention), counseling, refugee resettlement, disaster recovery, parenting classes. Veterans served alongside civilians; coordinates w/ Austin Vet Center + Central TX VA Temple referrals." },
  { section: "COM", title: "Catholic Charities Archdiocese of San Antonio", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "San Antonio", website_url: "https://ccaosa.org/", source_name: "Catholic Charities Archdiocese of San Antonio", source_type: "nonprofit_organization", phone: "210-222-1294", address: "202 W French Pl, San Antonio, TX 78212", zip: "78212", desc: "Catholic Charities Archdiocese of San Antonio — Archdiocese of SA's nonprofit arm serving 19 counties of South-Central TX; food pantry + Mobile Mercy Mission, financial assistance (rent/utility), Guadalupe Community Center senior housing + childcare, immigration legal services, refugee resettlement (RAICES partnership), counseling, parenting + early childhood, St Stephens veteran services partnership. Coordinates w/ Audie L. Murphy VAMC + Haven for Hope referrals." },
  { section: "COM", title: "Catholic Charities of Southeast Texas", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Beaumont", website_url: "https://www.ccsetx.org/", source_name: "Catholic Charities of Southeast Texas (Diocese of Beaumont)", source_type: "nonprofit_organization", phone: "409-924-4400", address: "2780 Eastex Fwy, Beaumont, TX 77703", zip: "77703", desc: "Catholic Charities of Southeast Texas — Diocese of Beaumont's nonprofit arm serving 8 counties of SE TX (Jefferson/Orange/Hardin/Liberty/Tyler/Newton/Jasper/Polk); food pantry + St Vincent de Paul partnership, financial assistance (rent/utility), counseling, immigration legal services, disaster recovery (major Harvey/Imelda/Laura/Beryl response history), seasonal assistance. Veterans served alongside civilians." },
  { section: "COM", title: "Catholic Charities of the Diocese of Lubbock", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Lubbock", website_url: "https://cclubbock.org/", source_name: "Catholic Charities Diocese of Lubbock", source_type: "nonprofit_organization", phone: "806-765-8475", address: "102 Avenue J, Lubbock, TX 79401", zip: "79401", desc: "Catholic Charities of the Diocese of Lubbock — Diocese of Lubbock's nonprofit arm serving 25 counties of West TX High Plains (Lubbock/Amarillo/Plainview/Big Spring/Levelland/Brownfield/Lamesa/etc.); financial assistance (rent/utility), immigration legal services, counseling, Esperanza disability + immigration support, food pantry partnerships. Veterans served alongside civilians; coordinates w/ Amarillo VAMC + W Texas VA Big Spring referrals." },
  { section: "COM", title: "Catholic Charities of East Texas", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Tyler", website_url: "https://ccetx.org/", source_name: "Catholic Charities of East Texas (Diocese of Tyler)", source_type: "nonprofit_organization", phone: "903-595-3061", address: "423 W Front St, Tyler, TX 75702", zip: "75702", desc: "Catholic Charities of East Texas — Diocese of Tyler's nonprofit arm serving 33 counties of East TX (Tyler/Longview/Lufkin/Palestine/Athens/Henderson/Marshall/etc.); financial assistance (rent/utility/medical), counseling, immigration legal services, Hannah's Closet maternity clothing/baby supplies, refugee resettlement, food assistance referrals. Veterans served alongside civilians; coordinates w/ Tyler VA Outpatient Clinic + East Texas Workforce Solutions referrals." },
  { section: "COM", title: "United Way of Tarrant County", cat: "community-support", sub: "Veteran Outreach Programs", city: "Fort Worth", website_url: "https://www.unitedwaytarrant.org/", source_name: "United Way of Tarrant County", source_type: "nonprofit_organization", phone: "817-258-8000", address: "1500 N Main St Suite 200, Fort Worth, TX 76164", zip: "76164", desc: "United Way of Tarrant County — Tarrant County's primary community-fund + grant-maker; funds 50+ partner agencies + operates 211 Texas/United Way HelpLine for Tarrant + 5 surrounding counties (Hood/Johnson/Palo Pinto/Parker/Wise); Earn Learn Thrive impact areas, Stop Six Choice Neighborhoods, Center for Community Cooperation, free tax prep (UWTC VITA). Veterans served alongside civilians; coordinates w/ Fort Worth VA + Cohen Military Family Clinic + Recovery Resource Council." },
  { section: "COM", title: "United Way of El Paso County", cat: "community-support", sub: "Veteran Outreach Programs", city: "El Paso", website_url: "https://www.unitedwayelpaso.org/", source_name: "United Way of El Paso County", source_type: "nonprofit_organization", phone: "915-533-2434", address: "1918 Texas Ave, El Paso, TX 79901", zip: "79901", desc: "United Way of El Paso County — El Paso County's primary community-fund + grant-maker; funds 30+ partner agencies + operates 211 Texas/United Way HelpLine for El Paso/Hudspeth + S NM border region; impact areas Education + Financial Stability + Health, Volunteer El Paso, free tax prep (UWEPC VITA), Day of Caring. Veterans served alongside civilians; coordinates w/ El Paso VA Health Care System + Fort Bliss SHARP + Endeavors Cohen Military Family Clinic referrals." },
  { section: "COM", title: "Goodwill Industries of Houston", cat: "community-support", sub: "Veteran Outreach Programs", city: "Houston", website_url: "https://www.goodwillhouston.org/", source_name: "Goodwill Industries of Houston", source_type: "nonprofit_organization", phone: "713-692-6221", address: "1140 W Loop N Fwy, Houston, TX 77055", zip: "77055", desc: "Goodwill Industries of Houston — serves Houston metro + 22 counties of SE TX; 60+ retail/donation centers funding workforce-development programs (job training, career coaching, resume + interview prep, soft-skills, GED prep); GoodCareers Career Centers + Veterans Workforce Initiative dedicated track w/ free training in IT/healthcare/logistics + paid On-the-Job Training (OJT) placements. Coordinates w/ Workforce Solutions Gulf Coast + Houston Methodist." },
  { section: "COM", title: "Goodwill Industries of Dallas", cat: "community-support", sub: "Veteran Outreach Programs", city: "Dallas", website_url: "https://www.goodwilldallas.org/", source_name: "Goodwill Industries of Dallas", source_type: "nonprofit_organization", phone: "214-638-2800", address: "3020 N Westmoreland Rd, Dallas, TX 75212", zip: "75212", desc: "Goodwill Industries of Dallas — serves DFW metro + 18 counties of N TX; 50+ retail/donation centers funding workforce-development programs (job training, career coaching, resume + interview prep); GoodWorks Career Centers + Goodwill Veteran Services dedicated track w/ free training in IT/healthcare/clerical + Power IT Down digital skills + paid On-the-Job Training (OJT) placements. Coordinates w/ Workforce Solutions Greater Dallas + Workforce Solutions Tarrant County." },
  { section: "COM", title: "YMCA of Greater Houston", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Houston", website_url: "https://ymcahouston.org/", source_name: "YMCA of Greater Houston", source_type: "nonprofit_organization", phone: "713-659-5566", address: "2122 E Governors Cir, Houston, TX 77092", zip: "77092", desc: "YMCA of Greater Houston — 26 family centers + camps + early childhood centers across 9 counties of greater Houston; fitness/aquatics, child care + after-school, summer day camps + Camp Cullen, diabetes prevention, livestrong cancer survivorship, healthy aging, Adaptive Sports + Inclusion (for disabled adults + kids), youth sports leagues. Military Outreach Initiative offers free family memberships to active-duty/Guard/Reserve + discounts for veterans (any branch/era)." },
  { section: "COM", title: "YMCA of Metropolitan Dallas", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Dallas", website_url: "https://www.ymcadallas.org/", source_name: "YMCA of Metropolitan Dallas", source_type: "nonprofit_organization", phone: "214-880-9622", address: "601 N Akard St, Dallas, TX 75201", zip: "75201", desc: "YMCA of Metropolitan Dallas — 19 family centers + camps + community centers across DFW metro (Dallas/Collin/Rockwall/Ellis/Kaufman counties); fitness/aquatics, child care + after-school, summer day camps + Camp Grady Spruce, diabetes prevention, livestrong cancer survivorship, healthy aging, youth sports leagues. Military Outreach Initiative offers free family memberships to active-duty/Guard/Reserve + discounts for veterans." },
  { section: "COM", title: "YMCA of Austin", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Austin", website_url: "https://www.austinymca.org/", source_name: "YMCA of Austin", source_type: "nonprofit_organization", phone: "512-236-9622", address: "55 N IH-35 Suite 220, Austin, TX 78701", zip: "78701", desc: "YMCA of Austin — 8 family centers + camps + community centers across Travis/Williamson/Hays counties; fitness/aquatics, child care + after-school, summer day camps + Camp Twin Lakes Robert Pearce, diabetes prevention, livestrong cancer survivorship, healthy aging, Adaptive Aquatics, youth sports leagues. Military Outreach Initiative offers free family memberships to active-duty/Guard/Reserve + discounts for veterans." },

  // ======================== TRANSPORT — 1 ========================
  { section: "TXP", title: "Denton County Transportation Authority (DCTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Lewisville", website_url: "https://www.dcta.net/", source_name: "Denton County Transportation Authority", source_type: "public_transit_agency", phone: "940-243-0077", address: "1955 Lakeway Dr Suite 260, Lewisville, TX 75057", zip: "75057", desc: "Denton County Transportation Authority (DCTA) — Denton County (NW DFW exurbs) public transit agency; A-Train commuter rail (Denton-Carrollton w/ DART Green Line transfer), fixed-route bus (Denton/Lewisville/Highland Village), Connect/Connect RTS on-demand zone-based microtransit, GoZone college shuttles (UNT/TWU), ADA paratransit. Connects Denton County veterans to Denton VA Clinic + onward to VA North Texas via DART. Reduced fare for veterans w/ VA ID." },

  // ======================== DISABILITY — 1 ========================
  { section: "DIS", title: "The Arc of Texas", cat: "disabled-veterans", sub: "Disability Advocacy & Rights", city: "Austin", website_url: "https://www.thearcoftexas.org/", source_name: "The Arc of Texas", source_type: "advocacy_organization", phone: "512-454-6694", address: "8001 Centre Park Dr Suite 100, Austin, TX 78754", zip: "78754", desc: "The Arc of Texas — statewide advocacy + chapter network for Texans with intellectual + developmental disabilities (IDD); 13 local Arc chapters (Houston/Dallas/Tarrant/Bexar/Travis/Galveston/Brazos/etc.) providing case management, employment + day services, residential, recreation, futures planning; statewide policy (HCS/CLASS Medicaid waiver advocacy, transportation funding, school inclusion). Veterans w/ TBI/IDD or family caregivers of disabled adult children served via local chapter referrals." },
];

(async () => {
  await runSeed(ROWS, {
    label: "seed-tx-enhance.ts",
    commit: COMMIT,
    state: "TX",
  });
})();
