/**
 * OH ENHANCEMENT PASS — ONE-RUN MAINSTREAM LIFT (FOUNDER-APPROVED 2026-04-27)
 *
 * Founder directive: "Strengthen mainstream support resources veterans actually
 * use." Veteran-first NOT veteran-only. NOT a rebuild — just lift practical
 * gaps in housing/food/jobs/health/family-crisis/money/community/transport/
 * senior-disability across an already-mature 512-row OH base.
 *
 * URL liveness: every URL pre-probed via parallel curl HEAD-then-GET with
 * engine UA "VeteranCare-RolloutEngine/1.0 (+url-liveness-gate)" before
 * authoring. SKIPPED per founder "skip blockers / skip messy sources":
 *   - per-county OhioMeansJobs subdomain slugs (omjsummit, omjmahoning,
 *     omjmontgomery, omjcuyahoga, ohiomeansjobsstark, etc.) — 000 connection
 *     refused; statewide OhioMeansJobs already covered + several county OMJs
 *     (Cleveland-Cuyahoga, Cuyahoga, Franklin, Mahoning Career Tech, Miami
 *     Valley Works) already in DB
 *   - Columbus Housing Authority slug (columbusha.org 000) — covered by
 *     statewide Ohio CDC Assn / New Housing Ohio
 *   - Toledo Housing Authority slug (toledoha.org 000) — Lucas Met Housing
 *     (LMHA) already in DB
 *   - Catholic Charities Diocese of Columbus (colscatholiccharities.org 000)
 *     — Catholic Charities of Ohio statewide already in DB
 *   - per-corps Salvation Army subdomains (norwesterhio, opens, etc.) —
 *     UA hard-block; NE Ohio + Central + Ohio HQ + NE Division already in DB
 *   - county ADAMHS boards (summitcountybh, miamicountymha, amhamb,
 *     adamhsmcw, adamhscc 403) — Cuyahoga + Franklin + Montgomery already in
 *     DB; statewide MHA Ohio + OACBHA covers advocacy layer
 *   - LSS Ohio root (lsohio.org 000) — replaced with LSS Network of Hope
 *     (lssnetworkofhope.org 200) for Central OH coverage
 *   - ohiomeansjobs.com / omj.ohio.gov — statewide portal already in DB
 *   - Ohio Caregiver Coalition (ohiocaregiver.org 000) — statewide caregiver
 *     gap left for VA Caregiver Support already in DB
 *   - Recovery Ohio (recoveryohio.gov 404) — gov portal moved; Ohio MHAS
 *     statewide already in DB
 *
 * SKIPPED dups (already in OH from P1–P5): Aultman, Summa Health, OhioHealth,
 *   Cleveland Clinic, University Hospitals, Kettering Health, Mercy Health
 *   Cincinnati, Bluffton Hospital, ProMedica, Premier Health, MetroHealth,
 *   Akron Children's, Cincinnati State, Lakeland CC, Clark State, Sinclair,
 *   Stark State, Hocking, EGCC, Tri-C, Wright State, Columbus State, Lorain
 *   CCC, Lake Erie College (Mentor); SARTA, COTA, GCRTA, Greater Dayton RTA,
 *   TARTA, SORTA, WRTA; AMHA, CMHA, LMHA; Mid-Ohio Food Collective, Greater
 *   Cleveland FB, Akron-Canton FB, Freestore Cincinnati FB, West OH FB Lima,
 *   Second Harvest North-Central + Mahoning Valley; PrimaryOne, Lower Lights,
 *   Heart of OH Family Health, Health Partners W OH, Cincinnati Health Network;
 *   Hospice of Cincinnati, Hospice of Dayton, Crossroads Hospice (statewide);
 *   Talbert House, Beech Brook, OhioGuidestone, Unison Health Lucas, Pro
 *   Seniors, Apprisen, ABLE Toledo, Community Legal Aid, LAS Cleveland/Cols/
 *   Cincy, Disability Rights Ohio, Ability Center Toledo; UW Cincy/Cols/
 *   Cleveland/Toledo/Mahoning/Summit-Medina, Catholic Charities Cleveland/
 *   Toledo/Youngstown/SW OH/statewide, Goodwill Akron/Cleveland/Cincy/Cols/
 *   Dayton/NW OH/statewide, Salvation Army NE OH + Central OH + Ohio HQ + NE
 *   Division, Red Cross Northern + Central+Southern + Ohio Region; YMCAs
 *   Akron/Dayton/Toledo/Youngstown; Habitat Cleveland/MidOhio/Cincy; AAA
 *   Region 9 + Western Reserve + Lake Co + COAAA + Council Aging SW OH +
 *   Ohio Dept Aging; ADAMH Cuyahoga/Franklin/Montgomery; Ohio 211 + 988
 *   CareLine + ODVN + NAMI Ohio.
 *
 * ROW STRUCTURE (12 sections, ~41 rows):
 *   HSG  housing authorities + emergency shelters     (8)
 *   FOD  food banks                                   (3)
 *   FQH  FQHCs + community hospitals + health systems (5)
 *   FAM  family services + parenting + DV             (4)
 *   TRD  trade / community college vocational         (4)
 *   SR   senior / area agencies on aging              (3)
 *   MNY  benefits / workers comp                      (1)
 *   COM  community orgs (SA division, YMCAs, LSS)     (4)
 *   TXP  transit (Akron Metro RTA)                    (1)
 *   ADV  advocacy coalitions (MH, BH, DD, CAA)        (4)
 *   IRF  info & referral (211 + JFS)                  (2)
 *   EOL  hospice (Heartland)                          (1)
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [

  // ======================== HOUSING — 8 ========================
  { section: "HSG", title: "Cincinnati Metropolitan Housing Authority (CMHA)", cat: "housing", sub: "Rental Assistance", city: "Cincinnati", website_url: "https://www.cintimha.com/", source_name: "Cincinnati Metropolitan Housing Authority", source_type: "public_housing_authority", phone: "513-721-4580", address: "1635 Western Ave, Cincinnati, OH 45214", zip: "45214", desc: "Cincinnati Metropolitan Housing Authority — Hamilton County's largest affordable housing provider; ~5,000 public housing units + 11,000 Housing Choice Vouchers (Section 8) incl HUD-VASH set-asides for homeless veterans; senior + disabled developments, Family Self-Sufficiency program, homeownership voucher conversion. Veterans referred via Cincinnati VAMC HCHV team." },
  { section: "HSG", title: "Stark Metropolitan Housing Authority (SMHA)", cat: "housing", sub: "Rental Assistance", city: "Canton", website_url: "https://www.starkmha.org/", source_name: "Stark Metropolitan Housing Authority", source_type: "public_housing_authority", phone: "330-454-8051", address: "400 East Tuscarawas St, Canton, OH 44702", zip: "44702", desc: "Stark Metropolitan Housing Authority — Stark County housing authority serving Canton/Massillon/Alliance; ~2,400 public housing units + 2,000 Housing Choice Vouchers incl HUD-VASH, RAD-converted properties, senior high-rises (Bow-Wal, Sherrick, Skyline). Veterans referred via Louis Stokes Cleveland VAMC outreach + Akron VA outpatient clinic." },
  { section: "HSG", title: "Faith Mission of LSS (Lutheran Social Services Network of Hope)", cat: "housing", sub: "Emergency Housing", city: "Columbus", website_url: "https://www.faithmission.us/", source_name: "Lutheran Social Services Network of Hope — Faith Mission", source_type: "nonprofit_organization", phone: "614-224-6617", address: "315 E Long St, Columbus, OH 43215", zip: "43215", desc: "Faith Mission — Central Ohio's largest emergency homeless shelter network operated by Lutheran Social Services; 4 shelter sites in Columbus (Long St, Nelson Park men's, Faith Mission for Women & Families, Park St veterans dorm); meals, day services, case management, employment + housing search; partnership w/ Chalmers P. Wylie VA Ambulatory Care Center for HCHV/SSVF veteran beds." },
  { section: "HSG", title: "Joseph's House", cat: "housing", sub: "Transitional Housing", city: "Akron", website_url: "https://josephshouse.org/", source_name: "Joseph's House Akron", source_type: "nonprofit_organization", phone: "330-535-5398", address: "205 N Forge St, Akron, OH 44304", zip: "44304", desc: "Joseph's House — Summit County faith-based long-term recovery housing (12-15 mo) for men exiting addiction treatment, jail, or homelessness; 50+ beds, peer recovery support, employment placement, life skills, IOP partnerships. Veterans served alongside civilians; coordinated entry through CoC of Summit County + Cleveland VAMC SSVF." },
  { section: "HSG", title: "Daybreak", cat: "housing", sub: "Emergency Housing", city: "Dayton", website_url: "https://daybreakdayton.org/", source_name: "Daybreak Dayton", source_type: "nonprofit_organization", phone: "937-461-1000", address: "605 S Patterson Blvd, Dayton, OH 45402", zip: "45402", desc: "Daybreak — Dayton's only emergency shelter for unaccompanied homeless youth & young adults ages 10-24 (incl young vets up to 24); 32-bed crisis shelter, transitional living program, drop-in center, street outreach team, education + employment support. Veterans transitioning out of military before age 25 or in custody-aged-out scenarios served." },
  { section: "HSG", title: "Lake County Housing Council", cat: "housing", sub: "Rental Assistance", city: "Painesville", website_url: "https://www.lakecountyhousing.org/", source_name: "Lake County Housing Council", source_type: "nonprofit_organization", phone: "440-354-1130", address: "1 Victoria Pl Suite 265, Painesville, OH 44077", zip: "44077", desc: "Lake County Housing Council — Lake County (suburban NE OH) HUD-approved housing counseling agency; rental assistance navigation, foreclosure prevention, first-time homebuyer education, fair housing complaints, reverse mortgage counseling, financial literacy. Veterans served alongside civilians; partnerships w/ Lake County Veterans Service Commission + Cleveland VAMC." },
  { section: "HSG", title: "Ohio CDC Association (New Housing Ohio)", cat: "housing", sub: "Home Ownership Programs", city: "Columbus", website_url: "https://www.newhousingohio.org/", source_name: "Ohio CDC Association", source_type: "trade_association", phone: "614-461-6392", address: "100 E Broad St Suite 500, Columbus, OH 43215", zip: "43215", desc: "Ohio CDC Association — statewide trade association of community development corporations (CDCs); affordable housing development, neighborhood revitalization, foreclosure prevention HUD-counseling network, individual development accounts (IDA), small business lending. Find-a-CDC directory connects veterans to nearest CDC across Ohio for affordable purchase/rental + financial coaching." },

  // ======================== FOOD — 0 (all 3 candidates are dups in DB) ========================
  // The Foodbank Inc Dayton + Toledo NW Ohio FB + Shared Harvest already in P1-P5

  // ======================== HEALTH — 5 ========================
  { section: "FQH", title: "HealthSource of Ohio", cat: "healthcare", sub: "Primary Care", city: "Loveland", website_url: "https://www.healthsourceofohio.org/", source_name: "HealthSource of Ohio", source_type: "fqhc", phone: "513-576-6464", address: "100 Lila Ave, Loveland, OH 45140", zip: "45140", desc: "HealthSource of Ohio — Federally Qualified Health Center (FQHC) network across 8 counties of SW Ohio (Clermont/Brown/Highland/Adams/Hamilton/Warren/Clinton/Pike); 17 health centers + 6 dental clinics offering primary care, OB/women's, pediatrics, behavioral health, dental, pharmacy on sliding-fee-scale (SFS); accepts Medicaid/Medicare/uninsured/VA Community Care + TRICARE." },
  { section: "FQH", title: "The HealthCare Connection", cat: "healthcare", sub: "Primary Care", city: "Lincoln Heights", website_url: "https://www.healthcare-connection.org/", source_name: "The HealthCare Connection", source_type: "fqhc", phone: "513-483-3100", address: "1401 Steffen Ave, Lincoln Heights, OH 45215", zip: "45215", desc: "The HealthCare Connection — FQHC serving northern Hamilton County (Lincoln Heights, Mt Healthy, Forest Park, Springdale, Sharonville); 5 health centers w/ primary care, women's, pediatrics, dental, behavioral health, pharmacy, SBHCs (school-based) on SFS; accepts Medicaid/Medicare/uninsured/VA Community Care. Veteran population referred via Cincinnati VAMC outpatient." },
  { section: "FQH", title: "OneHealth Ohio", cat: "healthcare", sub: "Primary Care", city: "Youngstown", website_url: "https://onehealthohio.org/", source_name: "OneHealth Ohio", source_type: "fqhc", phone: "330-744-1196", address: "777 Bears Den Rd, Youngstown, OH 44511", zip: "44511", desc: "OneHealth Ohio — FQHC serving Mahoning Valley & NE Ohio (Mahoning/Trumbull/Columbiana/Stark counties); 11 health centers in Youngstown/Warren/Salem/Alliance/Lisbon offering primary care, OB/women's, pediatrics, behavioral health, dental, optometry, pharmacy on SFS; Veterans Health Initiative w/ Youngstown VA Outpatient Clinic + Cleveland VAMC referrals; accepts Medicaid/Medicare/uninsured/VA Community Care." },
  { section: "FQH", title: "Bon Secours Mercy Health", cat: "healthcare", sub: "Specialty Care", city: "Cincinnati", website_url: "https://bsmhealth.org/", source_name: "Bon Secours Mercy Health", source_type: "regional_health_system", phone: "513-952-5000", address: "1701 Mercy Health Pl, Cincinnati, OH 45237", zip: "45237", desc: "Bon Secours Mercy Health — one of the largest Catholic-faith-based health systems in the U.S., headquartered in Cincinnati; 50+ hospitals across 7 states incl Mercy Health Cincinnati (West/Anderson/Fairfield/West Park/Clermont), Lima, Lorain, Springfield, Toledo, Youngstown markets in Ohio; cardiology, cancer, orthopedics, behavioral health, hospice. Veterans use as community-care referral from VA Cleveland/Cincinnati/Dayton/Chillicothe under MISSION Act." },
  { section: "FQH", title: "Fulton County Health Center (FMC Health)", cat: "healthcare", sub: "Specialty Care", city: "Wauseon", website_url: "https://www.fmchealth.org/", source_name: "Fulton County Health Center", source_type: "regional_health_system", phone: "419-335-2015", address: "725 S Shoop Ave, Wauseon, OH 43567", zip: "43567", desc: "Fulton County Health Center — independent rural community hospital in NW Ohio (Fulton County); 60-bed acute care + ER + surgery + cardiology + cancer + orthopedics + women's + behavioral health + dialysis + skilled nursing + 12 outpatient specialty clinics across Wauseon/Delta/Swanton/Archbold. Veterans use as community-care referral from Toledo VA CBOC + Ann Arbor VA Health System under MISSION Act." },

  // ======================== FAMILY / CRISIS — 4 ========================
  { section: "FAM", title: "Project Woman", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Springfield", website_url: "https://www.projectwomanohio.org/", source_name: "Project Woman", source_type: "nonprofit_organization", phone: "937-325-3707", address: "1316 N Limestone St, Springfield, OH 45503", zip: "45503", desc: "Project Woman — Clark/Champaign/Logan county domestic violence + sexual assault crisis center; 24/7 hotline, 30-bed emergency shelter, transitional housing, court advocacy + protection order assistance, sexual assault forensic exams, counseling, child & teen advocacy, prevention education. Veterans + military families served via DoD Family Advocacy + Springfield Community Hospital partnership." },
  { section: "FAM", title: "The Buckeye Ranch", cat: "family-support", sub: "Family Counseling", city: "Grove City", website_url: "https://www.buckeyeranch.org/", source_name: "The Buckeye Ranch", source_type: "nonprofit_organization", phone: "614-875-2371", address: "5665 Hoover Rd, Grove City, OH 43123", zip: "43123", desc: "The Buckeye Ranch — Central Ohio's largest behavioral health agency for children, youth & families; residential treatment campus (Grove City), foster care + adoption, in-home counseling + case management, school-based mental health (50+ districts), early childhood services, equine therapy, juvenile justice diversion. Veteran families served alongside civilians; Tricare-accepted; 11 outpatient offices across 13 counties." },
  { section: "FAM", title: "Beech Acres Parenting Center", cat: "family-support", sub: "Parenting Programs", city: "Cincinnati", website_url: "https://beechacres.org/", source_name: "Beech Acres Parenting Center", source_type: "nonprofit_organization", phone: "513-231-6630", address: "6881 Beechmont Ave, Cincinnati, OH 45230", zip: "45230", desc: "Beech Acres Parenting Center — Cincinnati's evidence-based parenting + family strengthening agency; classes, coaching, kinship care navigator (grandparents/relatives raising kids), school-based wellness programs (40+ districts), foster + adoption services, military-family-specific groups for deployed/transitioning service members. Tricare + Medicaid accepted." },
  { section: "FAM", title: "The Centers (Centers for Families and Children)", cat: "family-support", sub: "Family Counseling", city: "Cleveland", website_url: "https://thecentersohio.org/", source_name: "The Centers", source_type: "nonprofit_organization", phone: "216-325-9333", address: "4500 Euclid Ave, Cleveland, OH 44103", zip: "44103", desc: "The Centers — Cleveland's largest integrated nonprofit; behavioral health (outpatient counseling, MAT, peer recovery), primary care (FQHC look-alike), early childhood (Head Start), family support; 10+ Cleveland sites incl El Barrio (Latinx), East Side Recovery, West Side Recovery, Circle Health Services LGBTQ+. Veterans served alongside civilians; partnership w/ Louis Stokes Cleveland VAMC referrals." },

  // ======================== TRADE — 4 ========================
  { section: "TRD", title: "Terra State Community College", cat: "education", sub: "Trade Schools & Vocational", city: "Fremont", website_url: "https://www.terra.edu/", source_name: "Terra State Community College", source_type: "community_college", phone: "419-334-8400", address: "2830 Napoleon Rd, Fremont, OH 43420", zip: "43420", desc: "Terra State Community College — public community college serving Sandusky/Ottawa/Erie/Seneca counties (NW Ohio rural/Lake Erie shore); associate degrees + certificates in welding tech, advanced manufacturing, electrical eng tech, mechatronics, HVAC/R, automotive, nursing, criminal justice, business; Veteran Services Office handles GI Bill/Yellow Ribbon/VR&E + Vet Cafe peer support; Tuition Assistance for active duty." },
  { section: "TRD", title: "Zane State College", cat: "education", sub: "Trade Schools & Vocational", city: "Zanesville", website_url: "https://www.zanestate.edu/", source_name: "Zane State College", source_type: "community_college", phone: "740-454-2501", address: "1555 Newark Rd, Zanesville, OH 43701", zip: "43701", desc: "Zane State College — public community college serving Muskingum/Coshocton/Guernsey/Morgan/Noble/Perry counties (East Central Ohio Appalachian region); associate degrees + certificates in nursing/allied health, IT/cybersecurity, advanced manufacturing, welding, engineering tech, business, criminal justice + Cambridge campus. Veteran Services Office handles GI Bill/VR&E/Yellow Ribbon + adjacent to AAA9 Cambridge senior services." },
  { section: "TRD", title: "Ohio Technical College", cat: "education", sub: "Trade Schools & Vocational", city: "Cleveland", website_url: "https://www.ohiotech.edu/", source_name: "Ohio Technical College", source_type: "trade_school", phone: "216-881-1700", address: "1374 E 51st St, Cleveland, OH 44103", zip: "44103", desc: "Ohio Technical College (OTC) — Cleveland-based for-profit trade school accredited by ACCSC; programs in automotive tech, diesel + truck, collision repair, welding, alternative fuel + electric vehicle (Powersport Institute), classic car restoration; 18-month programs typical, GI Bill + VR&E approved, Yellow Ribbon participant; large veteran enrollment due to hands-on automotive/diesel pipeline to OEMs (Ford/GM/Cummins)." },
  { section: "TRD", title: "Belmont College", cat: "education", sub: "Trade Schools & Vocational", city: "St Clairsville", website_url: "https://belmontcollege.edu/", source_name: "Belmont College", source_type: "community_college", phone: "740-695-9500", address: "68094 Hammond Rd, St Clairsville, OH 43950", zip: "43950", desc: "Belmont College — public community college serving Belmont/Harrison/Monroe/Jefferson counties (Eastern Ohio Appalachian/Ohio Valley); associate degrees + certificates in building preservation, oil & gas tech, welding, nursing, IT, business, criminal justice; 3 campuses incl Building Preservation Conservation Lab (regionally unique). Veterans Resource Center handles GI Bill/VR&E + on-site DAV chapter partnership." },

  // ======================== SENIOR — 3 ========================
  { section: "SR", title: "Area Agency on Aging Region 7 (Buckeye Hills/Athens)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Rio Grande", website_url: "https://www.aaa7.org/", source_name: "Area Agency on Aging Region 7", source_type: "area_agency_on_aging", phone: "740-374-4017", address: "1005 Pinecrest Dr Suite F, Rio Grande, OH 45674", zip: "45674", desc: "Area Agency on Aging Region 7 — federally-designated AAA serving 9 counties of SE Ohio Appalachia (Athens/Gallia/Hocking/Jackson/Meigs/Perry/Pike/Ross/Vinton); home-delivered + congregate meals, transportation, in-home aide + homemaker, caregiver support, ombudsman, PASSPORT/Medicaid waiver, senior community service employment (SCSEP). Veterans 60+ served alongside civilians via SE OH county VSCs." },
  { section: "SR", title: "Area Agency on Aging PSA3 (Dayton)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Dayton", website_url: "https://www.psa3.org/", source_name: "Area Agency on Aging PSA3 / Council on Aging Greater Dayton", source_type: "area_agency_on_aging", phone: "937-341-3000", address: "40 W 4th St Suite 200, Dayton, OH 45402", zip: "45402", desc: "Area Agency on Aging PSA3 (Council on Aging of Greater Dayton) — federally-designated AAA serving 9 counties of W-Central Ohio (Champaign/Clark/Darke/Greene/Logan/Miami/Montgomery/Preble/Shelby); home-delivered + congregate meals, transportation (RTA + volunteer), in-home aide, caregiver respite, ombudsman, PASSPORT, SCSEP. Coordinates w/ Dayton VAMC Geriatrics + Aging Veterans Service for vets 60+." },
  { section: "SR", title: "Area Office on Aging of NW Ohio (PSA2)", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Toledo", website_url: "https://www.psa2.org/", source_name: "Area Office on Aging of Northwestern Ohio", source_type: "area_agency_on_aging", phone: "419-382-0624", address: "2155 Arlington Ave, Toledo, OH 43609", zip: "43609", desc: "Area Office on Aging of NW Ohio (PSA2) — federally-designated AAA serving 10 counties of NW Ohio (Defiance/Erie/Fulton/Henry/Huron/Lucas/Ottawa/Paulding/Sandusky/Williams); home-delivered + congregate meals, transportation (TARTA + volunteer), in-home aide, caregiver, ombudsman, PASSPORT/Medicaid waiver, SCSEP, info & assistance line. Coordinates w/ Toledo VA CBOC + Ann Arbor VAMC for vets 60+." },

  // ======================== MONEY — 1 ========================
  { section: "MNY", title: "Ohio Bureau of Workers' Compensation (BWC)", cat: "financial", sub: "Benefits Counseling", city: "Columbus", website_url: "https://ww9.ohbwc.com/", source_name: "Ohio Bureau of Workers' Compensation", source_type: "state_agency", phone: "800-644-6292", address: "30 W Spring St, Columbus, OH 43215", zip: "43215", desc: "Ohio Bureau of Workers' Compensation (BWC) — state agency administering workers' comp insurance for 247,000 Ohio employers + injured worker benefits (medical, lost wages, vocational rehab, death benefits); customer service centers in Columbus/Cleveland/Cincinnati/Dayton/Toledo/Youngstown/Akron/Canton/Mansfield/Lima/Logan; vocational rehabilitation for return-to-work after injury (relevant to vets w/ workplace injury overlap to VA disability). Free safety consultations + grants." },

  // ======================== COMMUNITY — 4 ========================
  { section: "COM", title: "Salvation Army Southwest Ohio & Northeast Kentucky Division", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cincinnati", website_url: "https://www.salvationarmyusa.org/usa-eastern-territory/southwest-ohio-northeast-kentucky/", source_name: "Salvation Army USA Eastern Territory — SW Ohio & NE Kentucky Division", source_type: "nonprofit_organization", phone: "513-762-5600", address: "114 E Central Pkwy, Cincinnati, OH 45202", zip: "45202", desc: "Salvation Army SW Ohio & NE Kentucky Division — divisional HQ in Cincinnati overseeing 30+ corps community centers + Adult Rehabilitation Center (ARC, 6-mo residential SUD) across SW Ohio (Cincinnati/Hamilton/Middletown/Wilmington/Lebanon/Portsmouth/Chillicothe) + NE Kentucky; emergency assistance (rent/utility/food), shelter, after-school, holiday programs, Pathway of Hope case mgmt. Veterans served via Cincinnati VAMC HCHV + SSVF coordination." },
  { section: "COM", title: "YMCA of Greater Cleveland", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Cleveland", website_url: "https://www.clevelandymca.org/", source_name: "YMCA of Greater Cleveland", source_type: "nonprofit_organization", phone: "216-344-9622", address: "2200 Prospect Ave, Cleveland, OH 44115", zip: "44115", desc: "YMCA of Greater Cleveland — 8 branch locations across Cuyahoga County (Downtown, West Park, Westside, Old Brooklyn, Hillcrest, Lakewood, Parma, Bedford) + camps; fitness/aquatics, child care + after-school, summer camps, diabetes prevention, livestrong cancer survivorship, healthy aging, youth sports leagues. Military Outreach Initiative offers free family memberships to active-duty/Guard/Reserve + discounts for veterans." },
  { section: "COM", title: "YMCA of Central Ohio", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Columbus", website_url: "https://www.ymcacolumbus.org/", source_name: "YMCA of Central Ohio", source_type: "nonprofit_organization", phone: "614-224-1142", address: "40 W Long St, Columbus, OH 43215", zip: "43215", desc: "YMCA of Central Ohio — 11 branch locations across Franklin/Delaware/Pickaway/Madison/Union counties incl Downtown, Hilliard, Eastside, Liberty Twp, North, Vaughn E Hairston, plus residential men's housing (260 SRO units at Downtown Y for very-low-income/homeless men incl vets); fitness/aquatics, child care + after-school, summer camps, healthy aging. Military Outreach Initiative + free memberships for active duty/Guard/Reserve." },
  { section: "COM", title: "Lutheran Social Services Network of Hope", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Columbus", website_url: "https://lssnetworkofhope.org/", source_name: "Lutheran Social Services Network of Hope", source_type: "nonprofit_organization", phone: "614-228-5200", address: "750 E Long St Suite 200, Columbus, OH 43203", zip: "43203", desc: "Lutheran Social Services Network of Hope — Central Ohio multi-service nonprofit (Franklin/Fairfield/Licking/Pickaway/Knox counties); operates Faith Mission shelters (men's, women & families, vets dorm), Choices Domestic Violence Shelter, Food Pantries (4 sites), CHOICES eviction-prevention, supportive housing for homeless w/ disabilities; partnerships w/ Chalmers P. Wylie VA Ambulatory Care for HCHV/SSVF veteran beds." },

  // ======================== TRANSPORT — 1 ========================
  { section: "TXP", title: "METRO Regional Transit Authority (METRO RTA / iRideRTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Akron", website_url: "https://www.iriderta.org/", source_name: "METRO Regional Transit Authority Summit County", source_type: "public_transit_agency", phone: "330-762-0341", address: "631 S Broadway St, Akron, OH 44311", zip: "44311", desc: "METRO Regional Transit Authority (METRO RTA, branded iRideRTA) — Summit County's public transit agency serving Akron + 30 surrounding municipalities; 30+ fixed-route bus lines, SCAT (Summit County ADA paratransit), DASH downtown circulator, Northcoast Express commuter to Cleveland, ride sharing pilot, reduced fare for veterans w/ VA ID. Connects to Akron VA Outpatient Clinic + Cleveland VAMC via Northcoast Express." },

  // ======================== ADVOCACY — 4 ========================
  { section: "ADV", title: "Mental Health & Addiction Advocacy Coalition (MHAC Ohio)", cat: "mental-health", sub: "Counseling & Therapy", city: "Columbus", website_url: "https://mhaohio.org/", source_name: "Mental Health & Addiction Advocacy Coalition", source_type: "advocacy_organization", phone: "614-225-0980", address: "33 N 3rd St Suite 510, Columbus, OH 43215", zip: "43215", desc: "Mental Health & Addiction Advocacy Coalition (MHAC) — statewide advocacy + policy organization for Ohioans w/ mental illness or addiction; Crisis Now Ohio campaign, parity enforcement, school-based mental health policy, MAT expansion, criminal justice diversion, peer + family voice. Veterans subgroup tracks veteran-specific BH legislation; resource hub for finding local services across Ohio." },
  { section: "ADV", title: "Ohio Association of County Behavioral Health Authorities (OACBHA)", cat: "mental-health", sub: "Crisis Support", city: "Columbus", website_url: "https://oacbha.org/", source_name: "Ohio Association of County Behavioral Health Authorities", source_type: "trade_association", phone: "614-224-1111", address: "33 N 3rd St Suite 540, Columbus, OH 43215", zip: "43215", desc: "Ohio Association of County Behavioral Health Authorities (OACBHA) — trade association for Ohio's 50 county/multi-county ADAMHS Boards (the local funders + planners of public mental health + addiction services); training + technical assistance, public policy, board-member development. Find-a-Board directory routes vets + civilians to nearest county ADAMHS Board for crisis lines, mobile teams, MAT, peer support across all 88 Ohio counties." },
  { section: "ADV", title: "Ohio Association of County Boards of DD (OACBDD)", cat: "disabled-veterans", sub: "Legal Advocacy & Rights", city: "Columbus", website_url: "https://www.oacbdd.org/", source_name: "Ohio Association of County Boards of Developmental Disabilities", source_type: "trade_association", phone: "614-431-0616", address: "73 E Wilson Bridge Rd Suite B1, Worthington, OH 43085", zip: "43085", desc: "Ohio Association of County Boards of DD (OACBDD) — trade association for Ohio's 88 county DD boards (the local funders of services for people w/ developmental disabilities); training, public policy, advocacy, family voice. Find-a-County-Board directory connects vets with TBI/IDD or family caregivers of disabled adult children to nearest county DD board for case management, day services, supported employment, residential, transportation across all 88 OH counties." },
  { section: "ADV", title: "Ohio Association of Community Action Agencies (OACAA)", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Columbus", website_url: "https://oacaa.org/", source_name: "Ohio Association of Community Action Agencies", source_type: "trade_association", phone: "614-224-8500", address: "50 W Broad St Suite 1616, Columbus, OH 43215", zip: "43215", desc: "Ohio Association of Community Action Agencies (OACAA) — trade association for Ohio's 47 Community Action Agencies (CAAs); training, public policy, federal grant pass-through (LIHEAP, HEAP, CSBG, Head Start, weatherization). Find-a-CAA directory routes vets + civilians to nearest CAA for utility help, weatherization, emergency rent, financial coaching, Head Start across all 88 OH counties." },

  // ======================== INFO & REFERRAL — 2 ========================
  { section: "IRF", title: "211 Summit County (United Way)", cat: "community-support", sub: "Veteran Outreach Programs", city: "Akron", website_url: "https://www.211summit.org/", source_name: "United Way of Summit & Medina — 211", source_type: "info_referral_service", phone: "211", address: "37 N High St, Akron, OH 44308", zip: "44308", desc: "211 Summit County — 24/7 free + confidential information & referral hotline operated by United Way of Summit & Medina; routes callers (incl veterans + their families) to local emergency food, rent + utility help, mental health crisis, addiction treatment, child care, senior services, housing across Summit/Medina counties; database of 1,000+ Summit-area orgs incl Akron VA Outpatient Clinic + DAV Akron + county VSC." },
  { section: "IRF", title: "Hamilton County JFS — Cash, Food & Medicaid Assistance", cat: "financial", sub: "Emergency Financial Assistance", city: "Cincinnati", website_url: "https://hcjfs.org/", source_name: "Hamilton County Department of Job & Family Services", source_type: "county_agency", phone: "513-946-1000", address: "222 E Central Pkwy, Cincinnati, OH 45202", zip: "45202", desc: "Hamilton County Job & Family Services (HCJFS) — Hamilton County's general social safety-net agency (separate from its Children's Services division); administers Ohio Works First (TANF cash), SNAP food assistance, Medicaid eligibility, child care vouchers, child support, adult protective services, Prevention Retention & Contingency (PRC emergency rent/utility) for low-income Cincinnati metro residents incl veteran families. Coordinates w/ Hamilton County VSC + Cincinnati VAMC SSVF." },

  // ======================== END-OF-LIFE — 0 (Heartland Hospice already in DB statewide) ========================
];

(async () => {
  await runSeed(ROWS, {
    label: "seed-oh-enhance.ts",
    commit: COMMIT,
    state: "OH",
  });
})();
