/**
 * California Statewide Saturation — Batch 7
 * High-confidence statewide network: AAAs (CDA PSA 1-33), Independent Living
 * Centers (DOR-funded, 28 statewide), Caregiver Resource Centers (CDA, 11),
 * Family Justice Centers (CA Partnership), and selected workforce/county anchors.
 *
 * Skips already in DB: Sourcewise (Santa Clara AAA), Council on Aging
 * Southern CA (Orange AAA / HICAP), USC Family Caregiver Support Center
 * (LA CRC), Solano Family Justice Center.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== AREA AGENCIES ON AGING (CDA PSA NETWORK) ==============
  {
    section: "AAA-1", title: "Area 1 Agency on Aging (PSA 1: Del Norte, Humboldt, Lake, Mendocino)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 1 Area Agency on Aging serving Del Norte, Humboldt, Lake, and Mendocino counties. Coordinates Older Americans Act services: Meals on Wheels, family caregiver support, HICAP referral, ombudsman, transportation, and adult day care.",
    website_url: "https://www.a1aa.org/",
    phone: "(707) 442-3763", address: "434 7th Street",
    city: "Eureka", zip: "95501",
    eligibility: "Adults 60+ in Del Norte/Humboldt/Lake/Mendocino",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-2", title: "Passages Adult Resource Center (PSA 2/3: Butte, Colusa, Glenn, Plumas, Tehama, Lassen, Modoc, Shasta, Siskiyou, Trinity)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 2 + PSA 3 combined Area Agency on Aging serving 10 counties of far Northern California. Coordinates Older Americans Act services: nutrition, family caregiver support, HICAP, ombudsman, in-home support.",
    website_url: "https://www.passagescenter.org/",
    phone: "(530) 898-5923", address: "25 Main Street, Suite 202",
    city: "Chico", zip: "95928",
    eligibility: "Adults 60+ in 10 far-North counties",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-4", title: "Agency on Aging Area 4 (PSA 4: Nevada, Placer, Sacramento, Sierra, Sutter, Yolo, Yuba)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 4 Area Agency on Aging serving 7 counties of greater Sacramento. Coordinates Older Americans Act services: nutrition, family caregiver support, HICAP, ombudsman, transportation, legal services for seniors.",
    website_url: "https://www.agencyonaging4.org/",
    phone: "(916) 486-1876", address: "2260 Park Towne Circle, Suite 100",
    city: "Sacramento", zip: "95825",
    eligibility: "Adults 60+ in greater Sacramento region",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-5", title: "Vivalon (PSA 5 Marin Area Agency on Aging)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 5 Marin County Area Agency on Aging (formerly Whistlestop). Operates Older Americans Act programs: senior center, meals, transportation, caregiver support, HICAP, healthy aging programs.",
    website_url: "https://vivalon.org/",
    phone: "(415) 456-9062", address: "999 3rd Street, Suite 270",
    city: "San Rafael", zip: "94901",
    eligibility: "Adults 60+ in Marin County",
    source_name: "California Department of Aging PSA network", source_type: "nonprofit",
  },
  {
    section: "AAA-6", title: "San Francisco Department of Disability and Aging Services (PSA 6)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 6 San Francisco Area Agency on Aging (housed within SF DAS). Coordinates OAA programs: senior centers, meals, in-home support, caregiver support, ombudsman, public guardian, adult protective services.",
    website_url: "https://www.sfhsa.org/about/departments/department-disability-and-aging-services-das",
    phone: "(415) 355-6700", address: "2 Gough Street",
    city: "San Francisco", zip: "94103",
    eligibility: "Adults 60+ and disabled adults in SF",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-7", title: "Contra Costa County Area Agency on Aging (PSA 7)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 7 Contra Costa County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, in-home support, adult protective services.",
    website_url: "https://ehsd.org/elderly-disabled/area-agency-on-aging-aaa/",
    phone: "(925) 602-4175", address: "400 Ellinwood Way",
    city: "Pleasant Hill", zip: "94523",
    eligibility: "Adults 60+ in Contra Costa County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-8", title: "San Mateo County Aging and Adult Services (PSA 8)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 8 San Mateo County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, IHSS, adult protective services, public guardian.",
    website_url: "https://www.smchealth.org/aas",
    phone: "(800) 675-8437", address: "225 37th Avenue",
    city: "San Mateo", zip: "94403",
    eligibility: "Adults 60+ and disabled adults in San Mateo County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-10", title: "Alameda County Area Agency on Aging (PSA 10)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 10 Alameda County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, senior info & assistance line, IHSS, adult protective services.",
    website_url: "https://www.acgov.org/aaa/",
    phone: "(510) 577-1900", address: "6955 Foothill Boulevard, Suite 143",
    city: "Oakland", zip: "94605",
    eligibility: "Adults 60+ in Alameda County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-11", title: "San Joaquin County Human Services Agency - Aging Services (PSA 11)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 11 San Joaquin County Area Agency on Aging (within HSA). Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, IHSS, adult protective services.",
    website_url: "https://www.sjgov.org/department/hsa/",
    phone: "(209) 468-1104", address: "102 S. San Joaquin Street",
    city: "Stockton", zip: "95202",
    eligibility: "Adults 60+ in San Joaquin County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-12", title: "Area 12 Agency on Aging (PSA 12: Alpine, Amador, Calaveras, Mariposa, Tuolumne)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 12 Area Agency on Aging serving 5 Sierra/foothill counties. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, transportation, legal services.",
    website_url: "https://area12.org/",
    phone: "(209) 532-6272", address: "19074 Standard Road, Suite A",
    city: "Sonora", zip: "95370",
    eligibility: "Adults 60+ in Alpine/Amador/Calaveras/Mariposa/Tuolumne",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-13", title: "Stanislaus County Department of Aging and Veterans Services (PSA 13)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 13 Stanislaus County Area Agency on Aging combined with County Veterans Service Office. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, transportation.",
    website_url: "https://www.stancounty.com/das/",
    phone: "(209) 558-8698", address: "121 Downey Avenue",
    city: "Modesto", zip: "95354",
    eligibility: "Adults 60+ in Stanislaus County; veterans of all ages",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-14", title: "Merced County Area Agency on Aging (PSA 14)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 14 Merced County Area Agency on Aging (within HSA). Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman.",
    website_url: "https://www.countyofmerced.com/281/Area-Agency-on-Aging",
    phone: "(209) 385-3000", address: "2150 M Street",
    city: "Merced", zip: "95340",
    eligibility: "Adults 60+ in Merced County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-15", title: "Fresno-Madera Area Agency on Aging (PSA 15)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 15 Fresno-Madera Area Agency on Aging. Coordinates OAA programs across Fresno and Madera counties: nutrition, family caregiver support, HICAP via Valley CRC, ombudsman, in-home support.",
    website_url: "https://fmaaa.org/",
    phone: "(559) 600-4405", address: "3837 N. Clark Street",
    city: "Fresno", zip: "93726",
    eligibility: "Adults 60+ in Fresno/Madera",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-16", title: "Kings/Tulare Area Agency on Aging (PSA 16)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 16 Kings/Tulare Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, in-home support.",
    website_url: "https://www.tularecountyhhsa.org/index.cfm/aging-adult-services/",
    phone: "(559) 624-8000", address: "5957 S. Mooney Boulevard",
    city: "Visalia", zip: "93277",
    eligibility: "Adults 60+ in Kings/Tulare",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-17", title: "Kern County Aging and Adult Services (PSA 17)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 17 Kern County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, IHSS, adult protective services.",
    website_url: "https://kernaging.org/",
    phone: "(661) 868-1000", address: "5357 Truxtun Avenue",
    city: "Bakersfield", zip: "93309",
    eligibility: "Adults 60+ in Kern County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-18", title: "Central Coast Commission for Senior Citizens (PSA 18: SLO, Santa Barbara)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 18 Area Agency on Aging serving SLO and Santa Barbara counties. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman.",
    website_url: "https://www.centralcoastseniors.org/",
    phone: "(805) 925-9554", address: "528 S. Broadway",
    city: "Santa Maria", zip: "93454",
    eligibility: "Adults 60+ in SLO/Santa Barbara",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-19", title: "Ventura County Area Agency on Aging (PSA 19)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 19 Ventura County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, in-home support.",
    website_url: "https://vcaaa.org/",
    phone: "(805) 477-7300", address: "646 County Square Drive, Suite 100",
    city: "Ventura", zip: "93003",
    eligibility: "Adults 60+ in Ventura County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-20", title: "City of Los Angeles Department of Aging (PSA 20)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 20 LA City Department of Aging. Coordinates OAA programs across the City of Los Angeles: 16 multipurpose senior centers, congregate meals, home-delivered meals, family caregiver support, HICAP, ombudsman.",
    website_url: "https://aging.lacity.gov/",
    phone: "(213) 482-7252", address: "221 N. Figueroa Street, Suite 500",
    city: "Los Angeles", zip: "90012",
    eligibility: "Adults 60+ residing in City of LA",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-25", title: "LA County Workforce Development, Aging and Community Services (PSA 25)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 25 LA County WDACS Area Agency on Aging covering all of LA County outside the City of LA. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, IHSS, adult protective services.",
    website_url: "https://wdacs.lacounty.gov/programs/aaa/",
    phone: "(800) 510-2020", address: "510 S. Vermont Avenue",
    city: "Los Angeles", zip: "90020",
    eligibility: "Adults 60+ in LA County outside City of LA",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-22", title: "PSA 22 Riverside County Office on Aging",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 22 Riverside County Office on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, in-home support.",
    website_url: "https://www.rcaging.org/",
    phone: "(951) 867-3800", address: "6296 River Crest Drive, Suite K",
    city: "Riverside", zip: "92507",
    eligibility: "Adults 60+ in Riverside County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-23", title: "PSA 23 San Bernardino County Department of Aging and Adult Services",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 23 San Bernardino County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, IHSS, adult protective services.",
    website_url: "https://www.sbcounty.gov/daas/",
    phone: "(909) 891-3900", address: "784 E. Hospitality Lane",
    city: "San Bernardino", zip: "92415",
    eligibility: "Adults 60+ in San Bernardino County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-24", title: "PSA 24 San Diego County Aging and Independence Services",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 24 San Diego County Area Agency on Aging (Aging & Independence Services / AIS). Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, in-home support, adult protective services.",
    website_url: "https://www.sandiegocounty.gov/hhsa/programs/ais/",
    phone: "(800) 339-4661", address: "5560 Overland Avenue, Suite 300",
    city: "San Diego", zip: "92123",
    eligibility: "Adults 60+ and disabled adults in SD County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-26", title: "PSA 26 Imperial County Area Agency on Aging",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 26 Imperial County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman.",
    website_url: "https://www.co.imperial.ca.us/socialservices/aaa/",
    phone: "(442) 265-7032", address: "2995 S. 4th Street, Suite 105",
    city: "El Centro", zip: "92243",
    eligibility: "Adults 60+ in Imperial County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-27", title: "PSA 27 Sonoma County Human Services Department - Adult & Aging Services",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 27 Sonoma County Area Agency on Aging (within HSD Adult & Aging Services). Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman, IHSS, adult protective services.",
    website_url: "https://sonomacounty.ca.gov/Adult-and-Aging/",
    phone: "(707) 565-5950", address: "3725 Westwind Boulevard, Suite 101",
    city: "Santa Rosa", zip: "95403",
    eligibility: "Adults 60+ in Sonoma County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-28", title: "PSA 28 Area Agency on Aging Serving Napa-Solano",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 28 Area Agency on Aging serving Napa and Solano counties. Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman.",
    website_url: "https://www.aaans.org/",
    phone: "(707) 644-6612", address: "275 Beck Avenue",
    city: "Fairfield", zip: "94533",
    eligibility: "Adults 60+ in Napa/Solano",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-30", title: "PSA 30 Seniors Council of Santa Cruz and San Benito Counties",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 30 Seniors Council Area Agency on Aging serving Santa Cruz and San Benito counties. Coordinates OAA programs: nutrition, family caregiver support, HICAP via Alliance on Aging, ombudsman.",
    website_url: "https://seniorscouncil.org/",
    phone: "(831) 688-0400", address: "234 Santa Cruz Avenue",
    city: "Aptos", zip: "95003",
    eligibility: "Adults 60+ in Santa Cruz/San Benito",
    source_name: "California Department of Aging PSA network", source_type: "nonprofit",
  },
  {
    section: "AAA-31", title: "PSA 31 Inyo-Mono Area Agency on Aging",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 31 Inyo-Mono Area Agency on Aging (within Inyo County HHS). Coordinates OAA programs: nutrition, family caregiver support, HICAP, ombudsman.",
    website_url: "https://inyocounty.us/services/health-and-human-services/aging-and-disability-resource-connection",
    phone: "(760) 873-3305", address: "1360 N. Main Street, Suite 201",
    city: "Bishop", zip: "93514",
    eligibility: "Adults 60+ in Inyo/Mono",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },
  {
    section: "AAA-33", title: "Monterey County Area Agency on Aging (PSA 33)",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "PSA 33 Monterey County Area Agency on Aging. Coordinates OAA programs: nutrition, family caregiver support, HICAP via Alliance on Aging, ombudsman.",
    website_url: "https://www.co.monterey.ca.us/government/departments-i-z/social-services/aging-and-adult-services/area-agency-on-aging",
    phone: "(831) 755-4466", address: "1000 S. Main Street, Suite 211",
    city: "Salinas", zip: "93901",
    eligibility: "Adults 60+ in Monterey County",
    source_name: "California Department of Aging PSA network", source_type: "government_agency",
  },

  // ============== INDEPENDENT LIVING CENTERS (DOR-FUNDED) ==============
  {
    section: "ILC-AC", title: "Center for Independence of Individuals with Disabilities (CID) - San Mateo",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded Independent Living Center serving San Mateo County. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition services. Disabled veterans served.",
    website_url: "https://cidsanmateo.org/",
    phone: "(650) 645-1780", address: "2001 Winward Way, Suite 103",
    city: "San Mateo", zip: "94404",
    eligibility: "People with disabilities in San Mateo County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-CRC", title: "Community Resources for Independent Living (CRIL) - Hayward",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Alameda County. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition services. Branches in Hayward, Fremont, Livermore.",
    website_url: "https://www.cril-online.org/",
    phone: "(510) 881-5743", address: "439 A Street",
    city: "Hayward", zip: "94541",
    eligibility: "People with disabilities in Alameda County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-CIL", title: "Center for Independent Living - Berkeley (CIL Berkeley)",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "World's first Independent Living Center, founded in Berkeley 1972 by disability rights pioneers. DOR-funded ILC for Alameda County. Core IL services and historic disability rights advocacy.",
    website_url: "https://www.thecil.org/",
    phone: "(510) 841-4776", address: "3075 Adeline Street, Suite 100",
    city: "Berkeley", zip: "94703",
    eligibility: "People with disabilities in Alameda County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-ILRCSF", title: "Independent Living Resource Center San Francisco (ILRC SF)",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving San Francisco. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition services. Disabled veterans served.",
    website_url: "https://www.ilrcsf.org/",
    phone: "(415) 543-6222", address: "825 Howard Street",
    city: "San Francisco", zip: "94103",
    eligibility: "People with disabilities in SF",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-MAR", title: "Marin Center for Independent Living (Marin CIL)",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Marin County. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition services.",
    website_url: "https://marincil.org/",
    phone: "(415) 459-6245", address: "710 4th Street",
    city: "San Rafael", zip: "94901",
    eligibility: "People with disabilities in Marin County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-NS", title: "North Bay Regional Center / Disability Services & Legal Center (DSLC)",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Sonoma, Lake, and Mendocino counties. Core IL services + integrated legal advocacy through the Disability Rights center model.",
    website_url: "https://mydslc.org/",
    phone: "(707) 528-2745", address: "521 Mendocino Avenue",
    city: "Santa Rosa", zip: "95401",
    eligibility: "People with disabilities in Sonoma/Lake/Mendocino",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-DRA", title: "FREED Center for Independent Living - Grass Valley",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Nevada, Sierra, Placer, Plumas, Yuba, Sutter, Colusa counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.freed.org/",
    phone: "(530) 477-3333", address: "2059 Nevada City Highway, Suite 101",
    city: "Grass Valley", zip: "95945",
    eligibility: "People with disabilities in 7 Sierra/Sacramento Valley counties",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-RES", title: "Resources for Independence Central Valley (RICV) - Fresno",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Fresno, Kings, Madera, Tulare counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition.",
    website_url: "https://www.ricv.org/",
    phone: "(559) 221-2330", address: "3008 N. Fresno Street",
    city: "Fresno", zip: "93703",
    eligibility: "People with disabilities in 4 Central Valley counties",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-DRC", title: "Dayle McIntosh Center (DMC) - Anaheim",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Orange County. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition. ADA technical assistance.",
    website_url: "https://www.daylemc.org/",
    phone: "(714) 621-3300", address: "501 N. Brookhurst Street, Suite 102",
    city: "Anaheim", zip: "92801",
    eligibility: "People with disabilities in Orange County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-DRSP", title: "Disability Rights and Resource Center (DRRC) - San Bernardino",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Inland Empire (San Bernardino and Riverside counties). Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.dprc.org/",
    phone: "(951) 682-6581", address: "6235 River Crest Drive, Suite L",
    city: "Riverside", zip: "92507",
    eligibility: "People with disabilities in Inland Empire",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-RC", title: "Rolling Start - San Bernardino",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving San Bernardino County and Inyo/Mono counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition.",
    website_url: "https://www.rollingstart.com/",
    phone: "(909) 884-2129", address: "570 W. 4th Street, Suite 107",
    city: "San Bernardino", zip: "92401",
    eligibility: "People with disabilities in San Bernardino/Inyo/Mono",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-CRD", title: "Communities Actively Living Independent and Free (CALIF) - LA",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Downtown LA, South LA, and surrounding areas. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition. Strong focus on housing.",
    website_url: "https://www.calif-ilc.org/",
    phone: "(213) 627-0477", address: "634 S. Spring Street, 2nd Floor",
    city: "Los Angeles", zip: "90014",
    eligibility: "People with disabilities in central LA",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-DLA", title: "Disabled Resources Center (DRC) - Long Beach",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving South LA County: Long Beach, Compton, Carson, Wilmington. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.drcinc.org/",
    phone: "(562) 427-1000", address: "2750 E. Spring Street, Suite 100",
    city: "Long Beach", zip: "90806",
    eligibility: "People with disabilities in South LA County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-WSV", title: "Westside Center for Independent Living (WCIL) - LA",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving West LA, Santa Monica, Culver City. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition.",
    website_url: "https://www.wcil.org/",
    phone: "(310) 390-3611", address: "12901 Venice Boulevard",
    city: "Los Angeles", zip: "90066",
    eligibility: "People with disabilities in West LA",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-SFV", title: "Service Center for Independent Life (SCIL) - Claremont",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving East LA County and West San Bernardino County: Pomona Valley, Claremont, San Gabriel Valley. Core IL services.",
    website_url: "https://scil-ilc.org/",
    phone: "(909) 621-6722", address: "107 S. Spring Street",
    city: "Claremont", zip: "91711",
    eligibility: "People with disabilities in Pomona/East SGV/West SB",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-VAL", title: "Independent Living Center of Southern California (ILCSC) - Van Nuys",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving the San Fernando, Santa Clarita, and Antelope valleys. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.ilcsc.org/",
    phone: "(818) 988-9525", address: "14354 Haynes Street, Suite 200",
    city: "Van Nuys", zip: "91401",
    eligibility: "People with disabilities in SFV/Santa Clarita/Antelope",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-NDC", title: "Disability Action Center (DAC) - Eureka",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Del Norte, Humboldt, Trinity counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition.",
    website_url: "https://www.tristatedisability.org/",
    phone: "(707) 445-8404", address: "2222 Harrison Avenue",
    city: "Eureka", zip: "95501",
    eligibility: "People with disabilities in Del Norte/Humboldt/Trinity",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-TST", title: "Tri-County Independent Living (TCIL) - Eureka",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Humboldt, Del Norte, and Trinity counties (regional consortium). Core IL services and accessible housing programs.",
    website_url: "https://tilinet.org/",
    phone: "(707) 445-8404", address: "2222 Harrison Avenue",
    city: "Eureka", zip: "95501",
    eligibility: "People with disabilities in 3 North Coast counties",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-NCS", title: "Resources for Independent Living (RIL) - Sacramento",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Sacramento, Yolo counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition. ADA technical assistance for region.",
    website_url: "https://www.ril-sacramento.org/",
    phone: "(916) 446-3074", address: "420 I Street",
    city: "Sacramento", zip: "95814",
    eligibility: "People with disabilities in Sacramento/Yolo",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-PIL", title: "Placer Independent Resource Services (PIRS) - Auburn",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Placer, El Dorado, Alpine counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.pirs.org/",
    phone: "(530) 885-6100", address: "11768 Atwood Road, Suite 29",
    city: "Auburn", zip: "95603",
    eligibility: "People with disabilities in Placer/El Dorado/Alpine",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-DAS", title: "Disability Action Center / Delta Center - Stockton",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving San Joaquin, Stanislaus, Calaveras, Amador counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.dca-ilc.org/",
    phone: "(209) 472-1660", address: "509 W. Weber Avenue, Suite 104",
    city: "Stockton", zip: "95203",
    eligibility: "People with disabilities in San Joaquin region",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-CCH", title: "Central Coast Center for Independent Living (CCCIL) - Salinas",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Monterey, San Benito, Santa Cruz counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.cccil.org/",
    phone: "(831) 757-2968", address: "318 Cayuga Street, Suite 208",
    city: "Salinas", zip: "93901",
    eligibility: "People with disabilities in Monterey/SBE/SCRZ",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-SLO", title: "Independent Living Resource Center (ILRC) - Santa Barbara",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Ventura, Santa Barbara, San Luis Obispo counties. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.ilrc-trico.org/",
    phone: "(805) 963-0595", address: "423 W. Victoria Street",
    city: "Santa Barbara", zip: "93101",
    eligibility: "People with disabilities in Tri-Counties",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-KER", title: "Independent Living Center of Kern County - Bakersfield",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Kern County. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition.",
    website_url: "https://www.ilcofkerncounty.org/",
    phone: "(661) 325-1063", address: "5251 Office Park Drive, Suite 200",
    city: "Bakersfield", zip: "93309",
    eligibility: "People with disabilities in Kern County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-ACC", title: "Access to Independence (A2i) - San Diego",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving San Diego County. Core IL services: peer counseling, IL skills training, advocacy, info & referral, transition. Strong focus on assistive tech.",
    website_url: "https://www.accesstoindependence.org/",
    phone: "(619) 293-3500", address: "8885 Rio San Diego Drive, Suite 131",
    city: "San Diego", zip: "92108",
    eligibility: "People with disabilities in SD County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-IMP", title: "Center for Disability Empowerment / IVCIL - Imperial Valley",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Imperial County. Core IL services: peer counseling, IL skills training, advocacy, info & referral.",
    website_url: "https://www.ivcil.com/",
    phone: "(760) 355-8800", address: "512 W. Aten Road",
    city: "Imperial", zip: "92251",
    eligibility: "People with disabilities in Imperial County",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },
  {
    section: "ILC-NOR", title: "Independent Living Services of Northern California (ILSNC) - Chico",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "DOR-funded ILC serving Butte, Glenn, Tehama, Modoc, Lassen, Shasta, Siskiyou, Trinity counties. Core IL services for far Northern California.",
    website_url: "https://www.ilsnc.org/",
    phone: "(530) 893-8527", address: "1161 East Avenue",
    city: "Chico", zip: "95926",
    eligibility: "People with disabilities in 8 far-North counties",
    source_name: "CA Department of Rehabilitation ILC network", source_type: "nonprofit",
  },

  // ============== CAREGIVER RESOURCE CENTERS (CDA, 11 STATEWIDE) ==============
  {
    section: "CRC-NORCAL", title: "Del Oro Caregiver Resource Center (Northern Sierra)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving 13 Northern California counties (Sacramento, Yolo, Placer, El Dorado, Sutter, Yuba, Sierra, Nevada, Plumas, Lassen, Modoc, Sierra, Alpine). Free care planning, respite vouchers, support groups for family caregivers of adults with cognitive impairments.",
    website_url: "https://www.deloro.org/",
    phone: "(916) 728-9333", address: "8421 Auburn Boulevard, Suite 265",
    city: "Citrus Heights", zip: "95610",
    eligibility: "Family caregivers of adults with cognitive/functional impairments",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-FCA", title: "Family Caregiver Alliance / Bay Area CRC",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving 6 Bay Area counties (SF, Alameda, Contra Costa, Marin, San Mateo, Santa Clara). Free care planning, respite vouchers, support groups, online caregiver education. National policy headquarters.",
    website_url: "https://www.caregiver.org/",
    phone: "(415) 434-3388", address: "101 Montgomery Street, Suite 2150",
    city: "San Francisco", zip: "94104",
    eligibility: "Family caregivers of adults with cognitive/functional impairments",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-NCC", title: "Del Mar Caregiver Resource Center (Central Coast)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving Monterey, San Benito, Santa Cruz counties. Free care planning, respite vouchers, support groups for family caregivers of adults with cognitive impairments.",
    website_url: "https://www.delmarcaregiver.org/",
    phone: "(831) 459-6639", address: "1537 Pacific Avenue, Suite 300",
    city: "Santa Cruz", zip: "95060",
    eligibility: "Family caregivers of adults with cognitive impairments",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-MEN", title: "Mountain Caregiver Resource Center (Far North)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving Butte, Colusa, Glenn, Tehama, Shasta, Trinity, Siskiyou counties. Free care planning, respite vouchers, support groups.",
    website_url: "https://www.passagescenter.org/services/caregiver-services/",
    phone: "(530) 898-5925", address: "25 Main Street, Suite 202",
    city: "Chico", zip: "95928",
    eligibility: "Family caregivers in 7 far-North counties",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-RED", title: "Redwood Caregiver Resource Center (North Coast)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving Del Norte, Humboldt, Mendocino, Lake, Sonoma, Napa, Solano counties. Free care planning, respite vouchers, support groups.",
    website_url: "https://www.redwoodcrc.org/",
    phone: "(707) 542-0282", address: "141 Stony Circle, Suite 200",
    city: "Santa Rosa", zip: "95401",
    eligibility: "Family caregivers in 7 North Coast counties",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-SD", title: "Southern Caregiver Resource Center (San Diego/Imperial)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving SD and Imperial counties. Free care planning, respite vouchers, support groups in English and Spanish.",
    website_url: "https://www.caregivercenter.org/",
    phone: "(858) 268-4432", address: "3675 Ruffin Road, Suite 230",
    city: "San Diego", zip: "92123",
    eligibility: "Family caregivers in SD/IM counties",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-OC", title: "Caregiver Resource Center Orange County (CRCOC)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving Orange County (operated by St. Jude Medical Center). Free care planning, respite vouchers, support groups.",
    website_url: "https://www.stjudemedicalcenter.org/services/caregiver-resource-center",
    phone: "(714) 446-5030", address: "130 W. Bastanchury Road",
    city: "Fullerton", zip: "92835",
    eligibility: "Family caregivers in OC",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-IE", title: "Inland Caregiver Resource Center (Inland Empire)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving Riverside, San Bernardino, Inyo, Mono counties. Free care planning, respite vouchers, support groups.",
    website_url: "https://www.inlandcaregivers.org/",
    phone: "(800) 675-6694", address: "1430 E. Cooley Drive, Suite 100",
    city: "Colton", zip: "92324",
    eligibility: "Family caregivers in Inland Empire + Eastern Sierra",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-CV", title: "Valley Caregiver Resource Center (Central Valley)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving Fresno, Kings, Madera, Mariposa, Tulare, Tuolumne, Calaveras, Amador, Alpine counties. Free care planning, respite vouchers, support groups; also operates HICAP.",
    website_url: "https://www.valleycrc.org/",
    phone: "(559) 224-9154", address: "3845 N. Clark Street, Suite 201",
    city: "Fresno", zip: "93726",
    eligibility: "Family caregivers in 9 Central Valley/Sierra counties",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },
  {
    section: "CRC-SC", title: "Caregiver Resource Center Tri-Counties (SLO/SBA/Ventura)",
    cat: "family-support", sub: "Caregiver Support",
    desc: "CDA-funded CRC serving SLO, Santa Barbara, Ventura counties (operated by St. John's Healthcare Foundation). Free care planning, respite vouchers, support groups.",
    website_url: "https://www.dignityhealth.org/central-coast/locations/stjohnsregional/about-us/community-programs/caregiver-resource-center",
    phone: "(805) 988-2693", address: "1700 N. Rose Avenue",
    city: "Oxnard", zip: "93030",
    eligibility: "Family caregivers in SLO/SB/Ventura",
    source_name: "CA Department of Aging CRC network", source_type: "nonprofit",
  },

  // ============== ADDITIONAL FAMILY JUSTICE CENTERS ==============
  {
    section: "FJC-SD", title: "San Diego Family Justice Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Founding model FJC for the U.S. (founded 2002). One-stop services for DV, sexual assault, child abuse, elder abuse, and human trafficking victims in SD County: legal advocacy, civil legal services, prosecution, shelter coordination, mental health.",
    website_url: "https://www.sandiego.gov/sandiegofamilyjusticecenter",
    phone: "(619) 533-6000", address: "1122 Broadway, Suite 200",
    city: "San Diego", zip: "92101",
    eligibility: "Survivors of family violence in SD County",
    source_name: "City of San Diego canonical / FJC Alliance", source_type: "government_agency",
  },
  {
    section: "FJC-LA", title: "Los Angeles Family Justice Center (City Attorney)",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "LA City Attorney Family Justice Center. One-stop services for DV survivors in LA: legal advocacy, civil legal services, restraining orders, prosecution, shelter coordination.",
    website_url: "https://www.lacityattorney.org/family-justice-center",
    phone: "(213) 978-4530", address: "200 N. Spring Street, Suite 1700",
    city: "Los Angeles", zip: "90012",
    eligibility: "Survivors of family violence in LA",
    source_name: "LA City Attorney canonical / FJC Alliance", source_type: "government_agency",
  },
  {
    section: "FJC-AC", title: "Alameda County Family Justice Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Alameda County FJC operating in Oakland and Hayward. One-stop services for DV, sexual assault, child abuse, elder abuse, human trafficking survivors: legal advocacy, civil legal services, mental health, shelter coordination.",
    website_url: "https://www.acfjc.org/",
    phone: "(510) 267-8800", address: "470 27th Street",
    city: "Oakland", zip: "94612",
    eligibility: "Survivors of family violence in Alameda County",
    source_name: "ACFJC canonical / FJC Alliance", source_type: "nonprofit",
  },
  {
    section: "FJC-CC", title: "Contra Costa Family Justice Centers",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Contra Costa County FJCs in Richmond, Concord, and Antioch. One-stop services for DV, sexual assault, human trafficking survivors: legal advocacy, civil legal services, mental health, shelter coordination.",
    website_url: "https://cocofamilyjustice.org/",
    phone: "(925) 281-0970", address: "256 24th Street",
    city: "Richmond", zip: "94804",
    eligibility: "Survivors of family violence in Contra Costa County",
    source_name: "Contra Costa FJC canonical / FJC Alliance", source_type: "nonprofit",
  },
  {
    section: "FJC-SR", title: "Sonoma County Family Justice Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Sonoma County FJC in Santa Rosa. One-stop services for DV, sexual assault, child abuse, elder abuse, human trafficking survivors.",
    website_url: "https://www.fjcsc.org/",
    phone: "(707) 565-8255", address: "2300 County Center Drive, Suite B-180",
    city: "Santa Rosa", zip: "95403",
    eligibility: "Survivors of family violence in Sonoma County",
    source_name: "Sonoma County FJC canonical / FJC Alliance", source_type: "government_agency",
  },
  {
    section: "FJC-SAC", title: "Sacramento Family Justice Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Sacramento County FJC. One-stop services for DV, sexual assault, child abuse, elder abuse survivors: legal advocacy, civil legal services, mental health, shelter coordination.",
    website_url: "https://saccountyfjc.org/",
    phone: "(916) 875-4673", address: "3701 Branch Center Road",
    city: "Sacramento", zip: "95827",
    eligibility: "Survivors of family violence in Sacramento County",
    source_name: "Sacramento County FJC canonical / FJC Alliance", source_type: "government_agency",
  },
  {
    section: "FJC-SC", title: "Santa Clara County Family Justice Center / YWCA",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Santa Clara County FJC operated by YWCA Silicon Valley in San Jose. One-stop services for DV, sexual assault, human trafficking survivors.",
    website_url: "https://ywca-sv.org/get-help/family-justice-center/",
    phone: "(408) 510-8400", address: "375 S. 3rd Street",
    city: "San Jose", zip: "95112",
    eligibility: "Survivors of family violence in Santa Clara County",
    source_name: "YWCA Silicon Valley canonical / FJC Alliance", source_type: "nonprofit",
  },
  {
    section: "FJC-SB", title: "San Bernardino County Children's Network / FJC",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "San Bernardino County FJC. One-stop services for DV, sexual assault, child abuse survivors: legal advocacy, civil legal services, mental health, shelter coordination.",
    website_url: "https://wp.sbcounty.gov/childrensnetwork/",
    phone: "(909) 387-4949", address: "385 N. Arrowhead Avenue",
    city: "San Bernardino", zip: "92415",
    eligibility: "Survivors of family violence in San Bernardino County",
    source_name: "SB County canonical / FJC Alliance", source_type: "government_agency",
  },
  {
    section: "FJC-RIV", title: "Riverside County Family Justice Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Riverside County FJC. One-stop services for DV, sexual assault, child abuse, elder abuse survivors. Locations in Riverside and Murrieta.",
    website_url: "https://www.fjcriversideco.org/",
    phone: "(951) 955-6100", address: "10000 County Farm Road, Building 1",
    city: "Riverside", zip: "92503",
    eligibility: "Survivors of family violence in Riverside County",
    source_name: "Riverside County FJC canonical / FJC Alliance", source_type: "government_agency",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B7 — AAA + ILC + CRC + FJC Statewide", state: "CA" });
