import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!
);

const CATEGORIES = {
  housing: "f222dcb7-1461-4d50-82da-ae1ed47b63c6",
  vaBenefits: "cd38f114-5259-48b8-a4e0-f63681029f58",
  employment: "7e6d093d-52de-4b93-b611-15800d54e2c0",
  mentalHealth: "19a1421f-fc22-486b-9730-b1c54339a123",
  education: "bbd2eb59-f434-4edd-b337-139f16ce54ff",
  legal: "2e666cde-1d62-481f-86ee-d60a5a5f866f",
  communitySupport: "728dcbf9-8941-4f9c-8953-0abf385409a2",
};

interface Resource {
  category_id: string;
  title: string;
  short_description: string;
  website_url?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  state: string;
  zip?: string;
  eligibility?: string;
  source_name: string;
  source_type: string;
  status: string;
  sponsored: boolean;
}

const resources: Resource[] = [
  // ===== HOUSING ASSISTANCE =====
  // Statewide
  {
    category_id: CATEGORIES.housing,
    title: "SC State Housing Finance & Development Authority",
    short_description: "Statewide housing programs including down payment assistance, homebuyer education, and rental assistance for South Carolina residents.",
    website_url: "https://www.schousing.com",
    phone: "803-896-9001",
    state: "SC",
    source_name: "SC Housing",
    source_type: "program",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.housing,
    title: "SC Coalition for the Homeless",
    short_description: "Statewide advocacy and coordination of services to prevent and end homelessness in South Carolina.",
    website_url: "https://www.schomeless.org",
    phone: "803-779-4706",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.housing,
    title: "SSVF – Supportive Services for Veteran Families (SC)",
    short_description: "Rapid rehousing and homelessness prevention for veteran families across South Carolina through case management and financial assistance.",
    website_url: "https://www.va.gov/homeless/ssvf/",
    phone: "1-877-424-3838",
    state: "SC",
    source_name: "VA",
    source_type: "program",
    status: "approved",
    sponsored: false,
  },
  // Charleston metro
  {
    category_id: CATEGORIES.housing,
    title: "Charleston County Veterans Affairs Office",
    short_description: "County veterans office providing housing referrals, benefits assistance, and emergency support for veterans in Charleston County.",
    website_url: "https://www.charlestoncounty.org/departments/veterans-affairs/",
    phone: "843-202-6685",
    address: "4045 Bridge View Dr, Suite B-244",
    city: "North Charleston",
    state: "SC",
    zip: "29405",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.housing,
    title: "One80 Place – Veterans Housing",
    short_description: "Emergency shelter and transitional housing for homeless veterans in the Charleston area, including HUD-VASH support.",
    website_url: "https://www.one80place.org",
    phone: "843-723-9477",
    address: "35 Walton St",
    city: "Charleston",
    state: "SC",
    zip: "29403",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Columbia
  {
    category_id: CATEGORIES.housing,
    title: "Richland County Veterans Affairs",
    short_description: "County veterans services including housing assistance, benefits claims support, and referrals for Richland County veterans.",
    phone: "803-576-1733",
    address: "2020 Hampton St",
    city: "Columbia",
    state: "SC",
    zip: "29204",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.housing,
    title: "Transitions Homeless Center",
    short_description: "Emergency shelter and support services for homeless individuals including veterans in the Columbia, SC area.",
    website_url: "https://www.transitionssc.org",
    phone: "803-708-4861",
    address: "2025 Main St",
    city: "Columbia",
    state: "SC",
    zip: "29201",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Greenville
  {
    category_id: CATEGORIES.housing,
    title: "Greenville County Veterans Affairs",
    short_description: "County VSO providing housing referrals, claims assistance, and emergency resources for Greenville County veterans.",
    phone: "864-467-7340",
    address: "301 University Ridge, Suite 2600",
    city: "Greenville",
    state: "SC",
    zip: "29601",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.housing,
    title: "United Housing Connections – Greenville",
    short_description: "Housing counseling, rental assistance, and homelessness prevention services in the Upstate SC region.",
    website_url: "https://www.unitedhousingconnections.org",
    phone: "864-235-4009",
    city: "Greenville",
    state: "SC",
    zip: "29601",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Myrtle Beach
  {
    category_id: CATEGORIES.housing,
    title: "Horry County Veterans Affairs",
    short_description: "County veterans office serving the Myrtle Beach area with benefits claims, housing referrals, and emergency assistance.",
    phone: "843-915-5390",
    address: "1301 2nd Ave",
    city: "Myrtle Beach",
    state: "SC",
    zip: "29577",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },

  // ===== VA BENEFITS =====
  // Statewide
  {
    category_id: CATEGORIES.vaBenefits,
    title: "SC Department of Veterans' Affairs",
    short_description: "State agency advocating for South Carolina's 400,000+ veterans. Provides claims assistance, benefits counseling, and referrals statewide.",
    website_url: "https://scdva.sc.gov",
    phone: "803-647-2434",
    address: "1205 Pendleton St, Suite 463",
    city: "Columbia",
    state: "SC",
    zip: "29201",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.vaBenefits,
    title: "Columbia VA Regional Office",
    short_description: "Federal VA regional office handling disability claims, pension, education benefits, and home loan eligibility for SC veterans.",
    website_url: "https://www.va.gov/columbia-regional-benefit-office/",
    phone: "800-827-1000",
    address: "6437 Garners Ferry Rd",
    city: "Columbia",
    state: "SC",
    zip: "29209",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.vaBenefits,
    title: "SC Veterans Trust Fund",
    short_description: "Emergency financial assistance for SC veterans and their families, including help with rent, utilities, food, and medical expenses.",
    website_url: "https://scdva.sc.gov/veterans-trust-fund",
    phone: "803-647-2434",
    state: "SC",
    source_name: "State agency",
    source_type: "program",
    status: "approved",
    sponsored: false,
  },
  // Charleston
  {
    category_id: CATEGORIES.vaBenefits,
    title: "Ralph H. Johnson VA Medical Center – Benefits Office",
    short_description: "On-site benefits assistance at the Charleston VA Medical Center for claims, enrollment, and eligibility verification.",
    website_url: "https://www.va.gov/charleston-health-care/",
    phone: "843-577-5011",
    address: "109 Bee St",
    city: "Charleston",
    state: "SC",
    zip: "29401",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.vaBenefits,
    title: "DAV Chapter 12 – Charleston",
    short_description: "Disabled American Veterans chapter providing free claims assistance, transportation to VA facilities, and veteran advocacy.",
    website_url: "https://www.dav.org",
    phone: "843-789-7000",
    city: "Charleston",
    state: "SC",
    zip: "29401",
    source_name: "DAV",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Columbia
  {
    category_id: CATEGORIES.vaBenefits,
    title: "WJB Dorn VA Medical Center",
    short_description: "Full-service VA medical center in Columbia providing healthcare, benefits enrollment, and veteran support services.",
    website_url: "https://www.va.gov/columbia-south-carolina-health-care/",
    phone: "803-776-4000",
    address: "6439 Garners Ferry Rd",
    city: "Columbia",
    state: "SC",
    zip: "29209",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Greenville
  {
    category_id: CATEGORIES.vaBenefits,
    title: "Greenville VA Clinic",
    short_description: "VA outpatient clinic providing primary care, mental health services, and benefits information for Upstate SC veterans.",
    website_url: "https://www.va.gov/columbia-south-carolina-health-care/locations/greenville-va-clinic/",
    phone: "864-299-1600",
    address: "41 Commonwealth Dr",
    city: "Greenville",
    state: "SC",
    zip: "29615",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.vaBenefits,
    title: "VFW Post 3747 – Greenville",
    short_description: "Veterans of Foreign Wars post offering claims assistance, community events, and veteran camaraderie in Greenville.",
    website_url: "https://www.vfw.org",
    phone: "864-271-5213",
    city: "Greenville",
    state: "SC",
    zip: "29607",
    source_name: "VFW",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Spartanburg
  {
    category_id: CATEGORIES.vaBenefits,
    title: "Spartanburg County Veterans Affairs",
    short_description: "County veterans office providing claims assistance, referrals, and benefits counseling for Spartanburg County veterans.",
    phone: "864-562-4119",
    address: "366 N Church St",
    city: "Spartanburg",
    state: "SC",
    zip: "29303",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Rock Hill
  {
    category_id: CATEGORIES.vaBenefits,
    title: "York County Veterans Affairs",
    short_description: "County veterans office serving Rock Hill and York County with claims assistance and benefits counseling.",
    phone: "803-684-8505",
    address: "6 S Congress St",
    city: "Rock Hill",
    state: "SC",
    zip: "29730",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Summerville
  {
    category_id: CATEGORIES.vaBenefits,
    title: "Dorchester County Veterans Affairs",
    short_description: "County veterans office providing claims filing assistance, benefits counseling, and referrals for Dorchester County veterans.",
    phone: "843-832-0270",
    address: "201 Johnston St",
    city: "Summerville",
    state: "SC",
    zip: "29483",
    source_name: "County VSO",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },

  // ===== EMPLOYMENT =====
  // Statewide
  {
    category_id: CATEGORIES.employment,
    title: "SC Works – Veterans Employment Services",
    short_description: "Priority employment services for veterans through SC Works centers statewide, including resume help, job search, and training referrals.",
    website_url: "https://www.scworks.org",
    phone: "803-737-2400",
    state: "SC",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.employment,
    title: "SC Department of Employment and Workforce – LVER/DVOP",
    short_description: "Local Veterans Employment Representatives (LVER) and Disabled Veterans Outreach Program (DVOP) specialists in SC Works centers statewide.",
    website_url: "https://dew.sc.gov/job-seekers/veterans",
    phone: "803-737-2400",
    state: "SC",
    source_name: "State agency",
    source_type: "program",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.employment,
    title: "Hire Heroes USA – South Carolina",
    short_description: "Free career coaching, resume writing, mentoring, and job placement for transitioning military, veterans, and military spouses.",
    website_url: "https://www.hireheroesusa.org",
    phone: "844-634-1520",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Charleston
  {
    category_id: CATEGORIES.employment,
    title: "SC Works Trident – North Charleston",
    short_description: "Full-service SC Works center with veteran priority of service, career counseling, workshops, and job placement assistance.",
    website_url: "https://www.tridentscworks.org",
    phone: "843-574-1800",
    address: "1930 Hanahan Rd, Suite 200",
    city: "North Charleston",
    state: "SC",
    zip: "29406",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Columbia
  {
    category_id: CATEGORIES.employment,
    title: "SC Works Midlands – Columbia",
    short_description: "SC Works center serving the Midlands region with veteran employment priority, job fairs, and career development resources.",
    website_url: "https://www.midlandsscworks.org",
    phone: "803-737-9935",
    address: "700 Taylor St",
    city: "Columbia",
    state: "SC",
    zip: "29201",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Greenville
  {
    category_id: CATEGORIES.employment,
    title: "SC Works Greenville Center",
    short_description: "Upstate SC Works center providing veteran priority employment services, skills assessments, and employer connections.",
    phone: "864-467-3636",
    address: "135 Edinburgh Ct",
    city: "Greenville",
    state: "SC",
    zip: "29607",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Myrtle Beach
  {
    category_id: CATEGORIES.employment,
    title: "SC Works Waccamaw – Myrtle Beach",
    short_description: "SC Works center serving the Grand Strand region with veteran employment services, training referrals, and job matching.",
    phone: "843-546-8502",
    city: "Myrtle Beach",
    state: "SC",
    zip: "29577",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.employment,
    title: "Goodwill Industries Veteran Services – SC",
    short_description: "Job training, placement assistance, and career services specifically designed for veterans across South Carolina.",
    website_url: "https://www.goodwillsc.org",
    phone: "864-467-3434",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.employment,
    title: "American Legion Post 147 – Mount Pleasant",
    short_description: "American Legion post providing veteran networking, employment referrals, and community support in the Mount Pleasant area.",
    website_url: "https://www.legion.org",
    phone: "843-884-7076",
    city: "Mount Pleasant",
    state: "SC",
    zip: "29464",
    source_name: "American Legion",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },

  // ===== MENTAL HEALTH =====
  // Statewide
  {
    category_id: CATEGORIES.mentalHealth,
    title: "SC Department of Mental Health – Veterans Services",
    short_description: "State mental health services for veterans including counseling, crisis intervention, and psychiatric care across SC community mental health centers.",
    website_url: "https://scdmh.net",
    phone: "803-898-8581",
    state: "SC",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Veterans Crisis Line",
    short_description: "24/7 confidential crisis support for veterans and their families. Call, text, or chat. Dial 988, then press 1.",
    website_url: "https://www.veteranscrisisline.net",
    phone: "988",
    state: "SC",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.mentalHealth,
    title: "NAMI South Carolina",
    short_description: "National Alliance on Mental Illness SC chapter providing peer support groups, education programs, and mental health advocacy for veterans and families.",
    website_url: "https://www.namisc.org",
    phone: "803-733-9592",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Charleston
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Charleston Vet Center",
    short_description: "Community-based readjustment counseling for combat veterans, including individual and group therapy, family counseling, and bereavement support.",
    website_url: "https://www.va.gov/find-locations/",
    phone: "843-789-7000",
    address: "5603A Rivers Ave",
    city: "North Charleston",
    state: "SC",
    zip: "29406",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Ralph H. Johnson VAMC – Mental Health Services",
    short_description: "Comprehensive mental health services at the Charleston VA including PTSD treatment, substance use programs, and psychiatric care.",
    website_url: "https://www.va.gov/charleston-health-care/",
    phone: "843-577-5011",
    address: "109 Bee St",
    city: "Charleston",
    state: "SC",
    zip: "29401",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Columbia
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Columbia Vet Center",
    short_description: "Readjustment counseling, PTSD treatment, military sexual trauma support, and bereavement counseling for Columbia-area veterans.",
    phone: "803-765-9944",
    address: "1513 Pickens St",
    city: "Columbia",
    state: "SC",
    zip: "29201",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.mentalHealth,
    title: "WJB Dorn VAMC – PTSD Clinical Team",
    short_description: "Specialized PTSD treatment program at the Columbia VA Medical Center including evidence-based therapies CPT and PE.",
    website_url: "https://www.va.gov/columbia-south-carolina-health-care/",
    phone: "803-776-4000",
    address: "6439 Garners Ferry Rd",
    city: "Columbia",
    state: "SC",
    zip: "29209",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Greenville
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Greenville Vet Center",
    short_description: "Community-based readjustment counseling for Upstate SC veterans including individual, group, and family therapy.",
    phone: "864-271-2711",
    address: "3 Caledon Ct, Suite A",
    city: "Greenville",
    state: "SC",
    zip: "29615",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Myrtle Beach
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Myrtle Beach VA Clinic – Mental Health",
    short_description: "Outpatient mental health services for Grand Strand area veterans including therapy, medication management, and crisis support.",
    phone: "843-477-0177",
    address: "3381 Phillis Blvd",
    city: "Myrtle Beach",
    state: "SC",
    zip: "29577",
    source_name: "VA",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.mentalHealth,
    title: "Steven A. Cohen Military Family Clinic at MUSC",
    short_description: "Low-cost mental health care for post-9/11 veterans and military families at the Medical University of South Carolina.",
    website_url: "https://www.cohenveteransnetwork.org",
    phone: "843-577-9888",
    city: "Charleston",
    state: "SC",
    zip: "29425",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },

  // ===== EDUCATION =====
  // Statewide
  {
    category_id: CATEGORIES.education,
    title: "SC Commission on Higher Education – Veterans Education",
    short_description: "Statewide coordination of GI Bill and education benefits at SC colleges and universities. Free tuition for certain SC veterans.",
    website_url: "https://www.che.sc.gov",
    phone: "803-737-2260",
    state: "SC",
    source_name: "State agency",
    source_type: "program",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.education,
    title: "SC Technical College System – Veterans Services",
    short_description: "16 technical colleges statewide offering GI Bill-approved programs, veteran liaisons, and career training for SC veterans.",
    website_url: "https://www.sctechsystem.edu",
    phone: "803-896-5320",
    state: "SC",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.education,
    title: "SC Free Tuition for Certain Veterans",
    short_description: "South Carolina offers free tuition at state colleges and universities for children of veterans who were POW, MIA, KIA, or permanently disabled.",
    website_url: "https://scdva.sc.gov/benefits/education",
    phone: "803-647-2434",
    state: "SC",
    source_name: "State agency",
    source_type: "program",
    status: "approved",
    sponsored: false,
  },
  // Charleston
  {
    category_id: CATEGORIES.education,
    title: "Trident Technical College – Veterans Center",
    short_description: "Dedicated veterans center at Trident Tech providing GI Bill processing, academic advising, tutoring, and peer support.",
    website_url: "https://www.tridenttech.edu/veterans",
    phone: "843-574-6111",
    address: "7000 Rivers Ave",
    city: "North Charleston",
    state: "SC",
    zip: "29406",
    source_name: "College",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.education,
    title: "The Citadel – Veteran Student Success Center",
    short_description: "Dedicated center for veteran students at The Citadel providing academic support, GI Bill assistance, and transition resources.",
    website_url: "https://www.citadel.edu",
    phone: "843-953-5000",
    address: "171 Moultrie St",
    city: "Charleston",
    state: "SC",
    zip: "29409",
    source_name: "College",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Columbia
  {
    category_id: CATEGORIES.education,
    title: "University of South Carolina – Student Veterans Association",
    short_description: "Student veteran organization and support services at USC including GI Bill processing, academic advising, and community.",
    website_url: "https://www.sc.edu/about/offices_and_divisions/veterans_and_military_services/",
    phone: "803-777-7700",
    city: "Columbia",
    state: "SC",
    zip: "29208",
    source_name: "College",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.education,
    title: "Midlands Technical College – Veterans Center",
    short_description: "Veterans resource center at Midlands Tech offering GI Bill support, career training, and academic guidance.",
    website_url: "https://www.midlandstech.edu",
    phone: "803-738-8324",
    city: "Columbia",
    state: "SC",
    zip: "29250",
    source_name: "College",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Greenville
  {
    category_id: CATEGORIES.education,
    title: "Greenville Technical College – Veterans Services",
    short_description: "GI Bill processing, academic advising, and veteran peer support at Greenville Tech's veteran resource center.",
    website_url: "https://www.gvltec.edu",
    phone: "864-250-8111",
    address: "506 S Pleasantburg Dr",
    city: "Greenville",
    state: "SC",
    zip: "29607",
    source_name: "College",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Spartanburg
  {
    category_id: CATEGORIES.education,
    title: "Spartanburg Community College – Veterans Center",
    short_description: "Veteran services center offering GI Bill support, career training programs, and academic advising for Spartanburg area veterans.",
    website_url: "https://www.sccsc.edu",
    phone: "864-592-4600",
    city: "Spartanburg",
    state: "SC",
    zip: "29303",
    source_name: "College",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },

  // ===== LEGAL HELP =====
  // Statewide
  {
    category_id: CATEGORIES.legal,
    title: "SC Legal Aid – Veterans Legal Assistance",
    short_description: "Free civil legal help for low-income SC veterans including housing disputes, family law, benefits appeals, and consumer issues.",
    website_url: "https://www.sclegal.org",
    phone: "888-346-5592",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.legal,
    title: "SC Bar Pro Bono Program – Veterans",
    short_description: "Volunteer attorneys providing free legal assistance to SC veterans for civil matters including wills, landlord-tenant, and discharge upgrades.",
    website_url: "https://www.scbar.org/public/pro-bono/",
    phone: "803-799-6653",
    state: "SC",
    source_name: "State Bar",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.legal,
    title: "SC Appleseed Legal Justice Center",
    short_description: "Advocacy organization providing legal support on issues affecting low-income South Carolinians including veterans' rights.",
    website_url: "https://www.scjustice.org",
    phone: "803-779-1113",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Charleston
  {
    category_id: CATEGORIES.legal,
    title: "Charleston Pro Bono Legal Services – Veterans Clinic",
    short_description: "Free legal clinics for Charleston-area veterans covering wills, powers of attorney, benefits appeals, and landlord-tenant issues.",
    website_url: "https://www.charlestonprobono.org",
    phone: "843-534-0066",
    city: "Charleston",
    state: "SC",
    zip: "29401",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Columbia
  {
    category_id: CATEGORIES.legal,
    title: "University of South Carolina School of Law – Veterans Legal Clinic",
    short_description: "Law school clinic providing free legal representation to SC veterans for discharge upgrades, VA benefits appeals, and civil matters.",
    website_url: "https://sc.edu/study/colleges_schools/law/",
    phone: "803-777-6860",
    city: "Columbia",
    state: "SC",
    zip: "29208",
    source_name: "Law School",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Greenville
  {
    category_id: CATEGORIES.legal,
    title: "SC Legal Services – Greenville Office",
    short_description: "Free civil legal services for low-income veterans in the Greenville area including housing, family law, and benefits issues.",
    website_url: "https://www.sclegal.org",
    phone: "864-679-3232",
    city: "Greenville",
    state: "SC",
    zip: "29601",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.legal,
    title: "SC Dept. of Consumer Affairs – Military/Veterans",
    short_description: "Consumer protection services for SC service members and veterans including fraud prevention, debt relief referrals, and SCRA enforcement.",
    website_url: "https://www.consumer.sc.gov",
    phone: "803-734-4200",
    state: "SC",
    source_name: "State agency",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.legal,
    title: "Fort Jackson Legal Assistance Office",
    short_description: "Free legal assistance for active duty, retirees, and veterans at Fort Jackson covering wills, POA, family law, and consumer issues.",
    phone: "803-751-6895",
    address: "4600 Strom Thurmond Blvd",
    city: "Columbia",
    state: "SC",
    zip: "29207",
    source_name: "Military",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },

  // ===== COMMUNITY SUPPORT (Helper Infrastructure) =====
  // VFW Posts
  {
    category_id: CATEGORIES.communitySupport,
    title: "VFW Post 10624 – Charleston",
    short_description: "Veterans of Foreign Wars post providing community, service referrals, benefits assistance, and events for Charleston-area veterans.",
    website_url: "https://www.vfw.org",
    phone: "843-747-5821",
    city: "Charleston",
    state: "SC",
    zip: "29407",
    source_name: "VFW",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.communitySupport,
    title: "VFW Post 3484 – Columbia",
    short_description: "VFW post serving Columbia-area veterans with camaraderie, community service, benefits referrals, and veteran advocacy.",
    website_url: "https://www.vfw.org",
    phone: "803-782-5218",
    city: "Columbia",
    state: "SC",
    zip: "29204",
    source_name: "VFW",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.communitySupport,
    title: "VFW Post 9138 – Myrtle Beach",
    short_description: "VFW post serving Grand Strand veterans with community events, service referrals, and veteran advocacy.",
    website_url: "https://www.vfw.org",
    phone: "843-448-8387",
    city: "Myrtle Beach",
    state: "SC",
    zip: "29577",
    source_name: "VFW",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // American Legion
  {
    category_id: CATEGORIES.communitySupport,
    title: "American Legion Post 16 – Summerville",
    short_description: "American Legion post providing veteran community, family programs, employment referrals, and service officer assistance.",
    website_url: "https://www.legion.org",
    phone: "843-871-0359",
    city: "Summerville",
    state: "SC",
    zip: "29483",
    source_name: "American Legion",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.communitySupport,
    title: "American Legion Post 3 – Spartanburg",
    short_description: "American Legion post offering veteran networking, youth programs, benefits referrals, and community support in Spartanburg.",
    website_url: "https://www.legion.org",
    city: "Spartanburg",
    state: "SC",
    zip: "29306",
    source_name: "American Legion",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // DAV
  {
    category_id: CATEGORIES.communitySupport,
    title: "DAV Chapter 6 – Columbia",
    short_description: "Disabled American Veterans chapter providing free transportation to VA facilities, claims assistance, and disability advocacy.",
    website_url: "https://www.dav.org",
    phone: "803-776-4000",
    city: "Columbia",
    state: "SC",
    zip: "29209",
    source_name: "DAV",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  // Other community support
  {
    category_id: CATEGORIES.communitySupport,
    title: "SC 211 – Veteran Resources Line",
    short_description: "Dial 211 for a comprehensive referral service connecting SC veterans with local resources for housing, food, employment, and more.",
    website_url: "https://sc211.org",
    phone: "211",
    state: "SC",
    source_name: "211 Network",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.communitySupport,
    title: "Palmetto Warrior Connection",
    short_description: "SC-based nonprofit connecting post-9/11 veterans and families with peer support, outdoor recreation therapy, and transition assistance.",
    website_url: "https://www.palmettowarriorconnection.org",
    phone: "843-693-9223",
    state: "SC",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.communitySupport,
    title: "Upstate Warrior Solution",
    short_description: "Connecting Upstate SC veterans with resources, peer support, and community through a network of care coordinators.",
    website_url: "https://www.upstatewarriorsolution.org",
    phone: "864-520-3002",
    city: "Greenville",
    state: "SC",
    zip: "29601",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
  {
    category_id: CATEGORIES.communitySupport,
    title: "Lowcountry Warrior Project",
    short_description: "Serving Charleston-area veterans through community events, peer support, outdoor activities, and family programs.",
    website_url: "https://www.lowcountrywarriorproject.org",
    city: "Charleston",
    state: "SC",
    zip: "29401",
    source_name: "Nonprofit",
    source_type: "service",
    status: "approved",
    sponsored: false,
  },
];

async function seed() {
  console.log(`Seeding ${resources.length} SC resources...`);

  const batchSize = 20;
  let inserted = 0;

  for (let i = 0; i < resources.length; i += batchSize) {
    const batch = resources.slice(i, i + batchSize);
    const { data, error } = await supabase.from("resources").insert(batch).select("id, title");

    if (error) {
      console.error(`Error inserting batch ${i / batchSize + 1}:`, error.message);
      continue;
    }

    inserted += (data?.length || 0);
    console.log(`Batch ${Math.floor(i / batchSize) + 1}: inserted ${data?.length || 0} resources`);
  }

  console.log(`\nDone! Inserted ${inserted} / ${resources.length} resources.`);

  const { count } = await supabase
    .from("resources")
    .select("*", { count: "exact", head: true })
    .eq("state", "SC")
    .eq("status", "approved");

  console.log(`Total approved SC resources in database: ${count}`);
}

seed().catch(console.error);
