/**
 * PA REBUILD — PHASE 4: MAJOR CITY SATURATION
 * Founder one-phase-per-run governance lock — approved 2026-04-27.
 *
 * Scope per founder approval:
 *   Priority metros: Philadelphia, Pittsburgh, Harrisburg, Allentown/Bethlehem,
 *   Scranton/Wilkes-Barre, Erie, Lancaster, Reading.
 *   Focus: housing, food banks, shelters, employment, legal aid,
 *   hospitals/clinics, transportation, crisis support, recovery, family
 *   support, disability help, veteran orgs, mainstream support.
 *
 * Skip blockers, skip messy sources (founder lock).
 *
 * URL liveness: every row pre-probed via parallel curl probe with engine UA
 *   "VeteranCare-RolloutEngine/1.0 (+url-liveness-gate)" before authoring.
 *   Drops (no canonical live URL): Veterans Place of Washington Blvd,
 *   Operation Stand Down Pittsburgh, Catholic Social Services NEPA,
 *   DV Service Center NEPA, DV Services of Lancaster, PA American Legion HQ,
 *   PA Paralyzed Vets — covered indirectly by PA DMVA county VSO directory
 *   + national parents (P1) and statewide AmVets/VFW posts.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [

  // ======================== PHILADELPHIA METRO — 14 ========================
  { section: "PHL", title: "Veterans Multi-Service Center (VMSC) — Philadelphia", cat: "housing", sub: "Homeless Veteran Services", city: "Philadelphia", website_url: "https://www.vmcenter.org/", source_name: "Veterans Multi-Service Center", source_type: "veteran_nonprofit", phone: "215-923-2600", address: "213-217 N 4th St, Philadelphia, PA 19106", zip: "19106", desc: "Veterans Multi-Service Center (VMSC) — Philadelphia-headquartered veteran nonprofit and one of the largest in the U.S.; operates Perimeter Veterans Outreach housing, employment & training (HVRP), HUD-VASH case management, supportive services for veteran families (SSVF), benefits counseling, and the Veterans House emergency-bridge shelter. Serves DE Valley veterans across PA/NJ/DE." },
  { section: "PHL", title: "Bethesda Project — Philadelphia", cat: "housing", sub: "Emergency Housing", city: "Philadelphia", website_url: "https://bethesdaproject.org/", source_name: "Bethesda Project", source_type: "nonprofit_organization", phone: "215-985-1600", address: "1630 South St, Philadelphia, PA 19146", zip: "19146", desc: "Bethesda Project — Philadelphia homeless-services nonprofit; 14 sites including emergency shelters (My Brother's House, Our Brothers' Place), recovery houses, permanent supportive housing, and outreach. Veterans accepted; coordinates referrals to VMSC and HUD-VASH." },
  { section: "PHL", title: "Sunday Breakfast Rescue Mission — Philadelphia", cat: "housing", sub: "Emergency Housing", city: "Philadelphia", website_url: "https://sundaybreakfast.org/", source_name: "Sunday Breakfast Rescue Mission", source_type: "faith_based_nonprofit", phone: "215-922-6400", address: "302 N 13th St, Philadelphia, PA 19107", zip: "19107", desc: "Sunday Breakfast Rescue Mission — 145-year-old Philadelphia rescue mission; 240-bed emergency shelter for men, women, and families; meals, addiction recovery (New Journey), workforce development, case management. Veterans welcome; partners with VMSC for veteran intake." },
  { section: "PHL", title: "People's Emergency Center (PEC) — West Philadelphia", cat: "housing", sub: "Transitional Housing", city: "Philadelphia", website_url: "https://www.pec-cares.org/", source_name: "People's Emergency Center", source_type: "nonprofit_organization", phone: "267-777-5880", address: "3902 Spring Garden St, Philadelphia, PA 19104", zip: "19104", desc: "People's Emergency Center — West Philadelphia community-development nonprofit; transitional housing for women & families experiencing homelessness, rapid rehousing, supportive services, workforce development. Veterans accepted; partners with VMSC, HUD-VASH continuum." },
  { section: "PHL", title: "Impact Services — Philadelphia", cat: "housing", sub: "Homeless Veteran Services", city: "Philadelphia", website_url: "https://impactservices.org/", source_name: "Impact Services Corporation", source_type: "nonprofit_organization", phone: "215-739-1600", address: "1952 E Allegheny Ave, Philadelphia, PA 19134", zip: "19134", desc: "Impact Services — Philadelphia community-development nonprofit; veteran transitional housing program (Perkins Veterans Residence, 50 beds), HVRP veteran employment, workforce training, neighborhood revitalization in Kensington. Federal SSVF + HVRP grantee." },
  { section: "PHL", title: "Philadelphia Housing Authority (PHA)", cat: "housing", sub: "Rental Assistance", city: "Philadelphia", website_url: "https://www.pha.phila.gov/", source_name: "Philadelphia Housing Authority", source_type: "public_housing_authority", phone: "215-684-4000", address: "2013 Ridge Ave, Philadelphia, PA 19121", zip: "19121", desc: "Philadelphia Housing Authority — fourth-largest public housing authority in the U.S.; administers HCV/Section 8, public housing, HUD-VASH vouchers (in partnership with Crescenz VAMC) for homeless veterans. Veteran preference applies; coordinates with VMSC for case management." },
  { section: "PHL", title: "Philabundance", cat: "food-assistance", sub: "Food Banks", city: "Philadelphia", website_url: "https://www.philabundance.org/", source_name: "Philabundance / Feeding America", source_type: "nonprofit_organization", phone: "215-339-0900", address: "3616 S Galloway St, Philadelphia, PA 19148", zip: "19148", desc: "Philabundance — region's largest hunger-relief organization, Feeding America affiliate; distributes 30+ million pounds of food annually across 9-county DE Valley through 350 partner agencies. Veteran families served via partner pantries; SNAP enrollment assistance available." },
  { section: "PHL", title: "SEPTA CCT Connect — Paratransit", cat: "transportation", sub: "Public Transit Assistance", city: "Philadelphia", website_url: "https://www.septa.org/fares/discounts/cct/", source_name: "Southeastern Pennsylvania Transportation Authority", source_type: "regional_transit_authority", phone: "215-580-7145", address: "1234 Market St, Philadelphia, PA 19107", zip: "19107", desc: "SEPTA CCT Connect — ADA paratransit service for residents of Philadelphia and Bucks/Chester/Delaware/Montgomery counties unable to use SEPTA fixed-route due to disability. Door-to-door shared-ride; serves disabled veterans, accommodates wheelchairs, life-saving medical trips. Reduced-fare program available for seniors 65+ and persons with disabilities." },
  { section: "PHL", title: "Philadelphia Legal Assistance (PLA)", cat: "legal", sub: "Legal Aid Services", city: "Philadelphia", website_url: "https://philalegal.org/", source_name: "Philadelphia Legal Assistance", source_type: "legal_aid_organization", phone: "215-981-3800", address: "718 Arch St Suite 300N, Philadelphia, PA 19106", zip: "19106", desc: "Philadelphia Legal Assistance — federally-funded LSC legal aid for low-income Philadelphians; civil legal help with public benefits (SNAP, Medicaid, SSI/SSDI, unemployment), VA disability/discharge appeals via Veterans Justice Project, eviction defense, consumer protection. Free for income-eligible veterans." },
  { section: "PHL", title: "Community Legal Services of Philadelphia (CLS)", cat: "legal", sub: "Legal Aid Services", city: "Philadelphia", website_url: "https://clsphila.org/", source_name: "Community Legal Services of Philadelphia", source_type: "legal_aid_organization", phone: "215-981-3700", address: "1424 Chestnut St, Philadelphia, PA 19102", zip: "19102", desc: "Community Legal Services of Philadelphia — region's largest legal aid; civil legal help with housing (eviction defense, foreclosure), public benefits (SNAP, Medicaid, TANF), employment, consumer/debt, healthcare. Free for income-eligible Philadelphians including veterans." },
  { section: "PHL", title: "Women Against Abuse — Philadelphia", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Philadelphia", website_url: "https://www.womenagainstabuse.org/", source_name: "Women Against Abuse", source_type: "nonprofit_organization", phone: "1-866-723-3014", address: "100 S Broad St Suite 1341, Philadelphia, PA 19110", zip: "19110", desc: "Women Against Abuse — Philadelphia's domestic-violence agency; 24-hour DV hotline (1-866-723-3014), 100-bed emergency shelter, transitional housing, legal advocacy (Legal Center), counseling, prevention programs. Serves veteran survivors and military spouses; accommodates families." },
  { section: "PHL", title: "Lutheran Settlement House — Philadelphia", cat: "family-support", sub: "Family Counseling", city: "Philadelphia", website_url: "https://www.lutheransettlement.org/", source_name: "Lutheran Settlement House", source_type: "nonprofit_organization", phone: "215-426-8610", address: "1340 Frankford Ave, Philadelphia, PA 19125", zip: "19125", desc: "Lutheran Settlement House — Fishtown neighborhood multi-service center; bilingual domestic-violence counseling and shelter referral, senior center, food pantry, adult education, family case management, immigrant services. Veterans and military families welcome." },
  { section: "PHL", title: "Liberty Resources Inc. — Philadelphia", cat: "disabled-veterans", sub: "Independent Living & Daily Support", city: "Philadelphia", website_url: "https://liberty-resources.org/", source_name: "Liberty Resources Inc.", source_type: "center_for_independent_living", phone: "215-634-2000", address: "112 N 8th St 6th Fl, Philadelphia, PA 19107", zip: "19107", desc: "Liberty Resources — federally-designated Center for Independent Living serving Philadelphia and 4 surrounding counties; disability rights advocacy, peer mentoring, attendant care, accessible housing referral, ADA navigation, transition services. Disabled veterans welcome; coordinates with Phila VAMC and PA OVR." },

  // ======================== PITTSBURGH METRO — 12 ========================
  { section: "PIT", title: "ACTION-Housing Inc. — Pittsburgh", cat: "housing", sub: "Rental Assistance", city: "Pittsburgh", website_url: "https://actionhousing.org/", source_name: "ACTION-Housing Inc.", source_type: "nonprofit_organization", phone: "412-281-2102", address: "611 William Penn Pl Suite 800, Pittsburgh, PA 15219", zip: "15219", desc: "ACTION-Housing — Western PA's leading nonprofit housing developer & service provider; SSVF veteran rapid rehousing & homelessness prevention, supportive housing, weatherization, foreclosure counseling, employment training. SSVF-grantee for 11-county Allegheny region." },
  { section: "PIT", title: "Housing Authority of the City of Pittsburgh (HACP)", cat: "housing", sub: "Rental Assistance", city: "Pittsburgh", website_url: "https://hacp.org/", source_name: "Housing Authority of the City of Pittsburgh", source_type: "public_housing_authority", phone: "412-456-5000", address: "100 Ross St 2nd Fl, Pittsburgh, PA 15219", zip: "15219", desc: "Housing Authority of the City of Pittsburgh — administers public housing, Housing Choice Vouchers (Section 8), and HUD-VASH for Pittsburgh; veteran preference applies. Coordinates with VA Pittsburgh Healthcare System case managers for VASH placement." },
  { section: "PIT", title: "Light of Life Rescue Mission — Pittsburgh", cat: "housing", sub: "Emergency Housing", city: "Pittsburgh", website_url: "https://lightoflife.org/", source_name: "Light of Life Rescue Mission", source_type: "faith_based_nonprofit", phone: "412-258-6100", address: "913 Western Ave, Pittsburgh, PA 15233", zip: "15233", desc: "Light of Life Rescue Mission — Pittsburgh North Side rescue mission; 84-bed emergency men's shelter, women & children's shelter, recovery program, daily meals, case management, workforce training. Veterans welcome; partners with VA Pittsburgh for HUD-VASH referral." },
  { section: "PIT", title: "Salvation Army Western Pennsylvania Division", cat: "financial", sub: "Emergency Financial Assistance", city: "Pittsburgh", website_url: "https://wpa.salvationarmy.org/", source_name: "The Salvation Army Western PA Division", source_type: "faith_based_nonprofit", phone: "412-446-1500", address: "700 N Bell Ave, Carnegie, PA 15106", zip: "15106", desc: "Salvation Army Western PA Division — 27-county service area headquartered Carnegie; emergency financial assistance (rent/utilities/food/clothing), shelters (Harbor Light Center recovery), Pathway of Hope family case management, holiday assistance. Veterans served at all corps community centers." },
  { section: "PIT", title: "Greater Pittsburgh Community Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Pittsburgh", website_url: "https://www.pittsburghfoodbank.org/", source_name: "Greater Pittsburgh Community Food Bank / Feeding America", source_type: "nonprofit_organization", phone: "412-460-3663", address: "1 N Linden St, Duquesne, PA 15110", zip: "15110", desc: "Greater Pittsburgh Community Food Bank — Feeding America affiliate serving 11 SW PA counties; distributes 47+ million meals annually through 1,000+ partner pantries, Mobile Pantry, Veterans In Need program (monthly food box for low-income veterans), SNAP enrollment, weekend food for kids." },
  { section: "PIT", title: "Pittsburgh Regional Transit (PRT) — ACCESS Paratransit", cat: "transportation", sub: "Public Transit Assistance", city: "Pittsburgh", website_url: "https://www.rideprt.org/", source_name: "Pittsburgh Regional Transit", source_type: "regional_transit_authority", phone: "412-562-5353", address: "345 Sixth Ave, Pittsburgh, PA 15222", zip: "15222", desc: "Pittsburgh Regional Transit (PRT, formerly Port Authority) — Allegheny County transit; ACCESS shared-ride paratransit for ADA-eligible riders (door-to-door with priority for medical trips), reduced-fare ConnectCard for seniors 65+/persons with disabilities. Disabled veterans qualify for ACCESS; serves VA Pittsburgh and CBOCs." },
  { section: "PIT", title: "Neighborhood Legal Services (NLS)", cat: "legal", sub: "Legal Aid Services", city: "Pittsburgh", website_url: "https://www.nlsa.us/", source_name: "Neighborhood Legal Services", source_type: "legal_aid_organization", phone: "412-255-6700", address: "928 Penn Ave 2nd Fl, Pittsburgh, PA 15222", zip: "15222", desc: "Neighborhood Legal Services — federally-funded LSC legal aid for SW PA (Allegheny, Beaver, Butler, Lawrence counties); free civil legal help with housing/eviction, public benefits, employment, family law, consumer/debt, VA benefits appeals. Veteran-priority intake." },
  { section: "PIT", title: "Women's Center & Shelter of Greater Pittsburgh", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Pittsburgh", website_url: "https://www.wcspittsburgh.org/", source_name: "Women's Center & Shelter of Greater Pittsburgh", source_type: "nonprofit_organization", phone: "412-687-8005", address: "PO Box 9024, Pittsburgh, PA 15224", zip: "15224", desc: "Women's Center & Shelter of Greater Pittsburgh — 24/7 DV crisis hotline, emergency shelter, transitional housing, legal advocacy, counseling, children's program. Founded 1974, one of the first DV shelters in the U.S. Serves veteran survivors and military spouses; accommodates families." },
  { section: "PIT", title: "Pittsburgh Mercy Behavioral Health", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Pittsburgh", website_url: "https://www.pittsburghmercy.org/", source_name: "Pittsburgh Mercy / Trinity Health", source_type: "nonprofit_healthcare_system", phone: "1-877-637-2924", address: "249 S 9th St, Pittsburgh, PA 15203", zip: "15203", desc: "Pittsburgh Mercy Behavioral Health — Trinity Health/Sisters of Mercy nonprofit; outpatient mental health & substance use disorder treatment, MAT (Suboxone/Vivitrol), Operation Safety Net street medicine for homeless, intensive outpatient (IOP), residential SUD beds at Bethany House. Veterans accepted; coordinates with VA Pittsburgh." },
  { section: "PIT", title: "Family Services of Western Pennsylvania", cat: "family-support", sub: "Family Counseling", city: "Pittsburgh", website_url: "https://www.fswp.org/", source_name: "Family Services of Western Pennsylvania", source_type: "nonprofit_organization", phone: "412-820-2050", address: "6401 Penn Ave 3rd Fl, Pittsburgh, PA 15206", zip: "15206", desc: "Family Services of Western PA — 100+ year nonprofit serving 7 SW PA counties; family counseling, child welfare/foster care, behavioral health, in-home parenting support (Healthy Families), early intervention, senior services. Veteran families welcome." },
  { section: "PIT", title: "Veterans Leadership Program of Western PA (VLP)", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Pittsburgh", website_url: "https://www.veteransleadership.org/", source_name: "Veterans Leadership Program of Western PA", source_type: "veteran_nonprofit", phone: "412-481-8200", address: "2934 Smallman St, Pittsburgh, PA 15201", zip: "15201", desc: "Veterans Leadership Program of Western PA — 40-year veteran nonprofit serving 26 W PA counties; SSVF veteran rapid-rehousing/homelessness-prevention, HVRP employment, financial counseling, transportation aid, ID-recovery, supportive services for very low-income veterans." },
  { section: "PIT", title: "DAV Department of Pennsylvania", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Pittsburgh", website_url: "https://www.davpa.com/", source_name: "Disabled American Veterans Department of Pennsylvania", source_type: "veteran_service_organization", phone: "412-741-3700", address: "1018 Beaver Grade Rd, Moon Township, PA 15108", zip: "15108", desc: "DAV Department of Pennsylvania — chartered VSO with 70+ chapters statewide; National Service Officers (NSOs) accredited to file VA disability/pension/appeals claims (FREE for any veteran), Transportation Network volunteer drivers to VA medical appointments, advocacy. Eligible: any wartime/peacetime veteran with service-connected disability." },

  // ======================== HARRISBURG METRO — 6 ========================
  { section: "HBG", title: "Bethesda Mission — Harrisburg", cat: "housing", sub: "Emergency Housing", city: "Harrisburg", website_url: "https://bethesdamission.org/", source_name: "Bethesda Mission", source_type: "faith_based_nonprofit", phone: "717-257-4442", address: "611 Reily St, Harrisburg, PA 17102", zip: "17102", desc: "Bethesda Mission — Harrisburg's largest rescue mission since 1914; emergency men's shelter (75 beds), women & children's shelter (Bethesda Mission Women's Shelter), recovery program, daily meals, dental/medical clinic, after-school program, community outreach. Veterans accepted; partners with Lebanon VAMC for VASH referral." },
  { section: "HBG", title: "Central Pennsylvania Food Bank — Harrisburg", cat: "food-assistance", sub: "Food Banks", city: "Harrisburg", website_url: "https://www.centralpafoodbank.org/", source_name: "Central Pennsylvania Food Bank / Feeding America", source_type: "nonprofit_organization", phone: "717-564-1700", address: "3908 Corey Rd, Harrisburg, PA 17109", zip: "17109", desc: "Central PA Food Bank — Feeding America affiliate serving 27 counties across central PA; distributes 65+ million pounds annually through 1,200+ partner pantries, Mobile Market, Healthy Pantry Initiative, Veterans In Need monthly food distribution, SNAP enrollment. Co-located warehouse in Williamsport for NE PA reach." },
  { section: "HBG", title: "MidPenn Legal Services — Harrisburg HQ", cat: "legal", sub: "Legal Aid Services", city: "Harrisburg", website_url: "https://www.midpenn.org/", source_name: "MidPenn Legal Services", source_type: "legal_aid_organization", phone: "1-800-326-9177", address: "213 N Front St, Harrisburg, PA 17101", zip: "17101", desc: "MidPenn Legal Services — federally-funded LSC legal aid serving 18 counties in south-central PA (Adams, Cumberland, Dauphin, Franklin, Lancaster, Lebanon, Perry, York + 10 more); free civil legal help with housing, public benefits, family law/PFA, consumer protection, VA benefits appeals. Veteran-priority intake; multilingual." },
  { section: "HBG", title: "YWCA Greater Harrisburg — Domestic Violence Services", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Harrisburg", website_url: "https://www.ywcahbg.org/", source_name: "YWCA Greater Harrisburg", source_type: "nonprofit_organization", phone: "1-800-654-1211", address: "1101 Market St, Harrisburg, PA 17103", zip: "17103", desc: "YWCA Greater Harrisburg — 24/7 DV/sexual-assault hotline, emergency shelter (75 beds, Dauphin County's only DV shelter), transitional housing, legal advocacy, counseling, children's program, residence for women in transition. Serves veteran survivors and military spouses; accommodates families." },
  { section: "HBG", title: "rabbittransit — Harrisburg / Capital Area Transit", cat: "transportation", sub: "Public Transit Assistance", city: "Harrisburg", website_url: "https://www.rabbittransit.org/", source_name: "rabbittransit (York Adams Transportation Authority)", source_type: "regional_transit_authority", phone: "1-800-632-9063", address: "1230 Roosevelt Ave, York, PA 17404", zip: "17404", desc: "rabbittransit — regional transit authority serving 10 south-central PA counties (Adams, Columbia, Cumberland, Dauphin, Franklin, Lancaster, Lebanon, Northumberland, Perry, York); fixed-route, ADA paratransit, Shared Ride for seniors 65+ (PA Lottery-funded), Medical Assistance Transportation (MATP). Disabled veterans qualify for paratransit; serves Lebanon VAMC trips." },
  { section: "HBG", title: "Gaudenzia Inc. — Harrisburg HQ", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Harrisburg", website_url: "https://www.gaudenzia.org/", source_name: "Gaudenzia Inc.", source_type: "nonprofit_healthcare_system", phone: "1-833-976-4357", address: "106 S 4th St, Harrisburg, PA 17101", zip: "17101", desc: "Gaudenzia — one of the largest non-profit SUD providers in the Mid-Atlantic; 45+ programs across PA/MD/DE/DC; detox, residential treatment, MAT (methadone/Suboxone/Vivitrol), outpatient/IOP, recovery houses, prison reentry SUD, women & children's residential. Veterans accepted; coordinates with Lebanon/Wilkes-Barre VAMCs." },

  // ======================== ALLENTOWN / BETHLEHEM METRO — 7 ========================
  { section: "ABE", title: "Second Harvest Food Bank of Lehigh Valley & Northeast PA", cat: "food-assistance", sub: "Food Banks", city: "Allentown", website_url: "https://www.shfblv.org/", source_name: "Second Harvest Food Bank of Lehigh Valley & NE PA / Feeding America", source_type: "nonprofit_organization", phone: "610-434-0875", address: "6969 Silver Crest Rd, Nazareth, PA 18064", zip: "18064", desc: "Second Harvest Food Bank of Lehigh Valley & NE PA — Feeding America affiliate serving 6-county region (Lehigh, Northampton, Carbon, Monroe, Pike, Wayne); 200+ partner agencies, Mobile Pantry, Backpack Buddies for kids, SNAP enrollment, Senior Box. Veteran families served via partner pantries." },
  { section: "ABE", title: "Turning Point of Lehigh Valley", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Allentown", website_url: "https://www.turningpointlv.org/", source_name: "Turning Point of Lehigh Valley", source_type: "nonprofit_organization", phone: "610-437-3369", address: "444 E Susquehanna St, Allentown, PA 18103", zip: "18103", desc: "Turning Point of Lehigh Valley — Lehigh & Northampton counties' designated DV agency; 24-hour hotline (610-437-3369), emergency shelter (45 beds), transitional housing, legal advocacy (PFA filing), counseling, children's program, prevention education. Serves veteran survivors and military spouses." },
  { section: "ABE", title: "North Penn Legal Services — Lehigh Valley", cat: "legal", sub: "Legal Aid Services", city: "Allentown", website_url: "https://www.northpennlegal.org/", source_name: "North Penn Legal Services", source_type: "legal_aid_organization", phone: "1-877-953-4250", address: "65 E Elizabeth Ave Suite 903, Bethlehem, PA 18018", zip: "18018", desc: "North Penn Legal Services — federally-funded LSC legal aid serving 9 counties across NE & central PA (Bradford, Carbon, Lackawanna, Lehigh, Luzerne, Monroe, Northampton, Pike, Susquehanna, Tioga, Wayne, Wyoming); free civil legal help with housing/eviction, public benefits, family law/PFA, consumer, VA benefits appeals. Veteran-priority intake." },
  { section: "ABE", title: "LANTA — Lehigh and Northampton Transportation Authority", cat: "transportation", sub: "Public Transit Assistance", city: "Allentown", website_url: "https://www.lantabus.com/", source_name: "Lehigh and Northampton Transportation Authority", source_type: "regional_transit_authority", phone: "610-776-7433", address: "2nd & Hamilton Sts, Allentown, PA 18101", zip: "18101", desc: "LANTA — regional transit authority for Lehigh & Northampton counties; fixed-route bus, LANTAVan ADA paratransit (door-to-door for ADA-eligible), Shared Ride for seniors 65+ (PA Lottery-funded), Medical Assistance Transportation. Disabled veterans qualify; serves Allentown VA OPC and Wilkes-Barre VAMC trips." },
  { section: "ABE", title: "Treatment Trends Inc. — Allentown", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Allentown", website_url: "https://www.treatmenttrends.org/", source_name: "Treatment Trends Inc.", source_type: "nonprofit_healthcare_system", phone: "610-439-8479", address: "18 S 6th St, Allentown, PA 18101", zip: "18101", desc: "Treatment Trends — 50-year Lehigh Valley SUD nonprofit; outpatient & IOP, MAT (Suboxone/Vivitrol), Halfway House (men's residential), Keenan House (women's residential), Confront youth program, Hispanic-American Organization recovery. Veterans accepted; PA DDAP-licensed." },
  { section: "ABE", title: "Valley Youth House — Lehigh Valley", cat: "family-support", sub: "Youth Programs", city: "Bethlehem", website_url: "https://valleyyouthhouse.org/", source_name: "Valley Youth House", source_type: "nonprofit_organization", phone: "610-691-1200", address: "524 Walnut St, Allentown, PA 18101", zip: "18101", desc: "Valley Youth House — 50-year Lehigh Valley & SE PA youth/family nonprofit; emergency youth shelter, transitional living for older youth (16-24), foster care, supervised independent living, in-home family services, LGBTQ+ youth program. Serves veteran families with at-risk youth." },

  // ======================== SCRANTON / WILKES-BARRE METRO — 6 ========================
  { section: "NEPA", title: "COLTS — County of Lackawanna Transit System", cat: "transportation", sub: "Public Transit Assistance", city: "Scranton", website_url: "https://www.coltsbus.com/", source_name: "County of Lackawanna Transit System", source_type: "regional_transit_authority", phone: "570-346-2061", address: "800 N South Rd, Scranton, PA 18504", zip: "18504", desc: "COLTS — Lackawanna County transit authority; 24 fixed-route bus lines connecting Scranton/Carbondale/Dunmore/Taylor, COLTS PLUS ADA paratransit (door-to-door), Shared Ride for seniors 65+ (PA Lottery), Medical Assistance Transportation. Disabled veterans qualify; serves Scranton Vet Center and Wilkes-Barre VAMC trips." },
  { section: "NEPA", title: "LCTA — Luzerne County Transportation Authority", cat: "transportation", sub: "Public Transit Assistance", city: "Wilkes-Barre", website_url: "https://www.lctabus.com/", source_name: "Luzerne County Transportation Authority", source_type: "regional_transit_authority", phone: "570-288-9356", address: "315 Wilkes-Barre Twp Blvd, Wilkes-Barre Township, PA 18702", zip: "18702", desc: "LCTA — Luzerne County transit authority; fixed-route bus serving Wilkes-Barre/Hazleton/Pittston/Nanticoke, ADA paratransit, Shared Ride for seniors 65+ (PA Lottery-funded), Medical Assistance Transportation (MATP), trips to Wilkes-Barre VAMC. Disabled veterans qualify for paratransit." },
  { section: "NEPA", title: "Weinberg Northeast Regional Food Bank (CEO)", cat: "food-assistance", sub: "Food Banks", city: "Pittston", website_url: "https://ceopeoplehelpingpeople.org/programs/weinberg-northeast-regional-food-bank/", source_name: "Commission on Economic Opportunity (CEO)", source_type: "nonprofit_organization", phone: "570-826-0510", address: "185 Research Dr, Pittston, PA 18640", zip: "18640", desc: "Weinberg Northeast Regional Food Bank — Feeding America affiliate (operated by CEO) serving 5 NEPA counties (Lackawanna, Luzerne, Susquehanna, Wayne, Wyoming); 175+ partner pantries/agencies, Mobile Market, Backpack Program, SNAP enrollment, Senior Food Box. Veteran families served via partner pantries." },
  { section: "NEPA", title: "St. Joseph's Center — Scranton", cat: "family-support", sub: "Family Counseling", city: "Scranton", website_url: "https://www.stjosephscenter.org/", source_name: "St. Joseph's Center", source_type: "faith_based_nonprofit", phone: "570-342-8379", address: "2010 Adams Ave, Scranton, PA 18509", zip: "18509", desc: "St. Joseph's Center — Sisters of IHM Scranton nonprofit; intellectual & developmental disabilities residential & day services, infant care/adoption, mother-infant program (Mary's Maternity), foster care, in-home support. Veteran families with disabled members welcome; PA OVR / Office of Developmental Programs partner." },
  { section: "NEPA", title: "Friends of the Poor — Scranton", cat: "housing", sub: "Emergency Housing", city: "Scranton", website_url: "https://www.friendsofthepoorscranton.org/", source_name: "Friends of the Poor", source_type: "faith_based_nonprofit", phone: "570-348-4429", address: "2210 Rockwell Ave, Scranton, PA 18508", zip: "18508", desc: "Friends of the Poor — 40-year Scranton nonprofit; emergency assistance (rent, utilities, food, clothing, prescriptions), choice food pantry, furniture bank, holiday assistance, summer kids program, low-income elderly support. Veterans accepted; partners with Scranton Vet Center for veteran referrals." },
  { section: "NEPA", title: "Marworth Treatment Center (Geisinger)", cat: "substance-recovery", sub: "Detox Programs", city: "Waverly", website_url: "https://www.marworth.org/", source_name: "Marworth (Geisinger Health System)", source_type: "nonprofit_healthcare_system", phone: "1-800-442-7722", address: "Lily Lake Rd, Waverly, PA 18471", zip: "18471", desc: "Marworth Treatment Center — Geisinger Health System SUD treatment campus near Scranton; medical detox, 28-day residential rehab, professionals' program (physicians/lawyers/pilots), uniformed services program (military/police/fire/EMS) with PTSD-informed care, family program. Veterans served by uniformed-services track; TRICARE accepted." },

  // ======================== ERIE METRO — 5 ========================
  { section: "ERI", title: "Second Harvest Food Bank of Northwest Pennsylvania", cat: "food-assistance", sub: "Food Banks", city: "Erie", website_url: "https://www.nwpafoodbank.org/", source_name: "Second Harvest Food Bank of NW PA / Feeding America", source_type: "nonprofit_organization", phone: "814-459-3663", address: "1507 Grimm Dr, Erie, PA 16501", zip: "16501", desc: "Second Harvest Food Bank of NW PA — Feeding America affiliate serving 11 NW PA counties; 200+ partner agencies, Mobile Food Pantry, Senior Food Box, Backpack Program, SNAP enrollment. Veteran families served via partner pantries; coordinates with Erie VAMC outreach." },
  { section: "ERI", title: "EMTA — Erie Metropolitan Transit Authority (the e)", cat: "transportation", sub: "Public Transit Assistance", city: "Erie", website_url: "https://www.ride-the-e.com/", source_name: "Erie Metropolitan Transit Authority", source_type: "regional_transit_authority", phone: "814-452-3515", address: "127 E 14th St, Erie, PA 16503", zip: "16503", desc: "EMTA (the e) — Erie County transit authority; fixed-route bus, the e Access ADA paratransit (door-to-door), Shared Ride for seniors 65+ (PA Lottery-funded), Medical Assistance Transportation. Disabled veterans qualify; serves Erie VAMC and CBOC trips." },
  { section: "ERI", title: "SafeNet — Erie", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Erie", website_url: "https://www.safeneterie.org/", source_name: "SafeNet (Erie County DV agency)", source_type: "nonprofit_organization", phone: "814-454-8161", address: "1702 French St, Erie, PA 16501", zip: "16501", desc: "SafeNet — Erie County's designated DV agency; 24-hour hotline (814-454-8161), emergency shelter (35 beds), transitional housing, legal advocacy (PFA filing, custody), counseling, children's program, abuse-prevention education. Serves veteran survivors and military spouses." },
  { section: "ERI", title: "Erie City Mission", cat: "housing", sub: "Emergency Housing", city: "Erie", website_url: "https://www.eriecitymission.org/", source_name: "Erie City Mission", source_type: "faith_based_nonprofit", phone: "814-452-4421", address: "1017 French St, Erie, PA 16501", zip: "16501", desc: "Erie City Mission — Erie's largest rescue mission since 1911; emergency men's shelter, daily meals, recovery program, workforce development (Bridges program), thrift store. Veterans accepted; partners with Erie VAMC for VASH referral." },
  { section: "ERI", title: "Family Services of Northwest Pennsylvania", cat: "family-support", sub: "Family Counseling", city: "Erie", website_url: "https://www.fsnwpa.org/", source_name: "Family Services of NW PA", source_type: "nonprofit_organization", phone: "814-866-4500", address: "5100 Peach St, Erie, PA 16509", zip: "16509", desc: "Family Services of NW PA — multi-service nonprofit; outpatient mental health & SUD counseling, MH crisis services, in-home family preservation, foster care, drug & alcohol prevention, parenting education, school-based behavioral health. Veteran families welcome; TRICARE accepted." },

  // ======================== LANCASTER METRO — 3 ========================
  { section: "LNC", title: "Lancaster County Food Hub", cat: "food-assistance", sub: "Food Pantries", city: "Lancaster", website_url: "https://www.lancasterfoodhub.org/", source_name: "Lancaster County Food Hub", source_type: "nonprofit_organization", phone: "717-394-0431", address: "812 N Queen St, Lancaster, PA 17603", zip: "17603", desc: "Lancaster County Food Hub — Lancaster City multi-service nonprofit; choice food pantry serving 4,000+ households monthly, hot meal program (lunch 7 days/week), homeless shelter referral, mailing address for unhoused, ID-recovery, hygiene kits. Veterans accepted; partners with MidPenn for legal aid referral." },
  { section: "LNC", title: "Red Rose Transit Authority (RRTA) — Lancaster", cat: "transportation", sub: "Public Transit Assistance", city: "Lancaster", website_url: "https://www.redrosetransit.com/", source_name: "Red Rose Transit Authority", source_type: "regional_transit_authority", phone: "717-397-4246", address: "45 Erick Rd, Lancaster, PA 17601", zip: "17601", desc: "Red Rose Transit Authority — Lancaster County transit; fixed-route bus across Lancaster City and county, ADA paratransit (Red Rose Access), Shared Ride for seniors 65+ (PA Lottery-funded), Medical Assistance Transportation, trips to Lebanon VAMC. Disabled veterans qualify for paratransit." },
  { section: "LNC", title: "Water Street Mission — Lancaster", cat: "housing", sub: "Emergency Housing", city: "Lancaster", website_url: "https://www.waterstreetmission.org/", source_name: "Water Street Mission", source_type: "faith_based_nonprofit", phone: "717-393-7709", address: "210 S Prince St, Lancaster, PA 17603", zip: "17603", desc: "Water Street Mission — 120-year Lancaster rescue mission; 220-bed emergency shelter for men/women/families, free medical/dental/vision clinic, daily meals, recovery program (Vision of Hope men's residential, Door of Hope women's), workforce training. Veterans accepted; partners with Lebanon VAMC for VASH referral." },

  // ======================== READING METRO — 4 ========================
  { section: "RDG", title: "Helping Harvest Fresh Food Bank — Reading", cat: "food-assistance", sub: "Food Banks", city: "Reading", website_url: "https://helpingharvest.org/", source_name: "Helping Harvest Fresh Food Bank / Feeding America", source_type: "nonprofit_organization", phone: "610-926-5802", address: "117 Morgan Dr, Reading, PA 19608", zip: "19608", desc: "Helping Harvest — Feeding America affiliate serving Berks & Schuylkill counties; 300+ partner agencies, Mobile Pantry, Backpack Program for kids, Senior Food Box, SNAP enrollment, fresh-produce focus. Veteran families served via partner pantries." },
  { section: "RDG", title: "BARTA — Berks Area Regional Transportation Authority", cat: "transportation", sub: "Public Transit Assistance", city: "Reading", website_url: "https://www.bartabus.com/", source_name: "Berks Area Regional Transportation Authority", source_type: "regional_transit_authority", phone: "610-921-0601", address: "1700 N 11th St, Reading, PA 19604", zip: "19604", desc: "BARTA — Berks County transit authority; fixed-route bus across Reading metro and county, BARTA Special Services ADA paratransit (door-to-door), Shared Ride for seniors 65+ (PA Lottery-funded), Medical Assistance Transportation, trips to Lebanon VAMC. Disabled veterans qualify for paratransit." },
  { section: "RDG", title: "Berks Women in Crisis (Safe Berks)", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Reading", website_url: "https://www.berkswomenincrisis.org/", source_name: "Safe Berks (Berks Women in Crisis)", source_type: "nonprofit_organization", phone: "1-844-789-7233", address: "PO Box 14959, Reading, PA 19612", zip: "19612", desc: "Safe Berks (formerly Berks Women in Crisis) — Berks County's designated DV/sexual-assault agency; 24-hour hotline (1-844-789-7233), emergency shelter (50 beds), legal advocacy (PFA filing), counseling, children's program, prevention education. Serves veteran survivors and military spouses; bilingual." },
  { section: "RDG", title: "Hope Rescue Mission — Reading", cat: "housing", sub: "Emergency Housing", city: "Reading", website_url: "https://www.hoperescuemission.com/", source_name: "Hope Rescue Mission", source_type: "faith_based_nonprofit", phone: "610-375-4224", address: "645 N 6th St, Reading, PA 19601", zip: "19601", desc: "Hope Rescue Mission — Reading rescue mission since 1903; 65-bed emergency men's shelter, daily meals, New Life Recovery program (12-month residential), workforce development, transitional housing. Veterans accepted; partners with Lebanon VAMC for VASH referral." },
];

runSeed(ROWS, { state: "PA", commit: COMMIT, scriptName: "seed-pa-p4.ts", urlCheckTimeoutMs: 12000 });
