/**
 * OHIO REBUILD — PHASE 2: HEALTHCARE
 * Florida SOP. VA OPCs/CBOCs, FQHCs, hospitals, CMHCs, MAT/SUD, crisis lines.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== VA OUTPATIENT CLINICS / CBOCs (10) ==============
  { section: "VA", title: "Sandusky VA Community Based Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Sandusky", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/sandusky-va-clinic/", source_name: "VA Northeast Ohio Healthcare System", source_type: "va_facility", phone: "419-625-3001", address: "3416 Columbus Ave Suite F, Sandusky, OH 44870", zip: "44870", desc: "Sandusky VA CBOC — VA Northeast Ohio Healthcare System (VANEOHS) outpatient clinic; primary care, mental health, telehealth specialty consults. Serves Erie/Huron/Sandusky/Ottawa County veterans. Ravenna also accessible." },
  { section: "VA", title: "Ravenna VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Ravenna", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/ravenna-va-clinic/", source_name: "VA Northeast Ohio Healthcare System", source_type: "va_facility", phone: "330-296-3641", address: "6751 N Chestnut St, Ravenna, OH 44266", zip: "44266", desc: "Ravenna VA Outpatient Clinic — VANEOHS clinic for Portage County; primary care, mental health, audiology, lab, telehealth specialty. Serves Portage/Geauga/Trumbull rural veterans referred from Wade Park (Cleveland VAMC)." },
  { section: "VA", title: "New Philadelphia VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "New Philadelphia", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/new-philadelphia-va-clinic/", source_name: "VA Northeast Ohio Healthcare System", source_type: "va_facility", phone: "330-602-5339", address: "1260 Monroe Ave Suite 1A, New Philadelphia, OH 44663", zip: "44663", desc: "New Philadelphia VA OPC — VANEOHS clinic for Tuscarawas County; primary care, mental health, women's health, telehealth specialty. Serves Tuscarawas/Carroll/Harrison rural veterans." },
  { section: "VA", title: "Parma VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Parma", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/parma-va-clinic/", source_name: "VA Northeast Ohio Healthcare System", source_type: "va_facility", phone: "440-845-7700", address: "8787 Brookpark Rd, Parma, OH 44129", zip: "44129", desc: "Parma VA OPC — Cleveland VAMC satellite for SW Cuyahoga County; primary care, mental health, audiology, women's health, telehealth specialty. Serves Parma/Brook Park/Strongsville veterans." },
  { section: "VA", title: "Akron VA Annex (West)", cat: "healthcare", sub: "VA Clinics", city: "Akron", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/akron-va-clinic/", source_name: "VA Northeast Ohio Healthcare System", source_type: "va_facility", phone: "330-344-7888", address: "55 W Waterloo Rd, Akron, OH 44319", zip: "44319", desc: "Akron VA West — Cleveland VAMC OPC for Summit County; primary care, mental health, women's health, telehealth specialty. Serves Akron/Barberton/Cuyahoga Falls/Stow veterans." },
  { section: "VA", title: "East Liverpool VA Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "East Liverpool", website_url: "https://www.va.gov/northeast-ohio-health-care/locations/east-liverpool-va-clinic/", source_name: "VA Northeast Ohio Healthcare System", source_type: "va_facility", phone: "330-386-4623", address: "15655 OH-170, Calcutta, OH 43920", zip: "43920", desc: "East Liverpool VA OPC — VANEOHS clinic for Columbiana County; primary care, mental health, lab, telehealth specialty. Serves Columbiana/Jefferson/Mahoning rural veterans referred from Pittsburgh & Cleveland VAMCs." },
  { section: "VA", title: "Belmont County VA Outpatient Clinic (St. Clairsville)", cat: "healthcare", sub: "VA Clinics", city: "St. Clairsville", website_url: "https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/", source_name: "VA Pittsburgh Healthcare System", source_type: "va_facility", phone: "740-695-9321", address: "67700 Mall Ring Rd Suite 195, St. Clairsville, OH 43950", zip: "43950", desc: "Belmont County VA OPC — VA Pittsburgh Healthcare System satellite for E Ohio Valley; primary care, mental health, telehealth. Serves Belmont/Harrison/Monroe Ohio veterans referred from Pittsburgh." },

  // ============== FQHCs (12) ==============
  { section: "FQHC", title: "Health Source of Ohio", cat: "healthcare", sub: "Primary Care", city: "Loveland", website_url: "https://www.healthsourceofohio.org/", source_name: "Health Source of Ohio", source_type: "fqhc", phone: "513-583-0040", address: "560 Cincinnati Batavia Pike Suite 100, Cincinnati, OH 45244", zip: "45244", desc: "Health Source of Ohio — FQHC network with 14 sites across Clermont, Hamilton, Brown, Adams, Highland, Butler, Warren, Clinton; primary care, dental, behavioral health, OB/GYN, and SUD treatment with sliding-fee scale for veterans." },
  { section: "FQHC", title: "Hopewell Health Centers (Athens)", cat: "healthcare", sub: "Primary Care", city: "Athens", website_url: "https://www.hopewellhealth.org/", source_name: "Hopewell Health Centers", source_type: "fqhc", phone: "740-592-3060", address: "90 Hospital Dr, Athens, OH 45701", zip: "45701", desc: "Hopewell Health Centers — FQHC network with 20+ sites across Appalachian SE Ohio (Athens, Hocking, Meigs, Vinton, Gallia, Jackson, Perry, Morgan, Washington, Pike, Adams); primary care, dental, behavioral health, SUD/MAT, sliding-fee scale; major rural-veteran provider." },
  { section: "FQHC", title: "Mahoning Valley Community Health Centers", cat: "healthcare", sub: "Primary Care", city: "Youngstown", website_url: "https://mvchealth.com/", source_name: "Mahoning Valley Community Health Centers", source_type: "fqhc", phone: "330-781-9085", address: "175 Javit Ct, Austintown, OH 44515", zip: "44515", desc: "Mahoning Valley Community Health Centers — FQHC network in NE Ohio Mahoning Valley; primary care, OB/GYN, dental, behavioral health, vision, pharmacy, sliding-fee scale; partner with Youngstown VA OPC." },
  { section: "FQHC", title: "Health Partners of Western Ohio", cat: "healthcare", sub: "Primary Care", city: "Lima", website_url: "https://hpwohio.org/", source_name: "Health Partners of Western Ohio", source_type: "fqhc", phone: "419-227-2000", address: "1620 Allentown Rd, Lima, OH 45805", zip: "45805", desc: "Health Partners of Western Ohio — FQHC network in W Ohio (Allen, Auglaize, Putnam, Mercer, Van Wert, Hardin); primary care, OB/GYN, dental, behavioral health, vision; sliding-fee scale; partner with Lima VA OPC." },
  { section: "FQHC", title: "PrimaryHealth Solutions (Hamilton)", cat: "healthcare", sub: "Primary Care", city: "Hamilton", website_url: "https://www.primaryhealthsolutions.org/", source_name: "PrimaryHealth Solutions", source_type: "fqhc", phone: "513-454-1111", address: "1011 NW Washington Blvd Suite 200, Hamilton, OH 45013", zip: "45013", desc: "PrimaryHealth Solutions — FQHC in Butler County (Hamilton, Middletown, Oxford, Trenton, Monroe); primary care, dental, behavioral health, OB/GYN, sliding-fee scale; partner with Hamilton VA OPC." },
  { section: "FQHC", title: "Family Practice Center of Wayne County (OneEighty)", cat: "healthcare", sub: "Primary Care", city: "Wooster", website_url: "https://one-eighty.org/", source_name: "OneEighty", source_type: "nonprofit", phone: "330-264-8498", address: "104 Spink St, Wooster, OH 44691", zip: "44691", desc: "OneEighty (Wayne County) — integrated FQHC + behavioral health + DV shelter; primary care, mental health, SUD/MAT, DV/SA shelter (Sojourners), workforce development; serves Wayne/Holmes/Ashland/Medina counties veterans." },

  // ============== HOSPITALS — RURAL & SECONDARY (10) ==============
  { section: "HOSP", title: "Marietta Memorial Hospital", cat: "healthcare", sub: "Specialty Care", city: "Marietta", website_url: "https://www.mhsystem.org/", source_name: "Memorial Health System", source_type: "nonprofit", phone: "740-374-1400", address: "401 Matthew St, Marietta, OH 45750", zip: "45750", desc: "Marietta Memorial Hospital — flagship of Memorial Health System (SE OH/N WV); 199-bed Level III trauma center, cancer, cardiac; partners with Marietta VA OPC and Belmont County VA OPC for veteran specialty care." },
  { section: "HOSP", title: "Wooster Community Hospital", cat: "healthcare", sub: "Specialty Care", city: "Wooster", website_url: "https://www.woosterhospital.org/", source_name: "Wooster Community Hospital", source_type: "public_university", phone: "330-263-8100", address: "1761 Beall Ave, Wooster, OH 44691", zip: "44691", desc: "Wooster Community Hospital — Wayne County 171-bed independent public hospital; emergency, surgery, women's services, behavioral health; serves Wayne/Holmes/Ashland veterans referred from Cleveland VAMC." },
  { section: "HOSP", title: "Holzer Health System", cat: "healthcare", sub: "Specialty Care", city: "Gallipolis", website_url: "https://www.holzer.org/", source_name: "Holzer Health System", source_type: "nonprofit", phone: "740-446-5000", address: "100 Jackson Pike, Gallipolis, OH 45631", zip: "45631", desc: "Holzer Health System — multi-site integrated system in SE OH/W WV (Gallia, Meigs, Athens, Lawrence, Vinton, Jackson); cardiac, cancer, surgery; serves Athens VA OPC referrals for rural Appalachian veterans." },
  { section: "HOSP", title: "Trinity Health System (Steubenville)", cat: "healthcare", sub: "Specialty Care", city: "Steubenville", website_url: "https://www.trinityhealth.com/", source_name: "Trinity Health System Steubenville", source_type: "nonprofit", phone: "740-264-8000", address: "380 Summit Ave, Steubenville, OH 43952", zip: "43952", desc: "Trinity Health System Steubenville — Catholic Trinity Health affiliate in Jefferson County; Trinity Medical Center West (Steubenville), Trinity Medical Center East; serves E Ohio Valley veterans referred from Pittsburgh VAMC." },
  { section: "HOSP", title: "Bluffton Hospital (Mercy Health)", cat: "healthcare", sub: "Specialty Care", city: "Bluffton", website_url: "https://www.mercy.com/locations/hospitals/lima/bluffton-hospital", source_name: "Mercy Health St Rita's", source_type: "nonprofit", phone: "419-358-9010", address: "139 Garau St, Bluffton, OH 45817", zip: "45817", desc: "Bluffton Hospital — Mercy Health critical access hospital in Allen County; Lima area; emergency, swing beds, outpatient surgery; partner with Lima VA OPC." },
  { section: "HOSP", title: "Adena Pike Medical Center (Waverly)", cat: "healthcare", sub: "Specialty Care", city: "Waverly", website_url: "https://www.adena.org/", source_name: "Adena Health", source_type: "nonprofit", phone: "740-947-2186", address: "100 Dawn Ln, Waverly, OH 45690", zip: "45690", desc: "Adena Pike Medical Center — Adena Health critical access hospital in Pike County; emergency, primary care; cross-referral with Chillicothe VAMC for south-central OH veterans." },
  { section: "HOSP", title: "Memorial Hospital of Union County (Marysville)", cat: "healthcare", sub: "Specialty Care", city: "Marysville", website_url: "https://www.memorialohio.com/", source_name: "Memorial Hospital of Union County", source_type: "nonprofit", phone: "937-644-6115", address: "500 London Ave, Marysville, OH 43040", zip: "43040", desc: "Memorial Hospital of Union County — Union County independent community hospital; emergency, surgery, cancer, women's health; partner with Wylie OPC (Columbus VA) for central OH veterans." },
  { section: "HOSP", title: "Knox Community Hospital (Mount Vernon)", cat: "healthcare", sub: "Specialty Care", city: "Mount Vernon", website_url: "https://www.kch.org/", source_name: "Knox Community Hospital", source_type: "nonprofit", phone: "740-393-9000", address: "1330 Coshocton Rd, Mount Vernon, OH 43050", zip: "43050", desc: "Knox Community Hospital — Knox County independent community hospital; emergency, surgery, cancer, behavioral health; partner with Newark VA OPC for central OH veterans." },
  { section: "HOSP", title: "Wayne HealthCare (Greenville)", cat: "healthcare", sub: "Specialty Care", city: "Greenville", website_url: "https://www.waynehealthcare.org/", source_name: "Wayne HealthCare", source_type: "nonprofit", phone: "937-548-1141", address: "835 Sweitzer St, Greenville, OH 45331", zip: "45331", desc: "Wayne HealthCare — Darke County independent hospital; emergency, surgery, cancer, primary care network; serves rural Darke/Mercer/Preble veterans referred from Dayton VAMC." },

  // ============== CMHCs / BEHAVIORAL HEALTH (10) ==============
  { section: "MH", title: "Ohio Mental Health Network — NAMI Ohio Affiliates", cat: "mental-health", sub: "Peer Support Groups", city: "Hilliard", website_url: "https://namiohio.org/", source_name: "NAMI Ohio", source_type: "nonprofit", phone: "800-686-2646", address: "1225 Dublin Rd Suite 125, Columbus, OH 43215", zip: "43215", desc: "NAMI Ohio — 36 county/regional NAMI affiliates statewide; free Family-to-Family, Connection Recovery Support, Veterans Family Support Group, In Our Own Voice presentations, NAMI Helpline (800-686-2646), and statewide advocacy." },
  { section: "MH", title: "Beech Brook (Cleveland)", cat: "mental-health", sub: "Family Support (Mental Health)", city: "Pepper Pike", website_url: "https://www.beechbrook.org/", source_name: "Beech Brook", source_type: "nonprofit", phone: "216-831-2255", address: "3737 Lander Rd, Pepper Pike, OH 44124", zip: "44124", desc: "Beech Brook — Cleveland's largest behavioral health agency for children/families; therapeutic foster care, residential treatment, family preservation, school-based MH, MST; serves veteran-family children with trauma-informed care." },
  { section: "MH", title: "Bellefaire Jewish Children's Bureau (JCB)", cat: "mental-health", sub: "Family Support (Mental Health)", city: "Shaker Heights", website_url: "https://www.bellefairejcb.org/", source_name: "Bellefaire JCB", source_type: "nonprofit", phone: "216-932-2800", address: "22001 Fairmount Blvd, Shaker Heights, OH 44118", zip: "44118", desc: "Bellefaire Jewish Children's Bureau — NE Ohio nonprofit serving children/families of all faiths; residential treatment, autism services, foster care/adoption, intensive home-based MH, school-based services for veteran-family children." },
  { section: "MH", title: "Mental Health & Recovery Board of Ashland County", cat: "mental-health", sub: "Counseling & Therapy", city: "Ashland", website_url: "https://www.ashlandmhrb.org/", source_name: "Ashland MHRB", source_type: "county_agency", phone: "419-281-3139", address: "1605 County Rd 1095, Ashland, OH 44805", zip: "44805", desc: "Mental Health & Recovery Board of Ashland County — county MH/SUD planning board; funds Appleseed CMHC, Catholic Charities, OhioGuidestone; 24/7 crisis line, suicide prevention, veteran outreach for Ashland County." },

  // ============== SUBSTANCE USE / RECOVERY (8) ==============
  { section: "SUD", title: "LCADA Way (Lorain County Alcohol & Drug Addiction Services)", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Lorain", website_url: "https://www.lcada.com/", source_name: "LCADA Way", source_type: "nonprofit", phone: "440-989-4900", address: "2115 W Park Dr, Lorain, OH 44053", zip: "44053", desc: "The LCADA Way — Lorain County's largest SUD provider; outpatient, residential (Men's House, Women's House), MAT (methadone, buprenorphine, Vivitrol), DUI assessments, peer recovery; serves Lorain/Erie/Huron/Medina veterans." },
  { section: "SUD", title: "CommQuest Services (Stark County)", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Canton", website_url: "https://www.commquest.org/", source_name: "CommQuest Services", source_type: "nonprofit", phone: "330-455-0374", address: "1341 Market Ave N, Canton, OH 44714", zip: "44714", desc: "CommQuest Services — Stark/Tuscarawas/Carroll County's largest SUD/MH provider; outpatient, residential (Deliverance House, ORCA House), Withdrawal Management Center, MAT, juvenile diversion; serves NE OH veterans referred from Canton VA OPC." },

  // ============== CRISIS LINES & MOBILE TEAMS (5) ==============
  { section: "CRIS", title: "Cleveland Rape Crisis Center", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Cleveland", website_url: "https://www.clevelandrapecrisis.org/", source_name: "Cleveland Rape Crisis Center", source_type: "nonprofit", phone: "216-619-6192", address: "526 Superior Ave Suite 1400, Cleveland, OH 44114", zip: "44114", desc: "Cleveland Rape Crisis Center — 24/7 hotline, hospital advocacy, individual/group therapy, prevention education, MST advocacy partnership with Cleveland VAMC; serves Cuyahoga/Geauga/Lake/Lorain/Ashtabula sexual-assault survivors." },
  { section: "CRIS", title: "Sexual Assault Response Network of Central Ohio (SARNCO)", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Columbus", website_url: "https://oaesv.org/", source_name: "SARNCO (OAESV)", source_type: "nonprofit", phone: "614-267-7020", address: "4900 Reed Rd Suite 200, Columbus, OH 43220", zip: "43220", desc: "Sexual Assault Response Network of Central Ohio (SARNCO) — 24/7 hotline (614-267-7020), hospital/police accompaniment, advocacy, support groups; serves Franklin/Delaware/Fairfield/Pickaway/Madison/Union; MST partnership with Wylie OPC." },
];

runSeed(ROWS, { state: "OH", commit: COMMIT, scriptName: "seed-oh-rebuild-p2.ts" });
