/**
 * OH Phase 1 fixup — re-queue 19 rows that failed on bad subcategory names.
 * Mapped to actual valid subs from this DB.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  { section: "STATE", title: "Ohio Department of Veterans Services", cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation", city: "Columbus", website_url: "https://dvs.ohio.gov/", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "614-644-0898", address: "77 S High St 7th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Veterans Services (ODVS) — cabinet-level state agency serving Ohio's 800,000+ veterans. Operates the Ohio Veterans Bonus, runs the Ohio Veterans Home in Sandusky and Georgetown, supervises County Veterans Service Commissions in all 88 counties, and coordinates Ohio National Guard Family Programs and statewide veteran outreach." },
  { section: "STATE", title: "Ohio Adjutant General's Department", cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation", city: "Columbus", website_url: "https://ong.ohio.gov/", source_name: "Ohio Adjutant General's Department", source_type: "state_agency", phone: "614-336-7000", address: "2825 W Dublin Granville Rd, Columbus, OH 43235", zip: "43235", desc: "Ohio Adjutant General's Department — state agency commanding the Ohio Army National Guard (16,000+ Soldiers), Ohio Air National Guard (5,000+ Airmen), Ohio Military Reserve, and Ohio Naval Militia. Coordinates state-active-duty deployments, federal Title 10 mobilizations, family support, and the Ohio Hall of Fame for Distinguished Citizen Soldiers." },
  { section: "VA", title: "VA Cleveland Regional Office (VBA)", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Cleveland", website_url: "https://www.benefits.va.gov/cleveland/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "800-827-1000", address: "1240 E 9th St, Cleveland, OH 44199", zip: "44199", desc: "VA Cleveland Regional Office — Veterans Benefits Administration regional office serving all 88 Ohio counties. Processes compensation, pension, education (GI Bill), VA home loans, vocational rehab (VR&E), and survivor (DIC) claims. In-person walk-in service Mon-Fri; partners with all 88 Ohio County Veterans Service Commissions for claim filings." },
  { section: "VA", title: "Chalmers P. Wylie Veterans Outpatient Clinic", cat: "healthcare", sub: "VA Clinics", city: "Columbus", website_url: "https://www.va.gov/central-ohio-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "614-257-5200", address: "420 N James Rd, Columbus, OH 43219", zip: "43219", desc: "Chalmers P. Wylie Veterans Outpatient Clinic — VA Central Ohio Healthcare System anchor serving 50,000+ veterans across 14 counties. Outpatient primary care, mental health, surgery (ambulatory), women's health, and PTSD clinic; 5 community-based outpatient clinics (Marion, Newark, Zanesville, Grove City, Wilmington) report up to Wylie." },
  { section: "VSO", title: "American Legion Department of Ohio", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Columbus", website_url: "https://www.ohiolegion.com/", source_name: "American Legion Department of Ohio", source_type: "nonprofit", phone: "614-362-7478", address: "1100 W Goodale Blvd, Columbus, OH 43212", zip: "43212", desc: "American Legion Department of Ohio — chartered veterans service org with 73,000+ members across 537 posts statewide. Free VA-claim assistance via Department Service Officers co-located at VA Cleveland RO, Cincinnati VAMC, Dayton VAMC, Chillicothe VAMC, and Wylie OPC; American Legion Auxiliary; Sons of the American Legion; Boys State; Oratorical contests." },
  { section: "VSO", title: "VFW Department of Ohio", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Columbus", website_url: "https://www.vfwohio.org/", source_name: "Veterans of Foreign Wars Department of Ohio", source_type: "nonprofit", phone: "614-203-4350", address: "165 N High St Suite 10, Columbus, OH 43215", zip: "43215", desc: "VFW Department of Ohio — chartered veterans service org with 38,000+ members across 400+ posts statewide. Free VA-claim assistance via Department Service Officers co-located at VA Cleveland RO and OH VAMCs; VFW Auxiliary; Voice of Democracy / Patriot's Pen scholarships; Buddy Poppy distributions; State Veterans Service Officer training." },
  { section: "VSO", title: "AMVETS Department of Ohio", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Columbus", website_url: "https://www.amvetsoh.org/", source_name: "AMVETS Department of Ohio", source_type: "nonprofit", phone: "614-431-6990", address: "1395 E Dublin-Granville Rd Suite 218, Columbus, OH 43229", zip: "43229", desc: "AMVETS Department of Ohio — chartered veterans service org with 22,000+ members across 200+ posts statewide. Free VA-claim assistance via Department Service Officers co-located at VA Cleveland RO and OH VAMCs; AMVETS Auxiliary; Sons of AMVETS; Riders; veteran scholarships; National Convention representation." },
  { section: "VSO", title: "Marine Corps League Department of Ohio", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Columbus", website_url: "https://www.deptohiomcl.org/", source_name: "Marine Corps League Department of Ohio", source_type: "nonprofit", phone: "614-538-9988", desc: "Marine Corps League Department of Ohio — chartered veterans service org for Marines and Navy Corpsmen with 60+ Ohio detachments. Detachment-administered emergency-financial-assistance grants; Toys for Tots Ohio coordination; Marine Corps Birthday Ball logistics; National Convention representation; coordinates with VA Cleveland RO for claims filings." },
  { section: "VSO", title: "Vietnam Veterans of America — Ohio State Council", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Columbus", website_url: "https://www.vva.org/state-council/ohio/", source_name: "Vietnam Veterans of America", source_type: "nonprofit", phone: "301-585-4000", desc: "Vietnam Veterans of America Ohio State Council — chartered veterans service org with 30+ Ohio chapters. Chapter-administered emergency-financial-assistance, Agent Orange and toxic-exposure benefits-claims service via VVA-trained Service Officers, and Veterans Initiative for POW/MIA accounting. Coordinates with VA Cleveland Regional Office for claim filings." },
  { section: "VNPO", title: "Ohio Means Veteran Jobs", cat: "employment", sub: "DVOP / Workforce Programs", city: "Columbus", website_url: "https://ohiomeansjobs.ohio.gov/job-seekers/veterans", source_name: "Ohio Department of Job and Family Services", source_type: "state_agency", phone: "888-296-7541", address: "30 E Broad St 32nd Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Means Veteran Jobs — ODJFS-administered statewide veteran employment portal and statewide network of OhioMeansJobs centers in all 88 counties. Veterans receive Priority of Service: dedicated DVOPs/LVERs, JVSG-funded case management, employer matching, on-the-job training reimbursement, and apprenticeship navigation." },
  { section: "STATE", title: "Ohio Department of Job and Family Services (ODJFS)", cat: "employment", sub: "DVOP / Workforce Programs", city: "Columbus", website_url: "https://jfs.ohio.gov/", source_name: "Ohio Department of Job and Family Services", source_type: "state_agency", phone: "614-466-6282", address: "30 E Broad St 32nd Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Job and Family Services — cabinet-level state agency administering Workforce Development (OhioMeansJobs / WIOA), Unemployment Compensation, SNAP / Medicaid / TANF / cash assistance / child support. 88-county network; Veteran Priority of Service mandated at all OhioMeansJobs centers." },
  { section: "STATE", title: "Ohio Department of Mental Health and Addiction Services (OhioMHAS)", cat: "mental-health", sub: "Inpatient / Outpatient Treatment", city: "Columbus", website_url: "https://mha.ohio.gov/", source_name: "Ohio Department of Mental Health and Addiction Services", source_type: "state_agency", phone: "614-466-2596", address: "30 E Broad St 36th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Mental Health and Addiction Services (OhioMHAS) — cabinet-level state agency. Operates 6 state psychiatric hospitals, certifies 600+ community behavioral-health and SUD providers, administers 988 Suicide & Crisis Lifeline statewide, and coordinates the Ohio Veteran Behavioral Health Initiative with all 5 OH VAMCs." },
  { section: "STATE", title: "Ohio Department of Health (ODH)", cat: "healthcare", sub: "Preventive Care & Wellness", city: "Columbus", website_url: "https://odh.ohio.gov/", source_name: "Ohio Department of Health", source_type: "state_agency", phone: "614-466-3543", address: "246 N High St, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Health — cabinet-level state agency. Public health, immunizations, WIC, infant mortality reduction, hospital licensure, vital records (birth/death/marriage), and the Ohio Buckeye Health Plan Medicaid managed-care contract. Partners with VA Ohio facilities for veteran public-health outreach (Vet Center coordination, COVID/flu, suicide prevention)." },
  { section: "STATE", title: "Ohio Housing Finance Agency (OHFA)", cat: "housing", sub: "Home Ownership Programs", city: "Columbus", website_url: "https://ohiohome.org/", source_name: "Ohio Housing Finance Agency", source_type: "state_agency", phone: "888-362-6432", address: "57 E Main St, Columbus, OH 43215", zip: "43215", desc: "Ohio Housing Finance Agency — quasi-governmental state agency. Administers below-market mortgage programs (Ohio Heroes for veterans/active-duty/teachers/first-responders), down-payment assistance grants, Mortgage Tax Credit Certificates, Low-Income Housing Tax Credit allocations, Save the Dream Ohio foreclosure prevention, and the Housing Trust Fund." },
  { section: "NPO", title: "Coalition on Homelessness and Housing in Ohio (COHHIO)", cat: "housing", sub: "Homeless Veteran Services", city: "Columbus", website_url: "https://cohhio.org/", source_name: "Coalition on Homelessness and Housing in Ohio", source_type: "nonprofit", phone: "614-280-1984", address: "175 S 3rd St Suite 580, Columbus, OH 43215", zip: "43215", desc: "Coalition on Homelessness and Housing in Ohio (COHHIO) — statewide nonprofit advocacy and TA org for Ohio's homeless-services and affordable-housing networks. Coordinates the Ohio Balance of State Continuum of Care (BoSCoC) covering 80 of 88 OH counties; provides SSVF/HUD-VASH technical assistance for veteran homeless prevention statewide." },
  { section: "NPO", title: "Ohio Suicide Prevention Foundation", cat: "mental-health", sub: "Crisis & Suicide Prevention", city: "Columbus", website_url: "https://www.ohiospf.org/", source_name: "Ohio Suicide Prevention Foundation", source_type: "nonprofit", phone: "614-429-1528", address: "1900 Polaris Pkwy Suite 450-115, Columbus, OH 43240", zip: "43240", desc: "Ohio Suicide Prevention Foundation — statewide nonprofit coordinating suicide prevention strategy across Ohio. Operates Zero Suicide Ohio, Ohio Veterans Suicide Prevention initiative partnered with VA Ohio facilities and the Veterans Crisis Line, the Ohio Lethal Means Safety project, and survivor support groups via OhioMHAS partnership." },
  { section: "HOT", title: "Ohio 211 — HelpLink", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://211ohio.org/", source_name: "Ohio United Way / Ohio 211", source_type: "nonprofit", phone: "211", desc: "Ohio 211 — statewide free 24/7 information & referral service connecting Ohioans to social services across food, housing, utilities, employment, healthcare, mental health, legal, and veteran-specific programs. Available via dial 211, text 898-211, or 211ohio.org. Coordinated through 23 regional 211 centers covering all 88 OH counties; multilingual." },
  { section: "COM", title: "United Way of Ohio (Ohio United Way)", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://www.ohiounitedway.org/", source_name: "Ohio United Way", source_type: "nonprofit", phone: "614-224-8146", address: "37 W Broad St Suite 1100, Columbus, OH 43215", zip: "43215", desc: "Ohio United Way — statewide association of 47 local United Way organizations across all 88 OH counties. Operates Ohio 211 statewide I&R; coordinates EITC outreach, FAFSA day, summer hunger, and community-impact grant-making; partners with all 5 OH VAMCs and the 88 County Veterans Service Commissions for veteran outreach campaigns." },
  { section: "COM", title: "Goodwill Industries of Ohio", cat: "employment", sub: "DVOP / Workforce Programs", city: "Cleveland", website_url: "https://www.goodwill.org/", source_name: "Goodwill Industries of Ohio", source_type: "nonprofit", phone: "216-431-3300", address: "2295 E 55th St, Cleveland, OH 44103", zip: "44103", desc: "Goodwill Industries — Ohio's 9 regional Goodwill agencies (Akron, Cleveland, Columbus, Cincinnati, Dayton, Lima, Toledo, Youngstown, Mid-Ohio Valley) operate retail, donation centers, workforce-development programs, AbilityOne contracts, and the Operation: GoodJobs veteran employment initiative partnered with VA OH and OhioMeansJobs." },
];

console.log(`[seed-oh-phase1-fixup] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "OH", commit: COMMIT, scriptName: "OH Phase 1 fixup — corrected subs",
  batchTag: "oh-phase1-fixup", allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: { STATE: "State Agencies", VA: "VA Anchors", VSO: "Chartered VSOs", VNPO: "Veteran Nonprofits", NPO: "Statewide Nonprofits", HOT: "Hotlines", COM: "Community Anchors" },
}).catch((e) => { console.error(e); process.exit(1); });
