/**
 * OHIO — PHASE 5: SATURATION LIFT (Crisis / Substance / End-of-life / MH / Transportation)
 * Per locked national 6-phase SOP. Target lifting weak cats toward 30+ floor.
 *   - Crisis-help (+15): mobile crisis, DV shelters, suicide prev
 *   - Substance-recovery (+15): AA/NA OH, OH certified SUD providers, recovery housing
 *   - End-of-life (+15): hospice & palliative care branches
 *   - Mental-health (+10): community MH centers across regions
 *   - Transportation (+15): ODOT mobility, vet transport, regional transit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ==============================================================
  // A. CRISIS-HELP (15)
  // ==============================================================
  { section: "CRISIS", title: "Mental Health Services for Homeless Persons (PsychBC) Cincinnati Crisis", cat: "crisis-help", sub: "Suicide Prevention", city: "Cincinnati", website_url: "https://www.talberthouse.org/", source_name: "Mental Health Access Point - Talbert House", source_type: "nonprofit", phone: "513-558-8888", address: "260 Stetson St, Cincinnati, OH 45219", zip: "45219", desc: "Mental Health Access Point (MHAP) — Hamilton County 24/7 crisis hotline operated by University of Cincinnati Department of Psychiatry; psychiatric assessment, mobile crisis team, walk-in services, and warm handoffs to Cincinnati VAMC for veterans in crisis." },
  { section: "CRISIS", title: "Coleman Crisis Services — Stark/Mahoning/Trumbull/Portage", cat: "crisis-help", sub: "Suicide Prevention", city: "Canton", website_url: "https://www.colemanservices.org/", source_name: "Coleman Health Services", source_type: "nonprofit", phone: "330-452-6000", address: "400 N Tuscarawas Ave NW, Canton, OH 44708", zip: "44708", desc: "Coleman Crisis Services — operates 24/7 crisis hotlines and mobile crisis teams in Stark, Mahoning, Trumbull, Portage, and 6 other Ohio counties under contract with county MHRS boards. Psychiatric assessment, suicide-prevention follow-up, and warm handoffs to Canton VA OPC, Cleveland VAMC, Youngstown OPC." },
  { section: "CRISIS", title: "CHOICES (Lutheran Social Services) — Franklin County DV Shelter", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Columbus", website_url: "https://www.lssnetworkofhope.org/choices/", source_name: "Lutheran Social Services of Central Ohio", source_type: "nonprofit", phone: "614-224-4663", address: "PO Box 06157, Columbus, OH 43206", zip: "43206", desc: "CHOICES (Lutheran Social Services of Central Ohio) — Franklin County's only domestic-violence emergency shelter (60 beds); 24/7 DV crisis hotline (614-224-HOME), civil protection-order advocacy, and counseling for survivors including military families." },
  { section: "CRISIS", title: "YWCA Greater Cincinnati — Domestic Violence Services", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Cincinnati", website_url: "https://www.ywcacincinnati.org/", source_name: "YWCA Greater Cincinnati", source_type: "nonprofit", phone: "513-872-9259", address: "898 Walnut St, Cincinnati, OH 45202", zip: "45202", desc: "YWCA Greater Cincinnati — operates the only DV emergency shelter in Hamilton County (40 beds), the regional 24/7 DV hotline (513-872-9259), AMEND violence-intervention program, and Project Lift mobile DV response with Cincinnati Police." },
  { section: "CRISIS", title: "Family Violence Project (Toledo)", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Toledo", website_url: "https://www.bethanyhousetoledo.org/", source_name: "Bethany House", source_type: "nonprofit", phone: "419-241-7386", address: "PO Box 4174, Toledo, OH 43609", zip: "43609", desc: "Bethany House — Toledo-area domestic-violence emergency shelter; 24/7 DV crisis hotline, civil protection-order advocacy, transitional housing for survivors and children, and counseling. Serves Lucas County including women veterans." },
  { section: "CRISIS", title: "Battered Women's Shelter & Rape Crisis Center of Summit County", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Akron", website_url: "https://hopeandhealingresources.org/", source_name: "Hope & Healing Survivor Resource Center", source_type: "nonprofit", phone: "330-374-1111", address: "759 W Market St, Akron, OH 44303", zip: "44303", desc: "Hope & Healing Survivor Resource Center — Summit County DV emergency shelter, 24/7 DV/SA hotline (330-374-1111), Rape Crisis Center, civil protection-order advocacy, and the Summit County Sexual Assault Response Team (SART) coordination." },
  { section: "CRISIS", title: "Buckeye Region Anti-Violence Organization (BRAVO) — LGBTQ+ Crisis", cat: "crisis-help", sub: "Suicide Prevention", city: "Columbus", website_url: "https://www.bravo-ohio.org/", source_name: "Buckeye Region Anti-Violence Organization", source_type: "nonprofit", phone: "866-862-7286", address: "PO Box 82068, Columbus, OH 43202", zip: "43202", desc: "Buckeye Region Anti-Violence Organization (BRAVO) — Ohio's LGBTQ+-focused anti-violence and crisis-support nonprofit; 24/7 statewide LGBTQ+ DV/SA/hate-crime hotline, advocacy, court accompaniment, and survivor support groups for LGBTQ+ Ohioans including LGBTQ+ veterans." },
  { section: "CRISIS", title: "Crisis Text Line — Ohio (Text 4HOPE / 741741)", cat: "crisis-help", sub: "Suicide Prevention", city: "Columbus", website_url: "https://www.crisistextline.org/", source_name: "Crisis Text Line", source_type: "nonprofit", phone: "741741", address: "Statewide Ohio service via SMS", zip: "43215", desc: "Crisis Text Line — free 24/7 text-based crisis counseling for Ohioans in any emotional crisis. Text 4HOPE to 741741 (Ohio shortcode); volunteer crisis counselors trained in suicide prevention, anxiety, depression, abuse, and grief; bilingual (English/Spanish). Veterans can also text 838255 for the Veterans Crisis Line." },

  // ==============================================================
  // B. SUBSTANCE-RECOVERY (15)
  // ==============================================================
  { section: "SUD", title: "Cleveland Area Intergroup of Alcoholics Anonymous", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Cleveland", website_url: "https://www.aacle.org/", source_name: "Cleveland Area Intergroup AA", source_type: "nonprofit", phone: "216-241-7387", address: "1374 W 9th St Suite 510, Cleveland, OH 44113", zip: "44113", desc: "Cleveland Area Intergroup of Alcoholics Anonymous — central service office for AA in NE Ohio; 24-hour answering service, meeting directory for 700+ weekly AA meetings across Cuyahoga and surrounding counties, literature distribution, public information." },
  { section: "SUD", title: "Central Ohio Group Services AA (Columbus)", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Columbus", website_url: "https://www.aacentralohio.org/", source_name: "Central Ohio Group Services AA", source_type: "nonprofit", phone: "614-253-8501", address: "1561 W 5th Ave, Columbus, OH 43212", zip: "43212", desc: "Central Ohio Group Services AA — central service office for AA in Franklin and surrounding counties; 24-hour answering service, meeting directory for 800+ weekly AA meetings, literature distribution, and public-information speakers including veteran-focused open meetings." },
  { section: "SUD", title: "Cincinnati Area Intergroup AA", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Cincinnati", website_url: "https://www.aacincinnati.org/", source_name: "Cincinnati Area Intergroup AA", source_type: "nonprofit", phone: "513-351-0422", address: "411 Oak St, Cincinnati, OH 45219", zip: "45219", desc: "Cincinnati Area Intergroup of Alcoholics Anonymous — central service office for AA in SW Ohio and Northern KY; 24-hour answering service, meeting directory for 600+ weekly AA meetings, literature distribution, public-information presentations." },
  { section: "SUD", title: "Dayton Area Intergroup of AA", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Dayton", website_url: "https://aadayton.org/", source_name: "Dayton Area Intergroup AA", source_type: "nonprofit", phone: "937-222-2211", address: "120 W 2nd St Suite 502, Dayton, OH 45402", zip: "45402", desc: "Dayton Area Intergroup of Alcoholics Anonymous — central service office for AA in Montgomery, Greene, Preble, Miami, and Darke counties; 24-hour answering service, meeting directory for 400+ weekly AA meetings, literature, and public-information speakers." },
  { section: "SUD", title: "NA Ohio Region (Region of Narcotics Anonymous)", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Columbus", website_url: "https://www.naohio.org/", source_name: "Narcotics Anonymous Ohio Region", source_type: "nonprofit", phone: "614-252-1700", address: "Statewide Ohio - 25 NA Areas", zip: "43215", desc: "Narcotics Anonymous Ohio Region — 25 NA Areas across Ohio with 1,500+ weekly meetings; statewide helpline directory, literature distribution, hospitals & institutions outreach to OH prisons and treatment centers, and the OH Regional Convention." },
  { section: "SUD", title: "BrightView Health (Statewide Ohio MAT Network)", cat: "substance-recovery", sub: "Medication Assisted Treatment", city: "Cincinnati", website_url: "https://www.brightviewhealth.com/", source_name: "BrightView Health", source_type: "for_profit", phone: "888-501-9865", address: "Statewide Ohio - 30+ centers", zip: "45202", desc: "BrightView Health — Ohio's largest outpatient SUD treatment network with 30+ centers across Cincinnati, Columbus, Dayton, Cleveland, Akron, Toledo, and beyond; SAMHSA-certified MAT (buprenorphine, naltrexone), individual & group therapy, peer recovery support, telehealth, and TRICARE/VA Community Care provider." },
  { section: "SUD", title: "Ohio Recovery Housing (Statewide)", cat: "substance-recovery", sub: "Recovery Support Services", city: "Columbus", website_url: "https://www.ohiorecoveryhousing.org/", source_name: "Ohio Recovery Housing", source_type: "nonprofit", phone: "614-453-5133", address: "359 E Livingston Ave, Columbus, OH 43215", zip: "43215", desc: "Ohio Recovery Housing — Ohio's NARR-affiliated state-recovery-residence-administering organization; certifies 600+ recovery houses statewide, maintains a public locator searchable by county and population (men/women/family/LGBTQ+/veteran-friendly), training, and quality standards." },
  { section: "SUD", title: "Oxford House Inc — Ohio Chapter", cat: "substance-recovery", sub: "Recovery Support Services", city: "Columbus", website_url: "https://www.oxfordhouse.org/", source_name: "Oxford House Inc", source_type: "nonprofit", phone: "800-689-6411", address: "Statewide Ohio - 100+ houses", zip: "43215", desc: "Oxford House Inc — Ohio Chapter — democratically-self-run, drug-free recovery housing; 100+ Oxford Houses across OH including dedicated veteran houses in Columbus, Cleveland, Cincinnati, Dayton, and Toledo. No time limit on residency; peer-supported." },
  { section: "SUD", title: "Stella Maris (Cleveland)", cat: "substance-recovery", sub: "Detox Programs", city: "Cleveland", website_url: "https://www.stellamariscleveland.com/", source_name: "Stella Maris", source_type: "nonprofit", phone: "216-781-0550", address: "1320 Washington Ave, Cleveland, OH 44113", zip: "44113", desc: "Stella Maris — Cleveland-area SUD treatment provider; ASAM Level 3.5 residential treatment, ASAM Level 3.7 medically-monitored detox, ASAM Level 1 outpatient, and IOP. OhioMHAS-certified, accepts Medicaid, Medicare, TRICARE, and Cleveland VAMC Community Care referrals." },
  { section: "SUD", title: "Glenbeigh (Rock Creek/Rock Creek - Largest OH Inpatient)", cat: "substance-recovery", sub: "Detox Programs", city: "Rock Creek", website_url: "https://www.glenbeigh.com/", source_name: "Glenbeigh Hospital", source_type: "nonprofit", phone: "800-234-1001", address: "PO Box 298, Rock Creek, OH 44084", zip: "44084", desc: "Glenbeigh — JCAHO-accredited 100-bed inpatient SUD hospital in Ashtabula County; medical detox, ASAM Level 3.5 residential treatment, family programs, and an active veterans track in partnership with Cleveland VAMC SUD program. Free 24/7 admissions hotline." },
  { section: "SUD", title: "The Recovery Village Columbus (Drug & Alcohol Rehab)", cat: "substance-recovery", sub: "Detox Programs", city: "Groveport", website_url: "https://www.columbusrecoverycenter.com/", source_name: "The Recovery Village Columbus", source_type: "for_profit", phone: "614-368-9622", address: "3964 Hamilton Square Blvd, Groveport, OH 43125", zip: "43125", desc: "The Recovery Village Columbus — JCAHO-accredited inpatient SUD facility in Groveport; medical detox, ASAM Level 3.5 residential, PHP, IOP, dual-diagnosis programming, and TRICARE/VA Community Care provider. 24/7 admissions hotline." },
  { section: "SUD", title: "SMART Recovery — Ohio (Self-Management & Recovery Training)", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Mentor", website_url: "https://www.smartrecovery.org/", source_name: "SMART Recovery", source_type: "nonprofit", phone: "440-951-5357", address: "7304 Mentor Ave Suite F, Mentor, OH 44060", zip: "44060", desc: "SMART Recovery — international 4-Point Program peer-support recovery program headquartered in Mentor, OH. 100+ weekly meetings across Ohio (in-person and online); evidence-based CBT/REBT/motivational tools as alternative to 12-step. Veteran-friendly meetings and Family & Friends program." },
  { section: "SUD", title: "Recovery Resources (Cleveland)", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Cleveland", website_url: "https://www.recres.org/", source_name: "Recovery Resources", source_type: "nonprofit", phone: "216-431-4131", address: "3950 Chester Ave, Cleveland, OH 44114", zip: "44114", desc: "Recovery Resources — Cuyahoga County's oldest community SUD provider (founded 1956); ASAM Level 1 outpatient, IOP, MAT, prevention services for youth, employment-readiness, and the SAMHSA-funded Veterans-Specific Outpatient Treatment program with Cleveland VAMC referrals." },

  // ==============================================================
  // C. END-OF-LIFE (15)
  // ==============================================================
  { section: "EOL", title: "Hospice of the Western Reserve (Cleveland)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Cleveland", website_url: "https://www.hospicewr.org/", source_name: "Hospice of the Western Reserve", source_type: "nonprofit", phone: "216-383-2222", address: "17876 St Clair Ave, Cleveland, OH 44110", zip: "44110", desc: "Hospice of the Western Reserve — NE Ohio's largest hospice provider; serves 1,500+ patients daily across Cuyahoga, Lake, Geauga, Ashtabula, Lorain, Medina, Summit, Portage, and Stark counties. Operates David Simpson Hospice House (in-patient), We Honor Veterans Level 5 partner, and Camp Bo Children's Bereavement." },
  { section: "EOL", title: "OhioHealth Hospice (Columbus)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Columbus", website_url: "https://www.ohiohealth.com/services/hospice/", source_name: "OhioHealth", source_type: "hospital_system", phone: "614-533-6299", address: "800 McConnell Dr, Columbus, OH 43214", zip: "43214", desc: "OhioHealth Hospice — Central Ohio's largest hospice; serves 1,000+ patients daily across 47 OH counties. Operates Kobacker House inpatient hospice in Columbus (Marion, Mansfield, Lima, Athens, Pickerington locations). We Honor Veterans Level 4 partner with Wylie VA OPC coordination." },
  { section: "EOL", title: "Hospice of Cincinnati", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Cincinnati", website_url: "https://www.hospiceofcincinnati.org/", source_name: "Hospice of Cincinnati", source_type: "nonprofit", phone: "513-891-7700", address: "4310 Cooper Rd, Cincinnati, OH 45242", zip: "45242", desc: "Hospice of Cincinnati — TriHealth-affiliated hospice serving Hamilton, Butler, Clermont, Warren, and Brown counties; operates 4 inpatient hospice care centers (Blue Ash, Anderson, Hamilton, Western Hills). We Honor Veterans Level 5 partner; Cincinnati VAMC palliative-care liaison." },
  { section: "EOL", title: "Hospice of Dayton (Ohio's Hospice)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Dayton", website_url: "https://www.ohioshospice.org/", source_name: "Ohio's Hospice Inc", source_type: "nonprofit", phone: "937-256-4490", address: "324 Wilmington Ave, Dayton, OH 45420", zip: "45420", desc: "Ohio's Hospice Inc (Hospice of Dayton + 9 affiliates) — serves Montgomery, Greene, Preble, Miami, Darke, Champaign, Logan, Shelby, Mercer, Auglaize, Van Wert, Putnam, Allen, Hardin, Hancock, Madison, Clark, Pickaway, and Fayette counties. Operates Hospice House Dayton (inpatient). We Honor Veterans Level 4 partner." },
  { section: "EOL", title: "Hospice of the Valley (Youngstown)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Youngstown", website_url: "https://www.hospiceofthevalley.com/", source_name: "Hospice of the Valley", source_type: "nonprofit", phone: "330-788-1992", address: "5190 Market St, Youngstown, OH 44512", zip: "44512", desc: "Hospice of the Valley — Mahoning Valley regional hospice serving Mahoning, Trumbull, Columbiana, Stark, Portage counties (OH) and Mercer, Lawrence (PA). Operates Hospice House Poland inpatient unit. We Honor Veterans Level 4 partner with Youngstown VA OPC coordination." },
  { section: "EOL", title: "Hospice of Northwest Ohio (Toledo)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Toledo", website_url: "https://www.hospicenwo.org/", source_name: "Hospice of Northwest Ohio", source_type: "nonprofit", phone: "419-661-4001", address: "30000 E River Rd, Perrysburg, OH 43551", zip: "43551", desc: "Hospice of Northwest Ohio — NW Ohio regional hospice serving Lucas, Wood, Ottawa, Sandusky, Fulton, Henry, Defiance, Williams, Paulding counties; operates 2 inpatient Hospice Centers (Perrysburg and Toledo South). We Honor Veterans Level 5 partner with Toledo CBOC coordination." },
  { section: "EOL", title: "VITAS Healthcare — Cincinnati & Cleveland", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Cincinnati", website_url: "https://www.vitas.com/", source_name: "VITAS Healthcare", source_type: "for_profit", phone: "800-723-3233", address: "11500 Northlake Dr Suite 400, Cincinnati, OH 45249", zip: "45249", desc: "VITAS Healthcare — nation's largest hospice provider with Ohio offices in Cincinnati and Cleveland; serves Hamilton, Butler, Clermont, Warren, Cuyahoga, Lake, Lorain, Medina, Summit counties. We Honor Veterans Level 5 partner; Veterans of Honor program." },
  { section: "EOL", title: "Compassus Hospice — Ohio Locations", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Columbus", website_url: "https://www.compassus.com/", source_name: "Compassus", source_type: "for_profit", phone: "614-486-6700", address: "Ohio locations: Columbus, Cincinnati, Cleveland, Dayton, Toledo, Akron, Mansfield, Marietta", zip: "43215", desc: "Compassus — national hospice and palliative-care provider with 8 Ohio offices serving 30+ counties; routine home care, continuous home care, general inpatient, respite care, and We Honor Veterans Level 4 partner with VAMC referrals statewide." },
  { section: "EOL", title: "Amedisys Hospice — Ohio Locations", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Cincinnati", website_url: "https://www.amedisys.com/", source_name: "Amedisys", source_type: "for_profit", phone: "888-553-9559", address: "Ohio locations: Cincinnati, Columbus, Dayton, Cleveland, Toledo, Akron", zip: "45242", desc: "Amedisys Hospice — national home-health and hospice provider with 6 Ohio hospice offices; routine home care, continuous home care, general inpatient (via partnership), respite care. We Honor Veterans Level 4 partner; Honoring Choices Veterans tribute program." },
  { section: "EOL", title: "Crossroads Hospice & Palliative Care (Cleveland & Cincinnati)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Garfield Heights", website_url: "https://www.crossroadshospice.com/", source_name: "Crossroads Hospice & Palliative Care", source_type: "for_profit", phone: "216-654-1800", address: "5300 Transportation Blvd Suite 1, Garfield Heights, OH 44125", zip: "44125", desc: "Crossroads Hospice & Palliative Care — Cleveland and Cincinnati offices serving Cuyahoga, Geauga, Lake, Lorain, Medina, Summit, Hamilton, Butler, Clermont, Warren counties. Signature Programs include Gift of a Day, Watch Program, and Veterans Recognition for terminally-ill veterans." },
  { section: "EOL", title: "Hospice & Palliative Care of Greater Wayne County (Wooster)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Wooster", website_url: "https://www.lifecarehospice.com/", source_name: "LifeCare Hospice", source_type: "nonprofit", phone: "330-264-4899", address: "1900 Akron Rd, Wooster, OH 44691", zip: "44691", desc: "LifeCare Hospice — Wayne County community hospice serving Wayne, Holmes, Ashland, Medina, Stark, Tuscarawas, Coshocton, and Carroll counties. We Honor Veterans Level 4 partner; Pet Peace of Mind animal-companion program for hospice patients." },
  { section: "EOL", title: "Hospice of Central Ohio (Newark)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Newark", website_url: "https://www.hospiceofcentralohio.org/", source_name: "Hospice of Central Ohio", source_type: "nonprofit", phone: "740-788-1400", address: "2269 Cherry Valley Rd SE, Newark, OH 43055", zip: "43055", desc: "Hospice of Central Ohio — Licking County community hospice serving Licking, Coshocton, Fairfield, Knox, Muskingum, and Perry counties. Operates Hospice of Central Ohio Inpatient Care Center in Newark (12 beds). We Honor Veterans Level 4 partner." },
  { section: "EOL", title: "Stein Hospice (Sandusky)", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Sandusky", website_url: "https://www.steinhospice.org/", source_name: "Stein Hospice", source_type: "nonprofit", phone: "419-625-5269", address: "1200 Sycamore Line, Sandusky, OH 44870", zip: "44870", desc: "Stein Hospice — Erie County community hospice serving Erie, Huron, Sandusky, Ottawa, Lorain, Crawford, and Seneca counties. We Honor Veterans Level 5 partner with Sandusky VA OPC coordination; pediatric hospice program; bereavement camps." },

  // ==============================================================
  // D. MENTAL-HEALTH (10) — Community MH centers across regions
  // ==============================================================
  { section: "MH", title: "Centerstone of Ohio (Statewide CMHC)", cat: "mental-health", sub: "Counseling & Therapy", city: "Columbus", website_url: "https://centerstone.org/", source_name: "Centerstone", source_type: "nonprofit", phone: "888-291-4357", address: "Ohio locations: Marion, Elyria, Mansfield, Bryan, Defiance, Napoleon, Wauseon", zip: "43302", desc: "Centerstone of Ohio — multi-state CMHC with 7+ Ohio locations serving Marion, Elyria, Mansfield, Bryan, Defiance, Napoleon, Wauseon. Outpatient mental health and SUD treatment, MAT, school-based services, and the Centerstone Military Services program for veterans and military families." },
  { section: "MH", title: "OhioGuidestone (Statewide CMHC)", cat: "mental-health", sub: "Counseling & Therapy", city: "Berea", website_url: "https://www.ohioguidestone.org/", source_name: "OhioGuidestone", source_type: "nonprofit", phone: "440-260-8300", address: "202 E Bagley Rd, Berea, OH 44017", zip: "44017", desc: "OhioGuidestone — Ohio's largest community-based behavioral-healthcare nonprofit; serves 30,000+ across 30+ counties through 50+ offices. Outpatient counseling, school-based mental health, SUD treatment, residential youth treatment, foster care, and family-centered care for veteran families." },
  { section: "MH", title: "Talbert House (Cincinnati Multi-Service)", cat: "mental-health", sub: "Counseling & Therapy", city: "Cincinnati", website_url: "https://www.talberthouse.org/", source_name: "Talbert House", source_type: "nonprofit", phone: "513-751-7747", address: "2600 Victory Pkwy, Cincinnati, OH 45206", zip: "45206", desc: "Talbert House — Greater Cincinnati's largest multi-service nonprofit (founded 1965); CMHC outpatient counseling, SUD treatment, recovery housing, child & family services, court-mandated/reentry services, and the Talbert House Veterans Project with Cincinnati VAMC and Fort Thomas OPC." },
  { section: "MH", title: "Crossroads Health (Lake County CMHC)", cat: "mental-health", sub: "Counseling & Therapy", city: "Mentor", website_url: "https://crossroadshealth.org/", source_name: "Crossroads Health", source_type: "nonprofit", phone: "440-255-1700", address: "8445 Munson Rd, Mentor, OH 44060", zip: "44060", desc: "Crossroads Health — Lake County's largest CMHC; outpatient mental health and SUD treatment, MAT (buprenorphine, naltrexone), 24/7 mobile crisis, school-based services, and the Lake County Veterans Treatment Court mental health partner." },
  { section: "MH", title: "Mental Health America of Northern Kentucky & SW Ohio", cat: "mental-health", sub: "Counseling & Therapy", city: "Cincinnati", website_url: "https://www.mhankyswoh.org/", source_name: "Mental Health America of NKY & SW Ohio", source_type: "nonprofit", phone: "513-721-2910", address: "2400 Reading Rd, Cincinnati, OH 45202", zip: "45202", desc: "Mental Health America of Northern Kentucky & Southwest Ohio — affiliate of MHA National; mental-health screening, advocacy, education, peer-support warmline, suicide-prevention training, and the Veterans Mental Health Initiative for Cincinnati-area veterans." },
  { section: "MH", title: "Coleman Health Services (Multi-County CMHC)", cat: "mental-health", sub: "Counseling & Therapy", city: "Kent", website_url: "https://www.colemanservices.org/", source_name: "Coleman Health Services", source_type: "nonprofit", phone: "330-296-3555", address: "5982 Rhodes Rd, Kent, OH 44240", zip: "44240", desc: "Coleman Health Services — multi-county CMHC serving Stark, Mahoning, Trumbull, Portage, Tuscarawas, Belmont, Carroll, Harrison, Jefferson, Columbiana counties; outpatient MH, SUD treatment, MAT, residential, 24/7 crisis services, and the Coleman Veterans Services with multi-VAMC partnerships." },
  { section: "MH", title: "Compass Family & Community Services (Mahoning Valley)", cat: "mental-health", sub: "Counseling & Therapy", city: "Youngstown", website_url: "https://compassfamily.org/", source_name: "Compass Family & Community Services", source_type: "nonprofit", phone: "330-783-2273", address: "535 Marmion Ave, Youngstown, OH 44502", zip: "44502", desc: "Compass Family & Community Services — Mahoning Valley CMHC; outpatient MH counseling, child & family therapy, SUD treatment, foster care & adoption services, domestic-violence shelter (Sojourner House), and the Veterans Behavioral Health program." },
  { section: "MH", title: "TCN Behavioral Health Services (Greene County)", cat: "mental-health", sub: "Counseling & Therapy", city: "Xenia", website_url: "https://www.tcn.org/", source_name: "TCN Behavioral Health Services", source_type: "nonprofit", phone: "937-376-8700", address: "452 W Market St, Xenia, OH 45385", zip: "45385", desc: "TCN Behavioral Health Services — Greene County's primary CMHC; outpatient MH and SUD treatment, MAT, 24/7 crisis services (Crisis Care Stabilization Center), school-based MH, and the Veterans Specialty Court mental-health partner with Wright-Patterson AFB and Dayton VAMC coordination." },
  { section: "MH", title: "Zepf Center (Lucas County)", cat: "mental-health", sub: "Counseling & Therapy", city: "Toledo", website_url: "https://www.zepfcenter.org/", source_name: "Zepf Center", source_type: "nonprofit", phone: "419-841-7701", address: "6605 W Central Ave, Toledo, OH 43617", zip: "43617", desc: "Zepf Center — Lucas County's primary CMHC for adults with severe mental illness; outpatient MH counseling, SUD treatment, MAT, supportive housing, vocational rehabilitation, and the Veterans Drop-In Center coordinated with Toledo CBOC." },

  // ==============================================================
  // E. TRANSPORTATION (15)
  // ==============================================================
  { section: "TRANS", title: "Louis Stokes Cleveland VAMC — DAV Volunteer Driver Program", cat: "transportation", sub: "Veteran Transportation Programs", city: "Cleveland", website_url: "https://www.va.gov/northeast-ohio-health-care/", source_name: "DAV / Cleveland VAMC", source_type: "va_facility", phone: "216-791-3800", address: "10701 East Blvd, Cleveland, OH 44106", zip: "44106", desc: "DAV Transportation Network — Cleveland VAMC volunteer driver program; free transportation for veterans to and from VA appointments at Louis Stokes Cleveland VAMC and 13 NE-OH CBOCs. DAV-purchased vans, volunteer drivers coordinated by VA Voluntary Services." },
  { section: "TRANS", title: "Chalmers P. Wylie OPC — DAV Volunteer Driver Program (Columbus)", cat: "transportation", sub: "Veteran Transportation Programs", city: "Columbus", website_url: "https://www.va.gov/central-ohio-health-care/", source_name: "DAV / Wylie VA OPC", source_type: "va_facility", phone: "614-257-5500", address: "420 N James Rd, Columbus, OH 43219", zip: "43219", desc: "DAV Transportation Network — Wylie VA OPC volunteer driver program; free transportation for veterans to and from Chalmers P. Wylie OPC, Chillicothe VAMC, and Columbus-area CBOCs. DAV-purchased vans, volunteer drivers coordinated by VA Voluntary Services." },
  { section: "TRANS", title: "Cincinnati VAMC — DAV Volunteer Driver Program", cat: "transportation", sub: "Veteran Transportation Programs", city: "Cincinnati", website_url: "https://www.va.gov/cincinnati-health-care/", source_name: "DAV / Cincinnati VAMC", source_type: "va_facility", phone: "513-861-3100", address: "3200 Vine St, Cincinnati, OH 45220", zip: "45220", desc: "DAV Transportation Network — Cincinnati VAMC volunteer driver program; free transportation for veterans to and from Cincinnati VAMC, Fort Thomas OPC, Bellevue OPC, and Hamilton-area CBOCs. DAV-purchased vans, volunteer drivers coordinated by VA Voluntary Services." },
  { section: "TRANS", title: "Dayton VAMC — DAV Volunteer Driver Program", cat: "transportation", sub: "Veteran Transportation Programs", city: "Dayton", website_url: "https://www.va.gov/dayton-health-care/", source_name: "DAV / Dayton VAMC", source_type: "va_facility", phone: "937-268-6511", address: "4100 W 3rd St, Dayton, OH 45428", zip: "45428", desc: "DAV Transportation Network — Dayton VAMC volunteer driver program; free transportation for veterans to and from Dayton VAMC and Springfield, Lima, Middletown, Richmond OPCs. DAV-purchased vans, volunteer drivers coordinated by VA Voluntary Services." },
  { section: "TRANS", title: "Chillicothe VAMC — DAV Volunteer Driver Program", cat: "transportation", sub: "Veteran Transportation Programs", city: "Chillicothe", website_url: "https://www.va.gov/chillicothe-health-care/", source_name: "DAV / Chillicothe VAMC", source_type: "va_facility", phone: "740-773-1141", address: "17273 OH-104, Chillicothe, OH 45601", zip: "45601", desc: "DAV Transportation Network — Chillicothe VAMC volunteer driver program; free transportation for veterans to and from Chillicothe VAMC and Athens, Marietta, Portsmouth, Lancaster CBOCs. DAV-purchased vans, volunteer drivers coordinated by VA Voluntary Services." },
  { section: "TRANS", title: "Greater Cleveland Regional Transit Authority (GCRTA) — Paratransit", cat: "transportation", sub: "Public Transit Assistance", city: "Cleveland", website_url: "https://www.riderta.com/paratransit", source_name: "Greater Cleveland Regional Transit Authority", source_type: "public_authority", phone: "216-621-9500", address: "1240 W 6th St, Cleveland, OH 44113", zip: "44113", desc: "GCRTA Paratransit Service — ADA complementary paratransit for Cuyahoga County riders unable to use fixed-route bus/rail due to disability, including disabled veterans. Door-to-door scheduled service; reduced veteran fare on fixed-route bus, rail, and BRT." },
  { section: "TRANS", title: "Central Ohio Transit Authority (COTA) — Mainstream", cat: "transportation", sub: "Public Transit Assistance", city: "Columbus", website_url: "https://www.cota.com/", source_name: "Central Ohio Transit Authority", source_type: "public_authority", phone: "614-228-1776", address: "33 N High St, Columbus, OH 43215", zip: "43215", desc: "COTA Mainstream — ADA complementary paratransit for Franklin County riders unable to use fixed-route bus due to disability, including disabled veterans. Door-to-door scheduled service; reduced veteran fare on fixed-route bus and CMAX BRT." },
  { section: "TRANS", title: "Southwest Ohio Regional Transit Authority (SORTA/Metro) — Access", cat: "transportation", sub: "Public Transit Assistance", city: "Cincinnati", website_url: "https://www.go-metro.com/transit-services/access", source_name: "Southwest Ohio Regional Transit Authority", source_type: "public_authority", phone: "513-632-7575", address: "525 Vine St Suite 2200, Cincinnati, OH 45202", zip: "45202", desc: "SORTA Metro Access — ADA complementary paratransit for Hamilton County riders unable to use Metro fixed-route bus due to disability, including disabled veterans. Door-to-door scheduled service; reduced veteran fare on Metro." },
  { section: "TRANS", title: "Greater Dayton RTA — Project Mobility", cat: "transportation", sub: "Public Transit Assistance", city: "Dayton", website_url: "https://www.greaterdaytonrta.org/services/project-mobility/", source_name: "Greater Dayton Regional Transit Authority", source_type: "public_authority", phone: "937-425-8300", address: "4 S Main St, Dayton, OH 45402", zip: "45402", desc: "Greater Dayton RTA Project Mobility — ADA complementary paratransit for Montgomery County riders unable to use RTA fixed-route bus or trolley due to disability, including disabled veterans. Door-to-door scheduled service; reduced veteran fare on RTA fixed-route." },
  { section: "TRANS", title: "Toledo Area Regional Transit Authority (TARTA) — TARPS", cat: "transportation", sub: "Public Transit Assistance", city: "Toledo", website_url: "https://www.tarta.com/", source_name: "Toledo Area Regional Transit Authority", source_type: "public_authority", phone: "419-243-7433", address: "1127 W Central Ave, Toledo, OH 43610", zip: "43610", desc: "TARTA TARPS — ADA complementary paratransit for Lucas County riders unable to use TARTA fixed-route bus due to disability, including disabled veterans. Door-to-door scheduled service; reduced veteran fare on fixed-route bus." },
  { section: "TRANS", title: "Lake County Council on Aging — Transportation", cat: "transportation", sub: "Ride Assistance Programs", city: "Painesville", website_url: "https://www.lccoa.org/", source_name: "Lake County Council on Aging", source_type: "county_agency", phone: "440-205-8112", address: "8520 East Ave, Mentor, OH 44060", zip: "44060", desc: "Lake County Council on Aging Transportation — door-to-door transportation for Lake County residents 60+ and disabled adults including older/disabled veterans; medical, grocery, pharmacy, and senior-center trips. Sliding-scale donation; coordination with Lake County VSC." },
  { section: "TRANS", title: "Council on Aging of Southwestern Ohio — Transportation", cat: "transportation", sub: "Ride Assistance Programs", city: "Blue Ash", website_url: "https://www.help4seniors.org/", source_name: "Council on Aging of Southwestern Ohio", source_type: "nonprofit", phone: "513-721-1025", address: "175 Tri County Pkwy, Cincinnati, OH 45246", zip: "45246", desc: "Council on Aging of Southwestern Ohio (Area Agency on Aging) — administers PASSPORT Medicaid waiver and Elderly Services Program in Hamilton, Butler, Clermont, Clinton, Warren counties including transportation services for older adults and disabled veterans aging in place." },
  { section: "TRANS", title: "Western Reserve Area Agency on Aging — Transportation", cat: "transportation", sub: "Ride Assistance Programs", city: "Cleveland", website_url: "https://www.areaagingsolutions.org/", source_name: "Western Reserve Area Agency on Aging", source_type: "nonprofit", phone: "216-621-0303", address: "1700 E 13th St Suite 114, Cleveland, OH 44114", zip: "44114", desc: "Western Reserve Area Agency on Aging — Area Agency on Aging serving Cuyahoga, Geauga, Lake, Lorain, Medina counties; PASSPORT Medicaid waiver, Older Americans Act services including transportation provider directory for older adults and disabled veterans." },
  { section: "TRANS", title: "Veterans Transportation Service (VTS) — VA Statewide", cat: "transportation", sub: "Veteran Transportation Programs", city: "Cleveland", website_url: "https://www.va.gov/healthbenefits/vtp/veterans_transportation_service.asp", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "216-791-3800", address: "Statewide VA service via 5 OH VAMCs", zip: "44106", desc: "Veterans Transportation Service (VTS) — VA-funded mobility-management program at all 5 OH VAMCs (Cleveland, Columbus/Wylie, Cincinnati, Dayton, Chillicothe); coordinates rides via DAV vans, contracted transportation, mileage reimbursement (Beneficiary Travel), and connects with local Section 5310 providers for rural OH veterans." },
];

console.log(`[seed-oh-phase5] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);

runSeed(ROWS, {
  state: "OH",
  state_full: "Ohio",
  commit: COMMIT,
  scriptName: "seed-oh-phase5",
}).catch((e) => { console.error(e); process.exit(1); });
