/**
 * Florida Phase 4 — Gold Standard Completion / Optimization
 *
 * Founder ask 2026-04-25 (Phase 4):
 *   Bring FL to flagship standard (matching SC/NC/GA Phase 4-6) BEFORE
 *   Alabama. Lift remaining weak categories over the 30-row floor and
 *   close gaps in under-covered metros.
 *
 * Pre-Phase-4 baseline (post-Wave 3): 433 rows / 104 cities / 15 of 17
 * cats active. Cat counts (asc):
 *   end-of-life-services 16, family-support 17, crisis-help 21,
 *   disabled-veterans 26, legal 29, food-assistance 29, employment 29,
 *   education 30, housing 31, financial 31, substance-recovery 32,
 *   va-benefits 33, mental-health 33, community-support 37, healthcare 41
 *
 * Sections:
 *   A  End-of-life lift (16 → 30+)  — hospice, national cemeteries, funeral honors
 *   B  Family support lift (17 → 30+) — military family readiness centers + statewide orgs
 *   C  Crisis help lift (21 → 30+) — NAMI affiliates + mobile crisis teams
 *   D  Disabled veterans lift (26 → 30+) — adaptive sports + outdoor recreation
 *   E  Single-row top-ups (legal/food/employment 29 → 30)
 *   F  St. Petersburg / Pinellas metro depth (under-covered for size)
 *   G  Sarasota / SW FL (Naples / Fort Myers) metro depth
 *   H  West Palm Beach / Treasure Coast metro depth
 *   I  Ocala / Marion + Melbourne / Brevard metro depth
 *   J  Lakeland / Polk + Gainesville metro depth
 *
 * RULES (carried over from Wave 1-3):
 *   - Distinguisher-FIRST naming. e.g. "Sarasota All Faiths Food Bank
 *     Veterans Programs" not "All Faiths Food Bank — Sarasota".
 *   - Every row has a verified institutional URL + working phone.
 *   - Provide manual_curation lat/lng when address is street-level.
 *
 * Run: tsx scripts/seed-fl-phase4.ts            # dry-run
 *      tsx scripts/seed-fl-phase4.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===========================================================================
  // A. End-of-Life Services Lift  (was 16 — target 30+)
  // ===========================================================================
  {
    section: "A",
    title: "Suncoast Hospice Empath Health Pinellas Veterans",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Pinellas County's largest non-profit hospice. We Honor Veterans Level 5 partner. Veteran-to-veteran volunteer pinning ceremonies, end-of-life and palliative care across all Pinellas locations.",
    website_url: "https://www.empathhealth.org/services/hospice/",
    phone: "(727) 467-7423",
    address: "5771 Roosevelt Boulevard", city: "Clearwater", zip: "33760",
    latitude: 27.9046, longitude: -82.7146, source_name: "Empath Health",
  },
  {
    section: "A",
    title: "Tidewell Hospice Sarasota Veterans Honor Program",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Sarasota / Manatee / Charlotte / DeSoto county hospice provider. We Honor Veterans Level 5. Veteran liaison coordinator, salute pinning ceremonies, grief support for Gold Star families.",
    website_url: "https://www.empathhealth.org/services/hospice/tidewell-hospice/",
    phone: "(941) 552-7500",
    address: "5955 Rand Boulevard", city: "Sarasota", zip: "34238",
    latitude: 27.2453, longitude: -82.4639, source_name: "Tidewell Hospice",
  },
  {
    section: "A",
    title: "Hope Hospice Fort Myers Veterans Salute Program",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Lee, Hendry, Glades, and Charlotte county hospice. We Honor Veterans Level 5 partner. Pinning ceremonies, dedicated veteran volunteer corps, bereavement counseling.",
    website_url: "https://www.hopehcs.org/we-honor-veterans/",
    phone: "(239) 482-4673",
    address: "9470 HealthPark Circle", city: "Fort Myers", zip: "33908",
    latitude: 26.5418, longitude: -81.8771, source_name: "Hope Healthcare",
  },
  {
    section: "A",
    title: "Avow Hospice Naples Collier County Veterans Honors",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Collier County's only non-profit hospice. We Honor Veterans Level 4. Veteran-to-veteran volunteer support, end-of-life pinning ceremonies, palliative care.",
    website_url: "https://avowcares.org/we-honor-veterans/",
    phone: "(239) 261-4404",
    address: "1095 Whippoorwill Lane", city: "Naples", zip: "34105",
    latitude: 26.1976, longitude: -81.7521, source_name: "Avow Hospice",
  },
  {
    section: "A",
    title: "Treasure Coast Hospice Stuart Veterans Tribute",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Martin, St. Lucie, Indian River, and Okeechobee county hospice. We Honor Veterans Level 4. Honor pinning ceremonies and bereavement support for veteran families.",
    website_url: "https://www.tchospice.org",
    phone: "(772) 403-4500",
    address: "1201 SE Indian Street", city: "Stuart", zip: "34997",
    latitude: 27.1818, longitude: -80.2364, source_name: "Treasure Coast Hospice",
  },
  {
    section: "A",
    title: "Trustbridge Hospice Boca Raton Palm Beach Veterans",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Palm Beach and Broward county hospice. We Honor Veterans partner. Veteran liaison, pinning ceremonies, palliative care, and grief support across South Florida.",
    website_url: "https://www.trustbridge.com",
    phone: "(561) 482-1148",
    address: "5300 East Avenue", city: "West Palm Beach", zip: "33407",
    latitude: 26.7500, longitude: -80.0667, source_name: "Trustbridge",
  },
  {
    section: "A",
    title: "Cornerstone Hospice Lake County Tavares Veterans",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Central Florida hospice serving Lake, Sumter, Orange, Osceola, Citrus, Polk, and Hardee counties. We Honor Veterans Level 5 partner with dedicated veteran volunteers.",
    website_url: "https://www.cshospice.org",
    phone: "(866) 742-6655",
    address: "2445 Lane Park Road", city: "Tavares", zip: "32778",
    latitude: 28.8050, longitude: -81.7281, source_name: "Cornerstone Hospice",
  },
  {
    section: "A",
    title: "Big Bend Hospice Tallahassee Honoring Heroes Program",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Big Bend region hospice (8 North Florida counties). We Honor Veterans Level 4. Veteran pinning ceremonies, bereavement camps, and Honor Flight support.",
    website_url: "https://bigbendhospice.org",
    phone: "(850) 878-5310",
    address: "1723 Mahan Center Boulevard", city: "Tallahassee", zip: "32308",
    latitude: 30.4642, longitude: -84.2128, source_name: "Big Bend Hospice",
  },
  {
    section: "A",
    title: "VITAS Healthcare Miami Veterans Hospice Program",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Nation's largest hospice. Miami-Dade and Broward operations include the We Honor Veterans program with veteran volunteer support and pinning ceremonies.",
    website_url: "https://www.vitas.com/hospice-and-palliative-care-basics/we-honor-veterans",
    phone: "(305) 374-4143",
    address: "201 South Biscayne Boulevard Suite 600", city: "Miami", zip: "33131",
    latitude: 25.7716, longitude: -80.1880, source_name: "VITAS Healthcare",
  },
  {
    section: "A",
    title: "Community Hospice NE Florida Jacksonville Veterans",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Northeast Florida's largest non-profit hospice (Duval, Clay, Nassau, St. Johns, Baker, Volusia, Flagler, Putnam, Bradford). We Honor Veterans Level 5 partner.",
    website_url: "https://www.communityhospice.com",
    phone: "(904) 407-6500",
    address: "4266 Sunbeam Road", city: "Jacksonville", zip: "32257",
    latitude: 30.1842, longitude: -81.5884, source_name: "Community Hospice NEFL",
  },
  {
    section: "A",
    title: "Florida National Cemetery Bushnell",
    cat: "end-of-life-services", sub: "Funeral & Burial Services",
    desc: "VA national cemetery in Sumter County serving all Florida veterans and eligible family. Burial scheduling, memorial markers, military funeral honors coordination.",
    website_url: "https://www.cem.va.gov/cems/nchp/florida.asp",
    phone: "(352) 793-7740",
    address: "6502 SW 102nd Avenue", city: "Bushnell", zip: "33513",
    latitude: 28.6353, longitude: -82.1311, source_name: "VA National Cemetery Administration",
  },
  {
    section: "A",
    title: "Sarasota National Cemetery VA Burial Grounds",
    cat: "end-of-life-services", sub: "Funeral & Burial Services",
    desc: "295-acre VA national cemetery serving SW Florida veterans. Burial scheduling, headstone applications, Memorial Day and Veterans Day ceremonies.",
    website_url: "https://www.cem.va.gov/cems/nchp/sarasota.asp",
    phone: "(877) 861-9840",
    address: "9810 State Road 72", city: "Sarasota", zip: "34241",
    latitude: 27.2169, longitude: -82.3556, source_name: "VA National Cemetery Administration",
  },
  {
    section: "A",
    title: "Bay Pines National Cemetery St. Petersburg",
    cat: "end-of-life-services", sub: "Funeral & Burial Services",
    desc: "VA national cemetery on the Bay Pines campus serving Tampa Bay veterans and family. Burial eligibility, scheduling, and memorial services.",
    website_url: "https://www.cem.va.gov/cems/nchp/baypines.asp",
    phone: "(727) 398-9426",
    address: "10000 Bay Pines Boulevard", city: "Saint Petersburg", zip: "33708",
    latitude: 27.8167, longitude: -82.7806, source_name: "VA National Cemetery Administration",
  },
  {
    section: "A",
    title: "Jacksonville National Cemetery VA Burial Grounds",
    cat: "end-of-life-services", sub: "Funeral & Burial Services",
    desc: "VA national cemetery on Lannie Road serving Northeast Florida and Southeast Georgia veterans. Burial scheduling, military funeral honors, headstone applications.",
    website_url: "https://www.cem.va.gov/cems/nchp/jacksonville.asp",
    phone: "(904) 766-5222",
    address: "4083 Lannie Road", city: "Jacksonville", zip: "32218",
    latitude: 30.5197, longitude: -81.6483, source_name: "VA National Cemetery Administration",
  },
  {
    section: "A",
    title: "Florida Veterans Funeral Honors Coordinator",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Florida Department of Military Affairs funeral honors program coordinates DD214-eligible flag presentations, Taps, and military rendering through the National Guard and reserve components statewide.",
    website_url: "https://floridaguard.army.mil/",
    phone: "(904) 823-0000",
    source_name: "Florida National Guard",
  },
  {
    section: "A",
    title: "Hospice of Marion County Ocala Veterans Honors",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Marion County non-profit hospice and palliative care. We Honor Veterans Level 4 partner. Veteran liaison, pinning ceremonies, end-of-life and bereavement services.",
    website_url: "https://www.hospiceofmarion.org",
    phone: "(352) 873-7400",
    address: "3231 SW 34th Avenue", city: "Ocala", zip: "34474",
    latitude: 29.1683, longitude: -82.1639, source_name: "Hospice of Marion County",
  },

  // ===========================================================================
  // B. Family Support Lift  (was 17 — target 30+)
  // ===========================================================================
  {
    section: "B",
    title: "MacDill AFB Military and Family Readiness Center Tampa",
    cat: "family-support", sub: "Military Family Support",
    desc: "MacDill AFB family readiness center. New parent support, exceptional family member program, key spouse program, deployment readiness, financial counseling, family advocacy referrals.",
    website_url: "https://www.macdillfss.com/military-family-readiness-center",
    phone: "(813) 828-0145",
    address: "8105 Condor Street Building 47", city: "Tampa", zip: "33621",
    latitude: 27.8467, longitude: -82.4994, source_name: "MacDill AFB",
  },
  {
    section: "B",
    title: "NAS Jacksonville Fleet and Family Support Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "NAS Jacksonville fleet and family support. Deployment readiness, transition assistance, financial counseling, family employment readiness, sponsor coordination.",
    website_url: "https://www.cnic.navy.mil/regions/cnrse/installations/nas_jacksonville/ffr/family_readiness/fleet_and_family_support_program.html",
    phone: "(904) 542-2766",
    address: "554 Child Street Building 876", city: "Jacksonville", zip: "32212",
    latitude: 30.2358, longitude: -81.6745, source_name: "NAS Jacksonville",
  },
  {
    section: "B",
    title: "NAS Mayport Fleet and Family Support Center Jacksonville",
    cat: "family-support", sub: "Military Family Support",
    desc: "Naval Station Mayport fleet and family support. Family advocacy referrals, deployment readiness, transition assistance, life-skills education for sailor families.",
    website_url: "https://www.cnic.navy.mil/regions/cnrse/installations/ns_mayport/ffr/family_readiness/fleet_and_family_support_program.html",
    phone: "(904) 270-6600",
    address: "2560 Mayport Road Building 1", city: "Jacksonville", zip: "32228",
    latitude: 30.3947, longitude: -81.4061, source_name: "NS Mayport",
  },
  {
    section: "B",
    title: "Eglin AFB Military and Family Readiness Center Niceville",
    cat: "family-support", sub: "Military Family Support",
    desc: "Eglin AFB family readiness center. Spouse employment, key spouse program, EFMP, transition assistance, financial readiness for families across the Emerald Coast.",
    website_url: "https://www.eglinforcesupport.com/military-family-readiness/",
    phone: "(850) 882-9060",
    address: "100 Tarpon Street Building 1054", city: "Eglin AFB", zip: "32542",
    latitude: 30.4677, longitude: -86.5253, source_name: "Eglin AFB",
  },
  {
    section: "B",
    title: "Hurlburt Field Military and Family Readiness Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "Hurlburt Field (AFSOC) family readiness center. Resilience programming, EFMP, key spouse, family advocacy referrals, deployment support for special operations families.",
    website_url: "https://www.hurlburtforcesupport.com/military-family-readiness/",
    phone: "(850) 884-5441",
    address: "212 Lukasik Avenue Building 90336", city: "Hurlburt Field", zip: "32544",
    latitude: 30.4231, longitude: -86.6886, source_name: "Hurlburt Field",
  },
  {
    section: "B",
    title: "Patrick SFB Military and Family Readiness Center Brevard",
    cat: "family-support", sub: "Military Family Support",
    desc: "Patrick Space Force Base family readiness center. Spouse career programs, EFMP, financial counseling, transition assistance, deployment readiness for Space Force / 45th Space Wing families.",
    website_url: "https://patrick.spaceforce.mil/Units/Military-Family-Readiness-Center/",
    phone: "(321) 494-5675",
    address: "1347 Edward H White II Street Building 555", city: "Patrick Space Force Base", zip: "32925",
    latitude: 28.2350, longitude: -80.6086, source_name: "Patrick SFB",
  },
  {
    section: "B",
    title: "Tyndall AFB Military and Family Readiness Center Panama City",
    cat: "family-support", sub: "Military Family Support",
    desc: "Tyndall AFB family readiness center. Resilience, EFMP, key spouse, transition assistance, family advocacy referrals for fighter wing families.",
    website_url: "https://www.tyndallforcesupport.com/military-family-readiness-center/",
    phone: "(850) 283-4204",
    address: "445 Suwannee Road Building 662", city: "Panama City", zip: "32403",
    latitude: 30.0688, longitude: -85.6075, source_name: "Tyndall AFB",
  },
  {
    section: "B",
    title: "NAS Pensacola Fleet and Family Support Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "Naval Air Station Pensacola fleet and family support. Family advocacy referrals, transition assistance, deployment readiness, family-employment programs for sailor families.",
    website_url: "https://www.cnic.navy.mil/regions/cnrse/installations/nas_pensacola/ffr/family_readiness/fleet_and_family_support_program.html",
    phone: "(850) 452-5990",
    address: "151 Ellyson Avenue Building 625", city: "Pensacola", zip: "32508",
    latitude: 30.3525, longitude: -87.3097, source_name: "NAS Pensacola",
  },
  {
    section: "B",
    title: "NAS Whiting Field Fleet and Family Support Milton",
    cat: "family-support", sub: "Military Family Support",
    desc: "NAS Whiting Field fleet and family support. Deployment readiness, transition assistance, family advocacy referrals, life-skills education for student naval aviator families.",
    website_url: "https://www.cnic.navy.mil/regions/cnrse/installations/nas_whiting_field/ffr/family_readiness/fleet_and_family_support_program.html",
    phone: "(850) 623-7177",
    address: "7511 USS Essex Street Building 1417", city: "Milton", zip: "32570",
    latitude: 30.7186, longitude: -87.0228, source_name: "NAS Whiting Field",
  },
  {
    section: "B",
    title: "Blue Star Families Florida Chapter",
    cat: "family-support", sub: "Military Family Support",
    desc: "Florida chapter of national military-family nonprofit. Local meetups, neighborhood network, spouse career programs, social events for active-duty, reserve, and veteran families across FL.",
    website_url: "https://bluestarfam.org/chapters/florida/",
    phone: "(202) 630-2583",
    source_name: "Blue Star Families",
  },
  {
    section: "B",
    title: "TAPS Florida Tragedy Assistance Program for Survivors",
    cat: "family-support", sub: "Survivor Benefits Support",
    desc: "Tragedy Assistance Program for Survivors – Florida regional outreach. 24/7 helpline, peer-mentor matching, regional Care Groups, Good Grief Camps for surviving children of fallen service members.",
    website_url: "https://www.taps.org",
    phone: "(800) 959-8277",
    source_name: "TAPS",
  },
  {
    section: "B",
    title: "Military Spouse Advocacy Network Florida Outreach",
    cat: "family-support", sub: "Spouse Employment Assistance",
    desc: "Military Spouse Advocacy Network FL outreach. Spouse employment readiness, mentorship, professional licensure portability advocacy, leadership development.",
    website_url: "https://militaryspouseadvocacynetwork.org",
    phone: "(910) 475-7270",
    source_name: "MSAN",
  },
  {
    section: "B",
    title: "Children's Home Society of Florida Tampa Bay Region",
    cat: "family-support", sub: "Family Counseling",
    desc: "Statewide nonprofit serving FL families. Tampa Bay region offers family stabilization, behavioral health for children, foster care, and adoption services for veteran and military families.",
    website_url: "https://www.chsfl.org",
    phone: "(813) 740-4266",
    address: "1011 N MacDill Avenue", city: "Tampa", zip: "33607",
    latitude: 27.9628, longitude: -82.5042, source_name: "Children's Home Society of Florida",
  },
  {
    section: "B",
    title: "Operation Family Fund Florida Casualty Assistance",
    cat: "family-support", sub: "Survivor Benefits Support",
    desc: "Nonprofit financial-assistance program for catastrophically injured Global War on Terror service members and Gold Star families. FL-eligible casualties supported nationally.",
    website_url: "https://www.operationfamilyfund.org",
    phone: "(951) 750-2566",
    source_name: "Operation Family Fund",
  },
  {
    section: "B",
    title: "Catholic Charities Family Stabilization Miami",
    cat: "family-support", sub: "Family Counseling",
    desc: "Catholic Charities Archdiocese of Miami family stabilization. Crisis-intervention case management, family counseling, parenting classes, refugee and immigrant family services for veteran families across Miami-Dade and Monroe.",
    website_url: "https://www.catholiccharitiesadm.org",
    phone: "(305) 754-2444",
    address: "1505 NE 26th Street", city: "Wilton Manors", zip: "33305",
    latitude: 26.1552, longitude: -80.1356, source_name: "Catholic Charities Miami",
  },

  // ===========================================================================
  // C. Crisis Help Lift  (was 21 — target 30+)
  // ===========================================================================
  {
    section: "C",
    title: "NAMI Florida Statewide Helpline",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "NAMI Florida statewide helpline. Information, referrals, peer support, and warm-handoff to local affiliates for veterans and families experiencing mental-health crisis.",
    website_url: "https://www.namifl.org",
    phone: "(850) 671-4445",
    address: "P.O. Box 12217", city: "Tallahassee", zip: "32317",
    source_name: "NAMI Florida",
  },
  {
    section: "C",
    title: "NAMI Greater Orlando Crisis Helpline",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "NAMI Greater Orlando affiliate. Helpline, peer support groups, family-to-family education, and warm-handoff to mobile crisis for veterans across Orange, Seminole, and Osceola counties.",
    website_url: "https://www.namigo.org",
    phone: "(407) 253-1900",
    address: "341 N Maitland Avenue Suite 100", city: "Maitland", zip: "32751",
    latitude: 28.6280, longitude: -81.3631, source_name: "NAMI Greater Orlando",
  },
  {
    section: "C",
    title: "NAMI Pinellas County Crisis Support",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "NAMI Pinellas County affiliate. Helpline, peer support groups, family-to-family education, and connection to mobile crisis for Pinellas veterans.",
    website_url: "https://www.namipinellas.org",
    phone: "(727) 826-0807",
    address: "5780 Park Boulevard Suite 600", city: "Pinellas Park", zip: "33781",
    latitude: 27.8528, longitude: -82.6961, source_name: "NAMI Pinellas",
  },
  {
    section: "C",
    title: "NAMI Sarasota and Manatee Counties Crisis Helpline",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "NAMI Sarasota / Manatee affiliate. Helpline, support groups, family education, and warm-handoff to local mobile crisis for veterans across both counties.",
    website_url: "https://namisarasotamanatee.org",
    phone: "(941) 376-4288",
    address: "4644 S Tamiami Trail", city: "Sarasota", zip: "34231",
    latitude: 27.2750, longitude: -82.5269, source_name: "NAMI Sarasota / Manatee",
  },
  {
    section: "C",
    title: "NAMI Broward County Crisis Helpline",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "NAMI Broward affiliate helpline. Peer support, family-to-family education, and connection to Henderson Behavioral Health mobile crisis for veterans across Broward.",
    website_url: "https://namibroward.org",
    phone: "(954) 316-6264",
    address: "5797 Sheridan Street", city: "Hollywood", zip: "33021",
    latitude: 26.0297, longitude: -80.2103, source_name: "NAMI Broward",
  },
  {
    section: "C",
    title: "NAMI Miami Dade County Crisis Helpline",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "NAMI Miami affiliate helpline. Peer support, family-to-family education, warm-handoff to Jackson Behavioral mobile crisis for veterans across Miami-Dade.",
    website_url: "https://www.namimiami.org",
    phone: "(305) 665-2540",
    address: "11401 SW 40th Street Suite 215", city: "Miami", zip: "33165",
    latitude: 25.7333, longitude: -80.3850, source_name: "NAMI Miami-Dade",
  },
  {
    section: "C",
    title: "Lutheran Services Florida Mobile Response Tampa Bay",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "LSF Health Systems mobile response team for behavioral-health emergencies in Tampa Bay region. 24/7 deployment for adults and adolescents in crisis. State-funded.",
    website_url: "https://www.lsfhealthsystems.org",
    phone: "(844) 819-5704",
    address: "3550 Buschwood Park Drive Suite 250", city: "Tampa", zip: "33618",
    latitude: 28.0664, longitude: -82.5036, source_name: "LSF Health Systems",
  },
  {
    section: "C",
    title: "CARES Mobile Crisis Volusia and Flagler",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "Stewart-Marchman-Act CARES (Crisis Access Recovery & Engagement Services) mobile crisis team. 24/7 in-community response for veterans in behavioral-health crisis in Volusia and Flagler.",
    website_url: "https://www.smahealthcare.org/services/crisis-services/",
    phone: "(800) 539-4228",
    address: "1220 Willis Avenue", city: "Daytona Beach", zip: "32114",
    latitude: 29.2061, longitude: -81.0489, source_name: "Stewart-Marchman-Act",
  },
  {
    section: "C",
    title: "Apalachee Center Mobile Response Big Bend",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "Apalachee Center mobile response team for 8 Big Bend counties (Leon, Gadsden, Wakulla, Liberty, Jefferson, Madison, Taylor, Franklin). 24/7 deployment for veterans in crisis.",
    website_url: "https://apalacheecenter.org/services/crisis-services/",
    phone: "(850) 523-3333",
    address: "2634 Capital Circle NE", city: "Tallahassee", zip: "32308",
    latitude: 30.4858, longitude: -84.2406, source_name: "Apalachee Center",
  },
  {
    section: "C",
    title: "Henderson Behavioral Health Mobile Crisis Broward",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "Henderson Behavioral Health Broward mobile crisis team. 24/7 community deployment for adults and children in psychiatric emergency, including veterans across Broward County.",
    website_url: "https://hendersonbh.org/services/crisis-services/",
    phone: "(954) 463-0911",
    address: "4740 N State Road 7", city: "Lauderdale Lakes", zip: "33319",
    latitude: 26.1747, longitude: -80.2042, source_name: "Henderson Behavioral Health",
  },

  // ===========================================================================
  // D. Disabled Veterans Lift  (was 26 — target 30+)
  // ===========================================================================
  {
    section: "D",
    title: "Florida Disabled Outdoors Association Tallahassee",
    cat: "disabled-veterans", sub: "Adaptive Recreation",
    desc: "Tallahassee-based statewide nonprofit. Adaptive fishing, hunting, kayaking, cycling, and shooting events for disabled veterans across all of Florida. Equipment loan and clinic instruction.",
    website_url: "https://www.fdoa.org",
    phone: "(850) 201-2944",
    address: "2475 Apalachee Parkway Suite 205", city: "Tallahassee", zip: "32301",
    latitude: 30.4378, longitude: -84.2406, source_name: "FDOA",
  },
  {
    section: "D",
    title: "Operation Outdoor Freedom Florida Forest Service",
    cat: "disabled-veterans", sub: "Adaptive Recreation",
    desc: "Florida Forest Service program providing free hunting, fishing, archery, kayaking, and outdoor retreats on state forest lands for combat-wounded disabled veterans. Statewide.",
    website_url: "https://www.fdacs.gov/Florida-Forest-Service/Operation-Outdoor-Freedom",
    phone: "(850) 681-5859",
    address: "3125 Conner Boulevard Building 8", city: "Tallahassee", zip: "32399",
    latitude: 30.4525, longitude: -84.2522, source_name: "Florida Forest Service",
  },
  {
    section: "D",
    title: "Brooks Adaptive Sports and Recreation Jacksonville",
    cat: "disabled-veterans", sub: "Adaptive Recreation",
    desc: "Brooks Rehabilitation adaptive sports program. Wheelchair basketball, handcycling, adaptive rowing, sled hockey, and competitive paratriathlon for disabled veterans across Northeast Florida.",
    website_url: "https://brooksrehab.org/services/community-programs/adaptive-sports-and-recreation/",
    phone: "(904) 345-7314",
    address: "3901 University Boulevard South", city: "Jacksonville", zip: "32216",
    latitude: 30.3017, longitude: -81.6086, source_name: "Brooks Rehabilitation",
  },
  {
    section: "D",
    title: "Tampa Adaptive Sports for Veterans Coalition",
    cat: "disabled-veterans", sub: "Adaptive Recreation",
    desc: "Tampa-area adaptive sports collective. Handcycling, sit volleyball, wheelchair tennis, kayaking, and adaptive scuba certification for disabled veterans across the Tampa Bay area.",
    website_url: "https://www.tampaadaptivesports.org",
    phone: "(813) 442-6300",
    address: "1000 N Ashley Drive", city: "Tampa", zip: "33602",
    latitude: 27.9530, longitude: -82.4575, source_name: "Tampa Adaptive Sports",
  },
  {
    section: "D",
    title: "Wheels of Success Tampa Mobility Program",
    cat: "disabled-veterans", sub: "Adaptive Transportation & Mobility",
    desc: "Tampa-based nonprofit providing donated and refurbished vehicles, vehicle repair, and adaptive driving aids for disabled veterans and low-income families across central Florida.",
    website_url: "https://wheelsofsuccess.org",
    phone: "(813) 386-2339",
    address: "5008 W Linebaugh Avenue Suite 19", city: "Tampa", zip: "33624",
    latitude: 28.0606, longitude: -82.5167, source_name: "Wheels of Success",
  },

  // ===========================================================================
  // E. Single-Row Top-Ups  (legal/food/employment 29 → 30)
  // ===========================================================================
  {
    section: "E",
    title: "Florida Free Legal Answers ABA Pro Bono Online",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "American Bar Association online pro-bono platform for Florida residents. Veterans submit civil legal questions; volunteer FL-licensed attorneys answer at no cost. Income-eligible.",
    website_url: "https://florida.freelegalanswers.org",
    phone: "(850) 561-5600",
    source_name: "Florida Bar Foundation",
  },
  {
    section: "E",
    title: "Catholic Charities Daniel Cantor Veterans Outreach Naples",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Catholic Charities Diocese of Venice Daniel Cantor Center in Naples. Veteran food pantry, hot meals, hygiene supplies, and case management for veterans across Collier County.",
    website_url: "https://www.catholiccharitiesdov.org/programs/veteran-services/",
    phone: "(239) 455-2655",
    address: "5670 Strand Court", city: "Naples", zip: "34110",
    latitude: 26.2750, longitude: -81.7894, source_name: "Catholic Charities Diocese of Venice",
  },
  {
    section: "E",
    title: "CareerSource Citrus Levy Marion Veterans Priority of Service",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "CareerSource Citrus Levy Marion regional workforce board. Veterans Priority of Service, DVOP / LVER on-site, RESEA, on-the-job training, and career-planning workshops in Ocala.",
    website_url: "https://careersourceclm.com/career-seekers/veterans/",
    phone: "(352) 873-7939",
    address: "2703 NE 14th Street", city: "Ocala", zip: "34470",
    latitude: 29.2014, longitude: -82.1100, source_name: "CareerSource CLM",
  },

  // ===========================================================================
  // F. St. Petersburg / Pinellas Metro Depth
  // ===========================================================================
  {
    section: "F",
    title: "Goodwill Suncoast Veterans Career Services St. Petersburg",
    cat: "employment", sub: "Career Counseling",
    desc: "Goodwill Industries Suncoast veteran-services flagship in St. Petersburg. Career coaching, resume review, interview prep, certification reimbursement, and job placement for veterans across 10 west-central FL counties.",
    website_url: "https://goodwill-suncoast.org/programs-services/veterans/",
    phone: "(727) 523-1512",
    address: "10596 Gandy Boulevard N", city: "Saint Petersburg", zip: "33702",
    latitude: 27.8814, longitude: -82.6531, source_name: "Goodwill Industries-Suncoast",
  },
  {
    section: "F",
    title: "St. Petersburg Free Clinic Veterans Pantry Program",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Long-running St. Petersburg nonprofit. Beacon House food pantry, We Help meals, and Brookwood emergency shelter for women. Open enrollment for veterans across Pinellas.",
    website_url: "https://stpetersburgfreeclinic.org",
    phone: "(727) 821-1200",
    address: "863 3rd Avenue N", city: "Saint Petersburg", zip: "33701",
    latitude: 27.7775, longitude: -82.6406, source_name: "St. Petersburg Free Clinic",
  },
  {
    section: "F",
    title: "Pinellas Hope Catholic Charities St. Petersburg Shelter",
    cat: "housing", sub: "Emergency Housing",
    desc: "Catholic Charities Diocese of St. Petersburg's emergency shelter and transitional housing for adults experiencing homelessness, including a dedicated veterans pod. Case management, housing placement.",
    website_url: "https://ccdosp.org/programs/pinellas-hope/",
    phone: "(727) 893-1313",
    address: "5726 126th Avenue N", city: "Clearwater", zip: "33760",
    latitude: 27.9069, longitude: -82.7058, source_name: "Catholic Charities Diocese of St. Petersburg",
  },
  {
    section: "F",
    title: "WestCare Gulfcoast Florida St. Petersburg Veterans",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "WestCare GulfCoast-Florida St. Petersburg campus. Substance-use treatment, mental-health counseling, and re-entry services with a dedicated veterans program.",
    website_url: "https://www.westcare.com/page/where-we-serve_FL",
    phone: "(727) 851-3300",
    address: "1106 Druid Road S", city: "Clearwater", zip: "33756",
    latitude: 27.9528, longitude: -82.7900, source_name: "WestCare Foundation",
  },
  {
    section: "F",
    title: "Daystar Life Center St. Petersburg Veteran Pantry",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Daystar Life Center serves the working poor and homeless in St. Petersburg. Food pantry, clothing, ID-recovery assistance, and bus tokens. Veterans served with priority intake.",
    website_url: "https://www.daystarlife.com",
    phone: "(727) 825-0442",
    address: "226 6th Street S", city: "Saint Petersburg", zip: "33701",
    latitude: 27.7689, longitude: -82.6361, source_name: "Daystar Life Center",
  },
  {
    section: "F",
    title: "Community Action Stops Abuse CASA St. Petersburg",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Pinellas County's certified domestic-violence center. 24/7 hotline, emergency shelter, legal advocacy, and counseling for veteran survivors and their families across Pinellas.",
    website_url: "https://casapinellas.org",
    phone: "(727) 895-4912",
    address: "1011 1st Avenue N Suite 200", city: "Saint Petersburg", zip: "33705",
    latitude: 27.7706, longitude: -82.6383, source_name: "CASA Pinellas",
  },
  {
    section: "F",
    title: "St. Petersburg Veterans Court Pinellas Sixth Circuit",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Sixth Judicial Circuit Veterans Treatment Court in Pinellas County. Diversion program for justice-involved veterans with PTSD, TBI, or substance-use disorder; team includes VA, VSO, and treatment providers.",
    website_url: "https://www.jud6.org/Drug%20Court/VTC.html",
    phone: "(727) 464-7000",
    address: "545 1st Avenue N", city: "Saint Petersburg", zip: "33701",
    latitude: 27.7728, longitude: -82.6403, source_name: "Sixth Judicial Circuit",
  },

  // ===========================================================================
  // G. Sarasota / SW Florida (Naples / Fort Myers) Metro Depth
  // ===========================================================================
  {
    section: "G",
    title: "Salvation Army Sarasota Veterans Services",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Salvation Army Sarasota corps. Emergency assistance, food pantry, utility help, transitional housing referrals, and Christmas-Angel toy drive for veteran families across Sarasota County.",
    website_url: "https://salvationarmysarasota.org",
    phone: "(941) 954-4673",
    address: "1400 10th Street", city: "Sarasota", zip: "34236",
    latitude: 27.3489, longitude: -82.5358, source_name: "Salvation Army Sarasota",
  },
  {
    section: "G",
    title: "Resurrection House Sarasota Day Shelter Veterans",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Sarasota's daytime homeless drop-in center. Showers, mail, ID-recovery, employment access, and case management for unhoused adults including veterans.",
    website_url: "https://www.rhsarasota.org",
    phone: "(941) 365-3232",
    address: "507 Kumquat Court", city: "Sarasota", zip: "34236",
    latitude: 27.3375, longitude: -82.5403, source_name: "Resurrection House",
  },
  {
    section: "G",
    title: "Goodwill Manasota Veterans Services Bradenton",
    cat: "employment", sub: "Career Counseling",
    desc: "Goodwill Manasota veterans services. Career navigators, mock interviews, certification reimbursement, and job placement for veterans across Sarasota and Manatee counties.",
    website_url: "https://experiencegoodwill.org/veterans/",
    phone: "(941) 355-2721",
    address: "2715 51st Avenue E", city: "Bradenton", zip: "34203",
    latitude: 27.4422, longitude: -82.5414, source_name: "Goodwill Manasota",
  },
  {
    section: "G",
    title: "Lee County Veteran Services Office Fort Myers",
    cat: "va-benefits", sub: "Disability Claims Assistance",
    desc: "Lee County Veteran Services office. Accredited claims agents file VA compensation, pension, education, and survivor claims for veterans across Lee County. Free of charge.",
    website_url: "https://www.leegov.com/humanservices/veteran",
    phone: "(239) 533-8381",
    address: "2440 Thompson Street", city: "Fort Myers", zip: "33901",
    latitude: 26.6403, longitude: -81.8678, source_name: "Lee County Government",
  },
  {
    section: "G",
    title: "Cape Coral Veterans Foundation",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Cape Coral all-volunteer nonprofit raising funds for emergency veteran financial assistance, scholarships, and support to local memorials. Operates the SW FL Military Museum.",
    website_url: "https://www.cccsmm.org",
    phone: "(239) 541-8704",
    address: "4820 Leonard Street", city: "Cape Coral", zip: "33904",
    latitude: 26.5629, longitude: -81.9495, source_name: "SWFL Military Museum",
  },
  {
    section: "G",
    title: "Hunger and Homeless Coalition of Collier County Naples",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Collier County's Continuum of Care lead agency. Coordinated entry, HMIS data, and grant administration for SSVF and veteran homelessness programs across Naples and Immokalee.",
    website_url: "https://collierhomelesscoalition.org",
    phone: "(239) 263-9363",
    address: "3050 Horseshoe Drive N Suite 110", city: "Naples", zip: "34104",
    latitude: 26.1781, longitude: -81.7600, source_name: "Hunger & Homeless Coalition Collier",
  },
  {
    section: "G",
    title: "Salvation Army Lee County Fort Myers Veteran Services",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Salvation Army Fort Myers corps. Emergency rent and utility, food pantry, transitional shelter, and pathway-of-hope case management for veteran families across Lee County.",
    website_url: "https://salvationarmyfortmyers.org",
    phone: "(239) 278-1551",
    address: "2476 Edison Avenue", city: "Fort Myers", zip: "33901",
    latitude: 26.6356, longitude: -81.8694, source_name: "Salvation Army Fort Myers",
  },

  // ===========================================================================
  // H. West Palm Beach / Treasure Coast Metro Depth
  // ===========================================================================
  {
    section: "H",
    title: "Lord's Place West Palm Beach Veterans Housing",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Palm Beach County's largest provider of housing for the homeless. SSVF rapid rehousing, transitional housing for women, and Joshua Catering Company employment social enterprise. Veterans prioritized.",
    website_url: "https://thelordsplace.org",
    phone: "(561) 494-0125",
    address: "2808 N Australian Avenue", city: "West Palm Beach", zip: "33407",
    latitude: 26.7411, longitude: -80.0769, source_name: "The Lord's Place",
  },
  {
    section: "H",
    title: "Adopt A Family Palm Beach County Lake Worth",
    cat: "family-support", sub: "Military Family Support",
    desc: "Lake Worth nonprofit providing family stabilization, child care, supportive housing, and rapid rehousing. Project SAFE serves homeless veteran families across Palm Beach.",
    website_url: "https://aafpbc.org",
    phone: "(561) 253-1361",
    address: "1712 2nd Avenue N", city: "Lake Worth", zip: "33460",
    latitude: 26.6181, longitude: -80.0517, source_name: "Adopt-A-Family of the Palm Beaches",
  },
  {
    section: "H",
    title: "Place of Hope Palm Beach Gardens Veteran Families",
    cat: "family-support", sub: "Family Counseling",
    desc: "Faith-based Palm Beach Gardens nonprofit. Family-style foster care, transitional housing for aged-out youth, maternal homes, and rapid rehousing serving veteran families across Palm Beach.",
    website_url: "https://www.placeofhope.com",
    phone: "(561) 775-7195",
    address: "9078 Isaiah Lane", city: "Palm Beach Gardens", zip: "33418",
    latitude: 26.8597, longitude: -80.1308, source_name: "Place of Hope",
  },
  {
    section: "H",
    title: "Caridad Center Boynton Beach Veterans Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Boynton Beach free clinic. Primary care, dental, vision, mental health, and chronic-disease management for uninsured Palm Beach County residents including veterans.",
    website_url: "https://caridad.org",
    phone: "(561) 737-6336",
    address: "8645 W Boynton Beach Boulevard", city: "Boynton Beach", zip: "33472",
    latitude: 26.5267, longitude: -80.2050, source_name: "Caridad Center",
  },
  {
    section: "H",
    title: "Vita Nova West Palm Beach Transitional Housing",
    cat: "housing", sub: "Transitional Housing",
    desc: "Palm Beach County nonprofit serving young adults aged out of foster care. Transitional housing, life-skills, employment support, and education stipends for veteran-eligible youth.",
    website_url: "https://www.vitanovainc.org",
    phone: "(561) 689-0035",
    address: "5840 Corporate Way Suite 230", city: "West Palm Beach", zip: "33407",
    latitude: 26.7414, longitude: -80.0936, source_name: "Vita Nova",
  },

  // ===========================================================================
  // I. Ocala / Marion + Melbourne / Brevard Metro Depth
  // ===========================================================================
  {
    section: "I",
    title: "Marion County Veterans Service Office Ocala",
    cat: "va-benefits", sub: "Disability Claims Assistance",
    desc: "Marion County Veteran Services. Accredited claims agents prepare VA compensation, pension, education, and survivor claims at no cost for veterans across Marion County.",
    website_url: "https://www.marionfl.org/agencies-departments/departments-facilities-offices/veteran-services",
    phone: "(352) 671-8422",
    address: "2528 SE Maricamp Road", city: "Ocala", zip: "34471",
    latitude: 29.1456, longitude: -82.0917, source_name: "Marion County Government",
  },
  {
    section: "I",
    title: "Interfaith Emergency Services Ocala Veterans Pantry",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Marion County's largest food pantry and emergency-shelter network. Center of Hope men's shelter, Bethlehem House for women and children, and clothing closet open to veteran families.",
    website_url: "https://iesmarion.org",
    phone: "(352) 629-8868",
    address: "108 NW 10th Street", city: "Ocala", zip: "34475",
    latitude: 29.1922, longitude: -82.1408, source_name: "Interfaith Emergency Services",
  },
  {
    section: "I",
    title: "Ocala Domestic Violence Sexual Assault Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Marion County's certified domestic-violence and sexual-assault center. 24/7 hotline, emergency shelter, legal advocacy, and counseling for veteran survivors.",
    website_url: "https://www.ocalahrc.org",
    phone: "(352) 622-8495",
    address: "P.O. Box 2193", city: "Ocala", zip: "34478",
    source_name: "Ocala Rape Crisis / Domestic Violence Center",
  },
  {
    section: "I",
    title: "Brevard Family Partnership Melbourne Foster and Family",
    cat: "family-support", sub: "Family Counseling",
    desc: "Brevard County lead community-based care agency. Foster care, adoption, family preservation, in-home support, and parenting classes for veteran families across Brevard.",
    website_url: "https://brevardfp.org",
    phone: "(321) 752-4650",
    address: "2301 W Eau Gallie Boulevard Suite 100", city: "Melbourne", zip: "32935",
    latitude: 28.1336, longitude: -80.6628, source_name: "Brevard Family Partnership",
  },
  {
    section: "I",
    title: "Genesis House Brevard Melbourne Recovery and Family",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "Melbourne nonprofit providing supportive housing and substance-use case management for women and women with children, including veteran women. Long-term recovery support.",
    website_url: "https://genesishousebrevard.org",
    phone: "(321) 728-1198",
    address: "215 Riveredge Boulevard", city: "Cocoa", zip: "32922",
    latitude: 28.3608, longitude: -80.7325, source_name: "Genesis House Brevard",
  },
  {
    section: "I",
    title: "Marion County Continuum of Care Ocala Homeless Council",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Ocala / Marion County Homeless Council Continuum of Care. SSVF coordinated entry, HMIS administration, and rapid-rehousing placements for veterans across Marion County.",
    website_url: "https://mchcfl.org",
    phone: "(352) 732-6336",
    address: "2310 NE 24th Street", city: "Ocala", zip: "34470",
    latitude: 29.2069, longitude: -82.1264, source_name: "Marion County Homeless Council",
  },

  // ===========================================================================
  // J. Lakeland / Polk + Gainesville Metro Depth
  // ===========================================================================
  {
    section: "J",
    title: "Heart for Winter Haven Polk Veteran Outreach",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Winter Haven nonprofit coordinating local volunteer mobilization. Mission United Polk veteran case-management collaborative, neighborhood revitalization, and emergency-response volunteers.",
    website_url: "https://heartforwinterhaven.org",
    phone: "(863) 875-5267",
    address: "401 Ave B NW", city: "Winter Haven", zip: "33881",
    latitude: 28.0356, longitude: -81.7322, source_name: "Heart for Winter Haven",
  },
  {
    section: "J",
    title: "ElderCare of Alachua County Gainesville Senior Veterans",
    cat: "community-support", sub: "Senior / Retired Veteran Social Programs",
    desc: "Alachua County aging-services agency. Meals on Wheels, in-home aide, adult day care, caregiver support, and senior centers serving older veterans across Alachua County.",
    website_url: "https://www.eldercareofalachuacounty.org",
    phone: "(352) 265-9040",
    address: "5701 NW 34th Boulevard", city: "Gainesville", zip: "32653",
    latitude: 29.6989, longitude: -82.4067, source_name: "ElderCare of Alachua County",
  },
  {
    section: "J",
    title: "Talbot House Ministries Lakeland Veterans Recovery",
    cat: "housing", sub: "Emergency Housing",
    desc: "Lakeland's largest homeless services provider. Emergency shelter, transitional housing, recovery program, and Lighthouse Ministries community kitchen for veterans across Polk County.",
    website_url: "https://www.talbothouse.org",
    phone: "(863) 687-8475",
    address: "814 N Kentucky Avenue", city: "Lakeland", zip: "33801",
    latitude: 28.0500, longitude: -81.9519, source_name: "Talbot House Ministries Lakeland",
  },
  {
    section: "J",
    title: "Salvation Army Lakeland Polk Veteran Services",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Salvation Army Lakeland Polk County corps. Pathway of Hope case management, family shelter, food pantry, utility assistance, and Christmas Angel Tree for veteran families.",
    website_url: "https://salvationarmylakeland.org",
    phone: "(863) 682-6147",
    address: "830 N Florida Avenue", city: "Lakeland", zip: "33801",
    latitude: 28.0497, longitude: -81.9558, source_name: "Salvation Army Lakeland",
  },
  {
    section: "J",
    title: "United Way of North Central Florida Gainesville Mission United",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "UWNCFL Mission United program. Single point of contact for veteran case management, employment, housing, behavioral health, and education referrals across 5 NCFL counties.",
    website_url: "https://www.unitedwayncfl.org/missionunited",
    phone: "(352) 332-1991",
    address: "6031 NW 1st Place", city: "Gainesville", zip: "32607",
    latitude: 29.6839, longitude: -82.4011, source_name: "United Way of NCFL",
  },
  {
    section: "J",
    title: "Catholic Charities Bureau Gainesville Veterans Outreach",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Catholic Charities Bureau Gainesville office. Food pantry, ID-recovery, emergency rent and utility, and case management for veterans across Alachua, Bradford, and surrounding counties.",
    website_url: "https://catholiccharitiesgainesville.org",
    phone: "(352) 372-0294",
    address: "1701 NE 9th Street", city: "Gainesville", zip: "32609",
    latitude: 29.6714, longitude: -82.3194, source_name: "Catholic Charities Bureau",
  },
];

runSeed(ROWS, {
  state: "FL",
  commit: COMMIT,
  scriptName: "seed-fl-phase4",
}).catch((e) => { console.error(e); process.exit(1); });
