/**
 * Texas Phase 6 — Audit / Patch / Closeout pass
 * Continued weak-cat lift (per Florida SOP P6 = Audit / Patch / Closeout).
 * Targets: substance-recovery (14→20+), insurance (15→20+), disabled-vets,
 * family-support, transportation depth.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  // SUBSTANCE-RECOVERY LIFT (14 → 22+)
  { section: "SR", title: "Salvation Army Houston Adult Rehabilitation Center", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Houston", website_url: "https://houstonarc.salvationarmy.org/", source_name: "The Salvation Army Adult Rehabilitation Centers Command", source_type: "treatment_center", phone: "713-869-3551", address: "2208 Jensen Dr, Houston, TX 77026", zip: "77026", desc: "Salvation Army's Houston ARC — 6-month no-cost residential addiction-recovery program for men with structured work-therapy, group counseling, spiritual care, and life-skills education. Beneficiary-funded through ARC thrift stores; veteran-priority intake; coordinates with DeBakey VAMC SUD program for aftercare." },
  { section: "SR", title: "Salvation Army Dallas Adult Rehabilitation Center", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Dallas", website_url: "https://dallasarc.salvationarmy.org/", source_name: "The Salvation Army Adult Rehabilitation Centers Command", source_type: "treatment_center", phone: "214-374-5151", address: "5302 Harry Hines Blvd, Dallas, TX 75235", zip: "75235", desc: "Salvation Army's Dallas ARC — 6-month no-cost residential addiction-recovery program for men with work-therapy, group counseling, spiritual care, and life-skills education. Beneficiary-funded through ARC thrift stores; veteran-priority intake; coordinates with Dallas VAMC SUD program for aftercare." },
  { section: "SR", title: "Salvation Army San Antonio Adult Rehabilitation Center", cat: "substance-recovery", sub: "Outpatient Recovery", city: "San Antonio", website_url: "https://sanantonioarc.salvationarmy.org/", source_name: "The Salvation Army Adult Rehabilitation Centers Command", source_type: "treatment_center", phone: "210-352-2046", address: "226 Nolan St, San Antonio, TX 78202", zip: "78202", desc: "Salvation Army's San Antonio ARC — 6-month no-cost residential addiction-recovery program for men with work-therapy, group counseling, spiritual care, and life-skills education. Beneficiary-funded through ARC thrift stores; veteran-priority intake; coordinates with Audie L. Murphy VAMC SUD program." },
  { section: "SR", title: "Volunteers of America Texas — Veteran Recovery Programs", cat: "substance-recovery", sub: "Veteran Recovery Programs", city: "Euless", website_url: "https://www.voatx.org/veterans", source_name: "Volunteers of America Texas", source_type: "nonprofit", phone: "972-660-2640", desc: "VOA Texas operating veteran-specific recovery and supportive-housing programs across DFW, including Patriot Place transitional housing for homeless veterans with co-occurring SUD/MH disorders, peer recovery support, and case management. SSVF / HUD-VASH partner agency." },
  { section: "SR", title: "The Right Step Texas (Promises Behavioral Health)", cat: "substance-recovery", sub: "Detox Programs", city: "Hill Country Village", website_url: "https://www.rightstep.com/locations/", source_name: "Promises Behavioral Health / The Right Step", source_type: "treatment_center", phone: "844-877-1781", desc: "Texas-based residential and outpatient SUD treatment network operating facilities in San Antonio (Hill Country Village), Dallas, Plano, Houston, Austin, and Wimberley. Inpatient detox, residential, PHP/IOP, MAT, and dual-diagnosis treatment; TRICARE provider; most insurance accepted." },
  { section: "SR", title: "Greenhouse Treatment Center (American Addiction Centers)", cat: "substance-recovery", sub: "Detox Programs", city: "Grand Prairie", website_url: "https://greenhousetreatment.com/", source_name: "American Addiction Centers", source_type: "treatment_center", phone: "972-559-2620", address: "1171 107th St, Grand Prairie, TX 75050", zip: "75050", desc: "DFW Metroplex residential SUD treatment center on a 22-acre campus in Grand Prairie. Medically-supervised detox, residential, PHP, IOP, MAT, family programs, and dual-diagnosis treatment; specialized Veterans & First Responders track; TRICARE provider; most insurance accepted." },
  { section: "SR", title: "Texas Veterans Treatment Court Network (TVC)", cat: "substance-recovery", sub: "Veteran Recovery Programs", city: "Austin", website_url: "https://www.tvc.texas.gov/grants/veterans-treatment-court-grant-program/", source_name: "Texas Veterans Commission", source_type: "state_agency", phone: "512-463-2207", desc: "TVC-funded statewide network of 30+ Veterans Treatment Courts (VTCs) in Texas — diversion programs combining judicial supervision, peer-mentor support, SUD/MH treatment, and VA benefits coordination for justice-involved veterans. Active VTCs in Bexar, Harris, Dallas, Travis, El Paso, Tarrant, Bell, Lubbock, and 20+ other counties." },
  { section: "SR", title: "Cornerstone Healing Center San Antonio", cat: "substance-recovery", sub: "Outpatient Recovery", city: "San Antonio", website_url: "https://www.discoverypoint.com/locations/san-antonio-tx/", source_name: "Discovery Point Retreat", source_type: "treatment_center", phone: "844-447-3239", desc: "San Antonio outpatient SUD and dual-diagnosis treatment program — IOP, PHP, MAT, individual and group counseling, and aftercare planning. TRICARE provider, most major insurance accepted; specialized military / first-responder track for JBSA-area veterans." },

  // INSURANCE LIFT (15 → 21+)
  { section: "INS", title: "AAFMAA — American Armed Forces Mutual Aid Association", cat: "insurance", sub: "Life Insurance", city: "Fort Sam Houston", website_url: "https://www.aafmaa.com/", source_name: "American Armed Forces Mutual Aid Association", source_type: "private_company", phone: "877-398-2263", desc: "Oldest non-profit, tax-exempt military life-insurance association in the U.S. (founded 1879). Term life, whole life, annuities, mortgage assistance (AAFMAA Mortgage Services), wealth management, and survivor assistance services exclusively for active, Guard, Reserve, retired, and veteran service members and families." },
  { section: "INS", title: "Navy Mutual Aid Association", cat: "insurance", sub: "Life Insurance", city: "Corpus Christi", website_url: "https://www.navymutual.org/", source_name: "Navy Mutual Aid Association", source_type: "private_company", phone: "800-628-6011", desc: "Oldest non-profit veterans service organization providing low-cost life insurance and survivor benefits exclusively for active, Reserve, retired, and veteran sea-service members (Navy, Marine Corps, Coast Guard, NOAA, USPHS) and their families. Free benefit counseling, education-loan service, and final-arrangements planning." },
  { section: "INS", title: "MOAA Life Insurance Plans", cat: "insurance", sub: "Life Insurance", city: "Austin", website_url: "https://www.moaa.org/content/benefits-and-discounts/insurance/", source_name: "Military Officers Association of America", source_type: "nonprofit", phone: "800-234-6622", desc: "MOAA-sponsored member life insurance plans (group term, level term, dependents, accident & health) underwritten by MetLife and Hartford for officers, warrants, and surviving spouses. Texas members serviced through the Texas Council of Chapters (Austin)." },
  { section: "INS", title: "VFW Insurance Programs", cat: "insurance", sub: "Life Insurance", city: "Austin", website_url: "https://www.vfwinsurance.com/", source_name: "Veterans of Foreign Wars", source_type: "nonprofit", phone: "800-821-2606", desc: "VFW-sponsored member benefit insurance programs (term life, accidental death, hospital income, cancer, dental, vision, Medicare supplement, and AD&D) underwritten by USAble Life and Mutual of Omaha for VFW members. Texas members enroll through the VFW Department of Texas Auxiliary." },
  { section: "INS", title: "Armed Forces Benefit Association (AFBA)", cat: "insurance", sub: "Life Insurance", city: "Fort Sam Houston", website_url: "https://www.afba.com/", source_name: "Armed Forces Benefit Association", source_type: "nonprofit", phone: "800-776-2322", desc: "Non-profit member-owned association providing low-cost group term life insurance, dependent life, AD&D, and the 5Star Bank financial services for active, Guard, Reserve, retired, and veteran service members, federal employees, and first responders. No war or aviation exclusion clauses." },

  // DISABLED-VETERANS LIFT (20 → 25)
  { section: "DV", title: "Brain Injury Association of America — Texas Affiliate", cat: "disabled-veterans", sub: "Healthcare & Rehabilitation", city: "Austin", website_url: "https://www.biausa.org/state-affiliates", source_name: "Brain Injury Association of America", source_type: "nonprofit", phone: "800-444-6443", desc: "Brain Injury Association affiliate serving Texas — National Brain Injury Information Center (NBIIC) helpline, brain-injury support-group locator, and resource navigation for the 144,000+ Texans (incl. veterans with TBI/PTSD comorbidity) living with a brain injury. Coordinates with Polytrauma Network Sites at South Texas VA and DeBakey VA." },
  { section: "DV", title: "Adaptive Training Foundation", cat: "disabled-veterans", sub: "Adaptive Recreation", city: "Carrollton", website_url: "https://adaptivetrainingfoundation.org/", source_name: "Adaptive Training Foundation", source_type: "nonprofit", phone: "972-803-6354", address: "2501 Crestside Dr, Carrollton, TX 75006", zip: "75006", desc: "Dallas-Fort Worth nonprofit operating the REDEFINE 9-week adaptive-fitness immersive program for veterans and civilians with physical disabilities. Coaching, strength training, mindfulness, nutrition, and community alongside other adaptive athletes; free to qualified veterans." },
  { section: "DV", title: "Adaptive Sports for Kids and Adults — Houston (TIRR Memorial Hermann)", cat: "disabled-veterans", sub: "Adaptive Recreation", city: "Houston", website_url: "https://memorialhermann.org/services/specialties/tirr-memorial-hermann/programs-and-services/adaptive-sports", source_name: "TIRR Memorial Hermann", source_type: "nonprofit", phone: "713-797-7180", desc: "TIRR Memorial Hermann's adaptive sports program in Houston offering wheelchair basketball, hand-cycling, sled hockey, wheelchair tennis, golf, hunting, and the annual TIRR Wheelchair Sports Camp. Open to veterans and civilians; sliding-fee scale; PVA Texas chapter partnership." },
  { section: "DV", title: "Texas State Independent Living Council (SILC)", cat: "disabled-veterans", sub: "Independent Living & Daily Support", city: "Austin", website_url: "https://www.txsilc.org/", source_name: "Texas State Independent Living Council", source_type: "nonprofit", phone: "512-371-7353", desc: "Federally-mandated state council coordinating Texas's 27-center Centers for Independent Living (CIL) network. Statewide directory and policy advocacy for the federal Independent Living program; supports disabled veterans transitioning out of institutional care into community-based living." },
  { section: "DV", title: "Achilles International Texas Freedom Team", cat: "disabled-veterans", sub: "Adaptive Recreation", city: "Austin", website_url: "https://www.achillesinternational.org/our-programs/freedom-team/", source_name: "Achilles International", source_type: "nonprofit", phone: "212-354-0300", desc: "Achilles International's Freedom Team chapters in Austin, Houston, Dallas, and San Antonio — adaptive endurance running and athletic training for wounded, injured, and ill veterans. Free participation; provides adaptive equipment, guided runs, and entry to major races (Houston, Austin, Dallas marathons)." },

  // FAMILY-SUPPORT LIFT (23 → 27)
  { section: "FAM", title: "TAPS — Tragedy Assistance Program for Survivors (Texas)", cat: "family-support", sub: "Survivor Benefits Support", city: "San Antonio", website_url: "https://www.taps.org/connect/local-events", source_name: "Tragedy Assistance Program for Survivors", source_type: "nonprofit", phone: "800-959-8277", desc: "National peer-based survivor-support nonprofit with active Texas community — Texas Survivor Care Team in Dallas, Houston, San Antonio, Austin, El Paso, and JBSA. Annual Texas Survivor Seminar, Good Grief Camps for children, peer mentors, casework assistance, and 24/7 National Military Survivor Helpline." },
  { section: "FAM", title: "Children of Fallen Patriots Foundation", cat: "family-support", sub: "Survivor Benefits Support", city: "Austin", website_url: "https://www.fallenpatriots.org/", source_name: "Children of Fallen Patriots Foundation", source_type: "nonprofit", phone: "888-744-1429", desc: "National scholarship and educational-counseling nonprofit providing college scholarships and educational support to surviving children of U.S. service members killed in active duty. Texas survivor-family caseload (largest by state) coordinated through dedicated Texas regional caseworker." },
  { section: "FAM", title: "Folds of Honor — Texas", cat: "family-support", sub: "Survivor Benefits Support", city: "Houston", website_url: "https://foldsofhonor.org/", source_name: "Folds of Honor", source_type: "nonprofit", phone: "918-274-4700", desc: "National educational scholarship nonprofit for spouses and dependents of fallen or disabled service members and (since 2022) first responders. Texas chapter coordinates Patriot Day events at Texas Motor Speedway, Cowboys Stadium, and Astros Park; Texas-resident scholarships awarded annually." },
  { section: "FAM", title: "Snowball Express — Gary Sinise Foundation", cat: "family-support", sub: "Gold Star Family Support", city: "Dallas", website_url: "https://www.garysinisefoundation.org/snowball-express/", source_name: "Gary Sinise Foundation", source_type: "nonprofit", phone: "888-708-3082", desc: "Gary Sinise Foundation's signature Gold Star children's program — annual all-expenses-paid 5-day Walt Disney World experience for 1,800+ children of fallen U.S. military heroes. Hosted from Dallas-Fort Worth area as the program's national gateway; year-round virtual community and regional reunion events." },

  // TRANSPORTATION LIFT (22 → 26)
  { section: "TR", title: "Brazos Transit District (The District)", cat: "transportation", sub: "Public Transit Assistance", city: "Bryan", website_url: "https://btd.org/", source_name: "Brazos Transit District", source_type: "transit_authority", phone: "979-778-0607", address: "1759 N Earl Rudder Fwy, Bryan, TX 77803", zip: "77803", desc: "16-county Central / East Texas rural transit district serving Brazos, Burleson, Grimes, Houston, Leon, Madison, Montgomery, Polk, Robertson, San Jacinto, Trinity, Tyler, Walker, Washington, Waller, and Liberty counties. Demand-response curb-to-curb, deviated fixed-route, and the Brazos Valley Connection commuter service to Houston; reduced fare for VA-rated disabled veterans." },
  { section: "TR", title: "East Texas Council of Governments — GoBus Transit", cat: "transportation", sub: "Public Transit Assistance", city: "Kilgore", website_url: "https://www.etcog.org/transportation/gobus", source_name: "East Texas Council of Governments", source_type: "transit_authority", phone: "903-984-8641", desc: "14-county East Texas rural transit district (GoBus / ETCOG Transit) serving Anderson, Camp, Cherokee, Gregg, Harrison, Henderson, Marion, Panola, Rains, Rusk, Smith, Upshur, Van Zandt, and Wood counties. Demand-response curb-to-curb; reduced fare for VA-rated disabled veterans; Tyler-Longview anchor service area." },
  { section: "TR", title: "Coastal Bend Council of Governments — Rural Transit", cat: "transportation", sub: "Public Transit Assistance", city: "Corpus Christi", website_url: "https://www.cbcog98.org/programs/rural-transportation/", source_name: "Coastal Bend Council of Governments", source_type: "transit_authority", phone: "361-883-5743", desc: "11-county Coastal Bend rural transit district serving Aransas, Bee, Brooks, Duval, Jim Wells, Kenedy, Kleberg, Live Oak, McMullen, Refugio, and San Patricio counties (excludes Nueces / Corpus served by RTA). Demand-response curb-to-curb; reduced fare for VA-rated disabled veterans." },
  { section: "TR", title: "South Plains Community Action Association — SPARTAN Transit", cat: "transportation", sub: "Public Transit Assistance", city: "Levelland", website_url: "https://spcaa.org/our-services/transportation-spartan/", source_name: "South Plains Community Action Association", source_type: "transit_authority", phone: "806-894-9590", desc: "9-county South Plains rural transit district (SPARTAN — South Plains Area Rural Transportation North) serving Bailey, Cochran, Dawson, Gaines, Hockley, Lamb, Terry, Yoakum, and rural Lubbock counties. Demand-response curb-to-curb plus deviated fixed-route in Levelland and Brownfield; serves SPC and rural Lubbock-area veterans." },
];

console.log(`[seed-tx-phase6-patch] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "TX", commit: COMMIT, scriptName: "TX Phase 6 Patch — Audit/Closeout Continuation",
  batchTag: "tx-p6-patch", allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: { SR: "Substance-recovery patch", INS: "Insurance patch", DV: "Disabled-veterans patch", FAM: "Family-support patch", TR: "Transportation patch" },
}).catch((e) => { console.error(e); process.exit(1); });
