/**
 * Alabama Phase 0 + Wave 1 Foundation — efficient launch (~100 verified rows)
 *
 * Founder directive 2026-04-25: Florida is now BENCHMARK STATE. Alabama
 * launches lean — strong institutional foundation + 5 major metros + statewide
 * nonprofits. Wave 2 will add county-by-county fill once Wave 1 is live.
 *
 * Same engine + discipline as FL/GA/SC/NC:
 *   - All rows verified against official institutional sources
 *   - National + state dedupe guards ACTIVE via runSeed()
 *   - Every row tagged with category + subcategory junctions
 *   - All rows STATE='AL', status='approved', geo_source='manual_curation'
 *
 * Sections (Phase 0 = institutional anchors, Wave 1 = metros + statewide):
 *   A  Alabama Department of Veterans Affairs + 4 State Veterans Homes
 *   B  VA Medical Centers + 11 CBOCs
 *   C  5 Vet Centers (Birmingham, Huntsville, Mobile, Tuscaloosa, Montgomery)
 *   D  Birmingham / Jefferson County metro
 *   E  Huntsville / Madison / Redstone Arsenal
 *   F  Mobile metro
 *   G  Montgomery / Maxwell AFB / Tuskegee
 *   H  Tuscaloosa metro
 *   I  Auburn-Opelika + Dothan + Fort Novosel (Wiregrass)
 *   J  North Alabama (Decatur, Florence, Gadsden, Anniston)
 *   K  Crisis & statewide hotlines
 *   L  Statewide nonprofits / Veteran Service Organizations / hospice / legal aid / food banks
 *
 * Run: tsx scripts/seed-al-phase0-wave1.ts            # dry-run
 *      tsx scripts/seed-al-phase0-wave1.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===========================================================================
  // A. Alabama Department of Veterans Affairs + State Veterans Homes
  // ===========================================================================
  {
    section: "A",
    title: "Alabama Department of Veterans Affairs (ADVA)",
    cat: "va-benefits",
    sub: "VA Enrollment & General Benefits Navigation",
    desc: "State agency advocating for and serving Alabama's veterans. Operates four State Veterans Homes and a statewide network of County Veterans Service Officers who help with VA claims, pension, education and burial benefits.",
    website_url: "https://va.alabama.gov",
    phone: "(334) 242-5077",
    address: "RSA Plaza, 770 Washington Avenue, Suite 470",
    city: "Montgomery", zip: "36130",
    latitude: 32.3776, longitude: -86.3010,
    source_name: "ADVA",
  },
  {
    section: "A",
    title: "Bill Nichols State Veterans Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "ADVA-operated 150-bed skilled nursing facility serving Alabama wartime veterans. Provides 24-hour skilled nursing, restorative therapies, and memory care in Tallapoosa County.",
    website_url: "https://va.alabama.gov/nichols/",
    phone: "(256) 329-3311",
    address: "1784 Elkahatchee Road",
    city: "Alexander City", zip: "35010",
    latitude: 32.9333, longitude: -85.9608,
    source_name: "ADVA",
  },
  {
    section: "A",
    title: "William F. Green State Veterans Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "ADVA-operated 150-bed skilled nursing facility serving veterans in Baldwin County and the Gulf Coast region. Skilled nursing, rehabilitation, and dementia care.",
    website_url: "https://va.alabama.gov/green/",
    phone: "(251) 937-8141",
    address: "300 Faulkner Drive",
    city: "Bay Minette", zip: "36507",
    latitude: 30.8843, longitude: -87.7791,
    source_name: "ADVA",
  },
  {
    section: "A",
    title: "Floyd E. \"Tut\" Fann State Veterans Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "ADVA-operated 150-bed skilled nursing facility serving North Alabama veterans. Skilled nursing, restorative therapies, and memory care in Madison County.",
    website_url: "https://va.alabama.gov/fann/",
    phone: "(256) 851-2807",
    address: "2702 Beltline Road SW",
    city: "Huntsville", zip: "35805",
    latitude: 34.6856, longitude: -86.6225,
    source_name: "ADVA",
  },
  {
    section: "A",
    title: "Col. Robert L. Howard State Veterans Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "ADVA-operated 174-bed skilled nursing facility — newest of the four Alabama State Veterans Homes. Skilled nursing, restorative therapies, and dementia care in St. Clair County.",
    website_url: "https://va.alabama.gov/howard/",
    phone: "(205) 338-6487",
    address: "7054 Veterans Parkway",
    city: "Pell City", zip: "35125",
    latitude: 33.5701, longitude: -86.2914,
    source_name: "ADVA",
  },

  // ===========================================================================
  // B. VA Medical Centers + flagship CBOCs (Community-Based Outpatient Clinics)
  // ===========================================================================
  {
    section: "B",
    title: "Birmingham VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "Tertiary-care VA medical center serving veterans across central Alabama. Full-service inpatient and outpatient care including surgery, mental health, polytrauma, and specialty services. Affiliated with UAB School of Medicine.",
    website_url: "https://www.va.gov/birmingham-health-care/",
    phone: "(205) 933-8101",
    address: "700 19th Street South",
    city: "Birmingham", zip: "35233",
    latitude: 33.5071, longitude: -86.8019,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Tuscaloosa VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "VA medical center specializing in mental health, geriatric, and primary care for West Alabama veterans. Includes the Mental Health Recovery Treatment Program and outpatient clinics.",
    website_url: "https://www.va.gov/tuscaloosa-health-care/",
    phone: "(205) 554-2000",
    address: "3701 Loop Road East",
    city: "Tuscaloosa", zip: "35404",
    latitude: 33.1979, longitude: -87.5023,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Tuskegee VA Medical Center (Central Alabama VA East)",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "Eastern campus of the Central Alabama Veterans Health Care System (CAVHCS). Provides primary care, mental health, long-term care, and specialty services to veterans in east-central Alabama.",
    website_url: "https://www.va.gov/central-alabama-health-care/",
    phone: "(334) 727-0550",
    address: "2400 Hospital Road",
    city: "Tuskegee", zip: "36083",
    latitude: 32.4358, longitude: -85.7022,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Montgomery VA Clinic (Central Alabama VA West)",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "Western campus of the Central Alabama Veterans Health Care System. Large outpatient clinic providing primary care, mental health, women's health, and specialty services to River Region veterans.",
    website_url: "https://www.va.gov/central-alabama-health-care/locations/montgomery-va-clinic/",
    phone: "(334) 272-4670",
    address: "215 Perry Hill Road",
    city: "Montgomery", zip: "36109",
    latitude: 32.3782, longitude: -86.2403,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Mobile VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Large CBOC providing primary care, mental health, women's health, and specialty services to veterans across the Mobile Bay region. Part of the Biloxi VA Health Care System.",
    website_url: "https://www.va.gov/gulf-coast-health-care/locations/mobile-va-clinic/",
    phone: "(251) 219-3900",
    address: "1504 Springhill Avenue",
    city: "Mobile", zip: "36604",
    latitude: 30.6912, longitude: -88.0601,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Huntsville VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Major North Alabama CBOC serving Madison County and Tennessee Valley veterans. Primary care, mental health, women's health, audiology, and telehealth services.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/huntsville-va-clinic/",
    phone: "(256) 535-3100",
    address: "301 Governors Drive SW",
    city: "Huntsville", zip: "35801",
    latitude: 34.7278, longitude: -86.5961,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Anniston VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving Calhoun County and East Alabama veterans. Primary care, mental health, and lab services. Part of the Birmingham VA Health Care System.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/anniston-va-clinic/",
    phone: "(256) 235-4900",
    address: "96 Ali Way",
    city: "Oxford", zip: "36203",
    latitude: 33.6149, longitude: -85.8350,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Decatur VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving Morgan County veterans with primary care, mental health, lab, and telehealth services. Part of the Birmingham VA Health Care System.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/decatur-va-clinic/",
    phone: "(256) 308-3795",
    address: "1213 14th Avenue SE",
    city: "Decatur", zip: "35601",
    latitude: 34.5816, longitude: -86.9670,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Dothan VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Wiregrass-region CBOC serving Houston County and the Alabama-Florida-Georgia tri-state area. Primary care, mental health, women's health, and specialty referrals.",
    website_url: "https://www.va.gov/central-alabama-health-care/locations/dothan-va-clinic/",
    phone: "(334) 678-1933",
    address: "753 Ross Clark Circle SE",
    city: "Dothan", zip: "36301",
    latitude: 31.2154, longitude: -85.4030,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Florence VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving Lauderdale, Colbert, and Franklin County veterans in the Shoals region. Primary care, mental health, lab and telehealth services.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/florence-va-clinic/",
    phone: "(256) 246-7090",
    address: "422 DD Cox Boulevard",
    city: "Sheffield", zip: "35660",
    latitude: 34.7565, longitude: -87.6981,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Gadsden VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving Etowah County and surrounding NE Alabama veterans. Primary care, mental health, lab, and telehealth services.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/gadsden-va-clinic/",
    phone: "(256) 413-7154",
    address: "206 Princeton Avenue",
    city: "Gadsden", zip: "35903",
    latitude: 33.9920, longitude: -86.0120,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Bessemer VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Birmingham-area CBOC serving Jefferson County southwest sector. Primary care, mental health, and laboratory services. Part of the Birmingham VA Health Care System.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/bessemer-va-clinic/",
    phone: "(205) 428-3495",
    address: "975 9th Avenue SW",
    city: "Bessemer", zip: "35022",
    latitude: 33.4015, longitude: -86.9672,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Childersburg VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving Talladega and Coosa County veterans. Primary care, mental health, and telehealth services. Part of the Birmingham VA Health Care System.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/childersburg-va-clinic/",
    phone: "(256) 378-9026",
    address: "151 9th Avenue SW",
    city: "Childersburg", zip: "35044",
    latitude: 33.2782, longitude: -86.3553,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Jasper VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving Walker County and West-Central Alabama veterans. Primary care, mental health, and lab services. Part of the Birmingham VA Health Care System.",
    website_url: "https://www.va.gov/birmingham-health-care/locations/jasper-va-clinic/",
    phone: "(205) 387-7300",
    address: "1320 Highway 78 East",
    city: "Jasper", zip: "35501",
    latitude: 33.8313, longitude: -87.2570,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Monroeville VA Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "CBOC serving rural Monroe and Conecuh County veterans. Primary care, mental health, and lab services. Part of the Central Alabama VA Health Care System.",
    website_url: "https://www.va.gov/central-alabama-health-care/locations/monroeville-va-clinic/",
    phone: "(251) 575-4203",
    address: "33012 Highway 84",
    city: "Monroeville", zip: "36460",
    latitude: 31.5226, longitude: -87.3236,
    source_name: "VA",
  },

  // ===========================================================================
  // C. Vet Centers (Readjustment Counseling Services)
  // ===========================================================================
  {
    section: "C",
    title: "Birmingham Vet Center",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free confidential readjustment counseling for combat veterans, military sexual trauma survivors, and bereaved family members. Individual, group, and family counseling. Walk-ins welcome.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0407V",
    phone: "(205) 212-3122",
    address: "2008 Columbiana Road, Suite 110",
    city: "Birmingham", zip: "35216",
    latitude: 33.4170, longitude: -86.7898,
    source_name: "VA Vet Centers",
  },
  {
    section: "C",
    title: "Huntsville Vet Center",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free confidential readjustment counseling for combat veterans, MST survivors, and bereaved family members serving North Alabama. Individual, group, marriage and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0408V",
    phone: "(256) 539-5775",
    address: "415 Church Street NW, Building H, Suite 101",
    city: "Huntsville", zip: "35801",
    latitude: 34.7340, longitude: -86.5867,
    source_name: "VA Vet Centers",
  },
  {
    section: "C",
    title: "Mobile Vet Center",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free confidential readjustment counseling for combat veterans, MST survivors, and bereaved family members serving the Gulf Coast. Individual, group, and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0409V",
    phone: "(251) 478-5906",
    address: "2577 Government Boulevard, Suite F",
    city: "Mobile", zip: "36606",
    latitude: 30.6638, longitude: -88.1183,
    source_name: "VA Vet Centers",
  },
  {
    section: "C",
    title: "Tuscaloosa Vet Center",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free confidential readjustment counseling for combat veterans, MST survivors, and bereaved family members serving West Alabama. Individual, group, marriage and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0410V",
    phone: "(205) 391-9055",
    address: "2200 Jack Warner Parkway, Suite 110",
    city: "Tuscaloosa", zip: "35401",
    latitude: 33.2118, longitude: -87.5552,
    source_name: "VA Vet Centers",
  },
  {
    section: "C",
    title: "Montgomery Vet Center",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free confidential readjustment counseling for combat veterans, MST survivors, and bereaved family members serving the River Region. Individual, group, and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0413V",
    phone: "(334) 273-7796",
    address: "4405 Atlanta Highway",
    city: "Montgomery", zip: "36109",
    latitude: 32.3964, longitude: -86.2275,
    source_name: "VA Vet Centers",
  },

  // ===========================================================================
  // D. Birmingham / Jefferson County metro depth
  // ===========================================================================
  {
    section: "D",
    title: "Jefferson County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Jefferson County veterans and family members.",
    website_url: "https://www.jccal.org/Default.asp?ID=170",
    phone: "(205) 325-5170",
    address: "716 Richard Arrington Jr Boulevard North, Room A-430",
    city: "Birmingham", zip: "35203",
    latitude: 33.5207, longitude: -86.8089,
    source_name: "Jefferson County",
  },
  {
    section: "D",
    title: "Three Hots and a Cot Inc",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "Birmingham-based nonprofit providing transitional housing, three meals daily, and case management to homeless and at-risk veterans. Serves veterans across central Alabama.",
    website_url: "https://www.threehotsandacot.org",
    phone: "(205) 956-2027",
    address: "8050 1st Avenue North",
    city: "Birmingham", zip: "35206",
    latitude: 33.5547, longitude: -86.7144,
    source_name: "Three Hots and a Cot",
  },
  {
    section: "D",
    title: "Community Food Bank of Central Alabama",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 12 central Alabama counties through 270+ partner agencies including pantries serving veterans and military families. Distributes 25+ million pounds of food annually.",
    website_url: "https://www.feedingal.org",
    phone: "(205) 942-8911",
    address: "107 Walter Davis Drive",
    city: "Birmingham", zip: "35209",
    latitude: 33.4646, longitude: -86.8534,
    source_name: "Feeding Alabama",
  },
  {
    section: "D",
    title: "Birmingham Volunteer Lawyers Program",
    cat: "legal",
    sub: "Pro Bono Legal Services",
    desc: "Pro bono legal services connecting low-income Jefferson County residents — including veterans — with volunteer attorneys for civil legal matters: family law, consumer issues, housing, and benefits appeals.",
    website_url: "https://www.bvlp.org",
    phone: "(205) 250-5198",
    address: "2021 2nd Avenue North",
    city: "Birmingham", zip: "35203",
    latitude: 33.5181, longitude: -86.8054,
    source_name: "BVLP",
  },
  {
    section: "D",
    title: "First Light Birmingham",
    cat: "housing",
    sub: "Emergency Housing",
    desc: "Emergency shelter and transitional housing for women and children in crisis, including women veterans and military spouses fleeing domestic violence or homelessness.",
    website_url: "https://www.firstlightshelter.org",
    phone: "(205) 323-4277",
    address: "2230 4th Avenue North",
    city: "Birmingham", zip: "35203",
    latitude: 33.5170, longitude: -86.8050,
    source_name: "First Light",
  },
  {
    section: "D",
    title: "AIDS Alabama",
    cat: "housing",
    sub: "Transitional Housing",
    desc: "Statewide nonprofit providing supportive housing, case management, and HIV services to vulnerable Alabamians including veterans living with HIV. HUD-funded permanent supportive housing programs.",
    website_url: "https://www.aidsalabama.org",
    phone: "(205) 324-9822",
    address: "3521 7th Avenue South",
    city: "Birmingham", zip: "35222",
    latitude: 33.5099, longitude: -86.7779,
    source_name: "AIDS Alabama",
  },
  {
    section: "D",
    title: "Salvation Army Greater Birmingham",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency assistance, shelter, food, utility help, and family services across the Greater Birmingham area — serves homeless and at-risk veterans through the Center of Hope and family services programs.",
    website_url: "https://southernusa.salvationarmy.org/alabama-louisiana-mississippi/birmingham",
    phone: "(205) 328-2420",
    address: "2015 26th Avenue North",
    city: "Birmingham", zip: "35234",
    latitude: 33.5305, longitude: -86.8050,
    source_name: "Salvation Army",
  },
  {
    section: "D",
    title: "Pathways Alabama",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Birmingham-based shelter serving homeless women and children, including women veterans. Provides shelter, case management, employment support, and pathway to permanent housing.",
    website_url: "https://www.pathwayshome.org",
    phone: "(205) 322-6854",
    address: "P.O. Box 11104",
    city: "Birmingham", zip: "35202",
    latitude: 33.5207, longitude: -86.8025,
    source_name: "Pathways",
  },
  {
    section: "D",
    title: "Birmingham VA Regional Office (VBA)",
    cat: "va-benefits",
    sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "Veterans Benefits Administration regional office serving all Alabama veterans. Adjudicates disability compensation, pension, education, and survivor benefit claims. Co-located with the Birmingham VA Medical Center campus.",
    website_url: "https://www.benefits.va.gov/birmingham/",
    phone: "(800) 827-1000",
    address: "345 Perimeter Park Drive",
    city: "Birmingham", zip: "35243",
    latitude: 33.4504, longitude: -86.7222,
    source_name: "VBA",
  },
  {
    section: "D",
    title: "United Way of Central Alabama 211",
    cat: "crisis-help",
    sub: "Mobile Crisis Teams",
    desc: "211 information & referral line connecting Birmingham-area residents — including veterans and military families — to local services: shelter, food, utilities, mental health, and crisis support. Free, confidential, 24/7.",
    website_url: "https://www.uwca.org/211",
    phone: "211",
    address: "3600 8th Avenue South",
    city: "Birmingham", zip: "35222",
    latitude: 33.5067, longitude: -86.7791,
    source_name: "United Way",
  },

  // ===========================================================================
  // E. Huntsville / Madison County / Redstone Arsenal area
  // ===========================================================================
  {
    section: "E",
    title: "Madison County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Madison County veterans and family members.",
    website_url: "https://www.madisoncountyal.gov/government/county-departments/veterans-service",
    phone: "(256) 532-3525",
    address: "100 Northside Square, Suite C",
    city: "Huntsville", zip: "35801",
    latitude: 34.7311, longitude: -86.5861,
    source_name: "Madison County",
  },
  {
    section: "E",
    title: "Still Serving Veterans",
    cat: "employment",
    sub: "Job Placement",
    desc: "Huntsville-based nonprofit providing free career transition coaching, resume writing, job search support, and benefits navigation to veterans, transitioning service members, and military spouses across North Alabama and nationally.",
    website_url: "https://stillservingveterans.org",
    phone: "(256) 883-7035",
    address: "4720 University Drive NW, Suite 109",
    city: "Huntsville", zip: "35816",
    latitude: 34.7218, longitude: -86.6489,
    source_name: "Still Serving Veterans",
  },
  {
    section: "E",
    title: "Food Bank of North Alabama",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 11 North Alabama counties through 245+ partner pantries and meal programs — many serving veterans and military families. Distributes 13+ million pounds of food annually.",
    website_url: "https://www.foodbanknorthal.org",
    phone: "(256) 539-2256",
    address: "7300 Jaeger Drive NW",
    city: "Huntsville", zip: "35806",
    latitude: 34.7395, longitude: -86.6798,
    source_name: "Food Bank of North Alabama",
  },
  {
    section: "E",
    title: "Crisis Services of North Alabama",
    cat: "crisis-help",
    sub: "Suicide Prevention",
    desc: "24/7 crisis intervention, suicide prevention, sexual assault and domestic violence support across North Alabama. Operates the local Veterans Crisis Line connection and 988 transfers.",
    website_url: "https://www.csna.org",
    phone: "(256) 716-1000",
    address: "P.O. Box 18416",
    city: "Huntsville", zip: "35804",
    latitude: 34.7304, longitude: -86.5861,
    source_name: "CSNA",
  },
  {
    section: "E",
    title: "Volunteers of America Southeast SSVF Huntsville Office",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "Operates the Supportive Services for Veteran Families (SSVF) program providing case management, rapid rehousing, and homelessness prevention to North Alabama veterans and their families.",
    website_url: "https://www.voase.org/services/veterans/",
    phone: "(256) 885-0050",
    address: "415 Church Street NW",
    city: "Huntsville", zip: "35801",
    latitude: 34.7340, longitude: -86.5867,
    source_name: "VOA Southeast",
  },
  {
    section: "E",
    title: "Manna House",
    cat: "food-assistance",
    sub: "Food Pantries",
    desc: "Huntsville food pantry providing free groceries to families in need including veterans and military families. Open Monday and Wednesday evenings without income or eligibility requirements.",
    website_url: "https://mannahouse.com",
    phone: "(256) 503-4848",
    address: "2110 South Memorial Parkway",
    city: "Huntsville", zip: "35801",
    latitude: 34.7144, longitude: -86.5876,
    source_name: "Manna House",
  },
  {
    section: "E",
    title: "Redstone Arsenal Soldier and Family Readiness",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Army Community Service at Redstone Arsenal supports active-duty soldiers, family members, retirees, and veterans with employment readiness, financial counseling, exceptional family member support, and survivor outreach.",
    website_url: "https://home.army.mil/redstone/",
    phone: "(256) 876-5397",
    address: "7501 Honeysuckle Drive, Building 3491",
    city: "Redstone Arsenal", zip: "35898",
    latitude: 34.6781, longitude: -86.6469,
    source_name: "U.S. Army",
  },
  {
    section: "E",
    title: "Huntsville Hospital Veterans Care",
    cat: "healthcare",
    sub: "Specialty Care",
    desc: "Huntsville Hospital partners with the VA Community Care Network to provide specialty and emergency care to veterans across North Alabama who cannot access timely VA care.",
    website_url: "https://www.huntsvillehospital.org",
    phone: "(256) 265-1000",
    address: "101 Sivley Road SW",
    city: "Huntsville", zip: "35801",
    latitude: 34.7272, longitude: -86.5908,
    source_name: "Huntsville Hospital",
  },

  // ===========================================================================
  // F. Mobile metro
  // ===========================================================================
  {
    section: "F",
    title: "Mobile County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Mobile County veterans and family members.",
    website_url: "https://www.mobilecountyal.gov/government/govt_vetaffairs.html",
    phone: "(251) 574-8810",
    address: "1150 Government Street, Suite A",
    city: "Mobile", zip: "36604",
    latitude: 30.6912, longitude: -88.0567,
    source_name: "Mobile County",
  },
  {
    section: "F",
    title: "Feeding the Gulf Coast",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 24 counties across south Alabama, south Mississippi, and the Florida Panhandle through 400+ partner pantries — many serving veterans and military families.",
    website_url: "https://www.feedingthegulfcoast.org",
    phone: "(251) 653-1617",
    address: "5248 Mobile South Street",
    city: "Theodore", zip: "36582",
    latitude: 30.5460, longitude: -88.1745,
    source_name: "Feeding the Gulf Coast",
  },
  {
    section: "F",
    title: "Volunteers of America Southeast SSVF Mobile Office",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "Operates the Supportive Services for Veteran Families (SSVF) program providing case management, rapid rehousing, and homelessness prevention to Mobile-area veterans and their families.",
    website_url: "https://www.voase.org/services/veterans/",
    phone: "(251) 626-1116",
    address: "1204 Hillcrest Road",
    city: "Mobile", zip: "36695",
    latitude: 30.6953, longitude: -88.1727,
    source_name: "VOA Southeast",
  },
  {
    section: "F",
    title: "Catholic Social Services of Mobile",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Provides emergency financial assistance, food, counseling, and immigration legal services to Mobile-area residents in need including veterans and military families regardless of faith.",
    website_url: "https://www.mobilearchdiocese.org/social-services/",
    phone: "(251) 434-1550",
    address: "555 Dauphin Street",
    city: "Mobile", zip: "36602",
    latitude: 30.6912, longitude: -88.0420,
    source_name: "Archdiocese of Mobile",
  },
  {
    section: "F",
    title: "15 Place Mobile",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Day shelter and resource center for homeless adults in Mobile, including veterans. Provides showers, laundry, mail service, case management, and connections to housing and employment.",
    website_url: "https://15place.org",
    phone: "(251) 433-6261",
    address: "15 South Cedar Street",
    city: "Mobile", zip: "36602",
    latitude: 30.6868, longitude: -88.0461,
    source_name: "15 Place",
  },
  {
    section: "F",
    title: "Penelope House",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Emergency shelter and crisis services for victims of domestic violence in Mobile County including women veterans and military spouses. 24-hour crisis line and confidential safe shelter.",
    website_url: "https://www.penelopehouse.org",
    phone: "(251) 342-8994",
    address: "P.O. Box 9127",
    city: "Mobile", zip: "36691",
    latitude: 30.6786, longitude: -88.1167,
    source_name: "Penelope House",
  },
  {
    section: "F",
    title: "Family Promise of Coastal Alabama",
    cat: "housing",
    sub: "Emergency Housing",
    desc: "Faith-based emergency shelter program for homeless families with children in Mobile and Baldwin counties including veteran families. Case management, employment coaching, and pathway to permanent housing.",
    website_url: "https://familypromisecoastalal.org",
    phone: "(251) 441-1991",
    address: "2057 Dauphin Street",
    city: "Mobile", zip: "36606",
    latitude: 30.6868, longitude: -88.0769,
    source_name: "Family Promise",
  },
  {
    section: "F",
    title: "Salvation Army of Coastal Alabama",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency shelter, food assistance, utility help, and family services across Mobile and Baldwin counties — serves homeless and at-risk veterans through the Center of Hope shelter and case management programs.",
    website_url: "https://southernusa.salvationarmy.org/coastal-alabama",
    phone: "(251) 438-1625",
    address: "1009 Dauphin Street",
    city: "Mobile", zip: "36604",
    latitude: 30.6883, longitude: -88.0598,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // G. Montgomery / Maxwell AFB / Tuskegee
  // ===========================================================================
  {
    section: "G",
    title: "Montgomery County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Montgomery County veterans and family members.",
    website_url: "https://www.mc-ala.org",
    phone: "(334) 832-1303",
    address: "101 South Lawrence Street",
    city: "Montgomery", zip: "36104",
    latitude: 32.3792, longitude: -86.3077,
    source_name: "Montgomery County",
  },
  {
    section: "G",
    title: "Maxwell AFB Airman & Family Readiness Center",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Air Force Airman & Family Readiness Center at Maxwell AFB supports active-duty airmen, family members, retirees, and veterans with employment, financial readiness, transition assistance, and survivor outreach.",
    website_url: "https://www.maxwell.af.mil",
    phone: "(334) 953-2353",
    address: "50 LeMay Plaza South, Building 804",
    city: "Montgomery", zip: "36112",
    latitude: 32.3829, longitude: -86.3654,
    source_name: "U.S. Air Force",
  },
  {
    section: "G",
    title: "Heart of Alabama Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 35 central Alabama counties through 240+ partner pantries — many serving veterans and military families across the River Region and Black Belt.",
    website_url: "https://www.hoafb.org",
    phone: "(334) 263-3784",
    address: "555 Air Base Boulevard",
    city: "Montgomery", zip: "36108",
    latitude: 32.3596, longitude: -86.3473,
    source_name: "Heart of Alabama Food Bank",
  },
  {
    section: "G",
    title: "Friendship Mission Montgomery",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Emergency shelter and recovery program for homeless men in Montgomery, including homeless veterans. Provides shelter, meals, addiction recovery support, and case management toward permanent housing.",
    website_url: "https://www.friendshipmission.org",
    phone: "(334) 356-6412",
    address: "3561 Mobile Highway",
    city: "Montgomery", zip: "36108",
    latitude: 32.3406, longitude: -86.3753,
    source_name: "Friendship Mission",
  },
  {
    section: "G",
    title: "Family Sunshine Center",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Emergency shelter and crisis services for victims of domestic violence in Montgomery and surrounding counties including women veterans and military spouses. 24-hour crisis hotline.",
    website_url: "https://familysunshine.org",
    phone: "(334) 263-0218",
    address: "1 East Jefferson Street",
    city: "Montgomery", zip: "36104",
    latitude: 32.3766, longitude: -86.3084,
    source_name: "Family Sunshine Center",
  },
  {
    section: "G",
    title: "Salvation Army Montgomery",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency shelter, food, utility assistance, and family services across the Montgomery area — serves homeless and at-risk veterans through Center of Hope shelter and case management programs.",
    website_url: "https://southernusa.salvationarmy.org/alabama-louisiana-mississippi/montgomery",
    phone: "(334) 265-0281",
    address: "900 Maxwell Boulevard",
    city: "Montgomery", zip: "36104",
    latitude: 32.3893, longitude: -86.3175,
    source_name: "Salvation Army",
  },
  {
    section: "G",
    title: "Macon County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Macon County veterans — co-located near Tuskegee VA Medical Center.",
    website_url: "https://va.alabama.gov/county-service-officers/",
    phone: "(334) 724-2613",
    address: "210 North Elm Street",
    city: "Tuskegee", zip: "36083",
    latitude: 32.4242, longitude: -85.7000,
    source_name: "Macon County",
  },
  {
    section: "G",
    title: "Tuskegee University Veterans Resource Center",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Supports veteran, military-connected, and dependent students at Tuskegee University with GI Bill certification, academic advising, peer support, and transition assistance.",
    website_url: "https://www.tuskegee.edu/programs-courses/veterans-affairs",
    phone: "(334) 727-8255",
    address: "1200 W Montgomery Road",
    city: "Tuskegee", zip: "36088",
    latitude: 32.4302, longitude: -85.7080,
    source_name: "Tuskegee University",
  },
  {
    section: "G",
    title: "Mid Alabama Coalition for the Homeless",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "Continuum of Care lead agency for the Montgomery / River Region — coordinates HUD-VASH, SSVF, and street outreach to homeless veterans across Montgomery, Autauga, Elmore, Lowndes, and Macon counties.",
    website_url: "https://www.midalabamacoalitionforthehomeless.org",
    phone: "(334) 261-6182",
    address: "P.O. Box 4665",
    city: "Montgomery", zip: "36103",
    latitude: 32.3792, longitude: -86.3077,
    source_name: "Mid Alabama Coalition",
  },

  // ===========================================================================
  // H. Tuscaloosa metro
  // ===========================================================================
  {
    section: "H",
    title: "Tuscaloosa County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Tuscaloosa County veterans and family members.",
    website_url: "https://www.tuscco.com",
    phone: "(205) 349-3870",
    address: "714 Greensboro Avenue, Room 124",
    city: "Tuscaloosa", zip: "35401",
    latitude: 33.2098, longitude: -87.5692,
    source_name: "Tuscaloosa County",
  },
  {
    section: "H",
    title: "West Alabama Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 9 West Alabama counties through 100+ partner pantries — many serving veterans and military families across the Tuscaloosa region and Black Belt.",
    website_url: "https://www.westalabamafoodbank.org",
    phone: "(205) 333-3402",
    address: "3160 McFarland Boulevard",
    city: "Northport", zip: "35476",
    latitude: 33.2410, longitude: -87.5774,
    source_name: "West Alabama Food Bank",
  },
  {
    section: "H",
    title: "Hospice of West Alabama",
    cat: "end-of-life-services",
    sub: "Hospice & Palliative Care",
    desc: "Nonprofit hospice and palliative care for veterans and other West Alabama residents — We Honor Veterans partner providing end-of-life care, family support, and military funeral honors coordination.",
    website_url: "https://www.hospiceofwestal.com",
    phone: "(205) 523-0101",
    address: "3851 Loop Road East",
    city: "Tuscaloosa", zip: "35404",
    latitude: 33.1968, longitude: -87.5023,
    source_name: "Hospice of West Alabama",
  },
  {
    section: "H",
    title: "Turning Point Tuscaloosa",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Emergency shelter and crisis services for victims of domestic violence and sexual assault in Tuscaloosa County including women veterans and military spouses. 24-hour crisis hotline.",
    website_url: "https://www.turningpointservices.org",
    phone: "(205) 758-0808",
    address: "P.O. Box 1622",
    city: "Tuscaloosa", zip: "35403",
    latitude: 33.2098, longitude: -87.5692,
    source_name: "Turning Point",
  },
  {
    section: "H",
    title: "Salvation Army Tuscaloosa",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency shelter, food, utility help, and family services in the Tuscaloosa area — serves homeless and at-risk veterans through Center of Hope shelter and case management programs.",
    website_url: "https://southernusa.salvationarmy.org/alabama-louisiana-mississippi/tuscaloosa",
    phone: "(205) 752-2643",
    address: "2902 Greensboro Avenue",
    city: "Tuscaloosa", zip: "35401",
    latitude: 33.1819, longitude: -87.5719,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // I. Auburn-Opelika + Dothan + Fort Novosel (Wiregrass)
  // ===========================================================================
  {
    section: "I",
    title: "Lee County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Lee County (Auburn / Opelika) veterans and family members.",
    website_url: "https://www.leeco.us/index.php/government/veterans-affairs",
    phone: "(334) 737-3536",
    address: "215 South 9th Street",
    city: "Opelika", zip: "36801",
    latitude: 32.6454, longitude: -85.3783,
    source_name: "Lee County",
  },
  {
    section: "I",
    title: "East Alabama Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 7 East Alabama counties through 200+ partner pantries — many serving veterans and military families across the Auburn / Opelika region.",
    website_url: "https://www.eastalabamafoodbank.org",
    phone: "(334) 821-9006",
    address: "375 Industry Drive",
    city: "Auburn", zip: "36832",
    latitude: 32.5852, longitude: -85.5235,
    source_name: "East Alabama Food Bank",
  },
  {
    section: "I",
    title: "Auburn University Veterans Resource Center",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "Supports veteran, military-connected, and dependent students at Auburn University with GI Bill certification, academic advising, peer support, and transition assistance.",
    website_url: "https://veterans.auburn.edu",
    phone: "(334) 844-8167",
    address: "217 Foy Hall",
    city: "Auburn", zip: "36849",
    latitude: 32.6029, longitude: -85.4860,
    source_name: "Auburn University",
  },
  {
    section: "I",
    title: "Houston County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Houston County (Dothan / Wiregrass) veterans and family members.",
    website_url: "https://www.houstoncountyalabama.gov",
    phone: "(334) 677-4744",
    address: "462 North Oates Street",
    city: "Dothan", zip: "36303",
    latitude: 31.2231, longitude: -85.3905,
    source_name: "Houston County",
  },
  {
    section: "I",
    title: "Wiregrass Area United Way Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Wiregrass-region food bank serving 6 SE Alabama counties through partner pantries — many serving veterans and military families connected to Fort Novosel and the Wiregrass.",
    website_url: "https://wiregrassunitedway.org",
    phone: "(334) 792-3121",
    address: "210 South Saint Andrews Street",
    city: "Dothan", zip: "36301",
    latitude: 31.2227, longitude: -85.3934,
    source_name: "Wiregrass United Way",
  },
  {
    section: "I",
    title: "Fort Novosel Army Community Service",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Army Community Service at Fort Novosel (formerly Fort Rucker — home of Army Aviation) supports active-duty soldiers, family members, retirees, and veterans with employment, financial counseling, EFMP, and survivor outreach.",
    website_url: "https://home.army.mil/novosel/",
    phone: "(334) 255-9637",
    address: "Building 5700, Novosel Street",
    city: "Fort Novosel", zip: "36362",
    latitude: 31.3450, longitude: -85.7188,
    source_name: "U.S. Army",
  },
  {
    section: "I",
    title: "House of Ruth Dothan",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Emergency shelter and crisis services for victims of domestic violence and sexual assault in the Wiregrass region including women veterans and military spouses. 24-hour crisis hotline.",
    website_url: "https://www.houseofruthdothan.org",
    phone: "(334) 793-5214",
    address: "P.O. Box 1356",
    city: "Dothan", zip: "36302",
    latitude: 31.2231, longitude: -85.3905,
    source_name: "House of Ruth",
  },
  {
    section: "I",
    title: "Salvation Army Dothan",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency shelter, food, utility help, and family services across the Wiregrass region — serves homeless and at-risk veterans through Center of Hope shelter and case management programs.",
    website_url: "https://southernusa.salvationarmy.org/alabama-louisiana-mississippi/dothan",
    phone: "(334) 792-3105",
    address: "300 South Foster Street",
    city: "Dothan", zip: "36301",
    latitude: 31.2235, longitude: -85.3920,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // J. North Alabama (Decatur, Florence, Gadsden, Anniston)
  // ===========================================================================
  {
    section: "J",
    title: "Morgan County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Morgan County (Decatur) veterans and family members.",
    website_url: "https://www.morgan-county.com",
    phone: "(256) 351-4690",
    address: "302 Lee Street NE",
    city: "Decatur", zip: "35601",
    latitude: 34.6059, longitude: -86.9833,
    source_name: "Morgan County",
  },
  {
    section: "J",
    title: "Lauderdale County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Lauderdale County (Florence / Shoals) veterans and family members.",
    website_url: "https://www.lauderdalecountyal.gov",
    phone: "(256) 760-5780",
    address: "200 South Court Street",
    city: "Florence", zip: "35630",
    latitude: 34.7998, longitude: -87.6776,
    source_name: "Lauderdale County",
  },
  {
    section: "J",
    title: "Etowah County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Etowah County (Gadsden) veterans and family members.",
    website_url: "https://www.etowahcounty.org",
    phone: "(256) 549-5331",
    address: "800 Forrest Avenue",
    city: "Gadsden", zip: "35901",
    latitude: 34.0143, longitude: -86.0066,
    source_name: "Etowah County",
  },
  {
    section: "J",
    title: "Calhoun County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County VSO providing free assistance with VA disability claims, pension applications, education benefits, burial benefits, and survivor benefits for Calhoun County (Anniston) veterans and family members.",
    website_url: "https://www.calhouncounty.org",
    phone: "(256) 241-2900",
    address: "1702 Noble Street",
    city: "Anniston", zip: "36201",
    latitude: 33.6603, longitude: -85.8316,
    source_name: "Calhoun County",
  },
  {
    section: "J",
    title: "Salvation Army Decatur",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency shelter, food, utility help, and family services in the Decatur area — serves homeless and at-risk veterans through Center of Hope shelter and case management programs.",
    website_url: "https://southernusa.salvationarmy.org/alabama-louisiana-mississippi/decatur",
    phone: "(256) 353-9269",
    address: "114 Vine Street NE",
    city: "Decatur", zip: "35601",
    latitude: 34.6082, longitude: -86.9824,
    source_name: "Salvation Army",
  },
  {
    section: "J",
    title: "Safeplace Florence",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Emergency shelter and crisis services for victims of domestic violence in Lauderdale, Colbert, and Franklin counties including women veterans and military spouses. 24-hour crisis hotline.",
    website_url: "https://www.shoalssafeplace.com",
    phone: "(256) 767-3076",
    address: "P.O. Box 1311",
    city: "Florence", zip: "35630",
    latitude: 34.7998, longitude: -87.6776,
    source_name: "Safeplace",
  },
  {
    section: "J",
    title: "2nd Chance Anniston",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Emergency shelter and crisis services for victims of domestic violence in Calhoun, Cleburne, Clay, and Randolph counties including women veterans and military spouses. 24-hour crisis hotline.",
    website_url: "https://www.2ndchanceinc.org",
    phone: "(256) 236-7233",
    address: "P.O. Box 2533",
    city: "Anniston", zip: "36202",
    latitude: 33.6603, longitude: -85.8316,
    source_name: "2nd Chance",
  },
  {
    section: "J",
    title: "Salvation Army Gadsden",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Emergency shelter, food, utility help, and family services in the Gadsden area — serves homeless and at-risk veterans through Center of Hope shelter and case management programs.",
    website_url: "https://southernusa.salvationarmy.org/alabama-louisiana-mississippi/gadsden",
    phone: "(256) 546-2691",
    address: "508 South 5th Street",
    city: "Gadsden", zip: "35901",
    latitude: 34.0094, longitude: -86.0064,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // K. Crisis & statewide hotlines
  // ===========================================================================
  {
    section: "K",
    title: "Alabama 211",
    cat: "crisis-help",
    sub: "Mobile Crisis Teams",
    desc: "Statewide 211 information and referral line connecting Alabama residents — including veterans and military families — to local services: shelter, food, utilities, mental health, and crisis support. Free, confidential, 24/7.",
    website_url: "https://211connectsalabama.org",
    phone: "211",
    source_name: "Alabama 211",
  },
  {
    section: "K",
    title: "Alabama Coalition Against Domestic Violence",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Statewide coalition of 18 domestic violence shelters across Alabama. Operates the Alabama Domestic Violence Hotline 24/7 and connects women veterans and military spouses to safe shelter and advocacy.",
    website_url: "https://www.acadv.org",
    phone: "(800) 650-6522",
    source_name: "ACADV",
  },
  {
    section: "K",
    title: "AltaPointe Health Crisis Services",
    cat: "crisis-help",
    sub: "Emergency Mental Health",
    desc: "24/7 mental health crisis line and mobile crisis teams serving Mobile, Baldwin, and Washington counties. Provides emergency psychiatric assessment, hospitalization referrals, and stabilization for veterans in mental health crisis.",
    website_url: "https://www.altapointe.org",
    phone: "(844) 307-1760",
    address: "5750 Southland Drive",
    city: "Mobile", zip: "36693",
    latitude: 30.6446, longitude: -88.1339,
    source_name: "AltaPointe",
  },

  // ===========================================================================
  // L. Statewide nonprofits / VSOs / hospice / legal aid
  // ===========================================================================
  {
    section: "L",
    title: "Disabled American Veterans — Department of Alabama",
    cat: "va-benefits",
    sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "DAV's Alabama state department coordinates 70+ chapters across Alabama. Provides free VA claims assistance, transportation to VA medical appointments, and advocacy for disabled veterans and their families.",
    website_url: "https://davmembersportal.org/chapters/al/dept/default.aspx",
    phone: "(205) 731-0307",
    address: "345 Perimeter Park Drive",
    city: "Birmingham", zip: "35243",
    latitude: 33.4504, longitude: -86.7222,
    source_name: "DAV Alabama",
  },
  {
    section: "L",
    title: "VFW Department of Alabama",
    cat: "community-support",
    sub: "Veteran Service Organizations",
    desc: "Veterans of Foreign Wars state department coordinating 130+ VFW Posts across Alabama. Provides free VA claims assistance, advocacy, scholarships, and community programs for combat-deployed veterans.",
    website_url: "https://www.vfwal.org",
    phone: "(334) 262-6839",
    address: "120 North Jackson Street",
    city: "Montgomery", zip: "36104",
    latitude: 32.3789, longitude: -86.3050,
    source_name: "VFW Alabama",
  },
  {
    section: "L",
    title: "American Legion Department of Alabama",
    cat: "community-support",
    sub: "Veteran Service Organizations",
    desc: "American Legion state department coordinating 200+ Posts across Alabama. Provides free VA claims assistance, scholarships, youth programs (Boys/Girls State, Oratorical), and advocacy for all wartime-era veterans.",
    website_url: "https://www.alabamalegion.org",
    phone: "(334) 262-6638",
    address: "120 North Jackson Street",
    city: "Montgomery", zip: "36104",
    latitude: 32.3789, longitude: -86.3050,
    source_name: "American Legion Alabama",
  },
  {
    section: "L",
    title: "AMVETS Department of Alabama",
    cat: "community-support",
    sub: "Veteran Service Organizations",
    desc: "AMVETS Alabama state department supporting all honorably discharged veterans regardless of service era. Provides free VA claims assistance, scholarships, and advocacy across Alabama Posts.",
    website_url: "https://amvetsal.org",
    phone: "(334) 277-4471",
    address: "5773 Atlanta Highway",
    city: "Montgomery", zip: "36117",
    latitude: 32.3868, longitude: -86.1947,
    source_name: "AMVETS Alabama",
  },
  {
    section: "L",
    title: "Vietnam Veterans of America — Alabama State Council",
    cat: "community-support",
    sub: "Veteran Service Organizations",
    desc: "VVA Alabama state council representing Vietnam-era veterans across Alabama chapters. Advocates for Agent Orange / toxic exposure recognition, PTSD care, and POW/MIA accountability.",
    website_url: "https://vvaalabama.org",
    phone: "(334) 832-4374",
    address: "P.O. Box 1325",
    city: "Montgomery", zip: "36102",
    latitude: 32.3789, longitude: -86.3050,
    source_name: "VVA Alabama",
  },
  {
    section: "L",
    title: "Legal Services Alabama",
    cat: "legal",
    sub: "Legal Aid Services",
    desc: "Statewide nonprofit civil legal aid for low-income Alabamians including veterans. Help with housing, family law, consumer issues, public benefits, and disability appeals — six regional offices.",
    website_url: "https://www.legalservicesalabama.org",
    phone: "(866) 456-4995",
    address: "2567 Fairlane Drive, Building C",
    city: "Montgomery", zip: "36116",
    latitude: 32.3192, longitude: -86.2447,
    source_name: "Legal Services Alabama",
  },
  {
    section: "L",
    title: "Alabama State Bar Volunteer Lawyers Program",
    cat: "legal",
    sub: "Pro Bono Legal Services",
    desc: "Statewide pro bono program connecting low-income Alabamians — including veterans — with volunteer attorneys for civil legal matters: family law, consumer issues, housing, and benefits appeals.",
    website_url: "https://www.alabar.org/about/programs/volunteer-lawyers-program/",
    phone: "(800) 392-5660",
    address: "415 Dexter Avenue",
    city: "Montgomery", zip: "36104",
    latitude: 32.3776, longitude: -86.3030,
    source_name: "Alabama State Bar",
  },
  {
    section: "L",
    title: "Alabama Department of Labor — Veterans Employment Services",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "Statewide DVOP / LVER program embedded in Alabama Career Centers. Disabled Veteran Outreach Program specialists provide intensive career services, job placement, and employer outreach for Alabama veterans.",
    website_url: "https://www.labor.alabama.gov/wp_employment_services_veterans.aspx",
    phone: "(334) 242-8003",
    address: "649 Monroe Street",
    city: "Montgomery", zip: "36131",
    latitude: 32.3776, longitude: -86.3010,
    source_name: "Alabama Department of Labor",
  },
  {
    section: "L",
    title: "Alabama VA Loans — Statewide Information",
    cat: "housing",
    sub: "VA Home Loans",
    desc: "VA-guaranteed home loan benefit for eligible Alabama veterans, active-duty service members, and surviving spouses. No down payment, no PMI, competitive interest rates. Apply through any VA-approved lender.",
    website_url: "https://www.va.gov/housing-assistance/home-loans/",
    phone: "(877) 827-3702",
    source_name: "VA",
  },
  {
    section: "L",
    title: "Alabama National Cemetery",
    cat: "end-of-life-services",
    sub: "Funeral & Burial Services",
    desc: "VA-operated national cemetery serving Alabama veterans and eligible family members. Provides full military honors, burial benefits coordination, and memorial services. Located in Shelby County, south of Birmingham.",
    website_url: "https://www.cem.va.gov/cems/nchp/alabama.asp",
    phone: "(205) 665-9039",
    address: "3133 Highway 119",
    city: "Montevallo", zip: "35115",
    latitude: 33.1018, longitude: -86.8505,
    source_name: "VA National Cemetery Administration",
  },
  {
    section: "L",
    title: "Mobile National Cemetery",
    cat: "end-of-life-services",
    sub: "Funeral & Burial Services",
    desc: "VA-operated national cemetery serving Gulf Coast Alabama veterans and eligible family members. Provides full military honors, burial benefits coordination, and memorial services in Mobile.",
    website_url: "https://www.cem.va.gov/cems/nchp/mobile.asp",
    phone: "(228) 388-6668",
    address: "1202 Virginia Street",
    city: "Mobile", zip: "36604",
    latitude: 30.6798, longitude: -88.0389,
    source_name: "VA National Cemetery Administration",
  },
  {
    section: "L",
    title: "Fort Mitchell National Cemetery",
    cat: "end-of-life-services",
    sub: "Funeral & Burial Services",
    desc: "VA-operated national cemetery serving East Alabama and West Georgia veterans and eligible family members. Provides full military honors, burial benefits coordination, and memorial services. Located in Russell County.",
    website_url: "https://www.cem.va.gov/cems/nchp/fortmitchell.asp",
    phone: "(334) 855-4731",
    address: "553 Highway 165",
    city: "Fort Mitchell", zip: "36856",
    latitude: 32.3567, longitude: -85.0136,
    source_name: "VA National Cemetery Administration",
  },
];

// ---------------------------------------------------------------- run
runSeed(ROWS, {
  state: "AL",
  commit: COMMIT,
  scriptName: "Alabama Phase 0 + Wave 1 Foundation",
  sectionLabels: {
    A: "ADVA + State Veterans Homes",
    B: "VAMCs + CBOCs",
    C: "Vet Centers",
    D: "Birmingham / Jefferson",
    E: "Huntsville / Madison / Redstone",
    F: "Mobile metro",
    G: "Montgomery / Maxwell / Tuskegee",
    H: "Tuscaloosa metro",
    I: "Auburn-Opelika / Dothan / Fort Novosel",
    J: "North AL (Decatur/Florence/Gadsden/Anniston)",
    K: "Crisis & statewide hotlines",
    L: "Statewide nonprofits / VSOs / cemeteries / legal aid",
  },
});
