/**
 * OHIO REBUILD — PHASE 4: MAJOR CITY SATURATION
 * Florida SOP. 7 priority metros: CLE, CMH, CIN, DAY, TOL, AKR, YNG.
 * Veteran-first not veteran-only. URLs liveness-pre-verified.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== CLEVELAND (12) ==============
  { section: "CLE", title: "Greater Cleveland Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Cleveland", zip: "44115", website_url: "https://www.greaterclevelandfoodbank.org/", source_name: "Greater Cleveland Food Bank", source_type: "nonprofit", phone: "216-738-2265", address: "15500 S Waterloo Rd, Cleveland, OH 44110", desc: "Greater Cleveland Food Bank — largest hunger-relief org in NE OH; serves 6 counties (Cuyahoga/Ashtabula/Geauga/Lake/Richland/Ashland) via 1,000+ partner pantries/hot-meal sites; SNAP enrollment, mobile pantries, senior food box, Veteran-specific food drops at Cleveland VAMC events." },
  { section: "CLE", title: "Lutheran Metropolitan Ministry (Cleveland)", cat: "housing", sub: "Homeless Veteran Services", city: "Cleveland", zip: "44115", website_url: "https://www.lutheranmetro.org/", source_name: "Lutheran Metropolitan Ministry", source_type: "nonprofit", phone: "216-696-2715", address: "4515 Superior Ave E, Cleveland, OH 44103", desc: "Lutheran Metropolitan Ministry — major Cleveland homeless services provider; Men's Shelter (2100 Lakeside, 365-bed), Women's 2100 Center, Veteran Services Program (HUD-VASH partner with Cleveland VAMC), Workforce Solutions, food/clothing pantry." },
  { section: "CLE", title: "Joseph's Home (Cleveland)", cat: "housing", sub: "Transitional Housing", city: "Cleveland", zip: "44103", website_url: "https://josephshome.org/", source_name: "Joseph's Home", source_type: "nonprofit", phone: "216-685-1551", address: "2412 Community College Ave, Cleveland, OH 44115", desc: "Joseph's Home — Cleveland transitional housing for medically-vulnerable homeless men (incl. veterans); 24-month stays, on-site case management, medical support, employment readiness, healthcare connections to MetroHealth and Cleveland VAMC." },
  { section: "CLE", title: "May Dugan Center (Cleveland)", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cleveland", zip: "44113", website_url: "https://www.maydugancenter.org/", source_name: "May Dugan Center", source_type: "nonprofit", phone: "216-631-5800", address: "4115 Bridge Ave, Cleveland, OH 44113", desc: "May Dugan Center — Cleveland west-side multi-service center; food pantry, clothing closet, hot meals, behavioral health, Project HOPE for women, Senior Outreach, family advocacy, AmeriCorps; serves veterans and families in Ohio City/Detroit-Shoreway/Tremont." },
  { section: "CLE", title: "United Way of Greater Cleveland", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Cleveland", zip: "44115", website_url: "https://www.unitedwaycleveland.org/", source_name: "United Way of Greater Cleveland", source_type: "nonprofit", phone: "216-436-2100", address: "1331 Euclid Ave, Cleveland, OH 44115", desc: "United Way of Greater Cleveland — funds 100+ Cuyahoga partner agencies; 211 HelpLink (24/7 community resource referral), Veteran-services pipeline, Strategic Investments in housing/food/health/education, Volunteer United." },
  { section: "CLE", title: "Cleveland Public Library — Veterans Resource Center", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cleveland", zip: "44114", website_url: "https://www.clevelandlibrary.org/", source_name: "Cleveland Public Library", source_type: "public_university", phone: "216-623-2800", address: "325 Superior Ave, Cleveland, OH 44114", desc: "Cleveland Public Library — 27 branches across Cleveland with a dedicated Veterans Resource Center (Main Library); free internet/printers, VA forms, Ancestry/military records research, claims-filing computer kiosk, English-as-second-language and GED prep." },
  { section: "CLE", title: "Greater Cleveland Regional Transit Authority (RTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Cleveland", zip: "44113", website_url: "https://www.riderta.com/", source_name: "Greater Cleveland RTA", source_type: "public_university", phone: "216-621-9500", address: "1240 W 6th St, Cleveland, OH 44113", desc: "Greater Cleveland RTA — Cuyahoga County public transit; 4 rail lines + bus + Paratransit (door-to-door for ADA-eligible riders incl. service-disabled veterans); Veterans ride free with valid VA ID on RTA buses, Red Line, Green/Blue Lines on Veterans Day." },
  { section: "CLE", title: "Cuyahoga Metropolitan Housing Authority (CMHA)", cat: "housing", sub: "Rental Assistance", city: "Cleveland", zip: "44113", website_url: "https://www.cmha.net/", source_name: "Cuyahoga Metropolitan Housing Authority", source_type: "public_university", phone: "216-348-5000", address: "8120 Kinsman Rd, Cleveland, OH 44104", desc: "CMHA — public housing authority for Cuyahoga County; 10,000+ public housing units, Housing Choice Voucher (Section 8), HUD-VASH vouchers in partnership with Cleveland VAMC for homeless veterans, family self-sufficiency, homeownership program." },
  { section: "CLE", title: "Cuyahoga Land Bank", cat: "housing", sub: "Home Ownership Programs", city: "Cleveland", zip: "44113", website_url: "https://www.cuyahogalandbank.org/", source_name: "Cuyahoga County Land Reutilization Corp", source_type: "public_university", phone: "216-698-8853", address: "323 W Lakeside Ave Suite 160, Cleveland, OH 44113", desc: "Cuyahoga Land Bank — quasi-public land reutilization corp; rehabs vacant/abandoned properties, Deed-in-Escrow rehab program, side-yard sales, demolition; partners with Veterans Inc and Habitat for Humanity for veteran-prioritized homeownership." },
  { section: "CLE", title: "Goodwill of Greater Cleveland & East Central OH", cat: "employment", sub: "Vocational Rehabilitation", city: "Cleveland", zip: "44104", website_url: "https://goodwillgoodskills.org/", source_name: "Goodwill of Greater Cleveland", source_type: "nonprofit", phone: "216-431-7800", address: "2295 E 55th St, Cleveland, OH 44103", desc: "Goodwill Industries of Greater Cleveland & East Central Ohio — workforce-development nonprofit; job training, vocational rehab, supported employment, GED prep, retail-store paid training; veteran-focused career navigation in Cleveland/Akron/Canton/Youngstown." },
  { section: "CLE", title: "Honor Flight Cleveland", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cleveland", zip: "44115", website_url: "https://www.honorflightcleveland.org/", source_name: "Honor Flight Cleveland", source_type: "nonprofit", phone: "216-503-1322", address: "PO Box 18044, Cleveland, OH 44118", desc: "Honor Flight Cleveland — NE Ohio hub of Honor Flight Network; flies WWII, Korean, Vietnam, and terminally-ill veterans to Washington DC to visit war memorials at no cost to veteran; spring & fall flights from Cleveland Hopkins Airport." },
  { section: "CLE", title: "Cuyahoga Community College — Veterans Resource Center", cat: "education", sub: "Veteran Student Services", city: "Cleveland", zip: "44115", website_url: "https://www.tri-c.edu/veterans/", source_name: "Cuyahoga Community College (Tri-C)", source_type: "public_university", phone: "216-987-3193", address: "700 Carnegie Ave, Cleveland, OH 44115", desc: "Tri-C Veterans Services — dedicated Veterans Resource Centers at all 4 Tri-C campuses (Metro/East/West/Westshore); GI Bill certification, VA work-study, Yellow Ribbon, Veterans Upward Bound prep program, peer-mentoring, priority registration." },

  // ============== CINCINNATI (10) ==============
  { section: "CIN", title: "Shelterhouse Cincinnati", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Cincinnati", zip: "45202", website_url: "https://www.shelterhousecincy.org/", source_name: "Shelterhouse", source_type: "nonprofit", phone: "513-721-0643", address: "411 Gest St, Cincinnati, OH 45203", desc: "Shelterhouse — Cincinnati's largest homeless shelter (David & Rebecca Barron Center for Men 150 beds; Esther Marie Hatton Center for Women 60 beds); rapid rehousing, behavioral health, employment program; HUD-VASH partnership with Cincinnati VAMC." },
  { section: "CIN", title: "Freestore Foodbank", cat: "food-assistance", sub: "Food Banks", city: "Cincinnati", zip: "45202", website_url: "https://www.freestorefoodbank.org/", source_name: "Freestore Foodbank", source_type: "nonprofit", phone: "513-482-4500", address: "1141 Central Pkwy, Cincinnati, OH 45202", desc: "Freestore Foodbank — Greater Cincinnati & N Kentucky's largest hunger-relief org; serves 20-county region via 600+ partner agencies; Cincinnati Cooks (culinary job training), Customer Connection Center (food/utility aid), kids cafe, SNAP enrollment, veteran outreach." },
  { section: "CIN", title: "Legal Aid Society of Greater Cincinnati", cat: "legal", sub: "Legal Aid Services", city: "Cincinnati", zip: "45202", website_url: "https://www.lascinti.org/", source_name: "Legal Aid Society of Greater Cincinnati", source_type: "nonprofit", phone: "513-241-9400", address: "215 E 9th St Suite 200, Cincinnati, OH 45202", desc: "Legal Aid Society of Greater Cincinnati — civil legal aid for low-income residents of Hamilton/Brown/Butler/Clermont/Clinton/Highland/Warren counties; Veterans Legal Clinic at Cincinnati VAMC, eviction defense, public benefits, family law, consumer/debt." },
  { section: "CIN", title: "Cincinnati Metro / SORTA", cat: "transportation", sub: "Public Transit Assistance", city: "Cincinnati", zip: "45202", website_url: "https://www.go-metro.com/", source_name: "Southwest Ohio Regional Transit Authority", source_type: "public_university", phone: "513-621-4455", address: "525 Vine St Suite 1200, Cincinnati, OH 45202", desc: "Cincinnati Metro (SORTA) — Hamilton County public transit; 46 bus routes + Access paratransit (door-to-door for ADA-eligible riders incl. disabled veterans); Veterans ride free system-wide on Veterans Day; reduced fare card for disabled veterans." },
  { section: "CIN", title: "St. Vincent de Paul — Cincinnati", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Cincinnati", zip: "45203", website_url: "https://www.svdpcincinnati.org/", source_name: "Society of St. Vincent de Paul Cincinnati", source_type: "nonprofit", phone: "513-562-8841", address: "1125 Bank St, Cincinnati, OH 45214", desc: "St. Vincent de Paul Cincinnati — Greater Cincinnati Catholic charity; Don & Phyllis Neyer Outreach Center (food pantry, prescription assistance, free pharmacy, dental/vision, homeless services), 5 thrift stores, rent/utility assistance to veterans." },
  { section: "CIN", title: "Cincinnati State Technical & Community College — Veteran Services", cat: "education", sub: "Veteran Student Services", city: "Cincinnati", zip: "45223", website_url: "https://www.cincinnatistate.edu/veterans/", source_name: "Cincinnati State", source_type: "public_university", phone: "513-569-1870", address: "3520 Central Pkwy, Cincinnati, OH 45223", desc: "Cincinnati State Veteran Services — VA-certified school certifying official, GI Bill processing, Yellow Ribbon, VA work-study, priority registration, Student Veterans of America chapter; veterans lounge in Main 230." },
  { section: "CIN", title: "YWCA of Greater Cincinnati", cat: "family-support", sub: "Family Counseling", city: "Cincinnati", zip: "45202", website_url: "https://www.ywcacincinnati.org/", source_name: "YWCA of Greater Cincinnati", source_type: "nonprofit", phone: "513-241-7090", address: "898 Walnut St, Cincinnati, OH 45202", desc: "YWCA of Greater Cincinnati — domestic violence shelter (50-bed safe house), 24-hour DV hotline (513-872-9259), AMEND batterer intervention, racial-justice programs, Rising Star early-childhood ed; serves military/veteran families experiencing DV." },
  { section: "CIN", title: "Boys & Girls Clubs of Greater Cincinnati", cat: "family-support", sub: "Youth Programs", city: "Cincinnati", zip: "45225", website_url: "https://www.bgcgc.org/", source_name: "Boys & Girls Clubs of Greater Cincinnati", source_type: "nonprofit", phone: "513-421-8909", address: "600 Dalton Ave, Cincinnati, OH 45203", desc: "Boys & Girls Clubs of Greater Cincinnati — 9 club sites in Hamilton/Butler counties; after-school + summer programs for ages 6-18, academic success, healthy lifestyles, leadership/character; serves military-connected youth from Wright-Patt and Cincinnati VAMC families." },
  { section: "CIN", title: "Cincinnati Works", cat: "employment", sub: "Job Placement", city: "Cincinnati", zip: "45202", website_url: "https://www.cincinnatiworks.org/", source_name: "Cincinnati Works", source_type: "nonprofit", phone: "513-744-9675", address: "708 Walnut St 2nd Floor, Cincinnati, OH 45202", desc: "Cincinnati Works — workforce development nonprofit serving people in poverty (incl. veterans); job-readiness, career coaching, retention support, employer partnerships, Phoenix Program (employment for individuals with criminal records); free, lifetime membership." },
  { section: "CIN", title: "St. Vincent de Paul of Dayton", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Dayton", zip: "45402", website_url: "https://www.svdpcincinnati.org/", source_name: "Society of St. Vincent de Paul", source_type: "nonprofit", phone: "513-562-8841", address: "Society serves multi-county; Cincinnati HQ", desc: "Note: St Vincent de Paul Society — Cincinnati Council parent — coordinates Dayton-region SVDP conferences; Catholic-parish based emergency assistance (food, rent, utilities, furniture) by parish in Dayton metro." },

  // ============== DAYTON (10) ==============
  { section: "DAY", title: "Sinclair Community College — Veterans Resource Center", cat: "education", sub: "Veteran Student Services", city: "Dayton", zip: "45402", website_url: "https://www.sinclair.edu/veterans/", source_name: "Sinclair Community College", source_type: "public_university", phone: "937-512-3252", address: "444 W 3rd St, Dayton, OH 45402", desc: "Sinclair Community College Veterans Resource Center — Dayton-based community college; GI Bill processing, Yellow Ribbon, VA work-study, military credit evaluation, Student Veterans of America chapter; serves Wright-Patterson AFB community + Dayton VAMC veterans." },
  { section: "DAY", title: "Legal Aid of Western Ohio (LAWO) — Dayton", cat: "legal", sub: "Legal Aid Services", city: "Dayton", zip: "45402", website_url: "https://www.lasco.net/", source_name: "Legal Aid of Western Ohio", source_type: "nonprofit", phone: "937-535-4408", address: "130 W Second St Suite 700, Dayton, OH 45402", desc: "Legal Aid of Western Ohio (LAWO) — civil legal aid for low-income residents of 32 W/NW Ohio counties; Veterans Justice Project (eviction, public benefits, discharge upgrade), family law, consumer; on-site weekly clinic at Dayton VAMC and Wright-Patt." },
  { section: "DAY", title: "Advocates for Basic Legal Equality (ABLE)", cat: "legal", sub: "Pro Bono Legal Services", city: "Dayton", zip: "45402", website_url: "https://www.ablelaw.org/", source_name: "Advocates for Basic Legal Equality (ABLE)", source_type: "nonprofit", phone: "937-535-4408", address: "130 W Second St Suite 700, Dayton, OH 45402", desc: "ABLE — sister org to LAWO; civil legal services for migrant/seasonal farmworkers and low-income residents in W Ohio; Veterans Justice Project pro-bono attorney panel, immigration relief for veterans/spouses, public benefits, housing." },
  { section: "DAY", title: "Miami Valley Works (Dayton Workforce)", cat: "employment", sub: "Job Placement Programs", city: "Dayton", zip: "45402", website_url: "https://miamivalleyworks.org/", source_name: "Miami Valley Works", source_type: "nonprofit", phone: "937-535-2002", address: "8 N Main St, Dayton, OH 45402", desc: "Miami Valley Works — Dayton-region workforce development; barriers-to-work program, soft-skills training, job placement, Phoenix Project for justice-involved adults; serves veterans/military spouses with employer partnerships in W OH." },
  { section: "DAY", title: "Dayton YMCA Association", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Dayton", zip: "45402", website_url: "https://www.daytonymca.org/", source_name: "YMCA of Greater Dayton", source_type: "nonprofit", phone: "937-223-5201", address: "118 W First St, Dayton, OH 45402", desc: "YMCA of Greater Dayton — 6 branches in Montgomery/Greene/Warren/Miami counties; military-family discounts, Mission YMCA scholarships for veterans, Healthy Living programs, youth development, after-school care; Vetreran Day free guest passes." },
  { section: "DAY", title: "YWCA Dayton", cat: "family-support", sub: "Family Counseling", city: "Dayton", zip: "45402", website_url: "https://ywcadayton.org/", source_name: "YWCA Dayton", source_type: "nonprofit", phone: "937-461-5550", address: "141 W Third St, Dayton, OH 45402", desc: "YWCA Dayton — Dayton Domestic Violence Crisis Center (24/7 hotline 937-222-7233), 89-bed DV shelter, sexual assault advocacy, civil protection order assistance, racial justice; serves military/veteran families experiencing DV." },
  { section: "DAY", title: "City of Dayton Veterans Commission Liaison", cat: "community-support", sub: "Veteran Outreach Programs", city: "Dayton", zip: "45402", website_url: "https://www.daytonohio.gov/", source_name: "City of Dayton", source_type: "city_agency", phone: "937-333-3333", address: "101 W Third St, Dayton, OH 45402", desc: "City of Dayton — coordinates Veterans Day events, Honor Flight reception, partnership with Dayton VAMC; Mayor's Office of Faith-Based & Community Initiatives, public works ADA accommodations, Civil Service hiring preference for veterans." },
  { section: "DAY", title: "Honor Flight Dayton", cat: "community-support", sub: "Veteran Outreach Programs", city: "Dayton", zip: "45458", website_url: "https://www.honorflightdayton.org/", source_name: "Honor Flight Dayton", source_type: "nonprofit", phone: "937-521-2400", address: "PO Box 1051, Springboro, OH 45066", desc: "Honor Flight Dayton — Miami Valley hub of Honor Flight Network; flies WWII/Korean/Vietnam veterans to Washington DC war memorials at no cost; spring & fall flights from Dayton International Airport; supported by Wright-Patt Federal Credit Union." },
  { section: "DAY", title: "Greater Dayton Premier Management (Dayton MHA)", cat: "housing", sub: "Rental Assistance", city: "Dayton", zip: "45402", website_url: "https://www.gdpm.org/", source_name: "Greater Dayton Premier Management", source_type: "public_university", phone: "937-910-7500", address: "400 Wayne Ave, Dayton, OH 45410", desc: "Greater Dayton Premier Management (GDPM) — Dayton Metropolitan Housing Authority; 5,500+ public housing units, Housing Choice Voucher (Section 8), HUD-VASH partnership with Dayton VAMC for homeless veterans, Family Self-Sufficiency program." },

  // ============== TOLEDO (10) ==============
  { section: "TOL", title: "Toledo Area Regional Transit Authority (TARTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Toledo", zip: "43604", website_url: "https://www.tarta.com/", source_name: "TARTA", source_type: "public_university", phone: "419-243-7433", address: "1127 W Central Ave, Toledo, OH 43610", desc: "Toledo Area Regional Transit Authority (TARTA) — Lucas County public transit; 30+ bus routes + TARPS paratransit (door-to-door for ADA-eligible riders incl. service-disabled veterans); reduced fares for disabled veterans, Veterans Day free rides system-wide." },
  { section: "TOL", title: "Toledo Northwestern Ohio Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Toledo", zip: "43608", website_url: "https://www.toledofoodbank.org/", source_name: "Toledo Northwestern Ohio Food Bank", source_type: "nonprofit", phone: "419-242-5000", address: "24 E Woodruff Ave, Toledo, OH 43604", desc: "Toledo NW Ohio Food Bank — distributes 14M+ lbs annually to 8-county region (Lucas/Wood/Defiance/Erie/Fulton/Henry/Ottawa/Sandusky); 220+ partner pantries, Mobile Food Pantry, Backpack Program, SNAP outreach, veteran food drops at Toledo VA OPC." },
  { section: "TOL", title: "Cherry Street Mission Ministries", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Toledo", zip: "43604", website_url: "https://www.cherrystreetmission.org/", source_name: "Cherry Street Mission Ministries", source_type: "nonprofit", phone: "419-242-5141", address: "1501 Monroe St, Toledo, OH 43604", desc: "Cherry Street Mission Ministries — Toledo's largest homeless services provider; emergency shelter (Life Revitalization Center), Meals (3/day open to public), addiction recovery, GED, vocational training; serves homeless veterans referred from Toledo VA OPC." },
  { section: "TOL", title: "United Way of Greater Toledo", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Toledo", zip: "43604", website_url: "https://www.uwgt.org/", source_name: "United Way of Greater Toledo", source_type: "nonprofit", phone: "419-244-3063", address: "424 Jackson St, Toledo, OH 43604", desc: "United Way of Greater Toledo — funds 80+ partner agencies in Lucas/Wood counties; 211 community-resource referral, Volunteer Income Tax Assistance (VITA), Born Learning early-childhood, Real Money Now financial coaching, veteran-services pipeline." },
  { section: "TOL", title: "YMCA of Greater Toledo", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Toledo", zip: "43604", website_url: "https://ymcatoledo.org/", source_name: "YMCA of Greater Toledo", source_type: "nonprofit", phone: "419-251-9622", address: "5605 Monroe St, Sylvania, OH 43560", desc: "YMCA of Greater Toledo — 6 branches across Lucas/Wood counties; Mission YMCA scholarships for veterans/military families, free military membership for active duty, Healthy Living, after-school care, youth sports." },
  { section: "TOL", title: "Lucas Metropolitan Housing Authority (LMHA)", cat: "housing", sub: "Rental Assistance", city: "Toledo", zip: "43604", website_url: "https://www.lucasmha.org/", source_name: "Lucas Metropolitan Housing Authority", source_type: "public_university", phone: "419-259-9400", address: "201 Belmont Ave, Toledo, OH 43604", desc: "Lucas Metropolitan Housing Authority (LMHA) — public housing authority for Lucas County; 2,800+ public housing units, Housing Choice Voucher (Section 8), HUD-VASH partnership with VA Ann Arbor / Toledo VA OPC for homeless veterans, Family Self-Sufficiency." },
  { section: "TOL", title: "University of Toledo — Military Service Center", cat: "education", sub: "Veteran Student Services", city: "Toledo", zip: "43606", website_url: "https://www.utoledo.edu/al/military/", source_name: "University of Toledo", source_type: "public_university", phone: "419-530-1392", address: "2801 W Bancroft St, Toledo, OH 43606", desc: "University of Toledo Military Service Center — VA School Certifying Official for GI Bill, Yellow Ribbon, military credit transfer, ROTC (Army/AF), Student Veterans of America chapter, Heroes Walk; Bowman-Oddy Hall room 0008." },
  { section: "TOL", title: "Boys & Girls Clubs of Toledo", cat: "family-support", sub: "Youth Programs", city: "Toledo", zip: "43604", website_url: "https://www.bgctoledo.org/", source_name: "Boys & Girls Clubs of Toledo", source_type: "nonprofit", phone: "419-243-4150", address: "1411 Bancroft St, Toledo, OH 43606", desc: "Boys & Girls Clubs of Toledo — 6 club sites + Camp Miakonda; ages 6-18 after-school + summer programs, academic success, Triple Play health, Smart Moves, leadership development; serves military-connected youth in Lucas County." },
  { section: "TOL", title: "Toledo Lucas County Public Library", cat: "community-support", sub: "Veteran Outreach Programs", city: "Toledo", zip: "43604", website_url: "https://www.toledolibrary.org/", source_name: "Toledo Lucas County Public Library", source_type: "public_university", phone: "419-259-5200", address: "325 N Michigan St, Toledo, OH 43604", desc: "Toledo Lucas County Public Library — 20 branches in Lucas County; Veterans Resource displays, free internet/printers, ancestry/military records research, GED prep, English-as-second-language, free meeting rooms for VSO/AA/NA groups." },
  { section: "TOL", title: "Goodwill Industries of Northwest Ohio", cat: "employment", sub: "Vocational Rehabilitation", city: "Toledo", zip: "43607", website_url: "https://www.goodwillnwohio.com/", source_name: "Goodwill Industries of NW Ohio", source_type: "nonprofit", phone: "419-255-0070", address: "626 N Huron St, Toledo, OH 43604", desc: "Goodwill Industries of NW Ohio — workforce nonprofit serving 13-county NW OH region; vocational rehab, supported employment, Job Connection (resume/interview), retail-store paid training; serves veterans with disabilities through Toledo VA OPC referrals." },

  // ============== AKRON (10) ==============
  { section: "AKR", title: "Akron-Summit County Public Library", cat: "community-support", sub: "Veteran Outreach Programs", city: "Akron", zip: "44326", website_url: "https://www.akronlibrary.org/", source_name: "Akron-Summit County Public Library", source_type: "public_university", phone: "330-643-9000", address: "60 S High St, Akron, OH 44326", desc: "Akron-Summit County Public Library — 17 branches in Summit County; Veterans Resource displays, free meeting rooms for VFW/AL/DAV/AA/NA, ancestry/military records research, GED prep, free 1-on-1 tech help; partner with Summit County VSC for outreach events." },
  { section: "AKR", title: "Akron-Canton Regional Foodbank", cat: "food-assistance", sub: "Food Banks", city: "Akron", zip: "44306", website_url: "https://www.akroncantonfoodbank.org/", source_name: "Akron-Canton Regional Foodbank", source_type: "nonprofit", phone: "330-535-6900", address: "350 Opportunity Pkwy, Akron, OH 44307", desc: "Akron-Canton Regional Foodbank — distributes 35M+ lbs annually to 8-county region (Summit/Stark/Carroll/Holmes/Tuscarawas/Wayne/Medina/Portage); 500+ partner pantries, mobile pantries, Backpack Program, senior food box, SNAP outreach, vet outreach." },
  { section: "AKR", title: "United Way of Summit & Medina", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Akron", zip: "44308", website_url: "https://www.uwsummitmedina.org/", source_name: "United Way of Summit & Medina", source_type: "nonprofit", phone: "330-643-5555", address: "37 N High St, Akron, OH 44308", desc: "United Way of Summit & Medina — funds 60+ partner agencies in Summit/Medina counties; 211 HelpLine community-resource referral, Bold Goals (financial stability/education/health), Volunteer Center, Ride United transportation; veteran-services pipeline." },
  { section: "AKR", title: "Akron Area YMCA", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Akron", zip: "44313", website_url: "https://www.akronymca.org/", source_name: "Akron Area YMCA", source_type: "nonprofit", phone: "330-869-9622", address: "750 W Market St, Akron, OH 44303", desc: "Akron Area YMCA — 4 branches in Summit/Portage/Wayne counties; military-family discount, Mission YMCA scholarships for veterans, free active-duty membership, Healthy Living programs, youth development, school-age childcare." },
  { section: "AKR", title: "Goodwill Industries of Akron", cat: "employment", sub: "Vocational Rehabilitation", city: "Akron", zip: "44308", website_url: "https://www.goodwillakron.org/", source_name: "Goodwill Industries of Akron", source_type: "nonprofit", phone: "330-724-6995", address: "570 E Waterloo Rd, Akron, OH 44319", desc: "Goodwill Industries of Akron — workforce nonprofit serving Summit/Medina/Stark/Portage/Wayne; vocational rehab, supported employment, Veterans Reentry Program, GED prep, retail-store paid training; on-site partner at OhioMeansJobs Summit County." },
  { section: "AKR", title: "Akron Metropolitan Housing Authority (AMHA)", cat: "housing", sub: "Rental Assistance", city: "Akron", zip: "44308", website_url: "https://www.akronhousing.org/", source_name: "Akron Metropolitan Housing Authority", source_type: "public_university", phone: "330-376-9699", address: "100 W Cedar St, Akron, OH 44307", desc: "Akron Metropolitan Housing Authority (AMHA) — public housing authority for Summit County; 4,300+ public housing units, Housing Choice Voucher (Section 8), HUD-VASH partnership with Cleveland VAMC / Akron VA OPC for homeless veterans, Family Self-Sufficiency." },
  { section: "AKR", title: "Battered Women's Shelter & Rape Crisis Center of Summit/Medina", cat: "family-support", sub: "Family Counseling", city: "Akron", zip: "44311", website_url: "https://www.scmcbws.org/", source_name: "Battered Women's Shelter of Summit & Medina", source_type: "nonprofit", phone: "330-374-1111", address: "1006 Brown St, Akron, OH 44311", desc: "Battered Women's Shelter & Rape Crisis Center — Summit/Medina County DV/SA crisis services; 24/7 hotline (330-374-1111), 50-bed emergency shelter, supportive housing, court advocacy, counseling, prevention education; serves military/veteran families." },

  // ============== YOUNGSTOWN (12) ==============
  { section: "YNG", title: "Western Reserve Transit Authority (WRTA)", cat: "transportation", sub: "Public Transit Assistance", city: "Youngstown", zip: "44503", website_url: "https://www.wrta.com/", source_name: "Western Reserve Transit Authority", source_type: "public_university", phone: "330-744-8431", address: "604 Mahoning Ave, Youngstown, OH 44502", desc: "Western Reserve Transit Authority (WRTA) — Mahoning County public transit; 25+ bus routes + WRTA Curb-to-Curb paratransit (door-to-door for ADA-eligible riders incl. disabled veterans); reduced fares for disabled veterans, Veterans Day free rides." },
  { section: "YNG", title: "Second Harvest Food Bank of the Mahoning Valley", cat: "food-assistance", sub: "Food Banks", city: "Youngstown", zip: "44510", website_url: "https://2harvest.org/", source_name: "Second Harvest Food Bank of the Mahoning Valley", source_type: "nonprofit", phone: "330-792-5522", address: "2805 Salt Springs Rd, Youngstown, OH 44509", desc: "Second Harvest Food Bank of the Mahoning Valley — distributes 12M+ lbs annually to 3-county region (Mahoning/Trumbull/Columbiana); 130+ partner pantries, mobile food pantries, Backpack Program, senior food box, veteran outreach via Mahoning Co VSC." },
  { section: "YNG", title: "United Way of Mahoning Valley", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Youngstown", zip: "44503", website_url: "https://www.unitedwaymv.org/", source_name: "United Way of Mahoning Valley", source_type: "nonprofit", phone: "330-746-8494", address: "2901 Mahoning Ave Suite 1, Youngstown, OH 44509", desc: "United Way of Mahoning Valley — funds 30+ partner agencies in Mahoning/Trumbull/Columbiana counties; 211 community-resource referral, Volunteer Income Tax Assistance (VITA), early-childhood ed, financial-stability initiatives, veteran-services coordination." },
  { section: "YNG", title: "YMCA-YWCA of Greater Youngstown", cat: "community-support", sub: "Fitness, Sports & Wellness Groups", city: "Youngstown", zip: "44503", website_url: "https://www.ymca-ywca.org/", source_name: "YMCA-YWCA of Greater Youngstown", source_type: "nonprofit", phone: "330-744-8411", address: "17 N Champion St, Youngstown, OH 44503", desc: "YMCA-YWCA of Greater Youngstown — combined Y serving Mahoning/Trumbull; military-family discounts, Mission scholarships for veterans, Healthy Living programs, youth development, after-school care, residential housing for women + Single Room Occupancy." },
  { section: "YNG", title: "Youngstown State University — Office of Veterans Affairs", cat: "education", sub: "Veteran Student Services", city: "Youngstown", zip: "44555", website_url: "https://www.ysu.edu/veterans/", source_name: "Youngstown State University", source_type: "public_university", phone: "330-941-2503", address: "Tod Hall Room 311, 1 University Plaza, Youngstown, OH 44555", desc: "Youngstown State University Office of Veterans Affairs — VA School Certifying Official for GI Bill, Yellow Ribbon, military credit evaluation, ROTC (Army), Student Veterans of America chapter; Tod Hall Room 311; partner with Youngstown VA OPC." },
  { section: "YNG", title: "City of Youngstown Mayor's Veterans Liaison", cat: "community-support", sub: "Veteran Outreach Programs", city: "Youngstown", zip: "44503", website_url: "https://www.youngstownohio.gov/", source_name: "City of Youngstown", source_type: "city_agency", phone: "330-742-8700", address: "26 S Phelps St, Youngstown, OH 44503", desc: "City of Youngstown — coordinates Veterans Day events, Memorial Day parade, Honor Flight reception with Mahoning County VSC; Mayor's Office of Diversity, Equity & Inclusion supports veteran initiatives; Civil Service hiring preference for veterans." },
  { section: "YNG", title: "Mahoning County Career & Technical Center (Workforce/Career)", cat: "employment", sub: "Career Counseling", city: "Canfield", zip: "44406", website_url: "https://www.mahoningctc.com/", source_name: "Mahoning County Career & Technical Center", source_type: "public_university", phone: "330-729-4000", address: "7300 Palmyra Rd, Canfield, OH 44406", desc: "Mahoning County Career & Technical Center — adult/secondary career training in Canfield (medical, IT, welding, HVAC, cosmetology, public safety); GI Bill-approved programs, military-credit acceptance, veterans receive priority enrollment." },
  { section: "YNG", title: "Eastern Gateway Community College — Youngstown Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Youngstown", zip: "44505", website_url: "https://egcc.edu/", source_name: "Eastern Gateway Community College", source_type: "public_university", phone: "330-480-0726", address: "101 E Federal St, Youngstown, OH 44503", desc: "Eastern Gateway Community College Youngstown Campus — VA School Certifying Official for GI Bill, Yellow Ribbon, military credit, free college benefit for AFSCME union members; partnerships with YSU and Mahoning County VSC for veteran-friendly transfers." },
  { section: "YNG", title: "Help Hotline Crisis Center (Mahoning Valley)", cat: "crisis-help", sub: "Suicide Prevention", city: "Youngstown", zip: "44503", website_url: "https://www.helphotline.org/", source_name: "Help Hotline Crisis Center", source_type: "nonprofit", phone: "330-747-2696", address: "535 Marmion Ave, Youngstown, OH 44502", desc: "Help Hotline Crisis Center — 24/7 crisis hotline serving Mahoning/Trumbull/Columbiana counties; suicide prevention, mobile crisis response, 988 Lifeline backbone for Mahoning Valley, addiction crisis, info & referral; partner with Youngstown VA OPC." },
  { section: "YNG", title: "Sojourner House Domestic Violence Program (Mahoning)", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Youngstown", zip: "44503", website_url: "https://compassfamily.org/sojourner-house/", source_name: "Compass Family & Community Services", source_type: "nonprofit", phone: "330-747-4040", address: "535 Marmion Ave, Youngstown, OH 44502", desc: "Sojourner House — Compass Family DV program; 24/7 hotline (330-747-4040), 35-bed safe house, court advocacy, supportive housing, children's program, prevention education for Mahoning County; serves military/veteran families experiencing DV." },
  { section: "YNG", title: "Mahoning County Children Services", cat: "family-support", sub: "Youth Programs", city: "Youngstown", zip: "44503", website_url: "https://www.mahoningkids.com/", source_name: "Mahoning County Children Services Board", source_type: "county_agency", phone: "330-941-8888", address: "222 W Federal St 4th Floor, Youngstown, OH 44503", desc: "Mahoning County Children Services Board — public child welfare; child abuse hotline (330-941-8888), foster care/adoption, in-home support, kinship care, military-family advocacy; serves children of veterans/active-duty in Mahoning County." },
];

runSeed(ROWS, { state: "OH", commit: COMMIT, scriptName: "seed-oh-rebuild-p4.ts" });
