/**
 * PA REBUILD — PHASE 5: WEAK-CAT LIFT + STATEWIDE MAINSTREAM UTILITY DEPTH
 * Founder one-phase-per-run governance — approved 2026-04-27 with explicit
 * scope correction: VeteranCare is veteran-FIRST not veteran-ONLY. Add BOTH
 * veteran-specific resources AND mainstream resources veterans realistically
 * use across major + secondary cities.
 *
 * Targets:
 *   - Insurance lift (1 → 7+) via APPRISE state, PA Insurance Dept, BCBS carriers
 *   - Education lift (3 → 16+) via 7 college VRE pages + 9 community colleges
 *   - Workforce/Employment lift (5 → 10+) via DLI Career Services / WEDGE /
 *     Apprenticeship / Hire Heroes USA / OICA / Bunker Labs
 *   - Disabled-Veterans lift (5 → 10+) via PA OVR + BBVS + DAV finder + WWP + AWP
 *   - Family-support depth (6 → 13+) via 7 Catholic Charities diocesan offices
 *   - Mainstream utility statewide:
 *     * United Way × 8 (Phila/SWPA/Capital/LV/Berks/Lancaster/Erie/WyValley)
 *     * Goodwill × 3 territories
 *     * Habitat for Humanity × 4 affiliates
 *     * YMCA × 2
 *     * Major hospital systems × 6
 *     * Mental-health × 7 (MHA, NAMI, Eagleville, Penn Foundation, Cohen Vet)
 *     * Substance-recovery × 4 (DDAP + Get Help Now + AAEPI + ProRehab)
 *     * Government & community × 7 (211, Aging, Health, Treasury, AARP,
 *       IRS VITA, SCSC, PA Rural Health)
 *     * Family / caregiver × 4 (FSA Bucks, Cradles to Crayons, Operation Warm,
 *       Penn State Extension)
 *     * National vet org finders × 4 (VFW, AMVETS, IAVA, Code of Support)
 *
 * URL liveness: every URL pre-probed via parallel curl HEAD-then-GET with
 *   engine UA "VeteranCare-RolloutEngine/1.0 (+url-liveness-gate)" before
 *   authoring. Skipped/blocked from list (no canonical live URL): davpa.org,
 *   easterseals.com regional pages, vfwpahq.org, pvakeystone.org, namibuxpa,
 *   namichestercopa, namisouthwesternpa, ymcaofgreaterpittsburgh, mhalv,
 *   tjuh.org, friendshospitalonline (already in PA via friendshospital.com),
 *   ccharitiesgbg, easternpa.salvationarmy and per-city corps subdomains
 *   (Salvation Army hard-blocks engine UA), villanova military pages (404),
 *   lehigh military pages (500), USAA & national-only insurers without PA
 *   anchor.
 *
 * Skip blockers, skip dups (founder lock).
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [

  // ======================== INSURANCE LIFT — 6 ========================
  { section: "INS", title: "PA APPRISE — Statewide Health Insurance Counseling Program", cat: "insurance", sub: "Medicare & VA Plans", city: "Harrisburg", website_url: "https://www.aging.pa.gov/aging-services/insurance/Pages/APPRISE.aspx", source_name: "PA Department of Aging — APPRISE (PA SHIP)", source_type: "state_government_agency", phone: "1-800-783-7067", address: "555 Walnut St 5th Fl, Harrisburg, PA 17101", zip: "17101", desc: "PA APPRISE — Pennsylvania's State Health Insurance Assistance Program (SHIP); free, confidential, unbiased Medicare counseling delivered through 52 county AAAs and 800+ trained volunteer counselors. Help understanding Medicare/Medigap/Medicare Advantage/Part D, comparing plans, applying for Extra Help & MSP, billing-issue resolution. Veterans coordinate Medicare with VA healthcare and TRICARE-for-Life." },
  { section: "INS", title: "Pennsylvania Insurance Department", cat: "insurance", sub: "Health Insurance", city: "Harrisburg", website_url: "https://www.insurance.pa.gov/", source_name: "PA Insurance Department", source_type: "state_government_agency", phone: "1-877-881-6388", address: "1326 Strawberry Sq, Harrisburg, PA 17120", zip: "17120", desc: "PA Insurance Department — state regulator and consumer protection for all lines of insurance sold in PA; Bureau of Consumer Services investigates complaints, mediates disputes (auto/home/health/life/long-term care), licenses agents/companies, runs Pennie ACA marketplace oversight. Veterans use for TRICARE supplement disputes, VA-coordinated health-plan issues, and pre-deployment policy reviews." },
  { section: "INS", title: "Highmark Blue Cross Blue Shield (Pennsylvania)", cat: "insurance", sub: "Health Insurance", city: "Pittsburgh", website_url: "https://www.highmark.com/", source_name: "Highmark Inc.", source_type: "insurance_carrier", phone: "1-866-823-2752", address: "120 Fifth Ave, Pittsburgh, PA 15222", zip: "15222", desc: "Highmark BCBS — largest health insurer in Western & Central PA (29 western/central PA counties); individual & family ACA plans, employer-group, Medicare Advantage, Medicare Supplement, Part D. Veterans use Highmark Medicare Advantage to coordinate with VA priority-group enrollment and TRICARE for Life. Has VA-network referral coordination for outpatient specialty referrals." },
  { section: "INS", title: "Independence Blue Cross (Philadelphia region)", cat: "insurance", sub: "Health Insurance", city: "Philadelphia", website_url: "https://www.ibx.com/", source_name: "Independence Blue Cross", source_type: "insurance_carrier", phone: "1-800-275-2583", address: "1901 Market St, Philadelphia, PA 19103", zip: "19103", desc: "Independence Blue Cross — largest health insurer in SE PA (5-county Philadelphia region); ACA marketplace plans, employer-group, Keystone HMO/POS, Medicare Advantage, dual-eligible (Medicare+Medicaid), pediatric (CHIP). Veterans use Medicare Advantage products to coordinate with Philadelphia VAMC priority-group care." },
  { section: "INS", title: "Capital Blue Cross (Central PA & Lehigh Valley)", cat: "insurance", sub: "Health Insurance", city: "Harrisburg", website_url: "https://www.capbluecross.com/", source_name: "Capital Blue Cross", source_type: "insurance_carrier", phone: "1-800-541-7000", address: "2500 Elmerton Ave, Harrisburg, PA 17110", zip: "17110", desc: "Capital BlueCross — health insurer for 21-county Central PA & Lehigh Valley region; ACA individual/family, employer-group, Medicare Advantage (Senior BlueRx & BlueJourney), Part D, dental & vision. Veterans use to coordinate with Lebanon VAMC + Allentown CBOC priority-group enrollment." },
  { section: "INS", title: "UPMC Health Plan", cat: "insurance", sub: "Health Insurance", city: "Pittsburgh", website_url: "https://www.upmchealthplan.com/", source_name: "UPMC Health Plan", source_type: "insurance_carrier", phone: "1-877-563-3375", address: "600 Grant St U.S. Steel Tower, Pittsburgh, PA 15219", zip: "15219", desc: "UPMC Health Plan — UPMC-affiliated insurer covering Western PA & growing Central/Eastern PA; ACA marketplace, employer-group, UPMC for You (Medicaid), UPMC for Life (Medicare Advantage), CHIP, Community HealthChoices (LTSS for dual-eligibles). Coordinates with VA Pittsburgh Healthcare for veteran enrollees." },

  // ======================== EDUCATION — COLLEGE VRE — 7 ========================
  { section: "EDU", title: "Penn State Office of Veterans Programs", cat: "education", sub: "Veteran Student Services", city: "University Park", website_url: "https://veterans.psu.edu/", source_name: "The Pennsylvania State University", source_type: "university_office", phone: "814-863-1893", address: "Outreach Bldg, University Park, PA 16802", zip: "16802", desc: "Penn State Office of Veterans Programs — Penn State's central VRE office serving 6,000+ student veterans/dependents across 24 campuses; GI Bill (Ch 33/30/31/35) certification, Yellow Ribbon participant, on-campus Vet Lounge, peer mentoring, military credit evaluation, transition support, financial aid coordination. Single point of contact for student vets statewide PSU system." },
  { section: "EDU", title: "University of Pittsburgh Office of Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Pittsburgh", website_url: "https://www.veterans.pitt.edu/", source_name: "University of Pittsburgh", source_type: "university_office", phone: "412-624-8147", address: "738 William Pitt Union, 3959 Fifth Ave, Pittsburgh, PA 15260", zip: "15260", desc: "Pitt Office of Veterans Services — central resource for ~600 student veterans/dependents/active-duty across all Pitt campuses; GI Bill certification, Yellow Ribbon institution, Veterans Lounge, Tutoring program, priority registration, mental-health & academic coaching, Veteran Mentor Project. Located in William Pitt Union." },
  { section: "EDU", title: "Temple University Military & Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Philadelphia", website_url: "https://veterans.temple.edu/", source_name: "Temple University", source_type: "university_office", phone: "215-204-2956", address: "Howard Gittis Student Center 200, 1755 N 13th St, Philadelphia, PA 19122", zip: "19122", desc: "Temple Military & Veterans Services — supports ~700 student veterans, dependents, active-duty, reservists; GI Bill certification (Ch 33/30/31/33/35), Yellow Ribbon participant, dedicated Veterans Resource Center, peer-to-peer mentoring, Vet-2-Vet group, priority registration, military credit translation." },
  { section: "EDU", title: "Drexel University Office of Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Philadelphia", website_url: "https://drexel.edu/veterans/", source_name: "Drexel University", source_type: "university_office", phone: "215-895-2118", address: "3210 Cherry St, Philadelphia, PA 19104", zip: "19104", desc: "Drexel Veterans Services — central office for ~500 student veterans, dependents, active-duty; full GI Bill certification, Yellow Ribbon participant (full tuition coverage for top-tier vets), dedicated lounge, on-campus VITAL counselor (Phila VAMC liaison), employment co-op pathway, transition workshops." },
  { section: "EDU", title: "Duquesne University Military & Veterans Programs", cat: "education", sub: "Veteran Student Services", city: "Pittsburgh", website_url: "https://www.duq.edu/about/diversity/military-and-veterans", source_name: "Duquesne University", source_type: "university_office", phone: "412-396-6212", address: "600 Forbes Ave, Pittsburgh, PA 15282", zip: "15282", desc: "Duquesne Military & Veterans Programs — Catholic-Spiritan university serving 200+ student vets/dependents; GI Bill certification, Yellow Ribbon (full coverage), military credit evaluation, dedicated Veterans Resource Center, Vet-friendly faculty network, undergrad and graduate priority for service-members." },
  { section: "EDU", title: "IUP Military Resource Center", cat: "education", sub: "Veteran Student Services", city: "Indiana", website_url: "https://www.iup.edu/military/", source_name: "Indiana University of Pennsylvania", source_type: "university_office", phone: "724-357-5775", address: "1011 South Dr, Indiana, PA 15705", zip: "15705", desc: "IUP Military Resource Center — Indiana University of PA's central VRE office for ~400 student vets, ROTC cadets, dependents; GI Bill (all chapters) certification, Yellow Ribbon institution, on-campus VA work-study, ROTC liaison (Crimson Battalion Army), Veterans Reception Center lounge, military credit transfer." },
  { section: "EDU", title: "La Salle University Military & Veterans Services", cat: "education", sub: "Veteran Student Services", city: "Philadelphia", website_url: "https://www.lasalle.edu/admission/military-veterans/", source_name: "La Salle University", source_type: "university_office", phone: "215-951-1015", address: "1900 W Olney Ave, Philadelphia, PA 19141", zip: "19141", desc: "La Salle University Military & Veterans Services — Christian Brothers university serving student vets, active-duty, dependents, reservists; GI Bill certification (Ch 30/31/33/35), Yellow Ribbon participant, military credit evaluation, dedicated admissions counselor, transition mentoring." },

  // ======================== EDUCATION — COMMUNITY COLLEGES — 9 ========================
  { section: "CCC", title: "Community College of Allegheny County (CCAC)", cat: "education", sub: "College & University Programs", city: "Pittsburgh", website_url: "https://www.ccac.edu/", source_name: "Community College of Allegheny County", source_type: "community_college", phone: "412-237-2525", address: "800 Allegheny Ave, Pittsburgh, PA 15233", zip: "15233", desc: "CCAC — Allegheny County's community college; 4 campuses (Allegheny, Boyce/Monroeville, North/McCandless, South/West Mifflin), 175+ programs, transfer & workforce credentials, GI Bill (Ch 33/30/31/35) certification, Veterans Resource Office at each campus, military credit evaluation, dedicated VA work-study positions." },
  { section: "CCC", title: "Bucks County Community College", cat: "education", sub: "College & University Programs", city: "Newtown", website_url: "https://www.bucks.edu/", source_name: "Bucks County Community College", source_type: "community_college", phone: "215-968-8000", address: "275 Swamp Rd, Newtown, PA 18940", zip: "18940", desc: "Bucks County CC — Bucks County community college; main campus Newtown plus Lower Bucks (Bristol) & Upper Bucks (Perkasie); 90+ associate & certificate programs, GI Bill certification, dedicated Veterans Affairs Office, Yellow Ribbon participant, military credit transfer, on-campus VA work-study positions." },
  { section: "CCC", title: "Montgomery County Community College", cat: "education", sub: "College & University Programs", city: "Blue Bell", website_url: "https://www.mc3.edu/", source_name: "Montgomery County Community College", source_type: "community_college", phone: "215-641-6300", address: "340 DeKalb Pike, Blue Bell, PA 19422", zip: "19422", desc: "Montgomery County CC (MCCC) — Montgomery County community college; 2 campuses (Blue Bell, Pottstown) plus Culinary Arts Institute, 100+ programs, dedicated Veterans Affairs Coordinator, GI Bill certification, military credit evaluation, Yellow Ribbon institution, Service Members Opportunity College participant." },
  { section: "CCC", title: "Delaware County Community College", cat: "education", sub: "College & University Programs", city: "Media", website_url: "https://www.dccc.edu/", source_name: "Delaware County Community College", source_type: "community_college", phone: "610-359-5000", address: "901 S Media Line Rd, Media, PA 19063", zip: "19063", desc: "DCCC — Delaware & Chester counties community college; main Marple Campus (Media), 4 satellite campuses (Downingtown, Exton, Phoenixville, Pennocks Bridge), 130+ programs, dedicated Office of Military & Veterans Affairs, GI Bill certification, military credit transfer, Yellow Ribbon program participant." },
  { section: "CCC", title: "Reading Area Community College (RACC)", cat: "education", sub: "College & University Programs", city: "Reading", website_url: "https://www.racc.edu/", source_name: "Reading Area Community College", source_type: "community_college", phone: "610-372-4721", address: "10 S 2nd St, Reading, PA 19602", zip: "19602", desc: "RACC — Berks County community college; downtown Reading campus, 70+ associate & certificate programs, dedicated Veterans Affairs Office, GI Bill certification (all chapters), military credit evaluation, on-campus Veterans Lounge, transfer agreements with Penn State Berks & Albright." },
  { section: "CCC", title: "Northampton Community College", cat: "education", sub: "College & University Programs", city: "Bethlehem", website_url: "https://www.northampton.edu/", source_name: "Northampton Community College", source_type: "community_college", phone: "610-861-5300", address: "3835 Green Pond Rd, Bethlehem, PA 18020", zip: "18020", desc: "Northampton CC (NCC) — Northampton & Monroe counties community college; main Bethlehem campus + Tannersville (Pocono); 100+ programs, Office of Military & Veteran Education, GI Bill certification, dedicated VA Coordinator, Yellow Ribbon institution, military credit transfer, on-campus Vet lounge." },
  { section: "CCC", title: "Lehigh Carbon Community College (LCCC)", cat: "education", sub: "College & University Programs", city: "Schnecksville", website_url: "https://www.lccc.edu/", source_name: "Lehigh Carbon Community College", source_type: "community_college", phone: "610-799-2121", address: "4525 Education Park Dr, Schnecksville, PA 18078", zip: "18078", desc: "LCCC — Lehigh, Carbon & Schuylkill counties community college; Schnecksville main campus + Allentown, Tamaqua, Jim Thorpe sites, 90+ programs, Veterans Services Office, GI Bill certification (Ch 33/30/31/35), military credit evaluation, Yellow Ribbon participant, on-campus Veterans Resource Center." },
  { section: "CCC", title: "Pennsylvania College of Technology (Penn College)", cat: "education", sub: "Trade Schools & Vocational", city: "Williamsport", website_url: "https://www.pct.edu/", source_name: "Pennsylvania College of Technology (Penn State affiliate)", source_type: "technical_college", phone: "570-326-3761", address: "1 College Ave, Williamsport, PA 17701", zip: "17701", desc: "Penn College — special-mission affiliate of Penn State; bachelor's & associate degrees in skilled trades & applied technology (welding, automotive, construction, HVAC, aviation maintenance, nursing, dental hygiene, IT). Dedicated Veterans Services Office, GI Bill certification, Yellow Ribbon institution, military credit transfer, hands-on training ideal for transitioning service-members." },
  { section: "CCC", title: "Harrisburg Area Community College (HACC)", cat: "education", sub: "College & University Programs", city: "Harrisburg", website_url: "https://www.hacc.edu/", source_name: "Harrisburg Area Community College", source_type: "community_college", phone: "717-780-2300", address: "1 HACC Dr, Harrisburg, PA 17110", zip: "17110", desc: "HACC — Central PA's community college (PA's first); 5 campuses (Harrisburg, Lancaster, York, Gettysburg, Lebanon) + Virtual Learning, 200+ programs, dedicated Office of Military & Veterans Affairs at each campus, GI Bill certification, Yellow Ribbon, military credit, Veteran-Friendly designation by Military Times." },
  { section: "CCC", title: "Westmoreland County Community College", cat: "education", sub: "College & University Programs", city: "Youngwood", website_url: "https://www.westmoreland.edu/", source_name: "Westmoreland County Community College", source_type: "community_college", phone: "724-925-4000", address: "145 Pavilion Ln, Youngwood, PA 15697", zip: "15697", desc: "Westmoreland CCC — Westmoreland County community college; main Youngwood campus + Latrobe, Murrysville, New Kensington, Indiana, Public Safety Training Center, 100+ programs, Veteran Services Office, GI Bill certification, military credit transfer, Yellow Ribbon institution." },
  { section: "CCC", title: "Luzerne County Community College", cat: "education", sub: "College & University Programs", city: "Nanticoke", website_url: "https://www.luzerne.edu/", source_name: "Luzerne County Community College", source_type: "community_college", phone: "570-740-0337", address: "1333 S Prospect St, Nanticoke, PA 18634", zip: "18634", desc: "Luzerne CCC — Luzerne County community college; Nanticoke main campus + Hazleton & Berwick sites, 80+ associate & certificate programs, dedicated Veterans Affairs Office, GI Bill certification, military credit evaluation, on-campus Vet study lounge, transfer pathway to Wilkes/King's/Bloomsburg." },
  { section: "CCC", title: "Pennsylvania Highlands Community College", cat: "education", sub: "College & University Programs", city: "Johnstown", website_url: "https://www.pennhighlands.edu/", source_name: "Pennsylvania Highlands Community College", source_type: "community_college", phone: "814-262-6400", address: "101 Community College Way, Johnstown, PA 15904", zip: "15904", desc: "Penn Highlands CC — Cambria/Somerset/Bedford/Blair counties community college; Richland Township (Johnstown) main + Blair/Ebensburg/Huntingdon sites, 50+ programs, Veteran Resource Center, GI Bill certification, military credit transfer, Yellow Ribbon institution." },

  // ======================== WORKFORCE / EMPLOYMENT — 5 ========================
  { section: "WORK", title: "PA CareerLink (PA DLI Career Services)", cat: "employment", sub: "DVOP / Workforce Programs", city: "Harrisburg", website_url: "https://www.dli.pa.gov/Individuals/Career-Services/Pages/PA-CareerLink-locations.aspx", source_name: "PA Department of Labor & Industry", source_type: "state_government_agency", phone: "1-866-858-0218", address: "651 Boas St, Harrisburg, PA 17121", zip: "17121", desc: "PA CareerLink — statewide One-Stop workforce system administered by PA DLI; 75+ comprehensive & affiliate centers, free job-search assistance, resume help, training scholarships (WIOA), career counseling, dedicated Disabled Veteran Outreach Program (DVOP) specialists & Local Veterans Employment Representatives (LVER) at every center. Veteran priority-of-service mandated." },
  { section: "WORK", title: "PA WEDGE — Workforce Development Grant for Employers", cat: "employment", sub: "Career Counseling", city: "Harrisburg", website_url: "https://www.dli.pa.gov/Individuals/Career-Services/wedge/Pages/default.aspx", source_name: "PA Department of Labor & Industry", source_type: "state_government_agency", phone: "717-787-2912", address: "651 Boas St, Harrisburg, PA 17121", zip: "17121", desc: "PA WEDGE — Workforce & Economic Development Network grant program; PA DLI-funded incumbent-worker training, on-the-job training (OJT), customized training contracts to upskill PA workers including transitioning service-members. Employers can claim WEDGE grants when hiring & training veterans; vets benefit indirectly via wage uplifts." },
  { section: "WORK", title: "PA Apprenticeship & Training Office", cat: "employment", sub: "Apprenticeships", city: "Harrisburg", website_url: "https://www.dli.pa.gov/Businesses/Workforce-Development/apprenticeship/Pages/default.aspx", source_name: "PA Department of Labor & Industry", source_type: "state_government_agency", phone: "717-787-3354", address: "651 Boas St, Harrisburg, PA 17121", zip: "17121", desc: "PA Apprenticeship & Training Office (ATO) — DLI registers & oversees 1,200+ Registered Apprenticeship programs in PA across construction, manufacturing, healthcare, IT, energy, transportation; veterans can use GI Bill funds toward apprenticeship wages, dedicated Veterans-in-Apprenticeship outreach, employer match programs, free apprentice-employer matchmaking." },
  { section: "WORK", title: "Hire Heroes USA — National Veteran Employment Services", cat: "employment", sub: "Job Placement", website_url: "https://www.hireheroesusa.org/", source_name: "Hire Heroes USA", source_type: "national_nonprofit", phone: "844-634-1520", desc: "Hire Heroes USA — national nonprofit providing free 1-on-1 employment coaching to U.S. veterans, transitioning service-members, and military spouses; resume building, interview prep, federal-resume conversion, employer connections, virtual career fairs, mentoring program. Serves PA veterans nationally with virtual delivery; 50,000+ vets placed since founding." },
  { section: "WORK", title: "Opportunities Industrialization Center of America (OICA) — Philadelphia HQ", cat: "employment", sub: "Job Placement", city: "Philadelphia", website_url: "https://www.oicofamerica.org/", source_name: "OIC of America", source_type: "national_nonprofit", phone: "215-236-7700", address: "1415 N Broad St Suite 222, Philadelphia, PA 19122", zip: "19122", desc: "OIC of America — founded 1964 in Philadelphia by Rev. Leon Sullivan; national workforce development network with 30+ affiliates; Philadelphia HQ delivers training in healthcare (CNA, medical billing), construction trades, IT, financial literacy, GED prep; veteran-priority program with WIOA wraparound services. Serves underserved adults including transitioning service-members." },

  // ======================== DISABLED VETERANS LIFT — 5 ========================
  { section: "DAB", title: "PA Office of Vocational Rehabilitation (OVR)", cat: "disabled-veterans", sub: "Employment & Vocational Rehabilitation", city: "Harrisburg", website_url: "https://www.dli.pa.gov/Individuals/Disability-Services/ovr/Pages/default.aspx", source_name: "PA Department of Labor & Industry", source_type: "state_government_agency", phone: "1-800-442-6351", address: "1521 N 6th St, Harrisburg, PA 17102", zip: "17102", desc: "PA OVR — DLI division providing vocational-rehabilitation services to Pennsylvanians with disabilities including service-connected disabled veterans; vocational counseling, job-skills training, on-the-job training, college/university tuition support, assistive technology, supported employment, customized employment. 18 OVR district offices statewide; coordinates with VA Vocational Readiness & Employment (Ch 31) services." },
  { section: "DAB", title: "PA Bureau of Blindness & Visual Services (BBVS)", cat: "disabled-veterans", sub: "Adaptive Equipment & Assistive Technology", city: "Harrisburg", website_url: "https://www.dli.pa.gov/Individuals/Disability-Services/ovr/bbvs/Pages/default.aspx", source_name: "PA Department of Labor & Industry — BBVS", source_type: "state_government_agency", phone: "1-866-325-6135", address: "1521 N 6th St, Harrisburg, PA 17102", zip: "17102", desc: "PA BBVS — DLI/OVR bureau dedicated to Pennsylvanians who are blind or have low vision; vocational rehabilitation, independent-living skills training (cane travel, braille, daily living), assistive-technology evaluation & training, Older Blind program (55+), Business Enterprise Program (vending). Veterans with service-connected vision loss coordinate with VA Blind Rehabilitation Service & PA BBVS for state-level wraparound." },
  { section: "DAB", title: "DAV — Find a Local Office (Pennsylvania)", cat: "disabled-veterans", sub: "Disability Benefits & Claims", website_url: "https://www.dav.org/veterans/find-your-local-office/?stateName=Pennsylvania", source_name: "Disabled American Veterans (DAV)", source_type: "veteran_service_organization", phone: "877-426-2838", desc: "DAV (Disabled American Veterans) — National finder for DAV-accredited Service Officers in PA; free VA disability claim filing, appeals, evidence-development, C&P prep, secondary-condition strategy, dependent claims, healthcare enrollment. PA DAV operates from VA Regional Offices in Philadelphia & Pittsburgh + 80+ chapters statewide. Use the locator to find your nearest chapter." },
  { section: "DAB", title: "Wounded Warrior Project (WWP) — Programs", cat: "disabled-veterans", sub: "Mental Health & PTSD Support", website_url: "https://www.woundedwarriorproject.org/programs", source_name: "Wounded Warrior Project", source_type: "national_veteran_nonprofit", phone: "904-405-1213", desc: "Wounded Warrior Project — national nonprofit serving post-9/11 wounded, ill, or injured veterans; free programs include Project Odyssey (PTSD), Warriors to Work (employment), Independence Program (severely injured caregivers), Combat Stress Recovery, Soldier Ride (adaptive cycling), Family Support, Benefits Service (claims). PA warriors enrolled receive virtual + Northeast regional gathering options." },
  { section: "DAB", title: "America's Warrior Partnership", cat: "disabled-veterans", sub: "Caregiver & Family Support", website_url: "https://www.americaswarriorpartnership.org/", source_name: "America's Warrior Partnership", source_type: "national_veteran_nonprofit", phone: "706-955-1356", desc: "America's Warrior Partnership — national nonprofit using proactive community-integration model (The Network) to connect post-9/11 veterans + families with vetted local providers; case-management for housing/employment/healthcare/finances/legal; suicide-prevention initiative (Operation Deep Dive); resource navigation. Serves PA veterans through partner network including local VA & VSO orgs." },

  // ======================== CATHOLIC CHARITIES DIOCESAN — 7 ========================
  { section: "CCH", title: "Archdiocese of Philadelphia Catholic Social Services", cat: "family-support", sub: "Family Counseling", city: "Philadelphia", website_url: "https://ccphila.org/", source_name: "Catholic Social Services Archdiocese of Philadelphia", source_type: "faith_based_nonprofit", phone: "215-587-3900", address: "222 N 17th St, Philadelphia, PA 19103", zip: "19103", desc: "Catholic Social Services — Archdiocese of Philadelphia (covers Phila, Bucks, Chester, Delaware, Montgomery counties); largest faith-based social-service network in SE PA; family counseling, residential programs, refugee resettlement, adoption, immigrant legal services, food pantries, homeless prevention, senior services. Veterans and families served regardless of religion." },
  { section: "CCH", title: "Diocese of Pittsburgh Catholic Charities", cat: "family-support", sub: "Family Counseling", city: "Pittsburgh", website_url: "https://ccdop.org/", source_name: "Catholic Charities Diocese of Pittsburgh", source_type: "faith_based_nonprofit", phone: "412-456-6999", address: "212 9th St, Pittsburgh, PA 15222", zip: "15222", desc: "Catholic Charities — Diocese of Pittsburgh (covers Allegheny, Beaver, Butler, Greene, Lawrence, Washington counties); free professional counseling, free dental & medical clinics (Allegheny), pregnancy services, immigrant legal services, refugee resettlement, financial-stability/case-management. Veterans and military families welcome regardless of religion." },
  { section: "CCH", title: "Diocese of Harrisburg Catholic Charities", cat: "family-support", sub: "Family Counseling", city: "Harrisburg", website_url: "https://www.cchbg.org/", source_name: "Catholic Charities Diocese of Harrisburg", source_type: "faith_based_nonprofit", phone: "717-657-4804", address: "939 E Park Dr Suite 102, Harrisburg, PA 17111", zip: "17111", desc: "Catholic Charities — Diocese of Harrisburg (covers 15 Central PA counties: Adams, Cumberland, Dauphin, Franklin, Lancaster, Lebanon, Mifflin, Northumberland, Perry, Snyder, Union, York + 3 more); counseling, immigration & refugee services, pregnancy support, residential maternity, foster care, parish social ministry. Veterans served regardless of faith." },
  { section: "CCH", title: "Diocese of Allentown Catholic Charities", cat: "family-support", sub: "Family Counseling", city: "Allentown", website_url: "https://www.catholiccharitiesad.org/", source_name: "Catholic Charities Diocese of Allentown", source_type: "faith_based_nonprofit", phone: "610-435-1541", address: "900 S Woodward St, Allentown, PA 18103", zip: "18103", desc: "Catholic Charities — Diocese of Allentown (covers Berks, Carbon, Lehigh, Northampton, Schuylkill counties); counseling, food pantries, homelessness prevention, immigration & refugee services, adoption, pregnancy support, senior services, prison ministry. Veterans and military families served regardless of religion." },
  { section: "CCH", title: "Diocese of Scranton Catholic Social Services", cat: "family-support", sub: "Family Counseling", city: "Scranton", website_url: "https://www.cssdioceseofscranton.org/", source_name: "Catholic Social Services Diocese of Scranton", source_type: "faith_based_nonprofit", phone: "570-207-2283", address: "33 E Olive St, Scranton, PA 18509", zip: "18509", desc: "Catholic Social Services — Diocese of Scranton (covers 11 NEPA counties: Bradford, Lackawanna, Luzerne, Lycoming, Monroe, Pike, Sullivan, Susquehanna, Tioga, Wayne, Wyoming); counseling, St Joseph's Mercy Center day shelter, St Anthony's Haven, food pantries, refugee resettlement, pregnancy services, parish ministry. Veterans served regardless of religion." },
  { section: "CCH", title: "Diocese of Erie Catholic Charities Counseling Services", cat: "family-support", sub: "Family Counseling", city: "Erie", website_url: "https://www.eriercd.org/socserv.html", source_name: "Diocese of Erie — Catholic Charities Counseling Service", source_type: "faith_based_nonprofit", phone: "814-456-2091", address: "329 W 10th St, Erie, PA 16502", zip: "16502", desc: "Catholic Charities Counseling Services — Diocese of Erie (covers 13 NW PA counties: Cameron, Clarion, Clearfield, Crawford, Elk, Erie, Forest, Jefferson, McKean, Mercer, Potter, Venango, Warren); professional outpatient counseling (individual, couples, family, child, group), DDAP-licensed substance-use treatment, prison ministry, pregnancy & adoption support. Veterans served regardless of religion." },
  { section: "CCH", title: "Diocese of Altoona-Johnstown Catholic Charities", cat: "family-support", sub: "Family Counseling", city: "Hollidaysburg", website_url: "https://www.catholiccharitiesaj.org/", source_name: "Catholic Charities Diocese of Altoona-Johnstown", source_type: "faith_based_nonprofit", phone: "814-695-3478", address: "1 Apostles Way, Hollidaysburg, PA 16648", zip: "16648", desc: "Catholic Charities — Diocese of Altoona-Johnstown (covers 8 South-Central PA counties: Bedford, Blair, Cambria, Centre, Clinton, Fulton, Huntingdon, Somerset); counseling, immigration services, parish-based social ministry, emergency assistance, refugee resettlement, adoption services. Veterans and military families welcome regardless of religion." },

  // ======================== UNITED WAY — 8 ========================
  { section: "UW", title: "United Way of Greater Philadelphia & Southern New Jersey", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Philadelphia", website_url: "https://www.unitedforimpact.org/", source_name: "United Way of Greater Philadelphia & Southern NJ", source_type: "nonprofit_organization", phone: "215-665-2500", address: "1709 Benjamin Franklin Pkwy, Philadelphia, PA 19103", zip: "19103", desc: "United Way of Greater Philadelphia & Southern NJ — region's largest community-impact nonprofit; funds 200+ partner agencies in basic-needs/financial empowerment/education across 9 PA & NJ counties; runs PA 211 SE region, free tax-prep coalition (Campaign for Working Families), college-access programs. Veterans and families connect via 211 to vetted local agencies." },
  { section: "UW", title: "United Way of Southwestern Pennsylvania", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Pittsburgh", website_url: "https://uwswpa.org/", source_name: "United Way of Southwestern Pennsylvania", source_type: "nonprofit_organization", phone: "412-456-6700", address: "1250 Penn Ave, Pittsburgh, PA 15222", zip: "15222", desc: "United Way of Southwestern Pennsylvania — community-impact nonprofit serving Allegheny, Westmoreland, Fayette, Butler counties; funds 200+ partner agencies, runs SWPA 211 (Get Connected), free tax-prep, BRIDGES financial coaching, Be There summer learning. Veterans connect via 211 to vetted partners (housing, food, behavioral health, employment)." },
  { section: "UW", title: "United Way of the Capital Region", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Enola", website_url: "https://www.uwcr.org/", source_name: "United Way of the Capital Region", source_type: "nonprofit_organization", phone: "717-732-0700", address: "2235 Millennium Way, Enola, PA 17025", zip: "17025", desc: "United Way of the Capital Region — community-impact nonprofit serving Cumberland, Dauphin, Perry counties; funds 50+ partner agencies in basic-needs/health/education/financial-empowerment, runs Capital Region 211, free tax-prep coalition (Money in Your Pocket), school-readiness Imagination Library. Veterans connect via 211 to vetted partners." },
  { section: "UW", title: "United Way of the Greater Lehigh Valley", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Allentown", website_url: "https://www.unitedwayglv.org/", source_name: "United Way of the Greater Lehigh Valley", source_type: "nonprofit_organization", phone: "610-758-8010", address: "1110 American Pkwy NE Suite F-130, Allentown, PA 18109", zip: "18109", desc: "United Way of the Greater Lehigh Valley — community-impact nonprofit serving Lehigh, Northampton + western NJ Warren county; funds 60+ partner agencies in education/income/health, runs Lehigh Valley 211 region, Community Schools (in-school wraparound), Real-Time Resources food/diaper distribution. Veterans connect via 211." },
  { section: "UW", title: "United Way of Berks County", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Reading", website_url: "https://www.uwberks.org/", source_name: "United Way of Berks County", source_type: "nonprofit_organization", phone: "610-685-4571", address: "501 Washington St Suite 700, Reading, PA 19601", zip: "19601", desc: "United Way of Berks County — community-impact nonprofit serving Berks County; funds 35+ partner agencies, runs Ready.Set.READ! literacy, BAVA Berks Alliance for Veteran Activities partnership for vet referrals, free tax-prep, financial coaching, Berks 211 region. Veteran-friendly via partner network." },
  { section: "UW", title: "United Way of Lancaster County", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Lancaster", website_url: "https://www.uwlanc.org/", source_name: "United Way of Lancaster County", source_type: "nonprofit_organization", phone: "717-394-0731", address: "630 Janet Ave, Lancaster, PA 17601", zip: "17601", desc: "United Way of Lancaster County — community-impact nonprofit serving Lancaster County; funds 40+ partner agencies in education/income/health, runs Lancaster Cares disaster recovery, financial-stability initiative, free tax-prep coalition (CASH Lancaster), Lancaster 211. Veterans served via partner network including Water Street Mission, COBYS, Lancaster County Council of Churches." },
  { section: "UW", title: "United Way of Erie County", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Erie", website_url: "https://unitedwayerie.org/", source_name: "United Way of Erie County", source_type: "nonprofit_organization", phone: "814-456-2937", address: "420 W 6th St, Erie, PA 16507", zip: "16507", desc: "United Way of Erie County — community-impact nonprofit serving Erie County; funds 30+ partner agencies, runs Community Schools initiative (in-school wraparound for 24 schools), free tax-prep coalition, Code Erie alert system, Erie 211 region. Veterans connect via 211 to local vet-friendly partners." },
  { section: "UW", title: "United Way of Wyoming Valley", cat: "community-support", sub: "Volunteer & Mission-Based Community", city: "Wilkes-Barre", website_url: "https://www.unitedwaywb.org/", source_name: "United Way of Wyoming Valley", source_type: "nonprofit_organization", phone: "570-829-6711", address: "100 N Pennsylvania Ave Suite 200, Wilkes-Barre, PA 18701", zip: "18701", desc: "United Way of Wyoming Valley — community-impact nonprofit serving Luzerne County; funds 25+ partner agencies in education/income/health, runs Hunger-Free Backpack Program, Poverty-to-Possibility initiative, free tax-prep, NEPA 211 region. Veterans connect via 211 to vet-friendly partners (CEO/Weinberg Food Bank, Catholic Social Svcs Scranton)." },

  // ======================== GOODWILL — 3 ========================
  { section: "GW", title: "Goodwill of Southwestern Pennsylvania", cat: "employment", sub: "Vocational Rehabilitation", city: "Pittsburgh", website_url: "https://www.goodwillswpa.org/", source_name: "Goodwill of Southwestern Pennsylvania", source_type: "nonprofit_organization", phone: "412-481-9005", address: "118 52nd St, Pittsburgh, PA 15201", zip: "15201", desc: "Goodwill of Southwestern Pennsylvania — workforce development nonprofit serving 17 SW PA counties; 39 retail stores fund free job training (Goodwill Center skills training in IT, healthcare, manufacturing, customer service), supported employment for people with disabilities, veteran services, financial literacy, GED prep. Veteran-priority Project SEARCH (transition-age youth)." },
  { section: "GW", title: "Goodwill Keystone Area", cat: "employment", sub: "Vocational Rehabilitation", city: "Lancaster", website_url: "https://www.goodwillkeystone.org/", source_name: "Goodwill Keystone Area", source_type: "nonprofit_organization", phone: "717-394-0647", address: "1150 Church Rd, Lancaster, PA 17601", zip: "17601", desc: "Goodwill Keystone Area — workforce nonprofit serving 22 Central & Eastern PA counties (Lancaster, York, Berks, Lebanon, Schuylkill, Dauphin, Cumberland, Adams, Franklin + 13 more); 38 retail stores fund free job training, supported employment for people with disabilities, mission services for adults with barriers to employment including veterans transitioning out of service." },
  { section: "GW", title: "Goodwill of Southern Pennsylvania", cat: "employment", sub: "Vocational Rehabilitation", city: "Camp Hill", website_url: "https://www.goodwillsp.org/", source_name: "Goodwill of Southern Pennsylvania", source_type: "nonprofit_organization", phone: "717-737-3477", address: "1840 Gettysburg Rd, Camp Hill, PA 17011", zip: "17011", desc: "Goodwill of Southern Pennsylvania — workforce nonprofit serving Adams, Franklin, Fulton, Huntingdon, Mifflin, Juniata counties; retail stores fund free job training (food service, retail, custodial, IT essentials), supported employment, GED, financial literacy. Veterans accepted with priority for Skills2Work transition program." },

  // ======================== HABITAT FOR HUMANITY — 4 ========================
  { section: "HAB", title: "Habitat for Humanity Philadelphia", cat: "housing", sub: "Home Ownership", city: "Philadelphia", website_url: "https://www.habitatphiladelphia.org/", source_name: "Habitat for Humanity Philadelphia", source_type: "nonprofit_organization", phone: "215-765-6000", address: "1829 N 19th St, Philadelphia, PA 19121", zip: "19121", desc: "Habitat for Humanity Philadelphia — affordable-homeownership nonprofit; new-build & home-rehabilitation programs for income-qualified Philadelphians (30-80% AMI), Veteran Build days, no-interest Habitat mortgages, home-repair program for senior + disabled homeowners (including veterans), Aging-in-Place modifications, ReStore retail to fund mission. Vet-priority Veterans Build initiative." },
  { section: "HAB", title: "Habitat for Humanity of Greater Pittsburgh", cat: "housing", sub: "Home Ownership", city: "Pittsburgh", website_url: "https://www.habitatpittsburgh.org/", source_name: "Habitat for Humanity of Greater Pittsburgh", source_type: "nonprofit_organization", phone: "412-243-6470", address: "200 Spahr St, Pittsburgh, PA 15232", zip: "15232", desc: "Habitat for Humanity of Greater Pittsburgh — affordable-homeownership nonprofit serving Allegheny County; new-build & home-rehab partnerships, no-interest Habitat mortgages, A Brush With Kindness home-preservation, Aging in Place modifications for seniors/disabled, Veterans Build program. ReStore retail funds mission. Vet-priority intake for transitioning service-members." },
  { section: "HAB", title: "Habitat for Humanity of the Lehigh Valley", cat: "housing", sub: "Home Ownership", city: "Allentown", website_url: "https://www.habitatlv.org/", source_name: "Habitat for Humanity of the Lehigh Valley", source_type: "nonprofit_organization", phone: "610-776-7737", address: "309 W Susquehanna St, Allentown, PA 18103", zip: "18103", desc: "Habitat for Humanity of the Lehigh Valley — affordable-homeownership nonprofit serving Lehigh & Northampton counties; new-build & rehab partnerships, no-interest Habitat mortgages, home-repair for seniors/disabled (including veterans), Critical Home Repair grants, Veterans Build, ReStore retail. Vet-priority intake & coordination with Allentown VA OPC + Wilkes-Barre VAMC." },
  { section: "HAB", title: "Habitat for Humanity of Berks County", cat: "housing", sub: "Home Ownership", city: "Reading", website_url: "https://www.habitatberks.org/", source_name: "Habitat for Humanity of Berks County", source_type: "nonprofit_organization", phone: "610-373-2415", address: "462 Park Ave, Reading, PA 19611", zip: "19611", desc: "Habitat for Humanity of Berks County — affordable-homeownership nonprofit serving Berks County; new-build & rehab partnerships, no-interest Habitat mortgages, Aging in Place + Critical Home Repair for seniors/disabled, Veterans Build initiative, ReStore retail. Vet-priority intake; coordinates with Lebanon VAMC for HUD-VASH wraparound." },

  // ======================== MAJOR HOSPITAL SYSTEMS — 6 ========================
  { section: "HSP", title: "Penn Medicine (University of Pennsylvania Health System)", cat: "healthcare", sub: "Specialty Care", city: "Philadelphia", website_url: "https://www.pennmedicine.org/", source_name: "Penn Medicine / University of Pennsylvania Health System", source_type: "academic_health_system", phone: "800-789-7366", address: "3400 Civic Center Blvd, Philadelphia, PA 19104", zip: "19104", desc: "Penn Medicine — University of Pennsylvania Health System; 6 hospitals (HUP, Pennsylvania Hospital, Presbyterian, Princeton, Chester County, Lancaster General), 3,000+ physicians; major academic referral center for cardiology, oncology (Abramson), neurology, transplant. Veterans use as community-care referral from Phila VAMC for specialty services Penn provides under VA Choice/MISSION Act." },
  { section: "HSP", title: "Lehigh Valley Health Network (LVHN)", cat: "healthcare", sub: "Specialty Care", city: "Allentown", website_url: "https://www.lvhn.org/", source_name: "Lehigh Valley Health Network", source_type: "regional_health_system", phone: "888-402-5846", address: "1200 S Cedar Crest Blvd, Allentown, PA 18103", zip: "18103", desc: "Lehigh Valley Health Network — Eastern PA regional system; 13 hospitals + 250+ outpatient sites across Lehigh, Northampton, Berks, Carbon, Monroe, Schuylkill counties; cancer (LVHN Cancer Institute), heart, neuroscience, trauma (Level I). Veterans use as community-care referral from Allentown VA OPC + Wilkes-Barre VAMC under VA MISSION Act." },
  { section: "HSP", title: "Allegheny Health Network (AHN)", cat: "healthcare", sub: "Specialty Care", city: "Pittsburgh", website_url: "https://www.ahn.org/", source_name: "Allegheny Health Network", source_type: "regional_health_system", phone: "412-359-3131", address: "4800 Friendship Ave, Pittsburgh, PA 15224", zip: "15224", desc: "Allegheny Health Network — Western PA & WV regional system (Highmark Health subsidiary); 14 hospitals (Allegheny General, West Penn, Forbes, Jefferson, St Vincent Erie + 9 more), 2,600 physicians; heart, cancer, neuroscience, women's health. Veterans use as community-care referral from VA Pittsburgh Healthcare under MISSION Act." },
  { section: "HSP", title: "Tower Health", cat: "healthcare", sub: "Specialty Care", city: "West Reading", website_url: "https://towerhealth.org/", source_name: "Tower Health", source_type: "regional_health_system", phone: "484-628-8000", address: "420 S 5th Ave, West Reading, PA 19611", zip: "19611", desc: "Tower Health — multi-hospital regional system serving Berks/Chester/Phoenixville/Pottstown areas; flagship Reading Hospital (Level I trauma center for Berks region), St Christopher's Hospital for Children (Phila), 75+ outpatient & specialty sites. Veterans use as community-care referral from Lebanon VAMC + Coatesville VAMC under MISSION Act." },
  { section: "HSP", title: "WellSpan Health", cat: "healthcare", sub: "Specialty Care", city: "York", website_url: "https://www.wellspan.org/", source_name: "WellSpan Health", source_type: "regional_health_system", phone: "717-851-2121", address: "1001 S George St, York, PA 17403", zip: "17403", desc: "WellSpan Health — South Central PA & Northern MD regional system; 8 hospitals (York, Gettysburg, Chambersburg, Ephrata, Good Samaritan/Lebanon, Surgery & Rehab/York, Waynesboro, Philhaven behavioral) + 220 outpatient sites; cancer, cardiac, behavioral health (Philhaven). Veterans use as community-care referral from Lebanon VAMC under MISSION Act." },
  { section: "HSP", title: "Penn State Health Milton S. Hershey Medical Center", cat: "healthcare", sub: "Specialty Care", city: "Hershey", website_url: "https://www.pennstatehealth.org/", source_name: "Penn State Health", source_type: "academic_health_system", phone: "717-531-8521", address: "500 University Dr, Hershey, PA 17033", zip: "17033", desc: "Penn State Health — Hershey-headquartered academic system anchored by Penn State Health Milton S. Hershey Medical Center (Level I adult & pediatric trauma); also includes St Joseph Medical Center Reading, Holy Spirit, Hampden, Lancaster Medical Centers, Penn State Cancer Institute, Penn State Children's Hospital. Veterans use as community-care referral from Lebanon VAMC under MISSION Act." },

  // ======================== MENTAL HEALTH — 6 ========================
  { section: "MH", title: "Mental Health Association of Southeastern PA (MHASP)", cat: "mental-health", sub: "Counseling & Therapy", city: "Philadelphia", website_url: "https://www.mhasp.org/", source_name: "Mental Health Association of Southeastern Pennsylvania", source_type: "nonprofit_organization", phone: "215-751-1800", address: "1211 Chestnut St 11th Fl, Philadelphia, PA 19107", zip: "19107", desc: "MHASP — region's leading mental-health advocacy & service nonprofit serving Phila, Bucks, Chester, Delaware, Montgomery counties; certified peer specialists, recovery-oriented training, Compeer friendship program, family education, system-navigation help, mental-health hotline. Veterans served alongside civilians; partners with Phila VAMC outreach." },
  { section: "MH", title: "Mental Health Association of Northeastern PA", cat: "mental-health", sub: "Counseling & Therapy", city: "Pittston", website_url: "https://mhanp.org/", source_name: "Mental Health Association of Northeastern Pennsylvania", source_type: "nonprofit_organization", phone: "570-823-3437", address: "260 Pierce St Suite 200, Kingston, PA 18704", zip: "18704", desc: "MHA NEPA — mental-health advocacy & service nonprofit serving 6 NEPA counties (Lackawanna, Luzerne, Susquehanna, Wayne, Wyoming, Bradford); peer support, family education, suicide-prevention training (QPR/safeTALK), system navigation, school-based programs, Working Order job-readiness, MHA Information & Referral. Veteran-friendly; partners with Wilkes-Barre VAMC." },
  { section: "MH", title: "Mental Health Partnerships", cat: "mental-health", sub: "Peer Support", city: "Philadelphia", website_url: "https://www.mhpartnerships.org/", source_name: "Mental Health Partnerships", source_type: "nonprofit_organization", phone: "267-507-3870", address: "100 S Broad St 17th Fl, Philadelphia, PA 19110", zip: "19110", desc: "Mental Health Partnerships — peer-led behavioral-health nonprofit serving Phila & SE PA region; certified peer specialist services (CPS workforce home), wellness recovery action plan (WRAP), Hearing Voices Network, supported education/employment, advocacy. Vets served via certified peers including veteran-CPS staff." },
  { section: "MH", title: "NAMI Keystone Pennsylvania", cat: "mental-health", sub: "Family Support (Mental Health)", city: "Pittsburgh", website_url: "https://namikeystonepa.org/", source_name: "NAMI Keystone Pennsylvania", source_type: "nonprofit_organization", phone: "412-366-3788", address: "105 Braunlich Dr Suite 200, Pittsburgh, PA 15237", zip: "15237", desc: "NAMI Keystone Pennsylvania — National Alliance on Mental Illness affiliate covering 36 counties in Western & Central PA; free Family-to-Family + Peer-to-Peer + Basics + Homefront (military families) education programs, support groups, NAMI Helpline (412-366-3788), Crisis Intervention Team (CIT) trainings for police, advocacy. Homefront program serves military families." },
  { section: "MH", title: "NAMI Main Line PA", cat: "mental-health", sub: "Family Support (Mental Health)", city: "Radnor", website_url: "https://namimainlinepa.org/", source_name: "NAMI Main Line Pennsylvania", source_type: "nonprofit_organization", phone: "610-687-1320", address: "320 King of Prussia Rd, Radnor, PA 19087", zip: "19087", desc: "NAMI Main Line PA — National Alliance on Mental Illness affiliate serving Western Phila suburbs (Delaware, Chester, Montgomery counties); free Family-to-Family, Peer-to-Peer, Homefront (military), Ending the Silence school programs, support groups, helpline & system navigation. Homefront (military families) cohort runs annually; veterans welcome at all programs." },
  { section: "MH", title: "Penn Foundation", cat: "mental-health", sub: "Counseling & Therapy", city: "Sellersville", website_url: "https://www.pennfoundation.org/", source_name: "Penn Foundation", source_type: "nonprofit_healthcare_system", phone: "215-257-6551", address: "807 Lawn Ave, Sellersville, PA 18960", zip: "18960", desc: "Penn Foundation — Mennonite-affiliated behavioral health nonprofit serving Bucks/Mont/Lehigh/Berks counties; outpatient mental-health (children/adults/families), psychiatric medication management, addictions treatment (DDAP-licensed SUD), case management, supported housing. Veterans accepted; coordinates with Coatesville VAMC + Allentown VA OPC." },

  // ======================== SUBSTANCE RECOVERY — 4 ========================
  { section: "REC", title: "PA Department of Drug & Alcohol Programs (DDAP)", cat: "substance-recovery", sub: "Recovery Support Services", city: "Harrisburg", website_url: "https://www.ddap.pa.gov/Pages/default.aspx", source_name: "PA Department of Drug and Alcohol Programs", source_type: "state_government_agency", phone: "717-783-8200", address: "02 Kline Plaza, Harrisburg, PA 17104", zip: "17104", desc: "PA DDAP — cabinet-level state agency overseeing prevention/intervention/treatment/recovery for substance use disorders in PA; licenses 800+ SUD treatment providers, funds 47 Single County Authorities (SCAs) that connect Pennsylvanians to local SUD treatment, oversees PA Get Help Now Helpline. Veterans referred to PA's SUD network including DDAP-VA partnerships." },
  { section: "REC", title: "PA Get Help Now Helpline (DDAP)", cat: "substance-recovery", sub: "Crisis Stabilization", city: "Harrisburg", website_url: "https://www.ddap.pa.gov/get-help-now/Pages/Get-Help-Now.aspx", source_name: "PA DDAP — Get Help Now", source_type: "state_government_agency", phone: "1-800-662-4357", address: "02 Kline Plaza, Harrisburg, PA 17104", zip: "17104", desc: "PA Get Help Now Helpline — DDAP-funded 24/7/365 toll-free helpline (1-800-662-HELP); free, confidential connection to SUD treatment for any Pennsylvanian or family member, immediate referral to local Single County Authority (SCA) intake & treatment placement, Spanish-speaking counselors. Veterans referred to VA SUD options + civilian DDAP-licensed providers." },
  { section: "REC", title: "Alcoholics Anonymous Eastern PA Intergroup (AAEPI)", cat: "substance-recovery", sub: "Peer Recovery Groups", city: "Philadelphia", website_url: "https://aaepi.org/", source_name: "Alcoholics Anonymous Eastern PA Intergroup", source_type: "peer_support_organization", phone: "215-923-7900", address: "444 N 3rd St Suite 410, Philadelphia, PA 19123", zip: "19123", desc: "AA Eastern PA Intergroup — central service office for AA in 11-county Eastern PA region (Phila, Bucks, Chester, Delaware, Montgomery, Berks, Lehigh, Northampton + 3 more); 24/7 helpline (215-923-7900), online & in-person meeting finder for 1,500+ weekly meetings, hospital/institutional commitments, beginners meetings. Free peer-recovery community open to veterans." },
  { section: "REC", title: "ProRehab — PA Outpatient Drug & Alcohol Treatment", cat: "substance-recovery", sub: "Outpatient Recovery", city: "Pittsburgh", website_url: "https://prorehab.com/", source_name: "ProRehab", source_type: "healthcare_organization", phone: "1-833-787-2632", desc: "ProRehab — PA-licensed outpatient SUD provider; intensive outpatient (IOP), partial hospitalization (PHP), medication-assisted treatment (MAT — Suboxone/Vivitrol), individual & group counseling, telehealth options. Multi-location across PA. Accepts most insurance + DDAP funding; veterans accepted alongside VA referrals (TRICARE/VA Choice). Online intake & assessment available." },

  // ======================== GOVERNMENT & COMMUNITY MAINSTREAM — 7 ========================
  { section: "GOV", title: "PA 211 — Statewide Information & Referral", cat: "community-support", sub: "Veteran Outreach Programs", website_url: "https://www.pa211.org/", source_name: "PA 211 (United Ways of PA + Council of Independent Living)", source_type: "statewide_information_referral", phone: "211", desc: "PA 211 — statewide free 24/7 information & referral service operated by United Way regions + community partners; dial 211 or text PA + ZIP to 898211; connects to vetted local resources for housing, food, utility assistance, healthcare, mental-health, employment, childcare, legal aid, and veteran services. Multilingual operators (170+ languages). Veterans connected to local VSO + VA + community partners." },
  { section: "GOV", title: "PA Department of Aging", cat: "community-support", sub: "Veteran Outreach Programs", city: "Harrisburg", website_url: "https://www.aging.pa.gov/", source_name: "PA Department of Aging", source_type: "state_government_agency", phone: "717-783-1550", address: "555 Walnut St 5th Fl, Harrisburg, PA 17101", zip: "17101", desc: "PA Department of Aging — cabinet-level state agency overseeing services for 3+ million Pennsylvanians 60+; funds 52 county Area Agencies on Aging (AAAs), administers PA APPRISE (SHIP), Caregiver Support Program, Older Adult Protective Services, PA MEDI (legal counseling), Senior Community Service Employment, LIFE program for nursing-home-eligible seniors. Veterans 60+ access via county AAA." },
  { section: "GOV", title: "PA Department of Health", cat: "healthcare", sub: "Preventive Care & Wellness", city: "Harrisburg", website_url: "https://www.health.pa.gov/", source_name: "PA Department of Health", source_type: "state_government_agency", phone: "1-877-724-3258", address: "625 Forster St, Harrisburg, PA 17120", zip: "17120", desc: "PA Department of Health — cabinet-level state agency for public health; runs WIC, immunizations, chronic-disease prevention/control, communicable disease (incl. HIV/STD/TB), county/municipal health-dept oversight, vital records (birth/death certificates needed for veteran benefits), Cancer Registry, Maternal Child Health programs. Free or low-cost services available to veterans and families." },
  { section: "GOV", title: "PA Treasury", cat: "financial", sub: "Veteran Relief Funds", city: "Harrisburg", website_url: "https://patreasury.gov/", source_name: "PA Treasury Department", source_type: "state_government_agency", phone: "717-787-2465", address: "613 N Front St, Harrisburg, PA 17101", zip: "17101", desc: "PA Treasury Department — independent state office managing PA's funds; PA 529 College Savings, PA ABLE (Achieving Better Life Experience for people with disabilities), Keystone Scholars, Unclaimed Property (PA holds ~$4B in unclaimed funds — vets often have unclaimed military allotments), property tax/rent rebate processing for seniors & disabled veterans (50%+ disability)." },
  { section: "GOV", title: "AARP Pennsylvania", cat: "community-support", sub: "Senior / Retired Veteran Social Programs", city: "Harrisburg", website_url: "https://states.aarp.org/pennsylvania/", source_name: "AARP Pennsylvania", source_type: "national_nonprofit_state_office", phone: "866-389-5654", address: "30 N 3rd St Suite 750, Harrisburg, PA 17101", zip: "17101", desc: "AARP Pennsylvania — state office of AARP serving 1.8 million PA members 50+; advocacy on Medicare/Social Security/caregiving/utility costs/long-term care, free educational events, Driver Safety classes (auto-insurance discount), Tax-Aide free tax prep (200+ PA sites), Fraud Watch Network. Veterans 50+ benefit from member discounts incl. on USAA + The Hartford auto/home insurance." },
  { section: "GOV", title: "IRS VITA — Free Tax Preparation Locator", cat: "financial", sub: "Tax Preparation", website_url: "https://irs.treasury.gov/freetaxprep/", source_name: "IRS Volunteer Income Tax Assistance", source_type: "federal_program", phone: "1-800-906-9887", desc: "IRS VITA / TCE — Volunteer Income Tax Assistance & Tax Counseling for the Elderly; free federal & state tax prep for households earning under $67,000, persons with disabilities, limited-English speakers, and people 60+ (TCE). 200+ VITA sites in PA (United Ways, Goodwill, faith-based partners, AARP Tax-Aide). Veterans can claim tax-free disability compensation, deductions for moving expenses." },
  { section: "GOV", title: "PA State Civil Service Commission — Veterans Preference", cat: "employment", sub: "State Employment", city: "Harrisburg", website_url: "https://www.scsc.pa.gov/", source_name: "PA State Civil Service Commission", source_type: "state_government_agency", phone: "717-783-3058", address: "320 Market St, Harrisburg, PA 17101", zip: "17101", desc: "PA State Civil Service Commission — administers PA's merit-based state employment system; veterans receive 10-point preference on civil-service exams (15 points for service-connected disabled), priority placement on hiring lists, expedited consideration. SCSC processes ~12,000 PA state-job applications annually; vets must submit DD-214 with application." },

  // ======================== FAMILY / CAREGIVER MAINSTREAM — 4 ========================
  { section: "FAM", title: "Family Service Association of Bucks County", cat: "family-support", sub: "Family Counseling", city: "Langhorne", website_url: "https://www.fsabc.org/", source_name: "Family Service Association of Bucks County", source_type: "nonprofit_organization", phone: "215-757-6916", address: "4 Cornerstone Dr Suite B, Langhorne, PA 19047", zip: "19047", desc: "Family Service Association of Bucks County — 70-year nonprofit serving Bucks County families; outpatient counseling (individual/couples/family/child), DV-victim services & shelter (A Woman's Place), trauma counseling, parent-child interaction therapy, financial counseling, Veterans 4 Veterans peer-support program for Bucks vets. Veteran families served regardless of income." },
  { section: "FAM", title: "Cradles to Crayons Philadelphia", cat: "family-support", sub: "Childcare Assistance", city: "Philadelphia", website_url: "https://www.cradlestocrayons.org/philadelphia/", source_name: "Cradles to Crayons", source_type: "national_nonprofit", phone: "215-836-0958", address: "1900 N 2nd St, Philadelphia, PA 19122", zip: "19122", desc: "Cradles to Crayons Philadelphia — free children's clothing & essentials (shoes, school supplies, hygiene, books, toys) for kids 0-12 living in low-income households; distributed via 200+ partner agencies (schools, shelters, churches). Single intake forms at participating agencies. Serves Philadelphia, Bucks, Chester, Delaware, Montgomery families including veteran families with children." },
  { section: "FAM", title: "Operation Warm — National HQ", cat: "family-support", sub: "Parenting Programs", city: "Glen Mills", website_url: "https://www.operationwarm.org/", source_name: "Operation Warm", source_type: "national_nonprofit", phone: "484-200-8260", address: "23 Garfield Way, Glen Mills, PA 19342", zip: "19342", desc: "Operation Warm — Glen Mills PA-headquartered national nonprofit; manufactures & distributes brand-new winter coats, shoes, books to children in need via partnership with police departments, schools, churches, community orgs. 5+ million coats delivered. PA program: 100+ partner sites distribute coats to kids of veteran families struggling financially." },
  { section: "FAM", title: "Penn State Extension", cat: "family-support", sub: "Parenting Programs", city: "University Park", website_url: "https://extension.psu.edu/", source_name: "Penn State Extension", source_type: "land_grant_university_extension", phone: "877-345-0691", address: "323 Agricultural Administration Bldg, University Park, PA 16802", zip: "16802", desc: "Penn State Extension — Penn State's land-grant outreach in all 67 PA counties; 4-H youth development (180,000+ youth), Better Kid Care training, Strong Families/Healthy Couples program, Master Gardener, Master Watershed Steward, agricultural & food-safety education, Diverse Voices podcast. Free or low-cost classes for veterans & families especially in rural counties." },

  // ======================== NATIONAL VET ORG FINDERS — 4 ========================
  { section: "VET", title: "VFW Post Locator (Veterans of Foreign Wars)", cat: "community-support", sub: "VFW Posts", website_url: "https://www.vfw.org/find-a-post", source_name: "Veterans of Foreign Wars of the United States", source_type: "veteran_service_organization", phone: "816-756-3390", desc: "VFW Find-a-Post locator — search 5,300+ VFW Posts nationwide including 400+ across PA in every county; combat-veteran community, free VA claims help by VFW-accredited service officers, scholarships (Voice of Democracy), Buddy Poppy program, post halls offer venues for vet gatherings, family programs. Eligibility: U.S. military service in foreign war or overseas combat zone." },
  { section: "VET", title: "AMVETS Post Locator", cat: "community-support", sub: "Veteran Service Organizations", website_url: "https://amvets.org/find-a-post/", source_name: "American Veterans (AMVETS) National HQ", source_type: "veteran_service_organization", phone: "877-726-8387", desc: "AMVETS Find-a-Post locator — search AMVETS posts nationwide including 50+ in PA in major + secondary cities; veteran community, free VA claims help by AMVETS-accredited National Service Officers, scholarships, AMVETS National Service Foundation grants, post halls for veteran gatherings, ladies auxiliary, Sons of AMVETS. Eligibility: all honorable U.S. military service since 9/15/1940." },
  { section: "VET", title: "Iraq and Afghanistan Veterans of America (IAVA)", cat: "community-support", sub: "Veteran Service Organizations", website_url: "https://iava.org/", source_name: "Iraq and Afghanistan Veterans of America", source_type: "national_veteran_nonprofit", phone: "212-982-9699", desc: "IAVA — first & largest nonprofit serving post-9/11 veterans (Iraq, Afghanistan, OCO eras); free Quick Reaction Force (QRF) one-on-one case management for crisis (mental health/employment/finances/healthcare/benefits/legal), Combat to Cure scholarships, advocacy on burn-pit/PACT Act/PFAS-toxic-exposure, women veterans/LGBTQ+ vets initiatives. Serves PA post-9/11 vets nationally via virtual + member events." },
  { section: "VET", title: "Code of Support Foundation", cat: "community-support", sub: "Veteran Outreach Programs", website_url: "https://www.codeofsupport.org/", source_name: "Code of Support Foundation", source_type: "national_veteran_nonprofit", phone: "703-562-0699", desc: "Code of Support Foundation — national nonprofit providing one-on-one case-management to post-9/11 service-members, veterans, and families across critical-need areas (employment, financial, family, behavioral health, education, benefits, legal, housing); proprietary PATRIOTlink resource database used by 100+ partner orgs. Serves PA veterans nationally via virtual case management." },

  // ======================== YMCA + ADDITIONAL MULTI-SVC — 2 ========================
  { section: "YMCA", title: "Philadelphia Freedom Valley YMCA", cat: "family-support", sub: "Youth Programs", city: "Philadelphia", website_url: "https://www.philaymca.org/", source_name: "Philadelphia Freedom Valley YMCA", source_type: "nonprofit_organization", phone: "215-686-3400", address: "2000 Hamilton St Suite 200, Philadelphia, PA 19130", zip: "19130", desc: "Philadelphia Freedom Valley YMCA — 18-branch YMCA serving Phila + suburban Mont/Chester/Delaware/Bucks counties; child-care, after-school programs, summer camp, swim lessons, fitness centers, senior programs (Active Older Adults), youth sports leagues, Community Schools, Diabetes Prevention. Military-family rates; YMCA's Military Outreach Initiative grants free memberships to active-duty + reserve families." },
  { section: "YMCA", title: "YMCA of the Greater Harrisburg", cat: "family-support", sub: "Youth Programs", city: "Harrisburg", website_url: "https://www.ymcaharrisburg.org/", source_name: "YMCA of the Greater Harrisburg", source_type: "nonprofit_organization", phone: "717-732-3711", address: "4400 Walnut St, Harrisburg, PA 17109", zip: "17109", desc: "YMCA of the Greater Harrisburg — 6-branch YMCA serving Cumberland, Dauphin, Perry counties; child-care, after-school, summer camp (Camp Curtin Y, Hampden Y), swim lessons, family fitness centers, senior wellness, sports leagues, Y Read literacy, Diabetes Prevention. Military Outreach Initiative grants free memberships to active-duty National Guard + Reserve families." },

];

runSeed(ROWS, { state: "PA", commit: COMMIT, scriptName: "seed-pa-p5.ts", urlCheckTimeoutMs: 12000 });
