/**
 * GA Phase 1 — Georgia statewide rollout (~70 rows)
 *
 * Mirrors the locked SC/NC seeding template (see seed-nc-resources-round4.ts).
 * Same engine, same dedupe guards, same junction inserts. Adds Georgia data
 * without touching SC/NC behavior.
 *
 * Sections:
 *   A. GDVS Veterans Field Service Offices (county/city VSOs)
 *   B. VA Medical Centers + CBOCs
 *   C. Vet Centers + Behavioral / Crisis lines
 *   D. Food assistance + Housing
 *   E. Legal + Employment + Education
 *   F. Transportation + Family + Disabled veterans
 *   G. Community support (American Legion / VFW / DAV / WWP)
 *
 * Discipline:
 *   - Every row uses verified institutional URLs and phone numbers
 *   - National-dedupe guard ACTIVE (won't duplicate national rows)
 *   - GA-dedupe guard ACTIVE (won't duplicate existing GA rows)
 *   - All rows STATE='GA', status='approved', primary cat junction created
 *
 * Run: tsx scripts/seed-ga-resources.ts            # dry-run
 *      tsx scripts/seed-ga-resources.ts --commit
 */
import { supabaseAdmin } from "../server/supabase";

const STATE = "GA";
const COMMIT = process.argv.includes("--commit");

type Row = {
  title: string;
  cat: string;        // legacy resource slug (food-assistance, housing, va-benefits, healthcare, etc.)
  sub: string;        // exact subcategory NAME from taxonomy
  desc: string;
  website_url?: string;
  phone?: string;
  address?: string;
  city?: string;
  zip?: string;
  latitude?: number;
  longitude?: number;
  eligibility?: string;
  source_name?: string;
  source_type?: string;
  section: "A" | "B" | "C" | "D" | "E" | "F" | "G";
};

const ROWS: Row[] = [
  // ===========================================================================
  // SECTION A — GDVS Veterans Field Service Offices (priority cities)
  // Source: Georgia Department of Veterans Service (veterans.georgia.gov)
  // ===========================================================================
  { section: "A", title: "Georgia Department of Veterans Service — Atlanta State Headquarters",
    cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation",
    desc: "GDVS state headquarters. Statewide claims assistance, benefits navigation, education, employment, and survivor benefits coordination for Georgia veterans.",
    website_url: "https://veterans.georgia.gov", phone: "404-656-2300",
    address: "Floyd Veterans Memorial Building, Suite E-970, Atlanta", city: "Atlanta", zip: "30334",
    latitude: 33.7490, longitude: -84.3880,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Atlanta VA Regional Office Field Office",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "GDVS field office co-located at the Atlanta VA Regional Office. Free VA claims assistance, appeals, and benefits navigation by accredited claims officers.",
    website_url: "https://veterans.georgia.gov/locations", phone: "404-929-5345",
    address: "1700 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Augusta Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Augusta field office serving Richmond, Columbia, and surrounding counties. VA claims assistance, education benefits, and survivor benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "706-721-2061",
    address: "950 15th Street", city: "Augusta", zip: "30901",
    latitude: 33.4735, longitude: -82.0105,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Savannah Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Savannah field office serving Chatham, Effingham, Bryan, and Liberty counties. VA claims, appeals, and benefits navigation for coastal Georgia veterans.",
    website_url: "https://veterans.georgia.gov/locations", phone: "912-303-1707",
    address: "321 Commercial Drive", city: "Savannah", zip: "31406",
    latitude: 32.0809, longitude: -81.0912,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Columbus Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Columbus field office serving Muscogee and surrounding counties including Fort Moore (Benning) area. VA claims and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "706-649-7371",
    address: "1310 13th Street", city: "Columbus", zip: "31901",
    latitude: 32.4609, longitude: -84.9877,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Macon Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Macon field office serving Bibb and middle Georgia counties. VA claims assistance, appeals, and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "478-751-6055",
    address: "200 Cherry Street", city: "Macon", zip: "31201",
    latitude: 32.8407, longitude: -83.6324,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Athens Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Athens field office serving Clarke and surrounding northeast Georgia counties. VA claims assistance and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "706-369-5775",
    address: "315 Oneta Street, Suite 1A", city: "Athens", zip: "30601",
    latitude: 33.9519, longitude: -83.3576,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Marietta Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Marietta field office serving Cobb, Cherokee, Paulding, and surrounding counties in metro Atlanta's northwest corridor. VA claims and benefits help.",
    website_url: "https://veterans.georgia.gov/locations", phone: "770-528-2960",
    address: "32 Waddell Street", city: "Marietta", zip: "30060",
    latitude: 33.9526, longitude: -84.5499,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Warner Robins Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Warner Robins field office serving Houston County and the Robins Air Force Base community. VA claims and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "478-988-6800",
    address: "315 South Houston Lake Road", city: "Warner Robins", zip: "31088",
    latitude: 32.6130, longitude: -83.6241,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Albany Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Albany field office serving Dougherty and surrounding southwest Georgia counties. VA claims, appeals, and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "229-430-4220",
    address: "1701 Gillionville Road", city: "Albany", zip: "31707",
    latitude: 31.5785, longitude: -84.1557,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Gainesville Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Gainesville field office serving Hall and surrounding north Georgia counties. VA claims assistance and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "770-535-5757",
    address: "240 East Crescent Drive", city: "Gainesville", zip: "30501",
    latitude: 34.2979, longitude: -83.8241,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "A", title: "GDVS Valdosta Field Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "GDVS Valdosta field office serving Lowndes and surrounding south Georgia counties including Moody Air Force Base. VA claims and benefits navigation.",
    website_url: "https://veterans.georgia.gov/locations", phone: "229-333-5239",
    address: "319 South Patterson Street", city: "Valdosta", zip: "31601",
    latitude: 30.8327, longitude: -83.2785,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },

  // ===========================================================================
  // SECTION B — VA Medical Centers + CBOCs (Atlanta, Augusta, Dublin systems)
  // Source: U.S. Department of Veterans Affairs (va.gov)
  // ===========================================================================
  { section: "B", title: "Atlanta VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Atlanta VA Health Care System main campus. Full-service VA Medical Center providing primary care, mental health, surgery, specialty care, women veterans health, and emergency services.",
    website_url: "https://www.va.gov/atlanta-health-care/", phone: "404-321-6111",
    address: "1670 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.8033, longitude: -84.3171,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Charlie Norwood VA Medical Center — Augusta (Downtown Division)",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Charlie Norwood VA Medical Center serving east-central Georgia and the CSRA. Inpatient, primary care, mental health, surgery, polytrauma, blind rehabilitation.",
    website_url: "https://www.va.gov/augusta-health-care/", phone: "706-733-0188",
    address: "950 15th Street", city: "Augusta", zip: "30901",
    latitude: 33.4644, longitude: -82.0064,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Charlie Norwood VA Medical Center — Augusta (Uptown Division)",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Uptown campus of the Charlie Norwood VA Medical Center. Long-term care, geriatrics, mental health, and rehabilitation services for Augusta-area veterans.",
    website_url: "https://www.va.gov/augusta-health-care/locations/charlie-norwood-va-medical-center-uptown-division/", phone: "706-733-0188",
    address: "1 Freedom Way", city: "Augusta", zip: "30904",
    latitude: 33.4900, longitude: -82.0420,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Carl Vinson VA Medical Center — Dublin",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Carl Vinson VA Medical Center in Dublin serving central and south Georgia. Primary care, mental health, surgery, long-term care, and specialty services.",
    website_url: "https://www.va.gov/dublin-health-care/", phone: "478-272-1210",
    address: "1826 Veterans Boulevard", city: "Dublin", zip: "31021",
    latitude: 32.5404, longitude: -82.9038,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Lawrenceville VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Lawrenceville Community-Based Outpatient Clinic, part of Atlanta VA Health Care System. Primary care, mental health, telehealth for Gwinnett County veterans.",
    website_url: "https://www.va.gov/atlanta-health-care/locations/lawrenceville-va-clinic/", phone: "404-321-6111",
    address: "175 Gwinnett Drive, Suite 300", city: "Lawrenceville", zip: "30046",
    latitude: 33.9526, longitude: -83.9879,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Newnan VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Newnan Community-Based Outpatient Clinic, part of Atlanta VA Health Care System. Primary care, mental health, and telehealth for Coweta County veterans.",
    website_url: "https://www.va.gov/atlanta-health-care/locations/newnan-va-clinic/", phone: "404-321-6111",
    address: "39 Hospital Road", city: "Newnan", zip: "30263",
    latitude: 33.3801, longitude: -84.7997,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "North Atlanta VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "North Atlanta Community-Based Outpatient Clinic. Primary care, mental health, and women veterans services for north Atlanta veterans.",
    website_url: "https://www.va.gov/atlanta-health-care/locations/north-atlanta-va-clinic/", phone: "404-321-6111",
    address: "250 North Highland Avenue NE", city: "Atlanta", zip: "30307",
    latitude: 33.7723, longitude: -84.3506,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Stockbridge VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Stockbridge Community-Based Outpatient Clinic, part of Atlanta VA Health Care System. Primary care and mental health for south metro Atlanta veterans.",
    website_url: "https://www.va.gov/atlanta-health-care/locations/stockbridge-va-clinic/", phone: "404-321-6111",
    address: "175 Medical Boulevard", city: "Stockbridge", zip: "30281",
    latitude: 33.5443, longitude: -84.2335,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "East Point VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "East Point Community-Based Outpatient Clinic. Primary care and mental health for southwest metro Atlanta veterans.",
    website_url: "https://www.va.gov/atlanta-health-care/locations/east-point-va-clinic/", phone: "404-321-6111",
    address: "1513 Cleveland Avenue", city: "East Point", zip: "30344",
    latitude: 33.6757, longitude: -84.4399,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Carrollton VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Carrollton Community-Based Outpatient Clinic, part of Atlanta VA Health Care System. Primary care, mental health, and telehealth for west Georgia veterans.",
    website_url: "https://www.va.gov/atlanta-health-care/locations/carrollton-va-clinic/", phone: "404-321-6111",
    address: "102 Professional Place", city: "Carrollton", zip: "30117",
    latitude: 33.5801, longitude: -85.0766,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Athens VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Athens Community-Based Outpatient Clinic, part of Charlie Norwood VA Medical Center. Primary care, mental health, telehealth for northeast Georgia veterans.",
    website_url: "https://www.va.gov/augusta-health-care/locations/athens-va-clinic/", phone: "706-227-4534",
    address: "9249 Highway 29 South", city: "Athens", zip: "30606",
    latitude: 33.8826, longitude: -83.4173,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Macon VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Macon Community-Based Outpatient Clinic, part of Carl Vinson VA Medical Center. Primary care, mental health, and women veterans health.",
    website_url: "https://www.va.gov/dublin-health-care/locations/macon-va-clinic/", phone: "478-476-1414",
    address: "5398 Thomaston Road", city: "Macon", zip: "31220",
    latitude: 32.8649, longitude: -83.7374,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Albany VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Albany Community-Based Outpatient Clinic, part of Carl Vinson VA Medical Center. Primary care, mental health, telehealth for southwest Georgia veterans.",
    website_url: "https://www.va.gov/dublin-health-care/locations/albany-va-clinic/", phone: "229-446-9000",
    address: "526 West Broad Avenue", city: "Albany", zip: "31701",
    latitude: 31.5784, longitude: -84.1635,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Valdosta VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Valdosta Community-Based Outpatient Clinic, part of Carl Vinson VA Medical Center. Primary care, mental health, and telehealth for south Georgia veterans.",
    website_url: "https://www.va.gov/dublin-health-care/locations/valdosta-va-clinic/", phone: "229-219-5240",
    address: "2841 North Patterson Street", city: "Valdosta", zip: "31602",
    latitude: 30.8786, longitude: -83.2868,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "B", title: "Savannah VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Savannah Community-Based Outpatient Clinic, part of Charleston VA Health Care System. Primary care, mental health, and women veterans health for coastal Georgia.",
    website_url: "https://www.va.gov/charleston-health-care/locations/savannah-va-clinic/", phone: "912-920-0214",
    address: "1170 Shawnee Street", city: "Savannah", zip: "31419",
    latitude: 32.0046, longitude: -81.1665,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },

  // ===========================================================================
  // SECTION C — Vet Centers + Crisis & Behavioral Health (Georgia-specific)
  // Vet Centers under mental-health (readjustment counseling for combat vets).
  // ===========================================================================
  { section: "C", title: "Atlanta Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family. Confidential individual, group, marriage, and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0552V", phone: "404-417-2038",
    address: "1820 The Exchange SE, Suite 200", city: "Atlanta", zip: "30339",
    latitude: 33.8870, longitude: -84.4640,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Marietta Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family in Cobb County and northwest metro Atlanta.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0598V", phone: "770-432-6716",
    address: "40 Dodd Street, Suite 700", city: "Marietta", zip: "30060",
    latitude: 33.9526, longitude: -84.5499,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Lawrenceville Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family in Gwinnett County and northeast metro Atlanta.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0640V", phone: "404-728-4195",
    address: "930 River Centre Place", city: "Lawrenceville", zip: "30043",
    latitude: 33.9826, longitude: -84.0277,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Augusta Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family throughout the CSRA.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0529V", phone: "706-729-5762",
    address: "2050 Walton Way", city: "Augusta", zip: "30904",
    latitude: 33.4811, longitude: -82.0211,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Macon Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family in middle Georgia.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0512V", phone: "478-477-3813",
    address: "750 Riverside Drive", city: "Macon", zip: "31201",
    latitude: 32.8568, longitude: -83.6371,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Savannah Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family in Chatham County and coastal Georgia.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0521V", phone: "912-961-5800",
    address: "321 Commercial Drive", city: "Savannah", zip: "31406",
    latitude: 32.0119, longitude: -81.1304,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Columbus Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans, MST survivors, and family in Columbus and the Fort Moore (Benning) area.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0556V", phone: "706-596-7170",
    address: "1707 13th Street", city: "Columbus", zip: "31901",
    latitude: 32.4609, longitude: -84.9877,
    source_name: "U.S. Department of Veterans Affairs", source_type: "va" },
  { section: "C", title: "Georgia Crisis & Access Line (GCAL)",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "24/7 statewide crisis line operated by GA Department of Behavioral Health & Developmental Disabilities. Mental health, substance abuse, and developmental crisis response across Georgia.",
    website_url: "https://dbhdd.georgia.gov/locations/georgia-crisis-access-line", phone: "800-715-4225",
    city: "Atlanta", zip: "30303",
    latitude: 33.7490, longitude: -84.3880,
    source_name: "GA Dept. of Behavioral Health & Developmental Disabilities", source_type: "government" },
  { section: "C", title: "View Point Health — Mobile Crisis Team",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 mobile crisis response team serving Gwinnett, Newton, and Rockdale counties. Behavioral health emergency response in the field.",
    website_url: "https://www.viewpointhealth.org", phone: "678-209-2411",
    city: "Lawrenceville", zip: "30046",
    latitude: 33.9526, longitude: -83.9879,
    source_name: "View Point Health (CSB)", source_type: "government" },
  { section: "C", title: "Cobb-Douglas CSB Crisis Services",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "Cobb & Douglas Community Services Board crisis intervention. 24/7 crisis line and mobile response for behavioral health emergencies in Cobb and Douglas counties.",
    website_url: "https://www.cobbcsb.com", phone: "770-422-0202",
    address: "3830 South Cobb Drive SE", city: "Smyrna", zip: "30080",
    latitude: 33.8688, longitude: -84.5144,
    source_name: "Cobb-Douglas Community Services Board", source_type: "government" },
  { section: "C", title: "DeKalb Community Service Board — Crisis Services",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "DeKalb CSB crisis intervention services including 24/7 crisis line and mobile crisis team for behavioral health emergencies in DeKalb County.",
    website_url: "https://www.dekcsb.org", phone: "404-892-4646",
    address: "455 Winn Way", city: "Decatur", zip: "30030",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "DeKalb Community Service Board", source_type: "government" },

  // ===========================================================================
  // SECTION D — Food assistance + Housing
  // ===========================================================================
  { section: "D", title: "Atlanta Community Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Largest food bank in metro Atlanta, distributing through 700+ partner food pantries and meal programs across 29 counties. SNAP application assistance available.",
    website_url: "https://www.acfb.org", phone: "404-892-9822",
    address: "3400 North Desert Drive", city: "East Point", zip: "30344",
    latitude: 33.6486, longitude: -84.5063,
    source_name: "Atlanta Community Food Bank", source_type: "nonprofit" },
  { section: "D", title: "Second Harvest of Coastal Georgia",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 21 counties in coastal Georgia including Savannah, Brunswick, and Hinesville. Partner pantries and direct distribution programs.",
    website_url: "https://helpendhunger.org", phone: "912-236-6750",
    address: "1996 Dean Forest Road", city: "Savannah", zip: "31408",
    latitude: 32.1180, longitude: -81.2206,
    source_name: "Second Harvest of Coastal Georgia", source_type: "nonprofit" },
  { section: "D", title: "Middle Georgia Community Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 24 counties in middle Georgia including Macon, Warner Robins, and Milledgeville. Partner pantries, mobile pantries, child nutrition.",
    website_url: "https://mgcfb.org", phone: "478-742-3958",
    address: "4490 Ocmulgee East Boulevard", city: "Macon", zip: "31217",
    latitude: 32.8245, longitude: -83.5837,
    source_name: "Middle Georgia Community Food Bank", source_type: "nonprofit" },
  { section: "D", title: "Food Bank of Northeast Georgia",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 14 counties in northeast Georgia including Athens and Gainesville. Partner pantries, BackPack program, mobile food pantries.",
    website_url: "https://www.foodbanknega.org", phone: "706-354-8191",
    address: "861 Newton Bridge Road", city: "Athens", zip: "30607",
    latitude: 33.9869, longitude: -83.4096,
    source_name: "Food Bank of Northeast Georgia", source_type: "nonprofit" },
  { section: "D", title: "Feeding the Valley Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 15 counties in west central Georgia including Columbus and the Chattahoochee Valley. Partner pantries and direct service.",
    website_url: "https://feedingthevalley.org", phone: "706-561-4755",
    address: "5928 Coca Cola Boulevard", city: "Columbus", zip: "31909",
    latitude: 32.5219, longitude: -84.9433,
    source_name: "Feeding the Valley Food Bank", source_type: "nonprofit" },
  { section: "D", title: "Second Harvest of South Georgia",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 30 counties in south Georgia including Valdosta, Albany, and Tifton. Partner pantries, mobile distributions, child nutrition.",
    website_url: "https://feedingsga.org", phone: "229-244-2678",
    address: "1411 Harbin Circle", city: "Valdosta", zip: "31601",
    latitude: 30.8327, longitude: -83.2785,
    source_name: "Second Harvest of South Georgia", source_type: "nonprofit" },
  { section: "D", title: "HOPE Atlanta — Veterans Programs",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Atlanta nonprofit providing veteran-specific homeless services including SSVF rapid rehousing, case management, and permanent supportive housing across metro Atlanta.",
    website_url: "https://hopeatlanta.org/programs/veterans/", phone: "404-817-7070",
    address: "75 Ted Turner Drive NW, Suite 300", city: "Atlanta", zip: "30303",
    latitude: 33.7585, longitude: -84.3922,
    source_name: "HOPE Atlanta", source_type: "nonprofit" },
  { section: "D", title: "U.S.VETS — Atlanta",
    cat: "housing", sub: "Transitional Housing",
    desc: "U.S.VETS Atlanta site providing transitional housing, employment services, and case management for homeless veterans. SSVF program serving 11 metro counties.",
    website_url: "https://usvets.org/locations/atlanta/", phone: "678-553-4099",
    address: "265 Boulevard NE", city: "Atlanta", zip: "30312",
    latitude: 33.7616, longitude: -84.3712,
    source_name: "United States Veterans Initiative", source_type: "nonprofit" },
  { section: "D", title: "Mary Hall Freedom Village",
    cat: "housing", sub: "Transitional Housing",
    desc: "Sandy Springs nonprofit providing housing, recovery, and trauma-informed care for women veterans and women with children experiencing homelessness or addiction.",
    website_url: "https://www.maryhallfreedomvillage.org", phone: "770-642-5500",
    address: "8995 Roswell Road", city: "Sandy Springs", zip: "30350",
    latitude: 33.9304, longitude: -84.3733,
    source_name: "Mary Hall Freedom Village", source_type: "nonprofit" },
  { section: "D", title: "Veterans Empowerment Organization (VEO) of Georgia",
    cat: "housing", sub: "Transitional Housing",
    desc: "Atlanta nonprofit providing transitional housing, employment, mental health, and case management for homeless and at-risk veterans on a campus near downtown.",
    website_url: "https://www.veoatlanta.org", phone: "404-367-2493",
    address: "740 Ralph David Abernathy Boulevard SW", city: "Atlanta", zip: "30310",
    latitude: 33.7340, longitude: -84.4124,
    source_name: "Veterans Empowerment Organization", source_type: "nonprofit" },
  { section: "D", title: "Travelers Aid of Metropolitan Atlanta — Veterans Services",
    cat: "housing", sub: "Rental Assistance",
    desc: "Metro Atlanta nonprofit providing emergency rental assistance, eviction prevention, and rapid rehousing for veterans through SSVF and partner programs.",
    website_url: "https://www.travelersaidatl.org", phone: "404-817-7070",
    address: "75 Ted Turner Drive NW, Suite 300", city: "Atlanta", zip: "30303",
    latitude: 33.7585, longitude: -84.3922,
    source_name: "Travelers Aid Society of Metropolitan Atlanta", source_type: "nonprofit" },
  { section: "D", title: "Inspiritus — Veterans Housing (Savannah)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Inspiritus SSVF program providing rapid rehousing and homelessness prevention for veterans in Savannah and the coastal Georgia region.",
    website_url: "https://weinspirit.org/programs/veterans-services/", phone: "912-651-0830",
    address: "5354 Reynolds Street", city: "Savannah", zip: "31405",
    latitude: 32.0119, longitude: -81.1304,
    source_name: "Inspiritus", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION E — Legal + Employment + Education
  // ===========================================================================
  { section: "E", title: "Georgia Legal Services Program — Veterans Project",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Free civil legal aid for low-income Georgia veterans across 154 counties outside metro Atlanta. Discharge upgrades, VA benefits appeals, family law, housing.",
    website_url: "https://www.glsp.org/get-help/military-veterans/", phone: "404-206-5175",
    address: "104 Marietta Street NW, Suite 250", city: "Atlanta", zip: "30303",
    latitude: 33.7560, longitude: -84.3932,
    source_name: "Georgia Legal Services Program", source_type: "nonprofit" },
  { section: "E", title: "Atlanta Legal Aid Society — Veterans Legal Services",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Free civil legal aid for low-income veterans in Clayton, Cobb, DeKalb, Fulton, and Gwinnett counties. Housing, family law, discharge upgrades, VA appeals.",
    website_url: "https://atlantalegalaid.org/get-help/veterans/", phone: "404-524-5811",
    address: "54 Ellis Street NE", city: "Atlanta", zip: "30303",
    latitude: 33.7566, longitude: -84.3887,
    source_name: "Atlanta Legal Aid Society", source_type: "nonprofit" },
  { section: "E", title: "Atlanta Volunteer Lawyers Foundation — Veterans Initiative",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Pro bono civil legal services for low-income metro Atlanta veterans. Eviction defense, discharge upgrades, family law, VA benefits appeals.",
    website_url: "https://avlf.org", phone: "404-521-0790",
    address: "235 Peachtree Street NE, Suite 1750", city: "Atlanta", zip: "30303",
    latitude: 33.7591, longitude: -84.3877,
    source_name: "Atlanta Volunteer Lawyers Foundation", source_type: "nonprofit" },
  { section: "E", title: "Mercer Law School Veterans' Legal Clinic",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Mercer University School of Law student-run clinic providing free representation to middle Georgia veterans on VA benefits appeals and discharge upgrades.",
    website_url: "https://law.mercer.edu/academics/clinics/", phone: "478-301-2533",
    address: "1021 Georgia Avenue", city: "Macon", zip: "31207",
    latitude: 32.8298, longitude: -83.6499,
    source_name: "Mercer University School of Law", source_type: "private" },
  { section: "E", title: "Hire Heroes USA — Headquarters",
    cat: "employment", sub: "Resume & Career Coaching",
    desc: "National HQ in metro Atlanta. Free 1:1 career coaching, resume building, federal employment guidance, and job placement for transitioning service members, veterans, and military spouses.",
    website_url: "https://www.hireheroesusa.org", phone: "844-634-1520",
    address: "1130 Northchase Parkway SE, Suite 200", city: "Marietta", zip: "30067",
    latitude: 33.9180, longitude: -84.4674,
    source_name: "Hire Heroes USA", source_type: "nonprofit" },
  { section: "E", title: "Georgia Department of Labor — Veterans Services",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "Statewide DVOP and LVER specialists co-located in GDOL career centers. Job search assistance, training referrals, and priority of service for Georgia veterans.",
    website_url: "https://dol.georgia.gov/individuals/veteran-services", phone: "404-232-3515",
    address: "148 Andrew Young International Boulevard NE", city: "Atlanta", zip: "30303",
    latitude: 33.7619, longitude: -84.3853,
    source_name: "Georgia Department of Labor", source_type: "government" },
  { section: "E", title: "VECTR Center — Warner Robins",
    cat: "employment", sub: "Career Pathways",
    desc: "Veterans Education Career Transition Resource Center. State-funded one-stop providing accelerated training, certifications, and career navigation for transitioning service members and veterans.",
    website_url: "https://vectrcenter.com", phone: "478-218-3900",
    address: "1001 South Armed Forces Boulevard", city: "Warner Robins", zip: "31088",
    latitude: 32.6011, longitude: -83.5826,
    source_name: "VECTR Center (TCSG)", source_type: "government" },
  { section: "E", title: "University of Georgia Student Veterans Resource Center",
    cat: "education", sub: "Veteran Student Services",
    desc: "UGA's dedicated center for student veterans, military-connected students, and dependents. GI Bill certification, advocacy, peer support, and study space.",
    website_url: "https://svrc.uga.edu", phone: "706-542-2002",
    address: "330 South Lumpkin Street", city: "Athens", zip: "30602",
    latitude: 33.9519, longitude: -83.3756,
    source_name: "University of Georgia", source_type: "government" },
  { section: "E", title: "Georgia State University — Military Outreach Center",
    cat: "education", sub: "Veteran Student Services",
    desc: "Georgia State's central resource for student veterans, active duty, guard, reserve, and military families. GI Bill certification, advising, peer support.",
    website_url: "https://military.gsu.edu", phone: "404-413-2331",
    address: "75 Piedmont Avenue NE, Suite 230", city: "Atlanta", zip: "30303",
    latitude: 33.7560, longitude: -84.3863,
    source_name: "Georgia State University", source_type: "government" },
  { section: "E", title: "Kennesaw State University — Military and Veterans Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "KSU support for student veterans and military-connected students across Kennesaw and Marietta campuses. GI Bill certification, advising, lounge, and events.",
    website_url: "https://veterans.kennesaw.edu", phone: "470-578-6234",
    address: "395 Cobb Avenue NW", city: "Kennesaw", zip: "30144",
    latitude: 34.0289, longitude: -84.5811,
    source_name: "Kennesaw State University", source_type: "government" },
  { section: "E", title: "Augusta University — Military and Veterans Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "Augusta University center serving military-connected students. GI Bill certification, tutoring referrals, advocacy, and peer support.",
    website_url: "https://www.augusta.edu/veterans/", phone: "706-737-1492",
    address: "1120 15th Street", city: "Augusta", zip: "30912",
    latitude: 33.4720, longitude: -82.0194,
    source_name: "Augusta University", source_type: "government" },

  // ===========================================================================
  // SECTION F — Transportation + Family + Disabled veterans
  // ===========================================================================
  { section: "F", title: "DAV Transportation Network — Atlanta VA",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "Disabled American Veterans volunteer driver network providing free rides to and from Atlanta VA Medical Center for veterans needing medical care.",
    website_url: "https://www.va.gov/atlanta-health-care/programs/dav-transportation/", phone: "404-321-6111",
    address: "1670 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.8033, longitude: -84.3171,
    source_name: "Disabled American Veterans / VA", source_type: "nonprofit" },
  { section: "F", title: "DAV Transportation Network — Charlie Norwood VAMC (Augusta)",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "DAV volunteer driver network providing free rides to and from Charlie Norwood VA Medical Center for Augusta-area veterans needing medical care.",
    website_url: "https://www.va.gov/augusta-health-care/programs/dav-transportation/", phone: "706-733-0188",
    address: "950 15th Street", city: "Augusta", zip: "30901",
    latitude: 33.4644, longitude: -82.0064,
    source_name: "Disabled American Veterans / VA", source_type: "nonprofit" },
  { section: "F", title: "DAV Transportation Network — Carl Vinson VAMC (Dublin)",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "DAV volunteer driver network providing free rides to and from Carl Vinson VA Medical Center for central and south Georgia veterans needing medical care.",
    website_url: "https://www.va.gov/dublin-health-care/programs/dav-transportation/", phone: "478-272-1210",
    address: "1826 Veterans Boulevard", city: "Dublin", zip: "31021",
    latitude: 32.5404, longitude: -82.9038,
    source_name: "Disabled American Veterans / VA", source_type: "nonprofit" },
  { section: "F", title: "Operation Homefront — Georgia",
    cat: "family-support", sub: "Military Family Support",
    desc: "National nonprofit serving Georgia military families with critical financial assistance, transitional housing, and family programs through partners statewide.",
    website_url: "https://www.operationhomefront.org", phone: "210-659-7756",
    city: "Atlanta", zip: "30303",
    latitude: 33.7490, longitude: -84.3880,
    source_name: "Operation Homefront", source_type: "nonprofit" },
  { section: "F", title: "USO Georgia",
    cat: "family-support", sub: "Military Family Support",
    desc: "USO centers and programs serving Georgia service members and families at Fort Moore, Fort Stewart, Hunter Army Airfield, Robins AFB, Moody AFB, and metro Atlanta airports.",
    website_url: "https://georgia.uso.org", phone: "678-816-4123",
    city: "Atlanta", zip: "30320",
    latitude: 33.6407, longitude: -84.4277,
    source_name: "USO of Georgia", source_type: "nonprofit" },
  { section: "F", title: "Hope For The Warriors — Hinesville Office",
    cat: "family-support", sub: "Military Family Support",
    desc: "Hope For The Warriors serves Fort Stewart and Hunter Army Airfield service members, veterans, and families with clinical health, sports recovery, and transition support.",
    website_url: "https://www.hopeforthewarriors.org", phone: "910-938-1817",
    city: "Hinesville", zip: "31313",
    latitude: 31.8413, longitude: -81.5957,
    source_name: "Hope For The Warriors", source_type: "nonprofit" },
  { section: "F", title: "Wounded Warrior Project — Atlanta Office",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "WWP Atlanta regional office providing programs in mental wellness, physical wellness, financial wellness, career counseling, and benefits assistance for post-9/11 wounded veterans.",
    website_url: "https://www.woundedwarriorproject.org", phone: "904-405-1213",
    address: "1100 Peachtree Street NE, Suite 200", city: "Atlanta", zip: "30309",
    latitude: 33.7847, longitude: -84.3856,
    source_name: "Wounded Warrior Project", source_type: "nonprofit" },
  { section: "F", title: "Disabled American Veterans — Department of Georgia",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "DAV Department of Georgia HQ. Free claims assistance through accredited service officers, transportation network, and chapter-based peer support across the state.",
    website_url: "https://www.davga.org", phone: "404-929-3024",
    address: "1700 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "DAV Department of Georgia", source_type: "nonprofit" },
  { section: "F", title: "Paralyzed Veterans of America — Southeastern Chapter (Atlanta)",
    cat: "disabled-veterans", sub: "Healthcare & Rehabilitation",
    desc: "PVA Southeastern Chapter serving Georgia, Alabama, Mississippi, and Tennessee veterans with spinal cord injury or disease. Claims, advocacy, sports, and peer support.",
    website_url: "https://southeastern.pva.org", phone: "404-321-6111",
    address: "1670 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.8033, longitude: -84.3171,
    source_name: "Paralyzed Veterans of America", source_type: "nonprofit" },
  { section: "F", title: "Blinded Veterans Association — Georgia Regional Group",
    cat: "disabled-veterans", sub: "Healthcare & Rehabilitation",
    desc: "BVA Georgia regional group providing peer support, advocacy, and benefits help for blinded and visually impaired veterans across the state.",
    website_url: "https://bva.org", phone: "202-371-8880",
    city: "Atlanta", zip: "30303",
    latitude: 33.7490, longitude: -84.3880,
    source_name: "Blinded Veterans Association", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION G — Community Support (American Legion / VFW / Veteran Homes)
  // ===========================================================================
  { section: "G", title: "American Legion Department of Georgia",
    cat: "community-support", sub: "American Legion Posts",
    desc: "American Legion Department of Georgia headquarters. Statewide network of posts providing fellowship, claims service officers, scholarships, and community programs.",
    website_url: "https://www.galegion.org", phone: "678-289-8883",
    address: "3035 Mt. Zion Road", city: "Stockbridge", zip: "30281",
    latitude: 33.5443, longitude: -84.2335,
    source_name: "American Legion Department of Georgia", source_type: "nonprofit" },
  { section: "G", title: "VFW Department of Georgia",
    cat: "community-support", sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Department of Georgia HQ. Statewide network of posts providing fellowship, claims service officers, and community service.",
    website_url: "https://www.vfwga.org", phone: "770-518-2691",
    address: "1395 East Cherokee Street", city: "Marietta", zip: "30060",
    latitude: 33.9580, longitude: -84.5366,
    source_name: "VFW Department of Georgia", source_type: "nonprofit" },
  { section: "G", title: "Georgia War Veterans Home — Milledgeville",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "State-operated long-term care facility for Georgia veterans. Skilled nursing, domiciliary, memory care, and rehabilitation services on a historic campus.",
    website_url: "https://veterans.georgia.gov/georgia-war-veterans-home-milledgeville", phone: "478-445-4711",
    address: "2249 Vinson Highway SE", city: "Milledgeville", zip: "31062",
    latitude: 33.0798, longitude: -83.2404,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "G", title: "Georgia War Veterans Nursing Home — Augusta",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "State-operated skilled nursing facility for Georgia veterans on the Augusta University campus. Long-term care, rehabilitation, and memory care services.",
    website_url: "https://veterans.georgia.gov/georgia-war-veterans-nursing-home-augusta", phone: "706-721-2531",
    address: "1101 15th Street", city: "Augusta", zip: "30901",
    latitude: 33.4720, longitude: -82.0194,
    source_name: "Georgia Department of Veterans Service", source_type: "government" },
  { section: "G", title: "American Legion Post 140 — Roswell",
    cat: "community-support", sub: "American Legion Posts",
    desc: "Roswell American Legion post serving north Fulton veterans. Fellowship, claims service officer, scholarships, and community service projects.",
    website_url: "https://www.alpost140.com", phone: "770-993-3010",
    address: "562 Atlanta Street", city: "Roswell", zip: "30075",
    latitude: 34.0232, longitude: -84.3616,
    source_name: "American Legion Post 140", source_type: "nonprofit" },
  { section: "G", title: "American Legion Post 160 — Smyrna",
    cat: "community-support", sub: "American Legion Posts",
    desc: "Smyrna American Legion post serving Cobb County veterans. Fellowship, claims service officer, scholarships, and community programs.",
    website_url: "https://post160.org", phone: "770-432-9325",
    address: "160 Legion Drive SE", city: "Smyrna", zip: "30080",
    latitude: 33.8688, longitude: -84.5144,
    source_name: "American Legion Post 160", source_type: "nonprofit" },
  { section: "G", title: "VFW Post 5408 — Albany",
    cat: "community-support", sub: "VFW Posts",
    desc: "Albany VFW post serving combat veterans of southwest Georgia. Fellowship, claims service officer, and community fundraising events.",
    website_url: "https://www.vfwga.org", phone: "229-883-4540",
    address: "1810 Newton Road", city: "Albany", zip: "31701",
    latitude: 31.5785, longitude: -84.1557,
    source_name: "VFW Post 5408", source_type: "nonprofit" },
  { section: "G", title: "VFW Post 660 — Savannah",
    cat: "community-support", sub: "VFW Posts",
    desc: "Savannah VFW post serving combat veterans of coastal Georgia. Fellowship, claims service officer, and community service projects.",
    website_url: "https://www.vfwga.org", phone: "912-352-2767",
    address: "5115 Skidaway Road", city: "Savannah", zip: "31404",
    latitude: 32.0309, longitude: -81.0698,
    source_name: "VFW Post 660", source_type: "nonprofit" },
];

async function main() {
  console.log(`\n=== GA PHASE 1 SEED (${COMMIT ? "COMMIT" : "DRY-RUN"}) — ${ROWS.length} rows ===\n`);

  // Load taxonomy
  const { data: cats } = await supabaseAdmin.from("categories").select("id, slug");
  const catBySlug = new Map<string, string>((cats || []).map((c: any) => [c.slug, c.id]));

  const { data: subs } = await supabaseAdmin.from("subcategories").select("id, name, category_id");
  const subKey = new Map<string, string>();
  (subs || []).forEach((s: any) => subKey.set(`${s.category_id}|${s.name.toLowerCase().trim()}`, s.id));

  // Dedupe guards: national rows AND existing GA rows
  const { data: nat } = await supabaseAdmin.from("resources").select("title").is("state", null);
  const natTitles = new Set((nat || []).map((r: any) => (r.title || "").toLowerCase().trim()));
  const { data: existing } = await supabaseAdmin.from("resources").select("title").eq("state", STATE);
  const gaTitles = new Set((existing || []).map((r: any) => (r.title || "").toLowerCase().trim()));

  const sectionStats: Record<string, { created: number; dup: number; bad_sub: number; err: number }> = {
    A: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    B: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    C: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    D: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    E: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    F: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    G: { created: 0, dup: 0, bad_sub: 0, err: 0 },
  };
  const errs: string[] = [];

  for (const r of ROWS) {
    const stats = sectionStats[r.section];
    const key = r.title.toLowerCase().trim();
    if (gaTitles.has(key) || natTitles.has(key)) { stats.dup++; continue; }

    const category_id = catBySlug.get(r.cat);
    if (!category_id) { errs.push(`${r.title}: cat ${r.cat} missing`); stats.err++; continue; }

    const subcategory_id = subKey.get(`${category_id}|${r.sub.toLowerCase()}`);
    if (!subcategory_id) {
      errs.push(`${r.title}: sub "${r.sub}" not in taxonomy for ${r.cat}`);
      stats.bad_sub++; continue;
    }

    const insert: Record<string, any> = {
      title: r.title, category_id,
      short_description: r.desc,
      website_url: r.website_url || null,
      phone: r.phone || null,
      address: r.address || null,
      city: r.city || null, state: STATE, zip: r.zip || null,
      latitude: r.latitude ?? null, longitude: r.longitude ?? null,
      geo_source: r.latitude ? "manual_curation" : null,
      geocoded_at: r.latitude ? new Date().toISOString() : null,
      eligibility: r.eligibility || "All veterans",
      subcategory: r.sub,
      source_name: r.source_name || null,
      source_type: r.source_type || null,
      status: "approved", sponsored: false,
    };

    if (!COMMIT) { stats.created++; continue; }

    const { data: ins, error } = await supabaseAdmin.from("resources").insert(insert).select("id").single();
    if (error || !ins) { errs.push(`${r.title}: ${error?.message}`); stats.err++; continue; }

    await supabaseAdmin.from("resource_categories").upsert({ resource_id: ins.id, category_id }, { onConflict: "resource_id,category_id" });
    await supabaseAdmin.from("resource_subcategories").upsert({ resource_id: ins.id, subcategory_id }, { onConflict: "resource_id,subcategory_id" });
    stats.created++;
  }

  console.log(`Section breakdown:`);
  for (const [sec, s] of Object.entries(sectionStats)) {
    console.log(`  ${sec}: created=${s.created} dup=${s.dup} bad_sub=${s.bad_sub} err=${s.err}`);
  }
  if (errs.length) {
    console.log(`\nErrors / skips (${errs.length}):`);
    errs.forEach(e => console.log(`  - ${e}`));
  }
  console.log(`\n=== TOTAL ROWS: ${ROWS.length} ===\n`);
}

main().catch(e => { console.error("FATAL:", e); process.exit(1); });
