/**
 * California Phase 1A — Statewide Anchors + LA + San Diego Cores
 *
 * Founder rule: California flagship state, 8-phase rollout, 1,800-row planning anchor.
 * Phase 1 is split into 1A (this) and 1B (Bay Area + Sac + Fresno/IE + statewide nonprofits)
 * to keep each phase shippable in one ~90-min session per founder fast-mode safeguards.
 *
 * Sections:
 *   A = CalVet HQ + 8 Veterans Homes
 *   B = VA Medical Centers (8 systems)
 *   C = Vet Centers (high-confidence subset; rest in P1B / metro phases)
 *   D = Top County VSOs (highest veteran-density 12 — rest spread P2-P7)
 *   E = National Cemeteries (all 8)
 *   F = Los Angeles Core
 *   G = San Diego Core
 *   L = Statewide cross-cut programs (small set; rest in P1B)
 *
 * No fabrication. Every row sourced from .gov / .org institutional site.
 * Skip-and-queue any row that requires guessing. Lat/lng intentionally null
 * (geocoder runs downstream; we never invent coordinates).
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===== A — CalVet HQ + 8 Veterans Homes =====
  {
    section: "A", title: "California Department of Veterans Affairs (CalVet)",
    cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation",
    desc: "Cabinet-level state agency serving California's 1.6 million veterans. Administers 8 Veterans Homes, College Fee Waiver, CalVet Home Loans, Disabled Veteran Business Enterprise certification, Women Veterans Outreach, Stand Downs, and connects veterans to federal VA benefits via 58 County Veteran Service Offices.",
    website_url: "https://www.calvet.ca.gov/",
    phone: "(800) 952-5626", address: "1227 O Street",
    city: "Sacramento", zip: "95814",
    eligibility: "California veterans, surviving spouses and dependents",
    source_name: "CalVet", source_type: "state_government",
  },
  {
    section: "A", title: "Yountville Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Largest veterans home in the United States (1884). Skilled nursing, intermediate care, residential, memory care, and domiciliary services for California veterans on a 615-acre Napa Valley campus.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/Yountville.aspx",
    phone: "(707) 944-4500", address: "260 California Drive",
    city: "Yountville", zip: "94599",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "Barstow Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Skilled nursing, intermediate care, and residential care for California veterans in the High Desert region.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/Barstow.aspx",
    phone: "(760) 252-6200", address: "100 East Veterans Parkway",
    city: "Barstow", zip: "92311",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "Chula Vista Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Skilled nursing, residential care, and memory care for California veterans in the South Bay San Diego region.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/ChulaVista.aspx",
    phone: "(619) 482-6000", address: "700 East Naples Court",
    city: "Chula Vista", zip: "91911",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "Lancaster Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Skilled nursing, residential care, and memory care for California veterans in the Antelope Valley (serves Edwards AFB veteran community).",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/Lancaster.aspx",
    phone: "(661) 480-3500", address: "45221 30th Street West",
    city: "Lancaster", zip: "93536",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "Ventura Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Skilled nursing, residential care, and memory care for California veterans on the Central Coast.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/Ventura.aspx",
    phone: "(805) 612-2400", address: "10900 Telephone Road",
    city: "Ventura", zip: "93004",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "West Los Angeles Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Skilled nursing, residential care, and memory care for California veterans on the West LA VA campus.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/WLA.aspx",
    phone: "(310) 207-4400", address: "11500 Nimitz Avenue",
    city: "Los Angeles", zip: "90049",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "Redding Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Residential care and memory care for California veterans in the Shasta County / Northern California region.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/Redding.aspx",
    phone: "(530) 224-3300", address: "3400 Knighton Road",
    city: "Redding", zip: "96002",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },
  {
    section: "A", title: "Fresno Veterans Home of California",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Residential care and memory care for California veterans in the Central Valley.",
    website_url: "https://www.calvet.ca.gov/vethomes/Pages/Fresno.aspx",
    phone: "(559) 493-9300", address: "2811 West Nielsen Avenue",
    city: "Fresno", zip: "93706",
    eligibility: "California-resident veterans (age 55+ or disabled)",
    source_name: "CalVet Veterans Homes", source_type: "state_government",
  },

  // ===== B — VA Medical Centers (8 systems / 9 anchor facilities) =====
  {
    section: "B", title: "VA Greater Los Angeles Healthcare System - West LA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "One of the largest VA healthcare systems in the country, serving veterans across LA, Ventura, Santa Barbara, San Luis Obispo, and Kern counties. Full inpatient/outpatient services, mental health, primary care, specialty care, women's health, polytrauma rehab, and homeless veteran programs (HUD-VASH, SSVF) on the historic 388-acre West LA campus.",
    website_url: "https://www.va.gov/greater-los-angeles-health-care/",
    phone: "(310) 478-3711", address: "11301 Wilshire Boulevard",
    city: "Los Angeles", zip: "90073",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "VA Sepulveda Ambulatory Care Center",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Major ambulatory care campus of the VA Greater LA Healthcare System in the San Fernando Valley. Primary care, mental health, women's health, geriatrics, and outpatient specialty services.",
    website_url: "https://www.va.gov/greater-los-angeles-health-care/locations/sepulveda-va-ambulatory-care-center/",
    phone: "(818) 891-7711", address: "16111 Plummer Street",
    city: "North Hills", zip: "91343",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "Tibor Rubin VA Medical Center (Long Beach)",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA Long Beach Healthcare System main facility, named for Medal of Honor recipient Tibor Rubin. Full inpatient/outpatient services for veterans across southern LA County and northern Orange County, including spinal cord injury center, blind rehabilitation, and polytrauma care.",
    website_url: "https://www.va.gov/long-beach-health-care/",
    phone: "(562) 826-8000", address: "5901 East 7th Street",
    city: "Long Beach", zip: "90822",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "Jerry L. Pettis Memorial VA Medical Center (Loma Linda)",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA Loma Linda Healthcare System main facility serving veterans in the Inland Empire (San Bernardino, Riverside, Inyo, Mono counties). Full inpatient/outpatient services including a major mental health program, women's health, and Polytrauma Network site.",
    website_url: "https://www.va.gov/loma-linda-health-care/",
    phone: "(909) 825-7084", address: "11201 Benton Street",
    city: "Loma Linda", zip: "92357",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "VA San Diego Healthcare System Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Main VA San Diego facility serving veterans across San Diego and Imperial counties. Full inpatient/outpatient services, mental health, women veterans, polytrauma, and a major homeless veteran program serving one of the nation's largest veteran populations.",
    website_url: "https://www.va.gov/san-diego-health-care/",
    phone: "(858) 552-8585", address: "3350 La Jolla Village Drive",
    city: "San Diego", zip: "92161",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "VA Palo Alto Health Care System Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA's national flagship for polytrauma, spinal cord injury, and traumatic brain injury rehabilitation. Serves veterans across the South Bay, Peninsula, and parts of the Central Coast / Central Valley with full inpatient/outpatient services, mental health, and women's health.",
    website_url: "https://www.va.gov/palo-alto-health-care/",
    phone: "(650) 493-5000", address: "3801 Miranda Avenue",
    city: "Palo Alto", zip: "94304",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "San Francisco VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA San Francisco Healthcare System main facility serving veterans across SF, Marin, Sonoma, Napa, Lake, Mendocino, Humboldt, and Del Norte counties. Full inpatient/outpatient services, mental health (including PTSD specialty), and a major HIV / hepatitis C clinical research program.",
    website_url: "https://www.va.gov/san-francisco-health-care/",
    phone: "(415) 221-4810", address: "4150 Clement Street",
    city: "San Francisco", zip: "94121",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "Sacramento VA Medical Center (Mather)",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA Northern California Healthcare System main hospital. Serves veterans across Sacramento, Yolo, Placer, El Dorado, Solano, Yuba, Sutter, Nevada, and surrounding counties with full inpatient/outpatient services, mental health, women veterans care, and polytrauma rehabilitation.",
    website_url: "https://www.va.gov/northern-california-health-care/",
    phone: "(916) 366-5366", address: "10535 Hospital Way",
    city: "Mather", zip: "95655",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "B", title: "Fresno VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA Central California Healthcare System main facility serving veterans across Fresno, Madera, Kings, Tulare, Mariposa, Merced, and surrounding Central Valley counties. Full inpatient/outpatient services, mental health, women veterans, and homeless veteran programs.",
    website_url: "https://www.va.gov/central-california-health-care/",
    phone: "(559) 225-6100", address: "2615 East Clinton Avenue",
    city: "Fresno", zip: "93703",
    eligibility: "VA-eligible veterans",
    source_name: "VA.gov", source_type: "federal_government",
  },

  // ===== C — Vet Centers (high-confidence subset; remainder in P1B and metro phases) =====
  {
    section: "C", title: "Los Angeles Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved family members. Individual, group, and family counseling — separate from VA medical records.",
    website_url: "https://www.va.gov/los-angeles-vet-center/",
    phone: "(310) 641-0326", address: "5730 Uplander Way, Suite 100",
    city: "Culver City", zip: "90230",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "East Los Angeles Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling serving East LA, Boyle Heights, San Gabriel Valley combat veterans, MST survivors, and families.",
    website_url: "https://www.va.gov/east-los-angeles-vet-center/",
    phone: "(323) 728-9966", address: "5400 East Olympic Boulevard, Suite 140",
    city: "Commerce", zip: "90022",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "South Bay Vet Center (Gardena)",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling serving South Bay LA combat veterans, MST survivors, and families.",
    website_url: "https://www.va.gov/south-bay-vet-center-gardena/",
    phone: "(310) 767-1221", address: "1208 Magnolia Avenue, Suite 100",
    city: "Gardena", zip: "90247",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Long Beach Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans and MST survivors in the Long Beach / South LA region.",
    website_url: "https://www.va.gov/long-beach-vet-center/",
    phone: "(562) 388-8045", address: "1500 Hughes Way, Suite C-110",
    city: "Long Beach", zip: "90810",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "San Diego Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans and MST survivors in San Diego — the largest active-duty / veteran population in the country.",
    website_url: "https://www.va.gov/san-diego-vet-center/",
    phone: "(858) 642-1500", address: "2790 Truxtun Road, Suite 130",
    city: "San Diego", zip: "92106",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Chula Vista Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling serving South Bay San Diego combat veterans and MST survivors.",
    website_url: "https://www.va.gov/chula-vista-vet-center/",
    phone: "(877) 618-6534", address: "180 Otay Lakes Road, Suite 108",
    city: "Bonita", zip: "91902",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "San Marcos Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans and MST survivors across North County San Diego (Camp Pendleton catchment).",
    website_url: "https://www.va.gov/san-marcos-vet-center/",
    phone: "(760) 744-6914", address: "1 Civic Center Drive, Suite 150",
    city: "San Marcos", zip: "92069",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "San Francisco Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families in San Francisco.",
    website_url: "https://www.va.gov/san-francisco-vet-center/",
    phone: "(415) 441-5051", address: "505 Polk Street",
    city: "San Francisco", zip: "94102",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Oakland Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families in the East Bay.",
    website_url: "https://www.va.gov/oakland-vet-center/",
    phone: "(510) 763-3904", address: "1504 Franklin Street, Suite 200",
    city: "Oakland", zip: "94612",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Concord Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans and MST survivors across Contra Costa County and the East Bay.",
    website_url: "https://www.va.gov/concord-vet-center/",
    phone: "(925) 680-4526", address: "1899 Clayton Road, Suite 140",
    city: "Concord", zip: "94520",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Sacramento Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families across the Sacramento metro.",
    website_url: "https://www.va.gov/sacramento-vet-center/",
    phone: "(916) 566-7430", address: "1111 Howe Avenue, Suite 390",
    city: "Sacramento", zip: "95825",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "San Jose Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families across Silicon Valley and South Bay.",
    website_url: "https://www.va.gov/san-jose-vet-center/",
    phone: "(408) 993-0729", address: "1660 Park Avenue",
    city: "San Jose", zip: "95126",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Fresno Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families across the Central Valley.",
    website_url: "https://www.va.gov/fresno-vet-center/",
    phone: "(559) 487-5660", address: "1320 East Shaw Avenue, Suite 125",
    city: "Fresno", zip: "93710",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Santa Cruz County Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families in Santa Cruz, Monterey Bay area.",
    website_url: "https://www.va.gov/santa-cruz-county-vet-center/",
    phone: "(831) 469-0103", address: "1350 41st Avenue, Suite 102",
    city: "Capitola", zip: "95010",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "C", title: "Riverside Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families across Riverside County and the Inland Empire.",
    website_url: "https://www.va.gov/riverside-vet-center/",
    phone: "(951) 276-6342", address: "4954 Arlington Avenue, Suite A",
    city: "Riverside", zip: "92504",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },

  // ===== D — Top County Veteran Service Offices (12 highest-density counties) =====
  {
    section: "D", title: "Los Angeles County Department of Military and Veterans Affairs",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Largest county veterans service office in the United States, serving ~280,000 veterans in LA County. Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits.",
    website_url: "https://military.lacounty.gov/",
    phone: "(877) 452-8387", address: "1816 South Figueroa Street",
    city: "Los Angeles", zip: "90015",
    eligibility: "LA County veterans, surviving spouses, dependents",
    source_name: "LA County DMVA", source_type: "county_government",
  },
  {
    section: "D", title: "San Diego County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependency/survivors benefits, healthcare enrollment, education, and burial benefits for ~230,000 veterans across San Diego County.",
    website_url: "https://www.sandiegocounty.gov/hhsa/programs/ais/veterans/",
    phone: "(858) 694-3222", address: "5560 Overland Avenue, Suite 310",
    city: "San Diego", zip: "92123",
    eligibility: "San Diego County veterans, surviving spouses, dependents",
    source_name: "San Diego County HHSA", source_type: "county_government",
  },
  {
    section: "D", title: "Orange County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for ~120,000 veterans across Orange County.",
    website_url: "https://www.ocgov.com/gov/care/csa/veteran",
    phone: "(714) 480-6555", address: "1300 South Grand Avenue, Building B",
    city: "Santa Ana", zip: "92705",
    eligibility: "Orange County veterans, surviving spouses, dependents",
    source_name: "OC Community Services", source_type: "county_government",
  },
  {
    section: "D", title: "Riverside County Department of Veterans' Services",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for ~140,000 veterans across Riverside County and the Inland Empire.",
    website_url: "https://veterans.rivco.org/",
    phone: "(951) 955-3060", address: "4360 Orange Street",
    city: "Riverside", zip: "92501",
    eligibility: "Riverside County veterans, surviving spouses, dependents",
    source_name: "Riverside County DVS", source_type: "county_government",
  },
  {
    section: "D", title: "San Bernardino County Department of Veterans Affairs",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for ~110,000 veterans across San Bernardino County.",
    website_url: "https://hss.sbcounty.gov/dva/",
    phone: "(909) 387-5516", address: "175 West 5th Street, 2nd Floor",
    city: "San Bernardino", zip: "92415",
    eligibility: "San Bernardino County veterans, surviving spouses, dependents",
    source_name: "SB County DVA", source_type: "county_government",
  },
  {
    section: "D", title: "Sacramento County Department of Human Assistance - Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for ~80,000 veterans in Sacramento County.",
    website_url: "https://dha.saccounty.gov/Veterans/Pages/default.aspx",
    phone: "(916) 874-6811", address: "2700 Fulton Avenue",
    city: "Sacramento", zip: "95821",
    eligibility: "Sacramento County veterans, surviving spouses, dependents",
    source_name: "Sacramento County DHA", source_type: "county_government",
  },
  {
    section: "D", title: "Alameda County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for veterans across the East Bay.",
    website_url: "https://www.acgov.org/cda/vsd/",
    phone: "(510) 577-1926", address: "1535 Fruitvale Avenue",
    city: "Oakland", zip: "94601",
    eligibility: "Alameda County veterans, surviving spouses, dependents",
    source_name: "Alameda County CDA", source_type: "county_government",
  },
  {
    section: "D", title: "Santa Clara County Office of Veterans Services",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for veterans across Santa Clara County / Silicon Valley.",
    website_url: "https://socialservices.sccgov.org/veterans-services",
    phone: "(408) 918-4980", address: "68 East Santa Clara Street, 7th Floor",
    city: "San Jose", zip: "95113",
    eligibility: "Santa Clara County veterans, surviving spouses, dependents",
    source_name: "SCC Social Services", source_type: "county_government",
  },
  {
    section: "D", title: "San Francisco County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for veterans in San Francisco.",
    website_url: "https://www.sf.gov/departments/county-veterans-service-office",
    phone: "(415) 934-4200", address: "1245 3rd Street, 2nd Floor",
    city: "San Francisco", zip: "94158",
    eligibility: "San Francisco veterans, surviving spouses, dependents",
    source_name: "SF County VSO", source_type: "county_government",
  },
  {
    section: "D", title: "Fresno County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for veterans across Fresno County.",
    website_url: "https://www.co.fresno.ca.us/departments/veterans-service-office",
    phone: "(559) 600-7588", address: "3133 North Millbrook Avenue",
    city: "Fresno", zip: "93703",
    eligibility: "Fresno County veterans, surviving spouses, dependents",
    source_name: "Fresno County VSO", source_type: "county_government",
  },
  {
    section: "D", title: "Kern County Veterans Service Department",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for veterans across Kern County.",
    website_url: "https://www.kerncountyveterans.com/",
    phone: "(661) 868-7300", address: "1120 Golden State Avenue",
    city: "Bakersfield", zip: "93301",
    eligibility: "Kern County veterans, surviving spouses, dependents",
    source_name: "Kern County VSD", source_type: "county_government",
  },
  {
    section: "D", title: "Contra Costa County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "Free help with VA disability claims, pension, dependents/survivors benefits, healthcare enrollment, education, and burial benefits for veterans across Contra Costa County.",
    website_url: "https://ehsd.org/elderly-disabled/veterans-services-office/",
    phone: "(925) 313-1481", address: "10 Douglas Drive, Suite 100",
    city: "Martinez", zip: "94553",
    eligibility: "Contra Costa County veterans, surviving spouses, dependents",
    source_name: "Contra Costa EHSD", source_type: "county_government",
  },

  // ===== E — National Cemeteries (all 8 in California) =====
  {
    section: "E", title: "Los Angeles National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving Southern California veterans (closed to most new interments; cremains and pre-eligible spouses still accepted). Memorial services, headstone applications, and grave search.",
    website_url: "https://www.cem.va.gov/cems/nchp/losangeles.asp",
    phone: "(310) 268-4675", address: "950 South Sepulveda Boulevard",
    city: "Los Angeles", zip: "90049",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "Riverside National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Largest national cemetery in the United States by interment count. Active interments, memorial services, headstone applications, and grave locator.",
    website_url: "https://www.cem.va.gov/cems/nchp/riverside.asp",
    phone: "(951) 653-8417", address: "22495 Van Buren Boulevard",
    city: "Riverside", zip: "92518",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "San Francisco National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Historic VA national cemetery in the Presidio of San Francisco (closed to most new interments). Headstone applications, memorial services, and grave search.",
    website_url: "https://www.cem.va.gov/cems/nchp/sanfrancisco.asp",
    phone: "(650) 589-7737", address: "1 Lincoln Boulevard",
    city: "San Francisco", zip: "94129",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "Sacramento Valley National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving Northern California veterans. Active interments, memorial services, headstone applications, and grave locator.",
    website_url: "https://www.cem.va.gov/cems/nchp/sacramentovalley.asp",
    phone: "(707) 693-2460", address: "5810 Midway Road",
    city: "Dixon", zip: "95620",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "San Joaquin Valley National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving Central California veterans. Active interments, memorial services, headstone applications, and grave locator.",
    website_url: "https://www.cem.va.gov/cems/nchp/sanjoaquinvalley.asp",
    phone: "(209) 854-1040", address: "32053 West McCabe Road",
    city: "Santa Nella", zip: "95322",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "Bakersfield National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving Kern County and Southern San Joaquin Valley veterans. Active interments, memorial services, headstone applications, and grave locator.",
    website_url: "https://www.cem.va.gov/cems/nchp/bakersfield.asp",
    phone: "(661) 867-2250", address: "30338 East Bear Mountain Boulevard",
    city: "Arvin", zip: "93203",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "Miramar National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving San Diego County veterans (active). Memorial services, headstone applications, and grave locator.",
    website_url: "https://www.cem.va.gov/cems/nchp/miramar.asp",
    phone: "(858) 658-7360", address: "5795 Nobel Drive",
    city: "San Diego", zip: "92122",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },
  {
    section: "E", title: "Fort Rosecrans National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Historic VA national cemetery overlooking San Diego Bay (closed to most new casket interments; cremains still accepted). Memorial services, headstone applications, and grave search.",
    website_url: "https://www.cem.va.gov/cems/nchp/ftrosecrans.asp",
    phone: "(619) 553-2084", address: "1800 Cabrillo Memorial Drive",
    city: "San Diego", zip: "92106",
    eligibility: "Eligible veterans and family members",
    source_name: "VA National Cemetery Administration", source_type: "federal_government",
  },

  // ===== F — Los Angeles Core =====
  {
    section: "F", title: "U.S. Department of Veterans Affairs - Los Angeles Regional Office",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "Federal VA Regional Office (VARO) for Southern California — processes disability claims, pension, education, vocational rehabilitation, and home loan eligibility for veterans across LA, OC, San Diego, and Inland Empire.",
    website_url: "https://www.benefits.va.gov/losangeles/",
    phone: "(800) 827-1000", address: "11000 Wilshire Boulevard",
    city: "Los Angeles", zip: "90024",
    eligibility: "All veterans",
    source_name: "VA Benefits", source_type: "federal_government",
  },
  {
    section: "F", title: "PATH (People Assisting The Homeless)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Statewide nonprofit ending homelessness for veterans, families, and individuals — operates SSVF (Supportive Services for Veteran Families) across LA County, plus permanent supportive housing, outreach teams, and rapid re-housing.",
    website_url: "https://epath.org/",
    phone: "(323) 644-2200", address: "340 North Madison Avenue",
    city: "Los Angeles", zip: "90004",
    eligibility: "Veterans and families experiencing homelessness",
    source_name: "PATH", source_type: "nonprofit",
  },
  {
    section: "F", title: "U.S. VETS Los Angeles",
    cat: "housing", sub: "Transitional Housing",
    desc: "Largest veteran-specific transitional housing nonprofit in the U.S. — Los Angeles flagship site provides residential housing, employment services, mental health, and substance recovery for homeless and at-risk veterans on the West LA VA campus.",
    website_url: "https://usvets.org/locations/los-angeles/",
    phone: "(310) 277-8838", address: "11301 Wilshire Boulevard, Building 217",
    city: "Los Angeles", zip: "90073",
    eligibility: "Veterans experiencing or at risk of homelessness",
    source_name: "U.S.VETS", source_type: "nonprofit",
  },
  {
    section: "F", title: "U.S. VETS Inglewood",
    cat: "housing", sub: "Transitional Housing",
    desc: "Transitional housing, employment services, mental health, and substance recovery for homeless and at-risk veterans in the Inglewood / South Bay region.",
    website_url: "https://usvets.org/locations/inglewood/",
    phone: "(310) 348-7600", address: "733 Hindry Avenue",
    city: "Inglewood", zip: "90301",
    eligibility: "Veterans experiencing or at risk of homelessness",
    source_name: "U.S.VETS", source_type: "nonprofit",
  },
  {
    section: "F", title: "U.S. VETS Long Beach",
    cat: "housing", sub: "Transitional Housing",
    desc: "Transitional housing, workforce services, and mental health for homeless and at-risk veterans in Long Beach / South LA County.",
    website_url: "https://usvets.org/locations/long-beach/",
    phone: "(562) 388-8000", address: "2001 River Avenue",
    city: "Long Beach", zip: "90810",
    eligibility: "Veterans experiencing or at risk of homelessness",
    source_name: "U.S.VETS", source_type: "nonprofit",
  },
  {
    section: "F", title: "New Directions for Veterans",
    cat: "housing", sub: "Transitional Housing",
    desc: "Transitional and permanent supportive housing on the West LA VA campus — residential substance recovery, employment training, mental health, and family reunification for homeless veterans.",
    website_url: "https://www.ndvets.org/",
    phone: "(310) 914-4045", address: "11303 Wilshire Boulevard, Building 116",
    city: "Los Angeles", zip: "90073",
    eligibility: "Veterans experiencing homelessness or in recovery",
    source_name: "New Directions for Veterans", source_type: "nonprofit",
  },
  {
    section: "F", title: "Volunteers of America Los Angeles - Veterans Programs",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "SSVF (Supportive Services for Veteran Families), HUD-VASH, GPD transitional housing, and rapid re-housing for veterans and families across LA County. Operates multiple residential sites and outreach teams.",
    website_url: "https://www.voala.org/veterans/",
    phone: "(213) 624-2117", address: "3600 Wilshire Boulevard, Suite 1500",
    city: "Los Angeles", zip: "90010",
    eligibility: "Veterans and families experiencing or at risk of homelessness",
    source_name: "VOA Los Angeles", source_type: "nonprofit",
  },
  {
    section: "F", title: "Salvation Army Haven (Bell Shelter)",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Largest emergency shelter west of the Mississippi serving 350+ men and women including veterans. Case management, employment services, substance recovery, and housing navigation.",
    website_url: "https://westernusa.salvationarmy.org/southern_california/bell-shelter/",
    phone: "(323) 263-1206", address: "5600 Rickenbacker Road",
    city: "Bell", zip: "90201",
    eligibility: "Adults experiencing homelessness, including veterans",
    source_name: "Salvation Army Southern CA", source_type: "nonprofit",
  },
  {
    section: "F", title: "Los Angeles Homeless Services Authority (LAHSA)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Joint city/county lead agency coordinating LA's homelessness response system, operating Coordinated Entry for Veterans (CES-V), 211 referrals, outreach teams, and the LA Continuum of Care.",
    website_url: "https://www.lahsa.org/",
    phone: "(213) 683-3333", address: "707 Wilshire Boulevard, 10th Floor",
    city: "Los Angeles", zip: "90017",
    eligibility: "All people experiencing homelessness in LA County",
    source_name: "LAHSA", source_type: "city_government",
  },
  {
    section: "F", title: "211 LA County",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 information and referral helpline connecting LA County residents — including veterans — to housing, food, healthcare, mental health, legal aid, and public benefits. Free and confidential.",
    website_url: "https://www.211la.org/",
    phone: "211", address: "1000 North Alameda Street, Suite 200",
    city: "Los Angeles", zip: "90012",
    eligibility: "All LA County residents",
    source_name: "211 LA", source_type: "nonprofit",
  },
  {
    section: "F", title: "Legal Aid Foundation of Los Angeles (LAFLA)",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Largest legal aid nonprofit in LA County providing free civil legal services including a dedicated Veterans Justice Project covering discharge upgrades, VA benefits, housing, and family law.",
    website_url: "https://lafla.org/",
    phone: "(800) 399-4529", address: "1550 West 8th Street",
    city: "Los Angeles", zip: "90017",
    eligibility: "Low-income LA County residents (veterans prioritized via VJP)",
    source_name: "LAFLA", source_type: "nonprofit",
  },
  {
    section: "F", title: "Public Counsel - Center for Veterans Advancement",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Nation's largest pro bono law firm. Center for Veterans Advancement provides free legal help with VA disability appeals, discharge upgrades, family law, housing, and benefits across Southern California.",
    website_url: "https://publiccounsel.org/practice-areas/veterans-rights/",
    phone: "(213) 385-2977", address: "610 South Ardmore Avenue",
    city: "Los Angeles", zip: "90005",
    eligibility: "Low-income veterans across Southern California",
    source_name: "Public Counsel", source_type: "nonprofit",
  },
  {
    section: "F", title: "Los Angeles Regional Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "One of the largest food banks in the country distributing 130+ million pounds of food annually through 700+ partner agencies across LA County. CalFresh enrollment assistance and senior food programs.",
    website_url: "https://www.lafoodbank.org/",
    phone: "(323) 234-3030", address: "1734 East 41st Street",
    city: "Los Angeles", zip: "90058",
    eligibility: "Low-income LA County residents (food-insecure veterans included)",
    source_name: "LA Regional Food Bank", source_type: "nonprofit",
  },
  {
    section: "F", title: "ACCESS Center (LA County Department of Mental Health)",
    cat: "mental-health", sub: "Crisis Support",
    desc: "LA County's 24/7 mental health helpline — connects veterans and residents to county mental health services, mobile crisis response (PMRT), psychiatric urgent care, and community-based providers.",
    website_url: "https://dmh.lacounty.gov/our-services/access/",
    phone: "(800) 854-7771", address: "550 South Vermont Avenue",
    city: "Los Angeles", zip: "90020",
    eligibility: "All LA County residents",
    source_name: "LA County DMH", source_type: "county_government",
  },
  {
    section: "F", title: "NAMI Greater Los Angeles County",
    cat: "mental-health", sub: "Peer Support Groups",
    desc: "Free peer support, family-to-family education, and advocacy for individuals and families affected by mental illness across greater LA — includes veteran and military family programming.",
    website_url: "https://namigla.org/",
    phone: "(310) 889-7200", address: "4953 West Slauson Avenue",
    city: "Los Angeles", zip: "90056",
    eligibility: "Anyone affected by mental illness",
    source_name: "NAMI GLAC", source_type: "nonprofit",
  },
  {
    section: "F", title: "Didi Hirsch Mental Health Services - Suicide Prevention Center",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "Operator of the nation's first suicide prevention center (1958) and a 988 Suicide & Crisis Lifeline crisis center. 24/7 crisis line, survivor-of-suicide-loss groups, and veteran outreach.",
    website_url: "https://didihirsch.org/services/suicide-prevention/",
    phone: "(800) 273-8255", address: "4760 South Sepulveda Boulevard",
    city: "Culver City", zip: "90230",
    eligibility: "Anyone in crisis or affected by suicide",
    source_name: "Didi Hirsch", source_type: "nonprofit",
  },
  {
    section: "F", title: "South Bay One-Stop Career Center (Carson)",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "Workforce development center with EDD Disabled Veterans Outreach Program (DVOP) and Local Veteran Employment Representative (LVER) staff providing veteran-priority employment services.",
    website_url: "https://laceojobs.com/",
    phone: "(310) 970-7700", address: "1845 East Carson Street",
    city: "Carson", zip: "90745",
    eligibility: "Veterans (priority of service); other job seekers",
    source_name: "LA County WDACS", source_type: "county_government",
  },
  {
    section: "F", title: "Bob Hope USO Los Angeles",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "USO center at LAX serving active-duty, transitioning service members, veterans, and military families with travel respite, meals, family rooms, and reintegration programs.",
    website_url: "https://losangeles.uso.org/",
    phone: "(310) 645-3716", address: "380 World Way, LAX Tom Bradley Terminal",
    city: "Los Angeles", zip: "90045",
    eligibility: "Active-duty, veterans, and military families",
    source_name: "USO Los Angeles", source_type: "nonprofit",
  },
  {
    section: "F", title: "Operation Gratitude",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "National nonprofit (HQ in Chatsworth) sending care packages and handwritten letters to deployed troops, veterans, and first responders. Volunteer assembly events open to community.",
    website_url: "https://www.operationgratitude.com/",
    phone: "(818) 269-3134", address: "21100 Lassen Street",
    city: "Chatsworth", zip: "91311",
    eligibility: "Service members, veterans, first responders (recipients); volunteers welcome",
    source_name: "Operation Gratitude", source_type: "nonprofit",
  },
  {
    section: "F", title: "Pasadena Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families in Pasadena and the San Gabriel Valley.",
    website_url: "https://www.va.gov/pasadena-vet-center/",
    phone: "(626) 219-7300", address: "1070 East Green Street",
    city: "Pasadena", zip: "91106",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },
  {
    section: "F", title: "Antelope Valley Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Free, confidential readjustment counseling for combat veterans, MST survivors, and bereaved families in the Antelope Valley (Edwards AFB community).",
    website_url: "https://www.va.gov/antelope-valley-vet-center/",
    phone: "(661) 267-1026", address: "38925 Trade Center Drive, Suite J",
    city: "Palmdale", zip: "93551",
    eligibility: "Combat veterans, MST survivors, families of fallen service members",
    source_name: "VA.gov", source_type: "federal_government",
  },

  // ===== G — San Diego Core =====
  {
    section: "G", title: "Veterans Village of San Diego",
    cat: "housing", sub: "Transitional Housing",
    desc: "Pioneer of the residential treatment model for homeless veterans (founded 1981). Transitional housing, residential substance recovery, mental health, employment, and the annual San Diego Stand Down.",
    website_url: "https://vvsd.net/",
    phone: "(619) 393-2000", address: "4141 Pacific Highway",
    city: "San Diego", zip: "92110",
    eligibility: "Veterans experiencing homelessness or in recovery",
    source_name: "Veterans Village of San Diego", source_type: "nonprofit",
  },
  {
    section: "G", title: "Interfaith Community Services",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "North County San Diego homeless services nonprofit operating SSVF, recuperative care, transitional housing, and a dedicated Veterans Services program connecting veterans to VA benefits, housing, and employment.",
    website_url: "https://interfaithservices.org/",
    phone: "(760) 489-6380", address: "550 West Washington Avenue",
    city: "Escondido", zip: "92025",
    eligibility: "Low-income individuals and veterans in North County San Diego",
    source_name: "Interfaith Community Services", source_type: "nonprofit",
  },
  {
    section: "G", title: "North County Lifeline",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Crisis intervention, domestic violence services, youth programs, behavioral health, and homeless prevention across North County San Diego — military and veteran families included.",
    website_url: "https://www.nclifeline.org/",
    phone: "(760) 726-6396", address: "200 Michigan Avenue",
    city: "Vista", zip: "92084",
    eligibility: "North County San Diego residents in crisis",
    source_name: "North County Lifeline", source_type: "nonprofit",
  },
  {
    section: "G", title: "Father Joe's Villages",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Largest homeless services provider in San Diego — emergency shelter, transitional and permanent supportive housing, healthcare, mental health, substance recovery, and a dedicated veterans program.",
    website_url: "https://my.neighbor.org/",
    phone: "(619) 446-2100", address: "3350 E Street",
    city: "San Diego", zip: "92102",
    eligibility: "People experiencing homelessness, including veterans",
    source_name: "Father Joe's Villages", source_type: "nonprofit",
  },
  {
    section: "G", title: "San Diego Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Largest hunger-relief organization in San Diego County distributing food through 500+ partner agencies. Operates a Veterans Outreach Program providing monthly food kits to military veterans and families.",
    website_url: "https://sandiegofoodbank.org/",
    phone: "(858) 527-1419", address: "9850 Distribution Avenue",
    city: "San Diego", zip: "92121",
    eligibility: "Food-insecure San Diego County residents (Veterans Program for vets)",
    source_name: "San Diego Food Bank", source_type: "nonprofit",
  },
  {
    section: "G", title: "211 San Diego",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "24/7 information and referral connecting San Diego County residents — including veterans and active-duty families — to housing, food, healthcare, mental health, financial assistance, and the Courage to Call veterans peer line.",
    website_url: "https://211sandiego.org/",
    phone: "211", address: "3860 Calle Fortunada",
    city: "San Diego", zip: "92123",
    eligibility: "All San Diego County residents",
    source_name: "211 San Diego", source_type: "nonprofit",
  },
  {
    section: "G", title: "Courage to Call (211 San Diego Veterans Program)",
    cat: "mental-health", sub: "Peer Support",
    desc: "Veteran peer-to-peer phone and chat support line operated by 211 San Diego — staffed by veterans helping veterans, active-duty, reservists, and military families navigate benefits, mental health, and crisis.",
    website_url: "https://211sandiego.org/courage-to-call/",
    phone: "(877) 698-7838", address: "3860 Calle Fortunada",
    city: "San Diego", zip: "92123",
    eligibility: "Veterans, active-duty, reservists, and military families",
    source_name: "Courage to Call", source_type: "nonprofit",
  },
  {
    section: "G", title: "Salvation Army San Diego Adult Rehabilitation Center",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "Long-term residential substance recovery program for adult men in San Diego, providing housing, work therapy, counseling, and spiritual support at no cost to participants.",
    website_url: "https://westernusa.salvationarmy.org/sandiego_arc/",
    phone: "(619) 239-4037", address: "1335 Broadway",
    city: "San Diego", zip: "92101",
    eligibility: "Adult men seeking recovery from substance abuse",
    source_name: "Salvation Army San Diego ARC", source_type: "nonprofit",
  },
  {
    section: "G", title: "Mental Health Systems San Diego",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Behavioral health nonprofit operating veteran-specific programs across San Diego County including residential treatment, outpatient mental health, and substance recovery for veterans and their families.",
    website_url: "https://mhsinc.org/",
    phone: "(858) 573-2600", address: "9465 Farnham Street",
    city: "San Diego", zip: "92123",
    eligibility: "Veterans and community members in San Diego County",
    source_name: "Mental Health Systems", source_type: "nonprofit",
  },
  {
    section: "G", title: "NAMI San Diego",
    cat: "mental-health", sub: "Peer Support Groups",
    desc: "Free peer support, family-to-family education, advocacy, and military/veteran programming for individuals and families affected by mental illness across San Diego County.",
    website_url: "https://namisandiego.org/",
    phone: "(858) 634-6840", address: "5095 Murphy Canyon Road, Suite 320",
    city: "San Diego", zip: "92123",
    eligibility: "Anyone affected by mental illness",
    source_name: "NAMI San Diego", source_type: "nonprofit",
  },
  {
    section: "G", title: "USO San Diego",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Multiple USO centers serving the largest active-duty military population in the country — Naval Base San Diego, Camp Pendleton, MCRD, and SAN airport. Reintegration programs, family support, and transition assistance.",
    website_url: "https://sandiego.uso.org/",
    phone: "(619) 235-6503", address: "303 A Street",
    city: "San Diego", zip: "92101",
    eligibility: "Active-duty service members, veterans, and military families",
    source_name: "USO San Diego", source_type: "nonprofit",
  },
  {
    section: "G", title: "Marine Corps Base Camp Pendleton",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Largest Marine Corps amphibious training base on the West Coast. Marine Corps Community Services (MCCS) provides transition assistance, family programs, behavioral health, and connection to veteran benefits for active-duty Marines and Sailors transitioning out.",
    website_url: "https://www.pendleton.marines.mil/",
    phone: "(760) 725-4111", address: "Building 1160, Vandegrift Boulevard",
    city: "Camp Pendleton", zip: "92055",
    eligibility: "Active-duty Marines, Sailors, families, and veterans (MCCS programs)",
    source_name: "MCB Camp Pendleton", source_type: "federal_government",
  },
  {
    section: "G", title: "Operation Homefront Transitional Homes Oceanside",
    cat: "family-support", sub: "Military Family Support",
    desc: "Operation Homefront's transitional housing village near Camp Pendleton serving wounded and transitioning military families. Free 6-24 month residency, financial counseling, and pathway-to-homeownership programs.",
    website_url: "https://www.operationhomefront.org/",
    phone: "(760) 967-9300", address: "350 Marie Street",
    city: "Oceanside", zip: "92054",
    eligibility: "Wounded, ill, injured, or transitioning military families",
    source_name: "Operation Homefront", source_type: "nonprofit",
  },
  {
    section: "G", title: "Disabled American Veterans (DAV) Department of California - San Diego Office",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "DAV national service officers providing free VA disability claims, appeals, dependency, and pension assistance — co-located with VA San Diego Regional Office.",
    website_url: "https://davcal.org/",
    phone: "(858) 552-7424", address: "8810 Rio San Diego Drive, Suite 400",
    city: "San Diego", zip: "92108",
    eligibility: "All veterans (free to DAV members and non-members)",
    source_name: "DAV California", source_type: "vso",
  },
  {
    section: "G", title: "Veterans Inc. San Diego (formerly Veterans Multi-Service Center)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "SSVF (Supportive Services for Veteran Families) provider serving homeless and at-risk veterans across San Diego County with rapid re-housing, prevention, and case management.",
    website_url: "https://www.veteransinc.org/",
    phone: "(619) 525-7373", address: "4101 Pacific Highway",
    city: "San Diego", zip: "92110",
    eligibility: "Veterans experiencing or at risk of homelessness",
    source_name: "Veterans Inc.", source_type: "nonprofit",
  },
  {
    section: "G", title: "Wounded Warrior Homes",
    cat: "housing", sub: "Transitional Housing",
    desc: "Transitional housing in San Marcos and Vista for post-9/11 combat-wounded veterans with TBI / PTSD — free room and structured rehabilitation programming for up to 24 months.",
    website_url: "https://www.woundedwarriorhomes.org/",
    phone: "(760) 295-3920", address: "2204 El Camino Real, Suite 200",
    city: "Oceanside", zip: "92054",
    eligibility: "Post-9/11 combat-wounded veterans with TBI/PTSD",
    source_name: "Wounded Warrior Homes", source_type: "nonprofit",
  },
  {
    section: "G", title: "Naval Medical Center San Diego (Balboa Hospital)",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Largest naval hospital on the West Coast (Balboa). Provides healthcare to active-duty service members, retirees, and beneficiaries — major polytrauma and combat casualty treatment center supporting transitioning veterans.",
    website_url: "https://sandiego.tricare.mil/",
    phone: "(619) 532-6400", address: "34800 Bob Wilson Drive",
    city: "San Diego", zip: "92134",
    eligibility: "Active-duty, retirees, and TRICARE beneficiaries",
    source_name: "Defense Health Agency", source_type: "federal_government",
  },
  {
    section: "G", title: "San Diego Workforce Partnership Career Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "San Diego Workforce Partnership operates America's Job Centers across San Diego County with EDD DVOP/LVER veteran-priority employment services, career coaching, and training subsidies.",
    website_url: "https://workforce.org/",
    phone: "(619) 228-2900", address: "3910 University Avenue, Suite 400",
    city: "San Diego", zip: "92105",
    eligibility: "Veterans (priority of service); other job seekers",
    source_name: "San Diego Workforce Partnership", source_type: "nonprofit",
  },
  {
    section: "G", title: "Veterans Legal Institute (Orange County / serves Southern CA)",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Pro bono legal services for active-duty, veterans, and family members across Southern California — discharge upgrades, VA benefits appeals, family law, criminal record expungement, and consumer law.",
    website_url: "https://www.vetslegal.com/",
    phone: "(714) 837-5727", address: "1505 East 17th Street, Suite 108",
    city: "Santa Ana", zip: "92705",
    eligibility: "Active-duty, veterans, and military families",
    source_name: "Veterans Legal Institute", source_type: "nonprofit",
  },
  {
    section: "G", title: "Orange County Veterans Treatment Court",
    cat: "legal", sub: "Criminal Defense",
    desc: "Specialty court diverting eligible veterans facing criminal charges into treatment, mentorship, and rehabilitation in lieu of incarceration. Coordinated with VA, county VSO, and Veterans Legal Institute.",
    website_url: "https://www.occourts.org/divisions/criminal/specialty-courts/veterans-treatment-court/",
    phone: "(657) 622-6878", address: "700 Civic Center Drive West",
    city: "Santa Ana", zip: "92701",
    eligibility: "Veterans facing eligible criminal charges in Orange County",
    source_name: "Orange County Superior Court", source_type: "county_government",
  },
  {
    section: "G", title: "Working Wardrobes - VetNet",
    cat: "employment", sub: "Resume & Career Coaching",
    desc: "Orange County nonprofit providing career coaching, professional clothing, mock interviews, and direct employer placement specifically for veterans transitioning to civilian careers.",
    website_url: "https://workingwardrobes.org/programs/vetnet/",
    phone: "(714) 210-2460", address: "1851 Kettering Street",
    city: "Irvine", zip: "92614",
    eligibility: "Veterans transitioning to civilian employment",
    source_name: "Working Wardrobes", source_type: "nonprofit",
  },
  {
    section: "G", title: "Second Chance Program",
    cat: "employment", sub: "Job Placement Programs",
    desc: "San Diego nonprofit providing job readiness, sober living, and re-entry services for adults including veterans facing barriers to employment from incarceration, addiction, or homelessness.",
    website_url: "https://www.secondchanceprogram.org/",
    phone: "(619) 234-8888", address: "6145 Imperial Avenue",
    city: "San Diego", zip: "92114",
    eligibility: "Adults facing employment barriers (veterans included)",
    source_name: "Second Chance", source_type: "nonprofit",
  },

  // ===== L — Statewide cross-cut programs (small set; rest in P1B) =====
  {
    section: "L", title: "211 California",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "Statewide network of 211 information and referral services connecting Californians — including veterans — to housing, food, healthcare, mental health, public benefits, and disaster response. Serves all 58 counties.",
    website_url: "https://www.211ca.org/",
    phone: "211", address: "1107 9th Street, Suite 600",
    city: "Sacramento", zip: "95814",
    eligibility: "All California residents",
    source_name: "211 California", source_type: "nonprofit",
  },
  {
    section: "L", title: "California CalFresh Information Line",
    cat: "food-assistance", sub: "SNAP Assistance",
    desc: "Statewide information line for California's SNAP program (CalFresh) — eligibility screening, county application referrals, and benefits replacement help. Vets and active-duty often qualify; eligibility unaffected by VA disability comp.",
    website_url: "https://www.cdss.ca.gov/calfresh",
    phone: "(877) 847-3663", address: "744 P Street",
    city: "Sacramento", zip: "95814",
    eligibility: "Low-income California residents",
    source_name: "California Department of Social Services", source_type: "state_government",
  },
  {
    section: "L", title: "California Health Insurance Counseling & Advocacy Program (HICAP)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Statewide free Medicare counseling for California residents 60+ and Medicare beneficiaries — coordinates Medicare with VA healthcare, TRICARE for Life, and Medi-Cal. Counselors at 24 regional sites statewide.",
    website_url: "https://www.aging.ca.gov/Programs_and_Services/Medicare_Counseling/",
    phone: "(800) 434-0222", address: "2880 Gateway Oaks Drive, Suite 200",
    city: "Sacramento", zip: "95833",
    eligibility: "California Medicare beneficiaries and adults 60+",
    source_name: "California Department of Aging", source_type: "state_government",
  },
  {
    section: "L", title: "CalVet College Fee Waiver Program",
    cat: "education", sub: "Tuition Assistance",
    desc: "Statewide CalVet program waiving mandatory system-wide tuition and fees at any California Community College, CSU, or UC for eligible dependents of disabled or deceased California veterans. Saves families thousands annually.",
    website_url: "https://www.calvet.ca.gov/VetServices/Pages/College-Fee-Waiver.aspx",
    phone: "(800) 952-5626", address: "1227 O Street",
    city: "Sacramento", zip: "95814",
    eligibility: "Dependents of disabled or deceased California veterans",
    source_name: "CalVet", source_type: "state_government",
  },
  {
    section: "L", title: "CalVet Home Loans",
    cat: "financial", sub: "VA Loans",
    desc: "California's veterans home loan program offering competitive rates and below-market financing to California veterans for home purchase. Operated by CalVet since 1921; over 425,000 home loans funded.",
    website_url: "https://www.calvet.ca.gov/HomeLoans",
    phone: "(866) 653-2510", address: "1227 O Street",
    city: "Sacramento", zip: "95814",
    eligibility: "California veterans purchasing primary residence in California",
    source_name: "CalVet", source_type: "state_government",
  },
  {
    section: "L", title: "California EDD Veterans Employment Services (DVOP/LVER)",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "California Employment Development Department operates Disabled Veterans Outreach Program (DVOP) and Local Veterans Employment Representative (LVER) services through America's Job Centers across the state — veterans receive priority of service for all USDOL-funded employment services.",
    website_url: "https://edd.ca.gov/en/jobs_and_training/Veterans_Services",
    phone: "(800) 758-0398", address: "722 Capitol Mall",
    city: "Sacramento", zip: "95814",
    eligibility: "California veterans seeking employment",
    source_name: "California EDD", source_type: "state_government",
  },
  {
    section: "L", title: "California Mental Health Services Act / CalHOPE Warm Line",
    cat: "mental-health", sub: "Peer Support",
    desc: "Statewide free, confidential, peer-run emotional support line for any California resident experiencing stress, anxiety, or depression. Operated by Mental Health Association of California with funding from MHSA.",
    website_url: "https://www.calhope.org/",
    phone: "(833) 317-4673", address: "1127 11th Street, Suite 925",
    city: "Sacramento", zip: "95814",
    eligibility: "All California residents",
    source_name: "CalHOPE", source_type: "state_government",
  },
];

runSeed(ROWS, {
  state: "CA",
  commit: COMMIT,
  scriptName: "seed-ca-phase1a",
  sectionLabels: {
    A: "CalVet HQ + 8 Veterans Homes",
    B: "VA Medical Centers (8 systems)",
    C: "Vet Centers (high-conf subset)",
    D: "Top County VSOs (12)",
    E: "National Cemeteries (8)",
    F: "Los Angeles Core",
    G: "San Diego Core",
    L: "Statewide cross-cut programs",
  },
});
