/**
 * Texas ROUND 2 — Phase 4: Metro Saturation (Florida SOP)
 * DAL / HOU / SA / AUS / EP / Killeen depth fillers across multiple cats.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  // HOUSTON
  { section: "HOU", title: "Coalition for the Homeless of Houston/Harris County", cat: "housing", sub: "Homeless Veteran Services", city: "Houston", website_url: "https://www.homelesshouston.org/", source_name: "Coalition for the Homeless of Houston/Harris County", source_type: "nonprofit", phone: "713-739-7514", desc: "Lead agency of The Way Home — Houston/Harris County's coordinated Continuum of Care that has housed 35,000+ homeless individuals since 2012, including 9,000+ veterans. Coordinates HUD-VASH, SSVF, and rapid-rehousing referrals across 100+ partner agencies in Harris/Fort Bend/Montgomery counties." },
  { section: "HOU", title: "SEARCH Homeless Services", cat: "housing", sub: "Homeless Veteran Services", city: "Houston", website_url: "https://www.searchhomeless.org/", source_name: "SEARCH Homeless Services", source_type: "nonprofit", phone: "713-739-7752", address: "2505 Fannin St, Houston, TX 77002", zip: "77002", desc: "Houston nonprofit operating the House of Tiny Treasures Early Childhood Education center plus engagement, employment, and housing-stabilization services for adults experiencing homelessness — partner with The Way Home and a key referral source for SSVF/HUD-VASH veteran enrollment in Harris County." },
  { section: "HOU", title: "Star of Hope Mission", cat: "housing", sub: "Emergency Housing", city: "Houston", website_url: "https://www.sohmission.org/", source_name: "Star of Hope Mission", source_type: "nonprofit", phone: "713-227-8900", desc: "Houston's largest emergency-shelter system serving 1,000+ men, women, and children nightly across the Men's Development Center, Women & Family Development Center, Cornerstone Community, and Doris & Carloss Morris Memorial Men's Center. Veteran-priority intake and recovery programming." },
  { section: "HOU", title: "Houston Volunteer Lawyers", cat: "legal", sub: "Pro Bono Legal Services", city: "Houston", website_url: "https://makejusticehappen.org/", source_name: "Houston Volunteer Lawyers", source_type: "nonprofit", phone: "713-228-0735", desc: "Pro-bono arm of the Houston Bar Association — Texas's largest pro-bono legal-services organization. Free civil legal help in family law, consumer, housing, probate, and veteran-specific matters (USERRA, discharge upgrades) for low-income Harris County residents including veterans." },
  { section: "HOU", title: "AVDA — Aid to Victims of Domestic Abuse", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Houston", website_url: "https://avda-tx.org/", source_name: "Aid to Victims of Domestic Abuse (AVDA)", source_type: "nonprofit", phone: "713-224-9911", desc: "Houston-based nonprofit providing free legal representation, counseling, and the Battering Intervention and Prevention Program (BIPP) for survivors of domestic violence in Harris and surrounding counties. 24-hour Greater Houston DV Hotline 713-528-2121." },
  { section: "HOU", title: "METROLift Paratransit (METRO Houston)", cat: "transportation", sub: "Veteran Transportation Programs", city: "Houston", website_url: "https://www.ridemetro.org/riding-metro/services/metrolift", source_name: "Metropolitan Transit Authority of Harris County (METRO)", source_type: "transit_authority", phone: "713-225-0119", desc: "METRO Houston's federally-mandated ADA paratransit service offering door-to-door rides for individuals (including disabled veterans) unable to use fixed-route bus or rail. Same low fare as fixed-route; serves Harris County METRO service area; also offers RideSponsor and curb-to-curb same-day service via METRO Curb2Curb." },

  // DALLAS
  { section: "DAL", title: "The Bridge Homeless Recovery Center", cat: "housing", sub: "Emergency Housing", city: "Dallas", website_url: "https://www.bridgehrc.org/", source_name: "The Bridge Homeless Recovery Center", source_type: "nonprofit", phone: "214-670-1100", address: "1818 Corsicana St, Dallas, TX 75201", zip: "75201", desc: "Dallas's primary low-barrier homeless recovery campus serving 800+ adults daily — emergency shelter, day services, mental-health and SUD treatment, employment services, and housing-navigation. Partners with Dallas VAMC HCHV outreach team for veteran identification and HUD-VASH referrals." },
  { section: "DAL", title: "Family Gateway", cat: "housing", sub: "Emergency Housing", city: "Dallas", website_url: "https://familygateway.org/", source_name: "Family Gateway", source_type: "nonprofit", phone: "214-823-4500", desc: "Dallas's largest provider of homeless services for families with children — emergency shelter at multiple Dallas locations, rapid-rehousing, and the lead agency for families in the Dallas Continuum of Care. Veteran-family priority enrollment via SSVF." },
  { section: "DAL", title: "Dallas Volunteer Attorney Program (DVAP)", cat: "legal", sub: "Pro Bono Legal Services", city: "Dallas", website_url: "https://www.dvapdallas.org/", source_name: "Dallas Volunteer Attorney Program", source_type: "nonprofit", phone: "214-748-1234", desc: "Joint pro-bono program of the Dallas Bar Association and Legal Aid of NorthWest Texas providing free civil legal representation to low-income Dallas County residents. Family law, consumer, housing, probate, immigration, and the Veterans Legal Initiative clinics statewide." },
  { section: "DAL", title: "North Texas Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Plano", website_url: "https://ntfb.org/", source_name: "North Texas Food Bank", source_type: "food_bank", phone: "214-330-1396", address: "3677 Mapleshade Ln, Plano, TX 75075", zip: "75075", desc: "Feeding Texas / Feeding America member food bank serving 13 North Texas counties (Dallas, Collin, Denton, Ellis, Hunt, Kaufman, Rockwall, Navarro, Fannin, Grayson, Cooke, Lamar, Delta) through 500+ partner agencies. Veteran-friendly intake at all partner pantries." },
  { section: "DAL", title: "Genesis Women's Shelter & Support", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Dallas", website_url: "https://www.genesisshelter.org/", source_name: "Genesis Women's Shelter & Support", source_type: "nonprofit", phone: "214-389-7700", desc: "Dallas's largest domestic-violence shelter and support agency — emergency shelter, transitional housing, individual and group counseling, legal advocacy, and Annie's House children's services for women and children fleeing domestic violence in Dallas County. 24-hour hotline 214-946-4357." },
  { section: "DAL", title: "Family Place", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Dallas", website_url: "https://www.familyplace.org/", source_name: "The Family Place", source_type: "nonprofit", phone: "214-559-2170", desc: "Dallas-based domestic-violence agency operating the largest DV emergency shelter in Texas plus the Safe Campus transitional-housing program, counseling, advocacy, and the Be Project youth-violence-prevention program. 24-hour Dallas County DV Hotline 214-941-1991." },
  { section: "DAL", title: "DART Paratransit", cat: "transportation", sub: "Veteran Transportation Programs", city: "Dallas", website_url: "https://www.dart.org/guide/transit-accessibility/dart-paratransit", source_name: "Dallas Area Rapid Transit (DART)", source_type: "transit_authority", phone: "214-515-7272", desc: "DART's federally-mandated ADA paratransit service offering door-to-door curb-to-curb rides for individuals (including disabled veterans) unable to use fixed-route DART bus or rail. Reduced fare for VA-rated disabled veterans; serves all 13 DART member cities across Dallas and Collin counties." },

  // SAN ANTONIO
  { section: "SA", title: "Haven for Hope", cat: "housing", sub: "Emergency Housing", city: "San Antonio", website_url: "https://www.havenforhope.org/", source_name: "Haven for Hope of Bexar County", source_type: "nonprofit", phone: "210-220-2100", address: "1 Haven for Hope Way, San Antonio, TX 78207", zip: "78207", desc: "Bexar County's transformational homeless campus — 22-acre downtown San Antonio campus with on-site shelter, transitional housing, mental-health and SUD treatment, employment services, and 100+ partner agencies including Audie L. Murphy VAMC HCHV outreach for HUD-VASH/SSVF veteran enrollment." },
  { section: "SA", title: "SAMMinistries", cat: "housing", sub: "Transitional Housing", city: "San Antonio", website_url: "https://samm.org/", source_name: "SAMMinistries", source_type: "nonprofit", phone: "210-340-0302", desc: "San Antonio interfaith homelessness-prevention agency operating the Transitional Living and Learning Center (TLLC) campus, scattered-site permanent supportive housing, and homelessness-prevention rapid-rehousing services. Veteran-family priority enrollment via SSVF." },
  { section: "SA", title: "Family Violence Prevention Services / Battered Women & Children's Shelter", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "San Antonio", website_url: "https://www.fvps.org/", source_name: "Family Violence Prevention Services, Inc.", source_type: "nonprofit", phone: "210-733-8810", desc: "San Antonio's primary DV agency operating the Battered Women & Children's Shelter, transitional housing, counseling, court advocacy, and economic-empowerment programs for survivors in Bexar County. 24-hour DV Crisis Hotline 210-733-8810." },
  { section: "SA", title: "VIA Trans Paratransit", cat: "transportation", sub: "Veteran Transportation Programs", city: "San Antonio", website_url: "https://www.viainfo.net/transportation-services/viatrans/", source_name: "VIA Metropolitan Transit", source_type: "transit_authority", phone: "210-362-2140", desc: "VIA's federally-mandated ADA paratransit service offering door-to-door curb-to-curb rides for individuals (including disabled veterans) unable to use fixed-route VIA bus across Bexar County. Free for VA-rated disabled veterans with a VIA-issued ADA Paratransit ID." },
  { section: "SA", title: "San Antonio Food Bank Mobile Pantries", cat: "food-assistance", sub: "Food Pantries", city: "San Antonio", website_url: "https://safoodbank.org/find-food/", source_name: "San Antonio Food Bank", source_type: "food_bank", phone: "210-431-8326", desc: "San Antonio Food Bank's Mobile Mercado and Mobile Pantry network distributing fresh produce, protein, and shelf-stable food at 400+ partner pantry sites and rotating pop-up locations across 16 South Central Texas counties. Veteran-friendly intake; no documentation required." },

  // AUSTIN
  { section: "AUS", title: "Caritas of Austin", cat: "housing", sub: "Homeless Veteran Services", city: "Austin", website_url: "https://caritasofaustin.org/", source_name: "Caritas of Austin", source_type: "nonprofit", phone: "512-479-4610", address: "611 Neches St, Austin, TX 78701", zip: "78701", desc: "Travis County nonprofit providing permanent supportive housing, rapid-rehousing, employment services, food assistance, and refugee resettlement for adults experiencing homelessness — including the largest Veteran SSVF provider in Travis County coordinating HUD-VASH and rapid-rehousing for veteran families." },
  { section: "AUS", title: "Front Steps", cat: "housing", sub: "Emergency Housing", city: "Austin", website_url: "https://frontsteps.org/", source_name: "Front Steps", source_type: "nonprofit", phone: "512-305-4100", desc: "Austin nonprofit operating the Austin Resource Center for the Homeless (ARCH) — a 24/7 day shelter, men's overnight shelter, and case-management hub in downtown Austin. Coordinates with Austin VA Outpatient Clinic HCHV outreach for HUD-VASH/SSVF veteran enrollment." },
  { section: "AUS", title: "SAFE Alliance Austin", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Austin", website_url: "https://www.safeaustin.org/", source_name: "The SAFE Alliance", source_type: "nonprofit", phone: "512-267-7233", desc: "Austin's primary DV/sexual-assault/child-abuse agency — operates the SAFE Place emergency shelter, transitional housing, counseling, legal advocacy, the Strong Start Children's Shelter, and the Eloise House SANE forensic clinic. 24-hour SafeLine 512-267-7233 (text, call, or chat)." },
  { section: "AUS", title: "MetroAccess (CapMetro Paratransit)", cat: "transportation", sub: "Veteran Transportation Programs", city: "Austin", website_url: "https://www.capmetro.org/metroaccess", source_name: "Capital Metropolitan Transportation Authority (CapMetro)", source_type: "transit_authority", phone: "512-369-6080", desc: "CapMetro's federally-mandated ADA paratransit service offering door-to-door rides for individuals (including disabled veterans) unable to use fixed-route CapMetro bus or rail across the CapMetro service area in Travis County. Reduced fare for VA-rated disabled veterans." },

  // EL PASO
  { section: "EP", title: "Opportunity Center for the Homeless", cat: "housing", sub: "Emergency Housing", city: "El Paso", website_url: "https://www.opportunitycenterhomeless.org/", source_name: "Opportunity Center for the Homeless", source_type: "nonprofit", phone: "915-577-0069", address: "1208 Myrtle Ave, El Paso, TX 79901", zip: "79901", desc: "El Paso's largest homeless-services campus operating the Welcome Center day shelter, men's and women's overnight shelters, transitional housing, the OASIS senior shelter, and the Veteran's Shelter — the only veteran-dedicated homeless shelter in El Paso. Coordinates with El Paso VA HCS HCHV team." },
  { section: "EP", title: "El Pasoans Fighting Hunger Food Bank", cat: "food-assistance", sub: "Food Banks", city: "El Paso", website_url: "https://elpasoansfightinghunger.org/", source_name: "El Pasoans Fighting Hunger Food Bank", source_type: "food_bank", phone: "915-298-0353", desc: "Feeding America / Feeding Texas member food bank serving El Paso, Hudspeth, Culberson, and Brewster counties through 175+ partner agencies plus mobile pantries. Largest food bank in West Texas; veteran-friendly intake; bilingual Spanish/English." },
  { section: "EP", title: "Center Against Sexual & Family Violence", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "El Paso", website_url: "https://www.casfv.org/", source_name: "Center Against Sexual and Family Violence", source_type: "nonprofit", phone: "915-593-7300", desc: "El Paso's primary DV/sexual-assault agency — operates the Centro de Violencia Familiar emergency shelter, transitional housing, bilingual counseling, legal advocacy, and the SANE forensic-exam program. 24-hour bilingual hotline 915-593-7300." },

  // KILLEEN / FORT CAVAZOS
  { section: "FC", title: "Families in Crisis", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Killeen", website_url: "https://www.familiesincrisis.net/", source_name: "Families in Crisis, Inc.", source_type: "nonprofit", phone: "254-634-1184", address: "P.O. Box 25, Killeen, TX 76540", zip: "76540", desc: "Bell, Coryell, Hamilton, Lampasas, Milam, Mills, and San Saba counties' primary DV / sexual-assault agency — operates the Genesis women's shelter in Killeen, transitional housing, counseling, legal advocacy, and the Children's Advocacy Center of Central Texas. Specialized military-family programming for Fort Cavazos." },
  { section: "FC", title: "Workforce Solutions of Central Texas — Killeen Veterans Workforce", cat: "employment", sub: "DVOP / Workforce Programs", city: "Killeen", website_url: "https://www.workforcelink.com/Veteran-Services", source_name: "Workforce Solutions of Central Texas", source_type: "workforce_board", phone: "254-200-2020", address: "300 Cheyenne Dr, Killeen, TX 76542", zip: "76542", desc: "Central Texas Workforce Development Board's Killeen Workforce Center hosting DVOP (Disabled Veterans' Outreach Program) specialists and LVERs (Local Veterans' Employment Representatives) for transitioning Fort Cavazos service members and Central Texas veterans across 7 counties." },
];

console.log(`[seed-tx-r2-phase4] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "TX", commit: COMMIT, scriptName: "TX Round 2 — Phase 4: Metro Saturation",
  batchTag: "tx-r2-phase4", allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: { HOU: "Houston metro depth", DAL: "Dallas metro depth", SA: "San Antonio metro depth", AUS: "Austin metro depth", EP: "El Paso metro depth", FC: "Killeen / Fort Cavazos depth" },
}).catch((e) => { console.error(e); process.exit(1); });
