/**
 * NY ROLLOUT — PHASE 3: COUNTY / BENEFITS BACKBONE
 * Founder one-phase-per-run governance lock.
 *
 * Scope (~34 rows): Easy verified county wins.
 *   A. NYC city-wide (Mayor's Office of Veterans' Services, HRA, DSS, DFTA, ACCESS HRA, MOPD, SBS Workforce1, plus CIDNY disability)
 *   B. Erie County (VSA, DSS, Aging)
 *   C. Monroe County / Rochester (Human Services, Aging, Public Health, RochesterWorks)
 *   D. Onondaga County / Syracuse (VSA, DSS, Aging, Health)
 *   E. Nassau County (DSS, HempsteadWorks workforce)
 *   F. Westchester County (VSA, DSS, Senior Programs, Westchester-Putnam OneStop)
 *   G. Broome County / Binghamton (VSA, DSS, Aging)
 *   H. Dutchess County / Poughkeepsie (Aging, OneStop)
 *   I. Statewide / cross-county (DOL Career Centers, NY Connects, ACCES-VR Independent Living Centers, statewide ILC)
 *
 * SKIPPED PER FOUNDER RULE "if county source is messy, skip quickly":
 *   - Albany County (whole site Cloudflare-403 to non-browser UAs — engine would fail liveness gate)
 *   - Suffolk County (same Cloudflare-403 pattern)
 *   - Rockland County (same Cloudflare-403 pattern)
 *   - Ulster County (same Cloudflare-403 pattern)
 *   - Orange County (vendor CMS — every numeric path /154/, /153/ etc redirects to wrong sub-page)
 *   - Monroe County Veterans Service Agency (no working URL on monroecounty.gov; will revisit P4)
 *   - Nassau County Veterans Service Agency (no working URL on nassaucountyny.gov; will revisit P4)
 *   - Nassau County Office of the Aging (no working URL; will revisit P4)
 *   - Dutchess County Veterans Services + DCFS (every Departments/* path redirects to custom404.htm)
 *   - CNY Works workforce board (cnyworks.com hijacked, .org DNS fail)
 *   - Capital Region / Rockland / Broome-Tioga workforce boards (DNS fail)
 *
 * All 5 skipped counties have their VSO covered upstream by the
 * "NY DVS — County Veterans Service Agency Directory" row already shipped in P1
 * (https://veterans.ny.gov/county-veterans-service-officers).
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN = process.argv.includes("--allow-broken-urls");
const ALLOW_BLEED = process.argv.includes("--allow-zip-bleed");

const ROWS: SeedRow[] = [
  // ============== A. NYC CITY-WIDE (8) ==============
  { section: "NYC", title: "NYC Mayor's Office of Veterans' Services (DVS)", cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation", city: "New York", website_url: "https://www.nyc.gov/site/veterans/index.page", source_name: "NYC Department of Veterans' Services", source_type: "city_government", phone: "212-416-5250", address: "1 Centre Street, Suite 2208, New York, NY 10007", zip: "10007", desc: "NYC Mayor's Office of Veterans' Services (DVS) — citywide cabinet-level agency for the 200,000+ veterans in NYC; benefits navigation, VetConnectNYC referral platform (housing, jobs, mental health), Mission: VetCheck wellness calls, Veteran Resource Centers in all 5 boroughs; helps veterans access VA + NYC + state benefits in one stop." },
  { section: "NYC", title: "NYC Human Resources Administration (HRA)", cat: "financial", sub: "Emergency Financial Assistance", city: "New York", website_url: "https://www.nyc.gov/site/hra/index.page", source_name: "NYC Human Resources Administration", source_type: "city_government", phone: "718-557-1399", address: "4 World Trade Center, 150 Greenwich Street, New York, NY 10007", zip: "10007", desc: "NYC Human Resources Administration (HRA) — citywide social services agency administering Cash Assistance, SNAP, Medicaid, HEAP, child support enforcement, emergency rental assistance, adult protective services; 30+ Job Centers and SNAP Centers across 5 boroughs; serves veterans alongside general low-income population in NYC." },
  { section: "NYC", title: "NYC Department of Social Services (DSS)", cat: "financial", sub: "Benefits Counseling", city: "New York", website_url: "https://www.nyc.gov/site/dss/index.page", source_name: "NYC Department of Social Services", source_type: "city_government", phone: "311", address: "150 Greenwich Street, New York, NY 10007", zip: "10007", desc: "NYC Department of Social Services (DSS) — parent umbrella over HRA + Department of Homeless Services (DHS); coordinates anti-poverty programs, public benefits eligibility, homeless prevention/shelter, emergency assistance for any New Yorker; serves veterans alongside general low-income population." },
  { section: "NYC", title: "NYC Aging (Department for the Aging / DFTA)", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "New York", website_url: "https://www.nyc.gov/site/dfta/index.page", source_name: "NYC Department for the Aging", source_type: "city_government", phone: "212-244-6469", address: "2 Lafayette Street, New York, NY 10007", zip: "10007", desc: "NYC Aging (DFTA) — citywide agency for 1.7M New Yorkers age 60+; 250+ Older Adult Centers (free meals, programs, social work), home-delivered meals (Meals on Wheels), case management, caregiver support, NY Connects info & referral, elder abuse prevention, friendly visiting; serves veteran seniors alongside general population." },
  { section: "NYC", title: "ACCESS HRA", cat: "food-assistance", sub: "SNAP Assistance", city: "New York", website_url: "https://access.nyc.gov/", source_name: "NYC Human Resources Administration", source_type: "city_government", phone: "311", address: "Online portal — NYC Human Resources Administration, New York, NY 10007", zip: "10007", desc: "ACCESS HRA / ACCESS NYC — official NYC Human Resources Administration online portal to apply, recertify, check status, upload documents, and pay back rent for SNAP, Cash Assistance, Medicaid, HEAP, emergency rental assistance, school meals, and other benefits; eligibility screener for 30+ programs; serves veterans citywide." },
  { section: "NYC", title: "NYC Mayor's Office for People with Disabilities (MOPD)", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "New York", website_url: "https://www.nyc.gov/site/mopd/index.page", source_name: "NYC Mayor's Office for People with Disabilities", source_type: "city_government", phone: "212-788-2830", address: "100 Gold Street, 2nd Floor, New York, NY 10038", zip: "10038", desc: "NYC Mayor's Office for People with Disabilities (MOPD) — citywide agency ensuring disabled New Yorkers (1M+) have equal access to NYC programs/services; ADA enforcement, accessible transit advocacy, NYC: ATWORK disability employment, Disability Service Facilitator program, NYC Accessible Mobile Transit (AMT); serves disabled veterans alongside general population." },
  { section: "NYC", title: "NYC Workforce1 Career Centers", cat: "employment", sub: "DVOP / Workforce Programs", city: "New York", website_url: "https://www.nyc.gov/site/sbs/index.page", source_name: "NYC Department of Small Business Services", source_type: "city_government", phone: "311", address: "1 Liberty Plaza, 11th Floor, New York, NY 10006", zip: "10006", desc: "NYC Workforce1 Career Centers — NYC Department of Small Business Services job-placement network with 18 centers in all 5 boroughs (incl. industry-specialized centers for healthcare, tech, construction, transportation, manufacturing); free job-search, training referrals, employer matching, sector-specific career advisors; veteran priority of service via DVOP/LVER staff." },
  { section: "NYC", title: "Center for Independence of the Disabled, NY (CIDNY)", cat: "disabled-veterans", sub: "Independent Living & Daily Support", city: "New York", website_url: "https://www.cidny.org/", source_name: "Center for Independence of the Disabled, NY", source_type: "nonprofit", phone: "212-674-2300", address: "841 Broadway, Suite 301, New York, NY 10003", zip: "10003", desc: "CIDNY — NYC area Independent Living Center serving people with all disabilities since 1978; benefits advisement (SSDI/SSI/Medicaid), independent living skills training, peer support, advocacy, NY State of Health navigation, transition services, ADA enforcement; offices in Manhattan and Queens; serves disabled veterans alongside general population." },

  // ============== B. ERIE COUNTY / Buffalo (3) ==============
  { section: "ERIE", title: "Erie County Veterans Service Agency", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Buffalo", website_url: "https://www3.erie.gov/veterans/", source_name: "Erie County Department of Veterans Services", source_type: "county_government", phone: "716-858-6363", address: "95 Franklin Street, 2nd Floor, Buffalo, NY 14202", zip: "14202", desc: "Erie County Veterans Service Agency — county-level office for 50,000+ Western NY veterans; free assistance with VA disability claims, pension applications, healthcare enrollment, education benefits, DD-214 retrieval, NYS Blind Annuity, NY State Veterans' Homes referrals; accredited by NY DVS; serves Erie County (Buffalo + suburbs)." },
  { section: "ERIE", title: "Erie County Department of Social Services", cat: "financial", sub: "Emergency Financial Assistance", city: "Buffalo", website_url: "https://www3.erie.gov/socialservices/", source_name: "Erie County Department of Social Services", source_type: "county_government", phone: "716-858-8000", address: "95 Franklin Street, Buffalo, NY 14202", zip: "14202", desc: "Erie County Department of Social Services — administers Temporary Assistance, SNAP, Medicaid, HEAP energy assistance, child welfare, adult protective services, daycare subsidy for 950K Western NY residents; 24/7 Child & Adult Protective hotlines; serves veteran families alongside general low-income population." },
  { section: "ERIE", title: "Erie County Department of Senior Services", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Buffalo", website_url: "https://www3.erie.gov/aging/", source_name: "Erie County Department of Senior Services", source_type: "county_government", phone: "716-858-8526", address: "95 Franklin Street, 8th Floor, Buffalo, NY 14202", zip: "14202", desc: "Erie County Department of Senior Services — county AAA for 200,000+ residents 60+; congregate + home-delivered meals (Meals on Wheels Erie), NY Connects info & referral, EISEP in-home aide, caregiver respite, transportation, elder abuse, health insurance counseling (HIICAP); serves veteran seniors alongside general aging population." },

  // ============== C. MONROE COUNTY / Rochester (4) ==============
  { section: "MON", title: "Monroe County Department of Human Services", cat: "financial", sub: "Emergency Financial Assistance", city: "Rochester", website_url: "https://www.monroecounty.gov/hs", source_name: "Monroe County Department of Human Services", source_type: "county_government", phone: "585-753-6960", address: "111 Westfall Road, Rochester, NY 14620", zip: "14620", desc: "Monroe County Department of Human Services — administers Temporary Assistance, SNAP, Medicaid, HEAP, child support, child welfare, adult protective services, foster care, daycare subsidy for 750K Greater Rochester residents; serves veteran families alongside general low-income population." },
  { section: "MON", title: "Monroe County Office for the Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Rochester", website_url: "https://www.monroecounty.gov/aging", source_name: "Monroe County Office for the Aging", source_type: "county_government", phone: "585-753-6280", address: "1900 South Clinton Avenue, Rochester, NY 14618", zip: "14618", desc: "Monroe County Office for the Aging — county AAA for 175,000+ residents 60+; NY Connects info & referral, congregate + home-delivered meals via Lifespan/CCSI, EISEP in-home aide, caregiver respite, HIICAP Medicare counseling, elder abuse prevention, naturally occurring retirement community (NORC) support; serves veteran seniors alongside general aging population." },
  { section: "MON", title: "Monroe County Department of Public Health", cat: "healthcare", sub: "Preventive Care & Wellness", city: "Rochester", website_url: "https://www.monroecounty.gov/health", source_name: "Monroe County Department of Public Health", source_type: "county_government", phone: "585-753-5500", address: "111 Westfall Road, Room 950, Rochester, NY 14620", zip: "14620", desc: "Monroe County Department of Public Health — public health for 750K Rochester-area residents; immunization clinic, STI clinic, lead poisoning prevention, communicable disease surveillance, environmental health, WIC, early intervention, opioid response (overdose prevention + Narcan), maternal/child health; serves Monroe County veterans alongside general population." },
  { section: "MON", title: "RochesterWorks!", cat: "employment", sub: "DVOP / Workforce Programs", city: "Rochester", website_url: "https://rochesterworks.org/", source_name: "RochesterWorks!", source_type: "nonprofit", phone: "585-258-3500", address: "100 College Avenue, Rochester, NY 14607", zip: "14607", desc: "RochesterWorks! — designated Workforce Development Board for Monroe County; operates 2 American Job Center career centers (College Ave + Goodman Plaza) offering free job-search assistance, career coaching, training scholarships, on-the-job training, business services; veteran priority of service via DVOP/LVER staff." },

  // ============== D. ONONDAGA COUNTY / Syracuse (4) ==============
  { section: "ONON", title: "Onondaga County Veterans Service Agency", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Syracuse", website_url: "https://onondaga.gov/veterans/", source_name: "Onondaga County Veterans Service Agency", source_type: "county_government", phone: "315-435-3219", address: "421 Montgomery Street, 11th Floor, Syracuse, NY 13202", zip: "13202", desc: "Onondaga County Veterans Service Agency — county-level office for 25,000+ Central NY veterans; free assistance with VA disability claims, pension, healthcare enrollment, education benefits, DD-214, NYS Blind Annuity, transportation to VA appointments, burial benefits; accredited by NY DVS; serves Onondaga County (Syracuse + suburbs)." },
  { section: "ONON", title: "Onondaga County Department of Social Services", cat: "financial", sub: "Emergency Financial Assistance", city: "Syracuse", website_url: "https://onondaga.gov/dss/", source_name: "Onondaga County Department of Social Services", source_type: "county_government", phone: "315-435-2700", address: "421 Montgomery Street, Syracuse, NY 13202", zip: "13202", desc: "Onondaga County Department of Social Services — administers Temporary Assistance, SNAP, Medicaid, HEAP, child support, child welfare, adult protective services, daycare subsidy for 460K Central NY residents; child & adult protective hotlines 24/7; serves veteran families alongside general low-income population." },
  { section: "ONON", title: "Onondaga County Department of Adult & Long Term Care Services (Aging)", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Syracuse", website_url: "https://onondaga.gov/aging/", source_name: "Onondaga County Office for Aging", source_type: "county_government", phone: "315-435-2362", address: "421 Montgomery Street, 11th Floor, Syracuse, NY 13202", zip: "13202", desc: "Onondaga County Department of Adult & Long Term Care Services / Office for Aging — county AAA for Central NY residents 60+; NY Connects info & referral, congregate + home-delivered meals (Meals on Wheels of Syracuse), in-home services, caregiver respite, HIICAP Medicare counseling, elder abuse prevention; serves veteran seniors alongside general aging population." },
  { section: "ONON", title: "Onondaga County Health Department", cat: "healthcare", sub: "Preventive Care & Wellness", city: "Syracuse", website_url: "https://onondaga.gov/health/", source_name: "Onondaga County Health Department", source_type: "county_government", phone: "315-435-3252", address: "421 Montgomery Street, Syracuse, NY 13202", zip: "13202", desc: "Onondaga County Health Department — public health for 460K Central NY residents; immunization clinic, STI clinic, lead poisoning prevention, dental, communicable disease surveillance, environmental health, WIC, early intervention, opioid response, maternal/child health; serves Onondaga County veterans alongside general population." },

  // ============== E. NASSAU COUNTY (2) ==============
  { section: "NASS", title: "Nassau County Department of Social Services", cat: "financial", sub: "Emergency Financial Assistance", city: "Uniondale", website_url: "https://www.nassaucountyny.gov/agencies/DSS/", source_name: "Nassau County Department of Social Services", source_type: "county_government", phone: "516-227-8000", address: "60 Charles Lindbergh Boulevard, Uniondale, NY 11553", zip: "11553", desc: "Nassau County Department of Social Services — administers Temporary Assistance, SNAP, Medicaid, HEAP, child support, child welfare, adult protective services, daycare subsidy for 1.4M Long Island residents; serves veteran families alongside general low-income population." },
  { section: "NASS", title: "HempsteadWorks Career Center (Town of Hempstead)", cat: "employment", sub: "DVOP / Workforce Programs", city: "Hempstead", website_url: "https://hempsteadworks.com/", source_name: "Town of Hempstead Workforce Development", source_type: "city_government", phone: "516-485-5000", address: "50 Clinton Street, Suite 400, Hempstead, NY 11550", zip: "11550", desc: "HempsteadWorks Career Center — Town of Hempstead American Job Center serving the largest township in the U.S. (760K residents); free job-search, career coaching, WIOA-funded training scholarships, business services, on-the-job training, youth programs; veteran priority of service via DVOP/LVER staff; serves Nassau County veterans." },

  // ============== F. WESTCHESTER COUNTY (4) ==============
  { section: "WEST", title: "Westchester County Veterans Service Agency", cat: "va-benefits", sub: "County Veterans Service Offices", city: "White Plains", website_url: "https://veterans.westchestercountyny.gov/", source_name: "Westchester County Veterans Service Agency", source_type: "county_government", phone: "914-995-2145", address: "112 East Post Road, 1st Floor, White Plains, NY 10601", zip: "10601", desc: "Westchester County Veterans Service Agency — county-level office for 30,000+ Westchester veterans; free assistance with VA disability claims, pension applications, healthcare enrollment, education benefits, DD-214 retrieval, burial benefits, NYS Blind Annuity, transportation referrals; accredited by NY DVS; office in White Plains plus satellite hours at municipal offices." },
  { section: "WEST", title: "Westchester County Department of Social Services", cat: "financial", sub: "Emergency Financial Assistance", city: "White Plains", website_url: "https://socialservices.westchestercountyny.gov/", source_name: "Westchester County Department of Social Services", source_type: "county_government", phone: "914-995-3333", address: "85 Court Street, White Plains, NY 10601", zip: "10601", desc: "Westchester County Department of Social Services — administers Temporary Assistance, SNAP, Medicaid, HEAP, child support, child welfare, adult protective services, daycare subsidy for 1M Lower Hudson Valley residents; district offices in White Plains, Mount Vernon, Yonkers, Peekskill, Port Chester; serves veteran families alongside general low-income population." },
  { section: "WEST", title: "Westchester County Department of Senior Programs and Services", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "White Plains", website_url: "https://seniorcitizens.westchestercountyny.gov/", source_name: "Westchester County Department of Senior Programs and Services", source_type: "county_government", phone: "914-813-6300", address: "9 South First Avenue, 10th Floor, Mount Vernon, NY 10550", zip: "10550", desc: "Westchester County Department of Senior Programs and Services — county AAA for 200,000+ residents 60+; congregate + home-delivered meals (Meals on Wheels of Westchester), in-home services (EISEP), caregiver respite, NY Connects info & referral, HIICAP Medicare counseling, elder abuse prevention, livable communities; serves veteran seniors alongside general aging population." },
  { section: "WEST", title: "Westchester-Putnam One-Stop Career Center", cat: "employment", sub: "DVOP / Workforce Programs", city: "White Plains", website_url: "https://westchesterputnamonestop.com/", source_name: "Westchester-Putnam Workforce Development Board", source_type: "county_government", phone: "914-995-3910", address: "120 Bloomingdale Road, White Plains, NY 10605", zip: "10605", desc: "Westchester-Putnam One-Stop Career Center — designated American Job Center for Westchester + Putnam Counties; free job-search assistance, career coaching, WIOA-funded training scholarships, business services, on-the-job training, youth programs (Summer Youth Employment); centers in White Plains, Mount Vernon, Peekskill, Carmel; veteran priority via DVOP/LVER." },

  // ============== G. BROOME COUNTY / Binghamton (3) ==============
  { section: "BRM", title: "Broome County Veterans Service Agency", cat: "va-benefits", sub: "County Veterans Service Offices", city: "Binghamton", website_url: "https://broomecountyny.gov/veterans", source_name: "Broome County Veterans Service Agency", source_type: "county_government", phone: "607-778-2147", address: "60 Hawley Street, 2nd Floor, Binghamton, NY 13901", zip: "13901", desc: "Broome County Veterans Service Agency — county-level office for 14,000+ Southern Tier veterans; free assistance with VA disability claims, pension, healthcare enrollment, education benefits, DD-214, NYS Blind Annuity, burial benefits; accredited by NY DVS; serves Broome County (Binghamton/Endicott/Johnson City)." },
  { section: "BRM", title: "Broome County Department of Social Services", cat: "financial", sub: "Emergency Financial Assistance", city: "Binghamton", website_url: "https://broomecountyny.gov/dss", source_name: "Broome County Department of Social Services", source_type: "county_government", phone: "607-778-1100", address: "36-42 Main Street, Binghamton, NY 13905", zip: "13905", desc: "Broome County Department of Social Services — administers Temporary Assistance, SNAP, Medicaid, HEAP, child support, child welfare, adult protective services, daycare subsidy for 200K Southern Tier residents; serves veteran families alongside general low-income population." },
  { section: "BRM", title: "Broome County Office for Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Binghamton", website_url: "https://broomecountyny.gov/senior", source_name: "Broome County Office for Aging", source_type: "county_government", phone: "607-778-2411", address: "60 Hawley Street, 5th Floor, Binghamton, NY 13901", zip: "13901", desc: "Broome County Office for Aging — county AAA for 60K+ Southern Tier residents 60+; NY Connects info & referral, congregate + home-delivered meals (Action for Older Persons + senior centers), EISEP in-home aide, caregiver respite, HIICAP Medicare counseling, elder abuse prevention; serves veteran seniors alongside general aging population." },

  // ============== H. DUTCHESS COUNTY / Poughkeepsie (2) ==============
  { section: "DUT", title: "Dutchess County Office for the Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Poughkeepsie", website_url: "https://www.dutchessny.gov/Departments/Aging/Office-for-the-Aging.htm", source_name: "Dutchess County Office for the Aging", source_type: "county_government", phone: "845-486-2555", address: "114 Delafield Street, Poughkeepsie, NY 12601", zip: "12601", desc: "Dutchess County Office for the Aging — county AAA for 65,000+ Mid-Hudson residents 60+; NY Connects info & referral, congregate + home-delivered meals via Dutchess senior centers, EISEP in-home aide, caregiver respite, HIICAP Medicare counseling, elder abuse prevention, telephone reassurance; serves veteran seniors alongside general aging population." },
  { section: "DUT", title: "Dutchess One-Stop Career Center", cat: "employment", sub: "DVOP / Workforce Programs", city: "Poughkeepsie", website_url: "https://www.dutchessonestop.org/", source_name: "Dutchess Workforce Development Board", source_type: "county_government", phone: "845-485-2100", address: "191 Main Street, Poughkeepsie, NY 12601", zip: "12601", desc: "Dutchess One-Stop Career Center — designated American Job Center for Dutchess County; free job-search assistance, career coaching, WIOA-funded training scholarships, business services, on-the-job training, youth programs; veteran priority of service via DVOP/LVER staff; serves Mid-Hudson veterans." },

  // ============== I. STATEWIDE / CROSS-COUNTY (4) ==============
  { section: "STATE", title: "NYS DOL Career Centers (Statewide American Job Center Network)", cat: "employment", sub: "DVOP / Workforce Programs", city: "Albany", website_url: "https://dol.ny.gov/career-centers", source_name: "NYS Department of Labor", source_type: "state_government", phone: "888-469-7365", address: "Statewide — NYS Department of Labor, Building 12, Albany, NY 12240", zip: "12240", desc: "NYS DOL Career Centers — statewide network of 90+ American Job Centers covering all 62 NY counties; free job-search, training scholarships (WIOA), unemployment insurance assistance, career coaching, business services; co-located with local workforce boards; veteran priority of service via DVOP / LVER specialists at every center; statewide locator at dol.ny.gov/career-centers." },
  { section: "STATE", title: "NY Connects (Statewide Aging & Disability Resource Center)", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Albany", website_url: "https://nyconnects.ny.gov/", source_name: "NYS Office for the Aging", source_type: "state_government", phone: "800-342-9871", address: "Statewide — NYS Office for the Aging, 2 Empire State Plaza, Albany, NY 12223", zip: "12223", desc: "NY Connects — NYS Office for the Aging statewide Aging & Disability Resource Center for older adults, people with disabilities, family caregivers, veterans; free, unbiased info + assistance + connection to long-term services and supports; one number 1-800-342-9871 connects to local Office for Aging or county DSS in any of 62 counties; online resource directory." },
  { section: "STATE", title: "ACCES-VR Independent Living Centers Directory", cat: "disabled-veterans", sub: "Independent Living & Daily Support", city: "Albany", website_url: "https://acces.nysed.gov/vr/independent-living-centers", source_name: "NYS Education Department — ACCES-VR", source_type: "state_government", phone: "518-474-3817", address: "NYS Education Department, 89 Washington Avenue, Albany, NY 12234", zip: "12234", desc: "ACCES-VR Independent Living Centers Directory — NYS Education Department portal listing all 41 NYS-funded Independent Living Centers covering every NY county; ILCs are consumer-controlled nonprofits providing peer support, independent living skills training, info & referral, individual + systems advocacy, transition services for people with disabilities; serves disabled veterans alongside general population." },
  { section: "STATE", title: "NYS Workers' Compensation Board — Veterans & Military Outreach", cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)", city: "Albany", website_url: "https://www.wcb.ny.gov/", source_name: "NYS Workers' Compensation Board", source_type: "state_government", phone: "877-632-4996", address: "328 State Street, Schenectady, NY 12305", zip: "12305", desc: "NYS Workers' Compensation Board — administers workers' comp, disability benefits, paid family leave, volunteer firefighter/ambulance worker benefits for all NYS workers; district offices in Albany, Binghamton, Brooklyn, Buffalo, Hauppauge, Hempstead, Manhattan, Peekskill, Queens, Rochester, Syracuse; serves veteran workers alongside general population; toll-free advocate hotline 877-632-4996." },
];

console.log(`SEED-NY-P3 — County / Benefits Backbone — ${ROWS.length} rows`);
console.log(`COMMIT=${COMMIT}  ALLOW_BROKEN_URLS=${ALLOW_BROKEN}  ALLOW_ZIP_BLEED=${ALLOW_BLEED}\n`);

(async () => {
  await runSeed(ROWS, {
    state: "NY",
    commit: COMMIT,
    allowBrokenUrls: ALLOW_BROKEN,
    allowZipBleed: ALLOW_BLEED,
    scriptName: "seed-ny-p3",
    batchTag: "ny-p3-county-benefits-backbone",
  });
})();
