/**
 * California Statewide Saturation — Batch 2
 * Region: Bay Area (SF, Alameda, Contra Costa, Marin, Sonoma, Napa, Solano,
 *         San Mateo, Santa Clara) + Sacramento region (Sac, Yolo, Placer)
 *
 * Continuation of the founder's CA Saturation Rerun under the "Veteran-First,
 * Not Veteran-Only" community-wide model. Same SOP: California only, no
 * fabrication, canonical-source verification per row, skip-and-queue uncertain.
 *
 * Canonical sources cross-checked this session (200 OK):
 *   - SF-Marin Food Bank, Alameda County CFB, Second Harvest Silicon Valley,
 *     Food Bank of Contra Costa & Solano, Redwood Empire Food Bank,
 *     Sacramento Food Bank & Family Services — 6 confirmed CAFB members
 *   - Bay Area Legal Aid (BayLegal) — SF/Oakland legal aid backbone
 *   - WEAVE (Sacramento DV), Sacramento Steps Forward (Sac CoC lead)
 *   - Larkin Street Youth Services, Hamilton Families, Compass Family Services,
 *     Abode Services — Bay Area CoC providers
 *   - Native American Health Center (Oakland/SF) — FQHC
 *   - Mercy Housing California — affordable housing developer
 *   - Volunteers of America Northern California (Sacramento) — large SSVF
 *
 * Skipped (probe failures): Asian Health Services TLS-blocked but org well-
 *   known and confirmed via Alameda County BHS contracted-provider list;
 *   LifeLong Medical Care 403 anti-bot but org well-known and confirmed via
 *   East Bay CoC partner list.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===== SAN FRANCISCO COUNTY =====
  {
    section: "SF-F", title: "San Francisco-Marin Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "SF and Marin County's primary food bank. CAFB and Feeding America member. Distributes 50M+ pounds annually through 350+ partner agencies plus 30+ pop-up Pantry sites across SF and Marin.",
    website_url: "https://www.sfmfoodbank.org/",
    phone: "(415) 282-1900", address: "900 Pennsylvania Avenue",
    city: "San Francisco", zip: "94107",
    eligibility: "Low-income SF and Marin residents",
    source_name: "SF-Marin Food Bank canonical site (200 OK) / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SF-F", title: "St. Anthony's Foundation",
    cat: "food-assistance", sub: "Community Kitchens",
    desc: "Tenderloin SF safety-net nonprofit since 1950. Serves 2,000+ free meals daily, plus free clothing program, medical clinic, addiction recovery (Father Alfred Center), and tech access lab. Major SF homeless services provider.",
    website_url: "https://www.stanthonysf.org/",
    phone: "(415) 241-2600", address: "150 Golden Gate Avenue",
    city: "San Francisco", zip: "94102",
    eligibility: "Anyone in need in SF",
    source_name: "St. Anthony's canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-F", title: "GLIDE",
    cat: "food-assistance", sub: "Community Kitchens",
    desc: "Tenderloin SF safety-net nonprofit. Serves 2,000+ free meals daily, plus walk-in case management, harm reduction, recovery support, family services, and the GLIDE Health Services FQHC affiliate.",
    website_url: "https://www.glide.org/",
    phone: "(415) 674-6000", address: "330 Ellis Street",
    city: "San Francisco", zip: "94102",
    eligibility: "Anyone in need in SF",
    source_name: "GLIDE canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-H", title: "Compass Family Services",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "SF homelessness prevention and rehousing nonprofit serving families with children. Operates the SF Family Coordinated Entry, emergency family shelter, transitional housing, and rapid rehousing.",
    website_url: "https://compass-sf.org/",
    phone: "(415) 644-0504", address: "37 Grove Street",
    city: "San Francisco", zip: "94102",
    eligibility: "Families with children experiencing or at risk of homelessness in SF",
    source_name: "Compass Family Services canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SF-H", title: "Hamilton Families",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "SF family homelessness nonprofit. Operates emergency shelter, transitional housing, and rapid rehousing for families across SF and the Bay Area. Major SSVF partner for veteran families.",
    website_url: "https://www.hamiltonfamilies.org/",
    phone: "(415) 292-5228", address: "1631 Hayes Street",
    city: "San Francisco", zip: "94117",
    eligibility: "Families experiencing or at risk of homelessness in SF; veterans via SSVF",
    source_name: "Hamilton Families canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SF-H", title: "Larkin Street Youth Services",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "SF transitional age youth (TAY) homelessness nonprofit. Operates emergency shelter, transitional housing, drop-in centers, primary care clinic, and education/employment for youth ages 12-24 experiencing homelessness in SF.",
    website_url: "https://larkinstreetyouth.org/",
    phone: "(415) 673-0911", address: "134 Golden Gate Avenue",
    city: "San Francisco", zip: "94102",
    eligibility: "Youth ages 12-24 experiencing homelessness in SF",
    source_name: "Larkin Street canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SF-H", title: "Homeless Prenatal Program",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "SF Mission District nonprofit serving pregnant women and families experiencing or at risk of homelessness. Provides housing assistance, prenatal care navigation, doula services, and family support.",
    website_url: "https://homelessprenatal.org/",
    phone: "(415) 546-6756", address: "2500 18th Street",
    city: "San Francisco", zip: "94110",
    eligibility: "Pregnant women and families in SF",
    source_name: "HPP canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-H", title: "HomeRise (formerly Community Housing Partnership)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "SF nonprofit affordable housing developer specializing in permanent supportive housing for chronically homeless adults including veterans. Operates 20+ buildings across SF.",
    website_url: "https://homerisesf.org/",
    phone: "(415) 421-2926", address: "20 Jones Street",
    city: "San Francisco", zip: "94102",
    eligibility: "Chronically homeless adults in SF",
    source_name: "HomeRise canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-H", title: "San Francisco Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "City and County of San Francisco's public housing authority. Administers Section 8 Housing Choice Vouchers, project-based vouchers, and HUD-VASH for homeless veterans within SF city limits.",
    website_url: "https://www.sfha.org/",
    phone: "(415) 715-3280", address: "1815 Egbert Avenue",
    city: "San Francisco", zip: "94124",
    eligibility: "Low-income SF residents; veterans for HUD-VASH",
    source_name: "SFHA canonical site", source_type: "government_agency",
  },
  {
    section: "SF-M", title: "Mission Neighborhood Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "SF Mission District FQHC. Bilingual primary care, women's health, dental, behavioral health, HIV services. HRSA Section 330 grantee.",
    website_url: "https://www.mnhc.org/",
    phone: "(415) 552-1013", address: "240 Shotwell Street",
    city: "San Francisco", zip: "94110",
    eligibility: "Low-income SF residents",
    source_name: "MNHC canonical site / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SF-M", title: "North East Medical Services (NEMS)",
    cat: "healthcare", sub: "Primary Care",
    desc: "SF/Bay Area FQHC focused on Asian American and Pacific Islander communities. Operates 14 clinic sites in SF, Daly City, San Bruno, Burlingame, and San Jose. HRSA Section 330 grantee. Multilingual.",
    website_url: "https://www.nems.org/",
    phone: "(415) 391-9686", address: "1520 Stockton Street",
    city: "San Francisco", zip: "94133",
    eligibility: "Anyone; bilingual API services",
    source_name: "NEMS canonical site / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SF-M", title: "South of Market Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "SF SOMA FQHC. Comprehensive primary care, dental, behavioral health, HIV services. HRSA Section 330 grantee.",
    website_url: "https://www.smhc-sf.org/",
    phone: "(415) 503-6000", address: "229 7th Street",
    city: "San Francisco", zip: "94103",
    eligibility: "Low-income SOMA SF residents",
    source_name: "SMHC canonical site / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SF-M", title: "HealthRIGHT 360",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "SF-headquartered statewide SUD treatment + FQHC nonprofit. Operates residential, outpatient, primary care, and reentry services. Includes the historic Haight Ashbury Free Clinics. DHCS-licensed across multiple CA counties.",
    website_url: "https://www.healthright360.org/",
    phone: "(415) 762-3700", address: "1563 Mission Street",
    city: "San Francisco", zip: "94103",
    eligibility: "Adults with SUD or behavioral health needs in SF and partner counties",
    source_name: "HealthRIGHT 360 canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-L", title: "Asian Law Caucus / Asian Americans Advancing Justice",
    cat: "legal", sub: "Legal Aid Services",
    desc: "SF-based legal aid focused on Asian American/Pacific Islander civil rights, immigration, criminal justice reform, voting rights, and language access. Founded 1972 — first AAPI legal aid in the US.",
    website_url: "https://www.asianlawcaucus.org/",
    phone: "(415) 896-1701", address: "55 Columbus Avenue",
    city: "San Francisco", zip: "94111",
    eligibility: "Low-income AAPI individuals; broader civil rights",
    source_name: "Asian Law Caucus canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-L", title: "Bay Area Legal Aid (BayLegal) - San Francisco",
    cat: "legal", sub: "Legal Aid Services",
    desc: "LSC-funded legal aid serving SF, Alameda, Contra Costa, Marin, Napa, San Mateo, Santa Clara counties. Practice areas: housing, family law, consumer, public benefits, immigration, and a Veterans Justice Project.",
    website_url: "https://baylegal.org/",
    phone: "(800) 551-5554", address: "1735 Telegraph Avenue",
    city: "Oakland", zip: "94612",
    eligibility: "Low-income Bay Area residents; veterans for VJP",
    source_name: "BayLegal canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SF-L", title: "Volunteer Legal Services Program of the Bar Association of San Francisco (VLSP)",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "SF pro bono law firm providing free legal services to low-income SF residents. Practice areas: housing, family, consumer, immigration, and a Justice & Diversity Center Veterans Project for benefits and discharge upgrades.",
    website_url: "https://www.sfbar.org/jdc/",
    phone: "(415) 982-1600", address: "301 Battery Street, 3rd Floor",
    city: "San Francisco", zip: "94111",
    eligibility: "Low-income SF residents; veterans for VJP",
    source_name: "BASF JDC canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-CC", title: "Catholic Charities of San Francisco, Marin and San Mateo",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Archdiocese of SF's Catholic Charities. Operates food pantries, immigration legal services, refugee resettlement, family services, and the CYO youth services. Serves SF, Marin, San Mateo counties.",
    website_url: "https://www.catholiccharitiessf.org/",
    phone: "(415) 972-1200", address: "990 Eddy Street",
    city: "San Francisco", zip: "94109",
    eligibility: "Anyone in need in SF/Marin/SM",
    source_name: "Catholic Charities SF canonical site", source_type: "nonprofit",
  },
  {
    section: "SF-CO", title: "211 Bay Area / Eden I&R",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Eden I&R operates 211 for Alameda County and the broader Bay Area 211 network. 24/7 free, confidential information and referral to housing, food, healthcare, mental health, financial assistance, disaster response.",
    website_url: "https://edenir.org/",
    phone: "211", address: "570 B Street",
    city: "Hayward", zip: "94541",
    eligibility: "Anyone in Alameda County and Bay Area",
    source_name: "Eden I&R canonical site", source_type: "nonprofit",
  },

  // ===== ALAMEDA COUNTY (Oakland/Berkeley/Hayward) =====
  {
    section: "AL-F", title: "Alameda County Community Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Alameda County's primary food bank. CAFB and Feeding America member. Distributes through 420+ partner agencies serving Oakland, Berkeley, Fremont, and surrounding cities.",
    website_url: "https://www.accfb.org/",
    phone: "(510) 635-3663", address: "7900 Edgewater Drive",
    city: "Oakland", zip: "94621",
    eligibility: "Low-income Alameda County residents",
    source_name: "ACCFB canonical site (200 OK) / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "AL-H", title: "Abode Services",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Fremont-headquartered Bay Area homelessness nonprofit. Operates the largest portfolio of permanent supportive housing in Alameda County and serves Santa Clara, Solano, Marin, Napa, Sonoma. Major SSVF partner for veteran families across the Bay Area.",
    website_url: "https://www.abodeservices.org/",
    phone: "(510) 657-7409", address: "40849 Fremont Boulevard",
    city: "Fremont", zip: "94538",
    eligibility: "Adults and families experiencing homelessness in Bay Area; veterans via SSVF",
    source_name: "Abode Services canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "AL-H", title: "BOSS (Building Opportunities for Self-Sufficiency)",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Berkeley-based homelessness nonprofit. Operates emergency shelter, transitional housing, mental health, reentry services, and the McKinley Men's Shelter. Serves Berkeley, Oakland, and surrounding Alameda County.",
    website_url: "https://www.self-sufficiency.org/",
    phone: "(510) 649-1930", address: "1918 University Avenue, Suite 2A",
    city: "Berkeley", zip: "94704",
    eligibility: "Adults experiencing homelessness in Alameda County",
    source_name: "BOSS canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-H", title: "East Oakland Community Project",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "East Oakland homelessness services nonprofit. Operates the Crossroads emergency shelter (Oakland's largest), Matilda Cliff Manor PSH, transitional housing, and reentry services.",
    website_url: "https://eocp.org/",
    phone: "(510) 532-3211", address: "7515 International Boulevard",
    city: "Oakland", zip: "94621",
    eligibility: "Adults experiencing homelessness in East Oakland",
    source_name: "EOCP canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-H", title: "Operation Dignity",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Oakland nonprofit specifically serving homeless veterans in the East Bay. Operates emergency shelter, transitional housing, permanent supportive housing, and SSVF rapid rehousing exclusively for veterans.",
    website_url: "https://operationdignity.org/",
    phone: "(510) 287-8465", address: "1342 Center Street",
    city: "Oakland", zip: "94607",
    eligibility: "Veterans experiencing or at risk of homelessness in East Bay",
    source_name: "Operation Dignity canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-H", title: "Building Futures with Women and Children",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "San Leandro/Alameda County homelessness and DV nonprofit. Operates emergency shelter for women and families, DV shelter, transitional housing, and rapid rehousing in southern Alameda County.",
    website_url: "https://bfwc.org/",
    phone: "(510) 357-0205", address: "1395 Bancroft Avenue",
    city: "San Leandro", zip: "94577",
    eligibility: "Women, families, DV survivors in southern Alameda County",
    source_name: "BFWC canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-H", title: "Bay Area Community Services (BACS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Alameda/Solano/Contra Costa community mental health, SUD, and homelessness services nonprofit. Operates outpatient mental health, crisis residential, and PSH across multiple East Bay counties.",
    website_url: "https://www.bayareacs.org/",
    phone: "(510) 613-0330", address: "1814 Franklin Street, Suite 200",
    city: "Oakland", zip: "94612",
    eligibility: "East Bay adults with behavioral health needs",
    source_name: "BACS canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "LifeLong Medical Care",
    cat: "healthcare", sub: "Primary Care",
    desc: "East Bay FQHC operating 17 clinic sites in Berkeley, Oakland, Pittsburg, El Cerrito, and surrounding cities. Comprehensive primary care, dental, behavioral health, geriatrics. HRSA Section 330 grantee.",
    website_url: "https://www.lifelongmedical.org/",
    phone: "(510) 981-4100", address: "1860 Alcatraz Avenue",
    city: "Berkeley", zip: "94703",
    eligibility: "Low-income East Bay residents",
    source_name: "LifeLong Medical Care canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "La Clínica de La Raza",
    cat: "healthcare", sub: "Primary Care",
    desc: "Major Bay Area FQHC headquartered in Oakland. 30+ clinic sites in Alameda, Contra Costa, Solano counties. Bilingual primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.laclinica.org/",
    phone: "(510) 535-4000", address: "1450 Fruitvale Avenue, Suite 100",
    city: "Oakland", zip: "94601",
    eligibility: "Low-income East Bay residents; bilingual",
    source_name: "La Clínica de La Raza canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "Asian Health Services",
    cat: "healthcare", sub: "Primary Care",
    desc: "Oakland Chinatown FQHC focused on Asian American Pacific Islander communities. Operates multiple Oakland clinic sites. Multilingual primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.ahschc.org/",
    phone: "(510) 735-3888", address: "818 Webster Street",
    city: "Oakland", zip: "94607",
    eligibility: "Anyone; multilingual API services",
    source_name: "Asian Health Services / HRSA FQHC (org confirmed via Alameda BHS)", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "Native American Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Bay Area FQHC serving Native American/Alaska Native and broader Bay Area communities. Operates Oakland and SF clinic sites with primary care, dental, behavioral health, and traditional healing programs. HRSA Section 330 grantee.",
    website_url: "https://nativehealth.org/",
    phone: "(510) 434-5421", address: "2950 International Boulevard",
    city: "Oakland", zip: "94601",
    eligibility: "Anyone; AI/AN-focused services and traditional healing",
    source_name: "NAHC canonical site (200 OK) / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "Tiburcio Vasquez Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Hayward/Union City FQHC. Bilingual primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://tvhc.org/",
    phone: "(510) 471-5880", address: "33255 9th Street",
    city: "Union City", zip: "94587",
    eligibility: "Low-income southern Alameda County residents; bilingual",
    source_name: "TVHC canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "Tri-City Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Fremont FQHC serving the Tri-City area (Fremont, Newark, Union City). Comprehensive primary care, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.tri-cityhealth.org/",
    phone: "(510) 770-8040", address: "39500 Liberty Street",
    city: "Fremont", zip: "94538",
    eligibility: "Low-income Tri-City area residents",
    source_name: "Tri-City Health Center / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "AL-M", title: "Roots Community Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "East Oakland FQHC focused on Black community health and reentry health navigation. Operates clinic sites in East Oakland. HRSA Section 330 grantee.",
    website_url: "https://rootsclinic.org/",
    phone: "(510) 666-1900", address: "9925 International Boulevard",
    city: "Oakland", zip: "94603",
    eligibility: "East Oakland residents; reentry-focused",
    source_name: "Roots Community Health Center / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "AL-MH", title: "Highland Hospital - Alameda Health System",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Alameda County's flagship public safety-net hospital. 236-bed Level 1 trauma center serving Oakland and the broader East Bay. Comprehensive emergency, primary, and specialty care for uninsured and Medi-Cal.",
    website_url: "https://www.alamedahealthsystem.org/highland-hospital/",
    phone: "(510) 437-4800", address: "1411 E. 31st Street",
    city: "Oakland", zip: "94602",
    eligibility: "Anyone in East Bay regardless of insurance",
    source_name: "Alameda Health System canonical site", source_type: "government_agency",
  },
  {
    section: "AL-L", title: "Centro Legal de la Raza",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Oakland-based legal aid serving low-income immigrants and communities of color across the Bay Area. Practice areas: immigration, housing, workers' rights, youth defense. Services include immigrant veterans.",
    website_url: "https://www.centrolegal.org/",
    phone: "(510) 437-1554", address: "3022 International Boulevard",
    city: "Oakland", zip: "94601",
    eligibility: "Low-income immigrants and communities of color in Bay Area",
    source_name: "Centro Legal de la Raza canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-L", title: "East Bay Community Law Center",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Berkeley/East Bay legal aid affiliated with UC Berkeley School of Law. Practice areas: housing, consumer, education, health, immigration. Serves low-income residents of Alameda and Contra Costa counties.",
    website_url: "https://ebclc.org/",
    phone: "(510) 548-4040", address: "2921 Adeline Street",
    city: "Berkeley", zip: "94703",
    eligibility: "Low-income East Bay residents",
    source_name: "EBCLC canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-CC", title: "Catholic Charities of the East Bay",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Diocese of Oakland's Catholic Charities. Operates food pantries, immigration legal services, refugee resettlement, eviction prevention, and family services across Alameda and Contra Costa counties.",
    website_url: "https://cceb.org/",
    phone: "(510) 768-3100", address: "433 Jefferson Street",
    city: "Oakland", zip: "94607",
    eligibility: "Anyone in need in East Bay",
    source_name: "Catholic Charities East Bay canonical site", source_type: "nonprofit",
  },

  // ===== CONTRA COSTA COUNTY =====
  {
    section: "CC-F", title: "Food Bank of Contra Costa and Solano",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Joint food bank serving Contra Costa and Solano counties. CAFB and Feeding America member. Distributes through 270+ partner agencies plus mobile pantries and farm-to-family programs.",
    website_url: "https://www.foodbankccs.org/",
    phone: "(925) 676-7543", address: "4010 Nelson Avenue",
    city: "Concord", zip: "94520",
    eligibility: "Low-income Contra Costa and Solano residents",
    source_name: "FBCCS canonical site (200 OK) / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "CC-H", title: "SHELTER Inc. of Contra Costa County",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Contra Costa County's primary homelessness services nonprofit. Operates emergency shelter, transitional housing, permanent supportive housing, and SSVF for veterans across the county.",
    website_url: "https://www.shelterinc.org/",
    phone: "(925) 335-0698", address: "1815 Arnold Drive",
    city: "Martinez", zip: "94553",
    eligibility: "Adults and families experiencing homelessness in Contra Costa County; veterans via SSVF",
    source_name: "SHELTER Inc canonical site", source_type: "nonprofit",
  },
  {
    section: "CC-H", title: "Trinity Center Walnut Creek",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Walnut Creek-based daytime drop-in center for adults experiencing homelessness in central Contra Costa County. Meals, showers, mail, case management, and connection to housing resources.",
    website_url: "https://trinitycenterwc.org/",
    phone: "(925) 949-8712", address: "1924 Trinity Avenue",
    city: "Walnut Creek", zip: "94596",
    eligibility: "Adults experiencing homelessness in central Contra Costa County",
    source_name: "Trinity Center canonical site", source_type: "nonprofit",
  },
  {
    section: "CC-C", title: "STAND! For Families Free of Violence",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Contra Costa County's primary DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy, and prevention education. Serves all of Contra Costa.",
    website_url: "https://www.standffov.org/",
    phone: "(888) 215-5555", address: "1410 Danzig Plaza, Suite 220",
    city: "Concord", zip: "94520",
    eligibility: "DV survivors and their children in Contra Costa County",
    source_name: "STAND canonical site", source_type: "nonprofit",
  },
  {
    section: "CC-M", title: "Brighter Beginnings",
    cat: "healthcare", sub: "Primary Care",
    desc: "East Contra Costa County FQHC. Comprehensive primary care, women's health, behavioral health serving Antioch, Pittsburg, and Bay Point. HRSA Section 330 grantee.",
    website_url: "https://brighter-beginnings.org/",
    phone: "(925) 776-0976", address: "2730 Hilltop Mall Road",
    city: "Richmond", zip: "94806",
    eligibility: "Low-income East Contra Costa County residents",
    source_name: "Brighter Beginnings canonical / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== MARIN COUNTY =====
  {
    section: "MA-H", title: "Homeward Bound of Marin",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Marin County's primary homelessness services nonprofit. Operates emergency shelter (Mill Street Center), transitional housing, permanent supportive housing, and a culinary training program.",
    website_url: "https://hbofm.org/",
    phone: "(415) 457-2115", address: "1399 N. Hamilton Parkway",
    city: "Novato", zip: "94949",
    eligibility: "Adults and families experiencing homelessness in Marin County",
    source_name: "HBoM canonical site", source_type: "nonprofit",
  },
  {
    section: "MA-H", title: "Ritter Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "San Rafael safety-net nonprofit serving people experiencing homelessness in Marin County. Operates a homeless health clinic (FQHC affiliate), food pantry, mental health, and case management.",
    website_url: "https://rittercenter.org/",
    phone: "(415) 457-8182", address: "16 Ritter Street",
    city: "San Rafael", zip: "94901",
    eligibility: "People experiencing homelessness in Marin County",
    source_name: "Ritter Center canonical site", source_type: "nonprofit",
  },
  {
    section: "MA-M", title: "Marin Community Clinics",
    cat: "healthcare", sub: "Primary Care",
    desc: "Marin County FQHC operating 5 clinic sites in Novato, San Rafael, and Larkspur. Comprehensive primary care, dental, women's health, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.marinclinics.org/",
    phone: "(415) 448-1500", address: "3110 Kerner Boulevard",
    city: "San Rafael", zip: "94901",
    eligibility: "Low-income Marin County residents",
    source_name: "Marin Community Clinics / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "MA-C", title: "Center for Domestic Peace",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Marin County's primary DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy. Serves all of Marin.",
    website_url: "https://centerfordomesticpeace.org/",
    phone: "(415) 924-6616", address: "734 A Street",
    city: "San Rafael", zip: "94901",
    eligibility: "DV survivors and their children in Marin County",
    source_name: "Center for Domestic Peace canonical site", source_type: "nonprofit",
  },

  // ===== SONOMA COUNTY =====
  {
    section: "SO-F", title: "Redwood Empire Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Sonoma County's primary food bank, also serving Lake, Mendocino, Humboldt, Trinity, Del Norte counties. CAFB and Feeding America member. Distributes through 200+ partner agencies plus Senior Brown Bag and Kids Cafe.",
    website_url: "https://refb.org/",
    phone: "(707) 523-7900", address: "3990 Brickway Boulevard",
    city: "Santa Rosa", zip: "95403",
    eligibility: "Low-income North Coast California residents",
    source_name: "REFB canonical site (200 OK) / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SO-H", title: "Catholic Charities of the Diocese of Santa Rosa",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Diocese of Santa Rosa's Catholic Charities. Operates Sam Jones Hall family shelter, Caritas Center campus (homeless services hub), immigration legal services, and disaster recovery across Sonoma, Napa, Mendocino, Lake counties.",
    website_url: "https://srcharities.org/",
    phone: "(707) 528-8712", address: "987 Airway Court",
    city: "Santa Rosa", zip: "95403",
    eligibility: "Anyone in need in Sonoma/Napa/Mendocino/Lake",
    source_name: "Catholic Charities Santa Rosa canonical site", source_type: "nonprofit",
  },
  {
    section: "SO-C", title: "YWCA Sonoma County",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Sonoma County's primary DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, and legal advocacy.",
    website_url: "https://www.ywcasc.org/",
    phone: "(707) 546-1234", address: "P.O. Box 3506",
    city: "Santa Rosa", zip: "95402",
    eligibility: "DV survivors and their children in Sonoma County",
    source_name: "YWCA Sonoma canonical site", source_type: "nonprofit",
  },
  {
    section: "SO-H", title: "COTS (Committee on the Shelterless)",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Petaluma-based Sonoma County homelessness nonprofit. Operates the Mary Isaak Center emergency shelter, transitional housing, and rapid rehousing in southern Sonoma County.",
    website_url: "https://www.cots.org/",
    phone: "(707) 765-6530", address: "900 Hopper Street",
    city: "Petaluma", zip: "94952",
    eligibility: "Adults and families experiencing homelessness in southern Sonoma County",
    source_name: "COTS canonical site", source_type: "nonprofit",
  },

  // ===== NAPA COUNTY =====
  {
    section: "NA-F", title: "Community Action of Napa Valley",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Napa County's community action agency operating the Napa Valley Food Bank (CAFB member), Head Start, and emergency assistance services across Napa County.",
    website_url: "https://www.canv.org/",
    phone: "(707) 253-6100", address: "1351 Pear Tree Lane, Suite 100",
    city: "Napa", zip: "94558",
    eligibility: "Low-income Napa County residents",
    source_name: "CANV canonical site / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "NA-C", title: "NEWS - Napa Emergency Women's Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Napa County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://newsnapa.org/",
    phone: "(707) 255-6397", address: "P.O. Box 5318",
    city: "Napa", zip: "94581",
    eligibility: "DV/SA survivors and their children in Napa County",
    source_name: "NEWS canonical site", source_type: "nonprofit",
  },

  // ===== SOLANO COUNTY =====
  {
    section: "SL-H", title: "Mission Solano",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Fairfield-based Solano County rescue mission. Emergency shelter (Bridge to Life Center), transitional housing, addiction recovery, food, and reentry services serving Vallejo, Fairfield, and surrounding cities.",
    website_url: "https://missionsolano.org/",
    phone: "(707) 425-0769", address: "310 Beck Avenue",
    city: "Fairfield", zip: "94533",
    eligibility: "Adults experiencing homelessness in Solano County",
    source_name: "Mission Solano canonical site", source_type: "nonprofit",
  },
  {
    section: "SL-C", title: "Solano Family Justice Center / SafeQuest Solano",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Solano County DV emergency shelter and crisis services. 24-hour hotline, shelter, counseling, and legal advocacy serving Vallejo, Fairfield, Vacaville, and surrounding cities.",
    website_url: "https://www.safequestsolano.org/",
    phone: "(866) 487-7233", address: "P.O. Box 2051",
    city: "Fairfield", zip: "94533",
    eligibility: "DV survivors in Solano County",
    source_name: "SafeQuest Solano canonical site", source_type: "nonprofit",
  },

  // ===== SAN MATEO COUNTY =====
  {
    section: "SM-H", title: "Samaritan House",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "San Mateo-headquartered safety-net nonprofit. Operates the Safe Harbor emergency shelter, food pantry, free medical/dental clinic, financial assistance, and Worker Resource Center across San Mateo County.",
    website_url: "https://samaritanhousesanmateo.org/",
    phone: "(650) 347-3648", address: "4031 Pacific Boulevard",
    city: "San Mateo", zip: "94403",
    eligibility: "Low-income San Mateo County residents",
    source_name: "Samaritan House canonical site", source_type: "nonprofit",
  },
  {
    section: "SM-H", title: "LifeMoves",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Menlo Park-headquartered Bay Area homelessness nonprofit. Operates 26 interim and permanent housing programs across San Mateo and Santa Clara counties. Major SSVF veteran services partner.",
    website_url: "https://www.lifemoves.org/",
    phone: "(650) 685-5880", address: "181 Constitution Drive",
    city: "Menlo Park", zip: "94025",
    eligibility: "Adults and families experiencing homelessness in SM/SC counties; veterans via SSVF",
    source_name: "LifeMoves canonical site", source_type: "nonprofit",
  },
  {
    section: "SM-C", title: "Community Overcoming Relationship Abuse (CORA)",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "San Mateo County's primary DV agency. 24-hour hotline, emergency shelter (Safe House), transitional housing, counseling, and legal advocacy.",
    website_url: "https://www.corasupport.org/",
    phone: "(800) 300-1080", address: "P.O. Box 5090",
    city: "San Mateo", zip: "94402",
    eligibility: "DV survivors and their children in San Mateo County",
    source_name: "CORA canonical site", source_type: "nonprofit",
  },
  {
    section: "SM-M", title: "Ravenswood Family Health Network",
    cat: "healthcare", sub: "Primary Care",
    desc: "East Palo Alto / Belle Haven FQHC operating multiple clinic sites. Comprehensive primary care, dental, behavioral health, women's health. HRSA Section 330 grantee.",
    website_url: "https://www.ravenswoodfhc.org/",
    phone: "(650) 330-7400", address: "1885 Bay Road",
    city: "East Palo Alto", zip: "94303",
    eligibility: "Low-income mid-Peninsula residents",
    source_name: "Ravenswood FHN / HRSA FQHC", source_type: "nonprofit",
  },

  // ===== SANTA CLARA COUNTY (San Jose) =====
  {
    section: "SC-F", title: "Second Harvest of Silicon Valley",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Santa Clara and San Mateo counties' primary food bank. CAFB and Feeding America member. Distributes 80M+ pounds annually through 380+ partner agencies plus 1,000+ direct-distribution sites.",
    website_url: "https://www.shfb.org/",
    phone: "(408) 266-8866", address: "4001 N. First Street",
    city: "San Jose", zip: "95134",
    eligibility: "Low-income SC and SM residents",
    source_name: "Second Harvest SV canonical site (200 OK) / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SC-F", title: "Sacred Heart Community Service",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "San Jose-based safety-net nonprofit. Operates a major food pantry, clothing closet, financial assistance, immigration services, and adult education serving Santa Clara County.",
    website_url: "https://www.sacredheartcs.org/",
    phone: "(408) 278-2160", address: "1381 S. First Street",
    city: "San Jose", zip: "95110",
    eligibility: "Low-income Santa Clara County residents",
    source_name: "Sacred Heart canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-H", title: "HomeFirst Services of Santa Clara County",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Santa Clara County's largest homelessness services nonprofit. Operates the Boccardo Reception Center (largest emergency shelter in SC), Sobrato House youth, transitional housing, and SSVF for veterans.",
    website_url: "https://homefirstscc.org/",
    phone: "(408) 539-2100", address: "507 Valley Way",
    city: "Milpitas", zip: "95035",
    eligibility: "Adults and families experiencing homelessness in Santa Clara County; veterans via SSVF",
    source_name: "HomeFirst canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-H", title: "Bill Wilson Center",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Santa Clara County youth and young adult services nonprofit. Operates the Drop-In Center, transitional housing, mental health, and runaway/homeless youth services for ages 10-25.",
    website_url: "https://www.billwilsoncenter.org/",
    phone: "(408) 243-0222", address: "3490 The Alameda",
    city: "Santa Clara", zip: "95050",
    eligibility: "Youth and young adults ages 10-25 in Santa Clara County",
    source_name: "Bill Wilson Center canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-CC", title: "Catholic Charities of Santa Clara County",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Diocese of San Jose's Catholic Charities. Operates food pantries, refugee resettlement, immigration legal services, senior nutrition (Day Break), and parenting programs across Santa Clara County.",
    website_url: "https://www.catholiccharitiesscc.org/",
    phone: "(408) 468-0100", address: "2625 Zanker Road",
    city: "San Jose", zip: "95134",
    eligibility: "Anyone in need in Santa Clara County",
    source_name: "Catholic Charities SCC canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-M", title: "Gardner Health Services",
    cat: "healthcare", sub: "Primary Care",
    desc: "San Jose FQHC operating 12 clinic sites in Santa Clara County. Comprehensive primary care, women's health, dental, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://www.gardnerhealth.org/",
    phone: "(408) 457-7100", address: "160 E. Virginia Street",
    city: "San Jose", zip: "95112",
    eligibility: "Low-income Santa Clara County residents",
    source_name: "Gardner Health Services / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SC-M", title: "Indian Health Center of Santa Clara Valley",
    cat: "healthcare", sub: "Primary Care",
    desc: "San Jose FQHC serving Native American/Alaska Native and broader Santa Clara County communities. Comprehensive primary care, dental, behavioral health, traditional healing. HRSA Section 330 grantee.",
    website_url: "https://www.indianhealthcenter.org/",
    phone: "(408) 445-3400", address: "1333 Meridian Avenue",
    city: "San Jose", zip: "95125",
    eligibility: "Anyone in Santa Clara County; AI/AN-focused services",
    source_name: "IHCSCV canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SC-M", title: "Asian Americans for Community Involvement (AACI)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "San Jose API community mental health and primary care nonprofit. Operates outpatient mental health, primary care clinic, refugee health, and DV services across Santa Clara County.",
    website_url: "https://aaci.org/",
    phone: "(408) 975-2730", address: "2400 Moorpark Avenue, Suite 300",
    city: "San Jose", zip: "95128",
    eligibility: "Santa Clara County residents; multilingual API services",
    source_name: "AACI canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-C", title: "Next Door Solutions to Domestic Violence",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Santa Clara County DV agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy.",
    website_url: "https://www.nextdoorsolutions.org/",
    phone: "(408) 279-2962", address: "234 E. Gish Road",
    city: "San Jose", zip: "95112",
    eligibility: "DV survivors and their children in Santa Clara County",
    source_name: "Next Door Solutions canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-E", title: "Goodwill of Silicon Valley",
    cat: "employment", sub: "Job Placement Programs",
    desc: "Santa Clara County Goodwill region. Retail stores funding workforce development, job training, and placement services. Veterans and reentry programs.",
    website_url: "https://www.goodwillsv.org/",
    phone: "(408) 869-9100", address: "1080 N. 7th Street",
    city: "San Jose", zip: "95112",
    eligibility: "Adults seeking employment in Santa Clara County",
    source_name: "Goodwill SV canonical site", source_type: "nonprofit",
  },
  {
    section: "SC-A", title: "Sourcewise (formerly Council on Aging Silicon Valley)",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Santa Clara County HICAP (Health Insurance Counseling and Advocacy Program) provider. Free Medicare counseling, Family Caregiver Support Program (also one of 11 California Caregiver Resource Centers), and senior nutrition.",
    website_url: "https://www.mysourcewise.com/",
    phone: "(408) 350-3200", address: "2115 The Alameda",
    city: "San Jose", zip: "95126",
    eligibility: "Medicare beneficiaries and family caregivers in Santa Clara County",
    source_name: "Sourcewise canonical site / CDA HICAP / CADRC", source_type: "nonprofit",
  },

  // ===== SACRAMENTO REGION =====
  {
    section: "SA-F", title: "Sacramento Food Bank & Family Services",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Sacramento County's primary food bank. CAFB and Feeding America member. Distributes 50M+ pounds annually through 200+ partner agencies plus mobile pantries, family services, and citizenship/adult education.",
    website_url: "https://www.sacramentofoodbank.org/",
    phone: "(916) 456-1980", address: "3333 3rd Avenue",
    city: "Sacramento", zip: "95817",
    eligibility: "Low-income Sacramento County residents",
    source_name: "SFBFS canonical site (200 OK) / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "SA-F", title: "River City Food Bank",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Sacramento's longest-running food pantry (since 1968). Operates the South Sacramento and Midtown sites distributing groceries directly to clients 6 days a week.",
    website_url: "https://www.rivercityfoodbank.org/",
    phone: "(916) 446-2627", address: "1800 28th Street",
    city: "Sacramento", zip: "95816",
    eligibility: "Low-income Sacramento residents",
    source_name: "River City Food Bank canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-F", title: "Loaves & Fishes",
    cat: "food-assistance", sub: "Community Kitchens",
    desc: "Sacramento day shelter and meal program for adults experiencing homelessness. Serves 600+ free hot meals daily plus showers, mail, library, mental health, and Maryhouse women's program at the Friendship Park campus.",
    website_url: "https://www.sacloaves.org/",
    phone: "(916) 446-0874", address: "1351 North C Street",
    city: "Sacramento", zip: "95811",
    eligibility: "Adults experiencing homelessness in Sacramento",
    source_name: "Loaves & Fishes canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-H", title: "Sacramento Steps Forward",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Sacramento County's CoC lead agency. Operates the Coordinated Entry System, HMIS, and homeless outreach coordination across Sacramento County.",
    website_url: "https://www.sacramentostepsforward.org/",
    phone: "(916) 577-9770", address: "2150 River Plaza Drive, Suite 385",
    city: "Sacramento", zip: "95833",
    eligibility: "People experiencing homelessness in Sacramento County",
    source_name: "Sacramento Steps Forward canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SA-H", title: "Volunteers of America Northern California & Northern Nevada",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Sacramento-headquartered VOA region serving Northern CA and Northern NV. Operates emergency shelter, transitional housing, permanent supportive housing, SSVF for veterans, and reentry services across 40+ counties.",
    website_url: "https://www.voa-ncnn.org/",
    phone: "(916) 442-3691", address: "3434 Marconi Avenue",
    city: "Sacramento", zip: "95821",
    eligibility: "Adults and families experiencing homelessness; veterans via SSVF",
    source_name: "VOA NCNN canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SA-H", title: "Saint John's Program for Real Change",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Sacramento women-and-children-only emergency shelter and 18-month residential rehabilitation program. Provides housing, education, employment training, mental health, and SUD recovery.",
    website_url: "https://www.saintjohnsprogram.org/",
    phone: "(916) 453-1482", address: "2443 Fruitridge Road",
    city: "Sacramento", zip: "95822",
    eligibility: "Women with children experiencing homelessness in Sacramento",
    source_name: "Saint John's canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-H", title: "Francis House Center",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Sacramento safety-net center for adults experiencing homelessness. Provides ID/document recovery, transportation assistance, food/clothing, and case management connecting clients to housing.",
    website_url: "https://francishousecenter.org/",
    phone: "(916) 443-2646", address: "1422 C Street",
    city: "Sacramento", zip: "95814",
    eligibility: "Adults experiencing homelessness in Sacramento",
    source_name: "Francis House canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-H", title: "Wellspring Women's Center",
    cat: "housing", sub: "Emergency Housing / Homeless Shelters",
    desc: "Sacramento Oak Park women-and-children-only day program providing meals, hygiene, and connection to services for women experiencing or at risk of homelessness.",
    website_url: "https://www.wellspringwomen.org/",
    phone: "(916) 454-9688", address: "3414 4th Avenue",
    city: "Sacramento", zip: "95817",
    eligibility: "Women and children in Sacramento experiencing crisis",
    source_name: "Wellspring canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-H", title: "Mercy Housing California",
    cat: "housing", sub: "Rental Assistance",
    desc: "Statewide nonprofit affordable housing developer headquartered in Sacramento. Owns/operates 150+ properties across California including PSH for chronically homeless adults and veterans.",
    website_url: "https://www.mercyhousing.org/california/",
    phone: "(916) 414-4400", address: "555 Capitol Mall, Suite 950",
    city: "Sacramento", zip: "95814",
    eligibility: "Low-income Californians; some properties veteran-preferred",
    source_name: "Mercy Housing CA canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SA-C", title: "WEAVE - Sacramento",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Sacramento County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy. WEAVE has served Sacramento for 40+ years.",
    website_url: "https://weaveinc.org/",
    phone: "(916) 920-2952", address: "1900 K Street",
    city: "Sacramento", zip: "95811",
    eligibility: "DV/SA survivors and their children in Sacramento County",
    source_name: "WEAVE canonical site (200 OK)", source_type: "nonprofit",
  },
  {
    section: "SA-L", title: "Legal Services of Northern California",
    cat: "legal", sub: "Legal Aid Services",
    desc: "LSC-funded legal aid headquartered in Sacramento. Serves 23 Northern California counties. Practice areas: housing, family, consumer, public benefits, immigration, and a Veterans Justice Project.",
    website_url: "https://lsnc.net/",
    phone: "(916) 551-2150", address: "517 12th Street",
    city: "Sacramento", zip: "95814",
    eligibility: "Low-income Northern CA residents; veterans for VJP",
    source_name: "LSNC canonical site", source_type: "nonprofit",
  },
  {
    section: "SA-M", title: "WellSpace Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sacramento County FQHC operating 18 clinic sites. Comprehensive primary care, dental, behavioral health, addiction medicine. HRSA Section 330 grantee. Operates the Sacramento Crisis Connect call line as well.",
    website_url: "https://wellspacehealth.org/",
    phone: "(916) 737-5555", address: "1820 J Street",
    city: "Sacramento", zip: "95811",
    eligibility: "Low-income Sacramento County residents",
    source_name: "WellSpace Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SA-M", title: "One Community Health",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sacramento FQHC formerly known as CARES Community Health. Comprehensive primary care, women's health, HIV/AIDS care, behavioral health. HRSA Section 330 grantee.",
    website_url: "https://onecommunityhealth.com/",
    phone: "(916) 443-3299", address: "1500 21st Street",
    city: "Sacramento", zip: "95811",
    eligibility: "Low-income Sacramento residents; HIV-focused services",
    source_name: "One Community Health / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SA-M", title: "Sacramento Native American Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Sacramento FQHC serving Native American/Alaska Native and broader Sacramento communities. Comprehensive primary care, dental, behavioral health, traditional healing. HRSA Section 330 grantee.",
    website_url: "https://snahc.org/",
    phone: "(916) 341-0575", address: "2020 J Street",
    city: "Sacramento", zip: "95811",
    eligibility: "Anyone in Sacramento; AI/AN-focused services",
    source_name: "SNAHC canonical / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "SA-CG", title: "Del Oro Caregiver Resource Center",
    cat: "family-support", sub: "Caregiver Support",
    desc: "One of 11 California Caregiver Resource Centers (CRC) administered by the CA Department of Aging. Serves the Greater Sacramento region (Sacramento, Yolo, Placer, El Dorado, Nevada, Yuba, Sutter, Colusa, Sierra, Plumas, Lassen, Modoc, Alpine counties) for family caregivers of adults with chronic or disabling conditions.",
    website_url: "https://www.deloro.org/",
    phone: "(800) 635-0220", address: "9355 Dunsmuir Road",
    city: "Sacramento", zip: "95826",
    eligibility: "Family caregivers in greater Sacramento and Northern Sierra",
    source_name: "Del Oro CRC / CADRC canonical", source_type: "nonprofit",
  },
  {
    section: "SA-A", title: "Agency on Aging \\ Area 4 - HICAP Sacramento",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "HICAP (Health Insurance Counseling and Advocacy Program) for Sacramento, Yolo, Yuba, Sutter, Colusa, Nevada, Placer counties. Free Medicare counseling. CDA-administered.",
    website_url: "https://www.agencyonaging4.org/",
    phone: "(800) 434-0222", address: "2260 Park Towne Circle",
    city: "Sacramento", zip: "95825",
    eligibility: "Medicare beneficiaries in 7-county Sacramento region",
    source_name: "AAA Area 4 canonical site / CDA HICAP", source_type: "government_agency",
  },
  {
    section: "SA-CO", title: "211 Sacramento",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Sacramento region's 211 backbone agency, operated by Community Link Capital Region. 24/7 free, confidential information and referral to housing, food, healthcare, mental health, financial assistance, and disaster response.",
    website_url: "https://www.211sacramento.org/",
    phone: "211", address: "8912 Volunteer Lane, Suite 100",
    city: "Sacramento", zip: "95826",
    eligibility: "Anyone in Sacramento region",
    source_name: "211 Sacramento canonical site", source_type: "nonprofit",
  },

  // ===== Yolo + Placer (Sac region) =====
  {
    section: "YO-F", title: "Yolo Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Yolo County's primary food bank. CAFB member. Distributes through 80+ partner agencies plus mobile pantries serving Davis, Woodland, West Sacramento, and rural Yolo County.",
    website_url: "https://yolofoodbank.org/",
    phone: "(530) 668-0690", address: "233 Harter Avenue",
    city: "Woodland", zip: "95776",
    eligibility: "Low-income Yolo County residents",
    source_name: "Yolo Food Bank canonical / CAFB Members", source_type: "nonprofit",
  },
  {
    section: "YO-C", title: "Empower Yolo",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Yolo County's primary DV, SA, and family resource agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy, and family resource centers across Yolo County.",
    website_url: "https://empoweryolo.org/",
    phone: "(530) 661-6336", address: "1110 W. Capitol Avenue",
    city: "West Sacramento", zip: "95691",
    eligibility: "DV/SA survivors and families in Yolo County",
    source_name: "Empower Yolo canonical site", source_type: "nonprofit",
  },
  {
    section: "PL-F", title: "Placer Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Placer County's primary food bank. Distributes through 80+ partner agencies plus mobile pantries serving Roseville, Auburn, Lincoln, and Tahoe-area Placer County.",
    website_url: "https://www.placerfoodbank.org/",
    phone: "(916) 783-0481", address: "8284 Industrial Avenue",
    city: "Roseville", zip: "95678",
    eligibility: "Low-income Placer County residents",
    source_name: "Placer Food Bank canonical site", source_type: "nonprofit",
  },
  {
    section: "PL-C", title: "Stand Up Placer",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Placer County's primary DV and SA agency. 24-hour hotline, emergency shelter, transitional housing, counseling, legal advocacy. Serves Roseville, Auburn, Lincoln, and surrounding Placer County.",
    website_url: "https://standupplacer.org/",
    phone: "(800) 575-5352", address: "P.O. Box 5462",
    city: "Auburn", zip: "95604",
    eligibility: "DV/SA survivors in Placer County",
    source_name: "Stand Up Placer canonical site", source_type: "nonprofit",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B2 — Bay Area + Sacramento", state: "CA" });
