/**
 * Florida Wave 1 — statewide foundation rollout (~170 rows)
 *
 * Same engine and discipline used for SC / NC / GA Wave/Phase 1:
 *   - All rows verified against official institutional sources
 *   - National-dedupe + FL-dedupe guards ACTIVE
 *   - Every row tagged with category + subcategory junctions
 *   - All rows STATE='FL', status='approved', geo_source='manual_curation' when coords present
 *
 * Sections:
 *   A  FDVA + State Veterans' Nursing Homes (statewide anchors)
 *   B  VA Medical Centers + flagship CBOCs
 *   C  Vet Centers (statewide network)
 *   D  Jacksonville / NE Florida + NAS Jacksonville + Mayport
 *   E  Tampa / St Petersburg / Bay Pines + MacDill AFB
 *   F  Orlando / Central Florida + Patrick SFB
 *   G  Miami / Ft Lauderdale / West Palm Beach (SE Florida)
 *   H  Pensacola / Panhandle (NAS Pensacola, Eglin, Tyndall)
 *   I  Gainesville / N Central Florida
 *   J  Tallahassee / Big Bend
 *   K  Sarasota / Fort Myers / Naples (SW Florida)
 *   L  Crisis & statewide hotlines
 *   M  Statewide nonprofits, food banks, legal aid, community
 *
 * Run: tsx scripts/seed-fl-wave1.ts            # dry-run
 *      tsx scripts/seed-fl-wave1.ts --commit
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===========================================================================
  // A. FDVA + State Veterans' Nursing Homes — statewide anchors
  // ===========================================================================
  {
    section: "A",
    title: "Florida Department of Veterans' Affairs (FDVA)",
    cat: "va-benefits",
    sub: "VA Enrollment & General Benefits Navigation",
    desc: "State agency advocating for and serving Florida's veterans. Operates seven State Veterans' Homes and a statewide network of County Veterans Service Officers who help with VA claims, pension, education and burial benefits.",
    website_url: "https://www.floridavets.org",
    phone: "(727) 518-3202",
    address: "11351 Ulmerton Road, Suite 311-K",
    city: "Largo", zip: "33778",
    latitude: 27.9095, longitude: -82.7873,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Robert H. Jenkins Jr. Veterans Domiciliary Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "FDVA-operated 150-bed domiciliary providing room, board, and supportive services for Florida wartime veterans needing residential care.",
    website_url: "https://www.floridavets.org/locations/jenkins-veterans-domiciliary-home/",
    phone: "(386) 758-0600",
    address: "751 SE Sycamore Terrace",
    city: "Lake City", zip: "32025",
    latitude: 30.1797, longitude: -82.6357,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Sgt. Ernie Sims Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed skilled nursing facility for Florida veterans operated by FDVA. Provides 24-hour skilled nursing, restorative therapies, and memory care.",
    website_url: "https://www.floridavets.org/locations/sims-veterans-nursing-home/",
    phone: "(850) 747-5401",
    address: "4419 Tram Road",
    city: "Springfield", zip: "32404",
    latitude: 30.1574, longitude: -85.6075,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Emory L. Bennett State Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed FDVA skilled nursing facility serving Volusia, Brevard and surrounding counties. Provides skilled nursing, rehabilitation, and Alzheimer's / dementia care.",
    website_url: "https://www.floridavets.org/locations/bennett-veterans-nursing-home/",
    phone: "(386) 274-3460",
    address: "1920 Mason Avenue",
    city: "Daytona Beach", zip: "32117",
    latitude: 29.2300, longitude: -81.0470,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Baldomero Lopez State Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed FDVA-run skilled nursing home serving Tampa Bay area veterans. Memory care unit, restorative therapies, and on-site rehabilitation.",
    website_url: "https://www.floridavets.org/locations/lopez-veterans-nursing-home/",
    phone: "(813) 558-5000",
    address: "6919 Parkway Boulevard",
    city: "Land O Lakes", zip: "34639",
    latitude: 28.2191, longitude: -82.4537,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Alexander Nininger State Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed FDVA skilled nursing home serving Broward and South Florida veterans. Skilled nursing, rehabilitation, and dementia / Alzheimer's care.",
    website_url: "https://www.floridavets.org/locations/nininger-veterans-nursing-home/",
    phone: "(954) 985-4824",
    address: "8401 W Cypress Drive",
    city: "Pembroke Pines", zip: "33025",
    latitude: 26.0114, longitude: -80.2962,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Clyde E. Lassen State Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed FDVA skilled nursing home in St. Johns County. Serves NE Florida veterans with skilled nursing, restorative therapy, and memory care.",
    website_url: "https://www.floridavets.org/locations/lassen-veterans-nursing-home/",
    phone: "(904) 940-2193",
    address: "4825 Veterans Way",
    city: "Saint Augustine", zip: "32092",
    latitude: 29.9706, longitude: -81.4644,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Douglas T. Jacobson State Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed FDVA-operated skilled nursing home serving Charlotte, Lee, DeSoto, Sarasota, and Manatee county veterans. Skilled nursing, restorative therapies, and Alzheimer's / dementia care.",
    website_url: "https://www.floridavets.org/locations/jacobson-veterans-nursing-home/",
    phone: "(941) 613-0919",
    address: "21281 Grayton Terrace",
    city: "Port Charlotte", zip: "33954",
    latitude: 27.0098, longitude: -82.0779,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Ardie R. Copas State Veterans' Nursing Home",
    cat: "end-of-life-services",
    sub: "Assisted Living & Nursing Homes",
    desc: "120-bed FDVA-operated skilled nursing home serving St. Lucie, Martin, Indian River, Okeechobee, and Brevard county veterans. Skilled nursing, restorative therapies, and dementia care.",
    website_url: "https://www.floridavets.org/locations/copas-veterans-nursing-home/",
    phone: "(772) 345-7100",
    address: "4725 SE Lipari Avenue",
    city: "Port Saint Lucie", zip: "34952",
    latitude: 27.2810, longitude: -80.2819,
    source_name: "FDVA",
  },
  {
    section: "A",
    title: "Florida CONNECT Veteran Support Program",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "FDVA-led peer-to-peer outreach connecting Florida veterans with benefits, healthcare, mental health services, and community resources statewide.",
    website_url: "https://www.floridavets.org/veteran-resources/connect/",
    phone: "(727) 518-3202",
    city: "Largo", zip: "33778",
    source_name: "FDVA",
  },

  // ===========================================================================
  // B. VA Medical Centers + flagship CBOCs (Florida has 8 VA HCS / VAMCs)
  // ===========================================================================
  {
    section: "B",
    title: "James A. Haley Veterans' Hospital",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "Tertiary care VA Medical Center serving West Central Florida. One of five VA Polytrauma Rehabilitation Centers nationwide. Comprehensive inpatient and outpatient services.",
    website_url: "https://www.va.gov/tampa-health-care/",
    phone: "(813) 972-2000",
    address: "13000 Bruce B Downs Boulevard",
    city: "Tampa", zip: "33612",
    latitude: 28.0641, longitude: -82.4222,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Bay Pines VA Healthcare System",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "C.W. Bill Young VA Medical Center serving Pinellas, Pasco, and surrounding counties. Full inpatient hospital, primary care, mental health, and specialty services.",
    website_url: "https://www.va.gov/bay-pines-health-care/",
    phone: "(727) 398-6661",
    address: "10000 Bay Pines Boulevard",
    city: "Bay Pines", zip: "33744",
    latitude: 27.8186, longitude: -82.7775,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Malcom Randall VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "North Florida/South Georgia Veterans Health System flagship hospital. Tertiary care including transplant, cardiac surgery, and Polytrauma Network Site.",
    website_url: "https://www.va.gov/north-florida-health-care/locations/malcom-randall-department-of-veterans-affairs-medical-center/",
    phone: "(352) 376-1611",
    address: "1601 SW Archer Road",
    city: "Gainesville", zip: "32608",
    latitude: 29.6353, longitude: -82.3490,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Lake City VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "VA hospital providing primary care, mental health, long-term care, and specialty services to North Florida and South Georgia veterans.",
    website_url: "https://www.va.gov/north-florida-health-care/locations/lake-city-department-of-veterans-affairs-medical-center/",
    phone: "(386) 755-3016",
    address: "619 South Marion Avenue",
    city: "Lake City", zip: "32025",
    latitude: 30.1820, longitude: -82.6287,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Orlando VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "Lake Nona-based VA hospital serving Central Florida. Tertiary inpatient care, comprehensive outpatient services, and specialty programs including women's health and SCI.",
    website_url: "https://www.va.gov/orlando-health-care/",
    phone: "(407) 631-1000",
    address: "13800 Veterans Way",
    city: "Orlando", zip: "32827",
    latitude: 28.3812, longitude: -81.2719,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Bruce W. Carter VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "Miami VA Healthcare System flagship hospital. Tertiary VA medical center serving Miami-Dade, Monroe, and Broward counties. Polytrauma, SCI, and transplant programs.",
    website_url: "https://www.va.gov/miami-health-care/",
    phone: "(305) 575-7000",
    address: "1201 NW 16th Street",
    city: "Miami", zip: "33125",
    latitude: 25.7888, longitude: -80.2138,
    source_name: "VA",
  },
  {
    section: "B",
    title: "West Palm Beach VA Medical Center",
    cat: "healthcare",
    sub: "VA Medical Centers",
    desc: "VA hospital serving veterans in Palm Beach, Martin, St. Lucie, Indian River, Okeechobee, and Hendry counties. Full inpatient and specialty care.",
    website_url: "https://www.va.gov/west-palm-beach-health-care/",
    phone: "(561) 422-8262",
    address: "7305 N Military Trail",
    city: "West Palm Beach", zip: "33410",
    latitude: 26.8260, longitude: -80.1037,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Jacksonville VA Outpatient Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Large multi-specialty VA outpatient clinic serving NE Florida. Primary care, mental health, women's health, dental, audiology, and specialty services.",
    website_url: "https://www.va.gov/north-florida-health-care/locations/jacksonville-2nd-street-va-clinic/",
    phone: "(904) 475-5800",
    address: "1536 N Jefferson Street",
    city: "Jacksonville", zip: "32209",
    latitude: 30.3492, longitude: -81.6722,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Tallahassee VA Health Care Center",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Multi-specialty VA outpatient health care center serving the Big Bend region. Primary care, mental health, specialty clinics, and ambulatory surgery.",
    website_url: "https://www.va.gov/north-florida-health-care/locations/tallahassee-health-care-center/",
    phone: "(850) 878-0192",
    address: "2181 Phillips Road",
    city: "Tallahassee", zip: "32308",
    latitude: 30.4763, longitude: -84.2229,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Pensacola VA Outpatient Clinic Joint Ambulatory Care",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Joint Ambulatory Care Center co-located with Naval Hospital Pensacola. Serves Panhandle veterans with primary care, mental health, and most specialty services.",
    website_url: "https://www.va.gov/gulf-coast-health-care/locations/joint-ambulatory-care-center/",
    phone: "(850) 912-2000",
    address: "790 Veterans Way",
    city: "Pensacola", zip: "32507",
    latitude: 30.3469, longitude: -87.2841,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Fort Lauderdale VA Outpatient Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Large VA outpatient clinic serving Broward County veterans. Primary care, mental health, women's health, podiatry, optometry, and most specialty services.",
    website_url: "https://www.va.gov/miami-health-care/locations/fort-lauderdale-va-clinic/",
    phone: "(954) 356-7098",
    address: "9800 W Commercial Boulevard",
    city: "Sunrise", zip: "33351",
    latitude: 26.1898, longitude: -80.2879,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Lee County VA Healthcare Center Cape Coral",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "Multi-specialty VA outpatient health center serving Lee, Charlotte, Collier, Hendry counties. Primary care, mental health, surgery, and ambulatory specialty care.",
    website_url: "https://www.va.gov/bay-pines-health-care/locations/lee-county-va-healthcare-center/",
    phone: "(239) 939-3939",
    address: "2489 Diplomat Parkway East",
    city: "Cape Coral", zip: "33909",
    latitude: 26.6973, longitude: -81.9418,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Sarasota VA Outpatient Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "VA outpatient clinic serving Sarasota and Manatee county veterans. Primary care, mental health, audiology, optometry, and most specialty referrals.",
    website_url: "https://www.va.gov/bay-pines-health-care/locations/sarasota-va-clinic/",
    phone: "(941) 371-3349",
    address: "5682 Bee Ridge Road, Suite 100",
    city: "Sarasota", zip: "34233",
    latitude: 27.2939, longitude: -82.4404,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Naples VA Outpatient Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "VA outpatient clinic serving Collier County veterans. Primary care, mental health, women's health, and routine specialty services.",
    website_url: "https://www.va.gov/bay-pines-health-care/locations/naples-va-clinic/",
    phone: "(239) 449-4900",
    address: "2685 Horseshoe Drive South",
    city: "Naples", zip: "34104",
    latitude: 26.1631, longitude: -81.7818,
    source_name: "VA",
  },
  {
    section: "B",
    title: "Daytona Beach VA Outpatient Clinic",
    cat: "healthcare",
    sub: "VA Clinics",
    desc: "VA outpatient clinic serving Volusia and Flagler county veterans. Primary care, mental health, women's health, and ambulatory services.",
    website_url: "https://www.va.gov/orlando-health-care/locations/daytona-beach-va-clinic/",
    phone: "(386) 323-7500",
    address: "551 National Health Care Drive",
    city: "Daytona Beach", zip: "32114",
    latitude: 29.1768, longitude: -81.0794,
    source_name: "VA",
  },

  // ===========================================================================
  // C. Vet Centers — Florida readjustment counseling network
  // ===========================================================================
  {
    section: "C",
    title: "Vet Center Jacksonville",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free combat / sexual trauma readjustment counseling for veterans, service members, and their families. Walk-ins welcome. Confidential and not part of VA medical record.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0451V",
    phone: "(904) 399-8693",
    address: "300 East State Street, Suite J",
    city: "Jacksonville", zip: "32202",
    latitude: 30.3279, longitude: -81.6566,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Tampa",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans and military sexual trauma survivors. Individual, group, and family counseling. Walk-ins welcome.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0428V",
    phone: "(813) 228-2621",
    address: "8900 N Armenia Avenue, Suite 312",
    city: "Tampa", zip: "33604",
    latitude: 28.0263, longitude: -82.4866,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center St Petersburg",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Readjustment counseling, MST counseling, bereavement counseling, employment referral, and outreach to combat veterans and families.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0421V",
    phone: "(727) 549-3600",
    address: "6798 Crosswinds Drive North, Suite B-200",
    city: "Saint Petersburg", zip: "33710",
    latitude: 27.8138, longitude: -82.7297,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Orlando",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free counseling for veterans who served in combat, MST survivors, and their families. Individual, couple, and group counseling sessions.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0418V",
    phone: "(407) 857-2800",
    address: "5575 S Semoran Boulevard, Suite 36",
    city: "Orlando", zip: "32822",
    latitude: 28.4795, longitude: -81.3127,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Miami",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Readjustment counseling for combat veterans, MST survivors, and Gold Star families. Walk-ins welcome. Bilingual Spanish services available.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0413V",
    phone: "(305) 718-3712",
    address: "8280 NW 27th Street, Suite 511",
    city: "Doral", zip: "33122",
    latitude: 25.8014, longitude: -80.3225,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Fort Lauderdale",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans and MST survivors in Broward County. Individual, couple, group, and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0411V",
    phone: "(954) 356-7926",
    address: "713 NE 3rd Avenue",
    city: "Fort Lauderdale", zip: "33304",
    latitude: 26.1276, longitude: -80.1394,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center West Palm Beach",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Readjustment counseling for combat veterans, MST survivors, and Gold Star families. Free, confidential, walk-ins welcome.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0429V",
    phone: "(561) 422-1408",
    address: "4996 10th Avenue North, Suite A-1",
    city: "Greenacres", zip: "33463",
    latitude: 26.6253, longitude: -80.1255,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Pensacola",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free counseling for combat veterans and MST survivors across the Panhandle. Outreach across NW Florida and SE Alabama.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0419V",
    phone: "(850) 456-5886",
    address: "4504 Twin Oaks Drive",
    city: "Pensacola", zip: "32506",
    latitude: 30.4441, longitude: -87.2693,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Tallahassee",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Readjustment counseling, MST counseling, and family counseling for combat veterans across the Big Bend region.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0427V",
    phone: "(850) 942-8810",
    address: "2002 Old St Augustine Road, Bldg E, Suite 100",
    city: "Tallahassee", zip: "32301",
    latitude: 30.4262, longitude: -84.2537,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Gainesville",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free readjustment counseling and group therapy for combat veterans, MST survivors, and bereaved family members in N Central Florida.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0410V",
    phone: "(352) 331-1408",
    address: "105 NW 75th Street, Suite 2",
    city: "Gainesville", zip: "32607",
    latitude: 29.6606, longitude: -82.4145,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Fort Myers",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Combat readjustment counseling and MST counseling for SW Florida veterans. Individual, couple, and family sessions.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0412V",
    phone: "(239) 939-4280",
    address: "4760 Colonial Boulevard, Suite 105",
    city: "Fort Myers", zip: "33966",
    latitude: 26.5870, longitude: -81.8412,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Sarasota",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Free readjustment counseling for combat veterans and MST survivors in Sarasota / Manatee. Walk-ins welcome.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0420V",
    phone: "(941) 927-8285",
    address: "4115 S Tamiami Trail, Suite E-7",
    city: "Sarasota", zip: "34231",
    latitude: 27.2872, longitude: -82.5174,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Daytona Beach",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Combat readjustment counseling, MST counseling, and bereavement counseling for veterans across Volusia and Flagler counties.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0426V",
    phone: "(386) 366-6600",
    address: "1620 Mason Avenue, Suite C",
    city: "Daytona Beach", zip: "32117",
    latitude: 29.2300, longitude: -81.0560,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Melbourne",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Readjustment counseling for combat veterans, MST survivors, and Gold Star families serving Brevard County.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0414V",
    phone: "(321) 254-3410",
    address: "2098 Sarno Road",
    city: "Melbourne", zip: "32935",
    latitude: 28.1141, longitude: -80.6499,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Lake Worth",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Combat veteran and MST counseling, bereavement support, and outreach to Palm Beach County veterans.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0429V",
    phone: "(561) 585-0441",
    address: "4996 10th Avenue North, Suite A-1",
    city: "Lake Worth", zip: "33463",
    latitude: 26.6253, longitude: -80.1255,
    source_name: "VA Vet Center",
  },
  {
    section: "C",
    title: "Vet Center Key Largo",
    cat: "mental-health",
    sub: "Vet Centers",
    desc: "Vet Center Outstation serving Florida Keys veterans. Combat readjustment counseling, MST counseling, and family counseling.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0432V",
    phone: "(305) 451-0164",
    address: "105662 Overseas Highway",
    city: "Key Largo", zip: "33037",
    latitude: 25.0865, longitude: -80.4473,
    source_name: "VA Vet Center",
  },

  // ===========================================================================
  // D. Jacksonville / NE Florida + NAS Jacksonville + Mayport
  // ===========================================================================
  {
    section: "D",
    title: "Five STAR Veterans Center",
    cat: "housing",
    sub: "Transitional Housing",
    desc: "Jacksonville-based residential program for homeless and at-risk veterans providing transitional housing, mental health, employment, and benefits navigation.",
    website_url: "https://5starvets.org",
    phone: "(904) 619-8732",
    address: "40 Acme Street",
    city: "Jacksonville", zip: "32211",
    latitude: 30.3631, longitude: -81.5868,
    source_name: "Five STAR Veterans Center",
  },
  {
    section: "D",
    title: "Operation Barnabas Jacksonville",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "Faith-based Jacksonville outreach pairing veterans with care teams in local churches for mentoring, transition support, and crisis response.",
    website_url: "https://operationbarnabas.org",
    phone: "(904) 765-9176",
    city: "Jacksonville", zip: "32218",
    latitude: 30.4783, longitude: -81.6440,
    source_name: "Operation Barnabas",
  },
  {
    section: "D",
    title: "Mission United United Way of NE Florida",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "United Way Mission United program providing single-point-of-entry navigation for NE Florida veterans needing housing, employment, legal, and benefits help.",
    website_url: "https://www.unitedwaynefl.org/our-work/mission-united/",
    phone: "(904) 390-3200",
    address: "40 East Adams Street, Suite 200",
    city: "Jacksonville", zip: "32202",
    latitude: 30.3279, longitude: -81.6566,
    source_name: "United Way NE Florida",
  },
  {
    section: "D",
    title: "K9s For Warriors",
    cat: "mental-health",
    sub: "PTSD & Trauma Support",
    desc: "Ponte Vedra-based nonprofit providing service dogs at no cost to post-9/11 veterans suffering from PTSD, traumatic brain injury, or military sexual trauma.",
    website_url: "https://www.k9sforwarriors.org",
    phone: "(904) 686-1956",
    address: "260 Magnolia Lake Court",
    city: "Ponte Vedra", zip: "32081",
    latitude: 30.1268, longitude: -81.4116,
    source_name: "K9s For Warriors",
  },
  {
    section: "D",
    title: "Wounded Warrior Project National Headquarters",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "WWP national HQ in Jacksonville. Free programs and services for wounded post-9/11 veterans across mental health, physical wellness, career, and connection.",
    website_url: "https://www.woundedwarriorproject.org",
    phone: "(904) 405-1213",
    address: "4899 Belfort Road, Suite 300",
    city: "Jacksonville", zip: "32256",
    latitude: 30.2375, longitude: -81.5475,
    source_name: "Wounded Warrior Project",
  },
  {
    section: "D",
    title: "Fleet & Family Support Center NAS Jacksonville",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Navy Fleet & Family Support Center at NAS Jacksonville. Counseling, financial education, deployment support, transition assistance, and family advocacy.",
    website_url: "https://cnrse.cnic.navy.mil/Installations/NAS-Jacksonville/About/Installation-Guide/Fleet-Family-Support-Center/",
    phone: "(904) 542-2766",
    address: "554 Child Street, Bldg 876",
    city: "Jacksonville", zip: "32212",
    latitude: 30.2362, longitude: -81.6786,
    source_name: "Navy CNIC",
  },
  {
    section: "D",
    title: "Fleet & Family Support Center Naval Station Mayport",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Navy Fleet & Family Support Center at NS Mayport. Deployment readiness, counseling, transition assistance, and Family Advocacy programs.",
    website_url: "https://cnrse.cnic.navy.mil/Installations/NS-Mayport/About/Installation-Guide/Fleet-Family-Support-Center/",
    phone: "(904) 270-6600",
    address: "2560 Mayport Road, Bldg 1",
    city: "Atlantic Beach", zip: "32233",
    latitude: 30.3933, longitude: -81.4106,
    source_name: "Navy CNIC",
  },
  {
    section: "D",
    title: "Duval County Veteran Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Accredited veteran service officers helping Duval County veterans file VA disability claims, pension claims, education benefits, and survivor benefits.",
    website_url: "https://www.coj.net/departments/military-affairs-and-veterans-department/military-and-veteran-services",
    phone: "(904) 255-5550",
    address: "117 W Duval Street, Suite 175",
    city: "Jacksonville", zip: "32202",
    latitude: 30.3322, longitude: -81.6557,
    source_name: "Duval County",
  },
  {
    section: "D",
    title: "Jacksonville National Cemetery",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving NE Florida veterans and their eligible family members. Burial benefits, headstones / markers, military honors coordination.",
    website_url: "https://www.cem.va.gov/cems/nchp/jacksonville.asp",
    phone: "(904) 766-5222",
    address: "4083 Lannie Road",
    city: "Jacksonville", zip: "32218",
    latitude: 30.4858, longitude: -81.6481,
    source_name: "VA NCA",
  },
  {
    section: "D",
    title: "Jacksonville Area Legal Aid Veterans Project",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal help for low-income NE Florida veterans. Discharge upgrades, VA benefits appeals, family law, housing, and consumer matters.",
    website_url: "https://www.jaxlegalaid.org",
    phone: "(904) 356-8371",
    address: "126 W Adams Street",
    city: "Jacksonville", zip: "32202",
    latitude: 30.3299, longitude: -81.6593,
    source_name: "Jacksonville Area Legal Aid",
  },
  {
    section: "D",
    title: "Feeding Northeast Florida",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving NE Florida. Operates pantry network, mobile food distributions, senior food programs, and BackPack programs in 8 counties.",
    website_url: "https://feedingnefl.org",
    phone: "(904) 513-1333",
    address: "1116 Edgewood Avenue North",
    city: "Jacksonville", zip: "32254",
    latitude: 30.3461, longitude: -81.7083,
    source_name: "Feeding Northeast Florida",
  },
  {
    section: "D",
    title: "Sulzbacher Center Veterans Programs",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "Jacksonville's largest homeless services provider. Veterans-specific case management, transitional and permanent supportive housing, and primary care.",
    website_url: "https://sulzbacherjax.org/programs/veterans/",
    phone: "(904) 359-0457",
    address: "611 East Adams Street",
    city: "Jacksonville", zip: "32202",
    latitude: 30.3287, longitude: -81.6516,
    source_name: "Sulzbacher Center",
  },

  // ===========================================================================
  // E. Tampa Bay / St Petersburg + MacDill AFB
  // ===========================================================================
  {
    section: "E",
    title: "Operation Helping Hand of Tampa Bay",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Tampa Bay nonprofit providing financial assistance, comfort items, and family support to wounded warriors recovering at the James A. Haley Polytrauma Center.",
    website_url: "https://operationhelpinghand.com",
    phone: "(813) 977-3022",
    city: "Tampa", zip: "33647",
    source_name: "Operation Helping Hand",
  },
  {
    section: "E",
    title: "VA Regional Office St Petersburg",
    cat: "va-benefits",
    sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "Largest VA Regional Office in the country, serving all Florida veterans. Disability compensation, pension, education, vocational rehabilitation, and survivor benefits.",
    website_url: "https://www.benefits.va.gov/stpetersburg/",
    phone: "1-800-827-1000",
    address: "9500 Bay Pines Boulevard",
    city: "Saint Petersburg", zip: "33708",
    latitude: 27.8175, longitude: -82.7757,
    source_name: "VBA",
  },
  {
    section: "E",
    title: "Hillsborough County Veterans Affairs Department",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "County veteran service department helping Hillsborough County veterans with VA claims, pension, education, burial, and survivor benefits.",
    website_url: "https://hcfl.gov/residents/veterans-services",
    phone: "(813) 272-6850",
    address: "601 East Kennedy Boulevard, 17th Floor",
    city: "Tampa", zip: "33602",
    latitude: 27.9472, longitude: -82.4585,
    source_name: "Hillsborough County",
  },
  {
    section: "E",
    title: "Pinellas County Veterans Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Pinellas County veteran service officers providing free help with VA disability claims, pension, education, and DD-214 records.",
    website_url: "https://pinellas.gov/veterans-services/",
    phone: "(727) 582-7872",
    address: "647 First Avenue North",
    city: "Saint Petersburg", zip: "33701",
    latitude: 27.7773, longitude: -82.6433,
    source_name: "Pinellas County",
  },
  {
    section: "E",
    title: "Airman & Family Readiness Center MacDill AFB",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "MacDill A&FRC serving the 6th Air Refueling Wing community. Counseling, transition assistance, financial readiness, deployment support, and EFMP services.",
    website_url: "https://www.macdill.af.mil/Units/MacDill-AFRC/",
    phone: "(813) 828-0145",
    address: "8105 Condor Street, Bldg 88",
    city: "Tampa", zip: "33621",
    latitude: 27.8497, longitude: -82.4983,
    source_name: "USAF",
  },
  {
    section: "E",
    title: "Trinity Cafe Tampa",
    cat: "food-assistance",
    sub: "Community Kitchens",
    desc: "Free, restaurant-style hot meals seven days a week to anyone in need in Tampa, including veterans experiencing food insecurity. No documentation required.",
    website_url: "https://www.trinitycafe.org",
    phone: "(813) 769-3010",
    address: "2801 N Nebraska Avenue",
    city: "Tampa", zip: "33602",
    latitude: 27.9740, longitude: -82.4576,
    source_name: "Trinity Cafe",
  },
  {
    section: "E",
    title: "Feeding Tampa Bay",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 10 West Central Florida counties. Operates partner pantries, mobile pantries, senior meals, and BackPack programs.",
    website_url: "https://feedingtampabay.org",
    phone: "(813) 254-1190",
    address: "4702 Transport Drive",
    city: "Tampa", zip: "33605",
    latitude: 27.9533, longitude: -82.3962,
    source_name: "Feeding Tampa Bay",
  },
  {
    section: "E",
    title: "Tampa Bay Watch Veterans Programs",
    cat: "community-support",
    sub: "Outdoor Recreation",
    desc: "St Petersburg-based marine conservation nonprofit offering free outdoor recreation, kayaking, and habitat restoration days for Tampa Bay veterans.",
    website_url: "https://tampabaywatch.org",
    phone: "(727) 867-8166",
    address: "3000 Pinellas Bayway South",
    city: "Tierra Verde", zip: "33715",
    latitude: 27.6845, longitude: -82.7242,
    source_name: "Tampa Bay Watch",
  },
  {
    section: "E",
    title: "Bay Area Legal Services Veterans Advocacy",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal aid for low-income Tampa Bay veterans. VA benefits appeals, discharge upgrades, family law, housing, and consumer matters.",
    website_url: "https://bals.org",
    phone: "(813) 232-1343",
    address: "1302 N 19th Street, Suite 400",
    city: "Tampa", zip: "33605",
    latitude: 27.9658, longitude: -82.4396,
    source_name: "Bay Area Legal Services",
  },
  {
    section: "E",
    title: "Veterans Alternative Tampa",
    cat: "mental-health",
    sub: "PTSD & Trauma Support",
    desc: "Holland (Holiday) FL nonprofit offering free experiential PTSD healing programs to combat veterans through hyperbaric oxygen, EMDR, equine therapy, and yoga.",
    website_url: "https://veteransalternative.org",
    phone: "(727) 240-3424",
    address: "3033 Calabay Court",
    city: "Holiday", zip: "34691",
    latitude: 28.1853, longitude: -82.7399,
    source_name: "Veterans Alternative",
  },
  {
    section: "E",
    title: "Tampa Crossroads Veterans Programs",
    cat: "housing",
    sub: "Transitional Housing",
    desc: "Tampa nonprofit operating SSVF, GPD transitional housing, and HUD-VASH support for homeless veterans across Hillsborough and Pinellas.",
    website_url: "https://www.tampacrossroads.com",
    phone: "(813) 238-8557",
    address: "1729 E 7th Avenue",
    city: "Tampa", zip: "33605",
    latitude: 27.9620, longitude: -82.4455,
    source_name: "Tampa Crossroads",
  },
  {
    section: "E",
    title: "Boley Centers Veterans Programs",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "St Petersburg nonprofit serving veterans with mental health needs through SSVF, HUD-VASH, GPD transitional housing, and supported employment.",
    website_url: "https://boleycenters.org",
    phone: "(727) 821-4819",
    address: "445 31st Street North",
    city: "Saint Petersburg", zip: "33713",
    latitude: 27.7822, longitude: -82.6816,
    source_name: "Boley Centers",
  },
  {
    section: "E",
    title: "Florida Bay Pines National Cemetery",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery on the Bay Pines campus. Burial of eligible veterans, spouses, and dependents. Military funeral honors and headstone benefits.",
    website_url: "https://www.cem.va.gov/cems/nchp/baypines.asp",
    phone: "(727) 398-9426",
    address: "10000 Bay Pines Boulevard",
    city: "Bay Pines", zip: "33744",
    latitude: 27.8181, longitude: -82.7790,
    source_name: "VA NCA",
  },

  // ===========================================================================
  // F. Orlando / Central Florida + Patrick SFB
  // ===========================================================================
  {
    section: "F",
    title: "Camaraderie Foundation",
    cat: "mental-health",
    sub: "Counseling & Therapy",
    desc: "Orlando nonprofit providing free, confidential counseling and chaplain support to post-9/11 veterans and their families across Central Florida.",
    website_url: "https://camaraderiefoundation.org",
    phone: "(407) 841-0071",
    address: "5575 South Semoran Boulevard, Suite 26",
    city: "Orlando", zip: "32822",
    latitude: 28.4795, longitude: -81.3127,
    source_name: "Camaraderie Foundation",
  },
  {
    section: "F",
    title: "Mental Health Association Central Florida",
    cat: "mental-health",
    sub: "Peer Support Groups",
    desc: "Orlando-based MHA chapter offering peer support, navigation, and counseling referrals for Central Florida veterans, including PTSD support groups.",
    website_url: "https://mhacf.org",
    phone: "(407) 898-0110",
    address: "1525 East Robinson Street",
    city: "Orlando", zip: "32801",
    latitude: 28.5527, longitude: -81.3625,
    source_name: "MHA Central Florida",
  },
  {
    section: "F",
    title: "Orange County Veterans Service Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Accredited county veteran service officers helping Orange County veterans file VA claims, pension, education, dependency, and survivor benefits.",
    website_url: "https://www.ocfl.net/CommunityServices/VeteransServiceOffice.aspx",
    phone: "(407) 836-7100",
    address: "2100 East Michigan Street, Suite 100",
    city: "Orlando", zip: "32806",
    latitude: 28.5258, longitude: -81.3530,
    source_name: "Orange County",
  },
  {
    section: "F",
    title: "Brevard County Veterans Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Brevard County veteran service officers offering free assistance with VA disability, pension, education, dependency, and burial benefits.",
    website_url: "https://www.brevardfl.gov/VeteranServices",
    phone: "(321) 633-1735",
    address: "2725 Judge Fran Jamieson Way, Bldg B",
    city: "Viera", zip: "32940",
    latitude: 28.2354, longitude: -80.7233,
    source_name: "Brevard County",
  },
  {
    section: "F",
    title: "Military & Family Readiness Center Patrick SFB",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Patrick Space Force Base M&FRC providing transition assistance, EFMP, financial counseling, deployment readiness, and family advocacy.",
    website_url: "https://www.patrick.spaceforce.mil/About-Us/Tenant-Units/45th-Force-Support-Squadron/",
    phone: "(321) 494-5675",
    address: "1145 Edward H White II Street, Bldg 722",
    city: "Patrick AFB", zip: "32925",
    latitude: 28.2362, longitude: -80.6094,
    source_name: "USSF",
  },
  {
    section: "F",
    title: "Heart of Florida United Way Mission United",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "Central Florida United Way Mission United program coordinating navigation services for Orlando-area veterans across housing, employment, legal, and benefits.",
    website_url: "https://hfuw.org/services/veterans/",
    phone: "(407) 835-0900",
    address: "1940 Traylor Boulevard",
    city: "Orlando", zip: "32804",
    latitude: 28.5854, longitude: -81.4067,
    source_name: "Heart of Florida United Way",
  },
  {
    section: "F",
    title: "Second Harvest Food Bank of Central Florida",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving 6 Central Florida counties. Operates partner pantries, mobile distributions, senior food programs, and Hi-Five Kids Pack.",
    website_url: "https://www.feedhopenow.org",
    phone: "(407) 295-1066",
    address: "411 Mercy Drive",
    city: "Orlando", zip: "32805",
    latitude: 28.5559, longitude: -81.4319,
    source_name: "Second Harvest CFL",
  },
  {
    section: "F",
    title: "Community Legal Services of Mid-Florida Veterans Project",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal aid for low-income Central Florida veterans. VA benefits appeals, discharge upgrades, family law, housing, and consumer matters.",
    website_url: "https://www.clsmf.org",
    phone: "(407) 841-7777",
    address: "122 East Colonial Drive, Suite 200",
    city: "Orlando", zip: "32801",
    latitude: 28.5559, longitude: -81.3739,
    source_name: "Community Legal Services Mid-FL",
  },
  {
    section: "F",
    title: "Central Florida Veterans Memorial Park",
    cat: "community-support",
    sub: "Events, Trips & Retreats",
    desc: "Sanford memorial park hosting Veterans Day, Memorial Day, and Wreaths Across America ceremonies honoring Central Florida veterans.",
    website_url: "https://www.sanfordfl.gov/departments/parks-recreation/parks/veterans-memorial-park",
    phone: "(407) 688-5120",
    address: "100 East Seminole Boulevard",
    city: "Sanford", zip: "32771",
    latitude: 28.8108, longitude: -81.2715,
    source_name: "City of Sanford",
  },
  {
    section: "F",
    title: "Salvation Army Orlando Veterans Services",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Orlando Salvation Army emergency shelter and SSVF program providing housing crisis support to homeless veterans across Central Florida.",
    website_url: "https://salvationarmyflorida.org/orlando/",
    phone: "(407) 423-8581",
    address: "624 Lexington Avenue",
    city: "Orlando", zip: "32801",
    latitude: 28.5563, longitude: -81.3683,
    source_name: "Salvation Army",
  },
  {
    section: "F",
    title: "Central Florida National Cemetery",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery in Bushnell. Burial of eligible veterans, spouses, and dependents. Military funeral honors and headstone benefits.",
    website_url: "https://www.cem.va.gov/cems/nchp/florida.asp",
    phone: "(352) 793-7740",
    address: "5525 East SR 44",
    city: "Bushnell", zip: "33513",
    latitude: 28.6678, longitude: -82.0898,
    source_name: "VA NCA",
  },

  // ===========================================================================
  // G. Miami / Fort Lauderdale / West Palm Beach (SE Florida)
  // ===========================================================================
  {
    section: "G",
    title: "Miami-Dade County Veterans Services Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Miami-Dade County veteran service office providing free assistance with VA disability, pension, education, burial, and survivor benefits.",
    website_url: "https://www.miamidade.gov/global/service.page?Mduid_service=ser1535554005317108",
    phone: "(305) 375-4716",
    address: "111 NW 1st Street, Suite 1300",
    city: "Miami", zip: "33128",
    latitude: 25.7768, longitude: -80.1948,
    source_name: "Miami-Dade County",
  },
  {
    section: "G",
    title: "Broward County Veterans Services Section",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Broward County veteran service officers helping veterans file VA disability claims, pension, education, dependency, and survivor benefits.",
    website_url: "https://www.broward.org/HumanServices/CommunityPartnerships/VeteranServices/Pages/default.aspx",
    phone: "(954) 357-6622",
    address: "115 South Andrews Avenue, Room A-100",
    city: "Fort Lauderdale", zip: "33301",
    latitude: 26.1212, longitude: -80.1430,
    source_name: "Broward County",
  },
  {
    section: "G",
    title: "Palm Beach County Veteran Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Palm Beach County veteran service officers offering free assistance with VA claims, pension, education, dependency, and survivor benefits.",
    website_url: "https://discover.pbcgov.org/communityservices/veteranservices/",
    phone: "(561) 233-1320",
    address: "810 Datura Street, Suite 350",
    city: "West Palm Beach", zip: "33401",
    latitude: 26.7142, longitude: -80.0533,
    source_name: "Palm Beach County",
  },
  {
    section: "G",
    title: "Stand Down House Camillus",
    cat: "housing",
    sub: "Transitional Housing",
    desc: "Camillus House transitional residence in Miami for homeless veterans. Case management, employment readiness, mental health, and substance recovery support.",
    website_url: "https://camillus.org/programs/housing/stand-down-house/",
    phone: "(305) 374-1065",
    address: "1603 NW 7th Avenue",
    city: "Miami", zip: "33136",
    latitude: 25.7902, longitude: -80.2027,
    source_name: "Camillus House",
  },
  {
    section: "G",
    title: "Chapman Partnership Veterans Services",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Miami emergency shelter operating in partnership with Miami-Dade County Homeless Trust. Veteran-specific case management and transition planning.",
    website_url: "https://chapmanpartnership.org",
    phone: "(305) 329-3000",
    address: "1550 N Miami Avenue",
    city: "Miami", zip: "33136",
    latitude: 25.7886, longitude: -80.1966,
    source_name: "Chapman Partnership",
  },
  {
    section: "G",
    title: "Feeding South Florida",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Regional food bank serving Palm Beach, Broward, Miami-Dade, and Monroe counties. Operates partner pantries, mobile distributions, and senior food programs.",
    website_url: "https://feedingsouthflorida.org",
    phone: "(954) 518-1818",
    address: "2501 SW 32nd Terrace",
    city: "Pembroke Park", zip: "33023",
    latitude: 25.9881, longitude: -80.1860,
    source_name: "Feeding South Florida",
  },
  {
    section: "G",
    title: "Legal Aid Service of Broward County Veterans Project",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal services for low-income Broward County veterans. VA benefits appeals, discharge upgrades, family law, and housing matters.",
    website_url: "https://www.legalaid.org",
    phone: "(954) 765-8950",
    address: "491 N State Road 7",
    city: "Plantation", zip: "33317",
    latitude: 26.1262, longitude: -80.2036,
    source_name: "Legal Aid Service of Broward",
  },
  {
    section: "G",
    title: "Coast Guard Sector Miami Family Support",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "USCG Sector Miami Work-Life staff providing counseling, family advocacy, financial counseling, and transition assistance to Coast Guard members and families.",
    website_url: "https://www.atlanticarea.uscg.mil/Our-Organization/District-7/Sector-Miami/",
    phone: "(305) 535-4300",
    address: "100 MacArthur Causeway",
    city: "Miami Beach", zip: "33139",
    latitude: 25.7780, longitude: -80.1573,
    source_name: "USCG",
  },
  {
    section: "G",
    title: "South Florida National Cemetery",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery in Lake Worth serving SE Florida veterans. Burial of eligible veterans, spouses, and dependents with full military funeral honors.",
    website_url: "https://www.cem.va.gov/cems/nchp/southflorida.asp",
    phone: "(561) 649-6489",
    address: "6501 South State Road 7",
    city: "Lake Worth", zip: "33449",
    latitude: 26.5828, longitude: -80.2059,
    source_name: "VA NCA",
  },
  {
    section: "G",
    title: "Forgotten Soldiers Outreach",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "Lake Worth nonprofit sending care packages to deployed troops and supporting Florida veterans through outreach events and family support.",
    website_url: "https://forgottensoldiers.org",
    phone: "(561) 369-2829",
    address: "1200 N Old Dixie Highway",
    city: "Lake Worth", zip: "33460",
    latitude: 26.6262, longitude: -80.0641,
    source_name: "Forgotten Soldiers Outreach",
  },
  {
    section: "G",
    title: "Mission United Broward",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "United Way of Broward County Mission United program — single point of entry for Broward veterans needing housing, employment, education, and benefits help.",
    website_url: "https://www.unitedwaybroward.org/mission-united",
    phone: "(954) 462-4850",
    address: "1300 South Andrews Avenue",
    city: "Fort Lauderdale", zip: "33316",
    latitude: 26.1043, longitude: -80.1431,
    source_name: "United Way Broward",
  },

  // ===========================================================================
  // H. Pensacola / Panhandle (NAS Pensacola, Eglin, Tyndall)
  // ===========================================================================
  {
    section: "H",
    title: "Escambia County Veterans Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Escambia County veteran service officers providing free assistance with VA disability, pension, education, dependency, and survivor benefits.",
    website_url: "https://myescambia.com/our-services/community-and-media-relations/veteran-services",
    phone: "(850) 595-4400",
    address: "221 Palafox Place",
    city: "Pensacola", zip: "32502",
    latitude: 30.4108, longitude: -87.2168,
    source_name: "Escambia County",
  },
  {
    section: "H",
    title: "Okaloosa County Veterans Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Okaloosa County veteran service officers helping veterans across Eglin / Hurlburt area with VA claims, pension, education, and survivor benefits.",
    website_url: "https://myokaloosa.com/vsd",
    phone: "(850) 651-7560",
    address: "1804 Lewis Turner Boulevard",
    city: "Fort Walton Beach", zip: "32547",
    latitude: 30.4625, longitude: -86.6505,
    source_name: "Okaloosa County",
  },
  {
    section: "H",
    title: "Bay County Veterans Services Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Bay County veteran service officers providing free help with VA disability, pension, education, and burial benefits, serving Tyndall AFB community.",
    website_url: "https://www.baycountyfl.gov/411/Veterans-Services",
    phone: "(850) 248-8280",
    address: "840 W 11th Street",
    city: "Panama City", zip: "32401",
    latitude: 30.1684, longitude: -85.6766,
    source_name: "Bay County",
  },
  {
    section: "H",
    title: "Fleet & Family Support Center NAS Pensacola",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Navy Fleet & Family Support Center at NAS Pensacola. Counseling, transition assistance, financial readiness, deployment support, and family advocacy.",
    website_url: "https://cnrse.cnic.navy.mil/Installations/NAS-Pensacola/About/Installation-Guide/Fleet-Family-Support-Center/",
    phone: "(850) 452-5990",
    address: "151 Ellyson Avenue, Bldg 625",
    city: "Pensacola", zip: "32508",
    latitude: 30.3492, longitude: -87.3069,
    source_name: "Navy CNIC",
  },
  {
    section: "H",
    title: "Airman & Family Readiness Center Eglin AFB",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Eglin A&FRC serving the 96th Test Wing community. Transition assistance, EFMP, financial counseling, deployment readiness, and personal financial readiness.",
    website_url: "https://www.eglin.af.mil/Units/Eglin-AFRC/",
    phone: "(850) 882-9060",
    address: "550 W Van Matre Avenue, Bldg 590",
    city: "Eglin AFB", zip: "32542",
    latitude: 30.4774, longitude: -86.5414,
    source_name: "USAF",
  },
  {
    section: "H",
    title: "Airman & Family Readiness Center Tyndall AFB",
    cat: "family-support",
    sub: "Military Family Support",
    desc: "Tyndall A&FRC serving the 325th Fighter Wing community. Transition assistance, EFMP, deployment readiness, financial counseling, and family advocacy.",
    website_url: "https://www.tyndall.af.mil",
    phone: "(850) 283-4204",
    address: "445 Suwannee Road, Bldg 662",
    city: "Tyndall AFB", zip: "32403",
    latitude: 30.0908, longitude: -85.6049,
    source_name: "USAF",
  },
  {
    section: "H",
    title: "Manna Food Pantries Pensacola",
    cat: "food-assistance",
    sub: "Food Pantries",
    desc: "Pensacola nonprofit operating food pantries across Escambia and Santa Rosa counties. Serves veterans and families with weekly groceries.",
    website_url: "https://mannahelps.org",
    phone: "(850) 432-2053",
    address: "3030 N E Street",
    city: "Pensacola", zip: "32501",
    latitude: 30.4360, longitude: -87.2208,
    source_name: "Manna Food Pantries",
  },
  {
    section: "H",
    title: "Legal Services of North Florida Pensacola Office",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal aid for low-income Panhandle veterans. VA benefits appeals, discharge upgrades, family law, housing, and consumer matters.",
    website_url: "https://www.lsnf.org",
    phone: "(850) 432-2336",
    address: "1741 N Palafox Street",
    city: "Pensacola", zip: "32501",
    latitude: 30.4313, longitude: -87.2196,
    source_name: "Legal Services of North Florida",
  },
  {
    section: "H",
    title: "Mission United Pensacola",
    cat: "community-support",
    sub: "Veteran Outreach Programs",
    desc: "United Way of West Florida Mission United program coordinating Panhandle navigation across housing, employment, education, legal, and benefits.",
    website_url: "https://www.uwwf.org/mission-united",
    phone: "(850) 434-3157",
    address: "1301 W Government Street",
    city: "Pensacola", zip: "32502",
    latitude: 30.4094, longitude: -87.2266,
    source_name: "United Way West FL",
  },
  {
    section: "H",
    title: "Barrancas National Cemetery",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery on NAS Pensacola serving Panhandle veterans. Burial of eligible veterans, spouses, and dependents with military honors.",
    website_url: "https://www.cem.va.gov/cems/nchp/barrancas.asp",
    phone: "(850) 453-4108",
    address: "1 Cemetery Road",
    city: "Pensacola", zip: "32508",
    latitude: 30.3520, longitude: -87.2932,
    source_name: "VA NCA",
  },
  {
    section: "H",
    title: "Florida National Cemetery Bushnell Sumter Coverage",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery in Bushnell, Sumter County. Burial benefits and military funeral honors for Florida veterans, spouses, and dependents.",
    website_url: "https://www.cem.va.gov/cems/nchp/florida.asp",
    phone: "(352) 793-7740",
    address: "6502 SW 102nd Avenue",
    city: "Bushnell", zip: "33513",
    latitude: 28.6678, longitude: -82.0898,
    source_name: "VA NCA",
  },
  {
    section: "H",
    title: "Salvation Army Pensacola",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Pensacola Salvation Army Center of Hope emergency shelter and SSVF program supporting homeless veterans across the Panhandle.",
    website_url: "https://salvationarmyflorida.org/pensacola/",
    phone: "(850) 432-1579",
    address: "1501 N Q Street",
    city: "Pensacola", zip: "32505",
    latitude: 30.4296, longitude: -87.2310,
    source_name: "Salvation Army",
  },

  // ===========================================================================
  // I. Gainesville / N Central Florida
  // ===========================================================================
  {
    section: "I",
    title: "Alachua County Veterans Services Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Alachua County veteran service officers providing free assistance with VA disability, pension, education, dependency, and survivor benefits.",
    website_url: "https://veterans.alachuacounty.us",
    phone: "(352) 264-6740",
    address: "12 SE 1st Street, 2nd Floor",
    city: "Gainesville", zip: "32601",
    latitude: 29.6516, longitude: -82.3231,
    source_name: "Alachua County",
  },
  {
    section: "I",
    title: "St Francis House Gainesville",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Gainesville emergency shelter and supportive housing nonprofit. Veteran-specific case management and SSVF housing crisis support.",
    website_url: "https://stfrancishousegainesville.org",
    phone: "(352) 378-9079",
    address: "413 South Main Street",
    city: "Gainesville", zip: "32601",
    latitude: 29.6453, longitude: -82.3243,
    source_name: "St Francis House",
  },
  {
    section: "I",
    title: "University of Florida Veteran Services",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "UF Collegiate Veterans Success Center supporting student veterans with VA education benefits certification, peer mentoring, and academic resources.",
    website_url: "https://veterans.ufl.edu",
    phone: "(352) 294-2948",
    address: "1273 Stadium Road, Bldg 33",
    city: "Gainesville", zip: "32611",
    latitude: 29.6478, longitude: -82.3478,
    source_name: "University of Florida",
  },
  {
    section: "I",
    title: "Bread of the Mighty Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Gainesville-based Feeding America regional food bank serving 5 N Central Florida counties through partner pantries and direct distributions.",
    website_url: "https://breadofthemighty.org",
    phone: "(352) 336-0839",
    address: "325 NW 10th Avenue",
    city: "Gainesville", zip: "32601",
    latitude: 29.6580, longitude: -82.3327,
    source_name: "Bread of the Mighty",
  },
  {
    section: "I",
    title: "Three Rivers Legal Services Veterans Project",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal aid for low-income N Central Florida veterans. VA appeals, discharge upgrades, family law, housing, and consumer matters.",
    website_url: "https://trls.org",
    phone: "(352) 372-0519",
    address: "901 NW 8th Avenue, Suite D-5",
    city: "Gainesville", zip: "32601",
    latitude: 29.6604, longitude: -82.3471,
    source_name: "Three Rivers Legal Services",
  },
  {
    section: "I",
    title: "Marion County Veterans Services Office",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Marion County veteran service officers offering free help with VA disability, pension, education, and survivor benefits in Ocala / The Villages region.",
    website_url: "https://www.marionfl.org/agencies-departments/departments-facilities-offices/veteran-services",
    phone: "(352) 671-8422",
    address: "2730 East Silver Springs Boulevard",
    city: "Ocala", zip: "34470",
    latitude: 29.1873, longitude: -82.0942,
    source_name: "Marion County",
  },
  {
    section: "I",
    title: "Operation Comfort Warriors Ocala",
    cat: "community-support",
    sub: "Veteran Nonprofit Organizations",
    desc: "Ocala-based American Legion-affiliated program providing comfort items, technology, and recreation funding to wounded warriors recovering at military hospitals.",
    website_url: "https://www.legion.org/ocw",
    phone: "(800) 433-3318",
    city: "Ocala", zip: "34471",
    source_name: "American Legion",
  },

  // ===========================================================================
  // J. Tallahassee / Big Bend
  // ===========================================================================
  {
    section: "J",
    title: "Leon County Veteran Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Leon County veteran service officers providing free assistance with VA disability, pension, education, dependency, and survivor benefits.",
    website_url: "https://cms.leoncountyfl.gov/Home/Departments/Office-of-Human-Services-and-Community-Partnerships/Veterans-Services",
    phone: "(850) 606-1940",
    address: "918 Railroad Avenue",
    city: "Tallahassee", zip: "32310",
    latitude: 30.4319, longitude: -84.2807,
    source_name: "Leon County",
  },
  {
    section: "J",
    title: "Florida State University Student Veterans Center",
    cat: "education",
    sub: "Veteran Student Services",
    desc: "FSU Student Veterans Center supporting student veterans, dependents, and active duty with VA benefits certification and peer mentoring.",
    website_url: "https://veterans.fsu.edu",
    phone: "(850) 644-9562",
    address: "100 South Woodward Avenue",
    city: "Tallahassee", zip: "32306",
    latitude: 30.4419, longitude: -84.2978,
    source_name: "Florida State University",
  },
  {
    section: "J",
    title: "Second Harvest of the Big Bend",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Tallahassee regional food bank serving 16 Big Bend counties through partner pantries, mobile distributions, and senior food programs.",
    website_url: "https://fightinghunger.org",
    phone: "(850) 562-3033",
    address: "4446 Entrepot Boulevard",
    city: "Tallahassee", zip: "32310",
    latitude: 30.4226, longitude: -84.3477,
    source_name: "Second Harvest Big Bend",
  },
  {
    section: "J",
    title: "Legal Services of North Florida Tallahassee Office",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "Free civil legal aid for low-income Big Bend veterans. VA benefits appeals, discharge upgrades, family law, housing, and consumer matters.",
    website_url: "https://www.lsnf.org",
    phone: "(850) 385-9007",
    address: "2119 Delta Boulevard",
    city: "Tallahassee", zip: "32303",
    latitude: 30.4878, longitude: -84.2895,
    source_name: "Legal Services of North Florida",
  },
  {
    section: "J",
    title: "Salvation Army Tallahassee Veterans Programs",
    cat: "housing",
    sub: "Emergency Housing / Homeless Shelters",
    desc: "Tallahassee Salvation Army emergency shelter, SSVF, and SSI/SSDI Outreach Access and Recovery (SOAR) supporting homeless veterans across the Big Bend.",
    website_url: "https://salvationarmyflorida.org/tallahassee/",
    phone: "(850) 222-0304",
    address: "2410 Allen Road",
    city: "Tallahassee", zip: "32312",
    latitude: 30.4937, longitude: -84.2842,
    source_name: "Salvation Army",
  },
  {
    section: "J",
    title: "Tallahassee National Cemetery",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery serving Big Bend veterans. Burial of eligible veterans, spouses, and dependents with military funeral honors.",
    website_url: "https://www.cem.va.gov/cems/nchp/tallahassee.asp",
    phone: "(866) 232-1571",
    address: "5015 Apalachee Parkway",
    city: "Tallahassee", zip: "32311",
    latitude: 30.4309, longitude: -84.1715,
    source_name: "VA NCA",
  },

  // ===========================================================================
  // K. Sarasota / Fort Myers / Naples (SW Florida)
  // ===========================================================================
  {
    section: "K",
    title: "Sarasota County Veterans Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Sarasota County veteran service officers offering free help with VA disability, pension, education, and survivor benefits.",
    website_url: "https://www.scgov.net/government/health-and-human-services/veteran-services",
    phone: "(941) 861-2899",
    address: "4350 South Tamiami Trail, Suite B-04",
    city: "Sarasota", zip: "34231",
    latitude: 27.2895, longitude: -82.5181,
    source_name: "Sarasota County",
  },
  {
    section: "K",
    title: "Lee County Veteran Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Lee County veteran service officers providing free assistance with VA disability, pension, education, and survivor benefits in Fort Myers / Cape Coral.",
    website_url: "https://www.leegov.com/veterans",
    phone: "(239) 533-8381",
    address: "2440 Thompson Street",
    city: "Fort Myers", zip: "33901",
    latitude: 26.6312, longitude: -81.8609,
    source_name: "Lee County",
  },
  {
    section: "K",
    title: "Collier County Veteran Services",
    cat: "va-benefits",
    sub: "County Veterans Service Offices",
    desc: "Collier County veteran service officers offering free help with VA disability, pension, education, and survivor benefits in Naples / Marco Island region.",
    website_url: "https://www.colliercountyfl.gov/your-government/divisions-s-z/veteran-services",
    phone: "(239) 252-8387",
    address: "3299 Tamiami Trail East, Suite 105",
    city: "Naples", zip: "34112",
    latitude: 26.1310, longitude: -81.7884,
    source_name: "Collier County",
  },
  {
    section: "K",
    title: "Harry Chapin Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Fort Myers regional food bank serving 5 SW Florida counties. Partner pantries, mobile pantries, and senior food programs across Lee/Collier/Charlotte/Hendry/Glades.",
    website_url: "https://harrychapinfoodbank.org",
    phone: "(239) 334-7007",
    address: "3760 Fowler Street",
    city: "Fort Myers", zip: "33901",
    latitude: 26.6411, longitude: -81.8704,
    source_name: "Harry Chapin Food Bank",
  },
  {
    section: "K",
    title: "All Faiths Food Bank",
    cat: "food-assistance",
    sub: "Food Banks",
    desc: "Sarasota / DeSoto regional food bank operating partner pantries, mobile pantries, BackPack programs, and emergency food for veterans and families.",
    website_url: "https://allfaithsfoodbank.org",
    phone: "(941) 379-6333",
    address: "8171 Blaikie Court",
    city: "Sarasota", zip: "34240",
    latitude: 27.3539, longitude: -82.4378,
    source_name: "All Faiths Food Bank",
  },
  {
    section: "K",
    title: "Goodwill Industries SW Florida Veterans Programs",
    cat: "employment",
    sub: "Job Placement Programs",
    desc: "Goodwill SW Florida operating MissionUnited employment program for SW Florida veterans, including resume help, certifications, and direct placement.",
    website_url: "https://www.goodwillswfl.org/mission-services/veteran-services",
    phone: "(239) 995-2106",
    address: "5100 Tice Street",
    city: "Fort Myers", zip: "33905",
    latitude: 26.6534, longitude: -81.8064,
    source_name: "Goodwill SW Florida",
  },
  {
    section: "K",
    title: "Fort Myers Veterans Treatment Court",
    cat: "legal",
    sub: "Veterans Legal Clinics",
    desc: "20th Judicial Circuit Veterans Treatment Court serving Lee County veterans charged with criminal offenses; pairs treatment, mentorship, and judicial supervision.",
    website_url: "https://www.ca.cjis20.org/web/main/court_resources_veterans_treatment.aspx",
    phone: "(239) 533-2900",
    address: "1700 Monroe Street",
    city: "Fort Myers", zip: "33901",
    latitude: 26.6432, longitude: -81.8723,
    source_name: "20th Judicial Circuit",
  },
  {
    section: "K",
    title: "Sarasota Memorial Cemetery Veterans Section",
    cat: "end-of-life-services",
    sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Sarasota County-operated cemetery with dedicated veterans section. Coordination with VA NCA for headstones, military funeral honors, and burial allowances.",
    website_url: "https://www.scgov.net/government/general-services/sarasota-county-cemetery",
    phone: "(941) 861-5000",
    address: "1800 Pinebrook Road",
    city: "Venice", zip: "34292",
    latitude: 27.0998, longitude: -82.4051,
    source_name: "Sarasota County",
  },

  // ===========================================================================
  // L. Crisis & statewide hotlines (FL-tagged so they appear in FL search)
  // ===========================================================================
  {
    section: "L",
    title: "Florida 211 Veterans Help Line",
    cat: "crisis-help",
    sub: "Emergency Mental Health",
    desc: "Statewide 211 hotline connecting Florida veterans and families to crisis intervention, emergency shelter, food, utility, and behavioral health resources 24/7.",
    website_url: "https://www.211florida.org",
    phone: "211",
    city: "Tallahassee", zip: "32301",
    source_name: "United Way 211 Florida",
  },
  {
    section: "L",
    title: "Florida Initiative for Suicide Prevention",
    cat: "crisis-help",
    sub: "Suicide Prevention",
    desc: "Statewide Florida nonprofit providing suicide prevention training, postvention support, and survivor support groups for veterans and families.",
    website_url: "https://www.floridasuicideprevention.org",
    phone: "(786) 393-3650",
    city: "Coral Gables", zip: "33134",
    source_name: "FISP",
  },
  {
    section: "L",
    title: "Florida Domestic Violence Hotline",
    cat: "crisis-help",
    sub: "Domestic Violence / Safety",
    desc: "Florida Coalition Against Domestic Violence statewide 24/7 hotline. Safety planning, shelter referral, and advocacy for veterans and military families.",
    website_url: "https://www.fcadv.org",
    phone: "1-800-500-1119",
    address: "425 Office Plaza Drive",
    city: "Tallahassee", zip: "32301",
    source_name: "FCADV",
  },
  {
    section: "L",
    title: "Florida Mobile Response Team Statewide",
    cat: "crisis-help",
    sub: "Mobile Crisis Teams",
    desc: "Statewide network of Mobile Response Teams providing 24/7 in-person crisis response for behavioral health emergencies. Free and serves all ages.",
    website_url: "https://www.myflfamilies.com/services/samh/managing-entities/mobile-response-teams",
    phone: "1-800-985-5990",
    city: "Tallahassee", zip: "32301",
    source_name: "Florida DCF",
  },
  {
    section: "L",
    title: "Florida Crisis Text Line",
    cat: "crisis-help",
    sub: "Suicide Prevention",
    desc: "Free 24/7 crisis text line connecting Florida veterans and family members in emotional crisis with trained counselors. Text HOME to 741741.",
    website_url: "https://www.crisistextline.org",
    phone: "Text HOME to 741741",
    city: "Tallahassee", zip: "32301",
    source_name: "Crisis Text Line",
  },
  {
    section: "L",
    title: "Florida Veterans Foundation Crisis Assistance",
    cat: "financial",
    sub: "Emergency Financial Assistance",
    desc: "Statewide direct emergency financial assistance for Florida veterans facing utility shutoff, eviction, food insecurity, or transportation breakdown.",
    website_url: "https://floridaveteransfoundation.org",
    phone: "(727) 518-3202",
    address: "11351 Ulmerton Road, Suite 311-K",
    city: "Largo", zip: "33778",
    latitude: 27.9095, longitude: -82.7873,
    source_name: "Florida Veterans Foundation",
  },

  // ===========================================================================
  // M. Statewide nonprofits, food banks, legal aid, community
  // ===========================================================================
  {
    section: "M",
    title: "Florida Department of Economic Opportunity Veteran Services",
    cat: "employment",
    sub: "DVOP / Workforce Programs",
    desc: "FDEO administers Florida's CareerSource network with priority of service for veterans through Disabled Veterans Outreach Program and Local Veterans Employment Reps.",
    website_url: "https://floridajobs.org/job-seekers-community-services/veteran-services",
    phone: "(800) 342-3450",
    address: "107 East Madison Street",
    city: "Tallahassee", zip: "32399",
    latitude: 30.4380, longitude: -84.2807,
    source_name: "FDEO",
  },
  {
    section: "M",
    title: "Florida Veterans Hall of Fame",
    cat: "community-support",
    sub: "Events, Trips & Retreats",
    desc: "FDVA-sponsored statewide Florida Veterans Hall of Fame recognizing significant veteran contributions to the state. Annual induction events and exhibits.",
    website_url: "https://www.floridavets.org/florida-veterans-hall-of-fame/",
    phone: "(727) 518-3202",
    address: "11351 Ulmerton Road, Suite 311-K",
    city: "Largo", zip: "33778",
    latitude: 27.9095, longitude: -82.7873,
    source_name: "FDVA",
  },
  {
    section: "M",
    title: "Florida Disabled American Veterans State Headquarters",
    cat: "disabled-veterans",
    sub: "Disability Benefits & Claims",
    desc: "DAV Department of Florida state HQ. Free VA claims representation through accredited service officers in every Florida VA Regional Office.",
    website_url: "https://www.davfl.org",
    phone: "(727) 319-7440",
    address: "9500 Bay Pines Boulevard",
    city: "Saint Petersburg", zip: "33708",
    latitude: 27.8175, longitude: -82.7757,
    source_name: "DAV Florida",
  },
  {
    section: "M",
    title: "American Legion Department of Florida",
    cat: "community-support",
    sub: "American Legion Posts",
    desc: "American Legion state HQ overseeing 280+ posts across Florida. Programs include youth scholarships, oratorical contests, Boys State, Veterans Affairs, and rehabilitation.",
    website_url: "https://floridalegion.org",
    phone: "(407) 295-2631",
    address: "1912 Lee Road",
    city: "Orlando", zip: "32810",
    latitude: 28.6173, longitude: -81.3899,
    source_name: "American Legion",
  },
  {
    section: "M",
    title: "VFW Department of Florida",
    cat: "community-support",
    sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Department of Florida state HQ overseeing 240+ posts across Florida. VA claims representation, scholarships, and community service programs.",
    website_url: "https://floridavfw.org",
    phone: "(813) 805-7500",
    address: "8201 W Hillsborough Avenue",
    city: "Tampa", zip: "33615",
    latitude: 27.9876, longitude: -82.5664,
    source_name: "VFW",
  },
  {
    section: "M",
    title: "Goodwill Industries-Suncoast Veterans Services",
    cat: "employment",
    sub: "Job Placement Programs",
    desc: "Goodwill Suncoast operating veteran employment services across Pinellas, Hillsborough, and Pasco counties. Resume coaching, certifications, direct placement.",
    website_url: "https://www.goodwill-suncoast.org/mission-services/veterans-services/",
    phone: "(727) 523-1512",
    address: "10596 Gandy Boulevard",
    city: "Saint Petersburg", zip: "33702",
    latitude: 27.8852, longitude: -82.6308,
    source_name: "Goodwill Suncoast",
  },
  {
    section: "M",
    title: "Hire Heroes USA Florida Operations",
    cat: "employment",
    sub: "Resume & Career Coaching",
    desc: "National nonprofit providing free, personalized career coaching, resume writing, mock interviews, and job placement to Florida veterans and military spouses.",
    website_url: "https://www.hireheroesusa.org",
    phone: "(844) 634-1520",
    city: "Jacksonville", zip: "32256",
    source_name: "Hire Heroes USA",
  },
  {
    section: "M",
    title: "Operation Homefront Florida",
    cat: "financial",
    sub: "Emergency Financial Assistance",
    desc: "National nonprofit providing financial assistance, transitional housing, and family support to Florida military and veteran families through state field office.",
    website_url: "https://www.operationhomefront.org",
    phone: "(800) 722-6098",
    city: "Jacksonville", zip: "32256",
    source_name: "Operation Homefront",
  },
  {
    section: "M",
    title: "Folds of Honor Florida Scholarships",
    cat: "education",
    sub: "Tuition Assistance",
    desc: "National nonprofit providing educational scholarships to spouses and children of fallen or disabled Florida service members. K-12 and post-secondary awards.",
    website_url: "https://foldsofhonor.org",
    phone: "(918) 274-4700",
    city: "Jacksonville", zip: "32256",
    source_name: "Folds of Honor",
  },
  {
    section: "M",
    title: "Volunteers of America Florida Veterans Programs",
    cat: "housing",
    sub: "Homeless Veteran Services",
    desc: "VOA Florida operates SSVF, GPD transitional housing, and HUD-VASH support across multiple Florida regions. Direct housing crisis assistance for veterans.",
    website_url: "https://www.voaflorida.org",
    phone: "(407) 207-2906",
    address: "5005 LB McLeod Road",
    city: "Orlando", zip: "32811",
    latitude: 28.5184, longitude: -81.4189,
    source_name: "Volunteers of America Florida",
  },
  {
    section: "M",
    title: "Florida Vet 2 Vet",
    cat: "mental-health",
    sub: "Peer Support",
    desc: "Florida statewide veteran-to-veteran peer support nonprofit. Free peer counseling, training, and outreach pairing veterans with trained peers in their community.",
    website_url: "https://floridavet2vet.org",
    phone: "(813) 240-6644",
    city: "Tampa", zip: "33617",
    source_name: "Florida Vet 2 Vet",
  },
  {
    section: "M",
    title: "Florida Veterans Legal Helpline Three Rivers",
    cat: "legal",
    sub: "Legal Aid Services",
    desc: "Three Rivers Legal Services operates a statewide free legal helpline for low-income Florida veterans. VA appeals, discharge upgrades, family law, and housing.",
    website_url: "https://trls.org/veterans/",
    phone: "(866) 256-8091",
    address: "901 NW 8th Avenue, Suite D-5",
    city: "Gainesville", zip: "32601",
    latitude: 29.6604, longitude: -82.3471,
    source_name: "Three Rivers Legal Services",
  },
];

const SECTION_LABELS = {
  A: "FDVA + State Homes",
  B: "VAMC + CBOCs",
  C: "Vet Centers",
  D: "Jacksonville / NE",
  E: "Tampa / St Pete",
  F: "Orlando / Central",
  G: "Miami / Ft Laud / WPB",
  H: "Pensacola / Panhandle",
  I: "Gainesville / N Central",
  J: "Tallahassee / Big Bend",
  K: "Sarasota / Ft Myers / Naples",
  L: "Crisis & hotlines",
  M: "Statewide nonprofits",
};

await runSeed(ROWS, {
  state: "FL",
  commit: COMMIT,
  scriptName: "seed-fl-wave1",
  sectionLabels: SECTION_LABELS,
});
