/**
 * Texas Phase 1 — Batch 2: VAMC + CBOCs + Vet Centers (+ MTF + Fisher House + NCA + VBA + Specialty)
 *
 * Goal: 120-150+ verified rows from VA + military-adjacent healthcare infrastructure
 * statewide, with priority on the 10 founder-named metros (Dallas / Houston / San Antonio /
 * Austin / El Paso / Temple / Harlingen / Corpus Christi / Lubbock / Amarillo).
 *
 * Discipline:
 *   - Every URL pre-probed in this session: only va.gov system URLs / .tricare.mil URLs /
 *     fisherhouse.org root / cem.va.gov roots / vetcenter.va.gov root that returned 200.
 *   - VA system URLs are the most stable canonical surface (rarely rot). Vet Centers without
 *     a working slug fall back to vetcenter.va.gov root + descriptive title.
 *   - Each row's title carries the unique facility identifier — engine normalizeTitle strips
 *     after first dash and trailing parens, so titles use city-prefix-then-facility-type
 *     pattern (e.g. "Beaumont VA Clinic", "Charles Wilson VA Clinic Lufkin").
 *   - ZERO fabricated phones / addresses. Each city-anchored row uses the VA-published
 *     city ZIP only when I am confident in the canonical 5-digit ZIP from the VA facility
 *     locator. Where uncertain, ZIP omitted (statewide-style).
 *
 * Sources of truth:
 *   - VA HCS system pages: https://www.va.gov/<system-slug>-health-care/
 *   - VA Vet Centers: https://www.va.gov/<city>-vet-center/  (or vetcenter.va.gov fallback)
 *   - VA find-locations facility pages: https://www.va.gov/find-locations/facility/<id>
 *   - VA National Cemeteries: https://www.cem.va.gov/CEM/cems/listcem.asp
 *   - MTFs: https://<base>.tricare.mil/  + cnic.navy.mil base pages
 *   - Fisher House: https://fisherhouse.org/
 *   - VBA Regional Offices: https://benefits.va.gov/<office>/
 *
 * Skip-and-queue (no canonical URL verifiable this session):
 *   - Naval Health Clinic Corpus Christi: nhccc.tricare.mil DNS-fail; using NAS Corpus
 *     Christi base page is acceptable (per founder "military-adjacent where valid").
 */

import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");
const ALLOW_ZIP_BLEED = process.argv.includes("--allow-zip-bleed");

const ROWS: SeedRow[] = [
  // ============================================================
  // Section HCS — VA Health Care System parent pages (3)
  // (Only systems with multiple VAMCs underneath: North TX, South TX, Central TX.
  //  Houston/Amarillo/El Paso/West TX/Valley Coastal Bend each = 1 VAMC, so no parent row.)
  // ============================================================
  {
    section: "HCS",
    title: "VA North Texas Health Care System",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA system serving North Texas / Dallas-Fort Worth / Northeast Texas. Parent of Dallas VA Medical Center, Sam Rayburn Memorial Veterans Center (Bonham), and 8 community-based outpatient clinics (Tyler, Plano, Fort Worth, Denton, Sherman, Bridgeport, Granbury, and others).",
    website_url: "https://www.va.gov/north-texas-health-care/",
    eligibility: "All enrolled veterans in North Texas / DFW / Northeast Texas",
    source_name: "VA.gov North Texas HCS system page",
    source_type: "va_facility",
  },
  {
    section: "HCS",
    title: "VA South Texas Veterans Health Care System",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA system serving South Texas / Bexar County / Hill Country. Parent of Audie L. Murphy Memorial Veterans Hospital (San Antonio), Kerrville VA Medical Center, and CBOCs in San Antonio (Frank Tejeda OPC, North Central Federal Clinic), Victoria, Beeville, Eagle Pass, Laredo.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    eligibility: "All enrolled veterans in South Texas / San Antonio / Hill Country",
    source_name: "VA.gov South Texas Veterans HCS system page",
    source_type: "va_facility",
  },
  {
    section: "HCS",
    title: "VA Central Texas Veterans Health Care System",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA system serving Central Texas / Bell County / Brazos Valley / Travis County. Parent of Olin E. Teague Veterans Medical Center (Temple), Doris Miller Department of Veterans Affairs Medical Center (Waco), and CBOCs in Austin, Cedar Park, College Station, Killeen, La Grange, Palestine, Brownwood.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    eligibility: "All enrolled veterans in Central Texas / Austin / Waco / Temple corridor",
    source_name: "VA.gov Central Texas Veterans HCS system page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section VAMC — VA Medical Centers (11)
  // Each with city + canonical city ZIP from VA facility locator.
  // ============================================================
  {
    section: "VAMC",
    title: "Michael E. DeBakey VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Flagship Houston-area VAMC, one of the busiest VA medical centers in the U.S. Tertiary care including cardiac, oncology, polytrauma rehabilitation, spinal cord injury, and post-deployment mental health. Affiliated with Baylor College of Medicine.",
    website_url: "https://www.va.gov/houston-health-care/",
    phone: "713-791-1414",
    address: "2002 Holcombe Blvd",
    city: "Houston", zip: "77030",
    eligibility: "All enrolled veterans, priority by service-connection",
    source_name: "VA.gov MEDVAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Audie L. Murphy Memorial Veterans Hospital",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Primary VAMC of the South Texas Veterans Health Care System. Tertiary care including polytrauma, blind rehabilitation, geriatric/extended care, residential SUD treatment. Affiliated with UT Health San Antonio.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    phone: "210-617-5300",
    address: "7400 Merton Minter",
    city: "San Antonio", zip: "78229",
    eligibility: "All enrolled veterans in South Texas",
    source_name: "VA.gov Audie Murphy VAH facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Olin E. Teague Veterans Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Primary tertiary care VAMC of the Central Texas Veterans Health Care System, located in Temple. Inpatient medical/surgical care, mental health residential rehab, polytrauma, geriatric/extended care, hospice. Serves Bell County and the Fort Cavazos catchment.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    phone: "254-778-4811",
    address: "1901 Veterans Memorial Dr",
    city: "Temple", zip: "76504",
    eligibility: "All enrolled veterans in Central Texas",
    source_name: "VA.gov Olin Teague VAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Doris Miller Department of Veterans Affairs Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Secondary VAMC of the Central Texas Veterans Health Care System, located in Waco. Long-term mental health and SUD residential rehabilitation, primary care, specialty mental health programs. Named for Pearl Harbor hero Doris Miller.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    phone: "254-752-6581",
    address: "4800 Memorial Dr",
    city: "Waco", zip: "76711",
    eligibility: "All enrolled veterans in Central Texas",
    source_name: "VA.gov Doris Miller VAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Sam Rayburn Memorial Veterans Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Secondary VAMC of the VA North Texas Health Care System, located in Bonham. Long-term care, residential rehab, primary care, mental health programs serving Northeast Texas and parts of Southern Oklahoma. Named for House Speaker Sam Rayburn.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    phone: "903-583-2111",
    address: "1201 E 9th St",
    city: "Bonham", zip: "75418",
    eligibility: "All enrolled veterans in Northeast Texas",
    source_name: "VA.gov Sam Rayburn Memorial VAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Dallas VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Primary tertiary VAMC of the VA North Texas Health Care System, located in Dallas. Inpatient medical/surgical, polytrauma, spinal cord injury rehab, cardiothoracic surgery. Affiliated with UT Southwestern Medical Center.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    phone: "214-742-8387",
    address: "4500 S Lancaster Rd",
    city: "Dallas", zip: "75216",
    eligibility: "All enrolled veterans in North Texas / DFW",
    source_name: "VA.gov Dallas VAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Amarillo VA Health Care System",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VAMC and HCS serving the Texas Panhandle, parts of Eastern New Mexico, and Western Oklahoma. Inpatient medical/surgical, primary care, mental health, geriatric/extended care. Parent of the Lubbock CBOC.",
    website_url: "https://www.va.gov/amarillo-health-care/",
    phone: "806-355-9703",
    address: "6010 Amarillo Blvd West",
    city: "Amarillo", zip: "79106",
    eligibility: "All enrolled veterans in Texas Panhandle / Eastern NM / Western OK",
    source_name: "VA.gov Amarillo VAHCS facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "George H. O'Brien Jr. VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Primary VAMC of the West Texas VA Health Care System, located in Big Spring. Primary care, inpatient medical, mental health residential rehab, geriatric care serving the Permian Basin and West Texas. Named for Korean War Medal of Honor recipient George O'Brien.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    phone: "432-263-7361",
    address: "300 Veterans Blvd",
    city: "Big Spring", zip: "79720",
    eligibility: "All enrolled veterans in West Texas / Permian Basin",
    source_name: "VA.gov George H. O'Brien Jr. VAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "El Paso VA Health Care System",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA Health Care System serving El Paso and Southern New Mexico. Outpatient ambulatory care center (no inpatient — referrals to William Beaumont AMC and community care). Primary care, specialty care, mental health, dental.",
    website_url: "https://www.va.gov/el-paso-health-care/",
    phone: "915-564-6100",
    address: "5001 N Piedras St",
    city: "El Paso", zip: "79930",
    eligibility: "All enrolled veterans in El Paso / Southern NM",
    source_name: "VA.gov El Paso VAHCS facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "Kerrville VA Medical Center",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "Secondary VAMC of the South Texas Veterans Health Care System, located in the Hill Country. Long-term care, hospice, residential rehab, primary care. Serves Kerr County and surrounding Hill Country veterans.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    phone: "830-896-2020",
    address: "3600 Memorial Blvd",
    city: "Kerrville", zip: "78028",
    eligibility: "All enrolled veterans in Hill Country / South Texas",
    source_name: "VA.gov Kerrville VAMC facility page",
    source_type: "va_facility",
  },
  {
    section: "VAMC",
    title: "VA Texas Valley Coastal Bend Health Care System",
    cat: "healthcare", sub: "VA Medical Centers",
    desc: "VA HCS serving the Rio Grande Valley and Coastal Bend. Headquartered at the Harlingen VA Health Care Center (large outpatient ambulatory center, no inpatient — referrals to South Texas VAMC). Parent of McAllen, Brownsville, and Corpus Christi outpatient clinics.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    phone: "956-291-9000",
    address: "2106 Treasure Hills Blvd",
    city: "Harlingen", zip: "78550",
    eligibility: "All enrolled veterans in Rio Grande Valley / Coastal Bend",
    source_name: "VA.gov Texas Valley Coastal Bend HCS facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section VC — Vet Centers (Readjustment Counseling) (22)
  // Combat-veteran / MST counseling, separate from VAMC. 15 with working VA slug,
  // 7 fall back to vetcenter.va.gov root with descriptive title.
  // ============================================================
  {
    section: "VC",
    title: "Houston Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Houston-area Vet Center providing readjustment counseling for combat veterans, military sexual trauma survivors, and bereaved families. Free, confidential, no enrollment in VA health care required.",
    website_url: "https://www.vetcenter.va.gov/",
    phone: "713-523-0884",
    city: "Houston",
    eligibility: "Combat veterans, MST survivors, bereaved military families",
    source_name: "VA Vet Center program (vetcenter.va.gov)",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Houston West Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Southwest Houston Vet Center serving Bellaire / Sugar Land / SW Houston metro. Readjustment counseling, group therapy, family services for combat veterans and MST survivors.",
    website_url: "https://www.va.gov/houston-west-vet-center/",
    phone: "713-981-8387",
    city: "Houston",
    eligibility: "Combat veterans, MST survivors in SW Houston",
    source_name: "VA.gov Houston West Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "North Houston Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "North Houston Vet Center serving Spring / FM 1960 / Conroe corridor. Readjustment counseling for combat veterans, MST survivors, and bereaved military families.",
    website_url: "https://www.vetcenter.va.gov/",
    phone: "346-303-1486",
    city: "Houston",
    eligibility: "Combat veterans, MST survivors in N Houston / Spring / Conroe",
    source_name: "VA Vet Center program (vetcenter.va.gov)",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Dallas Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Dallas Vet Center providing readjustment counseling for combat veterans, MST survivors, and bereaved military families across the DFW metroplex.",
    website_url: "https://www.va.gov/dallas-vet-center/",
    phone: "214-361-5896",
    city: "Dallas",
    eligibility: "Combat veterans, MST survivors, bereaved military families",
    source_name: "VA.gov Dallas Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Mesquite Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "East DFW Vet Center serving Mesquite / Garland / Rockwall corridor. Readjustment counseling for combat veterans and MST survivors.",
    website_url: "https://www.va.gov/mesquite-vet-center/",
    city: "Mesquite",
    eligibility: "Combat veterans, MST survivors in East DFW",
    source_name: "VA.gov Mesquite Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Fort Worth Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Fort Worth Vet Center serving Tarrant County. Readjustment counseling, individual and group therapy, family services for combat veterans and MST survivors.",
    website_url: "https://www.va.gov/fort-worth-vet-center/",
    city: "Fort Worth",
    eligibility: "Combat veterans, MST survivors in Tarrant County",
    source_name: "VA.gov Fort Worth Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Plano Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "North DFW Vet Center serving Plano / Frisco / Allen / Collin County. Readjustment counseling for combat veterans, MST survivors, and bereaved families.",
    website_url: "https://www.vetcenter.va.gov/",
    city: "Plano",
    eligibility: "Combat veterans, MST survivors in Collin County",
    source_name: "VA Vet Center program (vetcenter.va.gov)",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Tyler Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "East Texas Vet Center serving Tyler / Smith County / Longview corridor. Readjustment counseling for combat veterans and MST survivors.",
    website_url: "https://www.vetcenter.va.gov/",
    city: "Tyler",
    eligibility: "Combat veterans, MST survivors in East Texas",
    source_name: "VA Vet Center program (vetcenter.va.gov)",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Austin Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Austin Vet Center serving Travis / Williamson / Hays counties. Readjustment counseling, group therapy, MST and family services for combat veterans.",
    website_url: "https://www.va.gov/austin-vet-center/",
    phone: "512-416-1314",
    city: "Austin",
    eligibility: "Combat veterans, MST survivors in Central Texas",
    source_name: "VA.gov Austin Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Killeen Heights Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Bell County Vet Center serving Fort Cavazos active-duty transitioning veterans plus combat veterans of Bell / Coryell / Lampasas counties. High-volume military-adjacent center.",
    website_url: "https://www.va.gov/killeen-heights-vet-center/",
    phone: "254-953-7100",
    city: "Killeen",
    eligibility: "Combat veterans, MST survivors, transitioning Fort Cavazos veterans",
    source_name: "VA.gov Killeen Heights Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "San Antonio Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "San Antonio Vet Center serving Bexar County. Readjustment counseling for combat veterans, MST survivors, and bereaved military families. JBSA active-duty transitioning veterans served.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0306V",
    city: "San Antonio",
    eligibility: "Combat veterans, MST survivors in Bexar County",
    source_name: "VA.gov San Antonio Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Northeast San Antonio Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Northeast SA Vet Center serving Schertz / Cibolo / Universal City / Selma. Readjustment counseling for combat veterans and MST survivors with focus on JBSA Randolph veterans.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0606V",
    city: "San Antonio",
    eligibility: "Combat veterans, MST survivors in NE Bexar County / JBSA-Randolph veterans",
    source_name: "VA.gov NE San Antonio Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "El Paso Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "El Paso Vet Center serving El Paso County and Southern NM. Readjustment counseling for combat veterans, MST survivors, and Fort Bliss transitioning veterans.",
    website_url: "https://www.va.gov/el-paso-vet-center/",
    city: "El Paso",
    eligibility: "Combat veterans, MST survivors, transitioning Fort Bliss veterans",
    source_name: "VA.gov El Paso Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Lubbock Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Lubbock Vet Center serving the South Plains region. Readjustment counseling for combat veterans, MST survivors, and bereaved military families.",
    website_url: "https://www.va.gov/lubbock-vet-center/",
    city: "Lubbock",
    eligibility: "Combat veterans, MST survivors in South Plains region",
    source_name: "VA.gov Lubbock Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Amarillo Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Amarillo Vet Center serving the Texas Panhandle. Readjustment counseling for combat veterans, MST survivors, and bereaved families.",
    website_url: "https://www.va.gov/amarillo-vet-center/",
    city: "Amarillo",
    eligibility: "Combat veterans, MST survivors in Texas Panhandle",
    source_name: "VA.gov Amarillo Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Corpus Christi Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Corpus Christi Vet Center serving the Coastal Bend. Readjustment counseling for combat veterans, MST survivors, and Naval Air Station Corpus Christi transitioning veterans.",
    website_url: "https://www.va.gov/corpus-christi-vet-center/",
    city: "Corpus Christi",
    eligibility: "Combat veterans, MST survivors, NAS Corpus Christi transitioning",
    source_name: "VA.gov Corpus Christi Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "McAllen Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "McAllen Vet Center serving the Rio Grande Valley. Readjustment counseling for combat veterans and MST survivors. Bilingual services available.",
    website_url: "https://www.va.gov/mcallen-vet-center/",
    city: "McAllen",
    eligibility: "Combat veterans, MST survivors in Rio Grande Valley",
    source_name: "VA.gov McAllen Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Beaumont Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Southeast Texas Vet Center serving Beaumont / Port Arthur / Orange. Readjustment counseling for combat veterans, MST survivors, and bereaved families.",
    website_url: "https://www.va.gov/beaumont-vet-center/",
    city: "Beaumont",
    eligibility: "Combat veterans, MST survivors in Golden Triangle",
    source_name: "VA.gov Beaumont Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Laredo Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Laredo Vet Center serving Webb County and the South Texas border region. Readjustment counseling for combat veterans and MST survivors. Bilingual services.",
    website_url: "https://www.va.gov/laredo-vet-center/",
    city: "Laredo",
    eligibility: "Combat veterans, MST survivors in Webb County / border region",
    source_name: "VA.gov Laredo Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Midland Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Permian Basin Vet Center serving Midland / Odessa / surrounding West Texas. Readjustment counseling for combat veterans and MST survivors.",
    website_url: "https://www.va.gov/midland-vet-center/",
    city: "Midland",
    eligibility: "Combat veterans, MST survivors in Permian Basin",
    source_name: "VA.gov Midland Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Abilene Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Abilene Vet Center serving Big Country region. Readjustment counseling for combat veterans, MST survivors, and Dyess AFB transitioning veterans.",
    website_url: "https://www.va.gov/abilene-vet-center/",
    city: "Abilene",
    eligibility: "Combat veterans, MST survivors, Dyess AFB transitioning",
    source_name: "VA.gov Abilene Vet Center facility page",
    source_type: "va_facility",
  },
  {
    section: "VC",
    title: "Brazos Valley Vet Center",
    cat: "mental-health", sub: "Vet Centers",
    desc: "Brazos Valley (Bryan / College Station) Vet Center serving Brazos County. Readjustment counseling for combat veterans and MST survivors.",
    website_url: "https://www.vetcenter.va.gov/",
    city: "Bryan",
    eligibility: "Combat veterans, MST survivors in Brazos Valley",
    source_name: "VA Vet Center program (vetcenter.va.gov)",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_H — Houston-area CBOCs (9)
  // ============================================================
  {
    section: "CBOC_H",
    title: "Beaumont VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic serving Beaumont / Port Arthur / Orange. Primary care, mental health, basic specialty care.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Beaumont",
    eligibility: "Enrolled veterans in Southeast Texas",
    source_name: "VA.gov Beaumont VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Charles Wilson VA Clinic Lufkin",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Lufkin (East Texas). Primary care, mental health, telehealth specialty referrals. Named for Congressman Charlie Wilson.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Lufkin",
    eligibility: "Enrolled veterans in East Texas / Angelina County",
    source_name: "VA.gov Charles Wilson VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Conroe VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Conroe serving Montgomery County and North Houston suburbs. Primary care and mental health.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Conroe",
    eligibility: "Enrolled veterans in Montgomery County",
    source_name: "VA.gov Conroe VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Galveston VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Galveston. Primary care and mental health serving Galveston Island and the Bolivar Peninsula.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Galveston",
    eligibility: "Enrolled veterans in Galveston County",
    source_name: "VA.gov Galveston VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Katy VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Katy serving West Houston suburbs (Fort Bend / Waller). Primary care and mental health.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Katy",
    eligibility: "Enrolled veterans in Fort Bend / W Harris County",
    source_name: "VA.gov Katy VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Lake Jackson VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Lake Jackson serving Brazoria County and the Texas Gulf Coast. Primary care and mental health.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Lake Jackson",
    eligibility: "Enrolled veterans in Brazoria County",
    source_name: "VA.gov Lake Jackson VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Richmond VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Richmond serving Fort Bend County. Primary care and mental health.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Richmond",
    eligibility: "Enrolled veterans in Fort Bend County",
    source_name: "VA.gov Richmond VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Texas City VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Texas City serving the Galveston County mainland. Primary care and mental health.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Texas City",
    eligibility: "Enrolled veterans in Galveston County mainland",
    source_name: "VA.gov Texas City VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_H",
    title: "Tomball VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Houston VA HCS community-based outpatient clinic in Tomball serving NW Harris County and Magnolia / Hempstead corridor. Primary care and mental health.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Tomball",
    eligibility: "Enrolled veterans in NW Harris County",
    source_name: "VA.gov Tomball VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_N — North Texas CBOCs (8)
  // ============================================================
  {
    section: "CBOC_N",
    title: "Tyler VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS community-based outpatient clinic in Tyler serving Smith County and surrounding East Texas counties. Primary care, mental health, basic specialty care.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Tyler",
    eligibility: "Enrolled veterans in Smith County / East Texas",
    source_name: "VA.gov Tyler VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Plano VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS community-based outpatient clinic in Plano serving Collin County and North DFW suburbs. Primary care and mental health.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Plano",
    eligibility: "Enrolled veterans in Collin County",
    source_name: "VA.gov Plano VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Fort Worth VA Outpatient Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS large multi-specialty outpatient clinic in Fort Worth serving Tarrant County. Primary care, mental health, multiple specialty clinics, ambulatory surgery, dental.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Fort Worth",
    eligibility: "Enrolled veterans in Tarrant County",
    source_name: "VA.gov Fort Worth VA OPC facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Denton VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS community-based outpatient clinic in Denton serving Denton County. Primary care and mental health.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Denton",
    eligibility: "Enrolled veterans in Denton County",
    source_name: "VA.gov Denton VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Sherman VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS community-based outpatient clinic in Sherman serving Grayson County and the Red River corridor. Primary care and mental health.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Sherman",
    eligibility: "Enrolled veterans in Grayson County",
    source_name: "VA.gov Sherman VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Bridgeport VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS community-based outpatient clinic in Bridgeport serving Wise County and rural North Texas. Primary care and mental health.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Bridgeport",
    eligibility: "Enrolled veterans in Wise County / rural North Texas",
    source_name: "VA.gov Bridgeport VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Granbury VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS community-based outpatient clinic in Granbury serving Hood County and SW DFW corridor. Primary care and mental health.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Granbury",
    eligibility: "Enrolled veterans in Hood County",
    source_name: "VA.gov Granbury VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_N",
    title: "Polk Street VA Clinic Dallas",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA North Texas HCS satellite outpatient annex on Polk Street in Dallas, serving downtown / South Dallas overflow from the main Dallas VAMC. Primary care and outpatient mental health.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Dallas",
    eligibility: "Enrolled veterans in Dallas County",
    source_name: "VA.gov Polk Street VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_C — Central Texas CBOCs (7)
  // ============================================================
  {
    section: "CBOC_C",
    title: "Austin VA Outpatient Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS large outpatient clinic in Austin (largest CBOC in Texas). Primary care, mental health, multiple specialty clinics, ambulatory surgery. Serves Travis / Williamson / Hays counties.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Austin",
    eligibility: "Enrolled veterans in Austin metro / Central Texas",
    source_name: "VA.gov Austin VA OPC facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_C",
    title: "Cedar Park VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS community-based outpatient clinic in Cedar Park serving NW Austin metro and Williamson County. Primary care and mental health.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Cedar Park",
    eligibility: "Enrolled veterans in NW Austin / Williamson County",
    source_name: "VA.gov Cedar Park VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_C",
    title: "College Station VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS community-based outpatient clinic in College Station serving Brazos Valley. Primary care and mental health.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "College Station",
    eligibility: "Enrolled veterans in Brazos Valley",
    source_name: "VA.gov College Station VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_C",
    title: "La Grange VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS community-based outpatient clinic in La Grange serving Fayette County and the rural corridor between Austin and Houston. Primary care.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "La Grange",
    eligibility: "Enrolled veterans in Fayette County",
    source_name: "VA.gov La Grange VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_C",
    title: "Palestine VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS community-based outpatient clinic in Palestine serving Anderson County and rural East Central Texas. Primary care and mental health.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Palestine",
    eligibility: "Enrolled veterans in Anderson County",
    source_name: "VA.gov Palestine VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_C",
    title: "Brownwood VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS community-based outpatient clinic in Brownwood serving Brown County and the Heart of Texas region. Primary care and mental health.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Brownwood",
    eligibility: "Enrolled veterans in Brown County",
    source_name: "VA.gov Brownwood VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_C",
    title: "Killeen VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Central Texas VA HCS community-based outpatient clinic in Killeen serving Bell County and Fort Cavazos transitioning veterans. Primary care, mental health, women veterans services.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Killeen",
    eligibility: "Enrolled veterans in Bell County / transitioning Fort Cavazos",
    source_name: "VA.gov Killeen VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_S — South Texas CBOCs (7)
  // ============================================================
  {
    section: "CBOC_S",
    title: "Frank M. Tejeda Outpatient Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "South Texas VA HCS large outpatient clinic in San Antonio (NW SA), satellite of Audie Murphy VAMC. Primary care, mental health, women veterans, multiple specialty clinics. Named for Congressman Frank Tejeda.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "San Antonio",
    eligibility: "Enrolled veterans in NW Bexar County",
    source_name: "VA.gov Frank Tejeda OPC facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_S",
    title: "North Central Federal Clinic San Antonio",
    cat: "healthcare", sub: "VA Clinics",
    desc: "South Texas VA HCS multi-specialty federal clinic in NE San Antonio (Wurzbach Pkwy area). Primary care, mental health, specialty referrals.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "San Antonio",
    eligibility: "Enrolled veterans in NE Bexar County",
    source_name: "VA.gov North Central Federal Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_S",
    title: "Victoria VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "South Texas VA HCS community-based outpatient clinic in Victoria serving Victoria County and Crossroads region. Primary care and mental health.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "Victoria",
    eligibility: "Enrolled veterans in Victoria County",
    source_name: "VA.gov Victoria VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_S",
    title: "Beeville VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "South Texas VA HCS community-based outpatient clinic in Beeville serving Bee County and rural South Texas. Primary care and mental health.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "Beeville",
    eligibility: "Enrolled veterans in Bee County",
    source_name: "VA.gov Beeville VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_S",
    title: "Eagle Pass VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "South Texas VA HCS community-based outpatient clinic in Eagle Pass serving Maverick County and the South Texas border region. Primary care and mental health, bilingual services.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "Eagle Pass",
    eligibility: "Enrolled veterans in Maverick County",
    source_name: "VA.gov Eagle Pass VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_S",
    title: "Laredo VA Outpatient Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA outpatient clinic in Laredo serving Webb County and the Rio Grande border. Primary care, mental health, women veterans services. Bilingual.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "Laredo",
    eligibility: "Enrolled veterans in Webb County",
    source_name: "VA.gov Laredo VA OPC facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_S",
    title: "New Braunfels VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "South Texas VA HCS community-based outpatient clinic in New Braunfels serving Comal County and the Hill Country corridor between SA and Austin. Primary care and mental health.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "New Braunfels",
    eligibility: "Enrolled veterans in Comal County",
    source_name: "VA.gov New Braunfels VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_W — West Texas CBOCs (4)
  // ============================================================
  {
    section: "CBOC_W",
    title: "Abilene VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "West Texas VA HCS community-based outpatient clinic in Abilene serving the Big Country region and Dyess AFB transitioning veterans. Primary care and mental health.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Abilene",
    eligibility: "Enrolled veterans in Big Country / Dyess AFB transitioning",
    source_name: "VA.gov Abilene VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_W",
    title: "Odessa VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "West Texas VA HCS community-based outpatient clinic in Odessa serving Ector County and Permian Basin. Primary care and mental health.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Odessa",
    eligibility: "Enrolled veterans in Ector County",
    source_name: "VA.gov Odessa VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_W",
    title: "San Angelo VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "West Texas VA HCS community-based outpatient clinic in San Angelo serving Tom Green County and surrounding Concho Valley. Primary care and mental health.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "San Angelo",
    eligibility: "Enrolled veterans in Tom Green County / Concho Valley",
    source_name: "VA.gov San Angelo VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_W",
    title: "Fort Stockton VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "West Texas VA HCS community-based outpatient clinic in Fort Stockton serving Pecos County and rural West Texas. Primary care.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Fort Stockton",
    eligibility: "Enrolled veterans in Pecos County / rural West Texas",
    source_name: "VA.gov Fort Stockton VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_E — El Paso area (1)
  // ============================================================
  {
    section: "CBOC_E",
    title: "Eastside El Paso VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "El Paso VA HCS satellite community-based outpatient clinic on the East side of El Paso, complementing the main El Paso ambulatory care center. Primary care and mental health.",
    website_url: "https://www.va.gov/el-paso-health-care/",
    city: "El Paso",
    eligibility: "Enrolled veterans in East El Paso",
    source_name: "VA.gov Eastside El Paso VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_VCB — Valley Coastal Bend CBOCs (3)
  // ============================================================
  {
    section: "CBOC_VCB",
    title: "McAllen VA Outpatient Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA Texas Valley Coastal Bend HCS large outpatient clinic in McAllen serving Hidalgo County and the Rio Grande Valley. Primary care, mental health, multiple specialty clinics. Bilingual.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    city: "McAllen",
    eligibility: "Enrolled veterans in Hidalgo County / Rio Grande Valley",
    source_name: "VA.gov McAllen VA OPC facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_VCB",
    title: "Brownsville VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA Texas Valley Coastal Bend HCS community-based outpatient clinic in Brownsville serving Cameron County and the southern tip of Texas. Primary care and mental health. Bilingual.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    city: "Brownsville",
    eligibility: "Enrolled veterans in Cameron County",
    source_name: "VA.gov Brownsville VA Clinic facility page",
    source_type: "va_facility",
  },
  {
    section: "CBOC_VCB",
    title: "Corpus Christi VA Outpatient Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "VA Texas Valley Coastal Bend HCS large outpatient clinic in Corpus Christi serving Nueces County and the Coastal Bend. Primary care, mental health, multiple specialty clinics. Serves NAS Corpus Christi transitioning veterans.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    city: "Corpus Christi",
    eligibility: "Enrolled veterans in Coastal Bend",
    source_name: "VA.gov Corpus Christi VA OPC facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CBOC_AMA — Amarillo system CBOC (1)
  // ============================================================
  {
    section: "CBOC_AMA",
    title: "Lubbock VA Clinic",
    cat: "healthcare", sub: "VA Clinics",
    desc: "Amarillo VA HCS community-based outpatient clinic in Lubbock serving the South Plains region (Hub City). Primary care, mental health, women veterans services.",
    website_url: "https://www.va.gov/amarillo-health-care/",
    city: "Lubbock",
    eligibility: "Enrolled veterans in Lubbock County / South Plains",
    source_name: "VA.gov Lubbock VA Clinic facility page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section DOM — VA Domiciliary residential rehabilitation programs (4)
  // Distinct programs at major VAMCs for homeless rehab + SUD/MH residential.
  // ============================================================
  {
    section: "DOM",
    title: "DeBakey VAMC Domiciliary Residential Rehabilitation",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Residential rehabilitation domiciliary program at Michael E. DeBakey VAMC Houston. Long-term residential treatment for homeless veterans with SUD, mental health needs, and complex psychosocial issues. Intake via Houston VAMC.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Houston",
    eligibility: "Homeless veterans with rehabilitation needs",
    source_name: "VA.gov DeBakey Domiciliary program page",
    source_type: "va_facility",
  },
  {
    section: "DOM",
    title: "Sam Rayburn VAMC Domiciliary Residential Rehabilitation",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Long-standing residential rehabilitation domiciliary program at Sam Rayburn Memorial Veterans Center, Bonham. Long-term residential treatment for homeless veterans with SUD, mental health, and complex psychosocial needs. Intake via VA North Texas HCS.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Bonham",
    eligibility: "Homeless veterans referred from VA North Texas HCS",
    source_name: "VA.gov Sam Rayburn Domiciliary program page",
    source_type: "va_facility",
  },
  {
    section: "DOM",
    title: "Doris Miller VAMC Domiciliary Residential Rehabilitation",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Residential rehabilitation domiciliary program at Doris Miller VAMC Waco. Long-term residential SUD and mental-health treatment for homeless and at-risk veterans. Intake via VA Central Texas HCS.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Waco",
    eligibility: "Homeless veterans referred from VA Central Texas HCS",
    source_name: "VA.gov Doris Miller Domiciliary program page",
    source_type: "va_facility",
  },
  {
    section: "DOM",
    title: "George O'Brien VAMC Domiciliary Residential Rehabilitation",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Residential rehabilitation domiciliary program at George H. O'Brien Jr. VAMC Big Spring. Long-term residential SUD and mental-health treatment for homeless West Texas veterans.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Big Spring",
    eligibility: "Homeless veterans referred from West Texas VA HCS",
    source_name: "VA.gov George O'Brien Domiciliary program page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section NCA — National Cemeteries (5)
  // ============================================================
  {
    section: "NCA",
    title: "Dallas-Fort Worth National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery serving the DFW metroplex. Burial for eligible veterans, spouses, and dependents. Open daily for visitation; columbarium and casketed sections.",
    website_url: "https://www.cem.va.gov/",
    phone: "817-468-9333",
    address: "2000 Mountain Creek Pkwy",
    city: "Dallas", zip: "75211",
    eligibility: "Eligible veterans, spouses, and dependents per NCA rules",
    source_name: "VA NCA Dallas-Fort Worth National Cemetery listing",
    source_type: "va_facility",
  },
  {
    section: "NCA",
    title: "Houston National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery in north Houston serving Southeast Texas. Burial for eligible veterans, spouses, and dependents. One of the largest national cemeteries by burial volume.",
    website_url: "https://www.cem.va.gov/",
    phone: "281-447-8686",
    address: "10410 Veterans Memorial Dr",
    city: "Houston", zip: "77038",
    eligibility: "Eligible veterans, spouses, and dependents per NCA rules",
    source_name: "VA NCA Houston National Cemetery listing",
    source_type: "va_facility",
  },
  {
    section: "NCA",
    title: "Fort Sam Houston National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery on JBSA Fort Sam Houston in San Antonio. Burial for eligible veterans, spouses, and dependents. Adjacent to the historic San Antonio National Cemetery.",
    website_url: "https://www.cem.va.gov/",
    phone: "210-820-3891",
    address: "1520 Harry Wurzbach Rd",
    city: "San Antonio", zip: "78209",
    eligibility: "Eligible veterans, spouses, and dependents per NCA rules",
    source_name: "VA NCA Fort Sam Houston National Cemetery listing",
    source_type: "va_facility",
  },
  {
    section: "NCA",
    title: "Kerrville National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA National Cemetery on the grounds of Kerrville VA Medical Center. Burial for eligible veterans, spouses, and dependents in the Hill Country region.",
    website_url: "https://www.cem.va.gov/",
    phone: "210-820-3891",
    address: "3600 Memorial Blvd",
    city: "Kerrville", zip: "78028",
    eligibility: "Eligible veterans, spouses, and dependents per NCA rules",
    source_name: "VA NCA Kerrville National Cemetery listing",
    source_type: "va_facility",
  },
  {
    section: "NCA",
    title: "San Antonio National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Historic VA National Cemetery established in 1867, the oldest national cemetery in Texas. Closed to new casketed burials (cremated remains in existing family plots only). Open daily for visitation.",
    website_url: "https://www.cem.va.gov/",
    phone: "210-820-3891",
    address: "517 Paso Hondo St",
    city: "San Antonio", zip: "78202",
    eligibility: "Cremated remains of eligible veterans in existing family plots",
    source_name: "VA NCA San Antonio National Cemetery listing",
    source_type: "va_facility",
  },

  // ============================================================
  // Section MTF — Military Treatment Facilities (military-adjacent healthcare) (4)
  // Founder approved military-adjacent inclusion. Each serves veterans via TRICARE
  // for retirees, Space-A health care, and for active-duty transitioning vets.
  // ============================================================
  {
    section: "MTF",
    title: "Brooke Army Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Brooke Army Medical Center (BAMC) on JBSA Fort Sam Houston is the Department of Defense's largest medical center and the only Level I trauma center in DoD. Serves active-duty, retirees (TRICARE), and includes the San Antonio Military Medical Center polytrauma rehab program.",
    website_url: "https://bamc.tricare.mil/",
    phone: "210-916-4141",
    address: "3551 Roger Brooke Dr",
    city: "Fort Sam Houston", zip: "78234",
    eligibility: "Active-duty, retirees (TRICARE), and trauma referrals",
    source_name: "BAMC official tricare.mil portal",
    source_type: "military",
  },
  {
    section: "MTF",
    title: "Wilford Hall Ambulatory Surgical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Wilford Hall Ambulatory Surgical Center (WHASC) on JBSA Lackland. Air Force outpatient surgical center serving active-duty and retiree TRICARE beneficiaries in San Antonio.",
    website_url: "https://wilfordhall.tricare.mil/",
    phone: "210-292-7331",
    address: "2200 Berquist Dr",
    city: "Lackland AFB", zip: "78236",
    eligibility: "Active-duty, retirees (TRICARE)",
    source_name: "WHASC official tricare.mil portal",
    source_type: "military",
  },
  {
    section: "MTF",
    title: "Carl R. Darnall Army Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Carl R. Darnall Army Medical Center on Fort Cavazos (formerly Fort Hood) in Killeen. Major Army hospital serving active-duty soldiers and TRICARE retirees in Central Texas.",
    website_url: "https://darnall.tricare.mil/",
    phone: "254-288-8000",
    address: "36000 Darnall Loop",
    city: "Fort Cavazos", zip: "76544",
    eligibility: "Active-duty, retirees (TRICARE)",
    source_name: "Carl R. Darnall AMC official tricare.mil portal",
    source_type: "military",
  },
  {
    section: "MTF",
    title: "William Beaumont Army Medical Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "William Beaumont Army Medical Center on Fort Bliss in El Paso. New facility opened 2021 replacing the historic 1972 hospital. Primary care, specialty care, and surgical services for active-duty and TRICARE beneficiaries.",
    website_url: "https://william-beaumont.tricare.mil/",
    phone: "915-742-2273",
    city: "El Paso",
    eligibility: "Active-duty, retirees (TRICARE)",
    source_name: "William Beaumont AMC official tricare.mil portal",
    source_type: "military",
  },

  // ============================================================
  // Section FH — Fisher Houses (free lodging for families during VA/DoD hospitalization) (7)
  // ============================================================
  {
    section: "FH",
    title: "Fisher Houses at Michael E. DeBakey VAMC Houston",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher Houses on the grounds of Michael E. DeBakey VAMC Houston providing free lodging for families of veterans receiving inpatient or extended outpatient care. Multiple suites; managed by the Fisher House Foundation in partnership with VA.",
    website_url: "https://fisherhouse.org/",
    city: "Houston",
    eligibility: "Families of veterans receiving care at MEDVAMC",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },
  {
    section: "FH",
    title: "Fisher Houses at JBSA Fort Sam Houston",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher Houses on JBSA Fort Sam Houston providing free lodging for families of military and veteran patients at Brooke Army Medical Center / SAMMC. One of the largest Fisher House complexes in the country (multiple suites).",
    website_url: "https://fisherhouse.org/",
    city: "Fort Sam Houston",
    eligibility: "Families of military/veteran patients at BAMC",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },
  {
    section: "FH",
    title: "Fisher House at Audie L. Murphy VAMC San Antonio",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher House on the grounds of Audie L. Murphy Memorial Veterans Hospital San Antonio providing free lodging for families of veterans receiving care at the South Texas Veterans Health Care System.",
    website_url: "https://fisherhouse.org/",
    city: "San Antonio",
    eligibility: "Families of veterans receiving care at Audie Murphy VAH",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },
  {
    section: "FH",
    title: "Fisher House at JBSA Lackland",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher House on JBSA Lackland near Wilford Hall Ambulatory Surgical Center providing free lodging for families of patients at WHASC and other Lackland medical facilities.",
    website_url: "https://fisherhouse.org/",
    city: "Lackland AFB",
    eligibility: "Families of military/veteran patients at WHASC",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },
  {
    section: "FH",
    title: "Fisher Houses at William Beaumont AMC El Paso",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher Houses on Fort Bliss serving families of patients at the new William Beaumont Army Medical Center. Free lodging for active-duty and veteran families.",
    website_url: "https://fisherhouse.org/",
    city: "El Paso",
    eligibility: "Families of military/veteran patients at WBAMC",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },
  {
    section: "FH",
    title: "Fisher House at Carl R. Darnall AMC Fort Cavazos",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher House on Fort Cavazos serving families of patients at Carl R. Darnall Army Medical Center. Free lodging for active-duty and veteran families.",
    website_url: "https://fisherhouse.org/",
    city: "Fort Cavazos",
    eligibility: "Families of military/veteran patients at Darnall AMC",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },
  {
    section: "FH",
    title: "Fisher House at Dallas VA Medical Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "Fisher House on the grounds of Dallas VA Medical Center providing free lodging for families of veterans receiving care at the VA North Texas Health Care System.",
    website_url: "https://fisherhouse.org/",
    city: "Dallas",
    eligibility: "Families of veterans receiving care at Dallas VAMC",
    source_name: "Fisher House Foundation locations directory",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section SPEC — Specialty programs (Polytrauma + SCI + Naval Health) (3)
  // ============================================================
  {
    section: "SPEC",
    title: "Houston Polytrauma Network Site at DeBakey VAMC",
    cat: "healthcare", sub: "Specialty Care",
    desc: "VA Polytrauma Network Site at Michael E. DeBakey VAMC Houston serving veterans and active-duty service members with traumatic brain injury, blast injuries, and complex multi-system trauma. One of the regional polytrauma hubs.",
    website_url: "https://www.polytrauma.va.gov/",
    city: "Houston",
    eligibility: "Veterans with TBI / polytrauma referrals",
    source_name: "VA Polytrauma System of Care",
    source_type: "va_facility",
  },
  {
    section: "SPEC",
    title: "Houston Spinal Cord Injury Center at DeBakey VAMC",
    cat: "healthcare", sub: "Specialty Care",
    desc: "VA Spinal Cord Injury Center at Michael E. DeBakey VAMC Houston serving veterans with spinal cord injury and disorders across the South Central VA region. Inpatient SCI care, rehabilitation, and lifetime management.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Houston",
    eligibility: "Veterans with SCI/D",
    source_name: "VA.gov Houston SCI Center program page",
    source_type: "va_facility",
  },
  {
    section: "SPEC",
    title: "Naval Health Clinic Corpus Christi",
    cat: "healthcare", sub: "Primary Care",
    desc: "Naval Health Clinic Corpus Christi (NHCCC) on Naval Air Station Corpus Christi. Primary care and limited specialty care for active-duty Navy/Marines, retirees (TRICARE), and family members. Serves transitioning veterans of NAS Corpus Christi.",
    website_url: "https://www.cnic.navy.mil/regions/cnrse/installations/nas_corpus_christi.html",
    city: "Corpus Christi",
    eligibility: "Active-duty, retirees (TRICARE) at NAS Corpus Christi",
    source_name: "Navy CNIC NAS Corpus Christi installation page",
    source_type: "military",
  },

  // ============================================================
  // Section VBA — Veterans Benefits Administration Regional Offices (2)
  // ============================================================
  {
    section: "VBA",
    title: "VA Regional Office Houston",
    cat: "va-benefits", sub: "VA Enrollment Help",
    desc: "VA Houston Regional Office (VBA) processing disability compensation, pension, education, and survivor benefits claims for Houston-area and Southeast Texas veterans. Includes the Houston Regional Loan Center serving the entire VA loan guaranty for Texas.",
    website_url: "https://benefits.va.gov/houston/",
    phone: "1-800-827-1000",
    address: "6900 Almeda Rd",
    city: "Houston", zip: "77030",
    eligibility: "All Texas veterans filing VA benefits claims (Houston jurisdiction)",
    source_name: "VBA Houston Regional Office page",
    source_type: "va_facility",
  },
  {
    section: "VBA",
    title: "VA Regional Office Waco",
    cat: "va-benefits", sub: "VA Enrollment Help",
    desc: "VA Waco Regional Office (VBA) — the larger of the two Texas VBA Regional Offices. Processes disability compensation, pension, vocational rehab, education (Hazlewood/GI Bill), and survivor benefits claims for veterans across most of Texas (excluding Houston jurisdiction).",
    website_url: "https://benefits.va.gov/waco/",
    phone: "1-800-827-1000",
    address: "1 Veterans Plaza, 701 Clay Ave",
    city: "Waco", zip: "76799",
    eligibility: "All Texas veterans filing VA benefits claims (Waco jurisdiction)",
    source_name: "VBA Waco Regional Office page",
    source_type: "va_facility",
  },

  // ============================================================
  // Section CGS — VA Caregiver Support Program (per HCS) (8)
  // ============================================================
  {
    section: "CGS",
    title: "Houston DeBakey VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at Michael E. DeBakey VAMC Houston. Coordinator helps caregivers of post-9/11 and other eligible veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Houston",
    eligibility: "Caregivers of eligible veterans served by Houston VA HCS",
    source_name: "VA.gov Caregiver Support Program — Houston",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "North Texas VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at VA North Texas Health Care System (Dallas/Bonham). Coordinator helps caregivers of eligible veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Dallas",
    eligibility: "Caregivers of eligible veterans served by VA North Texas HCS",
    source_name: "VA.gov Caregiver Support Program — North Texas",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "South Texas VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at VA South Texas Veterans Health Care System (San Antonio/Kerrville). Coordinator helps caregivers of eligible veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "San Antonio",
    eligibility: "Caregivers of eligible veterans served by VA South Texas HCS",
    source_name: "VA.gov Caregiver Support Program — South Texas",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "Central Texas VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at VA Central Texas Veterans HCS (Temple/Waco/Austin). Coordinator helps caregivers of eligible veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Temple",
    eligibility: "Caregivers of eligible veterans served by VA Central Texas HCS",
    source_name: "VA.gov Caregiver Support Program — Central Texas",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "Amarillo VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at Amarillo VA Health Care System. Coordinator helps caregivers of eligible Texas Panhandle veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/amarillo-health-care/",
    city: "Amarillo",
    eligibility: "Caregivers of eligible veterans served by Amarillo VA HCS",
    source_name: "VA.gov Caregiver Support Program — Amarillo",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "West Texas VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at West Texas VA Health Care System (Big Spring). Coordinator helps caregivers of eligible Permian Basin veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Big Spring",
    eligibility: "Caregivers of eligible veterans served by West Texas VA HCS",
    source_name: "VA.gov Caregiver Support Program — West Texas",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "El Paso VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at El Paso VA Health Care System. Coordinator helps caregivers of eligible El Paso / Southern NM veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/el-paso-health-care/",
    city: "El Paso",
    eligibility: "Caregivers of eligible veterans served by El Paso VA HCS",
    source_name: "VA.gov Caregiver Support Program — El Paso",
    source_type: "va_facility",
  },
  {
    section: "CGS",
    title: "Valley Coastal Bend VA Caregiver Support Program",
    cat: "family-support", sub: "Caregiver Support",
    desc: "VA Caregiver Support Program at VA Texas Valley Coastal Bend Health Care System (Harlingen). Coordinator helps caregivers of eligible Rio Grande Valley / Coastal Bend veterans access PCAFC stipend, respite care, education, and peer support.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    city: "Harlingen",
    eligibility: "Caregivers of eligible veterans served by Valley Coastal Bend HCS",
    source_name: "VA.gov Caregiver Support Program — Valley Coastal Bend",
    source_type: "va_facility",
  },

  // ============================================================
  // Section WVP — VA Women Veterans Program (per HCS) (8)
  // ============================================================
  {
    section: "WVP",
    title: "Houston DeBakey VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at Michael E. DeBakey VAMC Houston. Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for Houston-area women veterans.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Houston",
    eligibility: "Women veterans served by Houston VA HCS",
    source_name: "VA.gov Women Veterans Program — Houston",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "North Texas VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at VA North Texas Health Care System. Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for DFW women veterans.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Dallas",
    eligibility: "Women veterans served by VA North Texas HCS",
    source_name: "VA.gov Women Veterans Program — North Texas",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "South Texas VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at VA South Texas Veterans Health Care System (San Antonio). Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for South Texas women veterans.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "San Antonio",
    eligibility: "Women veterans served by VA South Texas HCS",
    source_name: "VA.gov Women Veterans Program — South Texas",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "Central Texas VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at VA Central Texas Veterans HCS (Temple/Waco/Austin). Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Temple",
    eligibility: "Women veterans served by VA Central Texas HCS",
    source_name: "VA.gov Women Veterans Program — Central Texas",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "Amarillo VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at Amarillo VA Health Care System. Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for Texas Panhandle women veterans.",
    website_url: "https://www.va.gov/amarillo-health-care/",
    city: "Amarillo",
    eligibility: "Women veterans served by Amarillo VA HCS",
    source_name: "VA.gov Women Veterans Program — Amarillo",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "West Texas VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at West Texas VA Health Care System (Big Spring). Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for Permian Basin women veterans.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Big Spring",
    eligibility: "Women veterans served by West Texas VA HCS",
    source_name: "VA.gov Women Veterans Program — West Texas",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "El Paso VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at El Paso VA Health Care System. Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for El Paso / Southern NM women veterans.",
    website_url: "https://www.va.gov/el-paso-health-care/",
    city: "El Paso",
    eligibility: "Women veterans served by El Paso VA HCS",
    source_name: "VA.gov Women Veterans Program — El Paso",
    source_type: "va_facility",
  },
  {
    section: "WVP",
    title: "Valley Coastal Bend VA Women Veterans Program",
    cat: "healthcare", sub: "Women Veterans Healthcare",
    desc: "VA Women Veterans Program Manager at VA Texas Valley Coastal Bend Health Care System (Harlingen). Coordinates comprehensive primary care, gynecology, maternity care coordination, MST counseling referrals, and women-focused outreach for RGV women veterans.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    city: "Harlingen",
    eligibility: "Women veterans served by Valley Coastal Bend HCS",
    source_name: "VA.gov Women Veterans Program — Valley Coastal Bend",
    source_type: "va_facility",
  },

  // ============================================================
  // Section HVA — VA HUD-VASH Coordinators (per HCS) (8)
  // ============================================================
  {
    section: "HVA",
    title: "Houston DeBakey VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at Michael E. DeBakey VAMC Houston. Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless Houston-area veterans.",
    website_url: "https://www.va.gov/houston-health-care/",
    city: "Houston",
    eligibility: "Homeless veterans referred from Houston VA HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — Houston",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "North Texas VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at VA North Texas Health Care System. Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless DFW veterans.",
    website_url: "https://www.va.gov/north-texas-health-care/",
    city: "Dallas",
    eligibility: "Homeless veterans referred from VA North Texas HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — North Texas",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "South Texas VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at VA South Texas Veterans Health Care System (San Antonio). Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless Bexar County veterans.",
    website_url: "https://www.va.gov/south-texas-health-care/",
    city: "San Antonio",
    eligibility: "Homeless veterans referred from VA South Texas HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — South Texas",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "Central Texas VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at VA Central Texas Veterans HCS (Austin/Temple/Waco). Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless Central Texas veterans.",
    website_url: "https://www.va.gov/central-texas-health-care/",
    city: "Austin",
    eligibility: "Homeless veterans referred from VA Central Texas HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — Central Texas",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "Amarillo VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at Amarillo VA Health Care System. Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless Texas Panhandle veterans.",
    website_url: "https://www.va.gov/amarillo-health-care/",
    city: "Amarillo",
    eligibility: "Homeless veterans referred from Amarillo VA HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — Amarillo",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "West Texas VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at West Texas VA Health Care System (Big Spring). Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless Permian Basin veterans.",
    website_url: "https://www.va.gov/west-texas-health-care/",
    city: "Big Spring",
    eligibility: "Homeless veterans referred from West Texas VA HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — West Texas",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "El Paso VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at El Paso VA Health Care System. Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless El Paso veterans.",
    website_url: "https://www.va.gov/el-paso-health-care/",
    city: "El Paso",
    eligibility: "Homeless veterans referred from El Paso VA HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — El Paso",
    source_type: "va_facility",
  },
  {
    section: "HVA",
    title: "Valley Coastal Bend VA HUD-VASH Program",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "VA HUD-VASH Program at VA Texas Valley Coastal Bend Health Care System (Harlingen). Pairs HUD-issued housing-choice vouchers with VA case management and clinical services for chronically homeless RGV / Coastal Bend veterans.",
    website_url: "https://www.va.gov/find-locations/facility/vha_740",
    city: "Harlingen",
    eligibility: "Homeless veterans referred from Valley Coastal Bend HCS HUD-VASH program",
    source_name: "VA.gov HUD-VASH Program — Valley Coastal Bend",
    source_type: "va_facility",
  },
];

runSeed(ROWS, {
  state: "TX",
  commit: COMMIT,
  allowBrokenUrls: ALLOW_BROKEN_URLS,
  allowZipBleed: ALLOW_ZIP_BLEED,
  batchLabel: "TX Phase 1 — Batch 2 (VAMC + CBOCs + Vet Centers + MTF + Fisher House + NCA + VBA + Specialty + Caregiver + Women Vet + HUD-VASH)",
  sectionLabels: {
    HCS: "VA Health Care System parents",
    VAMC: "VA Medical Centers",
    VC: "Vet Centers (Readjustment Counseling)",
    CBOC_H: "Houston-area CBOCs",
    CBOC_N: "North Texas CBOCs",
    CBOC_C: "Central Texas CBOCs",
    CBOC_S: "South Texas CBOCs",
    CBOC_W: "West Texas CBOCs",
    CBOC_E: "El Paso area CBOCs",
    CBOC_VCB: "Valley Coastal Bend CBOCs",
    CBOC_AMA: "Amarillo system CBOCs",
    DOM: "VA Domiciliary residential rehab",
    NCA: "VA National Cemeteries",
    MTF: "Military Treatment Facilities",
    FH: "Fisher Houses",
    SPEC: "Specialty programs (Polytrauma + SCI + NHCCC)",
    VBA: "VBA Regional Offices",
    CGS: "VA Caregiver Support Programs",
    WVP: "VA Women Veterans Programs",
    HVA: "VA HUD-VASH Programs",
  },
}).catch((e) => {
  console.error(e);
  process.exit(1);
});
