/**
 * Texas ROUND 2 — Phase 2: Deeper Healthcare / Clinics / Systems (Florida SOP)
 * Mainstream + veteran-friendly: LMHAs, FQHCs, major hospital systems, additional CBOCs.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  // LMHA — Local Mental Health Authorities (statewide ADMH-equivalent network)
  { section: "LMHA", title: "The Harris Center for Mental Health and IDD", cat: "mental-health", sub: "Counseling & Therapy", city: "Houston", website_url: "https://www.theharriscenter.org/", source_name: "The Harris Center for Mental Health and IDD", source_type: "lmha", phone: "713-970-7000", desc: "Harris County's Local Mental Health Authority — Texas's largest LMHA — operating 80+ outpatient locations, NeuroPsychiatric Center, and crisis services across Harris County. Free / sliding-fee mental-health, IDD, and SUD services with veteran-priority intake at all sites." },
  { section: "LMHA", title: "MHMR Tarrant County", cat: "mental-health", sub: "Counseling & Therapy", city: "Fort Worth", website_url: "https://www.mhmrtarrant.org/", source_name: "MHMR of Tarrant County", source_type: "lmha", phone: "817-569-4300", desc: "Tarrant County's Local Mental Health Authority operating outpatient mental-health, IDD, SUD, and early-childhood intervention services across 50+ sites. Crisis Hotline (817-335-3022), Mobile Crisis Outreach Team, and dedicated Veteran Peer Service Coordinator embedded with TVC." },
  { section: "LMHA", title: "Bluebonnet Trails Community Services", cat: "mental-health", sub: "Counseling & Therapy", city: "Round Rock", website_url: "https://bbtrails.org/", source_name: "Bluebonnet Trails Community Services", source_type: "lmha", phone: "844-309-6385", desc: "8-county LMHA serving Williamson, Bastrop, Burnet, Caldwell, Fayette, Gonzales, Guadalupe, and Lee counties. Outpatient mental-health, IDD, SUD, crisis hotline, and Mobile Crisis Outreach with TVC Veteran Peer Service Coordinators." },
  { section: "LMHA", title: "Spindletop Center", cat: "mental-health", sub: "Counseling & Therapy", city: "Beaumont", website_url: "https://www.spindletopcenter.org/", source_name: "Spindletop Center", source_type: "lmha", phone: "409-839-1000", desc: "Southeast Texas LMHA serving Jefferson, Hardin, Orange, and Chambers counties (Beaumont/Port Arthur). Outpatient MH/IDD/SUD services, 24/7 crisis line (409-839-1010), MCOT, Veteran Peer Service Coordinator, and Vet One Stop in Beaumont." },
  { section: "LMHA", title: "Tropical Texas Behavioral Health", cat: "mental-health", sub: "Counseling & Therapy", city: "Edinburg", website_url: "https://www.ttbh.org/", source_name: "Tropical Texas Behavioral Health", source_type: "lmha", phone: "956-289-7000", desc: "Rio Grande Valley LMHA serving Hidalgo, Cameron, and Willacy counties. Outpatient MH/IDD/SUD across 30+ RGV sites; 24/7 crisis line (877-289-7199), MCOT, bilingual Spanish/English services, and TVC Veteran Peer Service Coordinator coverage." },
  { section: "LMHA", title: "Border Region Behavioral Health Center", cat: "mental-health", sub: "Counseling & Therapy", city: "Laredo", website_url: "https://www.borderregion.org/", source_name: "Border Region Behavioral Health Center", source_type: "lmha", phone: "956-794-3000", desc: "South Texas LMHA serving Webb, Zapata, and Jim Hogg counties (Laredo region). Bilingual outpatient MH/IDD/SUD, 24/7 crisis line (800-643-1102), MCOT, and TVC Veteran Peer Service Coordinator embedded for the Laredo veteran community." },
  { section: "LMHA", title: "Hill Country MHDD Centers", cat: "mental-health", sub: "Counseling & Therapy", city: "Kerrville", website_url: "https://www.hillcountry.org/", source_name: "Hill Country Mental Health and Developmental Disabilities Centers", source_type: "lmha", phone: "830-792-3300", desc: "19-county Hill Country / South Central Texas LMHA serving Bandera, Blanco, Comal, Edwards, Gillespie, Guadalupe (shared), Hays, Kendall, Kerr, Kimble, Llano, Mason, Medina, Menard, Real, Schleicher, Sutton, Uvalde, and Val Verde counties. 24/7 crisis line 877-466-0660." },
  { section: "LMHA", title: "PermiaCare (Permian Basin Community Centers)", cat: "mental-health", sub: "Counseling & Therapy", city: "Midland", website_url: "https://www.permiacare.org/", source_name: "PermiaCare", source_type: "lmha", phone: "432-570-3300", desc: "5-county Permian Basin LMHA serving Andrews, Crane, Ector, Martin, and Midland counties. Outpatient MH/IDD/SUD, 24/7 crisis line (844-420-3964), MCOT, jail diversion, and TVC Veteran Peer Service Coordinator coverage for Midland-Odessa." },
  { section: "LMHA", title: "Heart of Texas Region MHMR", cat: "mental-health", sub: "Counseling & Therapy", city: "Waco", website_url: "https://hotrmhmr.org/", source_name: "Heart of Texas Region MHMR Center", source_type: "lmha", phone: "254-752-3451", desc: "6-county Central Texas LMHA serving Bosque, Falls, Freestone, Hill, Limestone, and McLennan counties (Waco). Outpatient MH/IDD/SUD, 24/7 crisis line (866-752-3451), MCOT, and TVC Veteran Peer Service Coordinator for Waco-area veterans." },
  { section: "LMHA", title: "Texana Center", cat: "mental-health", sub: "Counseling & Therapy", city: "Rosenberg", website_url: "https://www.texanacenter.com/", source_name: "Texana Center", source_type: "lmha", phone: "281-239-1300", desc: "6-county LMHA serving Fort Bend, Austin, Colorado, Matagorda, Waller, and Wharton counties (southwest of Houston). Outpatient MH/IDD/SUD, 24/7 crisis line (800-633-5686), MCOT, and Behavioral Health Center of Excellence in Rosenberg." },

  // FQHC — Federally Qualified Health Centers
  { section: "FQHC", title: "Hope Clinic", cat: "healthcare", sub: "Primary Care", city: "Houston", website_url: "https://www.hopechc.org/", source_name: "Hope Clinic", source_type: "fqhc", phone: "713-773-0803", address: "7001 Corporate Dr, Houston, TX 77036", zip: "77036", desc: "Houston FQHC serving Asian American and Pacific Islander communities and all uninsured/underinsured Houstonians. Primary care, OB/GYN, pediatrics, dental, behavioral health, and pharmacy at sliding-fee scale; multilingual services in 17 Asian languages plus Spanish." },
  { section: "FQHC", title: "Avenue 360 Health & Wellness", cat: "healthcare", sub: "Primary Care", city: "Houston", website_url: "https://avenue360.org/", source_name: "Avenue 360 Health & Wellness", source_type: "fqhc", phone: "713-426-0027", desc: "Houston FQHC operating 8 clinic sites across Greater Houston with primary care, HIV care (Ryan White), behavioral health, dental, and pharmacy services. Sliding-fee scale; specialty care for veterans, LGBTQ+ populations, and people experiencing homelessness." },
  { section: "FQHC", title: "Vecino Health Centers", cat: "healthcare", sub: "Primary Care", city: "Houston", website_url: "https://vecinohealthcenters.org/", source_name: "Vecino Health Centers", source_type: "fqhc", phone: "713-225-7000", desc: "Houston FQHC operating Denver Harbor Family Clinic and Airline Children's Clinic in north and east Houston. Bilingual primary care, pediatrics, OB/GYN, behavioral health, dental, and pharmacy at sliding-fee scale for predominantly Hispanic/immigrant communities." },
  { section: "FQHC", title: "Healing Hands Ministries", cat: "healthcare", sub: "Primary Care", city: "Dallas", website_url: "https://www.healinghandsministries.org/", source_name: "Healing Hands Ministries", source_type: "fqhc", phone: "214-221-2964", desc: "Dallas FQHC providing primary care, women's health, pediatrics, behavioral health, and dental services on sliding-fee scale at three Dallas sites. Faith-based mission serving uninsured and underinsured Dallasites including refugees and veterans." },
  { section: "FQHC", title: "Los Barrios Unidos Community Clinic", cat: "healthcare", sub: "Primary Care", city: "Dallas", website_url: "https://www.lbuclinic.org/", source_name: "Los Barrios Unidos Community Clinic", source_type: "fqhc", phone: "214-540-0300", desc: "West Dallas FQHC since 1972 serving primarily Hispanic, low-income, uninsured Dallas residents. Bilingual primary care, OB/GYN, pediatrics, dental, behavioral health, optometry, and pharmacy across 6 clinic sites at sliding-fee scale." },
  { section: "FQHC", title: "CommUnityCare Health Centers", cat: "healthcare", sub: "Primary Care", city: "Austin", website_url: "https://communitycaretx.org/", source_name: "CommUnityCare Health Centers", source_type: "fqhc", phone: "512-978-9015", desc: "Travis County's largest FQHC operating 30+ clinic sites across Austin and Travis County with primary care, pediatrics, OB/GYN, behavioral health, dental, HIV care, and pharmacy at sliding-fee scale. Anchor partner with the Travis County Healthcare District." },
  { section: "FQHC", title: "Lone Star Circle of Care", cat: "healthcare", sub: "Primary Care", city: "Georgetown", website_url: "https://www.lonestarcares.org/", source_name: "Lone Star Circle of Care", source_type: "fqhc", phone: "877-800-5722", desc: "Central Texas FQHC operating 23+ clinic sites across Williamson, Bell, Travis, Hays, and Burnet counties. Primary care, pediatrics, OB/GYN, behavioral health, dental, and pharmacy at sliding-fee scale; veteran-friendly intake at all locations." },
  { section: "FQHC", title: "CommuniCare Health Centers", cat: "healthcare", sub: "Primary Care", city: "San Antonio", website_url: "https://communicaresa.org/", source_name: "CommuniCare Health Centers", source_type: "fqhc", phone: "210-233-7000", desc: "San Antonio's largest FQHC operating 25+ clinic sites across Bexar, Hays, and Kendall counties. Bilingual primary care, OB/GYN, pediatrics, behavioral health, dental, optometry, and 340B pharmacy at sliding-fee scale; HRSA Quality Health Center recognition." },
  { section: "FQHC", title: "CentroMed", cat: "healthcare", sub: "Primary Care", city: "San Antonio", website_url: "https://www.centromedsa.com/", source_name: "Centro Med", source_type: "fqhc", phone: "210-922-7000", desc: "San Antonio FQHC operating 24 clinic sites across South and Southwest Bexar County. Bilingual primary care, pediatrics, OB/GYN, behavioral health, dental, and pharmacy at sliding-fee scale; partnerships with University Health and JBSA-Lackland for veteran care." },
  { section: "FQHC", title: "Centro de Salud Familiar La Fe", cat: "healthcare", sub: "Primary Care", city: "El Paso", website_url: "https://www.lafeelpaso.org/", source_name: "Centro de Salud Familiar La Fe", source_type: "fqhc", phone: "915-545-4550", desc: "South El Paso FQHC since 1967 serving the Segundo Barrio and surrounding El Paso/Fort Bliss communities. Bilingual primary care, pediatrics, OB/GYN, behavioral health, dental, and HIV care at sliding-fee scale across 8 clinic sites." },
  { section: "FQHC", title: "Su Clinica Familiar", cat: "healthcare", sub: "Primary Care", city: "Harlingen", website_url: "https://www.suclinica.org/", source_name: "Su Clinica Familiar", source_type: "fqhc", phone: "956-365-6000", desc: "Rio Grande Valley FQHC operating clinic sites in Harlingen, Brownsville, Raymondville, and Mercedes. Bilingual primary care, OB/GYN, pediatrics, behavioral health, dental, and pharmacy at sliding-fee scale across the Lower RGV." },
  { section: "FQHC", title: "Brownsville Community Health Center", cat: "healthcare", sub: "Primary Care", city: "Brownsville", website_url: "https://bchcweb.org/", source_name: "Brownsville Community Health Center", source_type: "fqhc", phone: "956-548-7400", desc: "Cameron County FQHC operating 6 clinic sites across Brownsville and Los Fresnos. Bilingual primary care, OB/GYN, pediatrics, behavioral health, dental, and pharmacy at sliding-fee scale; HRSA Quality Health Center recognition." },

  // HOSP — Major hospital systems veterans use (mainstream)
  { section: "HOSP", title: "Houston Methodist Hospital System", cat: "healthcare", sub: "Specialty Care", city: "Houston", website_url: "https://www.houstonmethodist.org/", source_name: "Houston Methodist", source_type: "hospital_system", phone: "713-790-3311", address: "6565 Fannin St, Houston, TX 77030", zip: "77030", desc: "Houston-area 8-hospital health system anchored by the flagship Texas Medical Center campus. U.S. News Best Hospitals nationally ranked in 11 specialties; partner with the DeBakey VAMC for cardiac surgery, neuro-oncology, transplant, and cancer referrals." },
  { section: "HOSP", title: "Memorial Hermann Health System", cat: "healthcare", sub: "Specialty Care", city: "Houston", website_url: "https://www.memorialhermann.org/", source_name: "Memorial Hermann Health System", source_type: "hospital_system", phone: "713-222-2273", desc: "Greater Houston's largest not-for-profit health system operating 17 hospitals plus the Red Duke Trauma Institute (Level I trauma) and the Mischer Neuroscience Institute. Major partner with UTHealth Houston; serves veteran emergent and trauma referrals from DeBakey VAMC." },
  { section: "HOSP", title: "MD Anderson Cancer Center", cat: "healthcare", sub: "Specialty Care", city: "Houston", website_url: "https://www.mdanderson.org/", source_name: "The University of Texas MD Anderson Cancer Center", source_type: "hospital", phone: "877-632-6789", address: "1515 Holcombe Blvd, Houston, TX 77030", zip: "77030", desc: "Nation's #1 cancer hospital (U.S. News). Comprehensive cancer center providing every modality of cancer care; major referral center for VA Choice / Community Care oncology referrals from across the Texas, Louisiana, Oklahoma, and Arkansas VA networks." },
  { section: "HOSP", title: "UT Southwestern Medical Center", cat: "healthcare", sub: "Specialty Care", city: "Dallas", website_url: "https://www.utsouthwestern.edu/", source_name: "University of Texas Southwestern Medical Center", source_type: "hospital_system", phone: "214-645-8300", address: "5323 Harry Hines Blvd, Dallas, TX 75390", zip: "75390", desc: "Dallas academic medical center anchored by William P. Clements Jr. University Hospital and Zale Lipshy. U.S. News Best Hospitals nationally ranked in 9 specialties; major affiliation with Dallas VA Medical Center for cardiothoracic surgery, neurosurgery, and oncology." },
  { section: "HOSP", title: "Parkland Health & Hospital System", cat: "healthcare", sub: "Specialty Care", city: "Dallas", website_url: "https://www.parklandhealth.org/", source_name: "Parkland Health", source_type: "hospital_system", phone: "214-590-8000", address: "5200 Harry Hines Blvd, Dallas, TX 75235", zip: "75235", desc: "Dallas County's public safety-net hospital — a Level I trauma center serving 1M+ patient visits annually with sliding-fee scale. Operates 20+ Community Oriented Primary Care (COPC) health centers across Dallas serving uninsured, low-income, and immigrant communities including veterans." },
  { section: "HOSP", title: "Methodist Health System Dallas", cat: "healthcare", sub: "Specialty Care", city: "Dallas", website_url: "https://www.methodisthealthsystem.org/", source_name: "Methodist Health System", source_type: "hospital_system", phone: "214-947-8181", desc: "North Texas not-for-profit health system operating 13 hospitals across DFW including the flagship Methodist Dallas Medical Center (Level I trauma). Major Dallas VAMC referral partner for transplant, cardiothoracic, and neurosurgical care." },
  { section: "HOSP", title: "Baylor Scott & White Health", cat: "healthcare", sub: "Specialty Care", city: "Dallas", website_url: "https://www.bswhealth.com/", source_name: "Baylor Scott & White Health", source_type: "hospital_system", phone: "844-279-3627", desc: "Texas's largest not-for-profit health system with 50+ hospitals across DFW, Central Texas, Waco, Temple, College Station, and Round Rock. Anchor of the Central Texas VA Healthcare System (CTVHCS Olin E. Teague VAMC) referral network in Temple-Killeen." },
  { section: "HOSP", title: "UT Health San Antonio", cat: "healthcare", sub: "Specialty Care", city: "San Antonio", website_url: "https://www.uthscsa.edu/", source_name: "University of Texas Health Science Center San Antonio", source_type: "hospital_system", phone: "210-450-9000", address: "7703 Floyd Curl Dr, San Antonio, TX 78229", zip: "78229", desc: "San Antonio academic medical center operating University Hospital (Bexar County's Level I trauma center via University Health) and the Mays Cancer Center. Major Audie L. Murphy VAMC affiliation for cardiothoracic surgery, transplant, and oncology." },
  { section: "HOSP", title: "Methodist Healthcare San Antonio", cat: "healthcare", sub: "Specialty Care", city: "San Antonio", website_url: "https://sahealth.com/", source_name: "Methodist Healthcare", source_type: "hospital_system", phone: "210-575-0500", desc: "San Antonio's largest healthcare system operating 9 hospitals including Methodist Hospital | Texsan, Methodist Children's, and Methodist Specialty & Transplant. Joint venture between HCA Healthcare and Methodist Healthcare Ministries; serves Audie L. Murphy VAMC referrals." },
  { section: "HOSP", title: "Ascension Seton", cat: "healthcare", sub: "Specialty Care", city: "Austin", website_url: "https://healthcare.ascension.org/locations/texas/txaus/austin-ascension-seton-medical-center-austin", source_name: "Ascension Seton", source_type: "hospital_system", phone: "512-324-1000", desc: "Central Texas faith-based health system operating Dell Seton Medical Center at UT (Level I trauma), Ascension Seton Medical Center Austin, and 10+ regional Ascension Seton hospitals across the Austin and Hill Country region. Major Austin VA Outpatient Clinic referral partner." },
  { section: "HOSP", title: "Texas Tech University Health Sciences Center", cat: "healthcare", sub: "Specialty Care", city: "Lubbock", website_url: "https://www.ttuhsc.edu/", source_name: "Texas Tech University Health Sciences Center", source_type: "hospital_system", phone: "806-743-2011", address: "3601 4th St, Lubbock, TX 79430", zip: "79430", desc: "West Texas academic medical center with campuses in Lubbock, Amarillo, El Paso (separated as TTUHSC EP), Odessa, and Abilene. Schools of medicine, pharmacy, nursing, and allied health; Lubbock VA Outpatient Clinic affiliation for primary care/specialty referrals." },
  { section: "HOSP", title: "Texas Tech University Health Sciences Center El Paso", cat: "healthcare", sub: "Specialty Care", city: "El Paso", website_url: "https://elpaso.ttuhsc.edu/", source_name: "Texas Tech University Health Sciences Center El Paso", source_type: "hospital_system", phone: "915-215-4000", address: "5001 El Paso Dr, El Paso, TX 79905", zip: "79905", desc: "El Paso academic medical center separated from TTUHSC Lubbock in 2013. Paul L. Foster School of Medicine, Hunt School of Nursing, and Hunt School of Dental Medicine; clinical affiliation with University Medical Center of El Paso (Level I trauma) and El Paso VA HCS." },

  // VA — Additional VA facilities not yet loaded
  { section: "VA", title: "VA Heart of Texas Health Care Network", cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation", city: "Arlington", website_url: "https://www.vha.va.gov/visn17/", source_name: "VA Heart of Texas Health Care Network (VISN 17)", source_type: "government", phone: "817-385-3700", desc: "VA's regional VISN 17 network office overseeing all VA medical centers and CBOCs across Texas (and Eastern Oklahoma): VA North Texas (Dallas), Central Texas (Temple-Killeen), South Texas (San Antonio), El Paso, Amarillo, West Texas (Big Spring), VA Texas Valley Coastal Bend, and DeBakey VAMC Houston." },
  { section: "VA", title: "VA Texas Valley Coastal Bend Health Care System", cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation", city: "Harlingen", website_url: "https://www.va.gov/texas-valley-coastal-bend-health-care/", source_name: "U.S. Department of Veterans Affairs", source_type: "vamc", phone: "956-291-9000", address: "2601 Veterans Dr, Harlingen, TX 78550", zip: "78550", desc: "VA health care system serving the Rio Grande Valley and Coastal Bend with primary care, mental health, and specialty referrals. Anchor outpatient clinic in Harlingen plus CBOCs in Brownsville, McAllen, Corpus Christi, Laredo, La Sara, and Rio Grande City." },
  { section: "VA", title: "VA West Texas Health Care System", cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation", city: "Big Spring", website_url: "https://www.va.gov/west-texas-health-care/", source_name: "U.S. Department of Veterans Affairs", source_type: "vamc", phone: "432-263-7361", address: "300 Veterans Blvd, Big Spring, TX 79720", zip: "79720", desc: "George H. O'Brien Jr. VA Medical Center in Big Spring serving West Texas with inpatient + outpatient primary care, mental health, surgery, and long-term care. CBOCs in Abilene, Stamford, San Angelo, Odessa, and Fort Stockton." },
];

console.log(`[seed-tx-r2-phase2] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "TX", commit: COMMIT, scriptName: "TX Round 2 — Phase 2: Deeper Healthcare",
  batchTag: "tx-r2-phase2", allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: { LMHA: "Local Mental Health Authorities", FQHC: "FQHCs (community health centers)", HOSP: "Major hospital systems veterans use", VA: "Additional VA facilities/network" },
}).catch((e) => { console.error(e); process.exit(1); });
