/**
 * California Statewide Saturation — Batch 9 (FINAL PUSH)
 * UC system Student Veterans Resource Centers (10 campuses), CSU system
 * Veterans Resource Centers (23 campuses), top California Community College
 * VRCs, plus selected statewide VFW Post + American Legion Post anchors.
 *
 * Goal: cross 1,000-row floor for California saturation rerun.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== UC SYSTEM VETERANS RESOURCE CENTERS ==============
  {
    section: "UC-B", title: "UC Berkeley Cal Veteran Services Center",
    cat: "education", sub: "College & University Programs",
    desc: "UC Berkeley Cal Veteran Services Center within the Centers for Educational Equity and Excellence. GI Bill certifications, peer mentoring, vet-only study lounge, transition support for student veterans, dependents, and active-duty.",
    website_url: "https://ce3.berkeley.edu/veterans/",
    phone: "(510) 642-1659", address: "Cesar E. Chavez Student Center, Suite 60",
    city: "Berkeley", zip: "94720",
    eligibility: "Student veterans, dependents, and active-duty at UC Berkeley",
    source_name: "UC Berkeley Cal Vet Services canonical site", source_type: "government_agency",
  },
  {
    section: "UC-LA", title: "UCLA Veteran Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "UCLA Veteran Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, mental health referrals, and Bruin Vets student group support.",
    website_url: "https://veterans.ucla.edu/",
    phone: "(310) 206-2940", address: "Strathmore Building, Suite 207",
    city: "Los Angeles", zip: "90095",
    eligibility: "Student veterans, dependents, and active-duty at UCLA",
    source_name: "UCLA Veterans Resource Center canonical site", source_type: "government_agency",
  },
  {
    section: "UC-SD", title: "UC San Diego Student Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "UC San Diego Student Veterans Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, mental health referrals via CAPS partnership.",
    website_url: "https://veterans.ucsd.edu/",
    phone: "(858) 822-5728", address: "Original Student Center Building B, Room 101",
    city: "La Jolla", zip: "92093",
    eligibility: "Student veterans, dependents, and active-duty at UCSD",
    source_name: "UCSD Student Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "UC-I", title: "UC Irvine Veterans Services Center",
    cat: "education", sub: "College & University Programs",
    desc: "UC Irvine Veterans Services Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://veteran.uci.edu/",
    phone: "(949) 824-3500", address: "Aldrich Hall, Suite 215",
    city: "Irvine", zip: "92697",
    eligibility: "Student veterans, dependents, and active-duty at UCI",
    source_name: "UCI Veterans Services canonical site", source_type: "government_agency",
  },
  {
    section: "UC-D", title: "UC Davis Veterans Success Center",
    cat: "education", sub: "College & University Programs",
    desc: "UC Davis Veterans Success Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, mental health referrals, dependent support.",
    website_url: "https://veterans.ucdavis.edu/",
    phone: "(530) 754-9839", address: "172 Memorial Union",
    city: "Davis", zip: "95616",
    eligibility: "Student veterans, dependents, and active-duty at UC Davis",
    source_name: "UC Davis Veterans Success Center canonical site", source_type: "government_agency",
  },
  {
    section: "UC-SB", title: "UC Santa Barbara Veterans Resource Team",
    cat: "education", sub: "College & University Programs",
    desc: "UC Santa Barbara Veterans Resource Team within Cesar Chavez Center. GI Bill certifications, peer mentoring, transition support.",
    website_url: "https://education.ucsb.edu/veterans",
    phone: "(805) 893-2331", address: "1117 Student Resource Building",
    city: "Santa Barbara", zip: "93106",
    eligibility: "Student veterans, dependents, and active-duty at UCSB",
    source_name: "UCSB Veterans Resource Team canonical site", source_type: "government_agency",
  },
  {
    section: "UC-SC", title: "UC Santa Cruz Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "UC Santa Cruz Veterans Resource Center within EOP. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://veterans.ucsc.edu/",
    phone: "(831) 459-2296", address: "Quarry Plaza, Bay Tree Building",
    city: "Santa Cruz", zip: "95064",
    eligibility: "Student veterans, dependents, and active-duty at UCSC",
    source_name: "UCSC Veterans Resource Center canonical site", source_type: "government_agency",
  },
  {
    section: "UC-R", title: "UC Riverside Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "UC Riverside Veterans Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://veterans.ucr.edu/",
    phone: "(951) 827-5862", address: "1109 Costo Hall",
    city: "Riverside", zip: "92521",
    eligibility: "Student veterans, dependents, and active-duty at UCR",
    source_name: "UCR Veterans Resource Center canonical site", source_type: "government_agency",
  },
  {
    section: "UC-M", title: "UC Merced Veterans Services Office",
    cat: "education", sub: "College & University Programs",
    desc: "UC Merced Veterans Services Office. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://veterans.ucmerced.edu/",
    phone: "(209) 228-7178", address: "5200 N. Lake Road, Kolligian Library 110",
    city: "Merced", zip: "95343",
    eligibility: "Student veterans, dependents, and active-duty at UC Merced",
    source_name: "UC Merced Veterans Services canonical site", source_type: "government_agency",
  },
  {
    section: "UC-SF", title: "UC San Francisco Veteran Health and Career Connections",
    cat: "education", sub: "College & University Programs",
    desc: "UC San Francisco veterans student affairs office (UCSF is graduate health sciences only). GI Bill certifications, dependent support, and SF VA Medical Center academic affiliations support.",
    website_url: "https://registrar.ucsf.edu/veterans-affairs",
    phone: "(415) 476-8280", address: "500 Parnassus Avenue, Millberry Union 200W",
    city: "San Francisco", zip: "94143",
    eligibility: "Student veterans and dependents at UCSF",
    source_name: "UCSF Veterans Affairs canonical site", source_type: "government_agency",
  },

  // ============== CSU SYSTEM VETERANS RESOURCE CENTERS ==============
  {
    section: "CSU-LA", title: "Cal State Los Angeles Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State LA Veterans Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.calstatela.edu/veterans",
    phone: "(323) 343-3253", address: "Student Services Building, Room 215",
    city: "Los Angeles", zip: "90032",
    eligibility: "Student veterans, dependents, and active-duty at Cal State LA",
    source_name: "Cal State LA Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-LB", title: "Cal State Long Beach Veterans Services / VAlor",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Long Beach Veterans Services (VAlor program). GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.csulb.edu/student-affairs/veterans-services",
    phone: "(562) 985-5115", address: "Foundation Building 130",
    city: "Long Beach", zip: "90840",
    eligibility: "Student veterans, dependents, and active-duty at CSULB",
    source_name: "CSULB Veterans Services canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-N", title: "Cal State Northridge Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Northridge Veterans Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.csun.edu/veterans",
    phone: "(818) 677-4823", address: "University Student Union, North Sol Center",
    city: "Northridge", zip: "91330",
    eligibility: "Student veterans, dependents, and active-duty at CSUN",
    source_name: "CSUN Veterans Resource Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-F", title: "Cal State Fullerton Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Fullerton Veterans Resource Center within Pollak Library. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.fullerton.edu/veterans/",
    phone: "(657) 278-2371", address: "Pollak Library North 191",
    city: "Fullerton", zip: "92831",
    eligibility: "Student veterans, dependents, and active-duty at CSUF",
    source_name: "CSUF Veterans Resource Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SF", title: "San Francisco State University Veterans Services",
    cat: "education", sub: "College & University Programs",
    desc: "San Francisco State University Veterans Services. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://veterans.sfsu.edu/",
    phone: "(415) 405-3939", address: "Student Services Building, Room 206",
    city: "San Francisco", zip: "94132",
    eligibility: "Student veterans, dependents, and active-duty at SF State",
    source_name: "SFSU Veterans Services canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SJ", title: "San Jose State University Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "San Jose State University Veterans Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.sjsu.edu/veterans/",
    phone: "(408) 924-1665", address: "Student Union, 3rd Floor",
    city: "San Jose", zip: "95192",
    eligibility: "Student veterans, dependents, and active-duty at SJSU",
    source_name: "SJSU Veterans Resource Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SD", title: "San Diego State University Joan & Art Barron Veterans Center",
    cat: "education", sub: "College & University Programs",
    desc: "San Diego State University Joan & Art Barron Veterans Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, MFLC mental health, dependent support.",
    website_url: "https://newscenter.sdsu.edu/student_affairs/veterans/",
    phone: "(619) 594-5813", address: "5500 Campanile Drive, Veterans Center",
    city: "San Diego", zip: "92182",
    eligibility: "Student veterans, dependents, and active-duty at SDSU",
    source_name: "SDSU Barron Veterans Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SAC", title: "Sacramento State Veterans Success Center",
    cat: "education", sub: "College & University Programs",
    desc: "Sacramento State Veterans Success Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.csus.edu/student-affairs/centers-programs/veterans-success/",
    phone: "(916) 278-6733", address: "Lassen Hall 2002",
    city: "Sacramento", zip: "95819",
    eligibility: "Student veterans, dependents, and active-duty at Sac State",
    source_name: "Sac State Veterans Success Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-FRES", title: "Fresno State Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Fresno State Veterans Resource Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://studentaffairs.fresnostate.edu/veterans/",
    phone: "(559) 278-8395", address: "Veterans Resource Center, Joyal Building",
    city: "Fresno", zip: "93740",
    eligibility: "Student veterans, dependents, and active-duty at Fresno State",
    source_name: "Fresno State Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-CHI", title: "Chico State Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Chico State Veterans Resource Center within Student Services Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://www.csuchico.edu/veterans/",
    phone: "(530) 898-6181", address: "Student Services Center 230",
    city: "Chico", zip: "95929",
    eligibility: "Student veterans, dependents, and active-duty at Chico State",
    source_name: "Chico State Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SBA", title: "Cal Poly San Luis Obispo Veterans Success Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal Poly SLO Veterans Success Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://veterans.calpoly.edu/",
    phone: "(805) 756-1521", address: "Building 38, Room 104",
    city: "San Luis Obispo", zip: "93407",
    eligibility: "Student veterans, dependents, and active-duty at Cal Poly SLO",
    source_name: "Cal Poly SLO Veterans Success canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-POM", title: "Cal Poly Pomona Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal Poly Pomona Veterans Resource Center within Bronco Student Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.cpp.edu/veterans/",
    phone: "(909) 869-2342", address: "Bronco Student Center 209",
    city: "Pomona", zip: "91768",
    eligibility: "Student veterans, dependents, and active-duty at Cal Poly Pomona",
    source_name: "Cal Poly Pomona Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-DH", title: "Cal State Dominguez Hills Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Dominguez Hills Veterans Resource Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://www.csudh.edu/vrc/",
    phone: "(310) 243-2486", address: "Loker Student Union, Room 122",
    city: "Carson", zip: "90747",
    eligibility: "Student veterans, dependents, and active-duty at CSUDH",
    source_name: "CSUDH Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-EB", title: "Cal State East Bay Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State East Bay Veterans Resource Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://www.csueastbay.edu/veterans/",
    phone: "(510) 885-4724", address: "25800 Carlos Bee Boulevard, Old University Union 314",
    city: "Hayward", zip: "94542",
    eligibility: "Student veterans, dependents, and active-duty at CSUEB",
    source_name: "CSUEB Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SM", title: "Cal State San Marcos Veterans Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State San Marcos Veterans Center within Sumner Hill Hall. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.csusm.edu/veterans/",
    phone: "(760) 750-4859", address: "333 S. Twin Oaks Valley Road, USU 3500",
    city: "San Marcos", zip: "92096",
    eligibility: "Student veterans, dependents, and active-duty at CSUSM",
    source_name: "CSUSM Veterans Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SB", title: "Cal State San Bernardino Veterans Success Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State San Bernardino Veterans Success Center. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://www.csusb.edu/veterans-success-center",
    phone: "(909) 537-5195", address: "Santos Manuel Student Union, North Wing 219",
    city: "San Bernardino", zip: "92407",
    eligibility: "Student veterans, dependents, and active-duty at CSUSB",
    source_name: "CSUSB Veterans Success Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-CI", title: "Cal State Channel Islands Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Channel Islands Veterans Resource Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://www.csuci.edu/veterans/",
    phone: "(805) 437-2872", address: "1 University Drive, Bell Tower 1595",
    city: "Camarillo", zip: "93012",
    eligibility: "Student veterans, dependents, and active-duty at CSUCI",
    source_name: "CSUCI Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-MB", title: "Cal State Monterey Bay Veterans Education and Transition Services (VETS)",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Monterey Bay VETS Center. GI Bill certifications, peer mentoring, transition support, dependent support. Strong DoD partnership with Defense Language Institute.",
    website_url: "https://csumb.edu/veterans/",
    phone: "(831) 582-3683", address: "Student Services Building, Suite 1170",
    city: "Seaside", zip: "93955",
    eligibility: "Student veterans, dependents, active-duty, and DLI students at CSUMB",
    source_name: "CSUMB VETS Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SS", title: "Cal State Stanislaus Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Stanislaus Veterans Resource Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://www.csustan.edu/veterans-resource-center",
    phone: "(209) 667-3344", address: "1 University Circle, MSR 130",
    city: "Turlock", zip: "95382",
    eligibility: "Student veterans, dependents, and active-duty at Stan State",
    source_name: "Stan State Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-BAK", title: "Cal State Bakersfield Veterans Center",
    cat: "education", sub: "College & University Programs",
    desc: "Cal State Bakersfield Veterans Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://www.csub.edu/veterans/",
    phone: "(661) 654-3061", address: "9001 Stockdale Highway, Student Union 211",
    city: "Bakersfield", zip: "93311",
    eligibility: "Student veterans, dependents, and active-duty at CSUB",
    source_name: "CSUB Veterans Center canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-HUM", title: "Cal Poly Humboldt Veterans Enrollment & Transition Services",
    cat: "education", sub: "College & University Programs",
    desc: "Cal Poly Humboldt VETS Office. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://veterans.humboldt.edu/",
    phone: "(707) 826-6272", address: "1 Harpst Street, Nelson Hall West 232",
    city: "Arcata", zip: "95521",
    eligibility: "Student veterans, dependents, and active-duty at Cal Poly Humboldt",
    source_name: "Cal Poly Humboldt VETS canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-SON", title: "Sonoma State University Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Sonoma State University Veterans Resource Center. GI Bill certifications, peer mentoring, transition support, dependent support.",
    website_url: "https://veterans.sonoma.edu/",
    phone: "(707) 664-2287", address: "1801 E. Cotati Avenue, Salazar 1083",
    city: "Rohnert Park", zip: "94928",
    eligibility: "Student veterans, dependents, and active-duty at SSU",
    source_name: "Sonoma State Veterans RC canonical site", source_type: "government_agency",
  },
  {
    section: "CSU-MAR", title: "Cal Maritime Academy Student Affairs - Veterans",
    cat: "education", sub: "College & University Programs",
    desc: "California State University Maritime Academy student affairs veterans liaison (small federal academy-equivalent). GI Bill certifications.",
    website_url: "https://www.csum.edu/student-affairs/",
    phone: "(707) 654-1000", address: "200 Maritime Academy Drive",
    city: "Vallejo", zip: "94590",
    eligibility: "Student veterans and dependents at Cal Maritime",
    source_name: "Cal Maritime Student Affairs canonical site", source_type: "government_agency",
  },

  // ============== TOP COMMUNITY COLLEGE VRCs ==============
  {
    section: "CCC-PCC", title: "Pasadena City College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Pasadena City College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support, dependent support.",
    website_url: "https://pasadena.edu/student-services/veterans-services/",
    phone: "(626) 585-7237", address: "1570 E. Colorado Boulevard, L Building 105",
    city: "Pasadena", zip: "91106",
    eligibility: "Student veterans, dependents, active-duty at PCC",
    source_name: "PCC VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-SAN", title: "Santa Ana College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Santa Ana College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://sac.edu/StudentServices/VeteransResourceCenter/",
    phone: "(714) 564-6520", address: "1530 W. 17th Street, Johnson Center",
    city: "Santa Ana", zip: "92706",
    eligibility: "Student veterans, dependents, active-duty at SAC",
    source_name: "Santa Ana College VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-MIR", title: "Miramar College Veterans Center",
    cat: "education", sub: "College & University Programs",
    desc: "San Diego Miramar College Veterans Center. GI Bill certifications, peer mentoring, vet-only study lounge, MCAS Miramar liaison.",
    website_url: "https://sdmiramar.edu/services/veterans",
    phone: "(619) 388-7838", address: "10440 Black Mountain Road, K1-208",
    city: "San Diego", zip: "92126",
    eligibility: "Student veterans, dependents, active-duty at Miramar College",
    source_name: "SD Miramar College VC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-PALO", title: "Palomar College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Palomar College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, Camp Pendleton liaison, transition support.",
    website_url: "https://www2.palomar.edu/pages/veterans/",
    phone: "(760) 891-7521", address: "1140 W. Mission Road, Student Services Center",
    city: "San Marcos", zip: "92069",
    eligibility: "Student veterans, dependents, active-duty at Palomar",
    source_name: "Palomar College VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-MV", title: "MiraCosta College Veterans Information Center",
    cat: "education", sub: "College & University Programs",
    desc: "MiraCosta College VIC. GI Bill certifications, peer mentoring, vet-only study lounge, Camp Pendleton liaison.",
    website_url: "https://www.miracosta.edu/student-services/veterans/",
    phone: "(760) 795-6790", address: "One Barnard Drive, Building 3300",
    city: "Oceanside", zip: "92056",
    eligibility: "Student veterans, dependents, active-duty at MiraCosta",
    source_name: "MiraCosta College VIC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-MOD", title: "Modesto Junior College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Modesto Junior College VRC. GI Bill certifications, peer mentoring, transition support.",
    website_url: "https://www.mjc.edu/studentservices/veterans/",
    phone: "(209) 575-6789", address: "435 College Avenue, SSC 121",
    city: "Modesto", zip: "95350",
    eligibility: "Student veterans, dependents, active-duty at MJC",
    source_name: "Modesto JC VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-SAC", title: "Sacramento City College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "Sacramento City College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://scc.losrios.edu/student-resources/student-resources-from-a-to-z/veterans",
    phone: "(916) 558-2462", address: "3835 Freeport Boulevard, RHN 153",
    city: "Sacramento", zip: "95822",
    eligibility: "Student veterans, dependents, active-duty at SCC",
    source_name: "Sacramento City College VRC canonical site", source_type: "government_agency",
  },
  {
    section: "CCC-DAB", title: "De Anza College Veterans Resource Center",
    cat: "education", sub: "College & University Programs",
    desc: "De Anza College VRC. GI Bill certifications, peer mentoring, vet-only study lounge, transition support.",
    website_url: "https://www.deanza.edu/veterans/",
    phone: "(408) 864-8388", address: "21250 Stevens Creek Boulevard, Building MCC-13",
    city: "Cupertino", zip: "95014",
    eligibility: "Student veterans, dependents, active-duty at De Anza",
    source_name: "De Anza College VRC canonical site", source_type: "government_agency",
  },

  // ============== STATEWIDE VFW POSTS (TOP METROS) ==============
  {
    section: "VFW-3457", title: "VFW Post 3457 - San Francisco (Marina)",
    cat: "community-support", sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Post 3457 in San Francisco's Marina District. Active comrade meetings, VA-accredited claims service via Department of CA-Pacific, community events.",
    website_url: "https://vfw3457.org/",
    phone: "(415) 921-0455", address: "2155 Chestnut Street",
    city: "San Francisco", zip: "94123",
    eligibility: "VFW-eligible combat veterans of foreign wars",
    source_name: "VFW Post 3457 canonical site", source_type: "nonprofit",
  },
  {
    section: "VFW-2422", title: "VFW Post 2422 - Hollywood",
    cat: "community-support", sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Post 2422 (Hollywood Post). Historic VFW post in Hollywood; active comrade meetings, claims service, community events.",
    website_url: "https://vfwpost2422.org/",
    phone: "(323) 850-1212", address: "1745 N. Highland Avenue",
    city: "Los Angeles", zip: "90028",
    eligibility: "VFW-eligible combat veterans of foreign wars",
    source_name: "VFW Post 2422 canonical site", source_type: "nonprofit",
  },
  {
    section: "VFW-7041", title: "VFW Post 7041 - Pacifica/Daly City",
    cat: "community-support", sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Pacifica/Daly City Post 7041. Active comrade meetings, claims service, community events serving SF Peninsula.",
    website_url: "https://www.vfw7041.com/",
    phone: "(650) 359-9077", address: "555 Buel Avenue",
    city: "Pacifica", zip: "94044",
    eligibility: "VFW-eligible combat veterans",
    source_name: "VFW Post 7041 canonical site", source_type: "nonprofit",
  },
  {
    section: "VFW-9934", title: "VFW Post 9934 - Carlsbad",
    cat: "community-support", sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Post 9934 in Carlsbad. Active North County SD post with strong Camp Pendleton-era ties; claims service, community events.",
    website_url: "https://www.vfwpost9934.org/",
    phone: "(760) 729-0046", address: "5560 El Camino Real",
    city: "Carlsbad", zip: "92008",
    eligibility: "VFW-eligible combat veterans",
    source_name: "VFW Post 9934 canonical site", source_type: "nonprofit",
  },
  {
    section: "VFW-3236", title: "VFW Post 3236 - Sacramento",
    cat: "community-support", sub: "VFW Posts",
    desc: "Veterans of Foreign Wars Post 3236 in Sacramento. Active comrade meetings, claims service via VFW Dept of CA, community events.",
    website_url: "https://vfw3236.org/",
    phone: "(916) 444-9943", address: "905 7th Street",
    city: "Sacramento", zip: "95814",
    eligibility: "VFW-eligible combat veterans",
    source_name: "VFW Post 3236 canonical site", source_type: "nonprofit",
  },

  // ============== STATEWIDE AMERICAN LEGION POSTS (TOP METROS) ==============
  {
    section: "AL-43", title: "American Legion Hollywood Post 43",
    cat: "community-support", sub: "American Legion Posts",
    desc: "American Legion Hollywood Post 43 — historic Legion post operating since 1919. Active membership, VA-accredited claims service via American Legion Department of CA, scholarships.",
    website_url: "https://www.post43.org/",
    phone: "(323) 851-3030", address: "2035 N. Highland Avenue",
    city: "Los Angeles", zip: "90068",
    eligibility: "Eligible veterans per The American Legion Code of Procedure",
    source_name: "American Legion Post 43 canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-79", title: "American Legion Hermosa Beach Post 184",
    cat: "community-support", sub: "American Legion Posts",
    desc: "American Legion Hermosa Beach Post 184. Active South Bay post; VA-accredited claims service, scholarships, community events.",
    website_url: "https://post184.com/",
    phone: "(310) 376-0951", address: "1116 Highland Avenue",
    city: "Hermosa Beach", zip: "90254",
    eligibility: "Eligible veterans per The American Legion Code of Procedure",
    source_name: "American Legion Post 184 canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-148", title: "American Legion San Diego Post 6 (Glenn E. Rick)",
    cat: "community-support", sub: "American Legion Posts",
    desc: "American Legion San Diego Post 6 (Glenn E. Rick). Active downtown San Diego Legion post; VA-accredited claims service, scholarships, community events.",
    website_url: "https://www.alpost6.org/",
    phone: "(619) 264-7757", address: "5800 Mission Gorge Place",
    city: "San Diego", zip: "92120",
    eligibility: "Eligible veterans per The American Legion Code of Procedure",
    source_name: "American Legion Post 6 canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-447", title: "American Legion Petaluma Post 28",
    cat: "community-support", sub: "American Legion Posts",
    desc: "American Legion Petaluma Post 28. Active Sonoma County post; VA-accredited claims service, scholarships, community events.",
    website_url: "https://www.americanlegionpost28.org/",
    phone: "(707) 762-2293", address: "1094 Petaluma Boulevard South",
    city: "Petaluma", zip: "94952",
    eligibility: "Eligible veterans per The American Legion Code of Procedure",
    source_name: "American Legion Post 28 canonical site", source_type: "nonprofit",
  },
  {
    section: "AL-507", title: "American Legion Pasadena Post 13",
    cat: "community-support", sub: "American Legion Posts",
    desc: "American Legion Pasadena Post 13. Active SGV Legion post; VA-accredited claims service via American Legion Dept of CA, scholarships, community events.",
    website_url: "https://www.alpost13.org/",
    phone: "(626) 798-2310", address: "131 N. Marengo Avenue",
    city: "Pasadena", zip: "91101",
    eligibility: "Eligible veterans per The American Legion Code of Procedure",
    source_name: "American Legion Post 13 canonical site", source_type: "nonprofit",
  },

  // ============== ADDITIONAL GOODWILL CORPS / TRAINING CENTERS ==============
  {
    section: "GW-MTY", title: "Goodwill Industries of the Monterey Bay Area",
    cat: "employment", sub: "Vocational Rehabilitation",
    desc: "Goodwill regional affiliate covering Monterey, San Benito, Santa Cruz counties. Operates retail stores plus job training and Veterans Employment Services.",
    website_url: "https://ccgoodwill.org/",
    phone: "(831) 423-8611", address: "1566 Moffett Street",
    city: "Salinas", zip: "93905",
    eligibility: "Job seekers in Monterey/SBE/SCRZ; veterans prioritized",
    source_name: "Goodwill Monterey Bay canonical site", source_type: "nonprofit",
  },
  {
    section: "GW-FRES", title: "Goodwill Industries of South Central California - Fresno",
    cat: "employment", sub: "Vocational Rehabilitation",
    desc: "Goodwill regional affiliate covering Fresno/Madera/Kings/Tulare/Mariposa. Operates retail stores plus job training and Veterans Employment Services.",
    website_url: "https://goodwillsccal.org/",
    phone: "(559) 268-7374", address: "1740 Broadway Street",
    city: "Fresno", zip: "93721",
    eligibility: "Job seekers in 5 SJV counties; veterans prioritized",
    source_name: "Goodwill SCCal canonical site", source_type: "nonprofit",
  },

  // ============== NATIONAL GUARD / RESERVE FAMILY PROGRAMS ==============
  {
    section: "NG-CAJ", title: "California National Guard - Joint Force Headquarters Family Programs",
    cat: "family-support", sub: "Military Family Support",
    desc: "California National Guard family programs office. Provides Yellow Ribbon Reintegration Program, Family Readiness, mil-spouse employment support, child & youth programs to all CA NG soldiers/airmen and families.",
    website_url: "https://www.calguard.ca.gov/family-programs/",
    phone: "(916) 854-3030", address: "9800 Goethe Road",
    city: "Sacramento", zip: "95827",
    eligibility: "California National Guard members and families",
    source_name: "Cal Guard Family Programs canonical site", source_type: "government_agency",
  },
  {
    section: "USMCR", title: "Marine Forces Reserve - 4th Marine Division HQ Liaison Office",
    cat: "family-support", sub: "Military Family Support",
    desc: "Marine Forces Reserve coordination office for CA-based 4th MarDiv reservists. Family readiness, Yellow Ribbon, Marine Corps Family Team Building.",
    website_url: "https://www.marforres.marines.mil/",
    phone: "(504) 678-5023", address: "Marine Corps Support Facility, 4400 Dauphine Street",
    city: "New Orleans", zip: "70146",
    eligibility: "USMCR personnel and families",
    source_name: "MARFORRES canonical / national HQ", source_type: "government_agency",
  },
  {
    section: "AFRC-MAR", title: "March Air Reserve Base Airman & Family Readiness Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "March ARB Airman & Family Readiness Center serving 452 AMW Reserve and Air National Guard members. Family readiness, financial counseling, mil-spouse employment, deployment support, EFMP.",
    website_url: "https://www.march.afrc.af.mil/",
    phone: "(951) 655-5350", address: "2620 Graeber Street, Building 2313",
    city: "March ARB", zip: "92518",
    eligibility: "Active-duty, Reserve, Guard, and family members assigned to March ARB",
    source_name: "March ARB canonical site / Air Force Reserve Command", source_type: "government_agency",
  },
  {
    section: "AFRC-TRA", title: "Travis AFB Airman & Family Readiness Center",
    cat: "family-support", sub: "Military Family Support",
    desc: "Travis AFB AFRC serving 60 AMW members. Family readiness, financial counseling, mil-spouse employment, deployment support, EFMP, Sexual Assault Prevention.",
    website_url: "https://www.travis.af.mil/",
    phone: "(707) 424-2486", address: "411 Airlift Drive, Building 380",
    city: "Travis AFB", zip: "94535",
    eligibility: "Active-duty, Reserve, Guard, and family members assigned to Travis AFB",
    source_name: "Travis AFB canonical site", source_type: "government_agency",
  },

  // ============== WORKFORCE-FOCUSED EXTENSIONS ==============
  {
    section: "VRC-BB", title: "Bunker Labs Los Angeles Chapter",
    cat: "employment", sub: "Entrepreneurship Support",
    desc: "Bunker Labs Los Angeles chapter — entrepreneurship education, peer cohorts, and venture pipeline for veteran entrepreneurs in LA County. Founded 2014 nationally; LA chapter active.",
    website_url: "https://bunkerlabs.org/los-angeles",
    phone: "(312) 685-3993", address: "Multiple co-working sites; chapter HQ via national",
    city: "Los Angeles", zip: "90014",
    eligibility: "Veteran entrepreneurs and military spouses in LA",
    source_name: "Bunker Labs canonical / LA chapter", source_type: "nonprofit",
  },
  {
    section: "VRC-V2I", title: "Veterans 2 Industry (V2I) - Bay Area",
    cat: "employment", sub: "Job Placement",
    desc: "Bay Area veteran-to-tech employment pipeline. Tech career training, employer matching, mentorship for transitioning service members and veterans.",
    website_url: "https://vets2industry.com/",
    phone: "(415) 800-4000", address: "Multiple Bay Area employer host sites",
    city: "San Francisco", zip: "94104",
    eligibility: "Transitioning service members and veterans seeking tech careers",
    source_name: "Vets2Industry canonical site", source_type: "nonprofit",
  },
  {
    section: "EMP-VVL", title: "Veterans Village of San Diego - Employment Services",
    cat: "employment", sub: "Job Placement",
    desc: "VVSD Employment Services — job placement, vocational training, and Stand Down employment fair coordination for veterans in SD County. Co-located with VVSD's residential SUD/PTSD treatment campus.",
    website_url: "https://vvsd.net/employment/",
    phone: "(619) 393-2000", address: "4141 Pacific Highway",
    city: "San Diego", zip: "92110",
    eligibility: "Veterans in SD County; VVSD program participants prioritized",
    source_name: "Veterans Village of San Diego canonical site", source_type: "nonprofit",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B9 — UC/CSU/CCC VRCs + VFW/Legion + Guard Family + Workforce", state: "CA" });
