/**
 * Texas Phase 4 — Major Metros depth fill
 *
 * Strict 6-Phase Florida SOP (locked 2026-04-26):
 *   - 20-min hard cap
 *   - Skip blockers instantly
 *   - 90-95% practical > 99.9% perfect
 *   - High-ROI categories only: housing / food / employment / legal /
 *     community-support (healthcare already strong at 72 rows)
 *
 * Target metros: DFW (Dallas + Fort Worth + suburbs) / Houston / San Antonio /
 * Austin / El Paso. Rows are nationally- or regionally-known orgs whose
 * canonical landing pages and phone numbers are stable and well-documented.
 * Sources: each org's official .org / .gov / system website (no third-party
 * directories, no findglocal-style aggregators).
 */

import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");
const ALLOW_ZIP_BLEED = process.argv.includes("--allow-zip-bleed");

const ROWS: SeedRow[] = [
  // ============================================================
  // DFW — Dallas / Fort Worth / suburbs
  // ============================================================
  { section: "DFW", title: "Family Endeavors Veterans Services Dallas", cat: "housing", sub: "Homeless Veteran Services", city: "Dallas", website_url: "https://endeavors.org/veterans/", source_name: "Endeavors — Veterans & Military Family Services", source_type: "nonprofit", phone: "210-431-6466", desc: "Endeavors operates SSVF (Supportive Services for Veteran Families), HUD-VASH wraparound, and rapid-rehousing services in the Dallas-Fort Worth metro. National HQ in San Antonio; regional Veterans Services case-management offices serve North Texas veterans facing or experiencing homelessness." },
  { section: "DFW", title: "Family Endeavors Veterans Services Fort Worth", cat: "housing", sub: "Homeless Veteran Services", city: "Fort Worth", website_url: "https://endeavors.org/veterans/", source_name: "Endeavors — Veterans & Military Family Services", source_type: "nonprofit", phone: "210-431-6466", desc: "Endeavors' Tarrant County SSVF and Veteran Wellness case-management program. Provides rental assistance, utility help, security-deposit support, and connections to VA HUD-VASH for at-risk and homeless Fort Worth-area veterans." },
  // DROPPED 2026-04-26 P4: The Bridge Homeless Recovery Center — HEAD timeout in dry-run; skip-and-continue per founder rule.
  { section: "DFW", title: "North Texas Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Plano", website_url: "https://ntfb.org/", source_name: "North Texas Food Bank", source_type: "nonprofit", phone: "972-292-7500", address: "3677 Mapleshade Ln, Plano, TX 75075", zip: "75075", desc: "Member of Feeding America serving 13 North Texas counties (Dallas, Collin, Denton, and surrounding). Distributes through 500+ partner agencies including pantries that prioritize veterans and military families. Operates SNAP outreach and senior commodity programs." },
  { section: "DFW", title: "Tarrant Area Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Fort Worth", website_url: "https://tafb.org/", source_name: "Tarrant Area Food Bank", source_type: "nonprofit", phone: "817-857-7100", address: "2600 Cullen St, Fort Worth, TX 76107", zip: "76107", desc: "Feeding America member feeding 13 counties across Tarrant and surrounding North Texas. Operates Mobile Pantries, the Community Kitchen, SNAP outreach, and partners with Tarrant County veteran-serving nonprofits including Family Endeavors and Tarrant Area Veteran Council." },
  { section: "DFW", title: "Workforce Solutions Greater Dallas", cat: "employment", sub: "DVOP / Workforce Programs", city: "Dallas", website_url: "https://www.wfsdallas.com/", source_name: "Workforce Solutions Greater Dallas", source_type: "workforce_board", phone: "214-290-1000", desc: "Dallas County workforce development board operating Texas Workforce Commission Workforce Solutions Career Centers across Dallas County. DVOP/LVER staff give priority of service to veterans, transitioning service members, and eligible spouses for employment, training, and support services." },
  { section: "DFW", title: "Workforce Solutions for Tarrant County", cat: "employment", sub: "DVOP / Workforce Programs", city: "Fort Worth", website_url: "https://www.workforcesolutions.net/", source_name: "Workforce Solutions for Tarrant County", source_type: "workforce_board", phone: "817-413-4000", desc: "Tarrant County workforce development board operating Workforce Solutions Career Centers in Fort Worth, Arlington, Grapevine, and surrounding cities. DVOP/LVER veteran employment representatives provide priority-of-service career counseling, hiring events, and apprenticeship navigation." },
  // DROPPED 2026-04-26 P4: SER-Jobs for Progress National Dallas — HEAD timeout in dry-run; Houston entry retained as canonical regional presence.
  { section: "DFW", title: "Legal Aid of NorthWest Texas Dallas Office", cat: "legal", sub: "Legal Aid Services", city: "Dallas", website_url: "https://www.lanwt.org/", source_name: "Legal Aid of NorthWest Texas", source_type: "legal_aid", phone: "888-529-5277", desc: "LANWT serves 114 counties in north and west Texas including Dallas. Free civil legal aid for low-income clients with priority intake for veterans through the Equal Justice Veterans Center, including discharge upgrades, VA benefits appeals, family law, housing, and consumer cases." },
  { section: "DFW", title: "Legal Aid of NorthWest Texas Fort Worth Office", cat: "legal", sub: "Legal Aid Services", city: "Fort Worth", website_url: "https://www.lanwt.org/", source_name: "Legal Aid of NorthWest Texas", source_type: "legal_aid", phone: "817-336-3943", desc: "LANWT Fort Worth branch covering Tarrant and surrounding counties. Free civil legal services for income-qualified residents with veterans-priority intake through the Equal Justice Veterans Center: VA appeals, housing, family law, and discharge-upgrade representation." },
  { section: "DFW", title: "Allies in Service", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Dallas", website_url: "https://alliesinservice.org/", source_name: "Allies in Service", source_type: "nonprofit", phone: "214-238-7236", desc: "Dallas-based veteran nonprofit connecting veterans, transitioning service members, and military spouses to employment, education, healthcare, and housing partners across DFW. Operates a peer-navigator model that warm-hands-off to vetted community providers rather than duplicating services." },
  { section: "DFW", title: "Honor Flight DFW", cat: "community-support", sub: "Events, Trips & Retreats", city: "Dallas", website_url: "https://www.honorflightdfw.org/", source_name: "Honor Flight DFW", source_type: "nonprofit", desc: "DFW-area hub of the national Honor Flight Network. Flies WWII, Korean War, Vietnam, and terminally ill veterans of all eras to Washington, D.C. at no cost to visit their war memorials. Operates from Dallas Love Field and DFW International with volunteer guardians." },

  // ============================================================
  // HOU — Houston metro + Galveston
  // ============================================================
  { section: "HOU", title: "New Hope Housing", cat: "housing", sub: "Transitional Housing", city: "Houston", website_url: "https://newhopehousing.com/", source_name: "New Hope Housing", source_type: "nonprofit", phone: "713-942-9696", desc: "Houston's largest provider of permanent supportive single-room-occupancy housing for low-income working adults including a substantial veteran population. Eight apartment communities across Houston with on-site supportive services and direct VA HUD-VASH coordination." },
  { section: "HOU", title: "SEARCH Homeless Services Houston", cat: "housing", sub: "Homeless Veteran Services", city: "Houston", website_url: "https://www.searchhomeless.org/", source_name: "SEARCH Homeless Services", source_type: "nonprofit", phone: "713-739-7752", address: "2015 Congress St, Houston, TX 77002", zip: "77002", desc: "Houston's largest homeless-services provider operating day shelter, case management, employment services, and rapid rehousing. Designated VA SSVF subgrantee serving veterans and veteran families across the Houston/Harris County Continuum of Care (The Way Home)." },
  { section: "HOU", title: "Star of Hope Mission Houston", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "Houston", website_url: "https://www.sohmission.org/", source_name: "Star of Hope Mission", source_type: "nonprofit", phone: "713-748-0700", desc: "Houston's largest emergency-shelter system, operating men's, women's, and family campuses. Coordinates with Michael E. DeBakey VAMC HUD-VASH and Endeavors SSVF for veteran-specific intake and rehousing. Faith-based but accepts all clients regardless of faith." },
  { section: "HOU", title: "Houston Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Houston", website_url: "https://www.houstonfoodbank.org/", source_name: "Houston Food Bank", source_type: "nonprofit", phone: "832-369-9390", address: "535 Portwall St, Houston, TX 77029", zip: "77029", desc: "America's largest Feeding America food bank by distribution, serving 18 southeast Texas counties through 1,500+ partner agencies. Veteran-priority intake at multiple partner pantries; SNAP application assistance; senior food box program; mobile pantry events at VA-affiliated sites." },
  // DROPPED 2026-04-26 P4: Galveston County Food Bank — intermittent HEAD timeout in commit run; skip-and-continue.
  { section: "HOU", title: "Workforce Solutions Gulf Coast", cat: "employment", sub: "DVOP / Workforce Programs", city: "Houston", website_url: "https://www.wrksolutions.com/", source_name: "Workforce Solutions — Gulf Coast Workforce Board", source_type: "workforce_board", phone: "888-469-5627", desc: "Workforce development board for the 13-county Houston-Galveston region operating Texas Workforce Commission Career Centers across Greater Houston. DVOP/LVER staff give priority of service to veterans, recently separated service members, and eligible spouses." },
  { section: "HOU", title: "SER-Jobs for Progress Houston", cat: "employment", sub: "Job Placement Programs", city: "Houston", website_url: "https://www.serhouston.org/", source_name: "SER-Jobs Houston", source_type: "nonprofit", phone: "713-773-6000", address: "1710 Telephone Rd, Houston, TX 77023", zip: "77023", desc: "Houston-headquartered workforce nonprofit founded out of the American GI Forum and LULAC. Provides job training, placement, financial coaching, and youth career programs with a long history of serving veterans, military spouses, and underemployed workers in southeast Texas." },
  { section: "HOU", title: "Lone Star Legal Aid", cat: "legal", sub: "Legal Aid Services", city: "Houston", website_url: "https://www.lonestarlegal.org/", source_name: "Lone Star Legal Aid", source_type: "legal_aid", phone: "713-652-0077", address: "500 Jefferson St, Suite 960, Houston, TX 77002", zip: "77002", desc: "Free civil legal aid covering 72 east-Texas counties from Houston headquarters. Operates the Equal Justice Veterans Initiative providing veterans with representation in VA disability and benefits appeals, discharge-upgrade petitions, family law, housing, and consumer matters." },
  { section: "HOU", title: "Houston Volunteer Lawyers", cat: "legal", sub: "Pro Bono Legal Services", city: "Houston", website_url: "https://www.makejusticehappen.org/", source_name: "Houston Volunteer Lawyers (Houston Bar Foundation)", source_type: "legal_aid", phone: "713-228-0735", desc: "Pro bono arm of the Houston Bar Association placing income-qualified clients with volunteer attorneys. Operates a Veterans Legal Initiative offering free civil-legal clinics at Michael E. DeBakey VAMC, U.S. Vets Houston, and the Lone Star Veterans Association." },
  { section: "HOU", title: "Lone Star Veterans Association", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Houston", website_url: "https://lonestarveterans.org/", source_name: "Lone Star Veterans Association", source_type: "nonprofit", phone: "832-203-7233", desc: "Houston-based post-9/11 veteran membership and peer-network organization with 12,000+ members. Operates peer-mentorship, employment connections, family programming, and large social events that anchor the post-9/11 veteran community across Greater Houston." },
  { section: "HOU", title: "PTSD Foundation of America — Camp Hope", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "Houston", website_url: "https://www.ptsdusa.org/", source_name: "PTSD Foundation of America", source_type: "nonprofit", phone: "877-717-7873", desc: "Houston-headquartered nonprofit operating Camp Hope, a long-term peer-driven interim housing program for combat veterans with PTSD. Free 6-9 month residential program with mentorship by combat-veteran graduates; warm referrals from VA and community providers nationwide." },
  // DROPPED 2026-04-26 P4: Galveston County Coalition for Justice for Veterans — DNS fail in dry-run; skip-and-continue per founder rule.

  // ============================================================
  // SA — San Antonio metro
  // ============================================================
  { section: "SA", title: "Haven for Hope", cat: "housing", sub: "Emergency Housing / Homeless Shelters", city: "San Antonio", website_url: "https://www.havenforhope.org/", source_name: "Haven for Hope of Bexar County", source_type: "nonprofit", phone: "210-220-2100", address: "1 Haven for Hope Way, San Antonio, TX 78207", zip: "78207", desc: "San Antonio's transformational homeless-services campus, the largest in Texas. 22-acre campus offering emergency shelter, transitional housing, and 100+ on-site partner services. Direct coordination with Audie L. Murphy VAMC HUD-VASH and Endeavors SSVF for veteran-specific case management." },
  { section: "SA", title: "Endeavors National Headquarters", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "San Antonio", website_url: "https://endeavors.org/", source_name: "Endeavors", source_type: "nonprofit", phone: "210-431-6466", address: "535 Bandera Rd, San Antonio, TX 78228", zip: "78228", desc: "San Antonio-headquartered national nonprofit (founded 1969) serving veterans, military families, refugees, and disaster survivors. Operates SSVF, HUD-VASH wraparound, Veteran Wellness clinics, and Operation Veterans Connect across Texas, the Gulf Coast, and 11+ other states." },
  { section: "SA", title: "American GI Forum National Headquarters", cat: "community-support", sub: "Veteran Service Organizations", city: "San Antonio", website_url: "https://www.agifusa.org/", source_name: "American GI Forum of the United States", source_type: "vso", phone: "210-927-1932", desc: "Congressionally chartered Hispanic-American veterans organization founded in 1948 by Dr. Hector P. Garcia. National HQ in San Antonio; chapters across Texas and 22+ states advocate for veterans' civil rights, healthcare, education, and benefits with peer-to-peer claims navigation." },
  { section: "SA", title: "Soldiers' Angels National Headquarters", cat: "community-support", sub: "Veteran Nonprofit Organizations", city: "San Antonio", website_url: "https://soldiersangels.org/", source_name: "Soldiers' Angels", source_type: "nonprofit", phone: "210-629-0020", address: "2895 NE Loop 410, Suite 107, San Antonio, TX 78218", zip: "78218", desc: "San Antonio-headquartered national nonprofit supporting deployed service members, wounded warriors, veterans, and military families through letter-writing, care packages, the Veteran Mobile Food Distribution program at Audie L. Murphy VAMC, and the Veteran Family Support program." },
  { section: "SA", title: "San Antonio Food Bank", cat: "food-assistance", sub: "Food Banks", city: "San Antonio", website_url: "https://safoodbank.org/", source_name: "San Antonio Food Bank", source_type: "nonprofit", phone: "210-337-3663", address: "5200 Enrique M Barrera Pkwy, San Antonio, TX 78227", zip: "78227", desc: "Feeding America member serving 29 counties across Southwest Texas through 500+ partner agencies. Operates a Veteran Mobile Food Distribution at Audie L. Murphy VAMC, SNAP application assistance, and the Veterans Pantry Co-op partnership with Soldiers' Angels." },
  { section: "SA", title: "Workforce Solutions Alamo", cat: "employment", sub: "DVOP / Workforce Programs", city: "San Antonio", website_url: "https://www.workforcesolutionsalamo.org/", source_name: "Workforce Solutions Alamo", source_type: "workforce_board", phone: "210-272-3260", desc: "Workforce development board for the 13-county Alamo region operating Texas Workforce Commission Career Centers across San Antonio and South Central Texas. DVOP/LVER veteran employment representatives provide priority of service for job seekers and transitioning service members from JBSA." },
  { section: "SA", title: "Texas RioGrande Legal Aid San Antonio Office", cat: "legal", sub: "Legal Aid Services", city: "San Antonio", website_url: "https://www.trla.org/", source_name: "Texas RioGrande Legal Aid", source_type: "legal_aid", phone: "210-212-3700", address: "1111 N Main Ave, San Antonio, TX 78212", zip: "78212", desc: "TRLA serves 68 southwestern Texas counties from San Antonio HQ. Free civil legal services for low-income residents with veteran-priority intake including discharge upgrades, VA appeals, military divorce, USERRA, foreclosure, and consumer protection." },
  { section: "SA", title: "Patriots' Casa at Texas A&M-San Antonio", cat: "community-support", sub: "Veteran Outreach Programs", city: "San Antonio", website_url: "https://www.tamusa.edu/patriots-casa/", source_name: "Texas A&M University-San Antonio — Patriots' Casa", source_type: "university", phone: "210-784-1379", address: "One University Way, San Antonio, TX 78224", zip: "78224", desc: "Dedicated 16,000 sq ft veteran and military center on the Texas A&M-San Antonio campus serving the largest concentration of student veterans in South Texas. VITA tax prep, peer mentorship, claims navigation, and academic-support services for veterans, dependents, and Gold Star families." },

  // ============================================================
  // AUS — Austin metro
  // ============================================================
  { section: "AUS", title: "Caritas of Austin", cat: "housing", sub: "Homeless Veteran Services", city: "Austin", website_url: "https://caritasofaustin.org/", source_name: "Caritas of Austin", source_type: "nonprofit", phone: "512-479-4610", address: "611 Neches St, Austin, TX 78701", zip: "78701", desc: "Austin's largest provider of permanent supportive housing and rapid-rehousing programs. Designated VA SSVF subgrantee serving veterans and veteran families across the Austin/Travis County Continuum of Care. Operates Best Single Source Plus financial coaching and case management." },
  { section: "AUS", title: "LifeWorks Austin", cat: "housing", sub: "Transitional Housing", city: "Austin", website_url: "https://www.lifeworksaustin.org/", source_name: "LifeWorks", source_type: "nonprofit", phone: "512-735-2400", address: "835 N Pleasant Valley Rd, Austin, TX 78702", zip: "78702", desc: "Austin-based nonprofit providing housing, counseling, education, and workforce services to youth and young families experiencing homelessness, including young veterans and military-connected youth aging out of dependent benefits." },
  { section: "AUS", title: "Central Texas Food Bank", cat: "food-assistance", sub: "Food Banks", city: "Austin", website_url: "https://www.centraltexasfoodbank.org/", source_name: "Central Texas Food Bank", source_type: "nonprofit", phone: "512-282-2111", address: "6500 Metropolis Dr, Austin, TX 78744", zip: "78744", desc: "Feeding America member serving 21 Central Texas counties through 250+ partner agencies. Operates Veterans Mobile Pantry at the Austin VA Outpatient Clinic and partner pantries near Fort Cavazos and Camp Mabry. SNAP outreach and senior commodity distribution included." },
  { section: "AUS", title: "Workforce Solutions Capital Area", cat: "employment", sub: "DVOP / Workforce Programs", city: "Austin", website_url: "https://www.wfscapitalarea.com/", source_name: "Workforce Solutions Capital Area Workforce Board", source_type: "workforce_board", phone: "512-597-7100", desc: "Travis County workforce development board operating Texas Workforce Commission Career Centers across Austin and the Capital Area. DVOP/LVER staff provide priority of service to veterans, transitioning service members, and eligible spouses for employment, training, and apprenticeship navigation." },
  { section: "AUS", title: "Texas Legal Services Center", cat: "legal", sub: "Legal Aid Services", city: "Austin", website_url: "https://www.tlsc.org/", source_name: "Texas Legal Services Center", source_type: "legal_aid", phone: "512-477-6000", address: "2101 IH-35 South, Suite 300, Austin, TX 78741", zip: "78741", desc: "Statewide legal-services nonprofit providing free civil legal aid and operating specialized statewide projects including the Veterans Legal Assistance Project (VA appeals, discharge upgrades, healthcare access) and the Crime Victims Civil Legal Assistance Project." },
  { section: "AUS", title: "Honor Flight Austin", cat: "community-support", sub: "Events, Trips & Retreats", city: "Austin", website_url: "https://honorflightaustin.org/", source_name: "Honor Flight Austin", source_type: "nonprofit", desc: "Austin-area hub of the national Honor Flight Network. Flies Central Texas WWII, Korean War, Vietnam, and terminally ill veterans of all eras to Washington, D.C. at no cost to visit their war memorials. Operates from Austin-Bergstrom International with volunteer guardians." },
  // DROPPED 2026-04-26 P4: Texas Veterans Network — DNS fail in dry-run; Combined Arms parent already in DB.
  { section: "AUS", title: "Austin Bar Association Veterans Legal Assistance Program", cat: "legal", sub: "Pro Bono Legal Services", city: "Austin", website_url: "https://www.austinbar.org/", source_name: "Austin Bar Association", source_type: "legal_aid", phone: "512-472-0279", desc: "Austin Bar Association pro bono program placing low-income veterans with volunteer attorneys for civil legal needs. Hosts monthly veteran legal advice clinics in coordination with the Austin VA Outpatient Clinic and Texas Legal Services Center." },

  // ============================================================
  // EP — El Paso metro
  // ============================================================
  // DROPPED 2026-04-26 P4: Opportunity Center for the Homeless — DNS fail in dry-run; skip-and-continue.
  // DROPPED 2026-04-26 P4: Rescue Mission of El Paso — DNS fail in dry-run; skip-and-continue.
  { section: "EP", title: "El Pasoans Fighting Hunger Food Bank", cat: "food-assistance", sub: "Food Banks", city: "El Paso", website_url: "https://elpasoansfightinghunger.org/", source_name: "El Pasoans Fighting Hunger Food Bank", source_type: "nonprofit", phone: "915-298-0353", address: "9541 Plaza Cir, El Paso, TX 79927", zip: "79927", desc: "Feeding America member serving El Paso, Hudspeth, and Culberson counties through 150+ partner agencies. Distributes 100M+ pounds of food annually with Veterans Mobile Pantry distributions at the El Paso VA HCS and Fort Bliss-area community sites." },
  { section: "EP", title: "Workforce Solutions Borderplex", cat: "employment", sub: "DVOP / Workforce Programs", city: "El Paso", website_url: "https://www.borderplexjobs.com/", source_name: "Workforce Solutions Borderplex", source_type: "workforce_board", phone: "915-887-2600", desc: "Workforce development board for El Paso, Hudspeth, and Culberson counties operating Texas Workforce Commission Career Centers across the El Paso region. DVOP/LVER veteran employment representatives provide priority of service for veterans and Fort Bliss transitioning service members." },
  { section: "EP", title: "Texas RioGrande Legal Aid El Paso Office", cat: "legal", sub: "Legal Aid Services", city: "El Paso", website_url: "https://www.trla.org/", source_name: "Texas RioGrande Legal Aid", source_type: "legal_aid", phone: "915-585-5100", address: "1331 Texas Ave, El Paso, TX 79901", zip: "79901", desc: "TRLA's El Paso branch covering far-West Texas. Free civil legal services for low-income residents with veteran-priority intake: discharge upgrades, VA appeals, military divorce, USERRA employment cases, foreclosure prevention, and consumer protection." },
  { section: "EP", title: "American GI Forum El Paso Chapter", cat: "community-support", sub: "Veteran Service Organizations", city: "El Paso", website_url: "https://www.agifusa.org/", source_name: "American GI Forum of the United States — El Paso Chapter", source_type: "vso", desc: "El Paso chapter of the congressionally chartered Hispanic-American veterans organization founded by Dr. Hector P. Garcia. Provides peer claims navigation, civic engagement, scholarship advocacy, and community outreach across far-West Texas and Fort Bliss-connected veterans." },
  { section: "EP", title: "Project Vida Health Center — Veteran & Family Services", cat: "community-support", sub: "Veteran Outreach Programs", city: "El Paso", website_url: "https://projectvida.org/", source_name: "Project Vida Health Center", source_type: "nonprofit", phone: "915-533-7057", address: "3607 Rivera Ave, El Paso, TX 79905", zip: "79905", desc: "El Paso FQHC and community-services provider operating health, behavioral health, family-stability, and youth programs in the central El Paso corridor with a substantial military-connected client base from Fort Bliss-area neighborhoods." },
];

console.log(`[seed-tx-phase4] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);

runSeed(ROWS, {
  state: "TX",
  commit: COMMIT,
  scriptName: "TX Phase 4 — Major Metros (DFW/HOU/SA/AUS/EP)",
  batchTag: "tx-phase4",
  allowBrokenUrls: ALLOW_BROKEN_URLS,
  allowZipBleed: ALLOW_ZIP_BLEED,
  sectionLabels: {
    DFW: "Dallas-Fort Worth metroplex",
    HOU: "Houston metro + Galveston",
    SA: "San Antonio metro",
    AUS: "Austin metro",
    EP: "El Paso metro",
  },
}).catch((e) => {
  console.error(e);
  process.exit(1);
});
