/**
 * North Carolina Resources Seed — Round 2
 *
 * Deepens NC toward SC parity. Same pattern as round 1:
 * - Loads category UUIDs + subcategory IDs from live DB at runtime (no drift)
 * - Inserts into resources + resource_categories junction + resource_subcategories junction
 * - Dedupes by (title, state) — safe to re-run
 * - Service role client (bypasses RLS)
 *
 * Priorities (per founder Round 2 brief):
 *   - 30 more County VSOs (NC has 100 counties; round 1 covered top 29)
 *   - Housing / homeless / transitional expansion
 *   - Employment support
 *   - Legal services
 *   - Education / training
 *
 * Run: tsx scripts/seed-nc-resources-round2.ts
 */
import { supabaseAdmin } from "../server/supabase";

const STATE = "NC";

interface SeedResource {
  title: string;
  category_slug: string;
  subcategory_name?: string;
  short_description: string;
  website_url?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  zip?: string;
  latitude?: number;
  longitude?: number;
  eligibility?: string;
  source_name: string;
  source_type: "program" | "service" | "facility" | "nonprofit" | "government";
  status?: "approved" | "pending";
}

const NC_RESOURCES: SeedResource[] = [
  // ============================================================
  // VA BENEFITS — 30 additional County VSOs (counties 30-60)
  // ============================================================
  {
    title: "Alamance County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Burlington, Graham, and Alamance County veterans. VA claims and benefits assistance.",
    website_url: "https://www.alamance-nc.com/veterans/",
    phone: "336-570-6708",
    address: "319 N Graham-Hopedale Road",
    city: "Burlington",
    zip: "27217",
    latitude: 36.1135,
    longitude: -79.4197,
    source_name: "Alamance County Government",
    source_type: "government",
  },
  {
    title: "Pender County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Burgaw and Pender County veterans (coastal southeastern NC). VA claims assistance.",
    website_url: "https://www.pendercountync.gov/government/departments-i-z/veterans-services/",
    phone: "910-259-1474",
    address: "805 S Walker Street",
    city: "Burgaw",
    zip: "28425",
    latitude: 34.5524,
    longitude: -77.9264,
    source_name: "Pender County Government",
    source_type: "government",
  },
  {
    title: "Beaufort County Veterans Services (NC)",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Washington and Beaufort County veterans (eastern NC). VA claims and benefits guidance.",
    website_url: "https://www.co.beaufort.nc.us",
    phone: "252-940-6132",
    address: "121 W 3rd Street",
    city: "Washington",
    zip: "27889",
    latitude: 35.5460,
    longitude: -77.0521,
    source_name: "Beaufort County Government",
    source_type: "government",
  },
  {
    title: "Pasquotank County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Elizabeth City and Pasquotank County veterans (Coast Guard community). VA claims assistance.",
    website_url: "https://www.co.pasquotank.nc.us",
    phone: "252-338-4380",
    address: "200 E Colonial Avenue",
    city: "Elizabeth City",
    zip: "27909",
    latitude: 36.2946,
    longitude: -76.2511,
    source_name: "Pasquotank County Government",
    source_type: "government",
  },
  {
    title: "Granville County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Oxford and Granville County veterans. VA claims assistance.",
    website_url: "https://www.granvillecounty.org/government/veterans-services/",
    phone: "919-693-1484",
    address: "143 Williamsboro Street",
    city: "Oxford",
    zip: "27565",
    latitude: 36.3104,
    longitude: -78.5836,
    source_name: "Granville County Government",
    source_type: "government",
  },
  {
    title: "Stanly County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Albemarle and Stanly County veterans. VA claims and benefits guidance.",
    website_url: "https://www.stanlycountync.gov/veterans-services/",
    phone: "704-986-3674",
    address: "1000 N 1st Street",
    city: "Albemarle",
    zip: "28001",
    latitude: 35.3501,
    longitude: -80.2001,
    source_name: "Stanly County Government",
    source_type: "government",
  },
  {
    title: "Burke County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Morganton and Burke County veterans. VA claims and benefits assistance.",
    website_url: "https://www.burkenc.org/350/Veterans-Services",
    phone: "828-764-9080",
    address: "700 E Parker Road",
    city: "Morganton",
    zip: "28655",
    latitude: 35.7426,
    longitude: -81.6717,
    source_name: "Burke County Government",
    source_type: "government",
  },
  {
    title: "Cleveland County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Shelby and Cleveland County veterans. VA claims and benefits guidance.",
    website_url: "https://www.clevelandcounty.com/main/veterans-services/",
    phone: "704-484-4914",
    address: "130 S Post Road",
    city: "Shelby",
    zip: "28152",
    latitude: 35.2740,
    longitude: -81.5454,
    source_name: "Cleveland County Government",
    source_type: "government",
  },
  {
    title: "Surry County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Dobson, Mount Airy, and Surry County veterans. VA claims assistance.",
    website_url: "https://www.surryinfo.org",
    phone: "336-401-8233",
    address: "118 Hamby Road",
    city: "Dobson",
    zip: "27017",
    latitude: 36.4046,
    longitude: -80.7236,
    source_name: "Surry County Government",
    source_type: "government",
  },
  {
    title: "Wilkes County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving North Wilkesboro, Wilkesboro, and Wilkes County veterans. VA claims assistance.",
    website_url: "https://www.wilkescounty.net",
    phone: "336-651-7591",
    address: "201 Curtis Bridge Road",
    city: "Wilkesboro",
    zip: "28697",
    latitude: 36.1457,
    longitude: -81.1620,
    source_name: "Wilkes County Government",
    source_type: "government",
  },
  {
    title: "Nash County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Nashville, Rocky Mount, and Nash County veterans. VA claims assistance.",
    website_url: "https://www.nashcountync.gov/176/Veterans-Services",
    phone: "252-462-2613",
    address: "120 W Washington Street",
    city: "Nashville",
    zip: "27856",
    latitude: 35.9785,
    longitude: -77.9650,
    source_name: "Nash County Government",
    source_type: "government",
  },
  {
    title: "Wilson County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Wilson and Wilson County veterans. VA claims and benefits guidance.",
    website_url: "https://www.wilson-co.com/179/Veterans-Services",
    phone: "252-399-2900",
    address: "1817 Glendale Drive SW",
    city: "Wilson",
    zip: "27893",
    latitude: 35.7126,
    longitude: -77.9261,
    source_name: "Wilson County Government",
    source_type: "government",
  },
  {
    title: "Lenoir County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Kinston and Lenoir County veterans. VA claims assistance.",
    website_url: "https://www.lenoircountync.gov",
    phone: "252-559-6470",
    address: "2031 W Vernon Avenue",
    city: "Kinston",
    zip: "28504",
    latitude: 35.2695,
    longitude: -77.6111,
    source_name: "Lenoir County Government",
    source_type: "government",
  },
  {
    title: "Sampson County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Clinton and Sampson County veterans. VA claims assistance.",
    website_url: "https://www.sampsonnc.com",
    phone: "910-592-7081",
    address: "405 County Complex Road, Suite 100",
    city: "Clinton",
    zip: "28328",
    latitude: 34.9923,
    longitude: -78.3234,
    source_name: "Sampson County Government",
    source_type: "government",
  },
  {
    title: "Duplin County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Kenansville, Wallace, and Duplin County veterans. VA claims assistance.",
    website_url: "https://www.duplincountync.com",
    phone: "910-296-2179",
    address: "117 Beasley Street",
    city: "Kenansville",
    zip: "28349",
    latitude: 34.9624,
    longitude: -77.9619,
    source_name: "Duplin County Government",
    source_type: "government",
  },
  {
    title: "Bladen County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Elizabethtown and Bladen County veterans. VA claims assistance.",
    website_url: "https://www.bladenco.org",
    phone: "910-862-6800",
    address: "201 S Cypress Street",
    city: "Elizabethtown",
    zip: "28337",
    latitude: 34.6293,
    longitude: -78.6047,
    source_name: "Bladen County Government",
    source_type: "government",
  },
  {
    title: "Columbus County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Whiteville and Columbus County veterans. VA claims and benefits assistance.",
    website_url: "https://www.columbusco.org",
    phone: "910-640-6610",
    address: "112 W Smith Street",
    city: "Whiteville",
    zip: "28472",
    latitude: 34.3399,
    longitude: -78.7039,
    source_name: "Columbus County Government",
    source_type: "government",
  },
  {
    title: "Vance County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Henderson and Vance County veterans. VA claims assistance.",
    website_url: "https://www.vancecounty.org",
    phone: "252-738-2178",
    address: "122 Young Street",
    city: "Henderson",
    zip: "27536",
    latitude: 36.3296,
    longitude: -78.4006,
    source_name: "Vance County Government",
    source_type: "government",
  },
  {
    title: "Franklin County Veterans Services (NC)",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Louisburg and Franklin County veterans. VA claims and benefits guidance.",
    website_url: "https://www.franklincountync.us",
    phone: "919-496-5500",
    address: "215 E Nash Street",
    city: "Louisburg",
    zip: "27549",
    latitude: 36.0985,
    longitude: -78.3014,
    source_name: "Franklin County Government",
    source_type: "government",
  },
  {
    title: "Person County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Roxboro and Person County veterans. VA claims assistance.",
    website_url: "https://www.personcountync.gov",
    phone: "336-597-1772",
    address: "304 S Morgan Street",
    city: "Roxboro",
    zip: "27573",
    latitude: 36.3938,
    longitude: -78.9836,
    source_name: "Person County Government",
    source_type: "government",
  },
  {
    title: "Rockingham County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Wentworth, Reidsville, Eden, and Rockingham County veterans. VA claims assistance.",
    website_url: "https://www.rockinghamcountync.gov",
    phone: "336-342-8358",
    address: "371 NC 65",
    city: "Wentworth",
    zip: "27375",
    latitude: 36.4007,
    longitude: -79.7748,
    source_name: "Rockingham County Government",
    source_type: "government",
  },
  {
    title: "Davie County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Mocksville and Davie County veterans. VA claims assistance.",
    website_url: "https://www.daviecountync.gov",
    phone: "336-753-6230",
    address: "123 S Main Street",
    city: "Mocksville",
    zip: "27028",
    latitude: 35.8901,
    longitude: -80.5614,
    source_name: "Davie County Government",
    source_type: "government",
  },
  {
    title: "Caldwell County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Lenoir and Caldwell County veterans. VA claims and benefits guidance.",
    website_url: "https://www.caldwellcountync.org",
    phone: "828-757-1346",
    address: "905 West Avenue NW",
    city: "Lenoir",
    zip: "28645",
    latitude: 35.9143,
    longitude: -81.5390,
    source_name: "Caldwell County Government",
    source_type: "government",
  },
  {
    title: "Watauga County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Boone and Watauga County veterans (Appalachian State community). VA claims assistance.",
    website_url: "https://www.wataugacounty.org",
    phone: "828-265-8065",
    address: "126 Poplar Grove Connector",
    city: "Boone",
    zip: "28607",
    latitude: 36.2168,
    longitude: -81.6746,
    source_name: "Watauga County Government",
    source_type: "government",
  },
  {
    title: "Haywood County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Waynesville and Haywood County veterans. VA claims assistance.",
    website_url: "https://www.haywoodcountync.gov",
    phone: "828-356-2900",
    address: "157 Paragon Parkway",
    city: "Clyde",
    zip: "28721",
    latitude: 35.5379,
    longitude: -82.9079,
    source_name: "Haywood County Government",
    source_type: "government",
  },
  {
    title: "Jackson County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Sylva and Jackson County veterans (western NC mountains). VA claims assistance.",
    website_url: "https://www.jacksonnc.org",
    phone: "828-586-7560",
    address: "538 Scotts Creek Road",
    city: "Sylva",
    zip: "28779",
    latitude: 35.3737,
    longitude: -83.2257,
    source_name: "Jackson County Government",
    source_type: "government",
  },
  {
    title: "Macon County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Franklin and Macon County veterans (western NC mountains). VA claims assistance.",
    website_url: "https://www.maconnc.org",
    phone: "828-349-2104",
    address: "5 W Main Street",
    city: "Franklin",
    zip: "28734",
    latitude: 35.1827,
    longitude: -83.3812,
    source_name: "Macon County Government",
    source_type: "government",
  },
  {
    title: "Halifax County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Halifax, Roanoke Rapids, and Halifax County veterans. VA claims assistance.",
    website_url: "https://www.halifaxnc.com",
    phone: "252-583-8230",
    address: "10 N King Street",
    city: "Halifax",
    zip: "27839",
    latitude: 36.3290,
    longitude: -77.5894,
    source_name: "Halifax County Government",
    source_type: "government",
  },
  {
    title: "Edgecombe County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Tarboro, Rocky Mount, and Edgecombe County veterans. VA claims assistance.",
    website_url: "https://www.edgecombecountync.gov",
    phone: "252-641-7644",
    address: "201 St Andrew Street",
    city: "Tarboro",
    zip: "27886",
    latitude: 35.8968,
    longitude: -77.5358,
    source_name: "Edgecombe County Government",
    source_type: "government",
  },
  {
    title: "Stokes County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Danbury, King, and Stokes County veterans. VA claims assistance.",
    website_url: "https://www.co.stokes.nc.us",
    phone: "336-593-2403",
    address: "1014 Main Street",
    city: "Danbury",
    zip: "27016",
    latitude: 36.4076,
    longitude: -80.2011,
    source_name: "Stokes County Government",
    source_type: "government",
  },

  // ============================================================
  // HOUSING — Regional shelters, more SSVF, USVETS, transitional
  // ============================================================
  {
    title: "U.S.VETS — Charlotte (Veterans Village)",
    category_slug: "housing",
    subcategory_name: "Transitional Housing",
    short_description: "Transitional housing and supportive services for homeless veterans in Charlotte. Case management, employment services, sober living, and permanent housing placement.",
    website_url: "https://usvets.org/locations/charlotte/",
    phone: "704-595-0042",
    city: "Charlotte",
    zip: "28208",
    latitude: 35.2271,
    longitude: -80.8431,
    eligibility: "Homeless veterans",
    source_name: "U.S.VETS",
    source_type: "nonprofit",
  },
  {
    title: "Salvation Army Center of Hope — Charlotte (Veteran Services)",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Emergency shelter and supportive services for homeless women and families including veterans in Charlotte.",
    website_url: "https://southernusa.salvationarmy.org/charlotte/",
    phone: "704-348-2541",
    address: "534 Spratt Street",
    city: "Charlotte",
    zip: "28206",
    latitude: 35.2425,
    longitude: -80.8275,
    eligibility: "Homeless women, families, including veterans",
    source_name: "The Salvation Army",
    source_type: "nonprofit",
  },
  {
    title: "Roof Above (formerly Urban Ministry Center) — Charlotte",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Day services, emergency shelter, and supportive housing for adults experiencing homelessness in Mecklenburg County. Veteran-specific housing programs available.",
    website_url: "https://www.roofabove.org",
    phone: "704-371-3000",
    address: "945 N College Street",
    city: "Charlotte",
    zip: "28206",
    latitude: 35.2378,
    longitude: -80.8351,
    eligibility: "Adults experiencing homelessness",
    source_name: "Roof Above",
    source_type: "nonprofit",
  },
  {
    title: "Raleigh Rescue Mission — Veteran Services",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Emergency shelter, transitional programs, and recovery support for men, women, and families in Raleigh including veterans.",
    website_url: "https://www.raleighrescue.org",
    phone: "919-828-9014",
    address: "314 E Hargett Street",
    city: "Raleigh",
    zip: "27601",
    latitude: 35.7796,
    longitude: -78.6376,
    eligibility: "Adults experiencing homelessness",
    source_name: "Raleigh Rescue Mission",
    source_type: "nonprofit",
  },
  {
    title: "Durham Rescue Mission",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Emergency shelter, residential recovery, and transitional housing for men, women, and families in Durham. Serves veterans experiencing homelessness.",
    website_url: "https://www.durhamrescuemission.org",
    phone: "919-688-9641",
    address: "1201 E Main Street",
    city: "Durham",
    zip: "27701",
    latitude: 35.9961,
    longitude: -78.8810,
    eligibility: "Adults experiencing homelessness",
    source_name: "Durham Rescue Mission",
    source_type: "nonprofit",
  },
  {
    title: "Greensboro Urban Ministry — Veteran Services",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Weaver House emergency shelter, Pathways Center transitional housing, food pantry, and case management for homeless individuals in Greensboro.",
    website_url: "https://greensborourbanministry.org",
    phone: "336-271-5959",
    address: "305 W Lee Street",
    city: "Greensboro",
    zip: "27406",
    latitude: 36.0648,
    longitude: -79.7935,
    eligibility: "Adults experiencing homelessness",
    source_name: "Greensboro Urban Ministry",
    source_type: "nonprofit",
  },
  {
    title: "Western Carolina Rescue Ministries — Asheville",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Emergency shelter, transitional housing, and recovery programs for men and families in Asheville. Veterans welcome.",
    website_url: "https://www.westerncarolinarescue.com",
    phone: "828-254-0471",
    address: "225 Patton Avenue",
    city: "Asheville",
    zip: "28801",
    latitude: 35.5946,
    longitude: -82.5618,
    eligibility: "Adults experiencing homelessness",
    source_name: "Western Carolina Rescue Ministries",
    source_type: "nonprofit",
  },
  {
    title: "Veterans Services of the Carolinas (Asheville)",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "ABCCM division providing SSVF, HUD-VASH wraparound, transitional housing, and homelessness prevention for veterans across western NC.",
    website_url: "https://abccm.org/services/veterans/",
    phone: "828-259-5300",
    address: "1 Steadfast Way",
    city: "Asheville",
    zip: "28806",
    latitude: 35.5808,
    longitude: -82.5897,
    eligibility: "Veterans at risk of or experiencing homelessness",
    source_name: "Asheville-Buncombe Community Christian Ministry (ABCCM)",
    source_type: "nonprofit",
  },
  {
    title: "Good Shepherd Center — Wilmington",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Emergency shelter, supportive housing, and Veterans Endeavor for Recovery (VER) program for homeless veterans in Wilmington.",
    website_url: "https://www.goodshepherdwilmington.org",
    phone: "910-763-4424",
    address: "811 Martin Street",
    city: "Wilmington",
    zip: "28401",
    latitude: 34.2333,
    longitude: -77.9486,
    eligibility: "Adults experiencing homelessness",
    source_name: "Good Shepherd Center",
    source_type: "nonprofit",
  },
  {
    title: "Family Endeavors SSVF (NC)",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "VA SSVF grantee providing rapid rehousing, prevention, and case management for veteran families across multiple NC counties.",
    website_url: "https://www.endeavors.org",
    phone: "1-866-866-3122",
    state: "NC",
    eligibility: "Very low-income veteran families at risk of or experiencing homelessness",
    source_name: "Endeavors / VA SSVF",
    source_type: "program",
  },
  {
    title: "Salvation Army Center of Hope — Greensboro",
    category_slug: "housing",
    subcategory_name: "Emergency Housing / Homeless Shelters",
    short_description: "Emergency shelter, meals, and case management for homeless individuals and families in Greensboro including veterans.",
    website_url: "https://southernusa.salvationarmy.org/greensboro/",
    phone: "336-723-6366",
    address: "1311 S Eugene Street",
    city: "Greensboro",
    zip: "27406",
    latitude: 36.0492,
    longitude: -79.7967,
    eligibility: "Homeless individuals and families",
    source_name: "The Salvation Army",
    source_type: "nonprofit",
  },
  {
    title: "Community Empowerment Fund (Durham/Chapel Hill)",
    category_slug: "housing",
    subcategory_name: "Foreclosure Prevention",
    short_description: "Financial coaching, savings matching, and homelessness prevention for low-income individuals in Durham and Orange counties. Veterans served.",
    website_url: "https://www.communityef.org",
    phone: "919-200-0233",
    address: "1208 W Chapel Hill Street",
    city: "Durham",
    zip: "27701",
    latitude: 35.9981,
    longitude: -78.9114,
    eligibility: "Low-income residents of Durham/Orange counties",
    source_name: "Community Empowerment Fund",
    source_type: "nonprofit",
  },

  // ============================================================
  // EMPLOYMENT — NCWorks, NCDOC apprenticeship, IVMF, hire programs
  // ============================================================
  {
    title: "NCWorks Veterans Services",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "State workforce program with priority of service for veterans across 80+ NCWorks Career Centers statewide. Disabled Veterans Outreach Program (DVOP) and Local Veterans Employment Representatives (LVER) at major centers.",
    website_url: "https://www.ncworks.gov/vosnet/Default.aspx",
    phone: "919-814-0400",
    address: "200 W Jones Street",
    city: "Raleigh",
    zip: "27603",
    latitude: 35.7796,
    longitude: -78.6391,
    eligibility: "All NC veterans (priority of service)",
    source_name: "NC Department of Commerce",
    source_type: "government",
  },
  {
    title: "NCWorks Career Center — Fayetteville",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "Workforce center serving Fort Liberty community with veteran priority of service. DVOP/LVER staff on-site for individualized employment services.",
    website_url: "https://www.ncworks.gov",
    phone: "910-486-1010",
    address: "414 Ray Avenue",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0535,
    longitude: -78.8838,
    eligibility: "All NC veterans (priority of service)",
    source_name: "NC Department of Commerce",
    source_type: "government",
  },
  {
    title: "NCWorks Career Center — Charlotte",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "Workforce center serving Charlotte metro with veteran priority of service. DVOP/LVER on-site, job search assistance, training referrals.",
    website_url: "https://www.ncworks.gov",
    phone: "704-566-2870",
    address: "5601 Executive Center Drive",
    city: "Charlotte",
    zip: "28212",
    latitude: 35.1936,
    longitude: -80.7430,
    eligibility: "All NC veterans (priority of service)",
    source_name: "NC Department of Commerce",
    source_type: "government",
  },
  {
    title: "NCWorks Career Center — Raleigh",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "Workforce center serving Wake County with veteran priority of service. Job search, resume help, training referrals, DVOP/LVER staff.",
    website_url: "https://www.ncworks.gov",
    phone: "919-715-7000",
    address: "4101 Glenwood Avenue",
    city: "Raleigh",
    zip: "27612",
    latitude: 35.8364,
    longitude: -78.6816,
    eligibility: "All NC veterans (priority of service)",
    source_name: "NC Department of Commerce",
    source_type: "government",
  },
  {
    title: "Hiring Our Heroes — North Carolina",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "U.S. Chamber Foundation program connecting transitioning service members, veterans, and military spouses to NC employers. Career Summits, Corporate Fellowship Program at Fort Liberty and Camp Lejeune.",
    website_url: "https://www.hiringourheroes.org",
    phone: "1-888-376-2010",
    state: "NC",
    eligibility: "Transitioning service members, veterans, military spouses",
    source_name: "U.S. Chamber of Commerce Foundation",
    source_type: "nonprofit",
  },
  {
    title: "Helmets to Hardhats — North Carolina",
    category_slug: "employment",
    subcategory_name: "Building & Construction",
    short_description: "Free national program connecting veterans to careers in skilled construction trades through registered apprenticeships with union contractors across NC.",
    website_url: "https://helmetstohardhats.org",
    phone: "866-741-6210",
    state: "NC",
    eligibility: "Veterans, transitioning service members, National Guard, Reservists",
    source_name: "Helmets to Hardhats",
    source_type: "nonprofit",
  },
  {
    title: "IVMF Onward to Opportunity (O2O) — Fort Liberty",
    category_slug: "employment",
    subcategory_name: "Certifications & Licensing",
    short_description: "Free industry-recognized certifications and career training for transitioning service members, veterans, and military spouses. On-site at Fort Liberty.",
    website_url: "https://ivmf.syracuse.edu/programs/career-training/onward-to-opportunity/",
    phone: "315-443-0141",
    city: "Fort Liberty",
    state: "NC",
    eligibility: "Transitioning service members, veterans, military spouses (free)",
    source_name: "Institute for Veterans and Military Families (Syracuse)",
    source_type: "program",
  },
  {
    title: "IVMF Onward to Opportunity (O2O) — Camp Lejeune",
    category_slug: "employment",
    subcategory_name: "Certifications & Licensing",
    short_description: "Free industry-recognized certifications and career training for transitioning service members, veterans, and military spouses. On-site at Camp Lejeune.",
    website_url: "https://ivmf.syracuse.edu/programs/career-training/onward-to-opportunity/",
    phone: "315-443-0141",
    city: "Jacksonville",
    state: "NC",
    eligibility: "Transitioning service members, veterans, military spouses (free)",
    source_name: "Institute for Veterans and Military Families (Syracuse)",
    source_type: "program",
  },
  {
    title: "NC Apprenticeship — Veteran Pathways",
    category_slug: "employment",
    subcategory_name: "Trade Schools & Vocational",
    short_description: "ApprenticeshipNC connects veterans to registered apprenticeships in skilled trades, manufacturing, IT, healthcare. GI Bill benefits often usable for apprenticeship wages.",
    website_url: "https://www.apprenticeshipnc.com",
    phone: "919-807-7126",
    city: "Raleigh",
    state: "NC",
    eligibility: "Veterans seeking skilled trade careers",
    source_name: "NC Community College System / ApprenticeshipNC",
    source_type: "government",
  },
  {
    title: "Veterans Bridge Home — Charlotte (Career Programs)",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "Free career navigation, employer matching, and wraparound support for veterans and military families in the Charlotte region. Connects veterans to vetted employers.",
    website_url: "https://www.veteransbridgehome.org",
    phone: "704-332-2002",
    address: "1235 East Boulevard, Suite E",
    city: "Charlotte",
    zip: "28203",
    latitude: 35.2050,
    longitude: -80.8470,
    eligibility: "Veterans, transitioning service members, military families",
    source_name: "Veterans Bridge Home",
    source_type: "nonprofit",
  },
  {
    title: "Wounded Warrior Project Warriors to Work — North Carolina",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "Free career counseling, resume assistance, interview prep, and employer connections for wounded post-9/11 veterans and family members across NC.",
    website_url: "https://www.woundedwarriorproject.org/programs/warriors-to-work",
    phone: "888-997-2586",
    state: "NC",
    eligibility: "Wounded post-9/11 veterans and family members",
    source_name: "Wounded Warrior Project",
    source_type: "nonprofit",
  },
  {
    title: "Veterati Mentorship Network (NC veterans)",
    category_slug: "employment",
    subcategory_name: "Career Pathways",
    short_description: "Free 1-on-1 phone mentoring for veterans, transitioning service members, and military spouses. NC veterans connect with experienced professionals nationwide.",
    website_url: "https://www.veterati.com",
    state: "NC",
    eligibility: "Veterans, transitioning service members, military spouses",
    source_name: "Veterati",
    source_type: "nonprofit",
  },

  // ============================================================
  // LEGAL — Legal Aid offices, pro bono clinics, MUR Project
  // ============================================================
  {
    title: "Legal Aid of North Carolina — Statewide Helpline",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Free civil legal assistance for low-income North Carolinians including veterans. Housing, family, consumer, public benefits, expungement. 24 offices statewide.",
    website_url: "https://www.legalaidnc.org",
    phone: "1-866-219-5262",
    address: "224 S Dawson Street",
    city: "Raleigh",
    zip: "27601",
    latitude: 35.7766,
    longitude: -78.6440,
    eligibility: "Low-income NC residents",
    source_name: "Legal Aid of North Carolina",
    source_type: "nonprofit",
  },
  {
    title: "Legal Aid of NC — Charlotte Office",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Free civil legal services for low-income veterans and residents in Mecklenburg and surrounding counties.",
    website_url: "https://www.legalaidnc.org/office/charlotte",
    phone: "704-376-1600",
    address: "5535 Albemarle Road, Suite 200",
    city: "Charlotte",
    zip: "28212",
    latitude: 35.2078,
    longitude: -80.7486,
    eligibility: "Low-income residents",
    source_name: "Legal Aid of North Carolina",
    source_type: "nonprofit",
  },
  {
    title: "Legal Aid of NC — Fayetteville Office",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Free civil legal services for low-income veterans and residents in Cumberland and surrounding counties (Fort Liberty community).",
    website_url: "https://www.legalaidnc.org/office/fayetteville",
    phone: "910-483-0400",
    address: "517 S McPherson Church Road",
    city: "Fayetteville",
    zip: "28303",
    latitude: 35.0571,
    longitude: -78.9420,
    eligibility: "Low-income residents",
    source_name: "Legal Aid of North Carolina",
    source_type: "nonprofit",
  },
  {
    title: "NC State Bar Lawyer Referral Service",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Statewide attorney referral service. Reduced-fee initial consultation. Veteran-specific referrals available for VA benefits, military divorce, and disability appeals.",
    website_url: "https://www.ncbar.gov",
    phone: "1-800-662-7660",
    city: "Cary",
    state: "NC",
    eligibility: "Anyone needing legal services",
    source_name: "North Carolina State Bar",
    source_type: "government",
  },
  {
    title: "Duke Law Veterans Disability Clinic",
    category_slug: "legal",
    subcategory_name: "VA Benefits Appeals",
    short_description: "Free representation by Duke Law students (supervised by attorneys) for NC veterans appealing denied VA disability claims to the Board of Veterans Appeals.",
    website_url: "https://law.duke.edu/veterans/",
    phone: "919-613-7169",
    address: "210 Science Drive",
    city: "Durham",
    zip: "27708",
    latitude: 36.0027,
    longitude: -78.9419,
    eligibility: "NC veterans with denied VA disability claims",
    source_name: "Duke University School of Law",
    source_type: "service",
  },
  {
    title: "NCCU Law Veterans Law Clinic",
    category_slug: "legal",
    subcategory_name: "VA Benefits Appeals",
    short_description: "Free legal representation for veterans through NC Central University School of Law clinic. VA disability claims, appeals, discharge upgrades, and other veteran-specific matters.",
    website_url: "https://law.nccu.edu/clinics/",
    phone: "919-530-5244",
    address: "640 Nelson Street",
    city: "Durham",
    zip: "27707",
    latitude: 35.9737,
    longitude: -78.8990,
    eligibility: "Income-qualifying NC veterans",
    source_name: "NC Central University School of Law",
    source_type: "service",
  },
  {
    title: "Pisgah Legal Services — Veteran Services (Western NC)",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Free civil legal aid for low-income veterans in 18 western NC counties including Buncombe, Henderson, Madison. Housing, benefits, family law.",
    website_url: "https://www.pisgahlegal.org/veterans-services/",
    phone: "828-253-0406",
    address: "62 Charlotte Street",
    city: "Asheville",
    zip: "28801",
    latitude: 35.6041,
    longitude: -82.5519,
    eligibility: "Low-income residents of western NC",
    source_name: "Pisgah Legal Services",
    source_type: "nonprofit",
  },
  {
    title: "American Bar Association Military Pro Bono Project (NC)",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Free civil legal assistance from pro bono attorneys for active-duty service members (E-1 to E-6) and their families. NC matters routed to volunteer attorneys statewide.",
    website_url: "https://www.militaryprobono.org",
    phone: "703-560-7977",
    state: "NC",
    eligibility: "Active-duty E-1 to E-6 and families",
    source_name: "American Bar Association",
    source_type: "nonprofit",
  },
  {
    title: "Disability Rights NC — Veteran Services",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "NC's federally-mandated Protection and Advocacy organization. Free legal help for people with disabilities including veterans. Service animal access, ADA compliance, healthcare rights.",
    website_url: "https://disabilityrightsnc.org",
    phone: "919-856-2195",
    address: "3724 National Drive, Suite 100",
    city: "Raleigh",
    zip: "27612",
    latitude: 35.8462,
    longitude: -78.7146,
    eligibility: "People with disabilities, including veterans",
    source_name: "Disability Rights North Carolina",
    source_type: "nonprofit",
  },
  {
    title: "Charlotte Center for Legal Advocacy — Veterans Services",
    category_slug: "legal",
    subcategory_name: "Veterans Legal Clinics",
    short_description: "Free civil legal aid for low-income residents and veterans in Mecklenburg County. Public benefits, immigration, taxpayer assistance, healthcare access.",
    website_url: "https://charlottelegaladvocacy.org",
    phone: "704-376-1600",
    address: "5535 Albemarle Road, Suite 200",
    city: "Charlotte",
    zip: "28212",
    latitude: 35.2078,
    longitude: -80.7486,
    eligibility: "Low-income residents of Mecklenburg County",
    source_name: "Charlotte Center for Legal Advocacy",
    source_type: "nonprofit",
  },

  // ============================================================
  // EDUCATION — VITAL programs, NC tuition assistance, GI Bill schools
  // ============================================================
  {
    title: "NC Scholarship for Children of Wartime Veterans",
    category_slug: "education",
    subcategory_name: "Tuition Assistance",
    short_description: "State scholarship for children of certain disabled, deceased, or POW/MIA NC wartime veterans. Free tuition at NC public colleges/universities (Class I-A). Administered by NCDMVA.",
    website_url: "https://www.milvets.nc.gov/services/scholarship-program",
    phone: "844-624-8387",
    address: "4001 Mail Service Center",
    city: "Raleigh",
    zip: "27699",
    latitude: 35.7706,
    longitude: -78.6383,
    eligibility: "Children of qualifying disabled/deceased/POW NC wartime veterans",
    source_name: "NC Department of Military and Veterans Affairs",
    source_type: "government",
  },
  {
    title: "NC State University Veterans Education Services",
    category_slug: "education",
    subcategory_name: "Veteran Student Services",
    short_description: "Veteran student services at NC State University in Raleigh. GI Bill certification, VA work-study, Vet-to-Vet mentoring, dedicated veterans lounge.",
    website_url: "https://veterans.dasa.ncsu.edu",
    phone: "919-515-2173",
    address: "2610 Cates Avenue",
    city: "Raleigh",
    zip: "27695",
    latitude: 35.7847,
    longitude: -78.6821,
    eligibility: "Veteran students at NC State",
    source_name: "NC State University",
    source_type: "program",
  },
  {
    title: "UNC-Chapel Hill Veteran and Military Services",
    category_slug: "education",
    subcategory_name: "Veteran Student Services",
    short_description: "GI Bill certification, VA work-study, advising, and community for veteran/military students at UNC-Chapel Hill.",
    website_url: "https://veterans.unc.edu",
    phone: "919-962-5396",
    address: "450 Ridge Road",
    city: "Chapel Hill",
    zip: "27599",
    latitude: 35.9088,
    longitude: -79.0469,
    eligibility: "Veteran students at UNC-Chapel Hill",
    source_name: "University of North Carolina at Chapel Hill",
    source_type: "program",
  },
  {
    title: "UNC-Charlotte Veterans Services",
    category_slug: "education",
    subcategory_name: "Veteran Student Services",
    short_description: "Niner Veterans Network. GI Bill certification, VA work-study, VetSuccess on Campus (VSOC) counselor, student lounge, transition support.",
    website_url: "https://veterans.charlotte.edu",
    phone: "704-687-5774",
    address: "9201 University City Boulevard",
    city: "Charlotte",
    zip: "28223",
    latitude: 35.3084,
    longitude: -80.7375,
    eligibility: "Veteran students at UNC-Charlotte",
    source_name: "University of North Carolina at Charlotte",
    source_type: "program",
  },
  {
    title: "East Carolina University Office of Military & Veteran Resources",
    category_slug: "education",
    subcategory_name: "Veteran Student Services",
    short_description: "GI Bill certification, VA work-study, transition support, and dedicated veterans lounge at ECU in Greenville. Designated Military Friendly School.",
    website_url: "https://veterans.ecu.edu",
    phone: "252-737-1898",
    address: "Old Cafeteria Complex",
    city: "Greenville",
    zip: "27858",
    latitude: 35.6064,
    longitude: -77.3656,
    eligibility: "Veteran students at ECU",
    source_name: "East Carolina University",
    source_type: "program",
  },
  {
    title: "Fayetteville State University Veteran Services",
    category_slug: "education",
    subcategory_name: "Veteran Student Services",
    short_description: "Strong veteran/military student support at FSU near Fort Liberty. GI Bill certification, VA work-study, military programs office.",
    website_url: "https://www.uncfsu.edu/military",
    phone: "910-672-1604",
    address: "1200 Murchison Road",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0691,
    longitude: -78.8965,
    eligibility: "Veteran/military students at FSU",
    source_name: "Fayetteville State University",
    source_type: "program",
  },
  {
    title: "Fayetteville Technical Community College — Veteran Services",
    category_slug: "education",
    subcategory_name: "Technical Colleges",
    short_description: "Major community college serving Fort Liberty community with full veteran/military support. GI Bill, VA Voc Rehab, military credit articulation.",
    website_url: "https://www.faytechcc.edu/military",
    phone: "910-678-8378",
    address: "2201 Hull Road",
    city: "Fayetteville",
    zip: "28303",
    latitude: 35.0633,
    longitude: -78.9573,
    eligibility: "Veteran/military students at FTCC",
    source_name: "Fayetteville Technical Community College",
    source_type: "program",
  },
  {
    title: "Coastal Carolina Community College — Veteran Services",
    category_slug: "education",
    subcategory_name: "Technical Colleges",
    short_description: "Community college serving Camp Lejeune Marine community in Jacksonville. GI Bill, military tuition assistance, MOS to credit articulation.",
    website_url: "https://www.coastalcarolina.edu/military",
    phone: "910-938-6294",
    address: "444 Western Boulevard",
    city: "Jacksonville",
    zip: "28546",
    latitude: 34.7398,
    longitude: -77.3962,
    eligibility: "Veteran/military students at CCCC",
    source_name: "Coastal Carolina Community College",
    source_type: "program",
  },
  {
    title: "Central Piedmont Community College — Military Family Services",
    category_slug: "education",
    subcategory_name: "Technical Colleges",
    short_description: "CPCC's military and veteran services in Charlotte. GI Bill certification, VA Voc Rehab, military credit articulation, dedicated counselor.",
    website_url: "https://www.cpcc.edu/students/services/veterans",
    phone: "704-330-6447",
    address: "1201 Elizabeth Avenue",
    city: "Charlotte",
    zip: "28204",
    latitude: 35.2152,
    longitude: -80.8285,
    eligibility: "Veteran/military students at CPCC",
    source_name: "Central Piedmont Community College",
    source_type: "program",
  },
  {
    title: "Wake Technical Community College — Veterans Education Services",
    category_slug: "education",
    subcategory_name: "Technical Colleges",
    short_description: "Wake Tech's veteran services in Raleigh. GI Bill certification, VA Voc Rehab, priority registration, military credit articulation.",
    website_url: "https://www.waketech.edu/student-services/veterans",
    phone: "919-866-5470",
    address: "9101 Fayetteville Road",
    city: "Raleigh",
    zip: "27603",
    latitude: 35.6700,
    longitude: -78.6886,
    eligibility: "Veteran/military students at Wake Tech",
    source_name: "Wake Technical Community College",
    source_type: "program",
  },
  {
    title: "VA VetSuccess on Campus (VSOC) — UNC Charlotte",
    category_slug: "education",
    subcategory_name: "Education Counseling",
    short_description: "On-campus VA counselor at UNC-Charlotte providing benefits counseling, VR&E referrals, mental health connection, and transition support to veteran students.",
    website_url: "https://www.benefits.va.gov/vocrehab/vsoc.asp",
    phone: "704-687-5774",
    city: "Charlotte",
    zip: "28223",
    latitude: 35.3084,
    longitude: -80.7375,
    eligibility: "Veteran students at participating campuses",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },
  {
    title: "VA VetSuccess on Campus (VSOC) — Fayetteville State University",
    category_slug: "education",
    subcategory_name: "Education Counseling",
    short_description: "On-campus VA counselor at FSU providing benefits counseling, VR&E referrals, mental health connection, and transition support for Fort Liberty community veteran students.",
    website_url: "https://www.benefits.va.gov/vocrehab/vsoc.asp",
    phone: "910-672-1604",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0691,
    longitude: -78.8965,
    eligibility: "Veteran students at FSU",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },
  {
    title: "Student Veterans of America — NC Chapters",
    category_slug: "education",
    subcategory_name: "Veteran Student Services",
    short_description: "Student-led chapters at NC State, UNC-Chapel Hill, UNC-Charlotte, ECU, FSU, App State, UNC-Wilmington, and others. Peer support, advocacy, scholarships, leadership development.",
    website_url: "https://studentveterans.org",
    state: "NC",
    eligibility: "Veteran/military students at member campuses",
    source_name: "Student Veterans of America",
    source_type: "nonprofit",
  },
  {
    title: "Hire Heroes USA — NC Career Programs",
    category_slug: "education",
    subcategory_name: "Continuing Education",
    short_description: "Free job search training, resume coaching, career counseling, and skills training for veterans and military spouses. Self-paced courses and 1-on-1 coaching available to NC veterans.",
    website_url: "https://www.hireheroesusa.org",
    phone: "844-634-1520",
    state: "NC",
    eligibility: "Veterans, transitioning service members, military spouses",
    source_name: "Hire Heroes USA",
    source_type: "nonprofit",
  },
];

async function loadMaps() {
  const { data: cats, error: catErr } = await supabaseAdmin.from("categories").select("id, slug");
  if (catErr || !cats) throw new Error(`Failed to load categories: ${catErr?.message}`);
  const catMap = new Map<string, string>();
  cats.forEach((c: any) => catMap.set(c.slug, c.id));

  const { data: subs, error: subErr } = await supabaseAdmin.from("subcategories").select("id, name, category_id");
  if (subErr || !subs) throw new Error(`Failed to load subcategories: ${subErr?.message}`);
  const catIdToSlug = new Map<string, string>();
  cats.forEach((c: any) => catIdToSlug.set(c.id, c.slug));
  const subMap = new Map<string, string>();
  subs.forEach((s: any) => {
    const catSlug = catIdToSlug.get(s.category_id);
    if (catSlug) subMap.set(`${catSlug}|${s.name.toLowerCase()}`, s.id);
  });

  return { catMap, subMap };
}

async function main() {
  console.log(`\n=== NC Resources Seed ROUND 2 — ${NC_RESOURCES.length} rows ===\n`);

  const { catMap, subMap } = await loadMaps();
  console.log(`[setup] Loaded ${catMap.size} categories, ${subMap.size} subcategory mappings`);

  const { data: existing } = await supabaseAdmin
    .from("resources")
    .select("title")
    .eq("state", STATE);
  const existingTitles = new Set((existing || []).map((r: any) => (r.title || "").toLowerCase().trim()));
  console.log(`[setup] Found ${existingTitles.size} existing NC rows to dedupe against\n`);

  const counts = {
    created: 0,
    duplicates: 0,
    errors: 0,
    subcategoryMisses: 0,
    byCategory: {} as Record<string, number>,
    bySubcategory: {} as Record<string, number>,
    errorRows: [] as { title: string; reason: string }[],
    subMissList: [] as { title: string; key: string }[],
  };

  for (const r of NC_RESOURCES) {
    const titleKey = r.title.toLowerCase().trim();
    if (existingTitles.has(titleKey)) {
      counts.duplicates++;
      continue;
    }

    const category_id = catMap.get(r.category_slug);
    if (!category_id) {
      counts.errors++;
      counts.errorRows.push({ title: r.title, reason: `Unknown category slug: ${r.category_slug}` });
      continue;
    }

    let subcategory_id: string | null = null;
    if (r.subcategory_name) {
      subcategory_id = subMap.get(`${r.category_slug}|${r.subcategory_name.toLowerCase()}`) || null;
      if (!subcategory_id) {
        counts.subcategoryMisses++;
        counts.subMissList.push({ title: r.title, key: `${r.category_slug}|${r.subcategory_name}` });
      }
    }

    const insertRow: Record<string, any> = {
      title: r.title,
      category_id,
      short_description: r.short_description,
      website_url: r.website_url || null,
      phone: r.phone || null,
      email: r.email || null,
      address: r.address || null,
      city: r.city || null,
      state: STATE,
      zip: r.zip || null,
      latitude: r.latitude ?? null,
      longitude: r.longitude ?? null,
      geo_source: r.latitude ? "manual_curation" : null,
      geocoded_at: r.latitude ? new Date().toISOString() : null,
      eligibility: r.eligibility || "All veterans",
      subcategory: r.subcategory_name || null,
      source_name: r.source_name,
      source_type: r.source_type,
      status: r.status || "approved",
      sponsored: false,
    };

    const { data: ins, error } = await supabaseAdmin
      .from("resources")
      .insert(insertRow)
      .select("id")
      .single();

    if (error || !ins) {
      counts.errors++;
      counts.errorRows.push({ title: r.title, reason: error?.message || "Unknown insert error" });
      continue;
    }

    await supabaseAdmin
      .from("resource_categories")
      .upsert({ resource_id: ins.id, category_id }, { onConflict: "resource_id,category_id" });

    if (subcategory_id) {
      await supabaseAdmin
        .from("resource_subcategories")
        .upsert(
          { resource_id: ins.id, subcategory_id },
          { onConflict: "resource_id,subcategory_id" }
        );
    }

    counts.created++;
    counts.byCategory[r.category_slug] = (counts.byCategory[r.category_slug] || 0) + 1;
    if (r.subcategory_name) {
      counts.bySubcategory[r.subcategory_name] = (counts.bySubcategory[r.subcategory_name] || 0) + 1;
    }
    existingTitles.add(titleKey);
  }

  console.log(`\n=== ROUND 2 RESULTS ===`);
  console.log(`Total rows in script : ${NC_RESOURCES.length}`);
  console.log(`Created              : ${counts.created}`);
  console.log(`Duplicates skipped   : ${counts.duplicates}`);
  console.log(`Errors               : ${counts.errors}`);
  console.log(`Subcategory misses   : ${counts.subcategoryMisses}`);

  console.log(`\n--- By category ---`);
  Object.entries(counts.byCategory)
    .sort((a, b) => b[1] - a[1])
    .forEach(([k, v]) => console.log(`  ${k.padEnd(28)} ${v}`));

  console.log(`\n--- By subcategory (top 20) ---`);
  Object.entries(counts.bySubcategory)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .forEach(([k, v]) => console.log(`  ${k.padEnd(45)} ${v}`));

  if (counts.subMissList.length) {
    console.log(`\n--- Subcategory misses ---`);
    counts.subMissList.forEach(s => console.log(`  ${s.title} -> ${s.key}`));
  }

  if (counts.errorRows.length) {
    console.log(`\n--- Errors ---`);
    counts.errorRows.forEach(e => console.log(`  ${e.title}: ${e.reason}`));
  }
}

main().catch((e) => {
  console.error("FATAL:", e);
  process.exit(1);
});
