/**
 * Alabama Phase 6 — Elite Closeout (FAST COMPLETION MODE)
 *
 * Founder rule (locked 2026-04-25): Time/Cost Control — fast mode, no parity
 * scripts, no architect loops, verified easy wins only. Budget 10-20 min.
 *
 * Priorities:
 *   - Add 4 truly-missing county VSOs (Bullock/Choctaw/Lowndes/Perry)
 *   - Lift weak categories with high-confidence canonical orgs
 *   - Close Alabama as benchmark state, unlock California
 *
 * Sections:
 *   A = County VSOs (ADVA closeout)
 *   X = Crisis-help / DV / Children's Advocacy Centers
 *   I = Insurance (AL state programs + national veteran)
 *   M = Financial / Credit Unions / VITA
 *   L = Legal (state bar + advocacy)
 *   T = Transportation (Easter Seals + DAV networks)
 *   F = Family-support (BBBS + B&G Clubs)
 *   G = Food-assistance (food banks + ministries)
 *   D = Disabled-veterans (DAV chapters + adaptive)
 *   E = End-of-life (top-up)
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ===== A — County VSO completion (4 truly-missing counties) =====
  {
    section: "A", title: "Bullock County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "ADVA-accredited county veterans service office serving Bullock County. Free help with VA disability, pension, A&A, dependents/survivors, education, healthcare, and burial benefits.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 738-2670", address: "Bullock County Courthouse, 217 North Prairie Street",
    city: "Union Springs", zip: "36089",
    eligibility: "Veterans, surviving spouses and dependents",
    source_name: "ADVA County VSO Directory", source_type: "state_government",
  },
  {
    section: "A", title: "Choctaw County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "ADVA-accredited county veterans service office serving Choctaw County (and Sumter County, consolidated). Free help with VA disability, pension, A&A, dependents/survivors, education, healthcare, and burial benefits.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(205) 459-2100", address: "Choctaw County Courthouse, 117 South Mulberry Avenue",
    city: "Butler", zip: "36904",
    eligibility: "Veterans, surviving spouses and dependents",
    source_name: "ADVA County VSO Directory", source_type: "state_government",
  },
  {
    section: "A", title: "Lowndes County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "ADVA-accredited county veterans service office serving Lowndes County. Free help with VA disability, pension, A&A, dependents/survivors, education, healthcare, and burial benefits.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 548-2143", address: "Lowndes County Courthouse, 1 South Washington Street",
    city: "Hayneville", zip: "36040",
    eligibility: "Veterans, surviving spouses and dependents",
    source_name: "ADVA County VSO Directory", source_type: "state_government",
  },
  {
    section: "A", title: "Perry County Veterans Service Office",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "ADVA-accredited county veterans service office serving Perry County. Free help with VA disability, pension, A&A, dependents/survivors, education, healthcare, and burial benefits.",
    website_url: "https://va.alabama.gov/service-officer/",
    phone: "(334) 683-2200", address: "Perry County Courthouse, 300 Washington Street",
    city: "Marion", zip: "36756",
    eligibility: "Veterans, surviving spouses and dependents",
    source_name: "ADVA County VSO Directory", source_type: "state_government",
  },

  // ===== X — Crisis-help (DV shelters + Children's Advocacy Centers) =====
  {
    section: "X", title: "National Children's Advocacy Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "World's first child advocacy center (founded 1985, Huntsville) — model for the global CAC movement. Forensic interviewing, medical exams, mental health therapy, and family advocacy for child abuse victims. Trains professionals nationwide.",
    website_url: "https://www.nationalcac.org/",
    phone: "(256) 533-5437", address: "210 Pratt Avenue NE",
    city: "Huntsville", zip: "35801",
    eligibility: "Child abuse victims and families",
    source_name: "NCAC", source_type: "nonprofit",
  },
  {
    section: "X", title: "Prescott House Children's Advocacy Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Children's Advocacy Center serving Jefferson County. Forensic interviews, family advocacy, mental health services, and medical evaluations for child abuse victims.",
    website_url: "https://www.prescotthouse.net/",
    phone: "(205) 327-8888", address: "1330 9th Court South",
    city: "Birmingham", zip: "35205",
    eligibility: "Child abuse victims and non-offending family members",
    source_name: "Prescott House", source_type: "nonprofit",
  },
  {
    section: "X", title: "Child Protect Children's Advocacy Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Children's Advocacy Center serving Montgomery and surrounding River Region counties. Forensic interviews, mental health therapy, family advocacy, and medical evaluations for child abuse victims.",
    website_url: "https://childprotect.org/",
    phone: "(334) 262-1220", address: "108 Sayre Street",
    city: "Montgomery", zip: "36104",
    eligibility: "Child abuse victims and non-offending family members",
    source_name: "Child Protect", source_type: "nonprofit",
  },
  {
    section: "X", title: "Southeast Alabama Child Advocacy Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Children's Advocacy Center serving the Wiregrass region. Forensic interviewing, family advocacy, mental health services for child abuse victims across Houston, Henry, Geneva, Dale, Coffee, Pike, Barbour, Bullock counties.",
    website_url: "https://seacac.com/",
    phone: "(334) 671-1779", address: "1810 Westgate Pkwy, Suite 4",
    city: "Dothan", zip: "36303",
    eligibility: "Child abuse victims and non-offending family members",
    source_name: "SEACAC", source_type: "nonprofit",
  },
  {
    section: "X", title: "The Children's Center of Tuscaloosa",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Children's Advocacy Center serving Tuscaloosa, Bibb, Hale, Greene, Pickens, Fayette, Lamar, and Sumter counties. Forensic interviews, family advocacy, and trauma counseling for child abuse victims.",
    website_url: "https://childrenscentertuscaloosa.org/",
    phone: "(205) 752-3504", address: "2520 4th Street",
    city: "Tuscaloosa", zip: "35401",
    eligibility: "Child abuse victims and non-offending family members",
    source_name: "Children's Center Tuscaloosa", source_type: "nonprofit",
  },
  {
    section: "X", title: "Calhoun-Cleburne Children's Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Children's Advocacy Center serving Calhoun and Cleburne counties. Forensic interviews, family advocacy, and mental health support for child abuse victims.",
    website_url: "https://calhouncleburnechildrenscenter.org/",
    phone: "(256) 741-9445", address: "405 East 10th Street",
    city: "Anniston", zip: "36207",
    eligibility: "Child abuse victims and non-offending family members",
    source_name: "Calhoun-Cleburne CAC", source_type: "nonprofit",
  },
  {
    section: "X", title: "Penelope House Family Violence Center",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Emergency shelter, 24-hour crisis line, court advocacy, counseling, and transitional housing for survivors of domestic violence in Mobile and Baldwin counties.",
    website_url: "https://www.penelopehouse.org/",
    phone: "(251) 342-8994", address: "P.O. Box 9127",
    city: "Mobile", zip: "36691",
    eligibility: "Survivors of domestic violence and their children",
    source_name: "Penelope House", source_type: "nonprofit",
  },
  {
    section: "X", title: "Turning Point Domestic Violence Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Emergency shelter, 24-hour crisis line, court advocacy, counseling, and transitional housing for survivors of domestic and sexual violence across West Alabama (Tuscaloosa, Bibb, Fayette, Greene, Hale, Lamar, Pickens, Sumter).",
    website_url: "https://turningpointservices.org/",
    phone: "(205) 758-0808", address: "P.O. Box 1305",
    city: "Tuscaloosa", zip: "35403",
    eligibility: "Survivors of domestic and sexual violence",
    source_name: "Turning Point", source_type: "nonprofit",
  },
  {
    section: "X", title: "2nd Chance Inc — Domestic Violence Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Emergency shelter, 24-hour crisis line, court advocacy, and counseling for survivors of domestic violence across Calhoun, Cleburne, Cherokee, Etowah, Randolph, and Talladega counties.",
    website_url: "https://2ndchanceinc.org/",
    phone: "(256) 236-7233", address: "P.O. Box 1502",
    city: "Anniston", zip: "36202",
    eligibility: "Survivors of domestic violence and their children",
    source_name: "2nd Chance Inc", source_type: "nonprofit",
  },
  {
    section: "X", title: "One Place Family Justice Center (Mobile)",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "One-stop center co-locating police, prosecutors, advocates, attorneys, and counselors for survivors of domestic violence, sexual assault, child abuse, and elder abuse in the Gulf Coast region.",
    website_url: "https://www.oneplacefjc.org/",
    phone: "(251) 431-5111", address: "300 Government Street, Suite 100",
    city: "Mobile", zip: "36602",
    eligibility: "Victims of domestic violence and abuse",
    source_name: "One Place FJC", source_type: "nonprofit",
  },
  {
    section: "X", title: "Family Violence Project of Lee County",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "Emergency shelter, 24-hour crisis line, court advocacy, counseling, and transitional housing for domestic violence survivors in Lee, Russell, Chambers, Macon, and Tallapoosa counties.",
    website_url: "https://www.familyviolencecenter.org/",
    phone: "(334) 749-1515", address: "P.O. Box 2031",
    city: "Auburn", zip: "36831",
    eligibility: "Survivors of domestic violence and their children",
    source_name: "Family Violence Center Lee Co", source_type: "nonprofit",
  },

  // ===== I — Insurance (AL state programs + veteran-specific) =====
  {
    section: "I", title: "Alabama Department of Insurance",
    cat: "insurance", sub: "Health Insurance",
    desc: "State agency regulating insurance in Alabama. Consumer services division helps veterans and families with insurance complaints, fraud reports, and verifying licensed agents and companies.",
    website_url: "https://www.aldoi.gov/",
    phone: "(334) 269-3550", address: "201 Monroe Street, Suite 502",
    city: "Montgomery", zip: "36104",
    eligibility: "All Alabama residents",
    source_name: "AL Dept of Insurance", source_type: "state_government",
  },
  {
    section: "I", title: "Alabama Medicaid Agency",
    cat: "insurance", sub: "Health Insurance",
    desc: "Administers Medicaid in Alabama, including coverage for low-income veterans, their dependents, and surviving spouses who qualify. Long-term care, family planning, and disability programs.",
    website_url: "https://medicaid.alabama.gov/",
    phone: "(800) 362-1504", address: "501 Dexter Avenue",
    city: "Montgomery", zip: "36103",
    eligibility: "Low-income individuals meeting Medicaid criteria",
    source_name: "AL Medicaid Agency", source_type: "state_government",
  },
  {
    section: "I", title: "Alabama ALL Kids (CHIP)",
    cat: "insurance", sub: "Health Insurance",
    desc: "Alabama's Children's Health Insurance Program (CHIP) — low-cost health coverage for children of working families (including veteran families) up to age 19 who don't qualify for Medicaid.",
    website_url: "https://www.alabamapublichealth.gov/allkids/",
    phone: "(888) 373-5437", address: "201 Monroe Street",
    city: "Montgomery", zip: "36104",
    eligibility: "Children up to age 19 in qualifying families",
    source_name: "AL Department of Public Health", source_type: "state_government",
  },
  {
    section: "I", title: "TRICARE West Region",
    cat: "insurance", sub: "Health Insurance",
    desc: "TRICARE health plan administrator for the West Region (covering active-duty service members, retirees, and their families assigned to West Region installations and locations). 24/7 enrollment and claims support.",
    website_url: "https://tricare.mil/west",
    phone: "(844) 866-9378",
    eligibility: "Active duty, retirees, and family members enrolled in TRICARE West",
    source_name: "TRICARE", source_type: "federal_government",
  },
  {
    section: "I", title: "Patient Advocate Foundation",
    cat: "insurance", sub: "Health Insurance",
    desc: "National nonprofit providing case management and financial aid to patients (including veterans) with chronic, life-threatening, or debilitating diseases. Insurance appeals, debt crisis support, copay relief.",
    website_url: "https://www.patientadvocate.org/",
    phone: "(800) 532-5274",
    eligibility: "Patients with chronic or life-threatening illness",
    source_name: "Patient Advocate Foundation", source_type: "nonprofit",
  },
  {
    section: "I", title: "VA Veterans Group Life Insurance (VGLI)",
    cat: "insurance", sub: "Life Insurance",
    desc: "VA program allowing veterans to convert SGLI to renewable term insurance after separation. Coverage from $10,000 to $500,000 in $10,000 increments. No medical exam if applied within 240 days.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/vgli/",
    phone: "(800) 419-1473",
    eligibility: "Recently separated veterans (within 1 year, 120 days)",
    source_name: "US Department of Veterans Affairs", source_type: "federal_government",
  },
  {
    section: "I", title: "VA Service-Disabled Veterans Insurance (S-DVI)",
    cat: "insurance", sub: "Life Insurance",
    desc: "Life insurance for veterans with service-connected disabilities. Coverage up to $10,000 plus supplemental $30,000 for totally disabled veterans. Premiums waived for total disability.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/s-dvi/",
    phone: "(800) 669-8477",
    eligibility: "Veterans with service-connected disability rating",
    source_name: "US Department of Veterans Affairs", source_type: "federal_government",
  },
  {
    section: "I", title: "VA Veterans Mortgage Life Insurance (VMLI)",
    cat: "insurance", sub: "Life Insurance",
    desc: "Mortgage protection insurance for severely disabled veterans who received a Specially Adapted Housing grant. Coverage up to $200,000 paid directly to mortgage holder upon death.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/vmli/",
    phone: "(800) 669-8477",
    eligibility: "Veterans with SAH grant",
    source_name: "US Department of Veterans Affairs", source_type: "federal_government",
  },
  {
    section: "I", title: "AAFMAA — American Armed Forces Mutual Aid Association",
    cat: "insurance", sub: "Life Insurance",
    desc: "Member-owned military insurance and financial services nonprofit serving the military community since 1879. Life insurance, wealth management, mortgages, and survivor assistance.",
    website_url: "https://www.aafmaa.com/",
    phone: "(877) 398-2263",
    eligibility: "US military members, veterans, and families",
    source_name: "AAFMAA", source_type: "nonprofit",
  },
  {
    section: "I", title: "Navy Mutual Aid Association",
    cat: "insurance", sub: "Life Insurance",
    desc: "Nonprofit veterans service organization providing low-cost life insurance, education resources, and survivor benefit assistance to sea-services members (Navy, Marine Corps, Coast Guard) and families since 1879.",
    website_url: "https://www.navymutual.org/",
    phone: "(800) 628-6011",
    eligibility: "Sea-services members, veterans, and families",
    source_name: "Navy Mutual", source_type: "nonprofit",
  },

  // ===== M — Financial / Credit Unions / VITA =====
  {
    section: "M", title: "Family Security Credit Union",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Member-owned credit union serving North Alabama including military and veteran members at Redstone Arsenal area. Auto loans, mortgages, savings, and free financial education.",
    website_url: "https://www.fscu.com/",
    phone: "(256) 340-2000", address: "905 5th Avenue SE",
    city: "Decatur", zip: "35601",
    eligibility: "Members and family in service area",
    source_name: "Family Security Credit Union", source_type: "credit_union",
  },
  {
    section: "M", title: "Five Star Credit Union",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Member-owned credit union serving the Wiregrass and Gulf Coast region, including Fort Novosel-area military and veteran members. Auto loans, mortgages, military-friendly accounts.",
    website_url: "https://www.fivestarcu.com/",
    phone: "(888) 925-2557", address: "401 North Foster Street",
    city: "Dothan", zip: "36303",
    eligibility: "Members and family in service area",
    source_name: "Five Star Credit Union", source_type: "credit_union",
  },
  {
    section: "M", title: "Alabama Credit Union",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "University of Alabama-affiliated credit union serving members across Alabama, Florida, and Mississippi. Veteran-friendly mortgages, auto loans, and financial education programs.",
    website_url: "https://www.alabamacu.com/",
    phone: "(888) 817-2002", address: "220 Paul W. Bryant Drive East",
    city: "Tuscaloosa", zip: "35401",
    eligibility: "Members and family in service area",
    source_name: "Alabama Credit Union", source_type: "credit_union",
  },
  {
    section: "M", title: "Avadian Credit Union",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Member-owned credit union serving central Alabama with branches across the Birmingham metro. Free checking, auto and home loans, and member financial counseling.",
    website_url: "https://www.avadiancu.com/",
    phone: "(888) 282-3426", address: "1 Riverchase Parkway South",
    city: "Birmingham", zip: "35244",
    eligibility: "Members and family in service area",
    source_name: "Avadian Credit Union", source_type: "credit_union",
  },
  {
    section: "M", title: "Listerhill Credit Union",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Member-owned credit union serving the Shoals region of NW Alabama and southern Tennessee. Veteran-friendly accounts, auto loans, mortgages, and financial education.",
    website_url: "https://www.listerhill.com/",
    phone: "(800) 239-6033", address: "4790 Hwy 157",
    city: "Sheffield", zip: "35660",
    eligibility: "Members and family in service area",
    source_name: "Listerhill Credit Union", source_type: "credit_union",
  },
  {
    section: "M", title: "Operation HOPE Birmingham",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Free one-on-one financial coaching, credit counseling, homebuyer prep, small business launch support, and disaster recovery — co-located in Truist branches across Birmingham metro.",
    website_url: "https://operationhope.org/",
    phone: "(404) 941-2919",
    city: "Birmingham", zip: "35203",
    eligibility: "All US residents — no income requirement",
    source_name: "Operation HOPE", source_type: "nonprofit",
  },
  {
    section: "M", title: "Impact Alabama SaveFirst",
    cat: "financial", sub: "Tax Preparation",
    desc: "Free IRS-certified VITA tax preparation across Alabama for working families earning under ~$66k. College student and CPA volunteer-staffed sites in Birmingham, Tuscaloosa, Montgomery, Mobile, Huntsville.",
    website_url: "https://impactalabama.org/savefirst/",
    phone: "(205) 758-3624", address: "1320 University Boulevard",
    city: "Birmingham", zip: "35233",
    eligibility: "Working families earning under approximately $66,000",
    source_name: "Impact Alabama", source_type: "nonprofit",
  },
  {
    section: "M", title: "United Way of Central Alabama 211",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "211 information & referral hotline connecting central Alabama residents (including veterans) to emergency rent, utility, food, prescription, and crisis help. 24/7 multilingual.",
    website_url: "https://www.uwca.org/211/",
    phone: "(888) 421-1266", address: "3600 8th Avenue South",
    city: "Birmingham", zip: "35222",
    eligibility: "Central Alabama residents in need",
    source_name: "United Way Central AL", source_type: "nonprofit",
  },

  // ===== L — Legal =====
  {
    section: "L", title: "Birmingham Bar Volunteer Lawyers Program",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Free civil legal services for low-income Jefferson County residents (including veterans) — landlord/tenant, family, consumer, probate, simple wills, and benefits matters via volunteer attorneys.",
    website_url: "https://www.birminghambar.org/?pg=BVLP",
    phone: "(205) 250-5198", address: "2021 2nd Avenue North",
    city: "Birmingham", zip: "35203",
    eligibility: "Low-income Jefferson County residents",
    source_name: "Birmingham Bar Association", source_type: "bar_association",
  },
  {
    section: "L", title: "Alabama Disabilities Advocacy Program (ADAP)",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Federally-mandated Protection & Advocacy system for Alabama. Free legal advocacy for people with disabilities (including disabled veterans) on abuse/neglect, employment, education, voting, housing, and healthcare access.",
    website_url: "https://adap.ua.edu/",
    phone: "(800) 826-1675", address: "Box 870395",
    city: "Tuscaloosa", zip: "35487",
    eligibility: "Alabamians with disabilities",
    source_name: "ADAP", source_type: "state_government",
  },
  {
    section: "L", title: "Alabama State Bar Lawyer Referral Service",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Statewide attorney referral service. Initial 30-minute consultation for $25. Specialized panels including military/veterans, family, criminal, personal injury, and elder law.",
    website_url: "https://www.alabar.org/for-the-public/lawyer-referral-service/",
    phone: "(800) 392-5660", address: "415 Dexter Avenue",
    city: "Montgomery", zip: "36104",
    eligibility: "Anyone seeking legal counsel in Alabama",
    source_name: "Alabama State Bar", source_type: "bar_association",
  },
  {
    section: "L", title: "Alabama Appleseed Center for Law & Justice",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Statewide nonprofit advancing justice and equity in Alabama. Policy advocacy and direct services on criminal justice, payday lending, voting rights, and economic justice — including for veteran populations.",
    website_url: "https://www.alabamaappleseed.org/",
    phone: "(334) 263-0086", address: "P.O. Box 4334",
    city: "Montgomery", zip: "36103",
    eligibility: "Alabama residents needing civil justice advocacy",
    source_name: "AL Appleseed", source_type: "nonprofit",
  },
  {
    section: "L", title: "Cumberland School of Law Public Interest Program",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Samford University Cumberland School of Law clinical programs offering free legal services through the Civil Practice Clinic and Domestic Violence Clinic — supervised student attorneys.",
    website_url: "https://www.samford.edu/cumberlandlaw/clinics-externships",
    phone: "(205) 726-2848", address: "800 Lakeshore Drive",
    city: "Birmingham", zip: "35229",
    eligibility: "Income-qualified central Alabama residents",
    source_name: "Cumberland School of Law", source_type: "law_school",
  },
  {
    section: "L", title: "VA Accredited Attorney Search",
    cat: "legal", sub: "VA Benefits Appeals",
    desc: "Official VA tool to find accredited attorneys, claims agents, and VSO representatives authorized to assist with VA benefit claims. Critical for complex appeals.",
    website_url: "https://www.va.gov/ogc/apps/accreditation/index.asp",
    phone: "(800) 827-1000",
    eligibility: "Veterans and dependents needing VA claims representation",
    source_name: "US Department of Veterans Affairs", source_type: "federal_government",
  },

  // ===== T — Transportation =====
  {
    section: "T", title: "Easter Seals Central Alabama",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "Free and reduced-cost wheelchair-accessible transportation for seniors and people with disabilities (including disabled veterans) for medical appointments, work, and errands across the Birmingham metro.",
    website_url: "https://www.easterseals.com/centralal/",
    phone: "(205) 942-8711", address: "2185 Normandale Drive",
    city: "Montgomery", zip: "36111",
    eligibility: "Seniors and people with disabilities",
    source_name: "Easter Seals Central AL", source_type: "nonprofit",
  },
  {
    section: "T", title: "Easter Seals West Alabama",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "Wheelchair-accessible transportation, employment services, and rehabilitation programs for people with disabilities (including disabled veterans) in Tuscaloosa and surrounding West Alabama counties.",
    website_url: "https://www.easterseals.com/westal/",
    phone: "(205) 759-1211", address: "1110 6th Avenue East",
    city: "Tuscaloosa", zip: "35401",
    eligibility: "People with disabilities in West Alabama",
    source_name: "Easter Seals West AL", source_type: "nonprofit",
  },
  {
    section: "T", title: "DAV Transportation Network — Birmingham VAMC",
    cat: "transportation", sub: "Veteran Transportation Programs",
    desc: "Free DAV-volunteer-driven transportation to and from Birmingham VAMC for veterans needing medical appointments. Schedule through the Birmingham VAMC Voluntary Service office.",
    website_url: "https://www.dav.org/veterans/transportation-network/",
    phone: "(205) 933-8101 ext. 5772", address: "700 19th Street South",
    city: "Birmingham", zip: "35233",
    eligibility: "Veterans receiving care at Birmingham VAMC",
    source_name: "DAV", source_type: "vso",
  },
  {
    section: "T", title: "DAV Transportation Network — Tuscaloosa VAMC",
    cat: "transportation", sub: "Veteran Transportation Programs",
    desc: "Free DAV-volunteer-driven transportation to and from Tuscaloosa VAMC for veterans needing medical appointments. Schedule through the Tuscaloosa VAMC Voluntary Service office.",
    website_url: "https://www.dav.org/veterans/transportation-network/",
    phone: "(205) 554-2000", address: "3701 Loop Road East",
    city: "Tuscaloosa", zip: "35404",
    eligibility: "Veterans receiving care at Tuscaloosa VAMC",
    source_name: "DAV", source_type: "vso",
  },
  {
    section: "T", title: "DAV Transportation Network — Central Alabama VA (Montgomery)",
    cat: "transportation", sub: "Veteran Transportation Programs",
    desc: "Free DAV-volunteer-driven transportation to and from Central Alabama Veterans Health Care System (Montgomery and Tuskegee) for veterans needing medical appointments.",
    website_url: "https://www.dav.org/veterans/transportation-network/",
    phone: "(334) 727-0550 ext. 4250", address: "215 Perry Hill Road",
    city: "Montgomery", zip: "36109",
    eligibility: "Veterans receiving care at Central Alabama VA",
    source_name: "DAV", source_type: "vso",
  },
  {
    section: "T", title: "Veterans Transportation Service — Birmingham VA",
    cat: "transportation", sub: "Veteran Transportation Programs",
    desc: "VA-operated free transportation service for eligible veterans needing rides to and from VA medical facilities in the Birmingham VAMC catchment area. Includes wheelchair-accessible vans.",
    website_url: "https://www.va.gov/health-care/get-help-paying-expenses/vtp/",
    phone: "(205) 933-8101", address: "700 19th Street South",
    city: "Birmingham", zip: "35233",
    eligibility: "Eligible VA enrollees",
    source_name: "US Department of Veterans Affairs", source_type: "federal_government",
  },
  {
    section: "T", title: "Beneficiary Travel Self-Service System (BTSSS)",
    cat: "transportation", sub: "Veteran Transportation Programs",
    desc: "VA online portal for veterans to file mileage reimbursement claims for travel to VA medical appointments. Eligible veterans receive reimbursement at the GSA mileage rate.",
    website_url: "https://www.va.gov/health-care/get-reimbursed-for-travel-pay/",
    phone: "(855) 574-7292",
    eligibility: "Eligible veterans (service-connected, low-income, or other criteria)",
    source_name: "US Department of Veterans Affairs", source_type: "federal_government",
  },

  // ===== F — Family-support =====
  {
    section: "F", title: "Big Brothers Big Sisters of Greater Birmingham",
    cat: "family-support", sub: "Youth Programs",
    desc: "One-to-one volunteer mentoring matches for youth ages 6-18 in Jefferson, Shelby, St. Clair, Walker counties. Strong support for children of veterans and military families.",
    website_url: "https://bbbsbham.org/",
    phone: "(205) 251-7437", address: "1819 5th Avenue North",
    city: "Birmingham", zip: "35203",
    eligibility: "Youth ages 6-18 (including military/veteran families)",
    source_name: "BBBS Greater Birmingham", source_type: "nonprofit",
  },
  {
    section: "F", title: "Big Brothers Big Sisters of North Alabama",
    cat: "family-support", sub: "Youth Programs",
    desc: "One-to-one volunteer mentoring matches for youth ages 6-18 in Madison and surrounding North Alabama counties. Strong outreach to military and veteran family children at Redstone Arsenal.",
    website_url: "https://bbbsna.org/",
    phone: "(256) 880-2123", address: "2105 Clinton Avenue West, Suite 700",
    city: "Huntsville", zip: "35805",
    eligibility: "Youth ages 6-18 (including military/veteran families)",
    source_name: "BBBS North Alabama", source_type: "nonprofit",
  },
  {
    section: "F", title: "Boys & Girls Clubs of Central Alabama",
    cat: "family-support", sub: "Youth Programs",
    desc: "After-school and summer programs for youth ages 6-18 across the Birmingham metro. Academic support, character development, healthy lifestyles, and military family programming.",
    website_url: "https://www.bgcca.org/",
    phone: "(205) 942-2200", address: "1700 27th Court South",
    city: "Birmingham", zip: "35209",
    eligibility: "Youth ages 6-18",
    source_name: "BGCCA", source_type: "nonprofit",
  },
  {
    section: "F", title: "Boys & Girls Clubs of South Alabama",
    cat: "family-support", sub: "Youth Programs",
    desc: "After-school and summer programs for youth ages 6-18 across Mobile and Baldwin counties. Strong military family programming for Coast Guard and Reserve families on the Gulf Coast.",
    website_url: "https://bgcsalabama.org/",
    phone: "(251) 438-5662", address: "P.O. Box 1364",
    city: "Mobile", zip: "36633",
    eligibility: "Youth ages 6-18",
    source_name: "BGC South Alabama", source_type: "nonprofit",
  },
  {
    section: "F", title: "Military Family Readiness Center — Maxwell-Gunter AFB",
    cat: "family-support", sub: "Military Family Support",
    desc: "Air Force Military & Family Readiness Center serving active-duty, Guard, Reserve, retiree, and family populations at Maxwell-Gunter. Deployment support, financial counseling, EFMP, transition assistance.",
    website_url: "https://www.maxwell.af.mil/",
    phone: "(334) 953-2353",
    city: "Montgomery", zip: "36112",
    eligibility: "Active-duty, Guard, Reserve, retirees, and family members",
    source_name: "Maxwell AFB M&FRC", source_type: "federal_government",
  },

  // ===== G — Food-assistance =====
  {
    section: "G", title: "Greater Birmingham Ministries",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Emergency food pantry, clothing closet, financial assistance, and immigration legal services for low-income residents (including veterans) across the Birmingham metro.",
    website_url: "https://gbm.org/",
    phone: "(205) 326-6821", address: "2304 12th Avenue North",
    city: "Birmingham", zip: "35234",
    eligibility: "Low-income Birmingham metro residents",
    source_name: "GBM", source_type: "nonprofit",
  },
  {
    section: "G", title: "Christian Service Mission",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Free food, clothing, household items, and addiction recovery programs for individuals and families in Birmingham (including homeless and near-homeless veterans).",
    website_url: "https://csmissions.org/",
    phone: "(205) 252-8316", address: "3600 3rd Avenue South",
    city: "Birmingham", zip: "35222",
    eligibility: "Anyone in need",
    source_name: "Christian Service Mission", source_type: "nonprofit",
  },
  {
    section: "G", title: "Manna House",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Free food pantry serving Madison County families (including veterans) — fresh produce, meat, dairy, and shelf-stable groceries weekly. No appointment required.",
    website_url: "https://mannahousehsv.org/",
    phone: "(256) 503-4848", address: "2110 South Memorial Parkway",
    city: "Huntsville", zip: "35801",
    eligibility: "Madison County residents in need",
    source_name: "Manna House Huntsville", source_type: "nonprofit",
  },
  {
    section: "G", title: "Food Bank of North Alabama",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank distributing food to 250+ partner agencies (pantries, soup kitchens, shelters) across 11 North Alabama counties. Direct mobile pantries and SNAP outreach.",
    website_url: "https://foodbanknorthal.org/",
    phone: "(256) 539-2256", address: "4475 Evangel Circle NW",
    city: "Huntsville", zip: "35816",
    eligibility: "Partner agencies serving food-insecure families",
    source_name: "Food Bank of North AL", source_type: "nonprofit",
  },
  {
    section: "G", title: "Heart of Alabama Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 35 central Alabama counties. Distributes food through 400+ partner agencies including pantries, soup kitchens, shelters, and senior programs.",
    website_url: "https://hoafb.org/",
    phone: "(334) 263-3784", address: "521 Trade Center Street",
    city: "Montgomery", zip: "36108",
    eligibility: "Partner agencies serving food-insecure families",
    source_name: "Heart of AL Food Bank", source_type: "nonprofit",
  },
  {
    section: "G", title: "West Alabama Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank distributing food across 9 West Alabama counties (Tuscaloosa, Pickens, Greene, Hale, Bibb, Fayette, Lamar, Marion, Sumter) to 200+ partner agencies.",
    website_url: "https://www.westalabamafoodbank.org/",
    phone: "(205) 333-3320", address: "9550 Robert Cardinal Airport Road",
    city: "Northport", zip: "35476",
    eligibility: "Partner agencies serving food-insecure families",
    source_name: "West AL Food Bank", source_type: "nonprofit",
  },
  {
    section: "G", title: "Bay Area Food Bank (Feeding the Gulf Coast)",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Regional food bank serving 24 counties across coastal Alabama, Mississippi, and Florida Panhandle. Mobile pantries, child nutrition programs, and SNAP outreach for veterans and families.",
    website_url: "https://feedingthegulfcoast.org/",
    phone: "(251) 653-1617", address: "5248 Mobile South Street",
    city: "Theodore", zip: "36582",
    eligibility: "Partner agencies serving food-insecure families",
    source_name: "Feeding the Gulf Coast", source_type: "nonprofit",
  },

  // ===== D — Disabled-veterans =====
  {
    section: "D", title: "DAV Chapter 1 Birmingham",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "Local DAV chapter serving disabled veterans in the Birmingham metro. Free benefits assistance, transportation network coordination, and veteran outreach activities.",
    website_url: "https://www.davalabama.org/chapter-locator",
    phone: "(205) 933-8101",
    city: "Birmingham", zip: "35233",
    eligibility: "Disabled veterans and dependents",
    source_name: "DAV Alabama", source_type: "vso",
  },
  {
    section: "D", title: "DAV Chapter 6 Tuscaloosa",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "Local DAV chapter serving disabled veterans in Tuscaloosa and West Alabama. Free benefits assistance, transportation coordination, and veteran outreach activities.",
    website_url: "https://www.davalabama.org/chapter-locator",
    phone: "(205) 554-2000",
    city: "Tuscaloosa", zip: "35404",
    eligibility: "Disabled veterans and dependents",
    source_name: "DAV Alabama", source_type: "vso",
  },
  {
    section: "D", title: "DAV Chapter 24 Montgomery",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "Local DAV chapter serving disabled veterans in Montgomery and the River Region. Free benefits assistance, transportation coordination, and veteran outreach activities.",
    website_url: "https://www.davalabama.org/chapter-locator",
    phone: "(334) 727-0550",
    city: "Montgomery", zip: "36109",
    eligibility: "Disabled veterans and dependents",
    source_name: "DAV Alabama", source_type: "vso",
  },
  {
    section: "D", title: "Paralyzed Veterans of America — Mid-South Chapter",
    cat: "disabled-veterans", sub: "Healthcare & Rehabilitation",
    desc: "PVA chapter serving veterans with spinal cord injuries and disorders across Tennessee, Mississippi, Arkansas, and northern Alabama. Benefits, advocacy, sports/recreation programs.",
    website_url: "https://midsouth.pva.org/",
    phone: "(901) 327-9789", address: "1267 Madison Avenue",
    city: "Memphis", zip: "38104",
    eligibility: "Veterans with spinal cord injuries (regional)",
    source_name: "PVA", source_type: "vso",
  },
  {
    section: "D", title: "Lakeshore Foundation Lima Foxtrot",
    cat: "disabled-veterans", sub: "Adaptive Recreation",
    desc: "Adaptive sports, recreation, and wellness programming specifically for injured military service members and veterans at the Lakeshore Foundation in Birmingham. Free week-long camps and ongoing programs.",
    website_url: "https://www.lakeshore.org/military-veterans/",
    phone: "(205) 313-7400", address: "4000 Ridgeway Drive",
    city: "Birmingham", zip: "35209",
    eligibility: "Injured military service members and veterans",
    source_name: "Lakeshore Foundation", source_type: "nonprofit",
  },

  // ===== E — End-of-life (top-up) =====
  {
    section: "E", title: "Hospice of Marshall County",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Nonprofit community hospice providing end-of-life care, pain management, family support, and bereavement services for Marshall County residents (including veterans) since 1979.",
    website_url: "https://www.hospiceofmc.org/",
    phone: "(256) 891-7724", address: "8202 US Highway 431",
    city: "Albertville", zip: "35950",
    eligibility: "Patients with terminal diagnosis (any age)",
    source_name: "Hospice of Marshall County", source_type: "nonprofit",
  },
  {
    section: "E", title: "Hospice of West Alabama",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Nonprofit community hospice providing end-of-life care, pain management, family support, and bereavement services for the Tuscaloosa region (including veterans). We Honor Veterans Level 4 partner.",
    website_url: "https://hospiceofwestalabama.com/",
    phone: "(205) 523-0101", address: "3851 Loop Road East",
    city: "Tuscaloosa", zip: "35404",
    eligibility: "Patients with terminal diagnosis",
    source_name: "Hospice of West AL", source_type: "nonprofit",
  },
  {
    section: "E", title: "Hospice of EAMC (East Alabama Medical Center)",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Hospital-affiliated hospice serving Lee County and surrounding East Alabama with end-of-life care, pain management, family support, and bereavement services. We Honor Veterans partner.",
    website_url: "https://www.eamc.org/services/hospice/",
    phone: "(334) 528-1260", address: "2153 Frederick Road",
    city: "Opelika", zip: "36801",
    eligibility: "Patients with terminal diagnosis",
    source_name: "EAMC Hospice", source_type: "hospital_system",
  },
];

runSeed(ROWS, {
  state: "AL",
  commit: COMMIT,
  scriptName: "seed-al-phase6",
  sectionLabels: {
    A: "County VSO closeout (4 missing counties)",
    X: "Crisis-help / DV / Children's Advocacy Centers",
    I: "Insurance (state programs + VA + military)",
    M: "Financial / Credit Unions / VITA",
    L: "Legal (Bar VLPs + advocacy + clinics)",
    T: "Transportation (Easter Seals + DAV networks)",
    F: "Family-support (BBBS + B&G + military M&FRC)",
    G: "Food-assistance (food banks + ministries)",
    D: "Disabled-veterans (DAV chapters + PVA + adaptive)",
    E: "End-of-life (community hospice top-up)",
  },
});
