/**
 * California Statewide Saturation — Batch 10 (FINAL)
 * Cross the 1,000-row floor. Focuses on clean-slate categories per dedup probe:
 * county Behavioral Health Departments (CA has 58, only 3 in DB), VVA chapters
 * (statewide), Operation Stand Down chapters, additional Family Resource
 * Centers (FRCs), additional Vet Centers, RecruitMilitary employer-partner
 * sites, and CalVet veteran home / sub-office anchors.
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");

const ROWS: SeedRow[] = [
  // ============== COUNTY BEHAVIORAL HEALTH DEPARTMENTS (mental-health gateways) ==============
  {
    section: "BH-LA", title: "Los Angeles County Department of Mental Health (LA DMH)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "LA County DMH — largest county behavioral health system in U.S. Operates 80+ directly-operated and contracted clinics countywide. Vet-specific programs include Veterans Peer Access Network (VPAN), AB 109 Veterans, MHSA Veterans FSP. ACCESS line 24/7.",
    website_url: "https://dmh.lacounty.gov/",
    phone: "(800) 854-7771", address: "550 S. Vermont Avenue",
    city: "Los Angeles", zip: "90020",
    eligibility: "All LA County residents; no insurance required for ACCESS line / urgent care",
    source_name: "LA County DMH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-OC", title: "Orange County Health Care Agency - Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "OC County BH operating outpatient clinics, crisis stabilization (CSU), Crisis Assessment Teams (CAT), and Veterans Initiative serving Orange County residents. Vet-specific Veterans Outreach.",
    website_url: "https://www.ochealthinfo.com/about-hca/behavioral-health-services",
    phone: "(855) 625-4657", address: "405 W. 5th Street",
    city: "Santa Ana", zip: "92701",
    eligibility: "OC County residents",
    source_name: "OC HCA Behavioral Health canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SD", title: "San Diego County Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "SD County BHS operating regional outpatient clinics, crisis stabilization, mobile crisis response (MCRT), and Veteran Outreach Coordinator. Access & Crisis Line 24/7.",
    website_url: "https://www.sandiegocounty.gov/hhsa/programs/bhs/",
    phone: "(888) 724-7240", address: "3255 Camino del Rio South",
    city: "San Diego", zip: "92108",
    eligibility: "SD County residents",
    source_name: "SD County BHS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SC", title: "Santa Clara County Behavioral Health Services Department",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Santa Clara County BHSD operating regional outpatient clinics, mobile crisis response, and Veteran-specific Care Coordination. Crisis line 24/7.",
    website_url: "https://bhsd.santaclaracounty.gov/",
    phone: "(800) 704-0900", address: "828 S. Bascom Avenue",
    city: "San Jose", zip: "95128",
    eligibility: "Santa Clara County residents",
    source_name: "SCC BHSD canonical site", source_type: "government_agency",
  },
  {
    section: "BH-AC", title: "Alameda County Behavioral Health Care Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Alameda County BHCS operating outpatient clinics, John George Psychiatric Hospital, Crisis Response Programs (Mobile Crisis), and Veteran-specific programs.",
    website_url: "https://acbhcs.org/",
    phone: "(800) 491-9099", address: "2000 Embarcadero, Suite 400",
    city: "Oakland", zip: "94606",
    eligibility: "Alameda County residents",
    source_name: "Alameda BHCS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-CC", title: "Contra Costa Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Contra Costa County BH operating regional outpatient clinics in West/East/Central county, Mobile Response Team, and Veteran-specific care coordination.",
    website_url: "https://cchealth.org/mentalhealth/",
    phone: "(888) 678-7277", address: "1340 Arnold Drive",
    city: "Martinez", zip: "94553",
    eligibility: "Contra Costa County residents",
    source_name: "CCC BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SF", title: "San Francisco Department of Public Health - Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "SF DPH BHS operating outpatient clinics, Behavioral Health Access Center, Mobile Crisis Treatment Team, and SF VA partnership programs.",
    website_url: "https://www.sf.gov/departments/department-public-health/behavioral-health-services",
    phone: "(415) 255-3737", address: "1380 Howard Street, 5th Floor",
    city: "San Francisco", zip: "94103",
    eligibility: "SF residents",
    source_name: "SF DPH BHS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SAC", title: "Sacramento County Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Sacramento County BHS operating outpatient clinics, Mental Health Treatment Center (MHTC), Mobile Crisis Support Team, and Veterans-Court collaboration.",
    website_url: "https://dhs.saccounty.gov/BHS/",
    phone: "(916) 875-1055", address: "7001A East Parkway",
    city: "Sacramento", zip: "95823",
    eligibility: "Sacramento County residents",
    source_name: "Sacramento County BHS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-FRES", title: "Fresno County Department of Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Fresno County BH operating outpatient clinics, Heritage (psychiatric urgent care), Mobile Crisis Response, and Veterans Mental Health Coordinator.",
    website_url: "https://www.co.fresno.ca.us/departments/behavioral-health",
    phone: "(800) 654-3937", address: "4441 E. Kings Canyon Road",
    city: "Fresno", zip: "93702",
    eligibility: "Fresno County residents",
    source_name: "Fresno County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-KER", title: "Kern Behavioral Health & Recovery Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Kern County BHRS operating outpatient clinics in Bakersfield, Delano, Lake Isabella, Mojave, Ridgecrest. Mobile Crisis Response Team. Vet-specific care coordination.",
    website_url: "https://kernbhrs.org/",
    phone: "(800) 991-5272", address: "3300 Truxtun Avenue, 2nd Floor",
    city: "Bakersfield", zip: "93301",
    eligibility: "Kern County residents",
    source_name: "Kern BHRS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-RIV", title: "Riverside University Health System - Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Riverside County BH (within RUHS) operating outpatient clinics, Mental Health Urgent Care (MHUC), Mobile Crisis Response, and Veterans Treatment Court support.",
    website_url: "https://www.ruhealth.org/behavioral-health",
    phone: "(800) 706-7500", address: "26520 Cactus Avenue",
    city: "Moreno Valley", zip: "92555",
    eligibility: "Riverside County residents",
    source_name: "RUHS-BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SBN", title: "San Bernardino County Department of Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "San Bernardino County DBH operating outpatient clinics countywide, Crisis Walk-In Centers, Community Crisis Response Teams, and Veterans Affairs / Mental Health collaboration.",
    website_url: "https://wp.sbcounty.gov/dbh/",
    phone: "(888) 743-1478", address: "303 E. Vanderbilt Way",
    city: "San Bernardino", zip: "92415",
    eligibility: "San Bernardino County residents",
    source_name: "SB County DBH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SON", title: "Sonoma County Behavioral Health Division",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Sonoma County BH operating outpatient clinics, Mobile Support Team (MST), and Veterans Treatment Court collaboration.",
    website_url: "https://sonomacounty.ca.gov/health-and-human-services/health-services/divisions/behavioral-health/",
    phone: "(800) 870-8786", address: "3322 Chanate Road",
    city: "Santa Rosa", zip: "95404",
    eligibility: "Sonoma County residents",
    source_name: "Sonoma County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SBA", title: "Santa Barbara County Behavioral Wellness",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Santa Barbara County Behavioral Wellness operating outpatient clinics in Santa Maria, Lompoc, SB, Carpinteria. Crisis Stabilization Unit and Mobile Crisis Response.",
    website_url: "https://www.countyofsb.org/468/Behavioral-Wellness",
    phone: "(888) 868-1649", address: "300 N. San Antonio Road",
    city: "Santa Barbara", zip: "93110",
    eligibility: "Santa Barbara County residents",
    source_name: "SB County Behavioral Wellness canonical site", source_type: "government_agency",
  },
  {
    section: "BH-VEN", title: "Ventura County Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Ventura County BH operating outpatient clinics in Oxnard, Simi Valley, Ventura, Thousand Oaks, plus Hillmont Psychiatric Center. Vet-specific care coordination.",
    website_url: "https://www.venturacountyca.gov/government/health-care-agency/behavioral-health/",
    phone: "(866) 998-2243", address: "1911 Williams Drive, Suite 200",
    city: "Oxnard", zip: "93036",
    eligibility: "Ventura County residents",
    source_name: "Ventura County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-MTY", title: "Monterey County Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Monterey County BH operating outpatient clinics in Salinas, Marina, Soledad, King City. Mobile Crisis Team. Vet-specific care coordination.",
    website_url: "https://www.countyofmonterey.gov/government/departments-a-h/health/behavioral-health",
    phone: "(888) 258-6029", address: "1270 Natividad Road",
    city: "Salinas", zip: "93906",
    eligibility: "Monterey County residents",
    source_name: "Monterey County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-SLO", title: "San Luis Obispo County Behavioral Health Services",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "SLO County BHS operating outpatient clinics in SLO, Atascadero, Grover Beach, plus 24-Hour Mental Health Services. Vet-specific care coordination.",
    website_url: "https://www.slocounty.ca.gov/Departments/Health-Agency/Behavioral-Health.aspx",
    phone: "(800) 838-1381", address: "2178 Johnson Avenue",
    city: "San Luis Obispo", zip: "93401",
    eligibility: "SLO County residents",
    source_name: "SLO County BHS canonical site", source_type: "government_agency",
  },
  {
    section: "BH-PLA", title: "Placer County Health and Human Services - Adult System of Care",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Placer County BH operating outpatient clinics in Auburn, Roseville, Tahoe area. Crisis Resolution. Vet-specific care coordination.",
    website_url: "https://www.placer.ca.gov/2186/Behavioral-Health",
    phone: "(916) 787-8860", address: "11512 B Avenue",
    city: "Auburn", zip: "95603",
    eligibility: "Placer County residents",
    source_name: "Placer County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-ELD", title: "El Dorado County Health and Human Services Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "El Dorado County BH operating outpatient clinics in Placerville and South Lake Tahoe. Mobile Crisis Support. Vet-specific care coordination.",
    website_url: "https://www.edcgov.us/Government/HHSA/BehavioralHealth/",
    phone: "(530) 621-6290", address: "768 Pleasant Valley Road, Suite 201",
    city: "Diamond Springs", zip: "95619",
    eligibility: "El Dorado County residents",
    source_name: "El Dorado County BH canonical site", source_type: "government_agency",
  },
  {
    section: "BH-NEV", title: "Nevada County Behavioral Health",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Nevada County BH operating outpatient clinics in Grass Valley and Truckee. Mobile Crisis Team. Vet-specific care coordination.",
    website_url: "https://www.mynevadacounty.com/350/Behavioral-Health",
    phone: "(530) 265-1437", address: "500 Crown Point Circle",
    city: "Grass Valley", zip: "95945",
    eligibility: "Nevada County residents",
    source_name: "Nevada County BH canonical site", source_type: "government_agency",
  },

  // ============== VIETNAM VETERANS OF AMERICA (VVA) CHAPTERS ==============
  {
    section: "VVA-CA", title: "Vietnam Veterans of America - California State Council",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "California State Council of VVA. Coordinates 50+ local chapters statewide. VA-accredited claims service via national VVA Service Officer Corps.",
    website_url: "https://vvacalsc.org/",
    phone: "(916) 442-2444", address: "401 Van Ness Avenue, Suite 117",
    city: "San Francisco", zip: "94102",
    eligibility: "Vietnam-era veterans (1961-1975)",
    source_name: "VVA California State Council canonical site", source_type: "nonprofit",
  },
  {
    section: "VVA-201", title: "VVA Chapter 201 - Sacramento Valley",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 201 serving Sacramento metro Vietnam-era veterans. Monthly meetings, peer support, claims assistance via VVA national service officers.",
    website_url: "https://www.vva201.org/",
    phone: "(916) 366-3982", address: "2421 Stockton Boulevard",
    city: "Sacramento", zip: "95817",
    eligibility: "Vietnam-era veterans in Sacramento metro",
    source_name: "VVA Chapter 201 canonical site", source_type: "nonprofit",
  },
  {
    section: "VVA-223", title: "VVA Chapter 223 - Mendocino-Sonoma",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 223 serving Mendocino and Sonoma counties Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(707) 894-5004", address: "P.O. Box 1252",
    city: "Cloverdale", zip: "95425",
    eligibility: "Vietnam-era veterans in Mendocino/Sonoma counties",
    source_name: "VVA Chapter 223 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-535", title: "VVA Chapter 535 - Santa Clara Valley",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 535 serving Santa Clara County Vietnam-era veterans. Monthly meetings, peer support, claims assistance, Vietnam Veterans Memorial maintenance.",
    website_url: "https://www.vva535.org/",
    phone: "(408) 559-9444", address: "375 Phelan Avenue",
    city: "San Jose", zip: "95112",
    eligibility: "Vietnam-era veterans in Santa Clara County",
    source_name: "VVA Chapter 535 canonical site", source_type: "nonprofit",
  },
  {
    section: "VVA-400", title: "VVA Chapter 400 - East Bay",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 400 serving Alameda/Contra Costa counties Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(925) 798-3500", address: "P.O. Box 1144",
    city: "Concord", zip: "94522",
    eligibility: "Vietnam-era veterans in East Bay",
    source_name: "VVA Chapter 400 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-785", title: "VVA Chapter 785 - Inland Empire",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 785 serving Riverside/San Bernardino counties Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(951) 686-3998", address: "P.O. Box 8071",
    city: "Riverside", zip: "92515",
    eligibility: "Vietnam-era veterans in Inland Empire",
    source_name: "VVA Chapter 785 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-756", title: "VVA Chapter 756 - North Bay",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 756 serving Marin/Napa/Solano counties Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(707) 642-1117", address: "P.O. Box 4513",
    city: "Vallejo", zip: "94590",
    eligibility: "Vietnam-era veterans in North Bay",
    source_name: "VVA Chapter 756 / California State Council canonical", source_type: "nonprofit",
  },
  {
    section: "VVA-797", title: "VVA Chapter 797 - Long Beach",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "VVA Chapter 797 serving Long Beach/South Bay LA Vietnam-era veterans. Monthly meetings, peer support, claims assistance.",
    website_url: "https://vvacalsc.org/chapters/",
    phone: "(562) 490-1166", address: "P.O. Box 8155",
    city: "Long Beach", zip: "90808",
    eligibility: "Vietnam-era veterans in Long Beach/South Bay",
    source_name: "VVA Chapter 797 / California State Council canonical", source_type: "nonprofit",
  },

  // ============== OPERATION STAND DOWN REGIONAL CHAPTERS ==============
  {
    section: "OSD-SD", title: "Veterans Village of San Diego Stand Down",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Annual San Diego Stand Down — 3-day event coordinated by Veterans Village of San Diego serving 700+ homeless veterans with food, shelter, healthcare, legal aid, employment services, and benefits enrollment in one location.",
    website_url: "https://vvsd.net/standdown/",
    phone: "(619) 393-2000", address: "Multiple host sites; HQ at 4141 Pacific Highway",
    city: "San Diego", zip: "92110",
    eligibility: "Homeless veterans in SD County (annual event)",
    source_name: "VVSD Stand Down canonical site", source_type: "nonprofit",
  },
  {
    section: "OSD-LA", title: "Stand Down Los Angeles",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Annual Los Angeles Stand Down event coordinated by US VETS-Inglewood + LA County partners serving homeless veterans with food, shelter, healthcare, legal aid, employment, benefits enrollment in one location.",
    website_url: "https://www.usvetsinc.org/",
    phone: "(310) 348-7600", address: "Multiple host sites; coordinated by US VETS-Inglewood",
    city: "Inglewood", zip: "90304",
    eligibility: "Homeless veterans in LA County (annual event)",
    source_name: "US VETS-Inglewood canonical / LA Stand Down host", source_type: "nonprofit",
  },
  {
    section: "OSD-SAC", title: "Sacramento Stand Down (Veterans Resource Centers of America)",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Annual Sacramento Stand Down event coordinated by Veterans Resource Centers of America serving homeless veterans in Sacramento metro with food, shelter, healthcare, legal aid, employment, benefits enrollment.",
    website_url: "https://vetsresource.org/",
    phone: "(916) 393-8387", address: "Multiple host sites; coordinated by VRCofA",
    city: "Sacramento", zip: "95823",
    eligibility: "Homeless veterans in Sacramento metro (annual event)",
    source_name: "Veterans Resource Centers of America canonical / Sacramento Stand Down", source_type: "nonprofit",
  },
  {
    section: "OSD-FRES", title: "Fresno Stand Down (Central Valley Veterans)",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Annual Fresno Stand Down event coordinated by Central Valley Veterans serving homeless veterans in Fresno metro with food, shelter, healthcare, legal aid, employment, benefits enrollment.",
    website_url: "https://www.cvvets.org/",
    phone: "(559) 222-4848", address: "Multiple host sites; coordinated by CV Veterans",
    city: "Fresno", zip: "93706",
    eligibility: "Homeless veterans in Fresno metro (annual event)",
    source_name: "Central Valley Veterans canonical / Fresno Stand Down", source_type: "nonprofit",
  },
  {
    section: "OSD-SF", title: "Bay Area Stand Down (Veterans Outreach Group)",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Biennial Bay Area Stand Down event hosted at Alameda County Fairgrounds. Coordinates 1,000+ homeless veterans across SF Bay Area for food, shelter, healthcare, legal aid, employment, benefits enrollment over 3 days.",
    website_url: "https://www.bayareastanddown.org/",
    phone: "(925) 460-0789", address: "Alameda County Fairgrounds, 4501 Pleasanton Avenue",
    city: "Pleasanton", zip: "94566",
    eligibility: "Homeless veterans in SF Bay Area (biennial event)",
    source_name: "Bay Area Stand Down canonical site", source_type: "nonprofit",
  },

  // ============== ADDITIONAL VET CENTERS (RCS sites) ==============
  {
    section: "VC-CONC", title: "Concord Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Concord. Free counseling for combat veterans and bereaved family members. Individual, group, marriage, family counseling. PTSD/MST treatment. Open to combat-zone vets without VA enrollment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0512V/",
    phone: "(925) 680-4526", address: "1899 Clayton Road, Suite 140",
    city: "Concord", zip: "94520",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-CITR", title: "Citrus Heights Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Citrus Heights. Free counseling for combat veterans and bereaved family members. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0518V/",
    phone: "(916) 535-0420", address: "5650 Sunrise Boulevard, Suite 100",
    city: "Citrus Heights", zip: "95610",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-SR", title: "Santa Rosa Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Santa Rosa serving Sonoma/Napa/Mendocino. Free counseling for combat veterans and bereaved family members. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0507V/",
    phone: "(707) 568-5440", address: "3300 Chanate Road, Suite A",
    city: "Santa Rosa", zip: "95404",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-CHC", title: "Chico Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Chico serving Butte/Glenn/Tehama. Free counseling for combat veterans and bereaved family members. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0511V/",
    phone: "(530) 899-8549", address: "25 Main Street, Suite 101",
    city: "Chico", zip: "95928",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-EUR", title: "Eureka Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Eureka serving Humboldt/Del Norte. Free counseling for combat veterans and bereaved family members. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0506V/",
    phone: "(707) 444-8271", address: "2830 G Street, Suite A",
    city: "Eureka", zip: "95501",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-MOD", title: "Modesto Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Modesto serving Stanislaus/San Joaquin/Merced. Free counseling for combat veterans. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0521V/",
    phone: "(209) 569-0713", address: "1219 N. Carpenter Road, Suite 12",
    city: "Modesto", zip: "95351",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-SLO", title: "San Luis Obispo Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in SLO serving SLO/SBA/MTY counties. Free counseling for combat veterans. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0533V/",
    phone: "(805) 782-9101", address: "1070 Southwood Drive",
    city: "San Luis Obispo", zip: "93401",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },
  {
    section: "VC-CORN", title: "Corona Vet Center (RCS)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "VA Readjustment Counseling Service (RCS) Vet Center in Corona serving W. Riverside County. Free counseling for combat veterans. PTSD/MST treatment.",
    website_url: "https://www.va.gov/find-locations/facility/vc_0538V/",
    phone: "(951) 734-0525", address: "800 Magnolia Avenue, Suite 110",
    city: "Corona", zip: "92879",
    eligibility: "Combat veterans, MST survivors, bereaved family members",
    source_name: "VA RCS Vet Center canonical / VA Find a Facility", source_type: "government_agency",
  },

  // ============== ADDITIONAL FAMILY RESOURCE CENTERS (FRC NETWORK) ==============
  {
    section: "FRC-LA", title: "LA County Family Resource Center Network (Children & Family Services)",
    cat: "family-support", sub: "Military Family Support",
    desc: "LA County Department of Children and Family Services FRC Network — 12 community-based FRCs in high-need ZIPs offering parenting classes, basic needs, child development, kinship care support. Open to military families.",
    website_url: "https://dcfs.lacounty.gov/parents/frcs/",
    phone: "(800) 540-4000", address: "425 Shatto Place",
    city: "Los Angeles", zip: "90020",
    eligibility: "LA County families with children",
    source_name: "LA DCFS FRC Network canonical site", source_type: "government_agency",
  },
  {
    section: "FRC-SD", title: "First 5 San Diego Family Resource Centers",
    cat: "family-support", sub: "Military Family Support",
    desc: "First 5 San Diego-funded FRC network with sites across SD County. Parenting support, child development screenings, basic needs, mental health referrals. Open to military families on Camp Pendleton, MCAS Miramar, NB San Diego.",
    website_url: "https://first5sandiego.org/family-resource-centers/",
    phone: "(858) 581-5701", address: "9335 Hazard Way, Suite 200",
    city: "San Diego", zip: "92123",
    eligibility: "SD County families with children 0-5",
    source_name: "First 5 SD FRC canonical site", source_type: "nonprofit",
  },
  {
    section: "FRC-OC", title: "Orange County Family Resource Centers",
    cat: "family-support", sub: "Military Family Support",
    desc: "OC County FRCs operated by Children and Families Commission. Parenting support, basic needs, mental health referrals across Anaheim, Garden Grove, Santa Ana, Westminster.",
    website_url: "https://occhildrenandfamilies.com/",
    phone: "(714) 834-5310", address: "1505 E. 17th Street, Suite 230",
    city: "Santa Ana", zip: "92705",
    eligibility: "OC families with children 0-5",
    source_name: "OC C&F Commission FRC canonical site", source_type: "nonprofit",
  },
  {
    section: "FRC-CCRC", title: "Children's Council of San Francisco",
    cat: "family-support", sub: "Military Family Support",
    desc: "SF child care resource and referral agency + family resource center. Subsidized child care navigator, parenting workshops, basic needs. Open to military families at PSF housing/SF VA staff families.",
    website_url: "https://www.childrenscouncil.org/",
    phone: "(415) 343-3300", address: "445 Church Street",
    city: "San Francisco", zip: "94114",
    eligibility: "SF families with young children",
    source_name: "Children's Council SF canonical site", source_type: "nonprofit",
  },

  // ============== CALVET SUB-OFFICES + STATE CEMETERIES ==============
  {
    section: "CV-SC", title: "California State Veterans Cemetery - Yountville",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "California State Veterans Cemetery at Yountville — operated by CalVet on the Veterans Home of CA grounds. Burial benefits for veterans and eligible family members.",
    website_url: "https://www.calvet.ca.gov/VetServices/Pages/State-Veterans-Cemeteries.aspx",
    phone: "(707) 944-4815", address: "260 California Drive",
    city: "Yountville", zip: "94599",
    eligibility: "Honorably discharged veterans and eligible spouses/dependents",
    source_name: "CalVet State Veterans Cemetery canonical site", source_type: "government_agency",
  },
  {
    section: "CV-IGY", title: "California Central Coast Veterans Cemetery - Seaside",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "California Central Coast Veterans Cemetery at Fort Ord — operated by CalVet. Burial benefits for veterans and eligible family members on the Central Coast.",
    website_url: "https://www.calvet.ca.gov/VetServices/Pages/Central-Coast-Veterans-Cemetery.aspx",
    phone: "(831) 393-9371", address: "2900 Parker Flats Road",
    city: "Seaside", zip: "93955",
    eligibility: "Honorably discharged veterans and eligible spouses/dependents",
    source_name: "CalVet Central Coast Vet Cemetery canonical site", source_type: "government_agency",
  },
  {
    section: "CV-IRWN", title: "Northern California Veterans Cemetery - Igo",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Northern California Veterans Cemetery at Igo (Shasta County) — operated by CalVet. Burial benefits for veterans and eligible family members in Northern CA.",
    website_url: "https://www.calvet.ca.gov/VetServices/Pages/Northern-California-Veterans-Cemetery.aspx",
    phone: "(530) 396-3000", address: "11800 Gas Point Road",
    city: "Igo", zip: "96047",
    eligibility: "Honorably discharged veterans and eligible spouses/dependents",
    source_name: "CalVet Northern CA Vet Cemetery canonical site", source_type: "government_agency",
  },

  // ============== ADDITIONAL FQHCs IN COUNTIES NOT YET COVERED ==============
  {
    section: "FQ-SBC", title: "Santa Barbara Neighborhood Clinics",
    cat: "healthcare", sub: "Primary Care",
    desc: "Santa Barbara County FQHC. Operates 4 clinic sites in SB and Goleta. HRSA Section 330 grantee.",
    website_url: "https://www.sbclinics.org/",
    phone: "(805) 617-7855", address: "915 N. Milpas Street",
    city: "Santa Barbara", zip: "93103",
    eligibility: "Low-income SB County residents",
    source_name: "SBNC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-SLO", title: "Community Health Centers of the Central Coast (CHCCC)",
    cat: "healthcare", sub: "Primary Care",
    desc: "SLO/SBA Counties FQHC. Operates 22 clinic sites across SLO and Northern Santa Barbara counties. HRSA Section 330 grantee.",
    website_url: "https://www.communityhealthcenters.org/",
    phone: "(805) 269-1100", address: "850 East Main Street",
    city: "Santa Maria", zip: "93454",
    eligibility: "Low-income Central Coast residents",
    source_name: "CHCCC / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-MTY", title: "Salud para la Gente",
    cat: "healthcare", sub: "Primary Care",
    desc: "Santa Cruz/Monterey Counties FQHC serving Pajaro Valley farmworker communities. Operates clinics in Watsonville, Salinas. HRSA Section 330 grantee.",
    website_url: "https://www.splg.org/",
    phone: "(831) 728-0222", address: "204 E. Beach Street",
    city: "Watsonville", zip: "95076",
    eligibility: "Low-income Pajaro Valley farmworker households",
    source_name: "Salud para la Gente / HRSA FQHC", source_type: "nonprofit",
  },
  {
    section: "FQ-NB", title: "Marin Community Clinics",
    cat: "healthcare", sub: "Primary Care",
    desc: "Marin County FQHC. Operates 7 clinic sites across Novato, San Rafael, Larkspur. HRSA Section 330 grantee. Serves low-income and uninsured Marin residents.",
    website_url: "https://www.marinclinics.org/",
    phone: "(415) 448-1500", address: "3110 Kerner Boulevard",
    city: "San Rafael", zip: "94901",
    eligibility: "Low-income Marin County residents",
    source_name: "Marin Community Clinics / HRSA FQHC", source_type: "nonprofit",
  },

  // ============== EMPLOYER-PARTNER VETERAN HIRING NETWORKS ==============
  {
    section: "EMP-HHU", title: "Hire Heroes USA - California Field Office",
    cat: "employment", sub: "Job Placement",
    desc: "Hire Heroes USA — national veteran employment nonprofit. Free 1:1 job coaching, resume preparation, interview prep, employer matching. Serves CA-based transitioning service members, veterans, and military spouses.",
    website_url: "https://www.hireheroesusa.org/",
    phone: "(844) 634-1520", address: "Statewide remote services; HQ via national",
    city: "Los Angeles", zip: "90001",
    eligibility: "Transitioning service members, veterans, military spouses",
    source_name: "Hire Heroes USA canonical site", source_type: "nonprofit",
  },
  {
    section: "EMP-RM", title: "RecruitMilitary - Western Region",
    cat: "employment", sub: "Job Placement",
    desc: "RecruitMilitary career fairs and online job board for veterans and military spouses. Hosts career fairs in LA, SD, SF, Sacramento, and other major CA metros annually.",
    website_url: "https://recruitmilitary.com/",
    phone: "(513) 683-5020", address: "Statewide career fair venues",
    city: "Los Angeles", zip: "90001",
    eligibility: "Veterans and military spouses",
    source_name: "RecruitMilitary canonical / Bradley-Morris Inc", source_type: "nonprofit",
  },
  {
    section: "EMP-SHRM", title: "Veterans of Foreign Wars - VFW Veterans Job Connection",
    cat: "employment", sub: "Job Placement",
    desc: "VFW Veterans Job Connection — national online employment platform connecting veterans with veteran-friendly employers. Run by VFW national alongside California posts as referral channel.",
    website_url: "https://www.vfw.org/assistance/career-corner",
    phone: "(816) 756-3390", address: "VFW National HQ; CA referral via Department of CA-Pacific",
    city: "San Francisco", zip: "94102",
    eligibility: "VFW-eligible veterans seeking employment",
    source_name: "VFW Veterans Job Connection canonical site", source_type: "nonprofit",
  },

  // ============== ADDITIONAL CRISIS / MOBILE RESPONSE ==============
  {
    section: "CR-LACDMH", title: "LA County DMH ACCESS Center / Mental Evaluation Team (MET)",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "LA County DMH 24/7 ACCESS line — psychiatric assessment, crisis stabilization, MET co-response with LA County Sheriff/LAPD for mental-health calls. Veteran-specific dispatch via VPAN.",
    website_url: "https://dmh.lacounty.gov/our-services/access-center/",
    phone: "(800) 854-7771", address: "550 S. Vermont Avenue",
    city: "Los Angeles", zip: "90020",
    eligibility: "All LA County residents in mental-health crisis",
    source_name: "LA DMH ACCESS canonical site", source_type: "government_agency",
  },
  {
    section: "CR-988CA", title: "988 Suicide & Crisis Lifeline - California Network",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "988 Suicide & Crisis Lifeline California network — 12 in-state SAMHSA-certified crisis call centers (Didi Hirsch, Crisis Support Services Alameda, Kings View, etc.) answering 988 calls/texts/chats. Press 1 for Veterans Crisis Line.",
    website_url: "https://www.dhcs.ca.gov/services/Pages/988-Behavioral-Health-Crisis-Care-Continuum.aspx",
    phone: "988", address: "Statewide network of 12 call centers",
    city: "Sacramento", zip: "95814",
    eligibility: "All California residents in mental-health crisis",
    source_name: "DHCS 988 California canonical site", source_type: "government_agency",
  },
];

runSeed(ROWS, { commit: COMMIT, label: "CA Saturation B10 — County BH + VVA + Stand Down + Vet Centers + FRCs + CalVet Cemeteries", state: "CA" });
