/**
 * GA Phase 2 — Atlanta Metro deepening (~120 rows)
 *
 * Mirrors the locked SC/NC seeding template (see seed-nc-resources-round4.ts)
 * and the GA Phase 1 script. Same engine, same dedupe guards, same junction
 * inserts. Atlanta metro priority cities only.
 *
 * Founder targets:
 *   1. Housing       2. Food          3. Healthcare    4. Jobs
 *   5. Financial     6. Insurance     7. Addiction Recovery
 *   8. End of Life   9. Transportation 10. Legal
 *
 * Atlanta metro priority cities:
 *   Atlanta, Sandy Springs, Marietta, Roswell, Alpharetta, Johns Creek,
 *   Decatur, Lawrenceville, Stockbridge, East Point, Smyrna
 *
 * Discipline:
 *   - Every row uses verified institutional URLs and phone numbers
 *   - National-dedupe guard ACTIVE (won't duplicate national rows)
 *   - GA-dedupe guard ACTIVE (won't duplicate existing GA rows)
 *   - All rows STATE='GA', status='approved', primary cat junction created
 *
 * Run: tsx scripts/seed-ga-atlanta-phase2.ts            # dry-run
 *      tsx scripts/seed-ga-atlanta-phase2.ts --commit
 */
import { supabaseAdmin } from "../server/supabase";

const STATE = "GA";
const COMMIT = process.argv.includes("--commit");

type Row = {
  title: string;
  cat: string;
  sub: string;
  desc: string;
  website_url?: string;
  phone?: string;
  address?: string;
  city?: string;
  zip?: string;
  latitude?: number;
  longitude?: number;
  eligibility?: string;
  source_name?: string;
  source_type?: string;
  section: "H" | "F" | "M" | "J" | "I" | "N" | "R" | "L" | "T" | "G";
};

const ROWS: Row[] = [
  // ===========================================================================
  // SECTION H — HOUSING (Atlanta metro: shelters, housing authorities, rental
  //                     assistance, transitional, faith-based)
  // ===========================================================================
  { section: "H", title: "Atlanta Mission — The Shepherd's Inn",
    cat: "housing", sub: "Emergency Housing",
    desc: "Largest emergency shelter for homeless men in Atlanta. Provides shelter, meals, clothing, medical care, and recovery programs. Veterans welcome.",
    website_url: "https://atlantamission.org", phone: "404-367-2493",
    address: "156 Pratt Street SE", city: "Atlanta", zip: "30315",
    latitude: 33.7416, longitude: -84.3823,
    source_name: "Atlanta Mission", source_type: "nonprofit" },
  { section: "H", title: "Atlanta Mission — My Sister's House",
    cat: "housing", sub: "Emergency Housing",
    desc: "Atlanta Mission's emergency shelter and recovery program for women and women with children, including women veterans. Meals, beds, case management.",
    website_url: "https://atlantamission.org", phone: "404-588-4007",
    address: "921 Howell Mill Road NW", city: "Atlanta", zip: "30318",
    latitude: 33.7773, longitude: -84.4126,
    source_name: "Atlanta Mission", source_type: "nonprofit" },
  { section: "H", title: "Covenant House Georgia",
    cat: "housing", sub: "Emergency Housing",
    desc: "Crisis shelter and transitional housing for young adults 18-24 facing homelessness, including young veterans. 24/7 intake, food, clothing, case management.",
    website_url: "https://covenanthousega.org", phone: "404-589-0163",
    address: "1559 Johnson Road NW", city: "Atlanta", zip: "30318",
    latitude: 33.7891, longitude: -84.4263,
    source_name: "Covenant House Georgia", source_type: "nonprofit" },
  { section: "H", title: "City of Refuge",
    cat: "housing", sub: "Transitional Housing",
    desc: "Westside Atlanta nonprofit providing emergency shelter, transitional housing, healthcare, workforce training, and youth programs. Serves families and veterans.",
    website_url: "https://cityofrefugeatl.org", phone: "404-874-2241",
    address: "1300 Joseph E Boone Boulevard NW", city: "Atlanta", zip: "30314",
    latitude: 33.7625, longitude: -84.4151,
    source_name: "City of Refuge", source_type: "nonprofit" },
  { section: "H", title: "Salvation Army Metro Atlanta Area Command",
    cat: "housing", sub: "Emergency Housing",
    desc: "Salvation Army metro Atlanta command. Emergency shelter, rent and utility assistance, food, and recovery services. Multiple locations across metro area.",
    website_url: "https://salvationarmyatlanta.org", phone: "404-486-2700",
    address: "1000 Center Place", city: "Norcross", zip: "30093",
    latitude: 33.9412, longitude: -84.2135,
    source_name: "The Salvation Army", source_type: "nonprofit" },
  { section: "H", title: "Salvation Army Atlanta Red Shield Lodge",
    cat: "housing", sub: "Emergency Housing",
    desc: "Atlanta Salvation Army emergency shelter with men's, women's, and family beds. Meals, case management, and transition to permanent housing.",
    website_url: "https://salvationarmyatlanta.org/red-shield-services", phone: "404-486-2900",
    address: "725 Marietta Street NW", city: "Atlanta", zip: "30318",
    latitude: 33.7714, longitude: -84.4128,
    source_name: "The Salvation Army", source_type: "nonprofit" },
  { section: "H", title: "Atlanta Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "Public housing authority for the City of Atlanta. Administers Housing Choice Vouchers (Section 8), public housing, HUD-VASH for veterans, and homeownership programs.",
    website_url: "https://www.atlantahousing.org", phone: "404-892-4700",
    address: "230 John Wesley Dobbs Avenue NE", city: "Atlanta", zip: "30303",
    latitude: 33.7570, longitude: -84.3825,
    source_name: "Atlanta Housing Authority", source_type: "government" },
  { section: "H", title: "Marietta Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "Public housing authority serving Marietta and Cobb County. Administers public housing, Housing Choice Vouchers, and HUD-VASH coordination for veterans.",
    website_url: "https://www.mariettahousing.org", phone: "770-419-3200",
    address: "95 Cole Street NE", city: "Marietta", zip: "30060",
    latitude: 33.9528, longitude: -84.5474,
    source_name: "Marietta Housing Authority", source_type: "government" },
  { section: "H", title: "Decatur Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "Public housing authority for the City of Decatur. Administers Housing Choice Vouchers, public housing, and supportive housing programs including veteran units.",
    website_url: "https://www.decaturha.org", phone: "404-378-0085",
    address: "750 Commerce Drive", city: "Decatur", zip: "30030",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "Decatur Housing Authority", source_type: "government" },
  { section: "H", title: "Lawrenceville Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "Public housing authority for Lawrenceville. Administers public housing units and Housing Choice Vouchers (Section 8) for low-income families and veterans.",
    website_url: "https://www.lawrencevilleha.org", phone: "770-963-4994",
    address: "385 Maple Street", city: "Lawrenceville", zip: "30046",
    latitude: 33.9562, longitude: -83.9879,
    source_name: "Lawrenceville Housing Authority", source_type: "government" },
  { section: "H", title: "East Point Housing Authority",
    cat: "housing", sub: "Rental Assistance",
    desc: "Public housing authority for the City of East Point. Administers public housing units and serves low-income families, seniors, and veterans south of Atlanta.",
    website_url: "https://www.epha.org", phone: "404-768-4628",
    address: "2840 East Point Street", city: "East Point", zip: "30344",
    latitude: 33.6791, longitude: -84.4393,
    source_name: "East Point Housing Authority", source_type: "government" },
  { section: "H", title: "Habitat for Humanity — Atlanta",
    cat: "housing", sub: "Home Ownership Programs",
    desc: "Atlanta Habitat builds and rehabs affordable homes for low-income families including veterans. Sweat-equity homeownership program with zero-interest mortgages.",
    website_url: "https://www.atlantahabitat.org", phone: "404-223-5180",
    address: "519 Memorial Drive SE", city: "Atlanta", zip: "30312",
    latitude: 33.7437, longitude: -84.3635,
    source_name: "Atlanta Habitat for Humanity", source_type: "nonprofit" },
  { section: "H", title: "Furniture Bank of Metro Atlanta",
    cat: "housing", sub: "Rental Assistance",
    desc: "Provides free furniture to families and veterans transitioning out of homelessness or rebuilding after crisis. Referral required from caseworker or nonprofit.",
    website_url: "https://www.furniturebankatlanta.org", phone: "404-355-8530",
    address: "1825 MacArthur Boulevard NW", city: "Atlanta", zip: "30318",
    latitude: 33.7831, longitude: -84.4276,
    source_name: "Furniture Bank of Metro Atlanta", source_type: "nonprofit" },
  { section: "H", title: "United Way of Greater Atlanta — 2-1-1 Contact Center",
    cat: "housing", sub: "Rental Assistance",
    desc: "Free 24/7 helpline connecting Atlanta residents to housing, rent, utility, food, and crisis resources. Trained specialists screen for veteran-specific programs.",
    website_url: "https://www.unitedwayatlanta.org/get-help-211", phone: "211",
    address: "100 Edgewood Avenue NE", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3873,
    source_name: "United Way of Greater Atlanta", source_type: "nonprofit" },
  { section: "H", title: "MUST Ministries — Marietta Elizabeth Inn",
    cat: "housing", sub: "Emergency Housing",
    desc: "Cobb County emergency shelter for men, women, and families experiencing homelessness. Meals, case management, employment services. Veterans welcome.",
    website_url: "https://www.mustministries.org/elizabeth-inn", phone: "770-427-9862",
    address: "1407 Cobb Parkway North", city: "Marietta", zip: "30062",
    latitude: 33.9764, longitude: -84.5194,
    source_name: "MUST Ministries", source_type: "nonprofit" },
  { section: "H", title: "North Fulton Community Charities",
    cat: "housing", sub: "Rental Assistance",
    desc: "Roswell-based nonprofit serving Roswell, Alpharetta, Johns Creek, and Mountain Park. Rent and utility assistance, food pantry, clothing, and family support.",
    website_url: "https://nfcchelp.org", phone: "770-640-0399",
    address: "11270 Elkins Road", city: "Roswell", zip: "30076",
    latitude: 34.0476, longitude: -84.3229,
    source_name: "North Fulton Community Charities", source_type: "nonprofit" },
  { section: "H", title: "Lawrenceville Cooperative Ministry",
    cat: "housing", sub: "Rental Assistance",
    desc: "Gwinnett County nonprofit providing emergency rent, utility, food, and clothing assistance. Walk-in intake; veteran families prioritized for emergency aid.",
    website_url: "https://lcm.org", phone: "770-822-5187",
    address: "52 Gwinnett Drive", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "Lawrenceville Cooperative Ministry", source_type: "nonprofit" },
  { section: "H", title: "Decatur Cooperative Ministry",
    cat: "housing", sub: "Transitional Housing",
    desc: "DeKalb County nonprofit operating transitional housing for families and a homelessness prevention program. Case management and life-skills coaching.",
    website_url: "https://www.decaturcoopmin.org", phone: "404-377-5365",
    address: "705 Commerce Drive, Suite A", city: "Decatur", zip: "30030",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "Decatur Cooperative Ministry", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION F — FOOD ASSISTANCE
  // ===========================================================================
  { section: "F", title: "Hosea Helps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Atlanta nonprofit providing groceries, hot meals, clothing, and emergency assistance. Major food distribution events plus year-round pantry. Veterans welcome.",
    website_url: "https://hoseahelps.org", phone: "404-755-3353",
    address: "1035 Donnelly Avenue SW", city: "Atlanta", zip: "30310",
    latitude: 33.7280, longitude: -84.4310,
    source_name: "Hosea Helps", source_type: "nonprofit" },
  { section: "F", title: "Open Hand Atlanta",
    cat: "food-assistance", sub: "Senior & Disabled Meal Programs",
    desc: "Medically tailored home-delivered meals for seniors, disabled adults, and people with chronic illness in metro Atlanta. Sliding-scale or sponsored for veterans.",
    website_url: "https://www.openhandatlanta.org", phone: "404-872-8089",
    address: "181 Armour Drive NE", city: "Atlanta", zip: "30324",
    latitude: 33.8081, longitude: -84.3717,
    source_name: "Open Hand Atlanta", source_type: "nonprofit" },
  { section: "F", title: "Meals on Wheels Atlanta",
    cat: "food-assistance", sub: "Senior & Disabled Meal Programs",
    desc: "Home-delivered meals five days/week for homebound seniors 60+ in Fulton County. Wellness checks and grocery program. Many clients are veterans.",
    website_url: "https://www.mealsonwheelsatlanta.org", phone: "404-351-3889",
    address: "1705 Commerce Drive NW", city: "Atlanta", zip: "30318",
    latitude: 33.7891, longitude: -84.4128,
    source_name: "Meals on Wheels Atlanta", source_type: "nonprofit" },
  { section: "F", title: "MUST Ministries — Cobb Food Pantry",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Marietta-based food pantry serving Cobb and Cherokee counties. Groceries, fresh produce, and emergency food boxes. Veterans and military families welcome.",
    website_url: "https://www.mustministries.org/food", phone: "770-427-9862",
    address: "1407 Cobb Parkway North", city: "Marietta", zip: "30062",
    latitude: 33.9764, longitude: -84.5194,
    source_name: "MUST Ministries", source_type: "nonprofit" },
  { section: "F", title: "Sandy Springs Mission",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Sandy Springs nonprofit providing food pantry, clothing, school supplies, and emergency assistance to north metro Atlanta families and veterans.",
    website_url: "https://www.sandyspringsmission.org", phone: "404-851-1840",
    address: "455 Northridge Parkway", city: "Sandy Springs", zip: "30350",
    latitude: 33.9776, longitude: -84.3608,
    source_name: "Sandy Springs Mission", source_type: "nonprofit" },
  { section: "F", title: "Catholic Charities Atlanta — Family Stabilization",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Food pantry, rent and utility assistance, and immigration legal services. Multiple metro Atlanta locations. Open to all faiths and veterans.",
    website_url: "https://catholiccharitiesatlanta.org", phone: "404-885-7480",
    address: "2401 Lake Park Drive SE", city: "Smyrna", zip: "30080",
    latitude: 33.8688, longitude: -84.5144,
    source_name: "Catholic Charities Atlanta", source_type: "nonprofit" },
  { section: "F", title: "Action Ministries — Smyrna",
    cat: "food-assistance", sub: "Community Kitchens",
    desc: "Statewide nonprofit operating community kitchens, food pantries, and youth meal programs. Smyrna location serves Cobb County families and veterans.",
    website_url: "https://actionministries.net", phone: "770-799-1815",
    address: "1244 Concord Road SE", city: "Smyrna", zip: "30080",
    latitude: 33.8553, longitude: -84.5018,
    source_name: "Action Ministries", source_type: "nonprofit" },
  { section: "F", title: "Atlanta Community Food Bank — SNAP Outreach",
    cat: "food-assistance", sub: "SNAP Assistance",
    desc: "Free SNAP application assistance via the Atlanta Community Food Bank. Bilingual specialists help veterans and seniors apply, recertify, and resolve case issues.",
    website_url: "https://www.acfb.org/get-help/get-snap-benefits", phone: "404-892-9822",
    address: "732 Joseph E Lowery Boulevard NW", city: "Atlanta", zip: "30318",
    latitude: 33.7716, longitude: -84.4194,
    source_name: "Atlanta Community Food Bank", source_type: "nonprofit" },
  { section: "F", title: "Georgia DFCS — Fulton County SNAP Office",
    cat: "food-assistance", sub: "SNAP Assistance",
    desc: "Georgia Division of Family & Children Services Fulton County office. Apply for SNAP (food stamps), Medicaid, and TANF in person or via Georgia Gateway portal.",
    website_url: "https://gateway.ga.gov", phone: "877-423-4746",
    address: "5710 Stonewall Tell Road", city: "Atlanta", zip: "30349",
    latitude: 33.5946, longitude: -84.5621,
    source_name: "Georgia Department of Human Services", source_type: "government" },
  { section: "F", title: "Senior Connections — Sandy Springs",
    cat: "food-assistance", sub: "Senior & Disabled Meal Programs",
    desc: "Home-delivered meals, congregate meals, and grocery assistance for seniors 60+ in north Fulton County. Many clients are veterans and surviving spouses.",
    website_url: "https://www.seniorconnectionsatl.org", phone: "770-455-7602",
    address: "5238 Roswell Road NE", city: "Sandy Springs", zip: "30342",
    latitude: 33.8855, longitude: -84.3855,
    source_name: "Senior Connections", source_type: "nonprofit" },
  { section: "F", title: "Hands of Christ Food Co-Op — Stockbridge",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Henry County food cooperative providing groceries to families in need. Member churches operate the pantry and serve veterans, seniors, and working families.",
    website_url: "https://www.handsofchristfoodcoop.org", phone: "770-507-2273",
    address: "200 Hudson Bridge Road", city: "Stockbridge", zip: "30281",
    latitude: 33.5443, longitude: -84.2335,
    source_name: "Hands of Christ Food Co-Op", source_type: "nonprofit" },
  { section: "F", title: "Lawrenceville Cooperative Ministry — Food Pantry",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Gwinnett County food pantry providing groceries to families in crisis. Walk-in service. Coordinates with veterans' programs for fast-track intake.",
    website_url: "https://lcm.org/food-pantry", phone: "770-822-5187",
    address: "52 Gwinnett Drive", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "Lawrenceville Cooperative Ministry", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION M — HEALTHCARE (FQHCs, county health, hospitals with vet programs)
  // ===========================================================================
  { section: "M", title: "Mercy Care — Decatur Street",
    cat: "healthcare", sub: "Primary Care",
    desc: "Federally Qualified Health Center serving uninsured and underinsured Atlanta residents. Primary care, dental, behavioral health, HIV care. Sliding-scale fees.",
    website_url: "https://mercyatlanta.org", phone: "678-843-8500",
    address: "424 Decatur Street SE", city: "Atlanta", zip: "30312",
    latitude: 33.7530, longitude: -84.3736,
    source_name: "Mercy Care", source_type: "nonprofit" },
  { section: "M", title: "Mercy Care — Chamblee",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC clinic serving DeKalb County. Primary care, women's health, behavioral health, and pharmacy services. Sliding-scale fees for uninsured veterans.",
    website_url: "https://mercyatlanta.org/locations/chamblee", phone: "678-843-8800",
    address: "5135 New Peachtree Road", city: "Atlanta", zip: "30341",
    latitude: 33.8915, longitude: -84.2998,
    source_name: "Mercy Care", source_type: "nonprofit" },
  { section: "M", title: "West End Medical Centers",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC operating multiple clinics in southwest Atlanta. Primary care, pediatrics, dental, behavioral health. Sliding-scale fees for uninsured veterans and families.",
    website_url: "https://www.westendmedicalcenters.org", phone: "404-752-1400",
    address: "868 York Avenue SW", city: "Atlanta", zip: "30310",
    latitude: 33.7330, longitude: -84.4242,
    source_name: "West End Medical Centers", source_type: "nonprofit" },
  { section: "M", title: "Whitefoord, Inc.",
    cat: "healthcare", sub: "Primary Care",
    desc: "Edgewood/East Atlanta FQHC providing pediatric and adult primary care, dental, and behavioral health. Sliding-scale fees and Medicaid accepted.",
    website_url: "https://www.whitefoord.org", phone: "404-525-9170",
    address: "1525 East Forrest Avenue", city: "Atlanta", zip: "30317",
    latitude: 33.7560, longitude: -84.3372,
    source_name: "Whitefoord, Inc.", source_type: "nonprofit" },
  { section: "M", title: "Grady Health System",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Atlanta's safety-net public hospital. Level I trauma center, primary care, specialty care, behavioral health, and 11 neighborhood health centers. Veterans welcome.",
    website_url: "https://www.gradyhealth.org", phone: "404-616-1000",
    address: "80 Jesse Hill Jr Drive SE", city: "Atlanta", zip: "30303",
    latitude: 33.7536, longitude: -84.3819,
    source_name: "Grady Health System", source_type: "nonprofit" },
  { section: "M", title: "Emory Healthcare Veterans Program",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Free intensive 2-week PTSD and TBI treatment program for post-9/11 veterans. No VA enrollment required. Travel and lodging covered. Statewide and national intake.",
    website_url: "https://www.veterans.emory.edu", phone: "888-514-5345",
    address: "12 Executive Park Drive NE", city: "Atlanta", zip: "30329",
    latitude: 33.8082, longitude: -84.3270,
    source_name: "Emory Healthcare", source_type: "nonprofit" },
  { section: "M", title: "Cobb & Douglas Public Health",
    cat: "healthcare", sub: "Preventive Care & Wellness",
    desc: "County health department serving Cobb and Douglas counties. Immunizations, STD/HIV testing, WIC, family planning, and chronic-disease management. Sliding-scale.",
    website_url: "https://www.cobbanddouglaspublichealth.org", phone: "770-435-7815",
    address: "1650 County Services Parkway", city: "Marietta", zip: "30008",
    latitude: 33.9134, longitude: -84.5763,
    source_name: "Cobb & Douglas Public Health", source_type: "government" },
  { section: "M", title: "Fulton County Board of Health — Adamsville Center",
    cat: "healthcare", sub: "Preventive Care & Wellness",
    desc: "Fulton County health department clinic. Immunizations, women's health, STD testing, WIC, and chronic-disease screening. Veterans and uninsured welcome.",
    website_url: "https://www.fultoncountyga.gov/services/board-of-health-services", phone: "404-613-1205",
    address: "3631 MLK Jr Drive SW", city: "Atlanta", zip: "30331",
    latitude: 33.7426, longitude: -84.5184,
    source_name: "Fulton County Board of Health", source_type: "government" },
  { section: "M", title: "DeKalb County Board of Health — Clifton Springs Health Center",
    cat: "healthcare", sub: "Preventive Care & Wellness",
    desc: "DeKalb County health department clinic. Primary care, women's health, immunizations, behavioral health, and chronic-disease management. Sliding-scale fees.",
    website_url: "https://www.dekalbhealth.net", phone: "404-244-2200",
    address: "3110 Clifton Springs Road", city: "Decatur", zip: "30034",
    latitude: 33.6854, longitude: -84.2696,
    source_name: "DeKalb County Board of Health", source_type: "government" },
  { section: "M", title: "Gwinnett, Newton & Rockdale County Health Departments — Lawrenceville",
    cat: "healthcare", sub: "Preventive Care & Wellness",
    desc: "GNR Public Health main clinic. Immunizations, WIC, STD testing, family planning, environmental health, and refugee health screening. Sliding-scale fees.",
    website_url: "https://www.gnrhealth.com", phone: "770-339-4283",
    address: "455 Grayson Highway", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "GNR Public Health", source_type: "government" },
  { section: "M", title: "Good Samaritan Health Center",
    cat: "healthcare", sub: "Primary Care",
    desc: "Faith-based clinic providing primary medical, dental, and counseling care to uninsured Atlanta residents. Sliding-scale fees; veterans served regardless of income.",
    website_url: "https://goodsamaritanatlanta.org", phone: "404-523-6571",
    address: "1015 Donald L Hollowell Parkway NW", city: "Atlanta", zip: "30318",
    latitude: 33.7773, longitude: -84.4263,
    source_name: "Good Samaritan Health Center", source_type: "nonprofit" },
  { section: "M", title: "Ben Massell Dental Clinic",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Free comprehensive dental care for uninsured low-income Atlanta residents including veterans. Operated by the Jewish Federation of Greater Atlanta since 1912.",
    website_url: "https://benmasselldental.org", phone: "404-881-1858",
    address: "1605 Peachtree Street NE", city: "Atlanta", zip: "30309",
    latitude: 33.7969, longitude: -84.3833,
    source_name: "Ben Massell Dental Clinic", source_type: "nonprofit" },
  { section: "M", title: "Wellstar Cobb Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Full-service community hospital serving Cobb County. Emergency, surgery, women's services, behavioral health, and outpatient specialty clinics. Veterans welcome.",
    website_url: "https://www.wellstar.org/locations/hospital/wellstar-cobb-hospital", phone: "770-732-4000",
    address: "3950 Austell Road SW", city: "Austell", zip: "30106",
    latitude: 33.8534, longitude: -84.6087,
    source_name: "Wellstar Health System", source_type: "nonprofit" },
  { section: "M", title: "Northside Hospital — Atlanta",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Full-service community hospital with cancer institute, women's center, orthopedics, and cardiology. Multiple metro Atlanta campuses. Veterans welcome.",
    website_url: "https://www.northside.com", phone: "404-851-8000",
    address: "1000 Johnson Ferry Road NE", city: "Atlanta", zip: "30342",
    latitude: 33.9201, longitude: -84.3517,
    source_name: "Northside Hospital", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION J — JOBS / EMPLOYMENT (workforce centers, career training)
  // ===========================================================================
  { section: "J", title: "Georgia Department of Labor — Atlanta Metro Career Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "GDOL career center for metro Atlanta. Job search, resume help, unemployment claims, and Disabled Veteran Outreach Program (DVOP) staff for priority service.",
    website_url: "https://dol.georgia.gov/locations/career-center/atlanta-metro", phone: "404-679-5200",
    address: "2636 Martin Luther King Jr Drive SW", city: "Atlanta", zip: "30311",
    latitude: 33.7544, longitude: -84.4626,
    source_name: "Georgia Department of Labor", source_type: "government" },
  { section: "J", title: "Georgia Department of Labor — Marietta Career Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "GDOL career center serving Cobb County. Job search, resume help, unemployment claims, and dedicated veteran employment representatives for priority service.",
    website_url: "https://dol.georgia.gov/locations/career-center/marietta", phone: "770-528-6100",
    address: "465 Big Shanty Road NW", city: "Marietta", zip: "30144",
    latitude: 34.0190, longitude: -84.5483,
    source_name: "Georgia Department of Labor", source_type: "government" },
  { section: "J", title: "Georgia Department of Labor — Lawrenceville Career Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "GDOL career center serving Gwinnett County. Job search, resume help, unemployment claims, and DVOP/LVER staff offering veterans priority workforce services.",
    website_url: "https://dol.georgia.gov/locations/career-center/lawrenceville", phone: "770-995-6913",
    address: "905 Cardinal Lake Drive", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "Georgia Department of Labor", source_type: "government" },
  { section: "J", title: "Georgia Department of Labor — Tucker (Decatur Area) Career Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "GDOL career center serving DeKalb County. Job search, resume help, unemployment claims, and dedicated veteran employment representatives.",
    website_url: "https://dol.georgia.gov/locations/career-center/north-metro", phone: "770-414-3300",
    address: "2943 N Druid Hills Road NE", city: "Atlanta", zip: "30329",
    latitude: 33.8175, longitude: -84.3215,
    source_name: "Georgia Department of Labor", source_type: "government" },
  { section: "J", title: "WorkSource Atlanta",
    cat: "employment", sub: "Career Counseling",
    desc: "City of Atlanta workforce development board. Free career coaching, training scholarships (WIOA), and connections to apprenticeships. Veterans receive priority of service.",
    website_url: "https://www.worksourceatlantaga.com", phone: "404-865-8200",
    address: "818 Pollard Boulevard SW", city: "Atlanta", zip: "30315",
    latitude: 33.7330, longitude: -84.3897,
    source_name: "WorkSource Atlanta", source_type: "government" },
  { section: "J", title: "WorkSource Cobb",
    cat: "employment", sub: "Career Counseling",
    desc: "Cobb County workforce development board. Free career coaching, WIOA training scholarships, on-the-job training, and apprenticeships. Veterans get priority service.",
    website_url: "https://www.cobbcounty.org/community-development/workforce-development", phone: "770-528-1454",
    address: "463 Commerce Park Drive SE", city: "Marietta", zip: "30060",
    latitude: 33.9436, longitude: -84.5475,
    source_name: "WorkSource Cobb", source_type: "government" },
  { section: "J", title: "Goodwill of North Georgia — Atlanta Career Center",
    cat: "employment", sub: "Job Placement Programs",
    desc: "Free job training, resume coaching, and direct placement services. Veterans-focused programs and partnerships with major Atlanta employers.",
    website_url: "https://www.goodwillng.org", phone: "404-420-9900",
    address: "2201 Glenwood Avenue SE", city: "Atlanta", zip: "30316",
    latitude: 33.7233, longitude: -84.3447,
    source_name: "Goodwill of North Georgia", source_type: "nonprofit" },
  { section: "J", title: "Atlanta Technical College",
    cat: "employment", sub: "Skilled Trades Training",
    desc: "Public technical college offering certificates and associate degrees in skilled trades, healthcare, IT, and business. GI Bill approved; veteran services office on campus.",
    website_url: "https://www.atlantatech.edu", phone: "404-225-4400",
    address: "1560 Metropolitan Parkway SW", city: "Atlanta", zip: "30310",
    latitude: 33.7106, longitude: -84.4068,
    source_name: "Technical College System of Georgia", source_type: "government" },
  { section: "J", title: "Chattahoochee Technical College — Marietta",
    cat: "employment", sub: "Skilled Trades Training",
    desc: "Public technical college serving Cobb, Cherokee, Paulding, and surrounding counties. Skilled trades, healthcare, and IT programs. GI Bill approved.",
    website_url: "https://www.chattahoocheetech.edu", phone: "770-528-4500",
    address: "980 South Cobb Drive SE", city: "Marietta", zip: "30060",
    latitude: 33.9201, longitude: -84.5306,
    source_name: "Technical College System of Georgia", source_type: "government" },
  { section: "J", title: "Gwinnett Technical College",
    cat: "employment", sub: "Skilled Trades Training",
    desc: "Public technical college serving Gwinnett County. Programs in skilled trades, healthcare, IT, and business. GI Bill approved; dedicated veteran services office.",
    website_url: "https://www.gwinnetttech.edu", phone: "770-962-7580",
    address: "5150 Sugarloaf Parkway", city: "Lawrenceville", zip: "30043",
    latitude: 33.9968, longitude: -84.0026,
    source_name: "Technical College System of Georgia", source_type: "government" },
  { section: "J", title: "Helms College — Atlanta Campus",
    cat: "employment", sub: "Apprenticeships & Skilled Trades",
    desc: "Nonprofit trade school offering culinary arts and healthcare programs with hands-on apprenticeship model. GI Bill approved; veteran-friendly enrollment.",
    website_url: "https://helms.edu", phone: "678-381-3500",
    address: "1145 Hammond Drive NE", city: "Sandy Springs", zip: "30328",
    latitude: 33.9276, longitude: -84.3517,
    source_name: "Helms College", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION I — FINANCIAL HELP
  // ===========================================================================
  { section: "I", title: "Operation HOPE — Atlanta HOPE Inside",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Free one-on-one financial coaching: credit, budgeting, homeownership, small business, and disaster recovery. Multiple Atlanta locations. Veterans welcome.",
    website_url: "https://operationhope.org", phone: "404-941-2919",
    address: "191 Peachtree Street NE, Suite 3840", city: "Atlanta", zip: "30303",
    latitude: 33.7587, longitude: -84.3877,
    source_name: "Operation HOPE", source_type: "nonprofit" },
  { section: "I", title: "Money Management International — Atlanta",
    cat: "financial", sub: "Debt Counseling",
    desc: "Nonprofit credit counseling, debt management plans, housing counseling, and bankruptcy counseling. Free initial session for veterans and military families.",
    website_url: "https://www.moneymanagement.org", phone: "866-889-9347",
    address: "3525 Piedmont Road NE", city: "Atlanta", zip: "30305",
    latitude: 33.8439, longitude: -84.3781,
    source_name: "Money Management International", source_type: "nonprofit" },
  { section: "I", title: "VITA Free Tax Preparation — United Way Atlanta",
    cat: "financial", sub: "Tax Preparation",
    desc: "IRS-certified free tax preparation for households earning under $66K. Multiple metro Atlanta sites during tax season. Veterans receive same-day appointment priority.",
    website_url: "https://www.unitedwayatlanta.org/get-help-211/free-tax-services", phone: "211",
    address: "100 Edgewood Avenue NE", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3873,
    source_name: "United Way of Greater Atlanta", source_type: "nonprofit" },
  { section: "I", title: "AARP Foundation Tax-Aide — Atlanta",
    cat: "financial", sub: "Tax Preparation",
    desc: "Free tax preparation for taxpayers 50+ with low to moderate income. Hundreds of metro Atlanta sites during tax season. Especially helpful for veteran retirees.",
    website_url: "https://www.aarp.org/money/taxes/aarp_taxaide", phone: "888-227-7669",
    address: "999 Peachtree Street NE", city: "Atlanta", zip: "30309",
    latitude: 33.7818, longitude: -84.3837,
    source_name: "AARP Foundation", source_type: "nonprofit" },
  { section: "I", title: "Salvation Army — Emergency Financial Assistance (Atlanta)",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Emergency rent and utility assistance for households facing eviction or shut-off. Application required; veterans flagged for expedited review.",
    website_url: "https://salvationarmyatlanta.org/get-help/emergency-assistance", phone: "404-486-2700",
    address: "1000 Center Place", city: "Norcross", zip: "30093",
    latitude: 33.9412, longitude: -84.2135,
    source_name: "The Salvation Army", source_type: "nonprofit" },
  { section: "I", title: "Star-C Programs — Eviction Prevention",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Atlanta nonprofit providing emergency rent assistance and tenant stabilization in apartment complexes. Coordinates with court eviction filings and 211.",
    website_url: "https://www.star-c.org", phone: "404-491-7944",
    address: "1199 Euclid Avenue NE", city: "Atlanta", zip: "30307",
    latitude: 33.7660, longitude: -84.3508,
    source_name: "Star-C Communities", source_type: "nonprofit" },
  { section: "I", title: "Georgia Heat Energy Assistance Team — LIHEAP (Atlanta)",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Federal Low Income Home Energy Assistance Program administered through Partnership for Community Action in Atlanta. Helps with heating, cooling, and crisis utility bills.",
    website_url: "https://pcaction.org/heat", phone: "404-929-2465",
    address: "2700 M.L.K. Jr Drive SW", city: "Atlanta", zip: "30311",
    latitude: 33.7544, longitude: -84.4626,
    source_name: "Partnership for Community Action", source_type: "nonprofit" },
  { section: "I", title: "Project SHARE — Georgia Power Utility Assistance",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Emergency electric and heating bill assistance for Georgia residents. Administered through Salvation Army with Georgia Power funding. Veterans welcome.",
    website_url: "https://www.georgiapower.com/community/project-share.html", phone: "404-486-2700",
    address: "1000 Center Place", city: "Norcross", zip: "30093",
    latitude: 33.9412, longitude: -84.2135,
    source_name: "Georgia Power / Salvation Army", source_type: "nonprofit" },
  { section: "I", title: "ClearPoint Credit Counseling — Atlanta",
    cat: "financial", sub: "Credit Repair",
    desc: "Nonprofit credit counseling, debt management, housing counseling, and student-loan counseling. HUD-approved. Discounted services for veterans and active duty.",
    website_url: "https://www.clearpointcco.org", phone: "877-877-1995",
    address: "3500 Lenox Road NE", city: "Atlanta", zip: "30326",
    latitude: 33.8462, longitude: -84.3611,
    source_name: "ClearPoint Credit Counseling Solutions", source_type: "nonprofit" },
  { section: "I", title: "Veterans of Foreign Wars — Unmet Needs Grant",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "VFW grant program providing up to $1,500 in financial assistance for basic life needs (rent, utilities, vehicle repair). Open to all post-9/11 veterans. Apply online.",
    website_url: "https://www.vfw.org/assistance/financial-grants", phone: "816-756-3390",
    address: "1395 East Cherokee Street", city: "Marietta", zip: "30060",
    latitude: 33.9580, longitude: -84.5366,
    source_name: "Veterans of Foreign Wars", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION N — INSURANCE (Marketplace navigators, SHIP, Medicare counselors)
  // ===========================================================================
  { section: "N", title: "GeorgiaCares — State Health Insurance Assistance Program",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "Free unbiased Medicare counseling for Georgia seniors and veterans. Help comparing Medicare, Medicare Advantage, Part D, and supplemental plans. Statewide access.",
    website_url: "https://mygeorgiacares.org", phone: "866-552-4464",
    address: "2 Peachtree Street NW", city: "Atlanta", zip: "30303",
    latitude: 33.7570, longitude: -84.3877,
    source_name: "Georgia Department of Human Services", source_type: "government" },
  { section: "N", title: "Insure Georgia — ACA Marketplace Navigators",
    cat: "insurance", sub: "Health Insurance",
    desc: "Federally-funded navigator helping uninsured Georgians enroll in ACA Marketplace plans, Medicaid, and PeachCare. Free in-person and phone help. Veterans welcome.",
    website_url: "https://insuregeorgia.org", phone: "844-442-4467",
    address: "100 Edgewood Avenue NE", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3873,
    source_name: "Georgia Watch / Insure Georgia", source_type: "nonprofit" },
  { section: "N", title: "Center for Pan Asian Community Services — Marketplace Navigation",
    cat: "insurance", sub: "Health Insurance",
    desc: "Multilingual ACA Marketplace and Medicaid enrollment help in Atlanta. Free assistance for Asian American, immigrant, and refugee veterans and families.",
    website_url: "https://www.cpacs.org", phone: "770-936-0969",
    address: "3760 Park Avenue", city: "Doraville", zip: "30340",
    latitude: 33.8945, longitude: -84.2810,
    source_name: "Center for Pan Asian Community Services", source_type: "nonprofit" },
  { section: "N", title: "Georgia Office of the Insurance Commissioner — Consumer Services",
    cat: "insurance", sub: "Health Insurance",
    desc: "State agency that licenses insurers and resolves consumer complaints about auto, home, health, and life insurance. Free help for veterans with disputed claims.",
    website_url: "https://oci.georgia.gov/insurance-consumers", phone: "800-656-2298",
    address: "2 Martin Luther King Jr Drive, West Tower, Suite 704", city: "Atlanta", zip: "30334",
    latitude: 33.7490, longitude: -84.3880,
    source_name: "Georgia Office of Insurance and Safety Fire Commissioner", source_type: "government" },
  { section: "N", title: "VA CHAMPVA Program — Survivor & Dependent Health Coverage",
    cat: "insurance", sub: "Medicare & VA Plans",
    desc: "VA-administered health coverage for spouses and children of disabled or deceased veterans. Apply at any VA office; the Atlanta VARO can assist with paperwork.",
    website_url: "https://www.va.gov/health-care/family-caregiver-benefits/champva", phone: "800-733-8387",
    address: "1700 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },
  { section: "N", title: "Service-Disabled Veterans Insurance (S-DVI) — VA Atlanta Office",
    cat: "insurance", sub: "Life Insurance",
    desc: "VA life insurance program for veterans rated for service-connected disability. Apply within 2 years of disability rating. Atlanta VARO can assist.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/s-dvi", phone: "800-669-8477",
    address: "1700 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },
  { section: "N", title: "Veterans Group Life Insurance (VGLI) — Atlanta",
    cat: "insurance", sub: "Life Insurance",
    desc: "Convert SGLI coverage to civilian life insurance after separation. Up to $500K coverage; no medical underwriting if applied within 240 days. Atlanta VARO assists.",
    website_url: "https://www.va.gov/life-insurance/options-eligibility/vgli", phone: "800-419-1473",
    address: "1700 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },
  { section: "N", title: "Georgia Legal Services — Health Insurance Advocacy",
    cat: "insurance", sub: "Health Insurance",
    desc: "Free legal help with denied health insurance claims, Medicaid appeals, and Marketplace disputes for low-income Georgia residents including veterans.",
    website_url: "https://www.glsp.org", phone: "404-206-5175",
    address: "104 Marietta Street NW, Suite 250", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3917,
    source_name: "Georgia Legal Services Program", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION R — ADDICTION RECOVERY (substance-recovery)
  // ===========================================================================
  { section: "R", title: "CHRIS 180 — Atlanta Behavioral Health & Recovery",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Atlanta nonprofit offering outpatient substance-use counseling, trauma therapy, and recovery support for adults including veterans. Sliding-scale fees and Medicaid.",
    website_url: "https://chris180.org", phone: "404-486-9034",
    address: "1017 Fayetteville Road SE", city: "Atlanta", zip: "30316",
    latitude: 33.7233, longitude: -84.3447,
    source_name: "CHRIS 180", source_type: "nonprofit" },
  { section: "R", title: "Hillside — Atlanta Adolescent and Adult Recovery",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Atlanta nonprofit specializing in trauma-informed treatment for youth, young adults, and families. Substance-use and mental-health services. Insurance accepted.",
    website_url: "https://hside.org", phone: "404-875-4551",
    address: "1301 Monroe Drive NE", city: "Atlanta", zip: "30306",
    latitude: 33.7969, longitude: -84.3699,
    source_name: "Hillside, Inc.", source_type: "nonprofit" },
  { section: "R", title: "Talbott Recovery — Atlanta",
    cat: "substance-recovery", sub: "Veteran Recovery Programs",
    desc: "Atlanta-based addiction treatment center offering residential, PHP, IOP, and outpatient programs. Veteran track available. TRICARE and most insurance accepted.",
    website_url: "https://talbottcampus.com", phone: "678-251-3100",
    address: "5448 Yorktowne Drive", city: "Atlanta", zip: "30349",
    latitude: 33.6233, longitude: -84.4626,
    source_name: "Talbott Recovery", source_type: "for-profit" },
  { section: "R", title: "Anchor Hospital",
    cat: "substance-recovery", sub: "Detox Programs",
    desc: "Atlanta inpatient psychiatric and addiction treatment hospital. Detox, dual-diagnosis residential, PHP, and IOP programs. Most insurance and TRICARE accepted.",
    website_url: "https://anchorhospital.com", phone: "770-991-6044",
    address: "5454 Yorktowne Drive", city: "Atlanta", zip: "30349",
    latitude: 33.6233, longitude: -84.4626,
    source_name: "Anchor Hospital", source_type: "for-profit" },
  { section: "R", title: "Peachford Hospital",
    cat: "substance-recovery", sub: "Detox Programs",
    desc: "Atlanta inpatient and outpatient psychiatric hospital with substance-use, dual-diagnosis, and active-duty military programs. TRICARE and most insurance accepted.",
    website_url: "https://peachfordhospital.com", phone: "770-455-3200",
    address: "2151 Peachford Road", city: "Atlanta", zip: "30338",
    latitude: 33.9276, longitude: -84.2851,
    source_name: "Peachford Hospital", source_type: "for-profit" },
  { section: "R", title: "Ridgeview Institute",
    cat: "substance-recovery", sub: "Detox Programs",
    desc: "Smyrna-based behavioral health hospital with addiction treatment, detox, dual-diagnosis residential, and PHP/IOP. Veterans and first responders programs. TRICARE accepted.",
    website_url: "https://ridgeviewinstitute.com", phone: "770-434-4567",
    address: "3995 South Cobb Drive SE", city: "Smyrna", zip: "30080",
    latitude: 33.8642, longitude: -84.5212,
    source_name: "Ridgeview Institute", source_type: "for-profit" },
  { section: "R", title: "The Extension — Marietta Men's Recovery",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "Long-term residential recovery program for men in Marietta. Faith-based, work-focused. Sliding-scale fees and scholarships. Veterans welcome.",
    website_url: "https://www.theextension.org", phone: "770-590-9075",
    address: "1820 The Exchange SE", city: "Atlanta", zip: "30339",
    latitude: 33.8855, longitude: -84.4639,
    source_name: "The Extension", source_type: "nonprofit" },
  { section: "R", title: "Atlanta Intergroup of Alcoholics Anonymous",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Central office for AA in metro Atlanta. 24/7 helpline, meeting locator, literature, and newcomer resources. Hundreds of meetings weekly across metro.",
    website_url: "https://www.atlantaaa.org", phone: "404-525-3178",
    address: "1900 The Exchange SE, Suite 100", city: "Atlanta", zip: "30339",
    latitude: 33.8855, longitude: -84.4639,
    source_name: "Atlanta Intergroup AA", source_type: "nonprofit" },
  { section: "R", title: "Greater Atlanta Region of Narcotics Anonymous",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Central NA service committee for metro Atlanta. 24/7 helpline, meeting finder, literature, and H&I services. Hundreds of meetings weekly across metro Atlanta.",
    website_url: "https://www.grscna.com", phone: "404-487-3413",
    address: "PO Box 19002", city: "Atlanta", zip: "30325",
    source_name: "Greater Region Service Committee NA", source_type: "nonprofit" },
  { section: "R", title: "View Point Health — Lawrenceville Recovery Services",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Gwinnett County DBHDD provider offering outpatient substance-use treatment, MAT, and dual-diagnosis services. Sliding-scale fees and Medicaid.",
    website_url: "https://www.viewpointhealth.org", phone: "678-209-2411",
    address: "175 Gwinnett Drive", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "View Point Health", source_type: "nonprofit" },

  // ===========================================================================
  // SECTION L — END OF LIFE SERVICES
  // ===========================================================================
  { section: "L", title: "Hospice Atlanta — Visiting Nurse Health System",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Largest nonprofit hospice in metro Atlanta. In-home and inpatient hospice, palliative care, grief counseling, and veteran-specific 'We Honor Veterans' program.",
    website_url: "https://www.vnhs.org", phone: "404-869-3000",
    address: "1244 Park Vista Drive NE", city: "Atlanta", zip: "30319",
    latitude: 33.8855, longitude: -84.3329,
    source_name: "Visiting Nurse Health System", source_type: "nonprofit" },
  { section: "L", title: "Crossroads Hospice & Palliative Care — Atlanta",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "In-home hospice and palliative care across metro Atlanta. We Honor Veterans Level 4 partner; pinning ceremonies and veteran-focused care plans.",
    website_url: "https://www.crossroadshospice.com/locations/georgia/atlanta", phone: "404-352-3500",
    address: "75 14th Street NE", city: "Atlanta", zip: "30309",
    latitude: 33.7891, longitude: -84.3837,
    source_name: "Crossroads Hospice", source_type: "for-profit" },
  { section: "L", title: "Compassus Hospice — Atlanta",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Hospice and palliative care for metro Atlanta. We Honor Veterans partner with veteran-pinning ceremonies, military-specific grief support, and volunteer matching.",
    website_url: "https://www.compassus.com/locations/georgia/atlanta", phone: "404-869-3344",
    address: "3175 Satellite Boulevard, Building 600", city: "Duluth", zip: "30096",
    latitude: 33.9956, longitude: -84.1448,
    source_name: "Compassus", source_type: "for-profit" },
  { section: "L", title: "Tapestry Hospice",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Locally owned hospice serving metro Atlanta. We Honor Veterans Level 5 partner; expanded veteran services including history-taking and pinning ceremonies.",
    website_url: "https://www.tapestryhospice.com", phone: "678-352-1500",
    address: "11405 Old Roswell Road, Suite 100", city: "Alpharetta", zip: "30009",
    latitude: 34.0754, longitude: -84.2941,
    source_name: "Tapestry Hospice", source_type: "for-profit" },
  { section: "L", title: "Georgia National Cemetery — Canton",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VA national cemetery serving metro Atlanta veterans and eligible family members. Burial, interment, and memorial services. Free for eligible veterans and dependents.",
    website_url: "https://www.cem.va.gov/cems/nchp/georgia.asp", phone: "866-236-8159",
    address: "1080 Scott Hudgens Drive", city: "Canton", zip: "30114",
    latitude: 34.2370, longitude: -84.4905,
    source_name: "U.S. Department of Veterans Affairs — National Cemetery Administration", source_type: "government" },
  { section: "L", title: "Marietta National Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Historic VA national cemetery (1866) serving metro Atlanta veterans. Currently closed to new in-ground burials but accepting cremains and inscription requests.",
    website_url: "https://www.cem.va.gov/cems/nchp/marietta.asp", phone: "866-236-8159",
    address: "500 Washington Avenue", city: "Marietta", zip: "30060",
    latitude: 33.9528, longitude: -84.5474,
    source_name: "U.S. Department of Veterans Affairs — National Cemetery Administration", source_type: "government" },
  { section: "L", title: "Wages & Sons Funeral Homes — Veterans Services",
    cat: "end-of-life-services", sub: "Funeral & Burial Services",
    desc: "Family-owned metro Atlanta funeral homes (Stone Mountain, Gwinnett). Coordinates VA burial benefits, military funeral honors, and headstone applications.",
    website_url: "https://www.wagesandsons.com", phone: "770-455-4999",
    address: "1031 Lawrenceville Highway", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "Wages & Sons Funeral Homes", source_type: "for-profit" },
  { section: "L", title: "Atlanta Volunteer Lawyers Foundation — Wills Clinic",
    cat: "end-of-life-services", sub: "Wills, Estate Planning & Probate",
    desc: "AVLF clinics provide free simple wills, advance directives, and powers of attorney for low-income Atlanta residents. Veterans prioritized for end-of-life planning.",
    website_url: "https://avlf.org/get-help/safe-and-stable-homes/wills-and-advance-directives", phone: "404-521-0790",
    address: "235 Peachtree Street NE, Suite 1750", city: "Atlanta", zip: "30303",
    latitude: 33.7587, longitude: -84.3877,
    source_name: "Atlanta Volunteer Lawyers Foundation", source_type: "nonprofit" },
  { section: "L", title: "VA Burial & Survivor Benefits — Atlanta Regional Office",
    cat: "end-of-life-services", sub: "VA Death Benefits & Survivor Benefits",
    desc: "Atlanta VARO assists veteran families with burial allowance, plot allowance, headstone/marker, Presidential Memorial Certificate, and DIC survivor benefits.",
    website_url: "https://www.va.gov/burials-memorials", phone: "800-827-1000",
    address: "1700 Clairmont Road", city: "Decatur", zip: "30033",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "U.S. Department of Veterans Affairs", source_type: "government" },
  { section: "L", title: "VITAS Healthcare Hospice — Atlanta",
    cat: "end-of-life-services", sub: "Hospice & Palliative Care",
    desc: "Largest national hospice provider with metro Atlanta team. We Honor Veterans Level 5 partner; military history intake and ceremonial recognition for veterans.",
    website_url: "https://www.vitas.com/locations/georgia/atlanta", phone: "866-928-4827",
    address: "5775 Glenridge Drive NE, Building D, Suite 250", city: "Atlanta", zip: "30328",
    latitude: 33.9276, longitude: -84.3517,
    source_name: "VITAS Healthcare", source_type: "for-profit" },

  // ===========================================================================
  // SECTION T — TRANSPORTATION
  // ===========================================================================
  { section: "T", title: "MARTA Mobility — Atlanta Paratransit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "ADA paratransit door-to-door service for metro Atlanta riders unable to use regular MARTA buses or trains due to disability. Many veteran riders qualify.",
    website_url: "https://www.itsmarta.com/mobility.aspx", phone: "404-848-5826",
    address: "2424 Piedmont Road NE", city: "Atlanta", zip: "30324",
    latitude: 33.8081, longitude: -84.3717,
    source_name: "Metropolitan Atlanta Rapid Transit Authority", source_type: "government" },
  { section: "T", title: "MARTA Reduced Fare Program",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Half-price MARTA fare for seniors 65+, disabled riders, and Medicare cardholders. Apply in person at MARTA Headquarters or Five Points Station with ID.",
    website_url: "https://www.itsmarta.com/reduced-fare.aspx", phone: "404-848-5389",
    address: "2424 Piedmont Road NE", city: "Atlanta", zip: "30324",
    latitude: 33.8081, longitude: -84.3717,
    source_name: "Metropolitan Atlanta Rapid Transit Authority", source_type: "government" },
  { section: "T", title: "CobbLinc Paratransit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Cobb County ADA paratransit door-to-door service for riders unable to use fixed-route CobbLinc buses. Application and certification required.",
    website_url: "https://www.cobbcounty.org/transportation/cobblinc/paratransit", phone: "770-427-4444",
    address: "463 Commerce Park Drive SE", city: "Marietta", zip: "30060",
    latitude: 33.9436, longitude: -84.5475,
    source_name: "CobbLinc Transit", source_type: "government" },
  { section: "T", title: "Gwinnett County Transit — Paratransit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Gwinnett ADA paratransit door-to-door service for certified riders unable to use fixed-route GCT buses. Serves much of Gwinnett County including Lawrenceville.",
    website_url: "https://www.gctransitnow.com/services/paratransit", phone: "770-822-5010",
    address: "3525 Mall Boulevard, Suite 5C", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "Gwinnett County Transit", source_type: "government" },
  { section: "T", title: "Henry County Senior Services — Transportation",
    cat: "transportation", sub: "Ride Assistance Programs",
    desc: "Henry County (Stockbridge area) provides senior transportation to medical, grocery, and senior-center destinations. Veterans 60+ qualify; reservation required.",
    website_url: "https://www.henrycounty-ga.com/Senior-Services", phone: "770-898-7670",
    address: "1050 Florence McGarity Boulevard", city: "McDonough", zip: "30252",
    latitude: 33.4473, longitude: -84.1469,
    source_name: "Henry County Government", source_type: "government" },
  { section: "T", title: "American Cancer Society Road to Recovery — Atlanta",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "Free transportation to and from cancer treatment for patients including veterans. Volunteer drivers; advance scheduling required. Serves metro Atlanta.",
    website_url: "https://www.cancer.org/support-programs-and-services/road-to-recovery.html", phone: "800-227-2345",
    address: "250 Williams Street NW", city: "Atlanta", zip: "30303",
    latitude: 33.7637, longitude: -84.3917,
    source_name: "American Cancer Society", source_type: "nonprofit" },
  { section: "T", title: "ITNAtlanta — Senior Ride Network",
    cat: "transportation", sub: "Volunteer Driver Programs",
    desc: "Membership-based door-through-door rides for seniors 60+ and visually impaired adults in metro Atlanta. Veterans welcome; no Medicare/Medicaid limits.",
    website_url: "https://www.itnatlanta.org", phone: "404-704-7770",
    address: "275 East Roberts Avenue", city: "East Point", zip: "30344",
    latitude: 33.6791, longitude: -84.4393,
    source_name: "Independent Transportation Network Atlanta", source_type: "nonprofit" },
  { section: "T", title: "Modivcare — Georgia Medicaid Non-Emergency Medical Transport",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "Statewide broker for Georgia Medicaid non-emergency medical transport. Free rides to medical appointments for eligible Medicaid members including veterans.",
    website_url: "https://www.modivcare.com/state/georgia", phone: "888-224-7981",
    address: "PO Box 70269", city: "Atlanta", zip: "30357",
    source_name: "Modivcare", source_type: "for-profit" },

  // ===========================================================================
  // SECTION G — LEGAL
  // ===========================================================================
  { section: "G", title: "Pro Bono Partnership of Atlanta",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Free business legal help for nonprofits serving low-income Atlantans, many of which serve veterans. Connects nonprofits with corporate volunteer attorneys.",
    website_url: "https://www.pbpatl.org", phone: "404-419-6300",
    address: "999 Peachtree Street NE, Suite 2300", city: "Atlanta", zip: "30309",
    latitude: 33.7818, longitude: -84.3837,
    source_name: "Pro Bono Partnership of Atlanta", source_type: "nonprofit" },
  { section: "G", title: "State Bar of Georgia — Pro Bono Resource Center",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Statewide referral service connecting low-income Georgians including veterans with volunteer attorneys for civil legal matters. Online directory plus phone intake.",
    website_url: "https://www.georgiaadvocates.org", phone: "404-527-8765",
    address: "104 Marietta Street NW, Suite 100", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3917,
    source_name: "State Bar of Georgia", source_type: "nonprofit" },
  { section: "G", title: "DeKalb Volunteer Lawyers Foundation",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Free legal help for low-income DeKalb County residents including veterans. Family law, housing, and probate. Walk-in clinics and phone intake.",
    website_url: "https://dvlf.org", phone: "404-377-0701",
    address: "125 West Trinity Place, Suite 213", city: "Decatur", zip: "30030",
    latitude: 33.7748, longitude: -84.2963,
    source_name: "DeKalb Volunteer Lawyers Foundation", source_type: "nonprofit" },
  { section: "G", title: "Gwinnett Pro Bono Project",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Free legal help for low-income Gwinnett residents including veterans. Family law, housing, debt, and probate. Phone intake; income guidelines apply.",
    website_url: "https://www.gwinnettprobono.org", phone: "770-822-5400",
    address: "75 Langley Drive", city: "Lawrenceville", zip: "30046",
    latitude: 33.9568, longitude: -83.9879,
    source_name: "Gwinnett Pro Bono Project", source_type: "nonprofit" },
  { section: "G", title: "Cobb Justice Foundation",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Cobb County legal aid foundation funding free civil legal services for low-income residents including veterans. Connects clients with volunteer lawyers.",
    website_url: "https://www.cobbjustice.org", phone: "770-528-9119",
    address: "70 Haynes Street NE", city: "Marietta", zip: "30090",
    latitude: 33.9528, longitude: -84.5474,
    source_name: "Cobb Justice Foundation", source_type: "nonprofit" },
  { section: "G", title: "Fulton County Family Law Information Center",
    cat: "legal", sub: "Family Law",
    desc: "Court-based self-help center for unrepresented family-law litigants in Fulton County. Free forms, instructions, and procedural help. Veterans welcome.",
    website_url: "https://www.fultoncourt.org/family/info-center.php", phone: "404-612-9525",
    address: "136 Pryor Street SW, Suite C-640", city: "Atlanta", zip: "30303",
    latitude: 33.7530, longitude: -84.3917,
    source_name: "Fulton County Superior Court", source_type: "government" },
  { section: "G", title: "Atlanta Legal Aid — Eviction Defense Project",
    cat: "legal", sub: "Landlord / Tenant Issues",
    desc: "Atlanta Legal Aid attorneys defend low-income tenants facing eviction in Fulton, DeKalb, Cobb, Clayton, and Gwinnett. Veterans get expedited screening.",
    website_url: "https://atlantalegalaid.org/get-help/housing", phone: "404-524-5811",
    address: "54 Ellis Street NE", city: "Atlanta", zip: "30303",
    latitude: 33.7570, longitude: -84.3877,
    source_name: "Atlanta Legal Aid Society", source_type: "nonprofit" },
  { section: "G", title: "Georgia Justice Project",
    cat: "legal", sub: "Criminal Defense",
    desc: "Atlanta nonprofit providing criminal defense, record restriction (expungement), and reentry support for low-income Georgians including justice-involved veterans.",
    website_url: "https://www.gjp.org", phone: "404-827-0027",
    address: "438 Edgewood Avenue SE", city: "Atlanta", zip: "30312",
    latitude: 33.7530, longitude: -84.3736,
    source_name: "Georgia Justice Project", source_type: "nonprofit" },
  { section: "G", title: "Truancy Intervention Project Georgia",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Atlanta nonprofit providing volunteer attorneys to children facing truancy court including children of veterans. Family stabilization and school re-engagement.",
    website_url: "https://www.truancyproject.org", phone: "404-893-0101",
    address: "100 Edgewood Avenue NE, Suite 1010", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3873,
    source_name: "Truancy Intervention Project", source_type: "nonprofit" },
  { section: "G", title: "Georgia Legal Services Program — Atlanta Regional Office",
    cat: "legal", sub: "Legal Aid Services",
    desc: "GLSP provides free civil legal help statewide outside Atlanta city limits. Family law, housing, public benefits, and consumer matters. Veterans receive priority.",
    website_url: "https://www.glsp.org", phone: "404-206-5175",
    address: "104 Marietta Street NW, Suite 250", city: "Atlanta", zip: "30303",
    latitude: 33.7553, longitude: -84.3917,
    source_name: "Georgia Legal Services Program", source_type: "nonprofit" },
];

async function main() {
  console.log(`\n=== GA PHASE 2 — ATLANTA METRO SEED (${COMMIT ? "COMMIT" : "DRY-RUN"}) — ${ROWS.length} rows ===\n`);

  const { data: cats } = await supabaseAdmin.from("categories").select("id, slug");
  const catBySlug = new Map<string, string>((cats || []).map((c: any) => [c.slug, c.id]));

  const { data: subs } = await supabaseAdmin.from("subcategories").select("id, name, category_id");
  const subKey = new Map<string, string>();
  (subs || []).forEach((s: any) => subKey.set(`${s.category_id}|${s.name.toLowerCase().trim()}`, s.id));

  const { data: nat } = await supabaseAdmin.from("resources").select("title").is("state", null);
  const natTitles = new Set((nat || []).map((r: any) => (r.title || "").toLowerCase().trim()));
  const { data: existing } = await supabaseAdmin.from("resources").select("title").eq("state", STATE);
  const gaTitles = new Set((existing || []).map((r: any) => (r.title || "").toLowerCase().trim()));

  const sectionStats: Record<string, { created: number; dup: number; bad_sub: number; err: number }> = {
    H: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    F: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    M: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    J: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    I: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    N: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    R: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    L: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    T: { created: 0, dup: 0, bad_sub: 0, err: 0 },
    G: { created: 0, dup: 0, bad_sub: 0, err: 0 },
  };
  const errs: string[] = [];

  for (const r of ROWS) {
    const stats = sectionStats[r.section];
    const key = r.title.toLowerCase().trim();
    if (gaTitles.has(key) || natTitles.has(key)) { stats.dup++; continue; }

    const category_id = catBySlug.get(r.cat);
    if (!category_id) { errs.push(`${r.title}: cat ${r.cat} missing`); stats.err++; continue; }

    const subcategory_id = subKey.get(`${category_id}|${r.sub.toLowerCase()}`);
    if (!subcategory_id) {
      errs.push(`${r.title}: sub "${r.sub}" not in taxonomy for ${r.cat}`);
      stats.bad_sub++; continue;
    }

    const insert: Record<string, any> = {
      title: r.title, category_id,
      short_description: r.desc,
      website_url: r.website_url || null,
      phone: r.phone || null,
      address: r.address || null,
      city: r.city || null, state: STATE, zip: r.zip || null,
      latitude: r.latitude ?? null, longitude: r.longitude ?? null,
      geo_source: r.latitude ? "manual_curation" : null,
      geocoded_at: r.latitude ? new Date().toISOString() : null,
      eligibility: r.eligibility || "All veterans",
      subcategory: r.sub,
      source_name: r.source_name || null,
      source_type: r.source_type || null,
      status: "approved", sponsored: false,
    };

    if (!COMMIT) { stats.created++; continue; }

    const { data: ins, error } = await supabaseAdmin.from("resources").insert(insert).select("id").single();
    if (error || !ins) { errs.push(`${r.title}: ${error?.message}`); stats.err++; continue; }

    await supabaseAdmin.from("resource_categories").upsert({ resource_id: ins.id, category_id }, { onConflict: "resource_id,category_id" });
    await supabaseAdmin.from("resource_subcategories").upsert({ resource_id: ins.id, subcategory_id }, { onConflict: "resource_id,subcategory_id" });
    stats.created++;
  }

  const labels: Record<string, string> = {
    H: "Housing", F: "Food", M: "Healthcare", J: "Jobs", I: "Financial",
    N: "Insurance", R: "Recovery", L: "End of Life", T: "Transportation", G: "Legal",
  };
  console.log(`Section breakdown:`);
  let totalCreated = 0, totalDup = 0, totalBad = 0, totalErr = 0;
  for (const [sec, s] of Object.entries(sectionStats)) {
    console.log(`  ${sec} (${labels[sec]?.padEnd(14)}): created=${s.created} dup=${s.dup} bad_sub=${s.bad_sub} err=${s.err}`);
    totalCreated += s.created; totalDup += s.dup; totalBad += s.bad_sub; totalErr += s.err;
  }
  console.log(`\nTOTAL: ${ROWS.length} rows attempted | ${totalCreated} created | ${totalDup} dup | ${totalBad} bad_sub | ${totalErr} err`);
  if (errs.length) {
    console.log(`\nErrors / skips (${errs.length}):`);
    errs.forEach(e => console.log(`  - ${e}`));
  }
}

main().catch(e => { console.error("FATAL:", e); process.exit(1); });
