import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");
const ROWS: SeedRow[] = [
  { section: "EOL", title: "Compassus Hospice & Palliative Care — Houston", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Houston", website_url: "https://www.compassus.com/our-locations/texas/houston", source_name: "Compassus", source_type: "hospice", phone: "281-893-1004", address: "9225 Katy Fwy Suite 110, Houston, TX 77024", zip: "77024", desc: "Compassus Hospice & Palliative Care Houston — serving Harris, Fort Bend, Montgomery, Brazoria, Galveston, and surrounding counties. Routine home care, continuous home care, inpatient hospice (contracted IPU sites), respite care, bereavement support, and We Honor Veterans Level 4 partner with DeBakey VAMC and Texas Medical Center hospitals." },
  { section: "EOL", title: "Houston Methodist Hospice and Palliative Care", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Houston", website_url: "https://www.houstonmethodist.org/services/hospice/", source_name: "Houston Methodist", source_type: "hospice", phone: "832-667-1860", address: "6411 Fannin St, Houston, TX 77030", zip: "77030", desc: "Houston Methodist Hospice and Palliative Care — Houston Methodist System nonprofit hospice serving the 8-county Greater Houston region. Routine home care, continuous home care, inpatient hospice at Houston Methodist Hospital, respite care, pediatric hospice, bereavement support, and We Honor Veterans Level 4 partner with DeBakey VAMC." },
];
console.log(`[seed-tx-eol-final] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, { state: "TX", commit: COMMIT, scriptName: "TX EOL Final", batchTag: "tx-eol-final", allowBrokenUrls: ALLOW_BROKEN_URLS, sectionLabels: { EOL: "End-of-life-services" } }).catch(e => { console.error(e); process.exit(1); });
