/**
 * VIRGINIA — WAVE 5 (FL-pattern statewide category depth fill, ~95 rows)
 *
 * Founder release 2026-05-02 (Option A): low-count categories statewide.
 * Same FL Wave system. NO insurance touch. Speed > perfection. STOP after W5.
 *
 * Sections:
 *   A  Substance Recovery       (was  2 → +)  legitimate verified orgs only
 *   B  Transportation           (was 17 → +)  rural/regional/NEMT/DAV
 *   C  Financial & Credit       (was  9 → +)  VITA/relief funds/coaching
 *   D  Legal Services           (was 20 → +)  legal aid/clinics/pro bono
 *
 * APPENDS to W1 (125) + W2 (123) + W3 (135) + W4 (95) = post-W5 total ~570.
 *
 * Run:
 *   tsx scripts/seed-va-wave5.ts                                # dry-run
 *   tsx scripts/seed-va-wave5.ts --commit --allow-broken-urls   # write
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");
const ALLOW_ZIP_BLEED = process.argv.includes("--allow-zip-bleed");

const ROWS: SeedRow[] = [
  // ===========================================================================
  // A. SUBSTANCE RECOVERY (was 2 → +24)
  // ===========================================================================
  { section: "A", title: "McShin Foundation",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Henrico/Richmond-based peer-run recovery community organization — peer recovery support, recovery housing, family support, and Recovery Coach Academy training. Veteran-friendly with dedicated programming.",
    website_url: "https://mcshin.org/", phone: "804-249-1845",
    address: "2300 Dumbarton Rd", city: "Henrico", zip: "23228",
    source_name: "McShin Foundation" },

  { section: "A", title: "The Healing Place Richmond (CARITAS)",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "CARITAS-operated long-term residential recovery program in Richmond — peer-led, no-cost recovery for men and women experiencing homelessness with substance use disorder. 200+ beds.",
    website_url: "https://www.caritasva.org/", phone: "804-358-0964",
    address: "2220 Stockton St", city: "Richmond", zip: "23224",
    source_name: "CARITAS" },

  { section: "A", title: "SAARA of Virginia",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Substance Abuse and Addiction Recovery Alliance of Virginia — Richmond-based statewide recovery community organization; peer recovery specialists, advocacy, recovery support, and CRAFT family training.",
    website_url: "https://saara.org/", phone: "804-762-4445",
    address: "2000 Mecklenburg St", city: "Richmond", zip: "23223",
    source_name: "SAARA of Virginia" },

  { section: "A", title: "Williamsburg Place / The Farley Center",
    cat: "substance-recovery", sub: "Veteran Recovery Programs",
    desc: "Williamsburg Place / Farley Center — long-running residential addiction treatment in Williamsburg with dedicated professionals' and veterans' programs; medical detox, residential, and aftercare.",
    website_url: "https://williamsburgplace.com/", phone: "757-565-0106",
    address: "5477 Mooretown Rd", city: "Williamsburg", zip: "23188",
    source_name: "Williamsburg Place" },

  { section: "A", title: "Mount Regis Center",
    cat: "substance-recovery", sub: "Detox Programs",
    desc: "Acadia-operated medical detox and residential addiction treatment center in Salem (Roanoke metro) — adult detox + residential rehab + outpatient continuing care.",
    website_url: "https://mountregis.com/", phone: "540-389-4761",
    address: "405 Kimball Ave", city: "Salem", zip: "24153",
    source_name: "Mount Regis Center" },

  { section: "A", title: "Boxwood Recovery Center",
    cat: "substance-recovery", sub: "Detox Programs",
    desc: "Inova-operated medical detox and residential addiction treatment center in Culpeper — short-term residential rehab + dual-diagnosis treatment for adults; serves NoVA + Central VA via Inova network.",
    website_url: "https://www.inova.org/", phone: "703-289-7560",
    address: "16401 Inova Way", city: "Culpeper", zip: "22701",
    source_name: "Inova Boxwood Recovery Center" },

  { section: "A", title: "Pinnacle Treatment Centers — Richmond",
    cat: "substance-recovery", sub: "Medication Assisted Treatment",
    desc: "Pinnacle Treatment Centers — opioid use disorder MAT clinic offering methadone, buprenorphine, and counseling services across multiple Virginia locations including Richmond, Petersburg, and Fredericksburg.",
    website_url: "https://pinnacletreatment.com/", phone: "804-358-1714",
    address: "5310 Twin Hickory Rd", city: "Glen Allen", zip: "23059",
    source_name: "Pinnacle Treatment Centers" },

  { section: "A", title: "Phoenix House Mid-Atlantic — Arlington",
    cat: "substance-recovery", sub: "Veteran Recovery Programs",
    desc: "Phoenix Houses of Mid-Atlantic — Arlington adult outpatient addiction treatment + veterans' specialty programming + DUI/court-ordered programming. Sliding-scale.",
    website_url: "https://www.phoenixhouse.org/", phone: "703-841-0703",
    address: "1900 N Beauregard St", city: "Alexandria", zip: "22311",
    source_name: "Phoenix Houses of Mid-Atlantic" },

  { section: "A", title: "Right Path Addiction Treatment Centers — Norfolk",
    cat: "substance-recovery", sub: "Medication Assisted Treatment",
    desc: "Right Path Addiction Treatment — MAT (Suboxone, Vivitrol) and outpatient counseling for opioid + alcohol use disorder; multiple Hampton Roads + Richmond locations.",
    website_url: "https://rightpathaddiction.com/", phone: "844-815-7325",
    address: "5700 Cleveland St", city: "Virginia Beach", zip: "23462",
    source_name: "Right Path Addiction Treatment Centers" },

  { section: "A", title: "Virginia AA Area 71 Central Office (Richmond)",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Alcoholics Anonymous Richmond Central Office — meeting directory for Richmond + Central VA; 24/7 hotline; literature; veteran-friendly meetings throughout region.",
    website_url: "https://aarichmond.org/", phone: "804-355-1212",
    address: "2825 Hathaway Rd, Suite L01", city: "Richmond", zip: "23225",
    source_name: "AA Richmond Central Office" },

  { section: "A", title: "Tidewater AA Intergroup",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Alcoholics Anonymous Hampton Roads/Tidewater Intergroup — meeting directory for Norfolk + VA Beach + Chesapeake + Portsmouth + Suffolk; 24/7 hotline; literature; veteran-friendly meetings.",
    website_url: "https://aatidewater.org/", phone: "757-490-3980",
    address: "5544 Greenwich Rd, Suite 102", city: "Virginia Beach", zip: "23462",
    source_name: "Tidewater AA Intergroup" },

  { section: "A", title: "Roanoke Valley AA Intergroup",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Alcoholics Anonymous Roanoke Valley Intergroup — meeting directory for Roanoke + Salem + SW Virginia; 24/7 hotline; literature; veteran-friendly meetings throughout region.",
    website_url: "https://aaroanoke.org/", phone: "540-343-6857",
    address: "1502 Williamson Rd NE", city: "Roanoke", zip: "24012",
    source_name: "Roanoke Valley AA Intergroup" },

  { section: "A", title: "Narcotics Anonymous Virginia Regional Service",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Narcotics Anonymous Virginia Regional Service Office — statewide meeting directory + 24/7 helpline + literature; in-person and online meetings; veteran-friendly throughout state.",
    website_url: "https://www.avcna.org/", phone: "800-777-1515",
    address: "PO Box 35253", city: "Richmond", zip: "23235",
    source_name: "NA Virginia Regional Service" },

  { section: "A", title: "ARMS Recovery Services (Roanoke)",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "ARMS — Addiction Recovery Management Services in Roanoke — outpatient counseling, intensive outpatient programs (IOP), MAT support, and family programs serving Roanoke Valley + SW Virginia.",
    website_url: "https://www.armsofroanoke.com/", phone: "540-562-0322",
    address: "4515 Brambleton Ave SW", city: "Roanoke", zip: "24018",
    source_name: "ARMS" },

  { section: "A", title: "Virginia Department of Behavioral Health Helpline",
    cat: "substance-recovery", sub: "Crisis Stabilization",
    desc: "Virginia DBHDS-operated 24/7 statewide substance use disorder helpline — connects callers to local CSB substance use treatment + Marcus Alert crisis services + veteran resources.",
    website_url: "https://dbhds.virginia.gov/substance-use-disorder/", phone: "844-543-3242",
    address: "1220 Bank St", city: "Richmond", zip: "23219",
    source_name: "Virginia DBHDS" },

  { section: "A", title: "Crossroads Treatment Centers — Norfolk",
    cat: "substance-recovery", sub: "Medication Assisted Treatment",
    desc: "Crossroads Treatment Centers — MAT (methadone, buprenorphine, naltrexone) + counseling for opioid use disorder; multiple Hampton Roads + Richmond locations.",
    website_url: "https://crossroadstreatmentcenters.com/", phone: "757-461-4900",
    address: "1029 Norfolk Sq", city: "Norfolk", zip: "23502",
    source_name: "Crossroads Treatment Centers" },

  { section: "A", title: "Hampton Roads Recovery Center",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Hampton Roads Recovery Center — outpatient counseling, IOP, and aftercare for adults with substance use disorder; serves Hampton + Newport News + Williamsburg + Peninsula.",
    website_url: "https://hamptonroadsrecovery.com/", phone: "757-722-2222",
    address: "742 Thimble Shoals Blvd", city: "Newport News", zip: "23606",
    source_name: "Hampton Roads Recovery Center" },

  { section: "A", title: "Recovery Centers of America at Capital Region",
    cat: "substance-recovery", sub: "Detox Programs",
    desc: "RCA Capital Region Waldorf-area facility (serves NoVA) — medical detox + residential rehab + outpatient + Resilience for Heroes (first responder + veteran) program.",
    website_url: "https://recoverycentersofamerica.com/", phone: "844-242-2233",
    address: "11100 Billingsley Rd", city: "Waldorf", zip: "20602",
    source_name: "Recovery Centers of America" },

  { section: "A", title: "SMART Recovery Virginia",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "SMART Recovery (Self-Management And Recovery Training) — secular, science-based mutual-aid recovery meetings throughout Virginia; in-person and online; veteran-friendly.",
    website_url: "https://www.smartrecovery.org/", phone: "440-951-5357",
    address: "PO Box 22320", city: "Richmond", zip: "23224",
    source_name: "SMART Recovery" },

  { section: "A", title: "Refuge Recovery Richmond",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Refuge Recovery — Buddhist-inspired non-12-step mutual-aid recovery meetings in Richmond + Charlottesville + virtual; trauma-informed, secular peer support.",
    website_url: "https://refugerecovery.org/", phone: "323-207-6178",
    address: "Multiple Richmond meeting sites", city: "Richmond", zip: "23220",
    source_name: "Refuge Recovery" },

  { section: "A", title: "Celebrate Recovery Virginia",
    cat: "substance-recovery", sub: "Peer Recovery Groups",
    desc: "Celebrate Recovery — faith-based 12-step recovery program meeting in dozens of Virginia churches across all regions; addiction, codependency, trauma; veteran-friendly.",
    website_url: "https://celebraterecovery.com/", phone: "949-609-8210",
    address: "Multiple Virginia church sites", city: "Richmond", zip: "23230",
    source_name: "Celebrate Recovery" },

  { section: "A", title: "Insight Recovery Centers Virginia Beach",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Insight Recovery Centers Virginia Beach — outpatient and intensive outpatient (IOP) addiction treatment with MAT; specialty programming for first responders and veterans.",
    website_url: "https://insighttreatment.com/", phone: "757-204-0040",
    address: "780 Lynnhaven Pkwy", city: "Virginia Beach", zip: "23452",
    source_name: "Insight Recovery Centers" },

  { section: "A", title: "Newport News Behavioral Health Center",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "UHS Newport News Behavioral Health Center — adult and adolescent outpatient and partial hospitalization for substance use + co-occurring disorders; serves Hampton Roads veterans.",
    website_url: "https://newportnewsbhc.com/", phone: "757-245-5650",
    address: "17579 Warwick Blvd", city: "Newport News", zip: "23603",
    source_name: "Newport News Behavioral Health Center" },

  { section: "A", title: "Virginia Recovery Hub (Marion)",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "Mount Rogers Health District Recovery Hub Marion — peer recovery specialists + recovery support services + naloxone distribution + MAT navigation for Smyth + Wythe + Bland + Galax + Carroll + Grayson.",
    website_url: "https://www.vdh.virginia.gov/mount-rogers/", phone: "276-781-7460",
    address: "1019 N Main St", city: "Marion", zip: "24354",
    source_name: "Virginia Department of Health Mount Rogers Health District" },

  // ===========================================================================
  // B. TRANSPORTATION (was 17 → +25)
  // ===========================================================================
  { section: "B", title: "Virginia DRPT Statewide Rideshare",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Virginia Department of Rail and Public Transportation — statewide rideshare matching, vanpool subsidies, transit grants; oversees regional transit authorities; serves all Virginia veterans needing transit options.",
    website_url: "https://drpt.virginia.gov/", phone: "804-786-4440",
    address: "600 E Main St, Suite 2102", city: "Richmond", zip: "23219",
    source_name: "Virginia DRPT" },

  { section: "B", title: "Bay Aging Bay Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Bay Aging Bay Transit — public bus + on-demand transit serving Middle Peninsula + Northern Neck (Essex, Gloucester, King and Queen, King William, Lancaster, Mathews, Middlesex, Northumberland, Richmond Co, Westmoreland).",
    website_url: "https://baytransit.org/", phone: "877-869-6046",
    address: "5306 Old Virginia St", city: "Urbanna", zip: "23175",
    source_name: "Bay Aging" },

  { section: "B", title: "Mountain Empire Older Citizens Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "MEOC Transit — Far SW Virginia public transit serving Lee + Scott + Wise + Norton; demand-response and fixed-route service for elderly, disabled, and veteran riders.",
    website_url: "https://www.meoc.org/", phone: "276-523-7433",
    address: "1501 3rd Ave E", city: "Big Stone Gap", zip: "24219",
    source_name: "Mountain Empire Older Citizens" },

  { section: "B", title: "District Three Public Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "District Three Governmental Cooperative public transit — SW Virginia rural transit serving Bland, Carroll, Grayson, Smyth, Wythe + Galax; connects rural veterans to Wytheville + regional medical centers.",
    website_url: "https://district-three.org/transit/", phone: "276-228-5751",
    address: "1141 S 4th St", city: "Wytheville", zip: "24382",
    source_name: "District Three Governmental Cooperative" },

  { section: "B", title: "Four County Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Cumberland Plateau public bus + demand-response transit serving Buchanan + Dickenson + Russell + Tazewell counties; connects rural SW VA veterans to Cedar Bluff + Tazewell + Lebanon.",
    website_url: "https://www.fourcountytransit.org/", phone: "276-963-4048",
    address: "224 Clydesway Dr", city: "Lebanon", zip: "24266",
    source_name: "Four County Transit" },

  { section: "B", title: "Loudoun County Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Loudoun County Transit — local bus, commuter bus to DC/Pentagon/Tysons, paratransit, and on-demand Metro Connection for Silver Line; reduced-fare for low-income riders + ADA Paratransit for disabled veterans.",
    website_url: "https://www.loudoun.gov/transit/", phone: "703-771-5665",
    address: "750 Miller Dr SE", city: "Leesburg", zip: "20175",
    source_name: "Loudoun County Transit" },

  { section: "B", title: "Fairfax Connector",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Fairfax County's local bus transit — 90+ routes connecting Fairfax + Reston + Tysons + Springfield + Pentagon + Metro stations; reduced-fare for low-income + ADA Paratransit (Fastran) for disabled veterans.",
    website_url: "https://www.fairfaxcounty.gov/connector/", phone: "703-339-7200",
    address: "4050 Legato Rd, Suite 400", city: "Fairfax", zip: "22033",
    source_name: "Fairfax Connector" },

  { section: "B", title: "Virginia Railway Express (VRE)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "VRE — commuter rail linking Fredericksburg + Manassas + Woodbridge + Quantico + Burke to L'Enfant Plaza + Union Station DC; serves NoVA veterans commuting to federal/Pentagon jobs.",
    website_url: "https://www.vre.org/", phone: "703-684-1001",
    address: "1500 King St, Suite 202", city: "Alexandria", zip: "22314",
    source_name: "Virginia Railway Express" },

  { section: "B", title: "DAV Transportation Network — Richmond VAMC",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "DAV-operated free transportation network for Richmond McGuire VAMC + CBOCs — volunteer drivers shuttle veterans to/from VA medical appointments throughout Central Virginia.",
    website_url: "https://www.dav.org/veterans/i-need-a-ride/", phone: "804-675-5526",
    address: "1201 Broad Rock Blvd", city: "Richmond", zip: "23249",
    source_name: "Disabled American Veterans" },

  { section: "B", title: "Hampton VAMC DAV Volunteer Driver Shuttle",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "DAV-operated free transportation network for Hampton VAMC + Hampton Roads CBOCs — volunteer drivers shuttle veterans to/from VA medical appointments throughout Hampton Roads.",
    website_url: "https://www.dav.org/veterans/i-need-a-ride/", phone: "757-722-9961",
    address: "100 Emancipation Dr", city: "Hampton", zip: "23667",
    source_name: "Disabled American Veterans" },

  { section: "B", title: "Salem VAMC DAV Volunteer Driver Shuttle",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "DAV-operated free transportation network for Salem VAMC + SW Virginia CBOCs — volunteer drivers shuttle veterans to/from VA medical appointments throughout SW Virginia.",
    website_url: "https://www.dav.org/veterans/i-need-a-ride/", phone: "540-982-2463",
    address: "1970 Roanoke Blvd", city: "Salem", zip: "24153",
    source_name: "Disabled American Veterans" },

  { section: "B", title: "ModivCare Virginia Medicaid NEMT",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "ModivCare — Virginia Medicaid Non-Emergency Medical Transport (NEMT) broker; arranges free rides to medical appointments for Medicaid-enrolled veterans statewide.",
    website_url: "https://www.modivcare.com/members/virginia/", phone: "866-386-8331",
    address: "PO Box 21266", city: "Richmond", zip: "23286",
    source_name: "ModivCare" },

  { section: "B", title: "American Cancer Society Road To Recovery — Virginia",
    cat: "transportation", sub: "Volunteer Driver Programs",
    desc: "ACS Road To Recovery Virginia — free volunteer-driver rides to cancer treatment for Virginia residents incl. veterans receiving oncology care at VAMCs or community partners.",
    website_url: "https://www.cancer.org/support-programs-and-services/road-to-recovery.html", phone: "800-227-2345",
    address: "4240 Park Pl Ct", city: "Glen Allen", zip: "23060",
    source_name: "American Cancer Society" },

  { section: "B", title: "RADAR Roanoke Area Paratransit",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "RADAR (Roanoke Area Dial-A-Ride) — ADA paratransit + medical transport + senior transportation serving Roanoke Valley; complements Valley Metro fixed routes for disabled veterans.",
    website_url: "https://radarbus.org/", phone: "540-343-1721",
    address: "1410 3rd St SW", city: "Roanoke", zip: "24016",
    source_name: "RADAR" },

  { section: "B", title: "Smart Way Bus (Roanoke-Blacksburg)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Smart Way intercity bus — operated by Valley Metro connecting Roanoke + Salem + Christiansburg + Blacksburg (Virginia Tech); reduced-fare; key route for SW Virginia veterans accessing Roanoke VAMC.",
    website_url: "https://valleymetro.com/smart-way-bus", phone: "540-982-2222",
    address: "1108 Campbell Ave SE", city: "Roanoke", zip: "24013",
    source_name: "Valley Metro" },

  { section: "B", title: "Suffolk Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "City of Suffolk Transit — local bus transit serving Suffolk + connections to Hampton Roads regional system; reduced-fare for low-income + ADA Paratransit for disabled veterans.",
    website_url: "https://www.suffolkva.us/365/Suffolk-Transit", phone: "757-539-2256",
    address: "415 Hall Ave", city: "Suffolk", zip: "23434",
    source_name: "Suffolk Transit" },

  { section: "B", title: "Rockbridge Area Transportation System (RATS)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "RATS — Rockbridge Area Transportation System serving Lexington + Buena Vista + Rockbridge County; demand-response + medical transport for elderly, disabled, and veteran residents.",
    website_url: "https://www.rockbridgetransit.org/", phone: "540-463-7280",
    address: "150 S Main St", city: "Lexington", zip: "24450",
    source_name: "Rockbridge Area Transportation System" },

  { section: "B", title: "Senior Connections Capital Area Aging",
    cat: "transportation", sub: "Volunteer Driver Programs",
    desc: "Senior Connections Capital Area Agency on Aging — Richmond-region transportation programs incl. Volunteer Driver, RIDE Connection, and senior NEMT for elderly + disabled veterans across Greater Richmond.",
    website_url: "https://www.seniorconnections-va.org/", phone: "804-343-3000",
    address: "24 E Cary St", city: "Richmond", zip: "23219",
    source_name: "Senior Connections Capital Area Agency on Aging" },

  { section: "B", title: "Goochland Cares Transportation",
    cat: "transportation", sub: "Volunteer Driver Programs",
    desc: "Goochland Cares — volunteer-driver transportation for Goochland County seniors + veterans + people with disabilities to medical appointments + grocery + essential services.",
    website_url: "https://goochlandcares.org/", phone: "804-556-6260",
    address: "2999 River Road W", city: "Goochland", zip: "23063",
    source_name: "Goochland Cares" },

  { section: "B", title: "STAR Transit (Smart Transit Authority of Roanoke)",
    cat: "transportation", sub: "Non-Emergency Medical Transport",
    desc: "STAR — Specialized Transit-Arranged Rides — ADA paratransit complement to Valley Metro Roanoke fixed-route service; door-to-door for disabled veterans + seniors.",
    website_url: "https://valleymetro.com/star", phone: "540-982-2222",
    address: "1108 Campbell Ave SE", city: "Roanoke", zip: "24013",
    source_name: "Valley Metro STAR" },

  { section: "B", title: "Three Rivers Healthy Families Transportation",
    cat: "transportation", sub: "Ride Assistance Programs",
    desc: "Three Rivers Healthy Families — Williamsburg-Peninsula transportation assistance for at-risk families incl. military/veteran families needing rides to prenatal care + early childhood services.",
    website_url: "https://www.threeriversfamily.org/", phone: "804-758-3322",
    address: "PO Box 1208", city: "Saluda", zip: "23149",
    source_name: "Three Rivers Healthy Families" },

  { section: "B", title: "Lake Country Area Agency on Aging Transit",
    cat: "transportation", sub: "Volunteer Driver Programs",
    desc: "Lake Country AAA — Southside Virginia (Brunswick, Halifax, Mecklenburg) volunteer-driver transportation + senior transit; serves elderly + disabled veterans in rural Southside.",
    website_url: "https://lakecountryaaa.org/", phone: "434-572-6259",
    address: "1105 W Danville St", city: "South Hill", zip: "23970",
    source_name: "Lake Country Area Agency on Aging" },

  { section: "B", title: "WinTran Winchester-Frederick Senior Transit",
    cat: "transportation", sub: "Volunteer Driver Programs",
    desc: "Shenandoah Area Agency on Aging — volunteer-driver and senior transportation for Winchester + Frederick + Clarke + Page + Shenandoah + Warren elderly + disabled veterans.",
    website_url: "https://shenandoahaaa.com/", phone: "540-635-7141",
    address: "207 Mosby Ln", city: "Front Royal", zip: "22630",
    source_name: "Shenandoah Area Agency on Aging" },

  { section: "B", title: "DASH Alexandria Transit",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Alexandria Transit Company DASH — City of Alexandria local bus + free fares since 2021; serves Old Town + West End + Eisenhower + Pentagon City + connects to Metro for veterans.",
    website_url: "https://www.dashbus.com/", phone: "703-746-3274",
    address: "3000 Business Center Dr", city: "Alexandria", zip: "22314",
    source_name: "Alexandria Transit Company" },

  { section: "B", title: "Arlington Transit (ART)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Arlington Transit ART — supplements Metrobus throughout Arlington County; reduced-fare iRide for low-income + STAR ADA Paratransit for disabled veterans.",
    website_url: "https://www.arlingtontransit.com/", phone: "703-228-7433",
    address: "2100 Clarendon Blvd", city: "Arlington", zip: "22201",
    source_name: "Arlington Transit" },

  // ===========================================================================
  // C. FINANCIAL & CREDIT (was 9 → +22)
  // ===========================================================================
  { section: "C", title: "VITA Tax Preparation — Greater Richmond",
    cat: "financial", sub: "Tax Preparation",
    desc: "Volunteer Income Tax Assistance (VITA) coordinated by United Way of Greater Richmond — free tax prep for low-to-moderate-income households incl. veteran families across Richmond region.",
    website_url: "https://www.yourunitedway.org/vita/", phone: "804-771-5800",
    address: "7400 Beaufont Springs Dr", city: "Richmond", zip: "23225",
    source_name: "United Way of Greater Richmond" },

  { section: "C", title: "Hampton Roads United Way Free Tax Sites",
    cat: "financial", sub: "Tax Preparation",
    desc: "VITA coordinated by United Way of South Hampton Roads — free tax prep for low-to-moderate-income households incl. military families across Norfolk + VA Beach + Chesapeake + Portsmouth + Suffolk.",
    website_url: "https://www.unitedwayshr.org/vita/", phone: "757-624-2400",
    address: "2515 Walmer Ave", city: "Norfolk", zip: "23513",
    source_name: "United Way of South Hampton Roads" },

  { section: "C", title: "AARP Tax-Aide Virginia",
    cat: "financial", sub: "Tax Preparation",
    desc: "AARP Foundation Tax-Aide — free tax prep at 100+ Virginia sites for adults 50+ (no AARP membership required); serves senior veterans across all VA regions.",
    website_url: "https://www.aarp.org/money/taxes/aarp_taxaide/", phone: "888-227-7669",
    address: "Virginia statewide sites", city: "Richmond", zip: "23230",
    source_name: "AARP Foundation Tax-Aide" },

  { section: "C", title: "Operation Homefront Critical Financial Assistance",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Operation Homefront — national veteran/military family emergency financial grants for housing, utilities, food, transportation, child care; serves Virginia veterans facing crisis.",
    website_url: "https://www.operationhomefront.org/", phone: "210-659-7756",
    address: "1355 Central Pkwy S, Suite 100", city: "San Antonio", zip: "78232",
    source_name: "Operation Homefront" },

  { section: "C", title: "VFW Unmet Needs Program",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "Veterans of Foreign Wars Unmet Needs program — emergency grants up to $1,500 for Virginia post-9/11 veteran/active-duty families covering rent, mortgage, utilities, vehicle, medical bills.",
    website_url: "https://www.vfw.org/assistance/financial-grants", phone: "816-756-3390",
    address: "VFW Department of Virginia, 706 Hospital Dr", city: "Dublin", zip: "24084",
    source_name: "Veterans of Foreign Wars" },

  { section: "C", title: "American Legion Temporary Financial Assistance",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "American Legion Temporary Financial Assistance (TFA) — emergency grants for minor children of eligible Virginia veterans + Operation Comfort Warriors care packages.",
    website_url: "https://www.legion.org/financialassistance", phone: "317-630-1207",
    address: "American Legion Department of Virginia, 1708 Commonwealth Ave", city: "Richmond", zip: "23230",
    source_name: "American Legion" },

  { section: "C", title: "Modest Needs Foundation",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Modest Needs — national nonprofit providing one-time emergency grants for working low-income Americans incl. Virginia veteran families; rent/mortgage, utilities, vehicle, medical bills.",
    website_url: "https://www.modestneeds.org/", phone: "888-499-9913",
    address: "115 E 23rd St, Suite 700", city: "New York", zip: "10010",
    source_name: "Modest Needs Foundation" },

  { section: "C", title: "Coalition to Salute America's Heroes",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "Coalition to Salute America's Heroes — emergency financial assistance + caregiver support for combat-wounded post-9/11 Virginia veterans and their families.",
    website_url: "https://saluteheroes.org/", phone: "888-447-2588",
    address: "1130 Crater Lake Ave", city: "Medford", zip: "97504",
    source_name: "Coalition to Salute America's Heroes" },

  { section: "C", title: "Dominion Energy EnergyShare",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Dominion Energy EnergyShare — emergency utility-bill assistance for Dominion customers (incl. Virginia veteran households) facing financial hardship; administered by local agencies.",
    website_url: "https://www.dominionenergy.com/energyshare", phone: "800-572-1419",
    address: "120 Tredegar St", city: "Richmond", zip: "23219",
    source_name: "Dominion Energy" },

  { section: "C", title: "Virginia LIHEAP — Energy Assistance",
    cat: "financial", sub: "Utility Bill Assistance",
    desc: "Virginia DSS-administered Low Income Home Energy Assistance Program — winter fuel assistance + cooling assistance + crisis assistance + weatherization; available statewide for income-qualified veteran households.",
    website_url: "https://www.dss.virginia.gov/benefit/ea.cgi", phone: "800-552-3431",
    address: "801 E Main St", city: "Richmond", zip: "23219",
    source_name: "Virginia DSS" },

  { section: "C", title: "Operation HOPE Inside — Atlanta (serves Hampton Roads)",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Operation HOPE — free 1-on-1 financial coaching, credit/budgeting help, small-business + homeownership coaching; HOPE Inside locations serve Hampton Roads + Richmond veteran families.",
    website_url: "https://operationhope.org/", phone: "888-388-4673",
    address: "Multiple Virginia HOPE Inside locations", city: "Norfolk", zip: "23510",
    source_name: "Operation HOPE" },

  { section: "C", title: "Catholic Charities Diocese of Richmond Financial Counseling",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Catholic Charities Diocese of Richmond — financial counseling, emergency financial assistance, immigration legal services, and case management for Central + Eastern + Southside Virginia veteran families.",
    website_url: "https://www.cccofva.org/", phone: "804-545-5900",
    address: "7800 Carousel Ln", city: "Richmond", zip: "23294",
    source_name: "Catholic Charities Diocese of Richmond" },

  { section: "C", title: "Catholic Charities Diocese of Arlington",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Catholic Charities Diocese of Arlington — financial counseling, emergency financial assistance, refugee + immigration services, and case management for Northern Virginia veteran families.",
    website_url: "https://www.ccda.net/", phone: "703-841-2600",
    address: "200 N Glebe Rd, Suite 506", city: "Arlington", zip: "22203",
    source_name: "Catholic Charities Diocese of Arlington" },

  { section: "C", title: "Goodwill of Central and Coastal Virginia Financial Coaching",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Goodwill of Central and Coastal Virginia — free financial coaching + jobs programs + Excel Center adult HS diploma; serves veteran families across Richmond + Hampton Roads + Charlottesville.",
    website_url: "https://goodwillvirginia.org/", phone: "804-745-6300",
    address: "6301 Midlothian Tpke", city: "Richmond", zip: "23225",
    source_name: "Goodwill of Central and Coastal Virginia" },

  { section: "C", title: "Bank On Hampton Roads",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Bank On Hampton Roads — coalition connecting unbanked + underbanked Hampton Roads residents (incl. veterans) with safe, low-cost bank accounts at participating banks + credit unions.",
    website_url: "https://www.unitedwayshr.org/bankon/", phone: "757-624-2400",
    address: "2515 Walmer Ave", city: "Norfolk", zip: "23513",
    source_name: "United Way of South Hampton Roads" },

  { section: "C", title: "Bank On Greater Richmond",
    cat: "financial", sub: "Banking / Lending Support",
    desc: "Bank On Greater Richmond — coalition connecting unbanked + underbanked Greater Richmond residents (incl. veterans) with safe, low-cost bank accounts at participating banks + credit unions.",
    website_url: "https://www.yourunitedway.org/bank-on/", phone: "804-771-5800",
    address: "7400 Beaufont Springs Dr", city: "Richmond", zip: "23225",
    source_name: "United Way of Greater Richmond" },

  { section: "C", title: "Lutheran Family Services of Virginia",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Lutheran Family Services of Virginia — financial counseling, foster care, refugee resettlement, and adoption services for Virginia families incl. veteran households.",
    website_url: "https://lfsva.org/", phone: "434-237-4006",
    address: "1716 Memorial Ave", city: "Lynchburg", zip: "24501",
    source_name: "Lutheran Family Services of Virginia" },

  { section: "C", title: "Capital Area Asset Builders (CAAB)",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Capital Area Asset Builders — DC-region financial empowerment serving NoVA (Arlington, Alexandria, Fairfax) — free financial coaching, matched savings (IDA), tax prep; serves NoVA veteran families.",
    website_url: "https://www.caab.org/", phone: "202-419-1440",
    address: "1100 15th St NW, Suite 400", city: "Washington", zip: "20005",
    source_name: "Capital Area Asset Builders" },

  { section: "C", title: "Virginia Cooperative Extension Family Financial Education",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Virginia Cooperative Extension (Virginia Tech + Virginia State) — free family + consumer financial education programs, workshops, and online resources statewide; veteran-friendly.",
    website_url: "https://www.ext.vt.edu/family.html", phone: "540-231-5299",
    address: "100 Hutcheson Hall, Virginia Tech", city: "Blacksburg", zip: "24061",
    source_name: "Virginia Cooperative Extension" },

  { section: "C", title: "Veterans Inc Financial Counseling",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "Veterans Inc — national SSVF and veteran emergency assistance grantee serving Virginia; rapid rehousing, homeless prevention, employment, and financial assistance for VA veteran families.",
    website_url: "https://www.veteransinc.org/", phone: "800-482-2565",
    address: "69 Grove St", city: "Worcester", zip: "01605",
    source_name: "Veterans Inc" },

  { section: "C", title: "Virginia 211",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Virginia 211 — statewide 24/7 information + referral helpline operated by Council of Community Services; connects Virginia veterans + families to emergency financial, food, housing, and crisis resources.",
    website_url: "https://www.211virginia.org/", phone: "211",
    address: "502 Campbell Ave SW", city: "Roanoke", zip: "24016",
    source_name: "Virginia 211" },

  { section: "C", title: "Salvation Army Virginia Emergency Financial Assistance",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Salvation Army Virginia statewide network — emergency rent/mortgage/utility assistance + Pathway of Hope case management; serves veteran families across all Virginia corps locations.",
    website_url: "https://salvationarmypotomac.org/", phone: "800-728-7825",
    address: "1043 Turkey Foot Rd", city: "Glen Allen", zip: "23059",
    source_name: "Salvation Army" },

  // ===========================================================================
  // D. LEGAL SERVICES (was 20 → +24)
  // ===========================================================================
  { section: "D", title: "Central Virginia Legal Aid Society",
    cat: "legal", sub: "Legal Aid Services",
    desc: "CVLAS — civil legal aid for Richmond + Petersburg + Charlottesville regions; housing, family, public benefits, consumer; serves Central VA veterans without VA enrollment.",
    website_url: "https://cvlas.org/", phone: "804-648-1012",
    address: "101 W Broad St, Suite 101", city: "Richmond", zip: "23220",
    source_name: "Central Virginia Legal Aid Society" },

  { section: "D", title: "VLAS Lynchburg Civil Legal Aid Hub",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Virginia Legal Aid Society main Lynchburg office — civil legal aid for Lynchburg + Halifax + Danville + Suffolk regions; housing, family, public benefits, elder law; serves Southside + Lynchburg-area veterans.",
    website_url: "https://vlas.org/", phone: "866-534-5243",
    address: "513 Church St", city: "Lynchburg", zip: "24504",
    source_name: "Virginia Legal Aid Society" },

  { section: "D", title: "Blue Ridge Legal Services",
    cat: "legal", sub: "Legal Aid Services",
    desc: "BRLS — civil legal aid for Shenandoah Valley + Roanoke + New River Valley; housing, family, public benefits; serves Western Virginia veterans without VA enrollment.",
    website_url: "https://brls.org/", phone: "540-433-1830",
    address: "204 N High St", city: "Harrisonburg", zip: "22802",
    source_name: "Blue Ridge Legal Services" },

  { section: "D", title: "Southwest Virginia Legal Aid Society",
    cat: "legal", sub: "Legal Aid Services",
    desc: "SWVLAS — civil legal aid for Far SW Virginia (Bristol + Abingdon + Wise + Tazewell + Russell); housing, family, public benefits; serves SW Virginia veterans without VA enrollment.",
    website_url: "https://www.svlas.org/", phone: "276-783-8300",
    address: "227 W Main St, Suite 100", city: "Marion", zip: "24354",
    source_name: "Southwest Virginia Legal Aid Society" },

  { section: "D", title: "Legal Aid Works Fredericksburg",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Legal Aid Works (formerly Rappahannock Legal Services) — civil legal aid for Fredericksburg + Stafford + Spotsylvania + King George + Northern Neck + Tappahannock; serves Central + Eastern VA veterans.",
    website_url: "https://legalaidworks.org/", phone: "540-371-1105",
    address: "500 Lafayette Blvd, Suite 200", city: "Fredericksburg", zip: "22401",
    source_name: "Legal Aid Works" },

  { section: "D", title: "William & Mary Lewis B Puller Veterans Benefits Clinic",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "W&M Law School Puller Clinic — free legal help for Virginia veterans on VA disability claims, appeals, discharge upgrades, and benefits counseling; staffed by law students under faculty supervision.",
    website_url: "https://law.wm.edu/academics/programs/jd/electives/clinics/veterans/", phone: "757-221-7443",
    address: "613 S Henry St", city: "Williamsburg", zip: "23185",
    source_name: "William & Mary Law School" },

  { section: "D", title: "George Mason Veterans and Servicemembers Legal Clinic",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "GMU Antonin Scalia Law School Veterans and Servicemembers Legal Clinic — free legal help for NoVA veterans on VA disability claims, discharge upgrades, family law; staffed by law students under faculty supervision.",
    website_url: "https://www.law.gmu.edu/academics/clinics/vsclc", phone: "703-993-8088",
    address: "3301 Fairfax Dr", city: "Arlington", zip: "22201",
    source_name: "George Mason Antonin Scalia Law School" },

  { section: "D", title: "University of Richmond Veterans Legal Clinic",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "UR Law School National Center for Family Law Veterans Legal Clinic — free legal help for Richmond-area veterans on family law, VA benefits, discharge upgrades; staffed by law students under faculty supervision.",
    website_url: "https://law.richmond.edu/", phone: "804-289-8190",
    address: "203 Richmond Way", city: "Richmond", zip: "23173",
    source_name: "University of Richmond Law School" },

  { section: "D", title: "Washington and Lee Black Lung Legal Clinic",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "W&L Law School Black Lung Clinic — free legal help for SW Virginia coal miners + veterans on federal Black Lung benefits + related disability claims; staffed by law students under faculty supervision.",
    website_url: "https://law2.wlu.edu/blacklung/", phone: "540-458-8530",
    address: "Sydney Lewis Hall, 204 W Washington St", city: "Lexington", zip: "24450",
    source_name: "Washington and Lee Law School" },

  { section: "D", title: "National Veterans Legal Services Program (NVLSP)",
    cat: "legal", sub: "VA Benefits Appeals",
    desc: "NVLSP — DC-based national nonprofit providing free + low-cost legal help on VA benefits appeals to Virginia veterans + survivors; CCK and Lawyers Serving Warriors programs.",
    website_url: "https://www.nvlsp.org/", phone: "202-265-8305",
    address: "1100 Wilson Blvd, Suite 900", city: "Arlington", zip: "22209",
    source_name: "NVLSP" },

  { section: "D", title: "Veterans Consortium Pro Bono Program",
    cat: "legal", sub: "VA Benefits Appeals",
    desc: "Veterans Consortium Pro Bono — DC-based national pro bono program matching Virginia veterans with attorneys for free representation on Court of Appeals for Veterans Claims appeals + discharge upgrades.",
    website_url: "https://www.vetsprobono.org/", phone: "888-838-7727",
    address: "1100 Wilson Blvd, Suite 970-S", city: "Arlington", zip: "22209",
    source_name: "Veterans Consortium" },

  { section: "D", title: "ABA Military Pro Bono Project",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "ABA Military Pro Bono Project + Operation Stand-By — connects Virginia active-duty + veteran military families with pro bono attorneys for civil legal matters; military legal-assistance referrals.",
    website_url: "https://www.militaryprobono.org/", phone: "312-988-5775",
    address: "321 N Clark St", city: "Chicago", zip: "60654",
    source_name: "American Bar Association" },

  { section: "D", title: "Virginia Free Legal Answers",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Virginia Free Legal Answers — Virginia State Bar online platform connecting low-income Virginians (incl. veterans) with volunteer attorneys for free brief civil legal advice; family, housing, consumer, benefits.",
    website_url: "https://virginia.freelegalanswers.org/", phone: "804-775-0500",
    address: "1111 E Main St, Suite 700", city: "Richmond", zip: "23219",
    source_name: "Virginia State Bar" },

  { section: "D", title: "Virginia Poverty Law Center",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Virginia Poverty Law Center — Richmond-based statewide legal advocacy + training + impact litigation supporting Virginia's six legal aid programs; specialized projects on housing, healthcare, consumer, and benefits.",
    website_url: "https://vplc.org/", phone: "804-782-9430",
    address: "919 E Main St, Suite 610", city: "Richmond", zip: "23219",
    source_name: "Virginia Poverty Law Center" },

  { section: "D", title: "Virginia State Bar Lawyer Referral Service",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Virginia State Bar LRS — refers callers to Virginia attorneys for reduced-fee 30-minute consultations; veteran-friendly with reduced-fee veterans intake.",
    website_url: "https://www.vsb.org/site/sections/lrs/", phone: "804-775-0808",
    address: "1111 E Main St, Suite 700", city: "Richmond", zip: "23219",
    source_name: "Virginia State Bar" },

  { section: "D", title: "Stateside Legal",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Stateside Legal — LSC-funded national online resource center connecting Virginia veterans + military families with legal information, self-help tools, and local legal aid + military legal assistance referrals.",
    website_url: "https://statesidelegal.org/", phone: "207-774-8211",
    address: "Pine Tree Legal Assistance, 88 Federal St", city: "Portland", zip: "04101",
    source_name: "Stateside Legal" },

  { section: "D", title: "Virginia Indigent Defense Commission",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Virginia IDC — statewide network of Public Defender Offices providing free criminal defense to indigent Virginians (incl. veterans); 25+ offices across Commonwealth.",
    website_url: "https://www.vadefenders.org/", phone: "804-225-3297",
    address: "1604 Santa Rosa Rd, Suite 109", city: "Richmond", zip: "23229",
    source_name: "Virginia Indigent Defense Commission" },

  { section: "D", title: "JAG Legal Assistance Office — Naval Station Norfolk",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Region Legal Service Office Mid-Atlantic Naval Station Norfolk — free legal assistance for active-duty + retired veterans + dependents on family law, wills, powers of attorney, consumer, and landlord/tenant.",
    website_url: "https://www.jag.navy.mil/legal_services/rlso/", phone: "757-444-3266",
    address: "9620 Maryland Ave", city: "Norfolk", zip: "23511",
    source_name: "Region Legal Service Office Mid-Atlantic" },

  { section: "D", title: "JBLE Staff Judge Advocate Legal Assistance",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "JBLE Legal Office — free legal assistance for active-duty + retired veterans + dependents on Joint Base Langley-Eustis on family law, wills, powers of attorney, consumer, and landlord/tenant.",
    website_url: "https://www.jble.af.mil/", phone: "757-764-3277",
    address: "45 Nealy Ave", city: "Hampton", zip: "23665",
    source_name: "Joint Base Langley-Eustis" },

  { section: "D", title: "Marine Corps Base Quantico Legal Assistance",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "MCB Quantico Legal Assistance Office — free legal assistance for active-duty + retired veterans + dependents on family law, wills, powers of attorney, consumer, and landlord/tenant.",
    website_url: "https://www.quantico.marines.mil/", phone: "703-784-2706",
    address: "3250 Catlin Ave", city: "Quantico", zip: "22134",
    source_name: "Marine Corps Base Quantico" },

  { section: "D", title: "Fort Belvoir Legal Assistance Office",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Fort Belvoir Legal Assistance Office — free legal assistance for active-duty + retired veterans + dependents on family law, wills, powers of attorney, consumer, and landlord/tenant.",
    website_url: "https://home.army.mil/belvoir/", phone: "703-805-2856",
    address: "9990 Belvoir Rd", city: "Fort Belvoir", zip: "22060",
    source_name: "Fort Belvoir" },

  { section: "D", title: "Veterans Pro Bono Network of Virginia",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "Veterans Pro Bono Network — Virginia State Bar veterans pro bono initiative connecting Virginia veterans with volunteer attorneys for civil matters incl. wills, family law, landlord/tenant, and benefits.",
    website_url: "https://www.vsb.org/site/sections/military/", phone: "804-775-0500",
    address: "1111 E Main St, Suite 700", city: "Richmond", zip: "23219",
    source_name: "Virginia State Bar Military Law Section" },

  { section: "D", title: "Justice for Vets Veterans Treatment Court Network",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Justice For Vets — national initiative supporting Virginia's Veterans Treatment Courts (Norfolk, VA Beach, Hampton, Fairfax, Henrico, Chesterfield); training, mentor support, and resources for justice-involved veterans.",
    website_url: "https://justiceforvets.org/", phone: "703-575-9400",
    address: "1029 N Royal St, Suite 201", city: "Alexandria", zip: "22314",
    source_name: "Justice For Vets" },

  { section: "D", title: "Tidewater Legal Aid Society",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Tidewater Legal Aid Society — civil legal aid for Norfolk + VA Beach + Chesapeake + Portsmouth + Suffolk + Eastern Shore; housing, family, public benefits; serves Hampton Roads veterans without VA enrollment.",
    website_url: "https://tlasinc.org/", phone: "757-627-5423",
    address: "125 St Pauls Blvd, Suite 400", city: "Norfolk", zip: "23510",
    source_name: "Tidewater Legal Aid Society" },
];

await runSeed(ROWS, {
  state: "VA",
  commit: COMMIT,
  scriptName: "seed-va-wave5.ts (FL-pattern Wave 5 / statewide depth fill — Option A)",
  urlCheckTimeoutMs: 12000,
  allowBrokenUrls: ALLOW_BROKEN_URLS,
  allowZipBleed: ALLOW_ZIP_BLEED,
  sectionLabels: {
    A: "Substance Recovery (gap-fill from 2)",
    B: "Transportation (depth)",
    C: "Financial & Credit (depth)",
    D: "Legal Services (depth)",
  },
});
