/**
 * Texas Phase 1 — Batch 1: Statewide Backbone
 *
 * Goal: ~125 sponsor-grade statewide rows that anchor every subsequent batch.
 *
 * Discipline:
 *   - Every row's website_url is a published canonical org URL (not a deep
 *     path that rots). The new URL liveness gate will fail-fast on any 4xx.
 *   - No row has fabricated phone or address. Where unverified, fields are
 *     null. Phones included only where the number is widely published across
 *     multiple canonical sources (TVC main hotline, TWC main, etc.).
 *   - Statewide rows have no city/zip → ZIP gate passes automatically.
 *   - City-anchored rows (State Veterans Homes, State Veterans Cemeteries,
 *     TVC Austin HQ) carry city + city-canonical 5-digit ZIP from VLB roster.
 *   - Titles: NO leading-dash differentiators (engine normalizeTitle strips
 *     after first dash). NO trailing parens (also stripped). Each entity gets
 *     a UNIQUE substantive title.
 *
 * Source of truth:
 *   - TVC programs: https://www.tvc.texas.gov/
 *   - VLB / GLO: https://www.glo.texas.gov/vlb/
 *   - State agency vet sub-units: agency.gov landing pages
 *   - VSO TX departments: each org's national directory
 *   - University vet centers: each university's official VRC URL
 */

import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");
const ALLOW_ZIP_BLEED = process.argv.includes("--allow-zip-bleed");

const ROWS: SeedRow[] = [
  // ============================================================
  // Section TVC — Texas Veterans Commission programs (15)
  // ============================================================
  {
    section: "TVC",
    title: "Texas Veterans Commission",
    cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation",
    desc: "Statewide agency advocating for and providing direct services to Texas veterans. Coordinates claims, education, employment, mental health, and entrepreneur programs across Texas.",
    website_url: "https://www.tvc.texas.gov/",
    phone: "1-800-252-8387",
    address: "1700 N. Congress Ave., Suite 800",
    city: "Austin", zip: "78701",
    eligibility: "All Texas veterans and dependents",
    source_name: "TVC official website (tvc.texas.gov)",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Claims Representation Program",
    cat: "va-benefits", sub: "VA Claims Assistance (DAV, VSO, etc.)",
    desc: "TVC's accredited Veterans Benefits Counselors who file VA claims and represent veterans through the disability compensation, pension, and appeals process. Counselors stationed at VA Regional Office Waco and at VA medical centers across Texas.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "All Texas veterans and dependents filing VA claims",
    source_name: "TVC Claims Representation program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Veterans Mental Health Department",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Statewide network of regional mental-health coordinators connecting Texas veterans and families to peer support, counseling, and crisis services. Anchors the TVC Mental Health Grant program.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "All Texas veterans and family members",
    source_name: "TVC Veterans Mental Health Department program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Veterans Education Program",
    cat: "education", sub: "GI Bill Assistance",
    desc: "State Approving Agency for veterans education benefits in Texas. Approves and oversees GI Bill programs at Texas schools, training providers, and apprenticeships. Administers the Hazlewood Act tuition exemption.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas veterans, dependents, and approved education providers",
    source_name: "TVC Veterans Education program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Veterans Employment Services",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "State employment services for Texas veterans, including DVOP (Disabled Veterans Outreach Program) and LVER (Local Veterans Employment Representative) staff embedded across the Texas Workforce Solutions network.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas veterans and transitioning service members",
    source_name: "TVC Veterans Employment Services program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Health Care Advocacy Program",
    cat: "healthcare", sub: "VA Healthcare Enrollment",
    desc: "Helps Texas veterans navigate VA health-care enrollment, appointments, and resolve issues with VA health-care delivery. Statewide advocates serve as liaison between veterans and the VA medical centers in Texas.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas veterans enrolled or eligible for VA health care",
    source_name: "TVC Health Care Advocacy program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Women Veterans Program",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Statewide outreach and benefits navigation for women veterans in Texas. Coordinates resource fairs, peer-support cohorts, and coordinates with VA Women Veterans Program Managers across Texas VA medical centers.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Women veterans residing in Texas",
    source_name: "TVC Women Veterans Program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "Texas Veterans Leadership Program",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "TVC peer-mentor network for post-9/11 Texas veterans. Regional Veteran Resource and Referral specialists connect veterans to benefits, education, employment, mental health, and housing resources.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Post-9/11 Texas veterans",
    source_name: "TVC TVLP program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Veteran Entrepreneur Program",
    cat: "employment", sub: "Entrepreneurship & Small Business Support",
    desc: "Free statewide business consulting, training, and capital-access support for Texas veteran entrepreneurs. Partners with the Texas SBDC network and U.S. Small Business Administration.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas veteran-owned or veteran-led businesses",
    source_name: "TVC Veteran Entrepreneur Program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "Hazlewood Act Tuition Exemption",
    cat: "education", sub: "Tuition Assistance",
    desc: "Texas state education benefit providing up to 150 credit hours of tuition exemption at public Texas colleges and universities for qualifying veterans, eligible spouses, and dependent children (Hazlewood Legacy).",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Qualifying Texas veterans and dependents at public TX institutions",
    source_name: "TVC Hazlewood Act program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Fund for Veterans Assistance General Assistance Grant",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "TVC FVA grant program funding nonprofits across Texas that provide direct financial, transportation, food, and emergency assistance to Texas veterans and their families.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas-based nonprofits serving veterans (operates as a grantor)",
    source_name: "TVC FVA General Assistance Grant program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Fund for Veterans Assistance Housing 4 Texas Heroes Grant",
    cat: "housing", sub: "Rental Assistance",
    desc: "TVC FVA grant program funding nonprofits across Texas that provide rental assistance, transitional housing, and homelessness prevention services for Texas veterans.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas-based housing-services nonprofits serving veterans",
    source_name: "TVC FVA Housing 4 Texas Heroes Grant program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Fund for Veterans Assistance Veterans Mental Health Grant",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "TVC FVA grant program funding nonprofits delivering peer support, counseling, and behavioral-health services for Texas veterans and family members.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas-based mental-health nonprofits serving veterans",
    source_name: "TVC FVA Veterans Mental Health Grant program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Fund for Veterans Assistance Veterans Treatment Court Grant",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "TVC FVA grant program funding county Veterans Treatment Courts and supporting peer-mentor coordinators across Texas.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas county Veterans Treatment Court programs",
    source_name: "TVC FVA Veterans Treatment Court Grant program page",
    source_type: "state_agency",
  },
  {
    section: "TVC",
    title: "TVC Fund for Veterans Assistance County Service Office Grant",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "TVC FVA grant program supporting county Veterans Service Offices statewide with operational funding to expand benefits-counseling capacity.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas county VSO offices",
    source_name: "TVC FVA County Veterans Service Office Grant program page",
    source_type: "state_agency",
  },

  // ============================================================
  // Section GLO — Texas General Land Office / VLB programs (8)
  // ============================================================
  {
    section: "GLO",
    title: "Texas Veterans Land Board",
    cat: "financial", sub: "VA Loans",
    desc: "Texas General Land Office's veterans agency administering land loans, home loans, and home-improvement loans for Texas veterans. The only state-run veterans land program in the U.S.",
    website_url: "https://vlb.texas.gov/",
    phone: "1-800-252-8387",
    address: "1700 N. Congress Ave., Suite 935",
    city: "Austin", zip: "78701",
    eligibility: "Texas veterans meeting service and residency requirements",
    source_name: "VLB official website (vlb.texas.gov)",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "VLB Land Loan Program",
    cat: "financial", sub: "Personal Loans",
    desc: "VLB program offering Texas veterans below-market financing on tracts of one acre or more anywhere in Texas. Loans up to $150,000 with 5% down, no acreage cap if rural.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "Texas veterans (1+ year residency at time of application)",
    source_name: "VLB Land Loan Program page",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "VLB Veterans Housing Assistance Program",
    cat: "housing", sub: "VA Home Loans",
    desc: "VLB home loan program providing below-market interest rates on home purchases for Texas veterans. Stackable with the federal VA Home Loan Guaranty.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "Texas veterans, surviving spouses, and qualifying military",
    source_name: "VLB Veterans Housing Assistance Program page",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "VLB Home Improvement Loan Program",
    cat: "housing", sub: "Accessibility Modifications",
    desc: "VLB program providing low-interest loans up to $50,000 for major home improvements and accessibility modifications for Texas veterans.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "Texas veteran homeowners",
    source_name: "VLB Home Improvement Loan Program page",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "Texas State Veterans Homes Program",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-administered network of skilled-nursing care facilities across Texas serving veterans, spouses, and Gold Star parents. Affordable subsidized rates and 24/7 nursing care.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "Texas veterans, spouses, and Gold Star parents",
    source_name: "VLB State Veterans Homes program page",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "Texas State Veterans Cemeteries Program",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VLB-administered statewide system of veterans cemeteries providing burial benefits at no cost to eligible veterans, spouses, and dependent children.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "All veterans (federal eligibility), spouses, dependent children",
    source_name: "VLB State Veterans Cemeteries program page",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "Voices for Veterans Oral History Program",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "GLO program preserving the recorded oral histories of Texas veterans. Free recording, preservation in the Texas State Archives, and copy returned to the veteran's family.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "All Texas veterans",
    source_name: "VLB Voices for Veterans program page",
    source_type: "state_agency",
  },
  {
    section: "GLO",
    title: "VLB Veterans Outreach Coordinators",
    cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation",
    desc: "Statewide field network of VLB coordinators who travel to county VSOs, veterans events, and military bases across Texas to brief veterans on land/home loan and benefits eligibility.",
    website_url: "https://vlb.texas.gov/",
    eligibility: "All Texas veterans",
    source_name: "VLB Outreach program page",
    source_type: "state_agency",
  },

  // ============================================================
  // Section HOME — Texas State Veterans Homes (7 individually verifiable)
  // ============================================================
  {
    section: "HOME",
    title: "Frank M. Tejeda Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the South Texas / San Antonio region. 160-bed facility with 24/7 nursing care.",
    website_url: "https://vlb.texas.gov/",
    city: "Floresville", zip: "78114",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },
  {
    section: "HOME",
    title: "William R. Courtney Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the North Texas / Bonham region. Adjacent to the Sam Rayburn Memorial VA medical center.",
    website_url: "https://vlb.texas.gov/",
    city: "Bonham", zip: "75418",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },
  {
    section: "HOME",
    title: "Lamun Lusk Sanchez Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the West Texas / Permian Basin region.",
    website_url: "https://vlb.texas.gov/",
    city: "Big Spring", zip: "79720",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },
  {
    section: "HOME",
    title: "Ambrosio Guillen Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the El Paso / Trans-Pecos region.",
    website_url: "https://vlb.texas.gov/",
    city: "El Paso", zip: "79935",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },
  {
    section: "HOME",
    title: "Alfredo Gonzalez Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the Rio Grande Valley region.",
    website_url: "https://vlb.texas.gov/",
    city: "McAllen", zip: "78504",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },
  {
    section: "HOME",
    title: "Clyde W. Cosper Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the Central Texas / Temple region. Adjacent to the Olin E. Teague VA medical center.",
    website_url: "https://vlb.texas.gov/",
    city: "Temple", zip: "76502",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },
  {
    section: "HOME",
    title: "Richard A. Anderson Texas State Veterans Home",
    cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes",
    desc: "VLB-operated skilled nursing care facility serving Texas veterans, spouses, and Gold Star parents in the Greater Houston region.",
    website_url: "https://vlb.texas.gov/",
    city: "Houston", zip: "77076",
    eligibility: "Texas veterans, spouses, Gold Star parents",
    source_name: "VLB State Veterans Homes roster",
    source_type: "state_agency",
  },

  // ============================================================
  // Section CEM — Texas State Veterans Cemeteries (4)
  // ============================================================
  {
    section: "CEM",
    title: "Texas State Veterans Cemetery at Killeen",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VLB-operated state veterans cemetery in the Central Texas / Fort Cavazos region. Burial benefits at no cost to eligible veterans, spouses, and dependent children.",
    website_url: "https://vlb.texas.gov/",
    city: "Killeen", zip: "76542",
    eligibility: "All veterans (federal eligibility), spouses, dependent children",
    source_name: "VLB State Veterans Cemeteries roster",
    source_type: "state_agency",
  },
  {
    section: "CEM",
    title: "Texas State Veterans Cemetery at Mission",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VLB-operated state veterans cemetery serving the Rio Grande Valley region. Burial benefits at no cost to eligible veterans, spouses, and dependent children.",
    website_url: "https://vlb.texas.gov/",
    city: "Mission", zip: "78572",
    eligibility: "All veterans (federal eligibility), spouses, dependent children",
    source_name: "VLB State Veterans Cemeteries roster",
    source_type: "state_agency",
  },
  {
    section: "CEM",
    title: "Texas State Veterans Cemetery at Abilene",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VLB-operated state veterans cemetery serving the West Texas / Big Country region. Burial benefits at no cost to eligible veterans, spouses, and dependent children.",
    website_url: "https://vlb.texas.gov/",
    city: "Abilene", zip: "79602",
    eligibility: "All veterans (federal eligibility), spouses, dependent children",
    source_name: "VLB State Veterans Cemeteries roster",
    source_type: "state_agency",
  },
  {
    section: "CEM",
    title: "Coastal Bend State Veterans Cemetery",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "VLB-operated state veterans cemetery serving the Corpus Christi / Coastal Bend region. Burial benefits at no cost to eligible veterans, spouses, and dependent children.",
    website_url: "https://vlb.texas.gov/",
    city: "Corpus Christi", zip: "78415",
    eligibility: "All veterans (federal eligibility), spouses, dependent children",
    source_name: "VLB State Veterans Cemeteries roster",
    source_type: "state_agency",
  },

  // ============================================================
  // Section AGENCY — Other state agency vet sub-units (9)
  // ============================================================
  {
    section: "AGENCY",
    title: "Texas Workforce Commission Veterans Services",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "TWC's statewide veterans employment program, embedding DVOP and LVER specialists at every Texas Workforce Solutions office. Priority service, job-search assistance, and apprenticeship referrals for Texas veterans.",
    website_url: "https://www.twc.texas.gov/",
    phone: "1-800-628-5115",
    eligibility: "All Texas veterans and transitioning service members",
    source_name: "TWC Veterans Services program page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "TWC USERRA Texas Hotline",
    cat: "legal", sub: "Employment Law",
    desc: "Texas Workforce Commission's USERRA (Uniformed Services Employment and Reemployment Rights Act) help line for Texas veterans, Guard, and Reserve members facing employment discrimination or reemployment issues.",
    website_url: "https://www.twc.texas.gov/",
    phone: "1-800-628-5115",
    eligibility: "Texas veterans, Guard, Reserve members",
    source_name: "TWC USERRA program page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas Health and Human Services Veterans Mental Health Initiative",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "HHSC initiative coordinating local mental-health authorities (LMHAs) and certified providers across Texas to deliver veteran-specific behavioral-health care.",
    website_url: "https://www.hhs.texas.gov/",
    eligibility: "Texas veterans and family members",
    source_name: "HHSC Military and Veterans Services page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas Department of Licensing and Regulation Military Provisions",
    cat: "employment", sub: "Certification Programs",
    desc: "TDLR program providing fee waivers, expedited licensing, and credit-for-experience for Texas veterans, military spouses, and active-duty service members applying for state-issued occupational licenses.",
    website_url: "https://www.tdlr.texas.gov/",
    eligibility: "Texas veterans, military spouses, active duty",
    source_name: "TDLR Military Provisions page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas DPS Veteran Designation on Driver License",
    cat: "va-benefits", sub: "Military Records & DD214",
    desc: "Texas Department of Public Safety program adding a Veteran designation to a Texas driver license or ID card, used to access state and merchant veteran discounts and services.",
    website_url: "https://www.dps.texas.gov/",
    eligibility: "Honorably discharged Texas-resident veterans",
    source_name: "TX DPS Veteran Designation program page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas Parks and Wildlife Disabled Veteran Hunting and Fishing License",
    cat: "disabled-veterans", sub: "Adaptive Recreation",
    desc: "TPWD program providing free Super Combo hunting and fishing license packages to Texas resident veterans with a 50%+ VA service-connected disability rating.",
    website_url: "https://tpwd.texas.gov/",
    eligibility: "Texas-resident veterans with 50%+ VA disability rating",
    source_name: "TPWD Disabled Veterans License program page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas Comptroller Veteran-Owned Business Designation",
    cat: "employment", sub: "Entrepreneurship & Small Business Support",
    desc: "Texas Comptroller program providing a 5-year exemption from franchise tax and the $25 business-formation fee for new businesses formed by Texas veterans.",
    website_url: "https://comptroller.texas.gov/",
    eligibility: "Texas veterans forming a new business entity",
    source_name: "Texas Comptroller Veteran-Owned Business page",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas Veterans County Service Office Network",
    cat: "va-benefits", sub: "County Veterans Service Offices",
    desc: "TVC-coordinated statewide network of 254 county-level Veterans Service Offices providing free claims-filing assistance and benefits navigation. The local point of contact for VA claims in every Texas county.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "All Texas veterans and dependents",
    source_name: "TVC County Service Officer Directory",
    source_type: "state_agency",
  },
  {
    section: "AGENCY",
    title: "Texas State Cemetery Veterans Section",
    cat: "end-of-life-services", sub: "Veteran Funeral Honors & Cemetery Assistance",
    desc: "Historic state cemetery in Austin maintained by the Texas Facilities Commission. Final resting place of Texas governors, congressional Medal of Honor recipients, and other distinguished Texans including many veterans.",
    website_url: "https://cemetery.tspb.texas.gov/",
    address: "909 Navasota St.",
    city: "Austin", zip: "78702",
    eligibility: "Distinguished Texans (subject to State Cemetery Committee approval)",
    source_name: "Texas State Cemetery official website",
    source_type: "state_agency",
  },

  // ============================================================
  // Section HOTLINE — Statewide Texas vet hotlines / crisis lines (5)
  // ============================================================
  {
    section: "HOTLINE",
    title: "Texas 211 Information and Referral Service",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "Texas 211 (operated by HHSC) is a free, confidential, 24/7 statewide hotline connecting Texans to social services, including veteran-specific resources, mental-health crisis support, and rental/utility assistance.",
    website_url: "https://www.211texas.org/",
    phone: "211",
    eligibility: "All Texas residents",
    source_name: "Texas 211 official website",
    source_type: "state_agency",
  },
  {
    section: "HOTLINE",
    title: "Texas Veterans Toll-Free Hotline",
    cat: "va-benefits", sub: "VA Enrollment & General Benefits Navigation",
    desc: "TVC's master statewide hotline for Texas veterans. Single-number entry point routing callers to TVC claims, education, employment, mental health, women veterans, and outreach services.",
    website_url: "https://www.tvc.texas.gov/",
    phone: "1-800-252-8387",
    eligibility: "All Texas veterans and family members",
    source_name: "TVC contact page",
    source_type: "state_agency",
  },
  {
    section: "HOTLINE",
    title: "Texas Veterans Family Mental Health Network",
    cat: "mental-health", sub: "Family Support (Mental Health)",
    desc: "Statewide network coordinated by HHSC and TVC connecting Texas veteran families to behavioral-health services, including the Military Veteran Peer Network and local mental-health authorities.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas veterans and family members",
    source_name: "MVPN Texas official website",
    source_type: "nonprofit",
  },
  {
    section: "HOTLINE",
    title: "Military Veteran Peer Network of Texas",
    cat: "mental-health", sub: "Peer Support",
    desc: "TVC-funded statewide peer-mentor network deploying trained peer-support specialists across Texas. Coordinates regional peer-support coordinators in every TVC region.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Texas veterans, service members, and family members",
    source_name: "MVPN Texas program page",
    source_type: "state_program",
  },
  {
    section: "HOTLINE",
    title: "Texas Hope Line",
    cat: "crisis-help", sub: "Suicide Prevention",
    desc: "Statewide Texas hotline coordinated by HHSC providing 24/7 crisis counseling and referrals, including a veterans-and-military line.",
    website_url: "https://www.hhs.texas.gov/",
    eligibility: "All Texas residents in crisis",
    source_name: "HHSC Mental Health Crisis Services page",
    source_type: "state_agency",
  },

  // ============================================================
  // Section VSO — TX Department-level Veterans Service Organizations (12)
  // ============================================================
  {
    section: "VSO",
    title: "American Legion Department of Texas",
    cat: "community-support", sub: "American Legion Posts",
    desc: "State-level headquarters of the American Legion in Texas, coordinating ~600 local Legion posts across the state. Provides VA-accredited service officers, scholarship programs, and community-service initiatives.",
    website_url: "https://www.txlegion.org/",
    address: "3401 Ed Bluestein Blvd.",
    city: "Austin", zip: "78721",
    eligibility: "Honorably discharged wartime-era veterans (Legion eligibility)",
    source_name: "American Legion Department of Texas official website",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "VFW Department of Texas",
    cat: "community-support", sub: "VFW Posts",
    desc: "State-level headquarters of the Veterans of Foreign Wars in Texas, coordinating local VFW posts statewide. Provides VA-accredited service officers and the VFW Unmet Needs financial assistance program.",
    website_url: "https://www.texasvfw.org/",
    eligibility: "Veterans with overseas/expeditionary service (VFW eligibility)",
    source_name: "VFW Department of Texas official website",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "DAV Department of Texas",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "State-level headquarters of Disabled American Veterans in Texas, coordinating DAV chapters statewide. Free VA-accredited claims representation, transportation network, and benefits-counseling services.",
    website_url: "https://www.davtexas.org/",
    eligibility: "Veterans with service-connected disabilities",
    source_name: "DAV Department of Texas official website",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "AMVETS Department of Texas",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "State-level headquarters of AMVETS in Texas. Provides VA-accredited national service officers, career and benefits counseling, and community-service programs at AMVETS posts statewide.",
    website_url: "https://www.amvets.org/",
    eligibility: "Honorably discharged veterans of any era",
    source_name: "AMVETS Department of Texas official website",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "Military Officers Association of America Texas Council",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Texas state council coordinating MOAA chapters statewide for active, retired, and former officers and their families. Career transition, scholarship, and advocacy programs.",
    website_url: "https://www.moaa.org/",
    eligibility: "Active, retired, and former officers (MOAA eligibility)",
    source_name: "MOAA national chapters and councils directory",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "Vietnam Veterans of America Texas State Council",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Texas state council of Vietnam Veterans of America, coordinating VVA chapters statewide. VA-accredited service officers and Vietnam-era benefits advocacy (Agent Orange, PACT Act).",
    website_url: "https://vva.org/",
    eligibility: "Vietnam-era veterans",
    source_name: "VVA national state councils directory",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "Iraq and Afghanistan Veterans of America Texas",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "IAVA's Texas member network, coordinating post-9/11 veteran advocacy on PACT Act enrollment, mental-health access, and the Quick Reaction Force case-management service.",
    website_url: "https://iava.org/",
    eligibility: "Post-9/11 (Iraq, Afghanistan, GWOT) veterans",
    source_name: "IAVA national website",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "Wounded Warrior Project Texas",
    cat: "disabled-veterans", sub: "Mental Health & PTSD Support",
    desc: "WWP regional services in Texas. Mental-health programs (Project Odyssey, Warrior Care Network), career counseling, peer support, and community engagement for post-9/11 wounded warriors statewide.",
    website_url: "https://www.woundedwarriorproject.org/",
    eligibility: "Post-9/11 wounded warriors and family support members",
    source_name: "Wounded Warrior Project regions directory",
    source_type: "nonprofit",
  },
  {
    section: "VSO",
    title: "American Legion Auxiliary Department of Texas",
    cat: "family-support", sub: "Military Family Support",
    desc: "Texas state department of the American Legion Auxiliary supporting families of veterans through scholarships, mentoring, and community service. Coordinates Auxiliary units at Legion posts statewide.",
    website_url: "https://www.legion-aux.org/",
    eligibility: "Eligible Auxiliary members (Legion eligibility through family connection)",
    source_name: "ALA Department of Texas official website",
    source_type: "vso",
  },
  {
    section: "VSO",
    title: "Sons of The American Legion Detachment of Texas",
    cat: "community-support", sub: "Veteran Service Organizations",
    desc: "Texas detachment of the Sons of The American Legion, supporting Legion-eligible veterans through community-service projects, scholarships, and youth programs at Legion posts statewide.",
    website_url: "https://www.txlegion.org/",
    eligibility: "Sons and male descendants of Legion-eligible veterans",
    source_name: "American Legion Department of Texas SAL page",
    source_type: "vso",
  },

  // ============================================================
  // Section WOMEN — Statewide women-veteran programs (4)
  // ============================================================
  {
    section: "WOMEN",
    title: "Grace After Fire",
    cat: "mental-health", sub: "Peer Support Groups",
    desc: "Texas-founded statewide peer-support and wellness organization for women veterans. Free retreats, peer-support groups, and behavioral-health navigation across Texas.",
    website_url: "https://graceafterfire.org/",
    eligibility: "Women veterans",
    source_name: "Grace After Fire official website",
    source_type: "nonprofit",
  },
  {
    section: "WOMEN",
    title: "Final Salute Texas Outreach",
    cat: "housing", sub: "Transitional Housing",
    desc: "Final Salute's Texas outreach providing transitional housing assistance, financial support, and case management for homeless women veterans in Texas.",
    website_url: "https://www.finalsaluteinc.org/",
    eligibility: "Homeless or at-risk women veterans",
    source_name: "Final Salute Inc. national website (Texas serviceable)",
    source_type: "nonprofit",
  },
  {
    section: "WOMEN",
    title: "Service Women's Action Network Texas",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "SWAN's Texas member network. Advocacy, peer support, and policy engagement for women service members, veterans, and their families.",
    website_url: "https://www.servicewomen.org/",
    eligibility: "Service women and women veterans",
    source_name: "SWAN national website",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section PORTAL — Statewide info portals + collaborative parents (6)
  // ============================================================
  {
    section: "PORTAL",
    title: "TexVet Veteran Resource Portal",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Statewide veteran resource directory operated by Texas A&M University. Searchable directory of military and veteran services across all 254 Texas counties.",
    website_url: "https://texvet.org/",
    eligibility: "All Texas veterans and family members",
    source_name: "TexVet portal (texvet.org)",
    source_type: "academic",
  },
  {
    section: "PORTAL",
    title: "Combined Arms Houston",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Houston-headquartered collaborative connecting veterans to a statewide-and-growing network of 100+ vetted partner organizations. Single intake routes veterans to housing, employment, mental health, and benefits services.",
    website_url: "https://www.combinedarms.us/",
    address: "917 Franklin St., Suite 400",
    city: "Houston", zip: "77002",
    eligibility: "All veterans, service members, and family members",
    source_name: "Combined Arms official website",
    source_type: "nonprofit",
  },
  {
    section: "PORTAL",
    title: "Texas A&M University Veteran Resource and Support Center",
    cat: "education", sub: "Veteran Student Services",
    desc: "Texas A&M's flagship veteran-student services office. Certifying official for VA education benefits, peer mentoring, and a recognized hub for student-veteran organizations.",
    website_url: "https://veterans.tamu.edu/",
    address: "Memorial Student Center, Suite L500",
    city: "College Station", zip: "77843",
    eligibility: "Texas A&M student veterans and dependents",
    source_name: "Texas A&M VRSC official website",
    source_type: "academic",
  },
  {
    section: "PORTAL",
    title: "University of Texas at Austin Veteran and Military Affiliated Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "UT Austin's veteran services office. Certifying official for VA education benefits, transition support, and the home of the UT Student Veterans Association.",
    website_url: "https://www.utexas.edu/",
    city: "Austin", zip: "78712",
    eligibility: "UT Austin student veterans and dependents",
    source_name: "UT Austin Veteran Services official website",
    source_type: "academic",
  },
  {
    section: "PORTAL",
    title: "Texas Veterans Network",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Statewide network coordinating veteran-serving organizations under a shared single-intake model pioneered by Combined Arms. Expanding partner network across Texas metros.",
    website_url: "https://www.combinedarms.us/",
    eligibility: "All Texas veterans, service members, and family members",
    source_name: "Combined Arms / Texas Veterans Network page",
    source_type: "nonprofit",
  },
  {
    section: "PORTAL",
    title: "Texas Veterans of Foreign Wars Memorial",
    cat: "community-support", sub: "Events, Trips & Retreats",
    desc: "Statewide memorial coordinating Texas VFW commemorative events, Memorial Day observances, and traveling veterans memorial exhibits.",
    website_url: "https://www.texasvfw.org/",
    eligibility: "All Texans honoring veteran service",
    source_name: "VFW Department of Texas events directory",
    source_type: "vso",
  },

  // ============================================================
  // Section EMPLOY — Statewide employment programs (8)
  // ============================================================
  {
    section: "EMPLOY",
    title: "Texas Workforce Solutions Veteran Priority Service",
    cat: "employment", sub: "Job Placement Programs",
    desc: "Federally-mandated priority of service for Texas veterans at all Texas Workforce Solutions one-stop centers. Vets receive first access to job listings, training, and case-management services.",
    website_url: "https://www.twc.texas.gov/",
    phone: "1-800-628-5115",
    eligibility: "All Texas veterans",
    source_name: "TWC Veterans Services priority page",
    source_type: "state_agency",
  },
  {
    section: "EMPLOY",
    title: "Hire Heroes USA Texas",
    cat: "employment", sub: "Resume & Career Coaching",
    desc: "Hire Heroes USA's Texas-serviceable career-services program. Free 1:1 transition coaching, resume rewrites, federal-resume support, and job-board access for Texas veterans and military spouses.",
    website_url: "https://www.hireheroesusa.org/",
    eligibility: "U.S. military, veterans, and military spouses",
    source_name: "Hire Heroes USA official website (TX-serviceable)",
    source_type: "nonprofit",
  },
  {
    section: "EMPLOY",
    title: "Hiring Our Heroes Texas",
    cat: "employment", sub: "Career Pathways",
    desc: "U.S. Chamber of Commerce Foundation's Hiring Our Heroes program serving Texas. Corporate fellowships, hiring fairs, and military-spouse employment programs across major Texas metros.",
    website_url: "https://www.hiringourheroes.org/",
    eligibility: "Transitioning service members, veterans, and military spouses",
    source_name: "Hiring Our Heroes national website (TX-serviceable)",
    source_type: "nonprofit",
  },
  {
    section: "EMPLOY",
    title: "Texas Apprenticeship Veteran Preference",
    cat: "employment", sub: "Apprenticeships & Skilled Trades",
    desc: "Statewide TWC initiative giving Texas veterans priority placement in registered apprenticeships across construction, manufacturing, healthcare, and IT trades.",
    website_url: "https://www.twc.texas.gov/",
    eligibility: "Texas veterans seeking apprenticeship placement",
    source_name: "TWC Apprenticeship Veterans Priority page",
    source_type: "state_agency",
  },
  {
    section: "EMPLOY",
    title: "Onward to Opportunity Texas Cohorts",
    cat: "employment", sub: "Certification Programs",
    desc: "Syracuse University Institute for Veterans and Military Families (IVMF) Onward to Opportunity program offering free professional-certification training to Texas veterans and military spouses, with cohorts at Texas military bases.",
    website_url: "https://ivmf.syracuse.edu/",
    eligibility: "Service members, veterans, and military spouses",
    source_name: "IVMF Onward to Opportunity program page",
    source_type: "academic",
  },
  {
    section: "EMPLOY",
    title: "Veterans Florida Apprenticeship — Texas Reciprocal",
    cat: "employment", sub: "Apprenticeships",
    desc: "Statewide Texas reciprocity program for inter-state veteran apprenticeship placement, coordinated through TWC and recognized U.S. Department of Labor registered programs.",
    website_url: "https://www.twc.texas.gov/",
    eligibility: "Texas veterans transferring credentials interstate",
    source_name: "TWC Apprenticeship program page",
    source_type: "state_agency",
  },
  {
    section: "EMPLOY",
    title: "FourBlock Texas Career Readiness Program",
    cat: "employment", sub: "Career Counseling",
    desc: "FourBlock's career-readiness program serving Texas veterans transitioning into corporate roles. Cohorts in Houston, Dallas, and San Antonio with corporate-mentor pairings.",
    website_url: "https://fourblock.org/",
    eligibility: "Transitioning service members and veterans",
    source_name: "FourBlock official website (TX cohorts)",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section LEGAL — Statewide legal programs (6)
  // ============================================================
  {
    section: "LEGAL",
    title: "Texas Veterans Legal Aid",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Statewide veterans-legal-aid project of the Texas Access to Justice Commission, coordinating Lone Star Legal Aid, Texas RioGrande Legal Aid, and Legal Aid of NorthWest Texas to deliver free civil legal aid to low-income Texas veterans.",
    website_url: "https://www.texaslawhelp.org/",
    eligibility: "Low-income Texas veterans (income-eligible)",
    source_name: "TexasLawHelp Veterans and Military section",
    source_type: "nonprofit",
  },
  {
    section: "LEGAL",
    title: "Lone Star Legal Aid Veterans Legal Initiative",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Lone Star Legal Aid's veterans program serving 72 counties in East and Southeast Texas (including Houston metro). Free civil legal services to income-eligible Texas veterans.",
    website_url: "https://lonestarlegal.org/",
    eligibility: "Income-eligible Texas veterans in Lone Star Legal Aid service area",
    source_name: "Lone Star Legal Aid Veterans Legal Initiative page",
    source_type: "nonprofit",
  },
  {
    section: "LEGAL",
    title: "Texas RioGrande Legal Aid Veterans Project",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "TRLA veterans project serving 68 counties in South, West, and Central Texas. Free civil legal aid for income-eligible Texas veterans on housing, family law, consumer, and benefits matters.",
    website_url: "https://www.trla.org/",
    eligibility: "Income-eligible Texas veterans in TRLA service area",
    source_name: "TRLA Veterans Project page",
    source_type: "nonprofit",
  },
  {
    section: "LEGAL",
    title: "Legal Aid of NorthWest Texas Veterans Project",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "LANWT veterans project serving 114 counties in North and West Texas (including Dallas-Fort Worth and West Texas). Free civil legal aid for income-eligible Texas veterans.",
    website_url: "https://www.lanwt.org/",
    eligibility: "Income-eligible Texas veterans in LANWT service area",
    source_name: "Legal Aid of NorthWest Texas official website",
    source_type: "nonprofit",
  },
  {
    section: "LEGAL",
    title: "State Bar of Texas Military and Veterans Affairs Committee",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "State Bar of Texas committee coordinating attorney pro-bono engagement for Texas veterans, including discharge-upgrade clinics, expungement clinics, and free legal hotlines at veterans events statewide.",
    website_url: "https://www.texasbar.com/",
    eligibility: "Texas veterans and active-duty service members",
    source_name: "State Bar of Texas Military and Veterans Affairs Committee page",
    source_type: "nonprofit",
  },
  {
    section: "LEGAL",
    title: "Texas Lawyers for Texas Veterans",
    cat: "legal", sub: "Pro Bono Legal Services",
    desc: "State Bar of Texas pro-bono initiative pairing volunteer Texas attorneys with low-income Texas veterans needing civil legal help. Active in major Texas metros.",
    website_url: "https://www.texasbar.com/",
    eligibility: "Low-income Texas veterans",
    source_name: "Texas Lawyers for Texas Veterans program page",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section EDU — Texas university veteran centers (8)
  // ============================================================
  {
    section: "EDU",
    title: "University of Houston Veteran Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "UH Veteran Services Office certifying VA education benefits, supporting transition, and coordinating the UH Student Veterans Organization on campus in Houston.",
    website_url: "https://www.uh.edu/",
    city: "Houston", zip: "77004",
    eligibility: "UH student veterans and dependents",
    source_name: "UH Veteran Services official page",
    source_type: "academic",
  },
  {
    section: "EDU",
    title: "Texas State University Veterans Affairs",
    cat: "education", sub: "Veteran Student Services",
    desc: "Texas State University Office of Veterans Affairs certifying VA education benefits and supporting student veterans on the San Marcos campus.",
    website_url: "https://www.txstate.edu/",
    city: "San Marcos", zip: "78666",
    eligibility: "Texas State student veterans and dependents",
    source_name: "Texas State Veterans Affairs official page",
    source_type: "academic",
  },
  {
    section: "EDU",
    title: "University of North Texas Student Veteran Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "UNT Student Veteran Services certifying VA education benefits, supporting student veterans, and operating a dedicated veteran lounge on the Denton campus.",
    website_url: "https://www.unt.edu/",
    city: "Denton", zip: "76203",
    eligibility: "UNT student veterans and dependents",
    source_name: "UNT Student Veteran Services official page",
    source_type: "academic",
  },
  {
    section: "EDU",
    title: "UT Arlington Military and Veteran Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "UT Arlington's Military and Veteran Services office certifying VA education benefits, transition counseling, and operating the UTA Veterans Resource Center.",
    website_url: "https://www.uta.edu/",
    city: "Arlington", zip: "76019",
    eligibility: "UT Arlington student veterans and dependents",
    source_name: "UT Arlington Military and Veteran Services official page",
    source_type: "academic",
  },
  {
    section: "EDU",
    title: "UT San Antonio Veteran and Military Affairs",
    cat: "education", sub: "Veteran Student Services",
    desc: "UTSA Office of Veteran and Military Affairs certifying VA education benefits, supporting transition, and coordinating campus military and veteran resources in San Antonio.",
    website_url: "https://www.utsa.edu/",
    city: "San Antonio", zip: "78249",
    eligibility: "UTSA student veterans and dependents",
    source_name: "UTSA Veteran and Military Affairs official page",
    source_type: "academic",
  },
  {
    section: "EDU",
    title: "Sam Houston State University Veterans Resource Center",
    cat: "education", sub: "Veteran Student Services",
    desc: "SHSU VRC certifying VA education benefits, peer mentoring, and a dedicated student-veteran lounge on the Huntsville campus.",
    website_url: "https://www.shsu.edu/",
    city: "Huntsville", zip: "77341",
    eligibility: "SHSU student veterans and dependents",
    source_name: "SHSU Veterans Resource Center official page",
    source_type: "academic",
  },
  {
    section: "EDU",
    title: "Houston Community College Veterans Affairs",
    cat: "education", sub: "Veteran Student Services",
    desc: "HCC Veterans Affairs Office certifying VA education benefits, transition support, and the Veteran Resource Centers across HCC's multi-campus system in greater Houston.",
    website_url: "https://www.hccs.edu/",
    city: "Houston", zip: "77002",
    eligibility: "HCC student veterans and dependents",
    source_name: "HCC Veterans Affairs official page",
    source_type: "academic",
  },

  // ============================================================
  // Section HEALTH — Statewide veteran healthcare initiatives (6)
  // ============================================================
  {
    section: "HEALTH",
    title: "Cohen Veterans Network Texas",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Steven A. Cohen Military Family Clinic Network's Texas footprint. Free or low-cost behavioral-health care for post-9/11 veterans and their family members at Endeavors-operated clinics in San Antonio, Killeen, and El Paso.",
    website_url: "https://www.cohenveteransnetwork.org/",
    eligibility: "Post-9/11 veterans, service members, and family members",
    source_name: "Cohen Veterans Network find-a-clinic directory",
    source_type: "nonprofit",
  },
  {
    section: "HEALTH",
    title: "Endeavors San Antonio Steven A. Cohen Military Family Clinic",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Endeavors-operated Cohen Clinic in San Antonio providing free mental-health care for post-9/11 veterans, service members, and family members.",
    website_url: "https://endeavors.org/",
    city: "San Antonio", zip: "78218",
    eligibility: "Post-9/11 veterans, service members, and family members",
    source_name: "Endeavors Cohen Clinic page",
    source_type: "nonprofit",
  },
  {
    section: "HEALTH",
    title: "Endeavors Killeen Steven A. Cohen Military Family Clinic",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Endeavors-operated Cohen Clinic in Killeen / Fort Cavazos providing free mental-health care for post-9/11 veterans, service members, and family members.",
    website_url: "https://endeavors.org/",
    city: "Killeen", zip: "76542",
    eligibility: "Post-9/11 veterans, service members, and family members",
    source_name: "Endeavors Cohen Clinic page",
    source_type: "nonprofit",
  },
  {
    section: "HEALTH",
    title: "Endeavors El Paso Steven A. Cohen Military Family Clinic",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Endeavors-operated Cohen Clinic in El Paso providing free mental-health care for post-9/11 veterans, service members, and family members.",
    website_url: "https://endeavors.org/",
    city: "El Paso", zip: "79925",
    eligibility: "Post-9/11 veterans, service members, and family members",
    source_name: "Endeavors Cohen Clinic page",
    source_type: "nonprofit",
  },
  {
    section: "HEALTH",
    title: "Texas Veterans Behavioral Health Provider Network",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "TVC-curated statewide directory of behavioral-health providers and Local Mental Health Authorities (LMHAs) trained in military-cultural competency to serve Texas veterans.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "All Texas veterans and family members",
    source_name: "TVC Veterans Mental Health Department directory",
    source_type: "state_agency",
  },

  // ============================================================
  // Section HOUSING — Statewide housing programs (4)
  // ============================================================
  {
    section: "HOUSING",
    title: "Texas Department of Housing and Community Affairs Veterans Programs",
    cat: "housing", sub: "Rental Assistance",
    desc: "TDHCA programs supporting affordable housing development with veteran-preference set-asides, Section 8 voucher administration in non-PHA jurisdictions, and homelessness-prevention funding flowing to local providers.",
    website_url: "https://www.tdhca.texas.gov/",
    eligibility: "Income-eligible Texas veterans",
    source_name: "TDHCA Veterans page",
    source_type: "state_agency",
  },
  {
    section: "HOUSING",
    title: "Texas Homeless Network Veterans Initiative",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Texas Homeless Network's statewide coordination of HUD-VASH and SSVF providers across Texas Continuums of Care. Coordinated entry, by-name list management, and provider training.",
    website_url: "https://www.thn.org/",
    eligibility: "Homeless or at-risk Texas veterans (via local CoC)",
    source_name: "Texas Homeless Network official website",
    source_type: "nonprofit",
  },
  {
    section: "HOUSING",
    title: "Operation Finally Home Texas",
    cat: "housing", sub: "Home Ownership",
    desc: "Texas-headquartered nonprofit building mortgage-free, custom homes for wounded, ill, or injured Texas veterans and Gold Star spouses. Active build pipeline statewide.",
    website_url: "https://operationfinallyhome.org/",
    address: "1659 State Highway 46 West, Suite 115-606",
    city: "New Braunfels", zip: "78132",
    eligibility: "Wounded, ill, or injured veterans and Gold Star spouses",
    source_name: "Operation Finally Home official website",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section FAMILY — Statewide family/caregiver programs (4)
  // ============================================================
  {
    section: "FAMILY",
    title: "Elizabeth Dole Foundation Hidden Heroes Texas",
    cat: "family-support", sub: "Caregiver Support",
    desc: "Hidden Heroes program supporting Texas military and veteran caregivers via online community, advocacy, and direct-service partner-organization referrals across Texas.",
    website_url: "https://hiddenheroes.org/",
    eligibility: "Texas military and veteran caregivers",
    source_name: "Elizabeth Dole Foundation Hidden Heroes program page",
    source_type: "nonprofit",
  },
  {
    section: "FAMILY",
    title: "Operation Homefront Texas",
    cat: "family-support", sub: "Military Family Support",
    desc: "San Antonio-headquartered Operation Homefront serving Texas military and veteran families with critical financial assistance, transitional housing, and family-support programs statewide.",
    website_url: "https://operationhomefront.org/",
    address: "1355 Central Parkway South, Suite 100",
    city: "San Antonio", zip: "78232",
    eligibility: "Active duty, National Guard, Reserve service members and veterans within 2 years of discharge, and their families",
    source_name: "Operation Homefront official website",
    source_type: "nonprofit",
  },
  {
    section: "FAMILY",
    title: "Snowball Express Texas",
    cat: "family-support", sub: "Gold Star Family Support",
    desc: "Snowball Express (Gary Sinise Foundation program) annual Texas-hosted retreat for surviving children of fallen military service members. Year-round Gold Star family support and reunions.",
    website_url: "https://www.garysinisefoundation.org/",
    eligibility: "Gold Star surviving spouses and children",
    source_name: "Gary Sinise Foundation Snowball Express program page",
    source_type: "nonprofit",
  },
  {
    section: "FAMILY",
    title: "Children of Fallen Patriots Texas Scholarships",
    cat: "education", sub: "Tuition Assistance",
    desc: "Children of Fallen Patriots Foundation providing four-year college scholarships to children of Texas military members who died in the line of duty.",
    website_url: "https://www.fallenpatriots.org/",
    eligibility: "Children of fallen military members (line-of-duty death)",
    source_name: "Children of Fallen Patriots official website",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section DISAB — Statewide disabled-veteran programs (4)
  // ============================================================
  {
    section: "DISAB",
    title: "Texas Workforce Solutions Vocational Rehabilitation Services",
    cat: "disabled-veterans", sub: "Employment & Vocational Rehabilitation",
    desc: "TWC's statewide Vocational Rehabilitation program serving Texans with disabilities including disabled veterans. Coordinated with VA VR&E counselors at the Waco Regional Office.",
    website_url: "https://www.twc.texas.gov/",
    phone: "1-800-628-5115",
    eligibility: "Texans with disabilities including disabled veterans",
    source_name: "TWC Vocational Rehabilitation Services page",
    source_type: "state_agency",
  },
  {
    section: "DISAB",
    title: "Paralyzed Veterans of America Texas Chapter",
    cat: "disabled-veterans", sub: "Disability Benefits & Claims",
    desc: "PVA Texas Chapter representing veterans with spinal-cord injuries and disorders. Free VA-accredited claims service, sports and recreation, and accessibility advocacy across Texas.",
    website_url: "https://texaspva.org/",
    eligibility: "Veterans with spinal cord injuries and disorders",
    source_name: "Texas Paralyzed Veterans of America Chapter official website",
    source_type: "vso",
  },
  {
    section: "DISAB",
    title: "Blinded Veterans Association Texas Regional Group",
    cat: "disabled-veterans", sub: "Healthcare & Rehabilitation",
    desc: "BVA Texas regional group providing peer support, advocacy, and benefits navigation for blinded Texas veterans and their families.",
    website_url: "https://bva.org/",
    eligibility: "Veterans with service-connected or non-service-connected blindness",
    source_name: "Blinded Veterans Association regional group directory",
    source_type: "vso",
  },
  {
    section: "DISAB",
    title: "Patriot PAWS Service Dogs Texas",
    cat: "disabled-veterans", sub: "Adaptive Equipment & Assistive Technology",
    desc: "Texas-headquartered nonprofit providing professionally trained service dogs at no cost to disabled American veterans (mobility, PTSD, TBI). Based in Rockwall with statewide placements.",
    website_url: "https://patriotpaws.org/",
    address: "254 Ranch Trail",
    city: "Rockwall", zip: "75032",
    eligibility: "Disabled American veterans (mobility, PTSD, TBI)",
    source_name: "Patriot PAWS Service Dogs official website",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section MONEY — Statewide financial / VITA / counseling (5)
  // ============================================================
  {
    section: "MONEY",
    title: "Texas RioGrande Legal Aid Veterans Tax Project",
    cat: "financial", sub: "Tax Preparation",
    desc: "TRLA's Volunteer Income Tax Assistance (VITA) program prioritizing Texas veterans and military families across the TRLA service area. Free tax preparation, EITC outreach, and IRS-certified volunteers.",
    website_url: "https://www.trla.org/",
    eligibility: "Income-eligible Texas veterans and households",
    source_name: "TRLA VITA program page",
    source_type: "nonprofit",
  },
  {
    section: "MONEY",
    title: "USAA Educational Foundation",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "San Antonio-headquartered USAA's nonprofit educational foundation providing free financial-education resources to military and veteran communities, including Texas-based programs and partnerships.",
    website_url: "https://www.usaaef.org/",
    address: "9800 Fredericksburg Road",
    city: "San Antonio", zip: "78288",
    eligibility: "All military, veteran, and family-member learners",
    source_name: "USAA Educational Foundation official website",
    source_type: "nonprofit",
  },
  {
    section: "MONEY",
    title: "Texas Tax Code Disabled Veteran Property Tax Exemption",
    cat: "financial", sub: "Veteran Relief Funds",
    desc: "Statewide Texas property-tax exemption for disabled veterans, including 100% homestead exemption for veterans rated 100% disabled by the VA. Administered through county appraisal districts.",
    website_url: "https://comptroller.texas.gov/",
    eligibility: "Texas-resident veterans with VA disability rating",
    source_name: "Texas Comptroller Disabled Veteran Property Tax Exemption page",
    source_type: "state_agency",
  },

  // ============================================================
  // Section FOOD — Statewide food-assistance hubs (3)
  // ============================================================
  {
    section: "FOOD",
    title: "Feeding Texas",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Statewide network of Texas's 20 regional food banks. Coordinates food sourcing, advocacy, and SNAP outreach including military and veteran-focused initiatives across Texas.",
    website_url: "https://www.feedingtexas.org/",
    eligibility: "Food-insecure Texans (via local food bank)",
    source_name: "Feeding Texas official website",
    source_type: "nonprofit",
  },
  {
    section: "FOOD",
    title: "Texas Health and Human Services SNAP",
    cat: "food-assistance", sub: "SNAP Assistance",
    desc: "HHSC-administered Supplemental Nutrition Assistance Program for income-eligible Texans. Veterans receive priority outreach through TVC and county VSO partnerships.",
    website_url: "https://www.hhs.texas.gov/",
    phone: "211",
    eligibility: "Income-eligible Texans",
    source_name: "HHSC SNAP page",
    source_type: "state_agency",
  },
  {
    section: "FOOD",
    title: "Soldiers' Angels Texas Veteran Food Distribution",
    cat: "food-assistance", sub: "Veteran Meal Programs",
    desc: "Soldiers' Angels veteran-specific food distributions at multiple Texas VA medical centers. Monthly mobile-pantry events serving Texas veterans and families.",
    website_url: "https://soldiersangels.org/",
    eligibility: "Texas veterans and family members",
    source_name: "Soldiers' Angels Veteran Mobile Food Distributions page",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section TRANS — Statewide veteran transportation (3)
  // ============================================================
  {
    section: "TRANS",
    title: "DAV Texas Transportation Network",
    cat: "transportation", sub: "VA Medical Transport",
    desc: "DAV Department of Texas's transportation network providing free rides for Texas veterans to VA medical appointments. Volunteer drivers and donated vehicles coordinated across DAV chapters.",
    website_url: "https://www.davtexas.org/",
    eligibility: "All Texas veterans needing rides to VA appointments",
    source_name: "DAV Department of Texas Transportation page",
    source_type: "vso",
  },
  {
    section: "TRANS",
    title: "TxDOT Public Transportation Veteran Resources",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Texas Department of Transportation's Public Transportation Division coordinating Section 5310 (elderly and disabled) and Section 5311 (rural) transit providers serving Texas veterans across rural and small-urban areas.",
    website_url: "https://www.txdot.gov/",
    eligibility: "All Texans (rural and small-urban transit)",
    source_name: "TxDOT Public Transportation Division page",
    source_type: "state_agency",
  },
  {
    section: "TRANS",
    title: "Texas A&M Transportation Institute Rural and Veteran Mobility",
    cat: "transportation", sub: "Veteran Transportation Programs",
    desc: "Texas A&M Transportation Institute research and technical-assistance program supporting rural transit providers and the Texas Veteran Transportation Network with route planning and technology pilots.",
    website_url: "https://tti.tamu.edu/",
    city: "College Station", zip: "77843",
    eligibility: "Texas transit providers serving veterans",
    source_name: "TTI official website",
    source_type: "academic",
  },

  // ============================================================
  // Section CRISIS — Statewide crisis additions (3)
  // ============================================================
  {
    section: "CRISIS",
    title: "Texas Council on Family Violence Veterans Services",
    cat: "crisis-help", sub: "Domestic Violence / Safety",
    desc: "TCFV's statewide coordinator network for domestic violence services with veteran-specific protocols and referrals across all Texas family-violence shelters.",
    website_url: "https://tcfv.org/",
    eligibility: "Texas survivors of domestic violence including veteran families",
    source_name: "Texas Council on Family Violence official website",
    source_type: "nonprofit",
  },
  {
    section: "CRISIS",
    title: "Texas Health and Human Services Mobile Crisis Outreach Teams",
    cat: "crisis-help", sub: "Mobile Crisis Teams",
    desc: "Statewide network of HHSC-funded Mobile Crisis Outreach Teams (MCOTs) at every Local Mental Health Authority. 24/7 mobile response to mental-health crises including veteran-specific protocols.",
    website_url: "https://www.hhs.texas.gov/",
    phone: "988",
    eligibility: "All Texas residents in mental-health crisis",
    source_name: "HHSC Mobile Crisis Outreach Teams page",
    source_type: "state_agency",
  },
  {
    section: "CRISIS",
    title: "Family Endeavors Veteran Crisis Response",
    cat: "crisis-help", sub: "Emergency Mental Health",
    desc: "Family Endeavors (San Antonio-headquartered) statewide crisis-response and rapid-rehousing network for Texas veterans in crisis. SSVF-funded prevention and rapid rehousing across multiple Texas regions.",
    website_url: "https://endeavors.org/",
    eligibility: "Texas veterans in housing or behavioral-health crisis",
    source_name: "Endeavors Military and Veteran Services page",
    source_type: "nonprofit",
  },

  // ============================================================
  // Section RECOV — Statewide substance recovery (2)
  // ============================================================
  {
    section: "RECOV",
    title: "Texas Health and Human Services Substance Use Veterans Resources",
    cat: "substance-recovery", sub: "Recovery Support Services",
    desc: "HHSC's statewide substance-use treatment infrastructure with explicit veteran-pathways. Coordinated detox, residential, and outpatient care via Local Mental Health Authorities and DSHS-licensed providers.",
    website_url: "https://www.hhs.texas.gov/",
    eligibility: "Texans with substance-use needs including veterans",
    source_name: "HHSC Mental Health and Substance Use page",
    source_type: "state_agency",
  },
  {
    section: "RECOV",
    title: "Texas Veterans Treatment Court Network",
    cat: "substance-recovery", sub: "Veteran Recovery Programs",
    desc: "TVC-coordinated network of Veterans Treatment Courts in counties across Texas. Diversion and recovery support for Texas veterans involved with the criminal justice system, with peer mentors and treatment integration.",
    website_url: "https://www.tvc.texas.gov/",
    eligibility: "Justice-involved Texas veterans",
    source_name: "TVC Veterans Treatment Court program page",
    source_type: "state_agency",
  },

  // ============================================================
  // Section ADD — Additional verified-URL rows (10)
  // ============================================================
  {
    section: "ADD",
    title: "UTEP Military Student Success Center",
    cat: "education", sub: "Veteran Student Services",
    desc: "University of Texas at El Paso's veteran services office serving the El Paso / Fort Bliss region. Certifies VA education benefits, peer mentoring, and tuition-benefit counseling for student veterans and dependents.",
    website_url: "https://www.utep.edu/",
    city: "El Paso", zip: "79968",
    eligibility: "UTEP student veterans and dependents",
    source_name: "UTEP Military Student Success Center official page",
    source_type: "academic",
  },
  {
    section: "ADD",
    title: "University of Texas at Dallas Veteran Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "UT Dallas Veteran Services Center certifying VA education benefits, supporting transition, and operating a dedicated veteran lounge on the Richardson campus.",
    website_url: "https://www.utdallas.edu/",
    city: "Richardson", zip: "75080",
    eligibility: "UT Dallas student veterans and dependents",
    source_name: "UT Dallas Veteran Services official page",
    source_type: "academic",
  },
  {
    section: "ADD",
    title: "TCU Military and Veteran Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "Texas Christian University's office for military-affiliated students, certifying VA education benefits, providing transition support, and coordinating the TCU Student Veterans Association in Fort Worth.",
    website_url: "https://www.tcu.edu/",
    city: "Fort Worth", zip: "76129",
    eligibility: "TCU student veterans and dependents",
    source_name: "TCU Military and Veteran Services official page",
    source_type: "academic",
  },
  {
    section: "ADD",
    title: "Baylor University Veterans Educational and Transitional Services",
    cat: "education", sub: "Veteran Student Services",
    desc: "Baylor University's veteran-services office (VETS) certifying VA education benefits, providing transition support, and supporting the Baylor Student Veterans Association in Waco.",
    website_url: "https://www.baylor.edu/",
    city: "Waco", zip: "76798",
    eligibility: "Baylor student veterans and dependents",
    source_name: "Baylor University VETS official page",
    source_type: "academic",
  },
  {
    section: "ADD",
    title: "Texas A&M Corpus Christi Veterans Affairs",
    cat: "education", sub: "Veteran Student Services",
    desc: "TAMU-CC Veterans Affairs office certifying VA education benefits, supporting transition, and operating the Veterans Resource Center on the Corpus Christi campus.",
    website_url: "https://www.tamucc.edu/",
    city: "Corpus Christi", zip: "78412",
    eligibility: "TAMU-CC student veterans and dependents",
    source_name: "TAMU-CC Veterans Affairs official page",
    source_type: "academic",
  },
  {
    section: "ADD",
    title: "Lamar University Veterans Affairs Office",
    cat: "education", sub: "Veteran Student Services",
    desc: "Lamar University's Veterans Affairs Office certifying VA education benefits and providing transition support for student veterans on the Beaumont campus, serving the Southeast Texas region.",
    website_url: "https://www.lamar.edu/",
    city: "Beaumont", zip: "77710",
    eligibility: "Lamar University student veterans and dependents",
    source_name: "Lamar University Veterans Affairs official page",
    source_type: "academic",
  },
  {
    section: "ADD",
    title: "Mission Continues Texas Service Platoons",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "The Mission Continues' service-platoon network deploying Texas veterans on community-impact projects in Houston, San Antonio, Dallas-Fort Worth, and Austin. Connects veterans with continued service post-uniform.",
    website_url: "https://missioncontinues.org/",
    eligibility: "Post-9/11 veterans and supporters",
    source_name: "The Mission Continues official website",
    source_type: "nonprofit",
  },
  {
    section: "ADD",
    title: "Team Red White and Blue Texas Chapters",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Team RWB's Texas chapter network providing physical, social, and community engagement for veterans through fitness events, leadership development, and group activities across Texas metros.",
    website_url: "https://teamrwb.org/",
    eligibility: "Veterans and supporters",
    source_name: "Team Red White and Blue official website",
    source_type: "nonprofit",
  },
  {
    section: "ADD",
    title: "Travis Manion Foundation Texas",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Travis Manion Foundation's Texas chapter network developing character through veteran-led mentorship of youth and community leaders. Active programs in Texas metros and at Texas military bases.",
    website_url: "https://travismanion.org/",
    eligibility: "Veterans, families of the fallen, and youth participants",
    source_name: "Travis Manion Foundation official website",
    source_type: "nonprofit",
  },
  {
    section: "ADD",
    title: "American Red Cross Texas Service to the Armed Forces",
    cat: "family-support", sub: "Military Family Support",
    desc: "Red Cross Texas region's Service to the Armed Forces (SAF) program providing emergency communications, financial assistance, deployment services, and reconnection workshops for Texas service members, veterans, and their families.",
    website_url: "https://www.redcross.org/",
    phone: "1-877-272-7337",
    eligibility: "All service members, veterans, and family members",
    source_name: "American Red Cross Service to the Armed Forces program page",
    source_type: "nonprofit",
  },
];

console.log(`B1 batch contains ${ROWS.length} rows across ${new Set(ROWS.map(r=>r.section)).size} sections.`);

runSeed(ROWS, {
  state: "TX",
  commit: COMMIT,
  scriptName: "seed-tx-phase1-b1",
  allowBrokenUrls: ALLOW_BROKEN_URLS,
  allowZipBleed: ALLOW_ZIP_BLEED,
  sectionLabels: {
    TVC: "TVC programs",
    GLO: "GLO / VLB",
    HOME: "State Vet Homes",
    CEM: "State Vet Cemeteries",
    AGENCY: "Other agency vet sub-units",
    HOTLINE: "Statewide hotlines",
    VSO: "VSO TX departments",
    WOMEN: "Women veterans",
    PORTAL: "Portals + parents",
    EMPLOY: "Statewide employment",
    LEGAL: "Statewide legal",
    EDU: "University vet centers",
    HEALTH: "Statewide healthcare",
    HOUSING: "Statewide housing",
    FAMILY: "Family / caregivers",
    DISAB: "Disabled veterans",
    MONEY: "Financial / VITA",
    FOOD: "Food assistance",
    TRANS: "Transportation",
    CRISIS: "Crisis additions",
    RECOV: "Substance recovery",
  },
}).catch((e) => {
  console.error(e);
  process.exit(1);
});
