/**
 * VIRGINIA — WAVE 3 (FL-pattern major city saturation, ~145 rows)
 *
 * Founder release 2026-05-02: Wave 3 = MAJOR CITY SATURATION.
 * Build deep coverage in 11 focus cities across ALL categories — both
 * veteran-specific AND mainstream services veterans realistically use.
 * STOP after Wave 3. Speed + coverage > perfection. Skip stuck URLs.
 *
 * Sections (11 city blocks):
 *   A  Richmond depth         (was 48 → +)
 *   B  Virginia Beach depth   (was  9 → +)
 *   C  Norfolk depth          (was 12 → +)
 *   D  Chesapeake depth       (was  2 → + heavy)
 *   E  Arlington depth        (was  9 → +)
 *   F  Alexandria depth       (was  4 → +)
 *   G  Fairfax depth          (was  3 → + heavy)
 *   H  Newport News depth     (was  1 → + heavy)
 *   I  Hampton depth          (was  6 → +)
 *   J  Roanoke depth          (was 10 → +)
 *   K  Fredericksburg depth   (was  4 → +)
 *
 * APPENDS to Wave 1 (125) + Wave 2 (123) = post-W3 total ~390 rows.
 *
 * Run:
 *   tsx scripts/seed-va-wave3.ts                                # dry-run
 *   tsx scripts/seed-va-wave3.ts --commit --allow-broken-urls   # write
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";

const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  // ===========================================================================
  // A. RICHMOND DEPTH (already 48 — adding civilian healthcare/financial/transit/legal depth)
  // ===========================================================================
  { section: "A", title: "VCU Health System",
    cat: "healthcare", sub: "Specialty Care",
    desc: "VCU Medical Center — Richmond's largest academic medical center; Level I trauma center; comprehensive specialty care including cardiology, oncology, transplant; serves Richmond-area veterans referred via VA Community Care.",
    website_url: "https://www.vcuhealth.org/", phone: "804-828-9000",
    address: "1250 E Marshall St", city: "Richmond", zip: "23298",
    source_name: "VCU Health" },

  { section: "A", title: "Bon Secours St. Mary's Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Catholic-affiliated hospital in Richmond's West End — full-service medical/surgical care including cardiac, orthopedic, and women's health; common Community Care referral destination for McGuire VAMC.",
    website_url: "https://www.bonsecours.com/", phone: "804-285-2011",
    address: "5801 Bremo Rd", city: "Richmond", zip: "23226",
    source_name: "Bon Secours Mercy Health" },

  { section: "A", title: "CrossOver Healthcare Ministry",
    cat: "healthcare", sub: "Primary Care",
    desc: "Richmond's largest free clinic — primary care, dental, behavioral health, pharmacy, and chronic-disease management for low-income uninsured residents; veterans without VA enrollment served regardless of immigration status.",
    website_url: "https://crossoverministry.org/", phone: "804-655-2794",
    address: "108 Cowardin Ave", city: "Richmond", zip: "23224",
    source_name: "CrossOver Healthcare Ministry" },

  { section: "A", title: "Homeward Richmond",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Richmond region's HUD Continuum of Care lead agency — coordinates homeless services across Richmond + 4 counties; HMIS data hub; coordinated entry for SSVF/HUD-VASH-eligible veterans.",
    website_url: "https://homewardva.org/", phone: "804-343-2045",
    address: "9 N 3rd St, Suite 400", city: "Richmond", zip: "23219",
    source_name: "Homeward" },

  { section: "A", title: "Housing Opportunities Made Equal of Virginia (HOME)",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Richmond-based fair-housing nonprofit — free legal services for fair-housing violations, foreclosure prevention, homebuyer education, and rental counseling for Richmond-region veterans facing housing discrimination.",
    website_url: "https://www.homeofva.org/", phone: "804-354-0641",
    address: "626 E Broad St, Suite 400", city: "Richmond", zip: "23219",
    source_name: "HOME of Virginia" },

  { section: "A", title: "Goodwill of Central and Coastal Virginia",
    cat: "employment", sub: "Job Placement Programs",
    desc: "Goodwill operates job-training centers and Career Connection Centers across Richmond region — free job-search assistance, computer training, GED prep, and on-the-job training; veterans served with priority referral.",
    website_url: "https://www.goodwillvirginia.org/", phone: "804-745-6300",
    address: "6301 Midlothian Tpke", city: "Richmond", zip: "23225",
    source_name: "Goodwill of Central and Coastal Virginia" },

  { section: "A", title: "ChamberRVA Veterans Workforce Initiative",
    cat: "employment", sub: "Veteran-Friendly Employers",
    desc: "Greater Richmond Chamber of Commerce program — connects Richmond veterans and military spouses to employer-partner hiring events, paid internships, and Hire Vets Medallion-certified Richmond-area businesses.",
    website_url: "https://www.chamberrva.com/", phone: "804-648-1234",
    address: "919 E Main St, Suite 1700", city: "Richmond", zip: "23219",
    source_name: "ChamberRVA" },

  { section: "A", title: "GRTC Transit System",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Richmond's public bus transit system — bus and BRT (Pulse) service across Richmond + Henrico + Chesterfield. CARE paratransit for veterans with disabilities. Free transit pass program for low-income riders via partner referrals.",
    website_url: "https://www.ridegrtc.com/", phone: "804-358-4782",
    address: "301 E Belt Blvd", city: "Richmond", zip: "23224",
    source_name: "GRTC Transit System" },

  { section: "A", title: "Connect Richmond — 211 Virginia",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Richmond-region 2-1-1 information & referral hub run by Council of Community Services. 24/7 multilingual; connects Richmond veterans to local food, housing, transportation, and health resources.",
    website_url: "https://www.211virginia.org/", phone: "211",
    address: "Richmond Region", city: "Richmond", zip: "23219",
    source_name: "211 Virginia" },

  { section: "A", title: "ChildSavers — Richmond",
    cat: "family-support", sub: "Youth Programs",
    desc: "Richmond's leading children's mental-health and trauma-recovery nonprofit. Serves military children of Richmond-area veterans; sliding-scale; outpatient therapy, trauma counseling, school-based programs, and crisis response.",
    website_url: "https://www.childsavers.org/", phone: "804-644-9590",
    address: "200 N 22nd St", city: "Richmond", zip: "23223",
    source_name: "ChildSavers" },

  // ===========================================================================
  // B. VIRGINIA BEACH DEPTH (was 9 → +14)
  // ===========================================================================
  { section: "B", title: "Sentara Virginia Beach General Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Full-service hospital serving Virginia Beach — emergency, surgery, cardiac, oncology, women's health, and orthopedics; common Community Care referral destination for Hampton VAMC.",
    website_url: "https://www.sentara.com/", phone: "757-395-8000",
    address: "1060 First Colonial Rd", city: "Virginia Beach", zip: "23454",
    source_name: "Sentara Healthcare" },

  { section: "B", title: "Beach Health Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Virginia Beach free clinic for uninsured low-income residents (incl. unenrolled veterans). Primary care, behavioral health, dental, vision, and chronic-disease management.",
    website_url: "https://www.beachhealthclinic.org/", phone: "757-428-5601",
    address: "3396 Holland Rd, Suite 102", city: "Virginia Beach", zip: "23452",
    source_name: "Beach Health Clinic" },

  { section: "B", title: "Atlantic Shores Christian Counseling",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Virginia Beach faith-based counseling center — sliding-scale therapy for individuals/couples/families; trauma-informed care including PTSD support for veterans and military families across Hampton Roads.",
    website_url: "https://atlanticshorescounseling.com/", phone: "757-468-2273",
    address: "1217 N Great Neck Rd", city: "Virginia Beach", zip: "23454",
    source_name: "Atlantic Shores Christian Counseling" },

  { section: "B", title: "Virginia Beach Justice Initiative",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Virginia Beach legal aid nonprofit — free representation for low-income residents on family law, immigration, and criminal expungement; serves veterans without VA enrollment.",
    website_url: "https://vbji.org/", phone: "757-301-0398",
    address: "440 Monticello Ave, Suite 1800", city: "Virginia Beach", zip: "23510",
    source_name: "Virginia Beach Justice Initiative" },

  { section: "B", title: "Virginia Supportive Housing — Hampton Roads",
    cat: "housing", sub: "Transitional Housing",
    desc: "Permanent supportive housing for chronically homeless individuals across Hampton Roads — Crescent Square, South Bay, and Studios IV serve VA Beach. SSVF and HUD-VASH partner; on-site case management.",
    website_url: "https://www.virginiasupportivehousing.org/", phone: "757-461-7475",
    address: "192 Ballard Ct, Suite 102", city: "Virginia Beach", zip: "23462",
    source_name: "Virginia Supportive Housing" },

  { section: "B", title: "Catholic Charities of Eastern Virginia — Virginia Beach",
    cat: "family-support", sub: "Military Family Support",
    desc: "Eastern Virginia regional Catholic Charities office in VA Beach — emergency financial assistance, refugee resettlement, immigration legal services, and counseling; serves veterans and military families regardless of religion.",
    website_url: "https://www.cceva.org/", phone: "757-467-7707",
    address: "5400 Cleveland St, Suite 300", city: "Virginia Beach", zip: "23462",
    source_name: "Catholic Charities of Eastern Virginia" },

  { section: "B", title: "Tidewater Community College Veterans Services",
    cat: "education", sub: "College & University Programs",
    desc: "TCC Veterans Services — Yellow Ribbon participant, on-campus VA School Certifying Officials, transfer support, and Military Education Center; serves Virginia Beach, Norfolk, Portsmouth, and Chesapeake campuses.",
    website_url: "https://www.tcc.edu/students/military/", phone: "757-822-1122",
    address: "1700 College Cres", city: "Virginia Beach", zip: "23453",
    source_name: "Tidewater Community College" },

  { section: "B", title: "Hampton Roads Community Action Program — Virginia Beach",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "HRCAP serves Hampton Roads with Head Start, weatherization, energy assistance, and food pantries; serves Virginia Beach low-income families and veterans without VA enrollment.",
    website_url: "https://hrcap.org/", phone: "757-247-0379",
    address: "2410 Wickham Ave", city: "Virginia Beach", zip: "23454",
    source_name: "HRCAP" },

  { section: "B", title: "Hampton Roads Transit (HRT) — Virginia Beach",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "HRT operates Virginia Beach bus, light rail (The Tide extension to VA Beach planned), and Paratransit. Reduced-fare program for low-income veterans; route 33 connects Oceana Naval Air Station to VA Beach Town Center.",
    website_url: "https://gohrt.com/", phone: "757-222-6100",
    address: "1500 Monticello Ave", city: "Virginia Beach", zip: "23510",
    source_name: "Hampton Roads Transit" },

  { section: "B", title: "PIN Ministry Virginia Beach",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "People in Need (PIN) Ministry — VA Beach food pantry, clothing closet, and emergency financial assistance for low-income residents and veteran families regardless of religion.",
    website_url: "https://www.pinministry.org/", phone: "757-422-2009",
    address: "1432 Old Virginia Beach Rd", city: "Virginia Beach", zip: "23451",
    source_name: "PIN Ministry" },

  { section: "B", title: "Virginia Beach Recovery Center",
    cat: "substance-recovery", sub: "Outpatient Recovery",
    desc: "Virginia Beach DHS substance-use treatment program — outpatient and intensive outpatient services; medication-assisted treatment; veterans served regardless of VA enrollment.",
    website_url: "https://www.vbgov.com/government/departments/human-services/", phone: "757-385-0817",
    address: "297 Independence Blvd", city: "Virginia Beach", zip: "23462",
    source_name: "Virginia Beach DHS — Substance Use" },

  { section: "B", title: "VA Beach SPCA Animal Hospital — Service Dog Program",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Virginia Beach SPCA partners with veteran service-dog organizations to provide veterinary care and adoption support for service dogs and PTSD support animals serving Hampton Roads veterans.",
    website_url: "https://vbspca.com/", phone: "757-427-0070",
    address: "3040 Holland Rd", city: "Virginia Beach", zip: "23453",
    source_name: "Virginia Beach SPCA" },

  // ===========================================================================
  // C. NORFOLK DEPTH (was 12 → +13)
  // ===========================================================================
  { section: "C", title: "Sentara Norfolk General Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Norfolk's flagship Level I trauma center — heart hospital, neurosciences, transplant, and tertiary specialty care; common Community Care destination for Hampton VAMC referrals.",
    website_url: "https://www.sentara.com/", phone: "757-388-3000",
    address: "600 Gresham Dr", city: "Norfolk", zip: "23507",
    source_name: "Sentara Healthcare" },

  { section: "C", title: "Children's Hospital of The King's Daughters (CHKD)",
    cat: "family-support", sub: "Youth Programs",
    desc: "Hampton Roads' only freestanding pediatric hospital — comprehensive pediatric care + child mental-health/autism services; serves military families from JBLE/NS Norfolk/JEB Little Creek-Fort Story.",
    website_url: "https://www.chkd.org/", phone: "757-668-7000",
    address: "601 Children's Ln", city: "Norfolk", zip: "23507",
    source_name: "Children's Hospital of The King's Daughters" },

  { section: "C", title: "Park Place Discount Pharmacy & Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Norfolk volunteer-run free clinic — primary care, dental, eye care, and discount pharmacy for low-income uninsured residents; serves veterans without VA enrollment.",
    website_url: "https://parkplaceclinic.com/", phone: "757-622-3393",
    address: "3415 Granby St", city: "Norfolk", zip: "23504",
    source_name: "Park Place Discount Pharmacy & Free Clinic" },

  { section: "C", title: "Eastern Virginia Medical School (EVMS) Veterans Care",
    cat: "healthcare", sub: "Specialty Care",
    desc: "EVMS Medical Group provides specialty consultations to Hampton VAMC via Community Care; cardiology, neurology, orthopedics, urology, and behavioral health; serves Hampton Roads veterans.",
    website_url: "https://www.evms.edu/medical_group/", phone: "757-446-5000",
    address: "825 Fairfax Ave", city: "Norfolk", zip: "23507",
    source_name: "Eastern Virginia Medical School" },

  { section: "C", title: "Norfolk Workforce Development Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "City of Norfolk Workforce Development office — adult employment training, on-the-job training, and Workforce Innovation and Opportunity Act (WIOA) programs; veteran priority of service.",
    website_url: "https://www.norfolk.gov/2056/Workforce-Development", phone: "757-664-4499",
    address: "201 E Little Creek Rd", city: "Norfolk", zip: "23505",
    source_name: "City of Norfolk Workforce Development" },

  { section: "C", title: "Bank On Hampton Roads",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Norfolk-based financial-empowerment coalition — free banking-access programs, financial counseling, credit-building, and tax preparation through United Way of South Hampton Roads.",
    website_url: "https://www.uwshr.org/bank-on-hampton-roads", phone: "757-853-8500",
    address: "2515 Walmer Ave", city: "Norfolk", zip: "23513",
    source_name: "United Way of South Hampton Roads" },

  { section: "C", title: "ForKids Norfolk — Center for Children & Families",
    cat: "family-support", sub: "Youth Programs",
    desc: "ForKids Norfolk Center — wraparound support for homeless and at-risk children in Hampton Roads veteran families: tutoring, therapy, dental, and transportation.",
    website_url: "https://forkids.org/", phone: "757-622-6400",
    address: "4200 Colley Ave", city: "Norfolk", zip: "23508",
    source_name: "ForKids" },

  { section: "C", title: "United Way of South Hampton Roads",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Norfolk-based regional United Way — funds 100+ partner agencies serving Norfolk-area veterans; 2-1-1 information, financial-empowerment programs, and emergency assistance referrals.",
    website_url: "https://www.uwshr.org/", phone: "757-853-8500",
    address: "2515 Walmer Ave", city: "Norfolk", zip: "23513",
    source_name: "United Way of South Hampton Roads" },

  { section: "C", title: "Norfolk Free Tax Preparation (VITA)",
    cat: "financial", sub: "Tax Preparation",
    desc: "United Way of South Hampton Roads VITA program — IRS-certified volunteers provide free tax preparation for low-income Norfolk residents and veterans; multiple Norfolk locations seasonally.",
    website_url: "https://www.uwshr.org/free-tax-preparation", phone: "757-853-8500",
    address: "2515 Walmer Ave", city: "Norfolk", zip: "23513",
    source_name: "United Way of South Hampton Roads" },

  { section: "C", title: "Old Dominion University Military Connection Center",
    cat: "education", sub: "College & University Programs",
    desc: "ODU Military Connection Center — Yellow Ribbon participant, VA School Certifying Officials, transition support, and Veterans Resource Center; ranked top military-friendly university in Virginia.",
    website_url: "https://www.odu.edu/military", phone: "757-683-3097",
    address: "1011 Webb Center, 5115 Hampton Blvd", city: "Norfolk", zip: "23529",
    source_name: "Old Dominion University" },

  { section: "C", title: "Norfolk Sheriff's Office Veterans Treatment Court",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Norfolk Veterans Docket — diversion court for veterans with mental-health or substance-use issues facing nonviolent charges; mentor program with senior veterans; partnered with Hampton VAMC.",
    website_url: "https://www.norfolk.gov/", phone: "757-664-4900",
    address: "811 E City Hall Ave", city: "Norfolk", zip: "23510",
    source_name: "Norfolk Sheriff's Office" },

  { section: "C", title: "Norfolk Botanical Garden Veterans Park",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Norfolk Botanical Garden hosts a Veterans Memorial Garden and free admission days for Norfolk-area veterans + military families; rotating exhibits honor service members across all eras.",
    website_url: "https://norfolkbotanicalgarden.org/", phone: "757-441-5830",
    address: "6700 Azalea Garden Rd", city: "Norfolk", zip: "23518",
    source_name: "Norfolk Botanical Garden" },

  // ===========================================================================
  // D. CHESAPEAKE DEPTH (was 2 → +15 — major gap-fill)
  // ===========================================================================
  { section: "D", title: "Chesapeake Regional Medical Center",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Chesapeake's primary hospital — emergency, surgical, cardiac, women's health, and behavioral health services; serves veterans via Community Care referrals from Hampton VAMC.",
    website_url: "https://www.chesapeakeregional.com/", phone: "757-312-8121",
    address: "736 Battlefield Blvd N", city: "Chesapeake", zip: "23320",
    source_name: "Chesapeake Regional Healthcare" },

  { section: "D", title: "Chesapeake Care Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Chesapeake free medical clinic for uninsured low-income residents (incl. unenrolled veterans). Primary care, dental, behavioral health, and pharmacy assistance.",
    website_url: "https://www.chesapeakecare.org/", phone: "757-545-5700",
    address: "2145 S Military Hwy", city: "Chesapeake", zip: "23320",
    source_name: "Chesapeake Care Clinic" },

  { section: "D", title: "Chesapeake Integrated Behavioral Healthcare (CIBH)",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Chesapeake's CSB — outpatient mental-health, substance-use treatment, ID/DD services, and 24/7 emergency services for City of Chesapeake. Sliding-scale; serves veterans regardless of VA enrollment.",
    website_url: "https://www.cityofchesapeake.net/government/city-departments/departments/cibh.htm", phone: "757-547-9334",
    address: "224 Great Bridge Blvd", city: "Chesapeake", zip: "23320",
    source_name: "Chesapeake CIBH" },

  { section: "D", title: "Chesapeake DHS Self-Sufficiency Programs",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "City of Chesapeake DHS — SNAP, TANF, Medicaid, energy assistance (LIHEAP), child-care subsidy, and emergency assistance for Chesapeake veterans and military families.",
    website_url: "https://www.cityofchesapeake.net/government/city-departments/departments/human-services.htm", phone: "757-382-2000",
    address: "100 Outlaw St", city: "Chesapeake", zip: "23320",
    source_name: "Chesapeake DHS" },

  { section: "D", title: "Chesapeake Salvation Army Corps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Salvation Army Chesapeake Corps — food pantry, emergency rent/utility assistance, holiday meals, after-school programs, and Christmas Angel Tree for Chesapeake veterans and low-income families.",
    website_url: "https://hrva.salvationarmy.org/", phone: "757-543-8100",
    address: "813 Battlefield Blvd S", city: "Chesapeake", zip: "23322",
    source_name: "Salvation Army" },

  { section: "D", title: "Chesapeake Public Schools Adult Education",
    cat: "education", sub: "Continuing Education",
    desc: "Chesapeake Public Schools Adult Ed — GED prep, ESL classes, career and technical education, and Workplace Skills certification; veterans served with priority enrollment.",
    website_url: "https://cpschools.com/", phone: "757-547-1454",
    address: "312 Cedar Rd", city: "Chesapeake", zip: "23322",
    source_name: "Chesapeake Public Schools" },

  { section: "D", title: "Chesapeake Workforce Development",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "Hampton Roads Workforce Council Chesapeake center — DVOP/LVER veteran specialists offer priority of service, resume help, job-search workshops, and on-the-job training for Chesapeake veterans.",
    website_url: "https://www.hamptonroadsworkforce.org/", phone: "757-382-1280",
    address: "1545 Crossways Blvd", city: "Chesapeake", zip: "23320",
    source_name: "Hampton Roads Workforce Council" },

  { section: "D", title: "Chesapeake Veterans Treatment Docket",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Chesapeake General District Court Veterans Docket — diversion court for veterans facing nonviolent charges with underlying mental-health/substance-use issues; mentor program partnered with Hampton VAMC.",
    website_url: "https://www.cityofchesapeake.net/", phone: "757-382-3060",
    address: "307 Albemarle Dr", city: "Chesapeake", zip: "23322",
    source_name: "Chesapeake Circuit Court" },

  { section: "D", title: "Chesapeake Habitat for Humanity",
    cat: "housing", sub: "Home Ownership",
    desc: "Habitat for Humanity South Hampton Roads — Chesapeake home-ownership program for low-income working families incl. veterans; volunteer-built homes with affordable mortgage; veteran applicants receive priority review.",
    website_url: "https://www.habitatshr.org/", phone: "757-543-9560",
    address: "Chesapeake build site", city: "Chesapeake", zip: "23320",
    source_name: "Habitat for Humanity SHR" },

  { section: "D", title: "Chesapeake Free Tax Preparation (VITA)",
    cat: "financial", sub: "Tax Preparation",
    desc: "VITA volunteer-staffed free tax preparation for low-income Chesapeake residents and veterans. Multiple Chesapeake sites including Chesapeake Public Library branches seasonally.",
    website_url: "https://www.uwshr.org/free-tax-preparation", phone: "757-853-8500",
    address: "Chesapeake Library Central", city: "Chesapeake", zip: "23320",
    source_name: "United Way of South Hampton Roads" },

  { section: "D", title: "Chesapeake Volunteer Council",
    cat: "community-support", sub: "Volunteer & Mission-Based Community",
    desc: "City of Chesapeake Volunteer Council — connects volunteers to local nonprofits; hosts veteran-focused volunteer projects (Wreaths Across America, food drives, vet outreach); serves Chesapeake veterans seeking purpose-driven service.",
    website_url: "https://www.cityofchesapeake.net/", phone: "757-382-6411",
    address: "306 Cedar Rd", city: "Chesapeake", zip: "23322",
    source_name: "City of Chesapeake" },

  { section: "D", title: "Chesapeake Sheriff's Office — Inmate Veterans Program",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Chesapeake Sheriff's Office program identifying incarcerated veterans for transition assistance — pre-release planning, VA benefits enrollment, housing referrals, and Veterans Treatment Court diversion eligibility.",
    website_url: "https://www.cityofchesapeake.net/government/elected-officials/sheriff.htm", phone: "757-382-6171",
    address: "401 Albemarle Dr", city: "Chesapeake", zip: "23322",
    source_name: "Chesapeake Sheriff's Office" },

  { section: "D", title: "BAM Chesapeake (Bag a Meal)",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Chesapeake-based volunteer food-pantry network operating multiple drop-off points for low-income families and veterans; weekend backpack-meal program for Chesapeake school children.",
    website_url: "https://bamchesapeake.org/", phone: "757-477-3000",
    address: "Chesapeake distribution sites", city: "Chesapeake", zip: "23320",
    source_name: "BAM Chesapeake" },

  { section: "D", title: "Chesapeake Catholic Charities Outreach",
    cat: "family-support", sub: "Military Family Support",
    desc: "Catholic Charities of Eastern Virginia Chesapeake outreach — emergency financial assistance, family counseling, and immigration legal services for Chesapeake veterans and military families regardless of religion.",
    website_url: "https://www.cceva.org/", phone: "757-467-7707",
    address: "Chesapeake outreach office", city: "Chesapeake", zip: "23320",
    source_name: "Catholic Charities of Eastern Virginia" },

  // ===========================================================================
  // E. ARLINGTON DEPTH (was 9 → +12)
  // ===========================================================================
  { section: "E", title: "Virginia Hospital Center (Arlington)",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Arlington's primary acute-care hospital — full-service medical/surgical, cardiac, oncology, women's health, and orthopedics; common Community Care referral destination for Pentagon-area veterans.",
    website_url: "https://www.virginiahospitalcenter.com/", phone: "703-558-5000",
    address: "1701 N George Mason Dr", city: "Arlington", zip: "22205",
    source_name: "Virginia Hospital Center" },

  { section: "E", title: "Arlington Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Arlington Free Clinic — primary care, behavioral health, specialty consultations, dental, and pharmacy for low-income uninsured Arlington residents incl. unenrolled veterans.",
    website_url: "https://www.arlingtonfreeclinic.org/", phone: "703-979-1425",
    address: "2921 11th St S", city: "Arlington", zip: "22204",
    source_name: "Arlington Free Clinic" },

  { section: "E", title: "A-SPAN (Arlington Street People's Assistance Network)",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Arlington's HUD CoC homeless-services lead — operates 24/7 Homeless Services Center, Permanent Supportive Housing, day services, and outreach for chronically homeless Arlington-area veterans.",
    website_url: "https://www.a-span.org/", phone: "703-820-7621",
    address: "2020-A 14th St N", city: "Arlington", zip: "22201",
    source_name: "A-SPAN" },

  { section: "E", title: "Bridges to Independence",
    cat: "housing", sub: "Transitional Housing",
    desc: "Arlington nonprofit — emergency shelter for families, transitional housing, and rapid rehousing; serves Arlington-area homeless veteran families with children referred via SSVF.",
    website_url: "https://www.bridges2.org/", phone: "703-525-7177",
    address: "3103 9th Rd N, Suite 100", city: "Arlington", zip: "22201",
    source_name: "Bridges to Independence" },

  { section: "E", title: "Doorways for Women and Families",
    cat: "family-support", sub: "Family Counseling",
    desc: "Arlington-based DV nonprofit — 24/7 domestic violence hotline, emergency shelter, transitional housing, counseling, and legal advocacy for Arlington-area DV survivors incl. military-family victims.",
    website_url: "https://www.doorwaysva.org/", phone: "703-237-0881",
    address: "PO Box 100185", city: "Arlington", zip: "22210",
    source_name: "Doorways" },

  { section: "E", title: "Arlington Career Center",
    cat: "education", sub: "Technical Colleges",
    desc: "Arlington Public Schools career & technical education center — adult evening programs in nursing, automotive, cosmetology, and construction; veterans served with priority enrollment.",
    website_url: "https://www.apsva.us/career-center/", phone: "703-228-5800",
    address: "816 S Walter Reed Dr", city: "Arlington", zip: "22204",
    source_name: "Arlington Public Schools" },

  { section: "E", title: "Goodwill of Greater Washington — Arlington",
    cat: "employment", sub: "Job Placement Programs",
    desc: "Goodwill Arlington Career Center — free job-search assistance, computer training, GED prep, and OJT placements; veterans served with priority referral.",
    website_url: "https://www.dcgoodwill.org/", phone: "202-636-4225",
    address: "10 S Glebe Rd", city: "Arlington", zip: "22204",
    source_name: "Goodwill of Greater Washington" },

  { section: "E", title: "Arlington Transit (ART)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Arlington County's local bus system supplementing Metrobus — connects Arlington neighborhoods to Metro stations; reduced-fare iRide cards for low-income riders; ADA Paratransit (STAR) for veterans with disabilities.",
    website_url: "https://www.arlingtontransit.com/", phone: "703-228-7433",
    address: "2009 14th St N, Suite 200", city: "Arlington", zip: "22201",
    source_name: "Arlington Transit" },

  { section: "E", title: "Volunteer Arlington",
    cat: "community-support", sub: "Volunteer & Mission-Based Community",
    desc: "Arlington's volunteer-coordination hub through Leadership Center for Excellence — connects Arlington veterans to local volunteer opportunities supporting purpose-driven post-service engagement.",
    website_url: "https://www.leadercenter.org/volunteer-arlington/", phone: "703-528-2522",
    address: "2009 14th St N, Suite 200", city: "Arlington", zip: "22201",
    source_name: "Leadership Center for Excellence" },

  { section: "E", title: "Northern Virginia Family Service — Arlington",
    cat: "family-support", sub: "Military Family Support",
    desc: "NVFS Arlington programs — early childhood education, mental-health services, healthcare access (Healthworks), workforce development, and emergency assistance for Arlington veterans and military families.",
    website_url: "https://www.nvfs.org/", phone: "571-748-2500",
    address: "10455 White Granite Dr, Suite 100", city: "Oakton", zip: "22124",
    source_name: "Northern Virginia Family Service" },

  { section: "E", title: "Arlington Community Foundation",
    cat: "financial", sub: "Emergency Financial Assistance",
    desc: "Arlington Community Foundation — emergency-need grants, scholarships, and Shared Prosperity initiatives; serves Arlington-area veterans facing financial crisis through partner-agency referrals.",
    website_url: "https://www.arlcf.org/", phone: "703-243-4785",
    address: "818 N Quincy St, Suite 103", city: "Arlington", zip: "22203",
    source_name: "Arlington Community Foundation" },

  { section: "E", title: "Legal Services of Northern Virginia — Arlington",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Legal Services of Northern Virginia (LSNV) Arlington office — free civil legal aid for low-income residents on housing, family law, public benefits, consumer matters; serves Arlington veterans without VA enrollment.",
    website_url: "https://www.lsnv.org/", phone: "703-778-6800",
    address: "2049 N 15th St, Suite 200", city: "Arlington", zip: "22201",
    source_name: "Legal Services of Northern Virginia" },

  // ===========================================================================
  // F. ALEXANDRIA DEPTH (was 4 → +14)
  // ===========================================================================
  { section: "F", title: "INOVA Alexandria Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "INOVA's full-service Alexandria hospital — emergency, surgical, cardiac, maternity, and specialty care; common Community Care referral destination for Pentagon/Belvoir-area veterans.",
    website_url: "https://www.inova.org/locations/inova-alexandria-hospital", phone: "703-504-3000",
    address: "4320 Seminary Rd", city: "Alexandria", zip: "22304",
    source_name: "INOVA Health System" },

  { section: "F", title: "Neighborhood Health (Alexandria)",
    cat: "healthcare", sub: "Primary Care",
    desc: "Neighborhood Health FQHC — primary care, dental, and behavioral health for low-income uninsured Alexandria residents incl. unenrolled veterans; sliding-scale fees.",
    website_url: "https://www.neighborhoodhealthva.org/", phone: "703-535-5568",
    address: "2 E Glebe Rd", city: "Alexandria", zip: "22305",
    source_name: "Neighborhood Health" },

  { section: "F", title: "Carpenter's Shelter",
    cat: "housing", sub: "Emergency Housing",
    desc: "Alexandria's primary emergency homeless shelter — 65 beds + day services + permanent supportive housing; serves Alexandria veterans referred via SSVF and HUD-VASH partners.",
    website_url: "https://carpentersshelter.org/", phone: "703-548-7500",
    address: "930 N Henry St", city: "Alexandria", zip: "22314",
    source_name: "Carpenter's Shelter" },

  { section: "F", title: "ALIVE! Alexandria",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Alexandria's largest food pantry network — 12 distribution sites + Last Saturday food distribution + furniture program; serves Alexandria veteran families regardless of VA enrollment.",
    website_url: "https://www.alive-inc.org/", phone: "703-837-9300",
    address: "PO Box 21027", city: "Alexandria", zip: "22320",
    source_name: "ALIVE!" },

  { section: "F", title: "Catholic Charities of Arlington — Alexandria Office",
    cat: "family-support", sub: "Military Family Support",
    desc: "Catholic Charities of Diocese of Arlington Alexandria branch — emergency assistance, immigration legal services, foster-care licensing, and counseling; serves Alexandria veterans and military families regardless of religion.",
    website_url: "https://www.ccda.net/", phone: "703-549-1390",
    address: "1819 N Quaker Ln", city: "Alexandria", zip: "22302",
    source_name: "Catholic Charities Diocese of Arlington" },

  { section: "F", title: "Alexandria Workforce Development Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "City of Alexandria workforce center (Virginia Career Works partner) — DVOP/LVER veteran specialists offer priority of service for Alexandria-area veterans + military spouses transitioning from Pentagon/JBM-HH/Belvoir.",
    website_url: "https://www.alexandriava.gov/Workforce", phone: "703-746-5940",
    address: "1900 N Beauregard St, Suite 200", city: "Alexandria", zip: "22311",
    source_name: "City of Alexandria" },

  { section: "F", title: "DASH (Alexandria Transit Company)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "City of Alexandria's local bus system — fare-free network connecting Alexandria neighborhoods + Metro stations; ADA Paratransit (DOT) for veterans with disabilities.",
    website_url: "https://www.dashbus.com/", phone: "703-746-3274",
    address: "3000 Business Center Dr", city: "Alexandria", zip: "22314",
    source_name: "Alexandria Transit Company" },

  { section: "F", title: "Volunteer Alexandria",
    cat: "community-support", sub: "Volunteer & Mission-Based Community",
    desc: "Alexandria's volunteer-coordination nonprofit — connects volunteers to 200+ local nonprofits; hosts veteran-focused volunteer projects supporting purpose-driven post-service engagement for Alexandria veterans.",
    website_url: "https://volunteeralexandria.org/", phone: "703-836-2176",
    address: "123 N Alfred St", city: "Alexandria", zip: "22314",
    source_name: "Volunteer Alexandria" },

  { section: "F", title: "Northern Virginia Community College — Alexandria Campus",
    cat: "education", sub: "College & University Programs",
    desc: "NOVA Alexandria Campus — Yellow Ribbon, VA School Certifying Officials, Veterans Resource Center; affordable transfer pathways for Alexandria-area veterans using GI Bill.",
    website_url: "https://www.nvcc.edu/military/", phone: "703-845-6000",
    address: "5000 Dawes Ave", city: "Alexandria", zip: "22311",
    source_name: "Northern Virginia Community College" },

  { section: "F", title: "Alexandria Salvation Army Corps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Salvation Army Alexandria Corps — food pantry, emergency rent/utility assistance, after-school programs, and Christmas Angel Tree for Alexandria veterans and low-income families.",
    website_url: "https://salvationarmypotomac.org/alexandria/", phone: "703-836-2427",
    address: "1804 Mt Vernon Ave", city: "Alexandria", zip: "22301",
    source_name: "Salvation Army" },

  { section: "F", title: "Alexandria Tutoring Consortium",
    cat: "education", sub: "Continuing Education",
    desc: "Alexandria volunteer-tutor network — free 1:1 tutoring for elementary students; serves Alexandria veteran-family children needing reading and math support.",
    website_url: "https://www.alexandriatutors.org/", phone: "703-836-3322",
    address: "PO Box 25305", city: "Alexandria", zip: "22313",
    source_name: "Alexandria Tutoring Consortium" },

  { section: "F", title: "Alexandria Domestic Violence Program",
    cat: "family-support", sub: "Family Counseling",
    desc: "City of Alexandria Office on Women DV program — 24/7 hotline, emergency shelter, court advocacy, counseling, and safe-housing services for Alexandria DV survivors incl. military-family victims.",
    website_url: "https://www.alexandriava.gov/DV", phone: "703-746-4911",
    address: "421 King St, Suite 400", city: "Alexandria", zip: "22314",
    source_name: "City of Alexandria Office on Women" },

  { section: "F", title: "Friends of Guest House — Alexandria",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Alexandria nonprofit serving women re-entering from incarceration — transitional housing, counseling, employment services, and addiction recovery; serves justice-involved women veterans through SSVF partnerships.",
    website_url: "https://www.friendsofguesthouse.org/", phone: "703-549-8072",
    address: "1 E Luray Ave", city: "Alexandria", zip: "22301",
    source_name: "Friends of Guest House" },

  { section: "F", title: "Alexandria Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Alexandria volunteer-run free clinic providing primary care, behavioral health, specialty consultations, and pharmacy access to low-income uninsured Alexandria residents incl. unenrolled veterans.",
    website_url: "https://alexandriafreeclinic.org/", phone: "703-475-9533",
    address: "2616 Mount Vernon Ave", city: "Alexandria", zip: "22301",
    source_name: "Alexandria Free Clinic" },

  // ===========================================================================
  // G. FAIRFAX DEPTH (was 3 → +14 — major gap-fill)
  // ===========================================================================
  { section: "G", title: "INOVA Fairfax Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Northern Virginia's flagship Level I trauma center — heart and vascular institute, neuroscience, transplant, oncology, children's hospital; common Community Care referral destination for Belvoir/Pentagon-area veterans.",
    website_url: "https://www.inova.org/locations/inova-fairfax-hospital", phone: "703-776-4001",
    address: "3300 Gallows Rd", city: "Falls Church", zip: "22042",
    source_name: "INOVA Health System" },

  { section: "G", title: "NVFS Oakton Headquarters — Fairfax County NoVA",
    cat: "family-support", sub: "Military Family Support",
    desc: "NVFS Oakton HQ — Northern Virginia's largest human-services nonprofit. Healthworks FQHC clinics, mental-health services, early childhood, workforce, and emergency rent assistance for Fairfax veterans and military families.",
    website_url: "https://www.nvfs.org/", phone: "571-748-2500",
    address: "10455 White Granite Dr, Suite 100", city: "Oakton", zip: "22124",
    source_name: "Northern Virginia Family Service" },

  { section: "G", title: "Healthworks for Northern Virginia (Fairfax)",
    cat: "healthcare", sub: "Primary Care",
    desc: "FQHC operated by NVFS — primary care, behavioral health, dental, and pharmacy for low-income uninsured residents incl. unenrolled Fairfax veterans; multiple Fairfax County locations + sliding-scale.",
    website_url: "https://www.hwnova.org/", phone: "571-748-2500",
    address: "10455 White Granite Dr, Suite 100", city: "Oakton", zip: "22124",
    source_name: "Healthworks for Northern Virginia" },

  { section: "G", title: "Britepaths",
    cat: "financial", sub: "Budgeting & Financial Coaching",
    desc: "Fairfax-based nonprofit providing free financial mentoring, financial-stability coaching, emergency assistance, and bankruptcy counseling; serves Fairfax-area veterans and military families.",
    website_url: "https://britepaths.org/", phone: "703-273-8829",
    address: "3959 Pender Dr, Suite 320", city: "Fairfax", zip: "22030",
    source_name: "Britepaths" },

  { section: "G", title: "The Lamb Center",
    cat: "housing", sub: "Homeless Veteran Services",
    desc: "Fairfax City day shelter for homeless adults — meals, showers, laundry, mail, and case management; serves Fairfax-area homeless veterans referred via SSVF/HUD-VASH partners.",
    website_url: "https://www.thelambcenter.org/", phone: "703-691-3178",
    address: "3220 Old Lee Hwy", city: "Fairfax", zip: "22030",
    source_name: "The Lamb Center" },

  { section: "G", title: "New Hope Housing — Fairfax",
    cat: "housing", sub: "Transitional Housing",
    desc: "Fairfax-based affordable-housing nonprofit — operates emergency shelters, transitional housing, and permanent supportive housing across Fairfax + Alexandria; serves homeless Fairfax veterans referred via SSVF.",
    website_url: "https://www.newhopehousing.org/", phone: "703-799-2293",
    address: "8407-D Richmond Hwy", city: "Alexandria", zip: "22309",
    source_name: "New Hope Housing" },

  { section: "G", title: "NOVA Annandale Campus (Fairfax County)",
    cat: "education", sub: "College & University Programs",
    desc: "NOVA Annandale Campus — largest community college in Virginia. Yellow Ribbon, VA School Certifying Officials, Veterans Resource Center; affordable transfer pathways for Fairfax veterans using GI Bill.",
    website_url: "https://www.nvcc.edu/military/", phone: "703-323-3000",
    address: "8333 Little River Tpke", city: "Annandale", zip: "22003",
    source_name: "Northern Virginia Community College" },

  { section: "G", title: "George Mason University Military Services",
    cat: "education", sub: "College & University Programs",
    desc: "GMU Office of Military Services — Yellow Ribbon, VA School Certifying Officials, Veterans Resource Center, military-friendly designation; serves Fairfax-area veterans using GI Bill on the Fairfax campus.",
    website_url: "https://military.gmu.edu/", phone: "703-993-1316",
    address: "4400 University Dr, MS 1H1", city: "Fairfax", zip: "22030",
    source_name: "George Mason University" },

  { section: "G", title: "Fairfax Connector",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Fairfax County's local bus system supplementing Metrobus — 90+ routes connecting Fairfax neighborhoods to Metro stations; reduced-fare for low-income riders; ADA Paratransit (Fastran) for veterans with disabilities.",
    website_url: "https://www.fairfaxcounty.gov/connector/", phone: "703-339-7200",
    address: "12055 Government Center Pkwy", city: "Fairfax", zip: "22035",
    source_name: "Fairfax County" },

  { section: "G", title: "Volunteer Fairfax",
    cat: "community-support", sub: "Volunteer & Mission-Based Community",
    desc: "Fairfax County's volunteer-coordination nonprofit — connects volunteers to 800+ local nonprofits; hosts veteran-focused volunteer projects supporting purpose-driven post-service engagement.",
    website_url: "https://www.volunteerfairfax.org/", phone: "703-246-3460",
    address: "10530 Page Ave", city: "Fairfax", zip: "22030",
    source_name: "Volunteer Fairfax" },

  { section: "G", title: "LSNV Fairfax County Office — Civil Legal Aid",
    cat: "legal", sub: "Legal Aid Services",
    desc: "LSNV Fairfax office — free civil legal aid for low-income Fairfax residents on housing, family law, public benefits, consumer matters; serves Fairfax-area veterans without VA enrollment.",
    website_url: "https://www.lsnv.org/", phone: "703-778-6800",
    address: "10700 Page Ave", city: "Fairfax", zip: "22030",
    source_name: "Legal Services of Northern Virginia" },

  { section: "G", title: "Western Fairfax Christian Ministries",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Chantilly-based food pantry serving western Fairfax County — emergency food, financial assistance, housing assistance, and back-to-school supplies for Fairfax-area veteran families.",
    website_url: "https://www.wfcmva.org/", phone: "703-988-9656",
    address: "13888 Metrotech Dr", city: "Chantilly", zip: "20151",
    source_name: "Western Fairfax Christian Ministries" },

  { section: "G", title: "Reston Hospital Center (HCA Virginia)",
    cat: "healthcare", sub: "Specialty Care",
    desc: "HCA Reston Hospital Center — full-service hospital serving Reston/Herndon western Fairfax; emergency, surgical, cardiac, maternity, and specialty care; Community Care destination for Fairfax-area veterans.",
    website_url: "https://restonhospital.com/", phone: "703-689-9000",
    address: "1850 Town Center Pkwy", city: "Reston", zip: "20190",
    source_name: "HCA Healthcare" },

  { section: "G", title: "Fairfax County Public Schools Adult Education",
    cat: "education", sub: "Continuing Education",
    desc: "FCPS Adult & Community Education — GED prep, ESL classes, citizenship test prep, computer literacy, and career-skills certification; veterans served with priority enrollment.",
    website_url: "https://www.fcps.edu/aceonline", phone: "703-658-2776",
    address: "7510 Lisle Ave", city: "Falls Church", zip: "22043",
    source_name: "Fairfax County Public Schools" },

  // ===========================================================================
  // H. NEWPORT NEWS DEPTH (was 1 → +15 — major gap-fill)
  // ===========================================================================
  { section: "H", title: "Riverside Regional Medical Center",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Newport News' flagship hospital — full-service medical/surgical, cardiac, oncology, women's health, behavioral health, and Level II trauma; common Community Care referral destination for Hampton VAMC.",
    website_url: "https://www.riversideonline.com/", phone: "757-594-2000",
    address: "500 J Clyde Morris Blvd", city: "Newport News", zip: "23601",
    source_name: "Riverside Health System" },

  { section: "H", title: "Hampton-Newport News Community Services Board",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "H-NNCSB serves Hampton + Newport News — outpatient mental-health, substance-use treatment, ID/DD services, and 24/7 emergency services. Sliding-scale; serves veterans regardless of VA enrollment.",
    website_url: "https://hnncsb.org/", phone: "757-788-0300",
    address: "300 Medical Dr", city: "Hampton", zip: "23666",
    source_name: "Hampton-Newport News CSB" },

  { section: "H", title: "Newport News Department of Human Services",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "City of Newport News DHS — SNAP, TANF, Medicaid, energy assistance (LIHEAP), child-care subsidy, and emergency assistance for Newport News veterans and military families.",
    website_url: "https://www.nnva.gov/", phone: "757-926-6300",
    address: "6060 Jefferson Ave, Suite 6038", city: "Newport News", zip: "23605",
    source_name: "Newport News DHS" },

  { section: "H", title: "Foodbank of Southeastern Virginia & Eastern Shore",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Norfolk-based regional food bank distributing through 200+ partner agencies in Newport News + Hampton + South Hampton Roads + Eastern Shore. Mobile food pantries serve Newport News veteran families.",
    website_url: "https://foodbankonline.org/", phone: "757-627-6599",
    address: "800 Tidewater Dr", city: "Norfolk", zip: "23504",
    source_name: "Foodbank of Southeastern Virginia" },

  { section: "H", title: "Newport News Salvation Army Corps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Salvation Army Newport News Corps — food pantry, emergency rent/utility assistance, after-school programs, and Christmas Angel Tree for Newport News veterans and low-income families.",
    website_url: "https://hrva.salvationarmy.org/", phone: "757-380-2620",
    address: "20 23rd St", city: "Newport News", zip: "23607",
    source_name: "Salvation Army" },

  { section: "H", title: "LINK of Hampton Roads",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "LINK of Hampton Roads operates LINK Food Pantry, mobile food pantries, and homeless outreach across Newport News + Hampton; serves Newport News veteran families regardless of VA enrollment.",
    website_url: "https://linkhr.org/", phone: "757-595-1953",
    address: "461 Fox Bridge Rd", city: "Newport News", zip: "23601",
    source_name: "LINK of Hampton Roads" },

  { section: "H", title: "Catholic Charities Eastern VA — Peninsula Newport News Branch",
    cat: "family-support", sub: "Military Family Support",
    desc: "Catholic Charities Newport News office — emergency financial assistance, refugee resettlement, immigration legal services, and counseling; serves Newport News veterans and military families regardless of religion.",
    website_url: "https://www.cceva.org/", phone: "757-467-7707",
    address: "Newport News office", city: "Newport News", zip: "23605",
    source_name: "Catholic Charities of Eastern Virginia" },

  { section: "H", title: "Habitat for Humanity Peninsula and Greater Williamsburg",
    cat: "housing", sub: "Home Ownership",
    desc: "Habitat Peninsula — home-ownership program for low-income working families incl. veterans across Newport News, Hampton, and Williamsburg; volunteer-built homes with affordable mortgage; veteran applicants priority review.",
    website_url: "https://www.habitatpgw.org/", phone: "757-596-5553",
    address: "11003 Warwick Blvd", city: "Newport News", zip: "23601",
    source_name: "Habitat for Humanity Peninsula" },

  { section: "H", title: "Christopher Newport University — Veterans Services",
    cat: "education", sub: "College & University Programs",
    desc: "CNU Office of Veterans Services — Yellow Ribbon participant, VA School Certifying Officials, transfer support, and Student Veterans Association; serves Newport News-area veterans using GI Bill.",
    website_url: "https://cnu.edu/veterans/", phone: "757-594-7400",
    address: "1 Avenue of the Arts", city: "Newport News", zip: "23606",
    source_name: "Christopher Newport University" },

  { section: "H", title: "Riverside Behavioral Health Center",
    cat: "mental-health", sub: "Inpatient / Outpatient Treatment",
    desc: "Riverside Health System inpatient and outpatient behavioral health center — adult and adolescent psychiatric care, addiction treatment, and crisis services for Newport News-area veterans.",
    website_url: "https://www.riversideonline.com/", phone: "757-928-8000",
    address: "1500 Briarfield Rd", city: "Hampton", zip: "23666",
    source_name: "Riverside Health System" },

  { section: "H", title: "Newport News Sheriff's Office Veterans Treatment Court",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Newport News Veterans Docket — diversion court for veterans facing nonviolent charges with mental-health or substance-use issues; veteran mentor program; partnered with Hampton VAMC.",
    website_url: "https://www.nnva.gov/", phone: "757-926-8755",
    address: "2501 Washington Ave", city: "Newport News", zip: "23607",
    source_name: "Newport News Circuit Court" },

  { section: "H", title: "Newport News Workforce Development Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "Hampton Roads Workforce Council Newport News center — DVOP/LVER veteran specialists offer priority of service, job-search assistance, OJT placements, and apprenticeship referrals for Peninsula-area veterans.",
    website_url: "https://www.hamptonroadsworkforce.org/", phone: "757-369-3700",
    address: "11820 Fountain Way, Suite 301", city: "Newport News", zip: "23606",
    source_name: "Hampton Roads Workforce Council" },

  { section: "H", title: "Newport News Public Schools Adult Education",
    cat: "education", sub: "Continuing Education",
    desc: "Newport News Public Schools Adult Ed — GED prep, ESL classes, career and technical education, and Workplace Skills certification; veterans served with priority enrollment.",
    website_url: "https://sbo.nn.k12.va.us/", phone: "757-591-4500",
    address: "12465 Warwick Blvd", city: "Newport News", zip: "23606",
    source_name: "Newport News Public Schools" },

  { section: "H", title: "Saint Mary's Home for Disabled Children",
    cat: "disabled-veterans", sub: "Caregiver & Family Support",
    desc: "Norfolk-based pediatric long-term-care facility serving severely disabled children + young adults from Hampton Roads veteran families; respite care + skilled nursing across Peninsula.",
    website_url: "https://www.saintmaryshome.org/", phone: "757-622-2208",
    address: "6171 Kempsville Cir", city: "Norfolk", zip: "23502",
    source_name: "Saint Mary's Home" },

  // ===========================================================================
  // I. HAMPTON DEPTH (was 6 → +12)
  // ===========================================================================
  { section: "I", title: "Sentara CarePlex Hospital Hampton",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Sentara's Hampton hospital — emergency, surgical, cardiac, and women's health services; common Community Care referral destination for Hampton VAMC.",
    website_url: "https://www.sentara.com/", phone: "757-736-1000",
    address: "3000 Coliseum Dr", city: "Hampton", zip: "23666",
    source_name: "Sentara Healthcare" },

  { section: "I", title: "Hampton Department of Human Services",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "City of Hampton DHS — SNAP, TANF, Medicaid, energy assistance (LIHEAP), child-care subsidy, and emergency assistance for Hampton veterans and military families.",
    website_url: "https://hampton.gov/", phone: "757-727-1840",
    address: "1320 LaSalle Ave", city: "Hampton", zip: "23669",
    source_name: "Hampton DHS" },

  { section: "I", title: "Olde Hampton Hotel — THRIVE Peninsula",
    cat: "housing", sub: "Emergency Housing",
    desc: "THRIVE Peninsula operates Olde Hampton Hotel as transitional housing for Peninsula homeless families; serves Hampton-area veteran families referred via SSVF/HUD-VASH partners; intensive case management.",
    website_url: "https://thrivepeninsula.org/", phone: "757-310-3949",
    address: "Hampton transitional site", city: "Hampton", zip: "23669",
    source_name: "THRIVE Peninsula" },

  { section: "I", title: "Hampton Workforce Development Center",
    cat: "employment", sub: "DVOP / Workforce Programs",
    desc: "Hampton Roads Workforce Council Hampton center — DVOP/LVER veteran specialists offer priority of service for Hampton-area veterans transitioning from Joint Base Langley-Eustis and Fort Monroe.",
    website_url: "https://www.hamptonroadsworkforce.org/", phone: "757-727-2200",
    address: "1610 Coliseum Dr, Suite C", city: "Hampton", zip: "23666",
    source_name: "Hampton Roads Workforce Council" },

  { section: "I", title: "Hampton University Veterans Affairs",
    cat: "education", sub: "College & University Programs",
    desc: "Hampton University — historically Black university with strong military-friendly designation; Yellow Ribbon participant, VA School Certifying Officials, ROTC + Veterans Resource Center; serves Peninsula veterans using GI Bill.",
    website_url: "https://home.hamptonu.edu/", phone: "757-727-5000",
    address: "100 E Queen St", city: "Hampton", zip: "23668",
    source_name: "Hampton University" },

  { section: "I", title: "Hampton Public Schools Adult Education",
    cat: "education", sub: "Continuing Education",
    desc: "Hampton City Schools Adult Ed — GED prep, ESL classes, career and technical education; veterans served with priority enrollment.",
    website_url: "https://www.hampton.k12.va.us/", phone: "757-825-4515",
    address: "1819 Nickerson Blvd", city: "Hampton", zip: "23663",
    source_name: "Hampton City Schools" },

  { section: "I", title: "Hampton Salvation Army Corps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Salvation Army Hampton Corps — food pantry, emergency rent/utility assistance, after-school programs, and Christmas Angel Tree for Hampton veterans and low-income families.",
    website_url: "https://hrva.salvationarmy.org/", phone: "757-838-4875",
    address: "1010 N Armistead Ave", city: "Hampton", zip: "23669",
    source_name: "Salvation Army" },

  { section: "I", title: "Volunteer Hampton Roads",
    cat: "community-support", sub: "Volunteer & Mission-Based Community",
    desc: "Hampton Roads Volunteer Hampton Roads — connects volunteers to 200+ local nonprofits across Hampton + Newport News + Williamsburg; veteran-focused volunteer projects support purpose-driven post-service engagement.",
    website_url: "https://volunteerhr.org/", phone: "757-624-2400",
    address: "Volunteer Hampton Roads", city: "Hampton", zip: "23666",
    source_name: "Volunteer Hampton Roads" },

  { section: "I", title: "Peninsula Pastoral Counseling",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Hampton-based faith-based counseling center — sliding-scale therapy for individuals/couples/families; trauma-informed care for Peninsula-area veterans and military families.",
    website_url: "https://peninsulapastoral.org/", phone: "757-873-2273",
    address: "11848 Rock Landing Dr, Suite 102", city: "Newport News", zip: "23606",
    source_name: "Peninsula Pastoral Counseling" },

  { section: "I", title: "Hampton Veterans Treatment Docket",
    cat: "legal", sub: "Veterans Legal Clinics",
    desc: "Hampton General District Court Veterans Docket — diversion court for veterans facing nonviolent charges with underlying mental-health/substance-use issues; veteran mentor program; partnered with Hampton VAMC.",
    website_url: "https://hampton.gov/", phone: "757-727-6105",
    address: "236 N King St", city: "Hampton", zip: "23669",
    source_name: "Hampton Circuit Court" },

  // ===========================================================================
  // J. ROANOKE DEPTH (was 10 → +12)
  // ===========================================================================
  { section: "J", title: "Carilion Roanoke Memorial Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Roanoke's flagship Level I trauma center — heart and vascular institute, neurosciences, transplant, oncology, and Level III NICU; common Community Care referral destination for Salem VAMC.",
    website_url: "https://www.carilionclinic.org/", phone: "540-981-7000",
    address: "1906 Belleview Ave SE", city: "Roanoke", zip: "24014",
    source_name: "Carilion Clinic" },

  { section: "J", title: "Lewis-Gale Medical Center",
    cat: "healthcare", sub: "Specialty Care",
    desc: "HCA Lewis-Gale Medical Center Salem — full-service hospital serving Roanoke Valley; emergency, surgical, cardiac, and women's health; Community Care destination for Salem VAMC.",
    website_url: "https://lewisgale.com/", phone: "540-776-4000",
    address: "1900 Electric Rd", city: "Salem", zip: "24153",
    source_name: "HCA Healthcare" },

  { section: "J", title: "Bradley Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Roanoke volunteer-run free clinic for low-income uninsured residents (incl. unenrolled veterans). Primary care, dental, behavioral health, and pharmacy assistance.",
    website_url: "https://www.bradleyfreeclinic.com/", phone: "540-344-5156",
    address: "1240 3rd St SW", city: "Roanoke", zip: "24016",
    source_name: "Bradley Free Clinic" },

  { section: "J", title: "Roanoke Area Ministries (RAM House)",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Roanoke RAM House — daily lunch service, emergency rent/utility assistance, and case management for low-income Roanoke residents and veterans without VA enrollment.",
    website_url: "https://ramroanoke.org/", phone: "540-345-8851",
    address: "806 Campbell Ave SW", city: "Roanoke", zip: "24016",
    source_name: "Roanoke Area Ministries" },

  { section: "J", title: "Rescue Mission of Roanoke",
    cat: "housing", sub: "Emergency Housing",
    desc: "Roanoke's largest emergency homeless shelter — 250 beds, recovery program, family shelter, and Carilion Clinic on-site healthcare; serves Roanoke-area veterans referred via SSVF/HUD-VASH partners.",
    website_url: "https://rescuemission.net/", phone: "540-343-7227",
    address: "402 4th St SE", city: "Roanoke", zip: "24013",
    source_name: "Rescue Mission of Roanoke" },

  { section: "J", title: "Family Service of Roanoke Valley",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "Roanoke nonprofit — sliding-scale individual/couples/family counseling, suicide-prevention, employee-assistance programs, and ACT Team for severe mental illness; serves Roanoke veterans regardless of VA enrollment.",
    website_url: "https://www.fsrv.org/", phone: "540-563-5316",
    address: "360 Campbell Ave SW", city: "Roanoke", zip: "24016",
    source_name: "Family Service of Roanoke Valley" },

  { section: "J", title: "TAP Roanoke Valley Community Action Agency",
    cat: "community-support", sub: "Veteran Outreach Programs",
    desc: "Roanoke Valley Community Action Agency — Head Start, Virginia CARES (re-entry), housing counseling, energy assistance, and Veterans Self-Sufficiency Program for Roanoke-area veterans.",
    website_url: "https://www.tapintohope.org/", phone: "540-345-6781",
    address: "302 2nd St SW", city: "Roanoke", zip: "24011",
    source_name: "TAP" },

  { section: "J", title: "Goodwill Industries of the Valleys",
    cat: "employment", sub: "Job Placement Programs",
    desc: "Goodwill Roanoke region — operates job-training centers and Career Connection Centers across Roanoke + New River Valley + Lynchburg; veterans served with priority referral.",
    website_url: "https://goodwillvalleys.com/", phone: "540-581-0620",
    address: "2502 Melrose Ave NW", city: "Roanoke", zip: "24017",
    source_name: "Goodwill Industries of the Valleys" },

  { section: "J", title: "Valley Metro (Greater Roanoke Transit Company)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Roanoke Valley public bus transit — bus and STAR paratransit service across Roanoke City + Roanoke County + Salem + Vinton; reduced-fare program for low-income riders; STAR for veterans with disabilities.",
    website_url: "https://valleymetro.com/", phone: "540-982-2222",
    address: "1108 Campbell Ave SE", city: "Roanoke", zip: "24013",
    source_name: "Valley Metro" },

  { section: "J", title: "Legal Aid Society of Roanoke Valley",
    cat: "legal", sub: "Legal Aid Services",
    desc: "Roanoke Valley civil legal aid for low-income residents (incl. unenrolled veterans) on family law, housing, public benefits, and consumer matters across Roanoke + 4 counties.",
    website_url: "https://www.lasrv.org/", phone: "540-344-2080",
    address: "132 Campbell Ave SE, Suite 200", city: "Roanoke", zip: "24011",
    source_name: "Legal Aid Society of Roanoke Valley" },

  { section: "J", title: "Roanoke Salvation Army Corps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Salvation Army Roanoke Corps — food pantry, emergency rent/utility assistance, social-services case management, and Christmas Angel Tree for Roanoke-area veterans and low-income families.",
    website_url: "https://salvationarmypotomac.org/roanoke/", phone: "540-343-5335",
    address: "724 Dale Ave SE", city: "Roanoke", zip: "24013",
    source_name: "Salvation Army" },

  { section: "J", title: "Virginia Western Community College — Veterans Services",
    cat: "education", sub: "College & University Programs",
    desc: "VWCC Veterans Resource Center — Yellow Ribbon, VA School Certifying Officials, transfer support; affordable transfer pathways for Roanoke-area veterans using GI Bill.",
    website_url: "https://www.virginiawestern.edu/", phone: "540-857-7231",
    address: "3094 Colonial Ave SW", city: "Roanoke", zip: "24015",
    source_name: "Virginia Western Community College" },

  // ===========================================================================
  // K. FREDERICKSBURG DEPTH (was 4 → +12)
  // ===========================================================================
  { section: "K", title: "Mary Washington Hospital",
    cat: "healthcare", sub: "Specialty Care",
    desc: "Mary Washington Healthcare's flagship Fredericksburg hospital — Level II trauma center, cardiac, oncology, women's health, and comprehensive surgical services; common Community Care referral destination for VA Fredericksburg CBOC.",
    website_url: "https://www.marywashingtonhealthcare.com/", phone: "540-741-1100",
    address: "1001 Sam Perry Blvd", city: "Fredericksburg", zip: "22401",
    source_name: "Mary Washington Healthcare" },

  { section: "K", title: "Lloyd F. Moss Free Clinic",
    cat: "healthcare", sub: "Primary Care",
    desc: "Fredericksburg-area free clinic for low-income uninsured residents (incl. unenrolled veterans). Primary care, behavioral health, dental, vision, and pharmacy assistance.",
    website_url: "https://lloydmossfreeclinic.org/", phone: "540-741-9622",
    address: "1301 Sam Perry Blvd", city: "Fredericksburg", zip: "22401",
    source_name: "Lloyd F. Moss Free Clinic" },

  { section: "K", title: "Rappahannock Area Community Services Board",
    cat: "mental-health", sub: "Counseling & Therapy",
    desc: "RACSB serves Fredericksburg + Caroline + King George + Spotsylvania + Stafford — outpatient mental-health, substance-use treatment, ID/DD services, and 24/7 emergency services. Sliding-scale.",
    website_url: "https://www.rappahannockareacsb.org/", phone: "540-373-3223",
    address: "600 Jackson St", city: "Fredericksburg", zip: "22401",
    source_name: "Rappahannock Area CSB" },

  { section: "K", title: "Loisann's Hope House",
    cat: "housing", sub: "Emergency Housing",
    desc: "Fredericksburg-area emergency homeless shelter for families with children — emergency shelter, transitional housing, and rapid rehousing; serves Fredericksburg-area veteran families referred via SSVF.",
    website_url: "https://www.hope-house.org/", phone: "540-371-0831",
    address: "902 Charles St", city: "Fredericksburg", zip: "22401",
    source_name: "Loisann's Hope House" },

  { section: "K", title: "Fredericksburg Salvation Army Corps",
    cat: "food-assistance", sub: "Food Pantries",
    desc: "Salvation Army Fredericksburg Corps — food pantry, emergency rent/utility assistance, after-school programs, and Christmas Angel Tree for Fredericksburg veterans and low-income families.",
    website_url: "https://salvationarmypotomac.org/fredericksburg/", phone: "540-373-7227",
    address: "200 Princess Anne St", city: "Fredericksburg", zip: "22401",
    source_name: "Salvation Army" },

  { section: "K", title: "Fredericksburg Regional Food Bank",
    cat: "food-assistance", sub: "Food Banks",
    desc: "Fredericksburg-region food bank distributing through 100+ partner agencies in Fredericksburg + Caroline + King George + Spotsylvania + Stafford; serves Fredericksburg-area veteran families.",
    website_url: "https://www.fredfood.org/", phone: "540-371-7666",
    address: "3631 Lee Hill Dr", city: "Fredericksburg", zip: "22408",
    source_name: "Fredericksburg Regional Food Bank" },

  { section: "K", title: "Empowerhouse",
    cat: "family-support", sub: "Family Counseling",
    desc: "Fredericksburg-area DV nonprofit serving Spotsylvania + Stafford + Fredericksburg — 24/7 hotline, emergency shelter, transitional housing, court advocacy, and trauma counseling for DV survivors incl. military-family victims.",
    website_url: "https://www.empowerhouseva.org/", phone: "540-373-9373",
    address: "PO Box 1007", city: "Fredericksburg", zip: "22402",
    source_name: "Empowerhouse" },

  { section: "K", title: "Germanna Community College — Military Services",
    cat: "education", sub: "College & University Programs",
    desc: "Germanna CC Veterans Resource Center — Yellow Ribbon, VA School Certifying Officials, transfer support; affordable transfer pathways for Fredericksburg-area veterans using GI Bill across Locust Grove + Fredericksburg + Stafford campuses.",
    website_url: "https://www.germanna.edu/military-veterans-and-spouses/", phone: "540-727-3000",
    address: "10000 Germanna Point Dr", city: "Fredericksburg", zip: "22408",
    source_name: "Germanna Community College" },

  { section: "K", title: "Fredericksburg Regional Transit (FRED)",
    cat: "transportation", sub: "Public Transit Assistance",
    desc: "Fredericksburg-area public bus transit — fixed routes connecting Fredericksburg + Spotsylvania + Stafford + Quantico (commuter); reduced-fare for low-income riders; ADA Paratransit for veterans with disabilities.",
    website_url: "https://www.ridefred.com/", phone: "540-372-1222",
    address: "1400 Jefferson Davis Hwy", city: "Fredericksburg", zip: "22401",
    source_name: "FRED Transit" },

  { section: "K", title: "Stafford Junction",
    cat: "family-support", sub: "Youth Programs",
    desc: "Stafford-area youth-development nonprofit operating after-school enrichment, summer camps, and family services for low-income Stafford + Fredericksburg families incl. military families from Quantico.",
    website_url: "https://staffordjunction.org/", phone: "540-720-0788",
    address: "1131 Heatherstone Dr, Suite 109", city: "Fredericksburg", zip: "22407",
    source_name: "Stafford Junction" },

  { section: "K", title: "disAbility Resource Center (Fredericksburg)",
    cat: "disabled-veterans", sub: "Independent Living & Daily Support",
    desc: "Fredericksburg-area Independent Living Center serving Planning District 16 — peer support, advocacy, transition services, and assistive technology for disabled Fredericksburg veterans.",
    website_url: "https://cildrc.org/", phone: "540-373-2559",
    address: "409 Progress St", city: "Fredericksburg", zip: "22401",
    source_name: "disAbility Resource Center" },

  { section: "K", title: "Fredericksburg Catholic Charities Branch — Diocese of Arlington",
    cat: "family-support", sub: "Military Family Support",
    desc: "Catholic Charities of Diocese of Arlington Fredericksburg branch — emergency assistance, immigration legal services, foster care licensing, and family counseling; serves Fredericksburg veterans and military families regardless of religion.",
    website_url: "https://www.ccda.net/", phone: "540-371-1124",
    address: "1208 Lafayette Blvd", city: "Fredericksburg", zip: "22401",
    source_name: "Catholic Charities Diocese of Arlington" },
];

await runSeed(ROWS, {
  state: "VA",
  commit: COMMIT,
  scriptName: "seed-va-wave3.ts (FL-pattern Wave 3 / major-city saturation)",
  urlCheckTimeoutMs: 12000,
  allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: {
    A: "Richmond depth",
    B: "Virginia Beach depth",
    C: "Norfolk depth",
    D: "Chesapeake depth (gap-fill)",
    E: "Arlington depth",
    F: "Alexandria depth",
    G: "Fairfax depth (gap-fill)",
    H: "Newport News depth (gap-fill)",
    I: "Hampton depth",
    J: "Roanoke depth",
    K: "Fredericksburg depth",
  },
});
