/**
 * OHIO — PHASE 1: STATE FOUNDATION
 * Statewide backbone per locked national 6-phase SOP. ~45 anchor rows:
 *   - Ohio state veteran agencies + state veterans homes
 *   - VA Cleveland Regional Office + 5 OH VA Medical Centers (anchors only; CBOC depth in Phase 2)
 *   - Chartered statewide VSOs (Legion / VFW / DAV / AMVETS / MCL / VVA Ohio departments)
 *   - State agencies veterans need (ODJFS, OhioMHAS, ODH, Aging, Insurance/OSHIIP, OHFA)
 *   - Statewide nonprofit anchors (Ohio Assoc of Foodbanks, COHHIO, ODVN, OAESV, Suicide Prev)
 *   - Statewide hotlines + statewide community anchors (Salvation Army, Goodwill, Red Cross, United Way)
 */
import { runSeed, type SeedRow } from "./lib/rollout-engine";
const COMMIT = process.argv.includes("--commit");
const ALLOW_BROKEN_URLS = process.argv.includes("--allow-broken-urls");

const ROWS: SeedRow[] = [
  // ---- A. OHIO STATE VETERAN AGENCIES (8) ----
  { section: "STATE", title: "Ohio Department of Veterans Services", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://dvs.ohio.gov/", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "614-644-0898", address: "77 S High St 7th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Veterans Services (ODVS) — cabinet-level state agency serving Ohio's 800,000+ veterans. Operates the Ohio Veterans Bonus, runs the Ohio Veterans Home in Sandusky and Georgetown, supervises County Veterans Service Commissions in all 88 counties, and coordinates Ohio National Guard Family Programs and statewide veteran outreach." },
  { section: "STATE", title: "Ohio Veterans Home — Sandusky", cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes", city: "Sandusky", website_url: "https://dvs.ohio.gov/wps/portal/gov/dvs/services/ovh-sandusky", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "419-625-2454", address: "3416 Columbus Ave, Sandusky, OH 44870", zip: "44870", desc: "Ohio Veterans Home Sandusky — state-operated long-term care, skilled nursing, and domiciliary care facility for honorably-discharged Ohio veterans. 700+ beds; nursing care, dementia care, hospice, and domiciliary residence; eligibility: wartime service + 1 year Ohio residency; sliding maintenance fee based on income." },
  { section: "STATE", title: "Ohio Veterans Home — Georgetown", cat: "end-of-life-services", sub: "Assisted Living & Nursing Homes", city: "Georgetown", website_url: "https://dvs.ohio.gov/wps/portal/gov/dvs/services/ovh-georgetown", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "937-378-2900", address: "2003 Veterans Blvd, Georgetown, OH 45121", zip: "45121", desc: "Ohio Veterans Home Georgetown — state-operated 168-bed skilled nursing facility for honorably-discharged Ohio veterans, located on a 220-acre campus in Brown County. Nursing care, dementia care, hospice; eligibility: wartime service + 1 year Ohio residency; sliding maintenance fee based on income." },
  { section: "STATE", title: "Ohio Veterans Bonus Program", cat: "financial", sub: "Veteran Relief Funds", city: "Columbus", website_url: "https://dvs.ohio.gov/wps/portal/gov/dvs/main-areas-of-interest/ohio-veterans-bonus", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "877-644-6838", address: "77 S High St 7th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Veterans Bonus — state-funded compensation for Ohio veterans who served in Persian Gulf, Afghanistan, or Iraq theaters. Up to $1,500 (combat) or $1,000 (non-combat); surviving-spouse eligibility for service-connected deaths up to $5,000. Apply via ODVS or local County Veterans Service Commission." },
  { section: "STATE", title: "Ohio National Guard — Family Readiness Program", cat: "family-support", sub: "Military Family Support", city: "Columbus", website_url: "https://ong.ohio.gov/about-us/family-programs/", source_name: "Ohio National Guard", source_type: "state_agency", phone: "614-336-7000", address: "2825 W Dublin Granville Rd, Columbus, OH 43235", zip: "43235", desc: "Ohio National Guard Family Programs office — supports the families of OHARNG and OHANG service members through Family Readiness Groups, deployment-cycle support, Yellow Ribbon Reintegration, Family Assistance Centers (FACs) statewide, child & youth programs, and Survivor Outreach Services." },
  { section: "STATE", title: "Ohio Adjutant General's Department", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://ong.ohio.gov/", source_name: "Ohio Adjutant General's Department", source_type: "state_agency", phone: "614-336-7000", address: "2825 W Dublin Granville Rd, Columbus, OH 43235", zip: "43235", desc: "Ohio Adjutant General's Department — state agency commanding the Ohio Army National Guard (16,000+ Soldiers), Ohio Air National Guard (5,000+ Airmen), Ohio Military Reserve, and Ohio Naval Militia. Coordinates state-active-duty deployments, federal Title 10 mobilizations, family support, and the Ohio Hall of Fame for Distinguished Citizen Soldiers." },
  { section: "STATE", title: "Ohio War Orphans & Severely Disabled Veterans' Children Scholarship", cat: "education", sub: "Tuition Assistance", city: "Columbus", website_url: "https://www.ohiohighered.org/sgs/war-orphans", source_name: "Ohio Department of Higher Education", source_type: "state_agency", phone: "614-466-7420", address: "25 S Front St, Columbus, OH 43215", zip: "43215", desc: "Ohio War Orphans & Severely Disabled Veterans' Children Scholarship — state need-based scholarship covering tuition (up to 100%) at Ohio public universities/colleges for the children of Ohio veterans who died on active duty (1940-present) or are 60%+ service-connected disabled. Apply via Ohio Department of Higher Education." },
  { section: "STATE", title: "Ohio National Guard Scholarship Program (ONGSP)", cat: "education", sub: "Tuition Assistance", city: "Columbus", website_url: "https://ong.ohio.gov/our-units/special-staff/education/scholarships", source_name: "Ohio National Guard", source_type: "state_agency", phone: "888-400-6484", address: "2825 W Dublin Granville Rd, Columbus, OH 43235", zip: "43235", desc: "Ohio National Guard Scholarship Program — state-funded scholarship covering up to 100% of tuition and most fees at Ohio public colleges/universities (or proportional amount at Ohio private schools) for actively-serving OHARNG and OHANG members. Service obligation required; covers undergraduate and graduate study." },

  // ---- B. VA ANCHORS (Phase 1 statewide presence; CBOC depth in Phase 2) (6) ----
  { section: "VA", title: "VA Cleveland Regional Office (VBA)", cat: "va-benefits", sub: "VA Regional Offices", city: "Cleveland", website_url: "https://www.benefits.va.gov/cleveland/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "800-827-1000", address: "1240 E 9th St, Cleveland, OH 44199", zip: "44199", desc: "VA Cleveland Regional Office — Veterans Benefits Administration regional office serving all 88 Ohio counties. Processes compensation, pension, education (GI Bill), VA home loans, vocational rehab (VR&E), and survivor (DIC) claims. In-person walk-in service Mon-Fri; partners with all 88 Ohio County Veterans Service Commissions for claim filings." },
  { section: "VA", title: "Louis Stokes Cleveland VA Medical Center", cat: "healthcare", sub: "VA Medical Centers", city: "Cleveland", website_url: "https://www.va.gov/cleveland-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "216-791-3800", address: "10701 East Blvd, Cleveland, OH 44106", zip: "44106", desc: "Louis Stokes Cleveland VA Medical Center (VA Northeast Ohio Healthcare System flagship) — Level 1a tertiary-care hospital serving 112,000+ veterans across 24 NE Ohio counties. Full inpatient, emergency, surgery, mental health, SCI Center, polytrauma rehab, hemodialysis, hospice/palliative, and 13 community-based outpatient clinics (CBOCs)." },
  { section: "VA", title: "Cincinnati VA Medical Center", cat: "healthcare", sub: "VA Medical Centers", city: "Cincinnati", website_url: "https://www.va.gov/cincinnati-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "513-861-3100", address: "3200 Vine St, Cincinnati, OH 45220", zip: "45220", desc: "Cincinnati VA Medical Center — tertiary-care VA hospital serving 45,000+ veterans across SW Ohio, NKY, and SE Indiana. Full inpatient, surgery, mental health, polytrauma support clinic, hospice/palliative, and 6 community-based outpatient clinics (CBOCs) including Bellevue KY, Florence KY, Hamilton OH, Lawrenceburg IN, Clermont County OH." },
  { section: "VA", title: "Dayton VA Medical Center", cat: "healthcare", sub: "VA Medical Centers", city: "Dayton", website_url: "https://www.va.gov/dayton-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "937-268-6511", address: "4100 W 3rd St, Dayton, OH 45428", zip: "45428", desc: "Dayton VA Medical Center — tertiary-care VA hospital serving 41,000+ veterans across W Ohio and E Indiana. Full inpatient, surgery, mental health, Community Living Center (CLC), residential SUD, hospice/palliative, and 6 community-based outpatient clinics (CBOCs) including Lima, Middletown, Springfield, Richmond IN." },
  { section: "VA", title: "Chillicothe VA Medical Center", cat: "healthcare", sub: "VA Medical Centers", city: "Chillicothe", website_url: "https://www.va.gov/chillicothe-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "740-773-1141", address: "17273 SR 104, Chillicothe, OH 45601", zip: "45601", desc: "Chillicothe VA Medical Center — tertiary-care VA hospital on a 720-acre campus serving 23,000+ veterans across S/SE Ohio and NE Kentucky. Full inpatient, mental health residential rehabilitation (PTSD, SUD), Community Living Center, hospice/palliative, and 5 community-based outpatient clinics (CBOCs) including Athens, Cambridge, Lancaster, Marietta, Portsmouth." },
  { section: "VA", title: "Chalmers P. Wylie Veterans Outpatient Clinic", cat: "healthcare", sub: "VA Outpatient Clinics", city: "Columbus", website_url: "https://www.va.gov/central-ohio-health-care/", source_name: "Department of Veterans Affairs", source_type: "va_facility", phone: "614-257-5200", address: "420 N James Rd, Columbus, OH 43219", zip: "43219", desc: "Chalmers P. Wylie Veterans Outpatient Clinic — VA Central Ohio Healthcare System anchor serving 50,000+ veterans across 14 counties. Outpatient primary care, mental health, surgery (ambulatory), women's health, and PTSD clinic; 5 community-based outpatient clinics (Marion, Newark, Zanesville, Grove City, Wilmington) report up to Wylie." },

  // ---- C. CHARTERED STATEWIDE VSOs (6) ----
  { section: "VSO", title: "American Legion Department of Ohio", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://www.ohiolegion.com/", source_name: "American Legion Department of Ohio", source_type: "nonprofit", phone: "614-362-7478", address: "1100 W Goodale Blvd, Columbus, OH 43212", zip: "43212", desc: "American Legion Department of Ohio — chartered veterans service org with 73,000+ members across 537 posts statewide. Free VA-claim assistance via Department Service Officers co-located at VA Cleveland RO, Cincinnati VAMC, Dayton VAMC, Chillicothe VAMC, and Wylie OPC; American Legion Auxiliary; Sons of the American Legion; Boys State; Oratorical contests." },
  { section: "VSO", title: "VFW Department of Ohio", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://www.vfwohio.org/", source_name: "Veterans of Foreign Wars Department of Ohio", source_type: "nonprofit", phone: "614-203-4350", address: "165 N High St Suite 10, Columbus, OH 43215", zip: "43215", desc: "VFW Department of Ohio — chartered veterans service org with 38,000+ members across 400+ posts statewide. Free VA-claim assistance via Department Service Officers co-located at VA Cleveland RO and OH VAMCs; VFW Auxiliary; Voice of Democracy / Patriot's Pen scholarships; Buddy Poppy distributions; State Veterans Service Officer training." },
  { section: "VSO", title: "DAV Department of Ohio", cat: "disabled-veterans", sub: "Disability Benefits & Claims", city: "Columbus", website_url: "https://www.davohio.org/", source_name: "Disabled American Veterans Department of Ohio", source_type: "nonprofit", phone: "614-431-6990", address: "5024 N High St, Columbus, OH 43214", zip: "43214", desc: "Disabled American Veterans Department of Ohio — chartered veterans service org with 36,000+ members across 95+ chapters statewide. Free VA-claim assistance via DAV-trained NSOs co-located at VA Cleveland RO and OH VAMCs; DAV Transportation Network providing free volunteer-driver shuttle to VA appointments at all 5 OH VAMCs; legislative advocacy; chapter charters statewide." },
  { section: "VSO", title: "AMVETS Department of Ohio", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://www.amvetsoh.org/", source_name: "AMVETS Department of Ohio", source_type: "nonprofit", phone: "614-431-6990", address: "1395 E Dublin-Granville Rd Suite 218, Columbus, OH 43229", zip: "43229", desc: "AMVETS Department of Ohio — chartered veterans service org with 22,000+ members across 200+ posts statewide. Free VA-claim assistance via Department Service Officers co-located at VA Cleveland RO and OH VAMCs; AMVETS Auxiliary; Sons of AMVETS; Riders; veteran scholarships; National Convention representation." },
  { section: "VSO", title: "Marine Corps League Department of Ohio", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://www.deptohiomcl.org/", source_name: "Marine Corps League Department of Ohio", source_type: "nonprofit", phone: "614-538-9988", desc: "Marine Corps League Department of Ohio — chartered veterans service org for Marines and Navy Corpsmen with 60+ Ohio detachments. Detachment-administered emergency-financial-assistance grants; Toys for Tots Ohio coordination; Marine Corps Birthday Ball logistics; National Convention representation; coordinates with VA Cleveland RO for claims filings." },
  { section: "VSO", title: "Vietnam Veterans of America — Ohio State Council", cat: "va-benefits", sub: "VA Benefits Counselors", city: "Columbus", website_url: "https://www.vva.org/state-council/ohio/", source_name: "Vietnam Veterans of America", source_type: "nonprofit", phone: "301-585-4000", desc: "Vietnam Veterans of America Ohio State Council — chartered veterans service org with 30+ Ohio chapters. Chapter-administered emergency-financial-assistance, Agent Orange and toxic-exposure benefits-claims service via VVA-trained Service Officers, and Veterans Initiative for POW/MIA accounting. Coordinates with VA Cleveland Regional Office for claim filings." },

  // ---- D. STATEWIDE VETERAN NONPROFITS (4) ----
  { section: "VNPO", title: "Honor Flight Network — National Headquarters", cat: "community-support", sub: "Veteran Outreach Programs", city: "Springfield", website_url: "https://www.honorflight.org/", source_name: "Honor Flight Network", source_type: "nonprofit", phone: "937-521-2400", address: "300 E Auburn Ave, Springfield, OH 45505", zip: "45505", desc: "Honor Flight Network — national nonprofit (HQ Springfield, OH) honoring America's veterans by transporting them at no cost to Washington DC to visit the war memorials built in their honor. 130+ regional hubs nationwide; Ohio hubs include Honor Flight Cleveland, Columbus, Dayton, Cincinnati, Toledo, Akron-Canton, Mid-Ohio, and Lake Erie." },
  { section: "VNPO", title: "Buckeye Veterans Network", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://www.bvn.gov/", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "614-644-0898", address: "77 S High St 7th Floor, Columbus, OH 43215", zip: "43215", desc: "Buckeye Veterans Network (BVN) — Ohio Department of Veterans Services online directory and statewide referral platform connecting Ohio veterans to verified state, county, federal, and nonprofit veteran resources. Searchable by county and service category; partners with all 88 County Veterans Service Commissions." },
  { section: "VNPO", title: "Veterans Outreach Services — Ohio", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://www.vso.gov/", source_name: "Ohio Department of Veterans Services", source_type: "state_agency", phone: "614-644-0898", desc: "Ohio Veterans Outreach Services Program — ODVS-administered statewide outreach connecting underserved, rural, and at-risk Ohio veterans to VA benefits, healthcare, mental health, housing, and employment resources. Coordinates with VA Cleveland RO, all 5 OH VAMCs, and the 88 County Veterans Service Commissions." },
  { section: "VNPO", title: "Ohio Means Veteran Jobs", cat: "employment", sub: "Veteran Employment Services", city: "Columbus", website_url: "https://ohiomeansjobs.ohio.gov/job-seekers/veterans", source_name: "Ohio Department of Job and Family Services", source_type: "state_agency", phone: "888-296-7541", address: "30 E Broad St 32nd Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Means Veteran Jobs — ODJFS-administered statewide veteran employment portal and statewide network of OhioMeansJobs centers in all 88 counties. Veterans receive Priority of Service: dedicated DVOPs/LVERs, JVSG-funded case management, employer matching, on-the-job training reimbursement, and apprenticeship navigation." },

  // ---- E. STATE AGENCIES SERVING VETERANS (6) ----
  { section: "STATE", title: "Ohio Department of Job and Family Services (ODJFS)", cat: "employment", sub: "Workforce Development", city: "Columbus", website_url: "https://jfs.ohio.gov/", source_name: "Ohio Department of Job and Family Services", source_type: "state_agency", phone: "614-466-6282", address: "30 E Broad St 32nd Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Job and Family Services — cabinet-level state agency administering Workforce Development (OhioMeansJobs / WIOA), Unemployment Compensation, SNAP / Medicaid / TANF / cash assistance / child support. 88-county network; Veteran Priority of Service mandated at all OhioMeansJobs centers." },
  { section: "STATE", title: "Ohio Department of Mental Health and Addiction Services (OhioMHAS)", cat: "mental-health", sub: "State Mental Health Authority", city: "Columbus", website_url: "https://mha.ohio.gov/", source_name: "Ohio Department of Mental Health and Addiction Services", source_type: "state_agency", phone: "614-466-2596", address: "30 E Broad St 36th Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Mental Health and Addiction Services (OhioMHAS) — cabinet-level state agency. Operates 6 state psychiatric hospitals, certifies 600+ community behavioral-health and SUD providers, administers 988 Suicide & Crisis Lifeline statewide, and coordinates the Ohio Veteran Behavioral Health Initiative with all 5 OH VAMCs." },
  { section: "STATE", title: "Ohio Department of Health (ODH)", cat: "healthcare", sub: "State Health Department", city: "Columbus", website_url: "https://odh.ohio.gov/", source_name: "Ohio Department of Health", source_type: "state_agency", phone: "614-466-3543", address: "246 N High St, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Health — cabinet-level state agency. Public health, immunizations, WIC, infant mortality reduction, hospital licensure, vital records (birth/death/marriage), and the Ohio Buckeye Health Plan Medicaid managed-care contract. Partners with VA Ohio facilities for veteran public-health outreach (Vet Center coordination, COVID/flu, suicide prevention)." },
  { section: "STATE", title: "Ohio Department of Aging", cat: "end-of-life-services", sub: "Senior & Disabled Meal Programs", city: "Columbus", website_url: "https://aging.ohio.gov/", source_name: "Ohio Department of Aging", source_type: "state_agency", phone: "614-466-5500", address: "246 N High St 1st Floor, Columbus, OH 43215", zip: "43215", desc: "Ohio Department of Aging — cabinet-level state agency. Administers PASSPORT and MyCare Ohio Medicaid HCBS waivers, the 12 Area Agencies on Aging (AAA) statewide, Long-Term Care Ombudsman Program, OSHIIP Medicare counseling, and Senior Community Service Employment Program. Coordinates with VA Geriatrics & Extended Care for elderly veterans." },
  { section: "STATE", title: "Ohio Department of Insurance — OSHIIP (SHIP)", cat: "insurance", sub: "Medicare & VA Plans", city: "Columbus", website_url: "https://insurance.ohio.gov/wps/portal/gov/odi/about-us/divisions/oshiip", source_name: "Ohio Department of Insurance", source_type: "state_agency", phone: "800-686-1578", address: "50 W Town St 3rd Floor Suite 300, Columbus, OH 43215", zip: "43215", desc: "Ohio Senior Health Insurance Information Program (OSHIIP) — Ohio's federally-funded SHIP program. Free unbiased counseling for Medicare-eligible Ohioans (including veterans on Medicare + VA) on Original Medicare, Medicare Advantage, Part D, Medigap, and Medicaid Spend-down. 88-county volunteer counselor network coordinated through Area Agencies on Aging." },
  { section: "STATE", title: "Ohio Housing Finance Agency (OHFA)", cat: "housing", sub: "Affordable Housing", city: "Columbus", website_url: "https://ohiohome.org/", source_name: "Ohio Housing Finance Agency", source_type: "state_agency", phone: "888-362-6432", address: "57 E Main St, Columbus, OH 43215", zip: "43215", desc: "Ohio Housing Finance Agency — quasi-governmental state agency. Administers below-market mortgage programs (Ohio Heroes for veterans/active-duty/teachers/first-responders), down-payment assistance grants, Mortgage Tax Credit Certificates, Low-Income Housing Tax Credit allocations, Save the Dream Ohio foreclosure prevention, and the Housing Trust Fund." },

  // ---- F. STATEWIDE NONPROFIT ANCHORS (8) ----
  { section: "NPO", title: "Ohio Association of Foodbanks", cat: "food-assistance", sub: "Food Banks", city: "Columbus", website_url: "https://ohiofoodbanks.org/", source_name: "Ohio Association of Foodbanks", source_type: "nonprofit", phone: "614-221-4336", address: "51 N High St Suite 800, Columbus, OH 43215", zip: "43215", desc: "Ohio Association of Foodbanks — statewide collaborative of Ohio's 12 Feeding America-affiliated regional food banks distributing 250M+ pounds of food annually through 3,600+ partner food pantries, soup kitchens, and shelters. Operates Ohio Benefit Bank (free SNAP / Medicaid / tax filings), and the Ohio Veteran Food Pantry program with VA OH partners." },
  { section: "NPO", title: "Coalition on Homelessness and Housing in Ohio (COHHIO)", cat: "housing", sub: "Homeless Services", city: "Columbus", website_url: "https://cohhio.org/", source_name: "Coalition on Homelessness and Housing in Ohio", source_type: "nonprofit", phone: "614-280-1984", address: "175 S 3rd St Suite 580, Columbus, OH 43215", zip: "43215", desc: "Coalition on Homelessness and Housing in Ohio (COHHIO) — statewide nonprofit advocacy and TA org for Ohio's homeless-services and affordable-housing networks. Coordinates the Ohio Balance of State Continuum of Care (BoSCoC) covering 80 of 88 OH counties; provides SSVF/HUD-VASH technical assistance for veteran homeless prevention statewide." },
  { section: "NPO", title: "Ohio Domestic Violence Network", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Columbus", website_url: "https://www.odvn.org/", source_name: "Ohio Domestic Violence Network", source_type: "nonprofit", phone: "800-934-9840", address: "1855 E Dublin-Granville Rd Suite 301, Columbus, OH 43229", zip: "43229", desc: "Ohio Domestic Violence Network (ODVN) — statewide coalition of 73 certified domestic-violence programs across all 88 OH counties. Operates the statewide DV hotline (800-934-9840), trains DV advocates, coordinates DV homicide review, and runs the Ohio Veteran Survivor Project partnered with VA OH IPV Coordinators." },
  { section: "NPO", title: "Ohio Alliance to End Sexual Violence (OAESV)", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Cleveland", website_url: "https://www.oaesv.org/", source_name: "Ohio Alliance to End Sexual Violence", source_type: "nonprofit", phone: "888-886-8388", address: "6111 Oak Tree Blvd Suite 140, Independence, OH 44131", zip: "44131", desc: "Ohio Alliance to End Sexual Violence (OAESV) — statewide coalition of 30 rape-crisis centers serving all 88 OH counties. Operates the statewide sexual-assault hotline (888-886-8388), trains advocates, coordinates SANE forensic-exam programs, and partners with Cleveland VAMC Military Sexual Trauma Coordinator on veteran MST referrals." },
  { section: "NPO", title: "Ohio Suicide Prevention Foundation", cat: "mental-health", sub: "Suicide Prevention", city: "Columbus", website_url: "https://www.ohiospf.org/", source_name: "Ohio Suicide Prevention Foundation", source_type: "nonprofit", phone: "614-429-1528", address: "1900 Polaris Pkwy Suite 450-115, Columbus, OH 43240", zip: "43240", desc: "Ohio Suicide Prevention Foundation — statewide nonprofit coordinating suicide prevention strategy across Ohio. Operates Zero Suicide Ohio, Ohio Veterans Suicide Prevention initiative partnered with VA Ohio facilities and the Veterans Crisis Line, the Ohio Lethal Means Safety project, and survivor support groups via OhioMHAS partnership." },
  { section: "NPO", title: "Ohio Legal Help", cat: "legal", sub: "Legal Aid Services", city: "Columbus", website_url: "https://www.ohiolegalhelp.org/", source_name: "Ohio Legal Help", source_type: "nonprofit", phone: "614-628-4940", address: "1108 City Park Ave, Columbus, OH 43206", zip: "43206", desc: "Ohio Legal Help — statewide self-help legal portal serving Ohioans on civil legal issues (housing/eviction, family law, consumer, public benefits, expungement). Free interactive forms, statewide legal-aid referral, and the Ohio Veteran Legal Resource directory connecting OH veterans to county-level pro-bono and Volunteer Lawyer Project services." },
  { section: "NPO", title: "Ohio State Legal Services Association (Legal Aid of Ohio)", cat: "legal", sub: "Legal Aid Services", city: "Columbus", website_url: "https://www.oslsa.org/", source_name: "Ohio State Legal Services Association", source_type: "nonprofit", phone: "614-221-7201", address: "1108 City Park Ave, Columbus, OH 43206", zip: "43206", desc: "Ohio State Legal Services Association — statewide LSC-funded legal-aid coordinator overseeing 6 regional legal-aid orgs covering all 88 OH counties (Legal Aid of Cleveland, Legal Aid of Western Ohio, Community Legal Aid SE OH, SE Ohio Legal Services, Advocates for Basic Legal Equality, Ohio Poverty Law Center). Coordinates Ohio Veterans Legal Project." },
  { section: "NPO", title: "Ohio Council for Home Care and Hospice", cat: "end-of-life-services", sub: "Hospice & Palliative Care", city: "Columbus", website_url: "https://www.ochch.org/", source_name: "Ohio Council for Home Care and Hospice", source_type: "nonprofit", phone: "614-885-0434", address: "1105 Schrock Rd Suite 120, Columbus, OH 43229", zip: "43229", desc: "Ohio Council for Home Care and Hospice — statewide trade association of 350+ certified Ohio home-health, hospice, and palliative-care providers. Maintains statewide member directory; provider quality standards; advocacy at Ohio Statehouse; coordinates We Honor Veterans (WHV) program participation across OH hospices partnered with VA OH facilities." },

  // ---- G. STATEWIDE HOTLINES (4) ----
  { section: "HOT", title: "Ohio CareLine — 988 Suicide & Crisis Lifeline", cat: "crisis-help", sub: "Suicide Prevention", city: "Columbus", website_url: "https://mha.ohio.gov/get-help/get-help-now/ohio-careline", source_name: "Ohio Department of Mental Health and Addiction Services", source_type: "state_agency", phone: "988", desc: "Ohio CareLine — OhioMHAS-administered 24/7 statewide emotional-support and crisis line. Free, confidential, anonymous. Trained behavioral-health professionals; warm-handoff to local County ADAMH Boards' mobile crisis teams; specialized Press 1 Veterans line routes to Veterans Crisis Line. Available via 988 call/text/chat or 1-800-720-9616." },
  { section: "HOT", title: "Ohio Domestic Violence Hotline", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Columbus", website_url: "https://www.odvn.org/get-help/", source_name: "Ohio Domestic Violence Network", source_type: "nonprofit", phone: "800-934-9840", desc: "Statewide 24/7 confidential hotline operated by Ohio Domestic Violence Network connecting Ohioans experiencing intimate-partner violence to local certified DV programs across all 88 OH counties. Safety planning, shelter placement, civil protection-order navigation, and warm-handoff to local advocates. Partners with VA OH IPV Coordinators for veteran survivors." },
  { section: "HOT", title: "Ohio Sexual Assault Helpline", cat: "crisis-help", sub: "Domestic Violence / Safety", city: "Cleveland", website_url: "https://www.oaesv.org/get-help/", source_name: "Ohio Alliance to End Sexual Violence", source_type: "nonprofit", phone: "844-644-6435", desc: "Statewide 24/7 confidential helpline operated by Ohio Alliance to End Sexual Violence connecting Ohioans who have experienced sexual violence to local rape-crisis centers across all 88 OH counties. SANE forensic-exam coordination, advocacy, counseling referral; specialized handoff to VA OH MST Coordinators for veteran survivors of military sexual trauma." },
  { section: "HOT", title: "Ohio 211 — HelpLink", cat: "community-support", sub: "Information & Referral", city: "Columbus", website_url: "https://211ohio.org/", source_name: "Ohio United Way / Ohio 211", source_type: "nonprofit", phone: "211", desc: "Ohio 211 — statewide free 24/7 information & referral service connecting Ohioans to social services across food, housing, utilities, employment, healthcare, mental health, legal, and veteran-specific programs. Available via dial 211, text 898-211, or 211ohio.org. Coordinated through 23 regional 211 centers covering all 88 OH counties; multilingual." },

  // ---- H. STATEWIDE COMMUNITY ANCHORS (5) ----
  { section: "COM", title: "United Way of Ohio (Ohio United Way)", cat: "community-support", sub: "Information & Referral", city: "Columbus", website_url: "https://www.ohiounitedway.org/", source_name: "Ohio United Way", source_type: "nonprofit", phone: "614-224-8146", address: "37 W Broad St Suite 1100, Columbus, OH 43215", zip: "43215", desc: "Ohio United Way — statewide association of 47 local United Way organizations across all 88 OH counties. Operates Ohio 211 statewide I&R; coordinates EITC outreach, FAFSA day, summer hunger, and community-impact grant-making; partners with all 5 OH VAMCs and the 88 County Veterans Service Commissions for veteran outreach campaigns." },
  { section: "COM", title: "American Red Cross — Ohio Region", cat: "financial", sub: "Emergency Financial Assistance", city: "Cleveland", website_url: "https://www.redcross.org/local/ohio.html", source_name: "American Red Cross", source_type: "nonprofit", phone: "216-431-3010", address: "3747 Euclid Ave, Cleveland, OH 44115", zip: "44115", desc: "American Red Cross Ohio Region — statewide chapter operating disaster response, blood services, military Hero Care Network (24/7 emergency communications + financial assistance for active-duty/veterans/families), and Service to the Armed Forces casework. Partners with all OH military installations, VA OH facilities, and AER/AFAS/NMCRS/CGMA for emergency relief." },
  { section: "COM", title: "Goodwill Industries of Ohio", cat: "employment", sub: "Workforce Development", city: "Cleveland", website_url: "https://www.goodwill.org/", source_name: "Goodwill Industries of Ohio", source_type: "nonprofit", phone: "216-431-3300", address: "2295 E 55th St, Cleveland, OH 44103", zip: "44103", desc: "Goodwill Industries — Ohio's 9 regional Goodwill agencies (Akron, Cleveland, Columbus, Cincinnati, Dayton, Lima, Toledo, Youngstown, Mid-Ohio Valley) operate retail, donation centers, workforce-development programs, AbilityOne contracts, and the Operation: GoodJobs veteran employment initiative partnered with VA OH and OhioMeansJobs." },
  { section: "COM", title: "Salvation Army — Ohio Northeast Division", cat: "community-support", sub: "Veteran Outreach Programs", city: "Cleveland", website_url: "https://easternusa.salvationarmy.org/northeast-ohio/", source_name: "The Salvation Army", source_type: "nonprofit", phone: "216-861-8185", address: "2507 E 22nd St, Cleveland, OH 44115", zip: "44115", desc: "Salvation Army Ohio Northeast Division HQ overseeing 30+ corps community centers across NE Ohio. Daily soup kitchens, food pantries, emergency shelter, transitional housing, SSVF veteran homeless prevention partnered with HUD-VASH at Cleveland VAMC, Pathway of Hope, and disaster-response operations across the entire OH Northeast region." },
  { section: "COM", title: "Catholic Charities of Ohio", cat: "community-support", sub: "Veteran Outreach Programs", city: "Columbus", website_url: "https://www.catholicconference.org/social-action/catholic-charities/", source_name: "Catholic Conference of Ohio", source_type: "nonprofit", phone: "614-224-7147", address: "9 E Long St Suite 201, Columbus, OH 43215", zip: "43215", desc: "Catholic Charities Ohio — statewide affiliation of 6 diocesan Catholic Charities offices (Cleveland, Columbus, Cincinnati, Toledo, Youngstown, Steubenville) covering all 88 OH counties. Family services, food pantries, immigration legal services, refugee resettlement, behavioral health, and the Catholic Charities Veteran Services partnership with VA OH facilities." },
];

console.log(`[seed-oh-phase1] ${ROWS.length} rows queued (${COMMIT ? "COMMIT" : "DRY-RUN"})`);
runSeed(ROWS, {
  state: "OH", commit: COMMIT, scriptName: "OH Phase 1 — State Foundation",
  batchTag: "oh-phase1", allowBrokenUrls: ALLOW_BROKEN_URLS,
  sectionLabels: { STATE: "State Agencies/Veteran", VA: "VA Anchors", VSO: "Chartered VSOs", VNPO: "Veteran Nonprofits", NPO: "Statewide Nonprofits", HOT: "Hotlines", COM: "Community Anchors" },
}).catch((e) => { console.error(e); process.exit(1); });
