/**
 * North Carolina Resources Seed — Round 1
 *
 * Mirrors the proven SC ingestion model but built against the CURRENT live taxonomy:
 * - Loads category UUIDs + subcategory IDs from live DB at runtime (no hardcoded UUIDs that could drift)
 * - Inserts into resources table + resource_categories junction + resource_subcategories junction
 * - Uses verified hardcoded geo for major NC facilities (geocoder bypass, faster + more accurate)
 * - Dedupe by (title, state) — re-runs are safe
 * - Service role client (bypasses RLS)
 *
 * Run: tsx scripts/seed-nc-resources.ts
 */
import { supabaseAdmin } from "../server/supabase";

const STATE = "NC";

interface SeedResource {
  title: string;
  category_slug: string;
  subcategory_name?: string;
  short_description: string;
  website_url?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  zip?: string;
  latitude?: number;
  longitude?: number;
  eligibility?: string;
  source_name: string;
  source_type: "program" | "service" | "facility" | "nonprofit" | "government";
  status?: "approved" | "pending";
}

const NC_RESOURCES: SeedResource[] = [
  // ============================================================
  // HEALTHCARE — VA Medical Centers (4) + Major CBOCs/HCCs
  // ============================================================
  {
    title: "Fayetteville VA Medical Center (FAVAHCS)",
    category_slug: "healthcare",
    subcategory_name: "VA Medical Centers",
    short_description: "Full-service VA medical center serving veterans across eastern NC including Fort Liberty community. Primary care, mental health, surgery, specialty services.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/fayetteville-va-medical-center/",
    phone: "910-488-2120",
    address: "2300 Ramsey Street",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0786,
    longitude: -78.9007,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Durham VA Medical Center",
    category_slug: "healthcare",
    subcategory_name: "VA Medical Centers",
    short_description: "Tertiary care VA medical center serving central NC. Comprehensive medical, surgical, mental health, and rehabilitation services. Affiliated with Duke University Medical Center.",
    website_url: "https://www.va.gov/durham-health-care/",
    phone: "919-286-0411",
    address: "508 Fulton Street",
    city: "Durham",
    zip: "27705",
    latitude: 36.0033,
    longitude: -78.9352,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Charles George VA Medical Center (Asheville)",
    category_slug: "healthcare",
    subcategory_name: "VA Medical Centers",
    short_description: "VA medical center serving western NC. Full primary, specialty, and mental health services for veterans across the Blue Ridge region.",
    website_url: "https://www.va.gov/asheville-health-care/",
    phone: "828-298-7911",
    address: "1100 Tunnel Road",
    city: "Asheville",
    zip: "28805",
    latitude: 35.5841,
    longitude: -82.4757,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "W.G. (Bill) Hefner VA Medical Center (Salisbury)",
    category_slug: "healthcare",
    subcategory_name: "VA Medical Centers",
    short_description: "VA medical center serving central and western NC piedmont. Primary care, mental health, geriatric care, polytrauma, and PTSD treatment programs.",
    website_url: "https://www.va.gov/salisbury-health-care/",
    phone: "704-638-9000",
    address: "1601 Brenner Avenue",
    city: "Salisbury",
    zip: "28144",
    latitude: 35.6534,
    longitude: -80.4886,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Charlotte VA Health Care Center",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "Large outpatient VA clinic serving Charlotte metro. Primary care, mental health, women's health, audiology, optometry, and specialty services.",
    website_url: "https://www.va.gov/salisbury-health-care/locations/charlotte-vha-health-care-center/",
    phone: "704-329-1300",
    address: "8601 University East Drive",
    city: "Charlotte",
    zip: "28213",
    latitude: 35.3084,
    longitude: -80.7375,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Raleigh VA Health Care Center",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "Major outpatient VA clinic serving Wake County and surrounding area. Primary care, mental health, specialty care, and women veterans health.",
    website_url: "https://www.va.gov/durham-health-care/locations/raleigh-ii-vha-health-care-center/",
    phone: "919-212-0129",
    address: "3305 Sungate Boulevard",
    city: "Raleigh",
    zip: "27610",
    latitude: 35.7479,
    longitude: -78.6055,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Greenville Health Care Center (NC)",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA clinic serving eastern NC. Primary care, mental health, dental, and specialty services.",
    website_url: "https://www.va.gov/durham-health-care/locations/greenville-vha-health-care-center/",
    phone: "252-830-2149",
    address: "401 Moye Boulevard",
    city: "Greenville",
    zip: "27834",
    latitude: 35.6020,
    longitude: -77.3772,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Wilmington VA Health Care Center",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving southeastern NC coast. Primary care, mental health, women's health, and specialty services.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/wilmington-vha-health-care-center/",
    phone: "910-343-5300",
    address: "1705 Gardner Road",
    city: "Wilmington",
    zip: "28405",
    latitude: 34.2520,
    longitude: -77.8652,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Jacksonville VA Health Care Center (NC)",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Camp Lejeune Marine community and Onslow County. Primary care, mental health, specialty care for active-duty transitioning veterans.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/jacksonville-vha-health-care-center/",
    phone: "910-353-6406",
    address: "4006 Henderson Drive",
    city: "Jacksonville",
    zip: "28546",
    latitude: 34.7541,
    longitude: -77.4302,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Greensboro VA Health Care Center",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Triad region. Primary care, mental health, specialty services.",
    website_url: "https://www.va.gov/salisbury-health-care/locations/greensboro-vha-health-care-center/",
    phone: "336-545-5300",
    address: "3515 Lawndale Drive",
    city: "Greensboro",
    zip: "27408",
    latitude: 36.1232,
    longitude: -79.8369,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Winston-Salem VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Forsyth County. Primary care, mental health, telehealth.",
    website_url: "https://www.va.gov/salisbury-health-care/locations/winston-salem-vha-clinic/",
    phone: "336-768-3296",
    address: "190 Kimel Park Drive",
    city: "Winston-Salem",
    zip: "27103",
    latitude: 36.0931,
    longitude: -80.3198,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Hickory VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving foothills and Catawba County region. Primary care, mental health, telehealth.",
    website_url: "https://www.va.gov/salisbury-health-care/locations/hickory-vha-clinic/",
    phone: "828-431-5600",
    address: "2440 Century Place SE",
    city: "Hickory",
    zip: "28602",
    latitude: 35.7156,
    longitude: -81.3265,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Hamlet VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Richmond County and surrounding rural areas. Primary care and mental health.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/hamlet-vha-clinic/",
    phone: "910-582-3536",
    address: "100 Jefferson Street",
    city: "Hamlet",
    zip: "28345",
    latitude: 34.8854,
    longitude: -79.6948,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Robeson County VA Clinic (Pembroke)",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic in Pembroke serving Robeson County and surrounding rural communities.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/robeson-county-vha-clinic/",
    phone: "910-272-3220",
    address: "139 Three Hunts Drive",
    city: "Pembroke",
    zip: "28372",
    latitude: 34.6802,
    longitude: -79.1956,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Brunswick County VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Brunswick County. Primary care and mental health services.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/brunswick-county-vha-clinic/",
    phone: "910-754-6141",
    address: "20 Medical Campus Drive",
    city: "Supply",
    zip: "28462",
    latitude: 34.0235,
    longitude: -78.3614,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Goldsboro VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Wayne County and Seymour Johnson AFB community. Primary care and mental health.",
    website_url: "https://www.va.gov/durham-health-care/locations/goldsboro-vha-clinic/",
    phone: "919-731-4809",
    address: "2610 Hospital Road",
    city: "Goldsboro",
    zip: "27534",
    latitude: 35.3727,
    longitude: -77.9764,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Morehead City VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving NC Crystal Coast region. Primary care, mental health, specialty referrals.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/locations/morehead-city-vha-clinic/",
    phone: "252-240-2349",
    address: "5420 US Highway 70 West",
    city: "Morehead City",
    zip: "28557",
    latitude: 34.7393,
    longitude: -76.7513,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Franklin VA Clinic (NC)",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Macon County and far western NC mountains. Primary care, mental health, telehealth.",
    website_url: "https://www.va.gov/asheville-health-care/locations/franklin-vha-clinic/",
    phone: "828-369-1781",
    address: "647 Wayah Street",
    city: "Franklin",
    zip: "28734",
    latitude: 35.1827,
    longitude: -83.3812,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Rutherford County VA Clinic",
    category_slug: "healthcare",
    subcategory_name: "VA Clinics",
    short_description: "VA outpatient clinic serving Rutherford County and surrounding foothills. Primary care and mental health services.",
    website_url: "https://www.va.gov/asheville-health-care/locations/rutherford-county-vha-clinic/",
    phone: "828-288-2780",
    address: "374 Charlotte Road",
    city: "Rutherfordton",
    zip: "28139",
    latitude: 35.3705,
    longitude: -81.9637,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "Women Veterans Health Program — Fayetteville VAMC",
    category_slug: "healthcare",
    subcategory_name: "Women Veterans Healthcare",
    short_description: "Comprehensive women's health services at Fayetteville VAMC including primary care, gynecology, mental health, maternity care coordination, and military sexual trauma treatment.",
    website_url: "https://www.va.gov/fayetteville-coastal-health-care/programs/women-veterans-health/",
    phone: "910-488-2120",
    address: "2300 Ramsey Street",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0786,
    longitude: -78.9007,
    eligibility: "Women veterans enrolled in VA",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },
  {
    title: "Women Veterans Health Program — Durham VAMC",
    category_slug: "healthcare",
    subcategory_name: "Women Veterans Healthcare",
    short_description: "Women veterans health services at Durham VAMC. Primary care, gender-specific care, mental health, military sexual trauma coordinator.",
    website_url: "https://www.va.gov/durham-health-care/programs/women-veterans-health/",
    phone: "919-286-0411",
    city: "Durham",
    zip: "27705",
    latitude: 36.0033,
    longitude: -78.9352,
    eligibility: "Women veterans enrolled in VA",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },

  // ============================================================
  // MENTAL HEALTH — Vet Centers + Cohen Clinics + PTSD programs
  // ============================================================
  {
    title: "Fayetteville Vet Center",
    category_slug: "mental-health",
    subcategory_name: "Vet Centers",
    short_description: "Free and confidential readjustment counseling for combat veterans and families. Individual, group, marriage, and family counseling. Bereavement and military sexual trauma counseling.",
    website_url: "https://www.va.gov/fayetteville-vet-center/",
    phone: "910-488-6252",
    address: "4140 Ramsey Street, Suite 110",
    city: "Fayetteville",
    zip: "28311",
    latitude: 35.1314,
    longitude: -78.9159,
    eligibility: "Combat veterans, families, MST survivors — no enrollment required",
    source_name: "VA Vet Centers (Readjustment Counseling Service)",
    source_type: "facility",
  },
  {
    title: "Charlotte Vet Center",
    category_slug: "mental-health",
    subcategory_name: "Vet Centers",
    short_description: "Free confidential readjustment counseling for combat veterans and families across the Charlotte metro. Walk-ins welcome, no VA enrollment needed.",
    website_url: "https://www.va.gov/charlotte-vet-center/",
    phone: "704-549-8025",
    address: "2114 Ben Craig Drive",
    city: "Charlotte",
    zip: "28262",
    latitude: 35.3003,
    longitude: -80.7479,
    eligibility: "Combat veterans, families, MST survivors",
    source_name: "VA Vet Centers (Readjustment Counseling Service)",
    source_type: "facility",
  },
  {
    title: "Greensboro Vet Center",
    category_slug: "mental-health",
    subcategory_name: "Vet Centers",
    short_description: "Confidential counseling for combat veterans and families in the Triad region. Individual, group, family, and bereavement services.",
    website_url: "https://www.va.gov/greensboro-vet-center/",
    phone: "336-333-5366",
    address: "2009 Elm-Eugene Street",
    city: "Greensboro",
    zip: "27406",
    latitude: 36.0354,
    longitude: -79.7964,
    eligibility: "Combat veterans, families, MST survivors",
    source_name: "VA Vet Centers (Readjustment Counseling Service)",
    source_type: "facility",
  },
  {
    title: "Greenville Vet Center (NC)",
    category_slug: "mental-health",
    subcategory_name: "Vet Centers",
    short_description: "Free confidential counseling for combat veterans across eastern NC. Individual, group, marriage, family, and bereavement counseling.",
    website_url: "https://www.va.gov/greenville-nc-vet-center/",
    phone: "252-355-7920",
    address: "1021 W H Street",
    city: "Greenville",
    zip: "27834",
    latitude: 35.6088,
    longitude: -77.3829,
    eligibility: "Combat veterans, families, MST survivors",
    source_name: "VA Vet Centers (Readjustment Counseling Service)",
    source_type: "facility",
  },
  {
    title: "Raleigh Vet Center",
    category_slug: "mental-health",
    subcategory_name: "Vet Centers",
    short_description: "Free confidential readjustment counseling for combat veterans in Wake County and surrounding areas. Walk-ins welcome.",
    website_url: "https://www.va.gov/raleigh-vet-center/",
    phone: "919-856-4616",
    address: "1649 Old Louisburg Road",
    city: "Raleigh",
    zip: "27604",
    latitude: 35.8166,
    longitude: -78.6206,
    eligibility: "Combat veterans, families, MST survivors",
    source_name: "VA Vet Centers (Readjustment Counseling Service)",
    source_type: "facility",
  },
  {
    title: "Jacksonville Vet Center (NC)",
    category_slug: "mental-health",
    subcategory_name: "Vet Centers",
    short_description: "Free confidential counseling for Marine combat veterans and families near Camp Lejeune. Transitioning service members and dependents welcome.",
    website_url: "https://www.va.gov/jacksonville-nc-vet-center/",
    phone: "910-577-1100",
    address: "110 Branchwood Drive",
    city: "Jacksonville",
    zip: "28546",
    latitude: 34.7421,
    longitude: -77.4014,
    eligibility: "Combat veterans, families, MST survivors",
    source_name: "VA Vet Centers (Readjustment Counseling Service)",
    source_type: "facility",
  },
  {
    title: "Cohen Veterans Network Clinic — Fayetteville",
    category_slug: "mental-health",
    subcategory_name: "Counseling & Therapy",
    short_description: "Free or low-cost mental health care for post-9/11 veterans, service members, and families. Individual therapy, family therapy, child therapy, and psychiatry. Insurance not required.",
    website_url: "https://www.cohenveteransnetwork.org/clinics/easterseals-fayetteville/",
    phone: "910-985-2061",
    address: "2818 Owen Drive",
    city: "Fayetteville",
    zip: "28306",
    latitude: 35.0231,
    longitude: -78.9514,
    eligibility: "Post-9/11 veterans, service members, families",
    source_name: "Cohen Veterans Network",
    source_type: "nonprofit",
  },
  {
    title: "Cohen Veterans Network Clinic — Jacksonville (NC)",
    category_slug: "mental-health",
    subcategory_name: "Counseling & Therapy",
    short_description: "Free mental health services for post-9/11 veterans and families near Camp Lejeune. Individual, family, child therapy, and psychiatry.",
    website_url: "https://www.cohenveteransnetwork.org/clinics/easterseals-jacksonville/",
    phone: "910-353-2273",
    address: "201 Memorial Drive",
    city: "Jacksonville",
    zip: "28546",
    latitude: 34.7522,
    longitude: -77.4253,
    eligibility: "Post-9/11 veterans, service members, families",
    source_name: "Cohen Veterans Network",
    source_type: "nonprofit",
  },
  {
    title: "Salisbury VAMC PTSD Treatment Program",
    category_slug: "mental-health",
    subcategory_name: "PTSD & Trauma Support",
    short_description: "Specialized inpatient and outpatient PTSD treatment programs at Salisbury VAMC including PTSD Residential Rehabilitation Treatment Program (PRRTP).",
    website_url: "https://www.va.gov/salisbury-health-care/programs/mental-health-care/",
    phone: "704-638-9000",
    address: "1601 Brenner Avenue",
    city: "Salisbury",
    zip: "28144",
    latitude: 35.6534,
    longitude: -80.4886,
    eligibility: "Enrolled veterans with PTSD diagnosis",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },
  {
    title: "Durham VAMC Mental Health Services",
    category_slug: "mental-health",
    subcategory_name: "Inpatient / Outpatient Treatment",
    short_description: "Comprehensive mental health services including PTSD clinical team, addictive disorders treatment, women's mental health, and inpatient psychiatric care.",
    website_url: "https://www.va.gov/durham-health-care/programs/mental-health-care/",
    phone: "919-286-0411",
    address: "508 Fulton Street",
    city: "Durham",
    zip: "27705",
    latitude: 36.0033,
    longitude: -78.9352,
    eligibility: "Enrolled veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },

  // ============================================================
  // CRISIS HELP — Hotlines + LME-MCO Mobile Crisis (statewide coverage)
  // ============================================================
  {
    title: "Veterans Crisis Line",
    category_slug: "crisis-help",
    subcategory_name: "Veterans Crisis Line",
    short_description: "Free 24/7 confidential crisis support for veterans, service members, families. Dial 988 then press 1, text 838255, or chat online. Available across all of NC.",
    website_url: "https://www.veteranscrisisline.net",
    phone: "988",
    eligibility: "All veterans, service members, families",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "service",
  },
  {
    title: "988 Suicide & Crisis Lifeline (NC)",
    category_slug: "crisis-help",
    subcategory_name: "Suicide Prevention",
    short_description: "Free 24/7 crisis support — call or text 988. Statewide coverage across NC for anyone experiencing a mental health, substance use, or suicide crisis.",
    website_url: "https://988lifeline.org",
    phone: "988",
    eligibility: "Anyone in crisis",
    source_name: "988 Suicide & Crisis Lifeline",
    source_type: "service",
  },
  {
    title: "NAMI North Carolina",
    category_slug: "crisis-help",
    subcategory_name: "Emergency Mental Health",
    short_description: "Statewide NAMI affiliate offering helpline, education, support groups, and advocacy for individuals with mental illness and their families. Veterans-specific resources available.",
    website_url: "https://naminc.org",
    phone: "919-788-0801",
    address: "309 W Millbrook Road, Suite 121",
    city: "Raleigh",
    zip: "27609",
    latitude: 35.8728,
    longitude: -78.6422,
    eligibility: "Anyone affected by mental illness",
    source_name: "NAMI North Carolina",
    source_type: "nonprofit",
  },
  {
    title: "Trillium Health Resources Mobile Crisis (Eastern NC)",
    category_slug: "crisis-help",
    subcategory_name: "Mobile Crisis Teams",
    short_description: "24/7 mobile crisis response for mental health, substance use, and IDD crises across 28 eastern NC counties including Onslow, New Hanover, Brunswick, Pitt.",
    website_url: "https://www.trilliumhealthresources.org",
    phone: "877-685-2415",
    eligibility: "Residents of eastern NC counties served by Trillium",
    source_name: "Trillium Health Resources (LME-MCO)",
    source_type: "service",
  },
  {
    title: "Vaya Health Mobile Crisis (Western NC)",
    category_slug: "crisis-help",
    subcategory_name: "Mobile Crisis Teams",
    short_description: "24/7 mobile crisis response across 32 western NC counties including Buncombe, Henderson, Madison, Watauga. Mental health, substance use, IDD crisis support.",
    website_url: "https://www.vayahealth.com",
    phone: "1-800-849-6127",
    eligibility: "Residents of western NC counties served by Vaya",
    source_name: "Vaya Health (LME-MCO)",
    source_type: "service",
  },
  {
    title: "Alliance Health Mobile Crisis (Central NC)",
    category_slug: "crisis-help",
    subcategory_name: "Mobile Crisis Teams",
    short_description: "24/7 mobile crisis services for Wake, Durham, Cumberland, Johnston, Mecklenburg, Orange, Chatham, and Halifax counties.",
    website_url: "https://www.alliancehealthplan.org",
    phone: "877-223-4617",
    eligibility: "Residents of central NC counties served by Alliance",
    source_name: "Alliance Health (LME-MCO)",
    source_type: "service",
  },
  {
    title: "Sandhills Center Mobile Crisis",
    category_slug: "crisis-help",
    subcategory_name: "Mobile Crisis Teams",
    short_description: "24/7 mobile crisis response across Anson, Davidson, Guilford, Harnett, Hoke, Lee, Montgomery, Moore, Randolph, Richmond, and Rockingham counties.",
    website_url: "https://www.sandhillscenter.org",
    phone: "800-256-2452",
    eligibility: "Residents of central/sandhills NC counties",
    source_name: "Sandhills Center (LME-MCO)",
    source_type: "service",
  },
  {
    title: "Partners Health Management Mobile Crisis",
    category_slug: "crisis-help",
    subcategory_name: "Mobile Crisis Teams",
    short_description: "24/7 mobile crisis services across Burke, Cabarrus, Catawba, Cleveland, Davie, Forsyth, Gaston, Iredell, Lincoln, Rutherford, Stanly, Surry, Union, and Yadkin counties.",
    website_url: "https://www.partnersbhm.org",
    phone: "888-235-4673",
    eligibility: "Residents of west-central NC counties served by Partners",
    source_name: "Partners Health Management (LME-MCO)",
    source_type: "service",
  },
  {
    title: "Eastpointe Mobile Crisis",
    category_slug: "crisis-help",
    subcategory_name: "Mobile Crisis Teams",
    short_description: "24/7 mobile crisis services for Bladen, Columbus, Duplin, Edgecombe, Greene, Lenoir, Nash, Robeson, Sampson, Scotland, Wayne, and Wilson counties.",
    website_url: "https://www.eastpointe.net",
    phone: "800-913-6109",
    eligibility: "Residents of southeastern NC counties served by Eastpointe",
    source_name: "Eastpointe (LME-MCO)",
    source_type: "service",
  },

  // ============================================================
  // VA BENEFITS — NCDMVA + VARO + County VSOs (top 30) + State VSOs
  // ============================================================
  {
    title: "NC Department of Military and Veterans Affairs (NCDMVA)",
    category_slug: "va-benefits",
    subcategory_name: "Disability Claims Assistance",
    short_description: "State agency coordinating veteran services across NC. Operates 4 NC State Veterans Homes, 4 NC State Veterans Cemeteries, scholarship program, and supports county VSO network.",
    website_url: "https://www.milvets.nc.gov",
    phone: "844-624-8387",
    address: "4001 Mail Service Center",
    city: "Raleigh",
    zip: "27699",
    latitude: 35.7706,
    longitude: -78.6383,
    eligibility: "All NC veterans",
    source_name: "NC Department of Military and Veterans Affairs",
    source_type: "government",
  },
  {
    title: "VA Regional Office — Winston-Salem",
    category_slug: "va-benefits",
    subcategory_name: "Disability Claims Assistance",
    short_description: "VA Regional Office serving all of NC. Processes disability compensation claims, pension claims, education benefits, vocational rehabilitation referrals.",
    website_url: "https://www.benefits.va.gov/winston-salem/",
    phone: "1-800-827-1000",
    address: "251 N Main Street",
    city: "Winston-Salem",
    zip: "27155",
    latitude: 36.1004,
    longitude: -80.2452,
    eligibility: "All veterans",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "government",
  },
  {
    title: "Cumberland County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving veterans in Fayetteville and Cumberland County. VA claims assistance, benefits navigation, advocacy.",
    website_url: "https://co.cumberland.nc.us/departments/veterans-services",
    phone: "910-677-2970",
    address: "109 Bradford Avenue",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0468,
    longitude: -78.8784,
    eligibility: "Cumberland County veterans",
    source_name: "Cumberland County Government",
    source_type: "government",
  },
  {
    title: "Onslow County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Marines and veterans in Jacksonville and Onslow County (Camp Lejeune community). VA claims, appeals, benefits assistance.",
    website_url: "https://www.onslowcountync.gov/336/Veterans-Services",
    phone: "910-455-1742",
    address: "234 NW Corridor Boulevard",
    city: "Jacksonville",
    zip: "28540",
    latitude: 34.7541,
    longitude: -77.4302,
    eligibility: "Onslow County veterans",
    source_name: "Onslow County Government",
    source_type: "government",
  },
  {
    title: "Mecklenburg County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Charlotte metro veterans. Free claims assistance, appeals, accredited representation.",
    website_url: "https://www.mecknc.gov/CommunityResources/Pages/Veterans-Services.aspx",
    phone: "704-336-2102",
    address: "720 East 4th Street, Suite 311",
    city: "Charlotte",
    zip: "28202",
    latitude: 35.2271,
    longitude: -80.8401,
    eligibility: "Mecklenburg County veterans",
    source_name: "Mecklenburg County Government",
    source_type: "government",
  },
  {
    title: "Wake County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Raleigh and Wake County veterans. VA claims preparation, benefits counseling, appeals.",
    website_url: "https://www.wake.gov/departments-government/veterans-services",
    phone: "919-856-6563",
    address: "3010 Falstaff Road",
    city: "Raleigh",
    zip: "27610",
    latitude: 35.7536,
    longitude: -78.5907,
    eligibility: "Wake County veterans",
    source_name: "Wake County Government",
    source_type: "government",
  },
  {
    title: "Durham County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Durham veterans. VA claims, benefits navigation, appeals representation.",
    website_url: "https://www.dconc.gov/government/departments-f-z/veterans-services",
    phone: "919-560-8387",
    address: "414 East Main Street",
    city: "Durham",
    zip: "27701",
    latitude: 35.9969,
    longitude: -78.8995,
    eligibility: "Durham County veterans",
    source_name: "Durham County Government",
    source_type: "government",
  },
  {
    title: "Guilford County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Greensboro and High Point veterans. Free claims assistance and benefits counseling.",
    website_url: "https://www.guilfordcountync.gov/our-county/veterans-services",
    phone: "336-641-3411",
    address: "1203 Maple Street",
    city: "Greensboro",
    zip: "27405",
    latitude: 36.0726,
    longitude: -79.7919,
    eligibility: "Guilford County veterans",
    source_name: "Guilford County Government",
    source_type: "government",
  },
  {
    title: "Forsyth County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Winston-Salem and Forsyth County veterans. VA claims, appeals, benefits guidance.",
    website_url: "https://www.forsyth.cc/Veterans/",
    phone: "336-703-2950",
    address: "741 N Highland Avenue",
    city: "Winston-Salem",
    zip: "27101",
    latitude: 36.1027,
    longitude: -80.2370,
    eligibility: "Forsyth County veterans",
    source_name: "Forsyth County Government",
    source_type: "government",
  },
  {
    title: "New Hanover County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Wilmington and New Hanover County veterans. VA claims assistance and benefits counseling.",
    website_url: "https://veteranservices.nhcgov.com",
    phone: "910-798-7434",
    address: "230 Government Center Drive, Suite 145",
    city: "Wilmington",
    zip: "28403",
    latitude: 34.2375,
    longitude: -77.8729,
    eligibility: "New Hanover County veterans",
    source_name: "New Hanover County Government",
    source_type: "government",
  },
  {
    title: "Buncombe County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Asheville and Buncombe County veterans. VA claims, appeals, and benefits navigation.",
    website_url: "https://www.buncombecounty.org/governing/depts/veterans/",
    phone: "828-250-5726",
    address: "40 Coxe Avenue",
    city: "Asheville",
    zip: "28801",
    latitude: 35.5946,
    longitude: -82.5560,
    eligibility: "Buncombe County veterans",
    source_name: "Buncombe County Government",
    source_type: "government",
  },
  {
    title: "Wayne County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Goldsboro and Wayne County veterans (Seymour Johnson AFB community). VA claims and benefits assistance.",
    website_url: "https://www.waynegov.com/veterans-services",
    phone: "919-731-1452",
    address: "134 N John Street",
    city: "Goldsboro",
    zip: "27530",
    latitude: 35.3849,
    longitude: -77.9928,
    eligibility: "Wayne County veterans",
    source_name: "Wayne County Government",
    source_type: "government",
  },
  {
    title: "Craven County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Havelock (MCAS Cherry Point), New Bern, and Craven County. VA claims and benefits assistance.",
    website_url: "https://www.cravencountync.gov/281/Veteran-Services",
    phone: "252-636-6618",
    address: "406 Craven Street",
    city: "New Bern",
    zip: "28560",
    latitude: 35.1085,
    longitude: -77.0441,
    eligibility: "Craven County veterans",
    source_name: "Craven County Government",
    source_type: "government",
  },
  {
    title: "Harnett County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Harnett County veterans (adjacent to Fort Liberty). VA claims and benefits assistance.",
    website_url: "https://www.harnett.org/veterans/",
    phone: "910-893-7563",
    address: "309 W Cornelius Harnett Boulevard",
    city: "Lillington",
    zip: "27546",
    latitude: 35.3996,
    longitude: -78.8159,
    eligibility: "Harnett County veterans",
    source_name: "Harnett County Government",
    source_type: "government",
  },
  {
    title: "Hoke County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Hoke County veterans (adjacent to Fort Liberty). VA claims, benefits, and appeals.",
    website_url: "https://www.hokecounty.net",
    phone: "910-875-8746",
    address: "227 N Main Street",
    city: "Raeford",
    zip: "28376",
    latitude: 34.9810,
    longitude: -79.2236,
    eligibility: "Hoke County veterans",
    source_name: "Hoke County Government",
    source_type: "government",
  },
  {
    title: "Pitt County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Greenville and Pitt County veterans. VA claims and benefits assistance.",
    website_url: "https://www.pittcountync.gov/213/Veterans-Services",
    phone: "252-902-2887",
    address: "1717 W 5th Street",
    city: "Greenville",
    zip: "27834",
    latitude: 35.6127,
    longitude: -77.3964,
    eligibility: "Pitt County veterans",
    source_name: "Pitt County Government",
    source_type: "government",
  },
  {
    title: "Cabarrus County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Concord and Cabarrus County veterans (Charlotte metro). VA claims and benefits guidance.",
    website_url: "https://www.cabarruscounty.us/government/departments/veterans-services",
    phone: "704-920-2869",
    address: "65 Church Street S",
    city: "Concord",
    zip: "28025",
    latitude: 35.4093,
    longitude: -80.5860,
    eligibility: "Cabarrus County veterans",
    source_name: "Cabarrus County Government",
    source_type: "government",
  },
  {
    title: "Gaston County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Gastonia and Gaston County veterans. VA claims, appeals, benefits navigation.",
    website_url: "https://www.gastongov.com/departments/veterans_services/",
    phone: "704-862-7547",
    address: "330 Dr M.L.K. Jr Way",
    city: "Gastonia",
    zip: "28052",
    latitude: 35.2627,
    longitude: -81.1873,
    eligibility: "Gaston County veterans",
    source_name: "Gaston County Government",
    source_type: "government",
  },
  {
    title: "Union County Veterans Services (NC)",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Monroe and Union County veterans. VA claims and benefits assistance.",
    website_url: "https://www.unioncountync.gov/government/departments-r-z/veteran-services",
    phone: "704-292-2570",
    address: "500 N Main Street",
    city: "Monroe",
    zip: "28112",
    latitude: 34.9854,
    longitude: -80.5495,
    eligibility: "Union County veterans",
    source_name: "Union County Government",
    source_type: "government",
  },
  {
    title: "Iredell County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Statesville, Mooresville, and Iredell County veterans. VA claims and benefits guidance.",
    website_url: "https://www.iredellcountync.gov/241/Veterans-Services",
    phone: "704-878-3081",
    address: "316 E Broad Street",
    city: "Statesville",
    zip: "28677",
    latitude: 35.7842,
    longitude: -80.8869,
    eligibility: "Iredell County veterans",
    source_name: "Iredell County Government",
    source_type: "government",
  },
  {
    title: "Catawba County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Hickory, Newton, and Catawba County veterans. VA claims assistance.",
    website_url: "https://www.catawbacountync.gov/county-services/veterans-services/",
    phone: "828-695-6580",
    address: "3000 N Center Street",
    city: "Hickory",
    zip: "28601",
    latitude: 35.7541,
    longitude: -81.3270,
    eligibility: "Catawba County veterans",
    source_name: "Catawba County Government",
    source_type: "government",
  },
  {
    title: "Henderson County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Hendersonville and Henderson County veterans. VA claims and benefits navigation.",
    website_url: "https://www.hendersoncountync.gov/veterans",
    phone: "828-697-4861",
    address: "100 N King Street",
    city: "Hendersonville",
    zip: "28792",
    latitude: 35.3187,
    longitude: -82.4609,
    eligibility: "Henderson County veterans",
    source_name: "Henderson County Government",
    source_type: "government",
  },
  {
    title: "Brunswick County Veterans Services (NC)",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Brunswick County veterans (coastal southeastern NC). VA claims and benefits assistance.",
    website_url: "https://www.brunswickcountync.gov/veterans-services/",
    phone: "910-253-2273",
    address: "30 Government Center Drive NE",
    city: "Bolivia",
    zip: "28422",
    latitude: 34.0683,
    longitude: -78.1517,
    eligibility: "Brunswick County veterans",
    source_name: "Brunswick County Government",
    source_type: "government",
  },
  {
    title: "Robeson County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Lumberton and Robeson County veterans. VA claims and benefits assistance.",
    website_url: "https://www.co.robeson.nc.us",
    phone: "910-671-3112",
    address: "550 N Chestnut Street",
    city: "Lumberton",
    zip: "28358",
    latitude: 34.6182,
    longitude: -79.0086,
    eligibility: "Robeson County veterans",
    source_name: "Robeson County Government",
    source_type: "government",
  },
  {
    title: "Carteret County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Beaufort, Morehead City, and Carteret County veterans. VA claims and benefits guidance.",
    website_url: "https://www.carteretcountync.gov/337/Veterans-Services",
    phone: "252-728-8440",
    address: "210 Turner Street",
    city: "Beaufort",
    zip: "28516",
    latitude: 34.7188,
    longitude: -76.6638,
    eligibility: "Carteret County veterans",
    source_name: "Carteret County Government",
    source_type: "government",
  },
  {
    title: "Davidson County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Lexington, Thomasville, and Davidson County veterans. VA claims assistance.",
    website_url: "https://www.davidsoncountync.gov/241/Veterans-Services",
    phone: "336-242-2057",
    address: "913 Greensboro Street",
    city: "Lexington",
    zip: "27292",
    latitude: 35.8240,
    longitude: -80.2536,
    eligibility: "Davidson County veterans",
    source_name: "Davidson County Government",
    source_type: "government",
  },
  {
    title: "Randolph County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Asheboro and Randolph County veterans. VA claims and benefits navigation.",
    website_url: "https://www.randolphcountync.gov/Departments/Veterans-Services",
    phone: "336-318-6909",
    address: "1230 Zoo Parkway",
    city: "Asheboro",
    zip: "27205",
    latitude: 35.6810,
    longitude: -79.7832,
    eligibility: "Randolph County veterans",
    source_name: "Randolph County Government",
    source_type: "government",
  },
  {
    title: "Johnston County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Smithfield and Johnston County veterans. VA claims assistance.",
    website_url: "https://www.johnstonnc.com/veterans/",
    phone: "919-989-5396",
    address: "309 E Market Street",
    city: "Smithfield",
    zip: "27577",
    latitude: 35.5085,
    longitude: -78.3420,
    eligibility: "Johnston County veterans",
    source_name: "Johnston County Government",
    source_type: "government",
  },
  {
    title: "Moore County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Pinehurst, Southern Pines, and Moore County veterans. VA claims and benefits guidance.",
    website_url: "https://www.moorecountync.gov/veterans-services",
    phone: "910-947-3257",
    address: "1036 Carriage Oaks Drive",
    city: "Carthage",
    zip: "28327",
    latitude: 35.3460,
    longitude: -79.4170,
    eligibility: "Moore County veterans",
    source_name: "Moore County Government",
    source_type: "government",
  },
  {
    title: "Rowan County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Salisbury and Rowan County veterans. VA claims and benefits assistance.",
    website_url: "https://www.rowancountync.gov/156/Veterans-Services",
    phone: "704-216-8138",
    address: "1810 E Innes Street",
    city: "Salisbury",
    zip: "28144",
    latitude: 35.6678,
    longitude: -80.4540,
    eligibility: "Rowan County veterans",
    source_name: "Rowan County Government",
    source_type: "government",
  },
  {
    title: "Lincoln County Veterans Services",
    category_slug: "va-benefits",
    subcategory_name: "County Veterans Service Offices",
    short_description: "County VSO serving Lincolnton and Lincoln County veterans (Charlotte metro west). VA claims and benefits.",
    website_url: "https://www.lincolncounty.org/198/Veterans-Services",
    phone: "704-736-8635",
    address: "115 W Main Street",
    city: "Lincolnton",
    zip: "28092",
    latitude: 35.4754,
    longitude: -81.2543,
    eligibility: "Lincoln County veterans",
    source_name: "Lincoln County Government",
    source_type: "government",
  },
  {
    title: "American Legion Department of North Carolina",
    category_slug: "va-benefits",
    subcategory_name: "Veteran Service Officers (VSOs)",
    short_description: "Statewide American Legion department with accredited service officers providing free VA claims assistance, advocacy, and post network across NC.",
    website_url: "https://nclegion.org",
    phone: "919-832-7506",
    address: "4 N Blount Street",
    city: "Raleigh",
    zip: "27601",
    latitude: 35.7817,
    longitude: -78.6391,
    eligibility: "All veterans (membership not required for claims help)",
    source_name: "American Legion Department of North Carolina",
    source_type: "nonprofit",
  },
  {
    title: "VFW Department of North Carolina",
    category_slug: "va-benefits",
    subcategory_name: "Veteran Service Officers (VSOs)",
    short_description: "Statewide VFW department with accredited service officers providing free VA claims assistance, appeals advocacy, and post network across NC.",
    website_url: "https://www.vfwnc.org",
    phone: "919-790-0867",
    address: "8005 Old Stage Road",
    city: "Raleigh",
    zip: "27603",
    latitude: 35.6688,
    longitude: -78.6566,
    eligibility: "All veterans (membership not required for claims help)",
    source_name: "Veterans of Foreign Wars Department of NC",
    source_type: "nonprofit",
  },
  {
    title: "AMVETS Department of North Carolina",
    category_slug: "va-benefits",
    subcategory_name: "Veteran Service Officers (VSOs)",
    short_description: "Statewide AMVETS department offering accredited claims assistance, advocacy, and member services across NC.",
    website_url: "https://amvets.org/department/north-carolina/",
    phone: "919-779-5555",
    city: "Raleigh",
    eligibility: "All veterans",
    source_name: "AMVETS Department of NC",
    source_type: "nonprofit",
  },

  // ============================================================
  // DISABLED VETERANS — DAV state + chapters + VR&E + advocacy
  // ============================================================
  {
    title: "DAV Department of North Carolina",
    category_slug: "disabled-veterans",
    subcategory_name: "Disability Benefits & Claims",
    short_description: "Statewide Disabled American Veterans department coordinating chapter network, accredited claims service, and free transportation programs to VA appointments.",
    website_url: "https://davnc.org",
    phone: "919-779-5555",
    city: "Raleigh",
    state: "NC",
    eligibility: "Service-connected disabled veterans",
    source_name: "Disabled American Veterans Department of NC",
    source_type: "nonprofit",
  },
  {
    title: "DAV Chapter 1 — Charlotte",
    category_slug: "disabled-veterans",
    subcategory_name: "Disability Benefits & Claims",
    short_description: "DAV chapter serving Charlotte-area disabled veterans. Free claims assistance, member meetings, advocacy.",
    website_url: "https://davnc.org",
    phone: "704-391-8329",
    city: "Charlotte",
    zip: "28269",
    latitude: 35.3263,
    longitude: -80.8420,
    eligibility: "Service-connected disabled veterans",
    source_name: "Disabled American Veterans",
    source_type: "nonprofit",
  },
  {
    title: "DAV Chapter 5 — Raleigh",
    category_slug: "disabled-veterans",
    subcategory_name: "Disability Benefits & Claims",
    short_description: "DAV chapter serving Wake County disabled veterans. Claims assistance and advocacy.",
    website_url: "https://davnc.org",
    phone: "919-832-7506",
    city: "Raleigh",
    zip: "27601",
    latitude: 35.7796,
    longitude: -78.6382,
    eligibility: "Service-connected disabled veterans",
    source_name: "Disabled American Veterans",
    source_type: "nonprofit",
  },
  {
    title: "DAV Chapter 21 — Fayetteville",
    category_slug: "disabled-veterans",
    subcategory_name: "Disability Benefits & Claims",
    short_description: "DAV chapter serving Fort Liberty community and Cumberland County disabled veterans. Free claims assistance and advocacy.",
    website_url: "https://davnc.org",
    phone: "910-484-3268",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0527,
    longitude: -78.8784,
    eligibility: "Service-connected disabled veterans",
    source_name: "Disabled American Veterans",
    source_type: "nonprofit",
  },
  {
    title: "DAV Transportation Network — Salisbury VAMC",
    category_slug: "disabled-veterans",
    subcategory_name: "Adaptive Transportation & Mobility",
    short_description: "Free DAV-operated transportation to VA medical appointments at Salisbury VAMC for disabled veterans across central/western NC.",
    website_url: "https://www.va.gov/salisbury-health-care/work-with-us/volunteer-or-donate/",
    phone: "704-638-3475",
    address: "1601 Brenner Avenue",
    city: "Salisbury",
    zip: "28144",
    latitude: 35.6534,
    longitude: -80.4886,
    eligibility: "Veterans with VA appointments",
    source_name: "DAV / Salisbury VAMC",
    source_type: "service",
  },
  {
    title: "DAV Transportation Network — Durham VAMC",
    category_slug: "disabled-veterans",
    subcategory_name: "Adaptive Transportation & Mobility",
    short_description: "Free DAV-operated transportation to VA medical appointments at Durham VAMC for disabled veterans across central NC.",
    website_url: "https://www.va.gov/durham-health-care/work-with-us/volunteer-or-donate/",
    phone: "919-286-0411",
    city: "Durham",
    zip: "27705",
    latitude: 36.0033,
    longitude: -78.9352,
    eligibility: "Veterans with VA appointments",
    source_name: "DAV / Durham VAMC",
    source_type: "service",
  },
  {
    title: "Vocational Rehabilitation & Employment (VR&E) — Winston-Salem",
    category_slug: "disabled-veterans",
    subcategory_name: "Employment & Vocational Rehabilitation",
    short_description: "VA VR&E program (Chapter 31) for service-connected disabled veterans. Career counseling, training, education, employment support, and self-employment assistance for NC veterans.",
    website_url: "https://www.benefits.va.gov/vocrehab/",
    phone: "1-800-827-1000",
    address: "251 N Main Street",
    city: "Winston-Salem",
    zip: "27155",
    latitude: 36.1004,
    longitude: -80.2452,
    eligibility: "Service-connected disabled veterans (10%+)",
    source_name: "U.S. Department of Veterans Affairs",
    source_type: "program",
  },
  {
    title: "Wounded Warrior Project — North Carolina",
    category_slug: "disabled-veterans",
    subcategory_name: "Healthcare & Rehabilitation",
    short_description: "Free programs and services for wounded post-9/11 veterans and families: mental health, physical health, career, peer support, adaptive sports, family support.",
    website_url: "https://www.woundedwarriorproject.org",
    phone: "888-997-2586",
    city: "Charlotte",
    eligibility: "Wounded post-9/11 veterans and families",
    source_name: "Wounded Warrior Project",
    source_type: "nonprofit",
  },
  {
    title: "Paralyzed Veterans of America — Mid-Atlantic Chapter (NC)",
    category_slug: "disabled-veterans",
    subcategory_name: "Adaptive Equipment & Assistive Technology",
    short_description: "Serves NC paralyzed veterans with advocacy, benefits assistance, adaptive sports, accessibility, and research support. Mid-Atlantic Chapter covers NC.",
    website_url: "https://midatlanticpva.org",
    phone: "1-800-852-7639",
    eligibility: "Veterans with spinal cord injury or disease",
    source_name: "Paralyzed Veterans of America",
    source_type: "nonprofit",
  },
  {
    title: "Blinded Veterans Association — North Carolina",
    category_slug: "disabled-veterans",
    subcategory_name: "Adaptive Equipment & Assistive Technology",
    short_description: "Support and advocacy for blinded veterans across NC. Field service representatives provide benefits assistance and connect veterans to VA blind rehabilitation services.",
    website_url: "https://bva.org",
    phone: "1-800-669-7079",
    eligibility: "Veterans with vision loss",
    source_name: "Blinded Veterans Association",
    source_type: "nonprofit",
  },
  {
    title: "Independence Fund — NC HQ",
    category_slug: "disabled-veterans",
    subcategory_name: "Caregiver & Family Support",
    short_description: "NC-based nonprofit serving catastrophically wounded veterans. Provides mobility equipment, caregiver retreats, mental health programs, and advocacy. Headquartered in Charlotte.",
    website_url: "https://independencefund.org",
    phone: "888-851-7996",
    address: "9006 Stony Point Parkway",
    city: "Charlotte",
    zip: "28277",
    latitude: 35.0916,
    longitude: -80.8466,
    eligibility: "Catastrophically wounded post-9/11 veterans and caregivers",
    source_name: "Independence Fund",
    source_type: "nonprofit",
  },

  // ============================================================
  // HOUSING — Statewide programs + SSVF + HUD-VASH + nonprofits
  // ============================================================
  {
    title: "NC Housing Finance Agency",
    category_slug: "housing",
    subcategory_name: "Home Ownership Programs",
    short_description: "State agency offering down payment assistance, mortgage credit certificates, NC 1st Home Advantage, and Home Advantage Mortgage products. Veteran-friendly programs including waived first-time buyer requirement for veterans.",
    website_url: "https://www.nchfa.com",
    phone: "919-877-5700",
    address: "3508 Bush Street",
    city: "Raleigh",
    zip: "27609",
    latitude: 35.8454,
    longitude: -78.6366,
    eligibility: "NC homebuyers; veteran-specific options available",
    source_name: "NC Housing Finance Agency",
    source_type: "government",
  },
  {
    title: "SSVF — Supportive Services for Veteran Families (Volunteers of America Carolinas)",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "VA SSVF program providing rapid rehousing and homelessness prevention for veteran families across central and western NC. Case management, financial assistance, housing search.",
    website_url: "https://www.voacarolinas.org",
    phone: "704-647-0440",
    city: "Charlotte",
    state: "NC",
    eligibility: "Very low-income veteran families at risk of or experiencing homelessness",
    source_name: "Volunteers of America Carolinas / VA SSVF",
    source_type: "program",
  },
  {
    title: "SSVF — Easter Seals UCP NC (Eastern NC)",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "VA SSVF program for veteran families across eastern NC. Rapid rehousing, prevention, financial assistance, case management.",
    website_url: "https://www.eastersealsucp.com",
    phone: "919-783-8898",
    city: "Raleigh",
    state: "NC",
    eligibility: "Very low-income veteran families at risk of or experiencing homelessness",
    source_name: "Easter Seals UCP / VA SSVF",
    source_type: "program",
  },
  {
    title: "HUD-VASH — Fayetteville VAMC",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "Joint VA-HUD program providing housing vouchers + VA case management for chronically homeless veterans served by Fayetteville VAMC.",
    website_url: "https://www.va.gov/homeless/hud-vash.asp",
    phone: "910-488-2120",
    address: "2300 Ramsey Street",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0786,
    longitude: -78.9007,
    eligibility: "Chronically homeless veterans",
    source_name: "U.S. Department of Veterans Affairs / HUD",
    source_type: "program",
  },
  {
    title: "HUD-VASH — Durham VAMC",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "Joint VA-HUD program providing housing vouchers + VA case management for chronically homeless veterans served by Durham VAMC.",
    website_url: "https://www.va.gov/homeless/hud-vash.asp",
    phone: "919-286-0411",
    city: "Durham",
    zip: "27705",
    latitude: 36.0033,
    longitude: -78.9352,
    eligibility: "Chronically homeless veterans",
    source_name: "U.S. Department of Veterans Affairs / HUD",
    source_type: "program",
  },
  {
    title: "HUD-VASH — Salisbury VAMC",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "Joint VA-HUD housing vouchers + case management for chronically homeless veterans served by Salisbury VAMC across central/western NC.",
    website_url: "https://www.va.gov/homeless/hud-vash.asp",
    phone: "704-638-9000",
    city: "Salisbury",
    zip: "28144",
    latitude: 35.6534,
    longitude: -80.4886,
    eligibility: "Chronically homeless veterans",
    source_name: "U.S. Department of Veterans Affairs / HUD",
    source_type: "program",
  },
  {
    title: "HUD-VASH — Asheville VAMC (Charles George)",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "Joint VA-HUD housing vouchers + case management for chronically homeless veterans across western NC mountains.",
    website_url: "https://www.va.gov/homeless/hud-vash.asp",
    phone: "828-298-7911",
    city: "Asheville",
    zip: "28805",
    latitude: 35.5841,
    longitude: -82.4757,
    eligibility: "Chronically homeless veterans",
    source_name: "U.S. Department of Veterans Affairs / HUD",
    source_type: "program",
  },
  {
    title: "Operation Homefront — North Carolina",
    category_slug: "housing",
    subcategory_name: "Rental Assistance",
    short_description: "Critical financial assistance, transitional housing (Villages), and home repair programs for military families and veterans. Rent/mortgage relief, utilities, vehicle repair.",
    website_url: "https://www.operationhomefront.org",
    phone: "1-800-722-6098",
    eligibility: "Military families, post-9/11 wounded veterans",
    source_name: "Operation Homefront",
    source_type: "nonprofit",
  },
  {
    title: "NC Coalition to End Homelessness",
    category_slug: "housing",
    subcategory_name: "Homeless Veteran Services",
    short_description: "Statewide coalition coordinating homelessness response across NC. Connects veterans to local Continuum of Care, SSVF, HUD-VASH, and rapid rehousing resources.",
    website_url: "https://www.ncceh.org",
    phone: "919-755-4393",
    address: "5510 Six Forks Road, Suite 100",
    city: "Raleigh",
    zip: "27609",
    latitude: 35.8721,
    longitude: -78.6392,
    eligibility: "All experiencing homelessness",
    source_name: "NC Coalition to End Homelessness",
    source_type: "nonprofit",
  },
  {
    title: "Habitat for Humanity of NC — Veteran Build Programs",
    category_slug: "housing",
    subcategory_name: "Home Ownership Programs",
    short_description: "Habitat NC affiliates partner with veterans for affordable homeownership. Sweat equity + zero-interest mortgages. Repair Corps program for disabled veteran homeowners.",
    website_url: "https://www.habitatnc.org",
    phone: "919-832-2099",
    city: "Raleigh",
    state: "NC",
    eligibility: "Income-qualifying veterans",
    source_name: "Habitat for Humanity of NC",
    source_type: "nonprofit",
  },
  {
    title: "NC State Veterans Home — Fayetteville",
    category_slug: "housing",
    subcategory_name: "Transitional Housing",
    short_description: "150-bed long-term skilled nursing care facility for NC veterans operated by NCDMVA. Located near Fayetteville VAMC.",
    website_url: "https://www.milvets.nc.gov/services/state-veterans-homes/fayetteville",
    phone: "910-482-9000",
    address: "214 Cochran Avenue",
    city: "Fayetteville",
    zip: "28301",
    latitude: 35.0810,
    longitude: -78.9136,
    eligibility: "NC veterans needing skilled nursing care",
    source_name: "NC Department of Military and Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "NC State Veterans Home — Salisbury",
    category_slug: "housing",
    subcategory_name: "Transitional Housing",
    short_description: "Long-term skilled nursing care facility for NC veterans operated by NCDMVA, adjacent to Salisbury VAMC.",
    website_url: "https://www.milvets.nc.gov/services/state-veterans-homes/salisbury",
    phone: "704-638-4200",
    address: "1601 Brenner Avenue",
    city: "Salisbury",
    zip: "28144",
    latitude: 35.6534,
    longitude: -80.4886,
    eligibility: "NC veterans needing skilled nursing care",
    source_name: "NC Department of Military and Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "NC State Veterans Home — Black Mountain",
    category_slug: "housing",
    subcategory_name: "Transitional Housing",
    short_description: "Long-term skilled nursing care facility for NC veterans operated by NCDMVA in western NC mountains.",
    website_url: "https://www.milvets.nc.gov/services/state-veterans-homes/black-mountain",
    phone: "828-257-6800",
    address: "62 Lake Eden Road",
    city: "Black Mountain",
    zip: "28711",
    latitude: 35.6118,
    longitude: -82.3168,
    eligibility: "NC veterans needing skilled nursing care",
    source_name: "NC Department of Military and Veterans Affairs",
    source_type: "facility",
  },
  {
    title: "NC State Veterans Home — Kinston",
    category_slug: "housing",
    subcategory_name: "Transitional Housing",
    short_description: "Long-term skilled nursing care facility for NC veterans operated by NCDMVA in eastern NC.",
    website_url: "https://www.milvets.nc.gov/services/state-veterans-homes/kinston",
    phone: "252-939-8000",
    address: "2150 Hull Road",
    city: "Kinston",
    zip: "28504",
    latitude: 35.2627,
    longitude: -77.5816,
    eligibility: "NC veterans needing skilled nursing care",
    source_name: "NC Department of Military and Veterans Affairs",
    source_type: "facility",
  },
];

async function loadMaps() {
  const { data: cats, error: catErr } = await supabaseAdmin.from("categories").select("id, slug");
  if (catErr || !cats) throw new Error(`Failed to load categories: ${catErr?.message}`);
  const catMap = new Map<string, string>();
  cats.forEach((c: any) => catMap.set(c.slug, c.id));

  const { data: subs, error: subErr } = await supabaseAdmin.from("subcategories").select("id, name, category_id");
  if (subErr || !subs) throw new Error(`Failed to load subcategories: ${subErr?.message}`);
  const catIdToSlug = new Map<string, string>();
  cats.forEach((c: any) => catIdToSlug.set(c.id, c.slug));
  const subMap = new Map<string, string>();
  subs.forEach((s: any) => {
    const catSlug = catIdToSlug.get(s.category_id);
    if (catSlug) subMap.set(`${catSlug}|${s.name.toLowerCase()}`, s.id);
  });

  return { catMap, subMap };
}

async function main() {
  console.log(`\n=== NC Resources Seed — ${NC_RESOURCES.length} rows ===\n`);

  const { catMap, subMap } = await loadMaps();
  console.log(`[setup] Loaded ${catMap.size} categories, ${subMap.size} subcategory mappings`);

  // Dedupe: load existing NC titles
  const { data: existing } = await supabaseAdmin
    .from("resources")
    .select("title")
    .eq("state", STATE);
  const existingTitles = new Set((existing || []).map((r: any) => (r.title || "").toLowerCase().trim()));
  console.log(`[setup] Found ${existingTitles.size} existing NC rows to dedupe against\n`);

  const counts = {
    created: 0,
    duplicates: 0,
    errors: 0,
    subcategoryMisses: 0 as number,
    byCategory: {} as Record<string, number>,
    bySubcategory: {} as Record<string, number>,
    errorRows: [] as { title: string; reason: string }[],
    subMissList: [] as { title: string; key: string }[],
  };

  for (const r of NC_RESOURCES) {
    const titleKey = r.title.toLowerCase().trim();
    if (existingTitles.has(titleKey)) {
      counts.duplicates++;
      continue;
    }

    const category_id = catMap.get(r.category_slug);
    if (!category_id) {
      counts.errors++;
      counts.errorRows.push({ title: r.title, reason: `Unknown category slug: ${r.category_slug}` });
      continue;
    }

    let subcategory_id: string | null = null;
    if (r.subcategory_name) {
      subcategory_id = subMap.get(`${r.category_slug}|${r.subcategory_name.toLowerCase()}`) || null;
      if (!subcategory_id) {
        counts.subcategoryMisses++;
        counts.subMissList.push({ title: r.title, key: `${r.category_slug}|${r.subcategory_name}` });
      }
    }

    const insertRow: Record<string, any> = {
      title: r.title,
      category_id,
      short_description: r.short_description,
      website_url: r.website_url || null,
      phone: r.phone || null,
      email: r.email || null,
      address: r.address || null,
      city: r.city || null,
      state: STATE,
      zip: r.zip || null,
      latitude: r.latitude ?? null,
      longitude: r.longitude ?? null,
      geo_source: r.latitude ? "manual_curation" : null,
      geocoded_at: r.latitude ? new Date().toISOString() : null,
      eligibility: r.eligibility || "All veterans",
      subcategory: r.subcategory_name || null,
      source_name: r.source_name,
      source_type: r.source_type,
      status: r.status || "approved",
      sponsored: false,
    };

    const { data: ins, error } = await supabaseAdmin
      .from("resources")
      .insert(insertRow)
      .select("id")
      .single();

    if (error || !ins) {
      counts.errors++;
      counts.errorRows.push({ title: r.title, reason: error?.message || "Unknown insert error" });
      continue;
    }

    // Category junction
    await supabaseAdmin
      .from("resource_categories")
      .upsert({ resource_id: ins.id, category_id }, { onConflict: "resource_id,category_id" });

    // Subcategory junction (only if matched)
    if (subcategory_id) {
      await supabaseAdmin
        .from("resource_subcategories")
        .upsert(
          { resource_id: ins.id, subcategory_id },
          { onConflict: "resource_id,subcategory_id" }
        );
    }

    counts.created++;
    counts.byCategory[r.category_slug] = (counts.byCategory[r.category_slug] || 0) + 1;
    if (r.subcategory_name) {
      counts.bySubcategory[r.subcategory_name] = (counts.bySubcategory[r.subcategory_name] || 0) + 1;
    }
    existingTitles.add(titleKey); // protect against in-batch dupes
  }

  console.log(`\n=== RESULTS ===`);
  console.log(`Total rows in script : ${NC_RESOURCES.length}`);
  console.log(`Created              : ${counts.created}`);
  console.log(`Duplicates skipped   : ${counts.duplicates}`);
  console.log(`Errors               : ${counts.errors}`);
  console.log(`Subcategory misses   : ${counts.subcategoryMisses} (rows still inserted, just without sub junction)`);

  console.log(`\n--- By category ---`);
  Object.entries(counts.byCategory)
    .sort((a, b) => b[1] - a[1])
    .forEach(([k, v]) => console.log(`  ${k.padEnd(28)} ${v}`));

  console.log(`\n--- By subcategory (top 20) ---`);
  Object.entries(counts.bySubcategory)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .forEach(([k, v]) => console.log(`  ${k.padEnd(45)} ${v}`));

  if (counts.subMissList.length) {
    console.log(`\n--- Subcategory misses (would benefit from adding to subcategories table) ---`);
    counts.subMissList.forEach(s => console.log(`  ${s.title} -> ${s.key}`));
  }

  if (counts.errorRows.length) {
    console.log(`\n--- Errors ---`);
    counts.errorRows.forEach(e => console.log(`  ${e.title}: ${e.reason}`));
  }
}

main().catch((e) => {
  console.error("FATAL:", e);
  process.exit(1);
});
